### PR TITLE
Sound card mixer button

### PR DESCRIPTION
**Pull request by daschuer**
This adds a  button to the hardware preferences to open the OS specific hardware mixer window. 
Currently supported: ALSA / DirectSound (untested) 
The "control mmsys.cpl sounds" call works from  WinXP to Win10 

Fixes: 
https://bugs.launchpad.net/mixxx/+bug/1440675

### CODE REVIEW

**Comment by Be-ing** [comment]
"Hardware mixer" could be confused with an analog DJ mixer. Perhaps "sound card mixer" would be a less ambiguous label.

**Comment by daschuer** [comment]
Hi @Be-ing, 

Thank you for looking at this. I have just renamed the button. 

Do you support the idea for having this button, in master branch as well? 

I had a discussion at Lauchpad with @ywwg.  See: https://bugs.launchpad.net/mixxx/+bug/1440675
What is you opinion?

**Comment by daschuer** [comment]
Because of a recent issue in http://www.mixxx.org/forums/viewtopic.php?f=1&t=8847
I like to warm this PR up. 

Do we have still strong objections to merge this? 
@Be-ing: How do you think about this

**Comment by rryan** [comment]
I still agree with @ywwg -- this is a rats nest I really don't want us to open up. The code in this PR proves it's far more complicated than "just start alsamixer". I think we're only asking for maintenance woes down the road. I'd much prefer that we link the user to good documentation on how to configure their system.

**Comment by rryan** [comment]
(Also, integrate with PulseAudio-- once @illuusio's pulse backend is merged into portaudio we can do this by default)

**Comment by illuusio** [comment]
Yes once it get in. If you are wanting it there is thread where you can help me in this uphill battle.

**Comment by rryan** [comment]
> The code in this PR proves it's far more complicated than "just start alsamixer"

Sorry, I was being cranky because I was tired. I should have gone to bed instead of commenting. The code is fine, but I don't like that we have to guess at the right terminal to use -- it'll probably work, it just causes me to cringe.

My concrete objections are
*  I think it's not going to work reliably on all distros (what if alsamixer is not installed by default such as on Gentoo, Arch or some other less user-friendly distro?) 
* alsamixer has really terrible UX
* This is targeting a user who is
  * lost enough they don't know to open alsamixer
  * but would know how to use alsamixer were it popped open for them. 

Does this user exist? 

My typical experience with alsamixer is:
* that alsa thinks my internal soundcard has dozens of channels that don't exist or I had no clue about (like 5.1 outputs, digital in/outputs, etc. when there are definitely no ports like that on the motherboard)
* I can't find which channel actually controls the volume on my system or the particular device I'm trying to configure. 
* I always stumble a bit switching from controlling outputs to inputs (for the case of the users having trouble with mic input / VC gain) 

If this user does exist, will they be able to figure this out without any guidance (Lord help them if they need to make their own .asoundrc)? That's why I think linking to the manual makes much more sense. It gives us much more room to help the user than popping open this cryptic interface built for 90s-era computers.

**Comment by daschuer** [comment]
I agree that the situation on Linux is far from ideal. But such a button does not make it worse IMHO. 

A typical situation on Linux is like that: 
* Plug-In a USB soundcard lets say Maya44 
* Start Mixxx 
* we recommend to use ALSA, which is still true even if we have a  Pulse back-end, because this allows the lowest latencies.
* Configure the Maya44 in the hardware preferences

The Maya44 has the "feature" that it stores the volume slider position in its non volatile memory. 

-> Possible Results: 
a.) everything works at once with 100% Volume. 
b.) The Maya 44 plays at the volume from the last usage, which is most likely too low. 

The only solution I know for b.) is using alsamixer. The pulse mixer will not work, because it is only effecting the internal soundcard. Pulse is suspended anyway when starting Mixxx. 
Even if we have the pulse support in Mixxx, it is very unlikely that a app like "pavucontrol" is installed which might allow to tweak the hardware sliders of a second soundcard.  

What will the user do in case b.) 
1.) find the Mixxx manual, read it. 
2.)  There is no explicit reference to alsamixer only some weak words like "use your OS mixer", (this should be fixed, but users tend to not read the manual. 
3.) Now the user has to find out that if he uses alsa, the os mixer is alsamixer. 
4.)  he will not find it in in its application menu. 
5.)  he has to find a suitable terminal emulation and type "alsamixer"
6.)  now he has to fight with the 80th gui until the levels are set as desired. 

That's looks like a non joyful experience.  

A full featured solution in Mixxx would be, adding a view that allows to control the hardware mixers using portmixer or so. This will most likely end up in a aslamixer rewrite. Something like that: 
https://media-cdn.ubuntu-de.org/wiki/attachments/38/09/xfce4-mixer.png. 
This view will be started by a button in the hardware preferences. 

This PR is just a preview to that, it features the button, but instead of a shiny GUI it present the alsamixer, that the user has to use anyway. 

Please look at the button as if it contains only the knowledge to open alsamixer. It covers point 1 ... 5 from above.

Later we can consider to install a modern alsmixer replacement along with Mixxx, or build our own. 
Or we may add a detection for alsamixer replacements ... 

What do you think?

**Comment by Be-ing** [comment]
For most sound cards, there is no need to use alsamixer; the relevant controls are accessible on the hardware. Is adding a button that is not needed more likely to lead users to mess up settings that do not need adjustment?

**Comment by daschuer** [comment]
All my soundcards require using alsamixer.  I have a Maya44 and a RMX2 controller. Without alsamixer, I can only reduce the volume by the master gain (not recomended), or the amplifier volume (not reachable in any setup) 
But since alsamixer is really a bit scary, but required, we need a statregie to avoid unneccessary confusions. Do you have an idea?  

How about a pop that explains the issue?

**Comment by Be-ing** [comment]
This pull request has not been updated in years and usability concerns have been raised by multiple developers so I am closing it to reduce the clutter of open PRs.

**Comment by daschuer** [comment]
This is an open discussion without a solution, so I like to keep it open. 

I still think we should merge it. What are the alternatives?

**Comment by Be-ing** [comment]
I think it would be a better approach to improve the manual where we can discuss different how this is handled differently on each OS and with different kinds of hardware.

**Comment by Holzhaus** [comment]
I agree that we should improve the manual instead of adding that button. @daschuer do you still think it's worth keeping it open or shall we closet this?

**Comment by daschuer** [comment]
Ok, than let's close this.

**Pull request closed without merging**
