### PR TITLE
Merge 2.4

### PR DESCRIPTION
**Pull request by ronso0**
Just to abuse CI because I still can't built test locally atm.
Will push directly once CI is happy.

### CODE REVIEW

**Comment by ronso0** [comment]
Okay, so
* pre-commit complains about the midi-for-light mapping https://github.com/mixxxdj/mixxx/actions/runs/6575317520/job/17862186232?pr=12192#step:6:104
* Windows build /env is broken because of failing manual d/l

Tests pass with the other OS so I assume it's okay to push?

**Comment by Swiftb0y** [comment]
I guess you could push temporary commit to this branch that doesn't download the manual on windows to see if it otherwise succeeds.

**Comment by ronso0** [comment]
> I guess you could push temporary commit to this branch that doesn't download the manual on windows to see if it otherwise succeeds.

Done.

Actually it's only commits from #11527 which passed CI just fine, and 
Now clazy complains about https://github.com/mixxxdj/mixxx/pull/11527/commits/8e571ee12eefbb519eb20b7d32ac7275e9b18832
see https://github.com/mixxxdj/mixxx/actions/runs/6575317522/job/17862186214?pr=12192#step:9:696

Heeelp!

**Comment by Swiftb0y** [comment]
Yeah, those issues come from the API changes in Qt6. I'm little short on time so I'd prefer if you can take care of the fix but if you struggle with it, tell me and I'll try to find some time to sort it out for you. The fix is basically to just apply the `QList::insert()` and `QList::erase()` specific changes of #11701 to https://github.com/mixxxdj/mixxx/pull/11527

**Comment by ronso0** [comment]
Great, thanks for the hint!
I'll check whether I can figure that out.

**Comment by ronso0** [comment]
So that worked. I removed the test commit and pushed directly.

**Pull request closed without merging**
