### PR TITLE
"Fix issue in TagFetcher to handle cover art link errors"

### PR DESCRIPTION
**Pull request by urek69mazino**
### Overview
This PR enhances error handling in the `TagFetcher` class by properly emitting the `coverArtLinkNotFound` signal when a network error occurs during cover art fetching.

 Key Changes
- Added error handling to prevent stray calls from triggering redundant signals.
- Ensures that `coverArtLinkNotFound` is emitted only once when needed.

 Testing
- Verified that the signal is emitted correctly in response to network errors.
- Checked that no redundant signals are triggered during repeated fetch attempts.
Notes for Reviewers
- Please confirm that the error handling logic aligns with similar cases across the codebase.

### CODE REVIEW

**Comment by ronso0** [comment]
which commit exactly is supposed to fix the mentioned issue?

**Comment by urek69mazino** [comment]
i only did 1 commit , but whenever i do a pull request other unwanted commits get added too, can you suggest me what exactly am i doing wrong

**Comment by urek69mazino** [comment]
image
i made the following change and then committed it ,but when i do a pull request ,  other commits that i have not made gets added too , 
image

**Comment by ronso0** [comment]
Okay, I just don't find a commit from you in the list.
If you still have the commit hash, I suggest you start over and base a new branch on the (mixxx) target branch (it's a fix so 2.5 is okay):
* backup your branch
   * git checkout my-tagfetcher-fix
   * git branch -m my-tagfetcher-fix_backup
* create a new branch
git checkout -b my-tagfetcher-fix upstream/2.5
* pick the fix commit
git cherry-pick [commit-hash]
* force-push to you fork
git push -f my-tagfetcher-fix

I'll now change the target branch here to 2.5
Let's see if it works out this time.

**Comment by ronso0** [comment]
> I'll now change the target branch here to 2.5

I can't, apparently there are no new commits, ie. no commits = no PR possible
Please follow the steps I listed above, then I'll try again.

**Comment by daschuer** [comment]
Because this PR does not contains new commits, GitHub has marked it automatically as merged after merging 2.4 and 2.5 to main. @urek69mazino Please open a new PR once you have a working fix.

**Pull request merged**
