### PR TITLE
Update to latest vcpkg environment

### PR DESCRIPTION
**Pull request by daschuer**
This includes the switch to the macOS 11 workflow runner. 
https://github.com/mixxxdj/vcpkg/pull/52

### CODE REVIEW

**Comment by Holzhaus** [comment]
Who can test this?

**Comment by daschuer** [comment]
It has already be confirmed that it is working here:
https://github.com/mixxxdj/vcpkg/pull/52#issuecomment-1277519092
So I think it is safe to merge.

**Comment by Holzhaus** [comment]
Ok

**Comment by daschuer** [comment]
Thank you

**Pull request merged**
