### PR TITLE
Some more override and default

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by uklotzde** [comment]
Dependency issues

**Comment by uklotzde** [comment]
Still not fixed

**Comment by daschuer** [comment]
Travis fails now unrelated with: 
```
qt.qpa.screen: QXcbConnection: Could not connect to display :99.0
Could not connect to any X display.
```

Only CMake builds are affected. 
https://bugs.launchpad.net/mixxx/+bug/1881933

Any idea?

**Comment by uklotzde** [comment]
CI failure is unrelated. LGTM.Thank you!

**Pull request merged**
