### PR TITLE
Upgrade Travis CI Ubuntu images from Xenial to Bionic

### PR DESCRIPTION
**Pull request by uklotzde**

### CODE REVIEW

**Comment by daschuer** [comment]
That is OK for me. If no one has objections let's merge it.
Hovere do not start a PR that removes Xenial workarounds. 
I like to keep my Xenial dev machine until we drop 2.2 support.

**Comment by uklotzde** [comment]
@daschuer I disagree. The 2.2 branch builds fine on Xenial, no need to hinder anybody else from making progress.

Sorry to say, but I'm no longer willing to accept work and obstacles caused by the need to support outdated platforms until the very end.

**Comment by daschuer** [comment]
I was probably not clear enough. I support dropping Xenial for 2.3. 
I just want to save use from extra work, doing a PR to intentionally break Xenial support and introducing extra work when supporting 2.2. We Jan postpone this to the date we have released the final 2.2.x 

I think you have the mudicbrainz crasher in mind. I will adopt the work. If it is a Xenial QT bug we can ignore it. We just need to prove it, to be sure.

**Comment by uklotzde** [comment]
We have a separate 2.2 branch for exactly this purpose, so why not make progress in master?

**Comment by daschuer** [comment]
There is no pressing need to introduce a PR that brakes master for Xenial, right?
If so It would help me not do it now. This way I can stick on Xenial until we drop Xenial from all supported branches.

**Comment by uklotzde** [comment]
Xenial will never be dropped from 2.2.

**Comment by daschuer** [comment]
Yes, we drop the whole 2.2 support one day.

**Comment by uklotzde** [comment]
The GCC in Xenial has very limited C++17 support, especially when working with std::optional. I constantly bump into walls and refuse to continue before we are able to resolve those issues.

**Comment by daschuer** [comment]
Feel free to commit PRs that using this. I can later add a follow-Up PR with a workaround for Xenial. 
... until we drop 2.2 support. 
After we merge this, at least the CI does not fail instantly.

**Comment by daschuer** [comment]
So should we merge this now?

**Comment by uklotzde** [comment]
Please be aware that after upgrading all new contributions from my side will not longer be backwards compatible with Xenial. I'm deliberately using `constexpr` which is not supported by the old GCC.

On the other hand I'm no longer willing to waste my time with trial and error programming, pushing changes to CI, waiting for feedback, trying workarounds. This is getting ridiculous.

**Comment by daschuer** [comment]
If you can resist not to include Xenial breakers intentionally, it would be OK for me.

**Comment by daschuer** [comment]
I think the focus should be to remove a good amount of work from you supporting various distros, not using fancy new features everywhere.

**Comment by Holzhaus** [comment]
@uklotzde Can you reopen this for #2601?

**Pull request closed without merging**
