### PR TITLE
Update to latest vcpkg build

### PR DESCRIPTION
**Pull request by daschuer**
This updates the build environment foe windows and MacOs to the latest vcpkg build. 
This update brings many library updates.

### CODE REVIEW

**Comment by daschuer** [comment]
This is failing due to a qtkeychain issue fixed here: https://github.com/microsoft/vcpkg/pull/24013

**Comment by daschuer** [comment]
The upstream fix is merged, waiting until https://github.com/mixxxdj/vcpkg/pull/42 is merged.

**Comment by daschuer** [comment]
Now waiting for https://github.com/microsoft/vcpkg/pull/25018

**Comment by daschuer** [comment]
Hey this is finally working now. Who is able to do y smoke test on windows or mac? 
The artifacts can be found here: 
https://github.com/mixxxdj/mixxx/actions/runs/2463814609

**Comment by JoergAtGithub** [comment]
The Windows build from the artifacts doesn't start up:
grafik

**Comment by JoergAtGithub** [comment]
The version from the artifacts works now!

**Comment by fwcd** [comment]
I can confirm that the macOS build seems to work fine, at least from my limited testing under Rosetta.

**Comment by daschuer** [comment]
Great, thank you for your testing. @Swiftb0y: merge?

**Comment by fwcd** [comment]
Hm, something's strange with the macOS version, I cannot drag multiple tracks... I'll check whether the current `main` build has the same problem...

**Comment by Swiftb0y** [comment]
We'd appreciate if you report the track dragging issue on our bugtracker. Thank you.

**Review by Swiftb0y — APPROVED** [review]
LGTM.

**Pull request merged**
