### PR TITLE
[WIP] remove Qt4 high DPI hacks

### PR DESCRIPTION
**Pull request by Be-ing**
I intend for this to be merged when finished, but I am opening it now to illustrate the cost of merging #1741.

### CODE REVIEW

**Comment by ronso0** [comment]
Stupid question:
As I read the recent discussions -we switch to qt5 in 2.2 anyway, and there'll only be (maybe two) 2.1.X releases with qt4- is it worth the effort?

**Comment by Be-ing** [comment]
I'm not sure what you're asking. This PR is targeted at master, so it won't affect 2.1 or 2.2. This PR is to avoid hanging onto unnecessary legacy code for years into the future.

**Comment by ronso0** [comment]
Sorry, sleepy late-night post. I see you remove qt4 support for releases that don't use qt4 at all.

**Comment by uklotzde** [comment]
All those legacy customizations are error prone and have a high risk of breaking with any Qt version difference or across platforms. We should strive to get rid of legacy code and reduce the size of our code base before it becomes unmanageable. This PR nicely demonstrates the amount of custom code that has spread like cancer.

For all future development (including refactorings) we should closely follow the blueprints and examples provided by Qt. As a side effect (new) developers will be able to figure out the major design decisions and internal workings of Mixxx mostly by reading the official Qt docs. If we decide to use Qt we should do it the _Qt-way_ with only very few, restricted, well-justified, and documented(!) exceptions.

Everything in the UI layer should be based on Qt types and use straight forward Qt code without any hacks. We should even avoid to use _std_ types here. Engine and 3rd party library integrations are justified exceptions, where none-Qt types might be used as an implementation detail, but not in public interfaces that are exposed to the UI layer!

We must accept the limitations that come with the minimum Qt version we have agreed on. Otherwise we need to update our system requirements, thereby dropping support for outdated Linux distributions.

**Comment by daschuer** [comment]
To clarify: This is not a QT4 only hack. It is required for HiDPI screens on distros with Qt < 5.6

**Comment by Be-ing** [comment]
> We must accept the limitations that come with the minimum Qt version we have agreed on.

The problem is we have not agreed on any minimum Qt version. We need to agree on a consistent policy for determining that or these discussion will continue to waste development effort perpetually.

**Comment by uklotzde** [comment]
Can we still remove some workarounds that became obsolete for Qt 5.4, which is our minimum version?

We have too many open PRs in an unclear state.

**Comment by Be-ing** [comment]
If you want to do that, go ahead. I'm not especially inclined to work on this soon. Considering how many merge conflicts have developed, it would likely be easier to start over anyway.

**Pull request closed without merging**
