### PR TITLE
Update to latest vcpkg environment

### PR DESCRIPTION
**Pull request by daschuer**
This updates a bunch of libraries for Windows and macOS:
* harfbuzz 5.0.1 (from 04.02.0)
* libjpeg-turbo 2.1.4 (from 2.1.3)
* libusb  2.0.4 (from 1.0.24)
* libwebp 1.2.4 (from 01.02.02)
* openssl 3.0.7 (form 3.0.3)
* protobuf 3.21.8 (from 3.19.4)
* Windows only: qt5 5.15.7 (from 5.15.6) 
* rubberband 3.1.1 (from 3.0.0)
* sqlite3 3.39.2 (from 3.37.2)
* wavpack 5.5.0 (from 5.4.0)
* zlib 1.2.13 (from 1.2.12)

Before merge we need some manual smoke testes.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
I tested both the latest Main and this PR on my old Laptop with Windows7 and VS2019 and my new laptop with Windows11 and VS2022. I built x64_portable on both.

**Win7 + VS2019**
Builds succeeded
Tests 100% Pass
Short test of Mixxx with controller and ASIO looked good 

**Win10 + VS2022**
Builds succeeded
With both buildenvs (old and new) 4 SoundSourceProxyTests fail - see #11094 
Short test of Mixxx with controller and ASIO looked good
-Waveforms feel a bit smoother with the new buildenv - less drop-outs at 60fps

**Comment by JoergAtGithub** [comment]
Smoke Test results on MacOS: https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/qt.205.2E15.2Ex.20on.20MacOs/near/313733729

**Comment by daschuer** [comment]
Conclusion form the MacOS test by @m0dB: No regressions
> for me it runs on par as the current buildenv.

Can one merge this?

**Review by Swiftb0y — APPROVED** [review]
trusting @m0dB here

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
