### PR TITLE
Better support for hotcue colors on controllers

### PR DESCRIPTION
**Pull request by ferranlala**
**Remove Teal color**: It was a darkish color that I felt It didn't work very well on a controller.
**Replace Gray with white**: Same as above. White makes more sense.
~**Change default color representations**: I've changed the default rgba of the predefined colors to their pure primary or secondary shade. It's the most opinionated shade of the color and so the one that should be the default. I think it's also the most useful for a controller script in case it needs to be manipulated.
If this new defaults are not suitable for display on a screen we should address this by setting custom skin colors.~

**TODO**
- [x] Tune colors
- [ ] Add palette svg template

### CODE REVIEW

**Comment by ferranpujolcamins** [comment]
@daschuer @Swiftb0y

**Comment by Swiftb0y** [comment]
I feel a bit limited by only having 8 colors. Can we add all the pure tertiary colors + white? Similar to the outer ring of [this](https://commons.wikimedia.org/wiki/File:Farbkreis_Itten_RGB.svg)

**Comment by daschuer** [comment]
I think, now we have an issue if we consider to get matching colours on two different devices and on the GUI. I expect the RGB LEDs used in controllers quite bad. So if we pass the pure colore 1 by 1, the result defers without the chance for the other device to pick a matching colour, just because it is outside of its own RGB triangle.

**Comment by daschuer** [comment]
So I think it is time to define the absolute values of our colours in a xyL model.
The reference colour school be bit to much saturated in a way that even a weak a Weak RGB led is able to reproduce it.

This can be done by defining a standard PC monitor as reference. I expect that an that monitor is able to reproduce s colour way better than a RGB button in the controller.

The change here to the fully saturated colours create the situation that we define a colour that is only repridycable on some devices, because it is on the outline of the colour triangle.

**Comment by daschuer** [comment]
https://www.eizo.be/knowledge/monitor-expertise/understanding-color-gamut/

So let's say we go for sRGB, we must not pick a colour on the sRGB triangle birders, because it is most likely not repridycable on cheap RGB LEDs.

**Comment by daschuer** [comment]
If you for instance pass 255,255,255 to the controller button, you will getba white value value that might be yellowish or bluish, dependent on the hardware.
If we want to have the same white on all devices, we need to pick a sRGB value of let's say 240 240 240. This hopeful offers enough headrym to adust a bueish white to the blue white we desire

**Comment by Swiftb0y** [comment]
But the color gamut of a controllers RGB LEDs can differ vastly. I think there will always be differences. Many controllers also don't support every color (even though they have RGB Leds, you can only let the controller display colors from a built-in palette who's color would get picked via the midi velocity). Serato gets around this by making sure compatible/certified controllers support the available colors guarantied. We would either have to adapt Serato's colors to support most controllers or let the mapper specify a conversion table (I'm in favor of the latter).

Something I noticed while working on #2030: You can only send 7-bit values via SysEx messages. So it would make sense to rshift the color components by one while creating the js color object.

**Comment by Be-ing** [comment]
> But the color gamut of a controllers RGB LEDs can differ vastly. I think there will always be differences.

Yes, I think trying to get LEDs on different controllers to look exactly the same is futile.

**Comment by Swiftb0y** [comment]
IMO, its sufficient if the mapper just makes sure the hue of the color on his screen matches the hue of the color on his controller. And if the color is a bit dimmer, so be it. Pretty much nobody has a calibrated display anyways, so they will never really match exactly and I don't think you could exactly spot the difference by eye either (provided the mapper was rigorous enough while creating the conversion table).

**Comment by daschuer** [comment]
> Yes, I think trying to get LEDs on different controllers to look exactly the same is futile.

I agree in general, but I also think we must not make it impossible if one likes to do it. 
I think almost all screens are much better "calibrated" than any RGB led. So we might consider to add a color calibration mode that shows the desired in a resizable window. 
The most subtitle difference will be a gamma 2.2 vs a linear PWM value of the LEDs. 

I had just a look to the 
* ASMB-TTF0-0A20B3735 Tricolor PLCC-6 LED
It is a cheap ~0.1 € LED 
https://www.mouser.de/datasheet/2/678/SMB-TTF0-0A20B-DS101_2017-10-23-1314452.pdf
The green LED for instance has sRGB of -143, 326, 94, far outside of the sRGB range.

**Comment by daschuer** [comment]
So is sRGB actually a minimum compatible color sub set? Dos anyone know some insights?

**Comment by ferranpujolcamins** [comment]
We don’t need acurate colors. Colors are just a way to categorize hotcues.
As long as the user understands that a hotcue is red, it doesn’t matter if
the red we display on screen is not the same red that their controller can
render. It’s the responsibility of the controller mapping to drive its leds
to achieve a color that the user can identify as red, even though it’s a
different red than the one we display on screen.

Controllers have cheap and uncalibrated rgb leds. Our color set needs to be
small enough so users can identify each color without  mixing them up. I’m
afraid adding the ternary colors is not helping in this aspect. Maybe we
can add some extra color, like we did with pink, but let’s be extra careful.

**Comment by daschuer** [comment]
I have diggd through some LED datasheets and it turns out that almost all LEDs cover the full sRGB triangle. This means we can choose any sRGB colour and we can expect that the controller is able to display it. 

However, we have to give some hints how to reproduce the color the best on the controller. Just pass the RGB fractional as midi message to the controller work for the first instance, but it most likely will not reproduce the desired color shown on the monitor.

This means each mapping need to pick own RGB midi values for each colors. We should put a reference picture to the mapping guide that can be used to show it on the monitor and adjust the controller colors to it. If we make this process easy, hopefully we achieve a good result even if we combine two devices in a single setup. Even if it is a poor monitor it should close enough to the sRGB colour space, the reference for photos on the web. 

What do you think?

**Comment by daschuer** [comment]
Is it OK, that the controller color buttons have different lightness, violet button is darker than a yellow one.

**Comment by ferranpujolcamins** [comment]
I find this article to be very useful: https://programmingdesignsystems.com/color/color-models-and-color-spaces/index.html

What we send to the controllers is the RGB values without specifying any color space. I think it's safe to just assume that the color space to use is sRGB because:
- Both controller leds and computer screens work well with the sRGB space 
- sRGB is the default space in other software when no space is specified

So I think we only need to:
- Document that the RGB values are in sRGB color space
- Document best practices on how to treat color on controllers, covering different situations such as a controller with a limited amount of predefined colors (like the MidiFighter).
- Make sure that sRGB is used when rendering the RGB values on the screen.

Since we won't offer alternative color space now, we don't need to code anything to explicitly say that we are using sRGB.

Does it work for you?

Thanks for the discussion guys, it's been instructive :)

**Comment by ferranpujolcamins** [comment]
Second part is also very interesting:https://programmingdesignsystems.com/color/perceptually-uniform-color-spaces/index.html#perceptually-uniform-color-spaces-e7zMSWy

**Comment by Swiftb0y** [comment]
> Document best practices on how to treat color on controllers, covering different situations such as a controller with a limited amount of predefined colors (like the MidiFighter).

Would my current proposal in #2030 work for that?

**Comment by ferranpujolcamins** [comment]
> > Document best practices on how to treat color on controllers, covering different situations such as a controller with a limited amount of predefined colors (like the MidiFighter).
> 
> Would my current proposal in #2030 work for that?

Yes!

**Comment by daschuer** [comment]
> What we send to the controllers is the RGB values without specifying any color space. I think it's safe to just assume that the color space to use is sRGB because ...

If this is really the case, it would be nice. However I wouldn't be surprised if we find devices where the 127 midi rang is linear mapped to a PWM ratio. 

I just had a look to DMX color flood lights, the high price range has a calibrated mode and a full saturated mode.

**Comment by dszakallas** [comment]
Will this make the sampler pads customizable too?

**Comment by daschuer** [comment]
grafik

**Comment by daschuer** [comment]
This is the compassion of the proposed colors first row, the Serato colors, and the https://sashat.me/2017/01/11/list-of-20-simple-distinct-colors/

In the first row, green yellow and white are almost dazzling. Serato uses the hue colors of equal lightness which are not distinguishable for color blind people. 
Looking at this I like the lower row the most.  I would probably adjust red a bit darker though.

**Comment by daschuer** [comment]
Does this black background picture suite as a controller model?

**Comment by ferranpujolcamins** [comment]
I've reverted the defaultRGBA of the colors.

I'm a little bit lost on the conversation. What else is left to do?

**Comment by ferranpujolcamins** [comment]
`

**Comment by daschuer** [comment]
Thank you for this link which helps me for a fresh view on the topic: 
https://programmingdesignsystems.com/color/perceptually-uniform-color-spaces/index.html#perceptually-uniform-color-spaces-e7zMSWy

> In this scenario, designers use their eyes to decide whether a color is right or wrong, and the RGB values play no role in this decision.

I think it is a good idea to take the advice and not pick the colors by RGB values. This way we are free to adjust them by design and usability. 

I think we have a common understanding of the following: 
* All cue colors are primary defined by their given names   
* Skins can adjust the colors freely in a range that still fits to this given name. 
* We also provide a reference sRGB value for each color, that can be displayed 1:1 on any general purpose computer monitor. 
* So these values should be optimized to result in a good design and usability on controllers RGB knobs. 

The question here is, what are these values in Mixxx. Unfortunately I have no access to such a controller. I have only a non-sRGB lamp. 

@ferranpujolcamins: 
Do you think you controller is near the sRGB definition?  
Is it possible to compare the controller colors with the monitor, and define a compensation function? 
Do you think the dots from above on black background can be used for comparison? 

The colors in the lower line are a good start, because they have unlike Serato (middle line) different brightness, and they are also not to much saturated to be dazzling. 

I like also your idea to have white available, but I think a fully saturated white will be actually dazzling. 
So how about keep the name "white" but lower the brightness a bit. 

Do you think  this proposal will work? Ideas?

**Comment by ferranpujolcamins** [comment]
I'm open to any adjustment of the final colors.

> Do you think you controller is near the sRGB definition?

Somewhat. It is RGB, but you can only choose from a predefined set of colors.

> Is it possible to compare the controller colors with the monitor, and define a compensation function?

From my point of view, we can't anticipate how the leds will look on a controller. There are so many differences. For example, my controller has a clear plastic on top of the leds. So I expect it to display brighter colors than a controller that has the leds below a rubber pad. Shall the default colors be tuned for the former or the later?

Furthermore, what might be good colors for controllers might not be the best for computer screens. Then we need two default RGBs per PredefinedColor, one for screens, and one for leds. But as said, the default RGBs for the controllers might not fit all the controllers.

Thus, I suggest to only have one default RGB per PredefinedColor, tuned for computer screens (current situation). Then, let controller scripts manually tune the colors.
Also, controller scripts can always add a custom brightness adjustment.

**Comment by daschuer** [comment]
That sounds good. 

Do you like the idea to provide a reference graphic as orientation for the controller mapping? 
Do you think the example above works? If you like I can finally prepare one. 

How are the colors defined in your controller?  Do yo have a link to the users manual? 

So we have finally the hard chose to define the set of Mixxx colors. 
Do you share my opinion not to use "matching" colors instead of fully saturated? 
What do you think about the Serato idea to user colors of equal lightness? Is it the case on your controller?

**Comment by ferranpujolcamins** [comment]
> Do you like the idea to provide a reference graphic as orientation for the controller mapping?
Do you think the example above works? If you like I can finally prepare one.

Sure!

> How are the colors defined in your controller? Do yo have a link to the users manual?

See the [Manual on Page 8](https://s3.amazonaws.com/MF_Support_Docs/Midi+Fighter+Spectra+User+Guide.pdf)

In this picture you can see how the colors look like.
img_9909
As you can see, some of the colors are really hard to distinguish*. That's why I think it's important to keep a reduced color palette. We could offer 20 colors, but if the user cannot distinguish some of them, its like we only had 10 colors. If we need even more ways to categorize cue points, then we could let the user choose the shape of the marker. But we shall not over-use the colors feature.

> Do you share my opinion not to use "matching" colors instead of fully saturated?

On controllers, a dimm led can be used to mean "deactivated"*. Think when we have loop cues. Full brightness could mean currently playing that loop, dimm light might mean cue set but not playing, and led off could mean cue not set. So we must make sure that a darker version of the color can be generated, so we are future proof.
Thus I wouldn't use dark colors. But as long as colors are not dark, I don't mind different brightness among them.

**Comment by daschuer** [comment]
Interesting. The 10 colours of the color picker are not the primary colors, they have similar but not equal brightness. The only exception is white, which is actually dazzling. 
What we can also see in the photo that the color reproduction bad as expected bad. White is far from plain white and red and orange are quite similar. 

I will make a draft combining all findings.

**Comment by daschuer** [comment]
grafik

How about this? 
11 colors, that maps nicely to the Midi Fighter.

**Comment by ferranpujolcamins** [comment]
IMHO, there are still too many colors. Orange and red can be difficult to distinguish. Also Lime and Yellow. Also Blue and Purple.

**Comment by daschuer** [comment]
OK, It was just the idea to cover all colors of you controllers. I can imagine that it can be disappointing to not allow all.  Do you think it make sense to adjust brightness and saturation a bit or should we reduce the colors?

**Comment by ferranpujolcamins** [comment]
Keep in mind that my picture is just the color set of one particular controller. Other controllers might have a different number of colors (or be full RGB). So we don't need to exactly fit the MidiFighter.

> Do you think it make sense to adjust brightness and saturation a bit.

Sure, the goal is to make them distinguishable. But, when in doubt, aim for less colors. Adding a color is a backwards compatible change. Removing one is not ;)

The MidiFighter has 10 full-brightness colors and their dimm variant. Is one of your 11 colors supposed to be one of the MidiFIghter dimm colors? I'd prefer not to.

**Comment by daschuer** [comment]
> Orange and red can be difficult to distinguish. Also Lime and Yellow. Also Blue and Purple.

Interestingly It looks different with my eyes and monitor. Red and Orange looks good here, I can confirm Lime and Yellow. Purple looks actually closer to Magenta then to Blue. I have just crosschecked it on a different screen where Purple is closer to blue ... strange.

**Comment by ferranpujolcamins** [comment]
How about removing / replacing orange, lime and purple?

**Comment by daschuer** [comment]
Yes .. This is probably the best.

**Comment by Swiftb0y** [comment]
IMO I'd keep purple but make it a light purple. That should be easy enough to distinguish from the pure blue (atleast it is on my controller).
Other than that, I agree that we should remove Lime and Orange as they are hard to distinguish / not even reproducible (atleast on my Numark NS6II).

**Comment by daschuer** [comment]
grafik
grafik
grafik

OK, so we go for the lower one?

**Comment by daschuer** [comment]
Like this? 
grafik

**Comment by ferranpujolcamins** [comment]
For me purple is hard to distinguish from blue in your previous 11 colors palette. And in your last palette is too close to magenta.

:/

**Comment by daschuer** [comment]
So we take the one in between?

**Comment by ferranpujolcamins** [comment]
Could work. What if we make magenta a little bit darker, and then purple a little bit lighter.

**Comment by daschuer** [comment]
grafik

**Comment by daschuer** [comment]
I am fine with this :-)

**Comment by ferranpujolcamins** [comment]
For me it's still a mud of color :)

But I'm afraid we will be discussing this endlessly.

**Comment by daschuer** [comment]
grafik
Interesting how the colors behave differently with their neighbors.

**Comment by daschuer** [comment]
My wife suggest to review orange in favor of magenta which is too technical 
grafik

**Comment by Swiftb0y** [comment]
It might look good on the screen but differentiating between orange and red is much harder on the controller since it is unable to reproduce the orange as vibrant as other colors. I tested it on my Launchpad and my NS6II and they both gave equally bad results. So I don't other controllers will do a better job as well.

**Comment by daschuer** [comment]
she suggests to replace cyan with the more common Türkis in Germany. Is this valid for turquoise in English as well?

**Comment by daschuer** [comment]
OK, so lets your controller be the reference. Which proposal works best? Should we just remove the orange from the last one?

**Comment by Swiftb0y** [comment]
Yes I think that is the best solution. I can post some pictures of the lights on the controller tomorrow.

**Comment by daschuer** [comment]
turquoise 2.810.000.000 hits
cyan 308.000.000 hits

**Comment by Swiftb0y** [comment]
What about teal? I know they are technically different colors but since we only have that one cyan-like color I dont think it matters. And I think people use the term teal more than turquoise (it probably just has so many hits because people google how to spell it xD).

**Comment by ferranpujolcamins** [comment]
I think this new purple is too dark for led lights.

**Comment by daschuer** [comment]
grafik

**Comment by ferranpujolcamins** [comment]
> turquoise 2.810.000.000 hits
cyan 308.000.000 hits

According to Wikipedia they are two different colors

https://en.wikipedia.org/wiki/Cyan
https://en.wikipedia.org/wiki/Turquoise_(color)

**Comment by daschuer** [comment]
grafik

**Comment by ferranpujolcamins** [comment]
I like this last one. But maybe I prefer the old pink

**Comment by daschuer** [comment]
> According to Wikipedia they are two different colors

Yes Turquoise is more greenish, but that matters only if you have both side by side.

**Comment by ferranpujolcamins** [comment]
> But maybe I prefer the old pink

Or a mix between the new one and the old one would probably work too.

**Comment by Swiftb0y** [comment]
> I think this new purple is too dark for led lights.

I agree, my controller can't even reproduce dark purple (only light purple, which is very vibrant and can is easily distinguishable from the pure blue; pictures will follow tomorrow). So I think as long as we can create enough contrast in the UI, we should keep purple as pretty much any controller is able to display it.

**Comment by daschuer** [comment]
according to Wikipedia we have a "sky blue"

**Comment by daschuer** [comment]
Final Draft: 
grafik


red #c50a08ff
yellow #f8d200
green #32be44
sky blue #42d4f4
blue #0044ff
purple #af00cc
pink #fca6d7
white #c9c9ff

**Comment by ferranpujolcamins** [comment]
A(lmost)LGTM

I would just make white a little less bluish. What about:

white #F2F2FF

**Comment by daschuer** [comment]
Ok, I don't really mind.
My original idea was to make it a non dazzling  xenon white. But it is anyway up to the controller mapper.

**Comment by daschuer** [comment]
grafik

**Comment by ferranpujolcamins** [comment]
Shall we name SkyBlue Cyan? Right now is the only color with two words name. On the skin xml files, you specify the color with <CueXXXX>, so it would be <CueSkyBlue>. I think <CueCyan> it's easier.

What do you think?

I don't have strong feelings for this so please feel free to keep SkyBlue.

**Comment by daschuer** [comment]
In German the term cyan is only used for printer ink. So I prefer at least not to expose it to the user.  
Sky blue is also "Celeste". Google has many hits but just because a video game has the same name. 
https://en.wikipedia.org/wiki/Sky_blue

**Comment by ferranpujolcamins** [comment]
I like Celeste. I'll make the changes ASAP

**Comment by daschuer** [comment]
https://en.wikipedia.org/wiki/Celeste:
"Celeste (color), a turquoise-blue commonly called sky blue in English"

**Comment by Swiftb0y** [comment]
> red #c50a08
yellow #f8d200
green #32be44
sky blue #42d4f4
blue #0044ff
purple #af00cc
pink #fca6d7
white #f2f2ff

If that is gonna be the final graphic, can we change the Colors IDs sequence to line up with the graphic (like that yellow has ID 2 instead of 4), or are they fixed?

> Yes I think that is the best solution. I can post some pictures of the lights on the controller tomorrow.

I was too busy yesterday, here  are the pictures. I just took the with my phone camera so the exposure and the color balance are not quite right. The Bottom lights are from my NS6II and can only be set via MIDI (predefined palette). The top lights are from my launchpad mk2 and are set via SysEx to represent the proposed color palette as accurate as possible, so each color has a resolution of 18-bit (6-bit per channel).

### Dark room:



### Lit room:

**Comment by daschuer** [comment]
Are you satisfied withe the real results? Judged from the probably shifted photos by your camera and my monitor, the mk2 looks quite good. Pink and Red looks a bit off on the NS6II. I did not find a reference palette of it. Do you have a link to it?

**Comment by Swiftb0y** [comment]
I love Numark for their good price to performance ratio and their build quality but they keep _everything_ apart from the basic manual closed source. So I just tried out all colors by hand and tried to categorize them roughly. So unfortunately there is no reference palette available. The Pink on the NS6II looks IRL more like `#ff7f4c` and the red is pure red `#FF0000`. So you can differentiate them in person, just not on in the picture.
Something I also have to add is that the colors on the MK2 are not as bright and vibrant as they could be (as I used the proposed hex values instead of more appropriate pure controller colors; eg `#c50a08` instead of `#ff0000`).

**Comment by daschuer** [comment]
OK, I did not expect that you pass the RGB codes 1:1. It was intended that the mapper can pick the best color that mandatory matches the color name and may match the color palette above, to achieve a good usability and looking. So If you like brighter Buttons on the MK2, go ahead.

**Comment by Swiftb0y** [comment]
Ok this is a daylight picture again but with manually tweaked colors: 


All the obvious colors are made of their components maxed out (red: FF000, yellow: FFFF00, Pink, FF00FF etc). For future reference, I used `#FF7093` for pink.

**Comment by ferranpujolcamins** [comment]
@daschuer Colors updated and color svg template added. Shall we merge this?

**Comment by daschuer** [comment]
Yes, sorry for the delay. LGTM and thank you!

**Pull request merged**
