### PR TITLE
LateNight Palemoon: improve icon/font contrast

### PR DESCRIPTION
**Pull request by ronso0**
Even though PaleMoon with it's dim colors and low contrast is designed for dim club situations there are spots where accessibility can be improved.

- [x] deck settings Eject, Repeat, Slip Mode etc.
- [x] GUI toggles in the top bar
- [x] knob labels in the Main mixer
- [x] Fx buttons in the Main mixer
----
postponed:
- [ ] optimize BPM tap button?
- [ ] beautify / unify checkbox graphics
- [ ] improve duration/rate labels

based on #3788, will rebase when that is merged.

### CODE REVIEW

**Comment by daschuer** [comment]
I had just a brief look and I can confirm the improvement. The tips of the magnet are glowing a bit here.

**Comment by ronso0** [comment]
> The tips of the magnet are glowing a bit here.

...when quantize is On, yes. I adapted that from Tango long ago.

**Comment by Holzhaus** [comment]
@ronso0 do the missing changes depend on the changes already present? If not, let's use separate PRs so that we can already review and merge stuff in smaller pieces.

**Comment by ronso0** [comment]
If you prefer it that way let's go!

Besides small cosmetical tweaks, there's one accessibility issue left: the BPM Tap button hover highlight covers much more than the actual Tap button.

**Review by Holzhaus — COMMENTED** [review]
Looks good, thank you.

One thing I noticed: The slip button is not fully lit, is that intended?

Peek 2021-05-03 20-50

The alternative would be to make the filled background triangle dark gray (like the "U" shape of the magnet) and the foreground triangle outlines lighter gray (like the tips of the magnet).

**Comment by ronso0** [comment]
Good idea, so basically like in Classic, just with a fancy shadow:
image

**Comment by ronso0** [comment]
Ready!

**Review by Holzhaus — APPROVED** [review]
Thank you!

**Comment by ronso0** [comment]
btw this should also have resolved the issues with 'fill=' residues in SVG files, so you should now see palemoon as it was designed.

**Comment by uklotzde** [comment]
@ronso0 There are some merge conflicts with main. Are you able to resolve them?

**Comment by ronso0** [comment]
yup, done. Will lead to some more merge fun in #2618 -- which I can take care of when we continue working on it

**Pull request merged**
