### PR TITLE
Move cross.png from res/skins to res/images/library to avoid shipping it

### PR DESCRIPTION
**Pull request by sblaisot**
Fixes lp:1652971

This avoids skins/cross.png to be bundled in the installer and be shipped to users.
It is compiled within Mixxx

### CODE REVIEW

**Comment by rryan** [comment]
thanks! src/widget/wsearchlineedit.cpp:15 needs an update too

**Comment by sblaisot** [comment]
hummm, it's `QPixmap pixmap(":/skins/cross.png");` not res/skins/cross.png. 
isn't this one dynamic at runtime ? if this is the case, we need to bundle&ship this file.

**Comment by rryan** [comment]
> hummm, it's QPixmap pixmap(":/skins/cross.png"); not res/skins/cross.png.
> isn't this one dynamic at runtime ? if this is the case, we need to bundle&ship this file.

Nope, that's referring to the paths defined in the QRC file.  (a path starting with ":" means "look in a resource path"). 
https://doc.qt.io/qt-4.8/resources.html#using-resources-in-the-application

**Comment by sblaisot** [comment]
ok, done.

**Comment by rryan** [comment]
thanks!

**Pull request merged**
