### PR TITLE
Make sure to set the cue default mode based on userdata, not index

### PR DESCRIPTION
**Pull request by ywwg**

### CODE REVIEW

**Comment by ywwg** [comment]
@Be-ing take a look, this works for me

**Comment by Be-ing** [comment]
Not quite. The drop down in the preferences presents the mode that was saved on last shutdown, but the behavior of the play and cue buttons is incorrect.

**Comment by ywwg** [comment]
ah ok

**Comment by ywwg** [comment]
try now.  Also updated the tooltip

**Comment by Be-ing** [comment]
The code works now.

**Comment by Be-ing** [comment]
Thanks for taking care of this.

**Pull request merged**
