### PR TITLE
Update to mixxx-deps-2.3-x64-windows-318a1b3

### PR DESCRIPTION
**Pull request by daschuer**
This brings Portaudio fixes from https://github.com/mixxxdj/vcpkg/pull/63

### CODE REVIEW

**Comment by daschuer** [comment]
@JoergAtGithub Can we merge this? I think it has been received sufficient testing @ https://github.com/mixxxdj/vcpkg/pull/63

**Comment by JoergAtGithub** [comment]
I did a short test on my system for https://github.com/mixxxdj/vcpkg/pull/63 and I saw no regression. But I'm not affected by any of the addressed issues.

**Comment by Swiftb0y** [comment]
Then lets merge and ask the contributors that filed the original issues to test the resulting CI builds.

**Comment by JoergAtGithub** [comment]
The CI builds are already available and I asked the reporters of all 3 addressed issues to test it.

**Review by JoergAtGithub — APPROVED** [review]

**Review by Swiftb0y — APPROVED** [review]

**Pull request merged**
