### PR TITLE
Revert "Skins :: adjust styles of skin context menus, tooltip, ..."

### PR DESCRIPTION
**Pull request by ronso0**
Reverts mixxxdj/mixxx#2337

I'd rather revert the entire PR and fix the remaining issues (especially on MacOS) in a #2337 clone instead of having to rush things because of the now inconsitent and broken situation (at least in Deere) on MacOS.

### CODE REVIEW

**Comment by daschuer** [comment]
Oh sorry. I should have read closer.

**Comment by ronso0** [comment]
@daschuer What's the easiest way to get the previous branch into a comparable state again, without having to resolve merge conflicts...again?
Simply comparing the old branch to master now gives me "nothing to compare".
Renaming the old branch gives the same result.
Cherry-picking gives me conflicts already with the first commit.
`rebase -i` and `squash` all commits?
checkout master, revert to before my first commit, then cherry-pick all commits incl. merge-master?

**Comment by daschuer** [comment]
How about that:
git fetch upstream
git reset upstream/master --hard
git revert 6e1abd2a20dfbacb28c882fd5b65f0be142d2d4e
git push -f

(Untested) 

You need to open a new PR.
Sorry for all the hassle.

**Comment by ronso0** [comment]
I'll try that.
Nevermind, shizzle happens.

**Pull request merged**
