### PR TITLE
Fix the AppData file to actual validate

### PR DESCRIPTION
**Pull request by hughsie**
Also, while we're here update the file to the latest spec level and match the
style guide somewhat closer.

### CODE REVIEW

**Comment by illuusio** [comment]
Don't what to be downer but it would be better to cut those in smaller segments but it's in the future. I'll go through the changes..

**Comment by daschuer** [comment]
Thank you @hughsie for the pull request. Could you give some more details why the change is required? 

In order to distribute the changes, we need you permission. Please sign:

https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ

and comment here when done.

**Comment by hughsie** [comment]
@daschuer Without the change the AppData is not used for two reasons:
 * The screenshot URL is incorrect
 * The markup description contains invalid tags

Furthermore, the "appstream-util validate" program complains about missing tags and also about the lack of adherence to the style guide.

I don't know if I can agree to that contributor licence agreement without contacting my employer.

**Comment by hughsie** [comment]
All of my changes are trivial, and I'd be happy to either contribute them under a CC licence or a public domain "do whatever" licence, or just to waive my copyright if this is easier. Red Hat legal would have to study the CLA in detail before I can sign anything for obvious reasons.

**Comment by daschuer** [comment]
Thank you, public domain works for us.

**Comment by daschuer** [comment]
@illuusio: This looks good to me. Just give a hint, if you have finished your review.

**Comment by illuusio** [comment]
XMLlint is satisfied and all changes seems to better than the original. Wording is better and there actually nothing more to nag that splitting commits. LGTM also let's get this in to repo!

**Comment by daschuer** [comment]
Thank you :-)

**Pull request merged**
