### PR TITLE
ci(pre-commit): Use pre-commit to fix clang-format execution on Windows

### PR DESCRIPTION
**Pull request by Holzhaus**
@JoergAtGithub please check if this fixes clang_format on windows.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Unfortunately it doesn't help:
grafik

**Comment by Holzhaus** [comment]
next try, maybe this works

**Comment by JoergAtGithub** [comment]
The Python interpreter is now found, but it fails in the second pass:
grafik

**Comment by Holzhaus** [comment]
But you do have `clang-format` installed and in %PATH%`? So if you type `clang-format` in CMD it works?

**Comment by JoergAtGithub** [comment]
I had a clang-format installation, which wasn't in my search part. But this installation wasn't in the pre-commit cache folder, where the other code checkers are installed. I added it manually to the PATH, and it seems to work together with this PR.

**Comment by JoergAtGithub** [comment]
This was too early, it has always result `Passed` now, but doesn't detect or correct anything.

**Comment by Holzhaus** [comment]
> I had a clang-format installation, which wasn't in my search part. But this installation wasn't in the pre-commit cache folder, where the other code checkers are installed.

This is normal. In contrast to the other hooks, this hook depends clang format being installed on the host and does not set it up automatically.

> This was too early, it has always result `Passed` now, but doesn't detect or correct anything.

This is also normal, because our custom clang_format hook which is severly broken (we should just have opted for the regular clang-format instead). Have you tried actually changing a C++ file and making a really long line (> 120 chars) and then stage that change? This should work.

Anyway, i'll try to make a new PR that drops this custom stuff because it's a pain to maintain.

**Comment by JoergAtGithub** [comment]
> This is normal. In contrast to the other hooks, this hook depends clang format being installed on the host and does not set it up automatically.

This installation step is missing under: https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking

> Have you tried actually changing a C++ file and making a really long line (> 120 chars) and then stage that change? This should work.

Just tried exactly this, the line is not broken, but clang-format Passed

**Comment by Holzhaus** [comment]
Please let me know if #10972 works.

**Pull request closed without merging**
