### PR TITLE
Latenightoptimizations112

### PR DESCRIPTION
**Pull request by synthor**
Here we go. :) This pull request replaces #632, #633 and #634. I created a branch of master instead of 1.12 and messed up my local repo a bit. Sorry for effort.

### CODE REVIEW

**Comment by daschuer** [comment]
Yes! Thank you. Do you have signed the contributor agreement?

**Comment by synthor** [comment]
No, I created a launchpad account even now. Signing would be the next step.

**Comment by synthor** [comment]
Done. :)

**Comment by daschuer** [comment]
Thank you very much.

**Pull request merged**
