### PR TITLE
LateNight: half Screen width Waveform

### PR DESCRIPTION
**Pull request by nopeppermint**
If two waveforms share the width of the screen, the required hight is reduced, that's the idea of this button.

before/after (2 Decks):
parallel_wavefom2
halfe_wave_2deck

before/after (4 Decks):
paralell_waveform
have_wave_4deck

This can be toggled with this button:
toggle_buttons

Change from half width to full width waveform is not yet working, as I didn'n found a way to correctly implement
 ```<Template src="skin:button_2state.xml">```

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you.
I like the idea, but not the position of the button. It is paired with buttons to edit the waveform content. 
Can we move the button to the bottom row?

**Comment by nopeppermint** [comment]
> Can we move the button to the bottom row?

shure, you mean like this:
pressed
unpressed

**Comment by Be-ing** [comment]
Even if it is optional, I am a bit wary to rush such a big design change.

**Comment by nopeppermint** [comment]
2.2 is also fine, I will then try to add this as well to Tango and Deere and maybe add a vertical (black) spacer between the waveforms

**Comment by ronso0** [comment]
I like the idea implemented here, and/but I think it makes sense only after #1520 is merged so you can look further ahead than shown in the screenshots.

OT: Another idea (I think someone in the forums made a mockup) is to show only the upper half of each waveform so the waveform height can shrink but you have (almost) the same information available. And -more important IMO- all playpositions are in a line what makes visual beatmatching with 3/4 decks easier.

**Comment by nopeppermint** [comment]
> it makes sense only after #1520 is merged 

for me this is independent

> OT: Another idea...  to show only the upper half...

I think for another option we would need another button, and then in Latenight a "Skin Setting Button" like in Deere/Tango would be a good Idea as the toolbar is getting full..

BTW: is already someone working on such a "Skin Setting Button" for Latenight?

I now added a "black spacer" between the left and right waveform, this better separates the two waveforms.

black_spacer

I am done here, any comments?

**Comment by nopeppermint** [comment]
now it looks like this:
final

**Comment by nopeppermint** [comment]
closing, as i created a new branch based on 2.1
=> #1622

**Pull request closed without merging**
