### PR TITLE
Update Launchpad links to point to GitHub issues instead

### PR DESCRIPTION
**Pull request by fwcd**
Inspired by https://github.com/mixxxdj/mixxx/pull/11265#discussion_r1103712044, this PR updates all the Launchpad links to the corresponding GitHub issues.

In case anyone's curious/wants to verify the result, [this is the script I've used](https://gist.github.com/fwcd/abd9b719affeac5d4d6c4d2afe2206bf) (requires a GitHub API token).

### CODE REVIEW

**Comment by Swiftb0y** [comment]
IMO this counts as a frowned upon mass reformatting PR that comes with the usual merge conflicts. I don't think others will accept it. Also, if you had told us earlier, we could've given you the issue database that contains the mapping between github and launchpad issues...

**Comment by JoergAtGithub** [comment]
If we don't apply pre-commit changes for this PR, I don't see a problem with mass reformatting.

**Comment by fwcd** [comment]
Sorry, I was perhaps a bit too eager with this, I was in the mood for hacking together something for fun :D Yeah, I definitely see your point in this being hard to review... but that's probably in the nature of such a change.

Feel free to close this or repurpose the script e.g. to read the mapping from the database you've mentioned if that's easier to do.

**Comment by daschuer** [comment]
I consider the resulting conflicts easy to resolve and the scripting approach the only way we can manage this change. 
The change itself is helpful, because searching in our launchpad is disabled and we need to compose the links manually if they are shortened. 

I am a bit concerned about the existing bug links that are not following an unambiguous notation.
How about clean that up first and then apply the swap in a second commit?

**Comment by Swiftb0y** [comment]
I don't really see a huge need to swap all the links, after all you can just follow the link to launchpad and then follow to github since the backlink is posted on launchpad as well. That said, while its not a big improvement, it doesn't have much downsights either so I'm neutral on whether to merge this.

**Comment by uklotzde** [comment]
I would appreciate it to replace the legacy links that still point to Launchpad.

### Unrelated remarks

- The code should only reference open issues, not closed issues. All relevant information from closed issues that is still needed for understanding the code and its design decisions should be included literally as code comments.
- Cross-referencing open issues in the code has proven helpful for tracing and resolving them.

**Comment by fwcd** [comment]
Any updates on this? We should probably either move forward with this PR or close it to avoid accumulating a lot of conflicts.

**Comment by JoergAtGithub** [comment]
I would like to see this get merged. What are the preconditions, that everybody is fine with this?

**Comment by Swiftb0y** [comment]
No objections from me, but it would be nice if the couple ambiguous occurrences in the source could be fixed. They're only a few and can be fixed by hand. I used `grep -Hirn -E "(#|lp:?)[0-9]{7,10}"` to find them.

**Comment by daschuer** [comment]
I am also supporting the merge. I think that should go to 2.4 to lower the risk of future merge conflicts.

**Comment by fwcd** [comment]
I've rebased it to 2.4

**Review by daschuer — APPROVED** [review]
LGTM Thank you for taking care.

**Comment by daschuer** [comment]
I will issue another PR fixing the remaining LP numbers as suggested by @Swiftb0y-

**Pull request merged**
