### PR TITLE
Escape crate names filter, fixing lp1789728

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by daschuer** [comment]
This also fixes 
https://bugs.launchpad.net/mixxx/+bug/1784090
https://bugs.launchpad.net/mixxx/+bug/1789728

This may also be a 2.1.5 candidate, because it is a bug fix and the it has a local scope and a test.

**Comment by daschuer** [comment]
The Appveyor fail is unrelated to this PR,

**Comment by Be-ing** [comment]
> This may also be a 2.1.5 candidate, because it is a bug fix and the it has a local scope and a test.

I agree.

**Comment by daschuer** [comment]
OK, thank you. Ready for merge?

**Comment by Be-ing** [comment]
LGTM, but I'd like another review before merging this to a stable branch. @uklotzde could you take a look?

**Comment by uklotzde** [comment]
@Be-ing Sorry for the long response time. LGTM. I will just do a quick manual test before merging it.

**Pull request merged**
