### PR TITLE
mixed key (Lancelot/OpenKey + traditional) notations

### PR DESCRIPTION
**Pull request by Be-ing**
This fixes the merge conflict from #1794 and continues with some code cleanup.

### CODE REVIEW

**Comment by Be-ing** [comment]
Ready for merge?

**Comment by daschuer** [comment]
This fails to build on Travis.

#include "util/compatibility.h" is missing in
preferences/dialog/dlgpreflibrary.cpp

**Comment by Be-ing** [comment]
CI passed

**Comment by daschuer** [comment]
Thank you. LGTM.

**Pull request merged**
