### PR TITLE
Remove SoundSource plugins. Move SoundSourceM4A/WV into Mixxx.

### PR DESCRIPTION
**Pull request by rryan**
Fixes Bug #1792747. Tested on macOS 10.13.6

### CODE REVIEW

**Comment by rryan** [comment]
screen shot 2018-09-19 at 7 57 07 pm
😍

**Comment by uklotzde** [comment]
Yeah! I didn't have the courage for doing this. LGTM.

This will definitely get into my own customized and improved 2.2 version ;)

**Comment by uklotzde** [comment]
We can safely ignore any whitespace warnings from CodeFactor checks. The whole code will hopefully be reformatted at some day.

**Comment by Be-ing** [comment]
Thanks for the code cleanup!

**Pull request merged**
