### PR TITLE
Skins / WidgetStack: keep keyboard focus in Library when toggling [Master],maximize_library

### PR DESCRIPTION
**Pull request by ronso0**
https://bugs.launchpad.net/mixxx/+bug/1815314
"Maximize Library steals focus, makes keyboard presses non-working"

**Skins**
Deere, LateNight & Tango need separate widgets to show either the entire skin or a maximized library and minimal decks because we use `<Splitter>`s to have both resizable waveforms and an always dynamically expanding library.¹
I restructured Tango and Deere so they work like LateNight where a `WidgetStack` toggles the regular / maximized library views. For some reason the WidgetStack has an advantage over `WidgetGroup` with `visible` `<Connections>`, even though we use a Singleton for the library in both variants:
the keyboard focus remains on widgets in the WidgetStack. ~~The focus jumps between TreeView and LibraryTable though when using `[Master],maximize_library`. (shortcuts still work, so I consider this an improvement and resolution of the keyboard bug)~~ Fixed, see below:

**WidgetStack**
After switching to another widget in a WidgetStack it now checks if the previously focused widget is a child of the new widget. If true it is re-focused. This is fail-proof because all library widgets are placed in a SingletonContainer which is both in the regular and the maximized view.

¹Only in Shade the focus stays on the same libary widget (tree or table) when toggling [Master],maximize_library, because there we don't have separate, stacked and resizable waveforms.
IIRC Library Singletons are necessary in the other skins to implement a working `<Splitter>`

### CODE REVIEW

**Comment by ronso0** [comment]
Please test.

**Comment by daschuer** [comment]
Unfortunately the fix only works if no deck is playing. 

I think we need the help of the C++ domain. 

A rough idea: 
Overload setCurrentIndex in WidgetStack. 
Call QApplication::focusWidget() use objectName() to identify the current focus widget.
Change the stack.  
findChild() in the new stack and restore the focus.

**Comment by ronso0** [comment]
**Haa!**
With current master the keyboard shortcuts always work (tried `play` and `rate_up_perm`) no matter which widget has focus or if the library was maximized.
This is on Ubuntu 18.04 without a controller, mouse / keyboard only.

Can anyone confirm this?

**Comment by daschuer** [comment]
I have tested this PR merged to master on Ubuntu Xenial. Do I need to retest?

**Comment by ronso0** [comment]
okay, maybe (probably) Xenial has an older QT version?
I've built it on Bionic wit Qt 5.9.5 and this PR solves the issue

**Comment by daschuer** [comment]
OK, so if one else can confirm the fix we can merge it. 
@Be-ing can you confirm this?

**Comment by esbrandt** [comment]
Tested this patch on macos 10.14.6 (18G95) with ``2.3.0-alpha-pre (build master r6951)``, and the bug remains. 
Tested skins : All bundled

**Comment by ronso0** [comment]
Okay, @esbrandt which Qt version did you use for the build?
I've built it on Bionic wit Qt 5.9.5 and this PR solves the issue

So it seems to be necessary to tweak WidgetStack with a readFocus/setFocus function as @daschuer suggested.

**Comment by esbrandt** [comment]
Using qt 5.13.0 on this machine

**Comment by daschuer** [comment]
How do we want proceed here? This should not block 2.3 at least.

**Comment by ronso0** [comment]
Yeah! I'm confident I found a solution that is platform-independent. Works as intended for SearchBox, Clear button, tree view, tracks table, AutoDJ spinbox ....

Pretty much what @daschuer proposed earlier:
After switching to another widget in a WidgetStack it now checks if the previously focused widget is a child of the new widget. If true it is re-focused. Since all library widgets are placed in a SingletonContainer this is fail-proof. (except in Shade where the focus problem doesn't occur in the first place because there's no Splitter)
Please test!

In the meantime I'll optimize the controls in all skins' widgetstacks to reduce the calls within WWidgetStack.
It turned out that simple `<Connection>`s bound to 'visible' produce only one call to `setCurrentIndex` while a combination of `trigger=".."` and `on_hide_show="N"` produces about 3 different calls to functions in WWidgetStack which do `setCurrentIndex` redundantly.

**Comment by ronso0** [comment]
Ready for review & merge.

**Comment by ronso0** [comment]
@esbrandt Could you please test again? This PR now contains the necessary changes in C++ to track & restore the focused widget.

**Comment by ronso0** [comment]
@daschuer Could you have a look?
This is the essence: new [void WWidgetStack::slotSetIndex(int index)](https://github.com/mixxxdj/mixxx/pull/2289/files?file-filters%5B%5D=.cpp&file-filters%5B%5D=.h#diff-4b6aba6d92a26e74ada9014ac3c083edR168) to put the focus on the previous focus widget again.

**Comment by daschuer** [comment]
This works like a charm and LGTM. Thanks.

**Pull request merged**
