### PR TITLE
Latenight :: implement hotcue colors

### PR DESCRIPTION
**Pull request by ronso0**
- use transparent bg SVGs for set/unset & pressed/unpressed states
- define bg color in css
- adapt changes to in/outro cues as well, match colors to waveform markers
- align hotcue numbers right to waveform markers

latenight-hotcue-icons

### CODE REVIEW

**Comment by daschuer** [comment]
Looks good, howerver there is an issue with the no color cues. Their buttons are red, but the waveforms marker is green.

**Comment by ronso0** [comment]
red was the default, so I'll change the marker color so that it fits and is still ready to recognize

**Comment by ronso0** [comment]
@daschuer I managed to correct the marker color, however the `<TextColor>` node is not respeccted.

[1] is no color/default red
[5] is auto-assigned red
xml says `<TextColor>#FFFFFFTextColor>` (white)
latenight-hotcue-markers

@Holzhaus Any idea how to fix it?

**Comment by daschuer** [comment]
Thank you, better now. LGTM. Ready to merge?

**Comment by ronso0** [comment]
jup, ready to merge.

I had to pace myself and not tweak Cue, Play and other buttons the same way...
A sidenote: as soon as someone takes care of [lp:1836967](https://bugs.launchpad.net/mixxx/+bug/1836967) we could lower the LateNight maintenance burden, get rid of the vast number of button icons in LateNight by using `border-image` and css, which would also lower the barrier to create another flavor/color scheme.

**Comment by daschuer** [comment]
Thank you.

**Comment by foss-** [comment]
this closes https://bugs.launchpad.net/mixxx/+bug/1829884 if I am not mistaken.

**Pull request merged**
