### PR TITLE
Reloop beatpad mapping (for Mixx 1.12)

### PR DESCRIPTION
**Pull request by DJChloe**
Don't blame me if I did something wrong I battled all this evening to learn how to use git and github. This the first time I use this tool, so... LOL.
Anyway I think I managed to do the things following all the steps given in the wiki.

Through this pull request I proposed to be included in Mixxx the mapping files for the Reloop Beatpad (for Mixxx 1.12)

### CODE REVIEW

**Comment by DJChloe** [comment]
Definetly I did something wrong :/
I definetly did not understand how to do a pull request.

Can anybody reject this stupid pull request of 800 items ?
thanks.

**Comment by Be-ing** [comment]
It looks like you were working off the master branch then made a pull request against the 1.12 branch. You could either start a new branch from 1.12 and commit your finished files, or if you had multiple commits and wanted to keep that log of the changes as you worked on the mapping, you could cherry pick those commits to a new branch off 1.12.

**Comment by DJChloe** [comment]
Thank you for your reply Be-ing. Yes, I made the mistake to create a branch from the master instead of the 1.12
My changes consist only in two files and I think I will take your first option (start a new branch from 1.12 and commit my 2 finished files).

Github is totally counter intuitive for me, but that's ok, I progress :)

**Comment by Be-ing** [comment]
Yeah, git can be really confusing at first but it's also really flexible.

**Comment by ywwg** [comment]
Actually the correct way to deal with this situation is using git rebase with the --onto flag.  It should be as simple as:

git rebase --onto 1.12

That rewinds out all your changes, remembers them, switches to 1.12, and replays them.  It's exactly what you want here

**Comment by DJChloe** [comment]
Thank you ywwg, I've learned something :)

**Pull request closed without merging**
