### PR TITLE
Updated mappings for the Hercules Inpulse 300

### PR DESCRIPTION
**Pull request by ywwg**
Squashed version of https://github.com/mixxxdj/mixxx/pull/12503

____
original description:

I made some improvements to Mixxx's included Inpulse 300 mapping. I tried to stay close to the manufacturer mappings listed in [this manual](https://ts.hercules.com/download/sound/manuals/DJC_Inpulse300/DJControl_Inpulse_300_User_Manual_EN.pdf).

Full list of changes:
- Added ability to stop samplers (shift + button)

- Added toneplay
    - Pressing a pad jumps to the most recently used hotcue and changes the pitch
    - Shift + toneplay changes the pitch without jumping
    - Pads 1-4 increase the pitch by +0 to +3 semitones
    - Pads 5-8 decrease the pitch by -4 to -1 semitones
    - LED reflects total adjustment to current key

- Added slicer/slicer loop:
    - Press slicer button to activate a slicer section, press again to deactivate it
    - Slicer length is dependent on loop length
    - Exiting slicer mode or pressing LOOP OUT also deactivates the slicer section
    - Creating a slicer section overrides active loops, and creating a 4-beat loop overrides active slicer sections
    - Only works on constant BPM (also true in native software DJUCED)
    - Slicer section does not move backwards when scratching (also true in native software DJUCED)

- Added actual beatmatch guide functionality to the LEDs
    - This replaces the LEDs' old end-of-track warning functionality. Hopefully no one missed it :P

- Changed the way scratching works
    - Wheels have inertia rather than instantly stopping when released (this allows backspins and other tricks)
    - Removed scratchPad in XML (not sure what it was doing there)

- Updated VU meter syntax
    - Replaced vu_meter with VuMeter to comply with new version of Mixxx
    - Replaced connectControl with makeConnection to allow multiple connections (and also to comply with newer versions)

- Replaced "hotcue_X_enabled" with "hotcue_X_status" in XML file to comply with newer version of Mixxx

Manual is being updated accordingly in another PR: [PR#604](https://github.com/mixxxdj/manual/pull/604).

### CODE REVIEW

**Review by Swiftb0y — COMMENTED** [review]
please rebase on 2.5

**Comment by Holzhaus** [comment]
Windows build is failing due to executable signing issues.

**Comment by ywwg** [comment]
@BoredGuy1 please test and confirm that this includes all of your fixes. Then I can merge

**Comment by BoredGuy1** [comment]
LGTM

**Comment by ronso0** [comment]
@BoredGuy1 We got a report in the [2.5.1/2.6 testing thread saying the wheels on the Inpulse 300 aren't working anymore](https://mixxx.discourse.group/t/mixxx-needs-testers-for-2-5-1-and-2-6/31700/7?u=ronso).
Do you maybe have a chance to test a 2.5.1 build (or just build current 2.5 branch) to check out the official mapping?

**Comment by BoredGuy1** [comment]
Sure, give me some time.

**Comment by ronso0** [comment]
Sorry, I overlooked that it was 2.6-alpha for which the issue has been reported.

**Comment by BoredGuy1** [comment]
I saw that libra10 was able to get the jogwheels to work on 2.6 Version 157.

I also tested on 2.7.0 alpha and the jogwheels were still working fine (although I only tested for about 10 minutes).

Seems OK for now, but let me know if anything else comes up.

**Pull request merged**
