### PR TITLE
add Skin Settings to Latenight

### PR DESCRIPTION
**Pull request by nopeppermint**
this PR ads a "Skin Settings Menu" to Latenight (mostly copy past from Tango)

first impression:
latenight_deck_settings

### CODE REVIEW

**Comment by nopeppermint** [comment]
clearly no candidate for 2.1, as this will take some more time ;-)

**Comment by ronso0** [comment]
> clearly no candidate for 2.1, as this will take some more time ;-)

Then just change the branch back to `master`
4 FX units are coming, as well as sampler row button and ...

I still think we can come up with a different solution than the now 'traditional' skin menu, one that doesn't squeeze the skin at minimum width for example.
Nevertheless, thanks for starting this!

**Comment by nopeppermint** [comment]
> Then just change the branch back to master

hmm.. is not so easy, I just tried to rebase on master, but somehow I managed to get some of the commit in 2.1 in here as well, as I originally started on a 2.1 based branch..

**Comment by nopeppermint** [comment]
settings

**Comment by nopeppermint** [comment]
I am done here, now the Question is, which Buttons should remain in the toolbar?
buttons

I vote for the "main" Settings:
* BIG LIBRARY
* 4 DECKS
* MIXER
* EFFECTS
* MIC/AUX
* SAMPLERS
* SETTINGS (might be replaced with a gear wheel Icon)
* REC
 
this mean, the following Buttons would be removed (they are already in the settings menu):
* SPINNIES
* VINYL
* EQ
* EQ KILL
* SUPER KNOBS

@ronso0 
> I still think we can come up with a different solution than the now 'traditional' skin menu, one that doesn't squeeze the skin at minimum width for example.

I don't see a problem there, it's just temporary while you're doing the settings, I think a pop-up window like the "main" settings dialog is less useful..

Or where you thinking about a semi transparent skin menu which doesn't change size as it's an overlay on the right side?

**Comment by nopeppermint** [comment]
- removed buttons from toolbar which now are in "skin settings"
- added button for "Mixer" and "Effects" in "skin settings"
settings_latenight

**Comment by nopeppermint** [comment]
> semi transparent skin menu which doesn't change size as it's an overlay on the right side?

https://photoqt.org/ has a nice "transparent menu"
transparent_menu

**Comment by nopeppermint** [comment]
> there's a qt bug on OSX that would put the menu behind the skin 

maybe this bug is solved now (with Qt 5.10.1) .. 
Do you have more information about this?

**Comment by nopeppermint** [comment]
follow up => #1623

**Pull request closed without merging**
