### PR TITLE
Deere: enabled "shadow position feature" for preview + samplers

### PR DESCRIPTION
**Pull request by nopeppermint**
add PlayedOverlayColor to preview
(used same color as in https://github.com/mixxxdj/mixxx/blob/2.1/res/skins/Deere/left_gutter.xml for deck1/2)
before:
deere_before_fix

after:
deere_fix

### CODE REVIEW

**Comment by nopeppermint** [comment]
This feature is also missing in the samplers

I tried to add "PlayedOverlayColor" to 
https://github.com/mixxxdj/mixxx/blob/2.1/res/skins/Deere/sampler_overview_row.xml
as well but there it changes nothing...


@ronso0 any idea why?

like this:

```xml             
                <Overview>
                <TooltipId>waveform_overview</TooltipId>
                <Group><Variable name="group"/></Group>
                <SizePolicy>me,me</SizePolicy>
                <BgColor></BgColor>
                <PlayedOverlayColor>#88000000</PlayedOverlayColor>
                <SignalHighColor>#FFE300</SignalHighColor>
                <SignalMidColor>#0099FF</SignalMidColor>
                <SignalLowColor>#FF0035</SignalLowColor>
                <SignalRGBHighColor></SignalRGBHighColor>
                <SignalRGBMidColor></SignalRGBMidColor>
                <SignalRGBLowColor></SignalRGBLowColor>
                <SignalColor>#FF8000</SignalColor>
                <PlayPosColor>#00FF00</PlayPosColor>
                <DefaultMark>
                  <Align>bottom</Align>
                  <Color>#00FF00</Color>
                  <TextColor>#FFFFFF</TextColor>
                  <Text> %1 </Text>
                </DefaultMark>
                <MarkRange>
                  <StartControl>loop_start_position</StartControl>
                  <EndControl>loop_end_position</EndControl>
                  <EnabledControl>loop_enabled</EnabledControl>
                  <Color>#00FF00</Color>
                  <DisabledColor>#FFFFFF</DisabledColor>
                </MarkRange>
                <Mark>
                  <Control>cue_point</Control>
                  <Align>top</Align>
                  <Color>#FF001C</Color>
                  <TextColor>#FFFFFF</TextColor>
                  <Text>C</Text>
                </Mark>
                <Connection>
                  <ConfigKey><Variable name="group"/>,playposition</ConfigKey>
                  <EmitOnDownPress>false</EmitOnDownPress>
                </Connection>
              </Overview>```

**Comment by esbrandt** [comment]
Add ``PlayedOverlayColor`` near [sampler_controls_row.xml#L33](https://github.com/mixxxdj/mixxx/blob/2.1/res/skins/Deere/sampler_controls_row.xml#L33).

Looks like parts of ``sampler_overview_row.xml`` are unused.

**Comment by nopeppermint** [comment]
thanks @esbrandt 
now with fix for samplers
before:
deere_sampler_no_fix
after:
deere_sampler_fix

**Comment by nopeppermint** [comment]
> Looks like parts of sampler_overview_row.xml are unused.

the whole file sampler_overview_row.xml is unused!

If I delete this file, and reload the skin there is NO change...

this file was last changed by @Be-ing in https://github.com/mixxxdj/mixxx/pull/940

In https://github.com/mixxxdj/mixxx/blob/2.1/res/skins/Deere/sampler.xml the file sampler_overview_row.xml is no longer used, this was changed by @Be-ing 

https://github.com/mixxxdj/mixxx/commit/728c06c7bde735fb8c4307cb89e45fe2b798d5b5#diff-6ac4554c9d507ce52e901ebcede22be2

sampler_overview_row.xml is not used in anther file as the following command shows:
```bash
/mixxx/res/skins/Deere $ grep -Ril "sampler_overview_row" ./

```

I suggest to delete "sampler_overview_row.xml "

**Comment by daschuer** [comment]
LGTM. @Be-ing, merge?

**Comment by Be-ing** [comment]
Thanks for implementing this and cleaning up the old file.

**Pull request merged**
