### PR TITLE
Controller: Hercules DJControl Jogvision

### PR DESCRIPTION
**Pull request by perseo22**
Complete mapping rewrite, with prettier? code, better documentation in
comments, some bugfixes, and new mapping addings

### CODE REVIEW

**Comment by Holzhaus** [comment]
Hi @perseo22, thank you for your contribution. Please pull the latest 2.2 branch into yours to resolve the merge conflicts. Also, we now maintain the mapping documentation as part of the user's manual, so please open a PR that adds documentation to this directory and link it here (note that you need to base this on the `manual-2.3.x`).

**Comment by perseo22** [comment]
Hi Jan!

You may remember me from the PR 2370 (yes, I'm that guy who doesn't know
about git at all... :(  )

So, could you please tell  what git commands do I need to do what you want
me to do?
This is my local git right now:

[david@torrejon mixxx]$ git status
On branch Controller_Hercules_DJControl_Jogvision
Your branch is up to date with 'origin/2.2'.

nothing to commit, working tree clean
[david@torrejon mixxx]$ git --version
git version 2.28.0

[david@torrejon mixxx]$ git branch
* Controller_Hercules_DJControl_Jogvision
  master

[david@torrejon mixxx]$ git pull -v
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

From https://github.com/perseo22/mixxx
 = [up to date]            2.2
    -> origin/2.2
 = [up to date]            1.10
   -> origin/1.10
 = [up to date]            1.11
   -> origin/1.11
 = [up to date]            1.12
   -> origin/1.12
 = [up to date]            1.8
    -> origin/1.8
 = [up to date]            1.9
    -> origin/1.9
 = [up to date]            2.1
    -> origin/2.1
 = [up to date]            Controller_Hercules_DJControl_Jogvision
    -> origin/Controller_Hercules_DJControl_Jogvision
 = [up to date]            DarkMetal
    -> origin/DarkMetal
 = [up to date]            KeyboardController
   -> origin/KeyboardController
 = [up to date]            jmigual-library-redesign
   -> origin/jmigual-library-redesign
 = [up to date]            master
   -> origin/master
 = [up to date]            revert-1448-jenkins_win_build_fix
    -> origin/revert-1448-jenkins_win_build_fix
 = [up to date]
 revert-1517-restore_metaknob_effect_switch_behavior ->
origin/revert-1517-restore_metaknob_effect_switch_behavior
 = [up to date]            revert-1662-more-max-speed
   -> origin/revert-1662-more-max-speed
Already up to date.

[david@torrejon mixxx]$ cat .git/config
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/perseo22/mixxx.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[branch "Controller_Hercules_DJControl_Jogvision"]
        remote = origin
        merge = refs/heads/2.2


Thanks!!!
David TV.

**Comment by Holzhaus** [comment]
First of all I recommend configuring your git setup to not do rebases when pulling changes:

    $ git config --global pull.rebase false

Next, check your remotes (these are links to the different forks of the mixxx repository). It should look like this:

    $ git remote -v 
    origin	git@github.com:perseo22/mixxx.git (fetch)
    origin	git@github.com:perseo22/mixxx.git (push)
    upstream	git@github.com:mixxxdj/mixxx.git (fetch)
    upstream	git@github.com:mixxxdj/mixxx.git (push)

If the `upstream` remote (the main mixxx repository) is missing, then you can easily add it using:

    $ git remote add upstream git@github.com:mixxxdj/mixxx.git

Now you should make a backup of your current branch to prevent losing stuff (just in case):

    $ git checkout Controller_Hercules_DJControl_Jogvision
    $ git branch -c Controller_Hercules_DJControl_Jogvision_backup

There's now a copy of the `Controller_Hercules_DJControl_Jogvision` called `Controller_Hercules_DJControl_Jogvision_backup`.

I think the cause of these conflicts is that you added the new mapping files to a state of the `2.2` branch from before the previous mapping for this controller was added. 

                               Current 2.2 branch
                           (with old Jogvision mapping)
                                   /
                                  /
       Old 2.2 branch            /
    (Jogvision mapping ----------
       not added yet)            \
                                  \
                                   \
                        Controller_Hercules_DJControl_Jogvision
                           branch (with new Jogvision mapping)

This means that git is now confronted with two different mappings and doesn't know which one to use. Usually you could just run `git pull upstream 2.2` and then `git mergetool` to resolve the conflicts by hand, but in this case I think it's easier to start fresh and just overwrite the files.

First, reset your current branch to the current state of the `2.2` branch. *WARNING:* This deletes all changes from the current branch, make sure you have a backup (as described above)

    $ git fetch upstream
    $ git reset --hard upstream/2.2  

Now, copy the changes from the backup back into the current branch, commit and push the changes here.

    $ git checkout Controller_Hercules_DJControl_Jogvision_backup -- res/controllers/Hercules_DJControl_Jogvision*
    $ git commit
    $ git push origin Controller_Hercules_DJControl_Jogvision --force

Let me know if you need more help.

**Comment by perseo22** [comment]
Hi Jan!

Wow... your steps worked like a charm!
I could push the changes!

Thanks a lot!!!!!!!!!

- David TV

**Comment by Holzhaus** [comment]
> Also, we now maintain the mapping documentation as part of the user's manual, so please open a PR that adds documentation to the repo's `source/hardware/controllers/` directory and link the PR here (note that you need to base this on the `manual-2.3.x`).

Could you take care of this?

**Comment by Holzhaus** [comment]
@perseo22 ping

**Comment by perseo22** [comment]
Hi Jan!

I already added the cosument page to the Git (directly through the web
interface), but I don't know how to proceed.
I  mean: you want me to "link something to another thing" (that's what I
understood... :( ) , but I simply don't know what you mean nor what to do.

If you give me some "light", I'll follow the path, but I really don't know
what do I have to do... (my fault, I'm a noob in collaborative coding, my
developments have always been of one person: me ;) ...)

Thanks!!
David TV.

**Review by Holzhaus — CHANGES_REQUESTED** [review]
Can you replace the `<wiki>...</wiki>` element with  `<manual>hercules_djcontrol_jogvision</manual>`?

**Review by Holzhaus — APPROVED** [review]
LGTM. Please resolve the review comments on the manual PR (https://github.com/mixxxdj/manual/pull/134), then we can merge.

**Pull request merged**
