### PR TITLE
Update qm-dsp from upstream 

### PR DESCRIPTION
**Pull request by daschuer**
This is another update from upstream. 

https://github.com/c4dm/qm-dsp/commit/9b18a2294638e2a28c8b97ca04d870422a8da4ef

### CODE REVIEW

**Comment by Pegasus-RPG** [comment]
If we don't make any changes to this source, is there a way we can set up our GitHub repo to auto-mirror upstream so that every Master build has the latest upstream libraries?

**Comment by daschuer** [comment]
Currently we still do changes. See mixxx-changes.patch

**Comment by daschuer** [comment]
Travis fails unrelated with 
```
DownloadError: Failed to download resource "libid3tag"
```

**Comment by uklotzde** [comment]
I would prefer to pull qm-dsp in with `git subtree` as demonstrated [in this branch](https://github.com/uklotzde/mixxx/tree/lib_qm-dsp_subtree)

Initial add:
```
git subtree add --prefix lib/qm-dsp https://github.com/c4dm/qm-dsp.git master --squash
```

Pull changes:
```
git subtree pull --prefix lib/qm-dsp https://github.com/c4dm/qm-dsp.git master --squash
```

Using a submodule might also work, but I have no experience with that.

Open issue: How to apply any of our custom patches?

**Comment by daschuer** [comment]
I think we have a special situation here that we follow upstream master because we currently reintegrate Mixxx patches. If this is done we will switch back to a mode to follow stable releases, like we do with all other lib packages. 
Going to manual review process like we did before is appropriated I think. So nothing to change here IMHO.

**Comment by uklotzde** [comment]
While we still need to patch upstream the manual approach is justified. I agree.

LGTM.

**Comment by Be-ing** [comment]
> If we don't make any changes to this source, is there a way we can set up our GitHub repo to auto-mirror upstream so that every Master build has the latest upstream libraries?

This could easily backfire when an upstream change breaks something automatically. It would be hard for anyone to figure what caused the break in that situation because it was done automatically.

**Pull request merged**
