### PR TITLE
fix ANGLE OpenGL issues on Windows

### PR DESCRIPTION
**Pull request by Be-ing**
This is #3367 with a fixed CMakeLists.txt that actually installs the ANGLE DLLs. I confirmed it works by testing the artifact in my Windows VM.

### CODE REVIEW

**Comment by Be-ing** [comment]
@JoergAtGithub can you test the [artifact from the build on my fork](https://github.com/Be-ing/mixxx/actions/runs/383756451) to confirm the issues are fixed?

**Comment by Be-ing** [comment]
Waveform preferences in my Windows VM:
image

**Comment by JoergAtGithub** [comment]
> 
> 
> @JoergAtGithub can you test the [artifact from the build on my fork](https://github.com/Be-ing/mixxx/actions/runs/383756451) to confirm the issues are fixed?

I confirm that the version from this artifact fixes the issues!

**Comment by daschuer** [comment]
Thank you, for fixing this. I have done just a bit single stepping and I am not clear how this ever works without. 
I am glad this fixed now maybe some other GL issues are fixed in turn.

**Comment by ronso0** [comment]
Just a side note:
I tested with skins prior to #3144 and on Linux it doesn't fix the skin crashes caused by waveform/spinny gl issues :(

**Pull request merged**
