### PR TITLE
Add range display for tempo slider

### PR DESCRIPTION
**Pull request by Holzhaus**
A rebased and fixed version of #2942 by @katsar0v.

### CODE REVIEW

**Comment by ronso0** [comment]
Didn't check the fixes, yet, but do you really intend to merge it into 2.3?
If so it would be a LateNight-only feature. I'd be okay with that.

**Comment by Holzhaus** [comment]
Hmm, I'm fine with merging it into 2.3 as LateNight only. It's pretty useful for controllers that allow switching the rate range on the fly. But I don't insist. There are no conflicts, so we can simply switch the base branch to `main` if we want to.

**Comment by ronso0** [comment]
alright, let's put it in 2.3. I was just wondering if that was by mistake because #2942 was started for main.

**Comment by Be-ing** [comment]
I'm wary of including a new feature in 2.3 at the last minute. I'd prefer to wait until this is implemented in every skin before releasing it.

**Comment by ronso0** [comment]
@Be-ing I think it's okay to have it in LateNight only for now because compared to the other skins it's a bit advanced now anyway (full/medium/mini decks). Besides, we don't have equal feature sets in all skins, like split/parallel waves in Deere, or the wave toggle in Tango & LateNight.

@Holzhaus
The rate scale was blurred (I remember I fixed that already elsewhere..)
fixed with 01bc84862c

> > * when the slider handle is at max/min it overlaps rate range number
> 
> Then you can still look at the other end of the slider. Both numbers are always the same, right?

I think yo were right, also the current rate is shown below the BPM. I think those range labels are only needed once in a while to verify/control the rate range.
And I'd like to push the numbers a bit to the left (and crop the first/last stroke) so the slider is centered and range numbers don't touch the rate buttons.

**Comment by ronso0** [comment]
> fixed with 01bc848

conflicts with your last commit, will check.
i don't think we should make the range label that small

~~btw why `LateNight: Increase WRateRange width to make "100" fit`? How do you set 100%, it's not available in the preferences.~~
okay, I see https://manual.mixxx.org/2.3/en/chapters/advanced_topics.html#control-[ChannelN]-rateRange

**Comment by Holzhaus** [comment]
I added the labels to deere, too. I failed to add it to Tango (for some reason they don't show up). Didn't try shade yet, but I agree with @ronso0 regarding feature parity.

@ronso0 there were a lot of merge conflicts in the SVG files and didn't want them by hand, so I just used `git checkout --theirs res/skins/LateNight`.

**Comment by ronso0** [comment]
> fixed with 01bc848
> @ronso0 there were a lot of merge conflicts in the SVG files and didn't want them by hand, so I just used git checkout --theirs res/skins/LateNight.

I didn't edit the SVG files in https://github.com/mixxxdj/mixxx/commit/01bc84862c2e432fc555a9c3421670ea99f1cd93, just the size and positions.

hmmkay, you were too quick ; ) I already re-applied some tweaks on top of your latest LateNight commit https://github.com/mixxxdj/mixxx/commit/60616e9cc819d7fc1824752695bdee93af15c950 and I hope this works flawlessly now:
c2550a27f19977932f621f72ef2a7fa32c227e1e unblur rate slider, adjust fonts (+- are a bit bigger)
fb3902b50fe90f6555c13d154a86a0c45d217f76 singletons, reduce memory usage and maintenance effort

image

I'll take a look at Tango tomorrow

**Comment by ronso0** [comment]
> I failed to add it to Tango (for some reason they don't show up)

the pitch slider has a bg color, you need to style the stacked slider/rate display container instead:
image

**Comment by ronso0** [comment]
In Shade all controls in deck.xml are positioned in absolute mode with `<Pos>`, pretty much like the rate range widgets in LateNight. Just make sure to put them [_**before**_ the rate slider](https://github.com/mixxxdj/mixxx/blob/2.3/res/skins/Shade/deck.xml#L518-L530) so the are _**underneath**_ and don't block mouse interaction (exactly the opposite as in stacked layouts : )
Labels should also fit easily I think.

**Comment by Holzhaus** [comment]
> In Shade all controls in deck.xml are positioned in absolute mode with `<Pos>`, pretty much like the rate range widgets in LateNight. Just make sure to put them [_**before**_ the rate slider](https://github.com/mixxxdj/mixxx/blob/2.3/res/skins/Shade/deck.xml#L518-L530) so the are _**underneath**_ and don't block mouse interaction (exactly the opposite as in stacked layouts : )
> Labels should also fit easily I think.

Done. For some reason they disappear when the mixxx window loses focus though:
Peek 2021-03-12 12-58

**Comment by Holzhaus** [comment]
> I'd prefer to wait until this is implemented in every skin before releasing it.

It's now present in all skins.

**Comment by ronso0** [comment]
> > In Shade ...
> 
> Done. For some reason they disappear when the mixxx window loses focus though:

Works here. And no idea how we'd fix it.
maybe it's just setup. Mixxx tooltips appear to be translucent even thoug they have a solid qss color.

**Comment by ronso0** [comment]
Great, it also looks good in Tango. Thanks for picking this up and finishing it!
One more graphic change from me 7de1dee070 make the strokes of pitch scale wider

In Shade / Dark the labels are invisible. Either you inline the font size in the the xml so it's transformed for each theme, or you add it to style-dark.qss, too. 
the external way to se it 7f345f91ec

LGTM when those are merged.
@Be-ing Any notes from you?

**Comment by Be-ing** [comment]
If it's in all skins, I'm okay with releasing it in 2.3.

**Comment by Holzhaus** [comment]
Great, thanks.

Now that the latenight scale is wider, I need to check how to make the rate text display in front of the scale, not behind it: Screenshot from 2021-03-12 23-16-12

**Comment by ronso0** [comment]
That would only be possible by detaching the slider bg from the WSliderComposed and putting it behind everything else.
I don't think that's worth it.
the first & last stroke are indented a bit
image
image
image

please test a2995dd8a0 and pick it if you like.

**Comment by Holzhaus** [comment]
> Great, thanks.
> 
> Now that the latenight scale is wider, I need to check how to make the rate text display in front of the scale, not behind it:
> Screenshot from 2021-03-12 23-16-12

@ronso0 Do we have a way to set `Qt::WA_TransparentForMouseEvents` or `Qt::WindowTransparentForInput` for the widget group? Because If I put the rate range group in front of the slider, you can't move the slider with the mouse anymore.

If there is not way to fix this, we either need to make the scale less wide or we just ignore the issue because values >90% aren't settable via UI anyway.

**Comment by ronso0** [comment]
> need to make the scale less wide

that's https://github.com/mixxxdj/mixxx/commit/a2995dd8a0c7dcfbe807108c8edf989ede4f0762

> set Qt::WA_TransparentForMouseEvents or Qt::WindowTransparentForInput for the widget group

That is an interesting solution I wasn't aware of. That would allow to enlarge the slider surface and ease click/touch interaction
If that works via `<TransparentForClicks>` it would be handy for all passive widgets like WLabel (and derivatives) and WStatuslight for example, so we'd need to implement it for wbasewidget (or wbasewidget).

**Comment by ronso0** [comment]
> via <TransparentForClicks> 

`setAttribute(Qt::WA_TransparentForMouseEvents, true);` works perfectly for Label and WidgetGroup (inheriting from parent would be nice), but unfortunately that approach fails as soon as the transparent group also contains a SingletonContainer (like RateRange in LateNight here).

**Comment by Holzhaus** [comment]
Okay, then I guess we are ready to merge now. Thanks for helping out with the skin  integration!

**Comment by ronso0** [comment]
> That would only be possible by detaching the slider bg from the WSliderComposed and putting it behind everything else.
> I don't think that's worth it.
> the first & last stroke are indented a bit
> image
> image
> image
> 
> please test [a2995dd](https://github.com/mixxxdj/mixxx/commit/a2995dd8a0c7dcfbe807108c8edf989ede4f0762) and pick it if you like.

**Comment by Holzhaus** [comment]
Already picked it. Thanks.

**Comment by ronso0** [comment]
alright, was wondering why that didn't show up _after_ my comment.

Great. Quick maneuver.

**Review by ronso0 — APPROVED** [review]

**Pull request merged**
