### PR TITLE
[READY FOR MERGE] Denon MC6000MK2: Updates/fixes/documentation

### PR DESCRIPTION
**Pull request by uklotzde**
- Documentation
  - http://www.mixxx.org/wiki/doku.php/denon_mc6000mk2
- Break effect
  - press Shift + Cue while playing
- BPM synchronized echo loop effect
  - ~~due to an open echo effect bug the delay is currently only 1/2 beat long~~
  - ~~https://bugs.launchpad.net/mixxx/+bug/1465269~~
- Various internal improvements and fixes

### CODE REVIEW

**Comment by daschuer** [comment]
I cannot test this. Is it safe to merge without any additional tests?

**Comment by uklotzde** [comment]
Testing is always a problem with mapping scripts. I've played around with it and will continue during the following days. Final live test is during the next weekend. I don't expect anything serious that couldn't be fixed very quickly.

Unfortunately I don't ever get any feedback from the forum. If anyone encounters a problem (s)he can still fetch a previous version from there.

I've created a documentation page for this slightly modified mapping in the wiki that now serves as THE reference.

**Comment by daschuer** [comment]
Should I merge this now?

**Comment by uklotzde** [comment]
Ahem, no ;) I just found an issue with the BPM synchronization of the echo effect. I will mark the PR as ON HOLD until I've fixed it.

**Comment by uklotzde** [comment]
No major issues found so far. Ready for merging.

**Comment by daschuer** [comment]
Thank you @uklotzde

**Pull request merged**
