### PR TITLE
More math refactor

### PR DESCRIPTION
**Pull request by Swiftb0y**
clang-format is weird on this unfortunately. So excuse the f'd-up formatting.

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Comment by daschuer** [comment]
Can you rebase out the failing commit before merge?

**Comment by Holzhaus** [comment]
Converted to draft to prevent accidental merge of the`fixup!` commit.

**Comment by Swiftb0y** [comment]
Ready. Manually verified each commit builds.

**Comment by daschuer** [comment]
Thank you

**Pull request merged**
