### PR TITLE
Skin fixes for 2.3

### PR DESCRIPTION
**Pull request by ronso0**
* LateNight PaleMoon: visualize fx flow and more small improvements, css clean up, documentation
image

* Tango: fx layout fix https://bugs.launchpad.net/mixxx/+bug/1919378
* Deere: push fx parameter buttons apart

### CODE REVIEW

**Comment by Holzhaus** [comment]
Thanks, the screenshot looks good. But I would look even better if the dark area around FX 1 and FX 3 were the same size. What do you think?

**Comment by ronso0** [comment]
sure it would.
I'd prefer to not make the expanded unit's label wider because it is the header for the controls below. 
making the collapsed unit label wider which would steal width from the effectselectors (I still have the minimum skin size in mind where the entire skin is a bit tight)

**Comment by ronso0** [comment]
so there's no real solution for polishing this spot, unless we ignore the condensed layout

**Comment by Holzhaus** [comment]
> so there's no real solution for polishing this spot, unless we ignore the condensed layout 

We could make mixing button a bit slimmer (currently it's wider than the PFL button). That would solve the issue and also look less crammed on small screens when the unit is collapsed.

**Comment by ronso0** [comment]
reason for the mixmode button being wide is that as square icon it looks too much like a Close button (D/W mode) and should resemble something like a crossfader mix curve. so I wouldn't want to change that.

we could move the Pfl button _below_ the mixmode, so when expanding an Fx unit the entire control section is flipped from an h-layout to a v-layout.

**Comment by Holzhaus** [comment]
Tango looks still broken for me:

tango-issue

**Comment by ronso0** [comment]
in your screencast is there space below the mic section?
anyways, I'll take a look

**Comment by Holzhaus** [comment]
Here's a new screencast that captures the whole window and shows all 3 skins.

Peek 2021-04-13 14-51

I also noticed that the padding in the effect selector in deere looks wrong, but that shouldn't block this PR.

**Comment by ronso0** [comment]
@Holzhaus if you find time, please check the effect selector again in Deere and Shade.
Also the Tango fx layout has a fixed height now.

**Review by Holzhaus — APPROVED** [review]
Thanks, I had a look at all skins and they look fine now.

**Comment by NotYourAverageAl** [comment]
@ronso0 this PR seems to have messed my window10 gui and effect names are cutoff. Though is looks fine on your screenshot

before
image

This PR
image

**Comment by ronso0** [comment]
okay, so there are actually people using LateNight
- @1280px (or FHD @150%)
- with super knobs
- and with focus shown while the fx unit is collapsed

I wlll adjust the minimal size, of course.

**Comment by Holzhaus** [comment]
@NotYourAverageAl it looks like the effect names were cutoff in the before screenshot, too?

**Comment by NotYourAverageAl** [comment]
@Holzhaus wrong choice of words meant the effect name box is now cutoff by the >

@ronso0 if you build it I'll find a way to break it :)

**Comment by ronso0** [comment]
@NotYourAverageAl fixed in #3788

**Pull request merged**
