### PR TITLE
fix high details waveforms wrapping around after visual index 65K

### LINKED ISSUE #13472: Waveform issues with "High details" enabled
### Bug Description

RGB high details waveform are showing an offset:
High details, the beat marker is not on the visual beat: 
image
No High details, the beat marker is at the expected position: 
image

Tested with QT 6.2

### Version

2.6~alpha

### OS

Ubuntu Focal

### PR DESCRIPTION
**Pull request by ywwg**
Fixes https://github.com/mixxxdj/mixxx/issues/13472

### CODE REVIEW

**Comment by ywwg** [comment]
hm, this crashes with large waveforms, needs more debugging

**Comment by ywwg** [comment]
(works now)

**Comment by Swiftb0y** [comment]
I don't think I'm the right person for this. I have not been involved in the stems code at all. wdyt @acolombier of this fix?

**Comment by ywwg** [comment]
yeah I wasn't able to tag @acolombier as a reviewer

**Comment by fwcd** [comment]
I just wanted to report this strange bug that high detail waveform wrap around at 2:28. My first thought was that my analyzed waveforms got corrupted or something 😄  Glad to know this is being handled

**Review by acolombier — APPROVED** [review]
Fix LGTM!

We might have to revisit that in the future, if we want to have custom rendering for stem, but it will require more work anyway, so happy to go with that safe approach for now.

**Comment by JoergAtGithub** [comment]
@acolombier Thanks for your review! LGTM!

**Pull request merged**
