### PR TITLE
Re-enable property editing in wtracktableview for library-redesign [library-redesign]

### PR DESCRIPTION
**Pull request by LindyBalboa**

### CODE REVIEW

**Comment by LindyBalboa** [comment]
Seems the build failures were not due to the code, but setting up the build environment. Could someone take a look at the build output and restart it?

**Comment by daschuer** [comment]
Thank you for taking care of this.
The line was uncommented in this PR: jmigual#2
Unfortunately I cannot remember what was the reason.
Maybe it disabled keyboard navigation, because it eats key presses?
Could you verify this? If this is an issue we need a way around it.
(copied from https://github.com/daschuer/mixxx/pull/23)

**Comment by daschuer** [comment]
I do not notice any regression as well. So we can merge this after we have got your permission. 
LGTM

**Comment by daschuer** [comment]
Thank you!

**Pull request merged**
