### PR TITLE
fix audiotaperpot_test lp1810495

### PR DESCRIPTION
**Pull request by daschuer**
Attempt to fix https://bugs.launchpad.net/mixxx/+bug/1810495

### CODE REVIEW

**Comment by ferranpujolcamins** [comment]
LGTM

**Comment by daschuer** [comment]
This is the last 2.2.1 fix. @dvzrv can you confirm if this passes the test now archlinux?

**Comment by dvzrv** [comment]
I can confirm, that this fixes the test for me!
@daschuer thanks for the invested work!

**Comment by daschuer** [comment]
Great, so we can finally release 2.2.1

**Pull request merged**
