### PR TITLE
fix app/window icons

### PR DESCRIPTION
**Pull request by ronso0**
* fix regression introduced by 564df770565496172e81eb450f51b2d0dd5e3ee9, all dialogs (except warnings) now use the Mixxx icon
(not 100% sure I caught all, and I didn't figure why the icon is implicitely inherited, for example by the _Replace Hotcue Color_ dialog)
* make About dialog reachable via Alt+Tab by _not_ parenting it to MixxxMainWindow
(this was a bit annoying until now, i.e. when trying to jump back and forth between About Mixxx and web browser to report bugs)

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
The regression is in the 2.3.1 branch, shouldn't the fix go into 2.3.1 too?

**Comment by ronso0** [comment]
I read this
image
while #4204 actually went into 2.3

will rebase.

**Comment by ronso0** [comment]
what's left to do @Be-ing ?

**Comment by uklotzde** [comment]
I will perform a test and then merge. Sorry for the delay.

**Comment by uklotzde** [comment]
I guess this cannot be tested properly without creating an installer and actually installing the broken, current version. But the changes seem reasonable.

@Be-ing Merge?

**Comment by Be-ing** [comment]
thanks

**Pull request merged**
