### PR TITLE
2.3 string update

### PR DESCRIPTION
**Pull request by esbrandt**
This updates the application translation template, and adds the latest available translations from Transifex.

My attempt to update to the latest available translations for the [WIX Windows installer ](https://github.com/mixxxdj/mixxx/blob/master/build/wix/Localization/README-Translations.md )was not successful, since there seems to be an error with the ``po2wxl`` script.
Maybe someone can share some insight.

```bash
for i in po/*.po; do destfile=${i#po/}; ./po2wxl.py -l Language -f -p 1 $i mixxx_${destfile%.po}.wxl; done
Traceback (most recent call last):
  File "./po2wxl.py", line 116, in <module>
    cultureShort = culture[:culture.index('-')]
ValueError: substring not found
Traceback (most recent call last):
  File "./po2wxl.py", line 116, in <module>
    cultureShort = culture[:culture.index('-')]
ValueError: substring not found
```

Version installed:
```bash
$ brew info python
python: stable 3.7.7 (bottled), HEAD
```

_Note_: On Transifex, the [available languages page](https://www.transifex.com/mixxx-dj-software/mixxxdj/languages/) has been uncluttered. Over 30 (mostly exotic) languages and dialects were deleted, that had no translators, and 0% translation progress. This was just noise.

Translators in one of the deleted languages can always add them back by demand.

### CODE REVIEW

**Comment by Holzhaus** [comment]
```python
cultureShort = culture[:culture.index('-')]
```

This won't work if `culture` does not contain that character.

I suggest using this instead:

```python
cultureShort, sep, region = culture.partition('-')
```

- For `de-DE` this will set `cultureShort` to `de`, `sep` to `-` and `region` to `DE`.
- For `de` this will set `cultureShort` to `de` and both `sep` and `region` to empty string.
- For `string with-multiple-dashes` it will set `cultureShort` to `string with`, `sep` to `-` and `region` to `multiple-dashes`.

**Comment by esbrandt** [comment]
Thanks for the hint.
Indeed, the script chokes on the Breton ``br.po`` language, which is not part of the [lcid.py](https://github.com/sblaisot/wxl-po-tools/blob/master/lcid.py), but has a valid LCID according to [ specs](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid).

``po2xml.py`` works in its current form after editing ``lcid.py`` locally.
```python
'br': {'locale': "Breton", 'language': "br", 'LCID': 126, 'codepage': 1252},
'br-FR': {'locale': "Breton - France", 'language': "br-FR", 'LCID': 1150, 'codepage': 1252},
```

For now there is nothing to do, since ``br.po`` has not changed since lost commit.

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Comment by daschuer** [comment]
I think the Duplicate Chinese language issue from 
https://bugs.launchpad.net/mixxx/+bug/1837663
is still pending. 
What is the best way forward? 
Do we know a native Chinese we can ask?

**Pull request merged**
