### PR TITLE
Effect parameter label: set hand cursor to make dragability more discoverable

### PR DESCRIPTION
**Pull request by ronso0**

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you, it works as proposed. The CI failure is unrelated. 

While I am not against merging this, I am unsure if this is actually an improvement. The rare "sorting the parameter use case" is now very prominent.
Following the "open hand" = grag-able we need to do much more for consistency. 
On the other hand having the "open hand" in the whole library table for instance would feel unusual.   
Dragging the Deck Title label is also such a hidden feature. 

Here on Ubuntu Focal, it is already the closed hand, shown during dragging.  

What do others think?

**Comment by daschuer** [comment]
I am still unsure about this. Can anyone else test this and share the opinion?

**Comment by ronso0** [comment]
Just an idea regarding discoverability and maybe "What's new?", dunno if that's overkill:
we could show the hand cursor to make some action discoverable, and when one d'n'd operation succeeded we assume the user learned that, and set a flag to not apply the hand cursor anymore from now on. This could be per context (deck, fx params, ...)

Note I won't fight for this being merged, but IMO it's the best option atm to make this new feature visible. Very few users seem to read the manual, I bet even those won't read it again after an update. So we should add that to the manual, but I doubt it helps much. Squeezing this into every parameter tooltip seems overkill, but maybe we should do that instead, idk.

**Comment by ronso0** [comment]
> Later during performace, the mouse pointer will pointlessly move the shape when trying to adjust the parameter knob. This might be a visual distraction.

I understand the distraction aspect, but the pointer will only change if you hover the parameter _name_.

**Comment by daschuer** [comment]
Can you rebase this on master. I think this should fix the Qt 6.3 build.
@Swiftb0y Do you like the hand solution? Merge or not?

**Comment by Swiftb0y** [comment]
IMO this is an improvement, though I'm confused why you are asking for my opinion on this particular feature.

**Comment by daschuer** [comment]
> IMO this is an improvement, though I'm confused why you are asking for my opinion on this particular feature.

Thank you for confirming. I was just looking for a second unbiased opinion.

**Pull request merged**
