### PR TITLE
Fix setting the wrong default cue color.

### PR DESCRIPTION
**Pull request by daschuer**
This PR fixes also the issue that cues are shown with wrong default for a split of a second.

Fixes https://github.com/mixxxdj/mixxx/issues/11260

### CODE REVIEW

**Review by Swiftb0y — CHANGES_REQUESTED** [review]
put my review suggestions into a PR: https://github.com/daschuer/mixxx/pull/85

**Review by Swiftb0y — APPROVED** [review]
LGTM. I appreciate the team work. Should we merge or do we need a 3rd pair of eyes?

**Comment by daschuer** [comment]
I think we it is OK to just merge in cases like this.

**Comment by daschuer** [comment]
Thank you :-)

**Pull request merged**
