### PR TITLE
Hotplug for HID devices

### PR DESCRIPTION
**Pull request by hile**
This patch implements basic hotplug support for HID devices, and stub code for all other devices where backend does not yet support hotplug: if any other backend can actually rescan, add and remove devices this patch allows easy hotplug implementation for other device types as well. Unfortunately for example portmidi has no concept of hotplugging devices.

Please note there seems to be a memory leak with hotplugging HID devices on OS X, which I have not seen  with this patch + updated hidapi I use personally: it doesn't look like the bug is in this code but in hidapi.

I suggest someone else tests this patch with latest hidapi version as well, and we should likely pull latest hidapi fixes for 1.12 anyway. I did not include these in this patch to make the commit easier to read.

### CODE REVIEW

**Comment by Be-ing** [comment]
@hile , could you fix merge conflicts so this can be included in 2.1?

**Comment by Pegasus-RPG** [comment]
@hile are you still interested and able to work on this?

**Comment by Be-ing** [comment]
Why? #1308 will take care of this.

**Comment by Be-ing** [comment]
This pull request has not been updated in years so I am closing it to reduce the clutter of open PRs. If you fix the merge conflicts and would like to propose it for merging in the future, please reopen it.

**Pull request closed without merging**
