### PR TITLE
remove hack to work around waveform initialization bug on Windows 

### PR DESCRIPTION
**Pull request by Be-ing**
Hopefully this is no longer necessary now that the OpenGL waveform renderers are initialized correctly.

This PR is on top of #3407

### CODE REVIEW

**Comment by Be-ing** [comment]
@JoergAtGithub can you test this? Set the waveform type to an OpenGL type then restart Mixxx. Check if the waveform is rendered correctly on startup.

**Comment by Be-ing** [comment]
@ NotYourAverageAl can you test this?

**Comment by NotYourAverageAl** [comment]
Sure can, looks like the github build is in progress. I'll wait for that and test.

**Comment by NotYourAverageAl** [comment]
Weird results. Tested on two different laptops
1. Windows 10, Core i7, integrated gpu - waveforms do not initialise on startup. The do after a setting change.
2.a Windows 10 Core i5, integrated gpu - waveforms initialise on startup
  b Window 10 Core i5, Nvidia 840M - waveforms initialise but GUI is unbearably slow

**Comment by Be-ing** [comment]
Thank you for testing. I guess we will keep the hack then.

**Comment by JoergAtGithub** [comment]
I tested this PR too, with Windows7 and integrated Intel GPU. With native Intel OpenGL driver and ANGLE.
I also saw, the behavior of case 1: After startup there were no waveforms, but after changeing the waveform type in the preferences, they worked flawless.

**Pull request closed without merging**
