### PR TITLE
Add mapping for DJControl Starlight

### PR DESCRIPTION
**Pull request by kerrickstaley**
Add mapping for DJControl Starlight controller.

The original version was done by DJ Phatso, I touched up the code and added some features/tweaks (see forum thread https://www.mixxx.org/forums/viewtopic.php?f=7&t=12570&sid=a6efb78f13c1d2b7ce559e78de306be5).

### CODE REVIEW

**Comment by kerrickstaley** [comment]
What's the best way to get rid of the unused variable warnings from CodeFactor?

**Comment by kerrickstaley** [comment]
@daschuer this code is ready for review, could you or another Mixxx maintainer review it?

Also, how do you recommend I address the "unused variable" warnings in CodeFactor? These warnings are for function parameters that I'm not using. Is there some annotation I can add to silence the warnings?

**Comment by daschuer** [comment]
Sorry I am not a js expert. Hopfully one else find time to review this soon. 

You can use 
```
/*eslint no-unused-vars: ["error", {"args": "after-used"}]*/
DJCStarlight.scratchWheel = function(channel, control, value, status, group) {
```
But I would prefer a tool independent solution. Does this work: 

DJCStarlight.scratchWheel = function(channel, control, value, status, group) {
status = status
} 

We need something that is not executed but satisfies Eslint.

**Comment by ywwg** [comment]
The usual fix for this situation is to put _ in place of unused variables, like this:

`DJCStarlight.scratchWheel = function(_, _, _, status, _) {`

**Comment by ywwg** [comment]
or maybe

`DJCStarlight.scratchWheel = function(_channel, _control, _value, status, _group) {`

is preferred

**Comment by kerrickstaley** [comment]
I fixed the unused variables warning (by disabling that check for the file; eslint doesn't seem to provide a nicer way to do this other than repeatedly disabling and disabling the check, which adds a lot of noise). Please review when you have time!

**Comment by kerrickstaley** [comment]
The Codacy linter is giving several false positives like
```
The numeric literal '0x91' will have at different value at runtime.
```
This is a known issue ([here is the issue on GitHub](https://github.com/pmd/pmd/issues/861)) with older versions of the PMD linter library that Codacy uses. They use PMD 5.0.0, and the issue was fixed in [the PMD 6.5.0 release](https://github.com/pmd/pmd/releases/tag/pmd_releases%2F6.5.0) about 10 months ago.

We can fix this issue by changing the hex literals to decimal literals, but I think that would make the code less readable. I'll look into how we can disable this check for the file.

**Comment by kerrickstaley** [comment]
@uklotzde this is now ready for review, can you assign a reviewer?

Codefactor upgraded their version of PMD so now there are no CodeFactor issues.

**Comment by uklotzde** [comment]
@DJPhatso Any comments on this PR? You might be able to test the mapping.

@kerrickstaley Has the [wiki page](https://mixxx.org/wiki/doku.php/hercules_dj_control_starlight) been updated according to this PR?

If the mapping works as documented and if there are no obvious coding issues we can merge it. I'm neither a JS nor mapping wizard so someone else might chime in.

**Comment by DJPhatso** [comment]
@uklotzde  Sure, I can test out the updated version. Where/how to I get the files? (Sorry, nooby here...)

**Comment by uklotzde** [comment]
@DJPhatso Direct GitHub links for download: [XML](https://raw.githubusercontent.com/kerrickstaley/mixxx/add-djcontrol-starlight-mapping/res/controllers/Hercules%20DJControl%20Starlight.midi.xml) / [JS](https://raw.githubusercontent.com/kerrickstaley/mixxx/add-djcontrol-starlight-mapping/res/controllers/Hercules-DJControl-Starlight-scripts.js)

**Comment by DJPhatso** [comment]
First thing I noticed is that the issue with the Vinyl button @kerrickstaley had initially corrected seems to be back.

**Comment by kerrickstaley** [comment]
@DJPhatso I can't seem to reproduce the issue you're describing. On my setup with this .xml file and .js file, the `[Vinyl]` button is lit up when you start Mixxx, pressing it once disables vinyl mode and turns off the light, and pressing it again turns vinyl back on.

Can you double-check that there aren't any other .xml/.js files for the DJControl Starlight in your controllers folder? Also, can you describe the exact sequence of steps you did and what happened?

**Comment by DJPhatso** [comment]
@kerrickstaley  Can't reproduce it either. Might have been only on the first trial, but the controller folder was empty before copying the files. I even tried another computer this morning with a fresh install of Mixxx and still no luck.

I just loaded a song and tried to scratch and it didn't start until lifted my finger and tried again so it reminded me of the original issue, but thinking back on it now, I'm wondering if it wasn't something with the jog touch instead.

**Comment by kerrickstaley** [comment]
@DJPhatso one thing I've noticed with this controller is that sometimes the jog wheels don't correctly register touches on the top surface (so you get a bend instead of a scratch). I think it's a hardware issue with my specific unit but may also be a problem that affects your unit. It's not related to the software since I see the same issue in Serato.

**Comment by DJPhatso** [comment]
@kerrickstaley Good to know. I'll keep an ear out and ask a few questions about that. I've had many during development and never encountered that issue, but not impossible that something could go wrong once in a while during production.

**Comment by uklotzde** [comment]
Ready to merge? Code is readable, Wiki page exists. LGTM.

**Comment by uklotzde** [comment]
LGTM, thank you! We still have the beta phase if any fixes are needed.

**Comment by reginaldojunior** [comment]
This is disponible what version?

**Comment by Holzhaus** [comment]
> This is disponible what version?

This mapping will be part of the 2.3 release.

**Pull request merged**
