### PR TITLE
CI: Remove "mixxx-" prefix from tag deploy path

### PR DESCRIPTION
**Pull request by Holzhaus**
For 2.3.0, I fixed the path manually after deployment.

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Comment by daschuer** [comment]
Do we need to change the version back to 2.3.1 beta first? I think there is no need, because we rely on git describe, right?

**Comment by Holzhaus** [comment]
> Do we need to change the version back to 2.3.1 beta first? I think there is no need, because we rely on git describe, right?

no, I think it's okay like this:
```
$ git describe
2.3.0-1-gc1ac577264
```

**Comment by Holzhaus** [comment]
I'll mark this as blocker for 2.3.1, renaming the files via ssh and editing the manifest is error prone ;-)

**Pull request merged**
