### PR TITLE
[WiP] Disabled vsync on MacOS

### PR DESCRIPTION
**Pull request by daschuer**
This might be the issue of the GUI performance issues.

### CODE REVIEW

**Comment by Be-ing** [comment]
If this turns out to be helpful I think we should merge it to 2.2 instead of master.

**Comment by ywwg** [comment]
who are our mac testers? :)

**Comment by esbrandt** [comment]
Thanks , unfortunately i can not confirm any noticeable performance improvements after applying the patch. Heavy GUI lag, waveform max@15fps, basically still as reported in https://bugs.launchpad.net/mixxx/+bug/1810099
My machine:
``Mac OS 10.14.3 (18D109)  2,6 GHz Intel Core i7  /Radeon Pro 560X 4096 MB / Intel UHD Graphics 630 1536 MB``

```bash
Debug [Main]: "Mixxx" "2.3.0-alpha-pre" "(git master r6783; built on: May  1 2019 @ 11:41:13; flags: asan=0 battery=1 buildtime=1 bulk=0 color=0 coreaudio=1 faad=0 ffmpeg=0 hid=1 hss1394=0 lilv=1 localecompare=0 macappstore=0 mad=0 mediafoundation=0 modplug=1 opengles=0 optimize=portable opus=1 perftools=0 perftools_profiler=0 profiling=0 qt_sqlite_plugin=0 qtkeychain=0 shoutcast=1 test=False tsan=0 ubsan=0 verbose=0 vinylcontrol=1 wv=0)" is starting...
Debug [Main]: Compile time library versions:
Debug [Main]: Qt: 5.12.2
Debug [Main]: libshout: 2.4.1
Debug [Main]: PortAudio: 1246720 PortAudio V19.6.0-devel, revision 396fe4b6699ae929d3a685b3ef8a7e97396139a4
Debug [Main]: RubberBand: 1.8.2
Debug [Main]: SoundTouch: 2.1.1
Debug [Main]: TagLib: 1.11.1
Debug [Main]: ChromaPrint: 1.4.3
Debug [Main]: Vorbis: Xiph.Org libVorbis 1.3.6
Debug [Main]: libsndfile: libsndfile-1.0.28
Debug [Main]: FLAC: 1.3.2
Debug [Main]: libmp3lame: 3.100
```

Attached a link to a deep copy of the stack, sorted by weight. Hope it is of any use debugging the issue. My impression is that most of the cpu time is spend flushing buffers.
https://gist.github.com/esbrandt/f820219674c7a35644073cad3966e023

**Comment by daschuer** [comment]
22.05 s 86.2% 0 s WaveformWidgetFactory::render()
...
22.04 s   86.2%	0 s	 	     QWidget::repaint(QRect const&)
22.04 s   86.2%	0 s	 	      0x10c0dae90
22.04 s   86.2%	0 s	 	       0x10c0da590
22.04 s   86.2%       0 s                   QCoreApplication::notifyInternal2(QObject*, QEvent*)

This is the intersting part. I cannot break on this call tree on Linux. 
What are 0x10c0dae90 and 0x10c0da590? Do you have debug info to look this addresses up? 

My second question is, do we still suffer tearing on Mac OS with this patch? Does this PR have any kind of regression? I would prefer to use the same glFormat settings on all platforms.

**Comment by daschuer** [comment]
By the way: Thank you for the test :-)

**Comment by rryan** [comment]
In my experience disabling this in the past, it made the waveforms
jerk/tear more. I can re-test this weekend.

**Comment by daschuer** [comment]
Thank you, Maybe this has changed since qt5

**Comment by uklotzde** [comment]
Marked as *[WiP]* because manual testing is required before merging.

**Comment by JoergAtGithub** [comment]
I think we can close this PR, since the macOS performance issues are solved in 2.4?

**Comment by daschuer** [comment]
Yes

**Pull request closed without merging**
