### PR TITLE
Devendor SoundTouch

### PR DESCRIPTION
**Pull request by Be-ing**
Why was this vendored in the first place?

### CODE REVIEW

**Comment by Be-ing** [comment]
I guess we don't have SoundTouch in the macOS build environment. Let's remove this after switching to vcpkg for macOS.

**Comment by daschuer** [comment]
> Why was this vendored in the first place?

It was added here: 
https://github.com/mixxxdj/mixxx/commit/de762984c15d94cfdc2d4e50077c6cea28a0c621#diff-a89f5eadda3bbc9d161a7eb01d641c4c2a2b31f534469553251d42ebf3b76632

I guess because it was not part of any distro at that time. 
We have continually updated it to a new version, because of important bug fixes not included in the latest bistro versions.

Now it is fine to remove it, because our minimum distro Ubuntu Groovy is has soundtouch 2.1.2 which is one minor release ahead of our internal version. Ubuntu Bionic for Mixxx 2.3 is at 1.9.2 which has assert() which is a bad idea. So we cannot remove soundtouch from the 2.3 tree.

**Comment by Holzhaus** [comment]
> Ubuntu Bionic for Mixxx 2.3 is at 1.9.2 which has assert() which is a bad idea.

They didn't build it with `NDEBUG`?

**Comment by daschuer** [comment]
I don't know. But that is not really relevant für this PR.

**Comment by Be-ing** [comment]
Oof, it turns out the vcpkg port of SoundTouch is awfully broken. It wasn't even installing the headers. Working on it...

**Comment by Be-ing** [comment]
Upstream PR to add a CMake build system to SoundTouch: https://gitlab.com/soundtouch/soundtouch/-/merge_requests/11

**Review by daschuer — APPROVED** [review]
Thank you.
LGTM

**Pull request merged**
