### PR TITLE
Pioneer xdj rx

### PR DESCRIPTION
**Pull request by norayr**
hello, would like to contribute my mappings to the hardware i use.
originally published at: https://github.com/norayr/xdj-rx-mixxx-mapping
created wiki page: https://github.com/mixxxdj/mixxx/wiki/Pioneer-XDJ-RX

### CODE REVIEW

**Comment by Holzhaus** [comment]
Please close this PR and update #3008 instead (e.g. using force-push). @Swiftb0y already left you some comments there.

**Comment by Swiftb0y** [comment]
Not sure if thats too late now. Afaik github doesn't let you force push to previously closed PR (even if it was reopened).

**Comment by norayr** [comment]
because you want changes in one commit?
i can fork mixxx again, and make a commit.

**Comment by Holzhaus** [comment]
I closed this and reopened #3008 as they are originating from the same branch anyway.

> because you want changes in one commit?

No, it's fine to make multiple commits.

> i can fork mixxx again, and make a commit.

No, that's not necessary. You only need to fork it once and then never again. If you want to edit/combine/reorder commits later, you can use interactive rebase. And Please not that the pull request is updated automatically each time you push to the branch, so you don't need to open new PRs each time you make a change.

**Pull request closed without merging**
