### PR TITLE
Library layout clean ups

### PR DESCRIPTION
**Pull request by 22degrees**
Not a bugfix but a bit love to the library section.
Reset the default margins to zero and make it more styleable via qss.
Some commits breaks the skins a little bit. But if required, I would fix it.

Please review.

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for the Pull request. I have just tested it and IMHO some changes are improvements others not. The Buttons are now stacked together which looks odd. Why is the change required?

**Comment by daschuer** [comment]
What happens if you apply a css margin? 
Can we add a default margin, that is overridable by css, without breaking existing skins?

**Comment by 22degrees** [comment]
Thanks for your feedback.

My personal opinion is:
- all skin elements have no margins, paddings or spacings by default
- the designer add these values as required via qss
- it is easier to set a value via css as to make time-consuming experiments to find the right property for an override

Sure, it is possible to reset the defaults via qss. You have already mentioned it.
But I didn't find any workable solution to override the layout Spacing in the LibrarySection with "qproperty-layoutSpacing: 0;" or the hardcoded spacer.

I agree that the existing skins look odd with these changes, but my skin looks great now ;) 
(screenshot attached) and the skins can be quickly fixed.

I make a fix for the existing skins in the next few days.

regards Hendrik

skin roundcorners

**Comment by 22degrees** [comment]
I think the existing skins are fixed and they look like before.
Attached you will find screenshots.
 
latenight

shade

deere

**Comment by daschuer** [comment]
Nice, thank you for the work. LGTM 

@esbrandt and others: Any other comments before merge?  

Before merge, you need to become a Mixxx contributor. 
Please sign: https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ
and comment here when done.

**Comment by 22degrees** [comment]
Thanks for review.
Agreement subscribed.

**Comment by daschuer** [comment]
I would like to add your real name to the contributor list in the AboutBox inside Mixxx. 
Is this OK for you?

**Comment by 22degrees** [comment]
That's ok!

**Comment by daschuer** [comment]
Done:
https://github.com/mixxxdj/mixxx/commit/1b1a5f0ab1e649be699899c8002cf94ff5b6ee58

**Pull request merged**
