### PR TITLE
Numark DJ2GO2 Touch: add missing loop_out mapping for the right deck

### LINKED ISSUE #11592: Numark DJ2GO2 Touch missing part of mapping for pad 2 in manual loop mode for the right deck
### Bug Description

When I try to make a manual loop with the right deck I can easily set the start marker (pad 1), but setting the end marker does not work at all. When I try to make a manual loop with the left deck everything works as expected with the default configuration profile.

I fiddled with the midi learning and narrowed the problem to a missing `<key>DJ2GO2Touch.rightDeck.loopOut.input</key>` section in the `Numark_DJ2GO2_Touch.midi.xml` file. The left deck two entries for loopOut, but the right deck has only one. Here's the diff:
```
747a748,756
>         <key>DJ2GO2Touch.rightDeck.loopOut.input</key>
>         <status>0x95</status>
>         <midino>0x22</midino>
>         <options>
>           <script-binding/>
>         </options>
>       </control>
>       <control>
>         <group>[Channel2]</group>
```

I've attached the fixed [full version](https://github.com/mixxxdj/mixxx/files/11569627/Numark_DJ2GO2_Touch.midi.xml.gz) of the file.

Should I make a pull request or discuss it here first?

BTW thanks for an awesome piece of software!

### Version

2.3.4

### OS

Arch Linux

### PR DESCRIPTION
**Pull request by r0d0dendr0n**
Added a missing section for the DJ2GO2Touch.rightDeck.loopOut.input key to the Numark DJ2GO2 Touch controller scheme.

### CODE REVIEW

**Comment by ronso0** [comment]
Thank you for this PR.
Please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

**Comment by ronso0** [comment]
Changes LGTM, based on the pattern for deck1.
Doesn't hurt though if anynone with the controller at hand would confirm this fixes #11592. @tandy-1000 @doteya @fjordstrom maybe?

**Comment by r0d0dendr0n** [comment]
> Thank you for this PR. Please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future. Please comment here when done. Thanks!

Done. I have signed the Mixxx Contributor Agreement via the provided link.

**Comment by ronso0** [comment]
Oh, I noticed just now this PR targets the main branch.
Mappings and related fixes are supposed to go into the stable branch 2.3 atm). I already changed the target branch here, hence the hundreds of 2.4/main commits. Please rebase onto 2.3 and force-push. Thank you.

**Pull request closed without merging**
