### PR TITLE
Tango: change name of skin menu "Extras" to "Misc"

### PR DESCRIPTION
**Pull request by nopeppermint**
as requested by @ronso0 in #1623
 > "Misc" would work for me. Could you change that in Tango/Deere as well?

### CODE REVIEW

**Comment by daschuer** [comment]
This does not strictly fit to a 2.1.1 release, because it is not important and change the interface. 
On the other hand I can see now drawback by now. Is this string already part of a manual or a tutorial video ...  
Both target branches work for me. 
What do others think?

**Comment by ronso0** [comment]
It's not important, it just makes the skin menus consistent.

Point releases are for urgent, functional bugfixes only?

**Comment by daschuer** [comment]
Point releases must not effect the manual, translations and user-interface. 
I am hesitating to merge this, because it is an interface change, but it has no harm.  just need a second voice that supports a merge to 2.1

**Comment by Be-ing** [comment]
I'm in favor of merging this to 2.1.

**Comment by daschuer** [comment]
Thank you. LGTM.

**Pull request merged**
