### PR TITLE
2.3 i18n updates

### PR DESCRIPTION
**Pull request by esbrandt**
This backports some fixes made in #3633  , updates the translation template, and incorporates the latest translations from Transifex.

### CODE REVIEW

**Comment by uklotzde** [comment]
Were you able to resolve the issues with the "English pluralized strings should contain 2 plurals" with the workaround that I mentioned in the Wiki?

**Comment by esbrandt** [comment]
Yes that worked.
Drawback: You'd have do do that every time a new pluralised string is added to the source. Now `lupdate` happily adds the required numbers of `<numerusform></numerusform>` to respective new strings itself.

Tested with
```bash
$ lupdate -version
lupdate version 5.15.2
```

**Comment by uklotzde** [comment]
> Yes that worked.
> Drawback: You'd have do do that every time a new pluralised string is added to the source. Now `lupdate` happily adds the required numbers of `<numerusform></numerusform>` to respective new strings itself.
> 
> Tested with
> 
> ```shell
> $ lupdate -version
> lupdate version 5.15.2
> ```

Does this mean we can delete those special instructions from the Wiki now?

**Comment by esbrandt** [comment]
These instructions are obsolete now.
I`ll go aheads and remove them post merge with a meaningful edit message, just in case someone looks for them in the history.

Have not seen yet that plurals really work for a translation though. While having translated them to German locally ,  i can not get any message to display when using the reset options in the track menu. Possibly there are simply too few tracks in this library.

**Comment by uklotzde** [comment]
Thank you! LGTM

**Comment by uklotzde** [comment]
When trying to merge 2.3 I noticed that de-DE has disappeared!?

**Comment by esbrandt** [comment]
> ~When trying to merge 2.3 I noticed that de-DE has disappeared!?~

Yeah, those languages keep coming back, see https://github.com/mixxxdj/mixxx/pull/1937/commits/cca53a9d9a6f4738f9750002bbd1e42e7af7f6af

There was once a faulty push, which created all languages available in our [lang_map](https://github.com/mixxxdj/mixxx/blob/main/.tx/config#L3). This stayed for quite a while on Transifex. People startet to translate some words in some Language/region combination and lost interest. Gets pulled from Transifex > duplicate entries with varying quality, see [lp:1837668](https://bugs.launchpad.net/mixxx/+bug/1837663), [lp:1888486](https://bugs.launchpad.net/mixxx/+bug/1888486), [lp:1825644](https://bugs.launchpad.net/mixxx/+bug/1825644), [lp:1887185](https://bugs.launchpad.net/mixxx/+bug/1887185
)

I tried to clean up on Transifex (delete unused languages, remove duplicate entries etc). but they come back.
We allow for our contributors to crate languages, we should only allow them to create by request. Once a language is created e.g. `de_DE` the translation memory filling up from the delete resource = going in circles.

The main issue is, that we can not change the source language for a resource on Transifex. You delete, and loose all associated translations. 

Back when we started, we did not know better. Correct would be `en_US` , not `en` as source language. Going fro m there `de_DE` instead and you so on... I see no other way then manually switching the available languages to ISO 3166-2 (lang_REGION)

**Comment by uklotzde** [comment]
I always struggle to understand how Travis works. Ideally I would expect that the regional variants are just partial translations that are used as an overlay. But even if they contain only partial modifications those could get out of date when their corresponding main translation changes. It should not be too difficult for Travis to track those changes and inconsistencies that require a review.

**Comment by esbrandt** [comment]
> Ideally I would expect that the regional variants are just partial translations that are used as an overlay.

AFAIK Transifex works not different from other tools with these regards.
They are treated as separate entities. And that can be the only way it works. There _can_ be quite substantial differences between region specific translations in languages.

**Pull request merged**
