### PR TITLE
Track menu: order BPM action by factor, show peview (for single track)

### PR DESCRIPTION
**Pull request by ronso0**
image

Should close #10128, though that also mentions a Tap  solution :shrug: 

No tranlation changes, can be merged any time.

### CODE REVIEW

**Review by daschuer — CHANGES_REQUESTED** [review]
The menu looks good. Unfortunately it no longer works for dynamic tempo tracks.

**Comment by ronso0** [comment]
Please explain what's not working anymore.
This PR does not touch the actual BPM slots, it uses the same BPM we see in the library and use in the 'Search Related Tracks' menu.

**Comment by daschuer** [comment]
When I click on "Halve BPM" nothing happens. Maybe this was broken before? I need to test.

**Comment by daschuer** [comment]
This seems to be an unrelated issue. I see the following console log when the beat action fails: 
`warning [Main] Marker with 5 beats till next marker cannot be scaled by 0.5`

**Review by daschuer — APPROVED** [review]
LGTM, please resolve the conflict. By merge or rebase as you like.

**Comment by daschuer** [comment]
https://github.com/mixxxdj/mixxx/issues/12743

**Comment by ronso0** [comment]
Done. Thanks for you review!

**Comment by ronso0** [comment]
Oh, rebase was a bit big, relevant diff is here https://github.com/mixxxdj/mixxx/compare/4446437609e2c1240a21db5e9b7f02f68da75151..548dfc79cf8f3be6b846d1aa479095f9a5c24877#diff-848ff12a6bbb8c39f28e2a6be33ca2bbbe31f53e6ba550b2f6df7b8bdfaecf1f

**Comment by daschuer** [comment]
Thank you

**Pull request merged**
