### PR TITLE
lp1840537: Enable (lib)modplug support on Linux by default

### PR DESCRIPTION
**Pull request by uklotzde**
https://bugs.launchpad.net/mixxx/+bug/1840537

What else needs to be done?

When merging to master we also need to update 2 different lines in default.nix!

### CODE REVIEW

**Comment by daschuer** [comment]
Builds and works on Ubuntu Xenial. Do you wish to edit default.nix as well or merge it now?

**Comment by uklotzde** [comment]
default.nix is only on master, I had to remove my changes temporarily for this PR ;)

**Comment by uklotzde** [comment]
Let's modify master after merging this one.

**Comment by daschuer** [comment]
Ok LGTM

**Comment by Be-ing** [comment]
This made the build server fail. libmodplug needs to be installed there:
https://builds.renegadetech.mixxx.org/job/v2.2/job/mixxx-2.2-release/architecture=amd64,platform=ubuntu/191/console

**Comment by uklotzde** [comment]
My assumption was that everything needed for the .deb build is in build/debian/control? What else is missing?

**Comment by uklotzde** [comment]
Maybe this: buildserver/pbuilderrc EXTRAPACKAGES

**Pull request merged**
