### PR TITLE
Skins: scale context menus and table header with system and library font

### PR DESCRIPTION
**Pull request by ronso0**
with the recent scaling fixes in mind I took another look at this...and the solutions are rather obvious.

Now those scaled with the library font
- [x] sidebar icons (scaled in c++ using the library font metrics)
- [x] played checkbox & BPM lock (`em` size instead of `px`)
- [x] sidebar decoration (simply use vector images)
____
- [x] context menu checkboxes and expand arrows scale with the font (`em` size instead of `px`)
- [x] library sort arrows (`em` width instead of `px`)
(header, track menu, sidebar menu. set by the OS independent from Qt scale factor)

A few words on the assumptions those changes are based on: users _probably_
* customize the system font size so all regular texts are legible at regular eye--screen distance.
(that size is applied to the menubar, table header and all context menus, incl. decoration)
* scale the entire GUI when the fonts and controls are too small in a DJ situation = probably increased eye--screen distance (and the display is large enough to stretch the GUI..)
* scale the libary font only for  increased eye--screen distance. This could happen independently from system font size affecting the context menus, because for using those the user would get closer to the screen.

### CODE REVIEW

**Comment by ronso0** [comment]
intermediate result:

before
image


this PR
image

**Comment by ronso0** [comment]
Woohoo, done!

Now all context menus and the track table header should be scaled perfectly fine, no matter which library font or system font (size) is set. (Note there may still be issues with artistic fonts that use non-standard font size/line height ratios)

**Comment by ronso0** [comment]
image

**Comment by ronso0** [comment]
the previous and the following screenshots were taken with a huge system font (twice as tall as comfortable default for me) and an enlarged library font.

huge system font > table header, context menus
enlarged library font > font in all library widgets, all decoration and icons (sidebar, BPM, Played checkbox)

image
image
image

Here, the small icons and overlapping "Ctrl+A" are expected (dunno how to fix that, and it's subordinate)
image

**Comment by ronso0** [comment]
just noticed: unfortunately automatically adjusting the size of the BPM lock icon & Played checkbox with qss doesn't work under all circumstances. I'll trydo that in c++

**Comment by ronso0** [comment]
> just noticed: unfortunately automatically adjusting the size of the BPM lock icon & Played checkbox with qss doesn't work under all circumstances. I'll trydo that in c++

I got it to work for the BPM icon only, but icons are shifted up. 

Anyway, I don't see use cases where the library font is set **a)** much smaller than that of Mixxx buttons or **b)** more than like 200% bigger, because scaling Mixxx in general is much more reasonable if such sizes are required.

So the current state is nice improvement already -- please test and share screens if things look strange to you.

**Comment by ronso0** [comment]
works fine without regressions on
- [ ] Windows 10 with various combinations of app & font scaling
- [ ] Ubuntu20.04 with various combinations of Qt app scaling, Qt font scaling and system font scaling

**Comment by foss-** [comment]
Looking good on macOS. Tried all scaling options in System Preferences > Monitor.

contextual menu

mixxx main window

**Comment by ronso0** [comment]
@foss- Nice, thanks!
Do you mind sharing a screen of track menu > Crates submenu and of the header menu, too, please?

**Comment by foss-** [comment]
menubar
crates

**Comment by foss-** [comment]
track table header menu

**Comment by uklotzde** [comment]
So this is now ready to merge?

**Comment by ronso0** [comment]
Yes. Doesn't hurt though if someone on Linux with Qt 5.15 confirms there are no regressions in the context menus.

**Comment by Swiftb0y** [comment]
I tested with Qt 5.15 on a 1080x1920 screen with 200% scaling on Gnome 40
2.3:
image
image

this PR:
image
image

Unrelated issue (which is also evident in your screenshots): the library minimize/maximize buttons are still not vectorized it seems.

**Comment by daschuer** [comment]
It looks like we have an issue wit the Cue label with Qt 5.9. I am just checking if this is an issue form this PR.

**Comment by daschuer** [comment]
I have tested a bit and it is not related to the Qt Version, it relates to the used Skin. It is also no regression by this PR.
But here the results anyway:  

This is this PR (and plain 2.3) without scaling and Tango Skin:
grafik
This is the same with Shade: 
grafik
The intro start icon bigger in both versions the border in Tango makes it even more bigger. In LateNight Pale Moon it looks like this: 
grafik

Can we use the Pale Moon version for all?

**Review by daschuer — APPROVED** [review]
I can confirm that it works as desired on Ubuntu Bionic (QT 5.9)

**Comment by ronso0** [comment]
> Can we use the Pale Moon version for all?

the difference is only the `|` beam. That's missing in LateNight.
We can either remove it from all skins, or use capital i so that the markers match the icon of the intro/outro buttons.
I vs. |
image

> so that the markers match the icon of the intro/outro buttons

actually that may not be necessary since the waveform range is a clear indicator IMO

**Comment by ronso0** [comment]
Merge?

**Comment by ronso0** [comment]
Thanks @Swiftb0y 

> he library minimize/maximize buttons are still not vectorized it seems

I'll look into that, guess it's using `background-image`

**Comment by daschuer** [comment]
> actually that may not be necessary since the waveform range is a clear indicator IMO

Yes, the only question is how do new users know that this is the intro and not a loop. 

Since we are about to release, I vote for the PaleMoon version for all or just keep it as it is, in case there is more work involved an a regression risk.

**Comment by daschuer** [comment]
Thank you for this one!

**Review by daschuer — APPROVED** [review]

**Comment by ronso0** [comment]
> > actually that may not be necessary since the waveform range is a clear indicator IMO
> 
> Yes, the only question is how do new users know that this is the intro and not a loop.
> 
> Since we are about to release, I vote for the PaleMoon version for all or just keep it as it is, in case there is more work involved an a regression risk.

I mean we don't need I-beam prefix/suffix, the ramp icons suffice. and the color of the buttons matches that of the waveform markers and ranges.

**Comment by ronso0** [comment]
> I mean we don't need I-beam prefix/suffix, the ramp icons suffice. and the color of the buttons matches that of the waveform markers and ranges.

#3989

**Pull request merged**
