### PR TITLE
Pioneer-DDJ-SB2

### PR DESCRIPTION
**Pull request by dg3nec**
Old:  
Pioneer DDJ-SB2 controller #816
https://github.com/mixxxdj/mixxx/pull/816#issuecomment-166295645

### CODE REVIEW

**Comment by Be-ing** [comment]
Looks good to me! :+1: Thank you! I'm really glad Mixxx 2.0 will support this cheaper but capable controller. I'm sure many DJs will be grateful for this. :)

**Comment by dg3nec** [comment]
Uffff....... first one.
Now i transfer midi_for_light PR.

**Comment by rryan** [comment]
@dg3nec looks like you need to merge first -- could you run ```git merge origin/1.12```?

**Comment by dg3nec** [comment]
@rryan: Sorry, not realy know exactly whats to do.

**Comment by rryan** [comment]
No problem @dg3nec  I'll take it from here.

**Pull request merged**
