### PR TITLE
Add tests for isinf, isnan and denormal detection.

### PR DESCRIPTION
**Pull request by rryan**
I built with optimize=portable -- why do these tests pass on my OS X machine?

### CODE REVIEW

**Comment by rryan** [comment]
Uh, and even more troubling, the flush to zero doesn't seem to be working for me.

**Comment by rryan** [comment]
```
Note: Google Test filter = MathUtilTest.*
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from MathUtilTest
[ RUN      ] MathUtilTest.MathClampUnsafe
[       OK ] MathUtilTest.MathClampUnsafe (0 ms)
[ RUN      ] MathUtilTest.IsNaN
[       OK ] MathUtilTest.IsNaN (0 ms)
[ RUN      ] MathUtilTest.IsInf
[       OK ] MathUtilTest.IsInf (0 ms)
[ RUN      ] MathUtilTest.Denormal
src/test/mathutiltest.cpp:87: Failure
Value of: std::fpclassify(fDenormal) == FP_SUBNORMAL
  Actual: true
Expected: false
src/test/mathutiltest.cpp:88: Failure
Value of: std::fpclassify(dDenormal) == FP_SUBNORMAL
  Actual: true
Expected: false
[  FAILED  ] MathUtilTest.Denormal (1 ms)
[----------] 4 tests from MathUtilTest (1 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (1 ms total)
[  PASSED  ] 3 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] MathUtilTest.Denormal
```

**Comment by rryan** [comment]
Actually, adding zero checks the denormals are != to 0 before turning on FTZ and are equal to zero after, so maybe this is fine.

**Comment by rryan** [comment]
optimize=off
```
Note: Google Test filter = MathUtilTest.*
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from MathUtilTest
[ RUN      ] MathUtilTest.MathClampUnsafe
[       OK ] MathUtilTest.MathClampUnsafe (0 ms)
[ RUN      ] MathUtilTest.IsNaN
[       OK ] MathUtilTest.IsNaN (0 ms)
[ RUN      ] MathUtilTest.IsInf
[       OK ] MathUtilTest.IsInf (0 ms)
[ RUN      ] MathUtilTest.Denormal
[       OK ] MathUtilTest.Denormal (0 ms)
[----------] 4 tests from MathUtilTest (0 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (1 ms total)
[  PASSED  ] 4 tests.
```

**Comment by uklotzde** [comment]
Fedora 23, x86_64 (Sandy Bridge), optimize=native
[ RUN      ] MathUtilTest.MathClampUnsafe
[       OK ] MathUtilTest.MathClampUnsafe (0 ms)
[ RUN      ] MathUtilTest.IsNaN
src/test/mathutiltest.cpp:54: Failure
Value of: isnan(std::numeric_limits<float>::quiet_NaN())
  Actual: false
Expected: true
src/test/mathutiltest.cpp:58: Failure
Value of: isnan(std::numeric_limits<double>::quiet_NaN())
  Actual: false
Expected: true
[  FAILED  ] MathUtilTest.IsNaN (0 ms)
[ RUN      ] MathUtilTest.IsInf
src/test/mathutiltest.cpp:64: Failure
Value of: isinf(std::numeric_limits<float>::infinity())
  Actual: false
Expected: true
src/test/mathutiltest.cpp:68: Failure
Value of: isinf(std::numeric_limits<double>::infinity())
  Actual: false
Expected: true
[  FAILED  ] MathUtilTest.IsInf (0 ms)
[ RUN      ] MathUtilTest.Denormal
src/test/mathutiltest.cpp:88: Failure
Value of: std::fpclassify(fDenormal) == FP_SUBNORMAL
  Actual: true
Expected: false
src/test/mathutiltest.cpp:92: Failure
Value of: std::fpclassify(dDenormal) == FP_SUBNORMAL
  Actual: true
Expected: false
[  FAILED  ] MathUtilTest.Denormal (0 ms)
[----------] 4 tests from MathUtilTest (0 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] MathUtilTest.IsNaN
[  FAILED  ] MathUtilTest.IsInf
[  FAILED  ] MathUtilTest.Denormal

**Comment by daschuer** [comment]
Ubuntu Trusty optimize=portable

[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from MathUtilTest
[ RUN      ] MathUtilTest.MathClampUnsafe
[       OK ] MathUtilTest.MathClampUnsafe (0 ms)
[ RUN      ] MathUtilTest.IsNaN
[       OK ] MathUtilTest.IsNaN (0 ms)
[ RUN      ] MathUtilTest.IsInf
[       OK ] MathUtilTest.IsInf (0 ms)
[ RUN      ] MathUtilTest.Denormal
[       OK ] MathUtilTest.Denormal (0 ms)
[----------] 4 tests from MathUtilTest (0 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (1 ms total)
[  PASSED  ] 4 tests.

**Comment by daschuer** [comment]
Ubuntu Trusty optimize=off + -ffast-math for  src/test/mathutiltest.cpp  

Note: Google Test filter = MathUtilTest*
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from MathUtilTest
[ RUN      ] MathUtilTest.MathClampUnsafe
[       OK ] MathUtilTest.MathClampUnsafe (0 ms)
[ RUN      ] MathUtilTest.IsNaN
src/test/mathutiltest.cpp:54: Failure
Value of: isnan(std::numeric_limits<float>::quiet_NaN())
  Actual: false
Expected: true
src/test/mathutiltest.cpp:58: Failure
Value of: isnan(std::numeric_limits<double>::quiet_NaN())
  Actual: false
Expected: true
[  FAILED  ] MathUtilTest.IsNaN (1 ms)
[ RUN      ] MathUtilTest.IsInf
src/test/mathutiltest.cpp:64: Failure
Value of: isinf(std::numeric_limits<float>::infinity())
  Actual: false
Expected: true
src/test/mathutiltest.cpp:68: Failure
Value of: isinf(std::numeric_limits<double>::infinity())
  Actual: false
Expected: true
[  FAILED  ] MathUtilTest.IsInf (1 ms)
[ RUN      ] MathUtilTest.Denormal
src/test/mathutiltest.cpp:88: Failure
Value of: std::fpclassify(fDenormal) == FP_SUBNORMAL
  Actual: true
Expected: false
src/test/mathutiltest.cpp:92: Failure
Value of: std::fpclassify(dDenormal) == FP_SUBNORMAL
  Actual: true
Expected: false
[  FAILED  ] MathUtilTest.Denormal (1 ms)
[----------] 4 tests from MathUtilTest (4 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (5 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] MathUtilTest.IsNaN
[  FAILED  ] MathUtilTest.IsInf
[  FAILED  ] MathUtilTest.Denormal

**Comment by daschuer** [comment]
Ubuntu Trusty optimize=native + no -ffast-math for src/test/mathutiltest.cpp
Test succeeds again. 

Conclusion: It will work if we call the fpclassify functions via a wrapper in an unoptimized cpp module to prevent inlining.  

> Why does Denormal pass with optimize=off? Maybe compiler optimizations in the test module are messing with things.

FTZ and DTZ are hardware flags inside the CPU which works independently from compiler flags. 

I cannot find an official document how FTZ/DTZ are related, but from some forum threads I know there is a relation. Maybe it is like with using -ffast-math the compiler expects that the CPU denormal flags are set.  

Anyhow,  -ffast-math and FTZ/DTZ works nice im Mixxx 2.0.0 rc1. Lets fix the fpclassify functions and the issue is solved.

**Comment by daschuer** [comment]
strange, now I am on a different machine optimize=off:

Note: Google Test filter = MathUtilTest*
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from MathUtilTest
[ RUN      ] MathUtilTest.MathClampUnsafe
[       OK ] MathUtilTest.MathClampUnsafe (0 ms)
[ RUN      ] MathUtilTest.IsNaN
[       OK ] MathUtilTest.IsNaN (0 ms)
[ RUN      ] MathUtilTest.IsInf
[       OK ] MathUtilTest.IsInf (0 ms)
[ RUN      ] MathUtilTest.Denormal
src/test/mathutiltest.cpp:86: Failure
Value of: fDenormal
  Actual: 0
Expected: 0.0f
Which is: 0
src/test/mathutiltest.cpp:89: Failure
Value of: dDenormal
  Actual: 1.11254e-308
Expected: 0.0
Which is: 0
[  FAILED  ] MathUtilTest.Denormal (1 ms)
[----------] 4 tests from MathUtilTest (1 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (1 ms total)
[  PASSED  ] 3 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] MathUtilTest.Denormal

 1 FAILED TEST

**Comment by Pegasus-RPG** [comment]
(Guys, please edit your comments so that the test results have three back-ticks before and after them so they appear in fixed-width font.)

**Comment by rryan** [comment]
This is part of #803 now.

**Pull request closed without merging**
