### PR TITLE
fix(library): remove typo in user-facing string

### PR DESCRIPTION
**Pull request by Swiftb0y**
spotted while practicing just now. 
does this violate string freeze or can we just merge?

### CODE REVIEW

**Comment by ronso0** [comment]
I just tried to find out for which / how many languages this has been translated (and how : ) but the transifex GUI still gives me headaches.

IIUC updating the source would wipe the translations but there seems to be a way around it as I already noted in https://github.com/mixxxdj/mixxx/pull/12217#issuecomment-1780103472

___
Here's the intro to the new 'Update source' function added in July this year. it's available via Transifex User Interface (UI), Transifex API and Transifex Go CLI
https://community.transifex.com/t/introducing-enhanced-resource-updating-in-transifex/3503

Here the documentation for the 'new' CLI client:
https://github.com/transifex/cli#pushing-files-to-transifex
> `--keep-transations`: If present, translations of source strings with the same key whose content changes will not be discarded. This can also be set on a per-resource level in the configuration file.

**Comment by daschuer** [comment]
You can look it up form the Mixxx source tree by: 
`grep -R "Mark all tracks played)" -A1 | grep "<translation>"`

Result: 
```
mixxx_es_UY.ts-        <translation>Marcar todas las pistas reproducidas)</translation>
mixxx_es_AR.ts-        <translation>Marcar todas las pistas reproducidas)</translation>
mixxx_sl.ts-        <translation>Označi vse skladbe kot predvajane</translation>
mixxx_es_ES.ts-        <translation>Marcar todas las pistas reproducidas)</translation>
mixxx_es_MX.ts-        <translation>Marcar todas las pistas reproducidas)</translation>
mixxx_es.ts-        <translation>Marcar todas las pistas reproducidas)</translation>
mixxx_it.ts-        <translation>Segna tutte le tracce suonate)</translation>
mixxx_es_CO.ts-        <translation>Marcar todas las pistas reproducidas)</translation>
mixxx_es_CR.ts-        <translation>Marcar todas las pistas reproducidas)</translation>
mixxx_es_EC.ts-        <translation>Marcar todas las pistas reproducidas)</translation>
mixxx_es_419.ts-        <translation>Marcar todas las pistas reproducidas)</translation>
mixxx_ru.ts-        <translation>Отметить все треки как воспроизведённые)</translation>
mixxx_es_PA.ts-        <translation>Marcar todas las pistas reproducidas)</translation>
mixxx_cs.ts-        <translation>Označit všechny skladby jako přehrané)</translation>
```

**Comment by daschuer** [comment]
I think we need to either investigate how to keep the translations, or move it to main.

**Comment by ronso0** [comment]
Thanks for the shorthand, but I wanted to search up-to-date online sources, not the local ones.

And all translators adopted the trailing ')' XD
If that's the case for the tx online sources the we can safely merge the fix.
Or rather
* pull tx
* remove ')' from source and tx
* push tx

> I think we need to either investigate how to keep the translations

I'm not sure why you still overlook my hint to the 'Update source' function, seems to do exactly what we want (for #12217).

**Comment by daschuer** [comment]
I have already investigated these options a bit, but the documentation is to thin for being confident not messing up Transifex metadata. Do you have experiences with these? 
I will probably find some time to test and document the case like we have here. 

We need to 
* Replace the source string 
* keep existing translations 
* hint the translators to review the translation. 

This one is small enough to fix issues in the process.
So a good test object.

**Comment by Swiftb0y** [comment]
well, to KISS, lets merge to `main` for now?

**Comment by daschuer** [comment]
OK, I will try "--keep-transations" now. I am curious if this works because in the Qt case the source string and the key are the same.

**Comment by daschuer** [comment]
I get `flag provided but not defined: -keep-transations` with latest tx 1.6.10

**Comment by daschuer** [comment]
Of cause it is: `tx push --keep-translations --source` 
There is a typo in the Readme.

**Comment by daschuer** [comment]
Unfortunately `--keep-translations` does not work as assumed all translations are now gone. I restore them now manually, Including the removal of the closing brace.

**Comment by ronso0** [comment]
Okay, great. Thank you!
It worked out, the translations on transifex are unchanged.

Oh, and you already opened a PR fixing the typo :+1: 

So next time we tx pull we need to strip the trailing ')' for all
`grep -R "Mark all tracks played)" -A1 | grep "<translation>"`
Will you take care of it or shall I issue a PR?

Next item, same procedure #12217

**Comment by daschuer** [comment]
I have just restored the strings in the Transifex Web-UI. The old string was proposed with a 95% match. I am now pulling them in.

**Pull request merged**
