### PR TITLE
Pre commit python

### PR DESCRIPTION
**Pull request by daschuer**
It turns out the "language: python" are working only by luck. 
A python hook requires a python entry. That ensures that the same python version is used and not another one found at the path.  

Our use case of starting a system script is covered by "language: system"

This also pins the clang-format version and gets around the clang-format not found issue.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
All cheks make Pass on Windows with this PR, but it seems, that clang-format doesn't detect or correct anything.

**Comment by daschuer** [comment]
Did you to artificially introduce a formatting issue? 
I got:

```
clang-format.............................................................Failed
- hook id: clang-format
- files were modified by this hook

[INFO] First pass: Reformatting added/changed lines...
[INFO] Reformatting src/main.cpp [46-46, 66-66, 80-83]...
[INFO] Second pass: Breaking long added/changed lines...
[INFO] Reformatting src/main.cpp [46-46, 66-66]...
```

I also noticed that since 
https://github.com/mixxxdj/mixxx/commit/f1dce7699439b3129d498162c05e6cf915a5027c
we no longer have a length check for comments.

**Comment by JoergAtGithub** [comment]
After signifiantly destroying the formatting of a .cpp file I get this:
```
fix utf-8 byte order marker..............................................Passed
check for case conflicts.................................................Passed
check json...........................................(no files to check)Skipped
check for merge conflicts................................................Passed
check xml............................................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
fix end of files.........................................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.............................(no files to check)Skipped
don't commit to branch...................................................Passed
codespell................................................................Passed
eslint...............................................(no files to check)Skipped
clang-format.............................................................Passed
black................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
shellcheck...........................................(no files to check)Skipped
markdownlint-cli2....................................(no files to check)Skipped
Validate GitHub Workflows............................(no files to check)Skipped
prettier.............................................(no files to check)Skipped
qsscheck.............................................(no files to check)Skipped
changelog............................................(no files to check)Skipped
metainfo.............................................(no files to check)Skipped
[pr/11004 232c856183] Testcommit
 1 file changed, 3 insertions(+), 8 deletions(-)
```
and the .cpp file is commited unmodified.

**Comment by daschuer** [comment]
How did you run pre-commit? 
Does it work during an actual commit?

**Comment by daschuer** [comment]
Ah, it was a separator issue with / and \
@JoergAtGithub can you please retry.

**Comment by daschuer** [comment]
I have added some other couple of windows fixes. I think you can now use pre-commit on windows.
Please confirm.

**Comment by JoergAtGithub** [comment]
Now it works for me!

**Comment by daschuer** [comment]
Cool, thank you. Can you also confirm that pre-commit works now without disabling any check?

**Comment by JoergAtGithub** [comment]
Yes, nothing is disbabled!

**Comment by daschuer** [comment]
Thank you for confirming. Who can press merge? 
Note, that this PR just fixes the windows issue without changing any general workflow as proposed in #10972.

**Comment by ywwg** [comment]
This still fails on Ubuntu 22.04 but that version of python is known broken:

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /home/owen/.cache/pre-commit/repoujfceyzn/py_env-python3/bin/python>>
- expected version: 3.10.6.final.0

Check the log at /home/owen/.cache/pre-commit/pre-commit.log
```

using python 3.11, which has been my workaround, this works fine still

**Comment by daschuer** [comment]
Ok, it looks like the pre-commit issue is tracked here: 
https://github.com/pre-commit/pre-commit/issues/2299

The workaround using the python3.11 package has been confirmed or the patched python3.10 found here: 
https://launchpad.net/~deadsnakes/+archive/ubuntu/python3.10-jammy

**Comment by daschuer** [comment]
I have updated the wiki accordingly: 
https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking

**Comment by daschuer** [comment]
Ready for merge!

**Comment by ronso0** [comment]
Since no one familiar wit pre-commit finds time to take a look, I'll press merge now to move forward. Regressions we be fixed.
Changes seem reasonable from what I can tell and CI passes, though I'm curious how `ReflowComments: false` works out.

**Pull request merged**
