### PR TITLE
Keyboard sheet links

### PR DESCRIPTION
**Pull request by ronso0**
* make links clickable using the HREF object property
* fix links to Mixxx controls
* add link to complete hotkey list

Remember to update main after merging 2.3

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you, that is helpful. 

Do we want to remove the /en/ part so that the users are forwarded to the translated version?

**Comment by ronso0** [comment]
Jup, of course. Done.

**Review by Swiftb0y — APPROVED** [review]
LGTM

**Review by daschuer — APPROVED** [review]
Thank you.

**Pull request merged**
