### PR TITLE
Use static widgets for Main EQ

### PR DESCRIPTION
**Pull request by daschuer**
This adds 8 slider via the UI file. 
Please test if they look work normally with EQ "---" selected.

### CODE REVIEW

**Comment by ronso0** [comment]
> They seem to be strangely overlayed in the EQ mode

Yes, that's just a test with extra sliders that works only with no main EQ.

**Comment by daschuer** [comment]
That's interesting. The original EQ slider look also OK. Is this the empty column grid at start up? 
But Anyway. I will continue this route, as a band aid.

**Comment by daschuer** [comment]
Done!
@fwcd Now it should hopefully work at macOS without any glitches. Please verify. 
Thank you.

**Review by ronso0 — COMMENTED** [review]
Thank you, this works as before and code LGTM
Would be nice if you could update some comments, and rename `m_mainEQValues` to `m_mainEQValueLabels`.

**Comment by fwcd** [comment]
Seems to work pretty well

https://github.com/mixxxdj/mixxx/assets/30873659/2942dabc-6a45-4896-8302-4644b190470a

**Comment by fwcd** [comment]
Wait, you're targeting `main`, so this is likely a Qt 6 build (where it already worked). Did you intend to target 2.4?

**Comment by daschuer** [comment]
Oh thats unfortunately, in this case, we need to restest. The PR is on top of 2.4. 
Hopefully the work was not pointless.

**Comment by daschuer** [comment]
Done.

**Comment by fwcd** [comment]
On Qt 5 the UI feels glitchy again (the EQ works though)

https://github.com/mixxxdj/mixxx/assets/30873659/25ee2093-cdde-4ba0-b650-e0cb154281a4

**Comment by ronso0** [comment]
@fwcd So all the other preferences sliders work?
End-of-track, VC input boost and so on? They're all horizontal, that's the only difference now that the EQ sliders are static.
To confirm show/hide is irrelevant, could you put the first commit on top of 2.4 and test that?

**Comment by fwcd** [comment]
Don't have time to dig into this right now, sorry, but I can smoke-test a GH Actions build if you prepare a branch. Yes, all of the horizontal sliders look good and work well from what I can tell.

**Comment by daschuer** [comment]
You can find the first commit on top of 2.4 here: 
https://github.com/daschuer/mixxx/actions/runs/7762303438

**Comment by daschuer** [comment]
This is the very last regression PR. An anoying issue but no party stopper. Can we move it to 2.4.1?

**Comment by fwcd** [comment]
Personally I think we can, the EQ is (despite being glitchy) still functional and can also be turned off via the dropdown menu. I do not really use the main EQ though, so I'm probably the wrong person to ask.

**Comment by daschuer** [comment]
Ok, than let's not block on that. 

Did you find time to test the first commit on 2.4 found here: https://github.com/daschuer/mixxx/actions/runs/7762303438

**Comment by fwcd** [comment]
Same issue as the other 2.4 builds

**Comment by daschuer** [comment]
Mmm than this PR is pointless 😭

**Comment by fwcd** [comment]
This looks very similar to https://bugreports.qt.io/browse/QTBUG-98093

**Comment by fwcd** [comment]
Might have better luck backporting that Qt patch

**Pull request closed without merging**
