### PR TITLE
Delete obsolete -platform xcb args

### PR DESCRIPTION
**Pull request by uklotzde**
Enforcing Mixxx to use XWayland on Wayland now causes bugs like #11576.

I also don't experience any issue with the legacy GL/GLSL waveform shaders.

### CODE REVIEW

**Comment by uklotzde** [comment]
Otherwise I would need to manually patch this out.

**Review by Swiftb0y — APPROVED** [review]
Thank you. I forgot we decided to do this.

**Comment by Swiftb0y** [comment]
just fyi there is a small visual glitch with the (GL) waveform variants. My guess is that some blend setting or similar is wrong resulting in out-of-range values because the resulting waveforms look blown out onscreen but the screenshot produced by gnome looks entirely different. The difference probably comes from the GPU just clamping the values while the compositor (or whatever is responsible for screenshots) just ignores the integer part. 
RGB (GL) waveforms seemingly wrapped

In either case, nothing blocking this PR but we'll probably get reports of people being on the GL waveforms from 2.3 even though they should switch to the (all-shaders) anyways. I guess would be a valid reason to remove the GL waveforms altogether?

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Pull request merged**
