### PR TITLE
 Clear vs. Remove

### PR DESCRIPTION
**Pull request by daschuer**
Rearange track context menu to avoid ambigious clear and remove in translated versions, fixes https://bugs.launchpad.net/mixxx/+bug/1778797

new version: 
unbenannt

### CODE REVIEW

**Comment by daschuer** [comment]
This is the view in a crate. Remove removes the track from the crate. Remove is now in the crates and playlist region.

**Comment by Be-ing** [comment]
I see there is a problem here, but I don't think this is a great solution. The ellipsis looks redundant and out of place in the GUI. There already is an arrow in the context menu indicating there is a submenu to open.

I think this could be solved by adding more context to the "Remove" string and adding a translator tip for that string. Could we make it say "Remove from this playlist/crate" instead of just "Remove"?

**Comment by Be-ing** [comment]
"Remove" without any further context could be misunderstood as "delete from computer".

**Comment by Be-ing** [comment]
Looking at right click menus in GNOME Files and Firefox, it seems that the convention is that an ellipsis indicates that clicking the menu item will bring up another window that prompts for more user input. I do not see any ellipsis being used to indicate there is a submenu. The ">" icon at the right of the menu is enough to indicate there is a submenu.

**Comment by daschuer** [comment]
As explained, the ellipsis indicates that the string is incomplete, mainly to not think the track is cleared from the table. 
In English this is an unusual term for this so you probably cannot understand the issue.
Think of it if you have "Remove" and "Remove from Crate". If you find "Remove" first you will use this. The > is out of sight and even If I have stumbled over the issue once  I did it again and again. 
"Remove ...                       >" will help here a lot "..." is a place holder, showing that "..." is not "from Crate" 
If you have a better Idea to make clear that this does not remove the track I would be happy.

**Comment by Be-ing** [comment]
I'm not sure I fully understand the translation issue. Perhaps another German speaker has an idea for another solution that doesn't require adding an ellipsis?

**Comment by daschuer** [comment]
Why is the ellipsis such a big problem for you? It IMHO just works in all languages.

**Comment by daschuer** [comment]
Ok, so you are right, the ellipsis is used differently: 
https://stackoverflow.com/questions/637683/when-to-use-ellipsis-after-menu-items
What else can we do:
"Clear Data"

**Comment by ronso0** [comment]
The german translation conflict of remove/clear is really a tricky one..
Instead of "Clear Data" we could also use "Reset". What's reset will be clear once the submenu has opened.
So yes, to avoid further confusion we should use "Remove from playlist/crate" and "Clear Data" or "Reset (Data)"

**Comment by daschuer** [comment]
OK, now we have "Remove form Playlist" and "Remove from Crate"
and "Reset" instead of "Clear" 
Works nice ..

**Comment by Be-ing** [comment]
I like the new wording. To me "Hide from Library" feels out of place in the same menu section as "Add to Playlist" and "Crates". Can it be moved back down to the bottom section with "Open in File Browser" and "Properties"?

**Comment by Be-ing** [comment]
LGTM thanks for bringing this up. The "Clear" menu item felt a bit strange to me before but I didn't have any better ideas.

**Pull request merged**
