### PR TITLE
Release 2.2.2

### PR DESCRIPTION
**Pull request by uklotzde**
Tasks:
- [x] Update translations from Transifex (directly on branch 2.2)
- [x] Update translation templates (directly on branch 2.2)
- [x] Push updated translation templates to Transifex (finished by @daschuer, #2229)
- [x] Update version number
- [x] Update CHANGELOG
- [x] Update release date in CHANGELOG
- [x] Update Debian Changelog (ups, pushed on branch 2.2 instead of including it here)

After merge:
- [x] Check release package builds on the build server: https://builds.renegadetech.mixxx.org/job/v2.2/
- [ ] Manually test the build artefacts on all platforms -> [in progress](https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Release.202.2E2.2E2.20-.20Help.20needed/near/172832696)
- [ ] Tag release on Github

After release:
- [ ] Upload packages (???)
- [ ] Update the website -> *[in progress](https://github.com/mixxxdj/website/pull/57)*
- [ ] Launchpad Updates: https://launchpad.net/mixxx/+milestone/2.2.2
- [ ] Release announcement @ywwg 

See also: https://www.mixxx.org/wiki/doku.php/2.1.0_release_checklist

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for taking care of the 2.2.2 releas. This is really overdue.

Unfortunately I am cought in real live this week so I can't promise to help.

I recently suffered playlist order bug myself:
https://bugs.launchpad.net/mixxx/+bug/1829601 that's why it jumps on top of my personal priority list. But it is no blocker here.

**Comment by ywwg** [comment]
Thanks for working on this.  If there's a way I can help push out this release please let me know! (I'll do my usual social media advertising when it's done)

**Comment by daschuer** [comment]
see: https://github.com/mixxxdj/mixxx/pull/2229

**Comment by uklotzde** [comment]
Ok, ready. After merging this PR everything should be in place for releasing version 2.2.2.

I don't have an account for the build server and might need some help later to upload the release packages after the builds succeeded.

**Comment by uklotzde** [comment]
I will merge these changes now to continue with the check list.

**Comment by ywwg** [comment]
My login to the buildserver works so I should be able to help with that too

**Comment by uklotzde** [comment]
I'll post links to the release packages on Zulip when they are available to ask for feedback with a short check list (fresh or upgrade installation, version number, ...). Let's involve the community to proof that everyone is able to contribute.

**Pull request merged**
