### PR TITLE
Pioneer DDJ-ERGO:  added mappings

### PR DESCRIPTION
**Pull request by jssotomdz**
Followed the original mapping as close as possible here.

### CODE REVIEW

**Comment by jssotomdz** [comment]
Created manual merge request as well
https://github.com/mixxxdj/manual/pull/602

**Comment by JoergAtGithub** [comment]
Welcome at Mixxx!
As a first-time contributor we need you to sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

**Comment by jssotomdz** [comment]
> Welcome at Mixxx! As a first-time contributor we need you to sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

Done!

**Comment by JoergAtGithub** [comment]
The best way to fix pre-commit issues is to install pre-commit locally on your system, as described here: https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking
Than it will fix these issues automatically before every commit.
Alternatively, you can download the pre-commit.patch file from the artifacts of this PR
grafik
unzip it, and apply it using:
`git apply pre-commit.patch`

**Comment by jssotomdz** [comment]
> The best way to fix pre-commit issues is to install pre-commit locally on your system, as described here: https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking Than it will fix these issues automatically before every commit. Alternatively, you can download the pre-commit.patch file from the artifacts of this PR grafik unzip it, and apply it using: `git apply pre-commit.patch`

Thanks, applied them

**Comment by JoergAtGithub** [comment]
The code stale is applied now, the remaining eslint errors need to be fixed manually

**Comment by jssotomdz** [comment]
> The code stale is applied now, the remaining eslint errors need to be fixed manually

Unused parameters should be removed from function declaration? And the constants storing the callback connections should be dismissed and just call the methods without assigning them?

**Comment by JoergAtGithub** [comment]
Unused parameters are allowed, when they are named starting with an underscore. But if there is no reason to keep them, better delete them, than adding an underscore.
Storing the connections, make only sense, if you later use them for .trigger() or .disconnect().

**Comment by jssotomdz** [comment]
> Unused parameters are allowed, when they are named starting with an underscore. But if there is no reason to keep them, better delete them, than adding an underscore.
> Storing the connections, make only sense, if you later use them for .trigger() or .disconnect().

Fixed. It is kind of strange though. Sometimes status is marked as used even though it isn't referenced in the code. Is there some guidance over this? And for some reasons, Mixxx is complaining about expecting a `;` whenever I use `let` as a declaration. That is why I use `var` but then the action complains. How should I deal with those?

**Comment by jssotomdz** [comment]
sorry, messed up the PR. Will rebase and reopen

**Pull request closed without merging**
