### PR TITLE
Fix adopting hotcue button color

### LINKED ISSUE #12778: Hotcues: first time a UI button is clicked, it turns black
### Bug Description

As title really. The next button is clicked, the new one goes black and the last one goes the right colour. Delete a hotcue then remake and the colours ir correct. Using Deere-custom and original.

I guess related to https://github.com/mixxxdj/mixxx/pull/12733?

### Version

2.4-beta

### OS

_No response_

### PR DESCRIPTION
**Pull request by daschuer**
This fixes #12778

### CODE REVIEW

**Comment by ronso0** [comment]
This should go to 2.4

I don't understand why we didn't see this earlier. I did a lot of test for #12733

**Comment by ronso0** [comment]
I'd like to understand what exactly went wrong, but I don't have time atm.
@daschuer could you give a brief summary?

**Comment by daschuer** [comment]
Sorry, I have not tested you latest changes after my suggestions. They have introduced more checks regarding color changes via CO, like if the hotcue exists exists in slotHotcueColorChangeRequest()
When creating a new cue, the color and all properties are set before it is created, to avoid a glitch with a cue point with default values. This PR bypasses these checks in slotHotcueColorChangeRequest().

**Comment by ronso0** [comment]
Thank you, this fix LGTM.

However, I have a feeling we're working around flaws in CueControl.

FWIW the calls when setting a new hotcue are these (no guarantee for completeness):
```
hotcueSet
hotcueClear
  -> !pCue, return
trackCuesUpdated
loadCuesFromTrack
  -> hotcue 4
  -> pOldCue != pCue
attachCue
(detachCue)
setCue
  -> setColor #ff8000
  -> slotHotcueColorChangeRequest #ff8000
    -> !m_pCue, return
  -> set m_pCue
(detachCue for all cue controls)
attachCue
detachCue 4
resetCue 4
setCue
  -> setColor #ff8000
  -> slotHotcueColorChangeRequest #ff8000
    -> !m_pCue, return
  -> set m_pCue
setHotcueFocusIndex 3
setHotcueFocusIndex 3
setHotcueFocusIndex 3
```

**Pull request merged**
