### PR TITLE
LateNight Skin, moving Mixxx Logo

### PR DESCRIPTION
**Pull request by Russe**
Moving ToolbarLogo that there's less distraction between clock and CPU Load widgets.

### CODE REVIEW

**Comment by Swiftb0y** [comment]
Would you mind posting a picture before and after your changes?

**Comment by ronso0** [comment]
In the new place the logo is distracting IMO.
I'd go along with moving the logo to the far left, though.

FWIW with multi-core CPUs the CPU Load bar is not a reliable indicator anymore for buffer over/underruns.
I suggest you rather play as usual (pitch change, fx, 3 or 4 decks and maybe playing) and watch the underrun counter at the bottom of Preferences > Sound Hardware. If it's 0 (or close to zero and you don't hear any annoying audio glitches) you can lower the latency until you do see the counter increase. Then go back the previous value.

**Comment by ronso0** [comment]
For more info please read https://manual.mixxx.org/2.3/en/chapters/preferences.html?highlight=latency#audio-buffer
As well as https://github.com/mixxxdj/mixxx/wiki/Adjusting-Audio-Latency for latency optimisation.

**Comment by Russe** [comment]
> Would you mind posting a picture before and after your changes?

latenight-original
latenight-change

**Comment by Russe** [comment]
> In the new place the logo is distracting IMO. I'd go along with moving the logo to the far left, though.

Yes, I will add a screenshot first.

**Comment by Russe** [comment]
Thanks for information about latency.

**Comment by Russe** [comment]
Mixxx logo on the left side

latenight-change2

**Comment by ronso0** [comment]
Okay, I think this looks nice if there is more space at the left of the logo, like in between MAX LIBRARY and WAVEFORMS.

**Comment by Russe** [comment]
PaleMoon and Classic is a bit different, I used an empty WidgetGroup, and not the ToolbarSeparator with the dots at Classic Skin.

latenight-change3-palemoon
latenight-change3-classic

**Comment by JoergAtGithub** [comment]
IMHO the logo would look best where SETTINGS is now, maybe move settings to the other widget toggle buttons on the left?

**Comment by ronso0** [comment]
> IMHO the logo would look best where SETTINGS is now, maybe move settings to the other widget toggle buttons on the left?

That would require moving the cursor over half the screen to get to the menu. The point is to have the settings toggle close to the menu.

**Comment by Russe** [comment]
Here's a proposal with Mixxx logo in the right side, without moving the settings button.
I agree, the settings button should stay on the right side.

latenight-change5-palemoon
latenight-change5-classic

This version is my favourite.

**Comment by ywwg** [comment]
what about centered? :)

I do like the right-justified version too

**Comment by Russe** [comment]
I don't like the centered, that was my first attempt. Problem is, that it's centered within the white space, but not centered within the window with. So the logo will be displayed a bit to the right side of the window title.

I will update the code like in the last screenshot, so the logo will be on the right side.

**Comment by ronso0** [comment]
> I don't like the centered, that was my first attempt. Problem is, that it's centered within the white space,

Even though I think this is possible, I think we should not put the eye-catching logo in the center. It's distracting from all that already happens in the center column, mixer, pitch fader etc.

I do like the current proposal!
Please squash the commits, name it "LateNight: move logo to the right" and rebase onto mixxx/main.

**Comment by Russe** [comment]
Sorry, I got lost, this is my first contribution.
Could you explain where I can squash my commits? I'm working on github.com, and not with a git client.

I found something about in the docs:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request
But I can not see the merge or squash button.

**Comment by ronso0** [comment]
> I'm working on github.com, and not with a git client.

Okay, never mind. We will do that when merging. (only `mixxxdj` members see the merge options)

Since this is your first contribution we need you to sign the [contributor agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and thereby allow Mixxx to include your changes.
Thank you!

**Comment by ronso0** [comment]
Oh, and we need to update the preview screen for the preferences.
@ywwg when you approve the current state I can do that (I'd simply push pixels in Gimp)

**Comment by Russe** [comment]
OK, thanks.
I already signed the agreement, because I created the drawing of Traktor Kontrol Z2 controller and JoergAtGithub asked me to sign it.

If you want me I can update the screenshots/previews as well within this pull request, so please advise.

**Comment by ronso0** [comment]
Sure you can change the screenshots, too. In order to avoid creating a screenshot from scratch, just swap the buttons and the logo with an image editor so the look matches this PR, and try to keep the image quality (size) of the original if possible.
Note this needs to be done for both _skin_preview_Classic.png_ and _skin_preview_PaleMoon.png_
Thank you!

**Review by ronso0 — APPROVED** [review]

**Comment by Russe** [comment]
Just tested the installation on Ubuntu with the build deb-file from here. Everything looks as expected.
Is there anything I need to to do for this PR?
I don't want to rush you, just asking if something is missing from my side.

**Comment by ronso0** [comment]
No, nothing left to do, except waiting for the Okay! of another team member. Then we can squash and merge.

**Review by daschuer — APPROVED** [review]
LGTM Thank you.

**Pull request merged**
