### PR TITLE
update hidapi to 0.8.0-rc1

### PR DESCRIPTION
**Pull request by Be-ing**
douteiful reported on the mailing list that they had to update the version of hidapi that Mixxx is compiled with to get Mixxx to detect a Native Instruments Traktor Kontrol S2Mk2: http://sourceforge.net/p/mixxx/mailman/message/34488537/

This also fixes https://bugs.launchpad.net/mixxx/+bug/1502448 for me.

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for the pr. Nice to hear that this fixes a bug for you. Unfortunately this included a library that os already part of som Linux distribution. I would prefer to add this to our buildserver repo and remove it from the mixxx tree. 
@rryan @ywwg? What do you think?

**Comment by Be-ing** [comment]
When hidapi 0.8.0 is released and distros are packaging it, I think that would be a good idea. But Mixxx needs this release candidate version to function properly and I doubt distros are shipping it. Fedora still packages hidapi 0.7.0.

**Comment by Pegasus-RPG** [comment]
That's probably because 0.8.0 is still in RC status. I'll ask upstream what their release plans are.

**Comment by Be-ing** [comment]
Regardless, I don't think we should wait for distros to update to hidapi 0.8.0 whenever that comes out.

**Comment by ywwg** [comment]
Since we're already including a pre-release version of hidapi I feel like we might as well include a more up-to-date prerelease version rather than make a larger change.  But in general we should not be in the business of maintaining a distribution :).

Also, HID is still an experimental feature with a poor user experience, so I don't mind being a little more risky here.

**Comment by Be-ing** [comment]
When distros update to hidapi 0.8.0 they can also modify their Mixxx package to compile against the system version if they want.

**Comment by daschuer** [comment]
The situation is quite different as you assume.
From Ubuntu trusty hidapi 0.8 rc1 is part of the default distros. IMHO we should solve this issue by 
-removing hidapi from the mixxx repro. 
-add it to the Windows build
-change the homebrew script accordingly.
-add hidapi (only) to our Precise PPA

**Comment by Be-ing** [comment]
Ubuntu isn't the only distro that people use Mixxx with. I doubt many distros would be very comfortable updating their version of hidapi to a release candidate just to update Mixxx.

**Comment by daschuer** [comment]
The difference is that we provide binaries for Ubuntu only. It is in the responds of the user to add or remove a third party ppa. As usual for other apps, a ppa provides all packages for required to run the provided App. Apt and co makes sure that he can undo such actions without any pain. 

hidapi 0.8.0 rc1 is an default part of openSUSE 42.1 and available from openSUSE 13.1
Fedora 23 comes with hidapi 0.7.0, but there are 0.8.0 rc1packages available from Fedora 22
ArcLinux has hidapi 0.8.0 rc1 in the community repros.
So I seams no issue for the most common distros. 

So IMHO we will have no issues, if we let upstream Mixxx depend on 0.8.0 rc1. If a package maintainer decides to build a package with an older (broken) hidapi package, It is in his responds.

**Comment by rryan** [comment]
I think we're not in a rush to fix Bug 746346 and we are in a rush to release 2.0. So I don't want to add even more buildserver work to be done to split this out for 2.x. We can do this for 2.1.

**Comment by Pegasus-RPG** [comment]
@rryan then why did you merge this to the 1.12/2.0 branch?

**Comment by rryan** [comment]
> @rryan then why did you merge this to the 1.12/2.0 branch if you want to wait for 2.1 for it?

I think you misread the thread above -- I'm saying wait until 2.1 to solve lp:746346.

**Pull request merged**
