### PR TITLE
Reformat code to fix indentation

### PR DESCRIPTION
**Pull request by uklotzde**
The result of applying #2458

### CODE REVIEW

**Comment by Holzhaus** [comment]
If you prefer to indent switch case statements as well, we can also add `{ "SwitchCase": 1 }` to the `.eslintrc.json` file. The switch cases in the Roland DJ-505 controller script are indented, too.

**Comment by Holzhaus** [comment]
Btw, I updated the wiki and replaced instructions regarding jshint/jsbeautifier with eslint.

**Comment by uklotzde** [comment]
I have selected ESLint as the formatter in VS Code using our configuration.

**Comment by Holzhaus** [comment]
Ah OK, so there's manual work involved to use eslint for VSCode? I misinterpreted [your comment](https://github.com/mixxxdj/mixxx/pull/2442#issuecomment-575895392) then. Since VSCode is quite popular it might make sense to add the relevant config to the wiki?

In any case, would you rather prefer to merge this PR or change the indent settings for switch cases in `.eslintrc.json`? [`.clang-format` has `IndentCaseLabels` set to false](https://github.com/mixxxdj/mixxx/blob/master/.clang-format#L25), so the current eslint behavior is consistent with our formatting settings for C++ switch cases. That's OK to me, so feel free to merge this PR.

**Comment by uklotzde** [comment]
VS Code integration:
- Install required node_modules (the extension didn't work without this step!?)
- Install ESLint extension
- Select ESLint as default formatter (vs. MS TypeScript/JavaScript or Prettier extension)

**Comment by uklotzde** [comment]
The ESLint warnings are shown without any extra configuration. Only the formatter requires attention. Not sure if VS Code asked after installation of the extension.

**Comment by uklotzde** [comment]
@Holzhaus Let's keep the non-indented case labels here like we do for the C++ style. It's readable and reduces whitespace bloat.

**Pull request merged**
