### PR TITLE
Windows: Set CMAKE_BUILD_TYPE to support build from command line too

### PR DESCRIPTION
**Pull request by JoergAtGithub**
Based on #3977 
Set a default for the CMAKE_BUILD_TYPE. This is needed for Windows CMake builds called from command line only, which were not supported yet.
Builds started from VisualStudio take this setting from CMakeSettings.json as before, because the default is only applied, if CMAKE_BUILD_TYPE is not set before.

### CODE REVIEW

**Comment by Holzhaus** [comment]
Thanks. I think we should use the snipped from here: https://blog.kitware.com/cmake-and-the-default-build-type/

**Comment by Holzhaus** [comment]
I thought it defaulted to "Debug" if not set. I was wrong. I'll add this to my branch to get it merged faster.

**Comment by JoergAtGithub** [comment]
Yes, it defaults to "Debug", but we need "RelWithDebInfo"

**Comment by Holzhaus** [comment]
No, it defaults to empty string. I added a corresponding commit here: Holzhaus/mixxx@bc21d16945c07cc8c43c4676c154f1ab2f1e44bd

**Pull request closed without merging**
