### PR TITLE
WTrackTableView: keep selected tracks in view after sorting

### PR DESCRIPTION
**Pull request by ronso0**
[lp:1892942](https://bugs.launchpad.net/mixxx/+bug/1892942)
Appearantly `scrollTo()` is broken/unreliable, there's also a [comment](https://github.com/mixxxdj/mixxx/pull/3090/commits/3ec08c17fffdea1399ee07944a6f4cd6bc347d8a#diff-b4109738a7cfa72e329e8f5138e3caa4R181) about that in #3090 

Before restoring the previous seletion the first selection row is selected explicitely to set a starting point for navigation with Up/Down keys. (previously the selection was reset to the topmost row on key press)

In addition to plain selection restoration, the focused cell is also restored in order to keep the horizontal scroll position when navigating vertically.

### CODE REVIEW

**Comment by ronso0** [comment]
I wonder if we should have a utility function for restoring the previous selection. In a similiar way this is also required for [WLibraryTableView::focusInEvent](https://github.com/mixxxdj/mixxx/pull/3090/files#diff-b4109738a7cfa72e329e8f5138e3caa4R151)

Currently there are #3092 (this), #3090, #3063 and #2019 (stalled) that attempt to fix various table navigation and selection issues.

**Comment by JoergAtGithub** [comment]
I compiled this PR for Windows, but can't start it. I'm not sure if this is related to this PR.

\mixxx\dist64>Warning [Main]: Configuration file is at version "2.2.3" instead of the current 2.3.0-bet
a
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type WBeatSpinBox (parameter: QVariant(double, 0) )
Warning [Main]: WaveformSignalColors::fallBackDefaultColor - Skin does not provide valid signal colors, using default color...
Fatal [Main]: ASSERT: "!isEmpty()" in file C:\WINLIB\2.3-j00019-x64-release-fastbuild-static-55e94982-minimal\Qt-5.14.2\include\QtCore/qmap.h, line 390

**Comment by ronso0** [comment]
@JoergAtGithub 
`Warning [Main]: Property "highlight" was not defined for widget "Spinbox_embedded" of type ...`
This is just an unrelated skin warning, the relevant part is
`Fatal [Main]: ASSERT: "!isEmpty()" in file C:\WINLIB\2.3-j00019-x64-release-fastbuild-static-55e94982-minimal\Qt-5.14.2\include\QtCore/qmap.h, line 390`

please test again with https://github.com/mixxxdj/mixxx/pull/3092/commits/797eee8fdcb477cad5f4c9ac950f1cb1150c52dd and, after that with last commit https://github.com/mixxxdj/mixxx/pull/3092/commits/6d3f66f155dccca0e174df4b4bec9da3067eb77d I'm not sure which test is necessary, I guess it's failing with an empty `selectedRows` map at startup...

**Comment by JoergAtGithub** [comment]
Now my Windows build is starting up. I found the following messages in the log:
Warning [Main]: WaveformSignalColors::fallBackDefaultColor - Skin does not provide valid signal colors, using default color...
Debug [Main]: Didn't get mark TextColor, using parent's <SignalColor>: QColor(ARGB 1, 0, 1, 0)
Debug [Main]: Didn't get mark TextColor, using parent's <SignalColor>: QColor(ARGB 1, 0, 1, 0)
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 21 "Channels"
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 33 "Cover Art"
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 31 "Preview"
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 19 "Samplerate"
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 40 "#"
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 45 "Timestamp"
Debug [Main]: WTrackTableView::loadTrackModel() HiddenTableModel(0x1d828520)
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 21 "Channels"
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 33 "Cover Art"
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 31 "Preview"
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 19 "Samplerate"
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 40 "#"
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 45 "Timestamp"
Debug [Main]: WTrackTableView::loadTrackModel() MissingTableModel(0x1d828790)
Debug [Main]: WTrackTableView::loadTrackModel() PlaylistTableModel(0x120588d0)
Debug [Main]: Recordings folder set to "C:/Users/Joerg/Documents/MixxxControlerMappings/TraktorZ2/mixxx/dist64"
Debug [Main]: WTrackTableView::loadTrackModel() QSortFilterProxyModel(0x1d534d50)
Debug [BrowseThread]: Append last  0
Debug [BrowseThread]: Append last  0
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 21 "Channels"
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 19 "Samplerate"
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 40 "#"
Debug [Main]: BaseTrackTableModel - Skipping header properties for unsupported column 45 "Timestamp"
Debug [Main]: WTrackTableView::loadTrackModel() AnalysisLibraryTableModel(0x1d830650)
Debug [Main]: BaseTrackCache(0x320d170) updateIndexWithQuery took 3 ms
Debug [Main]: AnalysisLibraryTableModel(0x1d830650) select() took 14 ms 0
Warning [Main]: Requested control does not exist: "[LateNight],show_no_deck" Creating it.
Warning [Main]: Requested control does not exist: "[LateNight],show_ducking_controls" Creating it.
Warning [Main]: Requested control does not exist: "[LateNight],no_spinny_no_cover" Creating it.
Warning [Main]: Requested control does not exist: "[Skin],select_big_spinny_coverart" Creating it.
Debug [Main]: WaveformWidgetFactory::setWaveformWidget - waveform widget added in factory, index 0

**Comment by JoergAtGithub** [comment]
Now I see double decoration for the selected cell: 
grafik

**Comment by JoergAtGithub** [comment]
The scrolling behavoiur after sort is not what I expected:

Step 1) I selected a track:
grafik

Step 2) I clicked on the header "Key":
grafik

Step 3) I clicked on the header "Key" again:
grafik

You see that the selected track jumps to the first row in the visible area if ascending order is selected and to the row before the last row, if descending order is selected.
I expected that the selected row stays a the position where it was before sorting. But maybe this is implemented intentional?

**Comment by JoergAtGithub** [comment]
I reported also bug https://bugs.launchpad.net/mixxx/+bug/1895427 , which I saw in this build, but which seems unrelated to the library.

**Comment by ronso0** [comment]
> The scrolling behavoiur after sort is not what I expected

Before we used `scrollTo(index, ScrollHint)` where `ScrollHint` would scroll so the selection is at the top/bottom/center of the view, but we didn't use `PositionAtCenter` anyway.
AFAICT `scrollTo()` being broken/unreliable is the cause of the original bug with Qt 5.12.8 and 5.14.2 on Linux, so it's also broken in 2.2.3 here. (btw there ae quite a few Qt bugs about this)
Also this was only usable with mouse, as the scroll position would be reset when using arrow keys.

The solution used here `selectRow(row)` implicitely pulls the slection into view and we can use `MoveVertical` and arrow keys to navigate from there. `MoveSelection` also works.
I think this is the best we can achieve. I'm not motivated to implement a custom function that centers the selection.

**Comment by ronso0** [comment]
> Now I see double decoration for the selected cell:

This is a separate issue. Both the OS-styled outline and the border of item:focused (temp. debug style only) add up.
There's a related request about this and I'm gonna fix it for 2.3 https://bugs.launchpad.net/mixxx/+bug/1895413

**Comment by ronso0** [comment]
I squashed the commits and removed the focus indicator.
Ready for final testing.

**Comment by JoergAtGithub** [comment]
I just checked this version. Sorting works as intended!
But the red focus indicator is still there - did you missed to commit the file with this change?

**Comment by ronso0** [comment]
I squashed and force-pushed, so you need to fetch and checkout again.
the focus indicator is not included here anymore.

**Comment by MarcPlace** [comment]
LGTM, works as expected (Gentoo Linux 64-bit). Also works flawlessly together with the Denon MC7000 sorting buttons. The issue that @JoergAtGithub mentioned is also reproducible here, but that wouldn't really mind... at least for me, but YMMV of course. ;-)

**Comment by daschuer** [comment]
Thank you. 

I did some brief tests and I noticed that the selected track moves inside the visible area. 
Is this intended? 

The selection is lost if you search.

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Comment by daschuer** [comment]
Can we merge this? 
@JoergAtGithub

**Comment by JoergAtGithub** [comment]
Do you see the red border on the selected cell in your test build? This shouldn't be there, but I saw it in my last test build - most likely due to a GIT mistake on my side.
Otherwise it worked as intended!

**Comment by daschuer** [comment]
No red border. So w can merge. Thank you.

**Comment by ronso0** [comment]
> I did some brief tests and I noticed that the selected track moves inside the visible area.
Is this intended?

nope, it's unavoidable, see
https://github.com/mixxxdj/mixxx/pull/3092#issuecomment-691684757

**Comment by MarcPlace** [comment]
As you can see in my screen capture videos I've posted in [lp:1892942](https://bugs.launchpad.net/mixxx/+bug/1892942), the behaviour in Mixxx-2.1.8 is exactly the same (selected track is not centered after sorting). It could be obvious that this never has worked before, so I'm quite glad that Mixxx-2.3.0 now behaves at least like the old 2.1.8 (that's what I meant with ["that wouldn't really mind"](https://github.com/mixxxdj/mixxx/pull/3092#issuecomment-691732999)). Thanks again for fixing this.

**Pull request merged**
