### PR TITLE
Delete cuepoint on hotcue clear

### PR DESCRIPTION
**Pull request by ferranlala**
Fixes [lp:1653276](https://bugs.launchpad.net/mixxx/+bug/1653276)

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for adopting this. Unfortunately you cannot remove the hotcues anymore by right click on the hit cue buttons. 
```
Warning [Main]: Object::disconnect: Unexpected null parameter
```
is logged 

I also notice, that the unassigned hot cues are listed with 0 in the cue dialog. Is this also a bug?

**Comment by ferranpujolcamins** [comment]
My bad. Now is fixed.

**Comment by daschuer** [comment]
LGTM. Thank you.

**Comment by daschuer** [comment]
Can you rebase this on 2.1? This is a bugfix to me.

**Comment by ferranpujolcamins** [comment]
Done

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
