### PR TITLE
Opengles

### PR DESCRIPTION
**Pull request by amvanbaren**
Workaround to run Mixxx on embedded systems (Raspberry Pi, UDOO, Odroid)

### CODE REVIEW

**Comment by amvanbaren** [comment]
Related Launchpad feature request: [https://bugs.launchpad.net/mixxx/+bug/1401283](https://bugs.launchpad.net/mixxx/+bug/1401283)

**Comment by daschuer** [comment]
Thank you for the pull request. In order to merge this PR you need to become a Mixxx contributor. 
Please sign https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ
and comment here when done.

**Comment by daschuer** [comment]
I am not sure is this PR is fully on track towards a entire openGL ES solution. 

Will we be able to use a new openGL syntax that works on ES and non-ES GPUs? 
If yes, we should keep only one set of GL files and exclude the not working parts via 
and #ifdef condition. 

If we need two separate implementations for ES and non-ES GPSs, we should introduce an abstract base class and inherit a ES and a non ES version to reduce code duplication. 

Is a openGL Es version a subset of openGL?

**Comment by amvanbaren** [comment]
No, it is just a workaround and not a very pretty one.

Yes, OpenGL ES is a subset of OpenGL. OpenGL ES does have specific extensions, but I don't think the extensions are needed to render waveforms. From [https://www.khronos.org/opengles/](https://www.khronos.org/opengles/): "An OpenGL ES profile consists of two parts: a subset of the full OpenGL pipeline, and some extended functionality that is drawn from a set of OpenGL ES-specific extensions to the full OpenGL specification."

The pieces I've deleted are blocks starting with glBegin() and ending with glEnd(). This direct mode OpenGL API is deprecated: [http://gamedev.stackexchange.com/questions/34108/opengl-vbo-or-glbegin-glend](http://gamedev.stackexchange.com/questions/34108/opengl-vbo-or-glbegin-glend). Instead Vertex Buffer Objects need to be used: [http://stackoverflow.com/questions/6408202/how-do-i-replace-glbegin-and-related-functions-in-opengl-es-2-0](http://stackoverflow.com/questions/6408202/how-do-i-replace-glbegin-and-related-functions-in-opengl-es-2-0)

I think rewriting these code blocks to use Vertex Buffer Objects will solve the issue. The code blocks are relatively small and look very similar. For someone that is experienced with OpenGL Vertex Buffer Objects this should be relatively easy.

**Comment by daschuer** [comment]
OK, this means a final solution using Vertex Buffer Objects will work in a single Class for ES and non ES devices, right? 

It would be nice if you could change the PR in a way, that the deprecated GL instruction are excluded by 
#ifdef  __OPENGLES__

You need to add something like that to features.py:
build.env.Append(CPPDEFINES='__OPENGLES__')

Please add also you good explanations from above as comment. 

Maybe you fine a more reasonable CPPDEFINE, that  includes a Open GL version number or Vertex Buffer Objects.

Thank you.  

> For someone that is experienced with OpenGL Vertex Buffer Objects this should be relatively easy.

I am afraid there is no one like that on the Mixxx list. But maybe one will take the challenge ... or you? :-)

**Comment by amvanbaren** [comment]
Yes, VBOs seem like the way to go.
I will add the ifdef statements at the end of the week.

**Comment by daschuer** [comment]
LGTM, Thank you very much!

I would like to add you to the contributor list at the Mixxx about box. 
Which name do you like to see there?

**Comment by amvanbaren** [comment]
Hi,
It was fun working on this feature. 
Thanks for the support and feedback!

You can add me to the contributor list as Aart van Baren.

**Pull request merged**
