### PR TITLE
New Widget: Recording duration

### PR DESCRIPTION
**Pull request by ronso0**
I'd like to introduce a simple label widget that displays the duration of a running recording in the skin, apart from Recording section in Library.
A while ago I filed a [wishlist bug](https://bugs.launchpad.net/mixxx/+bug/1529908) but noone with more C++ experience & spare time picked this up so far.
Newbie that I am, I couldn't make something from the hints @daschuer posted, so I tried to learn from [WTime widget](https://github.com/mixxxdj/mixxx/blob/master/src/widget/wtime.cpp) (simple widget) and [dlgrecording.cpp](https://github.com/mixxxdj/mixxx/blob/master/src/library/recording/dlgrecording.cpp) (queries recordingmanager for recDurationString). Right now I fail to set up the header file correctly.
Is this approach promising at all? If yes, I'd appreciate very much if someone could explain that header file.

### CODE REVIEW

**Comment by daschuer** [comment]
This is the error message: 
```
src/skin/legacyskinparser.cpp:47:0:

src/widget/wrecordingduration.h:15:5: error: default argument missing for parameter 2 of ‘WRecordingDuration::WRecordingDuration(QWidget*, RecordingManager*)’
     WRecordingDuration(QWidget *parent=nullptr, RecordingManager* pRecManager);
     ^
scons: *** [lin64_build/skin/legacyskinparser.o] Error 1
scons: building terminated because of errors.
```

This means, there is a missmatch between the WRecordingDuration(QWidget *parent=nullptr, RecordingManager* pRecManager); including RecordingManager* pRecManager which is missing in the cpp file.

**Comment by daschuer** [comment]
For your current approach, you need to pass the RecordingManager  here: https://github.com/mixxxdj/mixxx/blob/2b26c4697cbaae7960975fab06274912bd16cda4/src/mixxx.cpp#L332 and here https://github.com/mixxxdj/mixxx/blob/93bc889521aeb3e1f7dea896052673e76a8f91c2/src/skin/skinloader.cpp#L127 similar to m_pVCManager and WSpinny

In general, I would prefer a ControlObject based solution passing the unformatted values around and format them at the using element. This would for example also allow to access the values from scripts. 
However this is somwhat more work.

**Comment by ronso0** [comment]
Thanks for your help! I will try that tonight.

> In general, I would prefer a ControlObject based solution passing the unformatted values around and format them at the using element. This would for example also allow to access the values from scripts.
However this is somwhat more work.

Okay, I see the advantage. Are there plans to use scripts for something other than controllers, skin maybe?
I recall how long it took me to work on brake/softStart so I took the easier appearing way here...

**Comment by ronso0** [comment]
Woohoo, it's working! Can't tell if the code okay, as well.
To test it, I put it behind Rec button in [Tango](https://github.com/mixxxdj/mixxx/pull/1151/commits/fe4446ee9c262bb0ef427741ef0d890d226112ce).

Last recordings duration is visible for a second when new recording is started.
Seconds seem to flip over irregularly, like in Library > Recording.

Now that I tried it a few times, I think it might be handy to have a all-in-one widget, actually a dynamic button that handles [Recording],toggle_recording, displays [custom_text][recording duration] when recording and would clear when the recording is stopped. Text could be defined with <InactiveLabel>, <ActivatingLabel> and <RecordingLabel>, that way the button could be designed for available space or even translated.
But this won't happen in this PR, if I can do it at all.

**Comment by ronso0** [comment]
...messed this up with local compile. F#*!
I'll close this and start over. Sorry!

**Pull request closed without merging**
