### PR TITLE
switch LateNight font to Segoe UI on windows seven+

### PR DESCRIPTION
**Pull request by sblaisot**
This will make LateNight looks more polished under windows seven+ and partially addresses lp:1454649 for windows seven+ (eject button not shown in effect racks under windows).

This doesn't addresses windows XP rack unit eject button bug which will need to switch to image buttons (but that will be the subject of another PR).

### CODE REVIEW

**Comment by sblaisot** [comment]
any comment, feedback ?

ready to merge ?

**Comment by Be-ing** [comment]
I notice that the title of the PR says "Sergoe" but the code says "Segoe". Which one is correct?

**Comment by sblaisot** [comment]
oups, there was a typo in the title of this PR. corrected. tanks @Be-ing

**Comment by Be-ing** [comment]
You can do "git commit --amend" to edit the commit message too.

**Comment by sblaisot** [comment]
Ah, I can't get it, I think I've messed up this PR. :(

**Comment by ywwg** [comment]
This is probably ok to merge, just a little checking please:

Can you play around with all of the skin UI options (open all panes, collapse them, various combinations) as well as try loading all of the effects?  Please be on the lookout for places where the text is too big for the boxes that contain it.  Some fonts have different width characteristics and this has caused layout problems in the past.  (I think if you load the echo plugin into all of the effect slots it will squish things too much anyway, but that's something I'm letting go for this release)

**Comment by sblaisot** [comment]
ok, I'll test this a bit more and comment here when done.

**Comment by sblaisot** [comment]
I played a little more with this font on latenaight.
I see no major problem, even with the echo plugin into all effect slot.

There is 2 minor things:
- French translation for the parameter names of the bitcrusher effect are too wide to fit under the knob. This has nothing to do with this PR but should be noted.
- the bpm is 2 pixels too low as you can see on this picture:
tempo
I can correct it by changing https://github.com/mixxxdj/mixxx/blob/1.12/res/skins/LateNight/deck.xml#L116 so it read 0,-2 but I'm afraid this will have a side effect on other system. Any hint ?

**Comment by sblaisot** [comment]
I also tried to change size on the next line to add 2 pixels height but this has no effect.

**Comment by sblaisot** [comment]
Well, my branch is all messed up, so I close this PR and make another one with a clean branch.

**Pull request closed without merging**
