### PR TITLE
Roland DJ-505: Update for explicit sync_master change from #2376

### PR DESCRIPTION
**Pull request by Holzhaus**
To be merged after #2561 and #2376.

### CODE REVIEW

**Comment by ywwg** [comment]
so if I have this right, a short press enables temporary beat sync. First long press enables sync in general, and second long press enables sync master?

**Comment by Holzhaus** [comment]
> so if I have this right, a short press enables temporary beat sync. First long press enables sync in general, and second long press enables sync master?

Yup, I have a "SYNC OFF" label for SHIFT+SYNC, so I instead of doing nothing on long press once that SYNC is enabled I thought I could make long press toggle `sync_master` sync is enabled. Thanks to your explicit master change, the `sync_mode` is now 3, not 2, so the SYNC button only blinks on when `sync_master` for deck was set by the user, not automatically by Mixxx.

**Comment by ywwg** [comment]
sounds good to me

**Review by ywwg — APPROVED** [review]
have you tried testing this?  if it works, lgtm!

**Comment by Holzhaus** [comment]
Yup, I merged this into your `mastersync-onemaster` branch locally and it works fine:

https://www.youtube.com/watch?v=u_DlrKw8oyU

**Comment by ywwg** [comment]
fancy!  anything else you want to do before merge?

**Comment by Holzhaus** [comment]
Nope. We can merge #2561 immediately and this one after your master sync changes are in `master`.

**Comment by ywwg** [comment]
retargetting to 2.3 pending discussion

**Comment by Holzhaus** [comment]
I rebased on master. Merge?

**Comment by uklotzde** [comment]
LGTM

**Pull request merged**
