### PR TITLE
lp1865957 TagLib: Fix detection of empty or missing file tags

### PR DESCRIPTION
**Pull request by uklotzde**
https://bugs.launchpad.net/mixxx/+bug/1865957

I didn't test if 2.2 is affected. But even if it is, no backport to 2.2!! I'm unable to take care of all this work, time and resources are limited.

### CODE REVIEW

**Comment by uklotzde** [comment]
Ready. Backward compatibility issues with older TagLib versions are fixed.

**Comment by Holzhaus** [comment]
I can't really comment on the code because I don't know the reason for many of these changes. How can I test this?

**Comment by uklotzde** [comment]
I have tested MP3, MP4, FLAC. Removed all tags with a tag editor and imported into a new library -> "artist - title" should be parsed from file name.

The FLAC file then contained no tags, but a cover image directly in the container. This revealed the repeated reimport bug.

TagLib is a tricky beast with an inconsistent API. Unfortunately we still "support" various old versions which make matters worse. I'm refusing to test all those variants manually.

**Comment by daschuer** [comment]
Tested with Taglib 1.9.1 without any issues.

**Comment by daschuer** [comment]
LGTM, Thank you.

**Pull request merged**
