### PR TITLE
Switch from C++14 to C++17

### PR DESCRIPTION
**Pull request by uklotzde**
Let's give it a try. No reason to stick to C++ versions from the past.

### CODE REVIEW

**Comment by uklotzde** [comment]
error: ISO C++17 does not allow 'register' storage class specifier

**Comment by daschuer** [comment]
I think we can just remove it. It is deprecated since c++11 and has probably no effect today.

**Comment by uklotzde** [comment]
OSX/clang/Scons:
osx64_build/src/analyzer/../../../src/analyzer/analyzerthread.h:66:5: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.14 or newer
    ~AnalyzerThread() override = default;

**Comment by uklotzde** [comment]
I have intentionally disabled memory alignment on macOS only for the SCons build (that still fails on Travis as expected). Until we switch the official release builds to CMake we won't need it anymore, hopefully.

**Comment by uklotzde** [comment]
lib\gtest-1.7.0\include\gtest/gtest-printers.h(497): error C2039: 'tr1': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\set(18): note: see declaration of 'std'
lib\gtest-1.7.0\include\gtest/gtest-printers.h(497): error C3083: 'tr1': the symbol to the left of a '::' must be a type

**Comment by uklotzde** [comment]
@Holzhaus After upgrading to gtest 1.8.1 the debug build now appends a 'd' suffix to the static gtest/gmock libraries, which is not appended in target_link_libraries() although both expressions match. Any idea how to fix this?

**Comment by Holzhaus** [comment]
Maybe something like this (untested):

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5e5f9368a9..c556a19ee4 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -988,38 +988,44 @@ elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU"
 endif()

 # gtest
+set(GTEST_POSTFIX "")
+if(DEBUG)
+    set(GTEST_POSTFIX "d")
+endif()
+set(GTEST_LIBRARY_PATH "${CMAKE_CURRENT_BINARY_DIR}/lib/gtest-1.8.1/googletest/${CMAKE_STATIC_LIBRARY_PREFIX}gtest${GTEST_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}")
 ExternalProject_Add(mixxx-gtest
   SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/lib/gtest-1.8.1/googletest"
   BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/lib/gtest-1.8.1/googletest"
   INSTALL_COMMAND ""
   CMAKE_ARGS "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}" "${GTEST_CMAKE_ARGS}"
-  BUILD_BYPRODUCTS "${CMAKE_CURRENT_BINARY_DIR}/lib/gtest-1.8.1/googletest/${CMAKE_STATIC_LIBRARY_PREFIX}gtest${CMAKE_STATIC_LIBRARY_SUFFIX}"
+  BUILD_BYPRODUCTS "${GTEST_LIBRARY_PATH}"
 )
 set_target_properties(mixxx-gtest PROPERTIES EXCLUDE_FROM_ALL TRUE)
 add_dependencies(mixxx-test mixxx-gtest)
 target_include_directories(mixxx-test SYSTEM PUBLIC
   "${CMAKE_CURRENT_SOURCE_DIR}/lib/gtest-1.8.1/googletest/include"
 )
-target_link_libraries(mixxx-test PUBLIC
-  "${CMAKE_CURRENT_BINARY_DIR}/lib/gtest-1.8.1/googletest/${CMAKE_STATIC_LIBRARY_PREFIX}gtest${CMAKE_STATIC_LIBRARY_SUFFIX}"
-)
+target_link_libraries(mixxx-test PUBLIC "${GTEST_LIBRARY_PATH}")

 # gmock
+set(GMOCK_POSTFIX "")
+if(DEBUG)
+    set(GMOCK_POSTFIX "d")
+endif()
+set(GMOCK_LIBRARY_PATH "${CMAKE_CURRENT_BINARY_DIR}/lib/gtest-1.8.1/googlemock/${CMAKE_STATIC_LIBRARY_PREFIX}gmock${GMOCK_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}")
 ExternalProject_Add(mixxx-gmock
   SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/lib/gtest-1.8.1/googlemock"
   BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/lib/gtest-1.8.1/googlemock"
   INSTALL_COMMAND ""
   CMAKE_ARGS "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}" "${GMOCK_CMAKE_ARGS}"
-  BUILD_BYPRODUCTS "${CMAKE_CURRENT_BINARY_DIR}/lib/gtest-1.8.1/googlemock/${CMAKE_STATIC_LIBRARY_PREFIX}gmock${CMAKE_STATIC_LIBRARY_SUFFIX}"
+  BUILD_BYPRODUCTS "${GMOCK_LIBRARY_PATH}"
 )
 set_target_properties(mixxx-gmock PROPERTIES EXCLUDE_FROM_ALL TRUE)
 add_dependencies(mixxx-test mixxx-gmock)
 target_include_directories(mixxx-test SYSTEM PUBLIC
   "${CMAKE_CURRENT_SOURCE_DIR}/lib/gtest-1.8.1/googlemock/include"
 )
-target_link_libraries(mixxx-test PUBLIC
-  "${CMAKE_CURRENT_BINARY_DIR}/lib/gtest-1.8.1/googlemock/${CMAKE_STATIC_LIBRARY_PREFIX}gmock${CMAKE_STATIC_LIBRARY_SUFFIX}"
-)
+target_link_libraries(mixxx-test PUBLIC "${GMOCK_LIBRARY_PATH}")

 # Benchmark
 add_library(gbenchmark STATIC EXCLUDE_FROM_ALL
```

**Comment by uklotzde** [comment]
The dependency in the debug build still points to the library without the 'd' suffix:

```
gmake[2]: *** No rule to make target 'lib/gtest-1.8.1/googletest/libgtest.a', needed by 'mixxx-test'.  Stop.
```

**Comment by uklotzde** [comment]
The upgrade to gtest-1.8.1 will finally fix the macOS SCons build on Travis.

**Comment by Holzhaus** [comment]
Please have a look at https://github.com/uklotzde/mixxx/pull/10

**Comment by uklotzde** [comment]
The local build now works :+1: The timeout of the last AppVeyor build should be unrelated.

**Comment by uklotzde** [comment]
std::aligned_alloc() is not available on Windows either and we have to keep the old work around.

**Comment by uklotzde** [comment]
Rebased on #2437

**Comment by uklotzde** [comment]
Rebased on #2440

**Review by Holzhaus — APPROVED** [review]
Builds fine with gcc 9.2.0 and fixes the alignment warnings. Now the only remaining warnings are the `restrict` and `deprecated-copy` warnings that we need to take care of.

It also builds with clazy 1.6/clang 9.0.1  (but throws thousands of warnings unrelated to this change).

**Review by daschuer — APPROVED** [review]
LGTM, and works here on Ubuntu trusty as well. 
Thank you.

**Pull request merged**
