### PR TITLE
LateNight: fix cover/spinny skin helper hack

### PR DESCRIPTION
**Pull request by ronso0**
Recently I noticed that in developer mode the cover/spinny toggles in the skin menu have no effect.
This fixes the issue for me.

### CODE REVIEW

**Comment by daschuer** [comment]
What is the state of this PR? 
I cannot confirm the bug here on Ubuntu Focal.
Is there another condition the must be met before the bug can be reproduces?

**Comment by robbert-vdh** [comment]
I also haven't been getting spinnies in main branch development builds of Mixxx since I started using those three weeks ago. They do show up in release builds. I'm using Arch Linux. I configured the builds with just `cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1`.

**Comment by ronso0** [comment]
> What is the state of this PR?
I cannot confirm the bug here on Ubuntu Focal.
Is there another condition the must be met before the bug can be reproduces?

This is ready, was a Draft just because that was preselected.

I can not reliably reproduce it with `--developer` and don't remember stumbling over it without.
Though with this safe change it didn't occur again so far and everything always works as intented.

**Comment by robbert-vdh** [comment]
I applied this patch to my branch and the spinnies still don't show up for me in `-DCMAKE_BUILD_TYPE=Development` builds: 
image. I've never used `--developer` before but the behavior is the same regardless of whether the option is used.

Okay, the issue doesn't seem to happen when using 100% display scaling, but at 125% and 150% display scaling the spinnies disappear. But only in development builds. 125%/150%+a release build does work correctly.

**Comment by ronso0** [comment]
Hmm.. I'll take another look to find the root cause.

**Comment by ronso0** [comment]
I just tested ~10 times with the 1st commit only and I could reproduce only once (when switching from windowed to maximize, though that didn't make any difference in later tests).
Reloading the skin fixed it. Resizing, showing/hiding the window did not.
Scaling to 125% or 150% doesn't trigger the bug for me.

@robbert-vdh Please try again with the latest commit.

**Comment by robbert-vdh** [comment]
Oh yeah sorry! I failed to mention that I'd been having this issue on the _main branch_. IIRC on 2.3 it's been working fine. On the main branch I'm not getting spinnies in development builds+(fractional?) scaling.

**Comment by ronso0** [comment]
Do you mind merging this branch into main and try to reproduce?

**Comment by robbert-vdh** [comment]
Yeah that's what I did when I said that it didn't help for me (I didn't notice this was targetting 2.3). I also did it again just now and it still behaves the same.

**Comment by ronso0** [comment]
One more try: does it work @ 200%?

**Comment by robbert-vdh** [comment]
Also doesn't work at 200% (with or without this patch). The spinnies only show up in debug builds at 100%.

**Comment by ronso0** [comment]
@robbert-vdh I pushed another attempt, please test again.

**Comment by robbert-vdh** [comment]
Applied the new patches on top of `main`, they still don't show up in development builds when using the skin scaling options. IIRC I saw someone else report the same issue of not getting spinnies in development builds.

**Comment by ronso0** [comment]
strange..
I only have Qt 5.12.8 to build with so I can only investigate with that.

There is a similiar hack for hiding the mic ducking controls when no mic is configured. Do those show up if configure at least one mic?

These ugly hacks are somewhat required to keep the skin xml easy to maintain. Without them, I'd need to build these `if A or B then C` logics with redundant xml nodes, and it's not guarantueed to work satisfyingly considering the troubles I had with `SizePolicy` in complex nested, flexible layouts.

Implementing some sort of scripting into the legacy skin system is entirely out of scope, even more so since QML is on the way.

Maybe this trivial logic can be moved to c++ for official skins. I'll check what's possible.

**Comment by robbert-vdh** [comment]
I'm using Qt 5.15.7.

**Comment by ronso0** [comment]
> On the main branch I'm not getting spinnies in development builds+(fractional?) scaling.

@robbert-vdh Could you please clarify what dev builds are?
Any main build or builds with some dev flags like `Debug`?

**Comment by robbert-vdh** [comment]
> > On the main branch I'm not getting spinnies in development builds+(fractional?) scaling.
> 
> @robbert-vdh Could you please clarify what dev builds are? Any main build or builds with some dev flags like `Debug`?

Like I said, I'm configuring the build with `-DCMAKE_BUILD_TYPE=Development`. The rest is all defaults. Also no special command line options when launching `build/mixxx`.

**Comment by ronso0** [comment]
oh, sorry, I overlooked that in your previous comment.
I'll try to figure what that does. Maybe we don't need to care about it at all if it works in regular builds.

**Comment by ronso0** [comment]
obsolete now that #11183 was merged

**Pull request closed without merging**
