### PR TITLE
move pre-commit hook back to travis

### PR DESCRIPTION
**Pull request by daschuer**
Unfortunately the output of the pre-commit hook on GitHub is only usable on BIG screens. 
Travis did a good job in the past, so let's move back until we have a solution on GitHub.

### CODE REVIEW

**Comment by daschuer** [comment]
Here how it looks on my HD-ready screen: 
grafik

Scaling it down using CTRL- makes th console output is unreadable.

**Comment by Holzhaus** [comment]
On my 15.4" 1080p laptop screen, it looks like this:

Screenshot from 2020-10-21 14-11-45

Can't you scroll down? Or click on the hamburger menu in the right top corner -> "Show full screen"?

In that case it looks like this:
Screenshot from 2020-10-21 14-13-10

**Comment by daschuer** [comment]
Ok, I had not yet discovered "Show full screen".
That works.

But this is still no solution for the phone, where it switches back to desktop view. Also all the hide buttons are still annoying.

The Travis experience is much more pleasant compared to that.

For my understanding we have switched to GitHub for an improved user experience, but the opposite is the case.

What is the drawback to just switch back?

**Comment by Holzhaus** [comment]
> But this is still no solution for the phone, where it switches back to desktop view.

The Full screen button works on my phone.

> Also all the hide buttons are still annoying.

I actually like them a lot, because that way I don't need to scroll down so much and my phone doesn't slow down due to hundres/thousands of lines.

> The Travis experience is much more pleasant compared to that.

I see your points, and the experience is not perfect. But I still like it a lot better than Travis, which has problems of its own. Slowdowns due to log loading (in contrast to lazy loading on GH Actions) and the non-working back buttons is quite annoying.

> For my understanding we have switched to GitHub for an improved user experience, but the opposite is the case.

One of the reasons was visibility to first-time contributors, yes. But I also proposed the switch to clear up the Travis Build queue, so that pre-commit jobs don't block build jobs and increases the waiting time.

**Comment by Holzhaus** [comment]
@mixxxdj/continuous-integration-managers What do the others think?

**Comment by Holzhaus** [comment]
Idea: I could also look into checking the output, and write a bot thwt comments on the PR if the pre-commit hook fails. That comment could explain how to install/use the precommit hooks and a link to a gist with the patch diff and how to apply that diff using `git apply`.

**Comment by daschuer** [comment]
>> But this is still no solution for the phone, where it switches back to desktop view.

> The Full screen button works on my phone.

Did you see a mobile view? I can also switch to full screen but the text is not readable without a magnifier glass. I use Chrome on Android. 

>>  Also all the hide buttons are still annoying.

> I actually like them a lot, because that way I don't need to scroll down so much and my phone doesn't slow down due to hundrets/thousands of lines.

This is not the case on Travis for the pre-commit hook. It also hides relevant lines and reduces the output from 1378 to 80 lines. 
It performer this in place, which is much more pleasant to me. 
In addition it has the "Scroll to the end of the Log" button.  
See: https://travis-ci.org/github/mixxxdj/mixxx/jobs/737688113

You other points are valid for me, I suffer the missing back button as well. Unfortunately this does not outweigh the usability shortcomings here.

**Comment by daschuer** [comment]
This has been discussed here: 
https://travis-ci.community/t/travis-ci-web-ui-browser-back-button-wont-let-you-leave/9314

**Comment by Holzhaus** [comment]
> > > But this is still no solution for the phone, where it switches back to desktop view.
> 
> > The Full screen button works on my phone.
> 
> Did you see a mobile view? I can also switch to full screen but the text is not readable without a magnifier glass. I use Chrome on Android.

Ah, I didn't notice how small it is because I usually turn my phone sideways to read code. This is how it looks for me:

Screenshot_20201021_153546_com duckduckgo mobile android

**Comment by daschuer** [comment]
> I see a scrollbar on the right of the log box. Can't you just scroll down?

Unfortunately only the 6 lines are scrolled. The whole website is not scroll-able.

**Comment by daschuer** [comment]
> Idea: I could also look into checking the output ...

If you like to go this extra mile? 
In the mean time, I prefer to keep it simple and just go back to Travis.

**Comment by uklotzde** [comment]
I disagree. The full-screen view works well, why should we go back to Travis?

The pre-commit hook is supposed to be executed locally by developers before publishing a PR. The GitHub Action is only the final quality gate and not intended as a development tool.

**Comment by daschuer** [comment]
> I disagree. The full-screen view works well, why should we go back to Travis?

What environment do you use? 

The issue is that new contributors will likely have the pre-commit hook not installed. This is the only case where the hook ever fails. For these users and for the reviewers we nee a smooth experience.  

I think I have reasonable outlined that the full-screen view does not work well and is hard to discover. This applies especially to new contributors. 

I will ask on Zulip.

**Comment by uklotzde** [comment]
Converted to draft, because we don't have an agreement yet.

**Comment by daschuer** [comment]
I will close this sind my opinion seems to be a minority.

**Pull request closed without merging**
