### PR TITLE
GitHub Actions: Remove "Set up cmake" build step

### PR DESCRIPTION
**Pull request by Holzhaus**
https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/CI.20breaks.20on.20CMake.20setup

### CODE REVIEW

**Comment by daschuer** [comment]
Why does this succeed in Bionic?
It has cmake 3.10 but we require cmake 3.13.

**Comment by daschuer** [comment]
```
2021-01-19T01:22:23.5605556Z Preparing to unpack .../076-cmake-data_3.10.2-1ubuntu2.18.04.1_all.deb
```

**Comment by Holzhaus** [comment]
> Why does this succeed in Bionic?
> It has cmake 3.10 but we require cmake 3.13.

No idea. But I won't complain about it.

**Comment by daschuer** [comment]
Is the environment cached? Will it fail once the cache is cleared? Can you add a 

cmake --version 
type -a cmake

to see what happens?

**Comment by daschuer** [comment]
Never mid, it is working again. 
I think we can close this, right? 
See:
https://github.com/mixxxdj/mixxx/pull/3569/checks?check_run_id=1731546849

**Pull request closed without merging**
