### PR TITLE
Use int for CannelCount

### PR DESCRIPTION
**Pull request by daschuer**
This is an alternative solution for https://github.com/mixxxdj/mixxx/pull/3893

I like this more, because this avoids the situation that external libraries uses a greater value range than Mixxx for the channel count. Most are on int so Mixxx does the same.

### CODE REVIEW

**Comment by uklotzde** [comment]
The idea was to use more restrictive types internally, because negative or excessive values do not make any sense and should be detected and handled at the boundary. Sure, we could use int everywhere or, even better, switch to an untyped language for maximum flexibility ;)

Seriously, I don't really care which solution to prefer. But we should be clear about the reasoning and motivation and then apply this strategy consistently.

**Comment by daschuer** [comment]
Do we have a reason for restrict the value to 255? If not lets merge this one.  
This way we have an universal class for channel counts and the boundaries check can be done individual in the using business logic.

**Comment by uklotzde** [comment]
I disagree for the reasons outlined above but I won't start a discussion. Someone else may merge.

Btw, it is not helpful if you open multiple, competing PRs. It is your responsibility to make a decision and stand behind it.

**Comment by Holzhaus** [comment]
Hmm, I think I prefer the original PR, too.

**Comment by uklotzde** [comment]
I second that. Then let's merge #3893 instead and close this one.

**Pull request closed without merging**
