### PR TITLE
Resolve merge conflicts from 1.12 to master

### PR DESCRIPTION
**Pull request by uklotzde**
As offered on mixxx-devel.

### CODE REVIEW

**Comment by ywwg** [comment]
hm is there any way to see just the merge conflicts?

**Comment by uklotzde** [comment]
@ywwg I will send you the files that had merge conflicts. Then you can do the merge yourself, makes me feel safer ;)

**Comment by uklotzde** [comment]
You only need to copy the following files from this branch:
src/test/coverartcache_test.cpp
src/test/soundproxy_test.cpp

Resolving the remaining conflicts should be straightforward to resolve. The file soundsourcemodplug.cpp can simply be deleted, I don't see any reason why parsing the header when opening the SoundSource.

**Comment by ywwg** [comment]
It's ok, if you're confident with the merge you did then that's fine with me.  I was just wondering if there was an easy way I could skim it in github.  The tests timed out on Travis, but if they pass for you then I'm ok with merging this in.

**Comment by uklotzde** [comment]
Just wait a second. I've done the merge again to double check the modifications. Now I will do a clean local build, run all the tests and force push this new branch.

**Comment by uklotzde** [comment]
I've repeated the merge, just to be sure that everything is correct. If the Travis CI build and tests pass this branch will be ready for merging.

The main conflicts that has to be resolved were in src/test/coverartcache_test.cpp and src/test/soundproxy_test.cpp

engine/enginefilteriir.h: No manual modifications even though it is shown in the diff
main.cpp: Removed "Console" (from 1.12)
soundsourcemodplug.cpp: Discarded modifications of commit 8082fdd, should not be relevant any longer
searchquery.cpp: Deleted obsolete destructor of NotNode
searchquery.h: No manual modifications even though is is mentioned as a merge conflict

**Comment by ywwg** [comment]
thanks for doing this -- if you want you could even do this once a week and make sure master is getting all our yummy bug fixes :)

**Comment by daschuer** [comment]
LGTM, Thank you.

**Pull request merged**
