### PR TITLE
pre-commit: Add markdownlint support

### PR DESCRIPTION
**Pull request by Holzhaus**
This prevents introducing broken markdown.

### CODE REVIEW

**Review by uklotzde — CHANGES_REQUESTED** [review]
Please update the comments in .pre-commit-config.yam. You now also have to install Ruby in addition to Python for running the pre-commit hooks.

**Comment by Holzhaus** [comment]
> You now also have to install Ruby in addition to Python for running the pre-commit hooks.

Are you sure? According to https://pre-commit.com/#ruby, ruby hooks work without any system level dependencies. It should download a suitable ruby installation automatically.

**Comment by uklotzde** [comment]
> > You now also have to install Ruby in addition to Python for running the pre-commit hooks.
> 
> Are you sure? According to https://pre-commit.com/#ruby, ruby hooks work without any system level dependencies. It should download a suitable ruby installation automatically.

The pre-commit hook failed until I manually install `rubygem`.

**Comment by uklotzde** [comment]
```
[INFO] Installing environment for https://github.com/markdownlint/markdownlint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('gem', 'build', 'mdl.gemspec')
return code: 1
expected return code: 0
stdout:
    Executable `gem` not found
stderr: (none)
```

**Comment by Holzhaus** [comment]
> ```
> [INFO] Installing environment for https://github.com/markdownlint/markdownlint.
> [INFO] Once installed this environment will be reused.
> [INFO] This may take a few minutes...
> An unexpected error has occurred: CalledProcessError: command: ('gem', 'build', 'mdl.gemspec')
> return code: 1
> expected return code: 0
> stdout:
>     Executable `gem` not found
> stderr: (none)
> ```

This looks like you have an incomplete ruby version installed. According to the code, it should only use the system ruby if you have both `ruby` and `gem` installed. Let me double check, maybe a bug in `pre-commit`.

**Comment by Holzhaus** [comment]
@uklotzde please retest, it should now always install ruby regardless of the system.

**Comment by uklotzde** [comment]
[ruby-build.20210818170924.121021.log](https://github.com/mixxxdj/mixxx/files/7008298/ruby-build.20210818170924.121021.log)

**Comment by Holzhaus** [comment]
I opened a bug report upstream: https://github.com/pre-commit/pre-commit/issues/2016

@uklotzde For now I switched to a nodejs-based markdown linter. Please retest.

**Comment by uklotzde** [comment]
Nice side-effect: If you already use his markdownlint VS Code plugin then the configuration is recognized and warnings are also shown there.

**Comment by uklotzde** [comment]
I still get warnings in CONTRIBUTING.md:

```sh
SKIP=end-of-file-fixer,trailing-whitespace,clang-format,eslint,no-commit-to-branch \
pre-commit run --all-files
```

**Comment by Holzhaus** [comment]
> I still get warnings in CONTRIBUTING.md:
> 
> ```shell
> SKIP=end-of-file-fixer,trailing-whitespace,clang-format,eslint,no-commit-to-branch \
> pre-commit run --all-files
> ```

Weird. I don't get any warnings. Maybe it also uses some global config from vscode?

**Comment by Holzhaus** [comment]
> > I still get warnings in CONTRIBUTING.md:
> > ```shell
> > SKIP=end-of-file-fixer,trailing-whitespace,clang-format,eslint,no-commit-to-branch \
> > pre-commit run --all-files
> > ```
> 
> Weird. I don't get any warnings. Maybe it also uses some global config from vscode?

No, CONTRIBUTING.md does not exist in my tree, because this PR targets the 2.3 branch.

**Comment by uklotzde** [comment]
> > > I still get warnings in CONTRIBUTING.md:
> > > ```shell
> > > SKIP=end-of-file-fixer,trailing-whitespace,clang-format,eslint,no-commit-to-branch \
> > > pre-commit run --all-files
> > > ```
> > 
> > 
> > Weird. I don't get any warnings. Maybe it also uses some global config from vscode?
> 
> No, CONTRIBUTING.md does not exist in my tree, because this PR targets the 2.3 branch.

My bad, tested on main.

**Review by uklotzde — APPROVED** [review]
Thank you! LGTM

**Pull request merged**
