### PR TITLE
Denon MC6000MK2: Fix JSHint warnings for 1.12

### PR DESCRIPTION
**Pull request by uklotzde**
...forgot to validate the current version.

Just some small fixes in the JavaScript code, functionality is not affected!

### CODE REVIEW

**Comment by illuusio** [comment]
Still have these:
line 34, col 110, Unclosed string.
line 36, col 108, Unclosed string.
line 295, col 1, Bad line breaking before '+'.
line 302, col 111, Unclosed string.
line 317, col 112, Unclosed string.

**Comment by uklotzde** [comment]
I upgraded JSHint from version 2.7.0 to 2.8.0, but I still don't see those warnings. Do you have any ideas why?

I just installed js-beautify and will fix the indentation and other stuff.

**Comment by uklotzde** [comment]
The warning messages and line numbers don't seem to match the content of the file Denon-MC6000MK2-scripts.js

Example: Line 36 is "};"

And I noticed that I used Tabs instead of Spaces so the indentation depends on the settings of the editor. Will be fixed with by applying js-beautify.

**Comment by illuusio** [comment]
I use JShint version 2.5.1 so I think that is the problem. I'll upgrade to latest and those will be vanish I think.

**Comment by ywwg** [comment]
done?

**Comment by illuusio** [comment]
Yes merge this those are ok. I'm middle of upgrading JShint packages and Node.js 4.0.0 depency hell..

**Pull request merged**
