### PR TITLE
Make HIDPackets own a link to HIDControllers

### PR DESCRIPTION
**Pull request by ywwg**
This should be a relatively safe noop.  Creating an HIDPacket now also requires a controller parameter.  This will enable better callbacks for virtual "deckX" connections.  We should do some basic checking just to make sure this doesn't break anything.

Linter made some changes to common-hid-devices.js that should also be noop.

### CODE REVIEW

**Comment by ywwg** [comment]
(for now it would also be acceptable to pass "undefined" as a controller... the controller parameter in HIDPacket is currently not used at all (yet).

**Comment by Be-ing** [comment]
I'm nervous about introducing backwards incompatible API changes. Can you make the new parameter the last one of the function signature? That way old scripts don't have to pass it.

**Comment by Be-ing** [comment]
I'm unclear what the use case for this is without seeing the code you're trying to implement. Circular references can create hassles in JS, for example JSON.stringify won't work on an object with a circular reference. On the other hand, this whole library is a mess with poor separation of responsibility between classes, so :shrug:

**Comment by ywwg** [comment]
>  Circular

oh, does the controller own the packets?  where is the circle?

**Comment by ywwg** [comment]
oh oh! it's not a circular reference, it's a bi-directional reference.  But this means I don't need to extra construction argument.  changing now

**Comment by ywwg** [comment]
based on further reading I think this is unnecessary

**Pull request closed without merging**
