### PR TITLE
lp1336866: Fixed bpm.tapButton in common-controller-script.js

### PR DESCRIPTION
**Pull request by Swiftb0y**
I somehow worked on the wrong branch and cherry-picking is not possible because the pre-commit hooks are acting up so I'm creating a new PR that supersedes #1811

### CODE REVIEW

**Comment by Holzhaus** [comment]
AFAIK the issue is already present in 2.2. Can you rebase?

**Comment by Swiftb0y** [comment]
Oh, yeah I forgot. I'll try. my git foo has been a bit rusty lately though.

**Comment by Holzhaus** [comment]
By the way, you can just force-push after rebase and then change the target branch by clicking the edit button next to the PR title next time :D

**Comment by Swiftb0y** [comment]
Oh, that feature must be new. Thanks.

**Pull request closed without merging**
