### PR TITLE
lp1777480: Pad unreadable samples with silence on cache miss

### PR DESCRIPTION
**Pull request by uklotzde**
An attempt to fix the timing issues on cache miss as demonstrated in this bug report:
https://bugs.launchpad.net/mixxx/+bug/1777480

### CODE REVIEW

**Comment by kazakore** [comment]
Build fails for me, this is the only line in red so assume the related on.

src/engine/cachingreader.cpp:369:34: error: ‘bufferedFrameIndexRangee’ was not declared in this scope
                     DEBUG_ASSERT(bufferedFrameIndexRangee.empty());

**Comment by uklotzde** [comment]
Build failure: Fixed typo

**Comment by kazakore** [comment]
Looks good to me. I can see Cache Miss still showing up in the terminal log but it is no longer going out of time. Not tried to ascertain if the silence is noticeable, only have it at a barely audible volume as at work....

**Comment by kazakore** [comment]
Unfortunately this doesn't have the quantise always on fix of #1715 applied, yet alone the #1716  which was based on it I'm currently using. How would I combine the fixes from both this and 1716 for a copy for personal use??

**Comment by uklotzde** [comment]
This is just a single commit. Both cherry-picking or merging should work without any conflicts since it affects another file than the changes in #1715 and #1716.

**Comment by kazakore** [comment]
I've started a discussion on Zulip as didn't want to take things too off this PR itself here.
But I thought 1716 was based directly on 1715 and that 1715 was considered important enough to try and get into 2.1.2 so I'm surprised their based on Master....

**Comment by uklotzde** [comment]
Just some remarks about the history: I remember that the behaviour of the CachingReader in this special case might have been changed with the final SoundSource changes. Unfortunately I didn't notice that this leads to unexpected behaviour up the call stack, because the calling code didn't complain when receiving 0 samples on a cache miss.

Since the CachingReader already handles read requests in both directions it is better to keep the padding here instead of doing it later in the caller's code. The requested samples are intended for immediate consumption by the caller and should not be stored so this best effort approach is valid. The requested chunks are small and a short period of silence is not audible, especially when applying ramping/mixing to avoid discontinuities in the resulting signal.

**Comment by daschuer** [comment]
Thank you for fixing this issue here. 

We original had a fading issue in case of Cache misses: 
The user code fades into the padded silence. Once the Caching reader provides real samples they are starting without fading which may be heard as an audible pop. 
I don't find this bug, I have probably never reported it. I am also unsure if we have already fixed it or not. Do you know the current state? 

A probably related issue is this: 
https://bugs.launchpad.net/mixxx/+bug/1758790

I will now have a look.

**Comment by daschuer** [comment]
Here is the picture of a cache miss using a 440 kHz tone:

bildschirmfoto vom 2018-07-10 22 12 54

The edge with streams start is a hear-able click.

**Comment by Be-ing** [comment]
@daschuer is that waveform showing a cache miss with this branch or with master?

**Comment by uklotzde** [comment]
Unfortunately we cannot fix this easily. The caching is already very complicated and I spend a lot of time to get the brittle and buggy caching framework stable. I will not try to fix it again, next step would be a complete rewrite.

But we have much more serious usability issues that should be fixed before trying to eliminate small audio artefacts that are hardly noticeable in real-life situations. I don't have time for this kind of optimizations. And if I had I wouldn't rewrite the code it in C++ again ;)

**Comment by daschuer** [comment]
> @daschuer is that waveform showing a cache miss with this branch or with master?

This is a cache miss with this branch and was a known problem which exists before the cache returns no samples on a cache miss.

**Comment by daschuer** [comment]
Now a cache miss dos not click anymore: 
bildschirmfoto vom 2018-07-14 01 24 03
https://github.com/uklotzde/mixxx/pull/8

**Comment by uklotzde** [comment]
I need to finalize the new code:
- Keep returning the actual number of read samples to avoid processing garbage data
- Replace the boolean with an enum ... to catch the remaining lines where still a number is returned and implicitly converted to a boolean. C/C++ laziness ;)

**Comment by uklotzde** [comment]
Done.

**Comment by daschuer** [comment]
Thank you for improving the interface. 
LGTM.

**Pull request merged**
