### PR TITLE
RecordingDuration: Removed the Timer from the Record Button.

### PR DESCRIPTION
**Pull request by PawBud**
This PR removes the Recording Duration from the Record Button and now the toolbar looks like the following:-
Screenshot from 2020-12-02 00-40-25
I will be adding a Record Inactive Text if possible. For the time being the button is working well and is showing the toggled off/on States.

### CODE REVIEW

**Comment by ronso0** [comment]
You can turn it into ● **REC** and reduce the width so that it still fits in nicely.

**Comment by Holzhaus** [comment]
Didn't follow the discussion, but this seems like a regression to me. I don't see how the WAirTimer widget (for broadcasting) could replace the Recording timer. Broadcasting and Recording are two unrelated features that can be toggled at different times.

**Comment by ronso0** [comment]
I thought it was agreed on to have some sort of timer widget that takes care of both Rec and Broadcast timers?
#3364 doesn't reflect that yet.

**Comment by Be-ing** [comment]
> I thought it was agreed on to have some sort of timer widget that takes care of both Rec and Broadcast timers?

Yes, the first step is separating the timer from the recording toggle button.

**Comment by ronso0** [comment]
> > I thought it was agreed on to have some sort of timer widget that takes care of both Rec and Broadcast timers?
> 
> Yes, the first step is separating the timer from the recording toggle button.

As long as there's no new timer widget `that takes care of both Rec and Broadcast` this is just a design preference and an unnecessary change I object.

**Comment by Be-ing** [comment]
Okay. We don't need to merge it until the replacement is finished.

**Comment by PawBud** [comment]
> You can turn it into ● **REC** and reduce the width so that it still fits in nicely.

OK, so Since we will be adding 3 new extra buttons i just wanted to see how they would look in their default sizes. So, I guess, I'll change the size at the end, if that's ok

**Comment by PawBud** [comment]
> > > I thought it was agreed on to have some sort of timer widget that takes care of both Rec and Broadcast timers?
> > 
> > 
> > Yes, the first step is separating the timer from the recording toggle button.
> 
> As long as there's no new timer widget `that takes care of both Rec and Broadcast` this is just a design preference and an unnecessary change I object.

So for this, I agree having a separate recording duration widget and the timer widget is inconsistent, but I was planning to "dump" the `wrecordingduration` after adding the 3 buttons and their functionalities, but all of that depends on how the toolbar will look or if we think of a better solution.

**Comment by PawBud** [comment]
This PR is being closed, Kindly check out https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Adding.20an.20On-Air.20Timer.

**Pull request closed without merging**
