### PR TITLE
1.12 deere (minor) rework

### PR DESCRIPTION
**Pull request by ferranlala**
This is starting to look sweet!
Here I've put some love to the sliders so they fit the overall look of the skin. I've also changed some colours and text sizes to improve the overall look and improve visibility of text and buttons.

Other things I wanted to fix (and the reason why I didn't):

-Centering of the icons of buttons: I think this needs code modifications.

-Margins and paddings of the mixer: In general it's difficult to adjust margins, paddings and sizes in Deere because some parts are not properly nested in WidgetGroups. This issue is also what makes the beatloop buttons overlap when the skin is shrunk. A Deere rework solving this will be a huge PR and difficult to review. I think the current state of the skin is not optimal but pretty good, so I will leave this until 1.13.

@ywwg what are your skin-related blockers for 1.12?

### CODE REVIEW

**Comment by Be-ing** [comment]
This is starting to look pretty sweet. :) Thank you for doing this.

The text is almost all readable now, although the text labeling knobs could maybe be a tiny bit bigger. The text of the clock in the top right is still tiny.

Also, the text below knobs that have buttons is centered relative to the space between the edge of the button and the other edge of the knob rather than centered relative to the knob. That's just a tiny nitpicky detail; if it's not easy to fix don't worry about it much.

I like how LateNight has the master VU meter close to the channel meters, but I don't know if doing that in Deere could work well.

**Comment by daschuer** [comment]
IMHO the slider does not look flat enough compared to the knobs. 
Is there a transient to from the borders? The knobs are looking sharper.
How about remove the whole outer white border? 
Juts my two cents. 

The hotcue buttons 1 and 3 / 2 and 4 have no distance. The same happens for the bank buttons.

**Comment by ywwg** [comment]
I think this is looking good too!  I think the sliders look ok.  On my machine, the "head gain" label is slightly cut off.  When clicking the reveal button for effects and samplers, the button moves out from under the mouse cursor.  Make the buttons top-aligned and that won't happen.  

The highlight colors are a little broken.  On my system, if I have a track selected and then I click inside the search bar, the unfocussed track selection becomes white text on a white-to-gray gradient background.  This is impossible to read.

The sidebar still has issues -- the "y" characters all have the descenders cut off so they look like "v".  And if the sidebar is not translatable then I don't think we can use it until that problem is solved.  Skins aren't translated right now but most of the words are single nouns, whereas the sidebar looks like a menu that should be fully supported with keyboard navigation and text translation.  I'm also worried about the discoverability of the hamburger menu, which people know on mobile devices but is not used anywhere else in mixxx.

I've already said I would really prefer that the sidebar wait until after 1.12, and I still feel that way.  A right-side group of toggle buttons with icons would have the same function and not take up so much room or have the same usability issues.

**Comment by ywwg** [comment]
I think this skin is very near ready for 1.12.  

One thing I notice is that the vertical space per deck is quite large.  This has been a big problem with LateNight and it looks like it'll be an issue here too.  We might be able to save some space by reducing the height of the track text information area and the pitch sliders.  Make sure you look at the skin at 1365x768 or something like that.  Do what you can, but no need for major reworking if it starts to get really hard.

**Comment by ferranpujolcamins** [comment]
Thank you for your observations.

> The text is almost all readable now, although the text labeling knobs could maybe be a tiny bit bigger.

This might require a redesign for the mixer layout, so let me handle it in another PR.


> The text of the clock in the top right is still tiny.

Fixed.

> I like how LateNight has the master VU meter close to the channel meters, but I don't know if doing that in Deere could work well.

Unless we move the top toolbar controls to a mixer side-pane (like LateNight), I don't see how to put the meter closer.

Of all the designs of sliders I tested, IMHO this are the ones that fit Deere best. Please feel free to propose an alternative though :)

> Is there a transient to from the borders? The knobs are looking sharper.
Yeah, something was wrong. The dark background extended out the white zone. I fixed that, hopefully now they look smoother.

> The hotcue buttons 1 and 3 / 2 and 4 have no distance. The same happens for the bank buttons.

I've failed at this :( . I haven't been able to solve this neither modifying the style sheet nor the WidgetGroup nesting of those buttons. Can someone have a look at this?



> On my machine, the "head gain" label is slightly cut off.

Fixed.

> When clicking the reveal button for effects and samplers, the button moves out from under the mouse cursor. Make the buttons top-aligned and that won't happen.

Fixed.

> The highlight colors are a little broken. On my system, if I have a track selected and then I click inside the search bar, the unfocussed track selection becomes white text on a white-to-gray gradient background. This is impossible to read.

I can't reproduce that. Can you post a screenshot? How is it possible that this happens to you but not me?

> The sidebar still has issues -- the "y" characters all have the descenders cut off so they look like "v"

I either can reproduce this. Screenshot? :)

> I've already said I would really prefer that the sidebar wait until after 1.12, and I still feel that way. A right-side group of toggle buttons with icons would have the same function and not take up so much room or have the same usability issues.

+1. We can even try to fit this buttons on the top toolbar.

> One thing I notice is that the vertical space per deck is quite large. This has been a big problem with LateNight and it looks like it'll be an issue here too. We might be able to save some space by reducing the height of the track text information area and the pitch sliders. Make sure you look at the skin at 1365x768 or something like that. Do what you can, but no need for major reworking if it starts to get really hard.

Sure, let me handle this in another PR though.

**Comment by daschuer** [comment]
Thank you for the improvements. IMHO it is merge-able. Since there seams to be is still work in progress, we can hold it if you like. Just give a hint.

**Comment by ywwg** [comment]
ok I think this is fine for this PR, let's get it in and then work on the other issues I raise

**Comment by ferranpujolcamins** [comment]
Thank you. It was ok to merge :)

**Comment by ywwg** [comment]
:P

**Pull request merged**
