### PR TITLE
Avoid hotcue buttons from being stucked in the pressed state

### PR DESCRIPTION
**Pull request by daschuer**
We have and issue when someone pressed right click during preview or outside the button. 
In this case Mixxx sticks in the preview state, the user looses control which must not happen in any case. 
This PR aims to fix that.

### CODE REVIEW

**Comment by ronso0** [comment]
I'm afraid this only partly solves the issue because there are still two ways to get stuck in preview mode:
* press & hold a GUI hotcue button to preview, then press the same hotcue button on the keyboard
* press & hold  the Cue button > move outside > release

In both cases the initial GUI button is released but Mixxx is still in preview mode.
Guess this requires a fix in cuecontrol.cpp

**Comment by daschuer** [comment]
Which skin did you use for testing?

**Comment by ronso0** [comment]
I tested with LateNight, PaleMoon

**Comment by ronso0** [comment]
..and now Shade. Same result unfortunately.

**Comment by daschuer** [comment]
I was able to reproduce it when using the hotcue buttons on a controller together with a mouse.
This is now fixed. 

I still can't reproduce:
> press & hold the Cue button > move outside > release

Does it still happen after the latest commit? 

On which Qt version and OS did you test?

**Comment by ronso0** [comment]
The hotcue buttons seem to be fixed (tested with GUI and keyboard).

> press & hold the Cue button > move outside > release

This still happens. When I right-click outside the play position jumps back to the Cue point and keeps playing. Though with the last commit it switches to normal play mode, clicking Play stops the track.
(this is also what happened earlier, it did not get stuck in preview with Cue)

this is with Ubuntu Studio 20.04, Qt 5.12.8

**Comment by daschuer** [comment]
I cant confirm this with plain Ubuntu 20.04, Qt 5.12.8 and Unity.

**Comment by daschuer** [comment]
Ah, now I got it, it is only the cue button affected.

**Comment by ronso0** [comment]
Yes, only the main Cue.

**Comment by daschuer** [comment]
It is the "intended" right click action cue_gotoandstop. The stop part is the same as pressing the play button for latching. 
I am heading towards to remove the goto part during review and just latch play. This allows to continue playing with only a mouse.
I think I can remember that this was working in the past.  
The alternative would be to just end preview and perform cue_gotoandstop. 
What do you think?

**Comment by ronso0** [comment]
the Cue button is not stuck so if the goto part was removed that indeed be not a bug but a feature :)
We should make it discoverable. Can we cram that info into the tooltip or is it sufficient to add it to the manual?
`Right-click while previewing with pressed Cue button will latch the play button.`

**Comment by daschuer** [comment]
Done

**Comment by ronso0** [comment]
Nice, works nicely with mouse only, didn't test other situations with controller.

there are conflicts now (#3370)

**Comment by daschuer** [comment]
Ups, I messed it up with other tests. Fixed.

**Comment by uklotzde** [comment]
@daschuer Please fix the conflicts.
@ronso0 Then this is ready I guess?

**Comment by ronso0** [comment]
Yup, ready to go IMO.

**Comment by daschuer** [comment]
Done.

**Comment by uklotzde** [comment]
Thank you! LGTM

**Pull request merged**
