### PR TITLE
Hercules P32 mapping: pregain instead of dry/wet knob (optional)

### PR DESCRIPTION
**Pull request by pierrelegall**
This feature is optional (see the dryWetKnobAsPregain flag).

### CODE REVIEW

**Comment by lepieru** [comment]
Documentation PR: https://github.com/mixxxdj/manual/pull/343

**Comment by Be-ing** [comment]
I like the idea to implement a way to control the deck gain. But I think we may be able to come up with a better way to design this. I would not want to sacrifice any of the existing functionality of the mapping to make room for the gain control. My first thought was to use shift + dry/wet knob, but that would be complicated to implement and dealing with soft takeover is never ideal. Is there a way we could use one of the encoders? All possible actions with the encoders with and without shift are already mapped. Could we make another modifier? Maybe using the shift button of the opposite side? Do you have any other ideas?

**Comment by lepieru** [comment]
> Maybe using the shift button of the opposite side?

I did'nt know it was possible to map this kind of binding. Nice to know! But I like to be able to change pregain with just one hand. 

I found it nice at use (the chosen potentiometer feet the use case well). However, agreed to the fact this is not an ideal design ; and I don't have any better idea yet.

I don't really know if it's a good idea or not to merge this into Mixxx because it complixify the reading of the mapping. It's not really complex but it's not just one simple `if` statement as we can suppose. But don't forget it is an optional feature, the default behavior does not change.

**Review by Swiftb0y — APPROVED** [review]
Hey @pierrelegall 
Is there still any desire to get this merged? We'd also need a small PR to the manual in that case.

**Comment by pierrelegall** [comment]
> Is there still any desire to get this merged?

It's ok for me, I could write the documentation if @Be-ing approve this changes.

**Comment by Swiftb0y** [comment]
I don't think they do either. IMO this mapping is a minimal improvement, but if you don't think its worth the effort to document the changes, we can just close the PR too. Either is completely fine for me. I just want to shrink our PR backlog a bit.

**Review by Swiftb0y — APPROVED** [review]
LGTM, this doesn't change any behavior nor does it increase complexity much.

**Pull request merged**
