### PR TITLE
lp1828212: Fix missing key analysis

### PR DESCRIPTION
**Pull request by uklotzde**
https://bugs.launchpad.net/mixxx/+bug/1828212

The code comments document why and how.

### CODE REVIEW

**Comment by Be-ing** [comment]
LGTM thank you for the quick fix!

**Review by daschuer — COMMENTED** [review]
Can we make this hack somehow conditional that it will not bite us later?

**Comment by daschuer** [comment]
@be-ing Are you able to verify by ear that the previous not detected track has now the right value using a piano or a compatible track. Else you may look at the Fft spectrum in audacity. The peak frequencies should match the detected keys chord.

**Comment by uklotzde** [comment]
@daschuer I have no idea how those crappy QM plugins work. Please feel free to fix the workaround if needed ;)

**Comment by daschuer** [comment]
Ok, I can have a look. Do you have an idea why only master is effected?

**Comment by Be-ing** [comment]
The bug was introduced when VAMP plugins were removed in #926, so that is why only master is affected.

**Pull request merged**
