### PR TITLE
(fix) backport: require a minimum movement before initiating the drag&drop of tracks

### LINKED ISSUE #13095: Cannot select star rating in list view
### Bug Description

I can't set a star rating in the list view, but I _can_ set it from the deck up top:

https://github.com/mixxxdj/mixxx/assets/1039369/96e92a76-ad90-4de6-be17-c2fab41c0690

This wouldn't be too annoying for me if I could just import my ratings from macOS Music (formerly known as iTunes), but due to #7513 this is sadly not possible.

### Version

2.4.0 ARM64

### OS

macOS 14.4.1

### PR DESCRIPTION
**Pull request by ronso0**
#12903 for 2.4

Might already fix #13095 
If not I'll try to refactor mouse move in StarEditor.

### CODE REVIEW

**Comment by m0dB** [comment]
any reason for the draft status?

**Comment by ronso0** [comment]
Mhh, none actually, want to wait for CI and attempt the star delegate fix, but didn't find time.

**Comment by ronso0** [comment]
The star fix will be separate.
Feel free to merge!

**Comment by ronso0** [comment]
Seems this fixed #13095 :tada:

**Pull request merged**
