### PR TITLE
Add support for Hercules Universal DJ.

### PR DESCRIPTION
**Pull request by Yannig**
Stolen from https://www.mixxx.org/forums/viewtopic.php?f=7&t=8151.

### CODE REVIEW

**Comment by daschuer** [comment]
Do you see a chance to finish this by the end of the week?
Than this one can be part of the upcoming 2.1 release.

**Comment by Yannig** [comment]
I'll try to do it by the end of the week.

**Comment by Be-ing** [comment]
Please comment here when you have documented the mapping on the wiki.

**Comment by Be-ing** [comment]
This pull request cannot be reviewed by anyone who does not have the hardware without a wiki page documenting it, so I am closing it. @Yannig if you are interested in having this merged, please [document the mapping](https://mixxx.org/wiki/doku.php/contributing_mappings#documenting_the_mapping) and reopen this pull request.

**Pull request closed without merging**
