### PR TITLE
fix realtime scheduling notice overlapping other text

### PR DESCRIPTION
**Pull request by Be-ing**
2.0 and master:
realtime-text-overlapping
This PR:
realtime-text-fixed
Either with realtime priority:
realtime-text-hidden

### CODE REVIEW

**Comment by daschuer** [comment]
LGTM Thank you!

**Comment by Pegasus-RPG** [comment]
Wouldn't it be good to show somewhere that rt prio is enabled as a confirmation?

**Comment by Be-ing** [comment]
Sure, that would be nice.

**Comment by Pegasus-RPG** [comment]
Can you possibly add that too then? :)

**Pull request merged**
