### PR TITLE
Update old links in README.md

### PR DESCRIPTION
**Pull request by Thomva**
Fix old 'Creating Skins' and 'Hardware Compatibility' links.

### CODE REVIEW

**Comment by Be-ing** [comment]
Thanks. Could you rebase on the 2.3 branch?

**Comment by Be-ing** [comment]
Nevermind, I already did that: 418e5f4a46baa33eaf931f14c6c6c39ef03d3f9b

Thanks for taking the time to fix these.

**Comment by ronso0** [comment]
(contributor assignment)

**Comment by ronso0** [comment]
.. also for minimal co-authored commits

**Comment by Be-ing** [comment]
We have skipped that for trivial fixes like this before.

**Pull request closed without merging**
