### PR TITLE
Track->TrackDAO: Simplify changed/clean/dirty signals

### PR DESCRIPTION
**Pull request by uklotzde**
...and fixed some nasty warnings caused by `DlgTrackInfo`.

Passing a raw `Track*` pointer with the signal although we only need the `TrackId` was unnecessary and unsafe.

### CODE REVIEW

**Comment by daschuer** [comment]
LGTM, waiting for CI.
Did you consider to use signal signal connections?

**Comment by Holzhaus** [comment]
The CI fail is due to EOF in wcoverartlabel.cpp: https://travis-ci.org/mixxxdj/mixxx/jobs/651092762#L1232

**Comment by uklotzde** [comment]
> LGTM, waiting for CI.
> Did you consider to use signal signal connections?

No, I didn't think about it. Good point!

**Comment by uklotzde** [comment]
Done.

I have also removed the suspicious and highly unsafe Qt::DirectConnection arguments that may cause undefined behavior!! Please test.

**Comment by uklotzde** [comment]
The direct connections were definitely dangerous and invalid, because `BaseTrackCache` updates internal collections without any synchronization in the corresponding slots.

**Comment by daschuer** [comment]
There is nothing wrong with the direct connection here, because it is applied only for the signal to signal connection. 

Worst case after your change: 
Thread 1 changes the track and the Track::dirty is send
This is cached from Thread 2 and postponed as TrackDAO::trackDirty
This is cached at thread 3 and things are done in BaseTrackCache::slotTrackDirty 

Luckily Thread 2 and 3 are the same thread, so it does not really matter. 

In general the direct connection should preform better, so I would prefer to revert it. 
Will you? I don't really mind.

**Comment by uklotzde** [comment]
https://doc.qt.io/qt-5/signalsandslots.html
"You can connect as many signals as you want to a single slot, and a signal can be connected to as many slots as you need. It is even possible to **connect a signal directly to another signal. (This will emit the second signal immediately whenever the first is emitted.)**"

Using a signal-to-signal connection seems to do the right thing.

Shouldn't we rely on Qt to figure out the optimal and safe behavior instead of trying to micro-optimize without knowing what really happens behind the scenes?

**Comment by rryan** [comment]
> There is nothing wrong with the direct connection here, because it is applied only for the signal to signal connection.

Yea, @daschuer's right that they're safe. I think either signal-signal connections didn't exist when I wrote this (2010?) or I just didn't know about them :).

> **(This will emit the second signal immediately whenever the first is emitted.)**"

On its face that sounds like it wouldn't cause the issue @daschuer is worried about.

**Comment by uklotzde** [comment]
> > There is nothing wrong with the direct connection here, because it is applied only for the signal to signal connection.
> 
> Yea, @daschuer's right that they're safe. I think either signal-signal connections didn't exist when I wrote this (2010?) or I just didn't know about them :).
> 
> > **(This will emit the second signal immediately whenever the first is emitted.)**"
> 
> On its face that sounds like it wouldn't cause the issue @daschuer is worried about.

Correct. I did not consider the fact that both BaseTrackCache and AutoDjProcessor use a default connection to TrackDAO and thread-safety was always guaranteed.

The direct signal-to-signal connection should now do right thing without causing any confusion.

**Comment by uklotzde** [comment]
Broken signal slot connections

**Comment by uklotzde** [comment]
Ping

**Comment by daschuer** [comment]
Ups.. thank you for the reminder.

Before merge, let me clarify this:

A signal signal connections is nothing special compared to a signal slot connection. A signal is just a function generated by moc but it is called as slot in a signal signal connection.

Since signal calls are thread safe, it is perfectly OK to call them from any thread and so it is a good idea to use direct connections to avoid undedired utilizing a third thread.

> On its face that sounds like it wouldn't cause the issue @daschuer is worried about.

Currently the intermediate signal and the final slot are in the same thread. If this will not change with aoide, it can remain as it is currently. If we are unsure, let's keep the direct connection.

@uklotzde Can you finally verify this?

Thank you.

**Comment by uklotzde** [comment]
Since no slot is involved in a signal-to-signal connection this connection should implicitly be direct as the documentation states. What else is missing?

**Comment by daschuer** [comment]
I am sorry, the documentation is misleading, because it does not mention threads. 
To verify it, I have just done a small test. See attached.
Result: A signal signal is not implicit direct
[signaltest.txt](https://github.com/mixxxdj/mixxx/files/4237209/signaltest.txt)

.

**Comment by uklotzde** [comment]
@daschuer What does this file prove?

I have written a hello world with 3 objects on 3 threads: Sender, Relay, Receiver. Sender and Relay are connected with a signal-to-signal connection.

Inspecting the events in GammaRay shows that there is an unnecessary hop through the event loop of the Relay object if using Qt::AutoConnection:
SenderRelayAutoConnection

It can be avoided by using a Qt::DirectConnection for the signal-to-signal forwarding between Sender and Relay:
SenderRelayDirectConnection

Why do signal-to-signal connections do not use Qt::DirectConnection by default as expected and stated in the documentation???

**Comment by uklotzde** [comment]
Test sources: 
[Qt-CMake-HelloWorld-master.zip](https://github.com/mixxxdj/mixxx/files/4239085/Qt-CMake-HelloWorld-master.zip)

**Comment by daschuer** [comment]
I have filed a Qt Jira issue: 
https://bugreports.qt.io/browse/COIN-513

LGTM, Thank you.

**Pull request merged**
