### PR TITLE
Add Behringer-CMD-PL-1

### PR DESCRIPTION
**Pull request by yledoare**
New pull request with cleaner code

### CODE REVIEW

**Comment by yledoare** [comment]
Video demo :  https://youtu.be/XX5MXh1ZaXA

**Comment by Holzhaus** [comment]
Thank you for contributing! Please have a look at the pre-commit job on Travis CI. It shows that there are several code style issues with this PR.

Please apply this patch: https://gist.githubusercontent.com/Holzhaus/1489731b1797eb59d2c6fbb38c1b7594/raw/243ba82f943153666b40ab145f7103d2f9a27c56/behringer-cmd-pl-1.patch

    git apply < behringer-cmd-pl-1.patch

Also, you files this PR against the `master` branch. This means that it the mapping won't be part of Mixxx until 2.4 is release, which might take a long time. I suggest you rebase on 2.3 or 2.2 and change the target branch: https://github.com/mixxxdj/mixxx/wiki/Using-Git#targeting-another-base-branch

Also, starting with Mixxx 2.3, all controller mappings are now supposed to be documented in the Manual. This is necessary so that other users know how to use this mapping. We also need it to review it properly and check if the mapping makes sense and if the code matches the documentation.

Please fork the mixxxdj/manual repository, check out the `manual-2.3.x` branch and add documentation to the [`source/hardware/controllers` directory](https://github.com/mixxxdj/manual/tree/manual-2.3.x/source/hardware/controllers). Open the pull request and add the link to the PR description.

Here's an example how such documentation could look like: https://manual.mixxx.org/2.3/en/hardware/controllers/roland_dj_505.html (If you don't have schematic images and don't want to draw them yourself, just use the same numbering as in the controller's manual and document the buttons like that).

**Comment by Holzhaus** [comment]
Pinging @yledoare in case you didn't see my reply above.

**Comment by Holzhaus** [comment]
@yledoare Ping

**Comment by Holzhaus** [comment]
Superseeded by https://github.com/mixxxdj/mixxx/pull/3246.

**Pull request closed without merging**
