### PR TITLE
Fidlib update

### PR DESCRIPTION
**Pull request by daschuer**
This switches to a hopefully upcoming version of fidlib, including the Mixxx patches 
https://github.com/uazu/fidlib/pull/1

For us it just removed compiler warnings.
I have added Nicos tailing whitespace patch as well.

### CODE REVIEW

**Comment by rryan** [comment]
It sure would be nice to get rid of all the compiler warnings. OTOH it'd be nice to hear from @uazu first.

**Comment by uazu** [comment]
RJ Ryan wrote:
> It sure would be nice to get rid of all the compiler warnings. OTOH
> it'd be nice to hear from @uazu first.

I'm really sorry for not looking at these patches.  I've been
extremely short of time these recent months.  

I want to write some automated tests for 'fidlib' so that I can be
sure that things continue to work correctly as things are changed.  I
need to invest a few days of work to do this properly.

(Regarding my lack of time: We just built a small house on an
accelerated schedule within three months, we are about to move to
another city, and I have major paid-work deadlines coming up as well.)

**Comment by daschuer** [comment]
Ping! 
@uazu: Is this still on you todo list? 

@rryan: Maybe we should just merge it and adopt changes later if there are any upstream. 
Any thoughts?

**Comment by rryan** [comment]
> Ping! 
> @uazu: Is this still on you todo list?
> 
> @rryan: Maybe we should just merge it and adopt changes later if there are any upstream. 
> Any thoughts?

@uazu -- if you have some spare time we would love to get these changes merged upstream. For now I guess our copy can diverge from fidlib.

**Comment by rryan** [comment]
Thanks @daschuer and @nschloe !

**Comment by uazu** [comment]
Sorry I haven't dealt with this. I'm going to mark my fidlib as unmaintained. Time pressure from higher-priority life stuff means there is no way I'm going to find the time to maintain fidlib as I wish to, not for the foreseeable future. I will add links to the alternative version.

**Pull request merged**
