### PR TITLE
BPM rescan mode override

### PR DESCRIPTION
**Pull request by ywwg**
Create a new track right-click option to rescan a track's bpm and force either constant or nonconstant mode.  

Current workflow:
* track scans, bpm is off because the track is non-constant.
* open preferences, navigate to bpm, turn off "Assume constant tempo"
* right click track, reset bpm / beatgrid
* load track in deck
* open preferences, navigate to bpm, turn "assume constant tempo" back on

New workflow:
* track scans, bpm is off because the track is non-constant.
* right click track, select "Rescan BPM, Non-constant tempo"

This change does not do anything tricky with the actual preferences, it just overrides the bpm mode for the individual analysis.

current issue: no progress bar for the rescan.

### CODE REVIEW

**Comment by Be-ing** [comment]
I'm not sure we should merge this when we're in the process of getting rid of the distinction between these analyses.

> current issue: no progress bar for the rescan

Yeah, we could use a progress bar in the main window somewhere. Then we could get rid of the unintuitive Analyze library feature.

**Comment by ywwg** [comment]
> getting rid of the distinction between these analyses.

Even if we want to make everything into beatmaps, the analysis algorithms have extremely varying success rates with different types of tracks.  The const scanner obviously fails with disco, but the non-const scanner rarely understands when a bpm should be literally constant and fails often with ambient sections. Giving users a choice seems better.

In the meantime this is a big improvement for what is currently a really awkward process.

**Comment by Be-ing** [comment]
@crisclacerda will be working on detecting whether the analyzer should smooth the beat markers to a constant tempo or not. This can be done by comparing the distance between detected beats to a running average. This will allow for marking parts of the track as constant and others as nonconstant. The current distinction between constant versus nonconstant for entire tracks fails for many cases.

> In the meantime this is a big improvement for what is currently a really awkward process.

Yes, the current UX is very clunky. But on the other hand I don't want to create more work for what's already in progress. @crisclacerda what do you think? Should we merge this?

**Comment by crisclacerda** [comment]
I have agreed with @daschuer for my first evaluation (1/3) to be an improved beat/tempo detector that can handle varying tempo properly and that considers small unintended fluctuations to be a const tempo.

**Comment by ywwg** [comment]
if anything, I feel like this feature is more valuable if we're going to have a new detector.  Since we don't want to break master, we'll want to keep the existing detectors while the new one is being debugged and improved. We'll want to do a lot of testing and comparison of the new algorithm with the existing algorithms, so we'll want a fast way to rescan tracks that doesn't require diving into the preferences.

**Comment by ywwg** [comment]
@daschuer any thoughts?

**Comment by daschuer** [comment]
The basic idea of helping the analyzer when it is failing with default setting is nice.
I think we can keep this concept for the work of @crisclacerda 
We have already discussed this briefly.  

However we should implement the feature that is smoothly integrates into a new concept. 

In future we will have some more detector properties than just const and non const, so I am afraid the context integration does not live long. 

@crisclacerda @hacksdump What do you think about this. 

For me the use case would be to notice that the beat grid is wrong in a deck and I will also check that it is better afterwards in the deck. So I think this should become a deck feature. 
This solves the progress bar issue as well.

**Comment by crisclacerda** [comment]
Right, I think this will probably make sense and be useful down the road as well

**Comment by ywwg** [comment]
How about a submenu that is auto-populated by iterating over the list of known beat detectors?

**Comment by ywwg** [comment]
Or, it could be a button along with the other beat grid adjustment buttons next to the scrolling waveforms

**Comment by daschuer** [comment]
Since this is a subject of change, I would not put to much efforts into that. 
I assume in future we have a dedicated analyzer hint menu for various aspects. 
So a hard coded static solution is sufficient here for now.

**Comment by ywwg** [comment]
ok then I will work on getting the progress bar to work

**Comment by ywwg** [comment]
it sounds like we've changed our minds and are deleting the old bpm detectors entirely now.  So is this obsolete then?  (I disagree with this decision, but I guess hopefully the new scanner works)

**Comment by daschuer** [comment]
@crisclacerda 

(please correct me If I am wrong) 

I am afraid that we will always have tracks where the automatic detector may detect a floating tempo where it is actually const. This is only one problem I can imagine we can solve with a user input. 
So I think this PR is still pretty much valid. 

Does this fit to your ideas? Is the approach from this PR worse to follow? 

@ywwg 

> it sounds like we've changed our minds and are deleting the old bpm detectors entirely now. So is this obsolete then? (I disagree with this decision, but I guess hopefully the new scanner works)

What is the point you exactly disagree with?

**Comment by crisclacerda** [comment]
> @crisclacerda
> 
> (please correct me If I am wrong)
> 
> I am afraid that we will always have tracks where the automatic detector may detect a floating tempo where it is actually const. This is only one problem I can imagine we can solve with a user input.

Actually the new code does a very good job detecting when the tempo is actually constant.
On the tests I have run it only will detect a floating tempo for tracks that have a constant tempo when there is some arrhythmia going on, such as heavy effects of builds or a no beats part. 
So I think it's not really a problem detecting a floating bpm in these cases.

> So I think this PR is still pretty much valid.
> 
> Does this fit to your ideas? Is the approach from this PR worse to follow?

I think we could use this PR for setting the new detector preferences instead of a const tempo only rescan, if a track has a wrong downbeat or sections detected it may be useful to use this option to rescan without downbeats and so on... 
But actually in this case I don't think it would be actually necessary to rescan, but the idea from this PR is very much welcomed.

> it sounds like we've changed our minds and are deleting the old bpm detectors entirely now. So is this obsolete then? (I disagree with this decision, but I guess hopefully the new scanner works)

The "new" bpm detector is pretty much the exact same one, with only this new code to detect if the tempo is constant or not.

**Comment by crisclacerda** [comment]
> Actually the new code does a very good job detecting when the tempo is actually constant.
> On the tests I have run it only will detect a floating tempo for tracks that have a constant tempo when there is some arrhythmia going on, such as heavy effects of builds or a no beats part.
> So I think it's not really a problem detecting a floating bpm in these cases.

Okay, I just realized that this will mess up if there is another tracked synced to it. The const tempo may be useful after all.

**Pull request closed without merging**
