### PR TITLE
Skins: minimize Fx link invert button, put it next to link button

### PR DESCRIPTION
**Pull request by ronso0**
This is a pretty simple tweak that moves the rarely used Fx link inversion button next to the link mode button. With about one more library line, LateNight benefits the most from the additional v-space.

image

~~Addon:
desaturated Fx paramter controls in LateNight~~

### CODE REVIEW

**Comment by ronso0** [comment]
I'll revert the last commit (desaturated Fx controls in LateNight) and put it in #2342 , so this will be about link invert buttons only.

**Comment by daschuer** [comment]
Good idea. Some thoughts:
The red, compared to the green looks alarming in late night. On the other hand "something" different is required to destinuish two buttons. Did you considder other options? How about making the invert button quadratic with more distance or even round?

**Comment by ronso0** [comment]
Try LateNight with playing decks, Sync locked and a beatloop: all status indicators are alarmig red.
so the Super link blends in :)

I'll increase the spacing and test with white bg color, though.

**Comment by Be-ing** [comment]
Nice idea. It has long bothered me how much vertical space those took up but I didn't think of any good alternatives.

**Comment by ronso0** [comment]
@daschuer I noticed my post with screen snippets of the alternative colors somehow fell off the table.. I tried yellow but that was too close to green. White didn't work IMO because it wasn't strong enough considering the meaning of 'Link invert'.

**Pull request merged**
