### PR TITLE
Update google/benchmark library

### PR DESCRIPTION
**Pull request by uklotzde**
Our ancient version of the google benchmark library fails to build on some architectures (aarch64, ppc64le). This PR updates the code to the latest snapshot from GitHub (see COMMIT file in lib/benchmark) and migrates the manual build to CMake. Hopyfully this update will fix the build errors for the Fedora/RPMFusion build system.

http://koji.rpmfusion.org/koji/taskinfo?taskID=396501

**build.log (aarch64)**
```
[  2%] Building CXX object CMakeFiles/gbenchmark.dir/lib/benchmark/src/sysinfo.cc.o
ccache /usr/lib64/ccache/c++  -DHAVE_STD_REGEX -isystem /builddir/build/BUILD/mixxx-9c15f9eb257f4a65419d1e582f7907897bd28ed4/lib/benchmark/include  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fasynchronous-unwind-tables -fstack-clash-protection -fdiagnostics-color=auto -DNDEBUG   -pipe -std=gnu++17 -o CMakeFiles/gbenchmark.dir/lib/benchmark/src/sysinfo.cc.o -c /builddir/build/BUILD/mixxx-9c15f9eb257f4a65419d1e582f7907897bd28ed4/lib/benchmark/src/sysinfo.cc
{standard input}: Assembler messages:
{standard input}:429: Error: unknown mnemonic `mrc' -- `mrc p15,0,x0,c9,c14,0'
{standard input}:459: Error: unknown mnemonic `mrc' -- `mrc p15,0,x0,c9,c12,1'
{standard input}:503: Error: unknown mnemonic `mrc' -- `mrc p15,0,x0,c9,c14,0'
{standard input}:512: Error: unknown mnemonic `mrc' -- `mrc p15,0,x0,c9,c12,1'
{standard input}:568: Error: unknown mnemonic `mrc' -- `mrc p15,0,x0,c9,c13,0'
{standard input}:589: Error: unknown mnemonic `mrc' -- `mrc p15,0,x0,c9,c13,0'
make[2]: *** [CMakeFiles/gbenchmark.dir/build.make:213: CMakeFiles/gbenchmark.dir/lib/benchmark/src/sysinfo.cc.o] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/mixxx-9c15f9eb257f4a65419d1e582f7907897bd28ed4/cmake_build'
make[1]: *** [CMakeFiles/Makefile2:1012: CMakeFiles/gbenchmark.dir/all] Error 2
```

**build.log (ppc64le)**
```
ccache /usr/lib64/ccache/c++  -DHAVE_STD_REGEX -isystem /builddir/build/BUILD/mixxx-9c15f9eb257f4a65419d1e582f7907897bd28ed4/lib/benchmark/include  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mcpu=power8 -mtune=power8 -fasynchronous-unwind-tables -fstack-clash-protection -fdiagnostics-color=auto -DNDEBUG   -pipe -std=gnu++17 -o CMakeFiles/gbenchmark.dir/lib/benchmark/src/sysinfo.cc.o -c /builddir/build/BUILD/mixxx-9c15f9eb257f4a65419d1e582f7907897bd28ed4/lib/benchmark/src/sysinfo.cc
BUILDSTDERR: In file included from /builddir/build/BUILD/mixxx-9c15f9eb257f4a65419d1e582f7907897bd28ed4/lib/benchmark/src/sysinfo.cc:43:
BUILDSTDERR: /builddir/build/BUILD/mixxx-9c15f9eb257f4a65419d1e582f7907897bd28ed4/lib/benchmark/src/cycleclock.h: In function 'int64_t benchmark::cycleclock::Now()':
BUILDSTDERR: /builddir/build/BUILD/mixxx-9c15f9eb257f4a65419d1e582f7907897bd28ed4/lib/benchmark/src/cycleclock.h:82:23: error: 'int64' does not name a type; did you mean 'int64_t'?
BUILDSTDERR:    82 |   tbl &= -static_cast<int64>(tbu0 == tbu1);
BUILDSTDERR:       |                       ^~~~~
BUILDSTDERR:       |                       int64_t
BUILDSTDERR: make[2]: *** [CMakeFiles/gbenchmark.dir/build.make:213: CMakeFiles/gbenchmark.dir/lib/benchmark/src/sysinfo.cc.o] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/mixxx-9c15f9eb257f4a65419d1e582f7907897bd28ed4/cmake_build'
BUILDSTDERR: make[1]: *** [CMakeFiles/Makefile2:1012: CMakeFiles/gbenchmark.dir/all] Error 2
```

### CODE REVIEW

**Comment by Holzhaus** [comment]
Can you apply this patch to fix some deprecated declaration warnings?

```diff
diff --git a/src/test/sampleutiltest.cpp b/src/test/sampleutiltest.cpp
index 2aa26c8b3d..12ff6ce915 100644
--- a/src/test/sampleutiltest.cpp
+++ b/src/test/sampleutiltest.cpp
@@ -436,7 +436,7 @@ TEST_F(SampleUtilTest, copyReverse) {
 }

 static void BM_MemCpy(benchmark::State& state) {
-    size_t size = state.range_x();
+    size_t size = state.range(0);
     CSAMPLE* buffer = SampleUtil::alloc(size);
     SampleUtil::fill(buffer, 0.0f, size);
     CSAMPLE* buffer2 = SampleUtil::alloc(size);
@@ -452,7 +452,7 @@ static void BM_MemCpy(benchmark::State& state) {
 BENCHMARK(BM_MemCpy)->Range(64, 4096);

 static void BM_StdCpy(benchmark::State& state) {
-    size_t size = state.range_x();
+    size_t size = state.range(0);
     CSAMPLE* buffer = SampleUtil::alloc(size);
     SampleUtil::fill(buffer, 0.0f, size);
     CSAMPLE* buffer2 = SampleUtil::alloc(size);
@@ -468,7 +468,7 @@ static void BM_StdCpy(benchmark::State& state) {
 BENCHMARK(BM_StdCpy)->Range(64, 4096);

 static void BM_SampleUtilCopy(benchmark::State& state) {
-    size_t size = state.range_x();
+    size_t size = state.range(0);
     CSAMPLE* buffer = SampleUtil::alloc(size);
     SampleUtil::fill(buffer, 0.0f, size);
     CSAMPLE* buffer2 = SampleUtil::alloc(size);
@@ -583,7 +583,7 @@ TEST_F(SampleUtilTest, copy3WithGainSpeed) {
 */

 static void BM_Copy2WithGain(benchmark::State& state) {
-    size_t size = state.range_x();
+    size_t size = state.range(0);
     CSAMPLE* buffer = SampleUtil::alloc(size);
     SampleUtil::fill(buffer, 0.0f, size);
     CSAMPLE* buffer2 = SampleUtil::alloc(size);
@@ -602,7 +602,7 @@ static void BM_Copy2WithGain(benchmark::State& state) {
 BENCHMARK(BM_Copy2WithGain)->Range(64, 4096);

 static void BM_Copy2WithRampingGain(benchmark::State& state) {
-    size_t size = state.range_x();
+    size_t size = state.range(0);
     CSAMPLE* buffer = SampleUtil::alloc(size);
     SampleUtil::fill(buffer, 0.0f, size);
     CSAMPLE* buffer2 = SampleUtil::alloc(size);
```

**Review by Holzhaus — APPROVED** [review]
Thanks, looks good. Let's wait for the CI builds.

**Comment by uklotzde** [comment]
@Holzhaus Ping. Should be ready now after fixing the SCons build.

**Review by Holzhaus — APPROVED** [review]
Building this with scons and cmake both work fine and tests still pass. LGTM.

**Pull request merged**
