### PR TITLE
Move Beats et al. to mixxx namespace

### PR DESCRIPTION
**Pull request by JaviVilarroig**
This is just a technical PR. I have moved the Beats class, and associated ones, to the mixxx namespace.

### CODE REVIEW

**Comment by Be-ing** [comment]
Looks good to me. Anyone else want to take a look?

**Comment by Be-ing** [comment]
Do we have any guidelines on what belongs in the `mixxx` namespace? There doesn't seem to be any pattern that I have noticed.

**Comment by JaviVilarroig** [comment]
I understood from the [Coding guidelines](https://www.mixxx.org/wiki/doku.php/coding_guidelines) that we wanted top have a mixxx namespace to contain all the mixxx classes, at some point.
I also understood that we wanted to have classes moved to mixxx namespace when we work on them.
This is "in preparation" for #2372

**Comment by Holzhaus** [comment]
> Do we have any guidelines on what belongs in the `mixxx` namespace? There doesn't seem to be any pattern that I have noticed.

Most newer stuff goes into the mixxx Namespace. I think it makes sense to gradually switch over all our code to this namespace to avoid naming clashes with third party libraries.

**Comment by JaviVilarroig** [comment]
Done :)

**Comment by daschuer** [comment]
Thank you. That was quick :-)

**Pull request merged**
