### PR TITLE
GH Actions: fix Windows compiler caching

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by Be-ing** [comment]
```
 Post job cleanup.
C:\msys64\usr\bin\tar.exe --posix --use-compress-program "zstd -T0" -cf cache.tzst -P -C D:/a/mixxx/mixxx --files-from manifest.txt --force-local
/usr/bin/tar: C\:\\Users\runneradmin\\clcache: Cannot stat: No such file or directory
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Tar failed with error: The process 'C:\msys64\usr\bin\tar.exe' failed with exit code 2
```
???

**Comment by Holzhaus** [comment]
> ```
>  Post job cleanup.
> C:\msys64\usr\bin\tar.exe --posix --use-compress-program "zstd -T0" -cf cache.tzst -P -C D:/a/mixxx/mixxx --files-from manifest.txt --force-local
> /usr/bin/tar: C\:\\Users\runneradmin\\clcache: Cannot stat: No such file or directory
> /usr/bin/tar: Exiting with failure status due to previous errors
> Warning: Tar failed with error: The process 'C:\msys64\usr\bin\tar.exe' failed with exit code 2
> ```
> ???

I struggled with this as well. IIRC there is no way to use ccache with the default `tar` builtin because it doesn't support windows paths. I'll check.

**Comment by Holzhaus** [comment]
Does this work now?

**Comment by Be-ing** [comment]
no

**Comment by Be-ing** [comment]
@JosepMaJAZ IIRC you mentioned before that you got clcache working locally. How did you do that?

**Comment by Be-ing** [comment]
clcache says it's not adding anything to the cache:
```
Run clcache -s
clcache statistics:
  current cache dir         : Disk cache at C:\Users\runneradmin\clcache
  cache size                : 0 bytes
  maximum cache size        : 2,097,152 bytes
  cache entries             : 0
  cache hits                : 0
  cache misses
    total                      : 0
    evicted                    : 0
    header changed             : 0
    source changed             : 0
  passed to real compiler
    called w/ invalid argument : 0
    called for preprocessing   : 2
    called for linking         : 19
    called for external debug  : 847
    called w/o source          : 0
    called w/ multiple sources : 0
    called w/ PCH              : 0
```

**Comment by Be-ing** [comment]
Superseded by #3618

**Pull request closed without merging**
