### PR TITLE
resolved annoying pop up on clicking iTunes feature in library

### PR DESCRIPTION
**Pull request by garunaX**
With reference to 
https://bugs.launchpad.net/mixxx/+bug/1737668

### CODE REVIEW

**Comment by daschuer** [comment]
Please explain, how this pull request improved the situation.
What will be you next step. Thanks.

**Comment by garunaX** [comment]
There was an annoying pop up coming on selecting the itunes feature from library , on looking up the code i found there was an unnecessary call of a function, so removed it and resolved the error .

**Comment by daschuer** [comment]
The iTunes feature does not load the iTunes database anymore after your tests. 
Please prepare a solution that disables the iTune feature if the dialog is closed by cancel.

**Comment by Be-ing** [comment]
@daschuer that would still not really fix the original issue. As I explained in the bug report, the iTunes library location should be selected in the Library preferences. If it isn't, the iTunes feature should not be shown.

**Comment by daschuer** [comment]
That would require a bigger change and effects also the behaviour of the other external libraries for consistency and hides the iTunes knot from fist time users. IMHO we can effort a one time pop up as a short term solution.

**Comment by Be-ing** [comment]
I'd be in favor of changing the rest of the external libraries to behave the same way. What do we need a short term solution for? We have 6 months until the next feature freeze.

**Comment by garunaX** [comment]
Can we ask the user to put the file at a certain location and if mixxx finds the xml file then it displays the ITunes feature ?

**Comment by ronso0** [comment]
Before you closed this I spent my time after dinner to rebuild this onto mas.. main.
wasn't too hard, works well in Tracks and Crates currently.

I'll open a draft PR next days.

**Pull request closed without merging**
