### PR TITLE
CMake: Fix built-in keyfinder build

### PR DESCRIPTION
**Pull request by Holzhaus**
~~Current main doesn't build for me~~ Neither main nor 2.3 build at all for me.

### CODE REVIEW

**Comment by Be-ing** [comment]
I tested uninstalling libkeyfinder and I can't reproduce the build failure on Fedora.

**Comment by Holzhaus** [comment]
> I tested uninstalling libkeyfinder and I can't reproduce the build failure on Fedora.

I'm getting this error message:

```
make[2]: *** No rule to make target 'lib/keyfinder-install/usr/lib/libkeyfinder.a', needed by 'mixxx'.  Stop.
```

**Comment by Be-ing** [comment]
Can you reproduce that with the Ninja generator?

**Comment by Be-ing** [comment]
Both Unix Makefiles and Ninja generators work fine for me.

**Comment by Be-ing** [comment]
libkeyfinder installs to CMAKE_INSTALL_LIBDIR so I don't understand why it isn't working for you... https://github.com/mixxxdj/libkeyfinder/blob/main/CMakeLists.txt#L46

**Comment by Holzhaus** [comment]
Ok, I found the culprit. I had to delete the build directory (make clean didn't suffice). I'll close this.

**Comment by Be-ing** [comment]
Maybe you have discovered a bug in CMake. If you can reproduce it, report it upstream.

**Comment by Holzhaus** [comment]
I guess make clean doesn't apply to external projects, so keyfinder want rebuilt using the new path.

**Pull request closed without merging**
