### PR TITLE
KeyFinder: Add CMake ExternalProject support and bake it in by default 

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by uklotzde** [comment]
Downloading the sources of the external project doesn't seem to work:

```
-- Could NOT find KeyFinder (missing: KeyFinder_LIBRARY KeyFinder_INCLUDE_DIR)
```
```
CMake Error in CMakeLists.txt:
  Imported target "mixxx-keyfinder" includes non-existent path

    "/tmp/mixxx/cmake_build/lib/keyfinder-install/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
...
```

**Comment by uklotzde** [comment]
```
[ 15%] Performing build step for 'keyfinder'
gmake[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Scanning dependencies of target keyfinder
[  6%] Building CXX object CMakeFiles/keyfinder.dir/audiodata.cpp.o
[ 12%] Building CXX object CMakeFiles/keyfinder.dir/chromagram.cpp.o
[ 18%] Building CXX object CMakeFiles/keyfinder.dir/chromatransform.cpp.o
[ 25%] Building CXX object CMakeFiles/keyfinder.dir/chromatransformfactory.cpp.o
[ 31%] Building CXX object CMakeFiles/keyfinder.dir/fftadapter.cpp.o
[ 37%] Building CXX object CMakeFiles/keyfinder.dir/keyclassifier.cpp.o
[ 43%] Building CXX object CMakeFiles/keyfinder.dir/keyfinder.cpp.o
[ 50%] Building CXX object CMakeFiles/keyfinder.dir/lowpassfilter.cpp.o
[ 56%] Building CXX object CMakeFiles/keyfinder.dir/lowpassfilterfactory.cpp.o
[ 62%] Building CXX object CMakeFiles/keyfinder.dir/spectrumanalyser.cpp.o
[ 68%] Building CXX object CMakeFiles/keyfinder.dir/temporalwindowfactory.cpp.o
[ 75%] Building CXX object CMakeFiles/keyfinder.dir/toneprofiles.cpp.o
[ 81%] Building CXX object CMakeFiles/keyfinder.dir/windowfunctions.cpp.o
/tmp/mixxx/cmake_build/keyfinder-prefix/src/keyfinder/windowfunctions.cpp: In member function ‘double KeyFinder::WindowFunction::window(KeyFinder::temporal_window_t, int, int) const’:
/tmp/mixxx/cmake_build/keyfinder-prefix/src/keyfinder/windowfunctions.cpp:33:3: warning: control reaches end of non-void function [-Wreturn-type]
   33 |   }
      |   ^
```

```
[ 89%] Linking CXX static library libmixxx-lib.a
[ 89%] Built target mixxx-lib
[ 89%] Automatic MOC for target mixxx-test
Scanning dependencies of target mixxx
gmake[2]: *** No rule to make target 'lib/keyfinder-install/lib64/libkeyfinder.a', needed by 'mixxx'.  Stop.
gmake[2]: *** Waiting for unfinished jobs....
[ 89%] Building CXX object CMakeFiles/mixxx.dir/src/main.cpp.o
gmake[1]: *** [CMakeFiles/Makefile2:1252: CMakeFiles/mixxx.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 89%] Built target mixxx-test_autogen
gmake: *** [Makefile:183: all] Error 2
```

**Comment by Holzhaus** [comment]
@uklotzde can you retry with a clean build directory? It works fine on my machine.

**Comment by uklotzde** [comment]
- Clean local build fails after deleting `cmake_build`:
```
Scanning dependencies of target mixxx-test_autogen
Scanning dependencies of target mixxx
[ 89%] Automatic MOC for target mixxx-test
gmake[2]: *** No rule to make target 'lib/keyfinder-install/lib64/libkeyfinder.a', needed by 'mixxx'.  Stop.
gmake[2]: *** Waiting for unfinished jobs....
[ 89%] Building CXX object CMakeFiles/mixxx.dir/src/main.cpp.o
[ 89%] Built target mixxx-test_autogen
Scanning dependencies of target mixxx-test
gmake[1]: *** [CMakeFiles/Makefile2:1252: CMakeFiles/mixxx.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```

- Windows CI build fails:
```
cmake --build .
ninja: error: 'lib/keyfinder-install/lib/keyfinder.lib', needed by 'mixxx.exe', missing and no known rule to make it
Command exited with code 1
echo "*** FAILURE ***"
"*** FAILURE ***"
echo "*** DONE ***"
"*** DONE ***"
```

**Comment by poelzi** [comment]
I added the proper shell.nix additions in https://github.com/poelzi/mixxx/tree/nix-keyfinder-master
Since this branch has diverged from master a bit, I based it on master and should be merged after this one

**Comment by Holzhaus** [comment]
@uklotzde I think I found the issue. KeyFinder [hardcodes](https://github.com/ibsh/libKeyFinder/blob/master/CMakeLists.txt#L49) the `lib` directory name instead of using the system's dir (e.g. lib/lib32/lib64 on lines.)

**Comment by Be-ing** [comment]
@Holzhaus should that be fixed upstream in libKeyFinder? If so, please make a pull request upstream.

**Comment by uklotzde** [comment]
Works.

Any idea which build instruction causes the following warning?

```
gmake[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```

**Comment by Holzhaus** [comment]
Nope, I didn't see that warning on my machine. It thr build single threaded for the keyfinder build or everything else, too?

Unfortunately the keyfinder build doesn't work on Windows, probably because it hardcodes includes and lib names. I'll try to fix it upstream.

**Comment by poelzi** [comment]
I tested keyfinder with 23k songs and it works very nicely. Quite different results to QM on many tracks :)

**Comment by daschuer** [comment]
Which version of Mixxx did you start from? 

Do you have some significant tracks, where you are sure Taglib is correct and Mixxx not or vice versa?

**Comment by poelzi** [comment]
WFM
@daschuer I usually try to mix in key, so I looked at my old playlists. Now there are quite some jumps in there ;)
In general, I have the feeling that keyfinder gives me better choices.
I have some tracks with key notation directly from the label and the detected key hardly matches on any track, but this is with both algorithms. I think psy is quite hard to detect due the large amount of atonal sounds.

**Comment by uklotzde** [comment]
AppVeyor Windows build still fails!?

**Comment by Holzhaus** [comment]
> AppVeyor Windows build still fails!?

Yes, because FFTW is missing.

**Comment by Holzhaus** [comment]
Merge? It's still disabled on Windows/Appveyor until we add FFTW to the build env.

**Comment by Holzhaus** [comment]
Ping

**Comment by uklotzde** [comment]
Sorry for the delay. LGTM

**Comment by uklotzde** [comment]
@Holzhaus Are you aware that the slow KeyFinder analysis is now the default when built-in? I guess because of lexicographical ordering by name.

**Comment by Holzhaus** [comment]
I wasn't aware, but I think that's okay. The default settings should aim for the best quality. Users with slower machines can still switch to the old algorithm (similar to Rubberband/Soundtouch).

**Comment by uklotzde** [comment]
Unfortunately, it is *really* slow and takes ages to analyze tracks.

**Comment by Holzhaus** [comment]
Let's continue this discussion on Zulip, this PR is not really related because it only added CMake support. The actual integration happened in https://github.com/mixxxdj/mixxx/pull/2689. Maybe we can keep Keyfinder the default and just improve the performance.

**Pull request merged**
