### PR TITLE
Check pkg-config existence and version in mac

### PR DESCRIPTION
**Pull request by ferranlala**
Our build scripts did not check for pkg-config avaliability on mac. The issue manifested to me because the check for lilv uses pkg-config, so I got the error for missing lilv, not pkg-config.

### CODE REVIEW

**Comment by Be-ing** [comment]
Thanks for working on this. @rryan could you review this?

**Comment by rryan** [comment]
In the past, we've only required pkg-config for Linux and BSD, not macOS.

Looks like the lilv feature in build/features.py uses CheckForPKG (which uses pkg-config). 

@daschuer do you know if this was intentional? I think we might be able to fix this without requiring pkg-config on macOS, and instead switching that to a CheckLib.

**Comment by daschuer** [comment]
I have no Mac Os experiences. So it sounds that should be changed.

**Comment by rryan** [comment]
I tested locally and changing CheckPKG to CheckLib works fine on macOS (it found my homebrew lilv).

**Comment by ferranpujolcamins** [comment]
What about this line?:
`build.env.ParseConfig('pkg-config lilv-0 --silence-errors \
                                  --cflags --libs')`
Will it work without pkg-confiig installed?

**Comment by rryan** [comment]
> What about this line?:
> build.env.ParseConfig('pkg-config lilv-0 --silence-errors \ --cflags --libs')
> Will it work without pkg-confiig installed?

Sorry, should have mentioned that I deleted that line as well. It's not doing much for us anyway -- here's what I get from pkg-config on macOS with homebrew:

```
-I/Users/rjryan/.homebrew/Cellar/lilv/0.24.2/include/lilv-0 -I/Users/rjryan/.homebrew/Cellar/sratom/0.6.0/include/sratom-0 -I/Users/rjryan/.homebrew/Cellar/lv2/1.14.0/include -I/Users/rjryan/.homebrew/Cellar/sord/0.16.0/include/sord-0 -I/Users/rjryan/.homebrew/Cellar/serd/0.28.0/include/serd-0 -L/Users/rjryan/.homebrew/Cellar/lilv/0.24.2/lib -L/Users/rjryan/.homebrew/Cellar/sratom/0.6.0/lib -L/Users/rjryan/.homebrew/Cellar/sord/0.16.0/lib -L/Users/rjryan/.homebrew/Cellar/serd/0.28.0/lib -llilv-0 -ldl -lsratom-0 -lsord-0 -lserd-0
```

All those libraries are already linked to lilv-0 so they aren't necessary for Mixxx to link to directly:

```
otool -L ~/.homebrew/lib/liblilv-0.dylib
/Users/rjryan/.homebrew/lib/liblilv-0.dylib:
	/Users/rjryan/.homebrew/opt/lilv/lib/liblilv-0.0.dylib (compatibility version 0.0.0, current version 0.24.2)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/Users/rjryan/.homebrew/opt/serd/lib/libserd-0.0.dylib (compatibility version 0.0.0, current version 0.28.0)
	/Users/rjryan/.homebrew/opt/sord/lib/libsord-0.0.dylib (compatibility version 0.0.0, current version 0.16.0)
	/Users/rjryan/.homebrew/opt/sratom/lib/libsratom-0.0.dylib (compatibility version 0.0.0, current version 0.6.0)
```

**Comment by ferranpujolcamins** [comment]
Sorry for the delay, I changed to CheckLib. But how do I make it check that the minimum version is installed?

**Comment by Be-ing** [comment]
Thanks for working on this @ferranpujolcamins. I realized this problem is why 2.2 and master builds have been failing on macOS lately. Our macOS build environment does not have pkg-config installed, so checking for that would make builds fail. So I cherry-picked 4c2ecea into the 2.2 branch in 48a464d0fdde397cb5a14cdeb03291833a56b4af.

**Comment by ferranpujolcamins** [comment]
Nice, thanks!

**Pull request closed without merging**
