### PR TITLE
Numark Mixtrack VirtualDJ

### PR DESCRIPTION
**Pull request by TraITech**
Numark Mixtrack mapping like VirtualDJ.

### CODE REVIEW

**Comment by sblaisot** [comment]
Hi @TraITech 
Thanks for submitting this mapping.

When adding new file, please also add them to windows uninstaller: 
https://www.mixxx.org/wiki/doku.php/contributing_mappings#windows_installer_update

We will then review your code.

Thanks,

**Comment by TraITech** [comment]
Hi Sebastien, It's done:
https://github.com/TraITech/mixxx/commit/75cce54e7b8ca57988923d155dfc0de0f99f527f

---
REGARDS!
SCOLARI MAURICIO.

2017-06-09 13:14 GMT-03:00 Sebastien BLAISOT <notifications@github.com>:

**Comment by Be-ing** [comment]
Hi, thank you for submitting this. It looks like the current mapping in Mixxx for this controller is very outdated, so I think this mapping should replace that old mapping. Rename the files you are adding to overwrite the old Mixtrack mapping files and revert the last commit adding the new files names to the Windows uninstaller.

Taking a very brief look at your mapping's code, it looks like it has not been updated for the new effects and looping Controls in Mixxx 2.1. You can use a [master build](http://downloads.mixxx.org/builds/master/release/) or [compile the master branch yourself](https://mixxx.org/wiki/doku.php#compile_mixxx_from_source_code) to work on updating your mapping. Refer to the [wiki](https://mixxx.org/wiki/doku.php/updating_controller_mappings) for a list of what has changed for controller mappings for Mixxx 2.1. Unfortunately this controller has an usual effects layout that doesn't match very well with the design of the effects system. You could use two of the effects knobs as metaknobs of the first two effects in an EffectUnit and the other knob as the dry/wet (mix) knob of the chain.

**Comment by TraITech** [comment]
Hi, I don't completely agree with overwriting the existed scripts Those
have already been mapped for the mixxx functions. What I've done is
something completely different from what It already exists. I just mapped
the controller so that its functions work the same way as it does with
Virtualdj software.

I'm not intested in updating the files I've already uploaded so that it
works withh Mixx 2.1. If anybody is eager to do that, they can do so. I
know that this controller has an usual effects layout that doesn't match
very well with the design of the effects system as you mentioned. I've
chosen to have my own design of programming for the effects layout.

Thank you very much!

---
BEST REGARDS!
SCOLARI MAURICIO.

2017-06-10 14:18 GMT-03:00 Be <notifications@github.com>:

**Comment by Be-ing** [comment]
To keep the wiki consistently organized, I have consolidated the wiki pages for this controller back into [one page](https://mixxx.org/wiki/doku.php/numark_mixtrack) with different sections for the different mappings. I put links to the raw files in your GitHub repository for users to download.

I took a quick look through the JS code and saw a lot of complex, nonstandard behavior that is not documented on the wiki page. It is difficult to understand what is going on in the code and why it was designed the way it is. Personally I am doubtful that this mapping should be included in Mixxx if you are not willing to work on it further and explicitly designed it not to behave how Mixxx is designed. Mixxx is not VirtualDJ, nor is it any other software; it is its own program with its own design. IMO if a mapping is included in Mixxx it should follow the conventions of how Mixxx works as well as possible given the capabilities of the hardware. That said, there's no problem posting this mapping to the forum and keeping a link to the forum thread on the controller's wiki page.

I have [reached out](https://mixxx.org/forums/viewtopic.php?f=7&p=33231#p33231) to the author of another mapping for this controller that was designed for Mixxx 2.0 and asked him to open a pull request with that mapping.

What do others think?

**Comment by TraITech** [comment]
Hi, I agree with different sections for the different mappings in the wiki
pages. I maked a small update the section "Virtual DJ-like mapping".

In the other hand, I don't agree in not add "Virtual DJ-like mapping" to
next release. Mixxx is not VirtualDJ is true but wich is the problem in
make that Mixxx work like VirtualDJ? My new script not interfere on the
traditional old script.

I think that can by update the old script and add the new script "Virtual
DJ-like mapping".

---
BEST REGARDS!
SCOLARI MAURICIO.

2017-06-26 3:42 GMT-03:00 Be <notifications@github.com>:

**Comment by Be-ing** [comment]
In my opinion, that would create an impression that Mixxx aims to be a knock off or copycat of Virtual DJ, which is not the case. What do others think? Do you agree that including a mapping designed to work like another DJ program would create that impression?

**Comment by TraITech** [comment]
In my opinion, your thinking will restricted to other users the possibility
to use the Mixx like VirtualDJ.

---
REGARDS!
SCOLARI MAURICIO.

2017-06-26 18:59 GMT-03:00 Be <notifications@github.com>:

**Comment by radusuciu** [comment]
I think in general it's fine to have alternate mappings for controllers. I think that Mixxx's preferences UI is not the best at this however. I do also think that there is some value in there being one bundled mapping per controller as it encourages developers to work on improving existing mappings as opposed to creating new ones.

As far as the VirtualDJ issues goes.. I don't think there's a problem there - it's just a mapping of physical actions to manipulate music in ways that are similar across different pieces of software. Perhaps there shouldn't be explicit references to VirtualDJ or other software however. @TraITech, are there other descriptors you could use to express the difference between this mapping and the old one? Is it more complete?

@Be's point is that mappings should be designed to take advantage of Mixxx functionality to its fullest but I don't think that this is necessarily sacrificed here unless we decide that making full use of the revamped FX units is a necessary step for accepting contributions.

**Comment by Be-ing** [comment]
> Perhaps there shouldn't be explicit references to VirtualDJ or other software however. @TraITech, are there other descriptors you could use to express the difference between this mapping and the old one?

I think that would be a good solution. We could mention that it works similar to the Virtual DJ mapping on the wiki, but leave references to Virtual DJ out of the mapping title and description in the XML file. The mapping could be named something like "Numark Mixtrack (Alternate Mapping)".

> unless we decide that making full use of the revamped FX units is a necessary step for accepting contributions.

Considering we still don't officially have a beta release with the new effects UI, I think it's too early for that. After it is released I don't forsee that being an issue at all.

**Comment by radusuciu** [comment]
Alternate mappings make a lot of sense for smaller controllers like the Traktor X1, F1, Z1 etc.

If an alternate mapping for an all-purpose controller is just more complete then it probably should just replace the old mapping. If the differences are subtle and mostly matters of taste then it's less clear imo.

**Comment by Be-ing** [comment]
> If an alternate mapping for an all-purpose controller is just more complete then it probably should just replace the old mapping.

I agree, which is why I suggested replacing the old mapping with this one.

> If the differences are subtle and mostly matters of taste then it's less clear imo.

I think in these cases it would generally be better to merge the features into one mapping with options. It has been an issue that there are some controllers that have multiple mappings, none of which are complete, so users have to choose between which features are more important to them.

**Comment by TraITech** [comment]
>
> @TraITech <https://github.com/traitech>, are there other descriptors you
> could use to express the difference between this mapping and the old one?
> Is it more complete?

Are not there other descriptors because I programmed every function of
VirtualDJ in Mixxx, the controller work different with the functions
standars of Mixxx.

---
SALUDOS!
SCOLARI MAURICIO.

2017-06-26 21:25 GMT-03:00 Radu Suciu <notifications@github.com>:

**Comment by Be-ing** [comment]
As this PR is, it does not fit in with the Mixxx project. Mixxx 2.1 has been released with the new effects UI. @TraITech if you would like to update this mapping for Mixxx 2.1 and remove "VirtualDJ" from the name of the mapping then please reopen this PR and I would be happy to work with you.

**Pull request closed without merging**
