### PR TITLE
Include "util/assert.h" and add a missing semicolon

### PR DESCRIPTION
**Pull request by rrrapha**
This fixes a compilation error when the DEBUG_ASSERT code is reached.

### CODE REVIEW

**Comment by uklotzde** [comment]
This code doesn't seem to be covered by our CI build. Strange that no macOS user ever it in a custom build.

@daschuer Do we require Raphael to formally sign the contributor agreement for this obvious and simple fix? @rrrapha If you plan to contribute more code in the future it wouldn't help us to keep track.

LGTM.

**Comment by rrrapha** [comment]
@uklotzde Yes, I plan to submit some BSD compatibility fixes soon.

**Comment by daschuer** [comment]
I think yes, even a single semicolon change can be a huge amount of work, be cause a new contributor has to take the hurdle of setting up the build environment. We should use the normal process. 

Thank you for all that @rrrapha :-)

So would you mind to sign 

https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ

and comment here when done?

**Comment by rrrapha** [comment]
done

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
