### PR TITLE
CMake: Reconfigure to update git-dirty version when source files are changed

### PR DESCRIPTION
**Pull request by Holzhaus**
Creating a file that is not part of the mixxx build won't cause reconfiguration or relinking:
```
$ touch ../src/somefile.cpp
$ make
[  2%] Built target benchmark
[...]
[ 99%] Built target gtest_main
[100%] Built target benchmark_main
```

Touching a file that *is* part of the mixxx source will cause reconfiguration/relinking, but not because the version changed but because the file date of that file changed. This would be the same without reconfiguration.

```
$ touch ../src/mixxx.cpp
$ make
-- Optimization level: portable
-- Enabling SS2 CPU optimizations (>= Pentium 4)
-- Git describe: 2.3-beta-3885-g1bdc0103c9
-- Git commit date: 2021-05-06T12:24:10+02:00
-- Git branch: cmake-git-version
-- Git commit count: 8169
[...]
-- Build files have been written to: /home/jan/Projects/mixxx/build
Consolidate compiler generated dependencies of target benchmark
[  2%] Built target benchmark
[ 14%] Built target mixxx-lib_autogen
Consolidate compiler generated dependencies of target mixxx-lib
[ 14%] Building CXX object CMakeFiles/mixxx-lib.dir/src/mixxx.cpp.o
[ 14%] Linking CXX static library libmixxx-lib.a
[ 86%] Built target mixxx-lib
[...]
[ 87%] Linking CXX executable mixxx-test
[ 99%] Built target mixxx-test
Consolidate compiler generated dependencies of target mixxx
[ 99%] Linking CXX executable mixxx
[ 99%] Built target mixxx
[...]
[100%] Built target benchmark_main
```

If you actually change a source file, the version is updated:
```
$ printf "\n" >> ../src/mixxxapplication.cpp
$ make
-- Optimization level: portable
-- Enabling SS2 CPU optimizations (>= Pentium 4)
-- Git describe: 2.3-beta-3885-gc44b87007c-modified
-- Git commit date: 2021-05-06T13:09:23+02:00
-- Git branch: cmake-git-describe-dirty-fix
-- Git commit count: 8169+
-- Found ccache: /usr/bin/ccache
[...]
-- Build files have been written to: /home/jan/Projects/mixxx/build
Consolidate compiler generated dependencies of target benchmark
[  2%] Built target benchmark
[...]
Consolidate compiler generated dependencies of target mixxx-lib
[ 14%] Building CXX object CMakeFiles/mixxx-lib.dir/src/mixxxapplication.cpp.o
[ 14%] Building CXX object CMakeFiles/mixxx-lib.dir/src/util/versionstore.cpp.o
[ 14%] Linking CXX static library libmixxx-lib.a
[ 86%] Built target mixxx-lib
[...]
[ 87%] Linking CXX executable mixxx-test
[ 99%] Built target mixxx-test
Consolidate compiler generated dependencies of target mixxx
[ 99%] Linking CXX executable mixxx
[ 99%] Built target mixxx
[...]
[100%] Built target benchmark_main
```

### CODE REVIEW

**Comment by Holzhaus** [comment]
@daschuer I made the change to only update the version file if it's different, please have a look.

We could get rid of the reconfiguration if we move this logic to a separate cmake script that we add as a PRE_BUILD target using add_custom_command. I can do that, but it will only work for version.h and the windows RC file. If we do this, we can't use git information for CPACK because without reconfiguration, that information would be out of date. If we keep the reconfiguration, then this change would be pointless and just add unnecessary complexity.
What do you prefer?

**Comment by daschuer** [comment]
PRE_BUILD is not available with all build systems.
But the hack with a non existing file as dependency works for all.

**Comment by Holzhaus** [comment]
> PRE_BUILD is not available with all build systems.
> But the hack with a non existing file as dependency works for all.

The Mixxx lib target could depend on the custom target, so it's not an big issue. But I agree that this solution is easier to grasp, allows using the git stuff in the cpack configuration and the build performance is neglible (at least for me).

**Comment by Holzhaus** [comment]
So ready to merge? We can still improve things later on.

**Comment by daschuer** [comment]
Unfortunately that does not work. I have edited res/schema.xml and build via make. mixxx is rebuild, but the is no dirty flag in the about-box. :-/ 
I guess we really need to implement the second project idea for this. 
Or drop the idea of adding -modified to the package file.  

I am in favor of the later, because deploying a modified package is just a corner case.

**Comment by Holzhaus** [comment]
Please try again, CMake always rebuilds now for me.

**Comment by daschuer** [comment]
With make?

**Comment by Holzhaus** [comment]
Yes

**Comment by daschuer** [comment]
Ah yes, now we reconfigure always.

**Comment by Holzhaus** [comment]
> Yes

What I meant is that it always reconfigured. It doesn't rebuild without changes.

**Comment by daschuer** [comment]
So we have the reconfigure penalty on every build of ~1s! Just for maintaining the -modified package extension that no one cares for. 

We can add a target that always runs and 
add the cmake call 

COMMAND $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

configure_file() command deals with the file time already. I think you can remove the temp file hack.

**Comment by Holzhaus** [comment]
Replaced by #3841.

**Pull request closed without merging**
