### PR TITLE
LateNight :: repair [Channel2] xFader button, use button templates

### PR DESCRIPTION
**Pull request by ronso0**
https://bugs.launchpad.net/mixxx/+bug/1801363
This ~~is just~~ started as a quick fix for the scenario when a user switches to 2 decks and the xFader orientation of deck 1 or 2 differs from default, like 1=Right and 2=Center. In that case the xFader buttons would stay visible in 2-decks mode until decks 1/2 are assigned default xFader side again.

Just added <Size> attribute to PushButton. This is necessary since scalemode="STRETCH_ASPECT" was added to most buttons in #1858 but buttons wouldn't show up without Size attribute.

**Edit** I continued #1858 and replaced inline PushButtons with templates wherever it makes sense (almost everywhere, except some special cases, and except in sampler templates as that's fixed in #1840 already).

**Edit2** This also fixes blurred beatgrid icons next to the waveforms.

### CODE REVIEW

**Comment by rryan** [comment]
On macOS I don't see any issue with the xfader orientation buttons (even resized to its minimum size)

screen shot 2018-11-02 at 11 29 16 pm

**Comment by rryan** [comment]
Hm, just noticed the star rating widgets don't render or work (they don't seem to receive any mouse input).

**Comment by rryan** [comment]
> Hm, just noticed the star rating widgets don't render or work (they don't seem to receive any mouse input).

Nevermind, they do work (you need a track loaded). The mouse input is weirdly offset though.. clicking on star N causes a rating of N+1 to be set.

**Comment by ronso0** [comment]
This is just a quick fix for the scenario when a user switches to 2 decks and the xFader orientation of deck 1 or 2 differs from default, like 1=Right and 2=Center

The issue doesn't exist with 4 decks (no scalemode="STRETCH_ASPECT" there), but with 4 decks those buttons should look blurry when the skin is auto-sclaed to 4K. Will update those buttons, as well.

**Comment by ronso0** [comment]
I carried on with those HiDPI fix in #1858 and moved from inline PushButtons to button templates.

Just in case we're in a hurry for 2.2, and no one finds the time to thoroughly review, the essential quick fix for the orientation button(s) can https://github.com/mixxxdj/mixxx/pull/1881/commits/6308d13a942b549cebc65ec4f781d56af1b51148 and https://github.com/mixxxdj/mixxx/pull/1881/commits/4b43c06c1ee56492f93335bf8e5845763c3c0ac5 can be cherry-picked

**Comment by ronso0** [comment]
(rebased, cleaned up commit messages)

**Comment by rryan** [comment]
Ok, sorry for being dense. It works! LGTM

**Pull request merged**
