### PR TITLE
Make two plain controls a PushButton to make them Midi accessable.

### PR DESCRIPTION
**Pull request by daschuer**
This is an old error, discovered by a debug assert introduced here: 
https://github.com/mixxxdj/mixxx/pull/1362

### CODE REVIEW

**Comment by ronso0** [comment]
> Hi @ronso0
I have fixed the failed assertion
However [Library],MoveFocusBackward is not effected.

Thanks, I can test this in the next days!

**Comment by Be-ing** [comment]
ping @ronso0, have you tested this?

**Comment by ronso0** [comment]
> ping @ronso0, have you tested this?

scheduled for tomorrow morning..

**Comment by ronso0** [comment]
It's working, LGTM

**Comment by daschuer** [comment]
Thank you for testing.

**Pull request merged**
