### PR TITLE
fix(controllers): `engine.beginTimer(ms, string)` would evaluate the code immediately instead of after `ms`

### PR DESCRIPTION
**Pull request by Swiftb0y**
From what I can tell, this must've been broken for years in 2.4 (075664d792 to be exact)...
The resulting behavior until now was that the string was evaluated immediately instead of after the timeout and when the timer was recurring, it was never evaluated after (since the stored result value was likely not callable).

The first commit fixes the mapping, the second commit fixes the API call, the third commit is some refactoring required for the fourth commit which will cause a `logOrThrowError` when the callback was not callable.

### CODE REVIEW

**Comment by Swiftb0y** [comment]
fyi the pre-commit issue is from eslint because I touched a legacy mapping. Lets just ignore the eslint failure.

**Comment by daschuer** [comment]
This aims to fix https://github.com/mixxxdj/mixxx/issues/11932 Let's wait for @todx0 for confirmation.

**Comment by Swiftb0y** [comment]
they already did for the actual fix (second commit). the fourth is just to spot issues like this sooner in the future.

**Review by daschuer — APPROVED** [review]
OK, Than it should be safe to merge. 
Thank you for the fix.

**Comment by Swiftb0y** [comment]
Thank you.

**Pull request merged**
