### PR TITLE
track/serato/markers: Fix parsing of position values

### PR DESCRIPTION
**Pull request by Holzhaus**
The cue position values in the `Serato Markers_` tag use the same strange
4-byte encoding of 24 bit values that track colors use.

Prerequesite for #2526.

### CODE REVIEW

**Comment by uklotzde** [comment]
They did this on purpose. Bastards ;)

**Comment by Holzhaus** [comment]
Yeah, I wonder if it's to prevent reverse engineering or if it's for some kind of "poor man's integrity check".

**Comment by Holzhaus** [comment]
Most of the changes are renaming variables/function, modifying comments and fixing the tests. The actual changes to the position parsing are small: https://github.com/mixxxdj/mixxx/pull/2671/files#diff-ac00585ee405309584d3c94b489ffe17R122-R150

**Comment by Be-ing** [comment]
I wouldn't assume it's on purpose. It could be accidental, but it happens to work with whatever code they're using.

**Comment by Be-ing** [comment]
CI succeeded :+1:

**Comment by Be-ing** [comment]
Maybe the tests in [Uwe's branch](https://github.com/uklotzde/mixxx/tree/seratomarkers2_metadata) will work now with this fix?

**Comment by uklotzde** [comment]
I'll retry to parse and dump the tag obtained from a FLAC file.

**Comment by Holzhaus** [comment]
AFAIK the FLAC files only have Serato Markers V2, not the first version, so it should be unaffected.
https://github.com/Holzhaus/serato-tags/blob/master/docs/fileformats.md#flac

**Comment by uklotzde** [comment]
Still differences. The first bytes match, then some differences occur.

Applying the base64 encoding twice on some parts of their marker data is a strange decision by Serato.

Original:
```
YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtAABTZXJhdG8gTWFya2VyczIAAQFBUUZEVDB4UFVn
QUFBQUFFQVAvLy8wSlFUVXhQUTBzQUFBQUFBUUFBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA
```

Parsed and dumped:
```
YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtAABTZXJhdG8gTWFya2VyczIAAUFRRkRUMHhQVWdB
QUFBQUVBUC8vLzBKUVRVeFBRMHNBQUFBQUFRQUEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

**Pull request merged**
