### PR TITLE
Effect parameter knobs: implement ValueScaler::Integral, snap value to int

### PR DESCRIPTION
**Pull request by ronso0**
If the effect manifest sets `ValueScaler::Integral` for a parameter knob, the resulting values snap to integers.
This adds a new ControlBehaviour type `ControlLinSteppedPotBehavior`.
Parameter changes are accumulated, and as soon as the new value would snap to the next int it's adopted.

Currently only helpful for LV2 plugin parameters, for example `# Stages` knob of LV2 Calf Phaser.

### CODE REVIEW

**Comment by ronso0** [comment]
@davidchocholaty Should the Range knob of the PitchShift effect snap to ints? 0,1, 2

**Comment by ronso0** [comment]
I changed the "Stage" parameter of the built-in Phaser effect to int.

**Review by daschuer — CHANGES_REQUESTED** [review]
Thank you. This works already great. 

When first read the code I had expect a real snapping instead of a rounding. 
Something like a snap threshold of 0,4 and 0,6 that helps to avoid a jumping between two values with weak hardware at 0.5.
Not sure if this is required. 

When writing the value directly, I can still select fractional values. I guess this is OK, because there is no reason to do it.

**Comment by ronso0** [comment]
uff, had my git objects and other stuff screwed up after a hard power cut will pushing the fixup :| (and couldn't just start over becasue of unpushed branches.)

This branch is now building again.

> When first read the code I had expect a real snapping instead of a rounding.
Something like a snap threshold of 0,4 and 0,6 that helps to avoid a jumping between two values with weak hardware at 0.5.
Not sure if this is required.

You mean implementing a hysteresis? Not sure if we really need that.
Note that I consider this only a first step anyway. Finallly it would be great if the Echo's Time knob would snap if Quantize is enabled, though there are a few 'obstacles' to overcome. I'll comment in #8756

**Comment by daschuer** [comment]
> You mean implementing a hysteresis?

Yes that was my idea. However normally the hardware manufacturer should take care to take noise from the signal, that we have a stable midi value. So just a suggestion and nothing that will hold up this PR. Just give a hint when you consider this as ready.

**Review by daschuer — APPROVED** [review]
Thank you.

**Comment by davidchocholaty** [comment]
> @davidchocholaty Should the Range knob of the PitchShift effect snap to ints? 0,1, 2

Sorry for my later response. Probably not because if the range knob should be in the continuous mode, which is set by the [semitonesMode](https://github.com/mixxxdj/mixxx/blob/3990cabc52dbb3d715b83258f0ead81697529fc8/src/effects/backends/builtin/pitchshifteffect.cpp#L92), it is expected, that turning the knob will work linearly. Making the scale in ints implies multiplying the value 2 (which means two octaves) many times to make the changes unrecognizable and feel like a linear response of the knob for the user. IMHO the change on the `Integral` scale makes sense only in the case of semitones mode but based on allowing to use of the continuous way makes it impossible.

**Comment by ronso0** [comment]
Yeah, somehow that's the same obstacle like with the Echo effect: Time is continuous, only if an assigned group has beats AND Qunatize is enabled the value would 'snap' when the effect is processed.
So, in order to get both continuous and integral/steppd parameters by changing the value scaler on the fly parameters would need to be connected (only one-way in this example).
I'm kind of into (trying to understand) the Mixxx effect backend, maybe there's an easy way. If not, I'll drop it, it would be  useful for only two effects.

**Pull request merged**
