### PR TITLE
pre-commit: Some minor improvements and switch to GitHub Actions

### PR DESCRIPTION
**Pull request by Holzhaus**
Related Zulip discussion: https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/pre-commit/near/213702475

### CODE REVIEW

**Comment by Holzhaus** [comment]
All green on my repo: https://github.com/Holzhaus/mixxx/runs/1271741304?check_suite_focus=true#step:5:81

**Review by uklotzde — APPROVED** [review]

**Comment by uklotzde** [comment]
Waiting for a second opinion before merging.

**Review by poelzi — COMMENTED** [review]
LGTM

**Review by poelzi — APPROVED** [review]

**Review by daschuer — APPROVED** [review]
LGTM, Thank  you.

**Comment by JoergAtGithub** [comment]
I just commited to https://github.com/mixxxdj/mixxx/pull/3132 and got a mail with the following content:
grafik

The results link points to: https://github.com/mixxxdj/mixxx/actions/runs/315402573

**Pull request merged**
