### PR TITLE
engine: Minor refactor to prefer simplified ranged-for-loop

### PR DESCRIPTION
**Pull request by tcoyvwac**
A minor refactor to reduce codebase size using standard algorithm functions.
_(Previously this PR used the C++20 ranged version, but removed it because sadly the Apple Clang buildchain does not support it)_ :crying_cat_face:

### CODE REVIEW

**Review by Swiftb0y — COMMENTED** [review]
I appreciate the willingness to refactor, but in this case I'm seriously doubting the usefulness. The resulting code is harder to read and understand for beginners while providing no obvious performance benefit. The only change that would've made sense IMO is to replace the oldschool for loop with index lookup by a ranged-for loop...

**Comment by Swiftb0y** [comment]
I'm quite a noob on C++20 ranges, so I would've liked to see that implementation at least, maybe the resulting code would've had better ergonomics.

**Comment by daschuer** [comment]
I agree with @Swiftb0y. 

I think it is worth to eliminate all `int i` loop counters in our code base that are only used to access the container element. I am also open to do that as a (normally unwanted) mass refactoring, because the change is trivial, easy to review and possible conflicts easy to resolve. 

Introducing lambdas is not that trivial. They need a thoroughly review and manual tests. Doing that  in a mass refactoring will bind resources we can make better use of, in introducing new features ir fixing bugs.

**Comment by tcoyvwac** [comment]
> I'm quite a noob on C++20 ranges, so I would've liked to see that implementation, maybe the resulting code would've had better ergonomics.

So @Swiftb0y, the ranges version of this PR is still available to view here: https://github.com/mixxxdj/mixxx/commit/625656d16ba46e9519aa1df27ec1b655386449f5 :mag:  
It is much better, in my humble opinion, than the old-school verbose begin/end iterator version. However It was removed rapidly, as the [current version used of Apple Clang does not have C++20 ranges yet.](https://github.com/mixxxdj/mixxx/actions/runs/4059020686) :crying_cat_face:

**Comment by tcoyvwac** [comment]
@daschuer I understand that the project has limited bandwidth to review refactoring PRs especially if it uses the standard library or lambda syntax. I apologise; it was on me to explain the reason for the code in this PR & what the specific lambda does, so to ease the review of the PR. :heavy_check_mark: 

---

It is great @daschuer that we are in agreement that: :smile_cat: 
> it is worth to eliminate all int i loop counters in our code base that are only used to access the container element.

As the [popular computer science joke goes](https://martinfowler.com/bliki/TwoHardThings.html): 
> "There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors".

As you already know, the recommended common practice is by using the standard library, or some ranges form of code, it helps greatly to eliminate the even potential of variable-counter problems, and provides a uniform syntax to express _"intent"_ of code. 

From: [C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines)

> * [P.1: Express ideas directly in code](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rp-direct)
  _(Hint: Please note, [the "example - bad" code-snippet](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#example-bad) near like-for-like matches the [form / code previously used in codebase](https://github.com/mixxxdj/mixxx/commit/625656d16ba46e9519aa1df27ec1b655386449f5#diff-c9305122ac896279c70f48c3d6778a125e981a0174127a207743dcfd3ebed3b7L871-L876))._ :mag: :crying_cat_face:   

> * [ES.1: Prefer the standard library to other libraries and to “handcrafted code”](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-lib)

> * [SL.con.3: Avoid bounds errors](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rsl-bounds)

Maybe helpful for @Swiftb0y:
> From Sonarsource: 
> * [Code smell fix: STL constrained algorithms with range parameter should be used when iterating over the entire range.](https://rules.sonarsource.com/cpp/RSPEC-6197)

**Comment by tcoyvwac** [comment]
> I don't think anything trumps the simplicity of a "for-loop; if; return" construct.

I agree with you a lot @Swiftb0y! :wink: 
With containers, it is so basic and common, and drives so much software in so many pieces of code!
So much so, that this "construct" was standardised in the C++ language... I am very confident you can guess what it is! :smile_cat: 

["Possible implementation of std::find_if"](https://en.cppreference.com/w/cpp/algorithm/find)
```cpp
for (; first != last; ++first)
    if (p(*first))
        return first;
return last;
```
So you see @Swiftb0y, this `"for-loop; if; return" construct` you demonstrated does have a formal name in C++. That is `std::find_if`! :wink: 

`std::find_if` has been around for a very long time (Year 1989+), and made more streamlined in C++11. So do you wonder if it is wise, when using a C++ container, to let beginners use the pre-1989 C `"for-loop; if; return"` construct, vs the standardised way of `std::find_if`. 

```cpp
for (const ChannelInfo* pChannelInfo : m_channels) {
    if (pChannelInfo->m_pChannel->getGroup() == group) {
        return pChannelInfo->m_pChannel;
    }
}
return nullptr;
``` 

In your code example @Swiftb0y, one beginner would already:
* understand `std::vector` _(or some sort of standardised container)_
* referencing / dereferencing pointers
* predicates; what it is and how to use it

So why teach & continue non-standard coding methods in the project's codebase over the standardised way? I can understand & relate, if one has not used `std::find_if` often; I think it would be wiser to help beginners upgrade from their very old non-standard method, foster growth, and say "oh snap, that is a `std::find_if`!"...

To quote: [C++ Core Guidelines - P.1: Express ideas directly in code](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#example-good) 

> A C++ programmer should know the basics of the standard library, and use it where appropriate. Any programmer should know the basics of the foundation libraries of the project being worked on, and use them appropriately. [...]

We both agree that the construct is basic and simple, so let's look out for areas where we can use the basics of the standard way in the codebase in C++. :wink:

**Comment by tcoyvwac** [comment]
> The only thing that I still dislike about that is the conversion from `std::end(m_channels)` to `nullptr` (`return (it != std::end(m_channels)) ? (*it)->m_pChannel : nullptr);`

I agree with you again @Swiftb0y :wink: . 
Your comment however has _activated my trap ~~card~~_ question:

* (In this codebase & code-section), what is the purpose of `nullptr`; what does `nullptr` supposed to "represent"?

---

In your kind example, there are two code-patterns that seasoned C++ developers can see:

```cpp
for (const ChannelInfo* pChannelInfo : m_channels) {
    if (pChannelInfo->m_pChannel->getGroup() == group) {
        return pChannelInfo->m_pChannel;
    }
}
return nullptr;
```

1. The "maybe-type" pattern: `if(truthful_predicate) { return constructed_datatype } else {return null-type};`
  * https://github.com/mixxxdj/mixxx/blob/main/src/engine/enginemaster.cpp#L887-L889
  * https://github.com/mixxxdj/mixxx/blob/main/src/engine/enginemaster.cpp#L922-L924
  * https://github.com/mixxxdj/mixxx/blob/main/src/soundio/soundmanager.cpp#L408-L414
2. The located-item exist or not-exist pattern: `if(in_all_exists(value)) { return true } else {return false };`
  * https://github.com/mixxxdj/mixxx/blob/main/src/engine/controls/enginecontrol.cpp#L115-L116
  * https://github.com/mixxxdj/mixxx/blob/main/src/engine/sync/enginesync.cpp#L501-L504


If one uses [S.O.L.I.D ](https://en.m.wikipedia.org/wiki/SOLID)principles, this area of code has maybe already violated `S` for [Single-responsibility principle](https://en.m.wikipedia.org/wiki/Single-responsibility_principle).

The conversion code highlights this awkwardness. that piece of code-block must do above two responsibilities at once. To become some sort of better C++ "standardised" (code),  the point is to represent some sort of "maybe" state. In C++17 and later, we have an official datatype to represent this state. It is `std::optional`.

How to use it in the codebase with your current recommended code example... well, that is slightly outside of the scope of this current PR. But it is important down-the-line in making the code more closer to C++ standardisation (of algorithms & datatypes).

**Comment by Swiftb0y** [comment]
I fully agree with most of the points you make. The only thing I disagree with is that in order to understand `std::find_if` you don't need to know about the three points you mentioned (std::vector, pointers, predicates). Thus using `std::find_if` still requires a deeper understanding of C++ than the for of loop (which would be understood by pretty much anyone coming from common beginner languages such as python or js). 

I also acknowledge that the design of the entire function and even the class is flawed ($O(n)$ search to lookup an object by key?!?!).

The biggest problem I have with the proposed change (which also introduces the unwanted complexity) is the intermingling / conversion between the plain pointer-based code and the iterator based code. Unfortunately due to the member function signature, you can't change that without a bigger refactoring. For that reason I prefer the iterator-less function because the introduced shift in paradigm only introduces additional complexity.

**Comment by daschuer** [comment]
For me the issue is not the use of `std::find_if()` it is very useful to when initialize a value as const like: 
`const int result1 = std::find(vector.begin(), vector.end(), value);`
It is the use of the lambda and the extra conditional assignment when returning. 
You can spot instantly the control flow in an for .. if .. return control flow due to proper indention. This is of a high value but IMHO broken in your proposal.   
The other thing is that a mass refactoring for introducing `std::find_if()` has IMHO not enough benefits for us, compared to the hassle with review and merge conflicts.

**Comment by daschuer** [comment]
Can you rebase this on main? The Arch linux build failure has been fixed.

**Review by daschuer — APPROVED** [review]
LGTM. Oh, never mind this is only a small commit.

**Comment by daschuer** [comment]
Thank you.

**Comment by tcoyvwac** [comment]
Ah, just saw your update. Thanks for merging, grateful! :smile_cat:

**Pull request merged**
