### PR TITLE
BPM: allow to round / snap decimals

### PR DESCRIPTION
**Pull request by ronso0**
This should simplify BPM matching with short, high-res pitch faders on controllers.
Snap/round to
* integers
* nnn.N
* nnn.nN

BPM is snapped only if the pitch fader is off center to avoid unintended and unnecessary pitch shift.

image

requested here https://mixxx.discourse.group/t/pitch-fader-sensitivity-round-value-to-1/25140
https://bugs.launchpad.net/mixxx/+bug/1979822
One of the features for which I did quick and dirty test, which turned out to be rather easy to implement*.

What do you think?

*In case there are regressions with the sync engine / too much complications there or elsewhere I overlooked, the alternative would be a helper function in `common-controller-scripts.js`

### CODE REVIEW

**Review by daschuer — CHANGES_REQUESTED** [review]
I have read thought the original post and it looks like that snapping to a whole number is only a solution for this problem:
"We cannot adjust to a MATCHING bpm, because of the quantitation of the pitch slider to 127 steps"

Some calculations: 

With an 8% slider range range, we have 
110.4 - 129.6 for a 120 BPM track a step width of 0.15 BPM 
and for 50 %  60 - 180 BPM and a step width of 0.94 BPM 

So the proposed solution does not help using a wide slider range, if the other track is played at 120.5 BPM and the current track is at 120 BPM, because you have not enough steps on your slider and it will always snap to 121 even though you select a snapping of 0.1 decimals. 
You cannot even hit every 0.1 step on a 8 % rate slider. 

The whole BPM assumption does also only help with electronic tracks, that are recorded on a whole number. 

In the BeatUtils, we assume threshold a 25 ms offset before a double beat is notable. This is 0.25 % for a 10 s transition. A 127 Steps +- 8 % has 0,12 % which works well enough and a 50 %  Slider has 0,78 % which is too coarse. 

Conclusion: 
* With a 8 % slider this issue is only a visual thing 
* With a high range slider, or poor crackling hardware, the snapping does not solve the underlying issue. 

I think If we snap to the other Track's BPM and at whole factors of it, the musical issue is solved. 
Due to the snapping to whole BPMs in the BPM detector, this should be also a whole number. 

However, this does not solve the visual issue at any other BPM value. Do we have any? If yes a solution would be to introduce a adaptive Slider range that uses the 127 Midi steps to go in fixed BPM steps. But this IMHO a crazy idea not worth to implement it. This does also not help for dusty crackling sliders. 

What do you think?

**Comment by ronso0** [comment]
Thanks for your thorough consideration.

> I have read thought the original post and it looks like that snapping to a whole number is only a solution for this problem:
> "We cannot adjust to a MATCHING bpm, because of the quantitation of the pitch slider to 127 steps"

https://mixxx.discourse.group/t/pitch-fader-sensitivity-round-value-to-1/25140 is about the Hercules Inpulse 200 which has the pitch sliders' LSB/MSB mapped, so I _assume_ it definitely has a notably higher resolution than 127, even if thats's just 256.
Also, the second example here

> With an 8% slider range range, we have
110.4 - 129.6 for a 120 BPM track a step width of 0.15 BPM
and for **50 % 60 - 180 BPM and a step width of 0.94 BPM**

would of course not be covered by snapping because it's kinda unrealistic to do proper BPM matching with short GUI or controller faders. For such a case (wide range, short sliders, Sync not desired) users would need to adjust the perm rate(_small)_up amount in the preferences and use the buttons (GUI or mapped).
For 127-steps sliders with a +-8% range and a 180 BPM track the step would be 0.22 BPM, so snapping to integer BPM would work, wouldn't it.

> * With a 8 % slider this issue is only a visual thing

Tbh I rarely manage (or intend) to transition within 10 s. In my exxperience, this is also uncommon with electronic music.

FWIW, I have high-res faders and I suffered the issue as well (first world problem, of course). Matching 160 and 164 BPM may be possible but it's tedious, so snapping the first decimal would be really helpful. 

Edge case I enounter now & then: match 160 to 160.08 BPM (both kinda hand-made with MPCs)
without snapping this was hard, I'd rather keep nudging the second track until the mix is done.
With snapping I'dtry to change 160.08 > 160.0, or change both to 160.1

I didn't consider "dusty crackling sliders" tbh (skipping values, or randomly changing values by itself), with those you'd have lost anyway and look for another solution : p

**Comment by Be-ing** [comment]
I agree with @uklotzde, I don't think this feature makes a lot of sense. If someone wants to get finer control out of a small fader (or a large fader), they can already decrease the tempo range of the fader.

**Comment by daschuer** [comment]
OK the quantization problem can be probably neglected, with a double precision slider.
There seems to be a mechanical quantization problem instead ....

Hover isn't is solved with snapping to the synced BPM? 

What is the value to snap to any full integer BPM?

**Comment by ronso0** [comment]
> What is the value to snap to any full integer BPM?

I added that just for completeness.
For me (if I had the Inpulse) it would help to adjust to external sources (playing b2b) quickly.

**Comment by daschuer** [comment]
>>   Hover isn't is solved with snapping to the synced BPM?

> What synced BPM?

I mean the BM value, the sync feature would pick when you press sync. 
https://github.com/mixxxdj/mixxx/blob/d209239967f2f4709d03c05261f8fef07ba47f75/src/engine/sync/synccontrol.cpp#L456

Sure, that will not work for external sources.

**Comment by daschuer** [comment]
I did not realize that it was a 14 bit slider and that it is actually to difficult, to hit the desired value. 

With an 8% slider range range, we have
110.4 - 129.6 for a 120 BPM track a step width of 0,0012 BPM
and for 50 % 60 - 180 BPM and a step width of 0,0074 BPM

But you see it becomes even more a visual issue than a musical.
In case of a 120.00 bpm Display (Shade)  you can see only 2 k steps of you 16 k steps, almost "analog" slider and 192 steps on a 120.0 bpm Display (Tango)

On the other hand the interference issue due to similar snapping frequency and 7 bit quantization will be no issue.  
And if we reduce the step count to 0.1 you will have only a minimum musically regression but your eyes are pleased. 
Not sure if this is a good trade off

To solve the original musically issue, we just need to make sure that at least the the beat sync tempo and all harmonics are also snapped. It would be nice to have this feature without controller. 

The relative short GUI slider has the interference issue and should IMHO not be snapped to visual values.

**Comment by ronso0** [comment]
Oh, it seems the dicussion got unnecessarily complex:
@daschuer is right, changing the engine bpm is the wrong place. It's the rate/rate_ratio that should snap -- snapped bpm is the result then.
I fixed that. Though, this requires taking a small detour via engine bpm to snap the rate.

However, this PR resulted from the quick test implementation, though a completely working solution requires more changes, e.g. to the rate temp buttons, as well as allowing to snap back to rate center even if that doesn't match the snap grid.
I guess that's the complication @uklotzde feared.

So I'll drop this, the effort / benefit balance is just not worth my time (but don't delete it so others can test if they like).
Instead I'll eventually try to add the script helper, so only the incoming rate change is computed, and users can implement it in mappings at their own responsibility, for whatever use case they need it for.

Thanks for all your feedback!

**Pull request closed without merging**
