### PR TITLE
Help menu: link to online manual only, remove obsolete 2.2 manual

### PR DESCRIPTION
**Pull request by ronso0**

### CODE REVIEW

**Comment by Be-ing** [comment]
We should update the manual build instead of removing it.

**Comment by ronso0** [comment]
IIRC we agreed on _not_ delivering the 3.6MB manual with the binaries?
(the manual is not mentioned anywhere in /packaging/ therefore I seem to recall correctly)
Btw, currently even opening the local manual is broken on Linux.

With the web version we can keep updating and improving the manual without users requiring to update, and we probably won't make a point release just for an updated manual.

**Comment by Be-ing** [comment]
> IIRC we agreed on not delivering the 3.6MB manual with the binaries?

Huh? Where was that discussed?

Viewing the manual should not require Internet access. The current situation requiring manual rebuilds of the PDF is hacky but we won't be improving that until 2.4 with #3047.

**Comment by ronso0** [comment]
I thought that was discussed when @hozhaus revamped the entire manual process.

**Comment by Holzhaus** [comment]
We could include the PDF manual by adding a CMake option for it that fetched the PDF from downloads.mixxx.org at configure time. But we can also not include it, I'm fine with it either way.

**Comment by ronso0** [comment]
okay, nevemind.

https://github.com/mixxxdj/mixxx/blob/main/src/widget/wmainmenubar.cpp#L574
if (resourceDir.cd("../doc/mixxx") && resourceDir.exists(MIXXX_MANUAL_FILENAME)) {

this fails because the manual is compressed and installed as Mixxx-Manual.pdf.gz

continued in https://mixxx.zulipchat.com/#narrow/stream/109176-documentation/topic/2.2E3.20manual.20PDF

**Pull request closed without merging**
