### PR TITLE
LateNight: Reposition spinnies so they can be bigger

### PR DESCRIPTION
**Pull request by ywwg**
Hey @ronso0 and @nopeppermint, I've noticed the spinnies in latenight are quite small, but it looks like there's enough room to make them bigger, even at the smallest window size.  Here's a quick change I made to do so.

image

### CODE REVIEW

**Comment by nopeppermint** [comment]
Hi @ywwg 
I prefer to have more space for the Title name instead of the spinnies.
And with so large spinnies you won't be able to show all the buttons in the topbar of the decks (vinyl control, 4 effect units), there is not enough space !

**Comment by ronso0** [comment]
> but it looks like there's enough room to make them bigger, even at the smallest window size

I suggest to exclude the top row where we have optional vinyl controls, and the title row needs to host elapsed AND remaining time if the user needs it. The 'time' widgets can be tuned though as the ellipsis in your screenshot appears to early IMO

IF we stick with the current minimal size (1280x600) the decks will get quite tight then. But looking at 
http://gs.statcounter.com/screen-resolution-stats/desktop/worldwide and
https://www.w3schools.com/browsers/browsers_display.asp
we can probably increase the minimal size for LateNight as we still have Deere and Tango that are supposed work on netboook screens. What about **1366x768**?

**Comment by nopeppermint** [comment]
> 1366x768?

this is the maximal resolution of my 11'6 netbook I am using for djing (with latenight)
I am against increasing minimal size and I do not need a bigger spinny.

**Comment by Be-ing** [comment]
I agree, 1366 x 768 is the minimum screen resolution we should design for.

**Comment by ywwg** [comment]
I feel like at the size they are at, the spinnies are pretty useless -- I can't see the cover art or interact with the spinny very well.  Perhaps turning off the spinny setting should cause them to disappear instead of being replaced with just the cover art?  That would free up space.

In general, it's unreasonable to expect that all possible features work at all resolutions.  Even on my 1920x1080 laptop I can't keep the effects window up all the time.

**Comment by ywwg** [comment]
what about

image

**Comment by ywwg** [comment]
I'm mostly really happy with all the work y'all have done to keep my "ugly" skin up to date!  (People complained about the design in reviews, oh well).  The new settings look great.  But it was feeling like the skinny was becoming a unloved appendix :)

**Comment by Be-ing** [comment]
> In general, it's unreasonable to expect that all possible features work at all resolutions.

4 decks and 4 effect units should be usable at 1366 x 768. Currently only Tango accomplishes this.

**Comment by Be-ing** [comment]
I don't really like how little space this leaves for the track title and time displays either. I think it may be possible to find a solution that satisfies everyone, but I'm not sure what to suggest. That may require a more extensive redesign of the decks.

There is a lot of wasted space around the cover art:
screenshot from 2018-07-02 13-28-47

Somehow the spinning indicator line looks blurry on my 3840 x 2160 screen. I'm confused why this happens considering the images are SVGs...
screenshot from 2018-07-02 13-26-40

**Comment by ywwg** [comment]
Yeah I noticed the coverart size problem, I'll have to fix that so it fills the space.

Personally I would like to move the time indicators so they overlay on the waveform overview in small text on the bottom (with a little shadow so it's readable).  That would free up the space for the song title.  The timing numbers are similar information to the overview and it would probably look pretty good.  I'm not sure if that kind of overlay is easy to accomplish, it would probably require coding.  I'm happy shelving this PR until a better solution is found.  

I also suggested what if turning the spinnies off freed up that space completely instead of showing the cover art?  What do people think of that?  

For every screenshot of the screen looking really cluttered, I could show you how much empty space there is on a modern laptop -- I think we should keep small screens in mind but I don't think they should preclude making things look good for users with bigger screens.  I agree with having a basic requirement for the smallest size ("4 decks at 1366") and letting users with more space add in more stuff on top of that.

**Comment by nopeppermint** [comment]
> I also suggested what if turning the spinnies off freed up that space completely instead of showing the cover art? What do people think of that?

I vote for having 3 options: spinny, cover art, or nothing

**Comment by ywwg** [comment]
svg blur issues are often caused by rendering happening at one rez and then a scale operation happening afterward.  In browsers there's hoops you have to jump through to get things done right. this might be a bug in the spinny code, detecting the virtual instead of real pixel size.

**Comment by ywwg** [comment]
> spinny, cover art, or nothing

do the skin settings screens support radio buttons, or dropdowns, or other non-bool settings widgets?

**Comment by nopeppermint** [comment]
> do the skin settings screens support radio buttons, or dropdowns, or other non-bool settings widgets?

I suggest one button for displaying spinny/cover art on decks, and the a related "sub-button" to change between spinny or cover.

```
if(display_spinny_cover)
{
  if(spinny_or_cover)
  {
   //display spinny
  }
  else
  {
    //display cover
  }
}
else
{
 //display no spinny and no cover art on decks
}
```

**Comment by nopeppermint** [comment]
what's if we add a toogle for a big/small(current) spinny?

**Comment by ywwg** [comment]
I'd prefer not to have to support too many layouts.  off/cover/spinny seems like a good compromise

**Comment by ronso0** [comment]
yeah, off/cover/spinny is fine.
two checkboxes Spiny & Cover Art would be sufficient IMO: spinny.xml is stack of spinny/cover/spinny-background, spinny and cover are toggled by simple visibility connections

resized spinny vectors 330ed29f8310376d5cc8bc424035a7c6d053ffbe
resized spinny efaefbca77a57b2d18e70ab7850542d1b6598461

**Comment by ronso0** [comment]
I just tried it (was more work I initially thought, but it was itching me so I finished it):
latenight-update-spinny-2 2_spinnycover

latenight-update-spinny-2 2_cover

latenight-update-spinny-2 2_empty

@ywwg If you like it check out those commits:
use simple COs for all Spinny/CoverArt combinations fde785bca4ca7b0fdfc1ce964c55e7963615da81
make skin settings buttons more efficient 9d514e0d88f911332af5f8a13405f2000f77f01a

**Comment by ronso0** [comment]
based on a 1360x768px screen, the minimal size would be 1344x668px:
latenight-update-spinny-2 2_minsize_timefix

that screen is shot with 2c8351f0b6784b4ed64abaa256151f57b6ab5943 LateNight: desgin for 1366x768, fix time display 

@ywwg I also like the idea to put time and duration on the overview. It should be optional and the vertical and horizontal positon should be configurable like for HotCues and Loop markers.

**Comment by nopeppermint** [comment]
before:
bevore
now:
after

I do not like it, those spinnies are now way to big for me, I prefer the small ones.

**Comment by nopeppermint** [comment]
@ronso0  btw. the logic of the skin settings button "crossfade" is somehow inverted on your branch https://github.com/ronso0/mixxx/commits/latenight-spinny
checkmark => crossfader not visible
empty square => crossfader visible

I think it may be caused on changes in https://github.com/ronso0/mixxx/commit/9d514e0d88f911332af5f8a13405f2000f77f01a

**Comment by ronso0** [comment]
fix spinny height with xfader enabled, fix xfader toggle a55e973276a9ad76ef6ca620ec9d28493e920c1f

@ywwg I'm posting those commits here to cherry-pick simply because I have a few items on my LateNight ToDo* I'm working on anyway and don't like to interfere with another PR (wasted a lot of time with rebasing recently)

* xfader assign buttons are buggy, lower_half.xml needs a rework, ...

**Comment by ronso0** [comment]
@ywwg  I picked up the big spinny and made them optional in #1754 Please have a look.

**Comment by ronso0** [comment]
#1754 was merged so this can be closed.
Thanks for the idea and the first steps!

**Pull request closed without merging**
