### PR TITLE
signalinfo: Add explicit double casts

### PR DESCRIPTION
**Pull request by Holzhaus**
Unfortunately, we are far away from being able to enable -Wconversion,
but this is a very small first step towards that.

### CODE REVIEW

**Review by uklotzde — APPROVED** [review]
LGTM

**Comment by daschuer** [comment]
I am in doubt that -wconversion is good idea. I am afraid this will clutter our code with tons of unnecessary casts like this one here. There is nothing wrong by deviding a double by an integer. The x86 instruction set as even a command for it:
FIDIV
https://www.felixcloutier.com/x86/fdiv:fdivp:fidiv

Did you expect that this reveals some code smell?

I am afraid the introduced hassle to make the code warning free is not worth it.

**Comment by Holzhaus** [comment]
`-Wconversion` only warns if the implicit conversion may change value: https://gcc.gnu.org/wiki/NewWconversion

I do think there are probably bugs hidden in our code. For example, there a places where we assign a long int to an int, etc. I think it's reasonable to require an explicit cast in such cases.

**Comment by daschuer** [comment]
Ah Ok, I misread the code.  
It warms because it is a div by a 64 bit integer and that dies not fit into the resulting double.

Maybe we did something wrong using SINT for channel count. How about using just int, and remove this cast here?

**Pull request merged**
