### PR TITLE
LateNight: half Screen width Waveform

### PR DESCRIPTION
**Pull request by nopeppermint**
follow up to 
LateNight: half Screen width Waveform #1567
but rebased on branch 2.1

### CODE REVIEW

**Comment by nopeppermint** [comment]
now it looks like this:
waveform_half

**Comment by nopeppermint** [comment]
I am done here, please test/review:
- might it be possible to add this to 2.1.1 ?
- any comments @Be-ing @ronso0 @daschuer

**Comment by ywwg** [comment]
This feature runs counter to the foundational concept of the latenight skin, which is stacking all the waveforms so the beats line up :/.  I prefer the idea of saving height by cutting the vertical size in half and displaying mono data.

**Comment by nopeppermint** [comment]
> This feature runs counter to the foundational concept of the latenight skin, which is stacking all the waveforms so the beats line up :/. I prefer the idea of saving height by cutting the vertical size in half and displaying mono data.

@ywwg  it's an option, if you don't like it you don't have to use it, for me it's useful this way ..

Why not add both options?

one's we have the "Skin Settings Menu" as well in Latenight  #1591 we have space for a lot of options ;-)

**Comment by daschuer** [comment]
The 2.1 branch is only open for Bugfixes.
This one is a feature, so it should IMHO got to master.

**Comment by ywwg** [comment]
every additional option creates:

- ongoing maintenance as skins and the program evolve over time
- documentation including screenshots, tooltips, and text translations
- regular testing to make sure it hasn't broken or doesn't break at weird screen sizes
- more testing to ensure it interacts with all of the other options for the skin
- adds visual clutter and can make the interface more confusing (we already have users reporting that mixxx looks hard to use)

And since I'm the one who created this skin originally and maintained it for several years I'm sensitive to my original intent and use-case

**Comment by ronso0** [comment]
> This feature runs counter to the foundational concept of the latenight skin, which is stacking all the waveforms so the beats line up :/. I prefer the idea of saving height by cutting the vertical size in half and displaying mono data.

I agree. Sorry for all the work being done before dicussing this.. https://github.com/mixxxdj/mixxx/pull/1567#issuecomment-377550115
I think it was a premature screenshot of [Rounded Corners skin](https://www.mixxx.org/forums/viewtopic.php?f=8&t=9443) where I saw this first..it just makes sense to cut the waves in halve and keep the ability to beat-match by eye.

**Comment by ronso0** [comment]
> we already have users reporting that mixxx looks hard to use

Really? I promote Mixxx to Vinyl and digital digital alike, and they all get along very nicely and quickly...in the end it's just the controller mapping taht matters. Can't tell about mouse/key DJs though

**Comment by Be-ing** [comment]
> we already have users reporting that mixxx looks hard to use

This will always happen with such a specialized application no matter what we do. Saying "it's hard to use" isn't really helpful. Identifying specific issues users get confused about and finding ways to solve them does help.

**Comment by esbrandt** [comment]
> And since I'm the one who created this skin originally and maintained it for several years I'm sensitive to my original intent and use-case

Really?
Just disappointing

**Comment by Be-ing** [comment]
I agree with @ywwg that this is not a good solution to the issue of using more vertical space than ideal. However I disagree that just because someone originally made a feature one way means they should indefinitely have veto power over how it develops further.

**Comment by Be-ing** [comment]
Also, when the waveforms are no longer stacked on top of each other and directly comparable visually, it doesn't make much sense to keep them up top together. They would be more useful next to their respective overview waveforms. Getting Deere to support both those designs and look decent with each was a giant pain and continues to be a big maintenance burden, so I do not think it is a good idea to do that again with another skin.

**Comment by nopeppermint** [comment]
> However I disagree that just because someone originally made a feature one way means they should indefinitely have veto power over how it develops further.

thanks !

> I agree. Sorry for all the work being done before dicussing this.. #1567 (comment)
I think it was a premature screenshot of Rounded Corners skin where I saw this first..it just makes sense to cut the waves in halve and keep the ability to beat-match 4 decks by eye while reducing the required screen height.

> I agree with @ywwg that this is not a good solution to the issue of using more vertical space than ideal. 

so, then maybe not..

I hope there is more chance for #1623 to get merged ;-)

Does someone has a starting point for me, where this half size/mono waveform transformation might be?
Is this in an xml file or is there cpp coding required? 
It doesn't look like this could be done in waveform.xml ..

**Comment by daschuer** [comment]
> However I disagree that just because someone originally made a feature one way means they should indefinitely have veto power over how it develops further.

In general I would agree. Unfortunately this is not that easy when it comes to design. Here, artists are involved, which in general do not accept changes because they will destroy the art. 

I have experiences from my real live, where we hired a designer for a task. he came up with tree design alternative and we should select one. My boss wants a mixture of 1 and 2, but the designer makes clear without a doubt that this was not possible. And even my boss pays the bills, I think the designer was right, the mixture looked ugly. 

In design issues we need a head of design.

**Comment by ronso0** [comment]
@nopeppermint Would you mind closing this PR? (can be re-opened any time)
It has been rejected for now, and it would be nice to reduce the number of open PRs.

**Pull request closed without merging**
