### PR TITLE
Update manual PDF with latest build from https://mixxx.org/manual/2.1/en/Mixxx-Manual.pdf

### PR DESCRIPTION
**Pull request by rryan**

### CODE REVIEW

**Comment by Be-ing** [comment]
There are some diagrams I did not get a chance to make for the new Using Microphones chapter. Is there a way to automatically hide those from the PDF build instead of showing a placeholder?

**Comment by Be-ing** [comment]
screenshot from 2018-04-15 16-52-45

**Comment by rryan** [comment]
> There are some diagrams I did not get a chance to make for the new Using Microphones chapter. Is there a way to automatically hide those from the PDF build instead of showing a placeholder?

I think we'll need to do it in the manual repo first then update this PDF.

**Comment by Be-ing** [comment]
Okay, I'll comment them out in the manual repo and open a new PR

**Comment by Be-ing** [comment]
Superceded by #1615

**Pull request closed without merging**
