### PR TITLE
.gitignore: qtscript-bytearray/*.cc moc files

### PR DESCRIPTION
**Pull request by drlight-code**

### CODE REVIEW

**Comment by daschuer** [comment]
now the Travis build fails on Ubuntu precise: 

/home/travis/build/mixxxdj/mixxx/src/engine/sidechain/networkstreamworker.cpp:16: multiple definition of `NetworkStreamWorker::s_networkStreamWorkerState'

**Comment by flv0** [comment]
fixed. thanks for reminding and sorry for not checking back myself.

**Comment by daschuer** [comment]
Thank you for th fix. 

Before we can merge this, we need you permission.  
Please sign https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ

and comment here when done,

**Comment by flv0** [comment]
Done! Out of interest, can someone elaborate what this section refers to exactly?

* You grant to Mixxx and to recipients of Mixxx a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer your contributions.

I am neither a lawyer nor a native english speaker, I just wonder what the word patent license means in this context. Thanks!

**Comment by daschuer** [comment]
I am as well neither a lawyer nor a native English speaker.

My interpretation is like that: 
If you own a patent and you contribution contains parts of the patented invention, you allow us to use it without any extra restriction.

**Pull request merged**
