### PR TITLE
Enforce a consistent pointer alignment (*/&) style

### PR DESCRIPTION
**Pull request by uklotzde**
To fix consistent violations as found in rekordboxfeature.cpp (#2119)

Reference: https://www.mixxx.org/wiki/doku.php/coding_guidelines#variables

### CODE REVIEW

**Comment by daschuer** [comment]
I think you want to set 
PointerAlignment = Left
as well.

**Comment by uklotzde** [comment]
PointerAlignment = Left is inherited from the Google style. We only set options that differ from this base style.

**Comment by daschuer** [comment]
Ah Ok, should we add a comment about that, or set it just for document purpose?

**Review by daschuer — APPROVED** [review]
Thank you. LGTM

**Pull request merged**
