### PR TITLE
disable track table editing after clicking selected track by default on macOS

### PR DESCRIPTION
**Pull request by Be-ing**
As discussed in #1561

### CODE REVIEW

**Comment by daschuer** [comment]
I like to keep the current behavior, because it will not change the Mixxx behavior for user that are upgrading from 2.0.

**Comment by Be-ing** [comment]
Just because something was in the last release does not mean it is set in stone for future releases. The old behavior has caused many users trouble, so I think it should be turned off by default/

**Comment by daschuer** [comment]
Yes but that would be the expected behavior, editing is still there as usual even for the users who cannot handle this. 
By the way: we have @ronso0 and @ywwg sharing this opinion.

**Comment by Be-ing** [comment]
If a user is confused by this behavior being turned off by default, they can ask on the forum or Zulip and we can simply tell them to check the box in the preferences. On the other hand, if this is kept on by default and a user does not understand the behavior, it is likely that they will accidentally edit the metadata of their track. IMO that is a much worse consequence than telling someone to click a checkbox.

**Comment by daschuer** [comment]
My vote is not to merge this. Since this does not effect me personally, can someone else decide here?
The underlying issue is fix with both defaults, we are talking about disabling library edit during upgrade.

**Comment by uklotzde** [comment]
I was surprised that suddenly in-place editing has been disabled and I needed to press Ctrl+F2 after clicking on a column. I was aware of the previous discussions and remembered what I had to do as a workaround. But the regular user? I suppose we will get lots of support requests about this changed default behavior. 

I use this feature a lot for quick tag fixes and with metadata export enabled. It never caused me any troubles, so I didn't quiet understand what the actual issue was.

If we want to introduce a new feature that affects the workflow we should do it in multiple steps or stages:
1. Add a new feature and make it optional, i.e. allow to enable it by changing a preference setting
2. Enable the new feature by default if it **has proven to be useful for the majority of users** and allow to disable it optionally
3. Drop the legacy behavior if it has become obsolete and cumbersome to maintain

I would prefer if we only implement the 1st step in Mixxx 2.1. Changing the default behavior should only be considered if the new feature has been adopted by the majority of users and not only by a few users who reported issues. That's not statistically relevant.

Open question: How do we know about which preference settings are actually preferred by our users? Identifying, collecting, and analyzing these kind of application usage metrics as anonymous feedback is a separate (and bigger) task.

**Comment by ronso0** [comment]
I'm sure I elaborated on this already, as well, but I fail to find my post since this discussion now spreads over 3 (or more?) PRs.

> If a user is confused by this behavior being turned off by default, they can ask on the forum or Zulip and we can simply tell them to check the box in the preferences.

Maybe this is true for experienced Mixxx users, but new users won't miss that feature and therefore wouldn't go to Zulip. Maybe at some point -once they are used to basic Mixxx usage- and if they are curious they'd go to Preferences having a look what can be adjusted apart from basic device and interface settings. 

> On the other hand, if this is kept on by default and a user does not understand the behavior, it is likely that they will accidentally edit the metadata of their track.

Right, that might happen. That's why we have an option now, so if a few users experience track editing to be unused, or even unwanted because it's buggy with touchpad, there will be an urge to go looking in the Preferences to change this behaviour. They'll be happy that there's an option.

+1 for default ON

**Comment by Be-ing** [comment]
In addition to the usability question, we also have the issue that inline metadata editing causes [choppy waveforms on macOS](https://bugs.launchpad.net/mixxx/+bug/1665583) and we have no solution in sight for that for 2.1.

> How do we know about which preference settings are actually preferred by our users?

Normally I would say that usability testing would be the answer, but that would not work in this case because the issue is subtle and new users aren't likely to encounter it until they have been using Mixxx for a long time.

> Maybe this is true for experienced Mixxx users, but new users won't miss that feature and therefore wouldn't go to Zulip. Maybe at some point -once they are used to basic Mixxx usage- and if they are curious they'd go to Preferences having a look what can be adjusted apart from basic device and interface settings.

Yes, that is the point. While some users find inline metadata editing to be useful, it is hardly an essential feature. If they have to explicitly enable it in the Preferences by reading a description of it, they will know how the feature is activated and hopefully won't be as prone to doing it on accident. Part of the current problem is that the click-selected-then-wait-but-don't-double-click behavior is unintuitive to the point that users have a hard time figuring out how they accidentally enter metadata editing mode.

> if a few users experience track editing to be unused, or even unwanted because it's buggy with touchpad, there will be an urge to go looking in the Preferences to change this behaviour.

I do not think it is safe to assume that users will go looking in the Preferences to disable this because users have a hard time articulating what is happening.

It seems we have a roughly even split of opinions here. To summarize the consequences again,

Default to on:
   * High chance of accidental metadata edits
   * Waveforms become choppy on macOS

Default to off:
   * Old users may be confused. This can be alleviated by adding an entry to the top of the [Troubleshooting wiki page](https://mixxx.org/wiki/doku.php/troubleshooting) and answering support requests.
  * New users may be unaware of the feature. IMO that is not an issue.

**Comment by Be-ing** [comment]
If we do merge this, we will get support requests asking how to get it back. On the other hand, if we do not merge this, we will get support requests about choppy waveforms on macOS. Either way we will get support requests. IMO the latter is much worse, so unless anyone voices strong objections, let's merge this.

**Comment by daschuer** [comment]
@Be-ing sorry, you are outvoted.
Let's not merge this.

**Comment by Be-ing** [comment]
Can we agree to a compromise?
  * Use an #ifdef to turn off inline metadata editing by default for macOS for 2.1.
  * For 2.2, change the default to off for all platforms. Users upgrading from 2.1 will not have their settings change because they will already have the ConfigKey in their mixxx.cfg.

**Comment by daschuer** [comment]
https://github.com/mixxxdj/mixxx/blob/master/src/library/library.cpp#L177
misses the #ifdefs.

**Comment by daschuer** [comment]
It would be better to have the default at a central place, to have only one #ifdef region.

**Comment by Be-ing** [comment]
I confirm this is working as intended on macOS.

**Pull request merged**
