### PR TITLE
Update USB HID/bulk udev rules

### PR DESCRIPTION
**Pull request by uklotzde**
As reported on [Zulip (USB HID API udev rules)](https://mixxx.zulipchat.com/#narrow/stream/109695-_support/topic/USB.20HID.20API.20udev.20rules) our udev rules doesn't seem to work as expected on modern Linux systems:

- Renamed .rules file
- Changed permissions from GROUP/MODE to TAG+="uaccess"
- Added more vendors to the list

**TODO: Testers with USB HID devices needed!**

Successfully tested on Fedora: https://mixxx.zulipchat.com/#narrow/stream/109695-_support/topic/USB.20HID.20API.20udev.20rules/near/190910621
On Fedora the file has to be copied and renamed to /usr/lib/udev/rules.d/69-mixxx-usb-uaccess.rules

### CODE REVIEW

**Review by Holzhaus — COMMENTED** [review]
udev rule syntax looks good, but I can't check if it actually works due to the lack of HID devices.

**Comment by uklotzde** [comment]
I have tested it successfully on Fedora as reported. It fixes access to USB HID devices that didn't work. That's all I can do for now.

2.2 is affected, too. But I am unsure if we should backport it, because hopefully only a small group of users is affected. Widespread testing during the beta phase is the preferred way to release this to the public.

**Comment by Holzhaus** [comment]
> 2.2 is affected, too. But I am unsure if we should backport it, because hopefully only a small group of users is affected. Widespread testing during the beta phase is the preferred way to release this to the public.

Adding new USB IDs is fine for 2.2.4, but I wouldn't switch from group/mode based to tag based udev rules in a bugfix release. Users running a bugfix release probably fixed the permissions by hand anyway.

**Comment by uklotzde** [comment]
Ok, no update for 2.2.

**Comment by Holzhaus** [comment]
Thanks!

**Comment by uklotzde** [comment]
I'll update the Wiki accordingly.

**Pull request merged**
