### PR TITLE
2.4.0 changelog updates 

### PR DESCRIPTION
**Pull request by daschuer**
This should be merged before starting 2.4-beta

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Shouldn't we mention, the change of the hidapi backend on Linux? I could imagine that some Linux users might have issues with the udev file changes.

**Comment by JoergAtGithub** [comment]
Could you please change
```
* Add generic USB HID "Set Reports (Feature)" functionality [#3051](https://github.com/mixxxdj/mixxx/pull/3051)
* Add support for reading the status of an HID controller (like MIDI SYSEX) [#3317](https://github.com/mixxxdj/mixxx/pull/3317)
```
to
```
* Add support to access HID FeatureReports [#3051](https://github.com/mixxxdj/mixxx/pull/3051)
* Add function to request HID InputReports, to determine controller state at startup [#3317](https://github.com/mixxxdj/mixxx/pull/3317)
```

**Comment by daschuer** [comment]
> Use hidapi's hidraw backend instead of libusb on Linux https://github.com/mixxxdj/mixxx/pull/4054

We have that already. 

We have anyway the task to beautify the list before releasing 2.4.0. Any help is welcome.

**Comment by JoergAtGithub** [comment]
What is about https://github.com/mixxxdj/mixxx/issues/11094 - even if the bug is introduced by a change in Windows, it's a major restriction. Do we need something like a known bugs list for the Beta?

**Comment by daschuer** [comment]
I have added the suggested changes. 

Regarding https://github.com/mixxxdj/mixxx/issues/11094 we have no list of common issues other than our bug tracker. 
Here we can use the regression tag to make them discoverable. I am also in doubt it is reasonable to track an extra list. 

If we are not able to find a fix for issue #11094, we may enable FFMPEG instead as suggested. Do you have interest to take care. First I would take a look if we are doing something wrong when seeking. Do we handle all error situations correctly.

**Comment by daschuer** [comment]
Can we merge this one now and advance to 2.4-beta?

**Comment by JoergAtGithub** [comment]
LGTM! Thank you for takeing care!

**Pull request merged**
