### PR TITLE
Reloop terminal mix2 cleanup

### PR DESCRIPTION
**Pull request by ronso0**
I removed some deprecated mappings, added a link to engine.brake() and updated link for Filter knob.
In detail:
* removed filterTurn() and mapped it to [QuickEffectRack1_[ChannelN]] directly
  (which is SuperKnob for 'Filter' by default and can be customized in Preferences)
* removed filterReset which was resetting EQs when filterKnobTurn() is set to center
* removed deprecated Flanger
* added tinyLoopMove() to move loop in smaller steps when combined with [Shift]
* mapped engine.brake() to [Shift]+[closest button] (Sync on left decks, Play on right decks)
I'll update ReloopTerminalMix wiki when this is merged.

I suppose 'Flanger' could be purged from many other mappings. Should I file a bug?

### CODE REVIEW

**Comment by Be-ing** [comment]
Thanks for taking care of this. :) All the changes look good so far.

We are working on a new interface for effects (see PRs #1062, #1063, and #1068) that will allow you to actually make use of all the effects controls on this controller in a really fun way. In the meantime, you can map the controls like they are on the [Denon MC4000](http://mixxx.org/wiki/doku.php/denon_mc4000), with the knobs on the left mapped to the dry/wet of EffectUnits 1-3 and the knobs on the right mapped to the superknob of EffectUnits 1-3.

**Comment by ronso0** [comment]
I see what you mean. What I don't like about this suggested mapping is that one wouldn't have a clear distinction between left and right channels unlike almost all other controls (EQs, Vol fader, play controls). This would be too much adaption from my current solution, a script approach to control FX which I currently polish to share it in the forum. 
(teaser: press an FX button to activate EffectN, then controls its first 3 knobs with the three physical knobs. Press any other FX button to control the respective Effect slot. Switch focus with Shift+FXbutton
#1068 comes in handy..)
And I was already watching discussion about Meta knobs, I'm excited about the implementation, it will be a huge step forward because a lot controllers share this knob/button layout.
Cheers!

**Comment by Be-ing** [comment]
> teaser: press an FX button to activate EffectN, then controls its first 3 knobs with the three physical knobs. Press any other FX button to control the respective Effect slot. Switch focus with Shift+FXbutton
#1068 comes in handy..

I have implemented a similar system as a generic JS object that can be reused for many controllers in the [Hercules P32 mapping](https://github.com/mixxxdj/mixxx/pull/1054/files#diff-400922cb0109e689c3d5404810aec4dfR697).

**Comment by sblaisot** [comment]
> teaser: press an FX button to activate EffectN, then controls its first 3 knobs with the three physical knobs. Press any other FX button to control the respective Effect slot.

Humm, you will have to handle soft takeover for this scenario or you risk to add a lot more of effect than desired to your song when switching.

**Comment by ronso0** [comment]
Yup, I know. With the script you can put focus even to an disabled effect in a chain, adjust, the turn it ON.
It's not perfect solution but working very well so far, especially for Filter with LPF, HPF and resonance on 3 physical knobs. For most other effects Meta knobs will be better I suppose..

**Comment by ronso0** [comment]
> I have implemented a similar system as a generic JS object that can be reused for many controllers in the Hercules P32 mapping.
Nice. I think I'll learn some more js tricks from that. In addition to enabling effects I use controller script to prepare effect chains. Looking forward to a Save/Load CO for effect units.

**Comment by Be-ing** [comment]
Note that the Controls library relies on changes to how Mixxx executes JS functions since 2.0 was released, so it will not work with Mixxx 2.0.

**Comment by ronso0** [comment]
Yeah, I noticed. Using alpha anyway. If I share anything I'll check with 2.0 as well

**Comment by Be-ing** [comment]
> Humm, you will have to handle soft takeover for this scenario or you risk to add a lot more of effect than desired to your song when switching.

In case you missed it, I fixed the bug with engine.setParameter() not working with soft takevoer in #1065.

**Comment by ronso0** [comment]
Since I'm new to this process: did I miss something in order this can be merged?

**Comment by Be-ing** [comment]
Apologies for letting this sit. The changes look good to me. 👍  Please document changes in functionality on the [the wiki page](http://mixxx.org/wiki/doku.php/reloop_terminal_mix).

I will update the EffectUnit object in the Controls library as the new effects interface is implemented. It would be cool to get your feedback on it when using it for this controller.

**Comment by ronso0** [comment]
Cool! And sure I'll update the wiki.
> I will update the EffectUnit object in the Controls library as the new effects interface is implemented.

Subscribed to #1054, will check it out!

**Comment by Be-ing** [comment]
Can someone merge this?

**Comment by Pegasus-RPG** [comment]
LGTM

**Pull request merged**
