### PR TITLE
add com.apple.security.device.audio-input entitlement on macOS

### PR DESCRIPTION
**Pull request by Be-ing**
fixes https://bugs.launchpad.net/mixxx/+bug/1917530

### CODE REVIEW

**Comment by Holzhaus** [comment]
Lol, PR race condition: https://github.com/mixxxdj/mixxx/pull/3681

**Comment by Holzhaus** [comment]
Please add some comments to clarify the distinction between the microphone and the audio-input entitlement. If you'd epazy you cna just cherry pick the commit from my fork.

**Comment by Be-ing** [comment]
I actually don't know what the difference is and Apple's documentation doesn't make it clear.

**Comment by Holzhaus** [comment]
> I actually don't know what the difference is and Apple's documentation doesn't make it clear.

Check my PR, I added comments there.

**Comment by Holzhaus** [comment]
> I can't reproduce the bug on macOS 10.13. It might only affect later versions of macOS.

Yes, the hardened runtime was introduced in macOS Mojave (10.14).

**Comment by Be-ing** [comment]
Confirmed working: https://mixxx.discourse.group/t/v2-3-beta-issue-with-mic-on-big-sur-m1/21349/11

**Comment by Holzhaus** [comment]
> Please add some comments to clarify the distinction between the microphone and the audio-input entitlement. If you'd lazy you can just cherry pick the commit from my fork. 

Ping!

**Comment by Be-ing** [comment]
I disagree with your proposed comments. They don't add any information. As I said before, I don't actually know what the difference between these confusingly named entitlements are and Apple's documentation doesn't clarify, so I don't know what comment could be helpful.

**Comment by Holzhaus** [comment]
> I disagree with your proposed comments. They don't add any information. As I said before, I don't actually know what the difference between these confusingly named entitlements are and Apple's documentation doesn't clarify, so I don't know what comment could be helpful.

Yes they do. They make clear that these entitlements are for two different, independent systems that partially overlap:
- Sandboxing
- Hardened Runtime

You can build an app with sandboxing but without hardened runtime, with hardened runtime but without sandboxing, with both or with none of them.

- https://developer.apple.com/documentation/security/hardened_runtime
- https://developer.apple.com/documentation/security/app_sandbox

**Comment by daschuer** [comment]
The missing documentation was added here: https://github.com/mixxxdj/mixxx/pull/3685
Thank you.

**Pull request merged**
