### PR TITLE
Update launchpad links in js

### PR DESCRIPTION
**Pull request by daschuer**
This is the follow up of https://github.com/mixxxdj/mixxx/pull/11377 
Including the commits to make eslint happy. This is not tested.

### CODE REVIEW

**Comment by ronso0** [comment]
now one mapping test fails:
`120 - LegacyControllerMappingValidationTest.MidiMappingsValid (Failed)`

**Comment by daschuer** [comment]
All green now. Can one JS expert have a brief look before merge?

**Comment by ronso0** [comment]
> All green now. Can one JS expert have a brief look before merge?

@Swiftb0y @JoergAtGithub ?

**Review by Swiftb0y — APPROVED** [review]
Thank you, the mappings themselves are quite outdated but thats outside the scope of this PR. as long as they pass eslint and the smoketest, they should still work.

**Pull request merged**
