### PR TITLE
Fix aliasing violations when using SampleUtil::copy2WithGain. Bug #1770771.

### PR DESCRIPTION
**Pull request by rryan**

### CODE REVIEW

**Comment by rryan** [comment]
It would be nice if Travis offered something newer than Ubuntu Trusty (!) 😠 so that we could get a newer compiler. Uwe noticed this with GCC 8.

**Comment by daschuer** [comment]
LGTM, Thank you.

**Comment by Be-ing** [comment]
Is there something wrong with the SampleUtil::copy2WithGain function? Should that be fixed or should the function be removed?

**Comment by Be-ing** [comment]
Ugh, why is there a "Close and comment" button?!

**Comment by rryan** [comment]
Thanks for the review!

**Pull request merged**
