### PR TITLE
Componentsjs fix syncbutton

### PR DESCRIPTION
**Pull request by JaviVilarroig**
This PR fixes a small issue in the SyncButton component. Long press was nor working properly.

### CODE REVIEW

**Comment by JaviVilarroig** [comment]
Ouch it seems that I mixed this PR and the one on g4v controller.
I'm closing it to fix that on my side.

**Comment by Be-ing** [comment]
Please do an interactive rebase to separate the relevant commit from your other branch. `git rebase -i upstream/main` then delete the lines for the unrelated commits.

**Comment by Be-ing** [comment]
There is no need to make a new PR. Do the rebase then force push this branch.

**Comment by JaviVilarroig** [comment]
OK. Thanks. I have a tendency to panic very fast with git.

**Comment by JaviVilarroig** [comment]
I did it but nothing has changed.

**Comment by Be-ing** [comment]
Did you `git push --force`?

**Comment by JaviVilarroig** [comment]
Yep :(

**Comment by Be-ing** [comment]
https://www.sitepoint.com/git-interactive-rebase-guide/

**Comment by JaviVilarroig** [comment]
I think I manage :)

**Comment by JaviVilarroig** [comment]
But now I pushed an undesired change in CMakeLists.txt

**Comment by Be-ing** [comment]
It looks like you picked the wrong commit. Don't panic, the commit you want is still there in your reflog. Run `git reflog` to find that one commit you want and copy its hash. Then:
```
git reset --hard upstream/main
git cherry-pick HASH_OF_THE_COMMIT
```

**Comment by Be-ing** [comment]
Thanks!

pre-commit issues are unrelated.

**Comment by JaviVilarroig** [comment]
Thanks to you, my friend. 

I will end learning git :)

**Pull request merged**
