### PR TITLE
Fix CPack WIX Installer for Windows

### PR DESCRIPTION
**Pull request by Holzhaus**
Adds some more settings for CPack Installer generation.

### CODE REVIEW

**Comment by Holzhaus** [comment]
Wohoo, it finally works! The CPack is now able to build a *working* Windows installer. It does not support all features that the old installer has but if we merge this, users can grab the build artifacts from AppVeyor and just install them.

**Comment by Be-ing** [comment]
Good work! Waiting for CI...

**Comment by Be-ing** [comment]
Please rebase on master to include #2638 so we can tell if this works with CI.

**Comment by Holzhaus** [comment]
Done.

**Comment by Be-ing** [comment]
AppVeyor build passed. Can someone on Windows test the artifact?

**Comment by ronso0** [comment]
Yup, I'll try that tomorrow morning.

**Comment by JosepMaJAZ** [comment]
Just tested here. Installer now installs correctly, but I saw a couple of things:

- The filename still doesn't include the PR. I strongly recommend about adding it to avoid confusion when trying different builds.

- Older installer just installed a Mixxx icon on top of the programs menu, while this one creates a program group with Mixxx and unistaller. Not sure what's better, just warning about the change.

- Misses the qt translations ( qt_ca.qm, etc..). 
In fact, the older installer doesn't do it completely right either. I found that now it requires to add multiple files for each language: qt_ca.qm, qtbase_ca.qm, qtscript_ca.qm, etc.. (translations subfolder in qt sources)
Possibly not all of them are necessary ( qtassistant, and the likes)
These are needed to translate the "Reset" button on the preferences, or the font dialog on the library preferences

- Misses the following dlls on the mixxx folder:
d3dcompiler_47.dll
libEGL.dll
libGLESv2.dll
Although the program has started and shows the GL waveforms correctly.

d3dcompiler_47 is on system32 (I have a slightly newer version than the one we distribute).
Just checked, Windows 7 also has it.

Maybe we no longer need them (since we build it statically).
I tried removing the three files from a mixxx 2.2.3 installed on a Win7 VirtualBox and the program started and showed GL waveforms.

**Comment by Holzhaus** [comment]
I also didn't set the WIX Product ID, because it's set dynamically in our current config and didn't had the time to check where it comes from.

**Comment by Be-ing** [comment]
> Older installer just installed a Mixxx icon on top of the programs menu, while this one creates a program group with Mixxx and unistaller. Not sure what's better, just warning about the change.

For AppVeyor artifacts that may be convenient. But for official builds, just the Mixxx icon would be better.

**Comment by Holzhaus** [comment]
Yeah, this is not in a state for an official release yet. I thought we stick with SCons for 2.3 so we don't have to hurry. My main concern was to make it usable for Windows testers.

**Comment by Be-ing** [comment]
So shall we merge this as is and continue working on making the Windows packaging release ready later?

**Comment by Holzhaus** [comment]
Yes. In the short term it would be good if someone can explain where the product id comes from so that the installer can detect if another version of mixxx is already installed and replace it.

**Pull request merged**
