### PR TITLE
Add support for ogg/m4a/caf files via libsndfile

### PR DESCRIPTION
**Pull request by uklotzde**
Only as a fallback with lower priority than the native decoders (if available).

ALAC support (.m4a) has been added to libsndfile 1.0.26. I have not tested it, because Fedora 23 still ships version 1.0.25. Please note that libsndfile is not capable of decoding AAC files, although both ALAC and AAC use an M4A container!

See also:
https://bugs.launchpad.net/mixxx/+bug/1336982

### CODE REVIEW

**Comment by Pegasus-RPG** [comment]
Cool, LGTM. I'm preparing libsndfile 1.0.26 for the Windows builds on the new build server anyway so this comes at a great time.

**Comment by daschuer** [comment]
Ubuntu has also no update yet. 
https://bugs.launchpad.net/ubuntu/+source/libsndfile/+bug/1534098
Is there an online resource for test files?

**Comment by uklotzde** [comment]
http://www.linnrecords.com/linn-downloads-testfiles.aspx

**Comment by uklotzde** [comment]
There is only one side-effect: Even if files are actually not decodable by 
Mixxx they now will appear in the library. But this will happen anyway for 
AAC files with the ending .m4a if no AAC decoder is available. libsndfile 
only supports ALAC in M4A containers, but not AAC.

**Comment by Pegasus-RPG** [comment]
Hmm, I wonder then if it's sensible for Mixxx to attempt to open each file during a library scan and only list it if it can open it.

**Comment by daschuer** [comment]
I like the idea to use libmagic, the library that drives the Linux file command, instead of rely on the file  extension only. But that does not help in our case here: 
```
file -k "tone24bit.m4a" 
tone24bit.m4a: ISO Media, MPEG v4 system, iTunes AAC-LC
``` 
But we can detect drm files: 
```
MPEG v4 system, iTunes AES encrypted
```

**Comment by rryan** [comment]
I wonder why travis didn't run?

**Comment by uklotzde** [comment]
There's a one-to-many relationship between a file extension and the possible formats contained in the file. We currently don't take this into account when opening a SoundSource.

Opening a SoundSource may fail with "unsupported format", even if the file extension is supported:

    enum class OpenResult {
        SUCCEEDED,
        FAILED,
        UNSUPPPORTED_FORMAT
    };
    OpenResult open(...);

I will improve the SoundSource interface. This extension is helpful even when using libmagic for file type detection in the future.

**Comment by uklotzde** [comment]
I've added and API extension that allows SoundSources to only support a subset of formats for a supported file extension.

**Comment by daschuer** [comment]
LGTM. 
However I still have not tested this. 
@Pegasus-RPG: Any test results on windows?

**Comment by daschuer** [comment]
I have just tried to test this branch with a fresh compiled version of libsndfile 1.0.26, but I cannot play the test files from the link above. 
I am sure Mixxx uses libsndfile-1.0.26  by adding sf_version_string(); to the debug output. 

But anyway it looks like there is no Mixxx issue, the files are handled safely. 
So we could merge this?

**Comment by uklotzde** [comment]
Mergeable, although I did not test decoding of the newly supported formats with the current version of libsndfile.

**Comment by daschuer** [comment]
Thank you @uklotzde!

**Comment by rryan** [comment]
Update: the new OS X and Windows build VMs will have libsndfile 1.0.26.

I tried a .caf file and Mixxx couldn't load it. It showed up in the library and taglib could decode the metadata.

```

Debug [CachingReaderWorker 1]: SoundSourceProvider "libsndfile" created a SoundSource for file "file:///Users/rjryan/Desktop/en-US_Male.caf" of type "caf"
Warning [CachingReaderWorker 1]: Error opening libsndfile file: "file:///Users/rjryan/Desktop/en-US_Male.caf" "Supported file format but unsupported encoding."
Debug [CachingReaderWorker 1]: Opened AudioSource for file "file:///Users/rjryan/Desktop/en-US_Male.caf" with provider "libsndfile"
Warning [CachingReaderWorker 1]: Invalid audio data in file "file:///Users/rjryan/Desktop/en-US_Male.caf"
Warning [CachingReaderWorker 1]: Failed to open AudioSource for file "file:///Users/rjryan/Desktop/en-US_Male.caf"
Warning [CachingReaderWorker 1]: Failed to open file: "/Volumes/Macintosh HD/Users/rjryan/Desktop/en-US_Male.caf"
Debug [CachingReaderWorker 1]: "[Channel1]" CachingReaderWorker::loadTrack() load failed for" "/Volumes/Macintosh HD/Users/rjryan/Desktop/en-US_Male.caf" ", file invalid, unlocked reader lock
Debug [Main]: Failed to load track "/Volumes/Macintosh HD/Users/rjryan/Desktop/en-US_Male.caf" "The file '/Volumes/Macintosh HD/Users/rjryan/Desktop/en-US_Male.caf' could not be loaded."
Debug [Main]: BaseTrackPlayerImpl::slotTrackLoaded
```

**Comment by rryan** [comment]
Eh looks like this CAF isn't supported by libsndfile.

**Comment by rryan** [comment]
I found one that works fine. Cool!

**Comment by rryan** [comment]
Hm, this ALAC m4a doesn't seem to want to load though:
http://www.thesixteendigital.com/testfiles/

**Comment by rryan** [comment]
After digging through the libsndfile source, I don't think it supports MP4 containers -- just CAF containers of ALAC encoded audio.

**Comment by rryan** [comment]
@uklotzde were you able to load an M4A with libsndfile?

**Comment by uklotzde** [comment]
Unfortunately not. Both Fedora 23 and 24 (Beta) come with libsndfile 1.0.25.

I will remove the "m4a" file extension from the SoundSource.

**Comment by uklotzde** [comment]
https://github.com/mixxxdj/mixxx/pull/955

**Pull request merged**
