### PR TITLE
Fix for fatal error LNK1117: syntax error in option 'INCREMENTAL:NO:NO'

### PR DESCRIPTION
**Pull request by JoergAtGithub**
Regression from https://github.com/mixxxdj/mixxx/pull/3660#

### CODE REVIEW

**Comment by Be-ing** [comment]
The other warning is back now:
```
LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/OPT:REF' specification
```

**Comment by JoergAtGithub** [comment]
/INCREMENTAL is at the end of the string:
grafik

**Comment by JoergAtGithub** [comment]
I'm in doubt, if it's right to change the CMake defaults so much.

**Comment by daschuer** [comment]
According to the cmake code 

CMAKE_EXE_LINKER_FLAGS_RELEASE
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL

have  /INCREMENTAL:NO

Which is fine for us. 

We need to remove /INCREMENTAL

form 

CMAKE_EXE_LINKER_FLAGS_DEBUG
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO

See: 

https://github.com/Kitware/CMake/blob/6bd251ace7a11d57fd250c8c4a89d480b10d664d/Modules/Platform/Windows-MSVC.cmake#L313

This pattern has not changed since cmake 3.1

https://github.com/Kitware/CMake/blob/1c94558abb653968de6da2cb4672006f31ca0d14/Modules/Platform/Windows-MSVC.cmake

So the original issue was "only" a typo between DEBUG and RELEASE. It was also intend to have the '/OPT:REF' also applied in Debug build, because it speed up initialization of the debugger.

**Comment by daschuer** [comment]
Please use: 

 string(REPLACE "/INCREMENTAL" "/INCREMENTAL:NO" CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG}")
      string(REPLACE "/INCREMENTAL" "/INCREMENTAL:NO" CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO}")

and remove else() above.

**Comment by JoergAtGithub** [comment]
Local build without /INCREMENTAL is no fun, it takes much longer. For any kind of debugging I never build without /INCREMENTAL.

**Comment by JoergAtGithub** [comment]
INCREMENTAL should be only disabled for advanced code optimization strategies of release builds at link time like IPO, PGO or OPT:REF
For normal DEBUG builds no optimization should be done, which allows stepping line by line through the code. Without optimisation there is no benefit in optimisation at link time.
For RELWITHDEBINFO code optimization at compile time is much more suitable. With /INCREMENTAL it provides short build times for code changes and a good apllication performance.

**Comment by daschuer** [comment]
> In our test the was no measurable difference between /INCREMENTAL and /INCREMENTAL:NO builds. Maybe we did something wrong. Can you verify it? 

> For normal DEBUG builds no optimization should be done, which allows stepping line by line through the code.

Mixxx is uselessly slow without optimizations. That's why we enable the normal optimize for debug builds as well. 
If you really need a build without optimization for some reasons use optimize=off    

Can you also confirm that starting the debugger with '/OPT:REF' is faster than without? 

Finally we want the best developer experience with Debug builds. I am happy to change the flags in order to achieve this according to your test results. We should just add also a note about our decision.

**Comment by JoergAtGithub** [comment]
If you want to use debugger to step through the code you need a build with O0 or Od, otherwise the compiler might optimize away the code line or variable of interest. This use case is what the optimization Off target provided.

For other local test builds, compile time optimization /O2 makes sense. With /INCREMENTAL this is possible with very fast build times vor small code changes.

The debugger always starts fast and loads Mixxx fast here, what takes time are build steps, which are executed before, to ensure that the debbuged build is clean.

**Comment by daschuer** [comment]
> With /INCREMENTAL this is possible with very fast build times vor small code changes.

What is the difference on you machine? 
We have compared the GitHub CI and we had build times in the range of 18 to 23 minutes independent of /INCREMENTAL. So it might has an effect, but is covered by the noise of different system loads during our tests.

**Comment by JoergAtGithub** [comment]
On CI you have always full builds. For local development I do a full build once and than modify the code only. The later is where incremental linking makes the difference. If I touch only a single cpp file, I've build times of about 20 seconds.

**Comment by daschuer** [comment]
> If I touch only a single cpp file, I've build times of about 20 seconds.

With or without /INCREMENTAL? 

Ok, it sounds like the else branch makes sense. So we just need a single line to hack around the warning: 

```
string(REPLACE "/INCREMENTAL" "/INCREMENTAL:NO" CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO}")
```

Can you also add a comment, that we use incremental builds for debug to speed up repeated builds? 

Thank you.

**Comment by JoergAtGithub** [comment]
The proposed string replace wouldn't be safe, because it relies on the case, that the developer use the CMake defaults. But this is a user editable parameter: 
grafik

**Comment by JoergAtGithub** [comment]
Something like this might work always:
```
 string(FIND CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "/INCREMENTAL:NO" INCREMENTAL_NO_POSITION)
 if(INCREMENTAL_NO_POSITION EQUAL -1)
    add_link_options(/OPT:REF)
 endif()
```

**Comment by daschuer** [comment]
This does not lead to the desired defaults. We use RelWithDebInfo for our releases to be able to also ship debug symbols these builds. These should not contain unused functions to keep the size small. This should work out of the box. With the proposed solution /OPT:REF is not set.

**Review by daschuer — APPROVED** [review]
Perfect now. Thank you very much. 
LGTM

**Pull request merged**
