### PR TITLE
libdjinterop 0.22.1, support for Engine 4.0.1

### LINKED ISSUE #13695: Export to Engine Prime: Unsupported database version
### Bug Description

Using `Library` -> `Export Library to Engine Prime`,

- The latest `Database version` isn't listed (Engine OS `v4.0.1` was released on `09/15/2024`, `4.0.0` was released on `06/12/2024`)
- Selecting the folder of a flash drive already being used for the controller, and continuing anyways results in `Export Failed: Unsupported database version 2.21.2`

I've attached the `Engine Library` files generated on a drive with only a few songs for reference (I've removed `Engine Library/Music/*` because copyright). This was generated with these steps:

1. Export a few songs to USB from Engine Desktop
2. Boot controller with USB in it
3. Move USB back to PC

[Engine Library.zip](https://github.com/user-attachments/files/17130169/Engine.Library.zip)

### Version

2.4.1

### OS

Ubuntu 22.04.5 LTS

### PR DESCRIPTION
**Pull request by mr-smidge**
Latest version of libdjinterop adds support for Engine 4.0.0/4.0.1.

Fixes #13695

### CODE REVIEW

**Review by Swiftb0y — APPROVED** [review]
Whats needed for this packaging wise @daschuer?

**Comment by Swiftb0y** [comment]
Thanks @mr-smidge for jumping on the issue this fast.

**Comment by JoergAtGithub** [comment]
I will provide the VCPKG port update needed for Windows!

**Comment by mr-smidge** [comment]
I'll do the [libdjinterop PPA](https://launchpad.net/~xsco/+archive/ubuntu/djinterop)...

**Comment by mr-smidge** [comment]
Ubuntu builds now all built and published :rocket:.

**Comment by JoergAtGithub** [comment]
https://github.com/mixxxdj/vcpkg/pull/147
https://github.com/mixxxdj/vcpkg/pull/148

**Comment by mr-smidge** [comment]
What's left to do before this can be merged?

**Comment by Swiftb0y** [comment]
I think we need to bump the vcpkg version we use (to the updated one).

**Comment by JoergAtGithub** [comment]
The new VCPKG 2.4 and 2.4-rel buildenvs are now ready at https://github.com/mixxxdj/vcpkg/branches
You need to apply the correct BUILDENV_NAMEs and BUILDENV_SHA256s now in this PR, similar as in: https://github.com/mixxxdj/mixxx/pull/13288/files

**Comment by JoergAtGithub** [comment]
BTW: Engine 4.1 was published today. DigitalDjTips write about it: "the software uses an updated database, it’s not backwards compatible with 4.0 databases."

**Comment by mr-smidge** [comment]
> BTW: Engine 4.1 was published today. DigitalDjTips write about it: "the software uses an updated database, it’s not backwards compatible with 4.0 databases."

Great timing! :confounded:

**Pull request merged**
