### PR TITLE
HID udev rule

### PR DESCRIPTION
**Pull request by Be-ing**
Users often have issues with Mixxx not detecting their HID controller because their user does not have permission to access the device (see http://mixxx.org/wiki/doku.php/troubleshooting#midi_controllers_on_gnu_linux ). This PR includes a udev rule in Mixxx specifically for HID devices from Pioneer, Hercules, and Native Instruments so users won't encounter this issue. I do not have any of these devices to test the udev rule with. It would be great if someone who has any of these devices could test it before this PR is merged.

src/SConscript was updated to install the udev rule to the absolute path /etc/udev/rules.d/mixxx-usb-hid.rules if the user has write permission in that directory. Does this cause any issues for building packages?

### CODE REVIEW

**Comment by daschuer** [comment]
The udev file should be moved to the /res folder, /res/udev or res/linux

Are there any security issues or any other objections? 
I have none.

**Comment by Be-ing** [comment]
The other GNU/Linux- and BSD- specific files, mixxx.desktop and mixxx.appdata.xml, are both in src. Should these all be moved to a new directory? If so, what should it be called? res/nix?

@Pegasus-RPG , what is the USB Vendor ID for Eks? Do you happen to know the USB Vendor ID for Gemini CDJs?

**Comment by daschuer** [comment]
> The other GNU/Linux- and BSD- specific files, mixxx.desktop and mixxx.appdata.xml, are both in src. Should these all be moved to a new directory? If so, what should it be called? res/nix?

Yes, good idea. "res/linux" will work for me since we distinguish OSX MSWin and Linux elsewhere.

> Come to think of it, there's no point in installing a udev rule on BSD.

I think the udev file is copied only if the folder /etc/udev/rules.d exists and is writable, right?
That should cover the case the system has no udev.

**Comment by Be-ing** [comment]
> I think the udev file is copied only if the folder /etc/udev/rules.d exists and is writable, right? That should cover the case the system has no udev. 

Yeah, I realized that after posting my last comment.

**Comment by daschuer** [comment]
LGTM Thank you @Be-ing!

**Comment by daschuer** [comment]
I would like to add you to the contributor list in the Mixxx about box. 
What is your name I should use?

**Comment by Be-ing** [comment]
Please list me as just "Be"

**Pull request merged**
