### PR TITLE
Replace some ContrlObjectThread by ControlObjectSlave

### PR DESCRIPTION
**Pull request by daschuer**
This is a next step towards fixing Bug #1406124

This is the successor of #707

### CODE REVIEW

**Comment by rryan** [comment]
fails to build

**Comment by daschuer** [comment]
Ups, merged again and now it works.

**Comment by rryan** [comment]
thanks!

**Comment by rryan** [comment]
There are now ~50 failed connections printed to the log on bootup (mostly waveformrendermark related) -- could you fix that?

**Pull request merged**
