### PR TITLE
Rename mixxx.{cpp,h} to mixxxmainwindow.{cpp,h}

### PR DESCRIPTION
**Pull request by Holzhaus**
The file should have the same name as the class. I was confused by this more than once.

### CODE REVIEW

**Review by Be-ing — APPROVED** [review]
This has confused me before as well. Waiting for CI.

**Review by uklotzde — APPROVED** [review]
LGTM

**Comment by JoergAtGithub** [comment]
I just tried to build Main on windows and get:
```
1> [CMake] -- Configuring done
1> [CMake] CMake Error at buildenv/mixxx-deps-2.3-x64-windows-049b5ad/scripts/buildsystems/vcpkg.cmake:702 (_add_library):
1> [CMake]   Cannot find source file:
1> [CMake] 
1> [CMake]     src/mixxx.cpp
1> [CMake] 
1> [CMake]   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++
1> [CMake]   .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:366 (add_library)
1> [CMake] -- Generating done
1> [CMake] CMake Generate step failed.  Build files cannot be regenerated correct
```ly.

**Comment by Holzhaus** [comment]
Please clean your build dir. I suppose there are leftover files from a previous build.

**Comment by JoergAtGithub** [comment]
Solved it! It was some weird cleanup issue.

**Pull request merged**
