### PR TITLE
library redesign single feature

### PR DESCRIPTION
**Pull request by Be-ing**
This is a continuation of #1117 using the upstream branch instead of @daschuer's branch.

Merge blockers:
  * [ ] #1722
  * [ ] Fix `[Library], GoToItem`
  * [ ] Fix `[ChannelX], LoadSelectedTrack` and `[ChannelX], LoadSelectedTrackAndPlay`

### CODE REVIEW

**Review by uklotzde — CHANGES_REQUESTED** [review]
Update: Most of my previous comments still apply.

Next try with a clean build based on Qt5 (5.10.1), pulling the latest changes from master.

Unfortunately the same results as reported earlier. I experience an extended startup time and even more severe lags during operation. The UI is very sluggish when browsing the library or selecting tracks ~~and freezes for an extended period of half a minute or even longer when loading tracks~~. Sorry, but this is totally unusable. It is not sufficient to test with a fresh and almost empty database containing just a few thousand tracks.

I strongly recommend NOT merging these changes until at least the major usability issues have been fixed. We won't be able to fix any serious design flaws when discovered during the beta phase. I suppose there are some.

**Comment by Be-ing** [comment]
@uklotzde do you have any ideas where the slowdowns are? Could you do some profiling to identify inefficient code?

**Comment by Be-ing** [comment]
With a library of 3440 tracks, this performs fine for me now. Can anyone else reproduce the sluggish GUI? How many tracks are in your library?

**Comment by Be-ing** [comment]
I made 10 copies of my library (for a total of 11 copies) and scanned them with this branch and cannot reproduce the GUI lag you report @uklotzde.

**Comment by Be-ing** [comment]
Can you clarify specifically what actions are slow? Is it just scrolling in the track tables and the startup time?

> Multiply your number of tracks by at least 10x or even 50x to obtain meaningful scalability results.

Theoretically, I agree, the code should be able to handle this without an issue. But I've already almost filled a 2 TB external hard drive testing this so scaling this 50x more seems way beyond what's necessary/

**Comment by Be-ing** [comment]
We should have some (semi-)automated way to test scalability of the library. Perhaps we could have a script that takes makes a million copies of a very small music file and writes a random string to every tag for every copy.

**Comment by uklotzde** [comment]
Such a small utility would be really helpful for artificially generating a huge and valid library, both for interactive and automated tests. The distribution of genres, track artists, album artists, and albums should be configurable. Temporary files could be placed into a /album artist/album/ directory structure. As a first step generating this directory structure with the files would be sufficient.

**Comment by Be-ing** [comment]
Okay, I will work on writing that. How do think it should be implemented? I am thinking of writing a Python script using pytaglib.

**Comment by uklotzde** [comment]
Configurable number of genres: "Genre 1", ..., "Genre m"
Configurable number of album artists: "Artist 1", ..., "Artist n"
Configurable max. albums per album artist, e.g. 5 (equally distributed for simplicity)
Configurable max. tracks per album, e.g. 15 (equally distributed for simplicity)
Configurable track artist variation probability: 0.3 -> Append a unique suffix to the album artist to get more distinct track artists than album artists

This should result in a fairly realistic library. You can use /tmp on tmpfs to save SSD lifetime, both for the generated audio files and the database file. I suppose the lags will become apparent with 100k-250k files even when storing the database on a fast Ramdisk. We may reuse the existing empty.mp3 test file as a template. A file size of 4kB results in 1 GB for 250k files and that should fit easily in tmpfs.

**Comment by Be-ing** [comment]
> Configurable number of genres: "Genre 1", ..., "Genre m"

How should genres be distributed? The simplest way that jumps to mind would be to group album artists into genre categories.

>  Configurable max. albums per album artist, e.g. 5 (equally distributed for simplicity)

By "equally distributed", do you mean every album artist would get the same number of albums, or every album artist would get a random number of albums between 1 and the maximum?

> Configurable track artist variation probability: 0.3 -> Append a unique suffix to the album artist to get more distinct track artists than album artists

Do you mean append a unique suffix to the track artist for 30% of the tracks in each album artist?

> You can use /tmp on tmpfs to save SSD lifetime, both for the generated audio files and the database file.

Good idea. I will make the root output directory a command line option. Using `/tmp/mixxx-test-music-library` seems like a good default.

**Comment by uklotzde** [comment]
Genres can be assigned radomly to tracks, shouldn't make any difference.

"equally distributed" = "uniform distribution", i.e. every choice gets the same probability. Then the mean value of 1..15 will be 8.

I found out that I have twice the number of track artists compared to track artists, i.e. with some secondary artists like "feat. ...", "vs. ...", ... This is a _track artist variation_ of 0.5, but I think 0.3 is will be common (I have a rule for normalizing my track metadata by moving this information from the track title appearing in braces right into the artist field). Just append some random suffix to the term "Album Artist n", e.g. "Album Artist 1283 & ZUHbjhg786z87" for 30% of the tracks to generate the track artist from the album artist. For the remaining 70% just copy the album artist.

**Comment by uklotzde** [comment]
My personal distinct track artists vs. distinct album artists ratio is even 4:1. That could be achieved by generating n + 1 track artists per album artist and assigning them randomly to all tracks of the same album artist. Reasonable choices for n are 2..5.

**Comment by Be-ing** [comment]
> Eagerly fetching and grouping the contents of the whole library including cover art is ridiculous.

Yeah, that's a serious architectural flaw. The database should only need to be queried for the leafs of the tree when the groupings are expanded.

> I don't know why even selecting individual in the tracks view table causes a noticeable delay of up to 1 second. It doesn't matter if a track has already been selected before.

I don't know where that's coming from either. This branch has [quite a bit of changes to WTrackTable](https://github.com/mixxxdj/mixxx/pull/1726/files#diff-61349d31f213f893363ef94336c26f62) that should probably have a thorough review.

**Comment by ronso0** [comment]
to save hours of scrolling:
most recent **UX design discussion** on multi-pane library in #1117 starts about [here](https://github.com/mixxxdj/mixxx/pull/1117#issuecomment-330538183)

**Comment by daschuer** [comment]
Yes, lets shift this by one release. I think we have enough to do to make Qt5 work.

**Comment by Be-ing** [comment]
> Okay, I will work on writing that. How do think it should be implemented? I am thinking of writing a Python script using pytaglib.

Forget Python, I'll make this my little Rust learning project. :)

**Comment by naught101** [comment]
Keyboard shortcuts are not working in the branch at the moment for me. Ones that I know and have tried, any way (D/L for play, shift F10/F11/F12 for auto dj shortcuts).

**Pull request closed without merging**
