### PR TITLE
Tooltip Text changed from Interface to Decks

### PR DESCRIPTION
**Pull request by saksham28hans**
Resolving issue #11384  :  Changed the Tooltip text from Preferences->Interface to Preferences->Decks.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Welcome and thanks for improving this! Please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

**Comment by JoergAtGithub** [comment]
pre-commit failed because of https://github.com/mixxxdj/mixxx/issues/11386

**Comment by daschuer** [comment]
Since we have no string freeze yet in our 2.4 branch, it can go to that. Can you rebase this to 2.4? 
`git rebase --onto=upstream/2.4 HEAD~1`
`git push -f`
Thank you. 
Than we can edit the target branch in this PR to 2.4

**Comment by JoergAtGithub** [comment]
Mixxx Contributor Agreement is signed

**Comment by JoergAtGithub** [comment]
This looks good now! Thank you!

**Pull request merged**
