### PR TITLE
Vinyl Gain

### PR DESCRIPTION
**Pull request by daschuer**
This introduces the magic vinyl gain formular, discussed 
https://bugs.launchpad.net/mixxx/+bug/1450665

Currently the vinyl gain it is applied all the time.
In my test it provides actually a more natural scratching sound especial notable on Vocal samples. 

I have originally planed to conditional enable the gain. But I am unsure what the conditions are since also pitch changes with a scale of 90 %  are benefit from it and sounding more natural now. At a 10% pitch range there is a nearly no notable gain difference. 

Any ideas, for the conditions or improvements for the magic formular?

### CODE REVIEW

**Comment by daschuer** [comment]
The test are failing as desired. This way we can see the difference to the golden sample.

**Comment by Bronxio** [comment]
Hi! I've already tested in the official release, and I see that the autogain control for scratching is too much agressive, because when I spin it back at a low speed, it get too much loud and it's a little disgusting. Here you have a comparison with Traktor (that I think it has only a limiter or something, because cares for not being so loud), that respect the low volumes when scratching (and that's nice!) In both I spin the vinyl control back a little (more or less at a half speed), but gain mantain always the same volume (and in the Mixxx recording you can't say where I do that)
gain change

**Comment by Be-ing** [comment]
@daschuer if you merge master and push it, AppVeyor will make builds that @Bronxio could test easily.

**Comment by daschuer** [comment]
Cool, I did not know that Traktor has this feature. Is there a way to configure it somehow? 
Could you create a recording of a 1kHz sine wave scratching using Traktor? 
It schould also include a slow transition form full speed to zero. 
On one hand it this feature produces a natural scratch sound, on the other hand finding a beat at low speed is effected as well. Performs Mixxx any better for that?

**Comment by Bronxio** [comment]
> Is there a way to configure it somehow?
As far as I know, no. There are only "enable autogain" and "enable limiter" options, but can't find anything more.

traktor - enable autogain

Here you have the waves with 1 KHz with start and stop only. My turntables have adjustable start and stop speeds: they are set to the longest when I tested start and stop. 

1 khz comparisson

> On one hand it this feature produces a natural scratch sound, on the other hand finding a beat at low speed is effected as well. Performs Mixxx any better for that?

Well, as I said, I feel it too much aggressive. I prefer that gain was lower to lower speeds, like Traktor does.

Here, the same scratch sequence performed with both programs (without crossfader cuts)

scratch comparisson without crossfader

I feel more natural some gain changing. It's ok to avoid spikes (louder than original at higher speeds)

By the way, I tested Traktor with and without autogain and autolimiter, but autogain I think it's the classic option that just set a constant gain after finishing analyzing the track, and autolimiter may avoid spikes when mixing two or more tracks... but in my tests the autogain only set gain lower in all of them and I don't think the autolimiter did something.

traktor scratch autogain-autolimiter comparisson

**Comment by Bronxio** [comment]
Just a thought, the low gain at lower speeds issue could be and adjustable option as well in Mixxx preferences, because I guess some people will prefer the actual autogain set for scratching (and maybe not other DJ software have the option of change that)

And Be's right: if you want me to test alphas, let me know! :)

**Comment by Bronxio** [comment]
Here you have the start-stop tests of the first screen shot (Mixxx and Traktor with the 1 KHz tone). If you prefer better quality, just let me know. (Autogain and limiter were activated in Traktor, but I modified gain after recording in both tracks)

[start-stop tests (1 KHz, Mixxx 2.0.0 & Traktor).zip](https://github.com/mixxxdj/mixxx/files/1149919/start-stop.tests.1.KHz.Mixxx.2.0.0.Traktor.zip)

**Comment by daschuer** [comment]
It looks like Traktor limits the gain change by speed to lower speeds. Faster speeds are not effected. 
In this PR, I have tried to do it more natural and apply a gain boost on faster speeds as well.
In @Bronxio recordings, x5 speed is somehow a physical maximum before the needle is loosing contact. 
The curve applied here is at 5.5 dB in that case which should not clip with Mixxx's default gain leveling.

I hope we have windows builds soon for testing.

Due to waveform scratching, it is possible to get clipping think I will limit the gain changing to just 5.5 dB to avoid that. This should be no problems because we are above the physical possible speed.

@Bronxio: @Be-ing: 
Do you think we need a preferences option for this? I t is still possible to find beats well (now, without blowing the speakers by subsonic beats) so i think not.

**Comment by Be-ing** [comment]
I don't have the hardware to test this myself, but I doubt that a preference option would be appropriate. I presume there's one way to make it sound best.

**Comment by daschuer** [comment]
@Be-ing: You could use jog-wheel scratching like me. Please try to listen to the scratching sound on one hand and try to find a beat on the other hand. It is a good sight for no preference option, if you do not find any regressions.

**Comment by Be-ing** [comment]
I don't have any controllers with jog wheels. I didn't realize this PR affected jog wheels. I thought it only affected vinyl control. In that case there are many other contributors who could test this. @ronso0, @radusuciu want to test?

**Comment by daschuer** [comment]
Here is the improved formula. This should be natural for normal scratching, but no clipping at insane waveform scratching speeds at default gain leveling.

**Comment by Bronxio** [comment]
I agree with Be, I actually think it's not really necessary neither. If the best setting is found and there's no advantage to use it in another way, better not to give any option.

**Comment by daschuer** [comment]
Since we have actually an over proportional gain boost on high speeds, my last formular was just rubbish. I think we schould go with the original formular, but apply a hard limit at x 5 where we do not increase the gain any further.  In addition, my new formular is also not 0 dB at normal speed, which is also wrong.

**Comment by ronso0** [comment]
@daschuer  Do you want to change the formula or is this now working as intended? Just tell me when to test and I'll give it a try

**Comment by daschuer** [comment]
Now I am satisfied. Windows builds should be here soon: 
https://ci.appveyor.com/project/mixxxdj/mixxx/build/master-2278/job/8nrqglert4n6g22o/artifacts

**Comment by ronso0** [comment]
Oh this feels much better!
Don't have experience with vinyl, just made some quick test, mainly finding beats and dropping tunes in. Basic scratching sounds nice as well. Especially when scratching very slowly it doesn't sound like dragging a cheap mp3 anymore.
Thanks!

**Comment by daschuer** [comment]
Cool! Thank you for the feedback.
Any other likes to test before merge @ywwg @Be-ing?

**Comment by Bronxio** [comment]
Wooops, I thought that alpha wasn't ready yet because the checks messages!

I tested that alpha as well, and it's very nice! I've testing it about one hour and sounds more natural for me! I recorded a comparison with Traktor and it's very similar (with no crossfader cuts, and please don't mind the end, I stopped the tone with Mixxx and not with Traktor)

new alpha wave for scratching

If I notice something, I'll let you know; but I think it's great like this for the official 2.1 release. Thanks, daschuer!

**Comment by ronso0** [comment]
Yeaiy!
Using it with touch-sensitive jogwheels for a few weeks now, it feels very good.
Brake and SoftStart benefit as well!

**Comment by Be-ing** [comment]
So it seems we have 3 people saying this sounds better. I cannot test it. Ready for merge then?

**Comment by daschuer** [comment]
Yes, it looks like. If we get complains later, we can consider to bring the old behaviour back as preferences option.
Thank you for testing!

**Comment by Bronxio** [comment]
Until today, I never associated a known problem (at least by myself) with the magic formula (I thought it was a MixVibes control signal native problem or something, because I remember failures like this in MixVibes Cross); but just to be sure... Could this bug be related with it (too much gain)? It only happens with fast spins: the wave position changes in the control vinyl. I recorded a video to show how it happens.

https://youtu.be/M1h2go2fH90

**Comment by daschuer** [comment]
This bug effects only the gain of the Mixxx output, not the transport. 
So your issue is a separate one. 

Please file a new bug, link the very good video and add also a vinyl pass through recording (the time code sound) from a scratching similar to that in the video. 
I assume we have an filter or something which is messed up with that fast scratching.   
Did you use relative or absolute mode?

**Comment by daschuer** [comment]
A new bug at https://bugs.launchpad.net/mixxx/+filebug

**Comment by Bronxio** [comment]
Ready! [bug reported](https://bugs.launchpad.net/mixxx/+bug/1714366).

**Comment by Be-ing** [comment]
I tested clicking and dragging the waveform and it sounds better with this.

**Pull request merged**
