### PR TITLE
skins: disable spinnies by default

### PR DESCRIPTION
**Pull request by Be-ing**
Spinnies cause extreme performance problems on macOS. I have tried
optimizing them, but even a minimal example drawing a single
QImage is practically just as slow.

### CODE REVIEW

**Review by uklotzde — APPROVED** [review]
@ronso0 Opinions?

**Comment by Be-ing** [comment]
Hold on, let's see if I can get Mixxx building on GH Actions with the macOS 10.13 SDK. Then this might not be needed.

**Comment by ronso0** [comment]
> @ronso0 Opinions?

Well, if that's the last resort to get good visual perfromance at least with the initial skin configuration..

**Comment by Be-ing** [comment]
Closing in favor of #3420

**Pull request closed without merging**
