### PR TITLE
[WIP] LateNight :: color knobs

### PR DESCRIPTION
**Pull request by ronso0**
no changes yet, for now this is just for discussing the possibilities as started in #1905 

Colored knobs would greatly improve the UX, especially for the 4-decks mixer where we have up to 5 identical knobs in a column.

Yes, this would break the LateNight tradition ;)

before:
latenight-color-knobs_before

proposal #1:
latenight-color-knobs_now

### CODE REVIEW

**Comment by Be-ing** [comment]
I like this solution better than #1905, although I personally don't like the color used for the EQ knobs very much.

**Comment by nopeppermint** [comment]
I like this as well.
maybe you could take another color for the gain, maybe blue?
or stay with orange, I don't care

**Comment by ronso0** [comment]
colors are just for illustration. 
the same base color for all knobs but different brightness values could work as well.

**Comment by daschuer** [comment]
I like the idea. Alternative you may alter the knob inner. Shades of gray may work. For me this is an addition to #1905 we can consider bot ideas independently.

**Comment by ronso0** [comment]
what about this one?
Gain: orange
FX/Meta/Super: green like FX enable buttons
latenight-colors_2

**Comment by ronso0** [comment]
@ywwg @esbrandt How do you like it?

**Comment by nopeppermint** [comment]
looks good

**Comment by ywwg** [comment]
I like it! I sometimes mix up the quickfx knob with the eq knobs so this helps.

**Comment by nopeppermint** [comment]
> I sometimes mix up the quickfx knob with the eq knobs

I had exactly the same problem..

**Comment by ywwg** [comment]
this is good for now, but I'd be ok with coming up with an even more different design for different types of knobs in the future.

**Comment by ronso0** [comment]
Coool.
@ywwg What do you have in mind?

the GiMP file I used for the mockups, with layers for each knob category:
[LateNigh - Color knobs.xcf.tar.gz](https://github.com/mixxxdj/mixxx/files/2601699/LateNigh.-.Color.knobs.xcf.tar.gz)

**Comment by ywwg** [comment]
for instance, what if the fx knob was mostly green with a black indicator stripe? or if the gain knobs had a dot indicator instead of a line.  There's lots of ways to work within the latenight style that would differentiate the different types of knobs more.

**Comment by ronso0** [comment]
Aah okay, you'd to redesign, got it. For some reason I considered the LateNight design being settled, therefore I was always trying to keep the essential shapes, like knobs and buttons.

**Comment by ronso0** [comment]
latenight-knob-colors

For consistency, I also changed the FX parameter knobs & buttons to green.
Is this okay for everyone?

**Comment by nopeppermint** [comment]
in my opinion there is not much visible difference between the red and orange knob, maybe replace orange with blue?

**Comment by daschuer** [comment]
.. or yellow. 
It looks already nice.

**Comment by ronso0** [comment]
yeah, yellow would be better. Blue is rather cold while the other knobs have warm colors.
What about this:
latenight-brighter-orange

**Comment by ywwg** [comment]
> Aah okay, you'd to redesign, got it. For some reason I considered the LateNight design being settled, therefore I was always trying to keep the essential shapes, like knobs and buttons.

there are parts of the latenight design that are really important (to me at least :3), like the stacked waveforms. But if there are other changes you'd like to make I'd like to hear what they are.

**Comment by ronso0** [comment]
Like this? It's quite bright, and it's to close to the green (see Headphone mixer)
latenight-yellow-gain

**Comment by ronso0** [comment]
> there are parts of the latenight design that are really important (to me at least :3), like the stacked waveforms. But if there are other changes you'd like to make I'd like to hear what they are.

hmm nothing comes to mind, exept some tweaks like this. Looking forward to your knob designs though. If I'd start playing with the design I'd probaly create a whole new skin ;)

**Comment by nopeppermint** [comment]
> Like this? It's quite bright, and it's to close to the green (see Headphone mixer)

that's true
what's about the orange we use for the highlight of the selected tab (library/search)?

**Comment by ronso0** [comment]
> the orange we use for the highlight

... would be even closer to red than my initial proposal.
I'd go with the dark yellow https://github.com/mixxxdj/mixxx/pull/1910#issuecomment-441223873

**Comment by ronso0** [comment]
Ready to merge?

**Comment by daschuer** [comment]
Yes. LGTM Thank you.

**Pull request merged**
