### PR TITLE
components.js fixes

### PR DESCRIPTION
**Pull request by eigengrau**
Since `forEachComponent` evaluates callbacks within the context of the current
component container, `this.currentDeck` will be undefined after we recurse into
a component container inside of the current deck.

Instead, we now propagate the current deck downwards by referring to the
argument `setCurrentDeck` was invoked with.

### CODE REVIEW

**Comment by uklotzde** [comment]
I suppose this branch should be rebased and targeted towards *mixxxdj:2.1*?

**Comment by eigengrau** [comment]
Rebased.

**Comment by Be-ing** [comment]
LGTM thank you for catching this subtle bug.

**Comment by Be-ing** [comment]
Before we merge your first pull request, please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you are done. In a nutshell, this allows us to distribute your work in the Mac App Store which has some terms that conflict with the GPL.

**Comment by Be-ing** [comment]
I tested this with the Hercules P32 mapping and confirm it still works.

**Comment by daschuer** [comment]
Can we move this to 2.1.x and release 2.1.1 this week?

**Comment by Be-ing** [comment]
This is already assigned to the 2.1.1 milestone.

**Comment by daschuer** [comment]
We need the signing. Will we get it before 2.1.1 release. If not we should move it to 2.1.x

**Comment by eigengrau** [comment]
Signed off!

**Pull request merged**
