### PR TITLE
Fix search in external libraries 

### LINKED ISSUE #11216: No search for Rythmbox Mixxx 2.3
### Bug Description

The search box is not enabled for the Rythmbox library in Mixxxx 2.3 HEAD 
Mixxxx 2.4 is not affected. 

### Version

2.3

### OS

Linux

### PR DESCRIPTION
**Pull request by daschuer**
This re-anable the search for external libraries. 
It fixes bug #11216 

Yes, QString("") means search enabled and QString() disabled. This magic has already been fixed in 2.4. 
We need to make sure to revert this PR during merge.

### CODE REVIEW

**Comment by ronso0** [comment]
For reference:
#11129 has the drive-by fix for main
the actual issue QString::isEmpty() != QString::isNull(), see https://github.com/mixxxdj/mixxx/pull/11129#discussion_r1050934342

I'll review this one asap

**Review by ronso0 — APPROVED** [review]

**Comment by ronso0** [comment]
LGTM, thanks!

**Comment by ronso0** [comment]
@daschuer Could you take care of merging into 2.4?
I'm not sure how to resolve the Serato color conflicts.

**Comment by daschuer** [comment]
Done.

**Pull request merged**
