### PR TITLE
Fix decoding of corrupt FLAC files (fixes bug #1406815)

### PR DESCRIPTION
**Pull request by uklotzde**
Prevents Mixxx from crashing

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for the fix. It looks good to me. 

Just one thought: Can you share some more info about you finding as comment? 

Is the file really corrupt or do we hit a limitation of Mixxx or the used encoder. 
Just had a look in: https://xiph.org/flac/format.html#frame_header
and it seams to be hard to get a too big block size since all bits are valid. 

Can it be a issue inside the decoder or a stereo/mono issue inside Mixxx?  

So it may be finally just an unsupported File .. ?

**Comment by Be-ing** [comment]
No, it is a corrupted file. I attached the file to the bug report. I accidentally formated my partition with all my music a year and a half ago and used an undelete program to recover what I could. I ended up with a lot of music files that stopped at random times (and occasionally files that spliced tracks together), which is likely where this corrupted file came from.

While this fix takes care of this specific way a FLAC file can be corrupted, I am wondering if it would be possible to have a more generic way of detecting corrupted files that might work for other ways files could be corrupted and/or other codecs. However, I have never had Mixxx crash when loading any other file format, including MP3s that were corrupted.

**Comment by uklotzde** [comment]
The file is indeeed corrupt. The maximum block size reported by the stream info is less than the actual block size in one of the frames. Decoding of a file should stop immediately when encountering such an invalid frame.

The size of the temporary sample buffer for decoding depends on the maximum block size in the stream info. There was no check that the block sizes of individual frames are not greater than this limit.

**Comment by rryan** [comment]
> I am wondering if it would be possible to have a more generic way of detecting corrupted files that might work for other ways files could be corrupted and/or other codecs. However, I have never had Mixxx crash when loading any other file format, including MP3s that were corrupted.

The goal here is that we will eventually move all decoding to a separate process so that crashes in decoding don't affect Mixxx itself. We'll also have to do this for external effect plugins.

**Comment by daschuer** [comment]
Thank you for the fix! LGTM

**Pull request merged**
