### PR TITLE
Force components.SamplerButton volume to max when not velocity sensitive

### PR DESCRIPTION
**Pull request by Swiftb0y**
Obvious Issue from the last samplerbutton change: When you disable the velocity sensitive feature, the deck is stuck at the volume it last played at. In the first commit I am forcing the volume to 1 whenever the unit gets triggered. In the second commit I am proposing a different solution where I reset value only when the button gets disconnected from the unit. I am not sure which solution is better so I am proposing both. I'd revert the solution we don't want once we decided.

### CODE REVIEW

**Comment by Holzhaus** [comment]
Couldn't this cause spikes in volume if I switch away from the velocity sampler mode while a long sample is playing?

**Comment by Swiftb0y** [comment]
Yes. so we should go with the solution in the first commit?

**Comment by Holzhaus** [comment]
I'm not sure. Ideally there would be a CO to set the volume of a sample when it is started, but does not change the volume of samples that are already playing.

**Comment by Swiftb0y** [comment]
Should we still merge this? Even though it obviously doesn't properly fix the issue, its still a bandage that helps a bit. If everyone agrees, I'll resolve the merge conflicts and test it. If not, we should close the PR and document the issue on launchpad.

**Comment by Holzhaus** [comment]
I'll close this for now. IMHO samplers need two volume settings, one is the regular volume and one is the velocity volume, and then we need to add a new CO to start playback that takes the velocity volume as input.

**Comment by Swiftb0y** [comment]
I agree, tho the current behavior is a bug IMO and this PR would've worked around it, but I guess as long as we don't receive any complaints, its fine.

**Pull request closed without merging**
