### PR TITLE
Add battery widget to Shade skin

### PR DESCRIPTION
**Pull request by rrrapha**
preview

preview

I'm open for other suggestions..

### CODE REVIEW

**Comment by daschuer** [comment]
It looks like this in my case: 

grafik

You may consider to color only two and use the pink highlight color of the buttons. 
The black for the full battery looks massive. Since it is a good normal state is should be more decent.  

By the way, is the battery hidden, in case the device has no battery? 

Looking at the ON AIR text, it looks wrong somehow. I think we should use the techno fonts from the other labels. We can also consider to use a question mark and a Mains Icon in this style. 

It is quite hard though, here my attempt: 
grafik

**Comment by rrrapha** [comment]
> It looks like this in my case:

Are you running 2.2? This scaling issue should be fixed with https://github.com/mixxxdj/mixxx/commit/60c9a2e71f17bf156288b11e4d69dabc1b352b03.

> By the way, is the battery hidden, in case the device has no battery?

I think the `<PixmapUnknown>` is shown if there is no battery.

**Comment by daschuer** [comment]
Ah yes, I will re-test with master. 

Can we distinguish between no battery installed and unknown? 
I think we should not bother desktop pc users with the question mark icon.

**Comment by daschuer** [comment]
I think the charging battery should be always gray.

**Comment by rrrapha** [comment]
> Can we distinguish between no battery installed and unknown?

We could distinguish between no battery detected and unknown.
IMO we should just hide the widget in both cases and never show the unknown icon. 
Any opinions?

> I think the charging battery should be always gray.

I won't change the colors for now, but it is easy to do using sed or similar.

**Comment by Be-ing** [comment]
> We could distinguish between no battery detected and unknown.
IMO we should just hide the widget in both cases and never show the unknown icon.

I agree, and I don't think skins should be responsible for this. I think the WBattery widget code should take care of this.

**Comment by ronso0** [comment]
> > Can we distinguish between no battery installed and unknown?

> We could distinguish between no battery detected and unknown.
IMO we should just hide the widget in both cases and never show the unknown icon.

When does 'unknown' occur?

**Comment by rrrapha** [comment]
> When does 'unknown' occur?

The current implementation sets the state to `Battery::UNKNOWN` when no battery is
found or the status is unknown.
If I understand correcly, the status should not be `UNKNOWN` if a battery is found, but it can happen because of driver problems, broken batteries or similar.

**Comment by Be-ing** [comment]
Looks good to me. @daschuer ready for merge?

**Comment by daschuer** [comment]
The mains plug was one of may failed attempts. The rest looks good for me.
If no one has a better idea, I think we should go with the original flash or the pixeled "->".
I would be happy if you prepare such version.
Thank you :-)

**Comment by rrrapha** [comment]
Something like this?
preview
preview

**Comment by Holzhaus** [comment]
@rrapha Looks good IMO.

**Comment by Be-ing** [comment]
LGTM thank you @rrrapha.

**Pull request merged**
