### PR TITLE
LateNight Optimizations

### PR DESCRIPTION
**Pull request by synthor**
For descripton see closed pull requests 632 and 633.

This one now targets 1.12 instead of master.

### CODE REVIEW

**Comment by ywwg** [comment]
ah, you'll have to do the following:

* record the hex numbers of the commits from your changes
* check out 1.12
* make a new branch from that
* git cherry-pick the commits from your changes in order

**Comment by synthor** [comment]
I already thought in that direction. I created a branch of the master and worked on it.

Thanks for your patience and help. :)

**Comment by daschuer** [comment]
you may try:
git rebase  ab53f56 --onto 1.12

**Comment by daschuer** [comment]
@ywwg: except the rebase issue, is this PR mergeable? 

@synthor: 
In order to merge you PR, wee need you permission. 
Please sign: https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ
and comment here when done. 
Do you have a Lunchpad account? I can add you to the contributor group. 
If you like, you can rebase this branch, if not it is no deal for me to do it just before merge.

**Comment by synthor** [comment]
I'm working on it, or try to. Your suggested rebase and ymmd hint didn't work. Looks like I messed up the 1.12 branch in my remote repository. I accidentally pushed the changes into that...

Any hint how to fix this? I really have to clue atm. Gonna get a cup of coffee and will read to find a solution for that. :)

**Comment by ywwg** [comment]
yes this PR is fine other than the merge issues

**Comment by daschuer** [comment]
This may help as well: http://pivotallabs.com/git-rebase-onto/
But nevermid, if you have already messed up your local repo, I will rebase it tonight once you have signed.

**Comment by synthor** [comment]
Managed to get my upstream/1.12 branch now beeing the same as origin/1.12. If I can mess up my local repository, I should be able to fix it again. So let me try to rebase it, otherwise I'll never learn how to use Git. ;)

Btw. I'm hungry, so I'll make a break and work on this one in 1-2 hours. Also sign and send you my Launchpad account details.

**Comment by synthor** [comment]
Looks good now, or?

**Pull request closed without merging**
