### PR TITLE
lp1879656 Track info: Show file name for tracks without artist&title

### PR DESCRIPTION
**Pull request by uklotzde**
https://bugs.launchpad.net/mixxx/+bug/1879656

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
LGTM, 

Unfortunately users Paring the window title for broadcasting need to adjust the parser. 
But that is OK, since we are not in the beta period.

**Comment by daschuer** [comment]
The pre-comit hook fails in res/skins/Deere/deck_text_row.xml because of a trailing white space. 
That does not matter.

**Comment by daschuer** [comment]
@uklotzde: Can you also add a changelog entry? This is a significant change for window headline paring useres.

**Comment by Holzhaus** [comment]
> The pre-comit hook fails in res/skins/Deere/deck_text_row.xml because of a trailing white space.
That does not matter.

Was this issue introduced in this PR? We shouldn't merge PRs with issues like these. Now the CI pre-commit job for every PR based on 2.3 will fail.

**Comment by uklotzde** [comment]
I have run the pre-commit hook locally and it fixed line endings in 3 files. No idea why this now failed on CI? I'll fix the remaining issues with the CHANGELOG updates.

**Comment by uklotzde** [comment]
@daschuer This string was buried deep inside the implementation as a plain literal without any documentation!!

**Comment by uklotzde** [comment]
res/skins/Deere/deck_text_row.xml doesn't no longer contain any whitespace or line ending issues. Instead these should have been fixed by this PR.

**Pull request merged**
