### PR TITLE
Pitchbend direction fix lp1770745

### PR DESCRIPTION
**Pull request by daschuer**
This fixes some pitchbend issues including https://bugs.launchpad.net/mixxx/+bug/1770745
See commit messages. 

It also adds a test.

### CODE REVIEW

**Comment by daschuer** [comment]
Before the patch we had:
Up increase, Abrupt "->" = faster (default)
Up increase, Smooth "->" = faster 
Down increase, Abrupt "->" = faster 
Down increase, Smooth "->" = slower (fixed with this patch) 

I have tested this and with the parallel waveforms, the odd thing is that "faster"  moves the waveform faster to the left, this means "<-" relative to the second deck waveform. 
@ronso0 is that a usability issue?

**Comment by daschuer** [comment]
Appveyor fails unrelated.

**Comment by ronso0** [comment]
that's a consequence of the opposite directions of the play position on the overview and the scrolling waveform moving underneath the static playposition. Neither the Play icon nor any seek or nudge icons are intuitive if they are related to the scrolling waveform. Since those buttons are located in sections of a deck they're closer to the overview, so I think the nudge icons are more intuitive as they are now than if we'd mirror them.

Maybe some kind of right-pointing arrow overlay/icon on or near the waveform play position marker would emphasize it's not the waveform underneath but actually the (static) play position line that's moving. Would that reduce the confusion?

**Comment by daschuer** [comment]
Right. Since I have never noticed the issue before and we have no user complaining about this. So I think we can stick with the current situation.

**Comment by uklotzde** [comment]
Does this introduce conflicts with #1924?

**Comment by uklotzde** [comment]
I haven't checked every conditional branch, but so far the code looks good. It is at least more reasonable than before.

**Comment by daschuer** [comment]
Does it mean we can merge this?

**Comment by uklotzde** [comment]
Tested successfully. LGTM.

**Pull request merged**
