### PR TITLE
[WiP] Pre C++17: Upgrade to googletest-1.8.1 or 1.10.0

### PR DESCRIPTION
**Pull request by uklotzde**
Using the most recent version 1.10.0 didn't work as expected, so let's start with 1.8.1 as a prerequisite for C++17.

The code has been adopted from #2428. It uses a renamed lib directory that reflects the actual project name.

### CODE REVIEW

**Comment by Holzhaus** [comment]
Since this also fixes the mysterious failing Travis CI builds on OSX, let's try to merge this ASAP.

**Comment by uklotzde** [comment]
All CI builds green again.

**Comment by uklotzde** [comment]
@Holzhaus One minor improvement would be to include the top-level CMakeLists.txt project instead of googletest and googlemock separately. Currently VERSION is undefined for both libs and CMake prints a warning.

**Comment by uklotzde** [comment]
Awaiting  build results from AppVeyor on Windows:
https://github.com/uklotzde/mixxx/commit/8fad4f834c5cc6dda372398b2e57c9f844f75bf0
https://ci.appveyor.com/project/uklotzde/mixxx/builds/30043876

**Comment by uklotzde** [comment]
Finally, I now try upgrading to googletest-1.10.0 directly:
https://travis-ci.org/uklotzde/mixxx/builds/635666045
https://ci.appveyor.com/project/uklotzde/mixxx/builds/30044601

**Comment by uklotzde** [comment]
Closed in favor of #2439

**Pull request closed without merging**
