### PR TITLE
Qm dsp upstream changes

### PR DESCRIPTION
**Pull request by daschuer**
The Queen Mary DSP repro is alive. 
I have worked with @cannam to integrate the proposed patches. 
Chris has also found a better solution for the noise issue #2112.
Thank you very much.

### CODE REVIEW

**Comment by uklotzde** [comment]
I guess the file  "lib/qm-dsp/mixx-changes.patch" should not be included?

**Comment by daschuer** [comment]
I have kept it to document our changes that are still differ from upstream. 
They are already purposed. So hopefully we can use a unchanged version later.

**Comment by uklotzde** [comment]
Then at least the typo in the file name should be fixed.

**Comment by daschuer** [comment]
OK file renamed and forced pushed.

**Comment by uklotzde** [comment]
I'll test the changes and also disable the mutex for the key analyzer.

**Comment by uklotzde** [comment]
LGTM.

Thank you also for getting in contact with the QM team! Hopefully we can unify the key detection algorithms in the future.

**Pull request merged**
