### PR TITLE
[WIP]: Denon mc7000 parameter buttons

### PR DESCRIPTION
**Pull request by flosse**
**Motivation**:
Currently the parameter buttons modify the stars of a track or (if shifted) it changes the color.
I never used this functionality and if I would, I'd do that at home at the laptop and not at stage
whereas during a live performance I really like to have quick access to buttons for beat jumps.

If somebody really like to keep the old behavior I could introduce a boolean flag in the script,
otherwise I'd suggest do map this as default behavior.

**Note**:
This is based on #4307 but if you like me to rebase it to `2.3` branch just tell me :)

### CODE REVIEW

**Comment by flosse** [comment]
BTW:
I'm going to remove the code style issues in a separate commit soon.

**Comment by ronso0** [comment]
Please describe the new button configuration in detail in the first post.

> parameter buttons modify the stars of a track or (if shifted) it changes the color.
I never used this functionality and if I would, I'd do that at home at the laptop and not at stage
whereas during a live performance

I often change the star ration from the controller as I hate to use the trackpad for that -- btw that's why I added the stars-up/down controls to Mixxx ; )
Seriously, I think there are users who prefer either configuration, both are valid IMO, while there's probably higher demand for beatjump controls. That said I suggest to go with the bool flag.

**Comment by ronso0** [comment]
Oh, it looks like this is your first contribution!
Please sign the [[contributor agreement]](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here afterwards.

Thank you!

**Comment by ronso0** [comment]
@toszlanyi What are your thoughts?

@flosse Please also open a PR for the manual https://github.com/mixxxdj/manual/ to change the mapping documentation accordingly.

**Comment by flosse** [comment]
> Oh, it looks like this is your first contribution!

not really.. see https://github.com/mixxxdj/mixxx/pull/206 :smile: 

> Please sign the [contributor agreement]

ok, I can do that additionally.

**Comment by flosse** [comment]
> @flosse Please also open a PR for the manual https://github.com/mixxxdj/manual/ to change the mapping documentation accordingly.

sure, I'll do that.

**Comment by toszlanyi** [comment]
> during a live performance I really like to have quick access to buttons for beat jumps.

Hello @flosse - In my first mapping I used the Parameter buttons as beatjump too but changed them with the Mixxx 2.3 update as **Beatjump is available with the performance pads -> Slicer mode**. I already updated the mapping to implement a counter with the pad LEDs. Please refer to the [user manual](https://manual.mixxx.org/2.3/en/hardware/controllers/denon_mc7000.html#beatjump-mode-red-led).


> I often change the star rating from the controller as I hate to use the trackpad for that -- btw that's why I added the stars-up/down controls to Mixxx ; )

@ronso0 - I really like to be independent of the laptop too and would keep the star and color mod by controller as well.

**Comment by ronso0** [comment]
> Beatjump is available with the performance pads -> Slicer mode

In that case I recommend to keep the stars/color controls, but add the beatjump controls as quick access alternative, activated by the bool flag in the script file as you suggested @flosse

**Comment by fwcd** [comment]
#13589 has now been merged to 2.5, which implements this.

**Pull request closed without merging**
