### PR TITLE
CI: Drop workarounds for sccache v0.2.x

### PR DESCRIPTION
**Pull request by uklotzde**
...after sccache v0.3.0 has been released.

### CODE REVIEW

**Comment by uklotzde** [comment]
First build on Windows: 47m

**Comment by uklotzde** [comment]
The new cache key does not depend on any particular version of sccache. Not sure if this is still needed.

**Comment by daschuer** [comment]
At least the original referenced commit is part of the 0.3.0 release 
https://github.com/mozilla/sccache/commit/3f318a8675e4c3de4f5e8ab2d086189f2ae5f5cf

The 9 minutes penalty is concerning though. 
I think we need a windows user to verify the performance before merge. 

Should we also pin the version?

**Comment by uklotzde** [comment]
2nd build: 16m

**Comment by uklotzde** [comment]
> Should we also pin the version?

Probably. https://github.com/mixxxdj/mixxx/pull/4741/commits/785eb2f33090cd4b8632593e232a9beb246a31a6

**Review by daschuer — APPROVED** [review]
OK than let's merge this. Thank you for taking care.

**Pull request merged**
