### PR TITLE
remove use of deprecated TagLib::String::null

### PR DESCRIPTION
**Pull request by Be-ing**
This causes link errors on Windows when TagLib is built dynamically
https://github.com/taglib/taglib/issues/651

### CODE REVIEW

**Comment by Holzhaus** [comment]
> Changing the default parameter to an empty value ( String() or "" ) would change the behavior of the method. Passing an empty string means "remove all empty tag named xxx" and passing null argument means "remove all tags with name xxx". These two legitimate intentions should be possible.

https://github.com/taglib/taglib/issues/651#issuecomment-136006998

**Comment by Holzhaus** [comment]
> > Changing the default parameter to an empty value ( String() or "" ) would change the behavior of the method. Passing an empty string means "remove all empty tag named xxx" and passing null argument means "remove all tags with name xxx". These two legitimate intentions should be possible.
> 
> [taglib/taglib#651 (comment)](https://github.com/taglib/taglib/issues/651#issuecomment-136006998)

Instead of passing `TagLib::String::null`, I think `tag->removeFields("ALBUM ARTIST");` should now be called instead.

**Comment by Be-ing** [comment]
`TagLib::String::isNull`, which we use in lots of places, is also deprecated. So I think the best solution would be using `std::optional<TagLib::String>` instead.

**Comment by Be-ing** [comment]
On a closer look, I don't think we actually use `TagLib::String::isNull`. Grepping src/track for `isNull` returns lots of results, but those are methods of other classes, not `TagLib::String`.

**Comment by Be-ing** [comment]
We scarcely use `TagLib::String` in our own application logic. It is only used to create temporary values converted from QStrings. The various functions for writing `TagLib::Strings` to file tags check `TagLib::String::isEmpty` already, not `TagLib::String::isNull`.

**Comment by uklotzde** [comment]
> `TagLib::String::isNull`, which we use in lots of places, is also deprecated. So I think the best solution would be using `std::optional<TagLib::String>` instead.

I also thought about this. If it helps with the migration then use it to not touch the remaining logic of the existing functions.

**Comment by uklotzde** [comment]
More changes: https://github.com/Be-ing/mixxx/pull/54

**Comment by uklotzde** [comment]
Merge? I guess we have no other choice. No issues so far, but I didn't have time for extensive tests.

TagLib is almost dead. Don't expect any new releases unless someone else takes over.

**Review by uklotzde — APPROVED** [review]

**Comment by Be-ing** [comment]
TagLib is not dead. https://github.com/taglib/taglib just had a commit 3 days ago. But I don't know why there hasn't been a release in 4 years.

**Comment by Be-ing** [comment]
https://github.com/taglib/taglib/issues/991

**Comment by Holzhaus** [comment]
> [taglib/taglib#991](https://github.com/taglib/taglib/issues/991)

> There's a second 1.12 beta planned for next week, and a final 1.12 release planned for February.

**Comment by Holzhaus** [comment]
I think we have the same problem with `TagLib::ByteVector::null`:

```
$ grep -HrnP '::null\b' src/
src/track/taglib/trackmetadata_common.h:69:        return TagLib::ByteVector::null;
src/track/taglib/trackmetadata_common.cpp:62:        // TagLib::null/isNull() is deprecated so we cannot distinguish
src/track/taglib/trackmetadata_common.cpp:72:        // TagLib::null/isNull() is deprecated so we cannot distinguish
```

**Comment by Holzhaus** [comment]
And we also need to remove:

```
$ grep -HrnP '\bremoveField\b' src/
src/track/taglib/trackmetadata_xiph.cpp:82:        pTag->removeField(key);
```

See https://github.com/taglib/taglib/issues/651 for details.

**Comment by uklotzde** [comment]
Same refactoring as for TagLib::String and then hope that nothing breaks.

**Comment by Be-ing** [comment]
merge?

**Comment by Holzhaus** [comment]
> merge?

It's still incomplete. We still need something like this: github.com/Holzhaus/mixxx/commit/51d1d73a736875e15bc74e33a07c2e7c9d22e078

**Comment by Be-ing** [comment]
@Holzhaus do you want to open a new PR then?

**Comment by Holzhaus** [comment]
You could also cherry pick that commit, do we keep the discussion in one place

**Pull request merged**
