### PR TITLE
[in progress] Skin lazy loading

### PR DESCRIPTION
**Pull request by daschuer**
This is a prove of concept for the skin singleton lazy loading idea. 
It actually works, but it needs some tidy up.
The library singleton is now broken, I think we need a switch for using explicit lazy loading.
I am in doubt that we finish this for Friday.

### CODE REVIEW

**Comment by Be-ing** [comment]
IMO it is no big deal if this isn't finished for the initial beta release as long as it is solved for the final release.

**Comment by Pegasus-RPG** [comment]
Anything that breaks things should either go into the first beta or be scheduled for the next release, with a strong preference for the latter. The whole point of beta testing is to ferret out bugs and that requires a fixed target.

**Comment by Be-ing** [comment]
I'm not certain this is a very good solution. As far as I understand, it wouldn't solve the issue at all for users who do want to use a whole 8x8 grid of samplers. Can you think of any other ways to optimize the skin loading and destruction processes? I did some profiling with Calgrind and it seemed the issue was the sheer number of calls to parseNode. I'm not sure if those profiling results were very informative with all the recursive calls to parseNode with so many WidgetGroups.

**Comment by daschuer** [comment]
> I'm not certain this is a very good solution. As far as I understand, it wouldn't solve the issue at all for users who do want to use a whole 8x8 grid of samplers.

Yes, that is true. But since this is a minority of users, it will actually help. 

It would help if we change the way the xml templating works. Currently we build a kind of virtual gigantic skin.xml which is parsed line by line. Each of the sampler templates is parsed 64 times. 
If we can store intermediate results and reuse them, this will also help.

**Comment by Be-ing** [comment]
Yeah, I had a similar idea. But it seems easier said than done. If you have ideas for how to go about that, I think that would be a better idea to implement than this.

**Comment by ronso0** [comment]
For me the actual 'issue' is skin un-loading. I don't mind (neither do my fellow DJs) if Mixx takes half a second longer to load. But seeing that 'Application is unresponsive' screen when closing or reloading Mixxx is annoying...
What is happenig then that takes so long?

**Comment by Be-ing** [comment]
Skin loading and shutdown time is still a big problem, but I do not think the approach this PR takes is a good solution. We are in no rush now to meet an impending feature freeze, so I think we should try to come up with a less hacky solution.

**Pull request closed without merging**
