### PR TITLE
[WIP] Tango :: fx controller focus tweak

### PR DESCRIPTION
**Pull request by ronso0**
This adds a subtle indicator telling users which unit the controller currently controls.
This only affects those who use **midi-components** and initialize fx units with
`[controller_prefix].effectUnit13 = new components.EffectUnit([1,3],true);` where `true` allows `[FxUnit],show_focus` even though the fx unit is collapsed.

If there's a broader demand for this feature midi-components needs to be altered so that the indicator also works with `bool allowFocusWhenParametersHidden = false`.

In expanded fx units the indicator works better IMO than only showing fcus buttons.

I'd like to add this to other skins as well but didn't have a look at them, yet.

tango-fx-tweak1

tango-fx-tweak2

### CODE REVIEW

**Comment by Be-ing** [comment]
Can you clarify how the "focused" effect unit is represented? Is it the effect unit that has `show_focus` set to 1? Or `focused_effect` not 0? Or both?

**Comment by ronso0** [comment]
> Is it the effect unit that has `show_focus` set to 1?

Yes.

**Comment by ronso0** [comment]
> If there's a broader demand for this feature midi-components needs to be altered so that the indicator also works with bool allowFocusWhenParametersHidden = false.

Of course, we'd need to use another control that [FxUnit],show_focus then.

**Comment by daschuer** [comment]
I have not yet understand the use case of this PR. 

Originally the focused effect was only highlighted if show_focus was enabled. 
Now the focused effect is always highlighted.

Currenty it behaves similar to Shade, which is probably also wrong.

See:
https://www.mixxx.org/wiki/doku.php/mixxxcontrols

**Comment by ronso0** [comment]
okay, I'll take another look next week

**Comment by ronso0** [comment]
fixed. it's now as before for those who don't set "show_focus" manually or with the mapping.

**Comment by ronso0** [comment]
I don't really get used to the gradients in the focus arrows. I'll try something else..

**Comment by ronso0** [comment]
Instead of abusing `show_focus` I'll try another approach, probably with midi-components.js itself by making `currentUnit` available as CO somehow

**Pull request closed without merging**
