### PR TITLE
LateNight 2.3 polishing

### PR DESCRIPTION
**Pull request by ronso0**
Mixer
* simplify mixer templates, better performance when switching 2/4 decks, less glitches
* Main / Head: accomodate Booth knob and 4 permanent Fx buttons

Samplers (PaleMoon)
* styled like decks, separate play/cue controls, gain & rate more
* relaxed colors & contrast for gain & pitch slider

Effects: dimension Super / Wet/Dry knobs like Meta knobs

Tool bar: expose clock more

image

### CODE REVIEW

**Comment by ronso0** [comment]
small ToDo:
fix / update some template descriptions

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you.

**Comment by uklotzde** [comment]
@ronso0 Are you able to resolve the merge conflicts and merge 2.3 into main?

**Comment by ronso0** [comment]
@uklotzde 

> Are you able to resolve the merge conflicts

sure.

> and merge 2.3 into main?

never did it before.. I knew that day would come :)
what's the procedure exactly?

```
git fetch mixxx
git checkout mixxx/main
git merge mixxx/2.3
```
* fix conflicts
* test if it builds
* also need to run the tests?

`git push mixxx/main`

**Comment by Holzhaus** [comment]
Yes, but instead of `git merge` you can just use `git pull mixxx 2.3`.

**Comment by ronso0** [comment]
okay.

> also need to run the tests?

**Comment by Holzhaus** [comment]
> okay.
> 
> > also need to run the tests?

Yes. `ctest -j$(nproc) --output-on-failure`

**Comment by ronso0** [comment]
there's also a conflict in browsetablemodel.cpp

```diff
diff --cc src/library/browse/browsetablemodel.cpp
index 01829aedf8,3e9b994ca7..0000000000
--- a/src/library/browse/browsetablemodel.cpp
+++ b/src/library/browse/browsetablemodel.cpp
@@@ -134,8 -163,8 +164,13 @@@ BrowseTableModel::~BrowseTableModel() 
  }
  
  int BrowseTableModel::columnIndexFromSortColumnId(TrackModel::SortColumnId column) {
++<<<<<<< HEAD
 +    if (column == TrackModel::SortColumnId::SORTCOLUMN_INVALID ||
 +            column >= TrackModel::SortColumnId::NUM_SORTCOLUMNIDS) {
++=======
+     if (column < TrackModel::SortColumnId::IdMin ||
+             column >= TrackModel::SortColumnId::IdMax) {
++>>>>>>> e10a8270a1f51661c0097626c5fea5aa1df56c8f
          return -1;
      }
```
didn't follow that sort PR that much, guess I pick the HEAD section?

**Comment by Holzhaus** [comment]
No, the other one :)

Btw, I find it hard to resolve merge conflicts without a proper 3-way diff:

https://psung.blogspot.com/2011/02/reducing-merge-headaches-git-meets.html?m=1

**Comment by ronso0** [comment]
strange: now have to `#include <QWindow>` in src/library/librarycontrol.cpp to get rid of this error, even though I didn't have to for [the actual fix in 2.3](https://github.com/mixxxdj/mixxx/pull/3199/files)
```sh
/home/ronso/Downloads/mixxx_source/src/master/src/library/librarycontrol.cpp: In member function ‘void LibraryControl::slotGoToItem(double)’:
/home/ronso/Downloads/mixxx_source/src/master/src/library/librarycontrol.cpp:713:36: error: invalid use of incomplete type ‘class QWindow’
  713 |     if (focusWindow && (focusWindow->type() & (Qt::Dialog | Qt::Popup))) {
      |                                    ^~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdialog.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmessagebox.h:45,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMessageBox:1,
                 from /home/ronso/Downloads/mixxx_source/src/master/src/errordialoghandler.h:22,
                 from /home/ronso/Downloads/mixxx_source/src/master/src/util/debug.h:7,
                 from /home/ronso/Downloads/mixxx_source/src/master/src/preferences/configobject.h:13,
                 from /home/ronso/Downloads/mixxx_source/src/master/src/preferences/usersettings.h:7,
                 from /home/ronso/Downloads/mixxx_source/src/master/src/control/controlencoder.h:4,
                 from /home/ronso/Downloads/mixxx_source/src/master/src/library/librarycontrol.h:6,
                 from /home/ronso/Downloads/mixxx_source/src/master/src/library/librarycontrol.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h:54:7: note: forward declaration of ‘class QWindow’
   54 | class QWindow;
      |       ^~~~~~~
/home/ronso/Downloads/mixxx_source/src/master/src/library/librarycontrol.cpp:715:33: error: cannot convert ‘QWindow*’ to ‘QObject*’
  715 |         QApplication::sendEvent(focusWindow, &event);
      |                                 ^~~~~~~~~~~
      |                                 |
      |                                 QWindow*
```

**Comment by ronso0** [comment]
tests pass.
[Lib],GoToItem also works as desired.

now we have
` Merge branch '2.3' of github.com:mixxxdj/mixxx into HEAD`
instead of
`Merge remote-tracking branch 'upstream/2.3' into main`

For reference, it should have been:
```
git fetch mixxx
git checkout -b main mixxx/main
git pull mixxx 2.3
```
* fix conflicts
* test if it builds
```
ctest -j$(nproc) --output-on-failure
git push mixxx main
```
Lesson learned.

**Comment by uklotzde** [comment]
Well done, @ronso0 :clap::clap: Thank you for taking care, and welcome to the club!

I was afraid to lose any of your UI work when resolving the conflicts.

**Comment by ronso0** [comment]
Yeah, first time :tada: 

> I was afraid to lose any of your UI work when resolving the conflicts.

... and I got kinda nevous while pushing after I messed with the browsetablemodel.

**Comment by Holzhaus** [comment]
If in doubt, you can also push to your fork first, and open a regular PR.

**Pull request merged**
