### PR TITLE
Linux: Prefer SoundSourceFFmpeg for .m4a/.mp4 files

### PR DESCRIPTION
**Pull request by uklotzde**
TODO:
- [x] Add changelog entry

https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Switch.20from.20FAAD2.20to.20FFmpeg.20on.20Linux

Prefer SoundSourceFFmpeg over SoundSourceM4A on Linux.

### CODE REVIEW

**Comment by uklotzde** [comment]
Any objections?

**Review by daschuer — APPROVED** [review]
LGTM. Is there anything else to consider @Holzhaus

**Comment by uklotzde** [comment]
We should add changelog entry!

**Comment by uklotzde** [comment]
Please verify the changelog entry. We only build with FFmpeg on Linux, correct? So, no ALAC support on Windows apparently if Windows Media Foundations does not support it.

**Review by Holzhaus — APPROVED** [review]
LGTM.

This might shift cue/beatgrid offsets, right? I think we can merge this anyway, however I suggest to switch to a normalized position for all positions in the long term by calculating offsets based on the current decoder. I'll open a zulip thread.

**Comment by daschuer** [comment]
If we decide to issue this problem, we need to hold this back until we have saving of the current codec implemented?

**Comment by uklotzde** [comment]
No. I will neither implement implement this *codec saving* nor do I have an idea how to do it correctly.

**Comment by uklotzde** [comment]
- no database schema upgrades for 2.3
- switching only Ubuntu 20.04 to FFmpeg while still using FAAD2 for all other Linux distributions is even more inconsistent

**Comment by Holzhaus** [comment]
How do we continue here? Shall we merge?

**Comment by daschuer** [comment]
Do we know if and which offset is introduced?
If there is no offset fo the mayority of tracks we can merge. 

If there is snow one, I see these options:
* Add an static artificial offset, making faad2 the reference.
* Store the decoder type and version along with the track decoration that we have a chance to compensate that later.
* Run the beat detection again and calc the offset.
* Install a reference point detection, like "the highest peak in the first chunk" 
* Require the user to adjust the offset if there is any. 
Is there anything else where we can help him?

Do we know all shifting effects? I expect that encoding and decoding has one I am also afraid that it depends to the encoding and decoding parameters.




Is there a kind of non-broken reference loop where the decoded wave has zero offset?




If encoding is involved as well we can't do much

**Comment by daschuer** [comment]
I think the reference point detection is the way to go. This is close related to the truth and will work even if we exchange the track with a one with better quality.

So we need to hold this back until it is implemented. IMHO the implementation is straight forward, just calc the reference point when opening the track and compare it to are stored point. If there is a difference, we can warn the user in the fist version, with an overlay text in the waveform overview.

What do you think?

**Comment by uklotzde** [comment]
- We will not have such a reference point detection in the foreseeable future
- Ubuntu 20.04 has already been switched from FAAD2 to FFmpeg

**Comment by uklotzde** [comment]
I also still question that such a reference point detection is even feasible and worth the effort. Providing a manual offset correction feature that is applied to **all** track positions (cues, beats, ...) would already help alot.

**Comment by uklotzde** [comment]
If this doesn't get merged I will patch the RPMFusion version.

**Comment by daschuer** [comment]
> We will not have such a reference point detection in the foreseeable future

If we decide to work on it we will. Technical it is not more difficult than detecting silence and adding a new library column.

> Ubuntu 20.04 has already been switched from FAAD2 to FFmpeg

Did we have the knowledge of that this involves an offset? If that is really an issue, we should implement a solution ASAP, to avoid such issues in future.

Theoretical this can happen on every decoder upgrade that "fixes" an offset issue.

> If this doesn't get merged I will patch the RPMFusion version.

What is the reasoning behind it. Is there a Fedora version which can't support Faad2 like Ubuntu 20.4?

**Comment by uklotzde** [comment]
Traditionally we had identical priorities on each platform. In the past users experienced offsets only due to bug fixes in Mixxx, i.e. when upgrading the application.

Now users will experience offsets not only when upgrading Mixxx, but also when upgrading their OS or switching between different Linux distributions.* Is anyone aware of this?

*This still might occur with a version change of a decoder library. But that's out of our control.

**Comment by Holzhaus** [comment]
This is why we need [https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Normalized.20track.20positions.20in.20the.20Database], but this is not feasible for 2.3. I think we have 3 options now:
1. Always prefer FFmpeg on Linux
2. Always prefer FAAD2 on Linux (revert change for ubuntu 20.04)
3. Leave it as-is

I'm okay with 1 or 2 (if FAAD2 is not unusable on Ubuntu 20.04).

**Comment by daschuer** [comment]
First of all lets clarify if there is an offset. @uklotzde can you verify this? I can't because I am on Ubuntu Bionic. 

If it turns out that there is an offset, we should not silently "break" the annotations during a Mixxx Upgrade, If we can avoid this. 

If we have a solution for it, I very much prefer to retire FAAD2 and avoid the maintenance efforts. 

Looking for the first peak in the first frame will fail as a solution if we have only silence.
I think in this case we can fall back to the silence detector output. This value is already there. 

What do you think?

**Comment by daschuer** [comment]
> 2 Always prefer FAAD2 on Linux (revert change for ubuntu 20.04)

For this we need to ship our own libmp4. 

If we cant effort the time for a offset detection/compensation feature, this will give us the time to let one settle.

**Comment by daschuer** [comment]
But first I like to see an evidence that we have actually an offset issue.

**Comment by uklotzde** [comment]
> But first I like to see an evidence that we have actually an offset issue.

cover-test-itunes-12.3.0-aac.m4a
Debug [AnalyzerThread 0 #1] mixxx.source.FFmpeg: Opened stream for decoding { index 0 | id 1 | codec_type 1 | codec_id 86018 | channels 1 | channel_layout 4 | channel_layout (fixed) 4 | format 8 | sample_rate 44100 | bit_rate 96036 | frame_size 1024 | initial_padding 0 | trailing_padding 0 | seek_preroll 0 | start_time 2112 | duration 1328128 | nb_frames 1297 | time_base 1 / 44100 }

The start time of 2112 is not respected by FAAD2. Decoding with FFmpeg results in the same (= correct) offset as for the original cover-test.wav.

cover-test-itunes-12.7.0-aac.m4a
Opened stream for decoding { index 0 | id 1 | codec_type 1 | codec_id 86018 | channels 1 | channel_layout 4 | channel_layout (fixed) 4 | format 8 | sample_rate 44100 | bit_rate 96006 | frame_size 1024 | initial_padding 0 | trailing_padding 0 | seek_preroll 0 | start_time 0 | duration 1328128 | nb_frames 1297 | time_base 1 / 44100 }

This file with start_time = 0 has the same (= wrong) offset for both FAAD2 and FFmpeg compared to the original WAV file. FFmpeg cannot deduce the missing start_time property after iTunes 12.7 missed to add it.

**Comment by uklotzde** [comment]
Now the decoded signal of both files matches that of the original WAV file. Still a hack, but works as expected.

**Comment by uklotzde** [comment]
My memory was wrong. FAAD2 seems to ignore the start_time and decodes all files correctly, while FFmpeg stumbles upon the incomplete iTunes 12.7 encoding metadata.

With the workaround, there should now not be any differing offsets between FAAD2 and FFmpeg. But we can neither prove nor guarantee it.

**Comment by daschuer** [comment]
Cool, Thank you very much. That means we can merge it, right? 

@Holzhaus, are you able to test that as well? I can remember you have experience with a sample rate dependency. Does it also apply to m4a files?

**Comment by uklotzde** [comment]
Sorry for the confusion, much too late. My memory was prefectly correct, I mixed up the previous testing.

A re-test with FAAD2 after deleting all analysis data revealed that it does **not** account for the offset at all. The Intro marker is set at 0.06 instead of 0.01 as expected. The track duration is also ~48 ms ms too long, i.e. 30.11 sec instead of 30.06 sec.

FFmpeg now produces the correct result for M4A files that matches that of WAV, ALAC, WV, OGG OPUS, FLAC. But at the cost of an offset of 2112 sample frames = 48 ms compared to our FAAD2 decoder. The FAAD2 decoder also needs to account for this, but I will not update it.

The MP3 results vary among the different files as expected, both offset and track duration. That's a different story.

**Comment by uklotzde** [comment]
Note: When decoding our test files using SoundSourceFFmpeg both offset and duration match that of the reference files, i.e. no suffering from offset issues!!

**Comment by daschuer** [comment]
That's bad. This means after merging this the track annotations do not match anymore. 

It looks like that it also proves that just storing a static offset per encoder does not work as well. 

The only thing we can do is to "detect" the offset and correct it. This should be immune against all current and future issues. 

What do you think about my proposal to find the first peak in the firsts frame and fall back to the silence detection when the first frame is silence.

**Comment by uklotzde** [comment]
Unfortunately, we cannot compensate for the metadata encoding fault of iTunes 12.7. Otherwise, we would mess up the offset of AAC files encoded with FFmpeg/Lavf.

**Comment by uklotzde** [comment]
If you still believe that developing a universal offset detection is possible I wish you luck ;) I am convinced that it is impossible and doomed to fail. You cannot account for all possible encoder/decoder issues, which are a moving target.

**Comment by daschuer** [comment]
Can you add some insights?
Why is it impossible? At which point will a peak detection fail?

**Comment by uklotzde** [comment]
@daschuer Sorry, no time for thinking about it.

**Comment by daschuer** [comment]
Than just quickly share you thoughts that convinces you that it will fails.
I have no interest to do the bussy work and than seeing it not merged because of your concerns.

**Comment by uklotzde** [comment]
Storing positions according to this implicit origin will be incompatible with all other software. Not sure about the consequences for importing/exporting positional data.

**Comment by daschuer** [comment]
Luckily we have already a two possible reliable offset detection, that is not user editable: The AudibleSound cue. 

Proposal: 
* After track load silently verify if the AudibleSound cue is still correct. 
* If yes, fine.
* If not not print into the waveform over view "Track annotation shifted or invalid" 
* Provide a button to auto adjust it. 
* Provide a feature to Auto-Mass adjust it. 

Unfortunately the AudibleSound cue is not yet released, so I propose to shift all the work including this PR to 2.4 and ship libmp3 for our Ubuntu builds. 

What do you think?  

A alternative could be the track duration. Not I am afraid this is not too reliable. Is the duration changed due to the offset issues? 
@uklotzde can you confirm this?

**Comment by daschuer** [comment]
@uklotzde would it be feasible to open the mp4 container with ffmpeg and still use FAAD2 for the decoding? 

There was already a libfaad wrapper, removed here: 
https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/6a74b1272efda1d85deb9485ca03230293864ec1

I have no idea if this code is useful for us or if we better include libmp4 in our source tree.

**Comment by uklotzde** [comment]
I will not work on this.

**Comment by daschuer** [comment]
Cool, Thank you very much.

**Comment by uklotzde** [comment]
The current situation with the partially unsupported SoundSourceM4A/FAAD2 in 2.3 is bad. It will cause issues for some users but we cannot give general advice for all users.

**Comment by uklotzde** [comment]
@daschuer Instead of discussing potential future solutions please provide an actual solution.

**Comment by daschuer** [comment]
> I will not work on this.

Ups, I missread you comment, thinking you will look into this.

Once we have a conclusion, I can adopt the work. 

Unfortunately I think there is no way around postponing an actual solution into the next version. Because we need to rely on that the user has collected the audible region for the mayority of tracks.

**Comment by daschuer** [comment]
Plan:
* Revive Faad2 for Ubuntu focal via the ffmpeg stub code.
* Release 2.3 and collect audible region with the already merged code.
* For 2.4, verify the audible region and earn the user if it dies not match anymore.
* Merge this to master after the steps above have lended in master as well.

If we agree that this is a good plan, I can do it.
What do you think?

**Comment by daschuer** [comment]
I would really like to make progress here.
Did you consider my plan?

I also think we can keep this valid PR open.
It is just that we cannot merge it now.

**Pull request closed without merging**
