### PR TITLE
Open in file browser Fix 

### PR DESCRIPTION
**Pull request by daschuer**
This fixes https://bugs.launchpad.net/mixxx/+bug/1719175

A regression since 
https://github.com/mixxxdj/mixxx/pull/1215

It was a problem that getTrackLocation was turned to native separators, which breaks the logic in the Open In Browser feature.

### CODE REVIEW

**Comment by daschuer** [comment]
I have just tested on win10: The original issue is fixed. 
Anyone likes to have a look?

**Comment by uklotzde** [comment]
Even if I haven't tested it practically all the changes seem to make sense. Good idea to rename the ColumnCache enum constant for documentation purposes to prevent misunderstandings in the future.

**Comment by daschuer** [comment]
@uklotzde: thank you for looking into it. Can I merge?

**Comment by uklotzde** [comment]
@daschuer That was the intent of my comment ;) A positive vote from me. If no one else disagrees, yes.

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
