### PR TITLE
widgethelper: hack around crash when right clicking cues

### PR DESCRIPTION
**Pull request by Be-ing**
I do not know why QWidget::windowHandle sometimes returns nullptr,
but this should at least prevent Mixxx from crashing when that
happens.
https://bugs.launchpad.net/mixxx/+bug/1880446

### CODE REVIEW

**Review by daschuer — CHANGES_REQUESTED** [review]
> If this is a native widget, return the associated QWindow. Otherwise return null.

Qt uses this code as a workaround: 
https://github.com/qt/qtbase/blob/d975ad4ed728553b765c61f38c1e0df899187cf5/src/widgets/kernel/qapplication_p.h#L220

Do you have an Idea when what must happen to have the on or the other case?

**Comment by Be-ing** [comment]
> Do you have an Idea when what must happen to have the on or the other case?

No. I am unable to reproduce the crash.

**Comment by uklotzde** [comment]
https://doc.qt.io/qt-5/qwidget.html#windowHandle
> If this is a native widget, return the associated QWindow. Otherwise return null.

Then lets add a windowForWidget() to our helper. Don't know why Qt didn't provide this as a public function.

**Comment by Holzhaus** [comment]
> https://doc.qt.io/qt-5/qwidget.html#windowHandle
> 
> > If this is a native widget, return the associated QWindow. Otherwise return null.
> 
> Then lets add a windowForWidget() to our helper. Don't know why Qt didn't provide this as a public function.

Should we merge this now anyway until someone finds the time to take care of this?

**Comment by daschuer** [comment]
Since a "propper" fix are only a few lines of code, let's wait until one finds time.

**Comment by uklotzde** [comment]
Adopting the Qt solution is a low hanging fruit.

**Comment by uklotzde** [comment]
https://github.com/Be-ing/mixxx/pull/47

**Comment by uklotzde** [comment]
@Be-ing Ping https://github.com/Be-ing/mixxx/pull/47

**Pull request merged**
