### PR TITLE
LateNight :: vectorize remaining graphics

### PR DESCRIPTION
**Pull request by ronso0**
still working on it, don't merge

### CODE REVIEW

**Comment by ronso0** [comment]
@Be-ing @daschuer 
Do you have any idea why there's no clipping indicator for Mic/Aux?
Are those level meters special in any way?

**Comment by daschuer** [comment]
IMHO there should be a clipping indicator. It is currently missing somehow.

**Comment by ronso0** [comment]
> IMHO there should be a clipping indicator. It is currently missing somehow.

Okay, I'll add it.

**Comment by ronso0** [comment]
Looking good now @200%, still fine @100%.
Please test on a real HD screen.

**Comment by ronso0** [comment]
> However, it looks like the spinboxes are not scaling

They still had min-/max-width in style.qss, changing it to width/height and even removing it doesn't help (master 2.2). So now neither the box nor the buttons have a size dfined anywhere, parent widgets provide enough space. IDK what's the matter..

**Comment by ronso0** [comment]
Stupid me,.. I was testing the above changes in the wrong skin folder.
It's working now: (don't know why the right-hand border is dropped when scaling up, but that's a tiny issue)
latenight-beatbox-scaling-fix


If you want to fix it in #1518, the WBeatSpinbox section in style.qss should look like this:
```
WBeatSpinBox {
  /* make it 2px smaller in each dimension,
    border is added for final size */
  width: 55px;
  height: 22px;
  border: 1px solid #666;
  /* size of spinbox: 54x22px
  incl. up/down button: 70x22px */
  border-radius: 2px;
  color: #cfb32c;
  background-color: #0f0f0f;
  selection-color: #0f0f0f;
  selection-background-color: #d2d2d2;
  font-size: 13px/13px;
  padding: 0px;
  padding: 1px 2px 1px 1px;
  margin: 0px -1px 2px 0px;
}
  WBeatSpinBox:hover {
    border-color: #888;
  }
  WBeatSpinBox:focus {
    border-color: #d2d2d2;
    color: #cfb32c;
  }

  WBeatSpinBox::up-button, WBeatSpinBox::down-button {
    subcontrol-origin: padding;
    position: relative;
    /* as with spinbox: border is added to size.
      define it with same width as hover border, otherwise size jumps */
    width: 18px;
    height: 12px;
    margin: 0px 0px 0px 0px;
    padding: 0px;
    border: 0px;
    }

  WBeatSpinBox::up-button {
    subcontrol-position: top right;
    margin-top: -1px;
    image: url(skin:/buttons/btn_beatbox_double.svg) no-repeat;
    }
    WBeatSpinBox::up-button:pressed {
      image: url(skin:/buttons/btn_beatbox_double_pressed.svg) no-repeat;
    }
  WBeatSpinBox::down-button {
    subcontrol-position: bottom right;
    margin-bottom: -1px;
    image: url(skin:/buttons/btn_beatbox_halve.svg) no-repeat;
    }
    WBeatSpinBox::down-button:pressed {
      image: url(skin:/buttons/btn_beatbox_halve_pressed.svg) no-repeat;
    }
```

**Comment by nopeppermint** [comment]
100% looks good (tested on Linux), 50% as well but the library is not scaling..

**Comment by ronso0** [comment]
> but the library is not scaling

To properly test skin scaling I also had to maually set the font size to double the regular value (xfce4), or use OS fontscaling (Ubuntu, Tweak Ubuntu app). Because library components rely on the OS font size to scale (search box, tree view, library buttons etc.)

**Comment by ronso0** [comment]
@Be-ing 
> If you want to fix it in #1518, the WBeatSpinbox section in style.qss should look like this:

Sorry, somehow I was under the impression this was already merged..
Will add it here, of course.

**Comment by daschuer** [comment]
Now the scaling works. Not perfect but OK. LGTM 
@Be-ing:  Can we merge this?

**Comment by Be-ing** [comment]
The space between the spinbox arrows looks odd, but I'm not sure if we can do better while using Qt4:
image

**Pull request merged**
