### PR TITLE
Traktor Kontrol S2 MK2: Fixes issue with jogs and FX knobs not working

### PR DESCRIPTION
**Pull request by z411**
* Fixed a major issue where the knobs and FX knobs in this mapping weren't working.
* Can now change beatjump size with shift+left encoder.
* Added soft takeover.

I feel that a few more things can be improved, particularly loop encoders.

Also if it's not an issue, as I'm the original author of the mapping I updated my name and e-mail in the header [proof](https://mixxx.discourse.group/t/ni-traktor-s2-mk2-hid-mapping/16856/34)

### CODE REVIEW

**Comment by Be-ing** [comment]
Please rebase on the 2.3 branch.

**Comment by z411** [comment]
> I don't understand the changes to the left encoder. You could already change beatjump size by pressing and turning the encoder, so why did you remove the key change feature to move beatjump size adjustment to shift + turn?

As I tested it was too easy to accidentally unpress the encoder and do an actual beatjump while trying to change its size, and it sounds really bad to happen in a live situation. But I can revert that change if you'd like.

After that I'll squash the changes and re-submit from the 2.3 branch.

**Comment by Be-ing** [comment]
How about cherry-picking f717c2d to another branch and opening another PR for that, then rebasing this on 2.3 without f717c2d (use `git rebase -i upstream/2.3` and delete the line for f717c2d)? Post the version with the changed behavior for the left encoder to the forum and ask other users with this controller what they think about the change. I did not have that problem with accidentally beatjumping but I didn't get that much time to play with the controller.

**Comment by z411** [comment]
Done.

**Comment by Be-ing** [comment]
Thank you!

**Comment by Holzhaus** [comment]
This is just a bugfix and doesn't change anything from the user's perpective, right? If not, please update the documentation: https://manual.mixxx.org/2.3/en/hardware/controllers/native_instruments_traktor_kontrol_s2_mk2.html

**Comment by Be-ing** [comment]
Yes, this is just a bug fix. The behavior change was not merged.

**Pull request merged**
