### PR TITLE
CMake: Set cmake_minimum_required version to 3.13.0

### PR DESCRIPTION
**Pull request by Holzhaus**
We're currently using the target_link_options() command which has been
introduced in CMake 3.13:
https://cmake.org/cmake/help/v3.13/release/3.13.html?highlight=target_link_options#commands

### CODE REVIEW

**Comment by Holzhaus** [comment]
Bug report: https://mixxx.zulipchat.com/#narrow/stream/109695-_support/topic/Compiling.20mixxx.20on.20windows/near/183947588

**Comment by daschuer** [comment]
Strange, how did the Xenial build succede before? Now they are failing with insufficient version.

We can update cmake from here:
https://blog.kitware.com/ubuntu-cmake-repository-now-available/

**Comment by daschuer** [comment]
Cmake 3.12.4 is installed on Travis.

**Comment by Holzhaus** [comment]
I think the `target_link_options` command is only used with MSVC. That's why we didn't notice it.

**Comment by daschuer** [comment]
OK, so we either need to update cmake on Travis or make the minimum cmake version target depending.

**Comment by Holzhaus** [comment]
I updated the CMake version on Ubuntu.

**Pull request merged**
