### PR TITLE
LateNight :: prevent overview from squeezing spinnies

### PR DESCRIPTION
**Pull request by ronso0**
minimum width of deck overview was to high, spinnies were eggs at minimal window size

### CODE REVIEW

**Comment by daschuer** [comment]
The spinnies are still eggs here.

**Comment by daschuer** [comment]
bildschirmfoto vom 2019-02-03 12 45 26

**Comment by ronso0** [comment]
hm.. 
how wide is the overview? how big is your screen?

**Comment by daschuer** [comment]
My display is 1366 x 786. The Spinnies are always eggs, even if I resize Mixxx to a width of 2000.

**Comment by ronso0** [comment]
okay, it was only the spinny that would stretch. I fixed it by setting MaxSize when loading the Singleton which is now only used for the small spinnies, big spinny is loaded regularly from template with different MaxSize.

**Comment by daschuer** [comment]
The big spinnies are still eggs when the skin preferences are shown. It looks odd in my eyes, but this might be acceptable. Unfortunately the pointer inside the spinny is resized correctly, but toes not fit to the egg outline ...

**Comment by ronso0** [comment]
yes, with skin settings open there are still squeezd GUI parts in all skins. But better they're squeezed than cropped or stacked.

**Comment by daschuer** [comment]
OK, at least it is an improvement. A merge conflict exists,

**Comment by ronso0** [comment]
Done, ready to merge.

**Comment by uklotzde** [comment]
LGTM. Thank you!

**Pull request merged**
