### PR TITLE
CI: Use custom CMake version on macOS/Ubuntu 18.04 only

### PR DESCRIPTION
**Pull request by Holzhaus**
See https://github.com/mixxxdj/mixxx/pull/3981#discussion_r650383968.

### CODE REVIEW

**Comment by Holzhaus** [comment]
@daschuer IIUC the Ubuntu 20.04 build should fail with this PR if it's actuallly a bug in CMake 3.16.3, right?

**Review by uklotzde — APPROVED** [review]
LGTM

Upgrade actions-setup-cmake from v1.4 to v1.9 while we are at it?

**Comment by uklotzde** [comment]
I have closed #3984, because 20.04 is still affected with its old CMake version.

**Comment by uklotzde** [comment]
I guess the bug is only triggered during packaging, because the build options are not defined explicitly as they are supposed to be. The workaround wouldn't be necessary if we wouldn't need to package several Ubuntu versions in parallel with the same build script by using some implicit dependency magic.

**Comment by uklotzde** [comment]
LGTM

**Pull request merged**
