### PR TITLE
Fixes CrateFeature to behave as PlaylistFeature

### PR DESCRIPTION
**Pull request by tmtnslt**
Fixes https://bugs.launchpad.net/mixxx/+bug/1414246 based on https://github.com/mixxxdj/mixxx/pull/585 adapted for CrateFeature.

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for this commit. I can confirm, that the crates tree is working now like the playlist tree. 

If you like, we can merge this as a fist step. 

Please sign;
https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ
do give us the permission. 

Comment here when done. 

However, the bug is IMHO not 100 % solved. 
If you now move all tracks from a crate to an empty crate, you can still confused which crate is displayed, since the highlighting moved to root crate item. 

Do you have fun to solve this as well?  
Thank you.

**Comment by richterskala** [comment]
I signed it.

I agree with you. The problem arises when you change a crate while you have selected a crate, because the cratefeature currently rebuilds the crate list on every change of crates (the same btw is valid for playlists).

If you send a new track to the crate from somewhere else (say the Library), the selection will perfectly stay where it was.

An easy fix is to select the new crate/playlist you have changed (and this time do it right ;-) ).
I wouldn't like this, because it makes building up crates annoying. The better solution in my eyes is to keep the selection where it was.

However, there doesn't seem to be a way to find out, which item in the sidebar was or is currently selected, or is there?

**Comment by richterskala** [comment]
Should be fixed by only updating the childModel item when the content of a crate/playlist is changed instead of recreating the whole tree (which still happens after deleting etc. a crate/playlist)

**Comment by daschuer** [comment]
Great, you have already found a solution. 
LGTM 
Thank you for your work!

While testing it, I am missing a hover follow feature for playlists, controlled by a timer. This is required to drop a track on a desired position inside the play-list. But nevermid that is a separate bug. 
I have just filed it: https://bugs.launchpad.net/mixxx/+bug/1505404

**Pull request merged**
