### PR TITLE
Color code

### PR DESCRIPTION
**Pull request by ghost**
Hey, I want to add a column to the table that allows user to color code tracks.
Qt is not a platform i work on usually, and this seems a lot confusing ,  but I am really interested to learn it.

This is an amateur start and does not (yet) solve my purpose for obvious reasons.
Looking forward to helps that'll help me fix this.

This is not safe to test. ( yet)

Thanks 
-Karan,

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for the PR.
This does not merge cleanly with master.
Please but some more details to you commit messages.

**Comment by daschuer** [comment]
How do you plan to set the color? 
What are your next steps? Where do you need help?

**Comment by karansanwal** [comment]
Hey, Seems like i should be the one thanking you for helping me out here.
Some of the older commits got resent by mistake, I'll remove them from the PR.

As far as what i have thought, my idea was to add a column with name 'Color' in the base Sql table that will contain an integer (a number) , and while retrieving the data from the color column , I thought of adding a qlabel ( or a qcolorcombo box) to the front-end table, that changes its background color according to the the integer(code) retrieved from the SQL table.

I think ( but i am not sure) I have added the column and set it visible, but i am unsure on how and where to carry out the changes in frontend.

Thanks for your time.
Will try my best to get better with my PR once i get the hang of qt and mixxx.

**Comment by rimorob** [comment]
@karansanwal, any further luck with this item?  I was thinking, too, that it might be more promising to mark the song itself rather than create a separate column, like here:
image

**Comment by karansanwal** [comment]
Totally forgot about this.
@rimorob , the idea was discussed , but turns out this new feature should be optional so it could only help the people that require it. So it was decided that a color tag column that could be hidden would be the right solution to the problem.

**Comment by rimorob** [comment]
But coloring of text could be similarly disabled, e.g. when selecting the color (such as ‘none/default’).  There doesn’t seem to be anything that an extra column can do that right-click-driven color selection can’t.

B

**Comment by Be-ing** [comment]
How would this affect https://bugs.launchpad.net/mixxx/+bug/872006 ?

**Comment by ferranpujolcamins** [comment]
MusicBee has a highlighting feature. You can specify a criterion and choose
a color for tracks that match it. Maybe we could aim for a general approach
like in MusicBee. In Mixxx it would simply mean assign a color to a search
query.

The only drawback I see is the added complexity for the user, but it would
really be a powerful feature.
El dia 17/07/2015 2:18, "Be-ing" <notifications@github.com> va escriure:

**Comment by rimorob** [comment]
I don't know what MusicBee does, but the intent of coloring in the image above is to help group types of songs together (I suppose, similar to harmonic mixing but manually).  Maybe the first right click brings up a menu with an option to set a color, that has a submenu of 'harmonic match', 'manual', 'none'?  Something like that?

**Comment by ferranpujolcamins** [comment]
In the general approach I proposed, you could configure something like:

comment has "floor filler": red

or

is_in_crate "slow songs": green

So you would specify criteria and the coloring would be automatically
applied. I was just brainstorming, but it is a more flexible approach that
fits both your use case and the key coloring one. And in fact many more :)


2015-07-17 3:42 GMT+02:00 rimorob <notifications@github.com>:

**Comment by ferranpujolcamins** [comment]
Here you can see what I mean:

[image: Imatge inserida 1]

2015-07-17 10:42 GMT+02:00 Ferran Pujol Camins <ferranpujolcamins@gmail.com>
:

**Comment by rimorob** [comment]
Somehow the image didn't come through but the verbal description sounds very nice.  How do we go from use cases to implementation?

**Comment by uklotzde** [comment]
User has deleted his GitHub account and the code is not worth keeping.

**Pull request closed without merging**
