### PR TITLE
Fix SkinContext parent/child relationships and overall design

### PR DESCRIPTION
**Pull request by uklotzde**
A successor of #2433 trying to fix the ~~uncommon (and possibly broken)~~ unsound `SkinContext` design.

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you very much. I am happy that you have found sometime for this itching spot. 
After a brief look, it LGTM. I hope I will find time for a manual test soon.

**Comment by uklotzde** [comment]
I had to replace the internal QVector with std::vector, because the required move operations are only supported since Qt 5.6. Otherwise this PR could have been smaller.

**Comment by uklotzde** [comment]
Ping

**Comment by daschuer** [comment]
Tested successful without any issues.

**Pull request merged**
