### PR TITLE
Added trans effect.

### PR DESCRIPTION
**Pull request by quirxmode**
This. Is there any contributor's agreement?

### CODE REVIEW

**Comment by quirxmode** [comment]
What kind of tests are expected for this effect?

**Comment by Swiftb0y** [comment]
> Is there any contributor's agreement?

You already signed it in the bugfix PR, no need to sign it again.

> What kind of tests are expected for this effect?

We don't have any tests for effects at the moment so we won't require it now...

Please take a look at the [Coding Guidelines](https://github.com/mixxxdj/mixxx/wiki/Coding%20Guidelines) and set up pre-commit.

**Comment by Swiftb0y** [comment]
I'm a bit confused by your effect. It seems very similar to the Tremolo effect we already have just with different parameters to shape the waveform which modulates the level. Can you elaborate a bit how what purpose the transeffect fulfills that is not already fulfilled by the tremolo effect?

**Comment by quirxmode** [comment]
> I'm a bit confused by your effect. It seems very similar to the Tremolo effect we already have just with different parameters to shape the waveform which modulates the level. Can you elaborate a bit how what purpose the transeffect fulfills that is not already fulfilled by the tremolo effect?

Hm it seems to do something similar indeed. To be honest, I did not find it because it did not have the name I expected.
Some remarks though - imho with the "Trans(former)" effect, people expect quite fast (~10/s), high contrast modulation. The tremolo cannot easily be set to that speed because the knob gets fiddly for high Rate. This can be worked around by enabling Triplets, which seems to multiply things by three, so the faster rates are still in a comfortably smooth area of the Rate knob. But then you have triplets of course and they have even more coarse steps in their rate.

The steps on the proposed Trans effect are smoother, probably because sync uses four beats.

Tremolo can do the same thing but it's a lot of fiddling imho. And you might not get exactly the rate you want. This can probably be fixed by adapting the tremolo effect. On a side note, people coming from other software/hardware might be looking for a Trans effect in the list...

**Comment by Swiftb0y** [comment]
I guess we're equally confused about the name. I tried to look up any software with a "transformer" effect and I wasn't able to find any. Could you point me to some example? 
I only understood what the effect was doing by looking at the code and testing it out myself.
IMO the term "Tremolo" is better because its the proper musical term for this kind of effect. See the wikipedia definition:
> A second type of tremolo is a variation in amplitude:
> * as produced on organs by tremulants
> * using electronic effects in guitar amplifiers and effects pedals which rapidly turn the volume of a signal up and down, creating a "shuddering" effect
> * an imitation of the same by strings in which pulsations are taken in the same bow direction
> * a vocal technique involving a wide or slow vibrato, not to be confused with the trillo or "Monteverdi trill"


> The tremolo cannot easily be set to that speed because the knob gets fiddly for high Rate.

For rates this high, does it really make a difference whether its modulating at 9Hz or 10Hz?

> The steps on the proposed Trans effect are smoother, probably because sync uses four beats.

I struggle to understand what you mean with "steps being smoother". Is the waveform of the tremolo effect problematic (you can lerp between a sine an square wave)? what does the sync have to do with this?

> On a side note, people coming from other software/hardware might be looking for a Trans effect in the list...

I can understand that, we can discuss renaming the tremolo effect to something like "tremolo/transformer".

**Comment by quirxmode** [comment]
The Trans effect is available on pretty much many popular modern digital DJ mixers, e.g. the  DJM-V10(-LF), DJM-TOUR1,  DJM-900NXS2, DJM-750MK2, it's in software like Rekordbox and VirtualDJ. The name seems to originate from the transformer scratch created by Jazzy Jeff. Also most mixers offer timings based on four beats, such as 2, 1, 3/4, 1/2, 1/4, 1/8, 1/16.
Sorry I'm a bit slow on this, my schedule is quite tight during the week.

**Comment by Swiftb0y** [comment]
> Also most mixers offer timings based on four beats, such as 2, 1, 3/4, 1/2, 1/4, 1/8, 1/16.

The tremolo effect already does that when quantized, it might just not be showing the actual interval its currently on in the UI.

> Sorry I'm a bit slow on this, my schedule is quite tight during the week.

Thats fine. I'd appreciate if you answer my previous questions if you find some time. Thanks.

**Comment by daschuer** [comment]
I have just found "Pad Trans" effect:
https://www.youtube.com/watch?v=OXbXgx7C-EA 

While I think that there is no room for another Tremolo effect with a different name, I can Imagine to have such fail save ready to use effect as addition.

Our current Tremolo is too complicated to just use it without preparation late at night. 
Do you see a way to turn this PR into that direction?

**Comment by Holzhaus** [comment]
Didn't test or take a closer look yet. Is this effect comparable to Traktor's "Gater" effect? I had problems to find the right settings to replicate it with our Tremolo effect.

**Comment by Be-ing** [comment]
IIRC Traktor's Gater effect has some magic combining multiple effects into one on a single parameter knob. I'm not sure it's something we should imitate. See also discussion on https://github.com/Be-ing/mixxx/pull/41

**Comment by quirxmode** [comment]
Not everything needs to be a built-in effect, especially if there is some overlap in the featureset with existing filters. That said, how can one write an "external" filter? There is no "Load" button in the UI, or i did not find it. If it's not yet done, it seems to me to be quite easy to implement.

**Comment by daschuer** [comment]
The external filters are using the LV2 interface. 

But since you have open this PR, it is a good evidence that there is a need for improvement of our internal effects. 
Can you tell use more about your  personal use case?

**Comment by quirxmode** [comment]
I'll have to read up on the LV2 interface and how to use it with Mixxx.

Imho it should be easy to use whatever effects you want, even if it is identical to another, built-in effect that is maybe just parameterized differently. So if you could just load whatever effects you like imho that would make for a great user experience. Maybe this is already possible with LV2, it should maybe be more obvious in the UI:
- How would you load them?
- Where do you have to put them to be found? (UX-wise, this is already worse than the above)
- Where do you find them? There should be a page on the Mixxx site with a list of community-provided plugins. I imagine not every LV2 plugin is meant for live DJing, and users shouldn't have to find out which ones are suitable.
- Then, make it clear that new filters should be written as plugins. These can be put into a separate repo to not taint the code quality of the main repository while making it possible to add new plugins relatively easily. I imagine it could also be possible to write type-parameterized tests that get instantiated with every plugin and just sweep through the parameters, checking that nothing crashes, just as basic quality control. Whether things sound good or not is not Mixxx' problem then, they are community-provided plugins. Play around until you find one you like. Eventually, good plugins might be moved to built-in.

Also, I am using Mixxx on Linux and under "Discovered LV2 Plugins", they are all greyed out with "This plugin has features which are not yet supported." 

Imho, the most obvious workflow for users is "Download, press 'Load', Done."

On a side note, I'd really like to have pad effects. Many controllers have dedicated buttons for these now. Combined with loadable plugins and a download page for community provided plugins this should be a powerful feature and easy enough to implement. It's basically just pre-defining settings for a plugin and exposing that towards the controller mapping API. I have not looked into that part of the code yet, so maybe I am imagining things to be overly simple, however most of the work is probably writing the UI, saving settings and updating controller mappings.

**Comment by Be-ing** [comment]
> maybe just parameterized differently

This is implemented in #2618.

**Comment by Be-ing** [comment]
> Imho, the most obvious workflow for users is "Download, press 'Load', Done."

That is why we don't want to rely on external effects plugins for core features.

**Comment by quirxmode** [comment]
#2618 sounds great! With that, pad effects should just be a matter of adapting the controller mappings, i hope.

**Comment by daschuer** [comment]
Can you tell us more about your use case for this trans effect itself? When you you use it, which parameter are tweaked which are left at default. What sound sou you like to acheve?

**Comment by quirxmode** [comment]
> Can you tell us more about your use case for this trans effect itself? When you you use it, which parameter are tweaked which are left at default. What sound sou you like to acheve?

Well the defaults coincide with what I like to use ;) But for an example, watch the first ~45 seconds of this video: https://www.youtube.com/watch?v=XwX7XuLZpkI
The main parameter is the Period. The other parameters are more to adapt to personal preferences, with exception of Send, which is there because apparently every filter has it.

**Comment by quirxmode** [comment]
I see that this is probably not the right way to add a new effect, therefore closing for now.

**Pull request closed without merging**
