### PR TITLE
Tango :: a few tweaks

### PR DESCRIPTION
**Pull request by ronso0**
- [x] tweaked headMix scale as suggested by @daschuer 
- [x] EQ kill buttons are at the outer side of the EQ knobs
- [x] finally a EQ kill indicator that looks good with and without EQ kill buttons
- [x] simplified deck VU meter templates and graphics
- [x] improve clipping indicator
- [x] apply key info option to mini decks
- [x] use individul deck colors only for artits & title. grey for BPM, key, position, duration
- [x] more contrast for spinny indicators/ghosts on whiteish covers

screenshots coming soon...

Nice-to-have, triggered by the general skin discussion in #2081 :
- [x] change the default skin configuration to reflect the original (controller) use case more

### CODE REVIEW

**Comment by ronso0** [comment]
tango-tweaks

**Comment by ronso0** [comment]
[WIP] again because I'd like to decouple hotcues and intro cues.
For the controller use case users probably have hotcues on the controller (hidden in skin) but may need intro cues. This is a bit tricky to realize...

**Comment by ronso0** [comment]
..ready to test anyway.

**Comment by ronso0** [comment]
> [WIP] again because I'd like to decouple hotcues and intro cues.

current skin system makes it super hard, I'll leave it as is now.

Ready to test & merge

**Comment by daschuer** [comment]
No itches found. LGTM, Thank you.

**Pull request merged**
