### PR TITLE
fix(controllers): Numark N4 inverted pitch slider

### LINKED ISSUE #10813: Numark N4 mapping: Pitch/Rate fader inverted
Reported by: **[leontheoriginal](https://launchpad.net/~leontheoriginal)**
Date: 2022-08-16T19:39:01Z
Status: New
Importance: Low
Launchpad Issue: [lp1986712](https://bugs.launchpad.net/bugs/1986712)

---

Playing around with the Numark N4 controller (with Mixxx 2.3.3), I found that the pitch fader is inverted. So when moving the hardware slider down towards "+", the software equivalent moves up towards "-". ("Down increases speed" is enabled in settings.)
Fixing that seems to be easy by changing the "invert" value to "true" in the "this.bpmSlider" property.

### PR DESCRIPTION
**Pull request by Swiftb0y**
fixes #10813 
rebased #10918 on 2.3 and fixed pre-commit

Thank you @LeonTheOriginal for raising the issue.

### CODE REVIEW

**Comment by daschuer** [comment]
Do you have access to the hardware to test the fix?

**Comment by Swiftb0y** [comment]
Not anymore no, but I'm the author of the original mapping. Also the fix seems to make sense since all of the numark hardware I encountered so far has inverted tempo sliders. I trust the original author of the fix to have properly tested their changes.

**Comment by Swiftb0y** [comment]
@LeonTheOriginal Can you confirm this PR still fixes your issue?

**Comment by daschuer** [comment]
This basically reverts:
https://github.com/mixxxdj/mixxx/commit/f397adcc7351492314234135ff9b307b0c2cf4f3

We have the same in these Numark mappings: 
https://github.com/mixxxdj/mixxx/blob/8affbbb2c5e429b9aa8e6ea7410b65c8a50e46b1/res/controllers/Numark-Mixtrack-Pro-FX-scripts.js#L273
https://github.com/mixxxdj/mixxx/blob/main/res/controllers/Numark-Mixtrack-Platinum-scripts.js#L596
https://github.com/mixxxdj/mixxx/blob/main/res/controllers/Numark_DJ2GO2_Touch_scripts.js#L98
https://github.com/mixxxdj/mixxx/blob/main/res/controllers/Numark%20MIXTRACK.midi.xml#L284

So I guess it is correct.

**Comment by Swiftb0y** [comment]
Thank you for merging.

**Pull request merged**
