### PR TITLE
Execute tests in binary dir

### PR DESCRIPTION
**Pull request by xeruf**
Prevents the creation of the test files, which were accidentally committed in https://github.com/mixxxdj/mixxx/commit/0cd2aec17725a972014dcb4bc3f86e6d946ec270, in the project root. Instead use the binary dir. 

See https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Running.20tests.20with.20ctest.20creates.20untracked.20files/near/203089624

### CODE REVIEW

**Comment by xerus2000** [comment]
I am currently testing whether we can get rid of manually specifying the working directory completely.

**Comment by xerus2000** [comment]
Yep, works. We can just rely on defaults :)

**Comment by xerus2000** [comment]
Would be great if we could merge this soon, before these extraneous files are merged into everything.
Also, should I maybe point it to one of the stable branches (2.3) to also have it there?

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you!

**Comment by uklotzde** [comment]
AppVeyor Windows builds on master seem to be failing since this PR has been merged!?

**Comment by uklotzde** [comment]
This needs to be fixed urgently!

**Comment by xerus2000** [comment]
Oof, this is weird. Why does it work on Linux?

**Pull request merged**
