### PR TITLE
LateNight min height decrease

### PR DESCRIPTION
**Pull request by ferranlala**
Based on https://github.com/mixxxdj/mixxx/pull/913 .

Reduces the minimum height of LateNight from 700 to 670 px.
Makes little adjustments to the skin to make it usable on minimum height.

### CODE REVIEW

**Comment by ferranpujolcamins** [comment]
DO NOT MERGE. 

Preview deck is still not usable with 4deck mode.

**Comment by ywwg** [comment]
great thanks for working on this!  As always, screenshots when it's in a state you're happy with :)

Also if you have any ideas for minor tweaks that will help people not call it "like something from the 90s" I'd appreciate ideas :).  I wonder if it's too two-dimensional and if a small amount of depth to the knobs and box edges would help.

**Comment by ferranpujolcamins** [comment]
Oh, I actually made the screenshots but forgot to upload them. I'll do later.

The preview deck issue is still pending. Any idea? The best solution I've come up so far is to place it along the coverart inside a WidgetStack when the skin is small (via a SizeAwareStack).

About the general skin looks (personal opinion):
-I don't really like the stripped backgrounds. I prefer how LateNight looked without them.
-I think the knobs need a redesign. Make them ring friendly: https://github.com/mixxxdj/mixxx/pull/645.
-The faders could also benefit from a new appearance.
It's a great skin though :)

**Comment by ywwg** [comment]
The problem with using the left part of the library is the library can get very small on small screen with 4 decks.  But if you can find a way to make it fit that seems fine to me.

That's weird, I remember copying the stripes from the original latenight skin when I was redoing it.  But anyway, I wouldn't mind getting rid of them.  Definitely agree about redoing the knobs and sliders, the sliders especially take up a lot of space because they are so wide.  An integrated slider-and-VU-meter might be nice.

I am still partial to the gray-and-yellow color scheme, but I'm open to looking at mockups for proposed changes :).

**Comment by Be-ing** [comment]
This does solve the height issue for me. Thanks :)

**Comment by Be-ing** [comment]
>-I don't really like the stripped backgrounds. I prefer how LateNight looked without them.
I'm not a big fan of those either.

>-I think the knobs need a redesign. Make them ring friendly: #645.


-The faders could also benefit from a new appearance.
It's a great skin though :)

>  Definitely agree about redoing the knobs and sliders, the sliders especially take up a lot of space because they are so wide. An integrated slider-and-VU-meter might be nice.

Maybe. I'm concerned it could get difficult to tweak levels if the top of the level meter happens to coincide with where the slider is. The meters are quite narrow, so I don't think combining them would be that beneficial.

**Comment by ferranpujolcamins** [comment]
Before:
before

After:
after

**Comment by ferranpujolcamins** [comment]
Some thoughts for a future new PR:

-If we shrink the tempo faders and refactor the crossfader we could:
    *Supress the space between the transport controls and the waveform overview
    *Supress the vinyl status light bar and put a new indicator along the vinyl control buttons.
-Make buttons a little bit thiner

**Comment by Be-ing** [comment]
I agree that the pitch faders on screen probably don't need to be so tall. If long pitch faders are important for a user, they are likely using a controller or turntable with long pitch faders anyway. Not wasting the vertical space between the waveforms and transport controls would be good. I think the section above the decks could be shrunk too.

**Comment by ferranpujolcamins** [comment]
Also, my preference is to have the quick effect knob below the eq knobs. I don't know if this would fit though.

**Comment by Be-ing** [comment]
I think moving the quick effect knob will be required to shrink the space above decks. Below the EQ knobs could work. There will need to be a label like the deck gain knob to clearly differentiate it from the EQ knobs. This will make the mixer quite tall, but if the decks take less vertical space, it might be possible to bump the zoomed in waveforms up above the decks.

**Comment by ferranpujolcamins** [comment]
Maybe the crossfader could be moved below the main meters. Some mixers had this layout:
http://media.musiciansfriend.com/is/image/MMGS7/PMC-CX-Carl-Cox-DJ-Mixer/633213000000000-00-500x500.jpg

**Comment by Be-ing** [comment]
Eh. I think a lot of DJs don't like that layout much. I feel it's kinda odd.

**Comment by ferranpujolcamins** [comment]
Then to make room for the quick effect knob we could shrink the mixer controls. But since we have a CO to show/hide the crossfader, if the crossfader is hidden then display bigger controls to take advantage of the extra space.

**Comment by ywwg** [comment]
I'd prefer not to do any major reworking of the layout right now.

where did the UI  toggles go? vinyl / eq /mixer etc

**Comment by ywwg** [comment]
> Maybe the crossfader could be moved below the main meters.

definitely do not like

**Comment by ferranpujolcamins** [comment]
> I'd prefer not to do any major reworking of the layout right now.
> 
> where did the UI toggles go? vinyl / eq /mixer etc

This branch is based on https://github.com/mixxxdj/mixxx/pull/913#issuecomment-209040434

**Comment by ferranpujolcamins** [comment]
@ronso0 Do you think after your LatNight work  this branch can be closed?

**Comment by ronso0** [comment]
commenting [here](https://github.com/mixxxdj/mixxx/pull/913#issuecomment-354615331)

**Comment by ferranpujolcamins** [comment]
Superseded by #1357

**Pull request closed without merging**
