### PR TITLE
GitHub CI: Don't abort clazy build on errors

### PR DESCRIPTION
**Pull request by uklotzde**
This change allows developers to review and fix all errors instead of only the first few.

Tested on the currently broken main clazy build that aborts after 20 errors.

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for trying to fix the issue. 

How is this intended to work? ferror-limit=0 is a clang parameter which is executed per cpp file. 
The default limit is 20, which is IMHO a reasonable value to hide useless follow up warnings or errors for a missing } or something that affects the whole file. 

I think we need to disable stopping after the first erroring clazy call instead. This is probably a CMake parameter, I do not know.

**Review by daschuer — CHANGES_REQUESTED** [review]
is it WARNINGS_FATAL=ON?

**Comment by Holzhaus** [comment]
> is it WARNINGS_FATAL=ON?

Yes, but if we disable it, then the job won't fail at all, even if there are errors.

**Comment by Holzhaus** [comment]
Maybe `cmake --build . -- --keep-going` would work?

**Comment by daschuer** [comment]
```
cmake --build . -- --keep-going
```
does the trick. Is this an issue that it is a passed through make flag?

**Comment by Holzhaus** [comment]
> ```
> cmake --build . -- --keep-going
> ```
> 
> does the trick. Is this an issue that it is a passed through make flag?

I don't think so, it's a CI build so we can hardcode stuff.

**Comment by daschuer** [comment]
Now it fails with: 
```
 Error: Process completed with exit code 2.
```

**Review by daschuer — APPROVED** [review]
LGTM thank you.

**Pull request merged**
