### PR TITLE
New Mapping for the Numark N4

### PR DESCRIPTION
**Pull request by Swiftb0y**
I wasn't able to write any documentation yet but the code works so far. While I'm confident that the mapping works well, it has not undergone any more extensive tests. The code looks a bit messy at some parts so please ask if something isn't clear.

### CODE REVIEW

**Comment by uklotzde** [comment]
Should this be distributed as an update for 2.1? Then please change the target branch from *master* to *2.1*. Maybe you first need to rebase this branch or create a new branch on top of 2.1 that contains just the relevant commits.

What is the current status and who else is able to test this?

**Comment by Swiftb0y** [comment]
I guess it could be included as an update for 2.1, but I'm quite  familiar enough with git to know which commits are relevant in this case. 
The mapping works so far but I have yet to complete the documentation.
As far as I know, the N4 was pretty popular back in the day but I don't know how many people still have one.

**Comment by Swiftb0y** [comment]
I'm working on the Wiki page as we speak. I already made a, for mixxx customized, vectorized version of the Overlay that comes for Serato/Traktor (listed on the wiki already).

**Comment by Swiftb0y** [comment]
Ill close this, merge 2.1 and PR it again to the 2.1 branch

**Pull request closed without merging**
