### PR TITLE
lp1838887: Fix formatting of playlist duration

### PR DESCRIPTION
**Pull request by uklotzde**
https://bugs.launchpad.net/mixxx/+bug/1838887

Just because it is annoying and a super easy fix ;)

### CODE REVIEW

**Comment by Be-ing** [comment]
Should this go to the 2.2 branch?

**Comment by uklotzde** [comment]
Uh, thanks for the hint!! I forgot that this was introduced in 2.2 and didn't take notice, very bad.

**Comment by uklotzde** [comment]
Phew, no bug in 2.2.2. This only affects master!

The function names have changed and while merging the playlist fixes from 2.2 to master this regression was introduced.

**Comment by uklotzde** [comment]
@daschuer ;)

**Comment by daschuer** [comment]
LGTM thank you. 
This falls off my radar because Be-ing has commented first.

**Pull request merged**
