### PR TITLE
Linux: .mixxx to XDG_DATA_HOME

### PR DESCRIPTION
**Pull request by daschuer**
This moves the Linux settingsPath from .mixxx to $XDG_DATA_HOME/Mixxx 
default at ~/.local/share/Mixxx.

It follows the pattern introduced in #606

### CODE REVIEW

**Comment by kain88-de** [comment]
You want to move the configs to the data folder? That doesn't make sense and will confuse people on linux, I personally really check ~/.local for configs I usually see what is in ~/.config. If we really want to adjust to xdg standards it should be done in a sensible way (best hiding all platform dependent code). Sensible would mean to put configuration files into `~/.config` like other programs using XDG. Waveforms should go into `~/.cache` and controller mappings into `~/.local/share`.  

To manage the configs in a sensible way we can use [QSettings](http://doc.qt.io/qt-4.8/qsettings.html). Since this would break backwards compatibility anyway we can as well just switch to the default qt ini style config files.

Personally I don't think we should switch to the xdg standards. I think it is quite nice that we can handle the file storage for configs and data equally on any unix system.  Makes it easier to handle questions from users and we don't need to maintain 3 different code paths for all the OSs.

**Comment by daschuer** [comment]
> Can you correct windows version at the same time (line 195 and 199) ?

fixed in 1.12 branch

**Comment by daschuer** [comment]
@kain88-de, What is your suggestion? 

Please have a look at the Qt5 source:
QStandardPaths::writableLocation 
it is located in 
qstandardpaths_mac
qstandardpaths_win
qstandardpaths_unix 

Currently we follow the windows way data config and cache at one location. 
This is the "settingsPath" inside Mixxx, which can be controlled by a command line option. 

Mac does support the three storage locations. Currently we use the data location as well:  
"~/Library/Application Support/Mixxx/" 
It is just consequent to use also the data location on Linux. 

It is no issue to move it to ~/.config/Mixxx but IMHO we should move on Mac to ~/Library/Preferences/Mixxx/" as well. 

A desired split into "data / config / cache" inside Mixxx is probably out of scope of 1.12, but possible. 
For this we have to decide ho to handle the use cases that are currently covered by the --settingsPath command line parameter. 
With this commit you can alternative start Mixxx with 
"XDG_DATA_HOME=newSettingsPath mixxx"

It is probably the right time to make the split in conjunction with a move to QSettings.
However I am in doubt if this will offer any benefit that is worth the work. 

The benefit of this PR, is that we stop cluttering the home directory, which is strongly advised by 
the Linux distributors.

**Comment by kain88-de** [comment]
> @kain88-de, What is your suggestion?

Don't do this for 1.12. 



> Currently we follow the windows way data config and cache at one location.

And the silent convention for this on linux to put a folder with the application name directly into the home directory. Why change this in a way that isn't used by anybody else for no good reason?

> The benefit of this PR, is that we stop cluttering the home directory, which is strongly advised by
> the Linux distributors

So what? I don't see any reason how this would make the life of our users easier. After this it is impossible to downgrade from 1.12. We move to a location that is not at all easily discoverable on linux. Besides there is still a ton of software saving it's settings directly into the home directory (Even aptitude does that). I'm against this PR since it breaks things for no good reason.

**Comment by daschuer** [comment]
> Don't do this for 1.12.

Yes, we can postpone it to a later release. The idea to do it now, is because we have it already done for Mac and we have just introduced it for the various windows version. So we have break in our docu anyway and we can handle Linux in the same way.

> Why change this in a way that isn't used by anybody else for no good reason?

The good reason is that it is advised by the distros. The way we do here it fits the best to the xdg 
specs without do the split. 
Of cause a split is desirable but that can postpone to a later release. 
The XDG_DATA_HOME location is the correct location for the sqlight db and the controller scripts. 

If we decide to split up the folders, this will require a lot more complexity to upgrade / downgrade. 
Don't know if this is worth the work. 

Here some links. 
https://wiki.debian.org/XDGBaseDirectorySpecification
https://wiki.gnome.org/Initiatives/GnomeGoals/XDGConfigFolders
https://fedoraproject.org/wiki/Features/XdgConfigDirs  

> After this it is impossible to downgrade from 1.12.

But if you upgrade from 1.11 everything works, because it prefers the legacy location.  
Windows suffers the same issue with this release. You can't downgrade the preferences if you install 1.12 first.

**Comment by sblaisot** [comment]
What we did for windows was to move the entire preference folder.
Complying with XDG needs preference folder split into data, cache and config.

I'm in favor of making both (moving & splitting) under linux at the same time.
If we move the whole folder in 1.12 and split in latter release, this will confuse user 2 times.
I think it's better to switch to XDG folders when 
1. we are ready to make the whole change in one time
2. these folders are "natural" for users, which doesn't seems to be the case actually

**Comment by daschuer** [comment]
The same applies for Mac. It has also three folders, but we use only the data folder. 
What was the reason that we migrate to the single data folder on Mac? 
Probably because Apple is more restrict about dot folders in the home directory.

Why is an approach is OK one OS, but not on an other? 

The requirement for the XDG_CONFIG_HOME folder is that the Mixxx is back to default but no user data is lost. Mac has a similar folder, which is currently not used. 
This applies only for the mixxx.cfg file, right?  

Should we move only the mixxx.cfg file on Mac AND Linux?  

By the way: We have just removed from a hard coded folder on mac and replaced it by a library generated folder. This is what this PR does for Linux.
Did we verify that the folder is not changed throughout the Mac version? 
#606 silently assumes that since there is no upgrade path. 
QT4 code: 
```
OSErr err = FSFindFolder(domain, translateLocation(type), false, &ref);
```

**Comment by sblaisot** [comment]
yes, verified on MAC that QDesktopblahblahblah == hard coded former value
https://github.com/mixxxdj/mixxx/pull/606#discussion_r32021208

Nothing has changed from a user's point of view on MacOSX with PR606.
Windows has changed in a way that users did want and that is natural to them.

I'm not sure that Mixxx Linux users want it to be XDG compliant nor that these change will not confuse linux users. But we can make a survey in forums to be sure.

**Comment by kain88-de** [comment]
> The good reason is that it is advised by the distros

I'm not sure that they advice in putting everything into the data folder. How many applications do you have that save their CONFIG there? All the info links you cite talk about splitting the user data into logical chunks making the sys-admins live easier. If we don't split the data according to that we don't make the live of anyone easier. When we merge this PR would you be able to find the configs not having read the source/build code or manual?

> What was the reason that we migrate to the single data folder on Mac

we always had only one folder on Mac. It used to be `~/.mixxx` until @asantoni changed it in 2011 84c2ade 

> Why is an approach is OK one OS, but not on an other?

We should adopt a principle of least surprise. Personally I would also prefer to have the mixxx config files under mac in `~/.mixxx`.

> This applies only for the mixxx.cfg file, right?

Nope we save configuration in the database. Which folders we track and well all the tracks and their configurations.

**Comment by rryan** [comment]
Hello! This branch is against the 1.12 branch, which is now closed to any changes except bugfixes. Please re-open your PR against master if this PR is still relevant.

**Pull request closed without merging**
