### PR TITLE
Windows clang-cl build

### PR DESCRIPTION
**Pull request by JoergAtGithub**
This is an experimental build with the clang-cl compiler that comes with VisualStudio 2019.
clang-cl is a clang compiler variant, with MSVC compatible command line interface.

The CI build fails due to a header of protobuf, which is part of the Windows buildenv. I could fix this locally by applying: https://github.com/protocolbuffers/protobuf/commit/1d2e8d93027d988f497a4690eb47ece1fe47d665

My local build succeed, passed all tests and works flawless. But it feels slower than the MSVC build - I expected the opposite after the auto-vectoization results from @daschuer in #4861

### CODE REVIEW

**Comment by daschuer** [comment]
It would be interesting how a mingw gcc build will perform. 
We may also consider to make sample.cpp a library and compile only this with a different compiler.

**Comment by JoergAtGithub** [comment]
Mingw is wormhole of problems, you would need to change the code at numerous places. Once I spend hours on a simple command line programm, due to differences in the implementation in the C standard function scanf.
For Mixxx you would need to compile the whole buildenv with Mingw first, because it's not ABI compatible to the other compilers. Mingw also force you, to use their own debugger, profiler etc. due to ABI incompatibilty.

Clang-cl is just a drop in for MSVC - only the compiler itself is changed and creates ABI compatible binaries, PDB files etc.

**Comment by JoergAtGithub** [comment]
I intend to delete the GitHub build action before merging.
Only the changes in `CMakelists.txt` and the fixes of build error/warning should be merged.

**Review by Swiftb0y — APPROVED** [review]
Anything left to do here?

**Comment by daschuer** [comment]
After merging this, we will have two windows build for every PR, a waste of energy if we will not use it, do we? 
Can we disable it before merging and only enable it when we want to check certain things?

**Comment by JoergAtGithub** [comment]
Yes, the CI build was only for testing. I will remove it.

**Review by Swiftb0y — COMMENTED** [review]
waiting for ci. thank you

**Review by Swiftb0y — APPROVED** [review]

**Pull request merged**
