### PR TITLE
Merge 2.4 to 2.5

### PR DESCRIPTION
**Pull request by acolombier**
Merges the following changes to `2.5`
- #13524 
- #13545 
- #13530

### CODE REVIEW

**Comment by acolombier** [comment]
I might have gone a bit too quick with this one... @Swiftb0y should I close that PR?

**Comment by Swiftb0y** [comment]
I'm afraid I can't follow you? Whats wrong with which PR?

**Comment by acolombier** [comment]
This is a follow up with #13530, however I took all the changes from 2.4 for 2.5, instead of cherry picking just my fix, so perhaps it would have been better? If we are happy with a full sync, then all good!

**Comment by Swiftb0y** [comment]
Ah, well we also have the 2.5 branch, so usually the workflow is 2.4->2.5->main. I'll take care of merging locally and push directly.

**Comment by Swiftb0y** [comment]
fyi, I'm currently fighting with https://github.com/DavidAnson/markdownlint/issues/1328 So merging to the newer branches will have to wait until we have resolved that (or we downgrade markdownlint again for now).

**Comment by Swiftb0y** [comment]
done. though CI still fails [because of codespell](https://github.com/mixxxdj/mixxx/pull/13567)...

**Pull request closed without merging**
