### PR TITLE
Effects refactoring: loaded chain

### PR DESCRIPTION
**Pull request by daschuer**
Ensure a consistent naming in EffectChain and fix some code issues.

### CODE REVIEW

**Comment by Be-ing** [comment]
As I have already said, I am firmly opposed to this renaming. A preset is loaded into a chain. Conflating a preset with a chain creates a confusing situation.

**Comment by daschuer** [comment]
I had to rebase this because unwanted commits from #2618 have slipped in.

**Comment by Be-ing** [comment]
There are still unwanted commits in here.

**Comment by Be-ing** [comment]
Still no justification has been made why this is so important to delay merging #2618 for months against unanimous consensus of everyone else.

**Pull request merged**
