### PR TITLE
Update default launchimage, that is displayed on startup. Found the cu…

### PR DESCRIPTION
**Pull request by esbrandt**
…rrent one looks a bit fuzzy.

Changes: filetype png->svg, color -> monochrome, icon height = text height, spacing now 0.5 em between icon and text

Follow up to mixxxdj#650

1st line is the new, 2nd the old launch image
lauchimage_update

### CODE REVIEW

**Comment by daschuer** [comment]
Nice, thank you! LGTM

**Comment by rryan** [comment]
+1, thanks @esbrandt

**Comment by rryan** [comment]
Oops -- this was against master. Did you intend 1.12 @esbrandt ?

**Comment by Be-ing** [comment]
Thanks, that looks nicer. :)

**Comment by esbrandt** [comment]
Don’t mind if this is only in master, but my target was 1.12.
Did not check that github gives master as default target branch when requesting a pr via website.

**Comment by ywwg** [comment]
I cherry-picked this for 1.12. Thanks!

**Pull request merged**
