### PR TITLE
CMake: tell MSVC that source code is UTF8

### PR DESCRIPTION
**Pull request by Be-ing**
alternative to #3562

### CODE REVIEW

**Comment by Be-ing** [comment]
> If no byte-order mark is found, it assumes the source file is encoded using the current user code page, unless you've specified a code page by using /utf-8 or the /source-charset option.

https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-160

**Comment by Holzhaus** [comment]
If you compile with `/W4` the flag isn't needed?

**Comment by uklotzde** [comment]
This PR is a band aid, not an alternative.

Using a different encoding for text files than the systems native encoding can still cause problems. This PR fixes interaction with the compiler. But you can't control which other applications a developer uses to edit files.

**Comment by uklotzde** [comment]
Unfortunately, C/C++ does not define a fixed encoding for source files. It always depends on your toolchain. And the toolchain involves more than just the compiler.

**Comment by uklotzde** [comment]
@Be-ing Still incomplete according to @Holzhaus

**Review by uklotzde — APPROVED** [review]
I am still unsure how Windows handles text files in the Git working tree, because UTF-8 is not the native encoding.

Nevertheless the Windows CI build succeeds so this should hopefully work for almost everyone.

**Comment by uklotzde** [comment]
@Holzhaus I got confused by al those open PRs? Did we miss something? I didn't even remember my old comment asking for your opinion.

**Comment by Holzhaus** [comment]
Don't worry, we can just fix the issue in another PR. Right now the flag is only passed when building with `/W3`, not `/W4`.

**Pull request merged**
