### PR TITLE
Changed track numbers to integer instead of QString

### PR DESCRIPTION
**Pull request by barshan23**

### CODE REVIEW

**Comment by barshan23** [comment]
test this please

**Comment by barshan23** [comment]
OK to test

**Comment by daschuer** [comment]
Comments at https://bugs.launchpad.net/mixxx/+bug/1388640

**Comment by rryan** [comment]
Hi @barshan23 -- I left a comment on https://bugs.launchpad.net/mixxx/+bug/1388640 but unfortunately I don't think this is actually a bug. I'm again very sorry for not making it more clear on the bug that the bug was working as intended.

**Pull request closed without merging**
