### PR TITLE
Effects fader compensation

### PR DESCRIPTION
**Pull request by Be-ing**
The character of dynamics effects change with the input level and effects are processed after the volume fader. So, to preserve the character of the effect as the volume fader is lowered, undo the attenuation from the volume fader on the input for the effect, then reapply it on the output. Currently Bitcrusher is the only effect this matters for, but when we have a compressor in the future I think the same trick would be appropriate.

### CODE REVIEW

**Comment by Be-ing** [comment]
Hmm, on second thought, this trick doesn't make much sense if the effect is not first in the chain...

**Comment by daschuer** [comment]
Uh, that becomes more and more hacky. You can make the bitcrusher a quick effect, an you are done.
To much magic does not suit here, it is also a value to have a predictable result, when changing effects.

We may also consider to add a kind of normalizer to the bitcrusher, to always hit the sweet point when being at one bit. When have anyway the issue, that the current bitcrusher implementation is optimized for the replay gain loudness with unity gain. That is not always the case.

**Comment by Be-ing** [comment]
I agree, this is quite hacky. Could you explain your idea a bit more? Are you suggesting to normalize the input to a target level then apply the inverse gain for the output? How could the effect do such normalization?

Anyway, this is a quite minor issue and we have bigger things to worry about now for 2.1.

**Comment by daschuer** [comment]
The sweet point of a bitcrusher in on bit mode is if some bits are 1 and some bits are 0.
Therefore we can use PT1 smoothing filter to detect the average peak over the time and adjust the gainCorrection accordingly.

**Comment by kazakore** [comment]
I know you guys don't want to give the user the option to select between pre and post for each effects chain themselves but I feel any other attempt to fix this is just going to be a hack! There's a reason this is provided by Traktor and on the DJM mixers. If you ever get integration of third party effects such as the LV2 fork which is in process this is going to become even more important. No point shooting yourself in the foot and giving yourself extra work down the line.

**Pull request closed without merging**
