### PR TITLE
WIP: Build for armv7 and aarch64

### PR DESCRIPTION
**Pull request by fayaaz**

### CODE REVIEW

**Comment by Be-ing** [comment]
Please rebase this on 2.3.

**Comment by Be-ing** [comment]
Do we really need to test 3 different ARM setups? GitHub Actions is generous and gives us 20 concurrent jobs for free but if we add another 3 to every push that will add up. I presume the primary purpose for this is for Raspbian, is that right? If so, I don't think we need Ubuntu ARM builds.

**Comment by Be-ing** [comment]
On the other hand, with Ubuntu builds we could push packages to our PPA.

**Comment by fayaaz** [comment]
We could limit the number of these [jobs running in parallel](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel). I think Ubuntu 20.04 arm64 and debian buster arm64 will be enough. However most of the OSs that people run will be 32-bit, as a stable 64-bit OS on the RPi is still not available.

**Comment by uklotzde** [comment]
A build time of almost 3 hrs? That's crazy. Unfortunately, we cannot enable this job for regular CI builds.

The ARM builds on RPM Fusion take considerably longer (especially for armv7hl), but not that much. The build logs don't show any time stamps, so I don't have exact numbers.

The longest SoundSourceProxy test took 84 sec -> timeout = 90 sec should be suffcient.

**Comment by Be-ing** [comment]
Perhaps we could enable this workflow only on `push` events but not `pull_request` and only build one ARM target. That won't catch ARM build failures before merging PRs, but we should at least notice them before making releases.

> A build time of almost 3 hrs? That's crazy. Unfortunately, we cannot enable this job for regular CI builds.

Cross compiling with Guix might be a faster alternative to emulation if we get Mixxx building with Guix (which I think we should do anyway).

**Pull request closed without merging**
