### PR TITLE
do not flash the cue button in Mixxx mode when deck is paused

### PR DESCRIPTION
**Pull request by Be-ing**
Blinking is annoying. See discussion in PR #661

### CODE REVIEW

**Comment by sblaisot** [comment]
This PR also needs a similar PR on mixxmanual.
http://mixxx.org/manual/1.12/chapters/user_interface.html#using-cue-modes

**Comment by Be-ing** [comment]
I can do that.

**Comment by daschuer** [comment]
This mode will work for me as an extra mode. 

I like to see clearly that the CUE button is in "Store" mode at the CUE button, especially on my midi controller. The Pioneer mode with its fast flashing Cue and flashing play is no alternative for me. 

We may discuss how we call both modes and which is the default. 
We should also discuss how this matches with the hot cue buttons.

**Comment by Be-ing** [comment]
I'll wait for others to chime in on whether we should merge this as is or add another cue mode.

>  We should also discuss how this matches with the hot cue buttons.

That's an issue for after 1.12. We can discuss it along with https://blueprints.launchpad.net/mixxx/+spec/cuepoins-2.0

**Comment by Be-ing** [comment]
Thoughts, anyone? Should there be a new mode? If so, what should it be called? Mixxx mode (no blinking)?

**Comment by daschuer** [comment]
> Mixxx mode (no blinking) 

works for me. 
"Pioneer mode (no blinking)" will be the same, probably a bit more significant for new users, but I have no preferenc for one of them.

**Comment by ywwg** [comment]
if you want to create a new mode, that seems fine.  I also dislike the blinking in the UI

**Comment by Be-ing** [comment]
> if you want to create a new mode, that seems fine. I also dislike the blinking in the UI

Okay, I'll do that then.

**Pull request closed without merging**
