### PR TITLE
Update mixxx.desktop

### PR DESCRIPTION
**Pull request by trebmuh**
adds French menu items

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for taking care! LGTM. 
Be fore merge, we need your permission.
Please sign https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ and comment here when done.

**Comment by trebmuh** [comment]
@daschuer : while I do acknowledge that you're doing the right way when exposing engagements and expectations to the contributors, I'd say that this contribution (a two-liners, 5 words of translations) doesn't require me to sign off a contract which anyway wouldn't have any value for me (I'm French, and in case of dispute, a French tribunal doesn't recognize paper in another language than French at the end of the day).

Anyway, far from me to argument here, let's say that this is a gift from me to the wonderful Mixxx project, feel free not to merge this PR, but to commit yourself a PR, then there is no contribution/licensing issue. As if we were mate and I'd tell you:
> Hey, do you know that "Digital DJ interface" translates to "Interface numérique pour DJ" in French ?"

then you come back home, sit down in front of your computer and decide to use your new knowledge to add a translation of the menu item.

Have a nice day.
Olivier

PS: and congrats for the new French knowledge that you learn today! Wouldn't it be a challenge for you to reuse it in a daily conversation with a random French speaker? :)

**Comment by daschuer** [comment]
Ok, thanks.

**Comment by trebmuh** [comment]
👍

**Pull request merged**
