### PR TITLE
Adjust nativeEventFilter() for Qt6

### PR DESCRIPTION
**Pull request by daschuer**
This fixes building the main branch with Qt6

### CODE REVIEW

**Comment by daschuer** [comment]
That is a windows only file. 
We did not notice this merging issue  before, because our main windows CI stops before starting to build.

**Comment by JoergAtGithub** [comment]
Something is corrupt with this PR. The number of compiled files matchs to 2.5, while the buildenv is from 2.4.

Otherwise the changes in this PR LGTM.

**Comment by daschuer** [comment]
Windows build fails unrelated because of: 
```
D:\a\mixxx\mixxx\src\test\enginemixertest.cpp: error C2220: the following warning is treated as an error
D:\a\mixxx\mixxx\src\test\enginemixertest.cpp: warning C4651: '/DDJINTEROP_SOURCE' specified for precompiled header but not for current compile
[844/956] Building CXX object CMakeFiles\mixxx.dir\cmake_pch.cxx.obj
```
Let's target that separate. 

Merge?

**Comment by JoergAtGithub** [comment]
The data in this PR are corrupted - CI build other code, than shown in the PR diff. I guess rebasing failed somehow.

Can you please create a clean PR with the same code change.

**Comment by daschuer** [comment]
Here it is: https://github.com/mixxxdj/mixxx/pull/12433

**Pull request closed without merging**
