### PR TITLE
numark party mix controller added by rylito

### PR DESCRIPTION
**Pull request by braindef**
added the tested files from your forum:

https://mixxx.org/forums/viewtopic.php?f=7&t=9232&start=10#p38408

tested on debian 11 (bullseye) in the dir ~/.mixxx/controllers

Greetings and Thank you for Mixxxx

### CODE REVIEW

**Comment by Holzhaus** [comment]
Hi braindef, thanks for you contribution!

There are some code style issues. I think you can fix most of them using our pre-commit hooks:
https://github.com/mixxxdj/mixxx/blob/master/.pre-commit-config.yaml#L20-L40

Just install `pre-commit` and then run:
```
$ git remote add upstream https://github.com/mixxxdj/mixxx.git
$ git fetch upstream
$ pre-commit run --origin HEAD --source upstream/master
```

Also, unless you used features that are not present in Mixxx 2.2.3, controller mappings usually go into the release branch (i.e. `2.2`), not `master`. This means that you should rebase after fixing the linter issues. See https://mixxx.org/wiki/doku.php/using_git#targeting_another_base_branch for details how to do that.

**Comment by braindef** [comment]
> Hi braindef, thanks for you contribution!
> 
> There are some code style issues. I think you can fix most of them using our pre-commit hooks:
> https://github.com/mixxxdj/mixxx/blob/master/.pre-commit-config.yaml#L20-L40
> 
> Just install `pre-commit` and then run:
> 
> ```
> $ git remote add upstream https://github.com/mixxxdj/mixxx.git
> $ git fetch upstream
> $ pre-commit run --origin HEAD --source upstream/master
> ```
> 
> Also, unless you used features that are not present in Mixxx 2.2.3, controller mappings usually go into the release branch (i.e. `2.2`), not `master`. This means that you should rebase after fixing the linter issues. See https://mixxx.org/wiki/doku.php/using_git#targeting_another_base_branch for details how to do that.

Hello @Holzhaus  (vermutlich könnt ich somit auch Schweizerdeut palavern)

ich hab nur die zwei Controller Files hinzugefügt für den Numark Party Mix Controller. Die hab ich von Eurem Forum und sind meiner Meinung i.O. also hab ich gedacht, knallt doch die zwei Files ins mein Repo...

Gruss aus der eingebildeten Schweiz
Marc jr Landolt

**Comment by Holzhaus** [comment]
Hi @braindef,
I'll answer in English so that other devs can follow the discussion, too :wink:
I appreciate that you decided to open a PR for this mapping. A lot of mappings fluctuate on the forums, but are not supported by Mixxx out of the box because nobody filed a PR to get it integrated.

Controller mappings usually go into the next Mixxx release, which will be 2.2.4. Your PR is currently targeting the `master` branch (where we're currently working on 2.3). Rebasing and changing the target branch only takes less than a minute with the instructions I linked above. You can also keep targeting `master` (i.e. 2.3), but then it will take a few months before this mapping will be released as part of Mixxx. 

Developing a software project as big as Mixxx is hard. This is why we need to make sure that all new code is maintainable and can easily be edited or extended by other developers. To make sure that this is the case we have code style guidelines and do code reviews. I didn't actually review yet, so there might be a few changes necessary to get this into a mergeable state. I hope that doesn't scare you away. It's not that much work for a single PR. 
Most of the code style issues can easily be fixed via `eslint`. Just run `eslint --fix /path/to/controller/script.js`. 

We also need to make sure that the controller is mapped in a sensible and intuitive way. A wiki page that describes the mapping would help with that.

**Comment by katsar0v** [comment]
Is there update on this issue? I am a developer who bought this controller and would like to help :)

**Comment by Be-ing** [comment]
If you don't see an update here then there is no update. @katsar0v if you want to open a new PR for a mapping for this controller, that would be great. Please read https://mixxx.org/wiki/doku.php/contributing_mappings first.

**Comment by Holzhaus** [comment]
It looks like @braindef is not going to fix the remaining issues, so I'll close this fow now. @katsar0v Feel free to open a new PR, support for more controllers is always good :D

**Pull request closed without merging**
