### PR TITLE
Update changelog for 2.3.4

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by daschuer** [comment]
This is now up to date (again)

**Review by ronso0 — APPROVED** [review]
Content LGTM

The change date is auto-filled when the xml is created? So it'll be updated when the actual package is created?

**Comment by daschuer** [comment]
> The change date is auto-filled when the xml is created? 

Yes, It is now taken form the previous commit. 

> So it'll be updated when the actual package is created?
Yes, because it is updated whenever the Changelog has been changed.

**Comment by ronso0** [comment]
Alright the, LGTM. Thank you!

**Pull request merged**
