### PR TITLE
let any effect with a default superknob linking be a QuickEffect

### PR DESCRIPTION
**Pull request by Be-ing**
Before, only Filter, Moog Filter, and Bitcrusher were able to be loaded as QuickEffects. This was arbitrary and artificially limiting the capability of the QuickEffect knob. In the future, when exporting/importing effects chains is implemented, it will be cool to let users import whatever custom effect chain they want as a QuickEffect.

### CODE REVIEW

**Comment by Be-ing** [comment]
This brings up the issue of how to fit the QuickEffect labels in Deere, but that is [not a new issue](http://djtechtools.com/2016/01/06/review-mixxx-2-0-free-dj-software/) because the Bitcrusher name was cut off in 2.0. I'll experiment with solutions for that.

**Comment by rryan** [comment]
Code LGTM

> Before, only Filter, Moog Filter, and Bitcrusher were able to be loaded as QuickEffects. This was arbitrary and artificially limiting the capability of the QuickEffect knob. In the future, when exporting/importing effects chains is implemented, it will be cool to let users import whatever custom effect chain they want as a QuickEffect.

:+1: this will be nice!

**Comment by rryan** [comment]
> This brings up the issue of how to fit the QuickEffect labels in Deere, but that is not a new issue because the Bitcrusher name was cut off in 2.0. I'll experiment with solutions for that.

Even the short names are too long?

**Comment by Be-ing** [comment]
> Even the short names are too long?

Yes, the short names were designed for identifying the effect in the effect section of the skin. There is more space available there than under a knob.

I thought about introducing a new super short effect name capability, but it's difficult to shorten "Bitcrusher" or "Moog Filter" any further.

**Comment by rryan** [comment]
> Yes, the short names were designed for identifying the effect in the effect section of the skin. There is more space available there than under a knob.

I know, let's use emoji! 

In all seriousness, I think marquees are garish but could work here. Either that or truncate and let the user hover if they're confused (after all, they set the effect in the preferences anyway so they should know what it is?).

**Comment by Be-ing** [comment]
I'll try eliding the effect name. With #940 users are able to resize the mixer to hide knob labels if they do not want to see them.

**Comment by Be-ing** [comment]
> after all, they set the effect in the preferences anyway so they should know what it is?.

Good point. I think as long as the default "Filter" label fits without eliding that is what is most important.

**Comment by daschuer** [comment]
The Limit to the best suitable effect was done by design. In the EQ preferences is a check-box which allows to load any effect to the Quick effect and EQ. It looks like this PR brakes this feature. 

Maybe the GUI presentation was not obvious. Lets tweak that instead.

**Comment by Be-ing** [comment]
The label for that preference is: "Allow EQ knobs to control only EQ-specific effects". It does not mention the QuickEffects. It is confusing that it changes the available options for the QuickEffect. Unchecking that option lets EQ effects be selected for the QuickEffect, which I think is a bug because they do not have a default superknob linking (and they should not).

While it would be really confusing if a user accidentally loaded an effect that is not an EQ to the EQ slots, I don't think it would be such an issue if a user loaded another effect to the QuickEffect. The names of the effects make it clear what they are.

**Comment by daschuer** [comment]
The Filter and Moog effect suits very good for the EQ slots. There are actually hardware devices which have a filter instead of an EQ.

IMHO "Best suited" super knob effects should have a fade out / fader in nature like Filter or bit crusher.
We should keep them explicit marked somehow. 

It is a good idea to remove effect from the list which do not have a superknob linking.

**Comment by Be-ing** [comment]
I don't think Bitcrusher belongs in the same category as Filter or Moog Filter, which is why I made this PR. Sure it could be used to fade a track in or out, but that sounds nothing like a typical fade.

With this PR, Filter and Moog Filter still appear at the top of the list of QuickEffects. I am not sure why that is, but it works.

**Comment by Be-ing** [comment]
> The Filter and Moog effect suits very good for the EQ slots.

Yeah, it could make sense to load Filter or Moog Filter to an EQ slot. But loading Reverb to the EQ slots is odd.

**Comment by rryan** [comment]
> In the EQ preferences is a check-box which allows to load any effect to the Quick effect and EQ. It looks like this PR brakes this feature.

I think this is confusing because the quick effect rack is in the EQ preferences -- it should probably go in the Effects preferences instead. 

> IMHO "Best suited" super knob effects should have a fade out / fader in nature like Filter or bit crusher.

I don't agree -- any effect with a superknob linking is essentially advertising "I am one-knob capable", so it seems arbitrarily limiting to define what the quick effect rack is "for". I'm for letting the user decide that.

**Comment by daschuer** [comment]
We may consider read something fancy, that allows to change a limited set of super knob effect on the fly. Since this this should be configurable by the user, it makes sense to remove the static solution for now. 

LGTM

**Pull request merged**
