### PR TITLE
Roland DJ-505: Fix SYNC button behaviour

### PR DESCRIPTION
**Pull request by Holzhaus**
This fixes a nasty little bug that was discovered while testing #2376.
Before, pressing the SYNC button always caused beatsync, even on long
press. This caused sudden jumps/rate changes on the playing deck even
when the other deck did not have sync enabled and was not playing.

~~This also adds support for setting sync_master on a deck:
When sync is already enabled and the button is long pressed, sync_master
is enabled. The SYNC button indicates the master state with a blinking
LED.~~ (Removed due to #2376)

### CODE REVIEW

**Comment by Holzhaus** [comment]
I also fixed a little issue with long pressing TAP, when the short press was already be trigger when first pressing down the button.  If sync and quantize was enabled, the phase was already starting to shift which is undesired if the track was already beatmatched manually.

**Comment by Holzhaus** [comment]
@dogo77 Do you have time to test this?

**Comment by Swiftb0y** [comment]
> The SYNC button indicates the master state with a blinking LED.

[From the Wiki](https://mixxx.org/wiki/doku.php/contributing_mappings#blinking_leds)
> Mappings should not blink LEDs for an extended period of time. 

Is there no other way to indicate the master?

**Comment by Holzhaus** [comment]
I don't see how, the LED is single color. What do other controllers do?

**Comment by Swiftb0y** [comment]
Well if its single color you have four options, off, dim (if the controller supports it), full on and blinking. You could switch some indicators around so the blinking output is only used for a state which occurs rarely or not displayed by default.
What do the other LED states currently signify?

**Comment by Holzhaus** [comment]
> What do the other LED states currently signify?

- Off: sync disabled (`sync_mode` == 0)
- On: sync enabled (`sync_mode` == 1)
- Blinking: sync enabled and deck is master (`sync_mode` == 2)
- Dim: Not supported by hardware

> You could switch some indicators around so the blinking output is only used for a state which occurs rarely or not displayed by default.

With our current `master` branch, the blinking only happens when the user explicitly sets a deck as sync master. So if a user does not care about master and just uses regular sync (where the internal clock is master), this should not cause any blinking.

**Comment by Holzhaus** [comment]
I'll just remove the sync_master related stuff from this PR, until we figured out how Mixxx should behave in #2376.

**Comment by Holzhaus** [comment]
Done.

**Comment by Holzhaus** [comment]
OK, I re-added the setting/showing the `sync_master` status again. This implementation works fine for current `master`. After #2376 and #2584, the button will only blink if the user has explicitly set `sync_master`, not when using regular sync (with automatic `master`) or one-shot beatsync.

**Comment by Holzhaus** [comment]
Merge?

**Comment by uklotzde** [comment]
Yes. LGTM.

**Pull request merged**
