### PR TITLE
Add vinyl control

### PR DESCRIPTION
**Pull request by jmigual**
Refers to bug: https://bugs.launchpad.net/mixxx/+bug/1530619

Adds the vinyl control option to Deere Skin

### CODE REVIEW

**Comment by Be-ing** [comment]
Great, thanks for taking care of this. Please post screenshots when you make a PR for skins.

**Comment by jmigual** [comment]
Ups sorry for the screenshot, here it is

screenshot from 2016-05-02 20-56-40

**Comment by daschuer** [comment]
Thank you for this PR. I will test it tomorrow. 

Currently Deere fits on a 1024 pixel width screen. I am afraid that this PR grows the skin. I will check it. 

How important is the minimum with for Deere? 
@esbrandt: any ideas?

**Comment by daschuer** [comment]
I have just noticed that the status text changes on the buttons in the same way as in the LateNight skin. 
On the first look it was confusing for me. Normally I would expect a "Call to action" button like we have at the Auto DJ. Pressing a "Vinyl off" button may switch the vinyl control off in this case. 
How do the other think? 

For now I it seams to be the best solution to just remove the "on" / "off" part, the color change should be sufficient.

**Comment by jmigual** [comment]
Ok, I agree with you colour must be enough, to add the vinyl control I read the LateNight code so I ended up using similar thins. I will remove the "on" / "off" part, this also should allow the skin to use less space.

**Comment by jmigual** [comment]
Ok, removed On / Off it fits in a 1024 screen but not very well...

screenshot from 2016-05-03 00-11-28

screenshot from 2016-05-03 00-13-21

**Comment by Be-ing** [comment]
The vinyl control buttons get a bit squashed with the menu open at 1024 width, but they look okay without the menu open so I think it's fine. 

I think it would make more sense to move the option to the "MAIN DECKS" section of the settings menu and rename it "Show vinyl control options".

**Comment by daschuer** [comment]
The new buttons are working well. Thank you. 

If I assume this skin should still work on 1024 x 768 screens, there are some issues ... 

Now the beat loop controls are not usable on 1024 width screens. 
I can think of two solutions: 
* A Shade skin like solution where we extend the vinyl control button into the waveform overview or the spinny. 
* use the WSizeAwareStack to hide some other buttons when there is no space left. (instead of squash them to an unusable state)

**Comment by jmigual** [comment]
I think I like more the Shade skin like solution so I will try and see if it fits well in Deere skin.

**Comment by jmigual** [comment]
Ok, moved

This is in a 1920x1080 window
screenshot from 2016-05-04 09-21-42

This is in a 1024x768 window
screenshot from 2016-05-04 09-21-57

**Comment by daschuer** [comment]
Great :-) LGTM. 
If there are no further objection, I like to merge this.

**Comment by Be-ing** [comment]
This won't work for stacked waveform mode. The vinyl buttons will misalign the center line of the waveforms.

**Comment by jmigual** [comment]
Currently the center line is misaligned because the Spinning Vinyl is shown in the current Mixxx version (2.1.0 rev 5763)

screenshot from 2016-05-04 17-52-22

**Comment by Be-ing** [comment]
Yes, and users can turn off the spinnies.

**Comment by daschuer** [comment]
Fixing the center issue requires some work on the waveforms. 
Instead of center the play-position to the waveform, we may center it to the parent widget group, or/and allow the skin to tweak the center position conditional. This will help in all skins. 
I have filed a bug: https://bugs.launchpad.net/mixxx/+bug/1578812

What does it mean for this PR? The center issue makes the solution not that ideal, but given the fact that the issue was there before and that the user can disable vinyl control again to have it centered, IMHO it is a minor issue compared improvement that you can now use Deere for vinyl control. 

@Be-ing: What do you think, Is this merge-able do we need a third solution. 
What are your ideas?

**Comment by jmigual** [comment]
So should we merge as it is or do you think there's some change to do?

**Comment by rryan** [comment]
Has anybody with a turntable tried it out to see if it works?

**Comment by Be-ing** [comment]
It is a bit odd to have the buttons up by the waveforms in stacked waveform mode. However, adding yet another cluster of buttons to the deck controls makes it feel cluttered. I think it's mergable.

**Comment by daschuer** [comment]
Thank you @jmigual for the work! LGTM.
Thank you all for review.

**Pull request merged**
