### PR TITLE
Set patched flag and build revison from git describe 

### PR DESCRIPTION
**Pull request by daschuer**
Since we move from the over all git count to the count since last tag, this is a step back in versioning. 
Does this cause any issues with the installer? I don't think so ... 

The tarball build will be marked as patched, the revision count is only used if the latest tag is a actually a version tag.   

Caveat: If anyone uses other tags, the build revsion is gone. 
That OK for me, because the about box shoes still the truth. 

A simple alternative would be to always not use the build number in the rc file.

### CODE REVIEW

**Comment by daschuer** [comment]
Wait. This is much easier with `git describe --match` and still allows other tags

**Comment by Holzhaus** [comment]
> Since we move from the over all git count to the count since last tag, this is a step back in versioning.

We didn't use the overall commit count though. You can get the commit count like this:

    $ git rev-list --count HEAD

But we are currently using:

    $ git rev-list --count --first-parent HEAD

That ignores all commits from the second parent of merge commit. No idea why we do that.

> The tarball build will be marked as patched, the revision count is only used if the latest tag is a actually a version tag.
>
> Caveat: If anyone uses other tags, the build revsion is gone.
> That OK for me, because the about box shoes still the truth.
>
> A simple alternative would be to always not use the build number in the rc file.

I'd rather not use the commit count at all, or always use it. Let's try to avoid doing special "magic" on tags.

Let's take a step back and ask ourselves why we need the commit count? On windows, the RC file doesn't support the `git describe` format. So the alternatives are: a) Just use the CMAKE_PROJECT_VERSION or b) Use CMAKE_PROJECT_VERSION + commit count. What difference does this make? That is not clear to me. Does it only have an impact on what is shown in the file properties dialog on windows or is it used for something else?

If it's just for display, we should probably just drop the overall commit count. There is no benefit IMHO, because the commit count could mean *anything*. If I branch off from 2.3 and a commit, and then make another branch from 2.3 and add another commit, both commit counts are there same. It doesn't help identifying what version is actually built. It will only confuse users and distract from the version that matters when reporting bugs (the git describe version).

**Comment by daschuer** [comment]
I think we have just a misunderstanding here.

We have an agreement to dispose GIT_COMMIT_COUNT and use git describe instead.

For the RC file version this means we go form 
2.3.0.8151 back to 2.3.0.3781  
I don't think this is a real issue, I just want to point it out, having the chance to verify this. 

The other related question is how to assert that the tag is formatted correctly. Wrong tags do not happen in our main repo (hopefully), but we don't know what contributors do locally.   

Git has a solution for it:
'git describe --match'

In our case this makes no difference, because it matches the recent tag anyway.

One exception: When building the release candidate before tagging. In this case it falls back to the new version, which will be the future tag = 'git describe' after tagging. Problems solved :-)

**Comment by Holzhaus** [comment]
> For the RC file version this means we go form
> 2.3.0.8151 back to 2.3.0.3781
> I don't think this is a real issue, I just want to point it out, having the chance to verify this.

Where does `3781` come from? I don't get it.

> We have an agreement to dispose GIT_COMMIT_COUNT and use git describe instead.

`2.3.0.3781` is not the output of `git describe` though. I think we either keep the git commit count (`2.3.0.8151`) or we drop it (`2.3.0`), depending on if that version is just used for display purposes (then we just remove the count, because it's not helpful anyway) or if it actually makes a difference, e.g. for the installer. Then we can just keep the commit count, don't we?

**Comment by Holzhaus** [comment]
> > For the RC file version this means we go form
> > 2.3.0.8151 back to 2.3.0.3781
> > I don't think this is a real issue, I just want to point it out, having the chance to verify this.
> 
> Where does `3781` come from? I don't get it.

Ah, now I get it. It's the number of commits since the last tag, i.e. the output of:

    $ git rev-list "$(git describe --abbrev=0)..HEAD" --count

Anyway, if it doesn't make a difference, we do we keep that number at all?

**Comment by daschuer** [comment]
It is the commit count since the tag taken from 2.3-beta-3781-g455b9d48d2

You see all these meta info if you right click the mixxx.exe and select properties. 

This commit count is our new consecutive version version number part, we need for the debian package manager.

**Comment by Holzhaus** [comment]
Ah OK, so we need it for debian packaging. 

Following problem:

| Commit | Result |
| - - - - | - - - - |
| 10th commit after the `2.3-beta` tag | `2.3.0.10` |
| 10th commit after the `2.3.0` tag | `2.3.0.10` |

We can solve it either by doing what you proposed, i. e. use the count since tags that match the pattern `^\d+\.\d+\.\d+$`. But then we'd now have a count that is since the 2.2.4 tag which would have the same "overlap" issue as I outlined above when we tag 2.3.0.

Therefore I suggest we use the overall commit count since the beginning of history:

    $ git rev-list --count HEAD

**Comment by daschuer** [comment]
In the windows case this is not the problem when because of the prebuild flag and in base of debian we can replace the leading 0 with alpha and beta.

Sure, we can also keep the commit count, for a not that fragile numbering. 
The only issue is that than we use two types of commit counts in our different distributions which might be confusing. 

I don't get the issue you describe with the 2.2.4 version.

If we ensure that the tag matches the Mixxx version, we always have a consistent count.
The only issue is the case where we have not yet tagged a release commit. In this case we will not find a matching tag and the number becomes 0.
It will be 0 anyway after the tag has been set.

**Comment by Holzhaus** [comment]
> I don't get the issue you describe with the 2.2.4 version.

Maybe this helps:

| Commit | CMAKE_PROJECT_VERSION | Commits since last tag | Description |
| ------ | -------- | ------ | ------ |
| 2.2.4 tag | 2.2.4 | 0 | 2.2.4 release
| 2.2.4 + X commits | 2.3.0 | X | 2.3 branch-off
| 2.3.0 | 2.3.0 | 0 | 2.3.0 release
| 2.3.0 + X commits | 2.3.0 | X |  This would be the same version as 2.2.4 + X commits

**Comment by Holzhaus** [comment]
Therefore I think we should probably just use the commit count for all of the history, indenpendent of the tag, i.e. `git rev-list --count HEAD`.

**Comment by daschuer** [comment]
In that case I would prefer to continue with the established: 
`git rev-list --count --first-parent HEAD`

If we want to move to "the count since the last tag" from git describe we need to make sure that we set a tag whenever we change the version number to avoid ambiguous versioning. We can make use of the --match feature of git describe to assert that the git describe is really matching. In case we have the ambiguous issue shown in the table, we have in addition the commit hash that always allows a unambiguous identification. 

So both would work for me. 

We have on the pro side a reliable fail save consecutive version number established for years and on the contra side a bit of confusing with the similar git describe number and withe a hard to remember git command. 

Since we have already done the switch an broke the sorting on https://downloads.mixxx.org/snapshots/2.3/ I am heading towards taking the risk and drop the old count. 

What do you think?

**Comment by daschuer** [comment]
I have reconsidered it and and you are right, that it is not very reliable to create the mixxx.rc build number from git describe. 
I think we can keep the current state. I guess no one really cares about the number value, but it is possible to distinguish two mixxx.exe without starting Mixxx. 

So I think this can be closed.

The ambiguity issue remains when branching off a version.

In short, we will branch off a 2.4 branch. 
When we do it, we have on https://downloads.mixxx.org/snapshots/

main/2.4-alpha-5383-g73a5e66a53-win64.msi
2.4/2.4-alpha-5383-g73a5e66a53-win64.msi

without tagging it will becomes a bit confusing, the Mixxx version may not match the tag. 
main/2.4-alpha-5384-gff4275e78f-win64.msi
2.4/2.4-alpha-5384-g48362a3480-win64.msi
This is only a temporary issue, effecting only a single build, so we can accept it.  

After Tagging, everything is fine again: 
without tagging it will becomes a bit confusing like this this
main/2.5-alpha-win64.msi
2.4/2.4-beta-win64.msi

And than 
main/2.5-alpha-1-g5e78fff427-win64.msi
2.4/2.4-beta-1-ga348048362-win64.msi

**Comment by Holzhaus** [comment]
> without tagging it will becomes a bit confusing, the Mixxx version may not match the tag.
> main/2.4-alpha-5384-gff4275e78f-win64.msi
> 2.4/2.4-alpha-5384-g48362a3480-win64.msi
> This is only a temporary issue, effecting only a single build, so we can accept it.

But if the git commit count is the same, it's still the same source code, right? So it's not actually a problem.

**Comment by daschuer** [comment]
> But if the git commit count is the same, it's still the same source code, right? So it's not actually a problem.

No, the commit hash is different. This is because both version have a different Mixxx version, but that can be anything.

**Comment by Holzhaus** [comment]
> without tagging it will becomes a bit confusing, the Mixxx version may not match the tag.
> main/2.4-alpha-5384-gff4275e78f-win64.msi
> 2.4/2.4-alpha-5384-g48362a3480-win64.msi
> This is only a temporary issue, effecting only a single build, so we can accept it.

I don't understand how this can happen? How can the commit hash be different but the count the same for the same version? Is this caused by `--first-parent` with excludes half of the commits from a merge?

**Comment by daschuer** [comment]
I have just did a real test. Now I have this: 
2.3-beta-3842-g6778e8a2be
2.3-beta-3842-gf641f942d2
grafik

**Comment by Holzhaus** [comment]
Can you remove `--first-parent` and check again? Then all commits should be taken into account and the number should be higher.

**Comment by daschuer** [comment]
That was just the output from plain:
git describe

This is because both branches are independently.
The commit count since tag does not change for one branch if we branch out another.
(Unlike SVN)

**Comment by Holzhaus** [comment]
I cannot reproduce this. As expected, branching doesn't change the commit hash:

```
$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'upstream/main'.
$ git describe
2.4-alpha-5383-g73a5e66a53
$ git branch -c 2.4
$ git checkout 2.4
Switched to branch '2.4'
Your branch is up to date with 'upstream/main'.
$ git describe
2.4-alpha-5383-g73a5e66a53
```

**Comment by Holzhaus** [comment]
The first commit after branching should increment the project version in `CMakeLists` and change the prerelease string to `beta`, then that commit should be tagged with `2.4-beta`. If we do that, it doesn't matter if the commit count is the same, right?

**Comment by daschuer** [comment]
> As expected, branching doesn't change the commit hash.

Yes, in your test you have the 2.4 lable next to the main lable. 

My situation happens when we commit to both branches the same number of commit. 

If we do it as you describe, only a single build is in that confusing state. It is distinguishabld via the commit hash. So not really an issue. 
It can be more, if we find a last minute issue and decide to postpone the tagging. 

But even that is not a real Problem IMHO.

**Comment by Holzhaus** [comment]
@daschuer Is this PR still relevant or should we close this? The patched flag was added by #3817.

**Comment by daschuer** [comment]
This can be closed.

**Comment by daschuer** [comment]
Hey, I have used the famous close and comment button :-)

**Pull request closed without merging**
