### PR TITLE
Qickfix for a Mac OS crash. 

### PR DESCRIPTION
**Pull request by daschuer**
This is the attempt to fix the crash reported here: 
https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/2.2E3.20planning

### CODE REVIEW

**Comment by daschuer** [comment]
Unfortunatly the original reporter steve-_- is not able to build this PR at home. 
Can we merge it just to provide a binary from the CI? 

Can one else verify the crash?

**Comment by esbrandt** [comment]
> Can one else verify the crash?

Steps to reproduce?

**Comment by daschuer** [comment]
Install: http://downloads.mixxx.org/builds/master/release/mixxx-2.3.0-alpha-pre-master-git6786-release-macintel64.dmg and check if it is crashing on startup. 

If yes, run it from the command line with ./mixxx --developer and post the console output. 

This PR is an attempt to fix this crash.

**Comment by esbrandt** [comment]
http://downloads.mixxx.org/builds/master/release/mixxx-2.3.0-alpha-pre-master-git6786-release-macintel64.dmg crashes (see crash report).
Unfortunately i can not  test the patch in this PR, cause there is an build error, introduced in cb151a7ce4dda37446c62cc88b835d5ebecc4f73
```bash
...
Configuring TestSuite
ERROR:root:Unmet dependency: invalid literal for int() with base 10: 'False'
...
```

<details>
  <summary>Crash Report</summary>

```bash
Process:               Mixxx [49950]
Path:                  /Applications/mixxx-2.3.0-alpha-pre-master-git6786.app/Contents/MacOS/Mixxx
Identifier:            org.mixxx.mixxx
Version:               2.3.0-alpha-pre (2.3.0-alpha-pre)
Code Type:             X86-64 (Native)
Parent Process:        bash [44221]
Responsible:           Mixxx [49950]
User ID:               501

Date/Time:             2019-05-05 16:53:31.025 +0200
OS Version:            Mac OS X 10.14.3 (18D109)
Report Version:        12
Bridge OS Version:     3.3 (16P3133)
Anonymous UUID:        985EEDE6-A2CC-6462-A4E3-BDE00383F734

Sleep/Wake UUID:       8D78452D-DD90-4E91-B4F8-EEC37B6BFACA

Time Awake Since Boot: 1100000 seconds
Time Since Wake:       260 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [49950]

VM Regions Near 0x8:
--> 
    __TEXT                 000000010e493000-000000010eefd000 [ 10.4M] r-x/rwx SM=COW  /Applications/mixxx-2.3.0-alpha-pre-master-git6786.app/Contents/MacOS/Mixxx

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   QtGui                         	0x00000001104aced4 QOpenGLContext::shareGroup() const + 4
1   QtGui                         	0x000000011075898d QOpenGLFunctionsPrivateEx* QOpenGLMultiGroupSharedResource::value<QOpenGLFunctionsPrivateEx>(QOpenGLContext*) + 29
2   QtGui                         	0x0000000110757dc0 QOpenGLFunctions::initializeOpenGLFunctions() + 16
3   org.mixxx.mixxx               	0x000000010ea1a29e WaveformWidgetFactory::WaveformWidgetFactory() + 574

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff57ca13f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff57ca13f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff57ca13f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 4:: StatsManager
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   QtCore                        	0x000000010f4a308b QWaitConditionPrivate::wait(QDeadlineTimer) + 59
3   QtCore                        	0x000000010f4a2fec QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	0x000000010f4a2f74 QWaitCondition::wait(QMutex*, unsigned long) + 100
5   org.mixxx.mixxx               	0x000000010e9e5a3a StatsManager::run() + 170
6   libsystem_pthread.dylib       	0x00007fff57ca2305 _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff57ca526f _pthread_start + 70
8   libsystem_pthread.dylib       	0x00007fff57ca1415 thread_start + 13

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff57ca13f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff57ca13f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff57ca13f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 8:
0   libsystem_pthread.dylib       	0x00007fff57ca13f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff57ca13f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 10:
0   libsystem_pthread.dylib       	0x00007fff57ca13f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 11:
0   libsystem_pthread.dylib       	0x00007fff57ca13f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 12:
0   libsystem_pthread.dylib       	0x00007fff57ca13f8 start_wqthread + 0

Thread 13:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff57be817a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff57be86d0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2a85dfde __CFRunLoopServiceMachPort + 337
3   com.apple.CoreFoundation      	0x00007fff2a85d52d __CFRunLoopRun + 1654
4   com.apple.CoreFoundation      	0x00007fff2a85cc64 CFRunLoopRunSpecific + 463
5   com.apple.AppKit              	0x00007fff27db6f89 _NSEventThread + 160
6   libsystem_pthread.dylib       	0x00007fff57ca2305 _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff57ca526f _pthread_start + 70
8   libsystem_pthread.dylib       	0x00007fff57ca1415 thread_start + 13

Thread 14:: EngineWorkerScheduler
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   QtCore                        	0x000000010f4a308b QWaitConditionPrivate::wait(QDeadlineTimer) + 59
3   QtCore                        	0x000000010f4a2fec QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	0x000000010f4a2f74 QWaitCondition::wait(QMutex*, unsigned long) + 100
5   org.mixxx.mixxx               	0x000000010e6b17d8 EngineWorkerScheduler::run() + 456
6   ???                           	0x00007ff2d90692c8 0 + 140680999899848
7   ???                           	0xf00007ffec27ef55 0 + 17293831364862799701

Thread 15:: EngineSideChain
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   QtCore                        	0x000000010f4a308b QWaitConditionPrivate::wait(QDeadlineTimer) + 59
3   QtCore                        	0x000000010f4a2fec QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	0x000000010f4a2f74 QWaitCondition::wait(QMutex*, unsigned long) + 100
5   org.mixxx.mixxx               	0x000000010e6c5d2a EngineSideChain::run() + 522

Thread 16:
0   libsystem_kernel.dylib        	0x00007fff57be81ce semaphore_timedwait_trap + 10
1   libdispatch.dylib             	0x00007fff57a6142c _dispatch_sema4_timedwait + 76
2   libdispatch.dylib             	0x00007fff57a61b1d _dispatch_semaphore_wait_slow + 58
3   libdispatch.dylib             	0x00007fff57a6eb66 _dispatch_worker_thread + 328
4   libsystem_pthread.dylib       	0x00007fff57ca2305 _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff57ca526f _pthread_start + 70
6   libsystem_pthread.dylib       	0x00007fff57ca1415 thread_start + 13

Thread 17:: VinylControlProcessor
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   QtCore                        	0x000000010f4a308b QWaitConditionPrivate::wait(QDeadlineTimer) + 59
3   QtCore                        	0x000000010f4a2fec QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	0x000000010f4a2f74 QWaitCondition::wait(QMutex*, unsigned long) + 100
5   org.mixxx.mixxx               	0x000000010e9f2e61 VinylControlProcessor::run() + 1393

Thread 18:: CachingReaderWorker
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   QtCore                        	0x000000010f4a308b QWaitConditionPrivate::wait(QDeadlineTimer) + 59
3   QtCore                        	0x000000010f4a2fec QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	0x000000010f4a2f74 QWaitCondition::wait(QMutex*, unsigned long) + 100
5   QtCore                        	0x000000010f49f523 QSemaphore::acquire(int) + 83
6   org.mixxx.mixxx               	0x000000010e6286c8 CachingReaderWorker::run() + 792
7   ???                           	0x00007ff2d91e1de0 0 + 140681001442784
8   ???                           	0x000000000000001f 0 + 31

Thread 19:: CachingReaderWorker
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   QtCore                        	0x000000010f4a308b QWaitConditionPrivate::wait(QDeadlineTimer) + 59
3   QtCore                        	0x000000010f4a2fec QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	0x000000010f4a2f74 QWaitCondition::wait(QMutex*, unsigned long) + 100
5   QtCore                        	0x000000010f49f523 QSemaphore::acquire(int) + 83
6   org.mixxx.mixxx               	0x000000010e6286c8 CachingReaderWorker::run() + 792
7   ???                           	0x00007ff2dfa947f0 0 + 140681111226352

Thread 20:: CachingReaderWorker
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   QtCore                        	0x000000010f4a308b QWaitConditionPrivate::wait(QDeadlineTimer) + 59
3   QtCore                        	0x000000010f4a2fec QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	0x000000010f4a2f74 QWaitCondition::wait(QMutex*, unsigned long) + 100
5   QtCore                        	0x000000010f49f523 QSemaphore::acquire(int) + 83
6   org.mixxx.mixxx               	0x000000010e6286c8 CachingReaderWorker::run() + 792
7   ???                           	0x00007ff2dfccc4c0 0 + 140681113552064

Thread 21:: CachingReaderWorker
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   QtCore                        	0x000000010f4a308b QWaitConditionPrivate::wait(QDeadlineTimer) + 59
3   QtCore                        	0x000000010f4a2fec QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	0x000000010f4a2f74 QWaitCondition::wait(QMutex*, unsigned long) + 100
5   QtCore                        	0x000000010f49f523 QSemaphore::acquire(int) + 83
6   org.mixxx.mixxx               	0x000000010e6286c8 CachingReaderWorker::run() + 792
7   ???                           	0x00007ff2dff07ae0 0 + 140681115892448

Thread 22:: CachingReaderWorker
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   QtCore                        	0x000000010f4a308b QWaitConditionPrivate::wait(QDeadlineTimer) + 59
3   QtCore                        	0x000000010f4a2fec QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	0x000000010f4a2f74 QWaitCondition::wait(QMutex*, unsigned long) + 100
5   QtCore                        	0x000000010f49f523 QSemaphore::acquire(int) + 83
6   org.mixxx.mixxx               	0x000000010e6286c8 CachingReaderWorker::run() + 792
7   ???                           	0x00007ff2e0140160 0 + 140681118220640

Thread 23:: CachingReaderWorker
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   QtCore                        	0x000000010f4a308b QWaitConditionPrivate::wait(QDeadlineTimer) + 59
3   QtCore                        	0x000000010f4a2fec QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	0x000000010f4a2f74 QWaitCondition::wait(QMutex*, unsigned long) + 100
5   QtCore                        	0x000000010f49f523 QSemaphore::acquire(int) + 83
6   org.mixxx.mixxx               	0x000000010e6286c8 CachingReaderWorker::run() + 792
7   ???                           	0x00007ff2e02836b0 0 + 140681119545008

Thread 24:: CachingReaderWorker
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   QtCore                        	0x000000010f4a308b QWaitConditionPrivate::wait(QDeadlineTimer) + 59
3   QtCore                        	0x000000010f4a2fec QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	0x000000010f4a2f74 QWaitCondition::wait(QMutex*, unsigned long) + 100
5   QtCore                        	0x000000010f49f523 QSemaphore::acquire(int) + 83
6   org.mixxx.mixxx               	0x000000010e6286c8 CachingReaderWorker::run() + 792
7   ???                           	0x00007ff2e03c6a70 0 + 140681120868976

Thread 25:: CachingReaderWorker
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   QtCore                        	0x000000010f4a308b QWaitConditionPrivate::wait(QDeadlineTimer) + 59
3   QtCore                        	0x000000010f4a2fec QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	0x000000010f4a2f74 QWaitCondition::wait(QMutex*, unsigned long) + 100
5   QtCore                        	0x000000010f49f523 QSemaphore::acquire(int) + 83
6   org.mixxx.mixxx               	0x000000010e6286c8 CachingReaderWorker::run() + 792
7   ???                           	0x00007ff2e050de50 0 + 140681122209360

Thread 26:: CachingReaderWorker
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   QtCore                        	0x000000010f4a308b QWaitConditionPrivate::wait(QDeadlineTimer) + 59
3   QtCore                        	0x000000010f4a2fec QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	0x000000010f4a2f74 QWaitCondition::wait(QMutex*, unsigned long) + 100
5   QtCore                        	0x000000010f49f523 QSemaphore::acquire(int) + 83
6   org.mixxx.mixxx               	0x000000010e6286c8 CachingReaderWorker::run() + 792
7   ???                           	0x00007ff2e0651230 0 + 140681123533360

Thread 27:: LibraryScanner 1
0   libsystem_kernel.dylib        	0x00007fff57bf02ee poll + 10
1   QtCore                        	0x000000010f6cb030 qt_safe_poll(pollfd*, unsigned int, timespec const*) + 576
2   QtCore                        	0x000000010f6cc8a9 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 873
3   QtCore                        	0x000000010f66f38e QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 430
4   QtCore                        	0x000000010f499a0c QThread::exec() + 140
5   org.mixxx.mixxx               	0x000000010e7fee20 LibraryScanner::run() + 624
6   libsystem_pthread.dylib       	0x00007fff57ca2305 _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff57ca526f _pthread_start + 70
8   libsystem_pthread.dylib       	0x00007fff57ca1415 thread_start + 13

Thread 28:: BrowseThread
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   QtCore                        	0x000000010f4a308b QWaitConditionPrivate::wait(QDeadlineTimer) + 59
3   QtCore                        	0x000000010f4a2fec QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	0x000000010f4a2f74 QWaitCondition::wait(QMutex*, unsigned long) + 100
5   org.mixxx.mixxx               	0x000000010e7250c2 BrowseThread::run() + 178
6   libsystem_pthread.dylib       	0x00007fff57ca2305 _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff57ca526f _pthread_start + 70
8   libsystem_pthread.dylib       	0x00007fff57ca1415 thread_start + 13

Thread 29:: AnalyzerThread
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   libc++.1.dylib                	0x00007fff55183bda std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   org.mixxx.mixxx               	0x000000010e9ec767 WorkerThread::waitUntilWorkItemsFetched() + 119

Thread 30:: AnalyzerThread
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   libc++.1.dylib                	0x00007fff55183bda std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   org.mixxx.mixxx               	0x000000010e9ec767 WorkerThread::waitUntilWorkItemsFetched() + 119

Thread 31:: AnalyzerThread
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   libc++.1.dylib                	0x00007fff55183bda std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   org.mixxx.mixxx               	0x000000010e9ec767 WorkerThread::waitUntilWorkItemsFetched() + 119

Thread 32:: AnalyzerThread
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   libc++.1.dylib                	0x00007fff55183bda std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   org.mixxx.mixxx               	0x000000010e9ec767 WorkerThread::waitUntilWorkItemsFetched() + 119

Thread 33:: AnalyzerThread
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   libc++.1.dylib                	0x00007fff55183bda std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   org.mixxx.mixxx               	0x000000010e9ec767 WorkerThread::waitUntilWorkItemsFetched() + 119

Thread 34:: AnalyzerThread
0   libsystem_kernel.dylib        	0x00007fff57beb7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff57ca5593 _pthread_cond_wait + 724
2   libc++.1.dylib                	0x00007fff55183bda std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   org.mixxx.mixxx               	0x000000010e9ec767 WorkerThread::waitUntilWorkItemsFetched() + 119

Thread 35:: Controller
0   libsystem_malloc.dylib        	0x00007fff57c5f568 tiny_malloc_from_free_list + 641
1   libsystem_malloc.dylib        	0x00007fff57c5ed71 tiny_malloc_should_clear + 273
2   libsystem_malloc.dylib        	0x00007fff57c5ebac szone_malloc_should_clear + 66
3   libsystem_malloc.dylib        	0x00007fff57c5d807 malloc_zone_malloc + 103
4   libsystem_malloc.dylib        	0x00007fff57c5d783 malloc + 24
5   libc++abi.dylib               	0x00007fff551d4f48 operator new(unsigned long) + 40
6   QtXml                         	0x00000001114b49d3 QDomDocumentPrivate::createElement(QString const&) + 51
7   QtXml                         	0x00000001114b6f64 QDomHandler::startElement(QString const&, QString const&, QString const&, QXmlAttributes const&) + 52
8   QtXml                         	0x00000001114c3a8d QXmlSimpleReaderPrivate::processElementEmptyTag() + 1597
9   QtXml                         	0x00000001114bdb36 QXmlSimpleReaderPrivate::parseElement() + 870
10  QtXml                         	0x00000001114c2aa9 QXmlSimpleReaderPrivate::parseContent() + 2297
11  QtXml                         	0x00000001114bdaf5 QXmlSimpleReaderPrivate::parseElement() + 805
12  QtXml                         	0x00000001114c2aa9 QXmlSimpleReaderPrivate::parseContent() + 2297
13  QtXml                         	0x00000001114bdaf5 QXmlSimpleReaderPrivate::parseElement() + 805
14  QtXml                         	0x00000001114c2aa9 QXmlSimpleReaderPrivate::parseContent() + 2297
15  QtXml                         	0x00000001114bdaf5 QXmlSimpleReaderPrivate::parseElement() + 805
16  QtXml                         	0x00000001114c2aa9 QXmlSimpleReaderPrivate::parseContent() + 2297
17  QtXml                         	0x00000001114bdaf5 QXmlSimpleReaderPrivate::parseElement() + 805
18  QtXml                         	0x00000001114c2aa9 QXmlSimpleReaderPrivate::parseContent() + 2297
19  QtXml                         	0x00000001114bdaf5 QXmlSimpleReaderPrivate::parseElement() + 805
20  QtXml                         	0x00000001114bc66c QXmlSimpleReaderPrivate::parseBeginOrContinue(int, bool) + 60
21  QtXml                         	0x00000001114b475a QDomDocumentPrivate::setContent(QXmlInputSource*, QXmlReader*, QXmlSimpleReader*, QString*, int*, int*) + 778
22  QtXml                         	0x00000001114b5e8a QDomDocument::setContent(QIODevice*, bool, QString*, int*, int*) + 138
23  org.mixxx.mixxx               	0x000000010e9ece7d XmlParse::openXMLFile(QString const&, QString const&) + 125
24  ???                           	0x00007ff2e1b02500 0 + 140681145230592
25  ???                           	0xc00007ff0000007c 0 + 13835066847080218748

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00000000ffffffff  rbx: 0x00007ffee176c420  rcx: 0x0000000000000008  rdx: 0x00000000000f6b60
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x00007ffee176c340  rsp: 0x00007ffee176c340
   r8: 0x0000000000000000   r9: 0x00007ff2d916e060  r10: 0x00007ffee176ca60  r11: 0x0000000110757db0
  r12: 0x00007ff2e1827f20  r13: 0x00007ff2e1824bd0  r14: 0x0000000000000000  r15: 0x00007ffee176c8b0
  rip: 0x00000001104aced4  rfl: 0x0000000000010206  cr2: 0x0000000000000008
  
Logical CPU:     2
Error Code:      0x00000004
Trap Number:     14
...
```
</details>

**Comment by daschuer** [comment]
Thank you for Testing, and confirming the crash.  

> What is the issue with Unfortunately i can not test the patch in this PR, cause there is an build error, introduced in cb151a7

Do you have an idea to fix this, I can't reproduce the issue?  This PR is against 2.2 so it should build anyway. 

What is your 
./mixxx --developer 
output?

**Comment by daschuer** [comment]
```
ERROR:root:Unmet dependency: invalid literal for int() with base 10: 'False'
``` 

is a python error .. https://github.com/mixxxdj/mixxx/pull/2054/files does not touch Python code ... 
So I guess there must be something else wrong.

**Comment by uklotzde** [comment]
https://github.com/mixxxdj/mixxx/commit/6fcfdc98bfe73b6d27d38ae77e53ae5ca229d339 contains Python code. Consider verifying that `compiler_major_version` is determined correctly.

The CI build was successful.

**Comment by uklotzde** [comment]
I will disable the code path for Clang, because Clang 8.0.0 reports "4.2.1" (for GCC compatibility).

**Comment by foss-** [comment]
cross linking launchbar bug: https://bugs.launchpad.net/mixxx/+bug/1828019

**Comment by uklotzde** [comment]
LGTM. Let's give it a try.

**Pull request merged**
