### PR TITLE
Sync track metadata: Pass parameters explicitly

### PR DESCRIPTION
**Pull request by uklotzde**
Another preliminary PR to improve testability, i.e. do not rely on side-effects when updating/importing and exporting track metadata.

### CODE REVIEW

**Comment by uklotzde** [comment]
Force pushed after renaming the type. This could be used not only for exporting metadata.

**Comment by uklotzde** [comment]
Picked some more low hanging fruits in `SoundSourceProxy`.

**Comment by uklotzde** [comment]
If you want me to provide additional tests then please consider merging these prerequisites.

**Review by ywwg — APPROVED** [review]
lgtm

**Comment by ywwg** [comment]
(you may merge this yourself in case there are any other minor tweaks.)

**Comment by uklotzde** [comment]
Merging now. Otherwise I would not able to write a regression for an upcoming PR.

Splitting into smaller PRs was requested. But if I have to wait days before continuing this doesn't work for me.

**Pull request merged**
