### PR TITLE
Electrix Tweaker mapping update

### PR DESCRIPTION
**Pull request by Be-ing**
Separate top shift button from shift buttons in lower button grids to make room for gain controls. See http://mixxx.org/wiki/doku.php/electrix_tweaker#top_shift_layer for description.

### CODE REVIEW

**Comment by daschuer** [comment]
Is there one on the forum to verify this or should we just merge it without test?

**Comment by ywwg** [comment]
In general I've been merging controller updates without question -- often the developer is the only one with the controller anyway.  If you want to ask the forum, ok, but merging is also ok.

**Comment by Be-ing** [comment]
Only one other user has said anything about the mapping on the forum and that was back in early June. The mapping has changed a lot since then and I haven't gotten any feedback.

> In general I've been merging controller updates without question -- often the developer is the only one with the controller anyway. If you want to ask the forum, ok, but merging is also ok.

I do not think this is a good idea. Having the controller is only necessary for verifying that it works. Mappings should be reviewed for code quality and style, which I've been doing lately. One can look at a picture of a controller, read the description, and judge whether the mapping makes sense.

**Comment by ywwg** [comment]
I barely know javascript, and our scripts are like the Wild West as RJ put it.  There's no consistency in naming, tab style, organization, or anything.  That's something we can work on, and if someone wants to do a javascript review that's ok, but I don't enforce it.

**Comment by Be-ing** [comment]
I'm no JavaScript expert either, but I can still spot some ways scripts could be better. I'm happy to continue reviewing mappings. All mappings should be documented on the wiki too, which helps with review.

**Comment by illuusio** [comment]
Hmm.. should we have some kind of incubator project for these mappings before they hit to main repo? More lease commiting and review and then when they 'ready' then hit to main Mixxx? I know javascript so I can review this.

**Comment by illuusio** [comment]
Let's start with jshint problems (these are basic but they don't follow Ecmascript specfication) and this just first 20% of problems:
Electrix-Tweaker-scripts.js: line 4, col 47, Missing semicolon.
Electrix-Tweaker-scripts.js: line 6, col 39, Missing semicolon.
Electrix-Tweaker-scripts.js: line 9, col 34, Missing semicolon.
Electrix-Tweaker-scripts.js: line 12, col 113, Missing semicolon.
Electrix-Tweaker-scripts.js: line 136, col 2, Missing semicolon.
Electrix-Tweaker-scripts.js: line 138, col 45, ['blue'] is better written in dot notation.
Electrix-Tweaker-scripts.js: line 139, col 45, ['blue'] is better written in dot notation.
Electrix-Tweaker-scripts.js: line 140, col 45, ['magenta'] is better written in dot notation.
Electrix-Tweaker-scripts.js: line 141, col 45, ['magenta'] is better written in dot notation.
Electrix-Tweaker-scripts.js: line 142, col 2, Missing semicolon.
Electrix-Tweaker-scripts.js: line 144, col 31, ['cyan'] is better written in dot notation.
Electrix-Tweaker-scripts.js: line 145, col 31, ['green'] is better written in dot notation.
Electrix-Tweaker-scripts.js: line 146, col 31, ['red'] is better written in dot notation.
Electrix-Tweaker-scripts.js: line 147, col 31, ['white'] is better written in dot notation.
Electrix-Tweaker-scripts.js: line 148, col 2, Missing semicolon.
Electrix-Tweaker-scripts.js: line 185, col 2, Missing semicolon.
Electrix-Tweaker-scripts.js: line 186, col 80, Missing semicolon.
Electrix-Tweaker-scripts.js: line 187, col 80, Missing semicolon.
Electrix-Tweaker-scripts.js: line 189, col 90, Missing semicolon.
Electrix-Tweaker-scripts.js: line 190, col 97, Missing semicolon.
Electrix-Tweaker-scripts.js: line 239, col 2, Missing semicolon.
Electrix-Tweaker-scripts.js: line 240, col 78, Missing semicolon.
Electrix-Tweaker-scripts.js: line 241, col 78, Missing semicolon.
Electrix-Tweaker-scripts.js: line 243, col 30, Missing semicolon.
Electrix-Tweaker-scripts.js: line 244, col 33, Missing semicolon.
Electrix-Tweaker-scripts.js: line 245, col 113, Missing semicolon.
Electrix-Tweaker-scripts.js: line 246, col 80, Missing semicolon.
Electrix-Tweaker-scripts.js: line 247, col 104, Missing semicolon.
Electrix-Tweaker-scripts.js: line 248, col 100, Missing semicolon.
Electrix-Tweaker-scripts.js: line 249, col 96, Missing semicolon.
Electrix-Tweaker-scripts.js: line 250, col 112, Missing semicolon.
Electrix-Tweaker-scripts.js: line 251, col 113, Missing semicolon.
Electrix-Tweaker-scripts.js: line 252, col 98, Missing semicolon.
Electrix-Tweaker-scripts.js: line 253, col 102, Missing semicolon.
Electrix-Tweaker-scripts.js: line 254, col 131, Missing semicolon.
Electrix-Tweaker-scripts.js: line 255, col 129, Missing semicolon.
Electrix-Tweaker-scripts.js: line 256, col 106, Missing semicolon.
Electrix-Tweaker-scripts.js: line 257, col 106, Missing semicolon.
Electrix-Tweaker-scripts.js: line 259, col 40, Don't use extra leading zeros '00'.
Electrix-Tweaker-scripts.js: line 259, col 55, Missing semicolon.
Electrix-Tweaker-scripts.js: line 261, col 10, Don't use extra leading zeros '00'.
Electrix-Tweaker-scripts.js: line 261, col 31, Don't use extra leading zeros '00'.
Electrix-Tweaker-scripts.js: line 261, col 39, Don't use extra leading zeros '00'.
Electrix-Tweaker-scripts.js: line 261, col 47, Don't use extra leading zeros '00'.
Electrix-Tweaker-scripts.js: line 261, col 55, Don't use extra leading zeros '00'.
Electrix-Tweaker-scripts.js: line 261, col 63, Don't use extra leading zeros '00'.
Electrix-Tweaker-scripts.js: line 261, col 71, Don't use extra leading zeros '00'.
Electrix-Tweaker-scripts.js: line 261, col 79, Don't use extra leading zeros '00'.
Electrix-Tweaker-scripts.js: line 261, col 87, Don't use extra leading zeros '00'.
Electrix-Tweaker-scripts.js: line 261, col 95, Don't use extra leading zeros '00'.

**Comment by Be-ing** [comment]
Those are all code style issues. We have no agreed upon style conventions for JavaScript.

**Comment by illuusio** [comment]
Hmm.. when bad code is the issue of coding style?

**Comment by Be-ing** [comment]
I'm planning a major refactor of this code which will take me a while. I'll rewrite it to make JSHint happy then. Until then, I think this should be merged as-is for 1.12. It works well as intended.

**Pull request merged**
