### PR TITLE
LateNight skin: small decks for big library view

### PR DESCRIPTION
**Pull request by bestdani**

### CODE REVIEW

**Comment by ywwg** [comment]
This is a nice idea.  I see there are some doubled border lines here and there, can you try to clean those up?  Also having single pixel lines everywhere makes the decks sort of run in to each other.  See if you can think of some ways to add whitespace between them or use some varying background colors to add more contrast

**Comment by Be-ing** [comment]
Yeah, a little bit of blank space between the decks would help. See this screenshot of Traktor: http://www.digitaldjtips.com/wp-content/uploads/2014/10/browser-mode-traktor-pro-2.png

IMO this should be targeted at 1.12 rather than master.

**Comment by ferranpujolcamins** [comment]
Nice! Some comments:

I suggest to make the background of the tempo section the same colour it is in the full decks.

I would also replace the controls next to the waveform for a play/pause button (or at least add the button elsewhere). This way if "Don't load tracks into a playing deck" is activated, the user can pause a track from there and load a new track.

Another idea is to put a mini fader and a mini vumeter in the middle, next to each deck. There's room for it and would allow the user to see at a glance which decks are live

Finally I would also make the title and artist text a little bit smaller.

**Comment by ywwg** [comment]
Please do not post links to other DJ software as examples.  While there's some inevitable similarity between DJ software programs, I don't want to just copy what other people are doing.

**Comment by ywwg** [comment]
> IMO this should be targeted at 1.12 rather than master.

Release manager hat:  no, master is the correct target.

**Comment by Be-ing** [comment]
>Please do not post links to other DJ software as examples. While there's some inevitable similarity between DJ software programs, I don't want to just copy what other people are doing.

Neither do I. But I do think we should be looking at other software for ideas and thinking critically about whether and how to incorporate them into Mixxx.

> Release manager hat: no, master is the correct target.

I think it is reasonable to hold off on releasing this until every skin has this feature (and I don't plan on putting the work into Deere and Shade to make that happen before 1.12).

**Comment by ywwg** [comment]
> Neither do I. But I do think we should be looking at other software for ideas and thinking critically about whether and how to incorporate them into Mixxx.

I just want to be very careful about saying things like "we should do it like Traktor" because we don't want to be accused of copying.  I like that our skins are home-grown and not just knock-offs, and even if someone only looks at the screenshot for reference, there's a temptation to include other elements.

**Comment by daschuer** [comment]
Hi @bestdani, thank you for working on this.

It would be nice if we can reduce the hight of the small decks some more. 
What about combine first and second row by reducing the font size?

**Comment by Be-ing** [comment]
@bestdani, do you plan to address the comments above so this can be included in Mixxx 2.1?

**Comment by bestdani** [comment]
I can't promise anything, but I'll try to find time for this.

2016-01-19 4:53 GMT+01:00 Be <notifications@github.com>:

**Pull request closed without merging**
