### PR TITLE
Download cleanup

### PR DESCRIPTION
**Pull request by daschuer**
This adds a manual workflow that deletes files from downloads.mixxx.org 
This deletes only a few files for testing. In case this is successful. I will add another PR that removes all obsolete files to free up space.

### CODE REVIEW

**Comment by ronso0** [comment]
FWIW http://downloads.mixxx.org/snapshots/1.12/debug/ and http://downloads.mixxx.org/snapshots/2.0/debug/ _seem_ identical. Is one of them just a symlink?
Deleting one of them (1.12?) would already free ~3.5 GB

**Comment by daschuer** [comment]
Probably is is a symlink. We need to be careful to not delete files in both we want to keep in one. 
But do we need 2.0 snapshots? Probably we can remove altogether. 

Let's first check if the manual workflow does what it should.

**Comment by ronso0** [comment]
Shall we merge this now?

**Comment by daschuer** [comment]
Yes, if you don't spot and obvious issue.

**Comment by ronso0** [comment]
Well, I don't because I'm not familiar with the runners syntax.
"LGTM" since it matches the syntax in the Build runner :man_shrugging:

**Pull request merged**
