### PR TITLE
Use QCollator for sort library.

### PR DESCRIPTION
**Pull request by daschuer**
This speeds up library access, because we don't need to make a deep copy when calling toLower().

### CODE REVIEW

**Comment by uklotzde** [comment]
So many unknown goodies! LGTM :+1:

Should we use the same technique in BaseSqlTableModel? Maybe we could even provide our own, reusable StringCollator class in util/string.h that uses a case-insensitive QCollator internally and provides overloaded methods for `const QChar*` and `const QString&`?

**Comment by uklotzde** [comment]
I've already prepared something, PR will follow in a moment...

**Comment by uklotzde** [comment]
https://github.com/daschuer/mixxx/pull/34

**Comment by daschuer** [comment]
Thank you :-)

**Comment by uklotzde** [comment]
If the CI build succeeds we should merge this nice improvement.

**Comment by daschuer** [comment]
Thanks.

**Pull request merged**
