### PR TITLE
engine/cuecontrol: Fix precision loss on hotcueGoto

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
LGTM waiting for CI.

**Comment by Holzhaus** [comment]
If we had `-Wfloat-conversion`, we would have noticed this easily:

```
src/engine/controls/cuecontrol.cpp: In member function ‘void CueControl::hotcueGoto(HotcueControl*, double)’:
src/engine/controls/cuecontrol.cpp:708:41: warning: conversion from ‘double’ to ‘int’ may change value [-Wfloat-conversion]
  708 |         int position = pCue->getPosition();
      |                        ~~~~~~~~~~~~~~~~~^~
src/engine/controls/cuecontrol.cpp: In member function ‘void CueControl::hotcueGotoAndStop(HotcueControl*, double)’:
src/engine/controls/cuecontrol.cpp:729:41: warning: conversion from ‘double’ to ‘int’ may change value [-Wfloat-conversion]
  729 |         int position = pCue->getPosition();
      |                        ~~~~~~~~~~~~~~~~~^~
src/engine/controls/cuecontrol.cpp: In member function ‘void CueControl::hotcueGotoAndPlay(HotcueControl*, double)’:
src/engine/controls/cuecontrol.cpp:752:41: warning: conversion from ‘double’ to ‘int’ may change value [-Wfloat-conversion]
  752 |         int position = pCue->getPosition();
      |                        ~~~~~~~~~~~~~~~~~^~
```

**Comment by daschuer** [comment]
> If we had -Wfloat-conversion, we would have noticed this easily:

due to out double typed control system that will alert everywhere. But maybe it is worth a try.

**Comment by ywwg** [comment]
LGTM shipit

**Comment by uklotzde** [comment]
CI will not succeed. LGTM

**Comment by uklotzde** [comment]
Using `auto` would also have prevented these errors. Redundant type specifications are a source of error.

**Pull request merged**
