### PR TITLE
Crate filter tests

### PR DESCRIPTION
**Pull request by gramanas**
Following PR #1263 here are ~~four~~ five tests for the crate filters.
The code is commented and what is happening should be pretty self explanatory.

### CODE REVIEW

**Comment by Be-ing** [comment]
Looks good so far. I thought the tests would have to clean up the database at the end of each test adding to the DB, but ~MixxxTest deletes all the temporary test files between each test run, so that isn't necessary.

It would be good to add a test combining crate filters like "crate:testCrate1 crate:testCrate2" and "crate:testCrate1 -crate:testCrate2". You can put these in the same test so you don't have to duplicate setting up the test crates and adding the test tracks.

**Comment by Be-ing** [comment]
LGTM. @uklotzde any comments?

**Comment by uklotzde** [comment]
LGTM. It would be possible to reduce the amount of redundant code among the very similar setup procedures for different tests. Just a minor remark, nothing that prevents merging this PR.

Thanks for completing the new feature with appropriate tests, Anast!

**Comment by daschuer** [comment]
Thank you all working on this!

**Pull request merged**
