### PR TITLE
Waveform: fix shifted pixmap markers with odd scale factors

### PR DESCRIPTION
**Pull request by ronso0**
follow-up for https://github.com/mixxxdj/mixxx/pull/3936 to fix
https://bugs.launchpad.net/mixxx/+bug/1917253

Now the pixmap waveform markers in Deere are 
* correctly scaled
* in the correct position

For testing set an non-int scale factor like
`export QT_SCREEN_SCALE_FACTORS=1.37`

### CODE REVIEW

**Review by uklotzde — COMMENTED** [review]
Thanks for adding those really helpful and important comments!

What is the difference between or the relation of scaleFactor() and getDevicePixelRatio()? Do we need to take both into account, i.e. multiply them? There is more code that uses WImageStore::getImage() with scaleFactor() and not getDevicePixelRatio().

**Comment by ronso0** [comment]
As far a sI can tell `getDevicePixelRatio()` is reading the Qt scale factors, which are set either automatically by the OS or manually by the user.

`scaleFactor` --just guessing here since I'm too lazy to browse the git history-- seems to be a hmm..residue of the Mixxx-internal scaling we had in 2.1(?). See [dlgprefinterface.cpp#L184](https://github.com/mixxxdj/mixxx/blob/2.3/src/preferences/dialog/dlgprefinterface.cpp#L184). It's still read from the config but not requested anywhere. Neither did I find a place where it would be set to anything else than `1.0`, nor a place in the GUI that's not scaled correctly (except the cue menu popup https://bugs.launchpad.net/mixxx/+bug/1930751)
About time to clean that up.
`getDevicePixelRatioF()` seems to be used in the relevant places, for example https://github.com/mixxxdj/mixxx/blob/2.3/src/library/coverartdelegate.cpp#L128-L129

**Review by uklotzde — APPROVED** [review]
I was just curious to see where scaleFactor() is used. It is not documented. Let's ignore this for now and simply only fix what is actually broken.

Thank you for your efforts! LGTM

**Comment by ronso0** [comment]
sure. cleaning up the internal scaling should happen for 2.4, it makes the code more complex than necessary.

**Comment by daschuer** [comment]
Did you try to uncomment the GUI for the old scaleing? By luck it still works.

On the other hand I have the impression we just need a few lines of code to allow to set the QT_SCREEN_SCALE_FACTORS from the GUI and require a restart afterwards.Than we can remove all internal scaling.

We loose the benefit of on the fly scaling and scaling factors lower than 1. 

But I think we can effort it. 

What do you think?

**Comment by ronso0** [comment]
> On the other hand I have the impression we just need a few lines of code to allow to set the QT_SCREEN_SCALE_FACTORS from the GUI and require a restart afterwards.Than we can remove all internal scaling.

Imo that's the way to go now that almost all scalong issues are resolved. internal scaling was an intermediate solution but we must please not reactivate it. just to much trouble composted to Qt scaling.

changing the scaling on the fly is not required IMO, that's mostly a one-time adjustment, isn't it?

**Comment by ronso0** [comment]
that said I have no intention to test the old scaling, and I dont see a use case for it as long as Qt scaling works. do you?

**Comment by Holzhaus** [comment]
May this be a regression from this PR: https://bugs.launchpad.net/mixxx/+bug/1930968 ?

**Comment by ronso0** [comment]
maybe. we don't know for sure if the song was broken before on macOS with custom Qt scaling, or if this is a regression on macOS 11.4 only

**Comment by ronso0** [comment]
to revert the fix for macOS I'll set the devicePixelRatio to 1 for macOS only

**Comment by ronso0** [comment]
hmm yeah I think we would have gotten reports about broken markers because some of the folks asking about unscaled Mixxx on Big Sur sure used odd factors with the Qt advice they got

**Pull request merged**
