### PR TITLE
Add a donate button to README.md.

### PR DESCRIPTION
**Pull request by rryan**
This is pretty low-key. Thoughts?

### CODE REVIEW

**Comment by Holzhaus** [comment]
What about adding a github sponsor button instead? I think that is a bit more prominent. https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

We can use the custom URL option to link to PayPal.

**Comment by rryan** [comment]
Here's what the Sponsor button would look like for comparison: https://github.com/rryan/mixxx

Personally it feels more hidden to me, but I guess if the Sponsor button catches on them people will come to expect it at the top of the page.

**Comment by rryan** [comment]
on second thought, ¿porque no los dos?

**Comment by ronso0** [comment]
> on second thought, ¿porque no los dos?

:+1:  Exactly, let's use both.

**Comment by ywwg** [comment]
lgtm!

**Pull request merged**
