### PR TITLE
Delete usage of deprecated QDesktopWidget

### PR DESCRIPTION
**Pull request by uklotzde**
Please also test with Qt <5.14! I have tested the compatibility workaround on Qt 5.14.

- Add a helper function for obtaining the screen of a widget
- Use the actual screen of a widget instead of QDesktopWidget
- Delete dead code

### CODE REVIEW

**Review by Be-ing — APPROVED** [review]

**Comment by uklotzde** [comment]
Not yet possible. This solution requires Qt 5.14.

**Comment by Be-ing** [comment]
What about this requires Qt 5.14? This is removing unused code...

**Comment by uklotzde** [comment]
We need to replace it with QWidget::screen() which requires Qt 5.14. Unfortunately, the new workaround in #3215 is cumbersome. But it seems to work.

**Comment by uklotzde** [comment]
It was not possible to reopen this PR after a force push.

**Pull request closed without merging**
