### PR TITLE
lp1695766: Use an in-memory database to speed up library tests

### PR DESCRIPTION
**Pull request by uklotzde**
Simple and with minimal code changes. Hopefully this helps.
https://bugs.launchpad.net/mixxx/+bug/1695766

### CODE REVIEW

**Comment by Pegasus-RPG** [comment]
Nice! How much RAM will the in-memory DB require though? And do we have any evidence if it is any faster?

**Comment by uklotzde** [comment]
Memory will not be an issue with an empty initial database containing just a few records written by tests before it is thrown away.
Local speed-up: 40 s -> 20 s

**Comment by uklotzde** [comment]
No actual reduction of CI build times observed. It doesn't seem the tests that take so much time.

Nevertheless a 2x speed-up during local execution more than justifies this approach.

**Comment by Pegasus-RPG** [comment]
Agree, still worthwhile to have. LGTM.

**Comment by daschuer** [comment]
LGTM

**Pull request merged**
