### PR TITLE
Added last time played column

### PR DESCRIPTION
**Pull request by zivlakmilos**
Add last time played column to library.
Column shows when last time track is played, or if never played nothing.

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you very much for working on this. The new column is a great help to find a suitable successor track. 

Related Bug: 
https://bugs.launchpad.net/mixxx/+bug/1490818

However, I am afraid the implementation does not match, my use case.
(Sorry for putting in my thoughts that late) 
 
Apart from the usage at gigs, I use Mixxx to prepare play-lists or pre listen tracks at home. 
I usually delete the History play lists from old at home sessions to keep the history tree and the played counter clean. I consider a track as played, only because it was played in front of an audience.  

I would like to use the last played column to avoid to bore the audience with short repeat cycles of the same track. This applies fro resident DJ or regular radio shows. 

On the other hand I could also think of a use case for using the last played column to find the cool track from my preview session when preparing the gig. 
This can be already done by watching the history playlist of the preview session. 

What is your use-case?

**Comment by daschuer** [comment]
I think the last played column should be created on the fly by the history playlists.
This would allow to update the last played value when a history- (setlog-) playlist is deleted. 

A similar problem was already solved for the "Add Random" feature of Auto DJ. 
Mixxx keeps a temporary table, including such a last played column.
This table is prepared here: 
https://github.com/mixxxdj/mixxx/blob/94e9c0c93d985119ffb6403d774882c02c4ce6a4/src/library/dao/autodjcratesdao.cpp#L43

updateLastPlayedDateTime() keeps track of the last played time: 
https://github.com/mixxxdj/mixxx/blob/94e9c0c93d985119ffb6403d774882c02c4ce6a4/src/library/dao/autodjcratesdao.cpp#L346

So it looks like we need to move the last played column to dedicated temporary table and reuse it for AutoDJCratesDAO and for all other track tables. 

Maybe @uklotzde and @rryan, can give some additional hints, how it can fit the best to the current library layout.

**Comment by daschuer** [comment]
Does any of the other external libraries add "last played" infos? 
The file system provides a last accessed info of a file. Could this a useful information for a DJ?

**Comment by zivlakmilos** [comment]
Oh, ok, sorry. I Fix that. I not a DJ actually I just do programming and robotics, and playling piano, but not DJ. Sorry, I fix it for couple of days.

**Comment by zivlakmilos** [comment]
I don't see that in auto DJ.

**Comment by daschuer** [comment]
> I don't see that in auto DJ.

What don't you see in auto DJ? 

Do you already have a plan how the database schema should be changed? 
I think it requires some refactoring in AutoDJCratesDAO.

**Comment by zivlakmilos** [comment]
I don't see last time played column in AtuoDJCreatedDAO.
No, I don't ave any idea jet. I must to study code for a while.
I am sorry. My english is realy bad.

**Comment by zivlakmilos** [comment]
We can create table history with data when song last time played and id of the track. Then we can filter table with that id for the track and use most recent date. And we have options to delete last record or all records with specific date. Meybi this similar table exises, but I don't see it.
Is this Ok?

**Comment by Be-ing** [comment]
This pull request has not been updated in years so I am closing it to reduce the clutter of open PRs. If you solve the merge conflicts, respond to the review comments above, and would like to have it merged in the future, please reopen it.

**Pull request closed without merging**
