### PR TITLE
Verify the CMAKE_PREFIX_PATH set by the vcpkg.cmake toolchain file

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
I just tested this PR on Win11 with VS2022 and it works as intended!

**Comment by daschuer** [comment]
Thank you for testing.

**Comment by daschuer** [comment]
Can someone merge this? Chandrashekar Iyer at Zulip has the related issue.

**Review by Swiftb0y — APPROVED** [review]
Seems like a viable workaround.

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
