### PR TITLE
Fix some warnings

### PR DESCRIPTION
**Pull request by Holzhaus**
This fixes some of the warnings that popped up while testing my CMake branch ~~with MSVC on Appveyor~~.

### CODE REVIEW

**Comment by Be-ing** [comment]
Changes to stable branches should _only_ be done to fix bugs that affect real world use of Mixxx. Cleaning code is usually safe, but there is always a risk for regression which is unnecessary on a stable branch. I have retargeted this to master.

**Comment by daschuer** [comment]
LGTM. Thank you.

**Comment by uklotzde** [comment]
The GCC build for Xenial build on Travis fails: https://travis-ci.org/mixxxdj/mixxx/jobs/600910492

```
[MOC] src/preferences/dialog/dlgprefautodj.h

[CXX] lin64_build/src/preferences/dialog/moc_dlgprefautodj.cc

In file included from src/preferences/dialog/dlgprefvinyl.cpp:30:0:

src/preferences/dialog/dlgprefvinyl.cpp: In member function ‘void DlgPrefVinyl::VinylTypeSlotApply()’:

src/util/platform.h:34:32: error: expected primary-expression before ‘__attribute__’

 #define M_FALLTHROUGH_INTENDED __attribute__ ((fallthrough));

                                ^

src/preferences/dialog/dlgprefvinyl.cpp:352:9: note: in expansion of macro ‘M_FALLTHROUGH_INTENDED’

         M_FALLTHROUGH_INTENDED;

         ^

src/util/platform.h:34:32: error: expected primary-expression before ‘__attribute__’

 #define M_FALLTHROUGH_INTENDED __attribute__ ((fallthrough));

                                ^

src/preferences/dialog/dlgprefvinyl.cpp:359:9: note: in expansion of macro ‘M_FALLTHROUGH_INTENDED’

         M_FALLTHROUGH_INTENDED;

         ^

src/util/platform.h:34:32: error: expected primary-expression before ‘__attribute__’

 #define M_FALLTHROUGH_INTENDED __attribute__ ((fallthrough));

                                ^

src/preferences/dialog/dlgprefvinyl.cpp:366:9: note: in expansion of macro ‘M_FALLTHROUGH_INTENDED’

         M_FALLTHROUGH_INTENDED;

         ^

[MOC] src/preferences/dialog/dlgprefbeats.h

scons: *** [lin64_build/src/preferences/dialog/dlgprefvinyl.o] Error 1

scons: building terminated because of errors.

The command "scons $COMMON_FLAGS $EXTRA_FLAGS" failed and exited with 2 during .

Your build has been stopped.
```

**Comment by daschuer** [comment]
Ups, I should have notice this before merge, sorry. 
Fixed in https://github.com/mixxxdj/mixxx/commit/b83b62d890f5b1954fd76ec10a2b8edd0d2bae6b

**Pull request merged**
