### PR TITLE
Retire osolete Ubuntu Groovy 20.10

### PR DESCRIPTION
**Pull request by daschuer**
End of Ubuntu Groovy 20.10 support has been reached Juli 2021.

### CODE REVIEW

**Review by uklotzde — APPROVED** [review]
LGTM

**Comment by Holzhaus** [comment]
Does it really make sense to drop support for older distros in a *bugfix* release? I'm not advocating for reverting this, but we should discuss this for future releases. If there is no pressing need, I think bugfixes releases should support the same platforms as the original release.

**Comment by uklotzde** [comment]
In Fedora and RPMFusion the entire build infrastructure is disabled with the deadline. I assumed that @daschuer intended a similar behavior for our PPA.

**Comment by daschuer** [comment]
The Ubuntu Groovy build server is offline now. So it is pointless trying to upload new builds. 
This PR just disables the Upload.

**Comment by Holzhaus** [comment]
Ok, then this makes sense.

**Pull request merged**
