### PR TITLE
Deere 2.1 knobs & faders redesign

### PR DESCRIPTION
**Pull request by ronso0**
Here I propose a new design for the knobs and faders in Deere as discussed [here](https://github.com/mixxxdj/mixxx/pull/1343#issuecomment-343768990).
It drastically improves visibility of knob position and applies color coding to the rings rather than the pointers.
Faders are reduced in complexity to match the overall Deere design and can IMO be scaled down a bit if we agree on the shape.

Current design
deere-knobs-redesign_current

New design
deere-knobs-redesign_new

To enable testing with a fresh design, this is based on Be's Deere PR #1343 

What do you think?
Any ideas for further improvement, i.e. the small knobs?

### CODE REVIEW

**Comment by Be-ing** [comment]
I like it! I think there could be a bit more contrast between the center of the knobs and the notches though.

This may be a good solution to the colorblindness issues.

Do you have any ideas for improving the small effect parameter knobs?

**Comment by Pegasus-RPG** [comment]
I like the change. It makes things easier to see at a glance. I noticed that the ring colors don't match the previous pointer colors though. Was that intentional?

**Comment by ronso0** [comment]
> I think there could be a bit more contrast between the center of the knobs and the notches though.

Even more? I'm afraid they'd blend too much with the mixer background and the pointers would seem to float.

> I noticed that some of the ring colors don't match the previous pointer colors though. Was that intentional?

Yes! I think it's an improvement to assign the ring colors to certain control categories:
**blue** 'special control' like Balance, Quick Effect & Super/Meta knobs (matches Meta link buttons)
**red** any kind of 'volume': Gain, Wet/Dry knob (& Sampler volume if will be implemented)
**orange** just EQs

**Comment by ronso0** [comment]
The small knobs could look like this
deere-knobs-redesign_new_small4

**Comment by ronso0** [comment]
I made the pointer a little shorter
deere-knobs-redesign_new2

**Comment by Be-ing** [comment]
> Even more? I'm afraid they'd blend too much with the mixer background and the pointers would seem to float.

Hmm, you might be right. I think it's worth trying though. Have you thought about changing the color of the insides of the knobs? I don't know if that's a good idea, but it might be worth experimenting with too.

**Comment by Pegasus-RPG** [comment]
> Don't know if we should add a scale here, like the big knobs have it.
Small knobs already fill the widget, so they'd need to be smaller to make space for a scale or end markers. Doubt this is worth it.

I agree, and there are bars below them already anyway that take up less room.

**Comment by ronso0** [comment]
> Hmm, you might be right. I think it's worth trying though. Have you thought about changing the color of the insides of the knobs?

What do you have in mind? It should stay dark to contrast with the pointers, otherwise we're back to square one.

**Comment by ronso0** [comment]
@Be-ing I played around but didn't find a nice color.
Maybe you give it a try. Just use `Colors` > `Colorize` on 2nd layer in this Gimp file
[deere-knobs-redesign.zip](https://github.com/mixxxdj/mixxx/files/1515345/deere-knobs-redesign.zip)

**Comment by ronso0** [comment]
With grey outlines the slider grooves are now visible even with bright light.
deere-knobs-redesign_new3

**Comment by uklotzde** [comment]
@ronso0 @Be-ing There are now 2 massive PRs for Deere which both seem to be (almost?) finished. I would like get this nice work merged ASAP! Which of those PRs should I consider first for merging? Or is #1343 superseded by this PR?

I  will not do any XML code reviews, just some final testing. The most valuable feedback about functionality and usability will come from our alpha and beta testers, so let's get started.

**Comment by ronso0** [comment]
This PR is just for checking the design. #1343 should be merged first, I'll rebase in case of conflicts.

**Comment by Be-ing** [comment]
@ronso0 can you rebase this on master?

**Comment by ronso0** [comment]
voilá.

Any ideas, objections?

**Comment by Be-ing** [comment]
In general, I like it, but I'm not sure about the color around the EQ knobs. I tried switching it to the yellow used by the EQ notches before but that is too bright so it makes the notch not stand out as much. How about making the orange a bit redder, like #fc9d00ff?

I also feel that the slider handles pop out slightly too much. How about desaturating them a tiny bit to #338dfbff?

**Comment by uklotzde** [comment]
The coloured indicators are a helpful addition! Just some ideas after my first impressions and without following your previous discussions very closely:
- The center indicator in the ring around the knobs is very small and hard to see. I would prefer a slightly wider gap.
- How about switching the colour of the gain and filter rings? The gain rings are currently coloured in red whereas other volume level controls like cross and channel fader are blue. On the other hand the filter rings are blue, which doesn't match the volume level association. After switching the colours orange/red stands for eq/filter and both are "colouring" the sound in a similar way by frequency manipulation.
- Ever thought about using the common red/green colour scheme for the cue/play buttons?

**Comment by uklotzde** [comment]
The master is coloured in red, too. I still would prefer a more consistent scheme that matches the distinction between _level_ and _frequency_ controls.

**Comment by Be-ing** [comment]
> How about switching the colour of the gain and filter rings? The gain rings are currently coloured in red whereas other volume level controls like cross and channel fader are blue. On the other hand the filter rings are blue, which doesn't match the volume level association. After switching the colours orange/red stands for eq/filter and both are "colouring" the sound in a similar way by frequency manipulation.

Alternatively, the handles of the sliders could be switched to red.

> Ever thought about using the common red/green colour scheme for the cue/play buttons?

Yes, I think we should do this.

**Comment by ronso0** [comment]
> On the other hand the filter rings are blue, which doesn't match the volume level association. After switching the colours orange/red stands for eq/filter and both are "colouring" the sound in a similar way by frequency manipulation.

Yes, good idea! Consequently all Meta/Super knob indicators would be red as well. Pitch sliders could be light grey to distinguish them from the Vol faders.
Because all indicators in Deere are blue I was hesitating to turn that color scheme upside-down, but if this can win a majority, I'll change it.
As I see it, red is not a good color in Deere context because with more ambient light the contrast on the skin background decreases. So we should probably change red to something like magenta or maybe purple. I'll test this in  the next days.

**Comment by ronso0** [comment]
Center mark is wider now, please test
making all FX-related knobs red is not a good idea, Deere looks like a peacock then
deere-knobs-redesign_voltempofader_redfxknobs

Grey tempo fader, red Vol fader and blue FX knobs looks good and it's closer to current Deere look
deere-knobs-redesign_voltempofader

What do you think?

**Comment by uklotzde** [comment]
Saturation and brightness of the red color does not really fit into the scheme. It seems to indicate that something is wrong. Just some first and unfiltered impressions from a naive user ;)

The grey/blue/orange color scheme fits really well. Unfortunately I have no idea which 4th color could be added to complement this scheme.

**Comment by nopeppermint** [comment]
> I have no idea which 4th color could be added to complement this  scheme.

maybe purple
http://www.color-hex.com/color/be29ec

**Comment by ronso0** [comment]
Purple Gain/DryWet, purple Volume
deere-knobs-redesign_purplevolgain


Purple Gain/DryWet, grey Volume
deere-knobs-redesign_greyvol_purplegain

I prefer gery/purple. With purple Vol faders the skin get sa feminine touch that could be nice but doesn't match the rest of the skin.

**Comment by Be-ing** [comment]
I like the purple! I tried using purple a while ago when I was trying to make the knob notches easier to see for colorblind users with the old design but I couldn't get it to work well. With this new design it works much better. For colorblind users, the purple looks almost identical to the blue. Here is your screenshot seen through KMag's dueteranopia (the most common form of colorblindness) simulator:

image
They lose the distinction between the blue and purple colors, but that is not essential, just a nice extra feature.

**Comment by Be-ing** [comment]
I like how the purplse volume slider handles emphasize those sliders. I'm not sure the deck gain knobs need to be that emphasized though. I think the grey pitch faders blend in with the background a bit too much. Maybe make those a bit whiter? Or a different color?

The crossfader handle should match the volume faders. The crossfader handle is in a separate SVG file.

**Comment by uklotzde** [comment]
The purple is too dark and also very saturated and heavy.

Maybe the lime colour that is used for the EQ knobs in the current version of the Deere skin could fit? It's a light colour that doesn't yell at you and is easily distinguishable from the light blue and light orange.

**Comment by ronso0** [comment]
check Lime. It looks okay, but IMO the whole skin is way to colorful now.
deere-knobs-redesign_lime



What about grey?
deere-knobs-redesign_grey

**Comment by nopeppermint** [comment]
> check Lime

I like Lime

**Comment by uklotzde** [comment]
I was thinking about this yellow/lime from the current Deere skin: #D6E20E
Less colourful, but good to distinguish from the orange and blue elements.

_upload of sample image doesn't seem to work_

**Comment by ronso0** [comment]
> I was thinking about this yellow/lime from the current Deere skin: #D6E20E
Less colourful, but good to distinguish from the orange and blue elements.

Ah, I didn't perceive it as Lime.
I lowered the saturation and brightness a bit (#D6E20E really is to bright) and that's what it looks like:
deere-knobs-redesign_lime2

Everybody's happy now?

**Comment by Be-ing** [comment]
Ehh, I feel that the yellow slider handles look strange. Maybe yellow for the knobs and purple for the fader handles? Or is that too many colors?

**Comment by uklotzde** [comment]
👍 Great, I like that! Nicely fits into the colour scheme.

**Comment by ronso0** [comment]
> Or is that too many colors?

Yes, this is too much IMO. So many colors trying to get attention...

> Do we actually need to color the slider handles?

For me, light grey fader handles would be totally okay.

**Comment by Be-ing** [comment]
IMO fader handles are important and should be emphasized. On the other hand, gains shouldn't need frequent adjustment and I don't think they need to be emphasized.

**Comment by ronso0** [comment]
I really think colored rings and white/grey handles are sufficient to make knobs and faders easy to discover. IMO faders don't necessarily need colors, they already stand out because they're much brighter than their surrounding.

One very last option that comes to mind is to color the fader handles outline.

**Comment by daschuer** [comment]
What is left to do here? 

Here are my two cents:

I have just tested it and from terms of my taste, I like the old one with white rings more, because the knobs are less eye catching. Especially the read color is the problem, it is the Alarm color which overrules all others. The channel volume slider should not be highlighted by red at all, because this is not the case on any hardware mixer. Can we use a shade of Bordeaux for instead of red for the gain knobs like on many hardware Mixers?

**Comment by daschuer** [comment]
The pink version was also better. The xfader and the channel fader should have the same color. It is obvious what is what by the orientation. The rate slider should have a different color. 
How about rate = blue (because it adds an effect to the sound) and xfader and volume = gray, because they are visible enough because of their shape.

**Comment by ronso0** [comment]
This is a color scheme I like to mixxx with
deere-knobs-redesign_2017-12-13-orange-grey-blue

**Comment by daschuer** [comment]
Great, I like it as well. LGTM. Ready for merge?

**Comment by Be-ing** [comment]
No, I don't like the use of gray. IMO the volume faders and crossfader are the most important things to keep an eye on while mixing so they should pop out visually. I like the purple screenshots [posted above](https://github.com/mixxxdj/mixxx/pull/1399#issuecomment-349048952) the best but the purple color could use a little adjustment to not pop out quite as much.

**Comment by ronso0** [comment]
> Great, I like it as well. LGTM. Ready for merge?

IMO yes.

To summarize:
- Blue for all effect-related knobs and tempo
- Orange for EQs and controls that 'mix something in' (Balance, Dry/Wet)
- Grey for plain levels (also Master gain is not emphasized too much, maybe avoids abuse as Vol knob?)
- Vol and Crossfader stand out enough and don't distract from other mixer controls

IMO it's a reasonable step from the previous ring design to this, not too many eye-catching colors.
Also, the orange EQs complement the dominating blue quite nicely IMO.

Before we merge: is the center gap looking okay on HD and netbook screens?

**Comment by ronso0** [comment]
> No, I don't like the use of gray. IMO the volume faders and crossfader are the most important things to keep an eye on while mixing so they should pop out visually.

I really don't see a reason to color the Vol and crossfader handles. They are clearly visible, even in the minimized images in this  thread. If you're having issues recogniznig them please try to make them brighter.

**Comment by daschuer** [comment]
Ok, so let's merge this 14 commits PR. If there is still something to do, it can go to an other PR. 
Thank you @ronso0 for taking care, and all others for reviewing.

**Comment by ferranpujolcamins** [comment]
I've just realized that this design suffers from the same problem that my  branch https://github.com/mixxxdj/mixxx/pull/645:
The design of the knobs implies that the 12 o'clock position is the default position for the knob. It is strange when I right click the SUPER or META knob the position jumps to 8 o'clock when the notch is at 12 o'clock.

@ronso0 Could you remove the notch on the META and the SUPER knobs?

@daschuer This got me thinking: when you were reviewing my branch you noted that the correct "neutral position" for the superknob depends on how the effects parameters are tied to it. But this does not only apply to the position where the knob ring is not visible, but also to knob design items like the notch introduced in this PR and also to the position where the knob jumps when reset. So we have a more general problem here.

**Comment by ronso0** [comment]
@ferranpujolcamins 
Sounds reasonable, I'll open a PR soon.
Related: [lp:1698408 effect specific Meta knob/QuickEffect knob default position](https://bugs.launchpad.net/mixxx/+bug/1698408)

**Pull request merged**
