### PR TITLE
Update hidapi to 0.12.0

### PR DESCRIPTION
**Pull request by JoergAtGithub**
This PR updates hidapi to the latest version 0.12.0

Furthermore it increases the minimum required version to 0.11.2. This solves the open FIXME of https://github.com/mixxxdj/mixxx/pull/4054. Since this PR getInputReport is no longer working on Linux, because the hidapi command hid_get_input_report wasn't implemented for the Linux hidraw backend at this time.
This was fixed by https://github.com/libusb/hidapi/issues/259 which was part of the hidapi 0.11.2 release.

Note: hid_get_input_report will only succeed with Linux Kernel 5.11 or later. With earlier Linux kernel versions, hid_get_input_report will return error code -1 as before this PR.

### CODE REVIEW

**Comment by Holzhaus** [comment]
Thanks. Could you remove the CI and documentation files from this PR and potentially add them as a gitignore pattern to avoid accidental commits in the future?

**Comment by uklotzde** [comment]
> Thanks. Could you remove the CI and documentation files from this PR and potentially add them as a gitignore pattern to avoid accidental commits in the future?

Please strip the archive down to the minimum as before, only required sources and license files.

**Comment by uklotzde** [comment]
The commits should be squashed.

**Comment by Be-ing** [comment]
Why is this still being vendored? IIRC it was in the past due to an old version in Ubuntu?

**Comment by daschuer** [comment]
If we only need a safety net for our minimum required version, we may only update to 0.11.2. than we have the chance to remove the vendored library once we drop support for focal / impish / Fedora 35.

**Comment by daschuer** [comment]
I don't have a strong opinion here. 

Without lifting the requirement to 0.12, out aged distros will build with 0.12 and the recent versions with 0.11. Is this desired?

**Review by uklotzde — APPROVED** [review]

**Review by daschuer — CHANGES_REQUESTED** [review]
I think before merge we should either lift the minimum requirements to 0.12 or downgrade the overlay to 0.11. that everything is consistent. 

Do the 0.12 changes outwaight the regression risk of using a 7 days old library no one else is using (yet) ? 

@uklotzde what do you think about this?

**Comment by uklotzde** [comment]
> I think before merge we should either lift the minimum requirements to 0.12 or downgrade the overlay to 0.11. that everything is consistent.
> 
> Do the 0.12 changes outwaight the regression risk of using a 7 days old library no one else is using (yet) ?
> 
> @uklotzde what do you think about this?

I don't care. But let's please stop these back and forth edits.

**Comment by daschuer** [comment]
For now I think it is best to downgrade to 0.11.
This allows us to de-vrndor this library earlier.
@JoergAtGithub shall I prepare an alternative PR with this change or do you have interest to do it her.

Sorry for the extra loop. I have original missed the missmatch between the required and the installed version.

**Pull request closed without merging**
