### PR TITLE
skin change: save fullscreen state before destroying main widget

### PR DESCRIPTION
**Pull request by ronso0**
maybe this fixes [lp:1777328 macOS: mixxx leaves fullscreen view when switching skins](https://bugs.launchpad.net/mixxx/+bug/1777328)

just a guess: macOS quits fullscreen when the skin widget is destroyed?
store fullscreen state beforehand.

### CODE REVIEW

**Comment by ronso0** [comment]
@foss- Please test!

**Comment by foss-** [comment]
Goes back to window mode after skin switch testing 2.3-beta-3983-g674fc8ceee (HEAD branch) (from this PR) on macOS 11.3.1.

**Comment by ronso0** [comment]
Yes, the fullscreen state is saved and Mixxx leaves fullscreen when the skin is switched, that works around a render bug in Linux.
When the new skin is loaded Mixxx goes fullscreen again. Does that work now or does it stay in window mode?

**Comment by uklotzde** [comment]
Will this be ready for 2.3.0 or shall we defer it?

**Comment by daschuer** [comment]
Am Mo., 17. Mai 2021 um 22:37 Uhr schrieb Uwe Klotz <
***@***.***>:

**Comment by Holzhaus** [comment]
@daschuer  It looks like your reply is missing from the comment.

**Comment by daschuer** [comment]
Deleted, both works for me.

**Comment by ronso0** [comment]
> Will this be ready for 2.3.0 or shall we defer it?

no hurry.
findings from debugging with @foss- : 
unlike other OS, macOS does not detect the fullscreen state correctly. after skin change isFullScreen() reports 'true' while Mixxx is in windowed mode.
so, to get fullscreen again one needs to click the fullscreen menu action *twice*

**Comment by ronso0** [comment]
= maybe be finished for 2.3.1 if we can find the root cause.

**Comment by ronso0** [comment]
@foss- Does it still happen with `main` builds?

**Comment by foss-** [comment]
2.4-alpha-1009-gc0679a2839 (main)
Mixxx in fullscreen mode
switch skin and restart Mixxx
Mixxx starts in windowed mode

**Comment by ronso0** [comment]
Thank you!
I rebased this branch on `main`. Does it still fail to restore fullscreen in those situations?

**Comment by ronso0** [comment]
@foss- Please try the new commit.

**Comment by foss-** [comment]
1. launch 2.4-alpha-1010-gbb3afd9467 (HEAD) on macOS 11.6.1
2. switch to fullscreen
3. switch skin
4. Mixxx opening in windowed mode after restart

What is noticeable is, that while native mac apps like mail app open the preferences over their own fullscreen window (i.e. have mail in fullscreen, open preferences and preferences will open over the fullscreen mail view).

In Mixxx the behavior is different: when Mixxx is in fullscreen and preferences are opened, the view shows the preferences window over the last viewed windowed app. Example: use Firefox, switch to fullscreen Mixxx, open preferences and the preferences window is displayed in windowed mode over the Firefox window.

This is unexpected and could indicate that there is a glitch in how Mixxx is aware or rather unaware of its own fullscreen state.

**Comment by ronso0** [comment]
That is somewhat congruent to the [showFullScreen() docu](https://doc.qt.io/qt-5/qwidget.html#showFullScreen), the preferences seem to be placed on another (virtual) desktop.

> On macOS, showing a window full screen puts the entire application in full-screen mode, providing it with a dedicated desktop. Showing another window while the application runs in full-screen mode might automatically make that window full screen as well. To prevent that, exit full-screen mode by calling showNormal() or by close() on the full screen window before showing another window.

Do you observe the same both with `main` and binaries from this PR?

**Comment by foss-** [comment]
Thought this might be how qt works. So from [linked qt showFullScreen() docu](https://doc.qt.io/qt-5/qwidget.html#showFullScreen) behavior seems expected.

Then again [Apple HIG](https://developer.apple.com/design/human-interface-guidelines/macos/app-architecture/fullscreen-mode/) and more specifically [fullScreenAuxiliary](https://developer.apple.com/documentation/appkit/nswindow/collectionbehavior/1419617-fullscreenauxiliary) seems to claim otherwise `The window can display on the same space as the full-screen window.`.

`main` indeed behaves differently and displays the preferences window over the fullscreen Mixxx window as expected.

**Comment by ronso0** [comment]
okay, so it' actually exactly the opposite of what the docu warns about:
* with `showFullScreen();` the prefs are on top of the fullscreen Mixxx window
* with `setWindowState(Qt::WindowFullScreen);` the prefs are displayed on top of another window.

and the actual bug is not resolved...

I'll try to read the fullscreen state from `windowState()`, not `isFullScreen()`, maybe that's the issue.

**Comment by ronso0** [comment]
Nope, the debug output shows that the fullscreen state detected by `windowState()` is congruent with `isFullScreen()`, and both don't match the actual state after a skin change.

Giving up here..

**Comment by foss-** [comment]
Sure, thanks for looking into this.

**Pull request closed without merging**
