### PR TITLE
Fix debug assert in CueDAO and track id property of Cue objects

### PR DESCRIPTION
**Pull request by uklotzde**
Try to keep the ids between Track and Cue objects consistent.

~~Unfortunately this doesn't fix the debug assertion in CueDAO~~ Fixes the debug assertion in CueDAO when adding audio files with embedded Serato cues.

### CODE REVIEW

**Comment by Holzhaus** [comment]
Doesn't work for be. Without looking further into the code: Maybe there's a race condition and it tries to save the imported cues *before* adding the track to the DB (and thus creating a valid ID?)

**Comment by Holzhaus** [comment]
Ok, apparently when I start to drag-and-drop a track from the file browser, `TrackDAO::addTracksAddTrack` (sic!) is called, which calls `saveTrackCues` and triggers the debug assertion.

**Comment by uklotzde** [comment]
> Ok, apparently when I start to drag-and-drop a track from the file browser, `TrackDAO::addTracksAddTrack` (sic!) is called, which calls `saveTrackCues` and triggers the debug assertion. The code you modified (`Track::initId`) is only called by the global track cache. I guess we need to make sure it's called here as well.

Yikes, the code managing the track cues is chaotic. We need to fix this step by step. I'll add some more commits here that at least "fix" (well, only a workaround) the synchronization between `Track` and `Cue`.

**Comment by Holzhaus** [comment]
I still get:
```
Debug [Main]: SoundSourceFFmpeg - Opened stream for decoding { index 0 | id 1 | codec_type 1 | codec_id 86018 | channels 2 | channel_layout 3 | channel_layout (fixed) 3 | format 8 | sample_rate 44100 | bit_rate 249318 | frame_size 1024 | initial_padding 0 | trailing_padding 0 | seek_preroll 0 | start_time 0 | duration 11083776 | nb_frames 10824 | time_base 1 / 44100 }
Debug [Main]: TrackMetadata - Modifying bitrate: 257 kbps -> 249 kbps
Debug [Main]: TrackMetadata - Modifying duration: 251000000000 ns -> 251332789115 ns
Debug [Main]: Track - Finishing deferred import of 17 cue(s)
Debug [Main]: TrackDAO: Adding track QFileInfo(/data/jan/Projects/serato-tags/shared/01-13 eminem mockingbird.m4a)
DEBUG ASSERT: "pCue->getTrackId() == trackId" in function void CueDAO::saveTrackCues(TrackId, const QList<CuePointer>&) const at /home/jan/Projects/mixxx/src/library/dao/cuedao.cpp:220
Aborted (core dumped)
```

**Comment by uklotzde** [comment]
No I am able to reproduce the assertion. It only happens for file not in the library with embedded Serato cues.

**Comment by uklotzde** [comment]
Fixed.

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
