### PR TITLE
Handle and ignore invalid bpm values in MP3 files

### PR DESCRIPTION
**Pull request by uklotzde**
Fixes https://bugs.launchpad.net/mixxx/+bug/1832325

Actually caused by an ugly workaround to adjust non-standard bpm values.

### CODE REVIEW

**Comment by daschuer** [comment]
Good catch. LGTM.
Waiting for CI

**Comment by uklotzde** [comment]
Looks like util/fpclassify.h is incomplete and not portable :((

**Comment by igor47** [comment]
fun fact: my laptop was stolen and i was re-setting up mixxx on a new one. i had an unexpectedly out-of-date backup of `.mixxx` (already bad, i lost about two years of cue points, stars, plays, and crates), but trying to use it resulted in pegged CPU and unresponsive UI. i then spent about 8 hours trying various things. eventually, working on the assumption that it was the large number of files in my music library that was causing the problem, i moved a bunch of directories out, and was moving them in one letter at a time (like `mv a* ~/Music/music`) and re-scanning the library. this allowed me to eventually zero in on certain specific files that were not working.

really appreciate the speed of resolution here, since i am hoping to use Mixxx at an event this weekend and some of my files cannot be added to the library.

**Comment by igor47** [comment]
confirmed that applying `https://github.com/mixxxdj/mixxx/pull/2157.patch` fixes all my problems

**Comment by uklotzde** [comment]
Oh, no. The plugins failed to build!! I have to find a workaround for 2.2 without using `fpclassify`.

I will revert all changes and force push this branch when finished.

**Comment by uklotzde** [comment]
I found a solution that doesn't need the fpclassify workaround and hopefully works on all platforms.

**Comment by daschuer** [comment]
Nice solution. LGTM. 
Waiting for CI

**Comment by uklotzde** [comment]
@igor47 Thanks for tracking this down, reporting, and providing the example file!

The supply of malformed and corrupt files is endless, there is always a new edge case that has not been covered yet.

If you enable metadata export Mixxx will replace the invalid ID3v2.3 tag with a fresh and valid ID3v2.4 tag.

**Comment by mbrouillet** [comment]
I built from source today, and "Rescan Library" does no longer hang. Thank you !

**Pull request merged**
