### PR TITLE
Check return value from getEffectManifest fro null, fixing lp1780148

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by Be-ing** [comment]
Thanks for looking into this. This is a small bug fix that should go into a 2.1 release. Please rebase it on the 2.1 branch.

**Comment by Be-ing** [comment]
Does this affect 2.2? If so, let's merge it to that branch.

These changes conflict with #1705, so I'd prefer to not merge this to master.

**Comment by daschuer** [comment]
We will have the conflict anyway when we merge 2.2 back to master. For now it looks be more straight forward to resolve the conflicts in https://github.com/mixxxdj/mixxx/pull/1705 and keep 2.2 and master in sync.

**Comment by Be-ing** [comment]
You're right, I tested with 2.1 and this bug does not affect that branch, so I'm merging this for 2.2. I presume the bug was introduced somewhere along the way with implementing LV2 effects. @kshitij98 or I could resolve the merge conflict in #1705.

**Pull request merged**
