### PR TITLE
Merge 2.3

### PR DESCRIPTION
**Pull request by ronso0**
There were conflicts in `.github/workflows/build.yml`. I ignored the 2.3 changes = kept the 2.4 state, was that correct?

If yes, merge this or should I push to `main` as usual?

### CODE REVIEW

**Comment by Swiftb0y** [comment]
IMO keeping the 2.4 state is correct. But in the end the decision lies with @daschuer since he introduced the workflow changes in #10820 and I don't know how the entire release process is intended to work.

**Comment by daschuer** [comment]
All looks correct. 
Yes, please push it to main as usual.

**Comment by ronso0** [comment]
oh, interesting: I pushed the local `main` branch directly and this branch is considerd merged, too.

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
