### PR TITLE
Shade :: 2.2 fixes

### PR DESCRIPTION
**Pull request by ronso0**
* moved all button icons to subfolder /btn
* removed double library border
* fixed screwed Previewdeck layout (10px margin that wasn't visible with 2.1)

I double checkd this, but please test if all button icons are in play in case something slippped through.

### CODE REVIEW

**Comment by nopeppermint** [comment]
it seems to me like on the analyze tab there are two buttons missing, there is just the text "new" / "all" but no round button..

otherwise it looks good on Linux

**Comment by ronso0** [comment]
good catch!
that was https://bugs.launchpad.net/mixxx/+bug/1753148 popping up, `width="100%"` and `height="100%"` in SVG icon. Appearantly, in 2.1 it didn't matter

**Comment by nopeppermint** [comment]
looks good now

BTW: the round buttons are missing in Latenight as well (in this branch)..

BTW: why we need a "All" button and a "Select All" Button ?
Without reading the manual (that's the case for most user's I think) It's not clear to my why there are two button's with "All" and they are not doing the same things..

**Comment by ronso0** [comment]
> BTW: why we need a "All" button and a "Select All" Button ?
Without reading the manual (that's the case for most user's I think) It's not clear to my why there are two button's with "All" and they are not doing the same things..

'All' selects all music files, 'New' selects only those added within last 7 days.
Button labels shouldn't be longer, IMO that's what the tooltip are for.

**Comment by ronso0** [comment]
Is anyone else seeing this offset of hovered effects?
shade_fx_offset
In 2.1 all effects in the list had space at the left

**Comment by beenisss** [comment]
If you're updating Shade, do you fancy taking a look at the inconsistent arrows in the below?

screen shot 2018-10-02 at 12 44 44

**Comment by ronso0** [comment]
Interesting. The buttons are just glyphs and it looks like the font sizes are scaled irregular.
I've set the font to OpenSans (included in Mixxx) and maximized the font size.
It should now look like this on your system, as well:
shade-2 2_rate_buttons

**Comment by beenisss** [comment]
That doesn't seem to have made a difference. The effect is more pronounced using my local build than it is in the 2.1 release (regardless of which version of the Shade skin I'm using in either scenario.)

To be honest I would just chalk this up to yet another weird graphics quirk on my Mac, unless somebody else reports the same issue.

**Comment by beenisss** [comment]
I've tested the skin in this PR, preview deck issue is indeed resolved. No other visible differences.

This is how the effect-drop down looks. I don't have the indent issue but the text doesn't fit:

Master build, skin from this PR:
master build 1824 skin

Master build, skin from master:
master build master skin

2.1 release:
2 1 release

I know this issue came up before, though maybe not with this skin. Let me know if I should log this somewhere else.

**Comment by beenisss** [comment]
Forgot to mention. Not sure what the deal with this is:

Just below the mix dial:
screen shot 2018-10-02 at 14 37 46

After clicking on it:
screen shot 2018-10-02 at 14 37 58

It toggles back and forth between those two if you click repeatedly. As above this is independent of skin version, but only occurs when I run the master build.

Finally, there is a rogue pixel inside the 'Mid' dial on the right, which shows up regardless of skin/Mixxx version:

screen shot 2018-10-02 at 14 38 20

**Comment by ronso0** [comment]
I removed the lonely pixel from mixer panel bg.
The issues with the rate buttons I can't confirm.

> It toggles back and forth between those two if you click repeatedly

You just dicovered the fx mixmode button! Check the tooltip..
The graphics are fine, though, so I guess it's an issue with your machine.

**Comment by ronso0** [comment]
Is the icon scaled correctly if you remove `viewBox="0 0 4.2333 1.3229"` from Shade/btn/btn_fxmix_d+w.svg with a tex editor?

**Comment by ronso0** [comment]
> Is the icon scaled correctly if you remove `viewBox="0 0 4.2333 1.3229"` from Shade/btn/btn_fxmix_d+w.svg with a tex editor?

This was just wrong: appearantly we need the viewbox attribute to render the icon at the correct size.
It should the the same as the icon size: viewBox="0 0 16 5"
Fixed.

**Comment by beenisss** [comment]
Nice, mixmode icons are sorted.

**Comment by ronso0** [comment]
Good.
As you use Qt scaling, could you please double-check the icons in the other expandable sections, as well? Like FX, Samplers, Looping, Preview deck
They're all looking fine here on my 1366px screen, and it would be nice to have it confirmed with scaling. If all those icons are looking as before, this is ready to merge.

**Review by benis — APPROVED** [review]
Re-checked as above, all looking good.

**Comment by uklotzde** [comment]
Still LGTM. I'm planning a new snapshot build for RPM Fusion and would like to include all these polishing changes.

**Pull request merged**
