### PR TITLE
devendor libebur128

### PR DESCRIPTION
**Pull request by Be-ing**
Why was this vendored in the first place?

### CODE REVIEW

**Comment by Be-ing** [comment]
I guess we don't have libebur128 in the macOS build environment. Let's remove this after switching to vcpkg for macOS.

**Comment by daschuer** [comment]
It was originally introduced here: 
https://github.com/mixxxdj/mixxx/pull/520
Because it was not part of Ubuntu Trusty. 
Now our olldes supported Version Ubuntu Groovy (20.10) has 1.2.4-2

**Comment by Holzhaus** [comment]
> Why was this vendored in the first place?

I suppose we should a comment to CMakeLists.txt for every new dependency we add to the lib directory that explains why we added it.

**Comment by Be-ing** [comment]
Unfortunately this let us get away with being lazy with maintaining our macOS build environment because we never added libebur128 to it. Let's merge this after switching macOS to vcpkg.

**Review by daschuer — APPROVED** [review]
All green. LGTM. Thank you.

**Pull request merged**
