### PR TITLE
Update Azure code signing action to 0.4

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by Swiftb0y** [comment]
can we merge this to a temporary upstream branch first instead of `main` directly? The signing code doesn't run on this PR branch so I'm 100% confident it works.

**Comment by daschuer** [comment]
Here is is: https://github.com/mixxxdj/mixxx/tree/azure_signing_update

**Comment by Swiftb0y** [comment]
Thanks. Waiting for the that branch's CI to complete.

**Review by Swiftb0y — APPROVED** [review]
signing succeeded. LGTM thank you.

**Comment by Swiftb0y** [comment]
> Here is is: https://github.com/mixxxdj/mixxx/tree/azure_signing_update

took the liberty to delete that branch again now that this is merged.

**Comment by daschuer** [comment]
Thanks

**Pull request merged**
