### PR TITLE
Fix for broken GLGS waveform Y-axis scaling

### PR DESCRIPTION
**Pull request by JoergAtGithub**
Using GLSL waveforms on Windows it can happen that the first wafevorm is scaled wrong in vertical size (only the lowest peaks of the waveform are visible, otherwise, the waveform is full functional):
grafik

I found out, that removing the workaround of double calling WaveformWidgetFactory::instance()->setWidgetTypeFromHandle in src/preferences/dialog/dlgprefwaveform.cpp fixes this issue in nearly all cases.

While testing I found only one special case, where it's not fixed:
1.) Start a fresh Mixxx session andload some tracks into the decks
2.) Open Preferences dialog
3.) Resize Mixxx Main Window
4.) Select another GLSL Waveform type
5.) Close Preferences dialog

All none GLSL waveform types work with and without this change.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
@JosepMaJAZ Could you test this in your environment?

**Comment by JoergAtGithub** [comment]
@NotYourAverageAl Could you test this with different graphis adapters as you did for https://github.com/mixxxdj/mixxx/pull/3416

**Comment by NotYourAverageAl** [comment]
@JoergAtGithub I'm running Mixxx-2.3-r7973-14bddb65a7.msi and couldn't reproduce this bug, so can't verify this PR fixes it. Do you still want me to test this PR and make sure it has not affected anything else anyway?

**Comment by JoergAtGithub** [comment]
Yes, that would be great, because I've only one system with am old Intel HD graphics GPU. Please try what happens, if you switch between GLSL waveform types.

**Comment by JosepMaJAZ** [comment]
I just installed the artifact and the waveforms worked as expected (without the error on your screenshot, and without the error that prompted to add the #ifdef). 

Since I implemented that patch and now, there have been other fixes that also affected linux and mac and seems to have been a better solution to the problem I just hacked around.

**Comment by NotYourAverageAl** [comment]
test on 2 machines, one with integrated graphics & the other with an Nvidia gpu. 
No issue detected and I cannot reproduce your special case either. '

**Comment by Be-ing** [comment]
Thanks for testing @NotYourAverageAl and @JosepMaJAZ.

**Pull request merged**
