### PR TITLE
Switch remaining user-facing text from 'preset' to 'mapping'

### PR DESCRIPTION
**Pull request by esbrandt**
follow up to mixxxdj/mixxx#3387

Needed for consistent translations

- [x] Update strings
- [x] Update translation template
- [ ] Upload updated translation template to Transifex

### CODE REVIEW

**Comment by ronso0** [comment]
Changes LGTM, thanks!

Do you mind waiting with pushing the transifex file until I have a PR ready that touches one large string in Preferences > Controllers? (currently finishing it, guess I'll open it today or tomorrow)

**Comment by Holzhaus** [comment]
There are pre-commit issues btw. Please set up [pre-commit](https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking) to avoid having to add "Fix pre-commit issues" commits.

**Comment by ronso0** [comment]
> Do you mind waiting with pushing the transifex file until I have a PR ready that touches one large string in Preferences > Controllers? (currently finishing it, guess I'll open it today or tomorrow)

@esbrandt  This is it #3464

**Comment by esbrandt** [comment]
@Holzhaus
The check seems a bit sensitive here, literally changed one word.
Do you want me to change style for the line anyway?

@ronso0 
Sure I can hold off until your pr gets merged. Translation template needs update anyway . Transifex should pick up the updated translation template automatically. So event frequent changes should be a non-issue.

**Comment by Holzhaus** [comment]
> @Holzhaus
> The check seems a bit sensitive here, literally changed one word.
> Do you want me to change style for the line anyway?

Yes, please. A lot of codebase still doesn't match our preferred code format. To avoid mass-reformatting all of our code and essentially breaking the git history, we opted for an incremental approach. The check only reformats changed lines, and our policy is that every time you touch a line, make sure it is formatted properly.

**Pull request merged**
