### PR TITLE
Fix typo in LateNight skin, fixing bug lp1781829

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by ronso0** [comment]
Thanks for this fix. LGTM

**Comment by daschuer** [comment]
Thank you for review. Is the different right click behavior in Tango intended?

**Comment by ronso0** [comment]
In Tango there are two situations: (1) with separate Cue button or (2) PLay/Cue combo.
Now I see I used `play` also for Play right-click with (1), which is not ideal. I'll add `cue_set` there.

**Comment by ronso0** [comment]
I notice that right-clicking the Play button in LateNight & Shade (cue_set) latches the button to pressed state, and I can't work out if and which combination of `<ConnectValueToWidget>` and `<ConnectValueFromWidget>` can prevent that situation. Removing the display connection doesn't help. Any ideas?

**Comment by daschuer** [comment]
I cannot confirm this with Shade and LateNight. If I right click the deck's play button, it just sets the cue point. 
Did you use this branch for testing?

**Comment by ronso0** [comment]
I'm using 2.1.1-pre with the changes from here. It's locked to pressed state, regardless if playing or not.
play-button-pressed

**Comment by daschuer** [comment]
Oh I got it, there is actually a bug in WPushButton. 
WPushButton adopts the behaviour from the connected control, which should lead tho the best behavior. It only requires to set "RightClickIsPushButton" if you want to force to treat that control as Pushbutton

**Pull request merged**
