### PR TITLE
Limit only use vinyl gain > 0 dB if total gain is <= -1 dB

### PR DESCRIPTION
**Pull request by daschuer**
This is the attempt to Fix Bug https://bugs.launchpad.net/mixxx/+bug/1741684 

It works now IMHO quite nice. Most tracks are scratched rather unchanged, because of a replay gain of ~-6 dB. 
The High dynamic tracks do not have big Gain increase by scratching anymore, which reduces the scratching effect, but avoid effective cliping.

If you pick a high pre-gain, the vinyl effect is lowered. If you pick a lower Gain you have the full effect in place. 

Does this work for you?

### CODE REVIEW

**Comment by Be-ing** [comment]
Did you mean to target this at the 2.1 branch?

**Comment by daschuer** [comment]
Ups,. ... Now for 2.1

**Comment by Be-ing** [comment]
macOS build failed:
```
src/engine/enginepregain.cpp:133:22: error: constexpr variable 'speedOneDiv' must be initialized by a constant expression
    constexpr double speedOneDiv = log10((1 * speedGainMultiplyer) + 1);
                     ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/engine/enginepregain.cpp:133:36: note: non-constexpr function 'log10' cannot be used in a constant expression
    constexpr double speedOneDiv = log10((1 * speedGainMultiplyer) + 1);
                                   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/math.h:391:15: note: declared here
extern double log10(double);
              ^
1 error generated.
scons: *** [osx64_build/engine/enginepregain.o] Error 1
scons: building terminated because of errors.
```

Windows build failed for the same reason:
```
[00:09:42] enginepregain.cpp
[00:09:43] src\engine\enginepregain.cpp(133): error C2131: expression did not evaluate to a constant
[00:09:43] src\engine\enginepregain.cpp(133): note: failure was caused by call of undefined function or one not declared 'constexpr'
[00:09:43] scons: *** [win64_build\engine\enginepregain.obj] Error 2
```

**Comment by Be-ing** [comment]
Could someone with timecode vinyl test this? @ywwg, @Bronxio?

**Comment by Bronxio** [comment]
Sure. How can I download that alpha?

**Comment by daschuer** [comment]
Which OS do you use? Here it is for Windows x64
https://ci.appveyor.com/api/buildjobs/ipc570t71ndj0245/artifacts/mixxx-2.1.0-beta1-2.1-PR1476-git6483-release-x64.exe

**Comment by daschuer** [comment]
You should not be able to clip the signal by scratching, (with no EQs and such)
The scratch sound should be still sound natural at default gain settings (deck VU Meter at Yellow to green threshold) 
This depends by the way not to vinyl control. All speed changing controls can be used.

**Comment by ywwg** [comment]
checking this out now

**Comment by ywwg** [comment]
I tried a few different things and it did not clip.  It also still sounds really good, thanks for fixing this.  Is it possible to see the differences in the reference buffers?  I'm happy to say LGTM without seeing them but I'm curious if there's a visible change.

**Comment by daschuer** [comment]
The change is almost not visible when plotting the output. Two lines side by side.

**Comment by Bronxio** [comment]
Yes, Windows 7 SP1 64-bit.

I made scratches with a normalized track (highlighted zone):

imagen

And no clipping at all, but the (default) rec level was low. Scratches and fast backspins are loader, but that's natural as far as I know. I didn't get if the issue was only with louder rec level, or no matter which one is it. If you need other conditions, please let me know to make more (if you want some specific track, for example).

imagen

**Comment by Be-ing** [comment]
I tested this with clicking and dragging the waveform and I agree that it sounds really good. I tried increasing the deck gain with a few tracks to get them into the yellow region of the meter and couldn't get them to clip by dragging the waveform. Ready for merge?

**Comment by daschuer** [comment]
Yes!

**Comment by daschuer** [comment]
Thank you for review.

**Pull request merged**
