### PR TITLE
skin: Move legacy skin classes to skin/legacy/

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
LGTM 

I am unsure about the pre-commit issues. Do you want to add a commit with these automatic changes to avoid future noise in PRs?  I don't mind about the listed issues itself.

**Comment by Holzhaus** [comment]
I can, but we usually had the policy to not do mass reformattings, so I intentionally skipped it. If you want, I can add it.

**Comment by Holzhaus** [comment]
> I can, but we usually had the policy to not do mass reformattings, so I intentionally skipped it. If you want, I can add it. 

So... Should I? @daschuer @uklotzde ?

**Comment by uklotzde** [comment]
I don't mind. Choose whatever you think is reasonable and doesn't waste your precious time ;)

**Comment by daschuer** [comment]
Oh I see. I Initially thought it was only header sorting. That would be to massive.

**Review by daschuer — APPROVED** [review]
LGTM

**Pull request merged**
