### PR TITLE
fix: Rotary Jog filter ring buffer indexing

### LINKED ISSUE #13965: `jog` CO behaviour regression
### Bug Description

Starting from 0df68b7c0fb7f57aef2c10e80233394cc92fe894 or 64d9f000a5356ef5e089dff064a3759b93de95ce, the behaviour of `[ChannelX],jog` has changed and doesn't seem to react to the same value any more.

This has broken the the S4 MK3 mapping, but I suspect this would have broken other mapping as well. 

## Expected/previous behaviour

Nudge the jog wheel crown slows down or speeds up the track

## Current behaviour

Nothing noticeable

### Version

main

### OS

Ubuntu 22.04/Qt 6.2

### PR DESCRIPTION
**Pull request by Swiftb0y**
Fixes #13965. Please confirm.

### CODE REVIEW

**Comment by acolombier** [comment]
Will test that ASAP. Any chance to had some test coverage on this?

**Comment by Swiftb0y** [comment]
like 65060ee9cba0e7935ccf0642cff6160d83a294b5?

**Comment by acolombier** [comment]
Yeah, look like a good start! Any test is better than none ;) 
I think anything that we can run on the previous version (before the 2 commits mentioned in https://github.com/mixxxdj/mixxx/issues/13965) and on the new version would be a good way to ensure no regression there and in the future. I appreciate this is no easy task so happy with anything you feel comfortable doing there.

**Comment by Swiftb0y** [comment]
Its just a simple moving average filter, I lets not overcomplicate things. The public interface of the type is deliberately small and I think these tests cover basically all of it. So I doing anymore is just bloat IMO.

**Comment by Swiftb0y** [comment]
Merge?

**Comment by acolombier** [comment]
If it's okay with you, I'd like to test it first. 
The issue I have IMO is that we do not have any test using the signal path in the reference buffer to ensure behaviour consistency, so it's hard to make sure that this small fix indeed restore the initial behaviour
I'll make sure to test that ASAP!

**Comment by Swiftb0y** [comment]
>  The issue I have IMO is that we do not have any test using the signal path in the reference buffer to ensure behaviour consistency, so it's hard to make sure that this small fix indeed restore the initial behaviour

Yes, I agree. Though the tests you asked me to add explicitly test the previously broken code. I can rearrange the commits and then you would be able to see the test fail before the fix and be fixed after. Otherwise we can of course wait with merging until you tested it. I just wanted to make sure this didn't get lost and the issue is fixed asap.

**Review by acolombier — APPROVED** [review]
LGTM!

Tested and work as expected. Thank you for that quick fix and the added test cases!

**Comment by Swiftb0y** [comment]
Thanks the testing.

**Pull request merged**
