### PR TITLE
Add Behringer-CMD-PL-1 controller

### PR DESCRIPTION
**Pull request by yledoare**
Hello, 
this a pull request from 2.3 branch 
I hope this fix the PR 11518
Regards

### CODE REVIEW

**Comment by ronso0** [comment]
Tthe mapping test fails:
```
The following tests FAILED:
	 93 - ControllerPresetValidationTest.MidiPresetsValid (Failed)
```
https://github.com/mixxxdj/mixxx/actions/runs/4859672642/jobs/8663843593?pr=11529

You need to install and run pre-commit as adviced multiple times there https://github.com/mixxxdj/mixxx/pull/11518#issuecomment-1528769398

**Comment by yledoare** [comment]
I have this error on pre-commit 

don't commit to branch...................................................Failed
- hook id: no-commit-to-branch
- exit code: 1

**Comment by yledoare** [comment]
And when I want to make tests, I have a timeout 

 1/650 Test   #1: AnalyzerWaveformTest.simpleAnalyze ..............................................***Timeout 1500.13 sec

Maybe because I need a defined DISPLAY ?

**Comment by ronso0** [comment]
> I have this error on pre-commit
> 
> don't commit to branch...................................................Failed
> 
>     * hook id: no-commit-to-branch
> 
>     * exit code: 1

That is because you named your branch like the target. You can skip this hook with
`SKIP=no-commit-to-branch git commit` as explained in https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking

**Comment by ronso0** [comment]
But `eslint` also fails, see https://github.com/mixxxdj/mixxx/actions/runs/4859672639/jobs/8663843595?pr=11529#step:6:185
But you should also see that locally.

**Comment by Swiftb0y** [comment]
@yledoare May I ask what your intention is with this PR? Do you need help with mapping it or is this supposed to be a complete submission?

**Comment by yledoare** [comment]
@ronso0 :

pre-commit makes no error with SKIP=no-commit-to-branch, thanks
eslint  error should be fixed in last commit

@Swiftb0y 

It is a complete submission

**Review by Swiftb0y — CHANGES_REQUESTED** [review]
I'm sorry, I can't accept the PR in this state. Only 10% of the hardware is actually mapped and the implementation is sloppy and full of errors to the point where I doubt this mapping has ever even been tested. @yledoare if you want to make a helpful contribution, please take the time to get familiar with our documentation, XML and Javascript so you can create a usable and polished mapping.

**Comment by o-bardiuk** [comment]
It's been 3 years to include a mapping into the code. Cool

**Pull request closed without merging**
