### PR TITLE
Latenight :. permanent xFader buttons

### PR DESCRIPTION
**Pull request by ronso0**
this adds xFader buttons to two deck mixer, as well as a smalller xfader for minimal mixer configurations.

now each character L/M/R can be clicked to directly set the desired deck xfader orientation

latenight-xfader

### CODE REVIEW

**Comment by ronso0** [comment]
helps solving the root issue from #2071 "disable crossfader"

**Comment by daschuer** [comment]
Thank you fro working at this. This way you might think that the orientation buttons are configuring the xfader sides. Did you consider to arrange them like in the four decks layout? 
The look a little bit lost if you hide the xfader. 

In general, I am a little bit worried to clutter the skin with these rarely used buttons. I think the only use case in a two decks layout is to disable the xFader, which is a configuration action and not done during mixing. 

Do you like the Idea to move them to the xfader preferences? This can also control showing and hiding the xfader.

**Comment by ronso0** [comment]
> This way you might think that the orientation buttons are configuring the xfader sides. Did you consider to arrange them like in the four decks layout?

There's just not enough space in the mixer. Resizing/redesigning slider graphics for this little tweak is not worth the effort.
I guess it helps to push the buttons up a bit so that they appear less attached to the crossfader
55619196-83d60e80-5798-11e9-869e-0851cef9f20c


> The look a little bit lost if you hide the xfader.

uups,.. yes they should disappear when the xfader is hidden.

**Comment by ronso0** [comment]
> In general, I am a little bit worried to clutter the skin with these rarely used buttons. I think the only use case in a two decks layout is to disable the xFader, which is a configuration action and not done during mixing.

While I agree with you here, I'm reluctant adding another skin option (default on or Off? how to make this discoverable to users who never switch to 4 decks?)
Looking at the picture above (with shifted xfader buttons) I think they don't hurt, but make the picture complete IMO

**Comment by ronso0** [comment]
porting those changes to Deere is going to be a PITA as the mixer templates are hard to maintain.

**Comment by daschuer** [comment]
I am fine with this screenshot now. Is there anything left to do?

Let's discuss the whole issue here:
https://github.com/mixxxdj/mixxx/pull/2071

**Comment by ronso0** [comment]
I still need to apply the changes from the Screenshot. that'll happen tonight I guess

**Comment by ronso0** [comment]
Ready, steady, ...

**Comment by ywwg** [comment]
thank you for this change!  it'll be very useful to me.  I have no notes :)

**Comment by uklotzde** [comment]
Ready for merge?

**Comment by ronso0** [comment]
I'd say so. I'm already working on the corresponding changes in Deere (for consistency across skins) in another branch. 
but the superordinate discussion is going on in #2071

**Comment by daschuer** [comment]
LGTM, Thank you.

**Pull request merged**
