### PR TITLE
Gitignore: Ignore common editor and tool files

### PR DESCRIPTION
**Pull request by fwcd**
I would like to revisit this section of the `.gitignore`:

```gitignore
# Don't add any custom patterns for platform-specific files like .DS_Store
# or generated by custom development tools like .vscode or .idea that don't
# affect other developers. Instead ignore those patterns through your global
# gitignore or locally in .git/info/exclude.
```

While I agree that keeping the `.gitignore` tidy is important, I think there are some arguments to be made in favor of keeping at least some, very common generated files in the repository's `.gitignore`:

- The decision to ignore some files is inherently a repository-level one. If `.vscode` is not supposed to be included in the repo, why place the burden on the developer to include this in their local gitignore? This only increases the likelihood to accidentally commit these types of files on new machines (or for new contributors looking to get started).
- Adding a few common tools like VSCode and IDEA (which are _very_ commonly used, being some of [the most popular IDEs in the world](https://insights.stackoverflow.com/survey/2021#section-most-popular-technologies-integrated-development-environment)) doesn't hurt or impact readability much. The same applies to `.DS_Store` and macOS.
- The mere fact that these files have to be mentioned in a comment on top of the `.gitignore` indicates that these are commonly excluded files and (IMO) warrant their inclusion in the repository's `.gitignore`.
- There is precedent for other tools, like Doxygen, which are currently included in the `.gitignore`.

Thoughts?

### CODE REVIEW

**Comment by robbert-vdh** [comment]
Is there ever a time you want to commit all of these files to a repo? If not, just add them to `~/.config/git/ignore` and you'll never have to worry about them. And if for whatever reason you do really want to check in your text editor's config file, or files ending in tildes, or `.DS_Store` files, then you can always forcefully `git add` them.

**Comment by fwcd** [comment]
As mentioned above, I think the value primarily lies in making it easier for new developers (and for people switching machines every now and then) to get started.

I was rather surprised that they were _not_ included when I started contributing to Mixxx, since (from my anecdotal experience) lots of very popular repos include these kinds of files:

- https://github.com/microsoft/vscode/blob/main/.gitignore#L1-L2
- https://github.com/vuejs/vue/blob/main/.gitignore#L1-L14
- https://github.com/apple/swift/blob/main/.gitignore#L37-L51
- https://github.com/facebook/react/blob/main/.gitignore#L1-L25
- https://github.com/tensorflow/tensorflow/blob/master/.gitignore#L1-L18

In fact, these types of files are often the first lines in the gitignore, indicating that they are actually pretty common files to exclude. Therefore I would pose this question the other way around and ask why they shouldn't be included in the gitignore?

**Comment by Holzhaus** [comment]
> Therefore I would pose this question the other way around and ask why they shouldn't be included in the gitignore?

They are not included because people may use any editor or IDE, and it's neither possible nor desirable to include each and every potential editor file in `.gitignore`.

- *Oh, you included VSCode's and KDevelop's files in the `.gitignore`, why no also add Sublime Text's?*
- ...
- *I see you have ignore patterns for VSCode, KDevelop, Sublime Text, Vim, Atom, emacs and CLion, why not add \$editor?*

This could go on forever.

The approach to put editor files into the global exclude file is also documented in the `gitignore` documentation:

> Which file to place a pattern in depends on how the pattern is meant to be used.
>
> - ...
> - Patterns which a user wants Git to ignore in all situations (e.g., **backup or temporary files generated by the user’s editor of choice**) generally go into a file specified by core.excludesFile in the user’s ~/.gitconfig. Its default value is $XDG_CONFIG_HOME/git/ignore. If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/ignore is used instead.

(Source: https://git-scm.com/docs/gitignore#_description)

> As mentioned above, I think the value primarily lies in making it easier for new developers (and for people switching machines every now and then) to get started.

I disagree. If you're a new developer that wants to start contributing, the best way to learn is by getting feedback.

When people commit editor files, this is usually an indication that they don't know how to use git properly and simply stage and commit everything with `git add .` or even `git commit -a` instead of using `git add  -p`, `git add -u` or staging individual files. Also, they probably don't know that it's even possible to use a global gitignore, or that you can enable `commit.verbose` to review the diff while writing the commit message. This is stuff you can point out during code review.

**Comment by Holzhaus** [comment]
> * There is precedent for other tools, like Doxygen, which are currently included in the `.gitignore`.

This is not a precedent. We ship a `Doxyfile` for generating documentation, and use `///` style comments in our code (so that it's included in the docs), so it makes sense to add it in `.gitignore`. We do not ship any IDE or editor configs.

**Comment by fwcd** [comment]
> I see you have ignore patterns for VSCode, KDevelop, Sublime Text, Vim, Atom, emacs and CLion, why not add $editor?

If it's a reasonably popular editor, why not? Is there any harm in dedicating maybe even a few dozen lines in the gitignore to a few popular editors and IDEs, considering it's standard practice across the industry? The gitignore is perhaps one of the smallest files in the entire repository, changes pretty rarely and if it makes it easier to get going with a fresh clone, that seems like a reasonable cost to me.

> Is there ever a time you want to commit all of these files to a repo?

Yes, e.g. a dotfiles repo often include such files.

To me, I generally like to state these kinds of repo-level decisions in the repository, since I generally like to keep configurations as local as possible. So what I end up doing is customizing `.git/info/exclude` in every single clone of Mixxx (as I'm sure many other contributors do). Is this really better than dedicating a few lines in the `.gitignore`?

**Comment by fwcd** [comment]
Okay, but in favor of keeping this discussion short and not bikeshedding too much, I'll close this. The general consensus seems to be to keep it the way it is and I respect that decision.

**Pull request closed without merging**
