### PR TITLE
Beats as autodj fade duration

### PR DESCRIPTION
**Pull request by jclaveau**
This is a first attempt to teach autodj to start the incoming track after an integer number measures of the outgoing one.

I use it for almost 3 weeks now and it works well.

What have been done : 
- The unit text in the autodj ("sec.") is now a button that can be toggled between seconds and beats. 
- There are now to transition durations saved in conf : in beats or in seconds. I chose to save two values and to don't convert them when changing the unit as I think it defines two different usages : "Seconds" is adapted for short transition of tracks that are not synced. "Beats" is adapted to the opposite (typically electronic music where breaks should happen together).
- When the duration is defined as a umber of beats, Mixxx will look for the beginning of the last measure of the outgoing track before this duration, and start the incoming there (this is required as most tracks won't finish at the end of a measure).

Some questions are opened : 
- Developing that, I realized that I had to count a number of measures from the beginning of the previous track so I wonder if "Measures" wouldn't be better than "Beats" as new unit.
- The computation of the starting beat is made from the information provided by the tags of the track. It would maybe be more accurate if i based it on the beats list of the track.
- I have no controller to try to bind this, so I'm absolutely not sure it should be made like that. 

Things to do : 
- Learn how to test it and do it.

### CODE REVIEW

**Comment by daschuer** [comment]
Hi

Thank you for working on this, it bugs me as well, since in the current implementation the duration time is wrong once a track is stretched.   

> typically electronic music where breaks should happen together. 

Can you explain the use case a bit more. I am probably not experienced enough to understand that.  

> "Measures" wouldn't be better than "Beats" 

Yes of cause, we should be prepared for that. We had already a discussion, to detect the downbeats and sync the tracks by that. 
Only this will be finally produce the desired results. But the issue is not trivial, not every track has a 4/4 measure. 
 
> It would maybe be more accurate if i based it on the beats list of the track. Yes, especially if we consider non const beatgrids. Mixxx should be already aware if that, in the syncing code. 
Probably @ywwg can give some hints, what is the best way to access this info.   

> Learn how to test it and do it.

Do not hesitate to ask ;-)

**Comment by daschuer** [comment]
We need to have a close look to the sec/beats/measure thing and the related use cases. 
Not sure if making all configurable is overdone. Can we hide some details from the user?

**Comment by daschuer** [comment]
I have just looked at the code. The implementation details are OK. I am also not that much concerned about the accuracy, because you will not hear if the xfader is exactly at the end at the desired beat. It is more a visual issue. Lets focus on the user interface first. 
A long term solution should use exact beat data though.

**Comment by daschuer** [comment]
I have recently pushed https://github.com/mixxxdj/mixxx/pull/555 to fix an issue with short tracks.
Would you mind to review it? I would like to merge this fist, because it is a bugfix. Unfortunately you have to resolve some merge conflicts after that. Sorry.

**Comment by midzer** [comment]
I havent tested this function yet.
Does it sync the BPM too when this new AutoDJ kicks in last x beats?

**Comment by jclaveau** [comment]
@midzer No, to keep the BPM synced I just use the normal way : long click on both sync buttons.
If the tracks are not synced, the duration will be calculated from the BPM of the outgoing track.

**Comment by jclaveau** [comment]
Hi @daschuer , thank you for the reply.

> Thank you for working on this, it bugs me as well, since in the current implementation the duration time is wrong once a track is stretched.

What i have done will just compute a duration from a number of beats based on the bpm of the previous track. This duration will be used exactly like the number of seconds that already exists so i don't think it will fix the stretch issue.

> Can you explain the use case a bit more. I am probably not experienced enough to understand that.

Almost all the tracks of techno, deep house I listen have a little sound happening on a 8 * x beats. The drops almost always happen on this grid two (I can send you one or two tracks if you want).

So mixing two tracks of techno is always smoother if you start the next track when a drop, or one of this "little sound", of the previous one occurs.

That is what I tried to reproduce here.


    "Measures" wouldn't be better than "Beats"

> Yes of cause, we should be prepared for that. We had already a discussion, to detect the downbeats and sync the tracks by that. Only this will be finally produce the desired results. But the issue is not trivial, not every track has a 4/4 measure.



> It would maybe be more accurate if i based it on the beats list of the track. Yes, especially if we consider non const beatgrids. Mixxx should be already aware if that, in the syncing code.
> Probably @ywwg can give some hints, what is the best way to access this info.

I tried to use fromTrack->getBeats() to retrieve the BPM but the number of beats is not available as Beatgrid is infinite. 
The only useful thing I did with it was to compute the sample number of the first beat to get the empty duration before it and remove it from the calcul. But it was complex for not enough gain as the duration is retrieved from the tags (there is a comment of @rryan explaining it's "super inaccurate"). 
More, accessing getBeats() produced segfaults.  

The accuracy is not perfect but it works most of the time and the ui works so I considered it could be proposed.

>  Learn how to test it and do it.

Probably next weekend, an I have to finish the effect too :)

**Comment by daschuer** [comment]
> This duration will be used exactly like the number of seconds that already exists so i don't think it will fix the stretch issue.

The good news, the implementation in master uses seconds relative to an un-stretched track. 
So once we are at beats the problem is solved :-)

**Comment by daschuer** [comment]
> If the breaks are happening ... 

Thank you for you explanation, I think I got it. 
It looks like these beats / measure / drop issue is more an issue of auto detect cue in and cue out points. Lets keep this PR focused on the fade duration. A beats scale seams to be a natural solution for now. 

The matching 8 beats break raster is an issue of the quantization feature. Currently you start beat matched if you press play. Probably it is desired to measure matched or break matched. 

Id you have fun to continue working on this topic? A natural next step is to introduce fade out points. 
This allows to set a desired point manually until Mixxx engine is able to decide on its own. 
Most of the work is already done, but the code is rotting for a while. I have failed to find time to keep it merge-able. https://github.com/daschuer/mixxx/tree/advanced_autodj_2
Look at:  src/engine/cuecontrol.cpp

**Comment by Be-ing** [comment]
This pull request has not been updated in years so I am closing it to reduce the clutter of open PRs. If you fix the merge conflicts and would like to propose it for merging in the future, please reopen it.

**Pull request closed without merging**
