### PR TITLE
Mp3e2 MIDI script update

### PR DESCRIPTION
**Pull request by sblaisot**
This PR correct errors in MP3e2 script, making it pass jshint test.
Coding style also updated based on jsbeautify

### CODE REVIEW

**Comment by illuusio** [comment]
Only thing that js-beautify issues is enter at the end but jshint is quiet.

**Comment by illuusio** [comment]
Why HerculesMP3e2.controls is commented out? It have been commented out but is this needed?

**Comment by sblaisot** [comment]
HerculesMP3e2.controls is completely useless but I kept it here to be used as a reference of MP3e2 MIDI controls

comment added

**Comment by illuusio** [comment]
LGTM so this can be merged

**Comment by daschuer** [comment]
@illuusio: Do you have the access right to merge it yourselves? Try it out.

**Comment by illuusio** [comment]
Sorry I don't have merge access.. so Can't merge this :baby_symbol:

**Pull request merged**
