### PR TITLE
Extend compatible keys from 4 to 6 possible keys

### PR DESCRIPTION
**Pull request by uklotzde**
As suggested here: https://bugs.launchpad.net/mixxx/+bug/872006/comments/10

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
LGTM. Thank you. 
I consider this a bug that schould be backported to 2.2.
For many tracks it is ambiguous if they are minor or minor or even something else. 
The more is kind of random in this case.

Tests are failing now.

**Comment by uklotzde** [comment]
Sorry, I forgot to update the tests before publishing this quick fix.

**Review by daschuer — CHANGES_REQUESTED** [review]
Thank you. Please also add a CHANGELOG entry.

**Review by Holzhaus — APPROVED** [review]

**Review by daschuer — APPROVED** [review]
LGTM Thank you.

**Pull request merged**
