### PR TITLE
add bpm to preview deck in latenight

### PR DESCRIPTION
**Pull request by nopeppermint**
also add bpm to preview deck in latenight

### CODE REVIEW

**Comment by ronso0** [comment]
Easy fix LGTM
Would you mind adding
```
<Connection>
  <ConfigKey>[PreviewDeck1],track_loaded</ConfigKey>
  <BindProperty>visible</BindProperty>
</Connection>
```
to BPM so that the preview deck looks clean when it's empty?

**Comment by ronso0** [comment]
Yeah, thanks!
Here's a commit that corrects the indentations, and also uses the small sampler's keylock & eject icons (blurry, wrong size, missed in a previous PR) 2873c7a7c1
If you'd pick that this LGTM!

**Comment by daschuer** [comment]
Thank you for this PR.
Did you consider to align the buttons right in the small sampler view? 
The buttons are jumping with the size of the bpm value.

**Comment by nopeppermint** [comment]
I now also made the small sampler play button a little bit smaller, now they are as heigh as the preview deck play button:

before:
normal_sampler_button
after:
smaler_sampler_button

with this more text is visible

**Comment by daschuer** [comment]
LGTM. Greate. Thank you for all that love.

**Comment by nopeppermint** [comment]
thanks @ronso0  and @daschuer for review, hints and merge

**Comment by ronso0** [comment]
Thanks for the initial fix, but I'd rather revert f73e834 to have the bigger Play buttons, they where bigger for a reason IMO: I consider LateNight rather mouse-focused so buttons should be accessible (as big as possible with appearing oversized) because unlike the in the preview deck you'd have to hit them just in time, which becomes harder the smaller the buttons get.

Also the samplers expand button is now taller than the collapsed sampler row itself.

**Comment by nopeppermint** [comment]
ok, I am fine with that

**Pull request merged**
