### PR TITLE
Deere :: compact FX units

### PR DESCRIPTION
**Pull request by ronso0**
This is an attempt to make the FX units a little more compact.
It's not polished yet. What do you think?

before:
deere-compactfx1_before

.
now:
deere-compactfx1_now
deere-compactfx2_now

### CODE REVIEW

**Comment by daschuer** [comment]
Nice idea.

**Comment by ronso0** [comment]
expand toggle moved to the right, fixed FX controls layout.
at minimal size, with focus buttons:
deere-compact-fx_2

**Comment by ronso0** [comment]
@Be-ing What do ou think about moving the Master FX buttons to the toolbar? And rearranging the mixer knobs a bit?
before:
deere-fx-mixerbar-before


after, #1848 merged:
deere-fx-mixerbar-after

**Comment by Be-ing** [comment]
Nice, I like this. I think it makes sense following our [discussion on Zulip about the effects GUI](https://mixxx.zulipchat.com/#narrow/stream/109171-development/subject/Custom.20effects.20GUI/near/136030588).

> What do ou think about moving the Master FX buttons to the toolbar? And rearranging the mixer knobs a bit?

Does it fit with the booth gain knob too? Regardless, it's a bit cluttered up there. It would help if we replaced the buttons with text, which takes up a lot of space, with icons.

**Comment by ronso0** [comment]
> Does it fit with the booth gain knob too?

Not really, the center is about the same before/after. Labels get squeezed at minimal size..
As you may know I prefer icons over text, let's talk about that after #1848

**Comment by ronso0** [comment]
wookay, this is how it looks now.

Finally, compact units aren't stretching horizontally anymore when the opposing unit is expanded.
And I removed the META label, hope that's okay. It kinda felt obsolete since the label isn't there when the unit's collapsed, and Super/Mix don't have a label as well.

Please test!
deere-compact-fx-after

**Comment by Be-ing** [comment]
Hmm... aesthetically something feels a bit odd about the collapsed view. Maybe try not having the expand button and the FX# label not on the same row?

**Comment by ronso0** [comment]
> Hmm... aesthetically something feels a bit odd about the collapsed view. Maybe try not having the expand button and the FX# label not on the same row?

I see what you mean. The label doesn't fit in between expand adn Pfl button, the unit would need to grow then. Or what do you have in mind?
I could try a border around the label, or group it with the expand toggle in another way:
deere-fxlabel-border

**Comment by Be-ing** [comment]
How does it look with the expand button and headphone button side by side?

**Comment by ronso0** [comment]
> How does it look with the expand button and headphone button side by side?

Will be tricky, they're differnetly sized. Also, the FX label is the header so it should stay at the top IMO

**Comment by ronso0** [comment]
The rules I try to follow:
- FX = header
- expand toggle sits in the top-right corner

So they could be grouped with a border like pictured above, or the expand toggle is stretched and includes the FX label:
deere-fxlabel-button

**Comment by Be-ing** [comment]
Hm, that looks better, but I'm not certain it's what we should ultimately go with. Perhaps we can merge that and if we come up with better ideas later, open a new PR?

**Comment by ronso0** [comment]
> Hm, that looks better, but I'm not certain it's what we should ultimately go with. Perhaps we can merge that and if we come up with better ideas later, open a new PR?

I agree. Will implement that later on.
For consistency the sampler expand toggle goes to the right, as well:
deere-sampler-expand

Only drawback: the Library expand toggle at the left looks kinda lost now. Should we move that to the right side of the search box?

**Comment by ronso0** [comment]
that's how it would look like:
deere-lib-expand

**Comment by ronso0** [comment]
I just force-pushed to clean up the commits a bit:
- merge FX label expand toggle
- move sampler expand toggle
- move library expand toggle right nex to search bar

deere-compactfx-finish

**Comment by ronso0** [comment]
@Be-ing Any objections? Ready to merge?

**Comment by Be-ing** [comment]
Something about the mix knob being adjacent to a rectangular button looks a little odd, but I think this does improve the design. Perhaps if you come up with an idea to improve that you can open a new PR.

**Pull request merged**
