### PR TITLE
Add a GPG signing key for PPA builds.

### PR DESCRIPTION
**Pull request by rryan**

### CODE REVIEW

**Comment by Be-ing** [comment]
Thanks. Please rebase on 2.3.

**Comment by Be-ing** [comment]
The build folder will be deleted imminently when we remove SCons. Please put the new file in the new packaging folder.

**Comment by rryan** [comment]
> The build folder will be deleted imminently when we remove SCons. Please put the new file in the new packaging folder.

Where is build/certificates moving to?

**Comment by Be-ing** [comment]
How about packaging/certificates?

**Comment by daschuer** [comment]
I would prefer not to put the certificates to the source tree. Let's put the password an the certificate itself to GitHub.
There is a GitHub action we can use to install the cert to gpg of the building machine.

I think that makes no difference for the process but is an extra safety net against brut force attacks.

**Comment by daschuer** [comment]
Check out this:
https://github.com/marketplace/actions/import-gpg

**Comment by daschuer** [comment]
Hopefully it is password protected.
After publishing it here, you may consider to create a new one and invalidatd this one.

**Review by daschuer — APPROVED** [review]
Please don't merge.

**Comment by daschuer** [comment]
I just head some issues with the GPG Key on Jenkins, because LGTM it is still your old name "RJ Ryan". So I had to change the package maintainer back. 
Can you create a new key with your new name then? 
Thank you.

**Comment by rryan** [comment]
> I would prefer not to put the certificates to the source tree. Let's put the password an the certificate itself to GitHub.
> There is a GitHub action we can use to install the cert to gpg of the building machine.
> 
> I think that makes no difference for the process but is an extra safety net against brut force attacks.

It is AES encrypted with a password. I don't see a risk to this, anymore than the other signing keys we already have in our tree? If you want to revisit the overall approach to storing certs encrypted in our tree then that should be discussed, but this is not any different than the other keys currently checked in.

**Comment by rryan** [comment]
> I just head some issues with the GPG Key on Jenkins, because LGTM it is still your old name "RJ Ryan". So I had to change the package maintainer back.
> Can you create a new key with your new name then?
> Thank you.

Hmmm, I don't understand -- for this key, I made the identity `The Mixxx Development Team <team@mixxx.org>`. I was thinking we could get away from my name being on the package for cpack-produced debs.

**Comment by daschuer** [comment]
The naming issue issue happens with the key installed on Jenkins. It is fine for me to use The Mixxx Development Team <team@mixxx.org>. Who receives the mails? 

> It is AES encrypted with a password. I don't see a risk to this, anymore than the other signing keys we already have in our tree?

Probably not a real risk, the attacker needs a lot of luck to hit the password early.

However https://github.com/marketplace/actions/import-gpg does not require to have the encrypted key in the repository so there is no point to do it.

**Comment by rryan** [comment]
> However https://github.com/marketplace/actions/import-gpg does not require to have the encrypted key in the repository so there is no point to do it.

If we think it's a real risk then we should do it for all key material. What makes this one special?

**Comment by rryan** [comment]
> The naming issue issue happens with the key installed on Jenkins. It is fine for me to use The Mixxx Development Team [team@mixxx.org](mailto:team@mixxx.org). Who receives the mails?

Hm, I see -- I didn't think the old SCons scripts would be used for this key. Was that the plan?

**Comment by daschuer** [comment]
> Hm, I see -- I didn't think the old SCons scripts would be used for this key. Was that the plan?

The first step was to change to cmake but keep the versioning and the signing as it was. 
Now this is in place and we can consider changes.

**Comment by Be-ing** [comment]
I thought we had to keep using the same keys to preserve the chain of trust?

I like the idea to put both the private key and password in GH Actions. It reduces the attack surface.

**Comment by daschuer** [comment]
> If we think it's a real risk then we should do it for all key material. What makes this one special?

There is only a marginal extra risk to have the private keys in the repro. That is not he main point. 

It is more an issue, that the workflow does not requires this. So there is no point do clutter the git repro with a useless signing keys. For signing we need the password and the key. That can be piped in via the same secure channel.

**Comment by Be-ing** [comment]
Will users be bothered with a question from apt-get asking them to verify a new key?

On macOS and Windows we are more restricted IIUC because Apple and Microsoft both build trust in a key over time in their centralized systems.

**Comment by daschuer** [comment]
> Will users be bothered with a question from apt-get asking them to verify a new key?

No. in the PPA case the user trusts the PPA as source and the uploaded source package is signed. The deb itself is not signed. 
This is not necessary here. 

This is different in windows, where the installer can be downloaded form any entrusted location. 

If we decide to build the deb somewhere else and offer it for download form un-trusted locations we can sign that and are at the same stage as the windows installer.

**Comment by uklotzde** [comment]
@daschuer The approval is confusing. Anything else to do here? Then please revert your approval or convert back to draft.

**Review by daschuer — CHANGES_REQUESTED** [review]
Let's not merge this. Use GitHub instead.

**Comment by daschuer** [comment]
build-ubuntu-18.04-amd64-rryan, jenkins does not upload to PPA now. 
@rryan: Please have a look.  

To continue here, we need a certificate with a valid E-Mail Address and a password upload to Github (privat key) and the public key to the Ubuntu key server. Than we need to verify this certificate at Launchpad.

**Comment by rryan** [comment]
Added a `RRYAN_AT_MIXXX_DOT_ORG_GPG_PRIVATE_KEY` secret containing the ASCII armored GPG private key that `build-ubuntu-18.04-amd64-rryan` currently uses to sign. It isn't password protected.

```
$ gpg --list-secret-keys
sec   rsa4096 2011-02-17 [SC] [expires: 2039-06-01]
      17E22EE118129D1F1996B9536F709194D92C4947
uid           [ unknown] RJ Skerry-Ryan <rryan@mixxx.org>
uid           [ unknown] RJ Ryan <rryan@mixxx.org>
ssb   rsa4096 2011-02-17 [E]
```

**Comment by Be-ing** [comment]
Hmm it's still not uploading to the PPA https://github.com/mixxxdj/mixxx/runs/1614523520#step:22:15 :
```
 gpg: error reading key: No public key
CMake Warning at /home/runner/work/mixxx/mixxx/packaging/CPackDebUploadPPA.cmake:40 (message):
  No secret key found for "RJ Skerry-Ryan <rryan@mixxx.org>", skip signing
```

**Comment by daschuer** [comment]
Please do not mess around with the PPA. Uploading a Pull Request is nothing we should do.

**Comment by Be-ing** [comment]
It is not uploading pull requests, only the 2.3 and main branches.

**Comment by Be-ing** [comment]
https://github.com/mixxxdj/mixxx/blob/main/.github/workflows/build.yml#L266

**Pull request closed without merging**
