### PR TITLE
Merge 2.4 into 2.5

### PR DESCRIPTION
**Pull request by Swiftb0y**
Lets see what CI says about this.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
LGTM! CI is pass! Thank you!

**Comment by ronso0** [comment]
Great!
I tried to merge 2.5 into main the other day, but there are conflicts I don't know how to deal with, especially the translations.
Could someone take a look please?

**Comment by Holzhaus** [comment]
@Swiftb0y we cannot do merges like this if the comment in our `.gitattributes` is correct. Because these kind of GUI merges do not honor it, at least as far I remember.

**Comment by Swiftb0y** [comment]
right, but no translation changes were made in this case judging by the diff. So in this specific case I'm fairly certain we didn't break anything.

**Pull request merged**
