### PR TITLE
Native Instruments Traktor Z1: Create controller mapping

### PR DESCRIPTION
**Pull request by fasterthanwhatever**

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Welcome at Mixxx!
As a first-time contributor we need you to sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

**Comment by JoergAtGithub** [comment]
Normally mappings go in the stable release, but in this case 2.4 makes sense, because there are a lot of improvements for HID in 2.4. And we are not far from the release.

**Comment by JoergAtGithub** [comment]
To fix the pre-commit fails automatically, please set up automatic code checking: https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking

**Comment by JoergAtGithub** [comment]
Please move the code from common-hid-utils.js into Traktor-Kontrol-Z1-scripts.js.

**Comment by JoergAtGithub** [comment]
Don't forget to sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ)
This is a mandatory requirement, without we can't merge this PR into Mixxx.

**Comment by JoergAtGithub** [comment]
You merged mixxx/Main into your branch, but your PR is targeted to mixxx/2.4. Please revert this by a hard reset of your branch to the last correct commit, which is 4edf59dcda533e1b3842310abc58f1a1861386cd
After that, you can merge the correct branch mixxx/2.4

**Comment by fasterthanwhatever** [comment]
> 

hopefully good now ...

thanks for having patience with me

**Comment by fasterthanwhatever** [comment]
is the pre-commit failure caused by me using v 3.3.3?

**Comment by JoergAtGithub** [comment]
What do you mean with v 3.3.3?

**Comment by JoergAtGithub** [comment]
The best way to fix pre-commit issues is to install pre-commit locally on your system, as described here: https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking
Than it will fix these issues automatically before every commit.
Alternatively, you can download the pre-commit.patch file from the artifacts of this PR
grafik
unzip it, and apply it using:
`git apply pre-commit.patch`

**Comment by fasterthanwhatever** [comment]
with v 3.3.3 i meant pre-commit version. i think that i forgot to run 

pre-commit install
pre-commit install -t pre-push


i've been installing and uninstalling it several times. i was struggling because arch linux only supports an older not supported version on pre-commit.

anyway, now all checks seem to have passed.

**Comment by JoergAtGithub** [comment]
@fasterthanwhatever Did you sign the contributor agreement? I can't find your agreement in our list - maybe your real name differs too much from your GitHub user name?

**Comment by fasterthanwhatever** [comment]
signed

**Comment by JoergAtGithub** [comment]
Superseded by #12366

**Pull request closed without merging**
