### PR TITLE
utf16 file path support for Windows

### PR DESCRIPTION
**Pull request by daschuer**
This merged the related 1.12 commit and adds a seek test for wavpack. 

It actually discovered an issue with the seeking, which is fixed now as well.
I have also noticed that our m4a test is broken. I have disabled it for now.

### CODE REVIEW

**Comment by uklotzde** [comment]
@daschuer I've sent you a fixed version of cover-test.m4a that allows us to keep the tests for AAC files enabled.

**Comment by daschuer** [comment]
Thank you.

**Comment by daschuer** [comment]
m4a test works and a ffmpeg utf16 solution is also in place (my first info where outdated) 

However the test using the ffmpeg build does not end. it continously prints 
```
Expected: contReadData[readSampleOffset]
Which is: -1
Mismatch in /home/daniel/workspace/advanced_autodj_3/src/test/id3-test-data/cover-test-png.mp3 at seek frame index 380000 for read sample offset 177
src/test/soundproxy_test.cpp:147: Failure
Value of: seekReadData[readSampleOffset]
  Actual: 0
Expected: contReadData[readSampleOffset]
Which is: -1
Mismatch in /home/daniel/workspace/advanced_autodj_3/src/test/id3-test-data/cover-test-png.mp3 at seek frame index 380000 for read sample offset 178
src/test/soundproxy_test.cpp:147: Failure
Value of: seekReadData[readSampleOffset]
  Actual: 0
Expected: contReadData[readSampleOffset]
Which is: -1
Mismatch in /home/daniel/workspace/advanced_autodj_3/src/test/id3-test-data/cover-test-png.mp3 at seek frame index 380000 for read sample offset 179
src/test/soundproxy_test.cpp:147: Failure
Value of: seekReadData[readSampleOffset]
  Actual: 0
Expected: contReadData[readSampleOffset]
Which is: -1
Mismatch in /home/daniel/workspace/advanced_autodj_3/src/test/id3-test-data/cover-test-png.mp3 at seek frame index 380000 for read sample offset 180
src/test/soundproxy_test.cpp:147: Failure
Value of: seekReadData[readSampleOffset]
  Actual: 3.05176e-05
Expected: contReadData[readSampleOffset]
Which is: -1
Mismatch in /home/daniel/workspace/advanced_autodj_3/src/test/id3-test-data/cover-test-png.mp3 at seek frame index 380000 for read sample offset 181
src/test/soundproxy_test.cpp:147: Failure
Value of: seekReadData[readSampleOffset]
  Actual: 3.05176e-05
Expected: contReadData[readSampleOffset]
Which is: -0.372894
Mismatch in /home/daniel/workspace/advanced_autodj_3/src/test/id3-test-data/cover-test-png.mp3 at seek frame index 380000 for read sample offset 182
src/test/soundproxy_test.cpp:147: Failure
Value of: seekReadData[readSampleOffset]
  Actual: 3.05176e-05
Expected: contReadData[readSampleOffset]
Which is: 0.374817
Mismatch in /home/daniel/workspace/advanced_autodj_3/src/test/id3-test-data/cover-test-png.mp3 at seek frame index 380000 for read sample offset 183
src/test/soundproxy_test.cpp:147: Failure
Value of: seekReadData[readSampleOffset]
  Actual: 3.05176e-05
Expected: contReadData[readSampleOffset]
Which is: 0.999969
Mismatch in /home/daniel/workspace/advanced_autodj_3/src/test/id3-test-data/cover-test-png.mp3 at seek frame index 380000 for read sample offset 184
src/test/soundproxy_test.cpp:147: Failure
Value of: seekReadData[readSampleOffset]
  Actual: 3.05176e-05
Expected: contReadData[readSampleOffset]
Which is: 0.999969
Mismatch in /home/daniel/workspace/advanced_autodj_3/src/test/id3-test-data/cover-test-png.mp3 at seek frame index 380000 for read sample offset 185
src/test/soundproxy_test.cpp:147: Failure
Value of: seekReadData[readSampleOffset]
  Actual: 3.05176e-05
Expected: contReadData[readSampleOffset]
Which is: 0.999969
Mismatch in /home/daniel/workspace/advanced_autodj_3/src/test/id3-test-data/cover-test-png.mp3 at seek frame index 380000 for read sample offset 186
src/test/soundproxy_test.cpp:147: Failure
Value of: seekReadData[readSampleOffset]
  Actual: 3.05176e-05
^C


```

**Comment by uklotzde** [comment]
I haven't built and run the ffmpeg version for quite some time now. The last 
thing I remember was that the ffmpeg SoundSource did not pass our seek tests.

**Comment by daschuer** [comment]
I have now skipped the ffmpeg test for mp3. 
This proves our concept to use ffmpeg as a backup soundsource only ;-) 

Can we merge it?

**Comment by uklotzde** [comment]
I've not tested this branch myself, but I haven't seen any suspicious 
changes in your commits. If the tests complete successfully it should be 
good enough for merging.

Afterwards I will rebase my tag writing branch on master and use it.

**Comment by daschuer** [comment]
Ah, fine, then I will merge. Thank you for review.

**Pull request merged**
