### PR TITLE
Sync Lock: restore Explicit Leader mode

### PR DESCRIPTION
**Pull request by ywwg**

### CODE REVIEW

**Comment by daschuer** [comment]
LGTM, Is this intended to merge to master now?

**Comment by Holzhaus** [comment]
I thought this was for experimenting with different sync modes (w/ or w/o internal clock).

**Comment by ywwg** [comment]
This basically just turns explicit master back on so we can play around with it and try different things.  It's not so much about finishing anything but getting to a place where we can experiment with what we have.

**Comment by ywwg** [comment]
yes the idea is to merge to master -- @daschuer can you do that?

**Comment by daschuer** [comment]
Yes sure. We just need to be aware that this is still bugy.

**Pull request merged**
