### PR TITLE
VMS4: Disable vertical touch strips while deck is playing

### PR DESCRIPTION
**Pull request by uklotzde**
@Pegasus-RPG I'm not able to test this. I think it makes sense to prevent seeking to random positions inside a track while it is playing.

https://bugs.launchpad.net/mixxx/+bug/1663881

### CODE REVIEW

**Comment by Be-ing** [comment]
Seeking with the touch strip while playing may be desired when the track isn't audible in the master mix, so I think shift + touch strip would be better. That is how the Mixtrack Pro 3 mapping does it.

**Comment by uklotzde** [comment]
Ok, then I'm out. I don't own this controller and the MIDI commands are not documented thoroughly.

**Comment by Be-ing** [comment]
@Pegasus-RPG do you have access to a VMS4? It would be good if you could implement the shift + touch strip functionality described above. Otherwise I think this should be merged as is.

**Comment by Pegasus-RPG** [comment]
I do have both a VMS4 and the Traktor Edition. I agree, needle drop functionality is useful. Plus now that we have effects, those strips can be used for their intended purpose. Go ahead and merge this now since I'll need a JS function to add that anyway and this stubs it out.

**Comment by richrd** [comment]
I know this is merged, but I just had to come by to say a big thanks for doing this. This was so annoying that I had to disable the strips entirely. Now I can use them again in a sane way :+1: :heart:

**Comment by uklotzde** [comment]
Thank you for your feedback 👌 Great to know that we could at least help 2 people with this simple fix.

**Comment by Pegasus-RPG** [comment]
@richrd I'm updating the VMS4 preset and am wondering how often this issue was happening to you. The strips also send "touch" and "release" messages and I wonder if by gating on those we could still eliminate the spurious events while still allowing seeking during playback. To confirm this, I'd need to see a MIDI dump when the issue occurs for you. (My controller only does it once in a couple hours at random.)

**Comment by Pegasus-RPG** [comment]
Or I could just implement that change and have you test it. :) PM me on the forums if you'd like to help.

**Comment by Pegasus-RPG** [comment]
Never mind, I just caught mine doing it and it does send touch and release events as well, unfortunately.

**Pull request merged**
