### PR TITLE
In ``Help --> Send Us Feedback``, use new link to updated 2.1 feedbac…

### PR DESCRIPTION
**Pull request by esbrandt**
…k form.

The 2.0 form has accumulated hundreds of responses over the last few years.

Please [test the new form](https://goo.gl/forms/IHf3JK7Q9DXmExXc2), so we could improve eventually.

Whats new?
- Conditional feedback. If the user use/plan to buy controllers, allow to select from brands he owns/plans to buy. Allows for more granular feedback data.
- Slightly improve the ``Please rank the following features in order of importance to you:``.
 We implemented some of the mentioned features mentioned in the old forms.

Should we disallow feedback in the forms of older versions, and point them to upgrade to the most recent version? We still get occasional responses even for v1.12.

### CODE REVIEW

**Comment by nopeppermint** [comment]
> so we could improve eventually

 maybe add a Question about the Skin they use mostly/preferred?
And what they like/miss in those skins

**Comment by daschuer** [comment]
Instead of hard coding the form link, we should store a static link to mixxx.org and redirect to any form that should be filled. That way we can change the form without updating Mixxx.

**Comment by rryan** [comment]
> Instead of hard coding the form link, we should store a static link to mixxx.org and redirect to any form that should be filled. That way we can change the form without updating Mixxx.

While that allows us to change the form, it prevents us from making future changes to the URL structure of the site without putting redirects in place. I'm for keeping things the way they are.

**Comment by rryan** [comment]
> That way we can change the form without updating Mixxx.

Just to point out, Google Forms can be updated without changing the form. Do you mean we can change the form to an entirely different form? Or do you mean for the case where we've forgotten to update the form in a release?

**Comment by Pegasus-RPG** [comment]
2.1 Release checklist on the wiki updated to include this item. And yes, @esbrandt I think we should put a message at the top of older forms directing people to the latest one.

**Comment by esbrandt** [comment]
Follow-up:
--

* **Users on v1.10-v1.12**
  The ``Help --> Send Feedback`` form does not accept responses anymore. The following message is displayed:

  ``
You are running an outdated version of Mixxx. Please use the latest version available.
Download your free copy today!
https://mixxx.org/
  ``

* **Users on v2.0.x**
  The ``Help --> Send Feedback`` form does still accept responses, and ``You are running an outdated version...`` is displayed too.

*  The question about controller usage was changed form optional to mandatory, since the form logic does not allow to conditionally jumps to sections if the base question is skipped (answer empty).
* As suggested, a question about skin usage was added.

**Pull request merged**
