### PR TITLE
allow win uninstaller to be run silently

### PR DESCRIPTION
**Pull request by sblaisot**
This PR adds defaults to windows uninstaller dialogs to allow it to run silently (if /S parameter is added)

### CODE REVIEW

**Comment by sblaisot** [comment]
This PR is a prerequisite to wix installer. My goal is to uninstall previous installation before installing new version with wix to avoid conflicts when installing over previous install (see @daschuer reply in mixxx-devel to my call for testers).
If we can have 2.0.1 include silent uninstall, migration path to 2.1 using wix installer will be easier.
upgrading from a version that do not have silent uninstaller will need extra user interaction (click yes to uninstall)

**Comment by daschuer** [comment]
LGTM. Thank you.

**Comment by sblaisot** [comment]
thanks @daschuer.
this PR was against 1.12 branch because I thought there will be a 2.0.1 soon includeing small bugfixes.
If this is not the case, we should make the same change to master/2.1

**Comment by daschuer** [comment]
We just need to merge 1.12 branch with master.

**Pull request merged**
