### PR TITLE
fix Windows build

### PR DESCRIPTION
**Pull request by Be-ing**
Looks like #1377 broke the Windows build. We urgently need reliable CI!!

### CODE REVIEW

**Comment by Be-ing** [comment]
Okay, the compile error with ratecontrol.cpp is fixed. The build is failing for an unrelated reason which has been affecting lots of AppVeyor builds seemingly randomly:
LINK : fatal error LNK1181: cannot open input file 'vamp-sdk.lib'

**Comment by sblaisot** [comment]
no, the build is failing because of 
```
[CXX] src\preferences\dialog\dlgprefdeck.cpp
dlgprefdeck.cpp
src\preferences\dialog\dlgprefdeck.cpp(459): error C2440: 'static_cast': cannot convert from 'double' to 'TrackTime::DisplayMode'
src\preferences\dialog\dlgprefdeck.cpp(459): note: Conversions between enumeration and floating point values are no longer allowed
scons: *** [win64_build\preferences\dialog\dlgprefdeck.obj] Error 2
scons: building terminated because of errors.
```

line 7274-7279 of the log

**Comment by Be-ing** [comment]
Ack, thanks for pointing that out.

**Comment by sblaisot** [comment]
you should be interested in #1440

**Comment by Be-ing** [comment]
Okay, AppVeyor build is working with this. EngineBufferE2ETest.KeylockReverseTest is failing, which I have already fixed in #1254

**Pull request merged**
