### PR TITLE
Remove half/double bpm syncing

### PR DESCRIPTION
**Pull request by ywwg**
When I was originally writing master sync I thought it would be useful to try to match wildly different bpms by dividing them in half or doubling them, e.g. matching 70bpm with 140bpm.  This hasn't been very useful in practice, creates some buggy situations, and has confused a lot of users.  Unless people actually like this feature, I think we should remove it.

### CODE REVIEW

**Comment by ronso0** [comment]
Haa, iit was just a few days ago that I used sync: deck1 playing at 65 BPM, deck2 120 BPM, and I was glad that Mixxx matched deck2 with 130 instead of pullling it dow to 65 BPM.

What are those buggy situations you refer to?

**Comment by daschuer** [comment]
Maybe we can fix it instead of remove. Can we name the buggy situations?

**Comment by ywwg** [comment]
If I recall, there were issues were around quantization and how the algorithm would choose to align the tracks.  But it's been a long time since I've tried to use this feature.

If it's useful I guess we can keep it -- mostly it was getting in the way of my other master sync changes

**Comment by daschuer** [comment]
It sounds as it is a chance to be fixed here: 
https://github.com/mixxxdj/mixxx/pull/1716

**Pull request closed without merging**
