### PR TITLE
Xfader

### PR DESCRIPTION
**Pull request by daschuer**
This PR increases the curve value form 1 .. 9 to 1 .. 1000 which allows a sharp cut hardly needed by
scratching DJs.

It keeps the CO and config interface unchanged.

The Slider has now a 1/x scale, which meeds the new insane range.

The preview graph was improved to show the edges correct.

The constant power mode is now really const over the whole range.

### CODE REVIEW

**Comment by daschuer** [comment]
This bug excludes a whole user group from Mixxx. 

The change does not touch the CO nor the config nor the GUI, so it should be nor harm to inculide it in 1.12.

Who has time and fun to review and test it? @uklotzde? 

Here the forums references: 
http://www.mixxx.org/forums/viewtopic.php?f=7&t=7194
http://www.mixxx.org/forums/viewtopic.php?f=1&t=4115  
http://www.mixxx.org/forums/viewtopic.php?f=1&t=4242
http://www.mixxx.org/forums/viewtopic.php?f=1&t=2824
http://www.mixxx.org/forums/viewtopic.php?f=7&t=1808&p=11628

**Comment by uklotzde** [comment]
@daschuer Ok, I will review the code and pull the changes into my main branch for testing purposes. Feedback might take some time, at least until next weekend.

**Comment by daschuer** [comment]
Thank you :-)

**Comment by uklotzde** [comment]
During a short test the cross fader didn't work as expected after playing around with various settings, especially when cutting. I didn't have the time to find out why and instead reverted back to my standard version. Will test again and compare the results with the current behaviour.

**Comment by daschuer** [comment]
The desired behaviour for cutting is: 
Additive: Fully Left -> 100 % left deck / Center area -> both decks / Fully right -> 100 % right deck 
Constant power: Left half -> 100 % left deck / Right half -> 100 % right deck

**Comment by daschuer** [comment]
Comments addressed. 
I have also added a unittest to verify the scaling function.
@uklotzde: Do you have now a better view how the slider should work?

**Comment by uklotzde** [comment]
I think I know how the xfader should work ;) I tested with the controller connected, so it might be an issue with the CO mapping. Just didn't have the time for further investigations. More detailed results will follow.

**Comment by uklotzde** [comment]
The name "LinearRescaler" would be more precise.

We could even think about replacing the min/max limits by:
offset = min
scale = max - min
An inverse linear mapping with max < min is allowed and the terms "min" and "max" don't reflect this. Then the calculation becomes even simpler:
norm = (in - inOffset) / inScale;
out = outOffset + outScale * norm;

**Comment by daschuer** [comment]
The class could be named "OneByXRescaler"
And we need a member function toOneByX and fromOneByX.

It depends on the other future use case, if the will be a benefit by having such a class. 
In this case it will increase the memory footprint and will move the limits out of sight (which can be good or bad ... a matter of taste) 
Building such a class as a template and making in bulletproof for a generic use, will be some extra amount of work, which I like to avoid now.  
The refactoring can be done, if we know the other user requirements. 
Will this be OK for you?

**Comment by daschuer** [comment]
I hope the rescaler code is clear now.

**Comment by daschuer** [comment]
Cool, Thank you for the test. Is it OK for you to merge it like it is and postpone further refactoring to the time, wen we want to reuse the rescaler functions?

**Comment by uklotzde** [comment]
Yes, I think this is ok.

**Comment by uklotzde** [comment]
@daschuer Do you have a reference that explains the theory behind the 1/x scaling and how it is used here? It would be helpful to add this to the code comments.

**Comment by daschuer** [comment]
The original range of m_transform was 1 ... 8 controlled by a linear slider. 
For a sharp cut we need an insane value of 1000. A linear slider does not suit any more, since the original range will be at 0,8 % of the slider. 
The 1/x range moves the 8 point to 88 % while the additional 8 .. 1000 is on the remaining 12 % 
http://www.andsol.org/geom/zach/hip.gif

**Comment by daschuer** [comment]
Thank you for review.

**Comment by esbrandt** [comment]
Nice fix for a longstanding issue, thanks.

Does this PR fix
https://bugs.launchpad.net/mixxx/+bug/829538 and/or
https://bugs.launchpad.net/mixxx/+bug/1516452 ?

Please mark fixed then on LP.

**Pull request merged**
