### PR TITLE
Revert "Allow maximum deck speed of 4x normal" in 2.1 branch

### PR DESCRIPTION
**Pull request by Be-ing**
Reverts mixxxdj/mixxx#1662

### CODE REVIEW

**Review by daschuer — CHANGES_REQUESTED** [review]
Let's not merge this as long we have not identified an issue.

**Comment by daschuer** [comment]
For the discussion see https://github.com/mixxxdj/mixxx/pull/1662

**Comment by daschuer** [comment]
This is obsolete after the latest discussion on Zulip.

**Comment by Be-ing** [comment]
What Zulip discussion are you referring to? I don't recall a Zulip discussion about this. The discussion is in #1662.

**Comment by daschuer** [comment]
https://mixxx.zulipchat.com/#narrow/stream/109121-core-team/topic/2.2E1.2E2

**Comment by Be-ing** [comment]
> Let's not merge this as long we have not identified an issue.

We have [identified an issue](https://github.com/mixxxdj/mixxx/pull/1878#discussion_r229662648).

**Comment by rryan** [comment]
I agree this shouldn't have gone in a point release...  we probably need some refactoring of the rate slider like @daschuer has been working on, plus a hard cap against it going to zero or negative.

**Comment by daschuer** [comment]
Is this superseded by https://github.com/mixxxdj/mixxx/pull/1878 and can be closed?

**Comment by daschuer** [comment]
I will prepare a 2.1.7 release now.

**Pull request closed without merging**
