### PR TITLE
FramePos improvements

### PR DESCRIPTION
**Pull request by Holzhaus**
Some minor improvements to the FramePos class added in #4043.

### CODE REVIEW

**Comment by Holzhaus** [comment]
This should ensure that all calculations with frame positions are well defined, and we never end up with weird Nan values in the engine.

**Comment by uklotzde** [comment]
I am still worried about the inconsistencies introduced by the special equality comparisons ==/!= that are incompatible with </<=/>/>=.

How about reverting them and only adding the assertion `DEBUG_ASSERT(lhs.isValid() == rhs.isValid()`?

**Comment by Holzhaus** [comment]
Actually the striked through suggestion from your comment is already the case.

The comparison operators all use `value()` which raises a debug assertion if the value is invalid. Exceptions are `==` and `!=`. There return true if both positions are valid and their value matches, or both are invalid. Otherwise they return false.

**Comment by Holzhaus** [comment]
What kind of issues do you expect?

IMHO allowing comparisons of valid and invalid values is more confusing. If you 
make a check `loopStart <= loopEnd` and due to some engine bug, `loopEnd` is set to infinity (and the FramePos is invalid), the check would return `true` and you won't notice. With this implementation, a debug assertion is raised, which indicates your assumption that both values are valid is wrong.

Do you have a use case for comparisons between valid and invalid values, or two invalid values?

**Comment by uklotzde** [comment]
I didn't consider the debug assertions that already prevent using </<=/>/>= with invalid values. Then there should be no inconsistencies.

**Review by uklotzde — APPROVED** [review]
Thank you! LGTM

**Pull request merged**
