### PR TITLE
merge 2.3

### PR DESCRIPTION
**Pull request by ronso0**
tests were failing locally so I open this PR.
```
	157 - ControlObjectScriptTest.CompressingProxyCompareCount1 (Failed)
	158 - ControlObjectScriptTest.CompressingProxyCompareValue1 (Failed)
	159 - ControlObjectScriptTest.CompressingProxyCompareCount2 (Failed)
	160 - ControlObjectScriptTest.CompressingProxyCompareValue2 (Failed)
	161 - ControlObjectScriptTest.QueuedCompareCount2 (Failed)
	162 - ControlObjectScriptTest.QueuedCompareValue2 (Failed)
	163 - ControlObjectScriptTest.CompressingProxyCompareCountMulti (Failed)
	164 - ControlObjectScriptTest.CompressingProxyCompareValueMulti (Failed)
	165 - ControlObjectScriptTest.CompressingProxyMultiConnection (Failed)
	166 - ControlObjectScriptTest.QueuedFallbackMultiConnection (Failed)
	167 - ControlObjectScriptTest.CompressingProxyManyEvents (Failed)
```
Any ideas why @JoergAtGithub ?

### CODE REVIEW

**Review by uklotzde — APPROVED** [review]
CI succeeded, LGTM

Nevertheless, we need to find out the reason for the local test failures. I didn't experience any issues.

**Comment by ronso0** [comment]
*comment race condition :)*

**Comment by JoergAtGithub** [comment]
None of the changed files is related to this test. Can it be, that just the testcase was rebuilt/pulled from upstream, but not the Mixxx code itself? Was `src/control/controlobjectscript.cpp` up to date in your local working copy?

**Comment by ronso0** [comment]
Of course merging 2.3 doesn't touch CompressingProxy. I built with feshly pulled `main`.
I just cleaned my build dir and reconfigured, will see if that fixes it.

**Comment by ronso0** [comment]
Hmm, it's still only those test that fail
```
	157 - ControlObjectScriptTest.CompressingProxyCompareCount1 (Failed)
	158 - ControlObjectScriptTest.CompressingProxyCompareValue1 (Failed)
	159 - ControlObjectScriptTest.CompressingProxyCompareCount2 (Failed)
	160 - ControlObjectScriptTest.CompressingProxyCompareValue2 (Failed)
	161 - ControlObjectScriptTest.QueuedCompareCount2 (Failed)
	162 - ControlObjectScriptTest.QueuedCompareValue2 (Failed)
	163 - ControlObjectScriptTest.CompressingProxyCompareCountMulti (Failed)
	164 - ControlObjectScriptTest.CompressingProxyCompareValueMulti (Failed)
	165 - ControlObjectScriptTest.CompressingProxyMultiConnection (Failed)
	166 - ControlObjectScriptTest.QueuedFallbackMultiConnection (Failed)
	167 - ControlObjectScriptTest.CompressingProxyManyEvents (Failed)
```
details:
[CompressProxyTests_Fail.txt](https://github.com/mixxxdj/mixxx/files/7786807/CompressProxyTests_Fail.txt)

**Comment by JoergAtGithub** [comment]
The details show the correct warning messages from the CompressingProxy in the error cases. So the proxy itself is operating.
But something with Google-Mock seems to fail. Mocked is only the function slotValueChanged, and arguments are used to distinguish the expected calls of it.

I wonder about this message:
GMOCK WARNING:
/home/ronso/Downloads/mixxx_source/src/master/src/test/controlobjectscripttest.cpp:100: Too many actions specified in EXPECT_CALL(*coScript2, slotValueChanged(_, _))...

Do you use the same Googletest/Googlmock than on CI?

**Comment by ronso0** [comment]
> Do you use the same Googletest/Googlmock than on CI?

How do I find out?
Anyway, I just re-ran `tools/debian_buildenv.sh` and got `lcov` installed.. :shrug:
Now the tests pass :+1: 

Should cmake require `lcov` when building tests to avoid such errors?

**Comment by JoergAtGithub** [comment]
I found out, that gtest and gmock are always the same, because they are taken from the lib directory in ./mixxx.
I can only guess, that the execution of tools/debian_buildenv.sh fixed something else in your environment.

**Comment by JoergAtGithub** [comment]
@ronso0 I looked on the posted test output again, this time on my laptop screen, last time I read it on my phone. Now I see, that multiple tests seem to run overlapped in parallel, while on CI, they run stricly serial.

Your local output (Start of **ManyEvents** followed by result of **CompareCountMulti**):
`        Start 167: ControlObjectScriptTest.CompressingProxyManyEvents
161/729 Test #163: ControlObjectScriptTest.CompressingProxyCompareCountMulti................................***Failed    0.21 sec`
CI output:
`        Start 167: ControlObjectScriptTest.CompressingProxyManyEvents
167/729 Test #167: ControlObjectScriptTest.CompressingProxyManyEvents ......................................   Passed    0.06 sec`

Could you try to execute only a single test, intead of all. Does it pass than?

**Comment by ronso0** [comment]
Hmm fails, too:
``` sh
$ ctest -R ControlObjectScriptTest.CompressingProxyCompareCount1 --output-on-failure

Test project /home/ronso/Downloads/mixxx_source/src/master_build/Debug
    Start 157: ControlObjectScriptTest.CompressingProxyCompareCount1
1/1 Test #157: ControlObjectScriptTest.CompressingProxyCompareCount1 ...***Failed    0.14 sec
QML debugging is enabled. Only use this in a safe environment.
Note: Google Test filter = ControlObjectScriptTest.CompressingProxyCompareCount1
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ControlObjectScriptTest
[ RUN      ] ControlObjectScriptTest.CompressingProxyCompareCount1

GMOCK WARNING:
/src/test/controlobjectscripttest.cpp:100: Too many actions specified in EXPECT_CALL(*coScript2, slotValueChanged(_, _))...
Expected to be never called, but has 1 WillOnce()./src/master/src/test/controlobjectscripttest.cpp:104: Failure
Actual function call count doesn't match EXPECT_CALL(*coScript1, slotValueChanged(_, _))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[  FAILED  ] ControlObjectScriptTest.CompressingProxyCompareCount1 (0 ms)
[----------] 1 test from ControlObjectScriptTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ControlObjectScriptTest.CompressingProxyCompareCount1

 1 FAILED TEST


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.17 sec

The following tests FAILED:
	157 - ControlObjectScriptTest.CompressingProxyCompareCount1 (Failed)
Errors while running CTest
```

**Comment by JoergAtGithub** [comment]
Here the local output for the same test looks as follows:

```
C:\Users\Joerg\source\repos\JoergAtGithub\mixxx\build\x64__portable>ctest -R ControlObjectScriptTest.CompressingProxyCompareCount1 --verbose
UpdateCTestConfiguration  from :C:/Users/Joerg/source/repos/JoergAtGithub/mixxx/build/x64__portable/DartConfiguration.tcl
Parse Config file:C:/Users/Joerg/source/repos/JoergAtGithub/mixxx/build/x64__portable/DartConfiguration.tcl
UpdateCTestConfiguration  from :C:/Users/Joerg/source/repos/JoergAtGithub/mixxx/build/x64__portable/DartConfiguration.tcl
Parse Config file:C:/Users/Joerg/source/repos/JoergAtGithub/mixxx/build/x64__portable/DartConfiguration.tcl
Test project C:/Users/Joerg/source/repos/JoergAtGithub/mixxx/build/x64__portable
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 157
    Start 157: ControlObjectScriptTest.CompressingProxyCompareCount1

157: Test command: C:\Users\Joerg\source\repos\JoergAtGithub\mixxx\build\x64__portable\mixxx-test.exe "--gtest_filter=ControlObjectScriptTest.CompressingProxyCompareCount1" "--logLevel" "info"
157: Test timeout computed to be: 1500
157: Note: Google Test filter = ControlObjectScriptTest.CompressingProxyCompareCount1
157: [==========] Running 1 test from 1 test suite.
157: [----------] Global test environment set-up.
157: [----------] 1 test from ControlObjectScriptTest
157: [ RUN      ] ControlObjectScriptTest.CompressingProxyCompareCount1
157:
157: GMOCK WARNING:
157: ..\..\src\test\controlobjectscripttest.cpp(100): Too many actions specified in EXPECT_CALL(*coScript2, slotValueChanged(_, _))...
157: Expected to be never called, but has 1 WillOnce().[       OK ] ControlObjectScriptTest.CompressingProxyCompareCount1 (29 ms)
157: [----------] 1 test from ControlObjectScriptTest (29 ms total)
157:
157: [----------] Global test environment tear-down
157: [==========] 1 test from 1 test suite ran. (30 ms total)
157: [  PASSED  ] 1 test.
1/1 Test #157: ControlObjectScriptTest.CompressingProxyCompareCount1 ...   Passed    2.78 sec

The following tests passed:
        ControlObjectScriptTest.CompressingProxyCompareCount1

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   2.93 sec

C:\Users\Joerg\source\repos\JoergAtGithub\mixxx\build\x64__portable>
```

**Comment by ronso0** [comment]
so the diff starts with the third line

mine
``` sh
157: GMOCK WARNING:
157: /../../src/test/controlobjectscripttest.cpp:100: Too many actions specified in EXPECT_CALL(*coScript2, slotValueChanged(_, _))...
157: Expected to be never called, but has 1 WillOnce()./../../src/master/src/test/controlobjectscripttest.cpp:104: Failure
157: Actual function call count doesn't match EXPECT_CALL(*coScript1, slotValueChanged(_, _))...
157:          Expected: to be called once
157:            Actual: never called - unsatisfied and active
157: [  FAILED  ] ControlObjectScriptTest.CompressingProxyCompareCount1 (4 ms)
```
yours
``` sh
157: GMOCK WARNING:
157: ..\..\src\test\controlobjectscripttest.cpp(100): Too many actions specified in EXPECT_CALL(*coScript2, slotValueChanged(_, _))...
157: Expected to be never called, but has 1 WillOnce().[       OK ] ControlObjectScriptTest.CompressingProxyCompareCount1 (29 ms)
157: [----------] 1 test from ControlObjectScriptTest (29 ms total)
```

**Comment by JoergAtGithub** [comment]
I guess this WillOnce is contradictory, because before it's specified, that it will occur zero times.
grafik
But I still don't understand, why Google-Mock report thisas error for you, but not elsewhere.
Could you try to remove line 102.

**Comment by ronso0** [comment]
with line 102 commented out it fails at line 104 "expected once but never called"

**Comment by JoergAtGithub** [comment]
Is the warning
```
GMOCK WARNING:
/src/test/controlobjectscripttest.cpp:100: Too many actions specified in EXPECT_CALL(*coScript2, slotValueChanged(_, _))...
```
gone?

**Comment by JoergAtGithub** [comment]
In your output there is the additional line for each test case:
`QML debugging is enabled. Only use this in a safe environment.`
Can you try to disable this?
BTW: The `#include <QtDebug>` is not needed, but I could find a relationship tothis message.

**Comment by JoergAtGithub** [comment]
I found that controllerscriptenginelegacy_test.cpp, which also uses application()->processEvents(); calls this function always twice to get all events. Maybe this helps also here.

**Comment by ronso0** [comment]
> Is the warning
> 
> ```
> GMOCK WARNING:
> /src/test/controlobjectscripttest.cpp:100: Too many actions specified in EXPECT_CALL(*coScript2, slotValueChanged(_, _))...
> ```
> 
> gone?

Yes. The output is now
``` sh
157: Test command: /../../src/master_build/Debug/mixxx-test "--gtest_filter=ControlObjectScriptTest.CompressingProxyCompareCount1" "--logLevel" "info"
157: Environment variables: 
157:  QT_QPA_PLATFORM=offscreen
157: Test timeout computed to be: 1500
157: QML debugging is enabled. Only use this in a safe environment.
157: Note: Google Test filter = ControlObjectScriptTest.CompressingProxyCompareCount1
157: [==========] Running 1 test from 1 test suite.
157: [----------] Global test environment set-up.
157: [----------] 1 test from ControlObjectScriptTest
157: [ RUN      ] ControlObjectScriptTest.CompressingProxyCompareCount1
157: /../../src/master/src/test/controlobjectscripttest.cpp:104: Failure
157: Actual function call count doesn't match EXPECT_CALL(*coScript1, slotValueChanged(_, _))...
157:          Expected: to be called once
157:            Actual: never called - unsatisfied and active
157: [  FAILED  ] ControlObjectScriptTest.CompressingProxyCompareCount1 (0 ms)
157: [----------] 1 test from ControlObjectScriptTest (0 ms total)
157: 
157: [----------] Global test environment tear-down
157: [==========] 1 test from 1 test suite ran. (0 ms total)
157: [  PASSED  ] 0 tests.
157: [  FAILED  ] 1 test, listed below:
157: [  FAILED  ] ControlObjectScriptTest.CompressingProxyCompareCount1
157: 
157:  1 FAILED TEST
1/1 Test #157: ControlObjectScriptTest.CompressingProxyCompareCount1 ...***Failed    0.13 sec
```

I don't know how to disable QML debugging. Remove the QDebug include doesn't help, and I have no idea where `mixxx-test` arguments are documented.

**Comment by JoergAtGithub** [comment]
Could you please try to double line 108 `application()->processEvents();` and execute the test again.

**Comment by ronso0** [comment]
:+1: then it'll pass, even if I re-enable line 102

**Comment by JoergAtGithub** [comment]
Great! Could you try this for the other tests as well.
They are much more complicated cases, I wonder, if duplication of `application()->processEvents();` helps everywhere.

**Comment by ronso0** [comment]
Jup, simply duplicating every `application()->processEvents();` line makes all tests pass.

**Comment by JoergAtGithub** [comment]
That's great to hear, I will prepare a PR tomorrow!

**Comment by JoergAtGithub** [comment]
I guess this is, because the QML debugger is hooked in the event pipeline, and it needs one process step from the testcase to the QML debugger, and a second from the debugger to my compressing proxy.

**Comment by ronso0** [comment]
Still, why would it fail on my machine in the first place?
Looking at the Github actions Ubuntu 20.04 build I don't spot a difference except I do not use `--config RelWithDebInfo` when building. Apart from that everything seems to be identical.

**Comment by JoergAtGithub** [comment]
That fits into the picture:
https://github.com/mixxxdj/mixxx/blob/6e3295f5cb149b51398318b033ea154b0b36e1f2/CMakeLists.txt#L1086-L1090
I also built locally with RelWithDebInfo, because Debug builds on Windows are so slow, that they are unusable.

**Comment by ronso0** [comment]
I just built `main` _with_ `--config RelWithDebInfo` and ran the unchanged `ControlObjectScriptTest.CompressingProxyManyEvents`. It failed.

**Pull request merged**
