### PR TITLE
Extract utility functions for QUuid

### PR DESCRIPTION
**Pull request by uklotzde**
Move QUuid utility functions from util/compatibility.h into util/quuid.h.

### CODE REVIEW

**Review by Be-ing — CHANGES_REQUESTED** [review]
I am working on a PR to remove these obsolete compatibility functions.

**Comment by Be-ing** [comment]
#4309

**Comment by uklotzde** [comment]
I have removed the obsolete utility function and the corresponding tests.

**Review by Be-ing — APPROVED** [review]
Waiting for CI

**Pull request merged**
