### PR TITLE
disable Travis

### PR DESCRIPTION
**Pull request by Be-ing**
Ubuntu and macOS builds are on GitHub Actions now which is
significantly faster.

### CODE REVIEW

**Comment by uklotzde** [comment]
If we disable Travis we immediately need to abandon the SCons build, because SCons builds will no longer tested.

I support this step, but everybody else should also be aware of the implications and consequences! We need a broad agreement to abandon the SCons build.

**Comment by Holzhaus** [comment]
We could also just remove the CMake builds from Travis for now, and discuss the SCons removal separately.

**Comment by uklotzde** [comment]
Let's remove only the CMake builds in a first step until a decision about SCons has been made.

**Comment by Be-ing** [comment]
We are not using scons for any builds anymore. IMO it is pointless to keep Travis at this point.

**Review by uklotzde — APPROVED** [review]
I agree. The constantly failing Travis builds are confusing. Let's drop it! We could revert this decision at any time if needed.

**Comment by uklotzde** [comment]
...then we can also drop SCons.

**Comment by uklotzde** [comment]
@daschuer @Holzhaus Opinions?

**Comment by Holzhaus** [comment]
OK for me.

**Comment by daschuer** [comment]
We cannot drop scons because PPA deployment is still based on scons. 
I am working towards a cmake solution.

**Comment by Be-ing** [comment]
Green checkmark :smile:

**Pull request merged**
