### PR TITLE
WSearchLineEdit

### PR DESCRIPTION
**Pull request by daschuer**
This is a backport of commits taken from @uklotzde
https://github.com/mixxxdj/mixxx/pull/1762

It fixes the high priority bug loading the wrong track to a deck using double click on Ubuntu 
Bionic.
https://bugs.launchpad.net/mixxx/+bug/1803148

### CODE REVIEW

**Comment by uklotzde** [comment]
@daschuer First I was concerned about potential merge conflicts. But surprisingly cherry-picking your commits into #1762 worked very well, good job :+1: The PR has already been updated.

I will test your additional changes within my custom 2.2 branch for a while.

**Comment by uklotzde** [comment]
LGTM. I didn't notice any unexpected behavior so far.

Any other test results on different platforms (Windows, macOS)?

**Comment by daschuer** [comment]
I can confirm the issue with Windows 10 an Mixxx 2.2.  Mixxx 2.1 is not effected, because the focus changes during scrolling the track table. The Appvajor artifacts works as expected. It is on top of 2.1 though. 
Merge?

**Comment by uklotzde** [comment]
Linux + Qt4 is affected by the bug? That would justify the fix. I've only tested Linux + Qt5.

**Comment by daschuer** [comment]
Yes, Mixxx 2.1 and Mixxx 2.2 are both effected on Bionic but not on Trusty. 
I have no Idea why the focus changes on one system but not on the other.

**Comment by uklotzde** [comment]
After merging into 2.1/2.2/master I will close #1762 and replace it with a new PR that only contains the type-safe signal/slot connections and the configurable timeout for debouncing.

**Comment by uklotzde** [comment]
Confusing behavior:
1. Enter a search phrase for _Tracks_
2. Switch to _Missing Tracks_ or _Hidden Tracks_: Search phrase remains visible but tracks are not filtered
3. Clear the edit field
4. Switch between _Missing Tracks_ and _Hidden Tracks_: Placeholder is shown, still no filtering (now as expected)
5. Switch back to _Tracks_: Original search phrase is restored and the tracks are filtered
6. Continue at step 2.

**Comment by daschuer** [comment]
I have also experienced that during testing, but I did not fix it, because it is unrelated to this bug fix.
There is a switch to the stored search phrase missing somewhere.

**Comment by uklotzde** [comment]
Follow-up: https://bugs.launchpad.net/mixxx/+bug/1803865

**Comment by uklotzde** [comment]
LGTM. Thank your for the great team work, Daniel!

**Comment by uklotzde** [comment]
I'll resolve the minor merge conflict and push it to 2.2 and master.

**Pull request merged**
