### PR TITLE
shell.nix: Update from scons to cmake

### PR DESCRIPTION
**Pull request by haslersn**

### CODE REVIEW

**Comment by Be-ing** [comment]
@poelzi could you review this?

**Review by matthiasbeyer — APPROVED** [review]
LGTM

**Comment by Be-ing** [comment]
@matthiasbeyer thanks. I'll take your word for it because I don't know much about Nix.

**Comment by uklotzde** [comment]
Thank you, Matze :)

**Comment by matthiasbeyer** [comment]
Yeah it all looks pretty straight-forward, no daemons that I can see, so I figured I just ACK this and maybe that's enough for you guys! :heart:

**Comment by poelzi** [comment]
I don't understand the change from default.nix to shell.nix. I use nix-build to produce a nix derivate which i use daytoday. I use nix-shell to get a build environment. Your change destroys my first use case while providing no benefits.

**Comment by matthiasbeyer** [comment]
no, `nix-shell` automatically uses `shell.nix` and if that's not available `default.nix`, but `default.nix` can also be used to package the repo without any further investigation.

Executing `nix-shell` should have the same effect before this change and after this change.

**Comment by haslersn** [comment]
> I don't understand the change from default.nix to shell.nix. I use nix-build to produce a nix derivate which i use daytoday. I use nix-shell to get a build environment. Your change destroys my first use case while providing no benefits.

I understand that this change destroys your first use case. However, there is the benefit that [lorri](https://github.com/target/lorri) can now be used. AFAIK there is no simple workaround for lorri, but there is a simple workaround for your first use case: Just run

```
$ nix-build shell.nix
or:
$ nix build -f shell.nix
```

**Comment by haslersn** [comment]
If it's okay with other maintainers to have two `.nix` files, then we can have a `default.nix` for building the derivation and a `shell.nix` which imports the `default.nix` with additional native build inputs `[ ccache shell-configure shell-build shell-run shell-debug ]`.

**Comment by haslersn** [comment]
@poelzi Would this work for you: #2828

**Pull request merged**
