### PR TITLE
Fix display of waveforms in LateNight child themes

### PR DESCRIPTION
**Pull request by morgannunan**
See [issue #134340](https://github.com/mixxxdj/mixxx/issues/13434). The 64 sampler version of LateNight was missing waveforms because the paths to the xml files were relative to the parent theme, and not absolute paths to it.

### CODE REVIEW

**Comment by ronso0** [comment]
Thank you for this PR.
Please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

**Comment by ronso0** [comment]
I just changed the base branch to 2.5 (this is where we need the fix).
Please rebase onto mixxx/2.5 and force-push.
Thanks.

**Comment by ronso0** [comment]
LGTM btw

**Comment by morgannunan** [comment]
Sorry for the delay. I will take care of this asap

**Comment by morgannunan** [comment]
Alright, well I tried to pull down my fork, then add the original repo here as a remote, then rebase and merge to my branch and it's a total cluster. Tons of merge conflicts and every time I reconcile a handful of them manually, I try to continue the rebase and I get scores more conflicts.

I'm happy to contribute to this project but I think I probably didn't do this right and I'm to stuck to move forward. Please advise.

**Comment by Swiftb0y** [comment]
you can go at it with a giant hammer, basically reset everything and then apply the last few changes you did. Eg. on your `late-wave-fix` branch, do `git switch -c late-wave-fix-backup` (just in case), then return back to this branch using `git switch late-wave-fix`. Ensure your view of upstream is up-to-date by doing `git fetch upstream`. Then get out the hammer by doing `git reset --hard upstream/2.5`. Now this branch looks exactly like the 2.5 branch. Now you gently apply your changes to this branch by doing `git cherry-pick 0c020b35d4db5836f93a3cfa27305acae7643de0 734462aef331651444a671c85407ba4bbe3db50a`. If you still get merge conflicts, then those are unavoidable, but they should only be in files you actually changed (and there shouldn't be many, after all its just two commits). Once those two commits have applied, you should be done and you can `git push --force` to update this PR (you'll need to force push because we previous used the `git reset` hammer, you usually should avoid force pushing because its likely not what you wanted). If you messed up, you can always return back to where you are currently by doing `git reset --hard late-wave-fix-backup`. Let me know if you need further assistance.

**Comment by morgannunan** [comment]
Alright, I started over, forking from 2.5 and making my branch from that. I have [a new PR](https://github.com/mixxxdj/mixxx/pull/13501) in and we can close this one.

**Comment by ronso0** [comment]
The instructions from @Swiftb0y are very clear and well explained (thanks!).
Next time please try these with another branch in order to avoid opening a new PR just because of some conflicts.

**Pull request closed without merging**
