### PR TITLE
fix echo effect reducing volume of input

### PR DESCRIPTION
**Pull request by Be-ing**
The input samples were being divided by 2.0 along with the echoed signal. This changes it so only the echoed signal is divided by 2.0. Now, with the send parameter all the way down, toggling the effect enable switch does not alter the sound at all. If the echoed signal is not attenuated, it can clip somewhat easily.

### CODE REVIEW

**Comment by timrae** [comment]
Now it gets louder when you press the switch :-/

**Comment by Be-ing** [comment]
With the send knob all the way down? If the send knob is not all the way down, it should get louder when enabled.

**Comment by timrae** [comment]
If it wasn't all the way down it was close to it.... Enough to be annoying

**Comment by timrae** [comment]
Btw reverb doesn't have this issue... Not sure if it will be of reference
to you, but might be worth checking

**Comment by Be-ing** [comment]
I tested this again and it seems fine to me. If the send knob is up a little bit, it gets a little louder when enabled, as I expect. When the send knob is all the way down, there is no change at all when enabled. Anyone else care to test?

**Comment by daschuer** [comment]
Yes, the result is better. However, this changes the clipping behavior. 

Before
(In + clipped(delay)) / 2 -> not clipping if input is not clipping 

Now
In + clipped(delay) / 2 -> clipping (going to red) can still happen 

This is basically the same as mixing two tracks. So it should be not an issue isn't it? 
Or should we add an other clipper to the output, like we do in the phaser? 

I think we can improve the sound by using a tanh clipper that models the sound of a clipped transistor circuit.  A bit faster tanh approx. is used in the moog filter: 

https://github.com/mixxxdj/mixxx/blob/75e85d359d964ce9b55c92ebe3e7ed5962b51947/src/engine/enginefiltermoogladder4.h#L238

**Comment by Be-ing** [comment]
> This is basically the same as mixing two tracks. So it should be not an issue isn't it?

No, it's not quite the same. It's like mixing in another track that is ~6 dB quieter. I tried not dividing the echoed signal by 2, but IMO it was too easy to clip that way. I think this PR should be merged as is. Afterwards, if you have ideas for improving the effect further, please open a new PR.

**Comment by daschuer** [comment]
LGTM Thank you.

**Pull request merged**
