### PR TITLE
Add warnign when trying to enable AutoDJ with left & right deck

### PR DESCRIPTION
**Pull request by MetriSomesh**
Added warning message when trying to enable AutoDJ if there's no left & right deck.

### CODE REVIEW

**Comment by daschuer** [comment]
Unfortunately I am not able to reopen this PR, because the Branch has been deleted on GitHub. 
I assume that you have it locally, so do the following from your working copy: 

```
git checkout Warning-msg
git fetch upstream 
git rebase --onto upstream/2.3 ad8db4030c554a34af6e3bbf3c62de5a7c044280
git push -f
```

Than you can amend the last commit into the first:
```
git reset --soft HEAD~1 
git commit --amend
git push -f
```

Than it is hopefully possible to open this PR again. Else issue a new one. 


If the branch has been deleted, I guess it is straight forward to redo the changes on a new branch 
```
git checkout -b Warning-msg2 upstream/2.3
<do the edits>
git commit -a 
git push --set-upstream origin Warning-msg2
```
Than create a new PR on GitHub

**Comment by MetriSomesh** [comment]
@ronso0  Tried all commands as you mentioned I guess I have to issue a new PR

**Comment by daschuer** [comment]
Ok .. you mean @daschuer

**Comment by MetriSomesh** [comment]
@daschuer  ohh yeah sorry about that

**Pull request closed without merging**
