### PR TITLE
Typo on Controller Learning wizard resolved

### LINKED ISSUE #11158: Typo on Controller Learning Wizard
### Bug Description

When you hit Choose Control > Speed in the second section of the menu it goes

Increase Speed
Increase Speed (Fine)
Decrease Speed
Increase Speed (Fine)

I believe the last Increase Speed should be Decrease Speed since that's what it links to according to the small print below: "_Ready to learn Deck #: Adjust speed slower (fine)_"

### Version

2.3.3

### OS

Windows 10

### PR DESCRIPTION
**Pull request by Bilsteen**

### CODE REVIEW

**Comment by ronso0** [comment]
Thanks for this fix.
It seems the 2.3 branch is also affected. Could you please rebase your branch onto upstream 2.3 (discard all unrelated commits from main branch) and force-push?

**Comment by Bilsteen** [comment]
Correct me if I am wrong, what i have done is rebased my branch onto the upstream 2.3 branch. Since the 2.3 branch is behind in commits from main, discarded those commits and then forced the branch to 2.3.

**Comment by Swiftb0y** [comment]
Unfortunately your rebasing resulted in merge conflicts and instead of fixing them, you just committed them, resulting in duplicte code and syntax issues from git's markup. Please take another look at your sourcefile and make sure to commit the correct content, then amend the commit and force push.

**Comment by ronso0** [comment]
@Bilsteen you don't need to close a PR if there are issues. With gut there are always methods to resolve them.
In the very worst case you reset your local branch, set upstream correctly (on top of 2.3 in this case) and git cherry-pick your commit. Then force-push.

**Comment by Bilsteen** [comment]
@ronso0 I apologize for my mistakes. Actually I was trying to undo the mistakes i made as pointed out by @Swiftb0y , for which i deleted my branch. I am still new to git and figuring stuff out . But i assure you I will make it right.

**Comment by Swiftb0y** [comment]
No worries, just make sure the file looks right and mixxx compiles, then `git add src/controllers/controlpickermenu.cpp`, `git commit --amend` and `git push --force`.

**Review by ronso0 — APPROVED** [review]
Thanks, you made it ; )

**Comment by ronso0** [comment]
Btw:
Since this is your first contribution we need you to sign the [contributor agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and thereby allows Mixxx to include your changes.

Please comment here when you filled the form and also let us know which name should appear in the contributor list.

**Comment by Bilsteen** [comment]
> Btw: Since this is your first contribution we need you to sign the [contributor agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and thereby allows Mixxx to include your changes.
> 
> Please comment here when you filled the form and also let us know which name should appear in the contributor list.

Thanks for helping me throughout the way and yes I have filled the form.

**Pull request merged**
