### PR TITLE
LateNight: improve performance when toggling mixer or maxized library

### PR DESCRIPTION
**Pull request by ronso0**
While testing LateNight on Windows I noticed some annoying lag when toggling the mixer or the maximized library (while this works almost flawlessly on Linux on the same machine, i7-8650U). I can imagine how slow this might be on older hardware...

This PR removes the SizeAwareStack hack that was supposed to simplify all the deck size toggling and moves the 'logic' to nested WidgetStacks in deck.xml

For easy testing this branch contains LateNight and LateNight_old.
Please test if the toggling in **LateNight** works faster for you than in **LateNight_old**.

- [x] remove old LateNight

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
I just tested this on Windows 7, and switching to big library / mixer is significiantly faster and now without visible intermediate layout states.

While testing, I noted two similar glitches while changeing layout (both occur with and without this PR)
- Such intermediate layout states still occur if I switch between 2 and 4 decks. (It looks like deck 1 + 3 are stacked on the left and deck 2 is first drawn vertical centered, before deck 4 is added to the layout too)
- While switching the spinnies show random widget from elswere in the UI (only for a very short period, but visible)

**Comment by daschuer** [comment]
When debugging the property connection, I have found an issue with the size aware stack that may cause an extra update round-trip. My fix brakes original LateNight, because initial updates where gone. Because it was unrelated at that point I have removed the "fix". But maybe this round trip is the underlying issue here ... 
mmm not sure, if it is worth to revive the idea and adjust the skins to it. I will have al look.

**Comment by NotYourAverageAl** [comment]
I can confirm on W10 that LateNight is significantly faster than LateNight_old

I can also confirm the glitch that JoergAtGithub encountered when switching btwn 2 & 4 decks 

https://user-images.githubusercontent.com/24758479/116781196-cfb52800-aac4-11eb-91d0-f7db20298244.mp4

**Comment by ronso0** [comment]
@daschuer 
I noticed the lag a few weeks ago so it's unrelated to the recent connection updates.
I will test this with an old build on a slow Linux machine. 

@JoergAtGithub @NotYourAverageAl 
Did you test with the binaries supplied by gh actions, or did you checkout the skin changes only with git?

**Comment by ronso0** [comment]
is 2/4 deck switching also slow for you when the mixer is hidden?

**Comment by JoergAtGithub** [comment]
I used the GH build. The effect with 2/4 deck switching is also there, if I hide the mixer. But with hidden mixers it's much faster and therefore barely to see.

**Comment by NotYourAverageAl** [comment]
@ronso0 I used the GH actions binary. 2/4 deck switching is faster with the mixer hidden but still get glitches/artifacting


https://user-images.githubusercontent.com/24758479/116782491-c203a080-aacc-11eb-8989-78818569e866.mp4

**Comment by ronso0** [comment]
@NotYourAverageAl Thanks for the effort of recording the screen, but I think with recording, encoding, decoding it's not reliabke to say whether it's that or the actual skin lags. I rather rely on your perception : )

So I'll look into the mixer template as well as the deck stack. If I can improve that, too, with little effort, fine. Otherwise this is already sufficient, because I assume 2/4 deck switching is done less often than togling the library or the mixer.

**Comment by ronso0** [comment]
seems switching 2/4 decks can't be accelerated anymore. I consider the current performance acceptable, glitches may occur only when the comapct VU meters are shown.

Ready to be merged.

**Comment by Holzhaus** [comment]
Thanks, the toggling the maximized library is much faster now.

**Comment by NotYourAverageAl** [comment]
@ronso0 this PR introduced a bug. the cover art & preview toggles are now missing in windows under **Library** settings
I missed this during testing
image

**Comment by ronso0** [comment]
yes, thanks, already fixed that last night. Before 2.3 there'll be a PR with small fixes that accumulated over time.

**Pull request merged**
