### PR TITLE
Fixing (some) stalled GUI during iTunes import 

### PR DESCRIPTION
**Pull request by daschuer**
Not perfect, but it is now usable even for bigger iTunes libraries.

https://bugs.launchpad.net/mixxx/+bug/1785545

### CODE REVIEW

**Comment by daschuer** [comment]
Travis GCC build fails unrelated to this PR

**Comment by daschuer** [comment]
Is this a 2.1.5 candidate? It matters a lot for people with a big iTunes library. How much are there?
Who is able to test this?

**Comment by uklotzde** [comment]
I neither have a ready to use Windows development environment nor an iTunes library for testing. Code LGTM so far.

The only actual change is clearing the existing table contents before re-importing them from the XML? Well, since the contents of those tables is simply a cache reflecting a snapshot of the XML during the last import this is non-crititcal, even if the following import fails.

**Comment by daschuer** [comment]
I moved the table clear to an early point to not show outdated tables if the import fails.

**Comment by daschuer** [comment]
Thank you for review.

**Pull request merged**
