### PR TITLE
Prevent error after failed SCons build

### PR DESCRIPTION
**Pull request by xeruf**
See https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Error.20building.20with.20SCons.20-.20no.20branch

### CODE REVIEW

**Comment by xerus2000** [comment]
@Be-ing please don't forget this :)

**Comment by Be-ing** [comment]
Does this break caching when building a commit not on a branch?

**Comment by Holzhaus** [comment]
The proper fix would be to wrap the `shutil.move` call into a `try`-`except`-block and catch `OSError`. This would also prevent issues when the file exists but cannot be moved for other reasons (permissions, etc.). And even if we checked that, the code has race-conditions (time of check vs. time of use). Ask for forgiveness, not permission.

**Comment by Holzhaus** [comment]
> The proper fix would be to wrap the `shutil.move` call into a `try`-`except`-block and catch `OSError`. This would also prevent issues when the file exists but cannot be moved for other reasons (permissions, etc.). And even if we checked that, the code has race-conditions (time of check vs. time of use). Ask for forgiveness, not permission.

ping

**Comment by xerus2000** [comment]
Merge or not? I don't fancy working on this more, since I don't know much about SCons and it will be abandoned soon anyways.

**Comment by Holzhaus** [comment]
Can someone verify that this fix works and does not break caching for detached HEAD? If that works, feel free to merge.

**Comment by xerus2000** [comment]
what do  you mean with "break caching"? Afaik the snippet I modified only applies if you _switch_ branches

**Review by daschuer — CHANGES_REQUESTED** [review]
```
INFO:root:Qt path: /usr/lib/x86_64-linux-gnu/qt5
branch has changed (no branch) -> master
shutil.move .sconsign.dblite -> cache/(no branch)/sconsign.dblite
IOError: [Errno 2] No such file or directory: 'cache/(no branch)/sconsign.dblite':
  File "/home/janek/daten/projects/_forks/mixxx/SConstruct", line 68:
    toolchain, available_features)
  File "/home/janek/daten/projects/_forks/mixxx/build/mixxx.py", line 250:
    self.virtualize_build_dir()
  File "/home/janek/daten/projects/_forks/mixxx/build/mixxx.py", line 573:
    shutil.move(sconsign_file, old_virtual_sconsign_file)
  File "/usr/lib/python2.7/shutil.py", line 325:
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 153:
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 97:
    with open(dst, 'wb') as fdst:
```

Unfortunately I cannot reproduce the issue. 

"(no branch)" is just the placeholder for a detached head build. 
It works here as every other branch. 

So I am afraid that excluding this branch from virtualization is a fix at the wrong place.

**Comment by daschuer** [comment]
Since you have no interest to continue here, I am closing this PR now. 
Thank you for taking care that far.

**Comment by xerus2000** [comment]
> ```
> INFO:root:Qt path: /usr/lib/x86_64-linux-gnu/qt5
> branch has changed (no branch) -> master
> shutil.move .sconsign.dblite -> cache/(no branch)/sconsign.dblite
> IOError: [Errno 2] No such file or directory: 'cache/(no branch)/sconsign.dblite':
>   File "/home/janek/daten/projects/_forks/mixxx/SConstruct", line 68:
>     toolchain, available_features)
>   File "/home/janek/daten/projects/_forks/mixxx/build/mixxx.py", line 250:
>     self.virtualize_build_dir()
>   File "/home/janek/daten/projects/_forks/mixxx/build/mixxx.py", line 573:
>     shutil.move(sconsign_file, old_virtual_sconsign_file)
>   File "/usr/lib/python2.7/shutil.py", line 325:
>     copy2(src, real_dst)
>   File "/usr/lib/python2.7/shutil.py", line 153:
>     copyfile(src, dst)
>   File "/usr/lib/python2.7/shutil.py", line 97:
>     with open(dst, 'wb') as fdst:
> ```
> 
> Unfortunately I cannot reproduce the issue.

But what you are posting there is the exact issue I encountered?

**Comment by daschuer** [comment]
I have just copied your error to GitHub.

**Pull request closed without merging**
