### PR TITLE
update libdjinterop to 0.20.2

### PR DESCRIPTION
**Pull request by Be-ing**
to fix Clang build
https://github.com/xsco/libdjinterop/issues/112

### CODE REVIEW

**Comment by Be-ing** [comment]
Linking libdjinterop fails on Windows when built via ExternalProject_Add?? PR to update vcpkg is here: https://github.com/microsoft/vcpkg/pull/36869

**Review by daschuer — CHANGES_REQUESTED** [review]
This does unfortunately not link on windows: 
`fatal error LNK1120: 8 unresolved externals`

I think It would be reasonable to stick with the VCPKG provided version for now and just add your change as patch. `PATCH_COMMAND`

Other option would be to required 0.20.1 but download 0.20.2 
We need also make sure that the djinterop PPA has the newest version in this case.

**Comment by Be-ing** [comment]
The update of libdjinterop in vcpkg has been merged.

**Comment by Be-ing** [comment]
It may have to do with this https://github.com/xsco/libdjinterop/blob/main/CMakeLists.txt#L156

```cmake
set_target_properties(DjInterop PROPERTIES C_VISIBILITY_PRESET hidden)
set_target_properties(DjInterop PROPERTIES CXX_VISIBILITY_PRESET hidden)
```

which makes me wonder how it works with vcpkg :thinking: Anyway, considering that it worked with vcpkg before somehow, I think it will work again when updating vcpkg.

**Comment by Be-ing** [comment]
Let's update vcpkg then try rebasing this.

**Comment by daschuer** [comment]
@mr-smidge Can you please you Launchpad PPA to 0.20.2? Than we can advance with Mixxx to that version. Thank you.

**Comment by mr-smidge** [comment]
> @mr-smidge Can you please you Launchpad PPA to 0.20.2? Than we can advance with Mixxx to that version. Thank you.

I've pushed 0.20.2, and bionic is building now... will copy for other distros tomorrow once it's done.

**Comment by daschuer** [comment]
Thank you

**Comment by mr-smidge** [comment]
0.20.2 now available for all Ubuntu series: https://launchpad.net/~xsco/+archive/ubuntu/djinterop/+packages

**Comment by daschuer** [comment]
Merged via https://github.com/mixxxdj/mixxx/pull/12898 
Thank you.

**Comment by Be-ing** [comment]
That was to the main branch. This needs to go to the 2.4 branch to fix the build failure.

**Comment by JoergAtGithub** [comment]
Merged in #13154

**Pull request closed without merging**
