### PR TITLE
Add and use mixxx::Bpm::valueOr()

### PR DESCRIPTION
**Pull request by uklotzde**
Follow-up of #4165 to resolve some FIXME comments.

### CODE REVIEW

**Comment by mr-smidge** [comment]
FWIW, I tried performing an "Entire music library" export to Engine Prime using this branch, and it completed successfully.  The previous codebase would occasionally trigger assertion failures in `Bpm::value()` for such an operation if there were tracks where analysis was not valid.

So gets my vote :+1:.

**Comment by Holzhaus** [comment]
I'm open to it, but the resulting double is not undefined, it's zero. Should it be `valueOrZero`? Unsure about that.

**Comment by uklotzde** [comment]
> I'm open to it, but the resulting double is not undefined, it's zero. Should it be `valueOrZero`? Unsure about that.

Good point! On the value level there is no *undefined*, which would otherwise be *NaN*.

**Comment by uklotzde** [comment]
An optional that wraps always valid BPM values would be more idiomatic. A value of 0.0 is valid for some rare, ambient, beatless tracks. Let's defer this until we rewrite in Rust ;)

**Review by Holzhaus — APPROVED** [review]

**Comment by Holzhaus** [comment]
Thanks, looks good.

**Pull request merged**
