### PR TITLE
revert to macOS build environment with Qt 5.12.3

### PR DESCRIPTION
**Pull request by Be-ing**
This is a temporary hack for Mixxx 2.3. Upgrading to Qt 5.14.2
caused a major performance regression with the legacy QGLWidgets.
The branch for switching to QOpenGLWidgets (PR #1974) is not yet
ready because of jerking with the waveforms.

### CODE REVIEW

**Comment by Be-ing** [comment]
If we merge this, we need to update https://mixxx.org/wiki/doku.php/compiling_on_os_x to warn against using dependencies from Homebrew until #1974 is merged.

**Comment by Holzhaus** [comment]
> If we merge this, we need to update https://mixxx.org/wiki/doku.php/compiling_on_os_x to warn against using dependencies from Homebrew until #1974 is merged.

Does this mean that OSX users need to compile the old Qt version themselves?

**Comment by Be-ing** [comment]
It means if they build locally, they need to use an old version of Qt. They can do that using our prebuilt environment. I think Homebrew can also be used to install specific versions of a package.

**Comment by uklotzde** [comment]
On CI we are always using the latest version installed by brew. But since we are using even older Qt versions on Ubuntu this doesn't really matter as long as no one tries to download and execute the build artifacts.

Merge?

**Comment by Be-ing** [comment]
We should use the same build environment on CI as our build server. But that's an issue for another PR.

**Pull request merged**
