### PR TITLE
MC7000: Fix code style issues in the controller script

### PR DESCRIPTION
**Pull request by fwcd**
There are a bunch of style issues in the script that the pre-commit hook didn't accept, mostly regarding `const`/`let` declarations of variables.

### CODE REVIEW

**Comment by fwcd** [comment]
Hm, blindly applying the linter fixes seems to break the script...

**Comment by toszlanyi** [comment]
Const/let its not working with the current releases of Mixxx, only for the future. So all your improvements will not be able to run on current release. Just my thought but I guess, the shift and jog acceleration should go first, so based to 2.3 branch and the const/let change to 2.4 or main branch. Maybe @Swiftb0y can comment better on this topic. Cheers

**Comment by uklotzde** [comment]
Fixing the ES6 linter issues on `main` should be deferred until no more 2.3.x releases are expected. Otherwise this would cause serious merge conflicts when improvements or fixes for 2.3.x mappings are provided. In this case #4729 would be affected.

**Comment by fwcd** [comment]
Looks like the 2.3 merges (e.g. 17f3c4251e675950d54afbc175d662a20695a3a8 and 302b40eefe6948a7080d1ee87bedafdf48624f69) already took care of everything in this PR (I think the code style changes were introduced during these merges since I couldn't find more granular commits).

**Pull request closed without merging**
