### PR TITLE
Fix 'unrecognized character escape sequence' warning + Qt 5.5 upgrade

### PR DESCRIPTION
**Pull request by uklotzde**
...and add a unit test to detect formatting issues.

### CODE REVIEW

**Comment by uklotzde** [comment]
The new string formatting test fails on 16.04 but succeeds on 18.04 and all other platforms. I don't know why.

**Comment by uklotzde** [comment]
No documentation for Qt 5.4 is available in the archives: https://doc.qt.io/archives/index.html

Another reason why we really should update our minimal requirements! I'm tried of keeping the code compatible with unsupported versions.

**Comment by ronso0** [comment]
I find Qt 5.5.1 in xenial & [xenial updates packages list](https://packages.ubuntu.com/xenial-updates/allpackages).
what do we need 5.4 for?

**Comment by daschuer** [comment]
I can have a look on my Xenial system.

**Comment by uklotzde** [comment]
Xenial indeed comes with Qt 5.5.1 as seen on Travis. We should raise the bar once again!

**Comment by uklotzde** [comment]
In #2409 string concatenation will be optimized away.

**Comment by uklotzde** [comment]
Rounding of the decimal literal 10.5 seems to fail on Travis for Xenial.

**Comment by uklotzde** [comment]
Now it works. Fast feedback from the cached CMake build, really nice!! Another reason for dropping SCons asap.

**Comment by daschuer** [comment]
I can confirm Qt 5.5.1 on my dev system.

**Comment by daschuer** [comment]
It already looks good to me. Do do have interests to change the code as suggested, in my old comment? I have missed to publish it in time.  
If not we can merge it right away.

**Comment by daschuer** [comment]
Ups, scratch my last comment. I did not notice the fix in the last commit. 
Thank you. LGTM

**Pull request merged**
