### PR TITLE
Fix OpenGL ES compile

### PR DESCRIPTION
**Pull request by daschuer**
This should fix the armhf build on our PPA (hopefully)

### CODE REVIEW

**Comment by uklotzde** [comment]
Does it work as expected?

**Review by uklotzde — APPROVED** [review]

**Comment by daschuer** [comment]
> Does it work as expected?

Here on my amd64 device yes. We need to merge it to verify the PPA build.

**Comment by uklotzde** [comment]
The let's give it a try. LGTM

**Comment by moretocome** [comment]
I am unable to build this for armhf on a raspberry pi 4b with a recent raspbian distribution. During the process, I get the message:

```AutoMoc: /home/pi/mixxx/src/waveform/renderers/glslwaveformrenderersignal.h:0: Note: No relevant classes found. No output generated.```

Eventually it fails with errors like:
```
In file included from /home/pi/mixxx/src/waveform/widgets/glrgbwaveformwidget.cpp:1:
/home/pi/mixxx/src/waveform/widgets/glrgbwaveformwidget.h:7:61: error: expected class-name before ‘{’ token
 class GLRGBWaveformWidget : public GLWaveformWidgetAbstract {
                                                             ^
In file included from /home/pi/mixxx/src/waveform/widgets/glrgbwaveformwidget.cpp:3:
/home/pi/mixxx/build/mixxx-lib_autogen/include/moc_glrgbwaveformwidget.cpp:66:8: error: ‘GLWaveformWidgetAbstract’ has not been declared
     { &GLWaveformWidgetAbstract::staticMetaObject, qt_meta_stringdata_GLRGBWaveformWidget.data,
        ^~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/mixxx/build/mixxx-lib_autogen/include/moc_glrgbwaveformwidget.cpp: In member function ‘virtual const QMetaObject* GLRGBWaveformWidget::metaObject() const’:
/home/pi/mixxx/build/mixxx-lib_autogen/include/moc_glrgbwaveformwidget.cpp:73:21: error: ‘QScopedPointer<QObjectData> QObject::d_ptr’ is protected within this context
     return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : &staticMetaObject;
                     ^~~~~
In file included from /usr/include/arm-linux-gnueabihf/qt5/QtWidgets/qwidget.h:45,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtOpenGL/qgl.h:46,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtOpenGL/QGLWidget:1,
                 from /home/pi/mixxx/src/waveform/widgets/glrgbwaveformwidget.h:3,
                 from /home/pi/mixxx/src/waveform/widgets/glrgbwaveformwidget.cpp:1:
/usr/include/arm-linux-gnueabihf/qt5/QtCore/qobject.h:433:33: note: declared protected here
     QScopedPointer<QObjectData> d_ptr;
```

**Pull request merged**
