### PR TITLE
Shade: remove superfluid margins and padding in sampler.xml

### PR DESCRIPTION
**Pull request by daschuer**
Fixing https://bugs.launchpad.net/mixxx/+bug/1773588

### CODE REVIEW

**Comment by daschuer** [comment]
@ronso0: does it fix your issue?

**Comment by ronso0** [comment]
this wasn't my issue ;) I tested with qt5.2 and I can't see the gaps without this PR.

Finally installed Xenial on another partition and tested with a official binaries qt5.5.1
There I dont have a proper workflow (not all my tools are available for xenial) so I hope I caught all bugs. The big samplers look good now, I continued removing other useless '10px' occurrences in skin.xml and looping.xml.

2b0f32e5b85122296a8d7727b802c185ec72b0b4 Shade qt5.5: remove further obsolete 10px margins/paddings/borders

before:
shade-fix-sam-loop-layout-before

after:
shade-fix-sam-loop-layout-after

**Comment by ronso0** [comment]
btw: I noticed a few times already that most of the indentations in Shade are screwed up.
I'd like to fix that in a separate PR; late-night Tab&Del meditation..

**Comment by daschuer** [comment]
Thank you for the commit. It still looks good for me, so I think we can merge this. 
The tab space issue is a legacy issue. I have never managed to find time to fix it, sorry. Only if you are bored, you can do it. :-) thank you.

**Pull request merged**
