### PR TITLE
clang-tidy: Manual fixes

### PR DESCRIPTION
**Pull request by Holzhaus**
Add manual fixes requested in https://github.com/mixxxdj/mixxx/pull/3449

### CODE REVIEW

**Review by daschuer — COMMENTED** [review]
Thank you for going this extra mile.
Did you consider to revert the changes in rekordbox_pdb.cpp? 
If we ever generate a new one it is easier to track down changes. 
I am unsure ..

**Review by uklotzde — APPROVED** [review]

**Comment by Be-ing** [comment]
Please take care of merging to main.

**Comment by uklotzde** [comment]
> Please take care of merging to main.

No conflicts

**Comment by Be-ing** [comment]
Ha, I just assumed there would be conflicts with another mass refactoring PR.

**Comment by Holzhaus** [comment]
> another mass refactoring PR

146 changed lines o.O

**Pull request merged**
