### PR TITLE
Use devicePixelRatio to scale the viewport in GLSLWaveformRendererSignal.

### PR DESCRIPTION
**Pull request by rryan**
Fixes Bug #1779972. Also fixes some lint and makes some minor C++11 style upgrades.

### CODE REVIEW

**Comment by Be-ing** [comment]
LGTM thanks. I changed the target branch to 2.2.

Do you have any idea why the RGB (GLSL) renderer is not showing up as an option?

**Comment by Pegasus-RPG** [comment]
Does that get added at build time or run time?

**Comment by rryan** [comment]
> Does that get added at build time or run time?

The detection is run whenever the widget is resized. It uses the current focused window to determine which to use. I think we probably need to implement some kind of detection for when the device pixel ratio changes -- for example if you move Mixxx from a hidpi laptop screen to a lowdpi external monitor, the ratio will be wrong. I'm not sure how this works when Mixxx is split across two screens with different dpis. I *think* the OS probably handles this for us, but we should check.

**Comment by Be-ing** [comment]
[Qt documentation](http://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt) implies that it takes care of handling multiple monitors with different scale factors, but I don't have any external monitors to test with:

> The application attribute Qt::AA_EnableHighDpiScaling, introduced in Qt 5.6, enables automatic scaling based on the pixel density of the monitor.

> Qt applications by default are Per-Monitor DPI Aware on Windows 8.1 or System-DPI Aware on older versions of Windows.

**Pull request merged**
