### PR TITLE
Tango :: fix spinny/cover with color schemes

### PR DESCRIPTION
**Pull request by ronso0**
discovered in [lp:1813436](https://bugs.launchpad.net/mixxx/+bug/1813436), probably a hickup after merging minimal decks and 2nd Tango scheme

### CODE REVIEW

**Comment by nopeppermint** [comment]
I think on Shade we have a similar Problem:

While testing #2008 with shade and color scheme dark I got some error messages :

```
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_bg.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_mask_.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator_ghost.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_bg.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_mask_.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator_ghost.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_bg.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_mask_.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator_ghost.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_bg.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_mask_.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator_ghost.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_bg.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_mask_.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator_ghost.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_bg.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_mask_.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator_ghost.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_bg.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_mask_.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator_ghost.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_bg.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_mask_.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator.svg', because: No such file or directory
Warning [Main]: Cannot open file 'skin:graphics/spinnyMini_indicator_ghost.svg', because: No such file or directory
Warning [Main]: src/skin/legacyskinparser.cpp:1799 SKIN ERROR at skin:deck_row_loop_jump.xml:28 <WidgetGroup>: Could not parse widget MaximumSize: "-1,-1"
Warning [Main]: src/skin/legacyskinparser.cpp:1799 SKIN ERROR at skin:deck_row_loop_jump.xml:65 <WidgetGroup>: Could not parse widget MaximumSize: "-1,-1"
Warning [Main]: src/skin/legacyskinparser.cpp:1799 SKIN ERROR at skin:deck_row_loop_jump.xml:44 <WidgetGroup>: Could not parse widget MaximumSize: "-1,-1"
Warning [Main]: src/skin/legacyskinparser.cpp:1799 SKIN ERROR at skin:deck_row_loop_jump.xml:65 <WidgetGroup>: Could not parse widget MaximumSize: "-1,-1"
Warning [Main]: src/skin/legacyskinparser.cpp:1799 SKIN ERROR at skin:deck_row_loop_jump.xml:28 <WidgetGroup>: Could not parse widget MaximumSize: "-1,-1"
Warning [Main]: src/skin/legacyskinparser.cpp:1799 SKIN ERROR at skin:deck_row_loop_jump.xml:65 <WidgetGroup>: Could not parse widget MaximumSize: "-1,-1"
Warning [Main]: src/skin/legacyskinparser.cpp:1799 SKIN ERROR at skin:deck_row_loop_jump.xml:44 <WidgetGroup>: Could not parse widget MaximumSize: "-1,-1"
Warning [Main]: src/skin/legacyskinparser.cpp:1799 SKIN ERROR at skin:deck_row_loop_jump.xml:65 <WidgetGroup>: Could not parse widget MaximumSize: "-1,-1"```

**Comment by ronso0** [comment]
Both errors types come from Tango: the upper part are the spinny errors I fix in this PR.
the others about MaximumSize can be ignored: `-1` means there's no maximum size set in that dimension, the widget can fill the available space. The error is thrown regardless of the way I try to tell this to the skinparser (it could as well be `i` or just left blank), and the skin is built exactly as intended.

**Comment by daschuer** [comment]
> Warning [Main]: src/skin/legacyskinparser.cpp:1799 SKIN ERROR at skin:deck_row_loop_jump.xml:28 <WidgetGroup>: Could not parse widget MaximumSize: "-1,-1"

You just need to need not set it at all.

**Comment by ronso0** [comment]
Yes, I do need it there. [deck_row_loop_jump.xml](https://github.com/mixxxdj/mixxx/blob/master/res/skins/Tango/deck_row_loop_jump.xml#L31) is used for left & right decks and the variable for x-MaximumSize (SpaceLeft, SpaceRight) makes the loop/jump controls stay in the center of the screen.
`-1`, `i` or just blank don't make a difference.

**Comment by daschuer** [comment]
Ah OK, I see the issue, it is because of the variable. So let's just remove the warning.

**Comment by daschuer** [comment]
LGTM, Thank you.

**Pull request merged**
