### PR TITLE
Fix LV2 wrapper

### PR DESCRIPTION
**Pull request by poelzi**
The LV2 environment variable is required for the subsystem
to find the enabled plugins.

This functionality got lost when the default.nix -> shell.nix transition happened.

### CODE REVIEW

**Comment by poelzi** [comment]
There is something odd with the build packages. Investigating.

**Comment by daschuer** [comment]
Is this still in draft state?

**Comment by poelzi** [comment]
I fixed the wrapper problem and now LV2 plugins work again, which was a regression when the file was refactored.
I added the dependencies forpre-commit in virtualenv. On my 19.04 the shipped version is to old for getting this runnig. I tried to port it into this nix but it got to bloated, so i choose virtualenv.

**Comment by poelzi** [comment]
please merge

**Comment by daschuer** [comment]
Thank you for taking care.

**Pull request merged**
