### PR TITLE
fix(build): windows codesign

### PR DESCRIPTION
**Pull request by Swiftb0y**
Backport of #4824

Failing build:
https://github.com/mixxxdj/mixxx/actions/runs/4015053658/jobs/6896323968
Fixed build:
https://github.com/mixxxdj/mixxx/actions/runs/4015973820/jobs/6898375765

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you. Do we also want to backport: 
https://github.com/mixxxdj/mixxx/pull/4825
?

**Comment by Swiftb0y** [comment]
Good idea, done.

**Comment by daschuer** [comment]
Thank you for the fast fix!

**Review by daschuer — APPROVED** [review]
LGTM

**Pull request merged**
