### PR TITLE
.travis.yml: Turn on WARNINGS_FATAL for CMake builds

### PR DESCRIPTION
**Pull request by Holzhaus**
This should make sure that our code is and stays warning free.

### CODE REVIEW

**Comment by uklotzde** [comment]
Only works for the Ubuntu build.

**Comment by daschuer** [comment]
The pre-commit failure here is fixed by https://github.com/mixxxdj/mixxx/pull/2880

**Comment by Holzhaus** [comment]
> Only works for the Ubuntu build.

Ok, let's only activate it for ubuntu for now.

**Comment by uklotzde** [comment]
Works as expected. LGTM.

**Pull request merged**
