### PR TITLE
Bump version to 2.1.1

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by rryan** [comment]
Confusing commit message (2.2.1 vs. 2.1.1). Rewrite?

**Comment by daschuer** [comment]
Ups, Yes.

**Comment by daschuer** [comment]
Buglist is cleared, Translation updated, manual included. 
What else is to do? 
https://www.mixxx.org/wiki/doku.php/2.1.0_release_checklist

**Comment by rryan** [comment]
Debian changelog needs updating too

**Comment by rryan** [comment]
The changelog entry needs to be my name though since the PGP key that signs the source package has to be present on the builder.

**Comment by daschuer** [comment]
Yes. I could do it if you wish, but than the maintainer name changes. Is this an issue?

**Comment by daschuer** [comment]
Should I manual enter your name?

**Pull request merged**
