### PR TITLE
Pref > Library: add link to manual > settings files info

### PR DESCRIPTION
**Pull request by ronso0**
Now, the directory and related info can be accessed from one place, and most support responses regarding log files, configs, mappings, database file etc. can be boiled down to
"Open the preferences, go to the Library page and scroll to the bottom"

image

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
LGTM. What do the others think?

**Comment by daschuer** [comment]
Yes, that will work hopefully better. I had a look to other applications:

* Eclipse "Installation details" button in the about box
* Firefox "Help" > "Info for .."
* SmartGit "Information" Tab in the about box 
* LibreOffice Exta Preferences node

So we are in good companion whatever we decide.

**Comment by ronso0** [comment]
To clarify:
this PR just adds the link to the manual.

Moving the entire section to another place will **not** happen in this PR.

Merge?

**Comment by Be-ing** [comment]
Eh, I'm not sure we should add even more text here; it's already quite wordy. I think it would be better to remove this whole section from the preferences and add a link to the Help menu.

**Comment by ronso0** [comment]
Those are currently three lines of text. Adding a link adds value _now_.

Moving the entire block to the Help menu and formatting the dialog is out of scope here and will happen in another PR.

**Comment by Be-ing** [comment]
Three lines of text is probably more than most users read already.

**Comment by Swiftb0y** [comment]
Please just merge this. The fact that we're already 10 messages deep into a discussion on a PR this trivial makes no sense. This is bikeshedding at its best. The work has been done and we only need to press a single button to merge this. If instead we start arguing about marginally better approaches, we'll get nowhere, this won't get merged, contributors will stop contributing.

**Comment by Be-ing** [comment]
I'm not sure that adding more text to a wall of text is a great idea but :shrug:

**Pull request merged**
