### PR TITLE
Fix armhf builds

### PR DESCRIPTION
**Pull request by daschuer**
Add a missing ifdef guard.

### CODE REVIEW

**Comment by daschuer** [comment]
This is a https://github.com/mixxxdj/mixxx/pull/3474 follow up. 

Unfortunately the server for ppa packaging is down. 

@moretocome: Can do give this a try?

**Comment by daschuer** [comment]
Jenkins is back. 

Merge?

**Comment by moretocome** [comment]
Building for armhf completed successfully on Raspbian Buster, RPi4b. Great effort, guys! :)

**Comment by Be-ing** [comment]
Thank you for testing.

**Comment by daschuer** [comment]
@moretocome 
Thank you very  much for testing.
Can you verify if the PPA works for armhf as well?
https://launchpad.net/~mixxx/+archive/ubuntu/mixxxbetas

Which hardware do you use?
How is the performance of the different waveforms types? 

I think you have no spinnies, right?

Please also start 
mixxx --developer 

And check how the vsync waveform behaves.
It should show a pink area when you let Mixxx playing a track, without additional Gui actions.

Thank you.

**Pull request merged**
