### PR TITLE
Add a QGLContext::makeCurrent call before checking if the context supports shaders.

### PR DESCRIPTION
**Pull request by rryan**

### CODE REVIEW

**Comment by Be-ing** [comment]
Hmmm, I thought I remember an RGB (GLSL) renderer, but the only GLSL renderer I see now is the Filtered one. It looks like there is a scaling issue:
screenshot from 2018-05-28 00-24-23
[Qt documentation](http://doc.qt.io/qt-5/highdpi.html) mentions that OpenGL rendering is not automatically scaled, but I am confused why the GL renderers are okay but not GLSL.

**Comment by rryan** [comment]
Yea I also have the same scaling issue on macOS. I see the RGB (GLSL) renderer though.

**Comment by rryan** [comment]
You're sure that the RGB (GLSL) option isn't available? I have no idea how that can happen, since the GLSL renderers are all guarded by this single boolean.

**Comment by Be-ing** [comment]
I think we need to scale everything in the GL renderers by [QWindow::devicePixelRatio](http://doc.qt.io/qt-5/qwindow.html#devicePixelRatio).

**Comment by ninomp** [comment]
I tested this today and didn't notice any issues, so let's merge this since it solves issue of disabled GLSL renderers on Qt5.

**Comment by Be-ing** [comment]
@ninomp the issue with high DPI scaling still hasn't been solved.

**Comment by rryan** [comment]
> @ninomp the issue with high DPI scaling still hasn't been solved.

I don't think the two issues are related though, so I think this can merge. Regular DPI users (I think the scaling is fine for that case?) can't use GLSL renderers in master right now too.

**Comment by rryan** [comment]
> I think we need to scale everything in the GL renderers by QWindow::devicePixelRatio.

Is anyone working on this? I can take a look.

**Comment by Be-ing** [comment]
Okay, let's merge this then. AFAIK no one is currently working on that scaling issue.

**Pull request merged**
