### PR TITLE
lp1763007: Fix invocation args of pasuspender

### PR DESCRIPTION
**Pull request by uklotzde**
https://bugs.launchpad.net/mixxx/+bug/1763007

### CODE REVIEW

**Comment by Be-ing** [comment]
Why is this change needed?

**Comment by uklotzde** [comment]
Not really need unti we add parameters to the invocation of Mixxx. Otherwise those command-line args would be interpreted by pasuspender: https://linux.die.net/man/1/pasuspender

**Comment by daschuer** [comment]
There are two more places.
In these cases without tailing "|| mixxx" should we add that as well?

**Comment by uklotzde** [comment]
Thanks for the hint. Yes, I will do this.

**Pull request merged**
