### PR TITLE
2.3 i18 update

### PR DESCRIPTION
**Pull request by esbrandt**
This also fixes [2.3.0 x64 column names wrong language](https://bugs.launchpad.net/mixxx/+bug/1887185).

### CODE REVIEW

**Review by Holzhaus — APPROVED** [review]
I merged this locally and it looks good with LANG=de_DE, LANG=en_UK, LANG=fr_FR, LANG=sl and LANG=tr_TR (at least at first glance). Do you recommend another way to test this? Reviewing a 95K line diff by hand is not feasible IMHO :D

**Comment by esbrandt** [comment]
I'm afraid this is kinda black hole.
Most of the changes are coming from line numbers that have changed since the last commit. So every language file gets updated, even if no string has possibly changed.
If we'd use ``lupdate -no-ui-lines`` the diffs are significant smaller. But since we use it with ui lines from the beginning, there is no practical knowledge about unwanted side effects.

I do check `DE` translations extensively for quality, other languages on occasion by running quality checks, and fixing the obvious (e.g. whitespace, repeated words etc.) by hand.

**Comment by Holzhaus** [comment]
Alright. Shall I merge then?

**Comment by esbrandt** [comment]
Please.
Transifex will pick it up automatically, and the translators can update the new strings.

Found a possible source for automating the process, see https://github.com/parente/helloworld-transifex-rtd

**Comment by Holzhaus** [comment]
@esbrandt Is it okay to use `git checkout --theirs res/translations` when merging `2.3` into `main`?

**Comment by Holzhaus** [comment]
I should proably use `--ours` instead.

**Pull request merged**
