### PR TITLE
cleanup: remove obsolete includes & forward declarations from pref dialogs

### PR DESCRIPTION
**Pull request by ronso0**

### CODE REVIEW

**Review by Swiftb0y — APPROVED** [review]
LGTM, waiting for CI

**Comment by daschuer** [comment]
Oh, the same happens here. Please merge PRs with a merge commit.

**Comment by Swiftb0y** [comment]
Do we have a guideline against that? If so we should forbid it in the repo settings

Screenshot from 2022-08-12 17-49-48

**Comment by daschuer** [comment]
Yes, but never mind in this case. 

https://github.com/mixxxdj/mixxx/blob/main/CONTRIBUTING.md
> Merge PRs using a merge .... 

I have just added the changelog entries to https://github.com/mixxxdj/mixxx/pull/4882 

Thank you for the hint with the GitHub preferences.

**Comment by daschuer** [comment]
I have updated the setting.

**Pull request merged**
