### PR TITLE
CMakeSettings.json: start with a copy of a UTF-8-BOM file. 

### PR DESCRIPTION
**Pull request by daschuer**
Starting with a UTF-8-BOM file removes the non ASCII Characters form the ASCII + code page encoded batch file.
These turns out to get lost regularly.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
@JosepMaJAZ Could you've a look. If I remind correct, the original code was added by you.

**Comment by daschuer** [comment]
If the resulting CMakeSettings.json is not changed by this patch, it should be save to merge.

**Comment by JosepMaJAZ** [comment]
It's an interesting solution. I guess this way it should not get damaged.

**Comment by daschuer** [comment]
CI is working now

**Comment by daschuer** [comment]
@JoergAtGithub can we merge this now?

**Comment by JoergAtGithub** [comment]
I tested this and it works for me. Thank you!

**Pull request merged**
