### PR TITLE
Replace qWarning() with qInfo()

### PR DESCRIPTION
**Pull request by Holzhaus**
qWarning() is used by Qt classes, e.g. when you try to use QList::insert
at an invalid index. To debug this, you can set the Q_FATAL_WARNINGS
environment variable.

Unfortunately, this is currently not feasible because we're using
qWarning() elsewhere in our code (we already have DEBUG_ASSERT for
potentially fatal programming errors).

Hence, this commit replaces all occurrences of qWarning() with qInfo(),
so that the environment variable can be used to debug these issues.

### CODE REVIEW

**Comment by Be-ing** [comment]
I am doubtful this bulk find-and-replace is a good idea. We are using Qt's logging categories incorrectly in many cases, but many of these warnings really should be warnings. Many of them should be debug level, but I am doubtful many of them should be info level. According to [Qt documentation](https://doc.qt.io/qt-5/debug.html#warning-and-debugging-messages):

```quote
    qDebug() is used for writing custom debug output.
    qInfo() is used for informational messages.
    qWarning() is used to report warnings and recoverable errors in your application.
    qCritical() is used for writing critical error messages and reporting system errors.
    qFatal() is used for writing fatal error messages shortly before exiting.
```

**Comment by Be-ing** [comment]
Also, I generally don't think we should be doing bulk find-and-replace changes on the beta branch.

**Comment by Holzhaus** [comment]
The point is that using qWarnings completely makes QT_FATAL_WARNINGS unusable.

We have multiple locations where we use Qt incorrectly. In that case a warning is printed:

    Warning [Main]: QList::insert(): Index out of range.

However, you have no indication what part of the codebase that error came from. The Qt documentation suggests this:

> If the QT_FATAL_WARNINGS environment variable is set, qWarning() exits after printing the warning message. This makes it easy to obtain a backtrace in the debugger.

Using this PR, I was able to fix the issue in #3067. However, we still have a bunch of other issue in our codebase. Also, we need a way to do this reliably to avoid introducing issues like this in the future.

If you know a better way to make these issues fatal (e.g. by specifying a specific compiler flag), I'm open to suggestions. But I'm not aware of an alternative.

**Comment by Holzhaus** [comment]
By the way, in the Qt 3.3 I found this:

> If you define the flag QT_FATAL_ASSERT, Q_ASSERT will call fatal() instead of warning(), so a failed assertion will cause the program to exit after printing the error message.

This seems to have been removed in Qt 5 though. Looks like QT_FATAL_WARNINGS is our best bet. If someone knows a better way to make Mixxx crash if Qt is used incorrectly, please let me know.

**Comment by uklotzde** [comment]
We need to report recoverable application errors somehow. Using log level *Info* for this purpose is wrong.

Logging: During normal operation (i.e. with default *verbosity* settings) only warnings and more severe errors are logged. Log level *Info* is typically enabled by increasing the verbosity.

**Comment by uklotzde** [comment]
...otherwise, we need to keep *Debug* as our default log level as before and use *Info* solely for warnings. But it feels wrong and every developer needs to be aware about this strange interpretation.

**Comment by uklotzde** [comment]
By using logging categories we could disable warning caused by Mixxx selectively. This will allow us to catch Qt warnings as needed during development. This is the way to go.

**Comment by uklotzde** [comment]
I have proposed a root "mixxx" logging category in #2782, which should cover exactly this use case.

**Comment by Holzhaus** [comment]
@uklotzde Did you test disabling mixxx warnings and setting `QT_FATAL_WARNINGS=1`? If that works, I'm happy to close this.

**Comment by uklotzde** [comment]
Not yet tested.

**Comment by uklotzde** [comment]
`QT_LOGGING_RULES="mixxx.*=false"` works as expected. Qt warnings still abort execution as intended.

**Pull request closed without merging**
