### PR TITLE
rearrange seek calls to remove an extra buffer of latency

### PR DESCRIPTION
**Pull request by ywwg**
how did this not break tests?
fixes lp:#1424412

### CODE REVIEW

**Comment by ywwg** [comment]
nevermind obvious scratching bug, lemme work on this

**Comment by rryan** [comment]
Cool -- thanks. So re: scratching -- this means we'll seek phase on the next callback instead of the current one. We could requestSyncPhase() and then processSeek() in that same block but then the speed would potentially be wrong. Which is worse -- one buffer delay in sync phase or an incorrect synced speed?

Can we call calculateSpeed again in that block? I think the scratch controller and jog filter wouldn't like that since they rely on one call to calculateSpeed per callback for their timing.

**Comment by ywwg** [comment]
Since we don't know if scratching is still active until calculatespeed has been called, I think the best choice is to have the syncphase be one buffer late.  Having wrong speed seems much worse to me.  Since syncphase is sample-perfect, a one-buffer delay won't cause any problems with sync.

**Comment by ywwg** [comment]
hand-tested, basic functions like loop rolls, master sync, and quantizing on overview click work.  (note to self, sounds like a good list of e2e tests to write)

**Comment by rryan** [comment]
cool, lg

**Pull request merged**
