### PR TITLE
fix keyboard mapping sheet background

### PR DESCRIPTION
**Pull request by ronso0**
whoopsy, besides the improvements in #3775 the actual keyboard layer was hidden  O_o
now it's fixed-fixed. please double-check...
image

this is also the base for the manual PNG https://github.com/mixxxdj/manual/pull/370

### CODE REVIEW

**Comment by esbrandt** [comment]
Auto DJ mappings are missing the ``Shift`` key image color.
https://github.com/mixxxdj/mixxx/blob/9df505c3c8f56d6ff1495b1ed9001648e70e1c45/res/keyboard/en_US.kbd.cfg#L1-L5

**Comment by ronso0** [comment]
uuh, thanks!

**Comment by ronso0** [comment]
ready to roll.
@esbrandt Wanna do another check?

**Comment by Holzhaus** [comment]
Thanks, looks got. But Is this really for en-US keyboard layout? Because the keyboard looks like an ISO keyboard, not a standard american ANSI keyboard.

https://support.getfreewrite.com/article/44-freewrites-physical-keyboard-layouts-ansi-vs-iso

Not sure if this is feasible to fix here, just want to point it out.

**Comment by ronso0** [comment]
I _think_ the key  layout was first made for de_DE and the en_US caption was added, thus only the labels somehow match en_US.
I have no intention to fix that here since all the single key graphics layering is a bit broken, and key Clone feature, too, and is cumbersome to work with. glad I'm done with that.

Merge?

**Pull request merged**
