### PR TITLE
Upgrade bundled libebur128 from version 1.2.3 to 1.2.4

### PR DESCRIPTION
**Pull request by uklotzde**
A minor bug fix release, not sure if we are actually affected:
https://github.com/jiixyj/libebur128/releases/tag/v1.2.4

Like for other bundled libs I removed the version tag from the directory name. This avoids to unnecessarily touch the build files for future version upgrades and provides a stable and dependable entry point, e.g. when deciding to drop the bundled libs during a distribution package build. The current version is noted in the bundled README.md.

### CODE REVIEW

**Comment by daschuer** [comment]
This fails on Windows: 
lib\libebur128\ebur128\ebur128.c(539): fatal error C1021: invalid preprocessor command 'warning'

it is 
#warning "manual FTZ is being used, please enable SSE2 (-msse2 -mfpmath=sse)"

because #ifdef __SSE2_MATH__  above

**Comment by uklotzde** [comment]
Same issue as last time. I will submit a PR for the upstream repo ;)

**Comment by daschuer** [comment]
Thank you. It looks like the same patch was applied before and was get lost. 
At least it cannot be found upstream. 
They have recently applied this PR: 
https://github.com/jiixyj/libebur128/pull/78

Dose it help for us? If not we should propose an own PR. 

At least we should here also commit a patch file into our source tree to document the changes and re-apply the patch on later upgrades.

**Comment by uklotzde** [comment]
Let's give it a try...

**Comment by uklotzde** [comment]
That did the trick. Since this commit will be part of the next release we don't need to create a separate patch file for documentation purposes.

We still don't have any concept how patches to bundled libraries are managed. Some libraries like the Soundtouch sources a just a collection of source files that have been copied manually out of some release archive.

**Comment by daschuer** [comment]
OK, Thank you. LGTM

**Pull request merged**
