### PR TITLE
remove Novinyl preferences page

### PR DESCRIPTION
**Pull request by ronso0**
[as discussed](https://mixxx.zulipchat.com/#narrow/stream/109176-documentation/topic/Vinyl.20Control) this page is useless because currently we built with VC for all targets.
In case we need to disable VC for any release/platform in the future we can restore that page with a more meaningful message.

### CODE REVIEW

**Comment by Be-ing** [comment]
Let's wait for #3476...

**Comment by ronso0** [comment]
Ready for merge?

**Comment by uklotzde** [comment]
If it is easier to add a new page in case it is needed again then let's drop it.

Does the build still work even if you compile with -DVINYLCONTROL=OFF?

**Comment by ronso0** [comment]
> Does the build still work even if you compile with -DVINYLCONTROL=OFF?

What do you mean, "work"? This PR jst removes the meaningles Pref page 'No Vinyl Control' for when VC is disabled.

Though buiding it with VC=Off throws a few 'unused' warnings.

**Comment by ronso0** [comment]
> Does the build still work even if you compile with -DVINYLCONTROL=OFF?

Hehe, actually it's `2.3` which can't be built with -DVINYLCONTROL=OFF
```
src/preferences/dialog/dlgpreferences.cpp:132:77: error: invalid new-expression of abstract class type ‘DlgPrefNoVinyl’
  132 |     m_noVinylControlPage = new DlgPrefNoVinyl(this, pSoundManager, m_pConfig);
```

I'll try to fix some of the 'unused' warnings here.

**Comment by ronso0** [comment]
Ready.

**Review by uklotzde — APPROVED** [review]
Thanks for going the extra mile and fixing the build for options that are not covered by CI.

**Comment by uklotzde** [comment]
LGTM

**Pull request merged**
