### PR TITLE
prepare a release candidate for 2.1

### PR DESCRIPTION
**Pull request by daschuer**
This can be merged if we have a release candidate. 

We need to pull the translations and we need to merge the skin preview PR https://github.com/mixxxdj/mixxx/pull/1525 and integrate the manual 
What else do we need?  

I think we can relay proud to the final result.Thank very much to all contributors.

### CODE REVIEW

**Comment by nopeppermint** [comment]
any chance for  #1567 in 2.1 ?

**Comment by Be-ing** [comment]
We still have several Critical and High priority bugs on Launchpad which we have not reached a conclusion about as well as a handful of open PRs. There are also a few last minute polishing touches I want to do for Deere (like fixing the alignment of the headphone buttons in the 4 deck mixer). So I am not okay with rushing a release candidate right now.

**Comment by Be-ing** [comment]
We should also double check the 2.0 to 2.1 upgrade process on every OS.

**Comment by Be-ing** [comment]
Remember we have no managers telling us we must meet a certain date. It is no problem to take a few more days to make a truly polished release.

**Comment by daschuer** [comment]
We are in the middle of: 
https://devrant.com/rants/37055/im-nearly-done-just-one-last-bug-to-fix-time-passes-coding-happens-no-not-quite
or 
definition-of-almost-done-300x225

Think from what we are coming, from a point were we where almost ready and started the beta phase to hunt some bugs. Now it feels like it has nothing changed, we are still almost done and hunt for some bugs. 

We have already a delay from around the weak from the original 2018-03-31 schedule. 
It is OK to delay the release even more, but only for named critical bugs with a responsible person and a clear target date. I am curious to see the results of @Be-ing MacOs test, but all that can go to a point release. Looking at the long list of bugs, it would be unfair to delay these fixes, because of a single bug effecting only a minority of users. 

How about issue the release candidate tomorrow and age it for a week and then release it. 
Critical bugs fixes with a low code impact can be added, but nothing else.

**Comment by foss-** [comment]
Another complex decision to be made. On the one hand it would be great to get 2.1 RC out the door. And then again Mixxx isn't exactly known for it's RERO software philosophy.

The last days had some really important fixes which I would not wanna miss in 2.1 (think disabling metadata editing option preventing mixxx becoming unusable on macOS, or Tango performance improvements like https://github.com/mixxxdj/mixxx/pull/1573).

Considering the time it took to get to 2.1 it doesn't even really matter at this point if a few more days pass without 2.1RC1. The work that's still happening does not at all feel like the comic strip posted. 8 open PRs are tagged w 2.1 milestone and it's not like a ton of bugs is hunted.

All that being said, no objections against a quicker release cycle and getting stuff fixed in point releases.

2 cent (of mine)

**Comment by JohnnyC1951** [comment]
Sanity check guys. I have been playing this game a very long time. (yawn.. old-dude talking).
I just installed the very latest beta on Ubuntu Xenial. Been here since Mixxx 1.x

Objective: to stream Mixxx to freeconferencecall.com conference as a virtual radio studio audio source
I am on Ubuntu Xenial and I just want to send the output of Mixxx as an input to Webrtc. I am an not a noobie.
Sounds simple eh?
So, following the docs.. It's so called simple,: run mixxx from terminal not menu and it will all be peachy. Result: mic and othe USB inputs disappeared from the input picking list.

What I do no want to hear (again): works on mac, pulse is crap, works here etc.

What is needed before 2.1 RC: basically works in basic functions on all basic platforms - out of the box.
If it doesn't it is not worthy to be called a RC.
I will get my coat...

**Comment by Be-ing** [comment]
> basically works in basic functions on all basic platforms - out of the box.
If it doesn't it is not worthy to be called a RC.

I agree. However the particular UX issue with the various sound APIs you are referring to is a broader problem on the GNU/Linux and Windows platforms which is outside of our control. The best we can do is document how to work with the mess of sound APIs on each platform. I agree that we are sorely lacking documentation on how to route software input to Mixxx on Windows. That is because we have few Windows developers and AFAIK none of them use Mixxx that way. If you would like to contribute to the [manual](https://github.com/mixxxdj/manual), that would be great.

**Review by Be-ing — CHANGES_REQUESTED** [review]

**Comment by Be-ing** [comment]
Changelog updates: https://github.com/daschuer/mixxx/pull/31

**Comment by Be-ing** [comment]
Also don't forget to merge the latest translations first.

**Comment by daschuer** [comment]
It is done! Great! THANK YOU all!

**Comment by JohnnyC1951** [comment]
@Be-ing  I have now sorted it for Xenial. The problem with Ubuntu sound is nobody seems to think it is THEIR problem. So the answers are strewn around and not all on one place. I have now got a simple procedure that seems to fix the Lion's share of reported issues in just a few lines. I would be happy to write it down and post it somewhere or email it for someone to put in the Manual. It seems a bit silly to set up the whole Git thingy just to insert a paragraph?

**Comment by daschuer** [comment]
Great, just post a patch here.

**Comment by JohnnyC1951** [comment]
This enables Mixxx to be used better **especially** from the command line if you want to use 'pulse only' devices, like my USB microphone and Pulse Virtual Devices. Tested on Xenial.

1/ sudo apt-get install qjackctl pulseaudio-module-jack
2/ IMPORTANT
sudo usermod -a -G audio _username_
That stops the 'Jack could not allocate memory' and 'Cannot start D-Bus - file not found' issues during Mixxx startup. Group membership is only updated on login, so you need to re-login or reboot.

3a/ Open qjackctl > Setup > Options  and into the box marked "Execute script after Startup" paste this:
pactl set-default-sink jack_out

3b/ Make sure you tick the adjacent checkbox to enable it.
_Explanation: Pulseaudio will recognize (through D-Bus) that JACK started, and automatically will route audio to it. When JACK is stopped Pulseaudio will revert to normal routing and start sending audio directly to card again._

If you want to put this in the installer you need to edit: $home/.config/rncbc.org.QjackCtl.conf
From
[Options]
..
PostStartupScript=
PostStartupScriptShell=
..
To:
PostStartupScript=true
PostStartupScriptShell=pactl set-default-sink jack_out

**Comment by JohnnyC1951** [comment]
I tried posting the above in the forum in Firefox & Chrome. It wipes my message, tells me I have too few characters and a phpBB warning at the very top.

**Pull request merged**
