### PR TITLE
Skins: add 'beats undo' button

### LINKED ISSUE #13318: add GUI controls for `beats_undo_adjustment`
### Feature Description

#12954 provides the controls, quoting the TODO from there
> add Undo button to skins to make this more accessible, probably to beatgrid controls section next to the waveforms
(Tango + LateNight only? in Deere controls are already quite dense)

Ideally this happens for 2.5, requires a new tooltip though

### PR DESCRIPTION
**Pull request by ronso0**
Besides the buttons, this also adds a new read-only control `beats_undo_possible` which is updated if beats change or BPM lock is toggled and allows to deactivate (cover) the Undo button.
(this restores the big CurPos button in Tango & LateNight)

image
image
image
image

### CODE REVIEW

**Comment by ronso0** [comment]
That failing Coveralls summary page doesn't make much sense to me https://coveralls.io/builds/67966984

**Comment by acolombier** [comment]
> That failing Coveralls summary page doesn't make much sense to me https://coveralls.io/builds/67966984

Have you tried to sync `main` in your branch? It might happen that some of the recent bits I've made for STEM are detected as removed, thus why it would flag [some of the engine code](https://coveralls.io/builds/67966984/source?filename=src%2Fengine%2Fcachingreader%2Fcachingreader.cpp#L104) not covered anymore

**Comment by ronso0** [comment]
Hmm, I'm pretty sure I worked on top of 2.5

**Comment by acolombier** [comment]
My bad - I didn't see the upstream of this PR.
Might still worth trying to rebase `upstream/2.5` as I guess that might have confused coveralls?

**Comment by ronso0** [comment]
> Might still worth trying to rebase `upstream/2.5` as I guess that might have confused coveralls?

Yep, that did the trick!

**Comment by ronso0** [comment]
This is ready for review!

**Review by acolombier — APPROVED** [review]
LGTM!

**Comment by ronso0** [comment]
Okay, didn't anyone else try this?
I don't think extensive beta testing is required for this addon but it would be cool to have it in asap.

**Comment by ronso0** [comment]
:bell:  _friendly ping_

**Review by daschuer — APPROVED** [review]
Thank you. LGTM

**Pull request merged**
