### PR TITLE
2.3 string update

### PR DESCRIPTION
**Pull request by esbrandt**

### CODE REVIEW

**Comment by ronso0** [comment]
can we include the Search box tooltip here?
https://bugs.launchpad.net/mixxx/+bug/1800047
should be easy, but I didn't start to work on it yet.

**Comment by esbrandt** [comment]
Apparently the string is already in the source, since it is part of the updated template, https://github.com/mixxxdj/mixxx/pull/2092/files#diff-2d788bb682e6c140c5a914473de75d9cR12627

Though i do think the ``artist:BooFar`` part of the string is not a straightforward choice, and the established ``Foo`` would have been better.

**Comment by daschuer** [comment]
LGTM, Thank you.

**Comment by ronso0** [comment]
Ha, how time flies by...
I finished the search box PR and I completely forgot about it
:facepalm:

**Pull request merged**
