### PR TITLE
controllers: add helper to control "waveform_zoom" with potmeters

### PR DESCRIPTION
**Pull request by ronso0**
This came up in the forums https://mixxx.discourse.group/t/waveform-zoom-midi-control-on-a-cc-dial/28293

* first comit is just a cleanup after I failed to find "behaviour"
* second commit is the script helper: default is a continuous range, set 'round' to `true` to get discrete integer steps
* third commit fixes some mappings using the `waveform_zoom` with the ancient range 0..6

**TODO**
- [ ] add note to [[ChannelN],waveform_zoom](https://manual.mixxx.org/2.4/en/chapters/appendix/mixxx_controls.html#control-[ChannelN]-waveform_zoom), improve Feedback note
- [ ] remove 'zoom' from ControlPotmeter controls examples

### CODE REVIEW

**Comment by mxmilkiib** [comment]
Very nice, thank you, but, ultimately, why not push it down to the C++ level? That way it could be bound to a control via the GUI/wizard.

Maybe I'm wrong, but I'm starting to get the feeling there's a "standard library" of these kinds of level of functionality that aren't bindable via the UI? Which as I wordly put on #12337, is an abstraction that's beyond the scope of most users.

**Comment by daschuer** [comment]
Yes, can't we make it a ControlPotmeter?

**Comment by ronso0** [comment]
I've tried that, or rather I tried to make a helper pot.

The issue with `waveform_zoom` is that the user can set the default value at runtime via the waveform preferences, hence we can of course create a ControlPotmeter (and set a step size of 1 so the GUI zoom buttons still work as before) but as soon as the default is changed the _set_default CO would not be working as expected anymore.
I also looked into creating a ControlPotmeterSimple that does not create all sub-controls (only _up/_down) and keep the `_set_default` pushbutton separate, but that that was too much just for one control.

We could also connect the preferences combobox to a separate ControlObject `waveform_zoom_set_default_value` which then triggers a slot in BaseTrackPlayer to `zoomCO->setDefault(newDefaultvalue)`. I didn't check if that is even possible after the control is created and that also felt like a bit too much work.
I can check that again though.

One thing to note: if you want individual zoom levels per deck (to look ahead or tweak cues on a deck while having the overview on another) the current stepped behaviour is good since it is very easy to manually re-sync the zoom levels of multiple decks. With a continuous range that's almost impossible.

**Comment by ronso0** [comment]
> We could also connect the preferences combobox to a separate ControlObject waveform_zoom_set_default_value which then triggers a slot in BaseTrackPlayer to zoomCO->setDefault(newDefaultvalue). I didn't check if that is even possible after the control is created and that also felt like a bit too much work.

Okay, that was easier than expected.

Replaced by #12387

**Pull request closed without merging**
