### PR TITLE
Fix biquad EQ

### PR DESCRIPTION
**Pull request by Be-ing**
When playing with parameter ranges for #1310 I took a look at the code for the 3 band biquad EQ and realized the cut & boost were symmetric instead of asymmetric as they were intended. After fixing that bug, I increased the limit of how much it cuts to -36 dB, which is an arbitrary value that seems to work well. I just chose it because it's an integer multiple of the boost amount (+12 dB).

I think this obviates the need for the biquad + Bessel combination EQ that does not sound as good. There's no need to remove that when it's working, but I think the plain 3 band biquad should be the default. It's close enough to a full kill that I think very few users would care that it's not 100% kill.

### CODE REVIEW

**Comment by daschuer** [comment]
Fist of all: Please revert the last commit making this a default. We have discussed this topic sufficiently and the current master default was the  conclusion.

Thank you for the fix. Even though I didn't use this EQ regular,  it feels not to bad to have only -12 dB to tweak the sound of a track.
Do you think we should offer both ranges?
How about offering the original xone23 type range , plus this, as a wide range type?

**Comment by Be-ing** [comment]
I have reset to the second-to-last commit and force pushed. We can revisit this discussion later. For now we have a big backup of PRs to polish and merge. But please try this updated EQ before dismissing it as the default. I do not think it matters whether it attenuates 100% as long as it is close enough. The deck is certainly audible with all 3 knobs fully down, but it is very faint and I think would only matter if the user sets the EQ knobs that way thinking it would completely mute the track and there is no other deck in the mix at the time.

> Even though I didn't use this EQ regular, it feels not to bad to have only -12 dB to tweak the sound of a track.
Do you think we should offer both ranges?
How about offering the original xone23 type range , plus this, as a wide range type?

I have been using this EQ since it was introduce. On a handful of occasions I have been frustrated that it did not attenuate enough. I do not think we should offer both ranges. I do not understand why the Xone 23 is special or worth emulating. If there is a Xone mixer that is particularly well regarded for its EQs that is worth emulating I think that would be the Xone 92 with its 4 band EQ.

**Comment by Be-ing** [comment]
I am not certain that -36 dB is the magic number to use for the maximum attenuation. I will try performing with this tonight.

**Comment by daschuer** [comment]
This EQ was original modeled after the xone 23
With has a good reputation. 
https://djworx.com/review-allen-heath-xone-23-mixer/
The EQ kill feature is not the main use case. It is more this decent control if sound. This is done in hardware by different circuits for boost and kill with "optimized" characteristics for this use it's use case. 
The xone 92 has a different focus with its EQs
For me, it sounds your use-cases matches more the xone 92 targets. That is no problem for me an you are welcome to design your own EQ for that.

If we now focus this EQ to an other target, we probably loose others. So we schould be sure about that.

**Comment by Be-ing** [comment]
The Xone 23's EQ knobs are labeled -infinity to +8.

**Comment by daschuer** [comment]
It looks like there must be a kind of mix-up happen 
My comment in EQ mentions a -23 dB .. +6 dB EQ as Xone:23 while A&H advertise a "3-band true total kill EQ" with -Inf to +8, which should would be an Isolator type since only this is able to "true" kill. 

However that is not the point, the point is that there is a use case for a gentle EQ and a full kill isolator. 
Because of this, there are many DJ Mixers with a switch to decide for one of it. 
In the DJM-900 you can switch between -26 dB .. +6 dB EQ and a -Inf .. +6 dB Isolator: 
https://forums.pioneerdj.com/hc/en-us/community/posts/203028579-DJM-900-isolator-behaviour-

Conclusion, we should keep a classic EQ with ~-26 dB. 
I am not against your approach here as alternative.

**Comment by Be-ing** [comment]
How about for the default we modify the Biquad + Bessel combination EQ so the Biquad filters go down further and the Bessel does not come in till later to reduce the coloration from the Bessel?

**Comment by Be-ing** [comment]
@daschuer what program were you using in [these screenshots](https://github.com/mixxxdj/mixxx/pull/1007#issuecomment-270791427)?

**Comment by Be-ing** [comment]
Can you find any examples of DJs asking for or praising an EQ for not being full kill? Every discussion I can find about full kill DJ EQs has DJs complaining about certain systems that are not full kill.

**Comment by esbrandt** [comment]
> what program were you using in these screenshots?

Not daschuer, but looks like ``Analyze > Plot Spectrum`` in [Audacity](http://www.audacityteam.org/) to me.

**Comment by daschuer** [comment]
Right, playing a frequency sweep sound.

**Comment by daschuer** [comment]
https://github.com/mixxxdj/mixxx/pull/1007#issuecomment-272103434
Here is also the answer for the mixer which was the model for this original EQ
The xone:32.

**Comment by Be-ing** [comment]
I realized this is another use case for [custom effect parameter ranges](https://bugs.launchpad.net/mixxx/+bug/1654491). If we had that functionality, we could set the maximum ranges to be ridiculously wide like +/- 100 dB and provide a more sensible range by default.

**Comment by Be-ing** [comment]
I have played a few sets now with the originally intended -23 dB kill and it worked out better than I initially thought it would. I also noticed that many controllers designed for Serato have EQ knobs labeled with -26 dB and the [Xone 32 EQ graph](https://github.com/mixxxdj/mixxx/pull/1007#issuecomment-272103434) shows a -26 dB max kill. Shall we go with a -26 dB max kill?

**Comment by daschuer** [comment]
OK, sounds good.

**Comment by daschuer** [comment]
Thanks!

**Pull request merged**
