### PR TITLE
2.4 i18n update

### PR DESCRIPTION
**Pull request by esbrandt**

### CODE REVIEW

**Comment by Holzhaus** [comment]
Btw you have a typo in your remote name :wink: 

```
$ git remote rename upstram upstream
```

**Comment by esbrandt** [comment]
> Btw you have a typo in your remote name

👍 

BTW, is there a closing tag missing in this new string ?
https://github.com/mixxxdj/mixxx/blob/7866dea6e4ad38392040ea37739feba4ae8cceae/src/encoder/encoderfdkaac.cpp#L263-L268

**Comment by Holzhaus** [comment]
I don't know (maybe it's closed somewhere else?), I think it was added by @daschuer or @Be-ing, maybe they know more?

**Comment by uklotzde** [comment]
> I don't know (maybe it's closed somewhere else?), I think it was added by @daschuer or @Be-ing, maybe they know more?

Seems to be malformed. We have to fix this for 2.3.

**Comment by uklotzde** [comment]
Thanks for taking care! LGTM

**Pull request merged**
