### PR TITLE
Rename debug assertion macro

### PR DESCRIPTION
**Pull request by uklotzde**
The DEBUG_ASSERT_AND_HANDLE macro is handy for handling unexpected runtime errors, e.g. malformed SQL commands and queries. Those errors are typically handled by aborting the invoked function through an early exit. Instead of only printing a warning log message the debug version should exit with an assertion. Otherwise those unexpected errors might slip into a release version without noticing during testing.

Evaluating the condition of a debug assertion should have no side effects. But in this case the side-effects are intended in contrast to the naming of the macro. Therefore I propose to rename this macro into VERIFY_OR_DEBUG_ASSERT. The debug assertion only kicks in if the condition evaluates to false.

See also: https://github.com/mixxxdj/mixxx/pull/1099
I'm using this macro extensively for checking the result of database operations. In accordance with @daschuer we came to the conclusion that the naming of this macro is inappropriate and misleading.

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you, taking care about it. This improves the situation and could be merged. 

My hope was you come up with something fancy, that moves the verified call more left and fixes the inversion issue due to the assert logic.

If (call() == -1) {
    return error;
} 

becomes

VERIFY_OR_DEBUG_ASSERT(call() != -1) {
    return error;
} 

It would be nice to have something like this:

If (call() == -1). assert_else {
    return error;
} 

Is this possible with c++11

**Comment by uklotzde** [comment]
After reading through this I became disappointed that I still need to use C++11/14/17... nowadays:

https://doc.rust-lang.org/book/error-handling.html

No, I don't have any clever C++ solution on how to improve this macro further. And I gave up to think about it ;)

**Comment by uklotzde** [comment]
The macro could also be named VERIFY_OR_ELSE_DEBUG_ASSERT, but I wanted to keep the name short.

**Comment by rryan** [comment]
> After reading through this I became disappointed that I still need to use C++11/14/17... nowadays:
> 
> https://doc.rust-lang.org/book/error-handling.html

:+1: let's rewrite in Rust. ;) 

One thing I miss from my work that makes C++ error handling saner is a Status/StatusOr class. Some of it has leaked into the open source world:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/core/status.h
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/core/error_codes.proto
https://github.com/google/kythe/blob/dde5e72515513b3d4cb0b90855d7839d87733b12/third_party/proto/src/google/protobuf/stubs/status_macros.h#L49
https://github.com/google/lmctfy/blob/94729318edb06f7d149f67581a07a4c70ed29250/util/task/statusor.h (This version of StatusOr does not have move constructors, which are a key part of making it lightweight.)

StatusOr is like the Result type (except you can't specify a custom error type -- it's always a result code and a string) and RETURN_IF_ERROR is like the try! macro in Rust.  Right now our error handling is a mix of enums, status integers, and code that creates a dialog box directly. If we're ever going to port to Android or iOS we at least need to get those dialog boxes out of there :).  I think having a more standard error handling setup that makes it easy to plumb an error code or message from the deep internals to the outside where the user-interface can handle it properly would be a win.

**Comment by rryan** [comment]
(The new name SGTM)

**Comment by daschuer** [comment]
> The macro could also be named VERIFY_OR_ELSE_DEBUG_ASSERT, but I wanted to keep the name short.

No, I am also heading for a shorter name, but the current is OK. To much C++ magic to makes it look nicer is probably a source of confusion later. 
So lets merge this. Thank you.

**Pull request merged**
