### PR TITLE
Denon MC6000MK2: Finish effect unit mapping

### PR DESCRIPTION
**Pull request by uklotzde**
Well, almost finished. Still a lot of housekeeping to do behind the scenes.

### CODE REVIEW

**Comment by Be-ing** [comment]
I am a little confused. What is the effectFocusButton mapped to? Pressing the Beats encoder?

**Comment by uklotzde** [comment]
Correct. It expands and collapses the effect unit panel. Do you have an idea that is more appropriate.

I also thought about controlling the super knob with Shift + Beats encoder, but that can be added later.

**Comment by Be-ing** [comment]
That works but does not have an LED indicating whether an effect is focused. I would have suggested using the Tap button for effectFocusButton but if you prefer to keep that for the effect unit enable button that is fine. IMO the effect unit enable button is an unnecessary layer of complication considering there are enable buttons for each effect, hence why it was removed from skins. The redundant enable switch at the effect unit level is one more state the user can get confused about while mixing.

**Comment by uklotzde** [comment]
I also assumed that is an unnecessary layer, but it isn't. While the effect unit is disabled, all enabled effects are still processed. When you enable the whole unit the effects are applied immediately without any ramp up! This difference in behavior is relevant for feedback effects like echo and delay.

For the push encoder I don't need a visual feedback on the controller if the function just changes the layout on the screen without affecting playback. Just like a click on your mouse. Although it is only useful for quickly checking the effect configuration. If you want to change it you still need to grap your mouse.

**Comment by Be-ing** [comment]
The effectFocusButton does not just change the layout, it allows for focusing effects: https://mixxx.org/wiki/doku.php/standard_effects_mapping

**Comment by uklotzde** [comment]
Thanks for the hint, Be! I'm now aware of it after reading your comments about the N4 ;) But before it becomes usable I have to replace the static led mapping with a components compliant version. I will gradually try to adopt the proposed standard mapping.

**Comment by Be-ing** [comment]
> While the effect unit is disabled, all enabled effects are still processed. When you enable the whole unit the effects are applied immediately without any ramp up! This difference in behavior is relevant for feedback effects like echo and delay.

I can reproduce this. It is a bug. You are right that it is necessary to have a way for Echo and Reverb to receive input without mixing their output. The intended way to do this is by turning those effects on with the dry/wet knob fully dry.

**Pull request merged**
