### PR TITLE
Mixxx skin: Dark Metal

### PR DESCRIPTION
**Pull request by daschuer**
#  Mixxx skin: Dark Metal

mixxx_dark_metal_thumb

## 1) 100% Scalable Vector Graphics (SVG).
• 100% Quality lossless graphics.
Not even one bitmat anywhere.
## 2) Fully resizable.
• Small screen users can use it too.
All elements must fit nicely in all resolutions. Please note that If your resolution is too small, some racks (rows) may overlap, even so, you can still disable their visibility (there are lots of buttons, in the top bar, for that. These buttons are always visible, no matter what, even you "enable" everything). Ready from 980x350, to infinity.
## 3) Mixxx features.
• Contains the lattest Mixxx features.
But!... I´m sure that not all tasks arent done, so I´m always sharping the graphics, correcting issues, adding forgotten stuff...
## 4) Unique features.
• Contains original and unique features.
I´ll try to add features not available (yet!...) anywhere else, they must be functional too, of course. Like the analog VUs, the digital fonts, a grey only color scheme (a fully "metallic" skin), etc, etc... Our imagination (vs. the code), will be the limit...

This skin lives here: 
http://www.mixxx.org/forums/viewtopic.php?f=8&t=6052
(Lives alone... No fitable skeleton was found yet!...)

### CODE REVIEW

**Comment by daschuer** [comment]
This is the successor of https://github.com/mixxxdj/mixxx/pull/1179
Please note comments there.

**Comment by jorgerosa** [comment]
Thankyou for your big help and work, Daniel Schürmann.

**Comment by jorgerosa** [comment]
**Last update: 4 August 2017**
1: Added the new Laptop Battery indicator. (NOT functional, since it seems that is not compiled with Mixxx yet)
2: Added the new "recording time" indicator.
3: Corrected colors for the #AARRGGBB color format. (Noticeable in the waves)
4: Added "star rating" in the main (big) decks.
5: Added the new "effect selector" (QComboBox) in the effects. (Click in the effect name)
6: Added button to show/hide the vinyl controls. (Per deck/channel. Because it seems that many people just dont use it)
7: Added button for "quick effect". (Per deck/channel, in the main (big) decks)
8: Added the "Beat Jump" and "Beat Loop" options.
9: Changed channels texts from "AB","CD" to "12","34". (Requested by users)
10: Added the "cover art", in the small buttons row. (Placed on decks. Helps me a lot, because it "drag-n-drop" feature)
11: Added options to select by module on the "Mics", "Aux" and at "Long Waves".
12: GUI was re-designed (Excessive/Confusing buttons. Much more user-friendly/intuitive GUI by now).
13: All resources were optimized (~300Kb less).
14: Big Decks and Mini Decks can now move partially too. (Done by a Splitter)
15: Beat Sync in the mixer. (Between the Big Decks)
16: Fixed many many other small (minor) issues.

**Comment by jorgerosa** [comment]
--> Added a new "unique" feature called "Strobes", no idea for what is good for... But I like it a lot!  :P 
--> Works sync with music´s "beats" + "gains" (Its a mix of lights)
--> Works 100% OK sync with the music beats, but it needs that the music have high values for "gain" (8 and above, to get the desired light effect... Sorry... Maybe I will be able to fix that, I´ve tried "<transform>" but no luck yet...)

**Comment by Be-ing** [comment]
There is not time to adequately review this before the 2.2 feature freeze.

**Comment by daschuer** [comment]
Nice, nice, nice. 

The Master Volume buttons looks a bit lifted. It would be cool as if they where looking halve way out of a convex metal plate ... 

I experience also a crasher when switching maximized effects. I assume that is unrelated to this PR
I will file a bug.

**Comment by alex-or-dc** [comment]
Hi daschuer and everyone, here is the last modified DarkMetal "styles.qss" I've made, as I've been purposed on the mixxx forum.
Thanks to let me know if you're interesting.
Greetings.
[styles.txt](https://github.com/mixxxdj/mixxx/files/3415018/styles.txt)

**Comment by daschuer** [comment]
@alex-or-dc I have just added your change. You do such things yourselfe. 
Here is a description https://www.mixxx.org/wiki/doku.php/using_git

I have also noticed that the skin has no preview image. If you like you can create them. 
We need a image per color schema. See Shade skin. 
Maybe it is time to consolidate the number of color schemas in turn ..

**Comment by alex-or-dc** [comment]
Hi, thank you very much ! it's great that it's now added ! I'll think about use the pull request, but I'm not used to...At this time I've noticed a sound volume bug when switching off an effect plugin, it was reducing the original volume value on the track. I've made an extended XML file wich should resolve the bug. I join the package with the comment...Would you consider to add these XML to the DarkMetal skin, main folder ?
THX !
Greetings.
[styles_xml.zip](https://github.com/mixxxdj/mixxx/files/3431730/styles_xml.zip)

**Comment by alex-or-dc** [comment]
Hi, dashuer, jorgerosa and everyone ! I'd just would like to purpose a new patch with Logarythmics Gain knobs and back-lighted EQ's for DarkMetal. By the way everything looks like to work fine at 1920x1200 too.
If you think it looks nice, I hope it will be joined to the main skin..
Greetings.
[logarythmic knob patch.zip](https://github.com/mixxxdj/mixxx/files/3472531/logarythmic.knob.patch.zip)

**Comment by alex-or-dc** [comment]
Hi Daschuer and everyone, I'd like to purpose you some new colors shemes for the Dark Metal skin and a multi-screenshot preview, the package also contains some EQs for bus left / right small decks, and others fixes.
Please let me know if you are interested to merge the update ?
Cordialy.

[DarkMetal_Update_Preview.zip](https://github.com/mixxxdj/mixxx/files/3775224/DarkMetal_Update_Preview.zip)

**Comment by alex-or-dc** [comment]
Hi Daschuer, and everyone, I've made a global patch reworking and improvement for both systems Linux and Windows, I'd like to post it on this page, do you also take updates for Windows ?
I'm still not used to setting up git for the pull request..
Waiting for your answer, I hope this page is 100% designed about both systems.

**Comment by daschuer** [comment]
Don't hesitate to send it to me.
I think this skin is equal on all OSs. 
What was you issue on Windows?

**Comment by alex-or-dc** [comment]
Thank you very much, I join the package now, I had general issue and it was not loading or upscaling fine, but this package is only working on x64 system, I've put some of the linux corrected bugs in the styles.xml file instead of the .qss (for windows), so new improvements applied to both versions. Thx.
[DarkMetal_Update_Preview.zip](https://github.com/mixxxdj/mixxx/files/3932017/DarkMetal_Update_Preview.zip)

**Comment by Be-ing** [comment]
>  I'm still not used to setting up git for the pull request..

This concerns me. Please understand that adding a new skin multiplies the work required to maintain Mixxx for every new feature that gets added in the future; it is not something that gets done once and then can be left alone. I am not comfortable merging this or even starting to review it unless we have someone who commits to maintaining the skin into the future and that requires using Git. IMO it is not reasonable to ask us to go out of our way to take the code you send us for every little change via ZIP file and put it into Git. That would be a lot of tedious extra work that we don't do for anyone else. We have a [guide](https://mixxx.org/wiki/doku.php/using_git) to help you start with Git and you can ask for help on [Zulip](https://mixxx.zulipchat.com/) if you have questions.

**Comment by ronso0** [comment]
... and from what I recall from my last review a lot needs to be done to make DarkMetal somehow conform to how the other skins work. Clean up & rename skin COs, tune effect controls etc.

**Comment by alex-or-dc** [comment]
ok no worries, I've removed the post at all. I was thinking I could work this way because of the communautary aspect of Linux and the software, I'm just a beginner, congratulation Mixxx is a great software !

**Comment by ronso0** [comment]
@alex-or-dc 
I see there's a DarkMetal fan base, and I guess that's the reason why @daschuer opened this PR.
I bet you've invested hundreds of hours into DarkMetal (like I did for Tango). It takes like 5min to set up git and another let's say 30min to read the git tutorial, maybe watch a few intro videos, to get used to the basic git commands. Then you'd be ready to open your own PR to add DarkMetal to Mixxx. The rest will learning-by-doing.
I think this way everyone interested in DarkMetal will benefit: the users because they'd get a skin that's working with latest Mixxx features and also working well when switching between official Mixxx skins, also Mixxx devs will support you solving skin issues.

**Comment by daschuer** [comment]
I did a download of your preview zip before you have removed it. 

There are two folders Linux and Windows with only marginal changes. 
Normally we try to find one setting that fits all. 
You changes itself are looking really interesting. 
A before / after screenshot would be nice. 

The preview in the preference is quite big can you reduce it to a height of 250 pixel? 

I can add you changes here so they are not lost, but if you issue a PR to https://github.com/mixxxdj/mixxx/tree/DarkMetal
that would be much better.

**Comment by Be-ing** [comment]
You're welcome to participate in the Mixxx community, but if you want to contribute code, you have to use the tools that the community uses. As @ronso0 said, learning to use Git is probably way less work than you have already invested in working on this skin.

**Comment by Holzhaus** [comment]
I don't think we should add yet another DJ skin to Mixxx without removing one (notable exception: Broadcasting skin). Otherwise we have too many builtin skins that we need to maintain.

**Comment by Be-ing** [comment]
I agree. Let's close this old unmaintained PR.

**Pull request closed without merging**
