### PR TITLE
Bump version to 2.3.0-alpha-pre

### PR DESCRIPTION
**Pull request by sblaisot**
Now that 2.2 branch has been cut out, updating version of master to `2.3.0-alpha-pre` to avoid having two branch with the same version number.

### CODE REVIEW

**Comment by Pegasus-RPG** [comment]
LGTM. (Should we include the bugfix number in the text files too?)

**Comment by daschuer** [comment]
Currently branch 2.2 and master are equal. This PR will change that. 
This means that we have to have to be careful we merge to 2.2 or master.  
Are there any 2.2 PRs target against master?

**Comment by Pegasus-RPG** [comment]
@daschuer If the branch has already been cut, then this PR needs to be merged ASAP to avoid confusion. Your concern applies to other PRs and doesn't hold this up.

**Comment by daschuer** [comment]
I don't not want to hold this up, just explain the situation.

> Should we include the bugfix number in the text files too?

No, I think not that avoids future maintenance.

LGTM

**Pull request merged**
