### PR TITLE
[dont merge] Dump mixxx-test crash report if it fails.

### PR DESCRIPTION
**Pull request by rryan**
[skip appveyor]

### CODE REVIEW

**Comment by rryan** [comment]
There we go -- looks like something is up with qt5 and our sqlite sorting hack. This does not happen on my machine when using qt5 built from source.

@daschuer any ideas?

```
(lldb) thread backtrace all

* thread #1: tid = 0x4620, 0x0000000000000000, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)

  * frame #0: 0x0000000000000000

    frame #1: 0x00007fff81d4119d libsqlite3.dylib`sqlite3_create_collation_v2 + 157

    frame #2: 0x00000001005d257d mixxx-test`TrackCollection::installSorting(this=0x00000001057eef20, db=0x00000001057eef40) + 253 at trackcollection.cpp:193

    frame #3: 0x00000001005d155e mixxx-test`TrackCollection::checkForTables(this=0x00000001057eef20) + 286 at trackcollection.cpp:79

    frame #4: 0x00000001005d137c mixxx-test`TrackCollection::TrackCollection(this=0x00000001057eef20, pConfig=UserSettingsPointer @ 0x00007fff5fbfe578) + 2700 at trackcollection.cpp:42

    frame #5: 0x00000001005d1ff5 mixxx-test`TrackCollection::TrackCollection(this=0x00000001057eef20, pConfig=<unavailable>) + 21 at trackcollection.cpp:29

    frame #6: 0x00000001007b12a0 mixxx-test`LibraryTest::LibraryTest(this=0x0000000105910000) + 144 at librarytest.h:13

    frame #7: 0x00000001007b01e5 mixxx-test`AutoDJProcessorTest::AutoDJProcessorTest(this=0x0000000105910000) + 37 at autodjprocessor_test.cpp:150

    frame #8: 0x00000001007b019f mixxx-test`AutoDJProcessorTest_TransitionTimeLoadedFromConfig_Test::AutoDJProcessorTest_TransitionTimeLoadedFromConfig_Test(this=0x0000000105910000) + 31 at autodjprocessor_test.cpp:206

    frame #9: 0x00000001007b0175 mixxx-test`AutoDJProcessorTest_TransitionTimeLoadedFromConfig_Test::AutoDJProcessorTest_TransitionTimeLoadedFromConfig_Test(this=0x0000000105910000) + 21 at autodjprocessor_test.cpp:206

    frame #10: 0x00000001007b010e mixxx-test`testing::internal::TestFactoryImpl<AutoDJProcessorTest_TransitionTimeLoadedFromConfig_Test>::CreateTest(this=0x000000010575d0d0) + 46 at gtest-internal.h:454

    frame #11: 0x0000000100b6faca mixxx-test`testing::Test* testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::TestFactoryBase, testing::Test*>(object=0x000000010575d0d0, method=11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00, location="the test fixture's constructor")(), char const*) + 122 at gtest.cc:2078

    frame #12: 0x0000000100b5c407 mixxx-test`testing::Test* testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::TestFactoryBase, testing::Test*>(object=0x000000010575d0d0, method=11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00, location="the test fixture's constructor")(), char const*) + 119 at gtest.cc:2114

    frame #13: 0x0000000100b2d253 mixxx-test`testing::TestInfo::Run(this=0x000000010575e400) + 179 at gtest.cc:2317

    frame #14: 0x0000000100b2def7 mixxx-test`testing::TestCase::Run(this=0x000000010575e4f0) + 231 at gtest.cc:2444

    frame #15: 0x0000000100b3c70c mixxx-test`testing::internal::UnitTestImpl::RunAllTests(this=0x000000010575c820) + 908 at gtest.cc:4315

    frame #16: 0x0000000100b7371a mixxx-test`bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(object=0x000000010575c820, method=80 c3 b3 00 01 00 00 00 00 00 00 00 00 00 00 00, location="auxiliary test code (environments or event listeners)")(), char const*) + 122 at gtest.cc:2078

    frame #17: 0x0000000100b5e337 mixxx-test`bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(object=0x000000010575c820, method=80 c3 b3 00 01 00 00 00 00 00 00 00 00 00 00 00, location="auxiliary test code (environments or event listeners)")(), char const*) + 119 at gtest.cc:2114

    frame #18: 0x0000000100b3c328 mixxx-test`testing::UnitTest::Run(this=0x000000010125f8d8) + 408 at gtest.cc:3926

    frame #19: 0x00000001009010b1 mixxx-test`RUN_ALL_TESTS() + 17 at gtest.h:2288

    frame #20: 0x0000000100901059 mixxx-test`main(argc=1, argv=0x00007fff5fbff188) + 297 at main.cpp:33

    frame #21: 0x00007fff8702f5ad libdyld.dylib`start + 1

    frame #22: 0x00007fff8702f5ad libdyld.dylib`start + 1
```

**Comment by uklotzde** [comment]
I'm clueless. Maybe it helps to register the collation function on demand as a workaround?

https://www.sqlite.org/c3ref/collation_needed.html

That might resolve initialization order issues that we currently don't spot.

**Comment by daschuer** [comment]
We have to make sure that the installed sqlite version is the same that is linked into QT.

**Comment by rryan** [comment]
Yea, you're probably right that Homebrew's qt5 isn't linking against Homebrew's sqlite. Looking at the compilation commands, neither specify ```-system-sqlite``` though.

**Pull request closed without merging**
