### PR TITLE
Tango: Make not-clipping light non transparent and adjust size

### LINKED ISSUE #11362: VU meter broken in Tango, Mixxx 2.3.4
### Bug Description

* peak indicatoris not reset
* mic VU meters are reported to not work anymore https://mixxx.discourse.group/t/problem-with-tango-skin/26866

### Version

2.3.4

### OS

Ubuntu + Windows

### PR DESCRIPTION
**Pull request by daschuer**
With the GL VU-Meters, the transparent clipping light does no longer show the background color.
This fixes #11362 

I have picked the darker color of the master background also used without mixer. 

A solution that behaves exactly like before does not allow to use the singleton VU meter. Now It looks like this, IMHO sufficient as a band aid. 

grafik

### CODE REVIEW

**Comment by ronso0** [comment]
Oh great, it was just the transparency, not the stacked layout in general!

1) Now the neutral peak indicator covers the upper part of the level meter?

2) What's actually worse:
initially the stack layout was supposed to work like this: the level background was using the full height and the peak indicator was filling the entire area, as well (instead of extending the level area as in other skins and hardware VU meters).
With my my last remake I shrunk the peak indicator which now covers the upper part only. This alone is pointless as it eliminates the initial, non-conform implementation.

3) Your current fix only covers the deck VU meters. Fixing the tiny sampler, mic, aux & preview meters is tedious.

I see two ways to fix this:
**A** I continue to work on my stashed solution which makes uses a standard vertical layout (peak + level), but that'll take a while. And it's boring tbh.

**B** We remove the peak indicator (rectangle) and use only the clipping border. That'll require a rework of the small meters, too, but I expect that to be easier.

I prefer **B** and I'll find some time to fix it this weekend so that 2.3.5. doesn't have to be delayed any further.

**Review by ronso0 — CHANGES_REQUESTED** [review]
..

**Comment by ronso0** [comment]
Btw, to allow using VUMeterGL singletons with variable background we have `mixxx::widgethelper::findBaseColor(QWidget* pWidget)`.

**Comment by ronso0** [comment]
Nevertheless, thank you for working on this @daschuer Actually this is my task since I messed it up (or didn't double-check when VUMeterGL was merged).

**Comment by ronso0** [comment]
#11430

**Comment by daschuer** [comment]
Superseded by https://github.com/mixxxdj/mixxx/pull/11430

**Pull request closed without merging**
