### PR TITLE
DEBUG 'LoadSelectedTrack' control, triggered via keyboard

### PR DESCRIPTION
**Pull request by ronso0**
added some warnings to maybe debug #13305 

@DJMaxergy Hopefully this helps finding the root cause of that issue.
As soon as CI builds succeeded, please get the macOS build and test (see Testing & Backup instructions https://github.com/mixxxdj/mixxx/wiki/Testing)
I think it would simplify the process if you start Mixxx from the command line and check the output right after you tried to load via keyboard. https://manual.mixxx.org/2.4/en/chapters/appendix/commandline_dev_tools
The copy the last lines with warnings and paste them here (also attach the entire log file https://github.com/mixxxdj/mixxx/wiki/Finding-the-mixxx.log-file)

### CODE REVIEW

**Comment by DJMaxergy** [comment]
Hi @ronso0, thank you for your efforts. 
[mixxx.log](https://github.com/user-attachments/files/15661425/mixxx.log)
I got the macOS build as you suggested, started Mixxx from command line using log level "debug" and clicked on a track in the library window, pressed the down key to highlight the next track and pressed shift+left to load the track into the left deck. This is what I got from the command line log output:

> debug [Main] keyboard press:  "Down"
debug [VSyncThread] DROP
debug [Main] GlobalTrackCache - Resolving track by id 38222
debug [Main] GlobalTrackCache - Resolving track by canonical location "/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3"
debug [Main] GlobalTrackCache - Cache miss - allocating track  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3",38222}
debug [Main] GlobalTrackCache - Cache miss - inserting new track into cache  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3",38222} QObject(0x0)
debug [Main] Successfully deserialized Beats ("BeatGrid-2.0")
debug [Main] Successfully deserialized KeyMap
debug [Main] SoundSourceProxy - SoundSourceProvider "Apple CoreAudio Version 12.7.5 (Build 21H1222)" created a SoundSource for file "file:///Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3" of type "mp3"
warning [Main] TagLib - ID3v2.2 is only partially supported - please convert your file tags to at least ID3v2.3
warning [Main] TagLib - Legacy ID3v2 version - importing only basic tags
debug [Main] BaseTrackCache(0x7fc3fb024d40) updateIndexWithQuery took 0 ms
debug [Main] GlobalTrackCache - Evicting track  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3",38223} Track(0x7fc3bf5ce660)
debug [Main] GlobalTrackCache - Deleting Track(0x7fc3bf5ce660)
debug [Thread (pooled)] SoundSourceProxy - SoundSourceProvider "Apple CoreAudio Version 12.7.5 (Build 21H1222)" created a SoundSource for file "file:///Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3" of type "mp3"
debug [VSyncThread] DROP
debug [VSyncThread] DROP
debug [VSyncThread] DROP
debug [VSyncThread] DROP
debug [Main] keyboard press:  "Shift+Left"

**Comment by ronso0** [comment]
Okay, thanks for testing!
Very strange, somehow the triggering call doesn't reach the track table. I'll add some more logging at the keyboard stage.

**Comment by DJMaxergy** [comment]
Ok, I will test it again as soon as you have added more logging. 
By the way: I tried 2.4.1 on a Windows 10 system and there the keyboard shortcuts for loading a track seem to work.

**Comment by ronso0** [comment]
@DJMaxergy I just added more logging, please test again as soon as CI builds are ready.

**Comment by DJMaxergy** [comment]
Hi @ronso0,
I now tested again and command line log output shows (entire log file
[mixxx.log](https://github.com/user-attachments/files/16146527/mixxx.log)
):

> debug [VSyncThread] DROP
debug [Main] phase-locked-loop: 18744677 16719.7 1705.2
debug [VSyncThread] DROP
debug [Main] GlobalTrackCache - Resolving track by id 38223
debug [Main] GlobalTrackCache - Resolving track by canonical location "/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3"
debug [Main] GlobalTrackCache - Cache miss - allocating track  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3",38223}
debug [Main] GlobalTrackCache - Cache miss - inserting new track into cache  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3",38223} QObject(0x0)
debug [Main] Successfully deserialized Beats ("BeatGrid-2.0")
debug [Main] Successfully deserialized KeyMap
debug [Main] SoundSourceProxy - SoundSourceProvider "Apple CoreAudio Version 12.7.5 (Build 21H1222)" created a SoundSource for file "file:///Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3" of type "mp3"
warning [Main] TagLib - ID3v2.2 is only partially supported - please convert your file tags to at least ID3v2.3
warning [Main] TagLib - Legacy ID3v2 version - importing only basic tags
debug [Main] BaseTrackCache(0x7fe4f98bfde0) updateIndexWithQuery took 0 ms
debug [Thread (pooled)] SoundSourceProxy - SoundSourceProvider "Apple CoreAudio Version 12.7.5 (Build 21H1222)" created a SoundSource for file "file:///Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3" of type "mp3"
debug [VSyncThread] DROP
debug [VSyncThread] DROP
debug [Main] keyboard press:  "Shift+Left"
debug [Main]  > keySeq not empty, lookup control
debug [VSyncThread] DROP
debug [Main] phase-locked-loop: 28753141 16704.5 2926.81
debug [Main] keyboard press:  "Down"
debug [Main]  > keySeq not empty, lookup control
debug [Main] GlobalTrackCache - Resolving track by id 38222
debug [Main] GlobalTrackCache - Resolving track by canonical location "/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3"
debug [Main] GlobalTrackCache - Cache miss - allocating track  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3",38222}
debug [Main] GlobalTrackCache - Cache miss - inserting new track into cache  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3",38222} QObject(0x0)
debug [Main] Successfully deserialized Beats ("BeatGrid-2.0")
debug [Main] Successfully deserialized KeyMap
debug [Main] SoundSourceProxy - SoundSourceProvider "Apple CoreAudio Version 12.7.5 (Build 21H1222)" created a SoundSource for file "file:///Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3" of type "mp3"
warning [Main] TagLib - ID3v2.2 is only partially supported - please convert your file tags to at least ID3v2.3
warning [Main] TagLib - Legacy ID3v2 version - importing only basic tags
debug [Main] BaseTrackCache(0x7fe4f98bfde0) updateIndexWithQuery took 0 ms
debug [Main] GlobalTrackCache - Evicting track  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3",38223} Track(0x7fe4cf9a2110)
debug [Main] GlobalTrackCache - Deleting Track(0x7fe4cf9a2110)
debug [Thread (pooled)] SoundSourceProxy - SoundSourceProvider "Apple CoreAudio Version 12.7.5 (Build 21H1222)" created a SoundSource for file "file:///Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3" of type "mp3"
debug [VSyncThread] DROP
debug [VSyncThread] DROP
debug [Main] keyboard press:  "Shift+Right"
debug [Main]  > keySeq not empty, lookup control
debug [VSyncThread] DROP
debug [Main] phase-locked-loop: 38748928 16722.3 1228.03

**Comment by ronso0** [comment]
Hmkay, it seems there is simply no control found for Shift+Left, which is weird.
Please attach your Custom.kbd.cfg (/Users/DJMaxergy/Library/Containers/org.mixxx.mixxx/Data/Library/Application Support/Mixxx/Custom.kbd.cfg).

**Comment by DJMaxergy** [comment]
But it doesn't work with the default keyboard config file, too. So I don't think it's the Custom.kbd.cfg.
[Custom.kbd.cfg.zip](https://github.com/user-attachments/files/16164190/Custom.kbd.cfg.zip)
*.cfg was not supported for upload, so I had to zip it.

**Comment by ronso0** [comment]
Okay, so it looks like the line `LoadSelectedTrack` for group `[Channel1]` is not found for some reason.
I added output for the parsed cfg file  and the transposed hash (key sequence to ConfigKey).
Please test again and upload the log.

> *.cfg was not supported for upload, so I had to zip it.

yeah, you can simply change/append a supported extension, like txt.

**Comment by DJMaxergy** [comment]
So here are the latest logs...
[mixxx.log](https://github.com/user-attachments/files/16180488/mixxx.log)

> debug [VSyncThread] DROP
debug [Main] GlobalTrackCache - Resolving track by id 38223
debug [Main] GlobalTrackCache - Resolving track by canonical location "/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3"
debug [Main] GlobalTrackCache - Cache miss - allocating track  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3",38223}
debug [Main] GlobalTrackCache - Cache miss - inserting new track into cache  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3",38223} QObject(0x0)
debug [Main] Successfully deserialized Beats ("BeatGrid-2.0")
debug [Main] Successfully deserialized KeyMap
debug [Main] SoundSourceProxy - SoundSourceProvider "Apple CoreAudio Version 12.7.5 (Build 21H1222)" created a SoundSource for file "file:///Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3" of type "mp3"
warning [Main] TagLib - ID3v2.2 is only partially supported - please convert your file tags to at least ID3v2.3
warning [Main] TagLib - Legacy ID3v2 version - importing only basic tags
debug [Main] BaseTrackCache(0x7fe87f0a4da0) updateIndexWithQuery took 0 ms
debug [Thread (pooled)] SoundSourceProxy - SoundSourceProvider "Apple CoreAudio Version 12.7.5 (Build 21H1222)" created a SoundSource for file "file:///Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3" of type "mp3"
debug [VSyncThread] DROP
debug [VSyncThread] DROP
debug [Main] phase-locked-loop: 38358367 16711.2 -369.116
debug [Main] keyboard press:  "Down"
warning [Main]  > keySeq: "Num+Down"
warning [Main]  > lookup control
warning [Main]  ! no CfgKey found
debug [VSyncThread] DROP
debug [Main] GlobalTrackCache - Resolving track by id 38222
debug [Main] GlobalTrackCache - Resolving track by canonical location "/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3"
debug [Main] GlobalTrackCache - Cache miss - allocating track  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3",38222}
debug [Main] GlobalTrackCache - Cache miss - inserting new track into cache  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3",38222} QObject(0x0)
debug [Main] Successfully deserialized Beats ("BeatGrid-2.0")
debug [Main] Successfully deserialized KeyMap
debug [Main] SoundSourceProxy - SoundSourceProvider "Apple CoreAudio Version 12.7.5 (Build 21H1222)" created a SoundSource for file "file:///Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3" of type "mp3"
warning [Main] TagLib - ID3v2.2 is only partially supported - please convert your file tags to at least ID3v2.3
warning [Main] TagLib - Legacy ID3v2 version - importing only basic tags
debug [Main] BaseTrackCache(0x7fe87f0a4da0) updateIndexWithQuery took 0 ms
debug [Main] GlobalTrackCache - Evicting track  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/15 Right Here.mp3",38223} Track(0x7fe87f075570)
debug [Main] GlobalTrackCache - Deleting Track(0x7fe87f075570)
debug [Thread (pooled)] SoundSourceProxy - SoundSourceProvider "Apple CoreAudio Version 12.7.5 (Build 21H1222)" created a SoundSource for file "file:///Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3" of type "mp3"
debug [VSyncThread] DROP
debug [VSyncThread] DROP
warning [Main]  > keySeq: ""
warning [Main]  > keySeq: ""
warning [Main]  > keySeq: ""
warning [Main]  > keySeq: ""
debug [Main] keyboard press:  "Shift+Left"
warning [Main]  > keySeq: "Shift+Num+Left"
warning [Main]  > lookup control
warning [Main]  ! no CfgKey found
debug [Main] keyboard press:  "Down"
warning [Main]  > keySeq: "Num+Down"
warning [Main]  > lookup control
warning [Main]  ! no CfgKey found
debug [Main] GlobalTrackCache - Resolving track by id 38221
debug [Main] GlobalTrackCache - Resolving track by canonical location "/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/13 One Track Mind.mp3"
debug [Main] GlobalTrackCache - Cache miss - allocating track  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/13 One Track Mind.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/13 One Track Mind.mp3",38221}
debug [Main] GlobalTrackCache - Cache miss - inserting new track into cache  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/13 One Track Mind.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/13 One Track Mind.mp3",38221} QObject(0x0)
debug [Main] Successfully deserialized Beats ("BeatGrid-2.0")
debug [Main] Successfully deserialized KeyMap
debug [Main] SoundSourceProxy - SoundSourceProvider "Apple CoreAudio Version 12.7.5 (Build 21H1222)" created a SoundSource for file "file:///Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/13 One Track Mind.mp3" of type "mp3"
warning [Main] TagLib - ID3v2.2 is only partially supported - please convert your file tags to at least ID3v2.3
warning [Main] TagLib - Legacy ID3v2 version - importing only basic tags
debug [Main] BaseTrackCache(0x7fe87f0a4da0) updateIndexWithQuery took 0 ms
debug [Main] GlobalTrackCache - Evicting track  TrackRef {"/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3","/Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/14 Disconnect.mp3",38222} Track(0x7fe853cec190)
debug [Main] GlobalTrackCache - Deleting Track(0x7fe853cec190)
debug [Thread (pooled)] SoundSourceProxy - SoundSourceProvider "Apple CoreAudio Version 12.7.5 (Build 21H1222)" created a SoundSource for file "file:///Volumes/MyMusic/Album Music/Becky Hill - Believe Me Now/13 One Track Mind.mp3" of type "mp3"
debug [VSyncThread] DROP
debug [VSyncThread] DROP
warning [Main]  > keySeq: ""
warning [Main]  > keySeq: ""
warning [Main]  > keySeq: ""
warning [Main]  > keySeq: ""
debug [Main] keyboard press:  "Shift+Right"
warning [Main]  > keySeq: "Shift+Num+Right"
warning [Main]  > lookup control
warning [Main]  ! no CfgKey found
debug [Main] phase-locked-loop: 48368128 16711.1 535.239

**Comment by ronso0** [comment]
Okay, the reason no control is found for `Shift`+`Left` is that obviously `Num` is also involved:
* for `Down` key the QKeySequence is resolved to `Num`+`Down` (which does what it should because Down is handled by the QTableView)
* `Shift`+`Left` resolves to `Shift`+`Num`+Left, and there is no such control in the kbd mapping.
> Debug [Main] keyboard press:  "Shift+Left"
Warning [Main]  > keySeq: "Shift+Num+Left"
Warning [Main]  > lookup control
Warning [Main]  ! no CfgKey found

Please try to disable Num (or whatever that is on mac keyboards) and try again.

**Comment by DJMaxergy** [comment]
Hi @ronso0 ,
I saw that `Num` thing, too, but I don't know where this comes from. The MacBook Air doesn't have any Numpad functionality to activate/deactivate and I don't have any external keyboard connected or something like that. I googled and searched in all the settings but I didn't find any possibility to activate/deactivate this `Num`.
I'm wondering why with Mixxx 2.4.0 the keyboard control works like expected and from 2.4.1 onwards it's not working because of the `Num`? 
The MacOS hasn't changed.

**Comment by ronso0** [comment]
I think I found the commit causing the regression (#12473 -> 59b54da8c16a26234bfc56f3e16a01e865afa450)
With this commit I switched from explicitly checking individual, relevant key modifiers to simply taking all modifiers.
The issue seems to be that Num is always the modifier for the arrow keys.

@DJMaxergy Please test again!
Btw, did you already test a newer version, e.g. 2.5-beta or main (2.6-alpha)?
(just checking if the culprit is just the Qt5 constructor `QKeySequence(e->modifiers() + e->key())` or if the Qt6 version is also affected `QKeySequence(e->modifiers() | e->key())`)

**Comment by ronso0** [comment]
I extracted the fix and opened #13481

**Comment by DJMaxergy** [comment]
> @DJMaxergy Please test again! Btw, did you already test a newer version, e.g. 2.5-beta or main (2.6-alpha)? (just checking if the culprit is just the Qt5 constructor `QKeySequence(e->modifiers() + e->key())` or if the Qt6 version is also affected `QKeySequence(e->modifiers() | e->key())`)

Sorry for the late response @ronso0 . I recently checked 2.5 beta (2.5-beta-15-gdf6529d87e): There the arrow keys as keyboard shortcuts were not working either.
So should I test #13481 instead?

**Comment by DJMaxergy** [comment]
Successfully tested #13481. Keyboard shorcuts with arrow keys are working again on macOS. Thank you :)

**Pull request closed without merging**
