### PR TITLE
LateNight 2.1 :. part II

### PR DESCRIPTION
**Pull request by ronso0**
This PR fixes some minor issues and continues to reduces vertical space requirements.
It's WIP and I'll let it grow for a week or so. Maybe we can even introduce FX unit 3/4 and more samplers here

Reducing samplers height:
ronso0__0 0 9__2018-01-05

### CODE REVIEW

**Comment by ywwg** [comment]
very nice, no comments from me just looking at the screenshot (except that I miss the instant loop buttons for quick rolls, but those disappeared a while ago)

**Comment by ywwg** [comment]
hm, it does look like there are some spacing issues with the loop buttons though.  The box for the loop size seems wider than it needs to be and it's cramming the adjustment buttons

**Comment by ronso0** [comment]
update
ronso0__0 0 10__2018-01-05

**Comment by ronso0** [comment]
> (except that I miss the instant loop buttons for quick rolls, but those disappeared a while ago)

Yeah missed them , too, so I brought them back in Tango a while ago. There it's optional though..
At least for least for quick rolls I'd say we should bring'em back here as well

**Comment by ronso0** [comment]
The up/down buttons of beatsize spinboxes are fixed.
The overlapping is intented: 1) group spinbox & up/down buttons  2) text alignment in spinboxes is not working 100% correctly. Sometimes manually set loops(izes) with decimals may be shifted in a way that only the decimals are visible but everything in front of the point is truncated. Rare case, though
Looking better now?

**Comment by nopeppermint** [comment]
mixer is a little bit higher than the two decks, couldn't you shift up the crossfader a little bit?

**Comment by ronso0** [comment]
> mixer is a little bit higher than the two decks, couldn't you shift up the crossfader a little bit?

@nopeppermint 
No, the mixer is already a good compromise of compact & quickly readable & enough space to be sure you hit the right spot with the mouse. It's just the decks that have bigger margin to the elements below, a nice gap that allows for quick orientation. That's one aspect of LateNight I'd like to keep. You'll notice when you hide the mixer.
 Maybe we also need to increase the other gaps, in between Samplers, FxUnits etc.

**Comment by nopeppermint** [comment]
- on Linux Mint there are some issues with the Text under the Knobs
latenight_update
- and Gain in 4 Deck mode
latenight_gain

- BTW I suggest to use a smaller font size for the sampler Title

**Comment by ronso0** [comment]
There are still font issues, thanks for the hint!
I consider including a font for LateNight, so we don't run into trouble again (like you did) when a system doesn't have the fonts it was originally designed with.

**Comment by ronso0** [comment]
A quick recap of what I changed so far:
- layout fixes everywhere
- QuickEffect & effect toggles are green now, a little darker than before
- nicer loop/jumpsize buttons
- reduced sampler height

Check it out!

**Comment by ywwg** [comment]
I'm not sure what our policies are about bundling fonts, but I agree that's a good idea to prevent this type of issue

**Comment by ronso0** [comment]
> I'm not sure what our policies are about bundling fonts, but I agree that's a good idea to prevent this type of issue

It's just the font license that must allow redistribution.
We already have dedicated fonts for Deere (Open Sans) and Tango (Ubuntu), so maybe we just use Open Sans for LateNight?

**Comment by naught101** [comment]
Latenight's current font is a bit more blocky and strong than Open Sans. I reckon it should be something that's got a bit of a "screenprint on hardware" feel. Possibly something like this? https://fonts.google.com/specimen/Rajdhani

**Comment by esbrandt** [comment]
Use any of the available fonts in /fonts.
Please just not include another font, it will increase load times even more.
They are loaded from /fonts app-wide,  see [Load fonts from the skin directory](https://bugs.launchpad.net/mixxx/+bug/1552427).

**Comment by ronso0** [comment]
> Please just not include another font, it will increase load times even more.

I wasn't aware of that. We should remove `Open Sans Light` since it's not used anywhere, only used as 4th fallback font in LateNight: `"Lucida Grande", "Helvetica Neue", "Segoe UI", Arial, "Open Sans Light"`

How LateNight looks like now (Arial in my case)
ronso0__0 0 11__2018-01-07_arial

with Open Sans
ronso0__0 0 11__2018-01-07_opensans

with Open Sans Light
ronso0__0 0 11__2018-01-07_opensanslight

with Ubuntu font
ronso0__0 0 11__2018-01-07_ubuntu

**Comment by ronso0** [comment]
IMO Ubuntu font comes colsest to what LateNight 'feels like'.
What do you think?

**Comment by naught101** [comment]
I think Open Sans looks slightly better, because it's less rounded (e.g. 3, 7 . But it's much less of a difference than I though it would be, so it's not a big deal either way.

**Comment by ronso0** [comment]
For now, I'll set Ubuntu font for all text buttons and artist/title and OpenSans for numbers like duration, BPM and the beatsize spinboxes.

Font configuration is simplified, so changing this later on is easy.

**Comment by ronso0** [comment]
@ywwg @esbrandt 
I'd like to tackle the button refresh/redesign/vectorize issue now, so maintaining button graphics will be less annoying. To complete the 3D effect, buttons appear to be pressed down/latched.
See CUE example below; I already implemented this in the skin to preview:
ronso0__0 0 11__2018-01-08__new_button_graphics


This affects transport, Cue, HotCue, loop, jump, Sync, Talk & Pfl buttons.

Also I'd create HotCue buttons 5-8. Since transport row is already quite crammed (at minimum window size), and we'll need to discuss where/when to show additional HotCues and what to do with reverse seek buttons. Any ideas?

**Comment by ronso0** [comment]
Re: [Bug1741152 LateNight widgets: Rating, Beatgrid adjustment](https://bugs.launchpad.net/mixxx/+bug/1741152)

Star rating could go to
A) decks' top row and pop up if vinyl controls are disabled or vinyl controls are visible and there's enough space left
B) into deck controls container:
ronso0__0 0 11__2018-01-08__star_rating

**Comment by naught101** [comment]
Or in the track title row, left of the total time?

**Comment by ronso0** [comment]
ping @ywwg @esbrandt 
If you don't have any objections regarding the new button graphics, I'll just do it.
I just did a quick test and see that transparency gradients work out for the drop shadows, so I'll also start the transition to vector graphics.

Any thoughts re: seek/reverse buttons?

**Comment by ywwg** [comment]
buttons look fine to me!  I'd even be ok with eventually replacing the graphics with raw css wherever possible

**Comment by ywwg** [comment]
> I'll also start the transition to vector graphics.

yes this sounds like a great idea



> Any thoughts re: seek/reverse buttons?

The seek buttons probably aren't needed, but reverse is nice (esp right clicking for a reverse roll)

**Comment by ywwg** [comment]
> The overlapping is intented: 1) group spinbox & up/down buttons 2) text alignment in spinboxes is not working 100% correctly. Sometimes manually set loops(izes) with decimals may be shifted in a way that only the decimals are visible but everything in front of the point is truncated.

can you post an example of this?  The overlapping looks like a mistake and if there's a problem with the text display we should fix that instead of working around it.

**Comment by ronso0** [comment]
> buttons look fine to me! I'd even be ok with eventually replacing the graphics with raw css wherever possible

What do you mean? And what did you mean with
> I much prefer keeping the graphics procedural.

Styling them in side xml with `<Pressed>` and `<Unpressed>` nodes has the only advantage to style the pressed (not toggled) state, which is cool for Cues etc. but in most places it's not visible.
Any idea how to achieve this via css?

Downside of xml styling is that graphics need to fit the button size, respectively determine the button size when it's not defined, and are not scaled but always aligned top-left in case the button is bigger than the graphic.

Anyway, a future task would be to switch to button templates like we use them in Deere and Tango. This saves miles of scrolling while maintaining the skin.

**Comment by ronso0** [comment]
> In mixxx 2.0 latenight the library sidebar could be shiftet much more to the side/made smaller
could you made this possible again in latenight with 2.1?

@nopeppermint Sure, I'll look into it.

**Comment by ronso0** [comment]
> can you post an example of this? The overlapping looks like a mistake and if there's a problem with the text display we should fix that instead of working around it.

@ywwg Back when I noticed it I filed a bug https://bugs.launchpad.net/mixxx/+bug/1716237
Right now I can't reproduce it, actually my workaround makes it worse (in LateNight, will check the other skins)
I'll try to remove the overlapping, but I'd like to the 'broken alignment' of the spinbox buttons. Right now this is the only "piece of funk" in LateNight, the rest is all grids, recctangular..
Do you know what I mean?

**Comment by nopeppermint** [comment]
@ronso0 
nice, now it is possible to made the library sidebar smaller, thanks!
But now you can no longer completely hide the sidebar by sliding even more to the left..

**Comment by Be-ing** [comment]
> IMO Ubuntu font comes closest to what LateNight 'feels like'.
Open Sans is too condensed and has worse readability.
What do you think?

Personally I don't like the Ubuntu font very much (it's one reason I don't like looking at Launchpad). I think the [Rajdhani font](https://fonts.google.com/specimen/Rajdhani) @naught101 suggested could work well with LateNight's aesthetics.

>  Maybe we also need to increase the other gaps, in between Samplers, FxUnits etc.

Yes, we should make clearer borders between skin sections in all skins. Currently only Shade does that well.

> The seek buttons probably aren't needed

I agree, the seek buttons are not needed because users can click on the waveforms.

> To complete the 3D effect, buttons appear to be pressed down/latched.

This looks good while the button is held down, for example with the hotcue buttons. But keeping the button looking like it is pressed down after it is released feels weird to me, especially for the play button. In general, the vectorized buttons look smoother, thanks.

> Sometimes manually set loops(izes) with decimals may be shifted in a way that only the decimals are visible but everything in front of the point is truncated.

I think this is a quirk of the widget that affects all skins. If anyone has ideas how to improve this, please share.

>  I miss the instant loop buttons for quick rolls, but those disappeared a while ago

I think every skin should have an option for the fixed loop size buttons like Tango (not necessarily toggled in the same way as it is in Tango) because they are easier to use with only a mouse and keyboard.

I feel the white/gray font color used when the beatloop size and beatjump size spinboxes are active is somewhat odd. It makes the text blend in with the surrounding buttons instead of jump out. I also feel like the way the up/down buttons next to the spinboxes don't have anything underneath them looks odd.

**Comment by ronso0** [comment]
> But now you can no longer completely hide the sidebar by sliding even more to the left..

fixed, was a copy/paste error.

**Comment by ronso0** [comment]
> Personally I don't like the Ubuntu font very much (it's one reason I don't like looking at Launchpad). I think the Rajdhani font @naught101 suggested could work well with LateNight's aesthetics.

Just a quick reply regarding the fonts:
Until we're clear about the loading time issue @esbrandt mentioned, I'd stick with fonts we already included.

Rajdhani looks nice in the preview, but I don't think it works in skin context becasue it is way to condensed and hard to read, especially all uppercase labels. See screen:
ronso0__0 0 11__2018-01-14__rajdhani-test

**Comment by Be-ing** [comment]
Do all fonts need to be loaded on startup? Maybe we could move font loading to be part of the skin loading process? @daschuer do you think that would be possible?

> Rajdhani looks nice in the preview, but I don't think it works in skin context becasue it is way to condensed and hard to read, especially all uppercase labels. See screen:

Yeah, now that I see the screenshot I agree.

**Comment by ronso0** [comment]
> This looks good while the button is held down, for example with the hotcue buttons. But keeping the button looking like it is pressed down after it is released feels weird to me, especially for the play button.

I introduced this exception only for buttons that snap to some kind of active state (Play, Sync & Pfl, EQ Kill, Effect toggles), like the GUI quick toggles do and I feel it makes sense for those.

> I feel the white/gray font color used when the beatloop size and beatjump size spinboxes are active is somewhat odd.

Font settings are not finalized, yet, so yeah: I'll unify the font colors as well.

> I also feel like the way the up/down buttons next to the spinboxes don't have anything underneath them looks odd.

Do mean the missing drop shadow or the buttons escaping the button grid?
I'll add shadows when I'll vectorize the remaining buttons, but I won't change their position, though: they are next to each other because we need to keep a reasonable buttons size here, and we need the horizontal space to make 8 HotCues fit the row with default GUI configuration at minimum size (1280px).

Remaining ToDos:

Any ideas where to put the **beatgrid buttons**? They're only useful when the waveform is visible, too, and the decks are already pretty crammed. Any objections against putting them into a container next to the waveforms, like in Tango? Maybe expandable..

Where to put the **star rating**?
- squeeze it into the deck controls grid? makes the grid quite large.. [see mockup](https://user-images.githubusercontent.com/5934199/34677852-b3144498-f491-11e7-8ebf-422c6b77859e.png)
- into artist/duration row? might get tight there when playing "DJ Awesome ft. Incredible MC and his brother"
- next to Key controls in decks' top row, when vinyl controls are hidden or there's space anyway? limited access, probably invisible with default configuration on most screens

**Comment by ronso0** [comment]
I reversed the spinbox style so that the buttons are stacked vertically. Considering min-size and the need to for 8 HotCues, this is the only way to make everything fit, also with 4 decks.
The padding/overlapping issues is solved tis way, as well.

Preview:
ronso0__0 0 11__2018-01-15__new-spinbox-buttons

**Comment by nopeppermint** [comment]
@ronso0 nice, it looks like font issue are now gone (Linux Mint x64, Cinnamon 3.6.3)
mixxx_latenight_new

but also the Play/Pause button in Preview is gone..
It was like this before:
latenight_bevore


In the first screenshot there is no longer a Play/Pause Button in Preview..

that's a Button I use a lot !
I would like to have this button back

**Comment by ronso0** [comment]
whoopsie.. Preview deck shared sampler's Play button graphics, which I removed with the last commit.
fixed.

**Comment by ronso0** [comment]
@Be-ing @daschuer @ywwg 
I'd like to get this merged asap so beta users can enjoy and test it.
Then we can fix remaining font issues and design a solution for advanced skin options (8 HotCues, mixer config, 4 FX units etc.) in another PR.

before
ronso0__0 0 11__2018-01-17__before

after
ronso0__0 0 11__2018-01-17__after

**Comment by ronso0** [comment]
It seems I also committed changes to HotCue graphics by mistake.
Will revert that asap

**Comment by ywwg** [comment]
looking great!  No more notes from me

**Comment by daschuer** [comment]
Is it intended to have capitals only in the title and artist fields?

**Comment by ronso0** [comment]
Don't ask me..it was like that.
But I will change the sampler title a bit. Now both title & artist are uppersçase

**Comment by naught101** [comment]
> into artist/duration row? might get tight there when playing "DJ Awesome ft. Incredible MC and his brother"

Truncating that would be fine. The full artist/guests name is rarely relevant anyway, you just need enough info to know that it's not that other track by that other artist with the same track name..

> Any ideas where to put the beatgrid buttons? They're only useful when the waveform is visible, too, and the decks are already pretty crammed. Any objections against putting them into a container next to the waveforms, like in Tango? Maybe expandable..

Yeah, a container next to the main waveform display would make sense. (BTW, the tango ones are a bit broken: when shown, the "hide" button half covers the "adjust beats later" button).

**Comment by ronso0** [comment]
I'm not 100% fine with putting the stars next to the Artist, but I'll do it since there's no other opinion poppin up, and the other solutions require more reworking.

Last ToDos here:
- stars next to Artist
- adapt Tango beatgrid buttons

**Comment by ronso0** [comment]
> BTW, the tango ones are a bit broken: when shown, the "hide" button half covers the "adjust beats later" button

Already fixed in #1473 Give it a shot if you like!

**Comment by ronso0** [comment]
Looking good? Ready to merge?

**Comment by daschuer** [comment]
Yes.

**Comment by daschuer** [comment]
Thank you, for all the love!

**Pull request merged**
