### PR TITLE
Clean up common-controller-scripts.js

### PR DESCRIPTION
**Pull request by Holzhaus**
This was pulled out of #2520 as per @ywwg's request.

### CODE REVIEW

**Comment by ywwg** [comment]
I skimmed this and it looks like a noop, thanks! can you confirm that it passes jslint or whatever we're using these days?

**Comment by Holzhaus** [comment]
It passes my pre-commit hooks (that run `eslint`) and our Travis CI job confirms that: https://travis-ci.org/github/mixxxdj/mixxx/jobs/661653421#L1211-L1226

**Comment by Holzhaus** [comment]
By the way, the CodeFactor now uses the same config that `eslint` uses, so 393 issues have been fixed. The 2 new issues are unrelated controller scripts that redefine variables that are exported as globals from `common-controller-script.js`.

**Comment by ywwg** [comment]
lgtm

**Comment by ywwg** [comment]
(I don't know what y'all have been doing these days, merging your own PRs or letting the reviewer do it?  I'm used to the developer doing it once they get lgtm)

**Comment by Holzhaus** [comment]
From the wiki:

> [Do not merge your own pull requests.](https://www.mixxx.org/wiki/doku.php/contribution_guidelines?s[]=Do%20not%20merge%20your%20own%20pull%20requests)

So please hit the Bütten if you think this is okay ;-)

**Pull request merged**
