### PR TITLE
Shade: Audio Latency meter fix 

### PR DESCRIPTION
**Pull request by daschuer**
This fixes an issue with the GLSL Shader when the widget has only on pixel height. 
Simply by using two widgets. 

I have moved a +1 to various places in our code, but I was not able to make it work. Only if the Widget itself has a height of two pixels, it works. 

@m0dB do you have an idea how to fix it? 
Can you confirm the issue with macOS?

### CODE REVIEW

**Comment by m0dB** [comment]
I confirm that on macOS the vumeter doesn't show either when the height is 1. The problem is not in the shader code, I tried by just simply making the window red with glClearColor and returning. With 2 pixels there is no problem (note btw that the size is determined by the background pixmap). Looks like a Qt bug to me.

I could implement a workaround: when the height is 1, make it two and set the glViewport to 1 pixel height.

Alternatively, I think it would be much better of the overload formed part of the vumeter, instead of using a separate statuslight for this. That would also solve the problem.

**Comment by daschuer** [comment]
Thank you for confirming that it is nothing wrong in your code. Maybe one with a more recent QT version can confirm if it has been fixed with QT 5.15. 

A new widget that combined both indicators would be nice. However it affects the skins. Not suitable for a beta. It would be welcome for main though.  

Is the glViewport workaround easy enough or should we just merge this workaround here?

**Comment by daschuer** [comment]
The tooltip is already fixed here: https://github.com/mixxxdj/mixxx/pull/11598

I had no luck with a transparent line in the background image, because black is shining through not gray. 
I will verify it again and also add the skin warning.

**Comment by daschuer** [comment]
With the border halve transparent and 200 % it looks like this: 
grafik

**Comment by daschuer** [comment]
With QOPENGL=OFF 
grafik

**Comment by daschuer** [comment]
And finally with --disable-vumetergl
grafik

**Comment by daschuer** [comment]
The issue is that in shade the background is a png, not a brush. The dark gray color is the backround color used before the background png is rendered. I don't think there is a big demand to fix that, we just need to look for another workaround here.

**Comment by daschuer** [comment]
Using the background color instead of transparent works: 
grafik

**Comment by daschuer** [comment]
Now it looks exactly like before. 
I have the fix for https://github.com/mixxxdj/mixxx/issues/11600 in my stash as well and added it here.

**Comment by daschuer** [comment]
Superseded by https://github.com/mixxxdj/mixxx/pull/11722

**Comment by daschuer** [comment]
I can confirm that this fixes the Shade issues on Ubuntu Jammy as well. 
@m0dB should we merge this and carry on?

**Comment by m0dB** [comment]
LGTM! Merged. Thanks for taking care of this!

**Pull request merged**
