### PR TITLE
[WIP] instruct Cmake generators to create a compile_commands.json

### PR DESCRIPTION
**Pull request by Swiftb0y**
I don't have much knowledge about Cmake so I could use some tips on whether we should only do this conditionally and how to move the file to the git root folder after compilation.

### CODE REVIEW

**Comment by Holzhaus** [comment]
What's the rationale for this? Do you need it for your IDE?

You can just do:
```
mkdir cmake_build
cd cmake_build
cmake - DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
cd ..
ln -s cmake_build/compile_commands.json
```

**Comment by Swiftb0y** [comment]
> What's the rationale for this? Do you need it for your IDE?

Yes. VSCode likes to complain when it is out of date. It was also created by default from scons so I considered this a regression worth fixing.
I'm not a C++ Building / Toolchain expert so we can close this PR if you don't consider it a regression.

**Comment by Holzhaus** [comment]
Maybe some other dev can weigh in, but IMHO this PR is not necessary. Just pass the flag and make a symlink manually if you need that file ;-)

**Comment by daschuer** [comment]
I agree to that. By default cmake should be optimized for speed.
In case of Eclipse, cmake4eclipse takes care of it.
So I think it is the common practice to pass the option on the command line.
We should follow it.

**Comment by daschuer** [comment]
I think these instruction should be on the wiki. I am closing this now.

**Pull request closed without merging**
