### PR TITLE
(nsis) delete new Reloop-Beatpad and Vestax VCI-100MKII mappings on uninstall

### PR DESCRIPTION
**Pull request by sblaisot**
This PR adds new Mappings for Reloop BeatPad and Vestax VCI-100MKII in the uninstall section of the windows installer

### CODE REVIEW

**Comment by sblaisot** [comment]
@Be-ing @ywwg @daschuer @illuusio don't forget when you review new mappings to make sure that new files are added to windows uninstaller list.

**Comment by daschuer** [comment]
Thank you for the reminder and the PR! LGTM.

**Comment by Be-ing** [comment]
Could you make a note of this on the Contributing Mappings wiki page?

**Comment by sblaisot** [comment]
Already done ;) -- Sébastien BLAISOT

**Pull request merged**
