### PR TITLE
Fix compatibility issues with QT 5.2

### PR DESCRIPTION
**Pull request by daschuer**
This fixes some issues compiling Mixxx with Trusty and Qt 5.2.

### CODE REVIEW

**Comment by daschuer** [comment]
@uklotzde: Mixxx crashes when loading the soundsource Plug-Ins. Do we need to advance the API version for QT5?

**Comment by rryan** [comment]
Could you make a PR against my qt5 branch instead? This has a lot of changes in common.

**Comment by rryan** [comment]
BTW, Travis uses Qt 5.2 and builds successfully from my qt5 branch. Is this needed?

**Comment by rryan** [comment]
Extirpate!

**Comment by rryan** [comment]
> ...one more argument for dropping the plugins and integrating their code into the source tree and main build process.

Now that we're dropping <Windows 7 support, there is no need for the MediaFoundation plugin to be separate from Mixxx.

**Comment by daschuer** [comment]
You mean: now that we are dropping "Win XP support" right?

**Pull request closed without merging**
