### PR TITLE
rename Hercules DJ Control MP3 e2 mapping to indicate MP3 LE and Glow support

### PR DESCRIPTION
**Pull request by Be-ing**
Thanks again to appendix on the forum: http://mixxx.org/forums/viewtopic.php?p=30384#p30384

Should the mapping files be renamed?
Does anyone know if the Hercules DJ Console Mk4 works with this mapping too? It also seems to have identical controls and is in the list of supported USB Bulk devices.

### CODE REVIEW

**Comment by sblaisot** [comment]
This controller is also a midi controller on windows and mac with hercules driver.
I think the same change should be made on the midi mapping if they share the same mapping.

I'll take a look at that tonight.

**Comment by daschuer** [comment]
@sblaisot: Do you have any results?

**Comment by sblaisot** [comment]
Yes.

MP3 e2, MP3 LE and glow are the same device (sharing the same mapping).
they use the same driver, so they should have the same MIDI messages.
Please also update https://github.com/mixxxdj/mixxx/blob/master/res/controllers/Hercules%20DJ%20Control%20MP3%20e2.midi.xml#L4

**Comment by sblaisot** [comment]
we already have another dedicated mapping for the Hercules DJ Console Mk4

**Comment by sblaisot** [comment]
LGTM

**Comment by rryan** [comment]
thanks @Be-ing and @sblaisot

**Pull request merged**
