### PR TITLE
sccache: Fix Windows CI build

### PR DESCRIPTION
**Pull request by uklotzde**
Deleting the branch broke the build.

### CODE REVIEW

**Comment by Be-ing** [comment]
Manual rebuild of the job failed???
```
 LINK: command "C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\mixxx-test.rsp /out:mixxx-test.exe /implib:mixxx-test.lib /pdb:mixxx-test.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL:NO /subsystem:console /OPT:REF /nodefaultlib:LIBCMT.lib /nodefaultlib:LIBCMTd.lib /entry:mainCRTStartup /manifest /MANIFEST /MANIFESTFILE:mixxx-test.exe.manifest" failed (exit code 0) with the following output:

LINK : fatal error LNK1000: Internal error during CImplib::EmitImportThunk
```
I have no idea.

**Comment by uklotzde** [comment]
@Be-ing The Windows builds still seem to be flaky. Unrelated to this PR.

**Comment by Be-ing** [comment]
What do you mean? I have not seen it fail on any other PRs.

**Comment by uklotzde** [comment]
> What do you mean? I have not seen it fail on any other PRs.

Nevertheless the failure is unrelated to this PR. Could also be a GitHub issue.

Please merge this PR, because the Windows build is currently broken due to the missing sccache feature branch in your repo.

**Comment by uklotzde** [comment]
https://github.com/uklotzde/mixxx/runs/2078077977?check_suite_focus=true

But now it seems to be fixed again after subsequent builds?! Don't know what happened.

**Comment by uklotzde** [comment]
```

Run cargo install --git https://github.com/Be-ing/sccache.git --branch fix_msvc_fp
    Updating git repository `https://github.com/Be-ing/sccache.git`
error: failed to find branch `fix_msvc_fp`

Caused by:
  cannot locate remote-tracking branch 'origin/fix_msvc_fp'; class=Reference (4); code=NotFound (-3)
```

**Comment by uklotzde** [comment]
Next build failure:

https://github.com/mixxxdj/mixxx/pull/3666/checks?check_run_id=2086611044

**Comment by Be-ing** [comment]
The cache key needs to be updated.

**Pull request merged**
