### PR TITLE
Trackmodel: Make some functions const and remove unused implementations

### PR DESCRIPTION
**Pull request by daschuer**
This was a drive by change during debugging.

### CODE REVIEW

**Comment by Holzhaus** [comment]
CI fails.

**Comment by daschuer** [comment]
Yes, unrelated because of:
```
-- verifying file...
       file='/home/runner/work/mixxx/mixxx/build/download/libKeyFinder/v2.2.3.zip'
-- SHA256 hash of
    /home/runner/work/mixxx/mixxx/build/download/libKeyFinder/v2.2.3.zip
  does not match expected value
    expected: '56887e7b51834223d4264f4ea9acf16f0b6a0c706c218478afbaf89ad1f9c6ea'
      actual: 'ad43ca006e3bbed0810ff62e170d04522a64f8606c2166bfa5a9b9158b7ebc11'
-- Hash mismatch, removing...
CMake Error at libKeyFinder-stamp/download-libKeyFinder.cmake:159 (message):
  Each download failed!
```

**Comment by uklotzde** [comment]
> CI fails.

@Holzhaus @Be-ing Did anyone mess up the released libKeyFinder v2.2.3 artifacts???

```
-- SHA256 hash of
    /home/runner/work/mixxx/mixxx/build/download/libKeyFinder/v2.2.3.zip
  does not match expected value
    expected: '56887e7b51834223d4264f4ea9acf16f0b6a0c706c218478afbaf89ad1f9c6ea'
      actual: 'ad43ca006e3bbed0810ff62e170d04522a64f8606c2166bfa5a9b9158b7ebc11'
-- Hash mismatch, removing...
CMake Error at libKeyFinder-stamp/download-libKeyFinder.cmake:159 (message):
  Each download failed!
```

**Comment by Holzhaus** [comment]
https://github.com/mixxxdj/mixxx/pull/3527#issuecomment-754599150

**Comment by uklotzde** [comment]
Tested locally. LGTM

**Pull request merged**
