### PR TITLE
Library: fix track relocation query

### PR DESCRIPTION
**Pull request by ronso0**
After all it was missing `:` that made the entire relocation fail.
Seems this was broken for years.

I'm surprised there's no error raised for no-op `bindvalue()`.

mentioning **Relink** so I find this PR later on

### CODE REVIEW

**Comment by ronso0** [comment]
@mixxxdj/developers This is quick fix and I'd appreciate if someone could take a look and press merge, for those millions of Mixxx users who will migrate to the new PCs they'll get for christmas ; )

**Review by fwcd — APPROVED** [review]
Looks reasonable to me, should this target 2.4 (base branch is `main` currently)?

**Comment by ronso0** [comment]
jup, correct, switched to 2.4

**Comment by ronso0** [comment]
Oh, oh... a bug slipped in here.
It unconditionally sets `directory` to the new **root** dir for all relocated tracks.

This will probably not be noticed. Afaict `directory` is not used, eg. "Search related.." -> Directory uses the `location` of the track, and a later relocate action will also work.
But there may be issues after purging tracks where the track file has not been deleted, see https://github.com/mixxxdj/mixxx/blob/43d6356a2fc4aa00d0399d1f12d0c3d0c04b66d4/src/library/dao/trackdao.cpp#L1116

And the `dir:` filter will not yield all results -- which partially broke #14683 for me :|

Fix is #16578

**Pull request merged**
