### PR TITLE
A&H Xone K2/K1 mappings for decks + effects

### PR DESCRIPTION
**Pull request by Be-ing**
This adds a 4 effect unit mapping for the Allen & Heath Xone K2/K1 using Components. The dry/wet knobs are mapped to the faders. The effectFocusButton is mapped to pressing the top encoders. The bottom buttons control the effect unit routing switches.

TODO:
  - [x] Rewrite the decks mapping using Components without using the firmware's Latching Layers ~~hack around other softwares' limited mapping systems~~ feature. The Xone K1 does not have Latching Layers, so this is required for compatibility with it.
  - [x] Make a 2 decks + 2 effect unit mapping for using one K2/K1. Rewriting the decks mapping is also required for this because the Latching Layers should not affect the effect assignment switches.
  - [x] Take advantage of the multicolor LEDs to show different states for effect units
  - [x] Redesign decks mapping
  - [ ] Mapping for one effect unit with all parameters on whole controller
  - [ ] Map master and headphone effect unit routing buttons

### CODE REVIEW

**Comment by Be-ing** [comment]
@ferranpujolcamins, @poelzi, @foss-, @ywwg, ready for testing! This mapping requires changing the firmware's settings compared to the old mapping. Refer to the [wiki](https://mixxx.org/wiki/doku.php/allen_heath_xone_k2) for details.

Currently the bottom left layer button does nothing for effect units. I plan on using it with the 4 effect unit layout to make another mode for manipulating all the parameters of each effect in one unit (and make that one unit selectable somehow). That doesn't need need to be done immediately or in this PR though.

**Comment by ywwg** [comment]
thanks for doing this! I'll try to give it a shot soon

**Comment by Be-ing** [comment]
I feel like I'm flying a spaceship with 2 K2s controlling 4 decks + 4 effect units... and I've barely gotten started learning to use it. :D

**Comment by ferranpujolcamins** [comment]
LGTM

many thanks for this mapping! It's really nice to have so many layout options

**Comment by Be-ing** [comment]
I'd like to get feedback from at least one more tester before merging this.

**Comment by ywwg** [comment]
I tried this out with a few modes and it works nicely!  It took me a moment to find the play/pause button, I wasn't expecting it to be up there, but I think it works all right.  As long as we update the wiki with the mappings it should be good.  thanks for doing this

**Comment by Be-ing** [comment]
Thanks for testing. I moved the play button up there so it is always immediately available (except with supershift mode which is meant for relatively infrequently used functions). It bugged me with the old mapping that I sometimes had to switch layers on bottom to access the play button.

**Pull request merged**
