### PR TITLE
fix typo: substract -> subtract

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by rryan** [comment]
thanks!

**Comment by daschuer** [comment]
Hi Nikolas, Thanks for helping here. 

we need your permission to distribute your patch with Mixxx. Please sign: 

https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ

and comment here when done.

**Comment by nikolas** [comment]
done

**Comment by daschuer** [comment]
I like to put your name into Mixxx's about box. How do you like to be listed there? Usually we take the real name.

**Pull request merged**
