### PR TITLE
Enable parallel builds for Travis.

### PR DESCRIPTION
**Pull request by rryan**

### CODE REVIEW

**Comment by rryan** [comment]
The Travis OSX build finished in 33 minutes with -j4 (timeout is 50 minutes). Could be the servers were less loaded when the checks ran though.

**Comment by rryan** [comment]
According to
https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments
the build VM has 2-ish cores, so this could explain why it helps.

**Comment by rryan** [comment]
Another run, this time using -j4 for Linux too. 27m/31m for Linux/Mac. 
https://travis-ci.org/mixxxdj/mixxx/builds/324006294

Compare to:
34/48: https://travis-ci.org/mixxxdj/mixxx/builds/323814017
33/48: https://travis-ci.org/mixxxdj/mixxx/builds/323988304
31/47: https://travis-ci.org/mixxxdj/mixxx/builds/323982741
34/48: https://travis-ci.org/mixxxdj/mixxx/builds/323974339

**Comment by Be-ing** [comment]
Cool, we can deprioritize speeding up the library tests then

**Comment by Be-ing** [comment]
Ready for merge?

**Comment by sblaisot** [comment]
Nice. LGTM.

**Comment by rryan** [comment]
Well shoot, I guess it could just have been lucky:
https://travis-ci.org/mixxxdj/mixxx/builds/324148236

I wonder if we need `brew update`. Looks like that takes 5 minutes.

**Comment by sblaisot** [comment]
they say we don't need it unless we need a fixed version: https://docs.travis-ci.com/user/reference/osx/#Homebrew

**Comment by Pegasus-RPG** [comment]
If it's about 2 cores, wouldn't -j3 be be slightly faster?

**Pull request merged**
