### PR TITLE
Update translations for 2.1 from Transifex.

### PR DESCRIPTION
**Pull request by rryan**
Manually deleted translations for 'en', since that's our source language.

@esbrandt any idea why there is an 'en' translation now?

### CODE REVIEW

**Comment by esbrandt** [comment]
[Last time](https://github.com/mixxxdj/mixxx/commit/6387dba9d458c3e81a17e8d18abced87a66eb385) i pulled the translations, i omitted all translations you just added. They have a below 1% completion, some even 0%. The ``de-DE`` translation is a duplicate of ``de``.

Are you sure you did pull from https://www.transifex.com/mixxx-dj-software/mixxxdj/github-release-210/ ?

If i do , there are new translations for ``fr`` and ``mixxx_zh_CN``, which is also what th e [Transifex timeline](https://www.transifex.com/mixxx-dj-software/mixxxdj/settings/timeline/) says.

**Comment by rryan** [comment]
```
$ tx pull -a                                    

tx INFO: New translations found for the following languages:en, it_IT, fr_BE, az, tl_PH, de_DE, hi_IN
tx INFO: Pulling translations for resource mixxxdj.github-release-210 (source: res/translations/mixxx.ts)
tx INFO: Skipping 'da' translation (file: res/translations/mixxx_da.ts).
tx INFO: Skipping 'bg' translation (file: res/translations/mixxx_bg.ts).
tx INFO: Skipping 'ia' translation (file: res/translations/mixxx_ia.ts).
tx INFO: Skipping 'pl' translation (file: res/translations/mixxx_pl.ts).
tx INFO: Skipping 'zh_CN' translation (file: res/translations/mixxx_zh_CN.ts).
tx INFO: Skipping 'eu' translation (file: res/translations/mixxx_eu.ts).
tx INFO: Skipping 'sq_AL' translation (file: res/translations/mixxx_sq-AL.ts).
tx INFO: Skipping 'ast' translation (file: res/translations/mixxx_ast.ts).
tx INFO: Skipping 'si' translation (file: res/translations/mixxx_si.ts).
tx INFO: Skipping 'ml' translation (file: res/translations/mixxx_ml.ts).
tx INFO: Skipping 'tr' translation (file: res/translations/mixxx_tr.ts).
tx INFO: Skipping 'de' translation (file: res/translations/mixxx_de.ts).
tx INFO: Skipping 'sn' translation (file: res/translations/mixxx_sn.ts).
tx INFO: Skipping 'mn' translation (file: res/translations/mixxx_mn.ts).
tx INFO: Skipping 'pt_BR' translation (file: res/translations/mixxx_pt_BR.ts).
tx INFO: Skipping 'fr' translation (file: res/translations/mixxx_fr.ts).
tx INFO: Skipping 'ms' translation (file: res/translations/mixxx_ms.ts).
tx INFO: Skipping 'hy' translation (file: res/translations/mixxx_hy.ts).
tx INFO: Skipping 'ro' translation (file: res/translations/mixxx_ro.ts).
tx INFO: Skipping 'uz' translation (file: res/translations/mixxx_uz.ts).
tx INFO: Skipping 'pt_PT' translation (file: res/translations/mixxx_pt-PT.ts).
tx INFO: Skipping 'nl' translation (file: res/translations/mixxx_nl.ts).
tx INFO: Skipping 'pt' translation (file: res/translations/mixxx_pt.ts).
tx INFO: Skipping 'ca_ES' translation (file: res/translations/mixxx_ca-ES.ts).
tx INFO: Skipping 'lv' translation (file: res/translations/mixxx_lv.ts).
tx INFO: Skipping 'id' translation (file: res/translations/mixxx_id.ts).
tx INFO: Skipping 'ko' translation (file: res/translations/mixxx_ko.ts).
tx INFO: Skipping 'ca' translation (file: res/translations/mixxx_ca.ts).
tx INFO: Skipping 'sl' translation (file: res/translations/mixxx_sl.ts).
tx INFO: Skipping 'te' translation (file: res/translations/mixxx_te.ts).
tx INFO: Skipping 'cs' translation (file: res/translations/mixxx_cs.ts).
tx INFO: Skipping 'hu' translation (file: res/translations/mixxx_hu.ts).
tx INFO: Skipping 'oc' translation (file: res/translations/mixxx_oc.ts).
tx INFO: Skipping 'hr' translation (file: res/translations/mixxx_hr.ts).
tx INFO: Skipping 'el' translation (file: res/translations/mixxx_el.ts).
tx INFO: Skipping 'he' translation (file: res/translations/mixxx_he.ts).
tx INFO: Skipping 'gl' translation (file: res/translations/mixxx_gl.ts).
tx INFO: Skipping 'it' translation (file: res/translations/mixxx_it.ts).
tx INFO: Skipping 'ar' translation (file: res/translations/mixxx_ar.ts).
tx INFO: Skipping 'fi' translation (file: res/translations/mixxx_fi.ts).
tx INFO: Skipping 'ru' translation (file: res/translations/mixxx_ru.ts).
tx INFO: Skipping 'sk' translation (file: res/translations/mixxx_sk.ts).
tx INFO: Skipping 'ta' translation (file: res/translations/mixxx_ta.ts).
tx INFO: Skipping 'en_GB' translation (file: res/translations/mixxx_en_GB.ts).
tx INFO: Skipping 'bs' translation (file: res/translations/mixxx_bs.ts).
tx INFO: Skipping 'ceb' translation (file: res/translations/mixxx_ceb.ts).
tx INFO: Skipping 'ja' translation (file: res/translations/mixxx_ja.ts).
tx INFO: Skipping 'mk' translation (file: res/translations/mixxx_mk.ts).
tx INFO: Skipping 'nn' translation (file: res/translations/mixxx_nn.ts).
tx INFO: Skipping 'es' translation (file: res/translations/mixxx_es.ts).
tx INFO: Skipping 'my' translation (file: res/translations/mixxx_my.ts).
tx INFO: Skipping 'ky' translation (file: res/translations/mixxx_ky.ts).
tx INFO: Skipping 'ga' translation (file: res/translations/mixxx_ga.ts).
tx INFO: Skipping 'sv' translation (file: res/translations/mixxx_sv.ts).
tx INFO: Skipping 'uk' translation (file: res/translations/mixxx_uk.ts).
tx INFO: Skipping 'is' translation (file: res/translations/mixxx_is.ts).
tx INFO: Skipping 'fa' translation (file: res/translations/mixxx_fa.ts).
tx INFO: Skipping 'mr' translation (file: res/translations/mixxx_mr.ts).
tx INFO: Skipping 'eo' translation (file: res/translations/mixxx_eo.ts).
tx INFO: Skipping 'vi' translation (file: res/translations/mixxx_vi.ts).
tx INFO: Skipping 'es_ES' translation (file: res/translations/mixxx_es-ES.ts).
tx INFO: Skipping 'sr' translation (file: res/translations/mixxx_sr.ts).
tx INFO: Skipping 'et' translation (file: res/translations/mixxx_et.ts).
tx INFO: Skipping 'br' translation (file: res/translations/mixxx_br.ts).
tx INFO: Skipping 'lt' translation (file: res/translations/mixxx_lt.ts).
tx INFO: Skipping 'zh_TW' translation (file: res/translations/mixxx_zh_TW.ts).
tx INFO: Skipping 'nb' translation (file: res/translations/mixxx_nb.ts).
tx INFO: Skipping 'lb' translation (file: res/translations/mixxx_lb.ts).
tx INFO: Pulling new translations for resource mixxxdj.github-release-210 (source: res/translations/mixxx.ts)
tx WARNING:  -> en: res/translations/mixxx_en.ts
tx WARNING:  -> it_IT: res/translations/mixxx_it-IT.ts
tx WARNING:  -> fr_BE: res/translations/mixxx_fr-BE.ts
tx WARNING:  -> az: res/translations/mixxx_az.ts
tx WARNING:  -> tl_PH: res/translations/mixxx_tl-PH.ts
tx WARNING:  -> de_DE: res/translations/mixxx_de-DE.ts
tx WARNING:  -> hi_IN: res/translations/mixxx_hi-IN.ts
tx INFO: Pulling translations for resource mixxxdj-windows-installer.mixxxpot (source: build/wix/Localization/po/mixxx.pot)
tx INFO: Skipping 'sk_SK' translation (file: build/wix/Localization/po/sk-SK.po).
tx INFO: Skipping 'hu_HU' translation (file: build/wix/Localization/po/hu-HU.po).
tx INFO: Skipping 'tr_TR' translation (file: build/wix/Localization/po/tr-TR.po).
tx INFO: Skipping 'ru_RU' translation (file: build/wix/Localization/po/ru-RU.po).
tx INFO: Skipping 'nl_NL' translation (file: build/wix/Localization/po/nl-NL.po).
tx INFO: Skipping 'ro_RO' translation (file: build/wix/Localization/po/ro-RO.po).
tx INFO: Skipping 'pt_PT' translation (file: build/wix/Localization/po/pt-PT.po).
tx INFO: Skipping 'da_DK' translation (file: build/wix/Localization/po/da-DK.po).
tx INFO: Skipping 'fr_FR' translation (file: build/wix/Localization/po/fr-FR.po).
tx INFO: Skipping 'zh_CN' translation (file: build/wix/Localization/po/zh-CN.po).
tx INFO: Skipping 'cs_CZ' translation (file: build/wix/Localization/po/cs-CZ.po).
tx INFO: Skipping 'de_DE' translation (file: build/wix/Localization/po/de-DE.po).
tx INFO: Skipping 'ca_ES' translation (file: build/wix/Localization/po/ca-ES.po).
tx INFO: Skipping 'es_ES' translation (file: build/wix/Localization/po/es-ES.po).
tx INFO: Skipping 'pl_PL' translation (file: build/wix/Localization/po/pl-PL.po).
tx INFO: Skipping 'it_IT' translation (file: build/wix/Localization/po/it-IT.po).
tx INFO: Skipping 'el_GR' translation (file: build/wix/Localization/po/el-GR.po).
tx INFO: Skipping 'zh_TW' translation (file: build/wix/Localization/po/zh-TW.po).
tx INFO: Skipping 'sv_SE' translation (file: build/wix/Localization/po/sv-SE.po).
tx INFO: Skipping 'et_EE' translation (file: build/wix/Localization/po/et-EE.po).
tx INFO: Skipping 'pt_BR' translation (file: build/wix/Localization/po/pt-BR.po).
tx INFO: Done.
```

**Comment by rryan** [comment]
Ah ok, let's not add them then.

**Comment by esbrandt** [comment]
> any idea why there is an 'en' translation now?

https://github.com/mixxxdj/mixxx/blob/8e006f1e9588aa20cb8241c2ae14362ae348ecf5/.tx/config#L8
Possible reason because the source langue on Transifex is ``en``.
Transifex doc says  ``The source language cannot be changed once you create your project``

**Comment by esbrandt** [comment]
> Are you sure you did pull from https://www.transifex.com/mixxx-dj-software/mixxxdj/github-release-210/ ?
> 
> If i do , there are new translations for fr and zh_CN, which is also what the Transifex timeline says.

My bad, the local branch was not up-to-date.

**Comment by esbrandt** [comment]
There is nothing to do - for the application and windows installer.
All up to date, since we decided to omit the near 0%-percent complete translation.

The PR can be closed.

**Comment by Be-ing** [comment]
Oh, okay. Thank you for clarifying.

**Comment by rryan** [comment]
I'm confused, if I run `tx pull -a -f` then I get new translations for some languages. Under what circumstances does transifex "skip" languages when you `tx pull -a` ?

**Pull request closed without merging**
