### PR TITLE
Hotfix: Logger must not use any static data for initialization

### PR DESCRIPTION
**Pull request by uklotzde**
Well, we should have noticed this earlier ;)

### CODE REVIEW

**Review by JoeMerten — APPROVED** [review]
Looks ok

**Comment by daschuer** [comment]
Sorry, I do not understand the issue here. Was there a real one? Normally such static instances are implemented by the compiler like a singleton class and initialized on the first usage. Am I wrong here? Please help me out.

Anyway, no need to hold of the merge.

**Comment by JoeMerten** [comment]
As Uwe wrote: "The order of static initializations across compilation units is undefined!!"

This might be a real issue in case of the following szenario:
- We have a compilation unit `a.cpp` which contains a function `a()` which is executed during static initialization (before entering `main()`).
- The function `a()` could call `Logger::Logger()`, before static initialization of compilation unit `logger.cpp` has been invoked.
- For my understanding, both `kLogPreambleSuffix` and `kLogPreambleSuffixLen` instances would be uninitialized in this case.

I don't know of a implicit singleton pattern for those instances.

Well, in C++11, there is thread safetiness for static variables (
see e.g. [here](https://stackoverflow.com/questions/8102125/is-local-static-variable-initialization-thread-safe-in-c11)). But this is different case and however, this C++11 feature is banned in your [coding guidelines / magic statics](https://mixxx.org/wiki/doku.php/coding_guidelines) because of buggee windows compiler.

**Comment by uklotzde** [comment]
@daschuer The preamble string " -" (declared as a static variable) was empty/missing when declaring a static const Logger instance in another compilation unit.

My explanation: The constructor of the Logger is invoked when the corresponding static instance is created, for example in soundsourceproxy.cpp. The constructor implementation uses the static const preamble string from logger.cpp which is not guaranteed to be initialized at this time.

**Comment by uklotzde** [comment]
@JoeMerten Thank you for your explanation 👍

**Comment by daschuer** [comment]
Ah, thank you I have got it.

**Pull request merged**
