### PR TITLE
Track: Fix debug assertion for missing/invalid bpm

### PR DESCRIPTION
**Pull request by uklotzde**
Occurred after applying changes in DlgTrackInfo.

### CODE REVIEW

**Review by ywwg — CHANGES_REQUESTED** [review]
Any way to add a test for this? otherwise lgtm

**Comment by uklotzde** [comment]
You cannot test a debug assertion.

The invocation of Bpm::value() was wrong. Not it is gone. Nothing to test.

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you. As [discussed on Zulip](https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/code.20review.20.2F.20decision.20making.20process/near/244459406) I won't hit merge until @ywwg had the chance to re-review (as he used "Request Changes" instead of "Comment").

**Comment by uklotzde** [comment]
@ywwg Ping. We already discussed the liabilities that come with *Request changes*.

**Comment by Holzhaus** [comment]
@ywwg Ping.

**Comment by Holzhaus** [comment]
@ywwg ping again. It would nice to get this fix into `main` soon.

**Comment by uklotzde** [comment]
There is no point in discussing review practices and contribution guidelines if even the basic rules of communication are not obeyed by ourselves. As a first-time contributor I would have closed the PR left now.

**Review by ywwg — APPROVED** [review]

**Comment by ywwg** [comment]
> @ywwg Ping.

I have no idea why github didn't tell me about these pings :(.  I am constantly trying to fix my notifications so I only get told about things that are important, but I am buried with notifications about every single PR that happens.  Sorry for the delay.

**Comment by Swiftb0y** [comment]
image
fyi you can restrict for what activities you get notifications for and you can also filter by the reason you got notified for.
image
Also please double check some of the recent PRs, there are a bunch that require your attention and you seem to have missed them so far.

**Pull request merged**
