### PR TITLE
Pitchbend race condition fix 

### PR DESCRIPTION
**Pull request by daschuer**
This fixes a race condition with the pitchbend controls found when working on:
https://bugs.launchpad.net/mixxx/+bug/1770745

It happens only in the unlikely case when you use Controller and GUI at the same time. 
However it should be fixed. 
It is on top of https://github.com/mixxxdj/mixxx/pull/1906 which contains the real 2.1.6 scheduled bug.
Which should be merged first.

### CODE REVIEW

**Comment by daschuer** [comment]
I don't mind a target branch. It is on top of 2.1 but can also go to 2.2 or master.

**Comment by WaylonR** [comment]
what is this for? what does it prevent? does hitting this cause a crash? So, its a good idea to merge it into my personal branch, for performance djing?

**Comment by daschuer** [comment]
Without this patch the pitbend value can go insane if you use it with a controller and a GUI button at the same time.

However https://github.com/mixxxdj/mixxx/pull/1906 should be merged first. 

I would be very happy if you could test and review that PR first.

**Comment by uklotzde** [comment]
@daschuer Please merge mixxxdj:2.1 to hide the changes from #1906.

**Comment by uklotzde** [comment]
Less redundant state, nice :+1: I will test this for a while, but otherwise LGTM.

**Comment by uklotzde** [comment]
Let's give it a try :+1: Time for public testing.

**Pull request merged**
