### PR TITLE
fix: `clazy-strict-iterators` warning

### PR DESCRIPTION
**Pull request by Swiftb0y**
~~Lets see if CI approves of this Qt 6.1 code. If not I'll implement the less pretty alternative.~~ Doesn't work, less pretty alternative it is.

### CODE REVIEW

**Review by Holzhaus — APPROVED** [review]
LGTM, thanks. Waiting for CI.

**Comment by daschuer** [comment]
I was already working on a fix here: https://github.com/mixxxdj/mixxx/pull/13856

**Comment by Holzhaus** [comment]
@daschuer it's the other way around, this PR is 10 minutes older.

**Comment by daschuer** [comment]
Yes, right. I did a CI run in my private repro first. After this was successful I have issued the PR afterthis one. 

I don't mind which one is merged. Current state: this is failing, https://github.com/mixxxdj/mixxx/pull/13856 is green.

**Pull request closed without merging**
