### PR TITLE
Playback to pause brake effect

### PR DESCRIPTION
**Pull request by goddisignz**
Introduces a brake effect when playback is paused.

- When it is activated it linearly decreases the playback speed until it becomes zero.
- The effect time until full stop can be configured in the deck preferences
- An effect time of zero disables the effect.
- It only reacts on button presses (UI-press, keyboard, or controller). Direct changes to the play state behave like before.
- During brake, pressing the button again immediately resumes to playback, quantized if enabled. This does not work for the UI-press because of the control objects state modification mechanism. Here, another click results in an immediate stop.
- For UI-press, only Deere is supported up to now. Other skins will have to introduce a three-state button accordingly.

### CODE REVIEW

**Comment by goddisignz** [comment]
Hm, seems like I am not completely done here.

**Comment by georgitsenov** [comment]
Hay @goddisignz I am trying to find a way to enable vinyl break, like it can be configured in Serato in order to perform this:
https://youtu.be/3dl2Lpnqy0w

I checked on various repositories, mixxx forums and launchpad and this pull request is the closest thing, that I found.
Do you have any info on how this can be enabled, or what is the progress % on your implementation?

Best Regards!

**Comment by ywwg** [comment]
you can leave this PR open and convert it to Draft mode, then when it's ready you can request reviews

**Comment by ronso0** [comment]
unfortunately this can't be reopened because it targets now nonexistant `master`.
@goddisignz In case you intend to continue working on this: leaving a PR open also allows repo members to pick up the PR and push chnages as well as merging the target branch every now and then in order to avoid too many conflicts stack up over time.

**Pull request closed without merging**
