### PR TITLE
2.4.2

### PR DESCRIPTION
**Pull request by daschuer**
This builds the release candidate for 2.4.2. 
This can be merged  for a release once https://github.com/mixxxdj/website/pull/368 is mature.

### CODE REVIEW

**Comment by Swiftb0y** [comment]
fyi, I have been running `2.4.1-100-g91e980dc5b` for a couple days on fedora now and I couldn't spot any regressions. I think that suffices as a smoke test on F41.

**Comment by daschuer** [comment]
The Qt 6.2 CI is fixed here: 
https://github.com/mixxxdj/mixxx/pull/13904

**Comment by daschuer** [comment]
All green now. 
Merge, Smoke test and Release.

**Comment by daschuer** [comment]
We still need a macOS smoke test. Who can help? 
This one can already be merged. Who wants to take care?

**Comment by fwcd** [comment]
Seems to work fine for me on macOS, only thing I've noticed is that the build isn't notarised, but IIRC we never did that for PR builds anyways, right?

**Comment by Swiftb0y** [comment]
@daschuer can you fix the last minute PRs #13923 and #13917 to the changelog? Then LGTM.

**Comment by daschuer** [comment]
Thank you for review and testing.

**Pull request merged**
