### PR TITLE
Update screenshot URL

### PR DESCRIPTION
**Pull request by City-busz**
The previous one is no longer available.

### CODE REVIEW

**Comment by ronso0** [comment]
Thank you. I didn't look at the change in detail, what jumps out though is Deere: since 2.3 LateNight (PaleMoon theme) is the default skin.

**Comment by City-busz** [comment]
I updated my PR, so now it lists all screenshots listed on https://mixxx.org/screenshots/ page.

**Comment by ronso0** [comment]
Thanks!
Since this is your first contribution we need you to sign the [contributor agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and thereby allow Mixxx to include your changes.

**Comment by ronso0** [comment]
oh, just noticed this should go to `main` but it's needed in 2.3 already.
Please target 2.3 and rebase your branch accordingly.

**Comment by City-busz** [comment]
> Since this is your first contribution we need you to sign the [contributor agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and thereby allow Mixxx to include your changes.

I filled the agreement.

> oh, just noticed this should go to `main` but it's needed in 2.3 already.
> Please target 2.3 and rebase your branch accordingly.

I opened another PR for the branch 2.3: https://github.com/mixxxdj/mixxx/pull/3833

**Comment by ronso0** [comment]
that's not necessary, rebase would have been sufficient since 2.3 is merged into main regularly anyway.
closing this as both PRs with identical changes would create a merge conflict.

**Pull request closed without merging**
