### PR TITLE
Mouse cursor wrapping

### PR DESCRIPTION
**Pull request by ninomp**
This PR implements wrapping of mouse cursor while using mouse to pitch-bend or scratch. It also includes some refactoring.

### CODE REVIEW

**Comment by Be-ing** [comment]
Have you tested this on a touchscreen?

**Comment by ninomp** [comment]
No. Unfortunately, I don't have a touchscreen device to test on.

**Comment by daschuer** [comment]
I have just tested this on my touch laptop. 

Scratching with touch does, does not work nice, because the track stops one you move out of the waveform widget. This was an issue before and is not changed by this PR. 

During test, I have managed that the cursor is always a closed hand. This could be fixed by restarting Mixxx. 

The jumping mouse cursor feels unnatural to me. Maybe I just need to get used to it though ... 
The reappearing on the opposite is somehow to eye-catching to me, and I loose the scratch start point. 

Is it possible to hide the mouse cursor instead when it moves out of the widget?

**Comment by daschuer** [comment]
I have never used then Mouse bending. 
Testing it now, it feels unnatural using my laptop's touch pad. 

It would be nice to have a mode that models a temporary speed change using the platter axis, or a speed up touch on the vinyl.  

Something like this: 
* Hold the right button: Enable Bending, as if you put your finger close to the vinyl. 
* Move the mouse right: Speed up the vinyl 
* Move the mouse left: Slow down the vinyl. 
* If the mouse stops, go back to normal.  
 
What do you think.

**Comment by ninomp** [comment]
Yes, I can imagine that mouse cursor wrapping works awfully on touchscreen devices. I will add a preference option for enabling mouse cursor wrapping that is off by default.

About hiding the mouse cursor, it can be done, but I see no reason to do it. VirtualDJ also wraps mouse cursor and does not hide mouse cursor. However, if you insist, I can implement it.

About your idea for a new mode, I love it and I'm going to implement it (in this PR). However, I will put it on middle button. Later we can exchange middle and right button behavior. Furthermore, maybe we should add preference option that allows users to choose which behavior they want on which mouse button. What do you think?

**Comment by Be-ing** [comment]
Adding yet another preference option is often an indicator of poor design. Is there a way to distinguish between mouse and touchscreen events with Qt?

**Comment by daschuer** [comment]
Yes. Qt passes the touch events to the widget. If it can't make use of it, it is converted into a mouse event and passed again. We already use some touch events here: 
https://github.com/mixxxdj/mixxx/blob/14e10b29b57ae46ff8bb9ac0b815f8a4cb475848/src/widget/wwidget.cpp#L50

**Comment by daschuer** [comment]
> About hiding the mouse cursor, it can be done, but I see no reason to do it. VirtualDJ also wraps mouse cursor and does not hide mouse cursor. However, if you insist, I can implement it.

In the past years we had not have complains, that the graped hand can be outside the waveforms. 
I think the Mixxx user get used to it, and It has the advantage that the scratch start position is always under the hand when you go back to the waveform widget. 

The original issue that you are solving here, is that you cannot scratch off the screen. Can't we just solve this, and postpone the mouse wrapping issue? 

This means: 
* wrap the mouse at the sceen borders. 
* hide the mouse once it is wrapped
* Count wrappings, and show th mouse again if it is unwrapped.

> About your idea for a new mode, I love it and I'm going to implement it (in this PR).

Thank you!

**Comment by ninomp** [comment]
> If you think you need a new preference option, you're probably avoiding making a decisive design decision.

OK I won't add new preference options.

>This means:
>- wrap the mouse at the sceen borders.
>- hide the mouse once it is wrapped
>- Count wrappings, and show th mouse again if it is unwrapped.

Hmm Well, this will also work. I will do it like that.

**Comment by Be-ing** [comment]
I have a touchscreen laptop now, so I"ll look into this soon.

**Comment by ninomp** [comment]
OK Thank you very much.

**Comment by Be-ing** [comment]
I tested this with Qt5 and it does not work well. Moving the cursor to the right edge of the screen makes the track seek a long distance and moving the cursor to the left edge does nothing. This is the same with both my mouse and touchscreen.

**Comment by ninomp** [comment]
I am not planning to work on this in near future, so I'm closing this now.

**Pull request closed without merging**
