### PR TITLE
Velocity sensitive ComponentsJS SamplerButtons

### PR DESCRIPTION
**Pull request by Swiftb0y**
You can now add `velocity: true,` while creating a SamplerButton. This will set the channel volume of the sampler accordingly when launched.

TODO:
* [ ] Testing
* [x] Documenting

### CODE REVIEW

**Comment by daschuer** [comment]
this looks like an interesting feature.
I think velocity: true is not self explaining. 
how about 
volumeByVelocity: true
or similar.

**Comment by Swiftb0y** [comment]
how about `velocitySensitive`?

**Comment by daschuer** [comment]
It is missing that the "volume" is effected

**Comment by daschuer** [comment]
LGTM @Be-ing anything else to consider before merge?

**Comment by Be-ing** [comment]
LGTM

**Pull request merged**
