### PR TITLE
controllers: Replace old-style Qt connect() calls

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by uklotzde** [comment]
Mismatching char types on Windows in Hss1394Controller. The signal/slot signatures are incompatible.

**Comment by Holzhaus** [comment]
Ideas why the overload doesn't work?

**Comment by uklotzde** [comment]
Let's wait for the CI builds to finish before finally updating the clazy options as suggested in #3319.

**Comment by Holzhaus** [comment]
All green

**Comment by uklotzde** [comment]
Let's merge after clazy passed.

**Comment by uklotzde** [comment]
q.o.d.

**Comment by uklotzde** [comment]
I'll fix the merge conflicts and merge 2.3 into main.

**Pull request merged**
