### PR TITLE
[WiP] SCons 3 / Fedora 27: Build failures

### PR DESCRIPTION
**Pull request by uklotzde**
https://bugs.launchpad.net/mixxx/+bug/1732272

Unfortunately even after these fixes the build is still failing:
```
scons: Reading SConscript files ...
INFO:root:Target Platform: linux
INFO:root:Target Machine: x86_64
INFO:root:Build: debug
INFO:root:Toolchain: gnu
INFO:root:Crosscompile: NO
INFO:root:Qt path: /usr/lib64/qt-3.3
branch has changed->scons3
os.makedirscache/scons3
touch.sconsign.branch
Deleting deprecated build file: /home/uk/Projects/Mixxx/mixxx/src/build.h
Checking whether the C++ compiler works... yes
Configuring MixxxCore
Checking for pkg-config (at least version 0.15.0)... yes
ERROR:root:Unmet dependency: name 'basestring' is not defined
Checking for C library X11... Configuring Mad
ERROR:root:Unmet dependency: Multiple ways to build the same target were specified for: /home/uk/Projects/Mixxx/mixxx/.sconf_temp/conftest_2.c  (from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'] and from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'])
(cached) Checking for C library libmad... Configuring CoreAudio
Configuring MediaFoundation
Configuring HSS1394
Configuring HID
ERROR:root:Unmet dependency: Multiple ways to build the same target were specified for: /home/uk/Projects/Mixxx/mixxx/.sconf_temp/conftest_2.c  (from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'] and from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'])
(cached) Checking for C library hidapi-libusb... Configuring Bulk
ERROR:root:Unmet dependency: Multiple ways to build the same target were specified for: /home/uk/Projects/Mixxx/mixxx/.sconf_temp/conftest_2.c  (from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'] and from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'])
(cached) Checking for C library libusb-1.0... Configuring MacAppStoreException
Configuring VinylControl
ERROR:root:Unmet dependency: 'dict' object has no attribute 'has_key'
Configuring LiveBroadcasting
ERROR:root:Unmet dependency: Multiple ways to build the same target were specified for: /home/uk/Projects/Mixxx/mixxx/.sconf_temp/conftest_2.c  (from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'] and from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'])
(cached) Checking for C library libshout... Configuring Opus
ERROR:root:Unmet dependency: Multiple ways to build the same target were specified for: /home/uk/Projects/Mixxx/mixxx/.sconf_temp/conftest_2.c  (from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'] and from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'])
(cached) Checking for C library opusfile... Configuring Profiling
Configuring BuildTime
Configuring QDebug
Configuring Verbose
Configuring Optimize
Configuring FAAD
ERROR:root:Unmet dependency: Multiple ways to build the same target were specified for: /home/uk/Projects/Mixxx/mixxx/.sconf_temp/conftest_2.c  (from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'] and from ['\n#include <mp4v2/mp4v2.h>\n\n'])
(cached) Checking for C header file mp4v2/mp4v2.h... Configuring WavPack
ERROR:root:Unmet dependency: Multiple ways to build the same target were specified for: /home/uk/Projects/Mixxx/mixxx/.sconf_temp/conftest_2.c  (from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'] and from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'])
(cached) Checking for C library wavpack... Configuring ModPlug
ERROR:root:Unmet dependency: Multiple ways to build the same target were specified for: /home/uk/Projects/Mixxx/mixxx/.sconf_temp/conftest_2.c  (from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'] and from ['\n#include <libmodplug/modplug.h>\n\n'])
(cached) Checking for C header file libmodplug/modplug.h... Configuring TestSuite
Configuring Vamp
ERROR:root:Unmet dependency: Multiple ways to build the same target were specified for: /home/uk/Projects/Mixxx/mixxx/.sconf_temp/conftest_2.c  (from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'] and from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'])
(cached) Checking for C library vamp-hostsdk... Configuring ColorDiagnostics
Configuring Sanitizers
Configuring LocaleCompare
ERROR:root:Unmet dependency: Multiple ways to build the same target were specified for: /home/uk/Projects/Mixxx/mixxx/.sconf_temp/conftest_2.c  (from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'] and from ['\n\n\nint\nmain() {\n  \nreturn 0;\n}\n'])
(cached) Checking for C library sqlite3... Configuring Battery
Configuring IOKit
Configuring UPower
Configuring PerfTools
Configuring AsmLib
Configuring IPod
Configuring FFMPEG
(cached) Checking for libavcodec (53.35.0 or higher)... 	yes
Checking for libavformat (53.21.0 or higher)... 	yes
Configuring OpenGLES
ERROR:root:Build had unmet dependencies. Exiting.
```

### CODE REVIEW

**Comment by daschuer** [comment]
Sometimes it helps to delete the .sconsign.dblite file. 
You may also try a fresh checkout.

**Comment by Be-ing** [comment]
I have encountered similar strange issues with scons not finding dependencies after updating to a new version of Fedora that were solved by deleting the .sconsign.dblite file. Running `scons -c` may help too.

**Comment by uklotzde** [comment]
I already have a full featured cleanup script ;)

Even after all those fixes building Mixxx is still not possible.

**Comment by uklotzde** [comment]
Build files are created now. Rotting Python code, really frustrating!!

Unfortunately neither the Qt4 nor the Qt5 build work:
Qt4: Includes of QtCore files fail
Qt5: uic is not run before compilation of dependent .h/.cpp files

**Comment by uklotzde** [comment]
```
Preparing target lin64_build/controllers/dlgcontrollerlearning.o...
Building lin64_build/controllers/dlgcontrollerlearning.o with action:
  $CXX -o $TARGET -c $CXXFLAGS $CCFLAGS $_CCCOMCOM $SOURCES
g++ -o lin64_build/controllers/dlgcontrollerlearning.o -c -std=c++11 -pipe -Wall -Wextra -g -O3 -ffast-math -funroll-loops -fomit-frame-pointer -march=native -pthread -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -Dx86_64 -DMIXXX_BUILD_DEBUG -DMIXXX_DEBUG_ASSERTIONS_FATAL -D__LINUX__ -D__UNIX__ -DSETTINGS_PATH=\".mixxx/\" -DSETTINGS_FILE=\"mixxx.cfg\" -DUNIX_SHARE_PATH=\"/usr/local/share/mixxx\" -DUNIX_LIB_PATH=\"/usr/local/lib/mixxx\" -D__PORTAUDIO__ -DQT_TABLET_SUPPORT -DQT_SHARED -DQT_CORE_LIB -DQT_GUI_LIB -DQT_OPENGL_LIB -DQT_XML_LIB -DQT_SVG_LIB -DQT_SQL_LIB -DQT_SCRIPT_LIB -DQT_NETWORK_LIB -DQT_SHARED -D__SNDFILE__ -DSFC_SUPPORTS_SET_COMPRESSION_LEVEL -D__MAD__ -D__HID__ -D__BULK__ -D__VINYLCONTROL__ -D__BROADCAST__ -D__OPUS__ -D__MODPLUG__ -D__VAMP__ -Dkiss_fft_scalar=double -DHAVE_FFTW3 -D__SQLITE3__ -D__BATTERY__ -D__FFMPEGFILE__ -Ilin64_build -Isrc -I/usr/include/soundtouch -Ilib/replaygain -I/usr/include/alsa -I/usr/lib64/qt-3.3/include/qt4/QtDBus -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtOpenGL -I/usr/include/QtXml -I/usr/include/QtSvg -I/usr/include/QtSql -I/usr/include/QtScript -I/usr/include/QtNetwork -I/usr/include/QtTest -I/usr/include/QtScriptTools -I/usr/include/QtDBus -Ilib/gtest-1.7.0/include -Ilib/fidlib-0.9.10 -I/usr/include/taglib -Ilib/qtscript-bytearray -Ilib/reverb -Ilib/portaudio -I/usr/include/hidapi -I/usr/include/libusb-1.0 -Ilib/xwax -Ilib/scratchlib -I/usr/include/opus -I/usr/include/libupower-glib -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/ffmpeg src/controllers/dlgcontrollerlearning.cpp
In file included from src/controllers/dlgcontrollerlearning.cpp:12:0:
src/controllers/dlgcontrollerlearning.h:16:10: fatal error: controllers/ui_dlgcontrollerlearning.h: No such file or directory
 #include "controllers/ui_dlgcontrollerlearning.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [lin64_build/controllers/dlgcontrollerlearning.o] Error 1
scons: internal stack trace:
  File "/usr/lib/scons/SCons/Job.py", line 258, in run
    task.execute()
  File "/usr/lib/scons/SCons/Script/Main.py", line 190, in execute
    SCons.Taskmaster.OutOfDateTask.execute(self)
  File "/usr/lib/scons/SCons/Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "/usr/lib/scons/SCons/Node/__init__.py", line 750, in build
    self.get_executor()(self, **kw)
  File "/usr/lib/scons/SCons/Executor.py", line 396, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "/usr/lib/scons/SCons/Executor.py", line 130, in execute_action_list
    raise status
scons: building terminated because of errors.
```

**Comment by uklotzde** [comment]
UIC is still not invoked and the build fails.

@Pegasus-RPG suggested to use SCons 2.5.1 in the meantime. I didn't even think of this most simple and obvious solution! It works 👍 I added a section to the [Linux build instructions in the Wiki](https://mixxx.org/wiki/doku.php/compiling_on_linux).

Should we close this PR our merge the changes? At least all modifications are backwards compatible with SCons 2.5.1 / Python 2.7.

**Comment by daschuer** [comment]
There is nothing against merging this. Unfortunately Travis fails for an unrelated reason. 
I will test it on my device.

**Comment by daschuer** [comment]
It works, LGTM. Thank you and sorry for your headaches!

**Comment by Be-ing** [comment]
:/ It looks like this broke the Ubuntu builds on the build server: https://builds.renegadetech.mixxx.org/job/master-release/architecture=amd64,platform=ubuntu/469/console

**Comment by daschuer** [comment]
Stange, I have explicit tested this on my Ubuntu Trusty 64 bit system and it work.
I bet it is a scons issue with a corrupt database or something. @Pegasus-RPG can you check if it works after entirely cleaning out the build dir.

**Pull request merged**
