### PR TITLE
Update Novation Launchpad controller scripts to v3.1.1

### PR DESCRIPTION
**Pull request by dszakallas**
# Upgraded scripts

Controllers:
- Novation Launchpad MK1 (Novation-Launchpad-scripts.js)
- Novation Launchpad MK2 (Novation-Launchpad MK2-scripts.js)

Changes since v2.3.1:

### Bug Fixes

* remove circular dependencies ([746cc72](https://github.com/dszakallas/mixxx-launchpad/commit/746cc72e985f25f0100495173fb70351d262dc0d))

## [3.0.0](https://github.com/dszakallas/mixxx-launchpad/compare/v2.3.3...v3.0.0) (2022-04-30)

⚠️ Requires Mixxx 2.4 or newer ⚠️ 

#### New features & improvements:
- [x] Introduce a JSON compatible declarative configuration of layouts to make preset authoring easier
- [x] Sampler palette layout
- [x] Basic RGB LED support for HOTCUEs
- [x] RGB LED support for samplers
- [x] Library maximize / minimize button

#### Fixes:
- [x] Loopjump and beatjump modifiers work more consistently with the rest of the controls
- [x] Fixed retain attack mode bug causing incorrect behavior when shift/control changed between attack/release

#### Breaking changes:
- [x] Drop compatibility with Mixxx < 2.4 (old JS engine)
---------

### Bug Fixes

* short layout clash ([f6e0085](https://github.com/dszakallas/mixxx-launchpad/commit/f6e008533dc24f1ecf103f31cd0e716d5530b04d))

### Bug Fixes

* **app:** initialize pfl control properly ([ffe460f](https://github.com/dszakallas/mixxx-launchpad/commit/ffe460fb6cb530b828eb80daac14be7814e3c7b4))

# New scripts

- Novation Launchpad Mini MK3 (Novation-Launchpad Mini MK3-scripts.js)

# Notes

Uses ES6 features, I tested compatibility with Mixxx 2.4.0. **Not compatible with Mixxx 2.3**

### CODE REVIEW

**Comment by Swiftb0y** [comment]
Hey there, I'm very happy to see this PR and will review it shortly. I've also taken a quick glance at your blog:

> As a functional programmer, I am not entirely happy with the amount of classes and state involved, but moving to a reactive functional paradigm seems to be too much work, as the system boundaries are imperative by nature, requiring extensive plumbing; while the inner, reactive part would be too thin.

This might change in the future. It would require significant work and breaking API changes, but if our mapping used Qt signals and slots and was run in a QMLEngine instead of JS engine, it would be much easier to write mappings in a FRP-style, which it seems you enjoy.

**Comment by Swiftb0y** [comment]
Please rebase on the 2.4 branch if you want your mapping to get included into 2.4 (`main` is already `2.5-alpha`).

**Comment by Swiftb0y** [comment]
Would it be possible in your build-system to emit a `/* eslint-disable */` at the top of each file? `eslint` does not need to run on autogenerated files like these.

**Comment by dszakallas** [comment]
Hey, I reopened it against 2.4: https://github.com/mixxxdj/mixxx/pull/11914. Let's continue the discussion there.

**Pull request closed without merging**
