### PR TITLE
pre-commit.ci

### LINKED ISSUE #11306: Switch to pre-commit.ci for pre-commit on CI.
pre-commit.ci is the CI service run by the maintainer of pre-commit. It would make sense to transition to them for two primary reasons: more efficient resource use (which also results in faster builds) and on-request automatic fixing which would significantly lower the barrier to entry for casual contributors (see https://github.com/mixxxdj/mixxx/pull/11279#issuecomment-1444333724). 

Thoughts?

### PR DESCRIPTION
**Pull request by Swiftb0y**
This serves as a first step for switching over to pre-commit.ci instead of our separate GA runner. I think the next step would be to authorize pre-commit.ci to run on our repo. After that passes, we can delete our pre-commit GA workflow. Does that sound reasonable?

Closes #11306

### CODE REVIEW

**Comment by Swiftb0y** [comment]
> So we want the auto commit an issue on demand, to not clutter the commit history with these commits by default. Right?

yes.

> How can we allow that pre-commit.ci edits the users branch?

From what I understand, the maintainer gives the pre-commit.ci application access to the repository, resulting in similar access rights as the maintainer. Then the user gives access rights to their PR branch (which is by default granted).

**Comment by daschuer** [comment]
The pre-commit.ci will act as a GitHub App on the behalf of the given use account. 
https://docs.github.com/de/apps/using-github-apps/authorizing-github-apps  
I am not sure if it is a good idea to give that away off of our control. 

Looking at our Netlify GitHub App it has these permissions: 

grafik

How is the situation with pre-commit.ci? 

The access should be limited to the Pull Request it running, not sure if that will be the case. 

There is also a lite version, where the commit is done from a workflow action, this has by default only write access to that PR it is running on. Is that a good alternative?

**Comment by Swiftb0y** [comment]
> There is also a lite version, where the commit is done from a workflow action, this has by default only write access to that PR it is running on. Is that a good alternative?

No, because its equivalent to the GA workflow we have now. The lite version does not have the on-demand autofix capability (nor the automatic `pre-commit autoupdate` but thats not really a reason for switching). 

> How is the situation with pre-commit.ci?

Screenshot from 2023-03-01 22-30-18

> The access should be limited to the Pull Request it running, not sure if that will be the case.

I'm not sure if the github api is granular enough for that.

**Comment by daschuer** [comment]
I looks like that the pre-comit.ci request code write permission to our whole repository. I am not strictly against it, but we need to well consider the security implications. 

Using a magic comment to apply the comment is also not very convenient. Maybe we can add a manual started workflow for the lite version and use it during an evaluation period. After that we can reconsider all the topics.

**Comment by Swiftb0y** [comment]
> Using a magic comment to apply the comment is also not very convenient. Maybe we can add a manual started workflow for the lite version and use it during an evaluation period. After that we can reconsider all the topics.

How is that less convenient than manually starting a workflow?

**Comment by daschuer** [comment]
This is a matter of taste finally. But what do you think about the proposal?

**Comment by Swiftb0y** [comment]
> This is a matter of taste finally. But what do you think about the proposal?

I'm not sure its worth the effort. I agree that we should minimize privileged access to our repository as much as possible. I just don't want to introduce even more things to maintain.
If you want to go that route and implement a workflow that manually applies a pre-commit patch, it would be trivial to run that automatically on PR comment too. So I'm ok with your proposal, but I don't want to spend the time implementing it.

**Comment by Swiftb0y** [comment]
I'll close this for now. A custom action that runs on repo dispatch is probably the more secure option, though that increases maintenance.

**Pull request closed without merging**
