### PR TITLE
de-vendor benchmark

### LINKED ISSUE #11742: RPM Fusion build fails: sampleutiltest.cpp
### Bug Description

Build fails on all supported platforms: https://koji.rpmfusion.org/koji/taskinfo?taskID=602238

See the build log(s) for details, e.g. [build_x86-64.zip](https://github.com/mixxxdj/mixxx/files/12039739/build_x86-64.zip)

```
In function '__fill_a1',
    inlined from '__fill_a' at /usr/include/c++/13/bits/stl_algobase.h:977:21,
    inlined from 'fill' at /usr/include/c++/13/bits/stl_algobase.h:1007:20,
    inlined from 'fill' at /builddir/build/BUILD/mixxx-f73413685fe173a07239c66a3a8d619c954f8e74/src/util/sample.h:48:18,
    inlined from 'FillBuffer' at /builddir/build/BUILD/mixxx-f73413685fe173a07239c66a3a8d619c954f8e74/src/test/sampleutiltest.cpp:46:25,
    inlined from 'TestBody' at /builddir/build/BUILD/mixxx-f73413685fe173a07239c66a3a8d619c954f8e74/src/test/sampleutiltest.cpp:318:19:
/usr/include/c++/13/bits/stl_algobase.h:931:18: warning: '__builtin_memset' specified bound between 18446744065119617024 and 18446744073709551612 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
  931 |         *__first = __tmp;
      |                  ^
```

Only the hardened RPM builds fail. The local build succeeds.

### Version

2.4

### OS

Fedora 38, 39 (rawhide)

### PR DESCRIPTION
**Pull request by daschuer**
Since benchmark is included in the vcpkg environments we can remove it from our lib folder. 

closes https://github.com/mixxxdj/mixxx/issues/11742

### CODE REVIEW

**Comment by daschuer** [comment]
This has unfortunately some dependency:
The VCPKG 2.5 branch has dropped Qt6 and than added benchmark. 
This means merging this to 2.4 and than to main will break main. 
For building main with Qt6 we need to merge https://github.com/mixxxdj/mixxx/pull/11701

**Comment by Swiftb0y** [comment]
Can we merge this now? Can you elaborate again how this is dependent Qt6?

**Comment by uklotzde** [comment]
This change would avoid a custom patch for the RPM Fusion build on Fedora.

**Comment by Swiftb0y** [comment]
> Can we merge this now? Can you elaborate again how this is dependent Qt6?

ping...

**Comment by daschuer** [comment]
We don't have a 2.5 vcpkg branch with benchmark and without Qt6. We need to switch to the 2.5 branch with benchmark before we merge the 2.4 branch to main. 
Alternative: disable Benchmark in main until that.

**Comment by daschuer** [comment]
Oh, I just realized that the GTest PR has the same issue and has been merged. So we can safely merge that. 
Just delay the 2.4 to master merge or accept that we have no MacOS and Windows CI for the (short) transition.

**Comment by Swiftb0y** [comment]
Neither is really good since any1 could merge those branches out of routine. Lets just accept the situation and do our best to keep the duration as short as possible. Whats required next for Qt6?

**Comment by daschuer** [comment]
Ok, so this one can be merged. 
I will than create a 2.4 merge PR including the Qt switch changes. I have such a branch already in preparation.

**Comment by daschuer** [comment]
Thank you.

**Comment by Holzhaus** [comment]
> Neither is really good since any1 could merge those branches out of routine.

Yes, I stumbled over this when merging `2.4` into `main`. Next time let's postpone the merge of such a PR and update the buildenvs for subsequent releases first to avoid this situation. Anyway, I tried to resolve the CI issues in #12762.

**Pull request merged**
