### PR TITLE
HidEnumerator: skip all HID devices with Apple's vendor ID

### PR DESCRIPTION
**Pull request by Be-ing**
https://github.com/mixxxdj/mixxx/pull/4243#issuecomment-911433869

### CODE REVIEW

**Review by uklotzde — APPROVED** [review]
I second that.

**Comment by uklotzde** [comment]
Please add a changelog entry!

Could we be sure that we don't break existing use cases? Or play it safe and target main instead of 2.3?

**Comment by ronso0** [comment]
since Apple doesn't build actual controllers, one use case would be to have a (second) Magazin c mouse and use that for whatever, scratching..?
safe to break those rare cases if that fixes issues for all other mac users, no?

**Comment by uklotzde** [comment]
No objections, then let's merge. LGTM

**Pull request merged**
