### PR TITLE
DjInteropt Require Version 0.16.1 exact

### PR DESCRIPTION
**Pull request by daschuer**
The upcoming not yet released Version 0.17.0 is not yet compatible. 
This fails the build early instead of causing obscure compiler errors:

```
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:20:27: error: expected namespace name
namespace el = djinterop::enginelibrary;
               ~~~~~~~~~~~^
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:195:13: error: use of undeclared identifier 'el'
            el::default_database_dir_name);
            ^
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:202:34: error: use of undeclared identifier 'el'
            versionIndex == -1 ? el::version_latest_firmware : el::all_versions[versionIndex];
                                 ^
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:202:64: error: use of undeclared identifier 'el'
            versionIndex == -1 ? el::version_latest_firmware : el::all_versions[versionIndex];
                                                               ^
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:224:13: error: use of undeclared identifier 'el'
            el::default_database_dir_name);
            ^
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:228:23: error: use of undeclared identifier 'el'
        bool exists = el::database_exists(databaseDirectory.toStdString());
                      ^
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:235:63: error: use of undeclared identifier 'el'
            for (const djinterop::semantic_version& version : el::all_versions) {
                                                              ^
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:237:48: error: use of undeclared identifier 'el'
                        QString::fromStdString(el::version_name(version)),
                                               ^
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:239:32: error: use of undeclared identifier 'el'
                if (version == el::version_latest_firmware) {
                               ^
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:252:34: error: use of undeclared identifier 'el'
        djinterop::database db = el::load_database(databaseDirectory.toStdString());
                                 ^
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:253:33: error: no member named 'version' in 'djinterop::database'
        const auto version = db.version();
                             ~~ ^
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:255:39: error: use of undeclared identifier 'el'
        const auto result = std::find(el::all_versions.begin(), el::all_versions.end(), version);
                                      ^
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:255:65: error: use of undeclared identifier 'el'
        const auto result = std::find(el::all_versions.begin(), el::all_versions.end(), version);
                                                                ^
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:256:23: error: use of undeclared identifier 'el'
        if (result == el::all_versions.end()) {
                      ^
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:265:46: error: use of undeclared identifier 'el'
            int versionIndex = std::distance(el::all_versions.begin(), result);
                                             ^
/home/aby/packages/mixxx-bsd/src/library/export/dlglibraryexport.cpp:271:47: error: use of undeclared identifier 'el'
                    0, QString::fromStdString(el::version_name(version)), QVariant{versionIndex});
                                              ^
16 errors generated.
```

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
How can it happen, that someone get this incomplete development version of libdjinterop unintentional?

**Comment by daschuer** [comment]
If you install this version on Linux. 
I made this PR to release us from discussions like this: 
https://mixxx.zulipchat.com/#narrow/stream/247620-development-help/topic/compiling.20mixxx.20on.20openbsd.20-current

**Comment by daschuer** [comment]
But it will not build with GCC 12 due to a missing include: 
https://github.com/xsco/libdjinterop/issues/78

**Comment by mr-smidge** [comment]
FYI, tag 0.16.1 should now fix the gcc 12/13 issue.

**Review by Swiftb0y — APPROVED** [review]
Thank you

**Pull request merged**
