### PR TITLE
Cue & CueControl Fixes

### PR DESCRIPTION
**Pull request by uklotzde**
This PR should fix the following bugs:

https://bugs.launchpad.net/mixxx/+bug/1596237

The implementation of cue management is unnecessarily complex and error prone. I just tried to fix the open bugs that affected me.

I also noticed that cleared hotcues don't get deleted from the database. Instead they are kept with a hotcue index of -1 forever and are implicitly ignored. This issue should be tracked and fixed separately: https://bugs.launchpad.net/mixxx/+bug/1653276

### CODE REVIEW

**Comment by daschuer** [comment]
I have not yet tested this, but the changes are looking good. 
I have just not understood why we have Cue::LOAD and Cue::CUE. 
The patch changes the place where LOAD is written. 
Is there a case when both are different? Is there a use case for a future version?

**Comment by uklotzde** [comment]
I don't see a need to store Cue::LOAD both in the track and as a separate 
cue point. It is THE cue point, without any need to label or assign a color 
to it. Unneeded redundancy. I just kept it, because the code doesn't explain 
or reveal why it is there.

**Comment by daschuer** [comment]
Ok. I will test that under that assumption. 

@nimitbhardwaj is working on a preview cue. https://bugs.launchpad.net/mixxx/+bug/1399321

Maybe it is time to clean up the issue a bit and remove the LOAD cue? ... or replace it with the new preview cue? 

Traktor has a LOAD cue, but I have no Idea what is the use-case behind it. 

A Deck loads at CUE or 0.0 Preview Deck will soon load at Preview cue or ~0:30

Any ideas? 

An other related issue, is that we should allow to place cues at 0.0 and in the lead-in region.

**Comment by daschuer** [comment]
LGTM. Thank you very much.

**Comment by ferranpujolcamins** [comment]
Taktor Load Cue is where the playback cursor is set when a track is loaded.
It would be nice to have.

On 3 Jan 2017 11:02 p.m., "Daniel Schürmann" <notifications@github.com>
wrote:

Merged #1098 <https://github.com/mixxxdj/mixxx/pull/1098>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mixxxdj/mixxx/pull/1098#event-910447194>, or mute the
thread

**Comment by daschuer** [comment]
What makes load cue different from THE CUE? What is the use-case not to load a Track at THE CUE? 
How is it set? Is it part of a different mixing style?

**Pull request merged**
