### PR TITLE
WWidget features and boxmodel for starrating

### PR DESCRIPTION
**Pull request by jclaveau**
This PR adds the following feature to the StarRating widget : 
- ObjectName
- Tooltips
- QSS Box model

### CODE REVIEW

**Comment by jclaveau** [comment]
I created a fake skin to check the behaviour of different widgets : 
https://github.com/demos/developer_skins/tree/render_tests

**Comment by rryan** [comment]
@jclaveau -- why did you need to add WWidget as the parent?

**Comment by jclaveau** [comment]
@rryan Because of its name, I thought I made a mistake when I didn't used it on the first time. Let's remove it!

**Comment by jclaveau** [comment]
@rryan It's done and the size policy is now fixed to avoid the stars to be hidden by a shrunk widget.

**Comment by jclaveau** [comment]
In fact I was right at the beginning, WWidget fixed the tooltip issue.

**Comment by jclaveau** [comment]
Even if it's really not clear in Qt's doc, I guess there is cleaner a way to support box model by inheritance of the QFrame widget. So let's close this PR and dig a bit.

**Comment by jclaveau** [comment]
This PR provides a fix for the missing tooltips : https://github.com/mixxxdj/mixxx/pull/685

**Pull request closed without merging**
