### PR TITLE
Add option to disable build time [1.12 branch]

### PR DESCRIPTION
**Pull request by jobermayr**
Some Linux distribution avoid **DATE** and **TIME** to avoid not needed rebuilds of packages.
(e. g. https://github.com/openSUSE/rpmlint-checks/blob/master/CheckBuildDate.py)

So add an option to disable it.

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for the PR. 
Can you explain why `__DATE__` and `__TIME__` trigger a rebuild?
On my system I get: 

scons: `.' is up to date.

**Comment by jobermayr** [comment]
E. g. openSUSE uses a tool called build-compare (https://build.opensuse.org/package/show/openSUSE:Tools/build-compare) which checks whether the build differs from a former build to avoid unneeded publishing of a new package.

Build can be triggered when the package source or a build dependency changed or manual trigger.

The buildroot gets initialized completely new, extracts the source package and builds again.

Mostly the only change in new binary is caused by different ```__DATE__``` and ```__TIME__```.

Lastly runs build-compare and detects this change in binary but it cannot detect its root. So the package gets published although there isn't a real change and so the package shouldn't become published.

If ```__DATE__``` and ```__TIME__``` are used in a library package it can so cause rebuilds of thousands of dependent packages ...

**Comment by daschuer** [comment]
Ah Thank you. I assume the build-compare tool is smart enough to work with your solution in this PR. 
Please add some comments like above to features.py to avoid future questions. 
Thank you.

**Comment by jobermayr** [comment]
> Please add some comments like above to features.py to avoid future questions. 

Done.

**Comment by rryan** [comment]
Thanks @jobermayr !

**Pull request merged**
