### PR TITLE
Beats: Make return value of mutation methods optional

### PR DESCRIPTION
**Pull request by Holzhaus**
This allows the caller to handle the failure case more efficiently, e.g. by exiting early if nothing changes.

If the caller does not care wether the operation worked and resulted in changes or not and simply needs a valid beats pointer, the following expression can be used:

    pBeats->scale(...).value_or(pBeats)

### Original PR description

~~Unsure if this is desired as it increases the risk for crashes (i.e. if the caller forgets to check for `nullptr`) and makes the code slightly less readable.~~

~~On the other hand it allows skipping code execution if nothing changed. This will become more relevant with #4255 (which only allows scaling if the scaled number of beats between markers is an integer).~~

### CODE REVIEW

**Comment by daschuer** [comment]
> I just implemented that and tbh it makes the code even more complicated.

I don't have a strong opinion here. The current solution looks good. 
@uklotzde What do you think?

**Comment by uklotzde** [comment]
Returning a nullptr as an indicator for an error is dangerous, not intuitive, and conceptually wrong. Unfortunately, we are hitting some C++ limitations here with this design.

As the caller I want to reassign the pointer with every call independent of the outcome. On errors the last state (= pointer) should be preserved and information about the error should be returned separately.

**Comment by uklotzde** [comment]
> I consider using std::pair as an anti pattern in terms of readability.

This is your personal opinion. Tell that the Go folks or consider any other modern programming language that supports anonymous tuples out-of-the box, including C++17. It works considerably well in strongly typed languages, even if I don't like how error handling is done in Go. We should not rule out this option unconditionally for the whole project.

**Comment by uklotzde** [comment]
> I think the semantically correct way would be using `std::optional`.
> 
> If you dont care if scaling worked or not, just use `pBeats->scaled(...).value_or(pBeats)`.

I didn't consider this option, seems to be convenient to use for preserving the existing state in case of a failure. Go for it.

**Comment by Holzhaus** [comment]
> I don't insist anything in this discussion. I have been jumped in because I was mentioned here. All these solutions are working for me. I have only expressed my personal opinion, else I would have issued a formal review.

Yeah sorry, i wasn't saying you were stubborn or something, I just wanted to say that if you'd prefer to add unused the infallible methods I could do that.

Just trying to find a solution here that everyone can live with :D

> In my opinion this is now the most complex, solution and not the best fit. std:::optional is useful if the returned value has no null value. A pointer already has a null value.

I agree that using `std::optional` to wrap a pointer seems weird at first, but I think this approach has several advantages the alternatives (using nullptr, using an pointer argument for output). First and foremost, it's semantically correct (the return value is literally *optional*).

- In contrast to the `nullptr` solution, it's not possible to accidently segfault mixxx by forgetting to check for a `nullptr` return value, because the type is different. It will cause a compiler warning.
- In contrast to the pointer argument solution, both the method implementation and the calling code are much shorter and nicer to read IMHO.

> The nice thing of the original and the pOK solution was that you can use unconditional
>
>      m_pBeatsClone = m_pBeatsClone->scale(bpmScale)
>
> This simplicity and safety is now lost.

If you're not interested in the failure case, the code only becomes slightly longer:

>      m_pBeatsClone = m_pBeatsClone->tryScale(bpmScale).value_or(m_pBeatsClone)

**Review by daschuer — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
