### PR TITLE
controlpickermenu: add missing controls, remove 'key' reset menus

### PR DESCRIPTION
**Pull request by ronso0**
https://bugs.launchpad.net/mixxx/+bug/1895364

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
LGTM, Thank you for taking care.

**Comment by ronso0** [comment]
actually this was a only a day old and WIP as I just asked the reporter to post more un-mappable controls here, like some skin controls.
will open a new PR

**Comment by Holzhaus** [comment]
I suggest to use a draft PR, that makes it more unlikely to merge by accident.

**Comment by mxmilkiib** [comment]
Had another go at clicking-everything whilst the MIDI learn is on, turned up these;
[EffectRack1_EffectUnit1_Effect1],button_parameter3
[EffectRack1_EffectUnit1_Effect2],button_parameter1
[EffectRack1_EffectUnit1_Effect3],button_parameter1
[EffectRack1_EffectUnit2_Effect3],button_parameter2
etc.

**Comment by ronso0** [comment]
interesting, I thought gx parameters were covered by https://github.com/mixxxdj/mixxx/blob/2.3/src/controllers/controlpickermenu.cpp#L638 but appearanly it's just about the knobs.
side note: for fx it's recommended to use the components fx mapping. 

Let's collect more controls here and start another PR soonish

**Comment by ronso0** [comment]
@mxmilkiib I just started #3112 
If you come across other missing controls please post them there. Thanks!

**Pull request merged**
