### PR TITLE
GitHub Actions: Improve package filename

### PR DESCRIPTION
**Pull request by Holzhaus**
Use the same package file name as we used on Appveyor, but use it on all OSes.

### CODE REVIEW

**Comment by daschuer** [comment]
This produces: 
```
Package name: mixxx-pr-3388-cpack-filename-bf1b75c1348a024b9ac6a038e94984405f5746ba
```
What do you want to archive? 

something like:
``` 
mixxxx_2.3.0-beta-pr3388-git7823-bf1b75c13
```
or
```
mixxxx_2.3.0-beta-pr3388-20201224120000-bf1b75c13
```
would be nice.

**Comment by Holzhaus** [comment]
Why not include the branch name? We could include the numeric revision to make the order more obvious, but it could also be confusing if someone force-pushes or rebases.

**Comment by Holzhaus** [comment]
On the other hand we don't deploy PR artifacts to the download server anyway (at least with #3386), so the numeric order isn't really important. You can always load the latest artifact from GitHub Actions instead.

**Comment by Be-ing** [comment]
I don't think this is a great idea to write a new script for this. It introduces code duplication with #3259.

**Comment by daschuer** [comment]
> Why not include the branch name?

Because that can be anything. It is not required to locate the PR. I have tried to keep a version that is continually grows over the time.

**Comment by Holzhaus** [comment]
> > Why not include the branch name?
> 
> Because that can be anything. It is not required to locate the PR. I have tried to keep a version that is continually grows over the time.

I don't think its possible to change the branch name for PRs, so you won't have version where the PR number is the same and the branch name is different. The branch name is not required, true, but it makes it easier to identify what the PR is about without looking it up on GitHub.

**Comment by daschuer** [comment]
I am in favor to keep the pattern mixxx_version, without cluttering the file name with redundant metadata. 
From this point of view we can even remove the comit hash.

**Comment by Be-ing** [comment]
That would require overwriting every old build with the latest build.

**Comment by daschuer** [comment]
> That would require overwriting every old build with the latest build.

please explain

**Comment by Be-ing** [comment]
Two builds of the same branch cannot coexist in the same folder if there is no other identifying information in the file name to distinguish them.

**Comment by daschuer** [comment]
Yes, that's why the PR number should be part of the version.

**Comment by Be-ing** [comment]
That doesn't solve the problem. It would still not be possible to distinguish different builds of the same branch.

**Comment by daschuer** [comment]
See my proposals above.

**Comment by Holzhaus** [comment]
This is probably obsolete now.

**Pull request closed without merging**
