### PR TITLE
LateNight: merge vinyl control toggle and status light

### LINKED ISSUE #10192: Tooltip for vinylcontrol_status does not match to skins
Reported by: **[JoergAtGithub](https://github.com/JoergAtGithub)**
Date: 2020-11-01T08:28:09Z
Status: Confirmed
Importance: Medium
Launchpad Issue: [lp1902412](https://bugs.launchpad.net/bugs/1902412)
Tags: skin, tooltip, vinylcontrol

---

The tooltip describes the colors of the vinylcontrol_status widget as follows:

Vinyl Status
Provides visual feedback for vinyl control status:
Green for control enabled.
Blinking yellow for when the needle reaches the end of the record.
Blue for passthrough enabled.

At least some skins use other visualizations (e.g. in LateNight it blinks green and passthrough is indicated by another widget).

### PR DESCRIPTION
**Pull request by ronso0**
This avoids squeezed controls in compact decks (at least in PaleMoon).

* change the tooltip to match the description of [[ChannelN],vinylcontrol_status](https://manual.mixxx.org/2.4/en/chapters/appendix/mixxx_controls.html#control-[ChannelN]-vinylcontrol_status)
* add toggle/status tooltip combo
* merge toggle and status light in LateNight
___
Side note:
I find `vinylcontrol_status` confusing (I don't actually use it). It's repeatedly [set to `1`/`VINYL_STATUS_OK`](https://github.com/mixxxdj/mixxx/blob/69e1caf53e372566b53b1e26ba114b3bc4d73f7f/src/vinylcontrol/vinylcontrolxwax.cpp#L789-L790) even though it receives only noise from my mic, regardless which mode I have set.
___
Closes: #10192

### CODE REVIEW

**Comment by ronso0** [comment]
Someone needs to test this with real VC.
I once tested by playing timecode in another deck and route it via a loopback device but that was glitchy.

**Comment by JoergAtGithub** [comment]
There are no line breaks in the tooltips anymore (on Windows 11).

2.4:
grafik

This PR:
grafik

**Comment by ronso0** [comment]
Oh. Fixed it.

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Pull request merged**
