### PR TITLE
lib: Update googletest 1.10.x to latest HEAD@9741c42

### PR DESCRIPTION
**Pull request by Holzhaus**
GoogleTest now follows the Abseil [Live at Head] philosophy and recommends
using the latest commit in the master branch.

The 1.10.x release causes a [CMake deprecation warning], which is
already fixed on master. Hence, this updates the googletest libraries to
https://github.com/google/googletest/commit/9741c42200b66abc708ee6da269a29c8bd912cee.

[Live at Head]: https://github.com/google/googletest#live-at-head
[CMake deprecation warning]: https://github.com/google/googletest/issues/3274

### CODE REVIEW

**Comment by Holzhaus** [comment]
Needs #3887 to work.

**Comment by Holzhaus** [comment]
No idea where the failing Appveyor check comes from. Maybe GitHub got confused or something.

**Comment by uklotzde** [comment]
Bundling everything is a lot of stuff. On the other hand deleting `docs`/`test`/`ci`/`github` directories manually after the download would be extra work that needs to be documented. Any ideas how to improve the situation?

**Comment by daschuer** [comment]
About how many mega bytes are.we talking?

Is there a plan to regular update google test, or only if we need a feature or a bug fix? 

If such an update happens once a year or such, we can IMHO effort extra work. If we want to keep up with googles head, I think we should remove it entirely, and require it as build dependecy.

For now I am in favor of the first.

**Comment by uklotzde** [comment]
Diff: +69k/-13k

**Comment by Holzhaus** [comment]
Done. This is what I removed:

```
m -rf docs ci .github googlemock/test/ googletest/samples/ googletest/test/
```

**Comment by uklotzde** [comment]
How about adding those directories to our .gitignore with a comment? This would exclude them from all future commits without manual intervention and works on all platforms.

**Comment by Holzhaus** [comment]
Done.

**Comment by uklotzde** [comment]
> Done.

The idea is so obvious that I wonder why we haven't applied this to all our bundled libraries, perfect use case for the project's .gitignore.

**Review by uklotzde — APPROVED** [review]
Thanks for pushing this. I also had it in mind, but it just never was important enough to actually do it. LGTM

**Pull request merged**
