### PR TITLE
Update DJ Control Instinct mapping with effect racks

### PR DESCRIPTION
**Pull request by freaktechnik**
The mapping for the Hercules DJ Control Instinct still uses the flanger effect instead of the new effect racks.
This pull request replaces the inputs and outputs of the effect buttons with mappings to the effect racks.

Repoened #698 agains the 1.12 branch.

### CODE REVIEW

**Comment by freaktechnik** [comment]
(oops, sorry)

**Comment by ywwg** [comment]
yeah, sorry, retargetting a PR is tricky -- you have to start a new branch of 1.12 and then git cherry-pick your commits to that

**Comment by ywwg** [comment]
or actually maybe that's where you can use your existing branch and do git rebase --onto 1.12.  I haven't done that before but I think that works.

**Comment by ywwg** [comment]
Yes, that's how to do it:

* checkout your feature branch
* git rebase --onto 1.12
* fix merge problems
* git diff 1.12 to see that the diffs to 1.12 are small
* retarget the PR to 1.12

**Pull request closed without merging**
