### PR TITLE
Require Taglib 1.10

### PR DESCRIPTION
**Pull request by daschuer**
This re-reverts 
https://github.com/mixxxdj/mixxx/commit/7858be0e938e79c64ac1aa203c00920203a00a88
Please see the discussion there. 

This setting works successful at: 
https://launchpad.net/~daschuer/+archive/ubuntu/mixxx  
So I would like to see it in our release 2.0

### CODE REVIEW

**Comment by rryan** [comment]
This commit breaks our build -- that's why I reverted it. 

Beyond that -- we don't need to require 1.10. The user gets whatever taglib their system has available. If they use our PPA (which is entirely what this PR touches -- not our Debian package in Universe) then they will get 1.10 if we provide TagLib in the PPA -- which I plan to do based on your work. We don't need to require it via the control file, since this will prevent users from being able to install the package if they take the .deb from the PPA and try to install it by hand.

**Comment by daschuer** [comment]
> This commit breaks our build -- that's why I reverted it.
 
Yes, sure, it will build again if you install libtag-dev 1.10 on the build server. 

> Beyond that -- we don't need to require 1.10. The user gets whatever taglib their system has available.

This will be most likely be taglib 1.9 and that is what I want to avoid.

This is more political issue than a technical. We have just to make sure what our strategy will be. 

A user can still install the mixxx deb manually if he also fetched the taglib 1.10 and installs it first. 
This patch forces that and make sure that no one runs Mixxx 2.0 with taglib 1.9 and experience crashes. 
I do not see a reason not to install taglib 1.10. 

This patch also clarifies that Mixxx 2.0 requires taglib 1.10 to all other maintainer of various Linux distros.  

So it is just the question force taglib 1.10 for Mixxx 2.0?

**Comment by rryan** [comment]
> So it is just the question force taglib 1.10 for Mixxx 2.0?

I don't see a strongly compelling reason to prevent someone from running Mixxx if they can't get taglib 1.10 installed. There's a decoding segfault for certain corrupt FLAC files and some other bugfixes. Given that we do have vast numbers of people "me too"'ing that FLAC crash bug, I'm going to go out on a limb and say it's minor impact but high severity.

**Comment by daschuer** [comment]
What else can we do to make clear, that we do not want anyone to run Mixxx 2.0 with taglib 1.10. ? 

A big note in the install script or something? 

We can use the new taglib API :-P

**Comment by Pegasus-RPG** [comment]
Why not just put "taglib >= 1.10" in the Recommends field? " This declares a strong, but not absolute, dependency. "

**Comment by daschuer** [comment]
That will be better than nothing. 
If one experience crashed, we can say: why you ignore our recommended packages (which are unfortunately almost hidden by default :-/)

**Comment by Pegasus-RPG** [comment]
Let's do that then. (Apt installs Recommended packages by default, you know.)

**Comment by daschuer** [comment]
I have tried to do a build with  libtag1-vanilla (>= 1.10) as recommended, but It is moved to required. 
I think because it is installed during the build process, due to re version less requirement. 

I am trying again.

**Comment by daschuer** [comment]
If I remove libtag1 1.10 from the ppa, it remains in the recommended section. So far so good. 
But the behaviour is like I have expected. During the install using GDebi or Ubuntu software-center, 
there is not a single hint that we like to see libtag 1.10 installed as well. You can see it after install, if you right click on mixxx in synaptics but the version number is entirely hidden. 

So it look like "recomended" does not help at all. If a user Installs from our PPA he gets the taglib update anyway if not, no hint ... :-( 

Different with this PR: The user is forced to use taglib 1.10. If he was able to download the mixxx.dep and gets "not resolvable dependency ibtag1-vanilla (>= 1.10)", he will surly be able to download it from the same source. 

By the way: Mixxx 1.10 was split into bin and data package and Nico has done it as well.  
Will we provide two packages anyway? 

A workings solution would be a pop-up from the install script. 

Any ideas?

**Comment by daschuer** [comment]
Any comments or ideas?

**Comment by rryan** [comment]
Hello! This branch is against the 1.12 branch, which is now closed to any changes except bugfixes. Please re-open your PR against master if this PR is still relevant.

**Comment by daschuer** [comment]
We have still no conclusion about this. 
..  and we even have not the minimal solution: A package for all Ubuntu versions in our ppa:mixxx/mixxx. 

See: https://bugs.launchpad.net/mixxx/+bug/1411479

**Comment by rryan** [comment]
If we require taglib 1.10 then the standalone deb will fail to install. I'm sorry but that's not an option when we're talking about a small impact problem. 

The solution we have -- that PPA users get taglib 1.10 -- is the most we should do here.

**Comment by daschuer** [comment]
Now I have got taglib 1.10 from ppa. 
So we can close this. 
Thank you.

**Pull request closed without merging**
