### PR TITLE
Fix Qt 5.15 build errors

### PR DESCRIPTION
**Pull request by uklotzde**
Caused by merging #4536.

### CODE REVIEW

**Review by ronso0 — APPROVED** [review]
LGTM 
reference: [obsolete QString::KeepEmptyParts](https://doc.qt.io/qt-5/qstring-obsolete.html#SplitBehavior-enum), [new Qt::SkipEmptyParts 5.14+](https://doc.qt.io/qt-5/qt.html#SplitBehaviorFlags-enum)
Though I built only with 5.12.8, so if you verified it builds with 5.14+. ready for merge.

**Comment by uklotzde** [comment]
Unrelated test failures for macOS, strange.

**Comment by ronso0** [comment]
@uklotzde 
> Though I built only with 5.12.8, so if you verified it builds with 5.14+. ready for merge.

A formal Yes and I hit Merge

**Comment by uklotzde** [comment]
Yes, sure. Just copy and paste from already used code.

**Pull request merged**
