### PR TITLE
SCons: Generate a compilation database for use with clang-tidy, clangd, etc.

### PR DESCRIPTION
**Pull request by rryan**
`scons compiledb` generates a `compile_commands.json` file which can be used with clang-tidy, clangd, clang-include-fixer, etc. 

Also fixes some issues found with clang-tidy.

### CODE REVIEW

**Comment by rryan** [comment]
> Can we also add a script, that calls clang-tidy? Or can GitHub do it?

Adding that in a follow-up PR :).

**Comment by daschuer** [comment]
Eclipse is able read the compile_commands.json file as well if you install cmake4eclipse.
This will help to get arround parsing the console output, which sometimes fails.

In case of cmake the json file is created during the configuration phase and is updated by every project change.

Can we do this here too, and make it a build optin?

**Comment by rryan** [comment]
> Eclipse is able read the compile_commands.json file as well if you install cmake4eclipse.
> This will help to get arround parsing the console output, which sometimes fails.
> 
> In case of cmake the json file is created during the configuration phase and is updated by every project change.
> 
> Can we do this here too, and make it a build optin?

I'd be happy with unconditionally building it (no build option) so that you don't have to remember re-building it when switching branches, etc.

**Comment by daschuer** [comment]
It the json file recreated after switching branches? Does the file belong to the output directory? It changed according to the target.
I think it should be virtualized, because it may change from branch to branch.

**Comment by rryan** [comment]
> It the json file recreated after switching branches? Does the file belong to the output directory? It changed according to the target.
> I think it should be virtualized, because it may change from branch to branch.

I believe tools expect it to be in the root of the repo, so it might be easiest to keep it there.

I can virtualize it, but I believe the end result is the same since on the same run of scons that triggers virtualization logic, SCons will also regenerate compile_commands.json (it does so on every invocation of scons).

**Comment by daschuer** [comment]
Ok, makes sense.

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
