### PR TITLE
lp1864512: Preferences DialogBox Left NavBar pane width made adjustable

### PR DESCRIPTION
**Pull request by ketan-lambat**
[Bug Worked on](https://bugs.launchpad.net/mixxx/+bug/1864512)
[Fix Suggested ](https://mixxx.zulipchat.com/#narrow/stream/109123-introduce-yourself/topic/Ketan/near/190611086)

### CODE REVIEW

**Comment by Holzhaus** [comment]
@ketan-lambat Thanks for your contribution. However, this does not actually fix the issue you mentioned since you can only make the left pane smaller, but not expand it. I guess that has to do with fixed size hints of the pane or widget on the right.

**Comment by ketan-lambat** [comment]
I changed the max size of the left navigation pane to match that of the right one and changed the size policy of both panes from 'Preferred' to 'Expanding'

**Comment by ronso0** [comment]
Thanks for your contribution!

In order to merge your work you first need to sign the contributor agreement:
https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ

**Comment by ketan-lambat** [comment]
> Thanks for your contribution!
> 
> In order to merge your work you first need to sign the contributor agreement:
> https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ

Welcome 
I have filled the form.
Thanks

**Comment by ronso0** [comment]
On my screen (1366x768) this opens the Pref window in fullscreen (which is not necessary) and I can't resize it. I'm trying to figure out how to avoid that.

Also, IMO we shouldn't allow to collapse the tree or pref page. This seems to be persistent.
I think a minimumSize for both panes is sufficient.
This should be added to the QSplitter
```
<property name="childrenCollapsible">
<bool>false</bool>
</property>
```

**Review by Holzhaus — CHANGES_REQUESTED** [review]
The sidebar is too wide on each restart of Mixxx. Can you restore the previous width of the sidebar?

2020-03-17-182942_2133x2127_scrot

**Comment by ketan-lambat** [comment]
> The sidebar is too wide on each restart of Mixxx. Can you restore the previous width of the sidebar?
> 
> 2020-03-17-182942_2133x2127_scrot

Sir, Can you please guide me on how to view/build the application with the changes made like in the screenshot. 
For eg. in this example, I was able to view the dialog box individually in QtDesigner, but unable to see the changes in the actual application.

I did follow the guidelines given [here](https://mixxx.org/wiki/doku.php/compiling_on_windows) and [here](https://www.mixxx.org/wiki/doku.php/build_windows_installer) but couldn't figure out the exact step to build the installer package / application.

**Comment by Holzhaus** [comment]
> Sir, Can you please guide me on how to view/build the application with the changes made like in the screenshot.

No need to call me "Sir", "Dude" is sufficient :wink:

I'm not a Windows user, so I can't really help you in that regard. Please to ask on Zulip instead. You can also wait for the Appveyor CI builds and download the `mixxx.exe` build artifact into you Mixxx directory. 

> I did follow the guidelines given here and here but couldn't figure out the exact step to build the installer package / application.

You don't need need to build the installer package, just build Mixxx and run the executable from the build directory.

**Comment by ketan-lambat** [comment]
Sorry for this delay
I could build the project in Linux in the first go and now I hate windows for development  ..!!

I made a new fork and made a commit fixing the bug with the latest changes there. Should I open another PR from the new fork ?

**Comment by Holzhaus** [comment]
No, you can just push the changes to this branch. Are you familiar with using hit or do you need help?

**Comment by ketan-lambat** [comment]
To start afresh, I deleted my previous fork and created a new one. So, if I make a PR now, it will be created as a new one and the commit won't add up here.

**Comment by ketan-lambat** [comment]
[The commit in my new fork](https://github.com/ketan-lambat/mixxx/commit/044721623e8664cdca01c3aae7f27ec76e498c91)

**Comment by Holzhaus** [comment]
Ok, I see you deleted your whole repository. In that case make a new PR.

But for next time: Using a version control system like git allows you to revert back to older versions (i.e. without your modifications) at any time, so deleting your fork was unnecessary. Usually, you create a feature branch and work there: https://mixxx.org/wiki/doku.php/using_git#create_a_new_branch

**Pull request closed without merging**
