### PR TITLE
default to 8 hotcues in skins

### PR DESCRIPTION
**Pull request by dfl**
made the changes but was not able to verify it actually works... still don't really understand the software UI 😕

### CODE REVIEW

**Comment by Be-ing** [comment]
> still don't really understand the software UI

Then we probably haven't documented it well enough. What don't you understand?

**Comment by ronso0** [comment]
You need to start with a clean (empty) config to see such default values in the skin after first start.
Temaparily rename your mixxx.cfg and you should see th effect.

**Comment by Be-ing** [comment]
Thanks, I tested this with a fresh `--settingsPath` directory and it works. @dfl can you sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) before we merge this?

**Review by daschuer — APPROVED** [review]
Thank You. 
LGTM.

**Pull request merged**
