### PR TITLE
Deere: add 'Sync Leader' button

### PR DESCRIPTION
**Pull request by ronso0**
|off|leader|follower|
|--|--|--|
|image|image|image|

### CODE REVIEW

**Comment by daschuer** [comment]
Did you consider to use a crown like symbol like in LateNight? This would simplify the manual.

**Comment by ronso0** [comment]
True, a distinct icon for all skins would be preferred.
Of course I considered the crown but the buttons in Deere is small (SYNC is 18 px tall) and cramming a rather detailed crown icon into such a small square button didn't feel like a good idea.
Though, making the crown a borderless button could work (would be the only top-level button without a border).

**Comment by ronso0** [comment]
> buttons in Deere is small (SYNC is 18 px tall) and cramming a rather detailed crown icon into such a small square button didn't feel like a good idea.

Okay, actually it worked. See first post for screenshots.

**Comment by daschuer** [comment]
Great, Thank you.

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Comment by JoergAtGithub** [comment]
Tested this on Windows11 and it works as expected. But the crown symbol doesn't look as in your screenshots: 
grafik
Screen resolution of my laptop is 1920x1200.

**Comment by ronso0** [comment]
> But the crown symbol doesn't look as in your screenshots:

I saw that intermediately, too. I suspect it's related to 'Optimized SVG' so I saved them as plain SVG.
Seems there was a leftover stroke color, even though I don't see it here.
Please try again.

**Comment by JoergAtGithub** [comment]
Now it looks even more broken: 
grafik

**Comment by ronso0** [comment]
Pleae try again.
It seems there are conflicting residues even when pasting a path into a new document with Inkscape (single style elements).

**Comment by JoergAtGithub** [comment]
Now it looks correct on Windows11 too! Thank you!

**Pull request merged**
