### PR TITLE
Tooltip additions

### PR DESCRIPTION
**Pull request by ronso0**
https://bugs.launchpad.net/mixxx/+bug/1820508
https://bugs.launchpad.net/mixxx/+bug/1753490
https://bugs.launchpad.net/mixxx/+bug/1852830

* `auxiliary_VuMeter` 
* `auxiliary_PeakIndicator`
* `auxiliary_pregain`
* `configure_input` for `+` buttons in unconfigured Mic / Aux decks #1755 
* add new tooltipIds to skins
* move AutoDJ tooltips from dlgautodj.ui to dlgautodj.cpp to ease maintenance
* add fixed keyboard shortcuts for AutoDJ button tooltips (F9 - F12)
* add drag hint to track properties, cover etc.:
`Drag this item to other decks/samplers, to crates and playlist or to external file manager.`
* add drop hint also to Cover Art

For the AutoDJ keyboard shortcuts, this is a quick solution only but sufficient for 2.3 IMO.
Next step -as @daschuer suggested- would be to adopt the skin parser code to look up the actual shortcuts from the keyboard mapping file currently in use. This won't happen here though.

**Reminder**
* add `configure_input` to #1755 after merge

### CODE REVIEW

**Comment by ronso0** [comment]
I'll look what's causing the build errors..

**Review by Holzhaus — APPROVED** [review]
LGTM, thanks!

**Comment by Holzhaus** [comment]
@ronso0 Can I merge this or is something still missing?

**Comment by ronso0** [comment]
yes, this is ready.

**Pull request merged**
