### PR TITLE
EngineBuffer: Add const & order methods

### PR DESCRIPTION
**Pull request by xeruf**
I was really struggling to understand the methods and their interactions, because the methods often seem to be sprinkled in at random order. I tried to at least somewhat improve logical grouping and match the order of declarations and definitions.
Also adds const to all getters.

### CODE REVIEW

**Review by daschuer — DISMISSED** [review]
Such a reorder commit breaks the blame feature. 
I don't see much benefit of such a reorder PR.
Do you actually navigate through a file by scrolling?

**Comment by xerus2000** [comment]
No I of course do not navigate by scrolling, but when I try to understand the relationships of methods, I go back and forth and it is much easier if the functions are close to each other because I can much more easily view them on one screen without using extra effort for splitting. There was so much chaos in that class that made my life unnecessarily hard.
And then there are changes like [this](https://github.com/mixxxdj/mixxx/pull/2997/files#diff-1471563a1888ea358fbf0c0cf5f05ac0L511-R574), which allows you to view both methods side-by-side and actually understand what is going on.

I for one value developer productivity over the git blame feature, which, as I mentioned before, can be configured to skip individual commits if you so choose. Besides, how often do you _really_ use that? I know it can be useful, but compared to the time I spent working in this class the slight inconvenience such a change introduces to using git blame pales in comparison, in my experience.

**Comment by ywwg** [comment]
This seems like minimal reordering, and Blame is overrated (and still accessible if you go back in the past). I'm ok with cleanups like this

**Comment by xerus2000** [comment]
So, we can merge? :)

**Pull request merged**
