### PR TITLE
Incorporate new mapping from bestdani on the forums.  Thanks!

### PR DESCRIPTION
**Pull request by ywwg**
Incorporate new mapping from bestdani on the forums.  Thanks!
http://www.mixxx.org/forums/viewtopic.php?f=7&t=3822&p=26610#p26610

### CODE REVIEW

**Comment by sblaisot** [comment]
No new file => no need to update windows installer.
Wiki page almost empty => I asked on the forum for someone to update the wiki page.

**Comment by Be-ing** [comment]
Whoa there. Why are you doing this for the mapping author? This circumvents the quality control procedures we've been working to develop. Furthermore, the author did not ask to include the mapping in Mixxx, so the legality of this is questionable.

**Comment by ywwg** [comment]
Well if he doesn't give us the goahead we can revert.  But usually if we a new mapping that someone says also works for them, we just merge it, since we don't have a real style guide for javascript.  We can't test the files without the controller, so we sort of have to take people's word for it.  But if things have changed, sorry, we can back this out and do whatever new process you've been doing.

**Comment by Be-ing** [comment]
The process is documented on the wiki (and is still a work in progress as we learn from reviewing more mappings): http://mixxx.org/wiki/doku.php/contributing_mappings

**Comment by Be-ing** [comment]
Reviewing this would be a hassle because the author would not be able to directly commit to the branch you opened this PR for. IMO this PR should be closed and the author can open their own.

**Comment by ywwg** [comment]
ok reverted

**Pull request merged**
