### PR TITLE
Codespell fixes

### PR DESCRIPTION
**Pull request by Holzhaus**
Attempt to solve #10946 by getting rid of the custom codespell wrapper, which not only makes pre-commit hard to use on windows, it's also broken (`pre-commit run codespell --all-files` does not work). Pre-commit failues are expected and should be ignored, because this touches a lot of files.

@JoergAtGithub please check if `pre-commit run codespell --all-files` works when you have this branch checked out.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Now the execution of codespell starts, but it seems codespell itself crashes:
```
PS C:\Users\Joerg.WORLDWARTWEB\source\repos\JoergAtGithub\mixxx> pre-commit run codespell --all-files
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/codespell-project/codespell.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-eslint.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-eslint:eslint@8.12.0.
[INFO] Initializing environment for local.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
[INFO] Initializing environment for https://github.com/shellcheck-py/shellcheck-py.
[INFO] Initializing environment for https://github.com/DavidAnson/markdownlint-cli2.
[INFO] Initializing environment for https://github.com/sirosen/check-jsonschema.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier:prettier@2.7.1.
[INFO] Initializing environment for local:tinycss==0.4.
[INFO] Initializing environment for local:Markdown==3.3.4,beautifulsoup4==4.9.3,lxml==4.6.3.
[INFO] Installing environment for https://github.com/codespell-project/codespell.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
codespell................................................................Failed
- hook id: codespell
- exit code: 1

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\Scripts\codespell.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 748, in _script_main
    return main(*sys.argv[1:])
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 862, in main
    build_exclude_hashes(options.exclude_file, exclude_lines)
  File "C:\Users\Joerg.WORLDWARTWEB\.cache\pre-commit\reporvepfeq7\py_env-python3\lib\site-packages\codespell_lib\_codespell.py", line 444, in build_exclude_hashes
    for line in f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2244: character maps to <undefined>
```

**Comment by Holzhaus** [comment]
Now that really is an upstream issue. We can update the codespell hook in `.pre-commit-config.yaml` to check if the issue is already fixed, but if not we should report it upstream at the codespell repo I guess.

**Comment by JoergAtGithub** [comment]
This was easy to fix: https://github.com/codespell-project/codespell/pull/2520

**Comment by Holzhaus** [comment]
Ah, because Python's `open` uses the system encoding, and Windows localized in German uses CP1251 encoding by default?

**Comment by JoergAtGithub** [comment]
I guess this is the case. I copied this line from another function in this file. This line was the only open statement which didn't specify the encoding.

Regarding this PR, I confirm, that it fixes codespell execution under Windows!

**Comment by JoergAtGithub** [comment]
Codespell 2.2.2 is released, with my bugfix merged: https://github.com/codespell-project/codespell/releases/tag/v2.2.2

**Comment by Holzhaus** [comment]
> Codespell 2.2.2 is released, with my bugfix merged: https://github.com/codespell-project/codespell/releases/tag/v2.2.2

https://github.com/mixxxdj/mixxx/pull/10970

**Comment by Holzhaus** [comment]
The pre-commit issue is expected because the spelling fixes touch a lot of files. Merge?

**Review by daschuer — APPROVED** [review]
Yes, Thank you. 
There are some more findings. But that does not matter.

**Pull request merged**
