### PR TITLE
CI: Trigger automatic update of manual repo if CHANGELOG.md was changed

### PR DESCRIPTION
**Pull request by Holzhaus**
See corresponding PR mixxxdj/manual#422 for details.

This requires a Personal Acess Token (PAT) with the `public_repo` scope
in the repository secrets (named `MANUAL_REPO_TOKEN`).

### CODE REVIEW

**Review by Be-ing — APPROVED** [review]

**Comment by ywwg** [comment]
this is very helpful! thank you

**Comment by ywwg** [comment]
(I don't know yaml so I can't review)

**Comment by Holzhaus** [comment]
Well, this PR is just s github workflow that should trigger another workflow on the manual repo. The other PR contains some python code if you want to review that.

**Comment by uklotzde** [comment]
Can we merge before mixxxdj/manual#422 has been merged?

**Comment by Holzhaus** [comment]
> Can we merge before mixxxdj/manual#422 has been merged?

I don't think it makes sense. Either it makes no difference or it results in a failing check every time we update the changelog.

**Comment by Swiftb0y** [comment]
@Holzhaus I think you messed up a merge or you are targeting the wrong branch...

**Comment by Holzhaus** [comment]
Oops, accidently rebased on main. Fixed.

**Comment by Be-ing** [comment]
Is there anything left to do here?

**Comment by Holzhaus** [comment]
No, but this PR only triggers a workflow run on the manual repo, so the PR on the manual repo should be merged first.

**Pull request merged**
