### PR TITLE
Deere: Fix settings menu sizing

### PR DESCRIPTION
**Pull request by ywwg**
Make fonts px sized.  Fix alignment of checkboxes

### CODE REVIEW

**Comment by ywwg** [comment]
Can people check that this change doesn't break the settings menu for them?  it fixes it for me

**Comment by ferranpujolcamins** [comment]
LGTM, just two things: the menu can be a few pixels thinner.
Maybe you could replace the menu icon for a text like "skin settings", it will help people find out that the menu exists.

**Comment by ywwg** [comment]
well, a hamburger menu (three lines) is fairly standard on mobile but I agree this is going to be a discoverability problem.  None of our other skins do this so it's going to be weird.  Also I suspect it's totally undiscoverable for blind users, though I don't know what skin elements they need to have visible.  I just don't know what the alternative is.

**Comment by ywwg** [comment]
tweaked the button so it doesn't move from under the mouse

**Pull request merged**
