### PR TITLE
Icon update

### PR DESCRIPTION
**Pull request by daschuer**
I have updated some icons to be more significant and not ambigious for future feature enhancements. 
See commits. 
I have also renamed the Library treeview entry to Tracks since all is finally in the library. 

I hope that this will help to avoid the confusion between Library and Browse. 

I would also like to rename the browse feature to something more significant since Browse can be anything. Do you have an idea?

### CODE REVIEW

**Comment by daschuer** [comment]
unfortunately this removes the color transition from the icons. @esbrandt: what is the receipt for the transition?

**Comment by Be-ing** [comment]
LGTM!

These icons should be vectorized. That does not need to be fixed right now. I have opened a [bug](https://bugs.launchpad.net/mixxx/+bug/1656443) to track it.

**Comment by rryan** [comment]
Nice, @daschuer did you draw these by hand? If not, is any of the source material copyright?

**Comment by ferranpujolcamins** [comment]
New name for Browse: what about "HDD", "system folders", or something like
this, that references the fact that you are looking at whats in the
harddrive as is?

**Comment by daschuer** [comment]
The musical note and the computer are from the gnome high contrast theme with LGPL 2.1
The Interface icon is my own work. 
The iTunes and tractor icons are redrawn from original icons found on their websites.

**Comment by Be-ing** [comment]
> New name for Browse: what about "HDD", "system folders", or something like this, that references the fact that you are looking at whats in the harddrive as is?

I think "Files" or "File system" would work better.

**Comment by daschuer** [comment]
> New name for Browse: what about "HDD", "system folders", or something like this, that references the fact that you are looking at whats in the harddrive as is?

"System Folders" sounds nice. Does this cover also implies jump drives?
"HDD" might be to trecky, maybe unroll HDD to "Drives"  
 
Gnome used the term "Places" but hat will probably only be understandable by Linux users. 

Any other votes?

**Comment by daschuer** [comment]
Yes "File system", but that might confuse windows users who are thinking in "Drive Letters".

**Comment by Be-ing** [comment]
> Yes "File system", but that might confuse windows users who are thinking in "Drive Letters".

I'm confused how it would be confusing. How does the feature behave on Windows? I'm guessing it shows the C drive as the root of the file system tree?

**Comment by daschuer** [comment]
On Linux we have 
* Quick links 
* Jump Drives
* / (root folder of file system) 

On windows we have 
* Quick links 
* Devices
** C: 
** D: 

If we agree "File system" is not confusing we can go for it.

**Comment by Be-ing** [comment]
I think "File system" would work for Windows too. It wouldn't be quite as clear, but I think it's the best option proposed so far. Any other opinions?

**Comment by rryan** [comment]
"File system" seems too technical to me, what do you think of:

* File Explorer
* Explorer
* My Computer
* Computer 

"Files" also sounds good to me, and is short and parallel to "Tracks".

**Comment by Be-ing** [comment]
"Computer" is clear and works well with Windows terminology.

**Comment by Be-ing** [comment]
> The musical note and the computer are from the gnome high contrast theme with LGPL 2.1

This should be acknowledged somewhere.

**Comment by Be-ing** [comment]
Rename `res/images/library/ic_library_library.png` to `res/images/library/ic_library_tracks.png`. Also rename the browse icon file for whatever new name we decide.

**Comment by daschuer** [comment]
Windows 7 uses "Computer" Windows 10 uses "This PC" Mac OS, just "MAC", Linux has the "Computer://" place where the Icon is taken from. 
How about just hit the Middle of windows 10 and 7: "This Computer" since this computer is a MAC on a MAC, it fits also there ;-)

**Comment by daschuer** [comment]
OK, now we have "This Computer" and polished icons with color gradients. 

One day, we should rename the C++ classes as well, but I like to postpone this to avoid conflicts and hard to track diffs, when merging the the new library layout.

**Comment by Be-ing** [comment]
> How about just hit the Middle of windows 10 and 7

IMO "This Computer" feels kinda weird because it is a middle ground that no other system uses exactly. I think just "Computer" works better.

**Comment by rryan** [comment]
:+1: to "Computer" as well

**Comment by Be-ing** [comment]
Can we distribute LGPL icons in the Mac App Store? I think the copyright should be acknowledged in the LICENSE file. It has been a long time since I read the LGPL 2.1. Do we need to distribute the full text of that license?

**Comment by timrae** [comment]
@daschuer 
Do have svg's for all of these icons? If you already have them it definitely make sense to add them to the source tree now, rather than hunting for them later.

**Comment by daschuer** [comment]
Sorry, no. That was just pixel shifting in Gimp

**Comment by daschuer** [comment]
LGPL should be no problem for Apple. I have just found that: 
https://forums.developer.apple.com/thread/27709
I think if this would be not allowed, we have a problem with the whole Qt library under LGPL

**Comment by ferranpujolcamins** [comment]
+1 to computer :)

On 15 Jan 2017 9:45 a.m., "Daniel Schürmann" <notifications@github.com>
wrote:

LGPL should be no problem for Apple. I have just found that:
https://forums.developer.apple.com/thread/27709
I think if this would be not allowed, we have a problem with the whole Qt
library under LGPL

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mixxxdj/mixxx/pull/1119#issuecomment-272681930>, or mute
the thread

**Comment by esbrandt** [comment]
> unfortunately this removes the color transition from the icons. @esbrandt: what is the receipt for the transition?

@daschuer 
sorry for being late. Moved recently and RL happened.
The icon templates are as always in https://github.com/mixxxdj/mixxx/blob/master/res/images/templates/ic_template_library_and_preferences.svg

Multi layered inkscape template, incl. filter settings for the overlays used. If the icons change , i´d love to see the template updated as well.

**Comment by daschuer** [comment]
Sorry, for now I have no svg versions of the new icons so I cannot update ic_template_library_and_preferences.svg

**Comment by daschuer** [comment]
I think we can merge now. Icon tweaking towards svg can be done in a separate PR.

**Pull request merged**
