### PR TITLE
Use std math functions and remove fpclassify.h hack

### PR DESCRIPTION
**Pull request by Holzhaus**
Let's see if this works. Only targeted at 2.3 because I wanted to upgrade GoogleTest to latest HEAD to get rid of the annoying CMake warning, but newer versions are incompatible with out fpclassify hack.

Due to the possible implications, we probably shouldn't merge this to 2.3 to close to a release. I can rebase on main if you agree.

### CODE REVIEW

**Comment by uklotzde** [comment]
This change may cause unnoticed bugs and is not suitable for inclusion in 2.3.

**Comment by Holzhaus** [comment]
> This change may cause unnoticed bugs and is not suitable for inclusion in 2.3.

Yes, that's why it's marked as draft and not added to the 2.3 milestone. I think the compiler version is too old on Ubuntu 18.04:
```
Note: Google Test filter = MathUtilTest.IsInf
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from MathUtilTest
[ RUN      ] MathUtilTest.IsInf
/home/runner/work/mixxx/mixxx/src/test/mathutiltest.cpp:54: Failure
Value of: std::isinf(std::numeric_limits<float>::infinity())
  Actual: false
Expected: true
/home/runner/work/mixxx/mixxx/src/test/mathutiltest.cpp:58: Failure
Value of: std::isinf(std::numeric_limits<double>::infinity())
  Actual: false
Expected: true
```

On main, it should work (no failure on Ubuntu 20.04, and Ubuntu 18.04 support is dropped anyway).

I just wanted to check if it builds on all target systems before rebasing.

**Comment by uklotzde** [comment]
We should consider to add an aarch64 build for 2.4.0.

There are already unresolved issues with floating-point operations on ARM: https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/ARM.20test.20failures

**Comment by uklotzde** [comment]
A bug report was missing: https://bugs.launchpad.net/mixxx/+bug/1929309

**Comment by uklotzde** [comment]
We need to split this into 2 tasks:
- Include `<cmath> and use math functions from `std::` for all regular calculations
- Provide non-fast-math versions to check for special values in fpclassify.h/.cpp, probably by encapsulating them in a namespace `mixxx::fp` or `mixxx::math`

**Comment by uklotzde** [comment]
@Holzhaus I'll give it a try to get rid of the #defines. This refactoring is safe for 2.3.

**Comment by Holzhaus** [comment]
Just some free functions in `mixxx::math` namespace should be fine.

**Comment by uklotzde** [comment]
I'll keep the `util_` prefix to minimize the changes.

**Comment by uklotzde** [comment]
Closing in favor of #3903.

**Pull request closed without merging**
