### PR TITLE
Rigtorp SPSCQueue

### PR DESCRIPTION
**Pull request by uklotzde**
- Header-only library/file
- Replace our custom, hand-written MpscFifo with a battle-tested, lock-free SPSC queue
- Use SPSCQueue instead of PortAudio ring buffer and fix a memory leak in StatsManager

The compiler warning about an unsupported C++17 feature can be ignored. If the memory is not aligned with the cache lines this only affects performance, which doesn't matter here.

### CODE REVIEW

**Comment by Be-ing** [comment]
What are the advantages of this over our existing implementation? Just that it is more widely tested? Are there specific problems that this PR is fixing?

**Comment by uklotzde** [comment]
The PortAudio ring buffer only supports POD data types and requires manual memory management. This works for audio data, but is cumbersome for C++ data types. It already causes a memory leak in the StatsManager. The effects manager is another candidate for the migration. I haven't checked the details, but I remember some compiler warnings.

I'm also not able to guarantee that my initial implementation was correct. We can get rid of this code and the corresponding tests.

**Review by daschuer — COMMENTED** [review]
Wow, that's a perfect queue.

I have added some comments, almost all to legacy code, you copied around. It would be nice to have this improved, but I don't mind if not.

**Comment by uklotzde** [comment]
The API of the queue could be improved slightly for this use case:
https://github.com/rigtorp/SPSCQueue/pull/11
But I didn't want to insist on it and we don't need maximum performance here.

In the comments of this PR you also find a link with my approach for an SCSP queue in Rust. Didn't get any feedback so far.

**Comment by uklotzde** [comment]
I intentionally didn't modify the existing implementation and only update the comments, function, or parameter names.

The symmetric design doesn't fit the use case very well. The communication paths into and out of the real-time thread require different lock-free queues or data structures depending on the direction: https://www.youtube.com/watch?v=-F7whGjquHI&feature=youtu.be&t=3496

**Comment by daschuer** [comment]
Does it mean we can merge this as it is?

**Comment by uklotzde** [comment]
Yes. I'm not planning any changes on the remaining code. I just wanted to get rid of our custom implementation and replace Pa_RingBuffer with a safer and more C++-ish solution where appropriate.

**Comment by daschuer** [comment]
Ok, than you.

**Pull request merged**
