### PR TITLE
remove legacy Simple and HSV waveform renderers

### PR DESCRIPTION
**Pull request by Be-ing**
There is no point maintaining these considering the RGB and Filtered renderers are more useful and look better.

As discussed on [Zulip](https://mixxx.zulipchat.com/#narrow/stream/109122-general/topic/legacy.20waveform.20renderers)

I started working on the QOpenGLWidget migration but I will not maintain these.

### CODE REVIEW

**Review by uklotzde — APPROVED** [review]

**Review by daschuer — CHANGES_REQUESTED** [review]
I think we can't remove simple. Waveform writing is a major CPU drain and we have users using Mixxx on a Raspberry Pie or such where this might be the the only one one that works in combination with a low audio buffer. 
It looks like as if in this video the simple waveform is used: 
https://www.youtube.com/watch?v=UZam2aeX3Nc

**Comment by Be-ing** [comment]
We still have the RGB and Filtered CPU rendered waveforms.

**Comment by Be-ing** [comment]
@fayaaz has reported OpenGL waveforms now work on Raspberry Pi.

**Comment by daschuer** [comment]
The qtsimplewaveformwidget is the one running on EGL. I think this is used on Such devices.

**Comment by Be-ing** [comment]
The CPU Simple waveform renderer was never implemented. This PR removes TODOs regarding it.

**Comment by Be-ing** [comment]
If we really need something back for a technical reason, it is there in the Git history and can be updated.

**Comment by Be-ing** [comment]
> @fayaaz has reported OpenGL waveforms now work on Raspberry Pi.

"OpenGL waveforms seem to work on 64 bit raspbian."
https://mixxx.discourse.group/t/raspberry-pi-4-opengl-waveform/20206/4

**Comment by daschuer** [comment]
This will not be possible if it is not maintained with QOpenGLWidget.

The Qt Simple is EGL rendered and GL Simple is GL rendered. 
We should keep both to have simple alternatives even during debugging the new API. 
We can compare rendering speed and might find bottle necks.

**Comment by daschuer** [comment]
The Rasbery Py uses the "OpenGL ES" waveforms.

**Comment by Be-ing** [comment]
The RGB and Filtered also have Qt GL ES options so why do we need Simple?

**Comment by daschuer** [comment]
Because it uses 3 x less CPU.

**Comment by daschuer** [comment]
Why it is used in the Video ...

**Comment by Be-ing** [comment]
And how would anyone know that? Where is that documented? I have 5 years using Mixxx, helping users set up Mixxx, and spent days with this code and there are zero hints about that. Has anyone switched to the Simple waveform renderer for that reason?

> Why it is used in the Video ...

I don't know. So what? We know OpenGL waveforms work on Raspberry Pis.

**Comment by Be-ing** [comment]
AFAIK the performance issues with waveforms are not the OpenGL rendering code. They are using the deprecated QGLWidget API and how the waveform rendering interacts with the rest of the application. Keeping an ugly legacy renderer just because of some hypothetically relevant performance difference that nobody knows about seems like a silly impediment to moving forward IMO.

**Comment by Be-ing** [comment]
I have already built commits on top of this. I really do not want to rebase them and fix conflicts for some hypothetical issue that no one knows about.

**Comment by uklotzde** [comment]
> AFAIK the performance issues with waveforms are not the OpenGL rendering code. They are using the deprecated QGLWidget API and how the waveform rendering interacts with the rest of the application. Keeping an ugly legacy renderer just because of some hypothetically relevant performance difference that nobody knows about seems like a silly impediment to moving forward IMO.

I totally agree. Keeping everything that ever existed for some (historical) reason will prevent us to move on. This does not only apply to software development. Everyone who does not want a rewrite should support this. Otherwise we will drown in legacy code during the migration to QML. We need to make some deep cuts. Maybe afterwards performance is even better than before?

**Comment by daschuer** [comment]
> I don't know. So what? We know OpenGL waveforms work on Raspberry Pis.

No it does not. Raspberry Pi has OpenGL ES, the OpenGL types do not work.

> And how would anyone know that? Where is that documented?

Only waveforms that can be shown are populating the combobox. 
See: WaveformWidgetFactory::evaluateWidgets 

> Keeping an ugly legacy renderer just because of some hypothetically relevant performance difference that nobody knows about seems like a silly impediment to moving forward IMO.

> I totally agree. Keeping everything that ever existed for some (historical) reason will prevent us to move on. This does not only apply to software development. Everyone who does not want a rewrite should support this decision. Otherwise we will drown in legacy code during the migration to QML. We need to make some deep cuts. Maybe afterwards performance is even better than before?

@uklotzde: You missed my point here:
We need maintain a set of waveform for different use cases. The low CPU OpenGL ES case is clearly one of it.
This will not be a legacy type that prevents development. It can be a stripped down type of the RGB without RGB for instance.

**Comment by Be-ing** [comment]
https://xkcd.com/1172/

**Comment by daschuer** [comment]
During your QOpenGLWidget update you will refactor all waveforms, to a new technology base.
This should serve all use case we know as valid.
Having a simple waveform that drews a minimum CPU is one of them. This has nothing to do with https://xkcd.com/1172/

**Comment by uklotzde** [comment]
> During your QOpenGLWidget update you will refactor all waveforms, to a new technology base.
> This should serve all use case we know as valid.
> Having a simple waveform that drews a minimum CPU is one of them. This has nothing to do with https://xkcd.com/1172/

Are you really insisting to migrate all of the existing variants at once? I would prefer to start with a small but working subset. The xkcd reference fits very well here, it applies to both bugs and features.

**Comment by Be-ing** [comment]
Here is the cost of maintenance:
image
image

Not everybody has a development machine with 16 GB of RAM and they shouldn't need that to contribute to Mixxx.

**Comment by Be-ing** [comment]
I do care about making Mixxx usable on cheap low powered hardware, but clinging to legacy code over hypothetically relevant concerns will hold us back from developing a new GUI that really performs well on such hardware using modern technologies like QML.

**Comment by daschuer** [comment]
> Are you really insisting to migrate all of the existing variants at once?

Not necessarily. The issue is that we can't have QOpenGl waveforms and QGl waveforms at the same time.

So a reasonable way forward would be to keep main working with QGl and migrate one waveform to QOpenGl in an extra branch. Once this is working, we can lift all waveforms to OpenGl and merge. This schould be fairly easy, because I assume that the I thermal render code an all resizing and such will remain untouched. 

This means here we can consolidated the number of waveforms for QGl, and do this again once we have one working QOpenGl type.

Running Mixxx on low power hardware is one of our unique selling point. No need to drop this here in main.

**Comment by Be-ing** [comment]
> So a reasonable way forward would be to keep main working with QGl and migrate one waveform to QOpenGl in an extra branch. Once this is working, we can lift all waveforms to OpenGl and merge.

Yes, that's exactly what I'm doing here. I just did some cleanup of unnecessary code first to make it easier.

**Comment by daschuer** [comment]
I think the main issue here is that you are trying to move step by step in main. This will not work in this case, because it may break main for other PRs.

How about create a new branch and make small PRs to this.
That would allow you to remove all waveforms except the Vsync type. 
Once this works smooth. We can adopt the changes to main, or reintegrate the renderers we think we have a use case for into it.

**Comment by Be-ing** [comment]
Moving step by step in main is the best way to do large projects unless we want every new feature PR to become as big as #2618 (in that case it was necessary to break major functionality to do the refactoring so it couldn't be merged in small steps).

Ping @ywwg

**Comment by Be-ing** [comment]
My first goal right now is to get a small branch on top of main building with Qt 6 so we can evaluate what work needs to be done, if any, besides the QOpenGLWidget migration.

**Comment by Be-ing** [comment]
Not once have I noticed a real world performance difference between Simple or RGB renderers within a category, not on a 2011 Macbook Air nor an even older netbook with an Intel Atom CPU. What does matter is the differences between categories (desktop OpenGL, OpenGL ES, CPU).

**Comment by ywwg** [comment]
> Moving step by step in main is the best way to do large projects unless we want every new feature PR to become as big as #2618 (in that case it was necessary to break major functionality to do the refactoring so it couldn't be merged in small steps).

I do agree that we need better ways to make gradual changes to mixxx and reduce PR size.  Why can't we support QGL and QOpenGl widgets at the same time?

**Comment by ywwg** [comment]
Maintaining support for old/slow hardware is a primary mission for Mixxx.  Having a dead-simple waveform has been important for compatibility and speed, and I think we should maintain one.  What if we just drop HSV? That doesn't seem to have a lot of fans.

**Comment by ywwg** [comment]
@Be-ing , can you be specific about the maintenance burden of not removing these renderers? I don't quite understand the screenshots.  What is the per-waveform migration like?  More than just renaming the GL Widget name I assume? :)

**Comment by Be-ing** [comment]
> Why can't we support QGL and QOpenGl widgets at the same time?

QOpenGLWidget doesn't let us control when the framebuffer is swapped to the screen so it's incompatible with how waveform rendering is done currently. It's not a simple matter of finding and replacing `QGL` with `QOpenGL`; the APIs have completely different requirements for our use case. However, I'm now doubting that it's even worth the effort to migrate to QOpenGLWidget instead of QML.

**Comment by Be-ing** [comment]
This has developed merge conflicts with the recent mass refactorings and it seems the entire waveform system may need to be rewritten from scratch anyway, so I'm currently not going to bother discussing what should or shouldn't be removed and just close this PR.

**Pull request closed without merging**
