### PR TITLE
Don't reset xfader when auto DJ is disabled

### PR DESCRIPTION
**Pull request by daschuer**
This fixes #10683

### CODE REVIEW

**Comment by ronso0** [comment]
As I stated in the original bug [lp:1965298](https://bugs.launchpad.net/mixxx/+bug/1965298) I disagree with the rationale of the PR which introduced this behaviour #313 (I just never noticed since I don't use AutoDJ)

**TLDR;**
Let's remove the crossfader auto-centering completely.

> Using automation when turning AutoDJ OFF to work around forgetting to check a central, obvious DJ control is not appropriate IMO. If that was about some rather inaccessible effect toggle or something, okay, but it's the crossfader :| And it's even more obvious since it's been moved by AutoDJ all the time.

> we should remove such magic and leave the crossfader where it is, no matter if it's the last queued song or if AutoDJ is stopped manually.

> You're right about not introducing changes for unaffected users in a stable release, that should be avoided if possible. However, I'd appreciate a consistent fix. Though, making the crossfader behaviour depend on the selected xfader mode is confusing IMO.

**Comment by daschuer** [comment]
I agree for 2.4 to remove the behaviour completely. 

When you think we can effort to break the existing reset feature in the stable release has well, I will change this PR accordingly. For now I think this PR is the least controversial version.

What do you think?

**Comment by ronso0** [comment]
> When you think we can effort to break the existing reset feature in the stable release has well

If we want to fix the volume bug **and** agree that consistent, predictable behaviour is crucial there is no other choice than removing auto-centering now.

Also, I _think_ for AutoDJ users it doesn't matter if we change the behaviour in a minor or in a major update. Let's keep in mind that Mixxx is primarily designed for manual DJing and AutoDJ is a supplementary feature. Even though there are appearantly many AutoDJ-only users, I doubt they mix its crossfader mixing with manual volume fader mixing, and if so resetting the crossfader is just a right-click away.

**Comment by ronso0** [comment]
What do other @mixxxdj/developers think?

When AutoDJ runs out (auto-off after fading to last queued track) should we
* center the crossfader only with crossfader's `mixing mode` to avoid the volume reduction
* remove auto-centering entirely

?

**Comment by Swiftb0y** [comment]
> Also, I think for AutoDJ users it doesn't matter if we change the behaviour in a minor or in a major update. Let's keep in mind that Mixxx is primarily designed for manual DJing and AutoDJ is a supplementary feature. Even though there are appearantly many AutoDJ-only users, I doubt they mix its crossfader mixing with manual volume fader mixing, and if so resetting the crossfader is just a right-click away.

see https://www.hyrumslaw.com/. I still think we should change the behavior, but we need to make it clear enough in the changelog.

> remove auto-centering entirely

I favor this. AutoDJ is already full of magic, making it seemingly unpredictable (and thus the reason I still don't trust it in live situations), so removing one more undocumented behavior is a good idea!

**Comment by daschuer** [comment]
OK, I have removed the xfader reset unconditionally.

**Review by ronso0 — APPROVED** [review]

**Comment by ronso0** [comment]
Thank you, LGTM

**Comment by ronso0** [comment]
I also did a manual test of this one-line change. Works as intended : )

**Pull request merged**
