### PR TITLE
Internationalization maintance

### PR DESCRIPTION
**Pull request by daschuer**
This adds new languages, removes redundant languages and languages with only a few strings translated < 1 % 

This also fixes: https://bugs.launchpad.net/mixxx/+bug/1837663

This webside was helpfull for a quick reference of language codes: 
https://www.localeplanet.com/icu/iso639.html

### CODE REVIEW

**Comment by uklotzde** [comment]
- How do we prevent the removed translations from re-appearing when pulling translations from Transifex?
- Is the process for updating translations affected and does it need to be updated?

Please provide more context. The standalone PR is not reviewable without this information.

**Comment by daschuer** [comment]
See: https://github.com/mixxxdj/mixxx/wiki/Internationalization

**Comment by uklotzde** [comment]
> See: https://github.com/mixxxdj/mixxx/wiki/Internationalization

Doesn't the `--minimum-perc` option exclude all languages below the given threshold, both existing and new ones?

Should we remove the `-f` option? It is not mentioned why it is needed and the docs of `tx` also don't explain it properly.

**Comment by daschuer** [comment]
> Doesn't the --minimum-perc option exclude all languages below the given threshold, both existing and new ones?

Yes, it does.

The -f option is described here:
https://docs.transifex.com/client/pull

It ensures that local changes are discarded.

**Comment by daschuer** [comment]
I have added the -f and --minimum-perc flags to the wiki description

**Review by uklotzde — APPROVED** [review]
Thanks for amending the documentation! LGTM

**Pull request merged**
