### PR TITLE
Library AutoDJ cleanup

### PR DESCRIPTION
**Pull request by Holzhaus**
This cleans up the library<->AutoDJ interaction a bit (consistent naming/spelling for context menu entries and variables, removes a duplicated function in `PlaylistDAO`). Also, this adds "Add to AutoDJ queue (replace)" context menu entries to `BasePlaylistFeature` and `BaseExternalLibraryFeature` (previously you could only add to top/bottom).

### CODE REVIEW

**Comment by Holzhaus** [comment]
The Appveyor build timed out.

**Comment by uklotzde** [comment]
Merge conflict resolution: https://github.com/uklotzde/mixxx/tree/library-autodj-fixes

**Comment by uklotzde** [comment]
Otherwise LGTM :+1:

**Comment by uklotzde** [comment]
LGTM and now mergeable.

**Pull request merged**
