### PR TITLE
Reloop Beatpad mapping files for Mixxx 1.12

### PR DESCRIPTION
**Pull request by DJChloe**
Haaaaaaaaaaaa finally I got it !!!!
Here is my pull request in order to include my mapping file (reloop Beatpad/Mixxx 1.12)

### CODE REVIEW

**Comment by Be-ing** [comment]
Please rename the XML file to "Reloop Beatpad.midi.xml".

**Comment by DJChloe** [comment]
But if i remember well it is the way Mixxx detects the reloop beatpad. If I
change the file name, Mixxx does not longer do the association between the
controller and the file. I have to check that tomorrow. :)

**Comment by Be-ing** [comment]
I don't think the file name matters for Mixxx detecting the file as a mapping as long as it ends in .midi.xml

**Comment by DJChloe** [comment]
It has to do with the internal name of the USB device if I remember well.
The internal USB string for the reloop beatpad 2 should be
"Reloop_Beatpad_MIDI_2".
Web Mixxx detects a new usb hid device, it automatically creates a
minimalist ready to be filled up for mapping xml file in the user
controller directory. On account of that I have a file for my Bluetooth
headset and also my wireless keyboard (for hid mappings).

**Comment by Be-ing** [comment]
Yeah, Mixxx automatically creates those files. It helps to have the files for mappings that are shipped with Mixxx named differently to make it clear that they are mappings that came with Mixxx rather than the user's mapping.

**Comment by illuusio** [comment]
Javascript have these issues:
res/controllers/Reloop-Beatpad-scripts.js: line 25, col 17, Weird construction. Is 'new' necessary?
res/controllers/Reloop-Beatpad-scripts.js: line 25, col 34, Missing '()' invoking a constructor.
res/controllers/Reloop-Beatpad-scripts.js: line 27, col 1, 'const' is available in ES6 (use esnext option) or Mozilla JS extensions (use moz).
res/controllers/Reloop-Beatpad-scripts.js: line 35, col 23, Expected an assignment or function call and instead saw an expression.
res/controllers/Reloop-Beatpad-scripts.js: line 224, col 32, ['SamplerPad1'] is better written in dot notation.
res/controllers/Reloop-Beatpad-scripts.js: line 225, col 32, ['SamplerPad2'] is better written in dot notation.
res/controllers/Reloop-Beatpad-scripts.js: line 226, col 32, ['SamplerPad3'] is better written in dot notation.
res/controllers/Reloop-Beatpad-scripts.js: line 228, col 32, ['SamplerPad4'] is better written in dot notation.
res/controllers/Reloop-Beatpad-scripts.js: line 462, col 18, Use '!==' to compare with '0'.
res/controllers/Reloop-Beatpad-scripts.js: line 488, col 41, Use '!==' to compare with '0'.
res/controllers/Reloop-Beatpad-scripts.js: line 551, col 63, Expected an assignment or function call and instead saw an expression.
res/controllers/Reloop-Beatpad-scripts.js: line 871, col 28, ['show5'] is better written in dot notation.
res/controllers/Reloop-Beatpad-scripts.js: line 872, col 28, ['show6'] is better written in dot notation.
res/controllers/Reloop-Beatpad-scripts.js: line 878, col 28, ['show5'] is better written in dot notation.
res/controllers/Reloop-Beatpad-scripts.js: line 879, col 28, ['show6'] is better written in dot notation.
res/controllers/Reloop-Beatpad-scripts.js: line 891, col 20, ['show5'] is better written in dot notation.
res/controllers/Reloop-Beatpad-scripts.js: line 900, col 35, ['show5'] is better written in dot notation.
res/controllers/Reloop-Beatpad-scripts.js: line 901, col 26, ['show5'] is better written in dot notation.
res/controllers/Reloop-Beatpad-scripts.js: line 911, col 20, ['show5'] is better written in dot notation.
res/controllers/Reloop-Beatpad-scripts.js: line 916, col 20, ['show5'] is better written in dot notation.
res/controllers/Reloop-Beatpad-scripts.js: line 942, col 44, Use '!==' to compare with '0'.
res/controllers/Reloop-Beatpad-scripts.js: line 964, col 28, Use '!==' to compare with '0'.
res/controllers/Reloop-Beatpad-scripts.js: line 970, col 28, Use '!==' to compare with '0'.
res/controllers/Reloop-Beatpad-scripts.js: line 971, col 28, Use '!==' to compare with '0'.
res/controllers/Reloop-Beatpad-scripts.js: line 1016, col 5, Don't use 'with'.
res/controllers/Reloop-Beatpad-scripts.js: line 1192, col 164, Missing semicolon.
res/controllers/Reloop-Beatpad-scripts.js: line 1193, col 164, Missing semicolon.
res/controllers/Reloop-Beatpad-scripts.js: line 1194, col 164, Missing semicolon.
res/controllers/Reloop-Beatpad-scripts.js: line 1661, col 35, Use '===' to compare with '0'.
res/controllers/Reloop-Beatpad-scripts.js: line 1684, col 35, Use '===' to compare with '0'.
res/controllers/Reloop-Beatpad-scripts.js: line 1851, col 39, Use '===' to compare with '0'.
res/controllers/Reloop-Beatpad-scripts.js: line 1885, col 14, Use '===' to compare with '0'.
res/controllers/Reloop-Beatpad-scripts.js: line 1939, col 37, Use '!==' to compare with '0'.
res/controllers/Reloop-Beatpad-scripts.js: line 2016, col 28, Use '!==' to compare with '0'.
res/controllers/Reloop-Beatpad-scripts.js: line 2020, col 33, Use '===' to compare with '0'.
res/controllers/Reloop-Beatpad-scripts.js: line 2032, col 54, Use '!==' to compare with '0'.

**Comment by illuusio** [comment]
XML indentation is also incorrect and again Mixxx is messing XML header that is have '1.0' not "1.0". If this is straight from Mixxx then it should be issued.

**Comment by illuusio** [comment]
Add header and Mixxx is trying to get from having GPLv2 header in every file so see 'Vestax-VCI-300-scripts.js' for example what kind of information there should be.
<pre>
////////////////////////////////////////////////////////////////////////
// JSHint configuration                                               //
////////////////////////////////////////////////////////////////////////
/* global engine                                                      */
/* global script                                                      */
/* global print                                                       */
/* global midi                                                        */
////////////////////////////////////////////////////////////////////////
</pre>

**Comment by DJChloe** [comment]
Le 21 oct. 2015 07:19, "Tuukka Pasanen" <notifications@github.com> a écrit :
Your js validator is an automatic validator, and excep two bugs (nice !),
it throws irrevelant warnings used only in js strict.
Use this js validator instead, more pertinent :
http://www.javascriptlint.com/online_lint.php

> Javascript have these issues:
> res/controllers/Reloop-Beatpad-scripts.js: line 25, col 17, Weird
> construction. Is 'new' necessary?
>
Yes it is !
It is a function object, not a declared function (Declared functions are
not executed immediately. ). It is supposed to receive objects with
constructors that need to be executed immediatly for initialisation. As an
executed block, it terminates with a semi-column ";"
It uses the same constructio than the midi script for Kane Quneo

> res/controllers/Reloop-Beatpad-scripts.js: line 25, col 34, Missing '()'
> invoking a constructor.
>
Nope with the previous valid construction it is valid

> res/controllers/Reloop-Beatpad-scripts.js: line 27, col 1, 'const' is
> available in ES6 (use esnext option) or Mozilla JS extensions (use moz).
> res/controllers/Reloop-Beatpad-scripts.js: line 35, col 23, Expected an
> assignment or function call and instead saw an expression.
> res/controllers/Reloop-Beatpad-scripts.js: line 224, col 32,
> ['SamplerPad1'] is better written in dot notation.
> res/controllers/Reloop-Beatpad-scripts.js: line 225, col 32,
> ['SamplerPad2'] is better written in dot notation.
> res/controllers/Reloop-Beatpad-scripts.js: line 226, col 32,
> ['SamplerPad3'] is better written in dot notation.
> res/controllers/Reloop-Beatpad-scripts.js: line 228, col 32,
> ['SamplerPad4'] is better written in dot notation.
>
this is just a point of view and does not garantee performance increase. It
is just "cosmetic" . More over for readability and consistence, since 2
lines later I have a ["SamplerPad"+i], I prefer to keep it like that
everywher I have a suffix number in my naming.

> res/controllers/Reloop-Beatpad-scripts.js: line 462, col 18, Use '!==' to
> compare with '0'.
> res/controllers/Reloop-Beatpad-scripts.js: line 488, col 41, Use '!==' to
> compare with '0'.
>
We compare  number against number, it is not aproblem.; the value compared
to the 0 is "provided" by the Mixxx engine and is supposedto be always a
number. We are not writing a library to be used as a framework for web
sites !!!

> res/controllers/Reloop-Beatpad-scripts.js: line 551, col 63, Expected an
> assignment or function call and instead saw an expression.
>
it is a ternary if, but anyway the classic if/else is better, I agree

> res/controllers/Reloop-Beatpad-scripts.js: line 871, col 28, ['show5'] is
> better written in dot notation.
> res/controllers/Reloop-Beatpad-scripts.js: line 872, col 28, ['show6'] is
> better written in dot notation.
> res/controllers/Reloop-Beatpad-scripts.js: line 878, col 28, ['show5'] is
> better written in dot notation.
> res/controllers/Reloop-Beatpad-scripts.js: line 879, col 28, ['show6'] is
> better written in dot notation.
> res/controllers/Reloop-Beatpad-scripts.js: line 891, col 20, ['show5'] is
> better written in dot notation.
> res/controllers/Reloop-Beatpad-scripts.js: line 900, col 35, ['show5'] is
> better written in dot notation.
> res/controllers/Reloop-Beatpad-scripts.js: line 901, col 26, ['show5'] is
> better written in dot notation.
> res/controllers/Reloop-Beatpad-scripts.js: line 911, col 20, ['show5'] is
> better written in dot notation.
> res/controllers/Reloop-Beatpad-scripts.js: line 916, col 20, ['show5'] is
> better written in dot notation.
>
nope (suffif number, see above

> res/controllers/Reloop-Beatpad-scripts.js: line 942, col 44, Use '!==' to
> compare with '0'.
> res/controllers/Reloop-Beatpad-scripts.js: line 964, col 28, Use '!==' to
> compare with '0'.
> res/controllers/Reloop-Beatpad-scripts.js: line 970, col 28, Use '!==' to
> compare with '0'.
> res/controllers/Reloop-Beatpad-scripts.js: line 971, col 28, Use '!==' to
> compare with '0'.
> res/controllers/Reloop-Beatpad-scripts.js: line 1016, col 5, Don't use
> 'with'.
>


> res/controllers/Reloop-Beatpad-scripts.js: line 1192, col 164, Missing
> semicolon.
> res/controllers/Reloop-Beatpad-scripts.js: line 1193, col 164, Missing
> semicolon.
> res/controllers/Reloop-Beatpad-scripts.js: line 1194, col 164, Missing
> semicolon.
>
Yes for those 3 ! My 2 cents !

> res/controllers/Reloop-Beatpad-scripts.js: line 1661, col 35, Use '===' to
> compare with '0'.
> res/controllers/Reloop-Beatpad-scripts.js: line 1684, col 35, Use '===' to
> compare with '0'.
> res/controllers/Reloop-Beatpad-scripts.js: line 1851, col 39, Use '===' to
> compare with '0'.
> res/controllers/Reloop-Beatpad-scripts.js: line 1885, col 14, Use '===' to
> compare with '0'.
> res/controllers/Reloop-Beatpad-scripts.js: line 1939, col 37, Use '!==' to
> compare with '0'.
> res/controllers/Reloop-Beatpad-scripts.js: line 2016, col 28, Use '!==' to
> compare with '0'.
> res/controllers/Reloop-Beatpad-scripts.js: line 2020, col 33, Use '===' to
> compare with '0'.
> res/controllers/Reloop-Beatpad-scripts.js: line 2032, col 54, Use '!==' to
> compare with '0'.
>

Your js validator missed like me the brackets line 1744 and 1746 and 1748
!!!

**Comment by DJChloe** [comment]
Le 21 oct. 2015 07:25, "Tuukka Pasanen" <notifications@github.com> a écrit :

> XML indentation is also incorrect and again Mixxx is messing XML header
> that is have '1.0' not "1.0". If this is straight from Mixxx then it should
> be issued.
>
It is a Mixxx issue, for the header, and for the indentation.

**Comment by DJChloe** [comment]
There is no GPL v2 header in the script you indicate as an example.
However, my script starts with the GPL v2 licence text :
https://www.gnu.org/licenses/gpl-2.0.html#SEC4

2015-10-21 7:30 GMT+02:00 Tuukka Pasanen <notifications@github.com>:

**Comment by illuusio** [comment]
Because it doesn't generate warnings about bad ways of coding it's better. Ok i'll run it against it. In Javascript it is not answer to say: Program always delivers numbers. Does it make your javascript worse to check that and it's better habit to use '!==' and '===' in Javascript?

**Comment by DJChloe** [comment]
I made a correction to all the !=0 and ==0 comparison making them !== and ===. I took it in consideration don't worry :)
The problem is that if one day a null value is passed to the function by the Mixxx engine, it will stuck/freeze/bug the mapping and the controller will not be usable.
I just said that Mixxx was supposed to deliver some numbers.
Keeping the eventual casting alive permits to live without that Damocles's sword.
Javascript is flexible for this and it is not very smart to restrict it just for the sake of a suposedly "nice coding".
The only reason to use !== 0 and === 0 is for performance (avoiding casting).
The reason of to use !=0 and =0, is to keep possible casting when you cannot rely on the value provided from outside of your script.

**Comment by illuusio** [comment]
About that new thing.. you shouldn't need to use new in that. In Javascript it should work without new (If Qt Javascript ain't some kind of weirdo) please note: http://stackoverflow.com/questions/8455598/javascript-weird-construction-in-simple-object.
Writing ['something'] or .something is not about religion.. it's just how it's made in Mixxx. Don't worry I'm all in thumbs up this stuff and want every Pad and controller to be supported in Mixxx but minus is that I like good looking/behaving code. Most of the stuff what are 'fixed' in code review are code beatifying and applying good practises. Most bad thing about Javascript is it doesn't have compilers and Firefox, Chrome and fellows are too loysy about bad habits.
If Mixxx delivers NULL then we are in deep piss and that bug should be fixed.
But I'll run jsl (https://www.npmjs.com/package/jsl) linter against this and let us see because it's the linter that your web page used.

**Comment by DJChloe** [comment]
About that new thing.. you shouldn't need to use new in that. In Javascript it should work without new (If Qt Javascript ain't some kind of weirdo) please note: http://stackoverflow.com/questions/8455598/javascript-weird-construction-in-simple-object.

---> Did you read it ?
I quote : "the purpose of defining a constructor is to be able to reuse it to create many objects."
And that is exactly what I do

I can eventually rewrite this part of code like this
ReloopBeatpad = new function () {
	this.decks = [];
	this.playlist = [];
	this.master = [];
	this.recording = [];
};

in  those array, some huge object are created.
If you don't use the "new", the js interpreter of mixxx do not find the main controller function.
Remove the "new" is a bug, and make it a declared function instead of a function object means a total rewrite of the mapping, of the Kane Quneo mapping, of the Numark DJ2go mapping and some others.
I have tried various possibilities for writing this litte part of code, and it is the only one that permits to declare objects in the "MyController" function without an explosion of code and without a mixxx stuck from start. 
Anyway this construct is OK for the jsl, and various alternate construct that are OK for your js lint validator are totally indigest for Mixxx.
like this one :
ReloopBeatpad =  (function () {}); <-- JS Lint OK, Mixxx bugs
or even this one :
ReloopBeatpad = function () {};   <-- JS Lint OK, Mixxx bugs

May be it is Mixxx wich is weird in that case. and then one should consider if you expect some JS lint compliant code and only that, the Mixxx scripting engine should be updated quickly in order to be JS Lint compliant too.

Writing ['something'] or .something is not about religion.. it's just how it's made in Mixxx
NO, it just how you made it, you, in Mixxx. When I have a look to other "official" mappings, I will can affirm I am not the first one to do so.

I will pull a request with a script slightly modified to take into account various pertinent remarks.

**Comment by Be-ing** [comment]
Regarding bracket vs dot notation, I agree that it's largely irrelevant. AFAIK the only downside to bracket notation is that it is a little bit more work to type brackets and quotes vs just a dot.

> ReloopBeatpad = (function () {}); <-- JS Lint OK, Mixxx bugs

That's not the notation suggested in the StackOverflow question. You need to put () after the function expression to immediately invoke the function, like
ReloopBeatpad = new (function () {this.property = something;})();

> the Mixxx scripting engine should be updated quickly

I believe the plan is to migrate Mixxx to Qt5 after 1.12 is released. Qt 5.2 introduced a new JavaScript engine optimized specifically for the ways that Qt applications use JavaScript.

**Comment by Be-ing** [comment]
Remove lines 1217-1220. Mixxx now remembers whether quantize and keylock were enabled on each deck when Mixxx shuts down, so users who want to have these enabled all the time can turn them on and leave them. For users who do not want to use either of these features, it would be a hassle to have to modify the mapping to prevent them from being turned on every time they start Mixxx.

**Comment by Be-ing** [comment]
From the wiki:
> At the end of a track, the jogwheel is flashing red faster and faster until it reaches the end of the track (full steady red).

Add an option to disable this behavior. Some may find it annoying. Initialize a boolean variable at the top of the script with a comment explaining how to disable that behavior.

**Comment by Be-ing** [comment]
I see there is no mapping for toggling quantize mode. Maybe shift + sync would be a good way to map that.

**Comment by Be-ing** [comment]
I'll keep looking through this later, but the weather is really nice here so I'm going to go enjoy that. :)

**Comment by DJChloe** [comment]
Guess what, I just pushed my files into my github ;)
I mapped the two shift buttons with your idea : quick double press shift to toggle the Flash warning for the end of the track

**Comment by DJChloe** [comment]
SHIFT +SYNC is already "traditionally" used for the Beatpad to go to the beginning of the track

**Comment by DJChloe** [comment]
By the way, thank you for the Wiki :)

**Comment by DJChloe** [comment]
I've just updated my two files and took into account ALL your remarks !
- JS Lint "weird construct"
- indents (4 spaces, removed all tabs and trailing spaces)
- xml file renamed, double quote in the xml tag
- more comments in the code
- Flash warning for the end of the track toggle on/off
- "Beautify" the code of the js  file
- A TODO completed that I had left aside in my code (nothing much, just a light display)

left : "this." and "with" structure in the javascript code

**Comment by DJChloe** [comment]
OK, I've got two ideas.
1) SHIFT+REC = Toggle Flash warning for the end of the track.
2) SHIFT+quick double PFL = Quantize toggle

**Comment by DJChloe** [comment]
And put the PFL button in script in order to enlight it when PFL is activated

**Comment by Be-ing** [comment]
> SHIFT +SYNC is already "traditionally" used for the Beatpad to go to the beginning of the track

This mapping doesn't have to match the djay mapping exactly. I'll keep looking through this tomorrow.

**Comment by illuusio** [comment]
I think we merge this one and make code quality later on like we have did other Javascripts..

**Comment by DJChloe** [comment]
Please wait before merging. I'll tell you wen It's OK. Thk you.

**Comment by DJChloe** [comment]
OK, I didd all my modifications.
I've included the "GPL v2" header in my js file (I hope I did it right like expected)
Code rework (double press/long press stuff), code cleanup.

All OK in JSHint !!! :smile: 
If you find something about the code quality, you are a god !

Tell me, validate and ... merge, please. :kiss:

**Comment by Be-ing** [comment]
> A mapping cannot call another mapping and they are supposed to live in separate threads. Global variables are local to each js file. For that reason, you cannot calll the utility function of another mapping file

I'm not sure this is the case. I'll test out an example and see what happens.

**Comment by DJChloe** [comment]
You need two controllers plugged to your computer in order to do this, is it possible ?

**Comment by Be-ing** [comment]
Yes, I have multiple controllers.

**Comment by DJChloe** [comment]
:+1:

**Comment by Be-ing** [comment]
You are correct, global variables from different scripts do not overwrite each other.

**Comment by Be-ing** [comment]
line 252: typo. There is a space missing between "change" and "in"

**Comment by Be-ing** [comment]
ReloopBeatpad.RGB is for the colors of the lights around the jog wheels, correct? Perhaps a better name would be ReloopBeatpad.jogColors or ReloopBeatpad.wheelColors.

**Comment by Be-ing** [comment]
Move the definition of the TrackEndWarning boolean to the very top of the script file so users don't need to look through any code (which would be intimidating to a lot of people) to change the default.

**Comment by DJChloe** [comment]
;)

**Comment by DJChloe** [comment]
I already thought about it but...

In fact there are multiple coloration systems for the jogwheels : one set
of 4 leds doing some RGB display placed in X, one set of 24 red leds all
around (used to display a spinny or visualize track position ) , and a set
of 4 blue leds placed in + .

Therefore, the MIDI.RGB values are not the only "colors " for the jogging
wheels.
More over it really represent a 3bits color encoding system (except that
reloop inversed the blue and the green  values with respect to the common
standard )

That's why I would prefer to keep it named RGB

**Comment by Be-ing** [comment]
Okay, then add a brief comment explaining that it is for the jog wheel.

**Comment by Be-ing** [comment]
The wiki says:
> Note: On account of the Reloop Beatpad limitations (bug ?), lights will not show on in Sampler mode when the controller is in SHIFT mode.

Did you ever figure out what is going on with that issue?

**Comment by DJChloe** [comment]
There 's no need to do so, you can desactivate it from the controller (see
in the Wiki, I've updated it ) : shift+record button

**Comment by Be-ing** [comment]
> There 's no need to do so, you can desactivate it from the controller (see in the Wiki, I've updated it ) : shift+record button

It is good that you added that, but for users who do not want flashing lights, it would be annoying to press shift + record every time they start Mixxx. It should be obvious how to change this as soon as they open the script in a text editor. (See also: https://bugs.launchpad.net/mixxx/+bug/1470278 )

**Comment by DJChloe** [comment]
> "Okay, then add a brief comment explaining that it is for the jog wheel."

Done !
 >"It is good that you added that, but for users who do not want flashing lights, it would be annoying to      >press shift + record every time they start Mixxx. It should be obvious how to change this as soon as >they open the script in a text editor. "

Done !

>The wiki says:
>
>>Note: On account of the Reloop Beatpad limitations (bug ?), lights will not show on in Sampler mode >>when the controller is in SHIFT mode.

>Did you ever figure out what is going on with that issue?

Yes, in fact the lights update after a second press on shift  !
In Hot cue mode, the same Pads are working perfectly in shift mode
I am not surprised that neither Virtual DJ, nor Algoriddim have implemented the Pad colors in Sampler mode (all buttons stay black). I cannot do better, I think it is a firmware design or worse a hardware problem.

**Comment by DJChloe** [comment]
typo is corrected also :)

**Comment by Be-ing** [comment]
Is there a way to turn off sync lock without having to sync that deck to another? The script only sets sync_enabled to true if the button is held down. It should set sync_enabled to false but without setting beatsync if the button is held down again.

> I think it is a firmware design or worse a hardware problem.

That's unfortunate :/

**Comment by DJChloe** [comment]
> That's unfortunate :/
There are a few things like that which are unfortunate with this controller : 
- mapping documentation is incomplete (sysex messages), and sometimes false
- big grounding problem (solved by making a home made alim cable) :
http://support.reloopdj.com/beatpad/otg-cable-missing-in-my-box-any-otg/
- ...

**Comment by Be-ing** [comment]
Could you make a note of those on the wiki?

line 709: By the way, I don't think .toString() is necessary there. JavaScript automatically converts numbers to strings when a string and a number are joined with the + operator. It's good to keep .toString() for clarity though.

**Comment by Be-ing** [comment]
Looking through the ReloopBeatpad.light constructor function, I see some methods with comments saying they are private, but they could still be called publicly. You can make them actually private members by defining them as local variables with 'var' rather than properties of the object by defining this.functionName. See http://javascript.crockford.com/private.html

**Comment by Be-ing** [comment]
Btw, please use your commit messages to write a brief description of the change you are committing. Something as simple as 'Reloop Beatpad: address comments on PR #752' works.

**Comment by Be-ing** [comment]
line 883: typo. There is a space missing between "a" and "layered".

Remove line 1321. It's not necessary and could cause issues if anything else (like another controller mapping) tries to access [Channel3] or [Channel4].

**Comment by Be-ing** [comment]
A few more typos in the comment in lines 1501-1503.

**Comment by DJChloe** [comment]
>Looking through the ReloopBeatpad.light constructor function, I see some methods with comments saying they are private, but they could still be called publicly. You can make them actually private members by defining them as local variables with 'var' rather than properties of the object by defining this.functionName. See http://javascript.crockford.com/private.html

Very interesting.
In fact I think I will adopt this approach in all my js projects now (I like the idea of private/public, I come from the world of Delphi and C++. A long time ago I've been admin for developpez.com, but lack of time, family, etc... You know).
Once this mapping is committed as an initial release for Mixxx integration, I will start to modiy it in order to have private/public methods and variables in all my functions.
For now it will be too much work and time on it for the benefit.
Consider it for a future pull request.

**Comment by Be-ing** [comment]
That's fine. There is no need to refactor the code right now if it works the way it is.

I've started to work on a JS library to make mapping easier, particularly for making complicated, layered mappings. I plan on rewriting the Electrix Tweaker mapping to use it and writing a mapping for the MIDI Fighter Twister with it. I'll reread your mapping in more detail and see how you organized it for inspiration. I think you may have some good insight on designing the library. If you would like to be involved, subscribe to the mailing list (https://lists.sourceforge.net/lists/listinfo/mixxx-devel ). If you want to look back at the mailing list thread, you can read it here: http://sourceforge.net/p/mixxx/mailman/mixxx-devel/thread/5588554B.40904%40gmx.com/#msg34230237

**Comment by Be-ing** [comment]
There are a couple places throughout the JS file where there is a space after the '//' to start a comment, but most of the comments do not start with a space. Please use one way or the other throughout the script.

**Comment by DJChloe** [comment]
Sync_enable is a toggle if i remember well. If it is already enabled it is
turned off when you set True. Will check this quickly tomorrow.

**Comment by DJChloe** [comment]
OK, let's pause again, will see that on monday.
Don't rush for commit

**Comment by DJChloe** [comment]
Ready to be merged...

**Comment by Be-ing** [comment]
Please sign the Mixxx contributor agreement before this is merged: https://docs.google.com/forms/d/1m_Ql2LyQ2nsgpFe6S4ED3jmzaLgA3U6P2TALOHMxGxA/viewform

**Comment by Be-ing** [comment]
Please move the EndTrackWarning declaration to the very top of the file, above the JSHint configuration.

**Comment by Be-ing** [comment]
There are still a few places (lines 129, 783, 813, 814) where the spacing in comments is inconsistent.

A few small spelling errors in the comments:
line 428: "wether" should be "whether"
line 644: "Mixx" should be "Mixxx"

**Comment by DJChloe** [comment]
Lst 4 comments addressed, Mixxx contributor agreement :)

**Comment by DJChloe** [comment]
By the way, could you explained to me what is this Travis thing ? Thank you

**Comment by Be-ing** [comment]
Looks good to me :+1:

**Comment by DJChloe** [comment]
What is this "1490 errored" ? JS files have nothing to do with the building process

**Comment by DJChloe** [comment]
Be, would you mind to have a look to the wiki by the way ? 4 days ago I have created a new section, and since English is not my mother language, I am not sure of what I have written, if it is understandable, etc...

**Comment by daschuer** [comment]
Travis is a build server service. Sometimes it reaches the time out which results in a false positive.

**Comment by daschuer** [comment]
Thank you very much, for all the work!

**Comment by DJChloe** [comment]
You are welcome !

**Comment by Be-ing** [comment]
I edited the new part of the wiki to change formatting and wording. Please make sure that the content is still correct. I moved the link about Windows settings to the Adjusting Audio Latency page and the link about USB cables to http://mixxx.org/wiki/doku.php/troubleshooting#my_sound_card_randomly_stops_working

**Comment by Be-ing** [comment]
Thanks again for contributing this mapping!

**Comment by DJChloe** [comment]
> Please make sure that the content is still accurate

perfect :+1: 

> I moved the link about Windows settings to the Adjusting Audio Latency page and the link about USB cables to http://mixxx.org/wiki/doku.php/troubleshooting#my_sound_card_randomly_stops_working

Perfect ! I won't complain. Those links were better there :)

**Comment by Be-ing** [comment]
If you want to translate the wiki page into French, that'd be great.

**Comment by DJChloe** [comment]
I will consider it for the future ;)

**Pull request merged**
