### PR TITLE
CMake: use CXX_COMPILER_LAUNCHER instead of RULE_LAUNCH_COMPILE

### PR DESCRIPTION
**Pull request by Be-ing**
This allows for removing the hack for RULE_LAUNCH_COMPILE with
sccache.
https://gitlab.kitware.com/cmake/cmake/-/issues/22405

### CODE REVIEW

**Review by daschuer — COMMENTED** [review]
Cool, it still works here on Ubuntu. Judged from the Windows build time running since 43 min by now it does not work for windows. 
Can a windows contributor confirm that?

**Comment by Be-ing** [comment]
The long build time was because there was no cache for the branch yet.

**Comment by Be-ing** [comment]
I just [asked upstream for a new release](https://github.com/mozilla/sccache/issues/1019) so we can install from Chocolatey instead of taking 10 minutes to build sccache from source.

**Comment by Be-ing** [comment]
I am confused why GitHub Actions keeps having cache misses.

**Review by uklotzde — APPROVED** [review]
Merge and keep an eye on Windows build times to detect possible regressions?

The new version is recommended and cleaner.

**Comment by daschuer** [comment]
Yes, I have just compared with other PRs and it is always around 50 min. This is suspicious, but no regression.

**Pull request merged**
