### PR TITLE
QML: Add developer tools window

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by ywwg** [comment]
lol I should have read this before my comment in #4567 !

**Comment by ywwg** [comment]
I am building qt6 so I can review these -- code looks fine but I'd like to be able to see it for myself

**Comment by Holzhaus** [comment]
> I am building qt6 so I can review these -- code looks fine but I'd like to be able to see it for myself

Oh, this PR is not finished yet. You cna see the controls but changing them does not work yet.

Also, Mixxx does not build with Qt6 yet. To test the QML UI, Qt5 suffices. I think current main requires at least Qt 5.12, but this PR needs Qt 5.15.

**Comment by Holzhaus** [comment]
> You can see the controls but changing them does not work atm.

Editing works now, but the values donz update yet. The QWidgets UI polls all controls using a timerEvent, but updating them via connections should be more performant.

**Comment by Holzhaus** [comment]
okay, it's not pretty but it works now. Just build Mixxx as you normally would (using Qt 5.15), then run mixxx using `./mixxx --qml`.

**Review by ywwg — APPROVED** [review]
yeah I figured out how to make it work finally. looks good!

**Comment by Holzhaus** [comment]
Alright, then feel free to merge.

**Comment by Swiftb0y** [comment]
The PR is broken. Seems like you forgot to include some QML files and didn't register some types:
```
warning [Main] QQmlApplicationEngine failed to load component
warning [Main] file:///home/swiftb0y/Sourcerepositories/mixxx/res/qml/main.qml:92:21: Type DeveloperToolsWindow unavailable
warning [Main] file:///home/swiftb0y/Sourcerepositories/mixxx/res/qml/DeveloperToolsWindow.qml:20:9: Type Skin.TextField unavailable
warning [Main] file:///home/swiftb0y/Sourcerepositories/mixxx/res/qml/TextField.qml: No such file or directory
critical [Main] Failed to load QML file "res/qml/main.qml"
```

**Review by Swiftb0y — DISMISSED** [review]
The PR is broken. Seems like you forgot to include `TextField.qml` ~~and didn't register some types~~:
```
warning [Main] QQmlApplicationEngine failed to load component
warning [Main] file:///home/swiftb0y/Sourcerepositories/mixxx/res/qml/main.qml:92:21: Type DeveloperToolsWindow unavailable
warning [Main] file:///home/swiftb0y/Sourcerepositories/mixxx/res/qml/DeveloperToolsWindow.qml:20:9: Type Skin.TextField unavailable
warning [Main] file:///home/swiftb0y/Sourcerepositories/mixxx/res/qml/TextField.qml: No such file or directory
critical [Main] Failed to load QML file "res/qml/main.qml"
```

**Comment by Swiftb0y** [comment]
thanks

**Comment by Swiftb0y** [comment]
headings get squeezed when the table is empty when there are no search results. Don't feed to fix it now if its too much of a hassle but then leave a comment please.
image

**Comment by Holzhaus** [comment]
> headings get squeezed when the table is empty when there are no search results. Don't feed to fix it now if its too much of a hassle but then leave a comment please.
> image
> 

Done.

**Comment by ywwg** [comment]
since this is high-flux developer code I don't think it has to be perfect UI.  we can iterate as needed but it sounds like this is needed to unblock QML work

**Pull request merged**
