### PR TITLE
Add 'primary dialect' to Code of Conduct

### PR DESCRIPTION
**Pull request by ebberg**
Instead of only talking about 'primary language', adds 'primary dialect'.

### CODE REVIEW

**Comment by daschuer** [comment]
Please add some more context. For me a dialect is just particular form of a language, so the original sentence should already cover this. 

The whole paragraph can make use of an overhaul though. It is most likely that you communicate in a forign language, so we should  pefere an explicit and simple language without Ironie or innuendo.

**Comment by daschuer** [comment]
@ebberg What are your plans with this PR?

**Comment by Holzhaus** [comment]
I don't think the author intends to elaborate. Closing this.

**Comment by Holzhaus** [comment]
> I don't think the author intends to elaborate. Closing this. Please open a new PR if you want to make a new attempt.

**Pull request closed without merging**
