### PR TITLE
Shade: Added deck effect routing button

### PR DESCRIPTION
**Pull request by daschuer**
bildschirmfoto vom 2018-03-27 23 35 12

### CODE REVIEW

**Comment by daschuer** [comment]
This is a changed requested and promised here: https://github.com/mixxxdj/mixxx/pull/1459
I will merge it now to have this in 2.1. I anyone has objections, we can fix it post merge.

**Comment by Be-ing** [comment]
Eh... this hardly improves the situation. I have started working on a follow up but it is not finished yet.

**Comment by ronso0** [comment]
> I have started working on a follow up but it is not finished yet.

Please, share your idea before/while working on it so we don't end up in a kind of difficult discussion like with some skin/UI PRs where we got stuck due to too many clashing oppinions.._after_ a lot of work was done already.
:v:

**Comment by Be-ing** [comment]
I propose:
  * Shrink horizontal width of effect selectors
  * Move mix knob into effect units
  * Keep effect unit assignment buttons in decks, but remove crossfader bus assignment buttons
  * Move headphones and master effect unit assignment buttons out of decks into either effect units or mixer
  * Replace effect unit superknob in decks with QuickEffect superknob

**Comment by daschuer** [comment]
> I propose:

Sorry @Be-ing, but you will destroy the alternative concept of Shade. "Mixing with Maximum Library, but all important controls under the thumbs." We have already tree skins that works like that. For me all of them do not work as good as Shade, because the library is often hidden.

> Shrink horizontal width of effect selectors

I am afraid this will destroy the visual design concept of the button grid in the deck area. 

> Move mix knob into effect units
 
It depends on the future plans with the Mixxx knob. Will it become an effect parameter? Currently it is essential to bring all effects in without thinking too much. So it should be instantly accessible.    

> Keep effect unit assignment buttons for decks in decks, but remove crossfader bus assignment buttons

I like the bus hook very much, because you have single button for all transition effects not important which source. It is hard to forget to switch it of because it is so prominent. Once we have the sync feature enabled for it. We can consider to remove the deck assignment button. 

 > Move headphones and master effect unit assignment buttons out of decks into either effect units or mixer

Currently the effect preview button works well in this place. We have no master effect button. 
The idea is to create a third effect unit in the SRC row. Which has a Mic and Master assignment buttons.
It is fine to have them hidden during the performance, because these effects are for most use cases only set at on time. 

> Replace effect unit superknob in decks with QuickEffect superknob

We may consider to make this a skin option. It depends could be useful if the user has a controller with a filter knob.

**Pull request merged**
