### PR TITLE
Deere :: 16 or 64 sample decks

### PR DESCRIPTION
**Pull request by ronso0**
[Bug 1707991 samplers don't scale well](https://bugs.launchpad.net/mixxx/+bug/1707991): Time to load and shut down Mixxx increases perceptibly if skins are loaded with a total of 64 sample decks.

This is a quick workaround that reduces the number of available sample decks to 16, and introduces a second version of the skin with 64 sample decks. Both versions are identical, except the number of available sample decks, of course.

The number of samplers is set in three places in `skin.xml` only:
- `<attribute config_key="[Master],num_samplers">16</attribute>`
defines the number of samplers available in the engine
- `<Template src="skin:sampler_rows_selection_stack_16.xml"/>`
this is a Singleton definition that loads the respective row selection button for the skin's settings menu
- `<Template src="skin:sample_decks_16.xml"/>`
this loads the appropriate sample decks template

When changing Deere in the future, just work on the standard version with 16 samplers, "Deere".
When all changes are in place
- delete the original 64-samplers version
- add a copy of the 16-samplers version to `/res/skins`, name it "Deere (64 sample decks)"
- change "16" to "64" in all three places listed above

### CODE REVIEW

**Comment by ronso0** [comment]
Added the ring to the Headphone gain knob in top bar

**Comment by ronso0** [comment]
It seems #1426 addresses the roots the sampler issues, so I'm closing this.

I'll fix Deere grids and knobs in another PR pretty soon

**Comment by daschuer** [comment]
I am not sure if #1426 is a good idea for 2.1. It is more than just a bug fix and the current state is quite hacky. Do you think we should continue this route fro 2.1? 
Alternative we can introduce a second skin with less samplers like here, but only duplicate the skin.xml and reference the files in the original skin folder by "..\Tango" 
Did you try this?

**Comment by ronso0** [comment]
As I depicted in the bug discussion, my primary goal is to reduce the shutdown time for all users who don't need 64 samplers. If one of the ideas mentioned in #1426 works out sooner or later, that's fine.
If it's too late to implement one of those safely in 2.1, I'd rather go the way I prepared here.

> Alternative we can introduce a second skin with less samplers like here, but only duplicate the skin.xml and reference the files in the original skin folder by "..\Tango"
Did you try this?

If understand you correctly we'd have a complete `Tango` folder for example, and another on called `Tango (64 samplers)`. In one of them we'd have all templates, stylesheet and graphics. In the other one there'd be a skin.xml only which loads templates etc. from another folder in `/skins`.
I just tried this but I don't find a way to use relative paths for template sources. I tried
`src="/skins/Tango-xy"` `src="../Tango-xy"` `src="skins:Tango-xy"`, none of that worked.
How can we reference files outside the actual skin directory?

**Comment by Be-ing** [comment]
Ah, so you mean creating child skins like WordPress has child themes.

**Comment by daschuer** [comment]
It is: 
src="skins:../Tango-xy

**Comment by ronso0** [comment]
Sorry, none of this is working:
`src="/skins/Tango-xy/template.xml"`
`src="../Tango-xy/template.xml"`
`src="skins:Tango-xy/template.xml"`

`src="skins:../Tango-xy/template.xml"`
`src="skins:/Tango-xy/template.xml"`

The errors indicate that mixxx is looking for a folder literally called `skins:` in the directory from where the binary is run:
> Could not open template file: "/home/ronso/skins:/Tango-xy/size_detector_stars.xml"
Could not open template file: "/usr/bin/skins:/Tango-xy/size_detector_stars.xml"

**Comment by daschuer** [comment]
ups, got it, it is just 
src="skin:../Tango-xy/template.xml"
sorry.

**Comment by ronso0** [comment]
Okay, thank you!

This works, but I also need to change `skin:...` to `skin:../Tango-xy` in style.qss and all templates.

**Comment by ronso0** [comment]
Excellent!

**Comment by ronso0** [comment]
Now it's super easy to create duplicate skins, also the maintenance effort is minimal, except when something in skin.xml itself is changed.

**Pull request closed without merging**
