### PR TITLE
Deere :: add Key/BPM expansion indicators, put Key controls next to play position

### PR DESCRIPTION
**Pull request by ronso0**
https://bugs.launchpad.net/mixxx/+bug/1800705

Either beatgrid or key controls can be expanded. They replace Stars and play position then.
I choose to expand downwards as horizontal expansion creates ugly situations i.e. if the track cover or the mixer incl. Kill buttons is visible. For the same reason Stars and play position are hidden. The preparation use case justifies hiding those IMO.

deere-bpmkey-expansion_0
deere-bpmkey-expansion_1
deere-bpmkey-expansion_2

As soon as this would be merged I'll compact the SVGs.

### CODE REVIEW

**Comment by ronso0** [comment]
Okay. Nevertheless, as soon as we add even small expansion indicators we don't have enough space with a standart mix on small screens.
For me this raises the question if we should stick to 1024px as Deere's minimal size or if we should introduce a 'recommended screen size' while it Deere would still fit 1024px screens but user would have to juggle with the components they need from case to case (Prep scenario vs. Live scenario)

**Comment by ronso0** [comment]
Other possibilities:
simply add expansion indicators, expand left
(needs ~1280px w/ mixer visible before key/bpm controls get squeezed)
deere-bpmkey-expansion_v1

move Key controls next to play position, expand left
(Key controls should replace position display on small screens)
deere-bpmkey-expansion_v2
deere-bpmkey-expansion_v2_closed

**Comment by beenisss** [comment]
The stacked key and beatgrid controls looks good. But even if you go with the original it's not gonna ruin Mixxx for me or anything. It would be nice to have track time still visible but I appreciate it's difficult to work with the space.

**Comment by ronso0** [comment]
@beenisss  @Be-ing What do you think?
I'd like this fix to be added to 2.2.0, and the easist way seems to be this:
Key controls are moved down, both Key & BPM controls can easily be visible at the same time, and nothing needs to be hidden to still have a nice UX
deere-bpmkey-expansion_v2
deere-bpmkey-expansion_v2_closed

That's a polished version from another branch [ronso/deere-beatgrid-key-controls-2rows2](https://github.com/ronso0/mixxx/tree/deere-beatgrid-key-controls-2rows2). If you go along I'd force-push it into this branch here.

**Comment by rryan** [comment]
Do the waveforms resize when you expand/collapse the key/bpm sections? They do for me on macOS.

**Comment by beenisss** [comment]
I did notice some minor glitches when I tried it out. I haven't tested it properly, but let me know if I should.

**Comment by daschuer** [comment]
LGTM so far, however there are some issues, not prevent merging for me:

* If both expanded they are squashed to unreadable if you open the skin preferences 
* If you enable both times, the first is truncated from the left to unusable. I think it should be hidden in this case. 
* It is odd that the "<" moves away under the mouse. I think the cent display should go the the left. 
* the time is truncated too early:  
image

**Comment by ronso0** [comment]
> The "MATCH" button text is cut off, but that's true for me without this PR too.
@rryan 
Your screenshot shows OpenSans is not used.. this was noticed in https://github.com/mixxxdj/mixxx/pull/1867#issuecomment-432795562 too

@daschuer 
There are plenty of issues at minimal size with the skin settings... 
I'll continue to fix those, but for now this is already a huge improvement IMO
The only _simple_ way to fix this is to force-open the key controls at full width:
deere-bpmkey-expansion_v2__squeezefix

> It is odd that the "<" moves away under the mouse.

The border and the highlight indicate that you don't need to hit that small arrow but the whole container is responsive. You think that doesn't suffice?

**Comment by daschuer** [comment]
I now, "perfect" is here probably not worth the effort. So we can IMHO merge it when you think it is ready.

**Comment by ronso0** [comment]
Yup, ready to go!

**Comment by daschuer** [comment]
@beenisss @rryan merge?

**Comment by rryan** [comment]
SGTM

**Comment by Be-ing** [comment]
:+1:

**Comment by Be-ing** [comment]
I have noticed a drawback of this design. The strings for different keys can be different widths, which can make the key adjustment buttons move from under the cursor when clicking them repeatedly.

**Comment by ronso0** [comment]
proposed changes are in #1925

**Pull request merged**
