### PR TITLE
DlgPrefController: remove Scripts tab

### PR DESCRIPTION
**Pull request by Be-ing**
This tab did nothing useful and only confused users, for example:
https://mixxx.org/forums/viewtopic.php?f=3&p=43444
https://mixxx.org/forums/viewtopic.php?p=39226#p39226
https://mixxx.org/forums/viewtopic.php?p=41743#p41743
https://mixxx.org/forums/viewtopic.php?p=32084#p32084

### CODE REVIEW

**Comment by ronso0** [comment]
the only option I found useful was "open file", when I had several xml and js files in the controller folder and was unsure wgich wad actually in use. 
can we somehow show that info in the mapping info tab?

**Comment by Be-ing** [comment]
We could... but do we need to?

**Comment by ronso0** [comment]
We should, I'd appreciate that. Without the scripts tab that information is not accessible.
In case my controller mapping doesn't work as expect during a performance I need to have quick way to know if I need to fix `~/.mixxx/controllers/Terminal_Mix_2-4.js` or `~/.mixxx/controllers/Terminal_Mix_4_SCRIPT_2.js` or `~/.mixxx/controllers/Terminal_Mix_4_SCRIPT_2.js`.

In the **Preset Info** section below _Support:_ we could add _Included files:_ and list all mapping files as clickable links. Basename should be visible and paths can be elided as necessary:
Screenshot_2019-12-11_12-56-08

**Comment by Holzhaus** [comment]
I agree that the scripts tab should be removed. However it makes sense to see which script has been loaded. This is useful since Mixxx currently copies scripts around even if nothing was changed.

**Comment by ferranpujolcamins** [comment]
Why do we even copy scripts around? If we show the current preset scripts paths, any user that wants to modify a script will know where to copy the originals from.

**Comment by Holzhaus** [comment]
I guess it's do to the learning assistant. I'm all for getting rid of that behavior.

**Comment by ronso0** [comment]
> We should, I'd appreciate that. Without the scripts tab that information is not accessible.
> In case my controller mapping doesn't work as expect during a performance I need to have quick way to know if I need to fix `~/.mixxx/controllers/Terminal_Mix_2-4.js` or `~/.mixxx/controllers/Terminal_Mix_4_SCRIPT.js` or `~/.mixxx/controllers/Terminal_Mix_4_SCRIPT_2.js`.
> 
> In the **Preset Info** section below _Support:_ we could add _Included files:_ and list all mapping files as clickable links. Basename should be visible and paths can be elided as necessary:
> Screenshot_2019-12-11_12-56-08

I'd like to pick this up, maybe I can even finish it for 2.3
One thing I need advice for is how to make the file names appear as links, then I'd adapt the 'Open In File Browser' function used in the library.

**Comment by Holzhaus** [comment]
@ronso0 
> One thing I need advice for is how to make the file names appear as links, then I'd adapt the 'Open In File Browser' function used in the library.

I think you need to set the text format to richtext and insert an HTML `<a>` element. You could then use https://doc.qt.io/qt-5/qlabel.html#linkActivated

**Comment by Holzhaus** [comment]
@ronso0 I'd like to merge this. We can add links in a separate PR, okay?

**Comment by daschuer** [comment]
Without the links I like to prefer to keep the current situation. 
Didn't we had links originally?

**Comment by ronso0** [comment]
I agree with @daschuer , without the links it's a small UI regression IMO.
I'll look into this at the weekend.

**Comment by ronso0** [comment]
> > One thing I need advice for is how to make the file names appear as links, then I'd adapt the 'Open In File Browser' function used in the library.
> 
> I think you need to set the text format to richtext and insert an HTML `<a>` element. You could then use https://doc.qt.io/qt-5/qlabel.html#linkActivated

okay, so the same way the New Playlist/Crate links are created. I'll try that.

**Comment by ronso0** [comment]
I added the script links in https://github.com/Be-ing/mixxx/pull/40
and also tweaked the layout a bit (label positions mainly)
image

**Comment by ronso0** [comment]
in a follow-up I'll remove some pointless /n from mapping descriptions. if we want to give the description in between mapping info & links we should do that in the layout (and qss)

**Comment by ronso0** [comment]
@Holzhaus @daschuer Merge?

**Comment by Be-ing** [comment]
ping @Holzhaus

**Review by Holzhaus — APPROVED** [review]
LGTM.

**Comment by ronso0** [comment]
> in a follow-up I'll remove some pointless /n from mapping descriptions. if we want to give the description more space in between mapping info & links we should do that in the layout (and qss)

Turns out it was just one: mine for Reloop TerminalMix :)

**Pull request merged**
