### PR TITLE
Mapping for MIDI Controller Behringer BCR2000

### PR DESCRIPTION
**Pull request by git-developer**
Documentation PR: https://github.com/mixxxdj/manual/pull/310

This PR contains more than an average mapping:
- Additional Javascript components for controls (Buttons & Encoders)
- A Layer Manager component that simplifies arranging controls on a Shift layer

We'll probably discuss a little bit about all this, which could be done in this PR or the [forum thread](https://mixxx.discourse.group/t/behringer-b-control-bcr2000/20287).

### CODE REVIEW

**Comment by git-developer** [comment]
I've come across a few Wiki articles that might be interesting for the mapping. I'd appreciate if someone could shortly comment on the progress on these topics:

1. [Registering Midi Input Handlers From Javascript](https://github.com/mixxxdj/mixxx/wiki/registering%20midi%20input%20handlers%20from%20javascript)
  The mapping between MIDI and Mixx controls is already done in Javascript, so I'd prefer to remove the XML file completely.
1. [Controller Script Modules](https://github.com/mixxxdj/mixxx/wiki/Controller-Script-Modules)
  Can / should the mapping be moved to a Script Module?
1. [New controller system](https://github.com/mixxxdj/mixxx/wiki/New-controller-system)
  Does the new controller system have effects on the format of the Javascript mapping?

**Comment by Be-ing** [comment]
> Registering Midi Input Handlers From Javascript, Controller Script Modules

These are old proposals that will not be implemented. The "New controller system page" has a summary of current plans.

>  Does the new controller system have effects on the format of the Javascript mapping?

Yes, it will be an entirely different API.

**Comment by git-developer** [comment]
This PR contains several independent building blocks that together form a mapping for the Behringer BCR2000 controller. I'd like to explain these building blocks a little bit so that the whole stuff is easier to understand. Maybe a part of this code can be re-used for other things, your thoughts and comments are welcome.

### General stuff (independent of the controller)
#### File `midi-components-extension.js`
This file contains a set of additional components which are quite generic and could be re-used for other mappings.

#####  Support objects (type `object`, currently private)
  - `log`: Allows to log to the console on different levels
  - `ComponentRegistry`: A registry that allows storing `Component`s in named `ComponentContainer`s. Within a container, components are identified by their MIDI address.

##### Public Components (type `Component`)
  - `LayerManager`: This component helps working with layered components.
    The wiki article [MIDI Scripting](https://github.com/mixxxdj/mixxx/wiki/MIDI%20scripting#modifier-shift-buttons-and-layered-mappings) describes two approaches to implement a shift layer: either working with a condition _within_ a component or switching components in a _container_. The LayerManager is a generic component that implements the second approach. Internally, it uses a component registry for the two layers _Default_ and _Shift_. It is itself a `Component` offering `shift()` and `unshift()` to toggle between the these layers. Additionally, it offers `input()`, a facade to be called from the XML file that delegates to the component on the currently active layer.
  - `ShiftButton`: Simple button that triggers `shift()` and `unshift()` on a target component.
  - `Trigger`: A component that is always triggered on every input, regardless of the value.
    Example use: Button to reset key (`pitch_set_zero`).
  - `RangeAwareEncoder`: An encoder for a value range of _[-bound..0..+bound]_.
    Example use: encoder to change key (`pitch`)
  - `EnumToggleButton`: A button to cycle through the values of an enumeration.
    Example use: Toggle vinyl control mode
  - `EnumEncoder`: An encoder for enumeration values.
    Example use: Base component for LoopEncoder
  - `LoopEncoder`: An enum encoder that knows beat sizes.
    Example use: Encoder for `beatloop_size` and `beatjump_size`
  - `LoopMoveEncoder`: An encoder that moves the current loop.
  - `BackLoopButton`: A button that toggles a beatloop _ending_ at the current play position, so the beat jump
    occurs immediately on button press and not after the first loop.
  - `Publisher`: Kind of a "sidecar" for the effect unit controls (buttons and knobs).
    When I mapped my controller, I wondered why the effect unit knobs do not send their value to the controller. It seems that they're just no made to do so. My guess is that the effect unit implementation was done with physical pots in mind that offer no LEDs. Anyway, when I looked at the [EffectUnitKnob implementation](https://github.com/mixxxdj/mixxx/blob/e47d6499245dc6822132ec621ff01317c7849b55/res/controllers/midi-components-0.0.js#L868), I saw that the `outKey` is used to implement focus changes, and I didn't want to touch that. Thus, I decided to create this `Publisher` component. It uses the Mixxx control of a _source_ component (an effect unit control) and defines an `outKey` only (no input handling).
Unfortunately, these effect unit control are quite tricky and change their internal state on focus and shift changes. Thus I had to implement a `bind()` function that syncs the `outKey`. `bind()` is to be called on those state changes. The call is currently done when the effect unit is setup (in `Behringer-BCR2000-core-scripts.js`).

#### File `Behringer-BCR2000-core-scripts.js`
  Skeleton for a controller mapping containing custom `EffectUnits` and `Decks`, where _custom_ means:
  - Effect units have support for sending output values for encoders.
  - Decks may be composed of arbitrary components.
  - All components are managed by a `LayerManager` and thus may be put on either the _Default_ or the _Shift_ layer by configuration.

The actual mapping configuration is a separate file (currently `Behringer-BCR2000-configuration-scripts.js`).

This skeleton has currently only a single dependency on the BCR2000 controller: the possibility to set a preset in the controller on `init()` and `shutdown()`. This could be refactored so that the skeleton may be used for other general purpose controllers (e.g. AKAI APC, AKAI Fire, AKAI midimix, Behringer X-Touch, DJ Techtools Midi Fighter, Faderfox, Icon Platform M+, Korg nanoKONTROL, Midiplus SmartPAD, Nektar Aura, Novation Launchpad, Studiologic SL Mixface).

### Controller-specific
#### File `Behringer-BCR2000-preset-scripts.js`
  This file maps the MIDI addresses of hardware controls to readable names like `buttonRow2[3]` or `pushEncoderGroup2[5]`. Since the BCR2000 has 32 user-programmable presets, the MIDI addresses are not fix. When a user prefers to use a customized preset over the factory settings, this file encapsulates the preset information, leaving the component mapping untouched.

### Preset-specific
#### File `BCR2000.midi.xml`
  I don't really want to maintain this file, but it seems to be necessary to delegate MIDI input to the Javascript world. So it simply contains a lot of input definitions that all delegate to the same input function of the controller mapping (delegating again to the LayerManager that knows the currently active component for a MIDI address).
#### File `Behringer-BCR2000-configuration-scripts.js`
  Configuration for the actual controller mapping. This file contains all information about
  - used components (e.g. a button or an encoder)
  - layer for each component (`Default` or `Shift`)
  - MIDI address and
  - Mixxx control (e.g. `vinylcontrol_mode` or `key`)

**Comment by Be-ing** [comment]
:confused: I don't know what to do with this PR. I have no desire to invest any effort into extending the legacy mapping system. At the same time, I don't want to merge a new library that hasn't been thoroughly reviewed which could then get used by other mappings...

**Comment by git-developer** [comment]
> I don't know what to do with this PR.

I've been looking for all relevant documentation carefully before I started this mapping. Based on that, I decided to use Component JS in favor of a XML-based mapping. I'm surprised the current mapping system is already considered legacy - is there an alternative currently available? If so, I could try to refactor the mapping towards it.

**Comment by Be-ing** [comment]
This is not just a mapping using Components, this is an entirely new JS library with as much code as the Components library. You're now asking us to:
1. Review this new library.
2. Learn how it works.
3. Review a new mapping using it.

This is a lot to ask, especially considering we are very busy trying to get 2.3 released and also have plans for a completely new controller system.

**Comment by Holzhaus** [comment]
Don't get us wrong, we appreciate all the effort that you've put into development. However, I tend to agree with @Be-ing that we shouldn't add a huge new JS library to the legacy controller system (we're working on a new one that doesn't require XML and uses proper JS modules, but work has stalled since we want to get 2.3 out ASAP).

PRs like this are the reason why we recommend opening an early draft PR and discussing your work on Zulip, because now we either have to add a new library or ask you to rewrite large parts of the mapping to remove the new lib. :-/

**Comment by git-developer** [comment]
I understand that a review of a PR like this means a lot of effort. My intention is not to create effort. I'd like to contribute something which created value for me, and hopefully creates value for the Mixxx project as a whole. That's the only reason why I cut my stuff into components, wrote the docs etc. If you think this contribution does not add value to the project, please don't accept it.

If I can support the review somehow, just tell me how. I can also refactor the code if that helps, I just didn't find the new API. If you don't want to accept the PR for whatever reasons (priorities, review effort, you name it), that's fine. I can attach the files to the forum and maybe create a PDF from the manual.

Maybe you've seen [on the forums](https://mixxx.discourse.group/t/ddm4000-controller-mapping/20045/7?u=mixxx-user) that I'm working on another mapping that uses the components from this PR. I will complete that one locally and await what's coming out here.

**Comment by uklotzde** [comment]
Currently the extensions are only used by a single mapping. Existing mappings are not affected.

At first sight the code looks clean and well-documented, no objections in this regard.

The only risk I see is that other developers may pick this up, assuming the generic code is officially reviewed, certified, and future proof. How about marking the code in midi-components-extension.js as *experimental* and *not officially supported* to prevent such misconceptions?

**Comment by Holzhaus** [comment]
How about copying all the code into the actual mapping JS file so that it's not possible to reuse it? I really don't want to extend an API that will be deprecated soon anyway.

**Comment by Holzhaus** [comment]
@git-developer Sorry for this mess. Maybe you're interested in joining the Zulip discussion regarding the new API?

**Comment by git-developer** [comment]
I understand your concerns.

It would be no problem for me to "hide" the code by moving it so that others don't use it unintentionally. Just one thing: some of those components are used in my [mapping for the Behringer DDM4000 mixer](https://github.com/git-developer/mixxx/compare/feature/controller-mapping-behringer-bcr2000...git-developer:feature/controller-mapping-behringer-ddm4000). Thus, I'd like to use a common namespace for these components. What do you think of changing the namespace `components.extension` to `components.experimental` or `behringer.experimental`, and renaming the `midi-components-extension.js` to `midi-components-experimental.js` or `Behringer-experimental-scripts.js` or something? Or do you prefer copying the common code into both mapping files (_shiver_)?

I'm new to Zulip. Is there a topic in the [controller stream](https://mixxx.zulipchat.com/#narrow/stream/113295-controller-mapping) for the discussion on the new mapping system?

**Comment by uklotzde** [comment]
Duplicating the code would be the worst decision. Using the `behringer` prefix works for me and prevents general usage.

**Comment by git-developer** [comment]
I replaced `common` by `behringer`.

Can I do something about the failing build? I'm not sure what's wrong, looks like a problem downloading a key finder library, unrelated to this PR.

**Comment by git-developer** [comment]
Looks like the build is failing in my fork only.

**Comment by Holzhaus** [comment]
> Can I do something about the failing build? I'm not sure what's wrong, looks like a problem downloading a key finder library, unrelated to this PR.

    git pull origin 2.3

**Review by uklotzde — APPROVED** [review]
After renaming the files I consider this ready to be merged. The corresponding manual PR is in place, though still failing to build.

Hopefully, there are still some owners of this/these devices who will appreciate the *retrofitting* efforts! :)

**Comment by uklotzde** [comment]
@Be-ing @Holzhaus Ready to merge? This is a prerequisite for the DDM 4000 mapping in #3542

**Comment by Be-ing** [comment]
No, this hasn't even begun review.

**Comment by git-developer** [comment]
This PR was marked as stale but is actually waiting for a review or merge.

**Comment by uklotzde** [comment]
Yes, sorry for the bot marker. Reviewers are a scarce resource and Mixxx is understaffed.

**Review by Swiftb0y — APPROVED** [review]
I'm sorry nobody was able to properly review your PR. I'm unable to review the mapping properly as well because of its enormous size. The code looks pretty solid at first glance and you seem to know your JS, so I trust you that this code is of decent quality.

does anyone object to merging this?

**Comment by uklotzde** [comment]
> I'm sorry nobody was able to properly review your PR. I'm unable to review the mapping properly as well because of its enormous size. The code looks pretty solid at first glance and you seem to know your JS, so I trust you that this code is of decent quality.
> 
> does anyone object to merging this?

This was also my impression when skimming over the code. Neither other mappings nor the core application would be affected if it doesn't work as expected.

I don't expect that we are able to find someone for testing who owns this legacy controller. After the mapping has been merged and becomes accessible for regular users we might get feedback.

@Holzhaus @daschuer Do you agree?

**Comment by Holzhaus** [comment]
Ok for me. In general I don't want to maintain another abstraction library. It should be clear that other controller mappings shouldn't build upon that library. But I'm okay with merging it.

Documentation PR looks good, so I'm okay with merging this.

**Comment by git-developer** [comment]
Thanks!

**Comment by Holzhaus** [comment]
@Swiftb0y please always merge the corresponding manual changes, too.

**Comment by Swiftb0y** [comment]
Yes, I'm sorry I didn't have that on my radar.

**Comment by uklotzde** [comment]
@Swiftb0y Thanks :tada:

As a consequence #3542 will become ready which builds on the common code merged with this PR.

**Pull request merged**
