### PR TITLE
WIP: add a fixed autodj tab to the library

### PR DESCRIPTION
**Pull request by nopeppermint**
on top of #1671 I like to add a optional, fixed autodj tab to the library, as shown here with latenight

this autodj tab on the right will be fixed on autodj, therefore no controll buttons are required for this tab, just one button on the toolbar to enable/disable this option

This would be a really useful tab for me, as at the moment I am switching constantly from autodj view to tracks/playlist or crates view..

autodj_no_tab
autodj_tab

### CODE REVIEW

**Comment by nopeppermint** [comment]
at the moment Autodj is fixed to this special tab and can not be used on the first tab, even if the second is not displayed... so this is not the final solution..

**Comment by Be-ing** [comment]
Let's work on flexible, robust designs instead of hacks that only work for one specific use case.

**Comment by ronso0** [comment]
@nopeppermint 
I remember a very long discussion about how to design the multi-pane library, and we worked towards a solution that fits more than one use case. If you're impatient to wait for this, just built a private branch ;)
Please refer to the first (or second?) lib redesign PR. I don't find it right now, but starting at the middle part of the discussion, there were a lot of illustrated ideas how to deal with multiple button bars and so on.

**Comment by nopeppermint** [comment]
ok

**Pull request closed without merging**
