### PR TITLE
Mapping files for Hercules DJControl Inpulse 300

### PR DESCRIPTION
**Pull request by DJPhatso**
Mapping files for Hercules DJControl Inpulse 300

Changes to v1.2
- Code cleanup.

 Changes to v1.1
- Fix seek-to-start and cue-master behavior.
- Tweak scratch, seek, and bend behavior (User settigns).
- Controller knob/slider values are queried on startup, so MIXXX is synced.
- Fixed vinyl button behavior the first time it's pressed.

v1.0 : Original forum release

### CODE REVIEW

**Comment by Holzhaus** [comment]
Thanks for contributing!

Does this mapping use any new features that are not present in Mixxx 2.2? If not, please rebase this on the 2.2 branch.

**Comment by DJPhatso** [comment]
I made this mapping with Mixxx 2.2.2/2.2.3, so I guess I should be ok

**Comment by Holzhaus** [comment]
> I made this mapping with Mixxx 2.2.2/2.2.3, so I guess I should be ok

In that case please rebase on `2.2` and [change the base branch of this PR](https://github.blog/2016-08-15-change-the-base-branch-of-a-pull-request/) to `2.2`, too.

**Comment by uklotzde** [comment]
Please rebase, switching the target branch is not sufficient.

**Comment by Holzhaus** [comment]
In case you don't know how to rebase:
https://mixxx.org/wiki/doku.php/using_git#targeting_another_base_branch

**Comment by Holzhaus** [comment]
After rebasing on the current 2.2 branch, please move the script files into the `res/controllers` directory.
Also, you can auto-fix a lot of common code-style errors by [running eslint](https://eslint.org/docs/user-guide/getting-started):

    $ eslint --fix res/controllers/Hercules-DJControl-Inpulse-300-script.js

**Comment by DJPhatso** [comment]
Still trying to figure the rebase part.

If I may say, that's a lot a hoops to go through to submit 2 mapping file....

**Comment by Holzhaus** [comment]
Hey @DJPhatso, did you close this PR because you didn't manage to rebase it? If you have problems with rebasing, feel free to post questions either here or on Zulip. We're glad to help if we can!

I it's too much work for you we can also just merge this to `master` instead (this will prevent it from being part of any 2.2.x release though).

**Comment by DJPhatso** [comment]
New try here https://github.com/mixxxdj/mixxx/pull/2465. 

Hopefully I've done everything right this time

**Pull request closed without merging**
