### PR TITLE
Revert "Write _version.h from CMakeList.txt to remove redundant Mixxx…

### PR DESCRIPTION
**Pull request by matthiasbeyer**
… version"

This reverts commit 2c55901a83bd5fc810352b4da70e824930d2619a.

---

This commit broke `shell.nix`.  Revert was done with `git revert <commit> -X theirs`, so this might have issues.

### CODE REVIEW

**Comment by poelzi** [comment]
my tip, don't bother. such commits will never be accepted, even trying to make the nix stuff better is working against windmills

**Comment by matthiasbeyer** [comment]
Yeah, you're probably right. People don't seem to care about proper workflows, I even found over 80 "merge remote-tracking branch 'main'" commits in the history of this project... I guess I'll just consider it dead.

**Comment by daschuer** [comment]
Please explain what you are trying to achieve? 
I think we are interested to integrate Mixxx into various environments. Maybe we can find a mode that works for all.

**Comment by matthiasbeyer** [comment]
> Please explain what you are trying to achieve?

Building mixxx in the nix-shell environment.

**Comment by daschuer** [comment]
Of course you want. So the nix-shell environment is broken, right? 
This is, because it is not actively maintained. Do you have interest to become the maintainer? 

Please also note that there is a default.nix for Mixxx here: 
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/mixxx/default.nix

So what is your use case of using the shell.nix and not directly cmake? 

But anyway,  my guess is that the version handling has to be adjusted. 
Currently we take the version from CMake, but it is also stored as a git tag. It happens only for a few commits during the release process that the version from git describe differs from the CMake version. So I guess you can adust the nix file for relying on the git version.  In case you like to have the nix file working with tar balls, you need to parse the CMakeLists.txt
In this case look for: 
```project(mixxx VERSION 2.4.0)````
and
```
set(MIXXX_VERSION_PRERELEASE "alpha-pre")
```

**Comment by ronso0** [comment]
> I even found over 80 "merge remote-tracking branch 'main'" commits in the history of this project... I guess I'll just consider it dead.

"Merge remote tracking branch XYZ **to** 'main'", which simply indicates that a PR ws merged, so I don't grasp the logic of your statement...

**Comment by poelzi** [comment]
I fixed those bugs in https://github.com/mixxxdj/mixxx/pull/3258 long ago btw

**Pull request closed without merging**
