### PR TITLE
Remove duplicate column names

### PR DESCRIPTION
**Pull request by daschuer**
This removes the duplicated column names by strictly follow the columns used in the database. 

LIBRARYTABLE_LOCATION to LIBRARYTABLE_LOCATION_ID because the column holds only a reference to the track locations table. Use the enum COLUMN_TRACKLOCATIONSTABLE_LOCATION instead of COLUMN_LIBRARYTABLE_NATIVELOCATION becase it points only to the id column. Delete also enums for non existing Playlist table columns.

### CODE REVIEW

**Comment by uklotzde** [comment]
So the column enum refers to database columns that are irrelevant for the purpose? Actually, all those columns need to be considered as *virtual columns* and their mapping to *database tables* or *view tables* depends on the context.

TODO for the future: Remove those confusing table names from the enum literals. Maybe we should even change the naming from "column" to "field" to prevent any invalid association?

**Comment by daschuer** [comment]
> So the column enum refers to database columns that are irrelevant for the purpose?

Not really because the string definitions are used to identify the columns AND are used in the queries accessing sqlite. I have made this now consistent for the "library" table but it looks odd for the external libraries where the constant are re-used in a different context. 

> TODO for the future: Remove those confusing table names from the enum literals.

I have also considered this, but not implement it to keep this PR reviewable.

**Comment by uklotzde** [comment]
> > So the column enum refers to database columns that are irrelevant for the purpose?
> 
> Not really because the string definitions are used to identify the columns AND are used in the queries accessing sqlite. I have made this now consistent for the "library" table but it looks odd for the external libraries where the constant are re-used in a different context.
> 
> > TODO for the future: Remove those confusing table names from the enum literals.
> 
> I have also considered this, but not implement it to keep this PR reviewable.

Just some thoughts, trying to understand the purpose behind all this. Nothing to be implemented in this PR.

**Comment by uklotzde** [comment]
Thank you! LGTM

**Comment by uklotzde** [comment]
I'll merge to main

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
