### PR TITLE
Deere 2.1

### PR DESCRIPTION
**Pull request by Be-ing**
Continuation of #940, with new effects UI from #1063 merged.

### CODE REVIEW

**Comment by rryan** [comment]
The commits from #1063 show up in the diff -- did you merge #1063 into this branch or did you merge with master? Could you merge with master or rebase onto master?

**Comment by Be-ing** [comment]
I just rebased onto master.

**Comment by rryan** [comment]
> I just rebased onto master.

Hm, but all the commits from #1063 show up in this PR as commits to be merged (which suggest you merged #1063 into this branch at some point).

**Comment by Be-ing** [comment]
I realized I forgot to fetch upstream before rebasing onto master. Working on rebasing it again now.

**Comment by rryan** [comment]
It seems you merged deere_new_effects into deere_2.1 on Jan 28 f5e35a848b34df5eebc287f47589992c579b856d but then subsequently rebased deere_new_effects which gave all of those commits new hashes

e.g. this commit is in master a3c1d80dcd48241b81a7edab65e88d254654978d

but this one is in this branch 166b9eb6a9b70317e099061262177a7a5469c9a3

**Comment by Be-ing** [comment]
Turned out to be easier to just merge master into #940, so I'll reopen that.

**Pull request closed without merging**
