### PR TITLE
Appveyor CI changes for CMake

### PR DESCRIPTION
**Pull request by Holzhaus**
These are the CI changes that were removed from #2280.

### CODE REVIEW

**Comment by uklotzde** [comment]
Requires #2280 as a prerequisite.

**Comment by PatrickLang** [comment]
@Holzhaus - what's the latest on this? Anything I can help with or test out? I work on Windows + Linux and am happy to do some check on the Windows side if that's helpful.

**Comment by Holzhaus** [comment]
> @Holzhaus - what's the latest on this? Anything I can help with or test out? I work on Windows + Linux and am happy to do some check on the Windows side if that's helpful.

Are you referring to CMake support? This has already landed in master and will be part of the 2.3 release (although scons will remain the official way to build Mixxx in 2.3). These CI changes will only become relevant for Mixxx 2.4.

However, at least for Travis CI we could just add 2 more jobs that build Mixxx via CMake, too. I don't see any downside to this IMHO. I'll look into it when #2375 has been merged.

**Comment by uklotzde** [comment]
Does this PR become obsolete with #2392?

**Comment by Holzhaus** [comment]
No, we still need the Appveyor changes.

**Comment by Holzhaus** [comment]
After merging #2490 this can replace the SCons based CI builds on Appveyor. It's not ideal to do this, but I'd argue that this is preferable to all the timeouts that happen right now.

**Comment by uklotzde** [comment]
I support the decision to introduce this workaround! Keeping the constantly failing SCons CI build is useless.

Afterwards we need to keep an eye on our own build servers that still use SCons for the official builds. A fair deal.

**Comment by Holzhaus** [comment]
What do the other devs think? Should we merge this now to get rid of the timeouts? @daschuer @Be-ing @rryan etc.?

**Comment by daschuer** [comment]
Yes, failing CI is anoying. However without a scons CI, we have no early warning that something goes wrong. 
I would support to drop scons now and than merge this. Or can we keep the scons Target in addition?

Why are disabled tests reported as failing? What happens if s test actually fails?

**Comment by Holzhaus** [comment]
We'd still have ir on Travis.

**Comment by uklotzde** [comment]
> We'd still have ir on Travis.

We have Travis for Linux and macOS and our own build server for Windows. There is a low chance to break the Windows build with an SCons change. But the SCons build should not be updated very often in the future.

**Comment by daschuer** [comment]
Ah OK, so we can safely merge this.

Is there a chance to not report the disabled tests as failing?
What happens if a test actually fails. Are we still green than?

**Comment by Holzhaus** [comment]
> Is there a chance to not report the disabled tests as failing?

Apparently the XSLT that converts the ctest results to JUnit XML did not support skipped tests. I added support in https://github.com/mixxxdj/mixxx/pull/2332/commits/23345587af95b1a6e0d8fbb9db3ea8c790fdf054.

> What happens if a test actually fails. Are we still green than?

No, because `ctest` should terminate with a non-zero exit status.

**Pull request merged**
