### PR TITLE
lp1913936: Remove unused sample layout property from SignalInfo

### PR DESCRIPTION
**Pull request by uklotzde**
https://bugs.launchpad.net/mixxx/+bug/1913936

### CODE REVIEW

**Comment by uklotzde** [comment]
Trying to enable -Werror unconditionally. This warning should have been recognized as an error!

**Comment by uklotzde** [comment]
CI build before the fix would have failed with the latest commit: https://github.com/uklotzde/mixxx/actions/runs/525343870

**Comment by daschuer** [comment]
Thank you for picking this up instantly.

**Review by daschuer — APPROVED** [review]
LGTM

**Pull request merged**
