### PR TITLE
 Explorer.exe: path file as third argument to fix open in Windows 7

### PR DESCRIPTION
**Pull request by daschuer**
Fixes https://bugs.launchpad.net/mixxx/+bug/1805515

### CODE REVIEW

**Comment by daschuer** [comment]
I have just tested with Windows 7 and 10. And it works now. Merge?

**Comment by Be-ing** [comment]
I don't have Windows to test this, but shouldn't this be targeted at the 2.2 branch?

**Comment by daschuer** [comment]
The select file feature was introduces to the master branch only.

**Comment by daschuer** [comment]
Who is able to test this?

**Comment by daschuer** [comment]
This works for me on Windows 7 and 10. Any objections to merge this now?

**Comment by uklotzde** [comment]
Sorry, but I'm not able to test this.

**Comment by daschuer** [comment]
Is it OK from the code side? I think we can merge it than, because it fixes the issue at least for me.

**Comment by uklotzde** [comment]
Code LGTM ;)

**Pull request merged**
