### PR TITLE
Replace all controlerDebug qDebug() by QDebug(QtDebugMsg)

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by rryan** [comment]
Could you define a macro at the top called controllerDebug() or something? That way you can leave a comment on why we use ```QDebug(QtDebugMsg)``` instead of ```qDebug()```.

**Comment by rryan** [comment]
Also, if you amend your commit you could fix "controlerDebug" typo in the description :).

**Comment by rryan** [comment]
Hm -- looks like this doesn't work on Qt5: 
https://github.com/RSATom/Qt/blob/af80d7ef4343b96603dad8287920b26e03fdf557/qtbase/src/corelib/global/qlogging.h#L151

**Comment by Pegasus-RPG** [comment]
Sweet, this is all it takes? I'll test it later on.

**Comment by daschuer** [comment]
Now we have a macro controllerDebug()
It should work with Qt5 as well, because QDebug is still a part of it.

**Comment by rryan** [comment]
Ok sounds good -- thanks for the fix @daschuer

**Comment by rryan** [comment]
BTW in honor of PR #808: https://www.youtube.com/watch?v=B2uBBtwEdRk

**Pull request merged**
