### PR TITLE
change default EQ to Linkwitz-Riley

### PR DESCRIPTION
**Pull request by Be-ing**
IMO the Linkwitz-Riley EQ sounds the best. The difference in CPU usage is negligible, even on my 5 year old netbook.

### CODE REVIEW

**Comment by Pegasus-RPG** [comment]
Please post CPU make & model of the test machine and relevant profiling output comparing the two EQ methods on the same track playing for the same period of time (30 seconds should be sufficient.)

**Comment by daschuer** [comment]
The biggest difference is that the Bessel EQs are bit perfect and do not consume any CPU at centre position. I assume that the most users do not use the EQs, so I pick the Bessel as default. 
See: https://www.mixxx.org/manual/latest/chapters/configuration.html#mixing-equalizers

The rest is somehow a matter of taste. I am afraid that visual test data cannot show it. 

Or is there an issue with the Bessels?

**Comment by Be-ing** [comment]
> I assume that the most users do not use the EQs

Huh? I think most users do use the EQs. In my experience, the CPU required by any of the EQs is tiny compared to other functionality like keylock. It doesn't do much harm to leave them at unity for those using a hardware mixer, and the option to disable them is there.

> The rest is somehow a matter of taste. I am afraid that visual test data cannot show it.

Correct, it's my subjective opinion that the Linkwitz-Riley EQ sounds better. I feel that the Bessel EQs sound a bit harsh, especially with any knobs all the way down. I know that "harsh" is not a very specific term, but I don't know how else to describe the difference.

**Comment by Pegasus-RPG** [comment]
The default option should use the least resources (CPU) so that new users can have a satisfactory first-time experience on the widest variety of hardware. This is why the current default was chosen. (Besides, CPU usage differences between the EQ methods can vary sometimes greatly between different CPU models/instruction sets.)

**Comment by Pegasus-RPG** [comment]
>  it's my subjective opinion that the Linkwitz-Riley EQ sounds better
...which is why it's offered as another option. There's no compelling reason to change the default given the costs.

**Comment by Be-ing** [comment]
> satisfactory first-time experience

Sounding good is important for this.

> widest variety of hardware

I'm currently updating my netbook to Fedora 24, then I'll compile Mixxx on it for profiling. It has an Intel Atom N270 1.6 GHz CPU from 2008.

**Comment by Pegasus-RPG** [comment]
> Sounding good is important for this.

Of course, but it's not like the Bessel EQ sounds _bad_. We just have to strike a balance between quality and latency on the lowest-common-denomintator hardware. An Atom N270 is a good benchmark. I'm looking forward to the results.

**Comment by daschuer** [comment]
Rough overview measured in filter stages to process: 

Bessel4 LV  0 .. 10 Stages
Bessel8 LV  0 .. 18 Stages
8 Band Graphic 0 .. 18 Stages
Linkwitz-Rriley8 32 Stages

**Comment by Be-ing** [comment]
Gprof output from my netbook with an Intel Atom N270:
[gprof-bessel4.txt](https://github.com/mixxxdj/mixxx/files/468912/gprof-bessel4.txt)
[gprof-bessel8.txt](https://github.com/mixxxdj/mixxx/files/468913/gprof-bessel8.txt)
[gprof-linkwitzriley.txt](https://github.com/mixxxdj/mixxx/files/468914/gprof-linkwitzriley.txt)

I selected the EQ type, turned the low EQ knob all the way down before loading a track (the same track each time), and played the whole track through. Keylock with Soundtouch was on without adjusting the tempo.

**Comment by daschuer** [comment]
Cool, it verifies my estimations: 

Total ms/call
0.32  Bessel4LVMixEQEffect::processChannel()
0.45  Bessel8LVMixEQEffect::processChannel()
1.12  LinkwitzRiley8EQEffect::processChannel()

63.2 % SoundDevicePortAudio::callbackProcessClkRef 

This is the audio main engine loop function
If we track down the CPU burners we find:

30.1 % PerChannelEffectProcessor<LinkwitzRiley8EQEffectGroupState>::process()
17.4 % EngineBufferScaleST::scaleBuffer()

So you see that 47 % of the Engine CPU time is spend for the  LinkwitzRiley. In the Bessel4 case it is only 20 %. 

Do you know that Mixxx has also an internal profiling features? 
It is enabled by mixxx --developer using the developers menu. 
You find the results in mixxx.log like 

Debug [Main]: Stat("SoundDevicePortAudio::callbackProcessClkRef 8, pulse_duration","count=159,average=1.20242e+06ns,min=180053ns,max=3.71398e+07ns,variance=9.87608e+12ns^2,stddev=3.14262e+06ns")

**Comment by Be-ing** [comment]
I'll run another set of tests later using the EQ on two decks.

**Comment by daschuer** [comment]
What is the use for the new test results? 

You will find out that the LinkwitzRiley8 EQ requires more CPU than the other EQs. 
If you disable all other CPU burner in the Engine thread, we will see that the majority of callback time is used by the EQs. 
We can construct cases where enabling the the LinkwitzRiley8 will cause buffer under runs, but the Bessel4 not. We can also construct cases where the CPU time for the LinkwitzRiley8 can be neglected. 

We can argue that recent CPUs are always able to process the LinkwitzRiley8 and the LinkwitzRiley8 is the best sounding EQ (I agree and and it is also a widely accepted opinion) 

But than we have still the issue, that it is not bit perfect at unity. 
Some times ago we had users complaining about that.  

The Bessel Lipshitz and Vanderkooy EQ allows us to make Mixxx bit perfect by default, but the EQs are still ready to use (not disabled) This is for me a good reason to stick at an alleged not optimal sounding EQ. 

By the way, if you search the web, you will find people complaining about dips at the crossover frequency using a pure Bessel crossover network. Our Bessel does not suffer this issue due to the LV mix.

**Comment by Be-ing** [comment]
> What is the use for the new test results?

Because the Bessel EQs were only working on one deck in the previous test but the Linkwitz-Riley EQ was working on two decks, so it wasn't a great comparison.

> We can construct cases where enabling the the LinkwitzRiley8 will cause buffer under runs, but the Bessel4 not.

Actually, I can't. Even running my netbook with a 1.45 ms buffer, the type of EQ used makes no practical difference. I only get 2 xruns playing a 2 minute track using EQs, regardless of EQ type (even with EQs off, I got 1 xrun, so I don't think those can be attributed to the EQs). If I turn on keylock with Soundtouch, I can play that track without any xruns with a 5.9 ms buffer. Again, using any type of EQ doesn't change that.

> We can also construct cases where the CPU time for the LinkwitzRiley8 can be neglected. 

I think the results above show it can always be neglected.

> But than we have still the issue, that it is not bit perfect at unity.
Some times ago we had users complaining about that. 

Why is that an issue? I haven't seen anyone complaining about that. I searched the bug tracker and forum and didn't see anyone asking for bit perfect playback. If anyone has asked for that elsewhere, it's a really niche concern. How it sounds when the EQ knobs are turned, which they very often are, is more important than theoretical perfection in particular circumstances. I can't hear any difference at all between Bessel4 and Linkwitz-Riley at unity using a high quality sound card and headphones (playing a FLAC file). If someone is really that concerned about bit perfection, they can switch to a Bessel EQ or turn the EQs off.

**Comment by Pegasus-RPG** [comment]
Were the gprof outputs not apples-to-apples?

**Comment by timrae** [comment]
I'm also in support of changing the defaults. The LR filter sounds much better, and buffer underruns with the default buffer size are extremely unlikely on any hardware made in the last ten years. People who are using very crappy hardware or require niche things like bit perfection are in the minority and they have options available to change the defaults. 

The default setting should be such that the majority of users are given the best user experience. The majority should not have to suffer average quality to protect the minority of users from changing the default latency / filter settings.

**Comment by daschuer** [comment]
> The LR filter sounds much better

Could you qualify the statement somehow? Is there an issue in the Bessel code which can be measured? 

The LV-Bessel is bit perfect at unity which cannot be beaten. In my use-case the EQs are at unity most of the time, so I benefit from the saved CPU and the best sound. I use them only during transitions with relative coarse actions. They sound well for me for that use case.  

What is your use-case?

**Comment by timrae** [comment]
> Is there an issue in the Bessel code which can be measured?

Fair call.

I had another play with the EQs just now, comparing the Bessel 8 (B8) with the LR16, and also the Serato Intro (SI) EQ. My conclusion is that the LR16 filter might actually be a bit too aggressive for the default. 

I made two recordings... In the first one I compare the B8, LR16, and SI filters with a song playing normal, and then with the LOW EQ fully cut. Here we can see that B8 and SI are relatively similar, while the LR16 is quite a lot more aggressive.

The same story can be told for the MID and HI EQs basically. In fact I found even the B8 was a lot more aggressive than the SI filters. TBH I didn't have motivation to do a lot of recordings after I made my mind up, but for the sake of objectivity, I at least made a second recording comparing the B8 HI EQ with the SI 
HI EQ.

So in the second recording I lower the HI EQ by one notch every 4 bars. If you skip to the last 4 bars in both sections, you'll see what I mean about the aggressiveness of the mixxx filters compared to SI. LR16 is even more aggressive (by design) in all cases, so I didn't feel it necessary to include that since B8 may already be more aggressive than new users are used to.

[EQ Comparison.zip](https://github.com/mixxxdj/mixxx/files/681587/EQ.Comparison.zip)

**Comment by Be-ing** [comment]
I don't understand why you think the LR is too "aggressive". Yes, it cuts out the band more completely when turned all the way down. Why is that a problem?

The Bessel EQs have a harshness to them when turned all the way down. I do not know why this is, but it sounds like there is something wrong. I avoided using EQs much to mix when I had it set to the default Bessel EQ because it sounded bad. The LR on the other hand sounds like the track has been changed but it doesn't sound distorted.

**Comment by Be-ing** [comment]
> The LV-Bessel is bit perfect at unity which cannot be beaten. In my use-case the EQs are at unity most of the time, so I benefit from the saved CPU and the best sound. I use them only during transitions with relative coarse actions. They sound well for me for that use case.

I think most DJs use EQs roughly how you describe. I don't understand why theoretical perfection (which is imperceptibly different to me than the LR at unity) at unity is more important than how it sounds when in use.

**Comment by timrae** [comment]
> I don't understand why you think the LR is too "aggressive". Yes, it cuts out the band more completely when turned all the way down. Why is that a problem? If that's not desired, don't turn the knob all the way.

I'm saying that the default behavior should be familiar for DJs coming from other hardware/software. I.e. it should sound similar to mixing with a DJM800 or using the default settings on Serato / Traktor. When you're mixing bass heavy music like dnb/techno, you would usually turn the bass EQ all the way down to zero on the track that you're bringing in, and then "swap" the basslines at some point. The sound is unfamiliar when you use the LR8 EQ, as demonstrated in my recording above.

> The Bessel EQs have a harshness to them when turned. I do not know why this is, but it sounds like there is something wrong.

I don't feel that it's hugely beneficial at this point in the discussion to speak subjectively about the sound of the filters. Can you give the steps to reproduce something that sounds obviously wrong? Preferably with a recording of an A/B comparison with an EQ that doesn't have the problem.

Maybe the answer is to improve the algorithm for the existing EQ rather than to change to a different EQ.

**Comment by Be-ing** [comment]
> I'm saying that the default behavior should be familiar for DJs coming from other hardware/software

Generally, yes, but I think sound quality is more important than that. If Mixxx can sound better than other systems, it should.

> I don't feel that it's hugely beneficial at this point in the discussion to speak subjectively about the sound of the filters. Can you give the steps to reproduce something that sounds obviously wrong?

I think the subjective sound of the EQs is all that there is to base this decision upon. IMO the recordings of the Bessel EQ you posted already demonstrate that they do not sound good.

> Maybe the answer is to improve the algorithm for the existing EQ rather than to change to a different EQ.

Perhaps that could help. I don't know enough about how EQs work to know if that's possible and practical. But we already have a great sounding EQ.

**Comment by daschuer** [comment]
It could be interesting to find out what kind of EQ SI or DJM800 uses. This can be done by playing and recording a sine sweep http://www.audiocheck.net/Audio/audiocheck.net_sweep20-20klog.wav in some EQ positions. These recordings can be than compared with the original to get a hint what they done with amplitude phase and roll-off. I think the Xone:22 is the best reference for good sounding EQ, can we get the hands on it?  

Tests: 
* all at unity 
* LP full kill 
* LP half 
* LP only 
* BP full kill 
* BP half
* BP only 
* HP full kill 
* HP half 
* HP only 

> I don't understand why theoretical perfection (which is imperceptibly different to me than the LR at unity) at unity is more important than how it sounds when in use.

I do not hear a difference at unity as well, but it is there. For me the main argument is that there is no CPU usage since in the majority of time, it is at unity. 

> I think the subjective sound of the EQs is all that there is to base this decision upon. IMO the recordings of the Bessel EQ you posted already demonstrate that they do not sound good.

Right, the LR Isolator, is known as one of the best sounding crossover network, but that comes with a cost of high CPU load. I think it is unusually in hardware mixers, since it is expensive to implement, 
so the sharp edges at the crossover frequency might be surprising for users coming from hardware. 

For me the Bessel LV-Sounds different, and good enough, to be a default EQ. 
The CPU is only used when turning the knobs. This allows the user to use Mixxx on not so recent hardware, without tweaking anything.

**Comment by Be-ing** [comment]
> I do not hear a difference at unity as well, but it is there. For me the main argument is that there is no CPU usage since in the majority of time, it is at unity.

Considering none of the EQs make no practical difference in whether I get xruns on my old netbook, I think the CPU usage is not an issue. Have you tested the different EQs on your netbook? Is there any difference in the minimum latency you can use without xruns?

**Comment by daschuer** [comment]
We already have nice test data: 
https://github.com/mixxxdj/mixxx/pull/1007#issuecomment-246616214

**Comment by Be-ing** [comment]
That data doesn't say anything about what practical difference that makes though.

Mixxx has Rubberband as the default keylock library. Yet I can't run that at any latency on this older laptop without xruns. I don't think we should make the defaults ideal for old hardware. The defaults should be optimal sound for today's hardware. If that doesn't work well for some users, that's what options are for. But users shouldn't have to choose less CPU intensive options at the expense of sound quality unless CPU is practically an issue for them.

**Comment by Be-ing** [comment]
BTW, Traktor uses its "Z ISO" EQ by default, [described as](https://support.native-instruments.com/hc/en-us/articles/210273465-EQ-and-Filter-Models-in-TRAKTOR-PRO-2):
>This is the same three-band EQ as found in the new TRAKTOR KONTROL Z2 DJ mixer. It is a full kill isolator EQ with a 24 db/octave slope, and sharply cuts the respective frequency band when turned fully counter-clockwise.

Catering to users coming from any system is arbitrary. We could look at any gear and it could use different EQs.

**Comment by ywwg** [comment]
> The defaults should be optimal sound for today's hardware.

I think this is a good rule of thumb.  Start optimistically, and then users on older hardware can try lowering quality as necessary to make it work.

**Comment by daschuer** [comment]
> I think this is a good rule of thumb. Start optimistically, and then users on older hardware can try lowering quality as necessary to make it work.

I disagree here, we should configure Mixxx in a way that it works without any issues on most devices by default, giving a good experience, in a way the user is willing to continue to give it a try. If a user has a recent device, he can tweak Mixxx for his personal needs, that might include CPU intensive features. 

The rubberband / soundtouch issue is a bit different, since both are disabled by default (keylock off) 

>This is the same three-band EQ as found in the new TRAKTOR KONTROL Z2 DJ mixer. It is a full kill isolator EQ with a 24 db/octave slope, and sharply cuts the respective frequency band when turned fully counter-clockwise.

Interesting. Traktor is considering a 24 dB/Oct slope a sharp. This explains that the LR 8 EQ sound to sharp and aggressive. This would be an argument to switch to our Bessel 4 by default or introduce a better sounding 4 pole filter. (Which is also used on the Traktor Hardware)

**Comment by Be-ing** [comment]
Your issue with the CPU usage is a non-issue. Have you actually tried using the different EQs on your netbook and experimenting with different latencies?

**Comment by Be-ing** [comment]
> The rubberband / soundtouch issue is a bit different, since both are disabled by default (keylock off)

Not really, because it should be expected that they are used if they're shown in skins.

**Comment by daschuer** [comment]
> Have you actually tried using the different EQs on your netbook and experimenting with different latencies?

Yes, on 11 ms latency, latency meter is at 1/2 when playing two decks with the Bessel Types at unity. With LR it is at 3/4. Using keylock (soundtouch) is possibel in both cases. With the LR it reaches the red end of the latency meter (red) but no underflows. 

Do you have Traktor installed? Am an curious to see the test results from:    
https://github.com/mixxxdj/mixxx/pull/1007#issuecomment-270592862

**Comment by Be-ing** [comment]
What are the specifications of your netbook @daschuer ?

> Do you have Traktor installed?

I don't have Windows or Mac OS X, so no.

**Comment by daschuer** [comment]
eeePC 901 Intel Atom N270 @ 1.6 GHz 2 GB Ram SSD

**Comment by Be-ing** [comment]
What OS?

**Comment by daschuer** [comment]
Mint 17.3 Rosa with Mate Desktop

**Comment by daschuer** [comment]
Mixxx High kill:
source
bessel4
bessel8
lr8

**Comment by Be-ing** [comment]
> on 11 ms latency, latency meter is at 1/2 when playing two decks with the Bessel Types at unity. With LR it is at 3/4. Using keylock (soundtouch) is possibel in both cases. With the LR it reaches the red end of the latency meter (red) but no underflows.

I can reproduce this on my netbook with the same Intel Atom N270 CPU and 2GB of RAM. I don't think this is an issue. These results are not bad; if a user was concerned they could change from the default EQ or raise the buffer size. It's pretty surprising these netbooks even work anymore considering their age. Netbooks have largely been obsoleted by tablets, smartphones, and cheaper laptops today. Choosing Mixxx's defaults in 2017 to squeeze every last bit of performance out of these old machines is pretty silly to me, especially considering that the change wouldn't even cause xruns at 11ms latency.

**Comment by Be-ing** [comment]
If you are concerned about Mixxx's performance on low powered hardware, taking care of [this bug](https://bugs.launchpad.net/mixxx/+bug/1641360) would be more helpful.

**Comment by rryan** [comment]
I think some of these concerns could be addressed by providing the user with better guidance on first run, or maybe if we detect a high rate of xruns popping a dialog like "Hey we noticed you're not getting a good experience, want to switch to lower-resource defaults?". 

I think we should be choosing our defaults for best user experience on modern hardware, too. (e.g. we still pick DirectSound as the default Sound API on Windows -- that's a recipe for user disappointment)

I think the strongest argument for the Bessel's is not performance, but that that they pass through the audio perfectly at unity (Audiophile Approved TM). We've had complaints about Mixxx's effect on the audio at unity settings before on the forums.

**Comment by Be-ing** [comment]
> I think some of these concerns could be addressed by providing the user with better guidance on first run, or maybe if we detect a high rate of xruns popping a dialog like "Hey we noticed you're not getting a good experience, want to switch to lower-resource defaults?".

That would be nice, but likely difficult to implement well.

> I think we should be choosing our defaults for best user experience on modern hardware, too. (e.g. we still pick DirectSound as the default Sound API on Windows -- that's a recipe for user disappointment)

The bigger issue with DirectSound, based on what people ask for help for on the forum, is that it does not support more than 2 channels, so users get confused when they cannot configure their headphone output.

> I think the strongest argument for the Bessel is not performance, but that that they pass through the audio perfectly at unity (Audiophile Approved TM). We've had complaints about Mixxx's effect on the audio at unity settings before on the forums.

This is a non-issue. The only complaint about this I can find is this [old forum thread](http://mixxx.org/forums/viewtopic.php?f=1&t=2998&p=14433) where the user actually wrote "bit-perfect _(or near it)_ playback capability" (emphasis mine). The user was actually complaining about a specific bug that cut off high frequencies and apparently was fixed for 1.11.

To repeat what I said above:
> I can't hear any difference at all between Bessel4 and Linkwitz-Riley at unity using a high quality sound card and headphones (playing a FLAC file). If someone is really that concerned about bit perfection, they can switch to a Bessel EQ or turn the EQs off.

**Comment by daschuer** [comment]
I think we have no strong arguments that beats one or an other EQ. 

The sharp edge of the LR sounds a bit like ringing compared to the Bessel. That can be a quality feature for one or the other depending on the personal taste. I think a test with Traktor default EQ, could help us to decide. The got good critics when changing the default to the new EQ. 

Who is able to record the sweep linked above with Traktor default EQ High kill?

**Comment by Be-ing** [comment]
I thought we were in agreement that the Linkwitz-Riley subjectively sounds better?

> I think a test with Traktor default EQ, could help us to decide. The got good critics when changing the default to the new EQ.

No, let's not try to be like Traktor. Let's try to sound good.

**Comment by timrae** [comment]
If you want to keep saying "sound good", this pr is never going to make any progress as we can't measure or agree on this... We want to choose a filter design (characteristic frequency, slope, phase characteristics) that behaves and sounds similar to common dj hardware (e.g. xone32, djm800) and software (e.g. Traktor) that is commonly considered to sound good by a large group of people.

LR8 doesn't meet this criteria (slope much larger than other hardware and software), so I don't think it's a good candidate. Rather, we should try to quantify the issues with the bessel via A/B comparisons, and look for ways to improve it or alternatives that meet the above criteria.

**Comment by timrae** [comment]
Maybe we go to a shop and just tell them we  can't decide between the A&H and Pioneer, and is it OK if we record how they sound on our laptop for our reference?

**Comment by timrae** [comment]
> No, let's not try to be like Traktor. 

Are you implying Traktor doesn't sound good?

**Comment by Be-ing** [comment]
> Are you implying Traktor doesn't sound good?

No, I'm saying that we shouldn't decide this based on what others do. Choosing which software or hardware to be more like is totally arbitrary. If we searched I wouldn't be surprised if we found one that sounds more like Mixxx's Linkwitz-Riley EQ, but based on that criterion there wouldn't be any reason to choose it over a different system.

**Comment by timrae** [comment]
Sounding "good" and "normal" can only be determined by a statistically
significant consensus, so it makes sense to look at the three most commonly
used designs for our design.

I'd be highly surprised if any of the designs I mentioned  use an 8 pole
filter.

**Comment by Be-ing** [comment]
> Sounding "good" and "normal" can only be determined by a statistically significant consensus, so it makes sense to look at the three most commonly used designs for our design. 

Good and normal are not the same. Sounding normal can only be determined by hearing what others do. Sounding good can only be determined by subjective opinion.

**Comment by timrae** [comment]
You previously asked what's "bad" about a large slope... It cut outs to a
larger extent the frequencies very close to the characteristic frequency
that you didn't intend. Like the kick drum when you only wanted the bass on
the LO EQ. This gives a less smooth transition when mixing. Also the
integrated signal intensity is lower.

Basically you need to recalibrate your brain on how to get the desired
sound you want, which is annoying and pointless for a default setting.

**Comment by Be-ing** [comment]
> It [the Linkwitz-Riley EQ] cut outs to a larger extent the frequencies very close to the characteristic frequency that you didn't intend.

Well, that depends on what you intend. When I see knobs labeled high/mid/low, I assume that when they're all the way down, there are no high/mid/low frequencies. You may have different assumptions based on your past experiences.

> Basically you need to recalibrate your brain on how to get the desired sound you want, which is annoying and pointless for a default setting.

Only if you assume it works other than how it does because of your past experience. If I was switching to Mixxx from another DJ setup, I'd assume it to work differently than what I am used to. Mixxx's master sync system works differently from Traktor, so DJs coming from Traktor need to adapt to use it in Mixxx. I don't think that's a problem. A large chunk of Mixxx users have no prior experience with DJ equipment and have no such expectations.

**Comment by ritschwumm** [comment]
i'd guess most DJs are after "smooth" transitions, and that means they should be as unnoticeable as possible _for the audience_. what do people notice? probably everything that sounds unusual, different from what your audience is used to. so, even if you have filter characteristics that do sound "better", it might still be a disadvantage.

**Comment by Be-ing** [comment]
When I first started using Mixxx I avoided using EQs for a long time because I felt it sounded bad. Since I changed my setting to Linkwitz-Riley I have been much more comfortable using EQs and my mixes have gotten smoother because of it.

**Comment by Be-ing** [comment]
> i'd guess most DJs are after "smooth" transitions, and that means they should be as unnoticeable as possible for the audience. what do people notice? probably everything that sounds unusual, different from what your audience is used to. so, even if you have filter characteristics that do sound "better", it might still be a disadvantage.

If we're going for unnoticable, IMO the Linkwitz-Riley fits that best. The way the Bessels change the sound is not hard to notice to me. If I forget to reset my EQ knobs to unity using the Bessels, in my opinion it sounds wrong. If I do the same using the Linkwitz-Riley, it's not a big deal.

**Comment by timrae** [comment]
Ok well it looks like everyone is open to changing the defaults, but there is no consensus to support using the LR8 at this time. My vote is to not use them. I think it'd be cool if we had several presets for hardware emulators like:
Pioneer (default)
Xone32
Xone92

And the underlying algorithms were only exposed in an advanced settings dialog.

**Comment by Be-ing** [comment]
> I think it'd be cool if we had several presets for hardware emulators

I'm not sure that should be in the GUI unless the EQs are specifically designed to mimic that hardware. However, it would be good to note which EQs sound more like which hardware mixers in the manual.

**Comment by timrae** [comment]
Yeah I mean the cutoff frequencies and slopes would be set to the exact
same values that we measure. These values have far more impact than the
actual algorithm used IMO, unless there's actually something wrong with the
algorithm.

**Comment by Be-ing** [comment]
The cutoffs are adjustable in the preferences. Maybe we should provide an easy way to set the cutoffs to mimic particular hardware mixers?

**Comment by timrae** [comment]
Yeah that's what I meant, a list view where you can choose presets. Some of
the presets might use a different slope (like LR8) or "kill" eq if the
hardware demands it.

In measuring the characteristics for these presets, maybe we settle on a
better algorithm, as we'll have A/B comparisons.

**Comment by ferranpujolcamins** [comment]
>
> Maybe we go to a shop and just tell them we can't decide between the A&H
> and Pioneer, and is it OK if we record how they sound on our laptop for our
> reference?

If you do this with the xone:92 I'll thank you for the rest of my life. A
Xone:92 clone is something I dream of for Mixxx, this is the first step I
wanted to do, never find time to do it :)


We are essentially discussing slope right? For me the best default option
is the one that best mimics Traktor, Serato and most used hardware mixers
Eq. Is that Bessel? If Bessel sounds worse because issues it has, lets fix
them.

Users can always change the default Eq if they have specific preferences,
let's make the default something standard.

2017-01-12 1:00 GMT+01:00 Tim Rae <notifications@github.com>:

> Yeah that's what I meant, a list view where you can choose presets. Some of
> the presets might use a different slope (like LR8) or "kill" eq if the
> hardware demands it.
>
> In measuring the characteristics for these presets, maybe we settle on a
> better algorithm, as we'll have A/B comparisons.
>

**Comment by Be-ing** [comment]
> If Bessel sounds worse because issues it has, lets fix them.

If anyone can identify what it is about the Bessels that sounds bad, sure. I figured that's just how the algorithm is, but I could be wrong.

**Comment by timrae** [comment]
The [user manual for the Xone32](http://www.allen-heath.com/media/XONE-32-USER-GUIDE-ISSUE-6.pdf) actually has a plot of the frequency response:

screenshot from 2017-01-12 17-25-29

Not so for the 92 unfortunately...

**Comment by daschuer** [comment]
It looks like the use standard EQs like what we have as 8 band EQ. Not a crossover network that allows full kill. It is very easy to hack up the 8 band EQ to a Xone32 type. 
The slopes are smother than our Bessel 4. Exactly the opposite what the LR8 does.

**Comment by daschuer** [comment]
The xone:92 is a very special EQ, it has four knobs, and combines two standard EQs like XONE:32 with two full cut types. https://bugs.launchpad.net/mixxx/+bug/1366680
So you have low and high kill for Mixing and two EQ knobs for the sound. Nice!

**Comment by ferranpujolcamins** [comment]
Are n-band eq posible right now? I mean, other than skin work and coding
the actual new effect, is there something more that needs to be changed?

**Comment by daschuer** [comment]
Task towards a Xone:92: 
* measure a original Xone:92 
* it is probably a combination of one our existing isolator IQ for High and low and two bequads from our 8 band EQ. 
* Add a fake Quick Effect which passes the Quick effect super knob to parameter 4 of the Equalizer Rack. 

I am currently working on a 3-Band Kill EQ which is the most common one legacy Hardware Mixers. 
https://bugs.launchpad.net/mixxx/+bug/1656681
I am curious to hear it compare to our current mixing EQs

**Comment by ferranpujolcamins** [comment]
2017-01-15 19:24 GMT+01:00 Daniel Schürmann <notifications@github.com>:

> Add a fake Quick Effect which passes the Quick effect super knob to
> parameter 4 of the Equalizer Rack.



I was thinking in something like:

   - Let EQs define a property to tell how many bands they have.
   - Let skins read this property and add knobs as needed.

This is similar to what Traktor does (which as you already know does not
mean neither good nor bad, it's just a fact).

What do you think?

**Comment by daschuer** [comment]
I am afraid the skinner will not like such a dynamic n-knob array in the center of the view. It is already a fight where to place the key and the filter knob. 

On the other hand the n-knob feature is already there, because the Equalizer Rack is just a renamed effect rack with different defaults. 

Reusing the Qick effect knob for the fourth EQ band, Is IMO very handy  
because it works for the Controller and for the GUI. The GUI still matches 1:1 to the controller. 

We have also discussed to use the gain knob as fourth EQ band. If we consider that, we need to decouple the GUI/Controller form the Internal CO values from the engine and allow to set a mapping form the EQ preferences.

I prefer this over scripting solution, since it will be "midi leanable" and it do not requires to touch all mappings, except changing the names to the new mappable knobs.

**Comment by ferranpujolcamins** [comment]
I move the n-band discussion to another thread.

2017-01-16 10:40 GMT+01:00 Daniel Schürmann <notifications@github.com>:

**Comment by ferranpujolcamins** [comment]
You might be interested in this to help you reverse engineering a filter:
https://es.mathworks.com/help/signal/ug/parametric-modeling.html#f11-7222

2017-01-16 13:40 GMT+01:00 Ferran Pujol Camins <ferranpujolcamins@gmail.com>
:

**Comment by Be-ing** [comment]
Anyone who has an opinion about the EQs, please test #1129 and note on that PR whether you think it should be the new default.

**Pull request closed without merging**
