### PR TITLE
Ignore the whole build folder during packaging

### PR DESCRIPTION
**Pull request by daschuer**
Buy default cmake ignores the build folder. But not in case you have two configurations side by side like: 

build/Debug
build/Release 

In this case the other folder is included in the package, leading to  a HUGE package. 

This PR fixes this.

### CODE REVIEW

**Comment by Be-ing** [comment]
Please let's merge #3550 first.

**Comment by Holzhaus** [comment]
`build` is an arbitrary name, the build directory could have *any* name. I usually name my build directory `supercalifragilisticexpialidocious`. Is there no other way to solve this?

**Comment by uklotzde** [comment]
> `build` is an arbitrary name, the build directory could have _any_ name. I usually name my build directory `supercalifragilisticexpialidocious`. Is there no other way to solve this?

I second that. It is just a convention, not a rule.

**Comment by daschuer** [comment]
Yes, we ignore also *_build wich is also just a convention. 
Calling the folder "build" is the most common convention. It is used by cmake4eclipse accordingly.

Let's make it a rule for Mixxx.

With your "supercalifragilisticexpialidocious" you have no problem as long you only build a single target.

If you have "supercalifragilisticexpialidocious_Debug" and "supercalifragilisticexpialidocious_Release" only the currently used build folder is aromatically ignored. 

To fix this you have to manually add not folders to the ignore list. 

A better solution is use either a _build prefixed folders or move both supercalifragilisticexpialidocious folders into the build directory or outside the source tree. Following the CMake conventions.

We should allow this without messing around with the CMakeListFile.txt.

**Comment by daschuer** [comment]
By the way: .git ignore has also the "build" folder ignored. So it should be consequently also be ignored here.

**Comment by Be-ing** [comment]
> By the way: .git ignore has also the "build" folder ignored. So it should be consequently also be ignored here.

I agree.

**Comment by Be-ing** [comment]
`build` is arbitrary but it is conventional and what we recommend in our build documentation so I think it's fine to assume the vast majority of users will name their build directory as `build`.

**Comment by Holzhaus** [comment]
okay, then let's merge.

**Comment by Be-ing** [comment]
Please merge #3550 first. IMO it is rude to make me deal with the merge conflicts when that PR has been sitting ready to merge.

**Comment by daschuer** [comment]
#3550 should not be merged at all. It is at least too early, given that the files are part of our current stable version.

Sorry if you feel that is rude. This was not my intention. 

It is just one line of code here, so it is nothing worth to complaining about IMHO.

**Comment by daschuer** [comment]
Can we merge this now?

**Review by uklotzde — APPROVED** [review]

**Comment by uklotzde** [comment]
@Be-ing Conflicts should not be hard to resolve. I leave it to you to merge this PR.

I would merge #3550 but others still disagree.

**Comment by Be-ing** [comment]
:shrug:

**Comment by uklotzde** [comment]
We need to make progress. Merging this now.

**Pull request merged**
