### PR TITLE
added a tool and a skin for day light

### PR DESCRIPTION
**Pull request by michelealbano**
Added a tool (intertcolor.py) to invert all the colors in a file, to be used with skins.

### CODE REVIEW

**Comment by michelealbano** [comment]
I developed a python script that visits the folders containing a skin, and re-creates in the current folder the same folder structure, copies locally the png / psd files, and for everything else it copies the files but inverts the colors.

This PR could solve issue https://github.com/mixxxdj/mixxx/issues/9217

**Comment by JoergAtGithub** [comment]
As a first-time contributor we need you to sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

**Comment by JoergAtGithub** [comment]
To fix the pre-commit fails automatically, please set up automatic code checking: https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking

**Comment by michelealbano** [comment]
Thank you but it's not working. When I commit, it either pass or skip all
tests, but it fails on github.
Can you point me to the documentation, so that I activate the local tests?
Thanks,
Michele

**Comment by JoergAtGithub** [comment]
Try to run `pre-commit run --all-files` from command line.
General documentation is here: https://pre-commit.com/

**Comment by michelealbano** [comment]
Thank you! I am working on windows, and I was ready to move everything
to my linux, but now it works.
... except that it complains a lot about res/controllers files, which
I did not touch :-P

**Comment by michelealbano** [comment]
I created a PR from another branch, to make the checks happy. See here:
https://github.com/mixxxdj/mixxx/pull/11748

**Comment by michelealbano** [comment]
moved to 
https://github.com/mixxxdj/mixxx/pull/11748

**Pull request closed without merging**
