### PR TITLE
Upgrade googletest from 1.8.x to 1.10.x

### PR DESCRIPTION
**Pull request by uklotzde**
The current master version did not work on macOS the last time I tried it. Only the last 1.10.x does.

I have stripped the `scripts` and `test` directories but kept `docs`.

How shall we handle with external dependencies in the future? I thought about downloading and installing the archive during the build instead of bundling the files like we do for libKeyFinder. With the new CMake build using unmodified versions that don't need to be bundled becomes possible.

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you. All green, so let's merge.

**Comment by Holzhaus** [comment]
Sigh, they still didn't fix https://github.com/google/googletest/issues/3040. Should be patch our copy manually?

**Comment by Be-ing** [comment]
We could, although we're using our minimum required CMake on CI.

**Comment by Holzhaus** [comment]
Yes, it's just annoying to see this warning all the time. I also see it when building locally.

**Comment by uklotzde** [comment]
1.10.x doesn't seem to receive any updates. We either have to upgrade to the current version or patch our bundled version.

**Pull request merged**
