### PR TITLE
Update contributor lists for the 2.3 release

### PR DESCRIPTION
**Pull request by daschuer**
I have updated the contributor lists. 
We move all contributors that have not added commits to the Mixxx repository for two years to the "Past Contributors" List. 

For 2.3 17 contributor have been moved to the past list and we have welcomed 11 new contributors.

### CODE REVIEW

**Comment by Be-ing** [comment]
Where are the new contributors? It looks like you only moved old ones to the past contributors list.

**Comment by daschuer** [comment]
The new one are added once there first PR has been merged.
It might has happened that I missed somone, did I?

**Comment by Be-ing** [comment]
Oh, I didn't realize that was already taken care of. LGTM then

**Comment by Holzhaus** [comment]
I think there are some people missing. We have 38 (10 release developers and 28 recent contributors) people in this list, but 44 people have contributed commits to this release (excluding merges).

```
$ git shortlog -s --no-merges upstream/2.2..upstream/master | wc -l
45
```

It's 44 people since RJ is included twice.

```
$ git shortlog -s --no-merges upstream/2.2..upstream/master
     1  Adam Szmigin
   289  Be
    18  Ben
     6  Codecat
     5  Cristiano
     8  Daniel Poelzleithner
   411  Daniel Schürmann
    63  Evan Dekker
   116  Ferran Pujol Camins
    55  Harshit Maurya
  1111  Jan Holthuis
     4  Josep Maria Antolín Segura
     8  JosepMaJAZ
    57  Kerrick Staley
    52  Matthew Nicholson
     1  Matthieu Imbert
     1  Nik Martin
   105  Nino Miškić-Pletenac
    14  Owen Williams
    10  Philip Gottschling
     4  Pradyuman
    28  RJ Ryan
    90  RJ Skerry-Ryan
    24  Raphael Graf
     1  Rebecca Wallander
    39  S.Brandt
     1  Sebastien Blaisot
     2  Sergey Ukolov
     2  Simon Harst
    10  Stéphane Lepin
    40  Swiftb0y
     2  Sébastien Blaisot
   685  Uwe Klotz
     1  YunQiang Su
     1  beenisss
     2  ehendrikd
    12  haslersn
     2  ketan-lambat
    17  luz.paz
     3  naught101
     4  ned haughton
     1  nikolas
     2  nopeppermint
   566  ronso0
     1  xerus2000
```

**Comment by daschuer** [comment]
Ups, I hit the delete branch button scrolling this PR on my phone.

Good idea @Holzhaus, I will go through the list probably some past contributors are back. And we normally do not list mapping contributors.

**Comment by Holzhaus** [comment]
When you pass the `-e` flag you can also see the email addresses (in case you don't recognize the name).

**Pull request merged**
