### PR TITLE
allow escape loops seeking backwards 

### PR DESCRIPTION
**Pull request by daschuer**
This fixes https://bugs.launchpad.net/mixxx/+bug/1716897
Now you can jump back to cue, or any other position and the loop remains active. 

This discovers also a "bug", that is jumps back to loop after changing the direction.
In this case we are suddenly "after" the loop.
How  should we handle this? Normaly we disable the loop if we jump after it. In this case it seems also be wrong.

### CODE REVIEW

**Comment by daschuer** [comment]
https://bugs.launchpad.net/mixxx/+bug/1669500 describes also the direction change issue.

**Comment by ronso0** [comment]
Cool, thanks for taking care of this.
Will test later on

> I have found a rounding issue when playing at fast rates.
OTOH this does not explain why it is fixes with FFmpeg 3.1

Do you mean 'fast rates' when scratching or just playing fast?

**Comment by daschuer** [comment]
Any fast speed. In you case scratching.

**Comment by ronso0** [comment]
Yeah, both issues are fixed!
I just tested with the files backward-scratching failed with (also failed with FFmpeg3.1).
Will test this for some more days.

**Comment by ronso0** [comment]
I doubt the loop should stay active when escaping it, either back or forth.
Loop-catch functionality should IMO be activated explicitly because it essentially (dramatically?) changes the playback flow. But here it's not activated on purpose, it's just 'still On' although the user escaped it.

So "bug or feature?" depends on the use use case. This is mine:
- bring a new song in
- fade out old song with a loop (not necessarily at the end)
- let the new song play (loop stays active, mostly because I forget about it)
- bring in the old song again from a Cue/Hotcue
- at that point I don't want to play the same loop again to repeat the former transition, so depending on where the loop was placed, it might screw up the replay of the old song and the new transition (if I forget the loop again...)

**Comment by daschuer** [comment]
We have introduced this catching loop behaviour here https://github.com/mixxxdj/mixxx/pull/1187
I think we did not consider your use case. Thinking about it again it is probably more clear to disable the loop always. The user can in any case Enable/Disable the loops as he wants, without jumping into the loop if the playposition is before the loop.

**Comment by daschuer** [comment]
Ready! Now it works nice. 
The Loop is now always disabled if you jump out of it. A jump from outside to outside position does not change the enable state of the loop.
This fixes also a bug that it could not enable a stored loop of a newly loaded Track.

**Comment by ronso0** [comment]
When I just tested again I noticed clicking "reloop" has no effect anymore when the play position is behind the loop. Before, it would jump from the later play pos to the loop_in position and enable the previously set loop.

What is the intention of "Allow scratching in front of an enabled loop"?
My expectation was that if scratching in front of an enabled loop, wouldn't get you caught in the loop as long as scratching is True.

**Comment by daschuer** [comment]
Oh, I will have a look. 

"Allow scratching in front of an enabled loop" was a commit, fixing a regression from a previous commit.

**Comment by daschuer** [comment]
Reloop works again.

**Comment by ronso0** [comment]
Yes, both bugs are fixed and reloop works again.
But.....while playing around with it I discovered another bug (no regression, it's also in master):
- play a track
- re-enable a previous loop way ahead of play position
- press loop_halve on controller or in GUI
- play position jumps to loop_in

**Comment by daschuer** [comment]
OK, It took me a three attempts to unscramble the code, but now it should be rock solid. 
@ronso0: Please give it a try.

**Comment by ronso0** [comment]
oh oh, it seems loop is not actually disabled although corresponding CO says so.
also, when reloop ('loop catch') is active, changing loop size would still force play position to jump inside that loop.

**Comment by ronso0** [comment]
This leads to some very strange behaviour, see [screen cast](https://weshare.me/b4c0540b0a723858/loopescape_bug.ogg)

**Comment by daschuer** [comment]
Ups, sorry I have moved some code outside the enabled check. Now it should work as it should.

**Comment by daschuer** [comment]
ready.

**Comment by Be-ing** [comment]
Could you add tests as you fix bugs to ensure they don't come back? The looping code is quite delicate.

**Comment by daschuer** [comment]
tests are in place now.

**Comment by ronso0** [comment]
Thanks for the hard work! All former issues are resolved.

Bad news: I found yet another two bugs and -while trying to reproduce those- n°3 popped up:
**1** when I moved a loop with `beatjump_size` smaller than 1 beat I can't resize that loop with loop_halve/double anymore (size in spinbox changes but not the actual loop)

**2** by pressing `loop_out` inside an active loop you can drag the `loop_out` point until released, but now playback leaves loop, loop stays active

**3** after ejecting and reloading a track, the loop is not restored. The loop IS restored when not I not eject that track but just load another one to that deck, than load the first track again

**Comment by daschuer** [comment]
Ready again. I could not reproduce 3 though, maybe it was fixed by 1 or 2 as well

**Comment by ronso0** [comment]
Thank you

> **1** when I moved a loop by beatjump_size < 1 beat I can't resize that loop with loop_halve/loop_double anymore (size in spinbox changes but not the actual loop)

not fixed yet, can reliably reproduce with 1/2 beat

There's a new bug: (it doesn't stop, sorry :)
if I scratch backwards while there's loop waiting way ahead, I get thrown into that loop.
Scratching forward works fine.

**Comment by daschuer** [comment]
Ups, Now I have switched to non const beatgrids (thought I had it already) 
Now I was able to reproduce your issue and solve it, hopefully.

**Comment by ronso0** [comment]
Uuh forget to mention I switched to non-const earlier..
Beside eject issue still persists, ...

 :boom: It's perfect now!  :+1:

**Comment by ronso0** [comment]
> Beside eject issue still persists, ...

It's in master too
[Bug 1732797](https://bugs.launchpad.net/mixxx/+bug/1732797)

**Comment by daschuer** [comment]
@Be-ing: can we merge this?

**Comment by Be-ing** [comment]
I'll give it some manual testing soon. Is there anything in particular I should test for?

**Comment by daschuer** [comment]
@ronso0 has already done good manual testing, more is always better. 
I originally want to ask if you are going to finish you code review?

**Comment by Be-ing** [comment]
I was not intending to do more code review, but I could if you want me to.

**Comment by daschuer** [comment]
We need a formal LGTM before merge. If you wish to do more code review for it I would be happy.
On the other hand I do not want to put extra work on you, since @ronso0 has followed and tested this PR step by step.

**Comment by Be-ing** [comment]
I added quite a lot of tests in #1187, so I'm not too concerned about regressions if the tests pass and @ronso0 has done manual testing. Too bad we do not have reliable CI services here on GitHub. Can you verify that the tests pass locally?

**Comment by daschuer** [comment]
Test are passing locally.

**Comment by daschuer** [comment]
Can we merge this now, or is something else to do?

**Comment by uklotzde** [comment]
I'm not familiar with this part of the code. It looks very complicated and there are lots of oddities like +/-2 for the next/previous sample frame. A complete rework will be necessary after switching the engine to a more appropriate frame indexing scheme and doubles. So let's just make it work and don't touch anything out of scope now ;)

I will give it a short test run.

**Comment by uklotzde** [comment]
Much better than before, LGTM. I tried to test all the use cases that were mentioned and some more. Of course, I'm not able to decide if the code covers  all possible cases correctly, too many paths ;)

Finding: Setting loop in and out markers works differently. Adjusting the in marker somewhere before an already existing out marker just (re-)sets this marker, leaving the loop disabled. Setting the out marker also activates the adjusted loop immediately, but the track keeps playing beyond this newly set out marker. Pressing loop out again now jumps to the in marker and into the loop, i.e. similar like pressing reloop. Does this work as designed?

**Comment by daschuer** [comment]
Good catch. I think this is a side effect, because you usually set the loop in marker before the loop out maker, where there is no loop we can enable. 

The use case of question is, adjusting a catching loop while playing.
IMHO the user adjust the loop to actually use it. He may have not enough time to enable the loop manually, so we should enable it in this case as well.

**Comment by uklotzde** [comment]
I agree. The loop might be short and setting the loop in marker should also enable the loop while entering it. If I press the in marker again within a loop it will be adjusted and the remaining part should be looped. Of course, this only applies if the loop in marker is strictly before an already set loop out marker.

The other question: Should pressing the loop out marker beyond an already activated loop again really jump to the beginning of the loop like pressing reloop? Or wouldn't it be more reasonable to extend the loop up to this point alike pressing the loop in button which will shorten the loop after this point.

And then all this must work mirrored when playing in reverse. I did not test this.

**Comment by daschuer** [comment]
> The other question: Should pressing the loop out marker beyond an already activated loop again really jump to the beginning of the loop like pressing reloop? Or wouldn't it be more reasonable to extend the loop up to this point alike pressing the loop in button which will shorten the loop after this point.

I do not understand the question. You cannot set a loop out marker behind an activated loop. You can also not set a loop out marker before a loop. You can only set a loop out marker behind a loop in marker. Since we activate the loop, it is quite natural that the playposition jumps to loop in as usual. 

I have tried to hard make everything working in forward and backward direction, but it was not possible in every detail, because of the different loop jump out and loop catching logic. IMHO this part works just right though.

**Comment by uklotzde** [comment]
I don't use loops very often, so don't take my questions too serious ;)

LGTM. And since everyone seems to be happy we are ready to merge this work, aren't we?

**Comment by daschuer** [comment]
Thank you :-)

**Review by uklotzde — CHANGES_REQUESTED** [review]
Tests enter an infinite loop

**Comment by daschuer** [comment]
ready.

**Comment by ronso0** [comment]
Shall I test it again with my controller?

**Comment by daschuer** [comment]
Yes, an other test can't hurt. Thank you.

**Comment by uklotzde** [comment]
Now tests are failing:
```
[  FAILED  ] 9 tests, listed below:
[  FAILED  ] LoopingControlTest.LoopOutButton_QuantizeDisabled
[  FAILED  ] LoopingControlTest.LoopOutButton_QuantizeEnabledNoBeats
[  FAILED  ] LoopingControlTest.LoopOutButton_AdjustLoopOutPointOutsideLoop
[  FAILED  ] LoopingControlTest.LoopOutButton_AdjustLoopOutPointInsideLoop
[  FAILED  ] LoopingControlTest.ReloopToggleButton_TogglesLoop
[  FAILED  ] LoopingControlTest.LoopScale_DoublesLoop
[  FAILED  ] LoopingControlTest.LoopDoubleButton_DoesNotResizeManualLoop
[  FAILED  ] LoopingControlTest.LoopHalveButton_DoesNotResizeManualLoop
[  FAILED  ] LoopingControlTest.LoopMoveTest
```

**Comment by daschuer** [comment]
OK, now it should be done. At least tests are not failing (sorry for not testing them before).
Now we have double everywhere and I managed to get rid of most these odd +2 -2 statements.

**Comment by uklotzde** [comment]
Is still see one test failing due to rounding errors (GCC 7.2.1):
```
src/test/looping_control_test.cpp:530: Failure
Value of: m_pLoopEndPoint->get()
  Actual: 300
Expected: 300
src/test/looping_control_test.cpp:555: Failure
Value of: m_pLoopEndPoint->get()
  Actual: 300
Expected: 300
...
[  FAILED  ] LoopingControlTest.LoopMoveTest
```

**Comment by uklotzde** [comment]
Only rounding errors. With EXPECT_NEAR and a delta of 10⁻⁹ the tests pass.

**Comment by daschuer** [comment]
Interesting that this fails compiler dependent.

**Comment by uklotzde** [comment]
I'm still a bit concerned about the complete removal of those strange +/-2 adjustments. The meaning of the code has changed and the behaviour should be different than before. On the other hand it seems to work when using floating point calculations without the adjustments.

**Comment by uklotzde** [comment]
LGTM. Thank you, Daniel.

**Pull request merged**
