### PR TITLE
CMake: fix TagLib linking on macOS

### PR DESCRIPTION
**Pull request by Be-ing**
The old module relied on the taglib-config script that taglib's
build system writes hardcoded absolute paths into. That was
problematic for the macOS build environment which required
replacing those absolute paths before building. This new CMake
module does not require modifying any taglib files.

### CODE REVIEW

**Comment by Be-ing** [comment]
I just copied & pasted the libebur128 CMake module then did a find-and-replace.

**Comment by Be-ing** [comment]
[macOS build succeeded](https://github.com/mixxxdj/mixxx/runs/1404139374)

**Comment by Be-ing** [comment]
Travis failure for macOS SCons build is unrelated. All other CI passed.

**Review by uklotzde — APPROVED** [review]
Seems to work as expected. @Holzhaus?

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
