### PR TITLE
When loading a track that has a loop defined, prefill beatloop_size

### PR DESCRIPTION
**Pull request by ywwg**
if one matches.

I tried to create a test but couldn't figure out how to set a Loop cuepoint before the fake tracks get loaded.

### CODE REVIEW

**Comment by daschuer** [comment]
LGTM, Thank you.

**Comment by Be-ing** [comment]
This was [considered](https://github.com/mixxxdj/mixxx/pull/1187#issuecomment-280878010) but decided against in #1187. I haven't played with this yet, so I'm not sure if this is a good change but I think there should have been more discussion before merging this. @JosepMaJAZ have your thoughts changed since #1187 was merged? Do you think this is a good change?

**Comment by daschuer** [comment]
Oh sorry, I forgot about this.
What are the pros and cons?

**Comment by Be-ing** [comment]
I think the downside is that it could be unexpected to have the loop size change without the user explicitly asking for that. But I think I understand why @ywwg implemented this. It is inconvenient to have to adjust the loop size on track load before loop_double/halve do anything.

**Comment by ywwg** [comment]
I could see modifying this so that we don't change beatloop_size, but when loop_double/halve is pushed and there's an existing loop, we detect its length and then apply the modification.  It wouldn't be too hard to tweak that.

**Comment by Be-ing** [comment]
I think that would unnecessarily create a confusing situation.

**Comment by daschuer** [comment]
I have tested this again and I am still convinced that this PR was a good change. 
In 2.2, we load a track with an existing loop. It changes only by the beatloop box if we hit by chance the current size. From that moment it behaves exactly like this PR. 

Pro:
In 2.2 you load a Track with an existing loop at the end of the track. You are not able to adjust it until you hit it's size. After this PR you have can initially adjust it. 
You don't have an indicator if the size has snapped in or not. 

Contra:
If you want to set a new loop you need to have a look at the loop size box. You cannot rely on the previous used size.

**Comment by Be-ing** [comment]
>  If you want to set a new loop you need to have a look at the loop size box. You cannot rely on the size used with the previous track.

I think that's a reasonable tradeoff to avoid the old situation where it could be confusing why change the loop size doesn't resize an existing loop.

**Pull request merged**
