### PR TITLE
PaleMoon contrast, SVG optimize, small fixes

### PR DESCRIPTION
**Pull request by ronso0**
* BPM Tap button now spans BPM and rate% (and matches previous hover highlight)
* picking up @Holzhaus's inspiration we now have a pale logo
image
image

### CODE REVIEW

**Comment by ronso0** [comment]
- [ ] Windows: remove useless dotted focus border from effect selector and AutoDJ mode selector

**Comment by Holzhaus** [comment]
Thanks.

Just a minor node: I think it would look better if there were less different shades of grey in the toolbar. Could we use #444444 or #A89A8C (like the battery icon and the clock)?

**Comment by ronso0** [comment]
I'll test that

**Comment by ronso0** [comment]
the small logo is now painted d like the charged battery, please take a look.

> * [ ]  Windows: remove useless dotted focus border from effect selector and AutoDJ mode selector

nice to have, doesn't block this PR though.

**Comment by Holzhaus** [comment]
Awesome, thank you!

**Pull request merged**
