### PR TITLE
DlgTrackInfo improvements

### PR DESCRIPTION
**Pull request by ronso0**
* [x] move track comment to Summary tab, remove Comments for quicker track editing
* [x] add Star rating below cover art to have ALL track properties in the dialog
* [ ] add "Export metadata to file.." button

### CODE REVIEW

**Comment by ronso0** [comment]
Eventhough the cover could theoretically spread over 4 rows it didn't because the labels/fields below don't grow.
Thus the star rating easily fits in row 4:
image

**Review by daschuer — APPROVED** [review]
LGTM, and also works good. Thank you.

**Comment by daschuer** [comment]
Waiting for CI

**Comment by ronso0** [comment]
Actually, to round up the metadata editing workflow, we should have an `Export metadata to file tags` button in the dialog, too. 
so, after editing via decks one can easily & instantly make sure the metadata is exported

**Comment by uklotzde** [comment]
> Actually, to round up the metadata editing workflow, we should have an `Export metadata to file tags` button in the dialog, too. directly below "Re-import.."
> so, after editing via decks one can easily & instantly make sure the metadata is exported

This is not the case. Export of metadata is always deferred until all track references have been dropped.

**Comment by daschuer** [comment]
> This is not the case. Export of metadata is always deferred until all track references have been dropped.

We may visualize the "dirty" flag than. In the context menu we have the "Export to file Tags" I think that works nice together.

**Comment by daschuer** [comment]
While we are talking about improvements. I really like to have an autocomplete feature for the genre field. 
Is this difficult?

**Review by Holzhaus — APPROVED** [review]
LGTM. CI fail is unrelated.

**Pull request merged**
