### PR TITLE
Mapping Hercule P32: Add pitch management

### PR DESCRIPTION
**Pull request by pierrelegall**
The pitch management inputs (`sync_key`, `pitch_up`, `pitch_down` and `reset_key`) have been added to the 4 right pad buttons of the loop mode.

### CODE REVIEW

**Comment by Holzhaus** [comment]
Thank you. In order to review the changes properly and to inform other users, please open a corresponding Pull request at the mixxxdj/manual repo and document the new behavior: https://github.com/mixxxdj/manual/blob/2.3/source/hardware/controllers/hercules_p32_dj.rst

**Comment by lepieru** [comment]
Documentation added here: https://github.com/mixxxdj/manual/pull/338

**Comment by Be-ing** [comment]
Nice idea. I think it would help to make the colors of these newly mapped buttons distinct from the unrelated buttons on this page. I suggest using red for off and purple for on. What do you think?

**Comment by lepieru** [comment]
I don't see how to do better than this colors :thinking:

There are already separated to the other features by the blue buttons (for reloop_toggle it's red when loop is active).

Before: https://pbs.twimg.com/media/ErC5V6IXUAAZJNk?format=jpg
After: https://pbs.twimg.com/media/ErC5X0EXAAIZy86?format=jpg

**Comment by lepieru** [comment]
I have no objection to change the colors after some user feedbacks. But maybe you don't want any color changes after a merge into 2.3?

**Comment by Be-ing** [comment]
I tested with my P32 using red for the off state of these new buttons and purple for the on state and I thought it helped distinguish them.

**Comment by Holzhaus** [comment]
@Be-ing when merging a mapping change, please always merge the corresponding manual PR, too.

**Comment by Be-ing** [comment]
Whoops, thanks for the reminder.

**Pull request merged**
