### PR TITLE
Migrate SoundSourceMediaFoundation from a plugin to a core SoundSource.

### PR DESCRIPTION
**Pull request by rryan**
Now that Mixxx's minimum required version is Windows 7, we no longer need to make this an optional plugin for Windows Vista+.

### CODE REVIEW

**Comment by daschuer** [comment]
What happens if a mediafoundation plugin dll is found as well?

**Comment by rryan** [comment]
> What happens if a mediafoundation plugin dll is found as well?

Great question... maybe we need a blacklist?

**Comment by rryan** [comment]
> > What happens if a mediafoundation plugin dll is found as well?
> 
> Great question... maybe we need a blacklist?

Instead of adding a blacklist I just ignore any plugin with an exact name match. Since there are only 3 plugins ever made a blacklist might be overkill :grin:.

**Comment by rryan** [comment]
@JosepMaJAZ tested the x64 AppVeyor build on Windows 7 and says it works fine.

**Comment by rryan** [comment]
@uklotzde when you have a chance would love a review. Please make sure I got all the SoundSourcePlugin -> SoundSource changes that are needed.

**Comment by uklotzde** [comment]
I currently don't have a Windows build environment, but all the code changes look good to me. Registering the SoundSourceProvider in the SoundSourceProxy is sufficient for enabling it.

Blacklisting the legacy plugin is a good idea that I even didn't think of :+1:

**Comment by uklotzde** [comment]
As expected the new SoundSource is used during the tests for reading M4A files:
```
...
[00:40:55] Skip and read test: "C:/projects/mixxx/src/test/id3-test-data/cover-test.m4a"
[00:40:55] SoundSourceProxy - Opening file "file:///C:/projects/mixxx/src/test/id3-test-data/cover-test.m4a" with provider "Microsoft Media Foundation" using mode Strict
[00:40:55] SoundSourceMediaFoundation - Number of channels in input stream 1
[00:40:55] SoundSourceMediaFoundation - Requested number of channels 2
[00:40:55] SoundSourceMediaFoundation - Samples per second in input stream 44100
[00:40:55] SoundSourceMediaFoundation - Sample buffer capacity 4096
[00:40:55] SoundSourceMediaFoundation - Frame index range [0 -> 1328128)
...
```

**Comment by rryan** [comment]
Thanks @uklotzde! Unless there are other comments, I'll merge today.

**Pull request merged**
