### PR TITLE
Fix automatic QML type registration for Qt 6.3.x

### LINKED ISSUE #10854: Experimental QML UI does not load with Qt 6.3
Currently, Mixxx fails to start when built with Qt 6.3.

I already spent some hours debugging it, but to no avail.

Using Qt 6.3.1 on ArchLinux, I'm getting the following terminal output when running Mixxx:

```
warning [QQmlThread] Binding on contentItem is not deferred as requested by the DeferredPropertyNames class info because one or more of its sub-objects contain an id.
warning [QQmlThread] Binding on background is not deferred as requested by the DeferredPropertyNames class info because one or more of its sub-objects contain an id.
warning [QQmlThread] Binding on background is not deferred as requested by the DeferredPropertyNames class info because one or more of its sub-objects contain an id.
warning [QQmlThread] Binding on handle is not deferred as requested by the DeferredPropertyNames class info because one or more of its sub-objects contain an id.
warning [Main] QQmlApplicationEngine failed to load component
warning [Main] file:///path/to/mixxx/res/qml/main.qml:91:21: Type DeveloperToolsWindow unavailable
warning [Main] file:///path/to/mixxx/res/qml/DeveloperToolsWindow.qml:115:20: Mixxx.ControlSortFilterModel is not a type
critical [Main] Failed to load QML file "/path/to/mixxx/res/qml/main.qml"
```

### PR DESCRIPTION
**Pull request by Holzhaus**
Works around [QTBUG-104373](https://bugreports.qt.io/browse/QTBUG-104373).

### CODE REVIEW

**Comment by Holzhaus** [comment]
Yikes, now we have a mismatch between CI qmlformat and local qmlformat because it's a system depedency that does not allow pinning :(

**Comment by Holzhaus** [comment]
I removed the formatting changes for now, I'll take care of that in a separate PR.

**Comment by m0dB** [comment]
Fix confirmed! It actually works with library and playback and all!

**Comment by Holzhaus** [comment]
Shall we merge then?

**Comment by m0dB** [comment]
Sounds good to me. But I wonder how you have been able to commit: When I try to commit qml files (e.g. main.qml without any actual changes) qmllint fails:
```
Warning: res/qml/main.qml:2:1: Warnings occurred while importing module "Mixxx":
import Mixxx 1.0 as Mixxx
^^^^^^
---
Warning: Failed to import Mixxx. Are your include paths set up properly?
---

Warning: res/qml/main.qml:73:25: Unqualified access
                        Mixxx.PreferencesDialog.show();
                        ^^^^^
```
Doesn't this happen to you?

**Comment by m0dB** [comment]
I see I can run qmllint successfully with these arguments:
```
qmllint -I build/qml/Mixxx/ -i build/qml/Mixxx/qmldir res/qml/main.qml
```

**Comment by m0dB** [comment]
> Yikes, now we have a mismatch between CI qmlformat and local qmlformat because it's a system depedency that does not allow pinning :(

Any suggestions how to deal with this? BTW, I notice that 6.3.2 qmlformat does some weird stuff, like this:
```
-            Skin.FadeBehavior on visible {
+            Skin.FadeBehavior on visible  {
```

**Comment by Holzhaus** [comment]
>> Shall we merge then?
>
> Sounds good to me.

We have a policy of not merging our own PRs, so this was just a small hint to the other core team members to have a look :wink: 

Regarding qmllint, this is clean on my machine. If it doesn't work for you, you probably have a different qmllint version installed.

```
$ pre-commit run qmllint --all-files
qmllint..................................................................Passed
$ qmllint --version
qmllint 1.0
```

>> Yikes, now we have a mismatch between CI qmlformat and local qmlformat because it's a system depedency that does not allow pinning :(
>
> Any suggestions how to deal with this? BTW, I notice that 6.3.2 qmlformat does some weird stuff, like this:
> ```
> -            Skin.FadeBehavior on visible {
> +            Skin.FadeBehavior on visible  {
> ```

Let's discuss this on #10929.

**Review by Swiftb0y — APPROVED** [review]
Code LGTM. Waiting for my local build so I can confirm with a smoke test. Thanks.

**Comment by Swiftb0y** [comment]
fyi I unwatched the repo. So please @ me or request a review if you need my involvement.

**Comment by Swiftb0y** [comment]
works with Qt 6.3.1 :heavy_check_mark:

**Comment by Holzhaus** [comment]
Thanks!

**Pull request merged**
