### PR TITLE
Fix disappearing fader handles for Deere skin

### PR DESCRIPTION
**Pull request by esbrandt**
If linked against QT 5.14.0, the fader handles can become invisible, depending on the position of the handle. Fixes [lp:1857813](https://bugs.launchpad.net/mixxx/+bug/1857813)

Copying parts of my comments from launchpad.net:
> There was a svg viewport fix in 5.14 worth investigating
https://bugreports.qt.io/browse/QTBUG-70256

> Another aspect of the bug is that stretching images inside mixxx do not work as they used to be.
 As seen in OP´s video [#1](https://bugs.launchpad.net/mixxx/+bug/1857813/+attachment/5316231/+files/2019-12-29%2016-46-40.mkv). The crossfader slider stretch is off, compared with QT 5.13.

>  Also, at least on macOS, there are major performance issues with this specific QT version.
On my machine, mixxx is at 100% CPU even while idle, just trying to render images.

> It appears there have been some changes to the graphics stack .
https://wiki.qt.io/Qt_5.14_Release

 > As said, apparently there is an issue with mixxx internal STRETCH image function. The crossfader slider graphic ``slider-crossfader.svg`` does not stretch (expand) correct to the sliders widget size, but the ``slider-crossfader-AutoDJ.svg`` , active when using AUTODJ and defined in ``style.qss`` does.

**Post**:
Screenshot 2020-01-17 at 12 02 05

**Pre**:
Screenshot 2020-01-17 at 12 18 46

### CODE REVIEW

**Comment by ronso0** [comment]
Did this also solve the high CPU issue?
If not, is it down to normal with minimal decks?

**Comment by esbrandt** [comment]
There is no noticable change in CPU utalisation.

**Comment by uklotzde** [comment]
What was causing the display issues and what did you fix in the SVG files? I don't get it by looking at the changes.

Are there still issues in the code and are we able to either fix them or otherwise need to add some TODO/FIXME comments?

**Comment by ronso0** [comment]
the slider handle SVG had some transform operations like scale, translate & rotate. now they're plain patht/rectangles.

**Comment by uklotzde** [comment]
Works fine on XWayland with Qt 5.13.2.

Anything else to do or merge as is for some broader testing? No further regressions expected IIRC?

**Review by Holzhaus — APPROVED** [review]
I can reproduce this issue with Qt 5.14.0 and this patch fixes it for me. Nice!

**Comment by uklotzde** [comment]
With Jan's approval LGTM.

**Pull request merged**
