### PR TITLE
Channel handle

### PR DESCRIPTION
**Pull request by daschuer**
This is now a version that uses the EffectChainManager as indexing Domain for the Effect framework. 

This has some advantage, the registration process is streamlined. 
Imho it is also better to understand, base it focuses exactly the problem.

I have changed the indexing container class to a QList, that allows much (x45)  faster iterations over the whole list.
Hers some test data for container class filled with key values from 0 ... 999
The time is in ns for 10000 iterations.

Iteration
Debug [Main]: list      51,314,075 
Debug [Main]: set 2,296,160,300 
Debug [Main]: map  262,436,844 

Contains()
Debug [Main]: list    41,891,643 
Debug [Main]: set   10,882,746
Debug [Main]: map 24,066,919 

I have also noticed that you have placed some todos for removing the list access. 
They are not at time critical path, but removing this will need some work we can do later.

### CODE REVIEW

**Comment by rryan** [comment]
Hi Daniel,

Thanks for taking the time to create a PR that outlines the idea. I warned you in #495 that I disagreed with this when you described it in words. I still disagree with it now that you've written it in code. 

Right now the ChannelHandle is only used for effects but future engine features will surely need a nice way to do associative lookups by channel.

Regarding your other changes in this PR:
* Renaming ChannelHandleAndGroup's "name" parameter to group is a good idea. I didn't feel up for it once I had cleared up the naming issues in the prior PR.

* Changing from QSet to QList for the list of registered effect groups. Performance-wise this code doesn't matter since it's not in the callback. It's a rounding error compared to all the allocation and other operations happening around it on the main thread.

**Comment by rryan** [comment]
> Debug [Main]: set 2,296,160,300 
> Debug [Main]: map 262,436,844

By map do you mean QMap?

**Comment by daschuer** [comment]
By map do you mean QMap? Yes.

**Comment by daschuer** [comment]
> Performance-wise this code doesn't matter since it's not in the callback.

This statement is not true in any case. Remember, that we have a limited amount of CPU speed. 
It does not matter in which thread the CPU work is done, once there is some, it consumes CPU time. 
And when we have a way to reduce CPU time in any thread, whole Mixxx will benefit from it.  

To be honest, I did not expect that you will agree to this, without objection. 
But I am fully convinced that this the best way to go. 
* Keeping group/item where ever possible/suitable 
* Using indexes in specific domains. 


> ... for effects but future engine features will surely... 

According to YAGNI, we should not do predict such demands. 
My solution requires less code and less CPU and still fits to the original problem.
(By the way, it is only a minor detail, the majority of you ideas are still included) 

The other engine Feature: EngineMaster does not need it. There is also the SoundDevice registering, which does not need it as well. What could be a future feature that benefits from it? 

You know that I already working on a StringAtom as a 1:1 replacement of QString for group and items. 
You are right that I have not proven the performance gain of this change but I am curios to see if there is on.

Appart of the performance discussion, this will also offer an unique handle to a group, which can be used allover Mixxx, not only in the engine.  I hope I will finish a fist version soon. This should of cause not block 1.12 since the biggest performance issues are solved now. 

I have done this PR, because it allows us to postpone the ChannelHandle/StringAtom discussion to a point where we have valid data to decide what is the best best solution for the next engine feature is we are planing at that time.

**Comment by rryan** [comment]
> This statement is not true in any case. Remember, that we have a limited amount of CPU speed. 
> It does not matter in which thread the CPU work is done, once there is some, it consumes CPU time. 
> And when we have a way to reduce CPU time in any thread, whole Mixxx will benefit from it.

Obviously yes there is a finite number of cores and clocks per second. That is not my point. 

The decision between whether to use a QSet or QList is a rounding error in terms of our overall CPU usage outside the callback. 

When the performance impact is negligible, I use the right data structure for the job (in this case, a unique list of channels that have been registered). When it is identified as an issue in profiling then I make changes.

> YAGNI

I don't follow this principle. I build a system that I think will be maintainable and future proof. 

> we should not do predict such demands. 

I have some experience predicting what we will need in Mixxx. I'm not bad at it.

> You know that I already working on a StringAtom as a 1:1 replacement of QString for group and items. 
You are right that I have not proven the performance gain of this change but I am curios to see if there is on.

I already gave you strong feedback that you're on the wrong path with StringAtom. You haven't responded to any of the issues I raised.

**Comment by daschuer** [comment]
> I already gave you strong feedback that you're on the wrong path with StringAtom. You haven't responded to any of the issues I raised.

The issues you have raised are all valid points and good ideas. I just had not the time to finish a first version, generate test data and fix the issues. I want to just save us from a discussion if it turns out that I was really on a wrong track. 

> When the performance impact is negligible, I use the right data structure for the job (in this case, a unique list of channels that have been registered). When it is identified as an issue in profiling then I make changes.

Sorry, but did you look at the code? QList is the right container for fast iterations, QSet for fast lookups. 
I have changed the container to QList that is used for iterations only. 
And I have removed all the unnecessary container classes. It is just unused code we just do not need. 

You can pull down any arguments with: "a rounding error amount" but since this is new code it is quite normal to pull out any issues even though they are minor. 

> I have some experience predicting what we will need in Mixxx. I'm not bad at it.

This is probably correct and I appreciate that, but it is not a good idea to go with a single person's guts and introduce unused code without having outlined the good reasons for it. 
And even if you have one, it is much better to introduce it once we have a real demand. You may keep it in a branch and put a hind in the code that other developer can find it.

**Comment by rryan** [comment]
> Sorry, but did you look at the code? QList is the right container for fast iterations

The usages of this container include insertion, containment checks and iteration. A QSet happens to satisfy these three operations in amortized constant time since it is implemented as a hash map. When I'm not prematurely optimizing, I use a concrete data structure that best matches the abstract data type I aim to represent.

You can implement a set with a QList by paying a linear insertion cost to check for duplicates. You make a reasonable argument that our usage of the container (n~=32, iterate more than insert) may make a linear insertion cost (primarily paid during Mixxx startup) worth taking in order to speed up iteration since it seems QList's constant factors outpace QSet in micro-benchmarks you presented. So we can swap out the set ADT implementation we use to get a speedup.

Great! So you sped something up by 45x. But if you you've improved 0.0001% of the CPU work we do in Mixxx by 45x, was that really worth your time? 

> My solution requires less code and less CPU and still fits to the original problem.

To be clear, there are 3 distinct changes in this branch. 

One of them has a CPU improvement that you've demonstrated in a micro-benchmark. It's a fine change to make. However, I don't think it was worth the keystrokes, assuming you value your free time as much as I value mine. I'm trying to urge you to better allocate your time in the future -- I'm not arguing against making the QSet -> QList change now that you have written it.

The contentious change we are discussing comes down to opinion. I don't agree with the change.

**Comment by daschuer** [comment]
Your are so opinion your original solution is the best. I am the opinion, it is good, since it solves the original problem, but we can do better. I know that it is hard for me to place critics, because your work is already merged. For me it is worth to spend my time now because I am really convinced that we are heading into a direction that does not suite well for undefined future problems, but it is hard to revert later.   

Lets get back to a mode where we compare arguments. 

My main concerns are not the performance, it is the API change and the change of paradigm in Mixxx. 
Prior this change, we had a universal Group/Item pair all over Mixxx. Your change is starting to change this.
Now we have functions that take an ChannelHandleAndGroup that needs more explanations than just group. It is clear, that we need to move away from "group" in places where we need fast lookups and iteration. Since long we had a solutions for this in SoundDevice an EngineMaster.     

Advantages of this PR:
* ChannelHandleAndGroup is moved to an inner scope (less attracting) 
* No extra register() call 
* Less code is used 
* Minor performance Gain 
* No dead code 

I am not the opinion that this PR is already the best solution, but it is a step in the right direction. 
So lets work together to get a solution that suits both of us. 

####

Side note: 
I am not the opinion we must keep the types for QString group and QString Item. We will have some benefit in maintenance and optimization when we place QString and by typedefs or inherited classes from QString. But that is an other topic.

**Comment by daschuer** [comment]
Hi @rryan, 

since you did not resound to my last  comment I do not know how to continue here. 
I would really like to clean that code up and keep the Mixxx API simple.
Is it OK to merge this or do you have still strong arguments against it? 
Any ideas for a compromise?

**Pull request closed without merging**
