### PR TITLE
Declare data types with trivial ctor/dtor as Q_MOVABLE_TYPE

### PR DESCRIPTION
**Pull request by uklotzde**
...to improve the efficiency when used as elements of Qt container classes like QList.

### CODE REVIEW

**Comment by daschuer** [comment]
LGTM,  waiting for pending Test

**Comment by uklotzde** [comment]
It's actually about "realloc"able types ;)

https://www.youtube.com/watch?v=Ov7s0GgBbOQ

**Comment by daschuer** [comment]
Interesting talk! On markable thing I have learned from it: 
"for( : ) on a non const QT container will make a deep copy if the reference count is > 1"
so we should consider to cast to const where possible.

**Comment by uklotzde** [comment]
Range-based for loop blueprints with auto that work universally, even for 
std::vector<bool>:

for (const auto& ...) { immutable/const container/elements } // default
for (auto&& ...) { mutable/non-const container/elements }

The Qt collection classes may hide some complexity, but you can easily mess 
up your algorithms and performance. This is the reason why I prefer the STL 
variants, because you can reason about the algorithmic complexity and the 
expected overhead. With the introduction of move construction and assignment 
implicit sharing (aka COW) has become (almost) obsolete and is only needed 
for vary rare use cases. But with Qt you pay this price unconditionally, 
even if it is unnecessary for the majority of uses cases. Qt claims to be 
designed for inexperienced C++ programmers. In the end you need to be even 
more experienced for understanding all the concepts and their consequences.

**Pull request merged**
