### PR TITLE
Fidlib Unit-Tests  

### PR DESCRIPTION
**Pull request by daschuer**
This adds two tests, that aims to detect bugs like https://github.com/mixxxdj/mixxx/issues/11483

This is one step closer to the source, compared to https://github.com/mixxxdj/mixxx/pull/11489 and can be a low impact alternative. We may consider to close the outer test PR or keep/tweak it to be an extension to this one.

### CODE REVIEW

**Comment by daschuer** [comment]
@uklotzde @hapst3r can you check if these test are failing with GCC 13?

**Comment by Swiftb0y** [comment]
```
Note: Google Test filter = EngineFilterBiquadTest.*
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from EngineFilterBiquadTest
[ RUN      ] EngineFilterBiquadTest.fidlibInputRespectsLocale
[       OK ] EngineFilterBiquadTest.fidlibInputRespectsLocale (0 ms)
[ RUN      ] EngineFilterBiquadTest.fidspecLengthIsLongEnough
[       OK ] EngineFilterBiquadTest.fidspecLengthIsLongEnough (0 ms)
[ RUN      ] EngineFilterBiquadTest.analysisPkBq
[       OK ] EngineFilterBiquadTest.analysisPkBq (0 ms)
[ RUN      ] EngineFilterBiquadTest.analysisLpBe4
/home/swiftb0y/Sourcerepositories/mixxx/src/test/enginefilterbiquadtest.cpp:41: Failure
Expected equality of these values:
  delay
    Which is: 22
  24
[  FAILED  ] EngineFilterBiquadTest.analysisLpBe4 (0 ms)
[----------] 4 tests from EngineFilterBiquadTest (0 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 3 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] EngineFilterBiquadTest.analysisLpBe4

```

**Review by uklotzde — APPROVED** [review]
Confirmed. Test is failing as expected.

**Review by Swiftb0y — CHANGES_REQUESTED** [review]
LGTM otherwise.

**Comment by daschuer** [comment]
Done.

**Review by Swiftb0y — APPROVED** [review]
LGTM, though I can't judge how robust these tests are actually are.

**Pull request merged**
