### PR TITLE
Update config string value for recent mixxx versions.

### PR DESCRIPTION
**Pull request by ywwg**
This prevents spurious config version warning.
Also delete m_bUpgraded dead code.

./mixxx-test passes

### CODE REVIEW

**Comment by ywwg** [comment]
(if we're frozen this can wait until 2.2, this is low-risk but totally not necessary for release)

**Comment by daschuer** [comment]
Mac build fails unrelated:

==> Installing opusfile
==> Downloading https://homebrew.bintray.com/bottles/opusfile-0.10.el_capitan.bo
==> Pouring opusfile-0.10.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/opusfile/0.10: 17 files, 292.7KB
The command "if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install scons portaudio libsndfile libogg libvorbis portmidi taglib libshout protobuf flac ffmpeg qt chromaprint rubberband fftw libmodplug libid3tag libmad mp4v2 faad2 wavpack opusfile; fi" failed and exited with 1 during .
Your build has been stopped.
/Users/travis/.travis/job_stages: line 166: shell_session_update: command not found

**Comment by daschuer** [comment]
Is the Mac build failure a release issue?

**Comment by daschuer** [comment]
Thank you, that is way better than what I had in mind to do during change to release version name.
If the config version is already 2.1rc1 it will never change to the release. Schoud we care about his as well?

**Comment by ywwg** [comment]
yeah I can add another conditional for "2.1rc"

**Comment by daschuer** [comment]
Sorry for my misleading comment. 
We need to check for "2.1.0"

**Comment by ywwg** [comment]
> We need to check for "2.1.0"

like this?  Or are you saying that the final version string for the release will still be 2.1.0-rc1?  Sorry if I'm still confused!  

I was assuming that 2.1.0-rc* would be the string during the rc period, and then for the release it will be 2.1.0 or 2.1.

Oh, do you mean it has been 2.1.0-rc, but the final one will be 2.1, so any string of the form 2.1.0* indicates a prerelease version?

**Comment by daschuer** [comment]
We have three versions out there which should be lifted to the release version string:
2.1.0-alpha-pre 2.1.0-beta1 and 2.1.0-rc1 (please verify) 
So the idea was to check for "2.1.0"

**Comment by daschuer** [comment]
Thank you! LGTM

**Pull request merged**
