### PR TITLE
add vamp-float-math build option to force single precision for calcul…

### PR DESCRIPTION
**Pull request by schnitzeltony**
On my way to mixxx on Raspi2 this is a small step enhancing performance. Experts review required!

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for the patch. 

Do you have benchmark results, that this actually improves the performance? 

I am just asking, because the Cortex-A7 has the NEON floating point extension, which supports 64 bit operations. Which compiler option do you use? 
-mfpu=neon-vfpv4

When I worked with the EQ filters, I had some bad experiences with self oscillation when using float instead of double. So it might be a good idea to identify the CPU hotspots and pick float where the precision is not important and we have a performance gain.   

But lets look at the benchmarks first.

**Comment by schnitzeltony** [comment]
On Thu, Dec 29, 2016 at 5:48 PM, Daniel Schürmann <notifications@github.com>
wrote:

> Do you have benchmark results, that this actually improves the performance?
>
At the moment  I only have what was mentioned in commit. I did:

* Install mixxx (single/double precision)
* Remove .mixx folder
* Start mixxx by shell to see messages
* Doubleclick on an mp3 which is the longest I found so far ~6min
* Checked the conversion times reported by mixxx 84s double / 72 single

What kind of benchmarks would you suggest?

> I am just asking, because the Cortex-A7 has the NEON floating point
> extension, which supports 64 bit operations. Which compiler option do you
> use?
> -mfpu=neon-vfpv4
>
Yes: '-march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard
-mcpu=cortex-a7'. That might explain why performance boost is a bit
disappointing. To be honest: I forgot that scalar double precision is
supported by vfp4 - that was caused by focusing on SIMD NEON: There we have
single precision on 32Bit machines only. Side note: I am playing around
with SIMD intrinsics but I did not get significant enhancements yet. SIMD
would need this patch.

> When I worked with the EQ filters, I had some bad experiences with self
> oscillation when using float instead of double. So it might be a good idea
> to identify the CPU hotspots and pick float where the precision is not
> important and we have a performance gain.
>
> But lets look at the benchmarks first.
>
See above

**Comment by daschuer** [comment]
SIMD NEON is the vectorizing hardware similar to MMX/SSE, right? 

gcc should support auto vectorizing ARM. 
https://gcc.gnu.org/projects/tree-ssa/vectorization.html

On Pentium, it does well. I have optimized our sample functions for it: 
https://github.com/mixxxdj/mixxx/blob/65008bd95f548bd9424ee995543225d36731303f/src/util/sample.cpp#L12
It would be interesting to know if it already uses SIMD NEON. 

It would be no big deal to just merge it as it is, since it is an experimental compile option. 
On the other hand, the vamp plug-ins, are external code, heavy patching might make it harder to stay on track with upstream. Analysis is a one time issue, where precision should be more important than some performance gains. 

Maybe there is a chance to work together with the original author and get your get your changes upstream? 

Maybe we can finally improve the patch in a way all CPU architectures benefit from your work. 

Optimizing the Vamp-Plugins for auto vectorizing would be really nice. 

We may also get rid of unnecessary double buffers like this: https://github.com/mixxxdj/mixxx/blob/65008bd95f548bd9424ee995543225d36731303f/vamp-plugins/plugins/BarBeatTrack.cpp#L353

For benchmark, you may use the ScopedTimer
https://github.com/mixxxdj/mixxx/blob/8d191bf7ce2d62d24c6e0ffac4b2afd7359afa8a/src/util/timer.h#L54

The result is printed to mixxx.log. if you start in developer mode. 
mixxx --devel
You can also switch the statistic domain using the developer menu

**Comment by rryan** [comment]
Thanks for the changes! 

Since VAMP and qm-dsp are external libraries, I think the best place for these changes is upstream. 
https://code.soundsoftware.ac.uk/projects/vamp
https://code.soundsoftware.ac.uk/projects/qm-dsp

Chris Cannam is the owner of both projects and has been friendly to contributions in the past.

**Comment by rryan** [comment]
Please let us know once the changes are picked up upstream and we'll update. Thanks again!

**Pull request closed without merging**
