### PR TITLE
Revert "DEBUG output for fullscreen changes"

### PR DESCRIPTION
**Pull request by daschuer**
This reverts commit 5a4fe74ca9bd90814ef0eadf3730a073fd01783f.
fixing #13030

### CODE REVIEW

**Comment by ronso0** [comment]
I'm not sure 2.5 has been tested sufficiently already. I'd like to keep this during beta and finally remove it when it's clear there are no regressions (only worried about macOS actually).

**Comment by daschuer** [comment]
Sounds good. I was unsure because the milestone.

**Comment by daschuer** [comment]
We are in the process of the 2.5.o release now. Can this be merged?

**Comment by ronso0** [comment]
Yup, there were no complaints afaik.
In case we need debug info we can simply revert this.

**Pull request merged**
