### PR TITLE
2.2 contributors

### PR DESCRIPTION
**Pull request by daschuer**
Update contributor lists for the 2.2 release.
Clarify the usage.

### CODE REVIEW

**Comment by Be-ing** [comment]
I'm not really in favor of calling people who made 0 commits for the current release current contributors when there is specifically a section for past contributors. Where did you get this information? What commands did you use?

**Comment by daschuer** [comment]
I have searched the names using gitk. The original commit of the user appears some lines below. Than I have searched the most recent commit of this user. I need to only check the topmost names. Since the lower are added within the last two years.

The wo years is what we have decided last time. For me this is a reasonable time to come back and continue to contribute without their name is dropped. Seeing > 100 open PRs for more than a year does also not rectifi a shorter period IMHO.

**Comment by rryan** [comment]
LGTM. This PR returns us to the status quo, so let's merge it until we can come to an agreement on what to do going forward.

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
