### PR TITLE
Deere .: remove center gap from Meta/Super knob ring

### PR DESCRIPTION
**Pull request by ronso0**
As requested in #1399 

related bug: [lp:1698408 effect specific Meta knob/QuickEffect knob default position](https://bugs.launchpad.net/mixxx/+bug/1698408)
related PR: #645 Knob masked ring

### CODE REVIEW

**Comment by ronso0** [comment]
despite the commit message it's the blue ring, of course

**Comment by daschuer** [comment]
LGTM.
Doesn't the same apply to the Mix knob?

**Comment by ronso0** [comment]
Thanks.
> Doesn't the same apply to the Mix knob?

No, the Mix knob defaults to center, like EQs.

**Comment by ronso0** [comment]
> Doesn't the same apply to the Mix knob?

...but I just noticed that HeadMix knob is affected.
Fixed in #1497

**Pull request merged**
