### PR TITLE
Update FaderFoxDJ2.midi.xml

### PR DESCRIPTION
**Pull request by tarche**
Hi,
This is a small update to the FaderFoxDJ2 mapping.
Hope that everything is fine, this is my first commit.
You can see changes on this forum thread : http://www.mixxx.org/forums/viewtopic.php?f=7&t=7865

### CODE REVIEW

**Comment by Be-ing** [comment]
Thank you for submitting this! Could you update http://mixxx.org/wiki/doku.php/faderfox_dj2 to explain how the mapping works?

**Comment by snue** [comment]
@tarche @Be-ing those are different opcodes by the same control on the same (first) midi channel. The 0x90 is the button press ("Note On"), 0x80 is release ("Note off"). Make sure things like "LoadSelectedIntoFirstStopped" are not executed twice on a single button click (press+release).

**Comment by Be-ing** [comment]
Considering that the author has not replied for months and this controller is quite simple, I think this should be merged as-is even if the documentation is absent.

**Comment by tarche** [comment]
Hi Be. 
I've documented the wiki with the few points that are not clearly labeled. Is that alright ?

**Comment by Be-ing** [comment]
That's a good start, but there are still some functions that aren't clear to me from looking at the picture.

* What does the joystick do?
* What does the lower black button by the encoders do?
* What do the FX1/FX2 LEDs at the top indicate?
* I'm guessing the blue buttons do temporary pitch bending. Looking at the XML, I'm guessing they do small temporary pitch bending with shift pressed.
* The labels on the grey buttons are confusing. I see one with a play/pause icon, one with a pause icon, and one with a play icon. In the XML, I see one is mapped to play, another to cue_set, another cue_goto, and another to cue_preview, but those labels don't clearly tell me which one is which.
* Do the grey buttons send different signals with shift held down? If so, it would be useful to map them to some additional functions like quantize, keylock, and beatjump_1_forward/backward.

**Comment by tarche** [comment]
Hi, sorry for the late update. I've been very busy but had time to work on the mapping during the holidays. I've modified the mapping according to your  remarks and documented the wiki accordingly. Feel free to correct any mistakes, my English is far from perfect.

**Comment by Be-ing** [comment]
Great, thank you! I made a few small edits to the wiki, but mostly it was good. :) I have one last small comment on the functionality. Considering that there is an encoder on each side, I think that pushing the encoder in List/Load mode should load the selected track to the corresponding deck, not the first stopped deck. Loading to the first stopped deck makes more sense when there is a single encoder on the controller for browsing the library.

**Comment by tarche** [comment]
Done. I actually never realized there was such a control as _LoadSelectedTrack_ because I was looking in the Playlist group and only saw _LoadSelectedIntoFirstStopped_.
Thanks a lot for your help !

**Comment by Be-ing** [comment]
Looks good to me! :+1:

**Comment by daschuer** [comment]
Thank you very much for the work!

**Pull request merged**
