### PR TITLE
Update hidapi to 0.11.2

### PR DESCRIPTION
**Pull request by daschuer**
This is https://github.com/mixxxdj/mixxx/pull/4777 downgraded to 0.11.2 to match the minimum requirement only. 
This will allow to remove this overlay one day. 

We can merge this either directly or @JoergAtGithub can reset his branch to this.

### CODE REVIEW

**Review by uklotzde — APPROVED** [review]
This is at least a step in the right direction. LGTM

**Comment by uklotzde** [comment]
Wait, this should go into 2.3!

**Review by uklotzde — CHANGES_REQUESTED** [review]
Please rebase on 2.3 and retarget.

**Comment by daschuer** [comment]
Done

**Comment by JoergAtGithub** [comment]
It's not neccessary, to raise the required hidapi version in CMakeLists.txt for 2.3.
Neither hid_get_input_report nor the hidraw backend for Linux is used in 2.3.

**Comment by daschuer** [comment]
OK so I will revert the rebase. It is better to not touch the stable version if not necessary.

**Review by uklotzde — APPROVED** [review]

**Pull request merged**
