### PR TITLE
Add Behringer-CMD-PL-1 controller

### PR DESCRIPTION
**Pull request by yledoare**
Hello,
This is a code that didn't be included in my last PR
I hope now it will be OK
Regards

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Welcome and thanks for improving this! Please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

**Comment by ronso0** [comment]
@yledoare Please read this comment in one of your abandoned previous CMD-PL-1 PRs
https://github.com/mixxxdj/mixxx/pull/3246#issuecomment-721944524
* install pre-commit
* rebase your branch onto Mixxx 2.3
* run pre-commit
* apply changes the proposed changes, ammend those to your first commit
* and finally force-push

Please also open a PR with the mapping documentation for the manual https://github.com/mixxxdj/manual/

**Comment by yledoare** [comment]
> Welcome and thanks for improving this! Please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

Done !

**Comment by ronso0** [comment]
> rebase your branch onto Mixxx 2.3

You don't need to rebase, commit history looks good after I changed the base branch here.

**Comment by Swiftb0y** [comment]
@yledoare thank you for retrying to submit this PR. Please follow the steps described by ronso0 in https://github.com/mixxxdj/mixxx/pull/11518#issuecomment-1528731077

Thank you.

**Comment by JoergAtGithub** [comment]
For the case, taht you don't know how to use Git, here is an article how to do these steps:
- https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking
- https://github.com/mixxxdj/mixxx/wiki/Using-Git#targeting-another-base-branch

**Comment by JoergAtGithub** [comment]
Please execute the steps in the order listed above, otherwise you will do everything twice.

**Comment by Swiftb0y** [comment]
This PR is based on main (likely quite outdated) but merging into 2.3. This is messing with our checks...

**Comment by yledoare** [comment]
New PR from 2.3 branch : https://github.com/mixxxdj/mixxx/pull/11529

**Comment by ronso0** [comment]
@yledoare Why do yo keep creating new PRs instead of following given advice? Setting up pre-commit and rebasing are skills you need anyway sooner or later.

> For the case, taht you don't know how to use Git, here is an article how to do these steps:
> 
>  * https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking
> 
>  * https://github.com/mixxxdj/mixxx/wiki/Using-Git#targeting-another-base-branch

**Pull request closed without merging**
