### PR TITLE
search user's settings path for controller presets

### PR DESCRIPTION
**Pull request by Be-ing**
Users should not need write access to their system's Mixxx resource directory to install controller presets. Note that autogenerated presets now show up in the available presets list, which may or may not be wanted.

### CODE REVIEW

**Comment by daschuer** [comment]
Would you mind to add a m_ to all PresetInfo and PresetEnumerator members? 
We try to fix some code style issues when touching it.

**Comment by daschuer** [comment]
If you feeling lucky, moving PresetEnumerator to its own file is also such unrelated a task. ;-)

**Comment by daschuer** [comment]
Thank you very much for fix and the extra work!
LGTM

**Comment by Be-ing** [comment]
Btw, presets in the user settings directory show up at the top of the list, which is probably good.

**Pull request merged**
