### PR TITLE
optimize some Preferences pages

### PR DESCRIPTION
**Pull request by ronso0**
Some small & big measures to make the preferences pages cleaner and reduce the need for horizontal scrollbars.

* Interface: move Meta knob behaviour to Effects
* Effects: put effect info below effect list
* Key Detection: transform notation selection to 3x2 grid to avoid overlapping names
* AutoDJ: reduce required width, more ambigious slots and objectnames, add documentation
* Vinyl Control: reduce required width, make Lead-In a spinbox

this PR | before:
pref-opti2_auto
pref-opti2_effects
pref-opti2_interface
pref-opti2_key
pref-opti2_vinyl

ToDo
- [x] Vinyl Control > Lead-In: NN s / NN sec ?
- [ ] double-check AutoDJ defaults
- [ ] double-check relations of AutoDj options, adjust section titles accordingly
- [x] minor alignment fixes

### CODE REVIEW

**Comment by ronso0** [comment]
This is basically finished, except the AutoDJ page which is a bit dense IMO and I didn't entirely understand / test how those five options are interconnected.
To make that clear I'd like to separate them visually and add titles where it makes sense. Suggestions for the titles are welcome!

I'll add some screenshots soon, in the mean time just build and see for yourself :)

**Comment by Be-ing** [comment]
Can you please leave DlgPrefEffects alone unless you're volunteering to fix merge conflicts with #2618? I am getting quite tired of resolving merge conflicts on that 2 year old branch.

**Comment by Holzhaus** [comment]
> Can you please leave DlgPrefEffects alone unless you're volunteering to fix merge conflicts with #2618? I am getting quite tired of resolving merge conflicts on that 2 year old branch.

I understand, but this is for 2.3 not 2.4. Since you completely redesigned the effects page in #2618 I think you can just ignore all changes to the effects dialog from this PR and override them with your changes during merge conflict resolution.

**Comment by ronso0** [comment]
Yes, I planned to supply commits fixing the conflicts :)

I simply can't leave the UX in that effects pref page as it is. It's the only page where I have to maximze the window just because selecting effects in that narrow table resizes the table and shifts the cell focused which makes the table scroll vertically, and I couldn't fix that with properties. Also it makes no sense to me why Meta knob options are in Interface in the first place.

**Comment by ronso0** [comment]
I added now/before screenshots in OP https://github.com/mixxxdj/mixxx/pull/2897#issue-437538179

**Comment by ronso0** [comment]
Any comments?

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you!

**Comment by Holzhaus** [comment]
Just noticed some minor thing that would be nice to fix in a follow-up PR: IMHO it would make sense to move the "Show signal quality in skins" to the "Signal Quality" group box.

**Comment by ronso0** [comment]
Yup, good idea!

**Comment by Be-ing** [comment]
I fixed the merge conflicts in #2618.

**Pull request merged**
