### PR TITLE
SoundSource: Change info message to a warning 

### PR DESCRIPTION
**Pull request by daschuer**
This is a replacement for https://github.com/mixxxdj/mixxx/pull/1698

### CODE REVIEW

**Comment by Be-ing** [comment]
Warnings should only be used when there is a problem detected. Won't this print a warning when a plugin successfully loads too?

**Comment by daschuer** [comment]
Yes, this warning is always printed.

**Comment by uklotzde** [comment]
I consider logging messages with level warning or error just to be visible an anti-pattern. This is very confusing!

**Comment by uklotzde** [comment]
Starting with Qt 5.5 _Info_ became available as a separate log level. We might enable this log level by providing the corresponding command line arguments.

**Comment by daschuer** [comment]
Ok, so this is a wrong band aid. 
Let's go back to the folder solution which is bullet prove with up and downgrades.

**Pull request closed without merging**
