### PR TITLE
Find and fix remaining Launchpad links using this Reg-Ex

### PR DESCRIPTION
**Pull request by daschuer**
A https://github.com/mixxxdj/mixxx/pull/11270 follow up. 

There are these remaining bugs that have not been ported to GitHub: 
res/linux/org.mixxx.Mixxx.metainfo.xml:3127:   lp:1815305
res/linux/org.mixxx.Mixxx.metainfo.xml:3169:   lp:1776949
res/linux/org.mixxx.Mixxx.metainfo.xml:3183:   lp:1795234
res/linux/org.mixxx.Mixxx.metainfo.xml:3278:   lp:1729345
res/linux/org.mixxx.Mixxx.metainfo.xml:3302:  lp:1751482

### CODE REVIEW

**Comment by Swiftb0y** [comment]
Weird that those have not been ported...

**Review by ronso0 — APPROVED** [review]
LGTM, though I'd rather have the js linting in a separate commit (or removed entirely)

**PS** and pre-commit now complains about the touched mapping files.

**Comment by daschuer** [comment]
The js changes are now separate https://github.com/mixxxdj/mixxx/pull/11379

**Comment by daschuer** [comment]
Conflict resolved. Merge?

**Pull request merged**
