### PR TITLE
Add warnign when trying to enable AutoDJ with left & right deck

### PR DESCRIPTION
**Pull request by MetriSomesh**
Added warning message when trying to enable AutoDJ if there's no left & right deck.

### CODE REVIEW

**Comment by daschuer** [comment]
Please do the following in the console: 

```
git checkout warning-msg
git fetch upstream 
git rebase --onto upstream/2.3 HEAD~1
git push -f
```
If something does not work, please paste the console output here.

**Comment by MetriSomesh** [comment]
err

**Comment by ronso0** [comment]
The output clearly states what you need to do to set upstream.

**Comment by MetriSomesh** [comment]
After following command this error occurs

err2

**Comment by daschuer** [comment]
You need to force in that case.
Just add the "-f" after push in this string.  

By the way, please prefer copying the text instead of doing screenshots. 
This way it is easier for us to copy and paste and edit the messages.

**Comment by MetriSomesh** [comment]
@daschuer  I added -f and it says now this is merged and closed is it done?

**Comment by daschuer** [comment]
It is closed because you have not added your change. 
You can now edit the file, commit and push again.

Alternatively you may recycle your commit: 
```
git cherry-pick ad8db4030c554a34af6e3bbf3c62de5a7c044280..2ef1bfe22d1969661d02f5e5f9503ae6ed60e02c
```

**Comment by daschuer** [comment]
If you feeling lucky, you may take a git training here: https://learngitbranching.js.org/

**Pull request closed without merging**
