### PR TITLE
test: Remove obsolete `baseeffecttest.h`/`.cpp` files

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
LGTM! CI passed without these files. Thank you!

**Comment by Holzhaus** [comment]
> LGTM! CI passed without these files. Thank you!

There were not compilable anyway ;-)

**Comment by Swiftb0y** [comment]
`MetaLinkTest` and `EffectsBenchmarkTest` both depend `BaseEffectTest`. How do we want to proceed? Remove those too or refactor both to work again?

**Comment by Holzhaus** [comment]
No idea, but this PR was one year ago. How long were these files not used?

**Comment by Swiftb0y** [comment]
well, since 26b118d and aa44159634b80518646d0ddcab401e4d3cddd6b1 respectively I guess. So quite a long time...

**Pull request merged**
