### PR TITLE
Make sure a track has at least a title after import metadata.

### PR DESCRIPTION
**Pull request by daschuer**
Here the fall back code to generate title and artist from the file name is applied whenever these values empty after reading metadata from file. 

Before the code was skipped even when only the metadata frame was available. Parts of the internal logic was not reachable, because the fall back was only applied when there was no artist AND no title and nothing else set. 

This fixes a regression in 2.3 
https://bugs.launchpad.net/mixxx/+bug/1913946

### CODE REVIEW

**Comment by uklotzde** [comment]
How about a regression test? The file `artist.mp3` has an artist but no title. This should cover exactly the use case you described.

**Comment by Holzhaus** [comment]
Yeah, let's try to add test for these kinds of bugs so that they won't happen again.

**Comment by daschuer** [comment]
A test is in place now.

**Review by uklotzde — APPROVED** [review]
Thank you! LGTM

**Pull request merged**
