### PR TITLE
Don't fail if QtKeychain is no available

### PR DESCRIPTION
**Pull request by xeruf**
https://github.com/mixxxdj/mixxx/pull/2854 fails the build if QtKeychain is not available on the system. This change still enables it by default but doesn't require it.

### CODE REVIEW

**Review by Holzhaus — CHANGES_REQUESTED** [review]
Thanks for taking care of this.
However, we shouldn't silently drop Qt5Keychain support even when the user requested it explicitly.

Instead, please use a [`cmake_dependent_option`](https://cmake.org/cmake/help/latest/module/CMakeDependentOption.html) instead, like we do here: https://github.com/mixxxdj/mixxx/blob/master/CMakeLists.txt#L292

**Comment by Holzhaus** [comment]
@daschuer By default, do we want to have this always enabled or just when Qt5::Keychain is installed?

**Comment by daschuer** [comment]
It was intended to fail the build if Qt5Keychain is not available. 
This in an important feature all user should benefit. 
Original we have introduced it as compile options because we where unsure if Qt5Keychain works on all targets. 
I think this is the case. If not, I would prefer a target depending default.

**Comment by Holzhaus** [comment]
OK, in that case the failure is intended and we can close this I think.

**Comment by xerus2000** [comment]
No worries, I learned something again :)

**Pull request closed without merging**
