### PR TITLE
Download libKeyFinder before build

### PR DESCRIPTION
**Pull request by uklotzde**
Needed for RPMFusion builds. The additional sources need to be downloaded and bundled **before** starting the build.

### CODE REVIEW

**Comment by uklotzde** [comment]
I don't know how to get rid of the duplicated external project settings? I just left a comment to indicate them.

**Comment by Be-ing** [comment]
I don't understand this change. Why would libkeyfinder sources be in the `lib` folder? How is this needed for RPMFusion? Don't you need to make a separate libkeyfinder package for RPMFusion?

**Comment by uklotzde** [comment]
No, I am not going to maintain libKeyFinder.

**Comment by Be-ing** [comment]
So what is the point of this? Does this not violate packaging guidelines??

**Comment by uklotzde** [comment]
The is no libKeyFinder package and I am not going to create an maintain one. Who uses this except us?

Bundling the source code and linking it statically is fine.

**Comment by uklotzde** [comment]
Local build succeeds. I am confident that this approach might also work for the RPM build.

**Comment by uklotzde** [comment]
Ready

**Review by Holzhaus — APPROVED** [review]
LGTM.

**Pull request merged**
