### PR TITLE
Controller mapping: Add mappings for Novation Launchpad and Novation Launchpad MK2

### PR DESCRIPTION
**Pull request by dszakallas**
Adds my mappings for the Novation Launchpad MK1 and MK2 controllers.
Replaces existing script for MK1.

Files are compiled, adding sources in separate directory.

Project has an [own repository](https://github.com/szdavid92/mixxx-launchpad).

### CODE REVIEW

**Comment by Be-ing** [comment]
Thanks for submitting these. I see you have some documentation in your GitHub repo. It's easier for users to find controller documentation when it's centralized on the Mixxx wiki (it's also easier to navigate because DocuWiki automatically generates a table of contents). There's an [existing wiki page for the Mk1](http://mixxx.org/wiki/doku.php/novation_launchpad_mk1) you could add a new section to. Do the Mk1 and Mk2 mappings function the same way? If so, it may make more sense to make a new wiki page for both the Mk1 and Mk2 and note the differences between them instead of having a wiki page for both. Does the Mk2 mapping make use of the additional colors?

**Comment by szdavid92** [comment]
> Do the Mk1 and Mk2 mappings function the same way?

Yes, only the colors are slightly different stemming from the difference between the devices.
Amber colors have been mapped to blue.

> Does the Mk2 mapping make use of the additional colors?

No, it doesn't. We'd need further abstractions for this, preferably some fallback mechanism like in CSS for fonts.

How should I include the sources? For now I simply copied them as regular files.

**Comment by Be-ing** [comment]
> How should I include the sources? For now I simply copied them as regular files.

I think that's fine as long as they have build instructions or a link to build instructions.

**Comment by szdavid92** [comment]
Well the entire repo is there.

**Comment by sblaisot** [comment]
please update windows uninstaller for all files you added : https://www.mixxx.org/wiki/doku.php/contributing_mappings#windows_installer_update

**Comment by szdavid92** [comment]
added docs to wiki: http://mixxx.org/wiki/doku.php/hardware_compatibility#community_supported_mappings

**Comment by Be-ing** [comment]
Thanks, I will take a closer look soon. Pretty busy trying to polish up some long-running PRs right now.

**Comment by Be-ing** [comment]
I apologize for the long delay reviewing this. We've decided to release Mixxx 2.1 beta on 12/22/2017. After that I'll get back to reviewing controller mappings to include in the 2.1 release.

@Swiftb0y, I remember you mentioned on IRC that you had made some edits to this mapping. What have you changed? Do you think there is room for both mappings, or should one be chosen over the other?

**Comment by Swiftb0y** [comment]
I just fixed some bugs. For example some lights didn't turn off on shutdown which I fixed with a bodge and there where some typos in one of the layouts.
I'll review this mod and my CMD MM-1 mapping this week and so it can safely be included in mixxx 2.1

**Comment by szdavid92** [comment]
I fixed some bugs in the meantime too, just forgot to update this PR. @Swiftb0y could you open a PR on [the repo]( https://github.com/szdavid92/mixxx-launchpad) so your bug fixes can be merged in as well?

**Comment by Be-ing** [comment]
By the way, do you know if this works for the Launchpad Pro?

**Comment by szdavid92** [comment]
I never tried. I guess we need a separate button mapping for that.

**Comment by szdavid92** [comment]
Next week I will have some time to put in this mapping. There are still some issues waiting to be fixed.

**Comment by Be-ing** [comment]
I will get to reviewing this soon, but for now I will be taking a break from development and code review for a few days.

**Comment by Be-ing** [comment]
@szdavid92 we're having a discussion about what features to show in skins for the samplers. That may affect this mapping, so if you want to join your input would be appreciated: https://bugs.launchpad.net/mixxx/+bug/1743109

**Comment by Be-ing** [comment]
@dszakallas is this the latest version of your mapping? If not, please push your latest updates so we can get them into the 2.1 release. I won't have time to do a detailed review of the code, but I'll at least go over the wiki quickly.

**Comment by Be-ing** [comment]
Please rename the `res/controllers/launchpad` folder to `res/controllers/novation-launchpad`. When I first saw the folder name I was confused because I thought it had something to do with our [Launchpad bug tracker](https://bugs.launchpad.net/mixxx/).

**Comment by Be-ing** [comment]
The wiki says for the tap button:
>  ctrl: instead of altering the playback tempo, tapping adjusts the beatgrid. Not implemented. Why?

The `bpm_tap` Control was fixed in #1429, so you can implement that now.

**Comment by Swiftb0y** [comment]
Dumb question: bpm_adjusts the beatgrid. Is there an alternative control for adjusting the playback tempo? I'm using script.bpmTap (as a workaround?) at the moment.

**Comment by Be-ing** [comment]
@Swiftboy: Let's not clutter this PR with comments that aren't related to this particular controller mapping. If you have general questions about controller mapping, ask on the forum or in the [#controller mapping stream on Zulip](https://mixxx.zulipchat.com/#narrow/stream/113295-controller-mapping).

**Comment by dszakallas** [comment]
I updated to the new stable version.

**Comment by Swiftb0y** [comment]
I can't test this in the next couple of days but I had an issue where the yellow navigation buttons stayed on when unmounting. Is this fixed now?

**Comment by dszakallas** [comment]
I can't test now either. If I remember correctly it is fixed. If not, that's not a showstopper either, as it only happens when unmounting the controller, and doesn't interfere with anything really.

**Comment by Be-ing** [comment]
You may want to map the new `reloop_andstop` Control to shift + reloop button.

**Comment by Be-ing** [comment]
Okay, this looks good to me. Thank you for contributing this and sorry again for procrastinating on reviewing it for so long. I'll merge this now. If you want to implement the `bpm_tap` and `reloop_andstop` Controls, feel free to do that in a follow up pull request.

We have been having some discussions about future directions for the controller mapping system in the [#controller mapping stream on Zulip](https://mixxx.zulipchat.com/#narrow/stream/113295-controller-mapping) and [this Launchpad bug](https://bugs.launchpad.net/mixxx/+bug/1733666). It looks like you know JavaScript really well, so your input would be appreciated if you're so inclined.

**Comment by dszakallas** [comment]
Thanks, I will look into the discussion. It would be great if we could update to a newer platform, so we won't need the shims and less transpilation are required. The biggest problem is the ES3 reserved keywords that can pop up in random dependencies, preventing me from including [mobx](https://github.com/mobxjs/mobx) for example, which would be a great declarative state machine. I create issues about the control enhancements on my repo.

**Comment by Be-ing** [comment]
We'll finally be upgrading to Qt5 after the 2.1 release. Qt5 has a new JS interpreter in its QJSEngine API which implements ES5. Refer to the [Launchpad bug](https://bugs.launchpad.net/mixxx/+bug/1733666) for further discussion.

**Pull request merged**
