### PR TITLE
controllers: fix engine.beginTimer() syntax

### PR DESCRIPTION
**Pull request by ronso0**
Reason to start this was #12384 

I know this is tedious to review. 35 mappings scripts.
These are not all mappings that are broken. A few other mappings seem to have other syntax issues, see https://github.com/mixxxdj/mixxx/blob/9eda4c399ca2f3bddd3fe602703285aac8252eeb/res/controllers/Numark-DJ2Go-scripts.js#L133 and I I have no clue how to fix those with the find/replace pattern I used.

### CODE REVIEW

**Comment by Swiftb0y** [comment]
In that case, you can use the index operator: 
```
NumarkDJ2Go.decks["D" + this.deckNum].scratchOff
```
But I wouldn't know how to do this automatically via regex.

**Comment by FrankwaP** [comment]
Some modifications like this one  
`LPD8RK.ledTimer = engine.beginTimer(LPD8RK.LEDinterval, "LPD8RK.setLeds()");̀`  
   to   
`LPD8RK.ledTimer = engine.beginTimer(LPD8RK.LEDinterval, LPD8RK.setLeds);`   
look very similar to the one fixing [#12384](https://github.com/mixxxdj/mixxx/issues/12384). 

But others looks more adventurous, like these ones 
`deck.playTimer = engine.beginTimer(500,"VMS2.playlightflash(\""+group+"\")");`     
  to   
`deck.playTimer = engine.beginTimer(500, function() { VMS2.playlightflash(group); });`   
  or   
`BehringerBCD3000.scratchTimer[deck] = engine.beginTimer(20, "BehringerBCD3000.stopScratch(" + deck + ")", true);`  
  to  
`BehringerBCD3000.scratchTimer[deck] = engine.beginTimer(20, function() { BehringerBCD3000.stopScratch(deck); }, true);`  
(basically the stuff with "+" in them).

Maybe a smaller PR with only the first cases?

**Comment by Swiftb0y** [comment]
fyi, we're in 2.4, so lets use arrow functions for wrapping these. I have a branch in progress as well.

**Comment by ronso0** [comment]
Superseded by #12401

**Pull request closed without merging**
