### PR TITLE
Search: save queries across restarts, related tweaks & fixes

### PR DESCRIPTION
**Pull request by ronso0**
**Store queries to mixxx.cfg** when WSearchLineEdit is destroyed (shutdown or skin change), load when it's created.
(only for the library searchbar, not the control searchbar in the developer tools dialog)
Currently only the selected query is stored on skin change, others are lost.

**`Delete` and `Backspace` in the popup delete the selected item**
This allows cleaning up the history, which I consider a rare maintenance job thus I did not add a delete shortcut for the _combobox view_.
I also added a control `[Library], delete_search_query` to delete the current item from the popup or the combobox view.

**tweaks & fixes**:
* The search queries popup holds indices 0..n, while the combobox also has index -1 (empty, "Search...").
When index -1 is selected in the combobox and the list view is opened index 0 is auto-set but not highlighted.
Select first index manually (only in the list).
* Avoid storing duplicate items when switching between library features.
* Some searchbar COs could be triggered (accidentally) while the searchbar is disabled (AutoDJ, Rec, ...). Debug asserts were used which I replaced with regular tests in order to avoid unexpected behaviour in releases.

https://bugs.launchpad.net/mixxx/+bug/1943084
https://bugs.launchpad.net/mixxx/+bug/1947479

### CODE REVIEW

**Review by daschuer — CHANGES_REQUESTED** [review]
The is just a readability issue. 
The rest looks good.
Thank you.

**Comment by ronso0** [comment]
> > Limiting the storage sounds reasonable. That could happen in WSearchLineEdit itself by setting `maxCount()`.
> 
> What about 50? I think that would allow the popup to be roughly as tall as the screen height.

ahemm, `kMaxSearchEntries = 50;` is already in place :grin:

**Comment by daschuer** [comment]
Thank you. 

I have just tested this and can confirm the issue: 
* Delete an entry form the pop up
* Restart Mixxx
* The last entry is listed twice. 

Another thing is that I was tempted to use the del key instead of backspace more than once during the test. Can we add it as well?

**Comment by ronso0** [comment]
> I fixed the duplicate bug, but I'll also need to fix the writing to the config to avoid duplicates there, probably wipe all entries before saving.

Done.

**Comment by ronso0** [comment]
Further optimization would be to set QKey constants and use them for the tooltip and the key event filter.
Won't happen here though.

**Comment by daschuer** [comment]
Thank you, I will do a final check.

In general, you should not rebase a PR under review. This creates untested commits and makes it hard for the reviewer to creview the changes compared to the last review. See: https://github.com/mixxxdj/mixxx/blob/main/CONTRIBUTING.md#all-contributors

**Review by daschuer — APPROVED** [review]
This works like a charm. Thank you.

**Pull request merged**
