### PR TITLE
Code by John Doe for adding color picker to library, LP #1100882

### PR DESCRIPTION
**Pull request by benis**
I've taken the patch file posted at the end of the thread on [this Launchpad bug](https://bugs.launchpad.net/mixxx/+bug/1100882/), applied it and updated any necessary bits based on changed/moved code. It builds and runs and does what it's supposed to do. Not saying it's fit for release necessarily, but here it is if anybody wants to take a look.

### CODE REVIEW

**Comment by Be-ing** [comment]
Thanks for doing this, but unfortunately we can't merge this or code based on it because the author has refused to sign the contributor agreement. There are a few cases where this has happened before such as the Reverb and we use ifdefs to remove a feature from Mac App Store builds. However, in this case that would get ugly because this is not an isolated feature and changes the code in many places.

**Comment by beenisss** [comment]
No worries. I got some exposure to the code out of it, so not an entirely useless exercise.

If I've understood correctly this raises an interesting question about the code content though. Unless the original author managed to find a sub-optimal way of implementing every aspect of this, if I remake the feature from scratch how can I create something that won't at least appear to be based on this implementation? If I can rely on the same principles, what would be the point of changing superficial details to make the implementation 'different'? If I can't, would I have to write something deliberately sub-optimal to avoid my code being 'based on' this PR?

**Comment by Pegasus-RPG** [comment]
In cases of copyright infringement avoidance, it would need to be a "clean room" implementation, i.e. written by someone/a group of people that have never seen the infringing code. I'm not a lawyer, so I don't know if FOSS contributions are that strict, or if simply re-writing the code from scratch without referencing the original (either directly or by memory) would suffice or not.

**Comment by daschuer** [comment]
I am not a lawyer, but for me the situation is clear.
John stated two times clearly that one can do whatever he wants with the code including uploading it to GitHub for putting it into Mixxx. 
This is the https://en.m.wikipedia.org/wiki/WTFPL

If he had not done this, we would have the problem, that we need to do a clean room implementation of the code. This can only do one who has not read the original code.

You have already ask him on Launchpad, so he has the chance to clarify the situation.
If we get no other statement, we can continues here, I think.

**Comment by Pegasus-RPG** [comment]
@daschuer Oh, perfect! Please reference his comment to that effect here (and in a code comment too) then we should be good to go.

**Comment by Be-ing** [comment]
This raises a question of whether we should even bother with the contributor agreement anymore. AFAIK the build in the Mac App Store hasn't been updated in many years and our build servers don't make these builds. I hadn't even heard of the Mac App Store before contributing to Mixxx, so I'm wondering if most Mac users use the Mac App Store. Either way, it doesn't seem to be an issue for Mac users to download the DMG from the Mixxx website.

**Comment by daschuer** [comment]
Sometimes authors does not want to be associated with there work if it is reused. 
Maybe the original Autor did not like to see his name on GitHub or in our commit History. This is also the case in the WTFPL, so I think it is better to remove the name from the commit message.

**Comment by daschuer** [comment]
The contributor agreement is important because it allows us to change the Mixxx license.

**Comment by WaylonR** [comment]
Still waiting on something for this to be mergable?

**Comment by daschuer** [comment]
We need to resolve the conflicts and do a proper review and test.  @benis do you plan to continue to work here later?

**Comment by benis** [comment]
Probably not to be honest. I was just getting the code into a PR to help move things along.

If there's anything specific you need me to do though, let me know.

**Comment by WaylonR** [comment]
depends.py conflicts, a lot of it due to a different relative directory. Remind me to push a fixed branch after my testing.

**Comment by benis** [comment]
Welp, I have messed this one up. I pushed the fix for the merge conflict prematurely and when I undid the push it wiped all the other changes I submitted and closed the PR. I don't know if there's an easy way to get the previous commit back.

**Comment by daschuer** [comment]
There is:

git checkout libraryColorCode
git reflog

this is mine
05bd675 HEAD@{0}: commit: Fix typo
6976fae HEAD@{1}: checkout: moving from 2.1 to lp1784185_
d60ac3c HEAD@{2}: reset: moving to upstream/2.1
fd15f29 HEAD@{3}: reset: moving to upstream/2.1
fbaf526 HEAD@{4}: pull https://github.com/uklotzde/mixxx.git 2.1_lp1635087_clear
98de7bc HEAD@{5}: checkout: moving from rate_ultra to 2.1
a3e0ca6 HEAD@{6}: checkout: moving from rate_ratio to rate_ultra

Pick the commit hash that you had before messing up the branch 

git reset fd15f29 --hard


than you can start over.

git merge upstream/master

resolve conflicts. I use smartgit for convenience.

**Comment by WaylonR** [comment]
I think theres a problem, in that the code used QVariantValue, which is now depreciated with error, in qt5.

**Comment by benis** [comment]
I don't think that will work because the commit in question has vanished. I'm basically asking Git to undo an undo action.

I will just reapply the patch at some point and push again.

**Comment by daschuer** [comment]
Git keeps all commits, even the vanished once. You need to explicite clear the reflog and call 
git gc ...

**Comment by benis** [comment]
I'm not getting anywhere with that unfortunately. It may not help that I deleted the branch yesterday. Why did I do that?

In any case I'm giving up on this, sorry. However @WaylonR, you did a commit earlier that contains all the changes that were in this PR - maybe you can do something with that?

**Comment by Be-ing** [comment]
The commits should still be accessible by checking out `upstream/pr/1771` if you have Git [set up as described on the wiki](https://mixxx.org/wiki/doku.php/using_git#set_up_git).

**Comment by Be-ing** [comment]
Or if you only deleted the branch via the GitHub website, you should still have it in your local Git repository, in which case you could just push it back to GitHub.

**Comment by benis** [comment]
Basically, I made a change in another branch, committed and pushed but didn't specify the branch name, so it changed things in the branch I had set up for this PR also. So I ran `git reset HEAD^` then 
`git push --force` thinking/hoping this would just revert that one push action on this one branch. Whereas what it seems to have done is reset that _and_ the original commit I made. I can't find a record of what was in it, my reflog for whatever reason doesn't go back to the original commit in August, when I go back to before the erroneous push the original changes still aren't there, and now both my local and remote repo don't appear to have any record of the original commit in this PR.

Yes, it might still be retrievable somehow, but I just really don't fancy devoting the time to it. Is there not a way to make use of the commit that @WaylonR did that contains the exact same changes, including resolution of the merge conflict?

**Comment by WaylonR** [comment]
yeah, i suppose i could do a new branch, and push out both the code and merge + qt5 changes.

**Comment by WaylonR** [comment]
Done. https://github.com/WaylonR/mixxx/tree/libraryColorCode
Doesn't work yet, need to figure out why it doesn't save.

**Pull request closed without merging**
