### PR TITLE
Auto dj crates improvements

### PR DESCRIPTION
**Pull request by daschuer**
This fixes Bug #1669767.
It does not pick a random and most likely not fitting library track when all crate tracks are already in the autoDJ queue. Instead, it re-adds tracks that are already queued up and member from the crates.

### CODE REVIEW

**Comment by daschuer** [comment]
Any volunteer for review and test?

**Comment by Be-ing** [comment]
Hmmm, I just tried this out and how it behaves in master. I think either behavior might be desired. Maybe this should pop up a dialog when Add Random gets to the end of the Auto DJ crates asking if the user wants to keep adding random from the crates or from the library? I think some users would get confused if they keep seeing the same tracks getting added repeatedly when they press Add Random.

**Comment by daschuer** [comment]
I cannot imagine a valid use case for the master behavior. IMHO it only linds a usage error, by hiding it. 

It happens to me that I have not enough track in a crate and it randomly adds surprisingly
"All I want for Christmas"  

Do you have one, maybe we can Include it with some tricks.

For me, the valid usecase are: 
* Play a random track from the library:  Remove all crates 
* Play a random track from crates: Add crates with enough tracks. 

The usecase
* Play a crate and than random tracks from library 
is already covered by adding the crate to the AutoDJ playlist 

What is missing is a radio like "controlled" random Mixxx from different crated 
Like "heavy rotation" crate and "light rotation" crate.

**Comment by daschuer** [comment]
We may add a warning if there are not enough tracks and Auto DJ is enabled. 
... mm but that can be quite complicated to make it rock solid.

**Comment by Be-ing** [comment]
Maybe there should be two buttons? "Add Random From Crates" and "Add Random From Library"?

**Comment by MK-42** [comment]
> Instead, it re-adds tracks that are already queued up and member from the crates.

How is that play together with the 'suspend track in track source from re-queue' and 
'minimum availiable tracks in Track Source' ? Actually I don't know what these settings to anyway, no native speaker, though the german translation is not really better...

**Comment by daschuer** [comment]
> Maybe there should be two buttons? "Add Random From Crates" and "Add Random From Library"?

Is this really such an important use case that it deserves a second button. For me, all this is only to code around users configuration issues, the case, if too few tracks are in the autoDJ crates to full fill the rules. 

> How is that play together with the 'suspend track in track source from re-queue' and
> 'minimum availiable tracks in Track Source' ? Actually I don't know what these settings to anyway, no native speaker, though the german translation is not really better...

The AutoDJ crate track are sorted by last played. The random Track is picked from the given percentage of less recently played track. If there are more tracks that are not played in the given time, they are also added to the selectable tracks. 
For example, If you have 10 Tracks in AutoDJ cates  percentage of 20 %  and a period of 23:59 there are always two tracks available. If non of the 10 tracks have been played today all tracks are available.

If finally all 10 tracks are queued. The master version picks random tracks form library. In this PR
will re-add one of the topmost tracks again, until every track is queued twice.

**Comment by Be-ing** [comment]
> Is this really such an important use case that it deserves a second button.

No. You're right, we shouldn't overcomplicate the UX for that use case. In case a user does get confused, it would be easy to tell them to remove crates from AutoDJ.

**Comment by daschuer** [comment]
The x64 bit build is stalled on AppVeyor not an issue of this PR

**Comment by daschuer** [comment]
Can we merge this now?

**Comment by Be-ing** [comment]
LGTM

**Comment by daschuer** [comment]
Thank you for review and test!

**Comment by esbrandt** [comment]
@daschuer 
I do have to come back to this after all these month, currently documenting all the stuff in the manual for 2.1

If you add a single crate as AutoDJ track source, containing one track, and hit ``Random`` multiple times, then the same track gets added to the queue over and over again.

I mean this is somewhat logical, but the user has to know the track source contains only of n tracks. We not even display the number and duration next to the crates, if under the ``Auto DJ > Crate`` root item.

I`d either expect that it does a) nothing or b) pull tracks from the library, if you running out of tracks from the track source.

However, if this is really on purpose, the tooltip for the AutoDJ ``Add Random`` button need an update then. It should reflect, that only tracks are added from the library, if no autodj crate is configured.

**Comment by daschuer** [comment]
Your case of only one track in the AutoDJ crate is not a real use case. But IMHO it is working correct. If you disable "Suspend Track in track source from re-queue" (default) it is allowed to add tracks again, so Mixxx does just does. Enable the feature and you have your expected behavior a) 
Before fixing this bug, we had b) but this is very annoying, explained here:  https://github.com/mixxxdj/mixxx/pull/1214#issuecomment-288856616

Do you think there is a valid use-case for b)?  

For now, updating the tooltip seems to be the best solution.

**Comment by Limag** [comment]
Hello All,

first of all thank you for this function, BUT real random seems quite unusable to me. If you going to set up a playlist, you like to follow some kind of equal music style,

Inspired from https://sayonara-player.com/, I examined its "dynamic playback" function. This creates impressive good playlists, using https://www.last.fm/api/show/artist.getSimilar . 

I implemented the (very) similar behavior in Mixxx. Works for me, but too bad for a pull request. 
And somebody has to decide that last.fm's license (https://www.last.fm/api/tos) works for Mixxx.

If something is interested in, let me know.
Again, the created playlists are deeply impressive.

**Comment by daschuer** [comment]
Hi @Limag 

Thank you for your suggestion. That sounds great. 
We have actually already discussed similar bugs: 
https://bugs.launchpad.net/mixxx/+bug/889898
https://bugs.launchpad.net/mixxx/+bug/894652
https://github.com/mixxxdj/mixxx/pull/1675

I think the TOS works for us. The only issue is that Last.fm is a commercial service so may want not include it by default to avoid to advertise them. 

Please issue a PR in any case. The code quality is not important for that. Many Mixxx features have been started as a quick hack. You can mark it with [WIP] and we can discuss along the code until it is mature.

**Comment by Limag** [comment]
Its now available on https://github.com/Limag/mixxx

**Comment by daschuer** [comment]
Thank you. Please issue a PR. With [WIP] as long there is work in progress.

**Comment by Limag** [comment]
My very first first pull request is done, #2058 . I also modified the README.md, hope this is not a problem.

**Pull request merged**
