### PR TITLE
Tango/Deere :: separate skin versions with 64 samplers

### PR DESCRIPTION
**Pull request by ronso0**
What's the plan regarding the sampler issue?

We now have the structure to offer each skin with either 16 or 64 samplers. This is done by creating a new skin directory named i.e. Tango-16-samplers containing a modified skin.xml only, and changing paths to templates and graphics i.e. from `skin:/buttons/xy.svg` to `skin:../Tango-64-samplers/buttons/xy-svg`, except for sampler decks template and sampler row selection button.
Additional maintenance effort is minimal and only necessary in case skin.xml itself is changed.

What do you think?
What are the chances of #1426 making it into 2.1?

Dependency: #1558

### CODE REVIEW

**Comment by daschuer** [comment]
I am no planning to continue #1426 for now. It is currently to hacky and a good solution is to much work. 
The outlined solution with a extra skin folder suites better for 2.1. 
So go ahead if you like.

**Comment by ronso0** [comment]
Alright.
Currently the skin name is just the skin's directory name.
I'd like name the skins `Deere (16 samplers)` etc. because it just looks better than `Deere-16-samplers`.
Do spaces in directory names work on all platforms?

**Comment by daschuer** [comment]
Yes, It should work with spaces.

**Comment by Be-ing** [comment]
I agree that #1426 would be an ugly hack that would only help in this specific situation. I think we should try to come up with other ways of optimizing skin loading and shutdown before going ahead with the hack proposed in this PR. I would not be surprised if the same issue with skin loading/shutdown comes back to haunt us in the future with a different scenario if we do not address the root issue now.

**Comment by daschuer** [comment]
I am afraid we cannot address the root issue for 2.1 in a rock solid way. So IMHO two skins is a good workaround.

**Comment by Be-ing** [comment]
I don't think we should jump to that conclusion without coming up with an idea for a good solution. What about caching instantiated templates and modifying copied widget objects instead of reparsing the XML for every single widget?

**Comment by Be-ing** [comment]
Why does shutdown take so long? That isn't related to processing the XML templates.

**Comment by ronso0** [comment]
I can't say anything to the root of the issue..but I see the guys I introduced Mixxx to, who don't use samplers so far (not to mention 64 of them) and they get that "Mixxx is not responding. Force-close or wait?" message (talking about Linux here, don't know about Win/OSX). They are asking themselves "Did I do something wrong?" or "The app isn't working correctly."
Not a good feeling, considering Mixxx is actually pretty stable right now..
So, even if I repeat myself: offering 64 samplers per default for a minority, or for the billboards, with the trade-off mentioned above just doesn't feel right.

For sure, the skin approach offered here is just a workaround, and should not at all keep anyone from investigating the root issue.

**Comment by Be-ing** [comment]
> offering 64 samplers per default for a minority, or for the billboards, with the trade-off mentioned above just doesn't feel right.

I agree. Even on my fancy new laptop with a quad core i7 8550U CPU and M.2 solid state drive the skin loading feels awkwardly long. If we can't figure out a better solution, I think we should adopt the hack of separate skins. But we still have 2 months until the scheduled 2.1 release to figure out a better solution, so I think we should try to find one.

**Comment by Be-ing** [comment]
We have no good solution to this for 2.1 yet. At this point I think we should go with the hack of shipping redundant skins.

**Comment by ronso0** [comment]
Sure. I don't see any other open skin-related PRs for 2.1, so I'll take care of this as soon as I find time..

Do we agree on the skin naming scheme? Should we attach the number of samplers to Shade and LateNight as well, although there's no option to change it there?
`Deere (64 Samplers)`
`Deere (16 Samplers)`
`Tango (64 Samplers)`
`Tango (16 Samplers)`
`LateNight (4 Samplers)`
`Shade (8 Samplers)`

**Comment by ronso0** [comment]
@Be-ing Do you go along with the suggested names?

**Comment by Be-ing** [comment]
I was thinking of leaving the number of samplers off the default versions of the skins and only specifically putting it for the ones with 64 samplers. But either way works.

**Comment by ronso0** [comment]
> I was thinking of leaving the number of samplers off the default versions of the skins and only specifically putting it for the ones with 64 samplers

Good idea.

**Comment by ronso0** [comment]
Sh*#! I should have done a more in-depth test.
It appears that loading graphics and templates i.e. for `Deere (64 Samplers)` like this `skin:../Deere/skin_settings.xml` works, but if that template needs to load other templates it looks for them in `skin` which is `Deere (64 Samplers)` not `Deere`.

So yes, this works, but in the 64-sampers folder we need all template-loading templates as well, not just those related to samplers number...

Do you know another solution?

**Comment by daschuer** [comment]
We should fix this in the cpp code.
I will have a look. Can you commit a version, that fails loading here?

**Comment by ronso0** [comment]
Looking at the commits here I see git marked several files as deleted although I just copied them...
will try to fix that.

**Comment by ronso0** [comment]
#1558 revealed some flaws about how icons where referenced in templates. I adapted this, now all skin versions work like before.

I'd say I'm done.
Tested with #1558 daschuer/lp1758485

**Comment by daschuer** [comment]
Are they flaws fixed now?
What is missing?

**Comment by ronso0** [comment]
> Are they flaws fixed now?

Yes. I just updated all skins' version to `2.1.0.01` Alright?

**Comment by daschuer** [comment]
Works good. Thank you. LGTM

**Pull request merged**
