### PR TITLE
common controller scripts es7 silence

### PR DESCRIPTION
**Pull request by Swiftb0y**
#11284 is suffering from a bunch of semi-bogus eslint issues. This somewhat fixes them. The most important change in the first commit, where we reduce the scope of the typescript-eslint to only apply to typescript definition files. The second commit then runs the automatic changes for eslint and adds the appropriate `eslint-disable no-var` where appropriate.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
I just tried an alternative for the no-unused-vars:
```
 "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        "argsIgnorePattern": "^_"
      }
    ],
```
which for me only printed the really unused vars.
see: https://typescript-eslint.io/rules/no-unused-vars/

Not sure what is the better solution.

**Comment by Swiftb0y** [comment]
that sorta works too, but that still leaves the eslint-typescript with linting our ES3 files. Moreover, the `eslint-typescript:recommended` config disables some of the eslint rules (such as no-unused-vars), because `tsc` already lints them by default. Unfortunately, the config for those doesn't carry over, which is why it creates bogus warnings again.

I think only applying the eslint-typescript rules to our `d.ts` files is the best solution for until someone figures out how to do this better.

**Comment by JoergAtGithub** [comment]
LGTM! Thank you!

**Comment by Swiftb0y** [comment]
Thank you

**Pull request merged**
