### PR TITLE
[WIP] (wix) automatically launch previous NSIS version uninstallation

### PR DESCRIPTION
**Pull request by sblaisot**
*** WORK IN PROGRESS, DO NOT MERGE ***

This PR improves the upgrade path from an NSIS-based Mixxx version to a WIX-based Mixxx version.
It detects if an uninstaller from NSIS is present and launch it asking the user to click Yes/Next to proceed to uninstallation.
If the exit code of the uninstaller is an error (by example if the user cancels the uninstallation, the wix installer fails sayingthere was a problem and the new version can't be installed.

- [x] Present a popup to explain what happens to the user
- [x] Automatically launch previous version uninstaller
- [ ] Auto-detect previous installation in custom directory (registry search ?)
- [ ] I18N
  - [ ] I18N logic
  - [ ] Make strings translatable on transifex

*** WORK IN PROGRESS, DO NOT MERGE ***

### CODE REVIEW

**Comment by sblaisot** [comment]
well, that doesn't work very well. Using batch file is a headache. I have a lot of side-effect with variables. This language is... well... not a language.
I think I will revert to a good old C program (after all, we surely have a C compiler at build time already).
Powershell and VBS are no option because we probably can't rely on having them on each user's PC.
So I need a way to build a native executable that looks for old versions, warn the user and launch the uninstall from these old versions. One working for 32 bits and 64 bits OS. (or maybe two and bundle the one in the same bitwidth than mixxx)

**Comment by Be-ing** [comment]
Yikes, that sounds like quite a pain. Thanks for working on this.

**Comment by sblaisot** [comment]
Well, I'm giving up.
Batch is just crap. Building a C++ application to uninstall Mixxx just triggers the antivirus (at least some of them, checked in virustotal, but too much to let this code spread to users).
Same thing as http://www.codeproject.com/Articles/71128/The-Case-of-Evil-WinMain
So, if someone has enough karma (and neurons to loose) to try building a "program" for the windows platform that
1. is native throughout all versions of windows from stock XP to last win10, without additionnal interpreter, DLL or anything
2. Look for MixxxUninstall.exe in the directory passed as argument AND in %PROGRAMFILES% AND %PROGRAMFILES32% and warn user (localized) and launch that exe with the /S parameter
3. work in 32-bits mode (so 64-bits %PROGRAMFILES% is not available, haha, thanks MS)
well, I will be happy to integrate it in the installer.

Before that, no way to have that f*cking upgrade path better.

/me is going back to good old *sh on good old *nix

**Comment by Be-ing** [comment]
Thanks for trying. Adding some hints about how to uninstall the old version to the error dialog will have to do.

**Comment by sblaisot** [comment]
I have another idea, let me try something different.

**Comment by Be-ing** [comment]
Any further progress on this? Should we let it go and be content with an error dialog telling the user to uninstall Mixxx 2.0?

**Pull request closed without merging**
