### PR TITLE
Install app icon in XDG hicolor icon theme

### PR DESCRIPTION
**Pull request by pinotree**
The application icon is a scalable icon (SVG) rather than a pixmap, so it does not fit well in that directory. Instead, install it in the
hicolor XDG icon theme: this way it can be properly loaded by XDG menus in the currently set XDG icon theme, without looking in the legacy pixmaps location.

### CODE REVIEW

**Comment by pinotree** [comment]
Note: I targeted this PR for the `2.3` branch, as I don't see 2.3.x releases yet, and this change should be quite straightforward and safe. In case it is not deemed wanted/safe for `2.3`, I can definitely retarget this for `master`, simply let me know.

**Comment by daschuer** [comment]
Thank you for taking care.

I think the icon requires to be named just mixxx.svg

**Comment by daschuer** [comment]
Sorry, I hit the famous close and comment button.

**Comment by daschuer** [comment]
Here is something about the naming:
https://specifications.freedesktop.org/icon-naming-spec/latest/

Interestingly I have already an icon there installed on my productive machine. Did we change it at some point?

If we change the naming, we need also adjust the .desktop file.

**Comment by pinotree** [comment]
> Interestingly I have already an icon there installed on my productive machine. Did we change it at some point?

Hmm not sure what you mean here; right now, `mixxx_icon.svg` is already installed, although in a legacy XDG icon theme directory (i.e. `/usr/share/pixmaps`, when the installation prefix is `/usr`).

> I think the icon requires to be named just mixxx.svg

The desktop file has:
```desktop
Icon=mixxx_icon
```
So the filename `mixxx_icon.svg` is correct.

Looking at the history of the desktop file, until ~3 years (see 85192acf6e50c19c3057fcca242f14c2adbe5540) ago the icon referenced was `mixxx-icon`; I took a look at the various XDG icon themes packaged in Debian, and I see some of them providing an icon for mixxx:
- Breeze (https://invent.kde.org/frameworks/breeze-icons): provides `mixxx`
- Deepin (https://github.com/linuxdeepin/deepin-icon-theme): provides `mixxx`
- Moka (https://github.com/snwh/moka-icon-theme): provides both `mixxx-icon`, and `mixxx`
- Numix Circle (https://github.com/numixproject/numix-icon-theme-circle): provides all `mixxx-icon`, `mixxx_icon`, and `mixxx`
- Obsidian (https://github.com/madmaxms/iconpack-obsidian): provides both `mixxx-icon`, and `mixxx` (and also `org.mixxx.Mixxx`, I guess to match the ID in the AppStream metainfo)
- Paper (https://github.com/snwh/paper-icon-theme): provides both `mixxx-icon`, and `mixxx`
- Papirus (https://github.com/PapirusDevelopmentTeam/papirus-icon-theme): provides both `mixxx-icon`, and `mixxx` (and also `org.mixxx.Mixxx`, I guess to match the ID in the AppStream metainfo)

there could be more XDG icon themes that provide an icon for mixxx, just I'm not aware of any.

So maybe it could be worth renaming the application icon to simply `mixxx`, since it seems well supported by various icon themes. What do you think, Daniel? I can add an additional commit doing the rename (adjusting the desktop file, of course).

**Comment by daschuer** [comment]
Thank you for digging that down. So I think we should rename it. 

Reading this:
https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup

> The support for SVG files is optional. Implementations that do not support SVGs should just ignore any ".svg" files.

I am concerned if it is correct to not ship a pixmap at all. Will there be still menu implementations not supporting svgs? 

Just to be save, I think we should install a 32x32 xpm file as for minimum compatibility.

**Comment by pinotree** [comment]
> So I think we should rename it.

I can do it. Do you prefer an additional commit to this PR, or a separate PR? Either is fine for me.

> I am concerned if it is correct to not ship a pixmap at all. Will there be still menu implementations not supporting svgs?

I'm not totally sure, however IMHO it would be reasonable to provide also non-SVG variants of the application icon.

> Just to be save, I think we should install a 32x32 xpm file as for minimum compatibility.

If I can make a small correction to this ;-) I'd rather generate PNGs in the XDG icon theme for some "well known" sizes, e.g. 16px, 32px, 64px, 128px. I tend to consider XPM as legacy format for icons (it is also marked as such in the XDG icon theme spec), and generally applications provide only PNG (and SVG when available) icons these days.

**Comment by daschuer** [comment]
Ok, thank you for offering your time.

I think we can do everything in one PR.

What is the purpose for fixed size icons in hicolor? If there is no specific scaling/rendering  problem to fix, I like to avoid maintaining additional icons.

Hopefully one SVG + one fixed size pixmap as fallback to comply with the XDG specs will be sufficient.

**Comment by daschuer** [comment]
Why the way, please sign 
https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ
To allow us to ship your work with Mixxx
And comment here when done.

Thank you.

**Comment by pinotree** [comment]
> Why the way, please sign
> https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ
> To allow us to ship your work with Mixxx
> And comment here when done.

Oh, bizarre -- anyway, done.

**Comment by ronso0** [comment]
Thanks for you research, @pinotree 

Interesting, I thought theme creators would adapt original icons, not completely twist them.
The _Paper_ icon looks more like 'Settings' than a DJ app..

image
https://github.com/snwh/paper-icon-theme/raw/master/Paper/48x48/apps/mixxx-icon.png

**Comment by uklotzde** [comment]
How about moving the files into an `icons` subfolder? The naming mixxx.svg/.png is very general and the *icon* context is lost.

**Comment by daschuer** [comment]
Thank you for this complete fix. 

This means we drop the /usr/share/pixmaps support completely.  
That works for me. What I have read, it is legacy anyway and there are issues when installing in the home directory. 
I just want to point this out. 

I have just started the CI and will test this now.

**Review by uklotzde — APPROVED** [review]
LGTM @daschuer Please merge when ready.

In a subsequent cleanup step we could reorder and rename the remaining images, i.e. icons and logos. But this affects only internal resources, not urgent.

**Review by daschuer — APPROVED** [review]
All green and works locally. 
Thank you for this PR with extended scope. 
LGTM

**Pull request merged**
