### PR TITLE
LateNight: style main menubar

### PR DESCRIPTION
**Pull request by ronso0**
Wooh, I finally managed to tame the Qt stylesheet madness and untangle my previous attempts.
This first implementation is for **LateNight** only.
It is tested on Ubuntu with xfce. If that works okay on Win and Mac, too, I will start to port the styles to all skins.

Confirmed to work in
- [x] *ubuntu with Xfce
- [ ] *ubuntu with Unity/Gnome
- [x] Fedora / Arch with Gnome
- [x] Windows10  (tested with 100% and 125% native app scaling)
- [x] Windows7
- [x] macOS (not affected due to global menu)

Linux, with xfce
image
image

It allows to save some vertical space but it also makes it obvious how much space is wasted by the menubar.

Consider this:
To style the main menubar we use the skin's font but
we try to preserve most other font properties set by
the operating system, such as the font weight, size and style.
This is because the user may use a HiDPI screen with fonts
slightly larger than the defaults but may NOT have scaled Mixxx.
Even though different fonts at the same point size don't necessarily
produce the same effective visual size the difference is
marginal inmy experience, except for some really weird fonts.

### CODE REVIEW

**Comment by NotYourAverageAl** [comment]
Before 
image

After image

On Windows10 (2560x1440)
1. Horizontally the menubar feels cramped; menu items are too close together. it looks fine on your screenshot, a windows issue maybe?
2. The checkboxes are nicely visible now, but super small.
3. I do feel like I'm missing vertical space. in saying that, I never really use the bar, so may I'll get used to it

**Comment by JoergAtGithub** [comment]
I tried this on Windows7 and in general it works, but I noticed the following:
-At startup the Menu Bar is displayed with Windows system skin after some seconds it switches to LateNight skin. This looks odd to me. Is it possible to hide the menu at all, until itis usable?
-If the main window looses focus, the Windows system skin shows the menus as inactive, the LateNight skin looks allways the same

Aestetical impressions:
-All other fonts in PaleMoon skin look more bold than the menu font
-In fullscreen mode the LateNight menu skin looks much better than before
-If Mixxx is shown as a window, the window decoration is very dominant. IMHO the tiny LateNight menu doesn't fit in this case.

**Comment by daschuer** [comment]
I can confirm that this work on Ubuntu Bionic with Ubuntu/Unity/Gnome Desktops
Thank you :-)

**Comment by ronso0** [comment]
Thanks for testing @NotYourAverageAl
@JoergAtGithub Can you also confirm that it looks like in my screenshot?
If so, this is great! And we just need this confirmed on macOS @foss- maybe?

Then we can get into tweaking the details.

**Comment by JoergAtGithub** [comment]
This is how it looks on Windows7:
grafik

**Comment by ronso0** [comment]
> At startup the Menu Bar is displayed with Windows system skin after some seconds it switches to LateNight skin. This looks odd to me. Is it possible to hide the menu at all, until itis usable?

This PR doesn't change that behaviour. The launch screen style is parsed first, before actually loading the skin incl. menu style.
Though, this multiple aspects:
**1** I noticed that opening the preferences from the menu bar before the launch process is finished may leed to incorrect preferences, IIRC not all controllers showed up or the mapping wasn't loaded, yet. This may be confusing
**2** When a skin fails to load for whatever reason users need the menubar to access the preferences

For a Consistent Experience™ we could isolate the menubar styles as we do with the launch screen, or even include it there.
I'll take look if that's still feasible for 2.3

**Comment by ronso0** [comment]
> If the main window looses focus, the Windows system skin shows the menus as inactive, the LateNight skin looks allways the same

Tbh I consider this an improvement. Even with an unfocused window in difficult lighting you can aim for a menu item, instead of clicking an emtpy place first to get a readable menu.
Or do you want to say that dim menus are required to realize the window's focus? If that's the only proper way of a Windows theme to signal the focus that's an issueof its own.

**Comment by ronso0** [comment]
Yeah, I see the main menu items could use more spacing.

> The checkboxes are nicely visible now, but super small.

should be sized like in the other menus.
Btw the entire row is responsive, not just the checkbox.

**Comment by ronso0** [comment]
@daschuer Could you please share a screenshot of the menu with Gnome?

This need some os-specific tweaks to look good, like the checkbox offset is computed differently on linux / windows for example.

**Comment by foss-** [comment]
macOS 11.2.3
mixxx 2.3.0-beta (build HEAD r8076)

**Comment by ronso0** [comment]
@foss- Did you install the [build from 'artifacts'](https://github.com/mixxxdj/mixxx/suites/2252635869/artifacts/46856833) at the bottom of the page _Show all checks > Build / macOS > click > artifacts (top right)_?
I don't expect the global menu on macOS to be styled I just want to make sure nothing is f##ed up ; )

**Comment by foss-** [comment]
Yes that's the artifact build.
Looking fine, fullscreen is ok as well.

**Comment by JoergAtGithub** [comment]
Is the global menu of MacOS also skined?
I imagine, that in full screen mode, MacOS looks like every other platform, but if I imagine a dark menu bar on top of a light desktop scheme, an a smaller Mixxx window somewhere below, I can't imagine, that this looks good. But I'm not a Mac user.

**Comment by foss-** [comment]
macOS dark mode: dark menu bar
macOS light mode: light menu bar

How would you end up with dark menu bar on light desktop scheme? That will never happen.

The only thing currently off is the light title bar of mixxx window on macOS dark mode. But that is due to some xcode shenaningans which will not be addressed for 2.3.

**Comment by daschuer** [comment]
Here is the GNOME view on Ubuntu Bionic:
grafik

**Comment by poelzi** [comment]
I think the checkbox could use a color from the palette. Maybe green or orange.
The difference in win10 spacing could be a result from DPI differences.
Thank you for finishing this madness. When I started with styling the menubar i questioned my sanity with qts strange behaviour :)

**Comment by NotYourAverageAl** [comment]
Agree with poelzi about colour. Also I think I liked the the storm trooper look, light menu bar & dark everything else..but that's just me

**Comment by ronso0** [comment]
@poelzi May be true. later I'll try to reenact my win10 installation and check on fullhd

**Comment by uklotzde** [comment]
Fedora (before)
latenight before

Fedora (after)
latenight after

**Comment by ronso0** [comment]
@uklotzde Your screenshots say this is a no-op PR ;)
please update the 'before' one.

**Comment by ronso0** [comment]
Until now it seems in Gnome and Xfce the checkbox is within the item padding, everywhere else (Fedora, Win7/10) it's added.
We can address Win via `<Style src-windows="style-windows.qss" ... >` but we can't filter for Fedora.
@uklotzde Could you post a screenhot of another Qt app where the main menu has solo items and those with checkboxes?

**Comment by ronso0** [comment]
In the end I'd try to make it look good on Linux for the most used desktop distros which appear to be Mint, Ubuntu, ... atm.

**Comment by Holzhaus** [comment]
This is how it looks on Arch Linux (GNOME Shell 3.38.4): 
Screenshot from 2021-03-16 00-00-16

**Comment by Be-ing** [comment]
Merge?

**Comment by ronso0** [comment]
obvioulsy not!
I found another way make it work on Linux (likely for Fedora/Arch as well) and I was fumbling with the styles on Wind'ohs and of course it's again _slightly_ different there, enough to look sh#*tty.

Now picking relevant parts from style_palemoon.qss and splitting styles into styles_linux.qss and styles_windows.qss because theme style sheets would override the platform-specific ones....
 
Coming closer to make it look like this for both:
image



I believe the folks who implemented the style parsing on certain platforms are not very popular...

**Comment by poelzi** [comment]
Sometimes the different behaviour of QT depending on the OS/Desktop Environment and version of QT is just confusing, the styling system in particular. I have seen the strange spacing problem as well on some desktops, but not others as well and gave up at some point ;)
@ronso0 while you at it ant still remember this mess, maybe your solution could be applied to the context menu as well ?
I think the spacing there is also broken, it is just not that noticeable because we only have checkboxes or normal menu items per submenu and not mixed, but the offsets between the checkboxes seem to be different.

**Comment by ronso0** [comment]
I will not mix up the main menu and the context menus for two reasons:
a) reliable test tesults and iteration is super slow, I'd rather not open that can of worms atm (in this PR) 
b) the main menu has only items, with or without ::indicators, no QCheckBoxes

But the new styles are quite compact and they are in separate stylesheets, so it's easy to remember what's what. So if I don't loose my mind I can start another PR once this here is merfed.

**Comment by ronso0** [comment]
@poelzi Are you aware of an OS or distro where the menu style is broken to justify a rework?

btw, while testing on Windows10 yesterday (pita by itself..) I noticed that in the effect selector menu there are no checkboxes, but at least the menu unfolds in a way that it does not cover the effect selector showing the active effect (which is ugly unstyled when the list is open).

**Comment by ronso0** [comment]
@poelzi 
Do you consider this broken? (menu in SublimeText) this is how most Mixxx menus look like.
image

I think this is the desired look because the item text is always aligned vertically, no matter if and how items and checkboxes are mixed. This is rather easy to style, and I'm currently testing if it is feasible and riskless to transform WMainMenu's QActions to QWidgetActions with QCheckboxes.
That way this qss nightmare would shrink to a regular QMenu PITA which I already tamed, somehow : )

**Comment by poelzi** [comment]
Yes, that looks correct.

Since I implemented the crate submenu which has a special behaviour, if I remember correctly, the way it is implemented was the only way I got it working, so the menu does not close when you toggle a crate. It is still not perfect as clicking at the place behind the text closes the menu, but I never got this bug solved.

**Comment by ronso0** [comment]
> I'm currently testing if it is feasible and riskless to transform WMainMenu's QActions to QWidgetActions with QCheckboxes.

That is more complicated than expected and doesn't work out style-wise: even without a custom theme the QWidgetActions with QCheckboxes are styled entirely different than current checkable QActions. Dropped...

**Comment by ronso0** [comment]
okay, I think I got it sorted both on Win and Linux. Shall I mention Windows has quite some quirks when it comes to font rendering?

Linux, with xfce
image

Windows (tested with 100% and 125% native app scaling)
image

I also noticed that on Windows "Open Sans" semi-bold is identified as separate font "Open Sans Semibold" (while on Linux all variants are "Open Sans") and fixed that along the way.

I force-pushed, check it out!
If the menu looks fine on Win and Linux for you I'll style LateNight Classic, too, and maybe also do that for the other skins.

I thought about moving the common menu properties to `default.qss`to remove redundant qss, but that would mean that the menu would be screwed up for all custom skins :\

**Comment by JoergAtGithub** [comment]
I tried this on Windows 7 and it worked flawless with LateNight Palemoon. I also tried switching the skin. This works, when I select a completly different skin, but if I just switch the color scheme to LateNight Classic, I get this:
grafik

One visual remark: The black checkbox is very difficult to recognize on the dark menu background.

**Comment by Holzhaus** [comment]
Not sure if this is related to this PR, but I get:

```
$ ./mixxx
Warning [Main]: Configuration file is at version "2.4.0-alpha-pre" instead of the current 2.3.0-beta
Warning [Main]: Cannot open file ':/images/mixxx_icon.svg', because: No such file or directory
Warning [Main]: Cannot open file ':/images/mixxx_icon.svg', because: No such file or directory
Warning [Main]: "/proc/10989/root"
Critical [Main]: SchemaManager - Failed to load database schema migrations from ":/schema.xml"
```

**Comment by uklotzde** [comment]
> Not sure if this is related to this PR, but I get:
> 
> ```
> $ ./mixxx
> Warning [Main]: Configuration file is at version "2.4.0-alpha-pre" instead of the current 2.3.0-beta
> Warning [Main]: Cannot open file ':/images/mixxx_icon.svg', because: No such file or directory
> Warning [Main]: Cannot open file ':/images/mixxx_icon.svg', because: No such file or directory
> Warning [Main]: "/proc/10989/root"
> Critical [Main]: SchemaManager - Failed to load database schema migrations from ":/schema.xml"
> ```
> 
> **EDIT** Unrelated, happens on 2.3 as well.

Did your forget to pass `--resourcePath`?

**Comment by Holzhaus** [comment]
> > Not sure if this is related to this PR, but I get:
> > ```
> > $ ./mixxx
> > Warning [Main]: Configuration file is at version "2.4.0-alpha-pre" instead of the current 2.3.0-beta
> > Warning [Main]: Cannot open file ':/images/mixxx_icon.svg', because: No such file or directory
> > Warning [Main]: Cannot open file ':/images/mixxx_icon.svg', because: No such file or directory
> > Warning [Main]: "/proc/10989/root"
> > Critical [Main]: SchemaManager - Failed to load database schema migrations from ":/schema.xml"
> > ```
> > 
> > 
> > **EDIT** Unrelated, happens on 2.3 as well.
> 
> Did your forget to pass `--resourcePath`?

I never did that. There should a symlink in the build dir. I'll check if someone broke that.

**Comment by Holzhaus** [comment]
https://bugs.launchpad.net/mixxx/+bug/1921549

**Comment by uklotzde** [comment]
> > > Not sure if this is related to this PR, but I get:
> > > ```
> > > $ ./mixxx
> > > Warning [Main]: Configuration file is at version "2.4.0-alpha-pre" instead of the current 2.3.0-beta
> > > Warning [Main]: Cannot open file ':/images/mixxx_icon.svg', because: No such file or directory
> > > Warning [Main]: Cannot open file ':/images/mixxx_icon.svg', because: No such file or directory
> > > Warning [Main]: "/proc/10989/root"
> > > Critical [Main]: SchemaManager - Failed to load database schema migrations from ":/schema.xml"
> > > ```
> > > 
> > > 
> > > **EDIT** Unrelated, happens on 2.3 as well.
> > 
> > 
> > Did your forget to pass `--resourcePath`?
> 
> I never did that. There should a symlink in the build dir. I'll check if someone broke that.

Confirmed that it works without the cmdline argument. Just noticed that we are checking if CMakeCache.txt exists in the application folder and then choose the build directory.

**Comment by ronso0** [comment]
> ```
> Warning [Main]: Cannot open file ':/images/mixxx_icon.svg', because: No such file or directory
> ```

@Holzhaus Maybe something went wrong with #3692 ? You can try to revert 3c8306ffcf9d9864abc59bfd149fa24f6d43caff

**Comment by ronso0** [comment]
@JoergAtGithub 
As stated in the PR and my last comment only PaleMoon is styled by now.
Classic is screwed up as it shares qss with PaleMoon but has no colors set, yet.
the other skins should still have the original, native menu bar.

@Holzhaus @uklotzde @daschuer @NotYourAverageAl 
Could you test again, please, and post a screen?
Styling Classic and porting to other skins will be a no-brainer.

**Comment by Holzhaus** [comment]
@ronso0 No, I can't test, due to the issue I mentioned above.

**Comment by Swiftb0y** [comment]
Fedora 33 on GNOME
image

**Comment by ronso0** [comment]
@Swiftb0y ..and the selected checkboxes also look alright, I guess?

**Comment by Holzhaus** [comment]
> Fedora 33 on GNOME
> image

GNOME 40 on Arch looks the same.

**Comment by NotYourAverageAl** [comment]
W10
before
image

new
image

**Comment by Swiftb0y** [comment]
> and the selected checkboxes also look alright, I guess?

yes

**Comment by ronso0** [comment]
perfecto!

**Comment by ronso0** [comment]
LateNight Classic is included now:
image

**Comment by Holzhaus** [comment]
On Arch/GNOME 40 the indentation for items without checkboxes is still slighty off but I don't know if that is fixable:

Peek 2021-03-31 00-24

**Comment by ronso0** [comment]
oh yeah, I noticed I screwed up some things with the consolidation into common style.qss
also affects Win10 I think.
I'll fix it

**Comment by ronso0** [comment]
The main menu should now look the same on all OS, see picture below.

Also, I took the opportunity to consolidate and clean up all QMenu styles and split off a few tweaks into style_windows.qss
Again, tests on ubuntu with xfce and Windows10 passed. Please tell me everything looks as pictured also with Gnome and other compositors.

Please check all menus in 
* main menu bar
* track menu (tracks table and in decks)
* editing metadata in the tracks table
* tree view
* spinboxes (beatsize, AutoDJ tab, BPM in tracks table)
* table header
* cover art
* label field in cue menu

image

The only weird things I noticed (on linux) is that `Select All` and `Ctrl+A` overlap in lineedit menus (english locale), and on Windows10 in PaleMoon the yellow library header sort arrow from the Classic theme is used :shrug:

**Comment by Swiftb0y** [comment]
Unfortunately, I couldn't compare everything from the list because some references are missing from your composed screenshot. The things that I was able to compare matched and everything that I wasn't able to compare still looked like it was styled in accordance to the latenight theme.
(GNOME 3.38 wayland on fedora btw). 

However, I encountered a major issue: I was not able to edit track metadata from within the library table. Selecting a table cell was no problem, but clicking on that cell again so bring up the editor just didn't work.

**Comment by ronso0** [comment]
okay, thanks. only the inline edit menu was missing, and that's the same for all spinboxes, track tag editing, cue label editing and the searchbox. Note that on windows there are no icons (same as in all other apps I checked).
image

> However, I encountered a major issue: I was not able to edit track metadata from within the library table. Selecting a table cell was no problem, but clicking on that cell again so bring up the editor just didn't work.

@Swiftb0y 
Even after you enabled that in Preferences > Library? than it's a regression in 2.3. This branch only chnages xml/qss.

**Comment by Swiftb0y** [comment]
> Even after you enabled that in Preferences > Library?

I'm sorry for the false alarm, I wasn't aware of this preference option. Works as expected.


Did you provide custom icons for that context menu? The one in your screenshot seem very latenight-ish but Qt seems to use the default ones. 
image
weirdly enough, the `Select All    Ctrl-A` seems to be fine for me (english locale as well)

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you.

Screenshot from 2021-04-04 21-07-10


System:

    gnome-desktop 1:40.0-1
    qt5-base 5.15.2-5
    xorg-server 1.20.10-3

**Comment by ronso0** [comment]
> Did you provide custom icons for that context menu? 

No. I'd like to try that to have entirely themed, failsafe menus, but that is on hold until we tackle to style all dialogs like the preferences and track properties dialogs, too. 
I did some brief research how to do load custom icons but didn't find anything useful, yet (with "qmenu use custom icons / icon set")
This is Papyrus-Dark theme, and it's actually only the inactive icons that match :\

**Comment by ronso0** [comment]
Alright, nice!
I guess we can merge this then, and I'll use it as blueprint for the other skins.

**Comment by daschuer** [comment]
@ronso0 Great, this really helps to release the pressure form the menu bar topic.

I notice that the menu bar is not styled during the load screen. Is this hard to solve?

**Comment by ronso0** [comment]
yes it looks great but I also realized how much space we waste with the menubar..

that it's unstyled initially is a minor annoyance. We could
**a**) split off the menubar stylesheets and parse them early before/together with the the launch screen, maybe [here](https://github.com/mixxxdj/mixxx/blob/e6ff669825a402c320a011b81e54747157ea8837/src/mixxx.cpp#L923)
**b**) on Linux and Windows, don't show the menubar until the skin is loaded succesfully (or failed!) because until then the menubar is neither responsive  nor needed anyway.

**Comment by ronso0** [comment]
as mentioned: the pain with the menubar is _only_ styling checkboxes and items concistently across all OS . so if we omit that we could set a minimal stylesheet (no the submenus, no checkboxes) until the entire skin is parsed.
so even though I'd prefer **b** we may get **a** working without too much hazzle (and no risk)

**Comment by daschuer** [comment]
Thank you for looking into it. Both ideas are reasonable ...

**Comment by poelzi** [comment]
@ronso0 I already implemented #3189 a solution for the menubar problem. There is only one drawback I was not able to solve: native menubar on linux. QT seems to be very broken when the qaction associated with a menubar item is not owned by the menubar or outlives changes :-/ 
Shade also needs a menubutton added.

**Pull request merged**
