### PR TITLE
Ramp vinyl scratching to zero and back

### PR DESCRIPTION
**Pull request by ywwg**
@daschuer 

This is the fix I was describing.  This keeps the logic contained and doesn't start leaking the scratching state all over the place.

### CODE REVIEW

**Comment by daschuer** [comment]
I really do not understand the advantage of this PR. You have originally rejected the solution with the extra ramping loop in sound enginebufferscalelinear. 
Because of this I have spend my free time and developed a solution that does not require and extra ramping loop. Now it is back. 

The other benefit of my solution is that we have all rate depended ramping in a single place. So it is in addition better to maintain and to understand. 

My solution is also in line with the following PRs, that centralized all gain changes in EnginePregain. 

Is there a leaking problem?

**Comment by ywwg** [comment]
> extra ramping loop

Are you referring to my comment here?  https://github.com/mixxxdj/mixxx/pull/539#discussion_r27625142

I meant the high-latency issue we had discussed (https://bugs.launchpad.net/mixxx/+bug/1434253) where when the latency value is set large, the track audibly gets quieter and then louder over the scratch. I'm still not convinced we have to ramp to zero, this is just an example of how I would fix that problem.  This has nothing to do with the CPU usage of iterating over a buffer. 

By leaking, I mean the leaking abstraction, not leaking memory.

In general I'm in favor of discussing a design before writing code, but my understanding is you prefer to write the code first and then discuss it.  Inevitably, some of that code will need to get thrown out.

**Comment by daschuer** [comment]
> Are you referring to my comment here? #539 (comment)

Yes.

> In general I'm in favor of discussing a design before writing code, but my understanding is you prefer to write the code first and then discuss it. Inevitably, some of that code will need to get thrown out.

Please stop discussion that way. I always try to discuss a solution first, but in this case it was discovered while coding. The pot calling the kettle black. 

Back to topic: I think the core question is: Do we need to fade when scratching with low speed. You have a vinyl setup and a time coded vinyl. Would you mind to record a slow transition from full speed to zero, and back to minus full speed? How does the gain change? 

I think the core issue for the vinyl sound emulator is that a vinyl needle is able to pick up at least 20 Hz to 20 kHz at any speed. Our source sample rate is 44100 Hz which can reproduce sound up to 22050 Hz. If we slow down the signal to 10 % we have a Nyquist frequency up to 2205 Hz. All the range from 2 kH to 20 KH is dropped. 

It is hard to emulate that. We probably may add a pink noise passed though a high pass with the current Nyquist frequency of stretched sound. But probably no user cares about it. 

So we may discuss to drop the rat related gain change entirely.  

Since we have decided that we need the vinyl sound emulation at on point. It is obvious that the 
gain should be zero at zero rate. 
The leaking in abstraction is a chicken or egg issue. In this PR we leak the vinyl sound emu in my PR we leak the "is scratching". My saves some CPU.

**Comment by ywwg** [comment]
> 20 Hz to 20 kHz at any speed

That assumes that vinyl is an infinitely-dense medium capable of retaining waveform data above the original frequency.  But in practice, vinyl has much poorer high frequency response so I don't think we're too far off by having an effective low-pass filter from 2Khz and above at 10% speed.

As for leaking the vinyl sound emu abstraction, I don't agree that this PR leaks it.  The linear scaler is the scaler designed for vinyl-style scaling, so it's perfectly reasonable to put the scaling code here.

In my testing, I have not found an audible difference between ramping to zero on scratch or not -- I think by the waveforms it seems we can either introduce new low-frequency information (no ramping) or new high-frequency information (ramping).  Since low-frequency is harder to hear, maybe the answer is just not to ramp as you suggest.

**Comment by daschuer** [comment]
One question we need to solve is: Do we need a rate related gain change? 

Looking at original scratch sound, I think yes: https://github.com/mixxxdj/mixxx/pull/525#issuecomment-84217817 
But is hard to spot if a 7% threshold is a valid assumption or if the gain to rate relation is linear. 
I have some doubts about it. Probably there is no hard threshold and a non linear relationship. 

Some time ago you had provided a recorded time coded vinyl during scratching. But I have lost it. 
Maybe you still have access to it or produce a new one.  
I hope that a recorded slow forward to backward transition suits to show how the gain changes with the rate. 

In any case, we should make not difference between slow and fast transitions, like we currently do.  

> .. so it's perfectly reasonable to put the scaling code here. 

From this point of view yes, as long as all rate related gain changes are placed there. 
From the performance point of view, it is better to have all gain changes in EnginePregain. 
This avoids also sudden CPU demands, which are always a candidates for buffer underflows in case CPU load is already high. In this case: Crossing Zero -> Sudden CPU demand -> Click

**Comment by ywwg** [comment]
I will see about creating a short recording of slow scratching.

**Comment by daschuer** [comment]
Cool, Thank you!

**Comment by rryan** [comment]
I believe this is obsolete now since I think all the linear scaler fixes PRs are merged.

**Pull request closed without merging**
