### PR TITLE
Various i18n fixes

### PR DESCRIPTION
**Pull request by esbrandt**
Some of the changes might worth back porting

### CODE REVIEW

**Review by esbrandt — COMMENTED** [review]
*Proposal standard punctuation marks*
How about settling for ``…``(HORIZONTAL ELLIPSIS
Unicode: U+2026, UTF-8: E2 80 A6) without leading or trailing whitespace?

This is [already used](https://www.transifex.com/mixxx-dj-software/mixxxdj/viewstrings/#en/mixxx2-4/290733954?q=text%3A…) with some newer strings.

**Review by daschuer — APPROVED** [review]
LGTM, 
Merge, or do you wish to add the ellypsis change as well?

**Comment by esbrandt** [comment]
I would like to hear what a native speaker/2nd opinion has to say about the punctuation eventually, before going to change the remaining strings.

One thing that goes against the use of Ellipsis`…` , is that it is not easily available when typing. It may be Lost in Translation (sic) , since you can't really see the difference on screen with most fonts. In Transifex you either have to copy the source string and work from there, or use the *Add special character* menu to add. Transifex itself has no check for punctation between source and translated string. Unless a translator uses a 3rd party app capable of proofreading ( Wordfast, Omega etc..) it may diverge from the source.

So using three dots instead `...` might be the more practical approach, while delivering the same consistency.

**Comment by ronso0** [comment]
then let's split the affected strings into QStringLiteral(...) and tr() to avoid mistakes?

**Comment by esbrandt** [comment]
Thanks for the feedback.

Will leave the strings for now as is, there is no pressing need to change. Mixed use of 3-dots and eclipses is not optimal, but it apparently works for the users. 

Eclipses are displayed different in some asian languages. And they are available in fewer fonts than thought.
Something learned during research.

Ready to merge. Then going to back-port some changes.

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
