### PR TITLE
LateNight: add effect chain menu button

### PR DESCRIPTION
**Pull request by ronso0**
image
image

### CODE REVIEW

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you. I think it might be worth considering to use a selector like the quickeffect combobox in the mixer section, at least if we want to make it usable with a controller. But no need to block this IMHO.

**Comment by ronso0** [comment]
Hmm, this is easier said than done because it's not only a list but also contains submenus.
I think for controller access we should rather add a control to open/close the menu, then use `[Library],MoveUp/Down/Vertical` to navigate and `[Library],GoToItem` to select. This works well for the track menu already.

**Comment by Holzhaus** [comment]
Yes, we could consider that. But it's not crucial for 2.4.0 IMHO. In any case, we can merge this now.

**Comment by Be-ing** [comment]
> controller access we should rather add a control to open/close the menu

The only feature from this menu I intended to be used from controllers is loading presets that already exist, which there already is a ControlObject for. I suppose you *could* add a CO to save a new preset... but then you have to move your hands from the controller to type the name in the dialog box anyway, so I don't think it would be worth it.

**Pull request merged**
