### PR TITLE
[Not a PR] Replace ChannelHandle/ChannelHandleAndGroup with GroupHandle

### PR DESCRIPTION
**Pull request by uklotzde**
I wrote this as an alternative to #4672 to get rid of the string-typed group handles. It also cleans up the code by getting rid of some redundancies. Worked reliably for me.

For whom it may concern. This PR is only intended as an offer to copy my branch before I finally delete.

You may close this PR when done. Otherwise I will do it eventually.

### CODE REVIEW

**Comment by Swiftb0y** [comment]
Thank you. I made a copy in my fork and may adopt this in the future.

**Comment by daschuer** [comment]
Thank you. 

@Swiftb0y you may also issue a new WIP PR, just to remind us that this work exists.

**Comment by Swiftb0y** [comment]
sure #4843

**Comment by daschuer** [comment]
Thanks :-)

**Pull request closed without merging**
