### PR TITLE
Require cmake 15 in debian/control

### PR DESCRIPTION
**Pull request by daschuer**
This should fix our ppa bionic builds. 
A regression since #3615

### CODE REVIEW

**Comment by moretocome** [comment]
Unfortunately building fails on Raspbian after this, where cmake is only at version 13. After manually lowering the requirement in CMakeList.txt to 1.13.0, building completes without errors.

**Comment by Holzhaus** [comment]
> Unfortunately building fails on Raspbian after this, where cmake is only at version 13. After manually lowering the requirement in CMakeLists.txt to 1.13.0, building completes without errors.

@daschuer can you elaborate why this change was needed? Maybe it's not necessary after all. 

@moretocome Raspian/Debian uses very old Software ("for stability") - a model that is fundamentally incompatible with the desire to run bleeding-edge beta/alpha software (such as Mixxx). I recommend switching to [Arch Linux ARM](https://archlinuxarm.org/) or another bleeding-edge distro.

**Comment by daschuer** [comment]
CMake 15 is required since #3615
https://github.com/Be-ing/mixxx/blob/3133372e05a9f0f0293aaea59dadfc01e5eb0601/CMakeLists.txt#L1

It is required for FOLLOW_SYMLINK_CHAIN, only used  
if(APPLE AND MACOS_BUNDLE AND FDK_AAC_LIBRARY)

So I think we can make this conditional.

**Comment by Holzhaus** [comment]
No, let's not make our build setup more complicated than it already is. Users just need to update, and cmake even offers prebuilt aarch64 executables on their website.

**Pull request merged**
