### PR TITLE
controlpickermenu: fix duplicate entries / empty reset menus

### PR DESCRIPTION
**Pull request by ronso0**
https://bugs.launchpad.net/mixxx/+bug/1895415

fixes a regression from da199583da12f065b06d24a68d74947f0d5a08d5

### CODE REVIEW

**Comment by ronso0** [comment]
if a reset action is added the regular/reset controls are swapped when picking them from the menu.
https://github.com/mixxxdj/mixxx/blob/2.3/src/controllers/controlpickermenu.cpp#L855

Controls are added:
```
Debug [Main]:    add index 984 to "Pitch (Musical key)" : "Deck 1" ( "pitch" )
Debug [Main]: 
Debug [Main]:    add index 985 to "Pitch (Musical key) (Reset to default)" : "Deck 1" ( "pitch_set_default" )
```

Controls clicked:
```
Debug [Main]:    controlChosen
Debug [Main]:            index: 984
Debug [Main]:          control: "[Channel1]" , "pitch_set_default"
Debug [Main]:            title: "Deck 1: Pitch (Musical key) (Reset to default)"
Debug [Main]:      description: "Deck 1: Pitch control (does not affect tempo), center is original pitch (Reset to default)"
Debug [Main]: 
Debug [Main]: 
Debug [Main]:    controlChosen
Debug [Main]:            index: 985
Debug [Main]:          control: "[Channel2]" , "pitch"
Debug [Main]:            title: "Deck 2: Pitch (Musical key)"
Debug [Main]:      description: "Deck 2: Pitch control (does not affect tempo), center is original pitch"
```

Any ideas how fix this index confusion?

**Comment by ronso0** [comment]
> if a reset action is added the regular/reset controls are swapped when picking them from the menu.

okay, got it! They're not swapped, it's just an index offset issue: https://github.com/mixxxdj/mixxx/pull/3094/commits/388b26854117310371072aa980a5209ca2d8f1e4

Fixed, ready to be merged!

**Comment by ronso0** [comment]
ping.
currently the mapping wizard menu is hard to use IF users notice the wrong combobox entries. 
if they don't notice the mapping will not work as expected.

**Review by Holzhaus — APPROVED** [review]
Works fine, thank you!

**Pull request merged**
