### PR TITLE
Shade :: add split cue button

### PR DESCRIPTION
**Pull request by ronso0**
...since Shade is the only without one.
https://bugs.launchpad.net/mixxx/+bug/1472411

just a draft for now to discuss if it's okay to implement it like this:
shade-splitcue_

before:
shade-splitcue_before

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for taking care.
I would prefer to use the normal empty square button with the lable "split" to stay in style. A alternative would be a halve headphone icon on top of it.

**Comment by ronso0** [comment]
hmyeah I see your preference, just SPLIT is enough. but I think there's not enough vertical space for both a button and a label above it if we use the EQ kill square button with a reasonable margin to the dark separator and to the HEAD label

**Comment by ronso0** [comment]
I'll make sketches for both versions

**Comment by ronso0** [comment]
button incl. label
shade_splitcue

separate label
shade_splitcue_sep

I very much prefer the first version as it leaves the HEAD label separate to mark the entire section instead of being misread as HEAD SPLIT

**Comment by daschuer** [comment]
I agree. Thank you for comparing the alternatives.

**Comment by daschuer** [comment]
Thank you. LGTM

**Pull request merged**
