### PR TITLE
fix: typo ;)

### PR DESCRIPTION
**Pull request by spotlesscoder**

### CODE REVIEW

**Comment by ronso0** [comment]
Thank you for this PR.
Please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

**Comment by CodingSpiderFox** [comment]
Done

**Comment by ronso0** [comment]
Thank you!

**Comment by daschuer** [comment]
Hi @CodingSpiderFox, I like to add your name to the Mixxx about box. What name should I pick?

**Comment by CodingSpiderFox** [comment]
Just call me codingspiderfox ;)

Thank you :)

**Pull request merged**
