### PR TITLE
vector icons for Preferences, Library & About dialog

### PR DESCRIPTION
**Pull request by ronso0**
- [x] vector icons in Preferences
- [x] vector icons in Libary features
- [x] vectorize icons not in `/res/images/templates/ic_template_library_and_preferences.svg`
- [x] use note in drag'n'drop icon
- [x] rename `locked` to `locked_tracklist` for locked playlists & crates

~~I'm still trying to figure out how the icons' drop shadow was created. I can't select or edit it and it's cut of in some places~~ Inkscape > Filters (> Remove Filters)
In general I think we don't need it. The icons would appear sharper without it.
Any objections?

### CODE REVIEW

**Comment by ronso0** [comment]
Where do we still need png's?
App icon for Windows?

**Comment by ronso0** [comment]
Feels like I'm done.
Tested with ubuntu studio 18.04, xfce session. Please test with Rhythmbox, Banshee & Traktor libraries.

**Comment by ronso0** [comment]
One issue I noticed in ubuntu 14.04: the Preferences icons are hard to identify with an OS theme that supplies a dark scrollarea background. No (nice) workaround comes to mind that would solve this for all shades of OS themes.
In 18.04 however, it seems to be the other way around: I didn't manage to apply any official GTK theme to Mixxx menubar as well (windowed), or the Preferences window; both always have a bright background.
OTOH menubar in fullscreen mode would always be dark with black menu items text (File, Edit etc.).

**Comment by Be-ing** [comment]
I have noticed that issue in the preferences too. How about adding a background color for those? For the library icons, it suspect it would be better to keep the transparent background so skins can set the background color easily.

**Comment by daschuer** [comment]
Since this is a 2.2 PR, we need to only make sure that it is no regression compared to 2.1.
IMHO For 2.3, we can read the text colour and apply this to the icons as well. This should be the best looking version for all OS and we can avoid here the ugliness if a background icon and the work creating it. I think most code for this is already in place. What do you think?

**Comment by ronso0** [comment]
A quick test with rounded rectangles looks like this
pref_lib_about_icons_bg

> For 2.3, we can read the text colour and apply this to the icons as well. I think most code for this is already in place.

Sounds great!

So, if someone tested it on Win and OSX this is ready to merge, isn't it?
I also altered the AutoDJ icon a bit (square head) so it doesn't look like the Android boot anymore.

**Comment by daschuer** [comment]
LGTM, On windows 10 it looks also well.

**Comment by daschuer** [comment]
By the way, did you consider the cloud icon for metadata broadcasting?

**Comment by ronso0** [comment]
Nope, that slipped through..
I put it on my ToDo.

**Comment by rryan** [comment]
Debian package builds are failing now b/c `mixxx-icon.png` is removed. It is referenced here:
https://github.com/mixxxdj/mixxx/blob/master/src/SConscript#L287

**Comment by rryan** [comment]
Oops, my mistake -- I hadn't pulled the changes yet. It's just `src/SConscript`.

**Comment by ronso0** [comment]
okay...I was just about to list the changes
can we use a vector file for the menu?

**Comment by rryan** [comment]
I've got an attempted fix in 1c02421824af5f25f32660ba4249f62bee2c8563.

**Comment by ronso0** [comment]
alright. thx!

**Comment by Be-ing** [comment]
Merging this branch created a lot of merge conflicts between master and jmigual-library-redesign. @ronso0 could you make a PR to resolve those?

**Comment by ronso0** [comment]
Yes, I'll do this when pick up #1723 again.

**Comment by daschuer** [comment]
ic_library_preview_pause.svg cause a regression in my eyes. It now resizes with the coloum, which does not match to other coloumn icons: 
bildschirmfoto vom 2018-09-15 12-07-16

**Comment by ronso0** [comment]
Interesting. I can fix it by adding more whitespace around the headphones and enlarge the play/pause icon.

It seems this PR wasn't merged to 2.2 completely: the files are not in Shade/style, and the path  in style.qss was not adopted but the the file names were. Strange..
change in this PR:
https://github.com/mixxxdj/mixxx/pull/1774/files#diff-95289ed10ae24ba4440de101a1813310L217
same region in 2.2:
https://github.com/mixxxdj/mixxx/blob/2.2/res/skins/Shade/style.qss#L216

**Comment by ronso0** [comment]
@daschuer what do you think about this:
lib-preview-button
that's the biggest the icon can get now.
now that you mentioned the ghost face I see it everytime.. ;)

**Comment by daschuer** [comment]
Compared to the original it is still bigger. I think we can make it sightly bigger than the original but this is IMHO still sightly too big. By be it is just a missing gap to the borders?

**Comment by ronso0** [comment]
I'll find a size that fits. Yes, it's the padding in the svg file that makes the difference; the size defined in qss is not respected.

btw https://bugs.launchpad.net/mixxx/+bug/1736001 is related: using vector images for i.e. BPM lock doesn't have the same effect there, it just stays at the initial size

**Pull request merged**
