### PR TITLE
Add controller Vestax VCI-100MKII

### PR DESCRIPTION
**Pull request by sohet**
Discontinued but still widely used 4-deck controller. For details, see the wiki http://www.mixxx.org/wiki/doku.php/vestax_vci-100mkii

### CODE REVIEW

**Comment by illuusio** [comment]
Jshint problems found:
Vestax-VCI-100MKII-scripts.js: line 28, col 2, Missing semicolon.
Vestax-VCI-100MKII-scripts.js: line 32, col 2, Missing semicolon.
Vestax-VCI-100MKII-scripts.js: line 90, col 49, Use '===' to compare with '0'.

**Comment by illuusio** [comment]
XML prefers '"'-char over '''. It's on the xml-topic tag.

**Comment by illuusio** [comment]
Please add
<pre>
////////////////////////////////////////////////////////////////////////
// JSHint configuration                                               //
////////////////////////////////////////////////////////////////////////
/* global engine                                                      */
/* global script                                                      */
/* global print                                                       */
/* global midi                                                        */
////////////////////////////////////////////////////////////////////////
</pre>
at the top

**Comment by illuusio** [comment]
if you can run js-beautify to sort code indentation and stuff easily. at least there 'function (' should be 'function('.

**Comment by sohet** [comment]
Thank you for checking. I believe all the syntactic problems to be removed.

**Comment by ywwg** [comment]
sohet have you signed our contributor agreement? https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ

**Comment by Be-ing** [comment]
Why can the filter knobs only control the high pass filters? Why not map them to [QuickEffectRack1_[ChannelX]_Effect1],super1?

**Comment by Be-ing** [comment]
The wiki page says the button labeled 23 is "Cup". Is this a typo? What does this mean?

**Comment by illuusio** [comment]
jshint is happy but code format is still incorrect. Too long lines (80 char per line) for example.

**Comment by sohet** [comment]
Thank you for checking again. I follow the suggestions of js-beautify
(python 1.5.10) except wrap. The result of automatic wrap seems ugly, so
I wrap the code by hand.

**Comment by sohet** [comment]
I have signed the agreement just now.

**Comment by sohet** [comment]
I have had mapped it as usual. But I feel some difficulties.

1. The filter knob of this controller has no mid click stop.
2. The curve of filter assigned to super knob is too critical
   around the mid point.
   
As a result, I sometimes loose kick and bass, despite my intention to
set it to mid. The knob mapped only hi-pass is far more easy to control.

**Comment by sohet** [comment]
Some controllers of some manufactures use "CUP" for "cue and play". Same
as "stutter" of Numark. It seems not widely know, so I will describe it
as "Cue and Play".

**Comment by sohet** [comment]
I notice that XML files automatically produced in ~/.mixxx/controller
have the first lines containing single quotes "'".

**Comment by Be-ing** [comment]
> I have had mapped it as usual. But I feel some difficulties.
> 1. The filter knob of this controller has no mid click stop.
> 2. The curve of filter assigned to super knob is too critical around the mid point.
> As a result, I sometimes loose kick and bass, despite my intention to set it to mid. The knob mapped only hi-pass is far more easy to control.

That makes sense. It's unfortunate the knob was made that way. Some users will likely still want the default filter superknob behavior or want to change it to control the low pass filter instead of the high pass filter. I'm fine with keeping the mapping as it is, but it would be helpful to mention how to change the mapping to do these on the wiki page.

**Comment by illuusio** [comment]
I have understood that XML specs favors '"' over ''' and xmllint does it so. I don't know where these automatic created files comes from but they should follow XML-spec.

**Comment by sohet** [comment]
For the moment, linking the filter description to my article in the
forum will help those who want low-high pass.

I hope Mixxx will provide option menu that enable users to change the
super knob binding.

**Comment by sohet** [comment]
It seems that Mixxx has come to take care of keylock control at scratch. So I drop it from the script.

**Comment by sohet** [comment]
If it will take a long time to merge, may I add and change functions as this?
<http://www.mixxx.org/forums/viewtopic.php?f=7&t=6038&start=30#p26166>

**Comment by Be-ing** [comment]
No need to merge this until you're ready.

**Comment by sohet** [comment]
Improve scratching following the scripts of Vestax VCI-400 and  Denon MC6000MK2. My implementation uses one loop timer for delay instead of a series of one-shot timers. This improvement also removes interference from jog, so change to inhibit it only in slip mode.

**Comment by Be-ing** [comment]
Please add a bit more detailed description of the change to your last commit message. To do this, simply run 'git commit --amend' before making another commit.

**Comment by Be-ing** [comment]
Is this ready to merge?

**Comment by illuusio** [comment]
LGTM ok me to merge.

**Comment by sohet** [comment]
[shift + pitch fader] mapping (playposition) seems not so useful, but I can't find an alternative one till now. Please merge it as is.

**Comment by ywwg** [comment]
we can probably cherry-pick this to 1.12 as well

**Comment by Be-ing** [comment]
> [shift + pitch fader] mapping (playposition) seems not so useful, but I can't find an alternative one till now. Please merge it as is.

Yeah, I just moved a functionality that was mapped to shift + volume fader on my controller. Having a shift function for a fader is really awkward and confusing to actually use.

> we can probably cherry-pick this to 1.12 as well

I didn't realize this was targeted at master. Yeah, I don't see why not to cherry pick it into 1.12.

**Comment by ywwg** [comment]
merged

**Pull request merged**
