### PR TITLE
add Pioneer DDJ-SB3 mappings

### PR DESCRIPTION
**Pull request by jevilalta**
Would like to submit the completed Pioneer DDJ-SB3 mapping.

### CODE REVIEW

**Comment by ronso0** [comment]
@jevilalta Thank for working on this!

Since this is your first contribution we need you to sign the [contributor agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and thereby allows Mixxx to include your changes.

Also, when adding a mapping please add the mapping documentation to the manual https://github.com/mixxxdj/manual

**Comment by Holzhaus** [comment]
Also, please have a look at the failibg pre-commit. You can also run this check locally on every commit: https://github.com/mixxxdj/mixxx/wiki/using%20git#set-up-automatic-code-checking

**Comment by jevilalta** [comment]
Thanks for the update.

I've signed the agreement and updated the base. I did not see anything there that would need to be updated in the for this mapping. Can you clarify why needs to be updated in the manual? There is the hardware guide in the wiki... is that what needs updating?

Am working on fixing the linting issues.

**Comment by Holzhaus** [comment]
> Can you clarify why needs to be updated in the manual? There is the hardware guide in the wiki... is that what needs updating?

You need to check out the 2.3 branch of the manual repo and add documentation. To `source/hardware/controllers`. Have a look at the documentation for the Roland DJ-505 or the Pioneer DDJ-200 for an example what controller documentation should look like. 

> Am working on fixing the linting issues.

👍

**Comment by uklotzde** [comment]
Please rebase your feature branch and force push. Switching the target branch doesn't suffice.

**Comment by jevilalta** [comment]
> 
> 
> Please rebase your feature branch and force push. Switching the target branch doesn't suffice.

Just saw you comment. Will rebase and push.

**Comment by Holzhaus** [comment]
> > 
> > 
> > Please rebase your feature branch and force push. Switching the target branch doesn't suffice.
> 
> Just saw you comment. Will rebase and push.

In case you don't know how: https://github.com/mixxxdj/mixxx/wiki/using%20git#targeting-another-base-branch

**Comment by jevilalta** [comment]
I'll create a new PR once I get his sorted out.

**Comment by Holzhaus** [comment]
> I'll create a new PR once I get his sorted out.

Please don't. Just force push to the branch and the PR will be updated automatically.

**Comment by Holzhaus** [comment]
> > I'll create a new PR once I get his sorted out.
> 
> Please don't. Just force push to the branch and the PR will be updated automatically.

Too late, you already deleted the branch 😞

**Pull request closed without merging**
