### PR TITLE
Fix broken knob interaction on touchscreens

### PR DESCRIPTION
**Pull request by Swiftb0y**
Fixes the knob issue reported on zulip: https://mixxx.zulipchat.com/#narrow/stream/109122-general/topic/Windows.2010.20Touchscreens

### CODE REVIEW

**Comment by Holzhaus** [comment]
@mixxxdj/developers Who has a touchscreen to test this?

**Comment by Swiftb0y** [comment]
To explain my changes a bit: 
previously, the code always reset the cursor position to the center of the knob after measuring the distance travelled since the previous cursor move. This doesn't work well on touchscreens because resetting the cursor conflicts with the users touchinput. this conflict ended up in mixxx always measuring a distance change on every move which occurs much more frequently on touchscreens and obviously also when the user didn't move the cursor much.
This PR changes this behavior to always measure from the previous move-position and only resetting the cursor when the knob is released.  This might be a problem on knobs located near screen corners, but from my testing on a 1080p screen (the current implementation translates the distance in pixels directly to value change for the control without scaling based off the screen size) this is not a problem in Deere or Tango.

**Comment by daschuer** [comment]
Well done! I have tested it and it is a big improvement.

**Review by daschuer — APPROVED** [review]
LGTM.

**Comment by Be-ing** [comment]
I finally gave this a try. Thank you, this works quite well.

**Pull request merged**
