### PR TITLE
 AppVeyor: Add Ubuntu 20.04 build

### PR DESCRIPTION
**Pull request by uklotzde**
- Install cmake package directly
- Add FFmpeg
- Remove FAAD2/libmp4v2 (unsupported)

### CODE REVIEW

**Comment by Holzhaus** [comment]
Is 20.04 the minimum supported version for 2.4?

**Comment by uklotzde** [comment]
Not sure about 2.4. But for 2.3 we should support both LTS versions. This is targeted at 2.3.

**Comment by uklotzde** [comment]
We should only drop support for Ubuntu 18.04 if it introducing us doing mandatory changes, e.g. removing unsupported, legacy Qt classes that cause issues with current OSes.

**Comment by uklotzde** [comment]
We could remove the Ubuntu1804 target from AppVeyor to save build time? CMake on Ubuntu 18.04 is already tested on Travis. The restriction to a single concurrent build already causes long delays for the PR builds.

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you. I'm a bit worried that the additional build will a lot of additional delays (because we only have a single concurrent build on Appveyor). But let's merge for now.

**Pull request merged**
