### PR TITLE
Obsolete Ubuntu Bionic 18.04

### PR DESCRIPTION
**Pull request by uklotzde**
- Update comments
- Update clang format settings
- Remove obsolete workaround
- Remove obsolete references in CI build
- Upgrade actions-setup-cmake in CI build

TODO:
- Update PPA build

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
LGTM, Thank you. 
What needs to be done at the PPA?

**Comment by uklotzde** [comment]
> LGTM, Thank you.
> What needs to be done at the PPA?

I deliberately excluded all PPA tasks, because I am not aware of all the subtleties and potential pitfalls.

**Comment by daschuer** [comment]
That's no Problem. I will take care. 
I just like to know what is to do for the PPA build.
I don't see a anything.

**Comment by Holzhaus** [comment]
Maybe delete the Ubuntu 18.04 package, so that users get a warning that the package is not updated any longer.

**Comment by uklotzde** [comment]
@daschuer Regarding the PPA: I was unsure if you want to delete all the conditionals that was required for supporting different releases with differing dependencies.

Do we distribute main builds through the PPA?? Then we definitely need to delete those 18.04 packages.

**Comment by daschuer** [comment]
Done, see: https://launchpad.net/~mixxx/+archive/ubuntu/nightlies

**Comment by daschuer** [comment]
Thank you for taking care.

**Pull request merged**
