### PR TITLE
add maping for Intech TEK2

### PR DESCRIPTION
**Pull request by Greg-Orca**
TEK2 config files

[https://mixxx.zulipchat.com/#narrow/stream/113295-controller-mapping/topic/Intech.20TEK2](https://mixxx.zulipchat.com/#narrow/stream/113295-controller-mapping/topic/Intech.20TEK2)

### CODE REVIEW

**Comment by Swiftb0y** [comment]
Welcome and thanks for upstreaming this mapping. Please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

**Comment by ronso0** [comment]
Thank you for this PR!

Controller mappings usually go to the stable branch (currently 2.4), unless they require new features.
I've changed the base branch to 2.4, please rebase onto that and force-push. Thank you.

**Comment by Greg-Orca** [comment]
Hi, I signed the contract. Thank you!

**Comment by Swiftb0y** [comment]
Great. Thank you.
Please understand that in order for us to be able to merge this, your contribution need to follow [our style guide](https://github.com/mixxxdj/mixxx/wiki/Coding%20Guidelines#mixxx-style-guide). Most of the required changes can be made automatically by use of `pre-commit`. Please [set up pre-commit](https://pre-commit.com/#installation) and make sure to manually apply the required changes using `pre-commit run --from-ref main --to-ref HEAD`. Thank you very much.

You will also need to rebase this branch so it gets merged into the next release. To do that, issue the following commands:
```bash
git switch -c intech-tek2 # put your work on a new branch
git switch main # go back to main branch
git reset --hard 6b62210eed71869fb2dd39c12261328912caf528 # ensure main branch is clean
git switch intech-tek2 # go back to your work
git rebase --onto=2.4 main # this is the step that actually does the rebase on 2.4
git push # publish
```
Then you'll probably need to create a new PR because the PR should now be originating from your intech-tek2 branch.

**Pull request closed without merging**
