### PR TITLE
Library: Traktor library detects latest collection folder

### PR DESCRIPTION
**Pull request by denvercoder21**
Fixes "Traktor library feature doesn't use latest library"
(https://bugs.launchpad.net/mixxx/+bug/1908475)

My first PR, let me know if I'm violating protocol or need to do something differently.

### CODE REVIEW

**Comment by Be-ing** [comment]
Thanks! Since this is a simple bug fix, please rebase it on the beta 2.3 branch (we won't be doing any more 2.2 releases because the build servers we used for 2.2 are no longer operational).

**Comment by Be-ing** [comment]
Please sign the contributor license agreement: https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ

**Comment by Be-ing** [comment]
pre-commit wants to make some code style changes. Please set it up locally: https://github.com/mixxxdj/mixxx/wiki/using-git#set-up-automatic-code-checking

For now, you can also download a patch from as an artifact from GitHub Actions and apply that.

**Comment by Be-ing** [comment]
Please leave a comment when you've signed the CLA so we know that you've done so.

**Comment by denvercoder21** [comment]
Signed CLA.
Rebasing 2.3 onto main gets mit into conflict resolution hell. Would it be okay to create another PR, started cleanly from 2.3?

**Comment by Be-ing** [comment]
Try `git rebase --onto upstream/2.3 upstream/main`

**Comment by Be-ing** [comment]
You can also do `git rebase -i upstream/2.3` and delete all the commits that aren't yours.

**Comment by denvercoder21** [comment]
> Try `git rebase --onto upstream/2.3 upstream/main`

That executes without problems, put `push`ing reports that everything is up to date.

**Comment by denvercoder21** [comment]
> You can also do `git rebase -i upstream/2.3` and delete all the commits that aren't yours.

This one shows me hundreds of commits.

**Comment by denvercoder21** [comment]
Wouldn't I kind of "screw up" my main with rebasing 2.3 onto it?

**Comment by Be-ing** [comment]
You shouldn't have a local `main` branch anyway. Only core developers with push access need that. Every feature/bug fix should be on its own branch. If you want to test the upstream main or 2.3 branches, check them out directly from the remote and you won't need to bother keeping a local branch up to date.

**Comment by Be-ing** [comment]
If you want to open a new PR with a new branch, that's fine too.

**Comment by denvercoder21** [comment]
> You shouldn't have a local `main` branch anyway. Only core developers with push access need that. Every feature/bug fix should be on its own branch. If you want to test the upstream main or 2.3 branches, check them out directly from the remote and you won't need to bother keeping a local branch up to date.

That makes sense, thanks for clarifying. I'll open a new PR and know better in the future. :)

**Pull request closed without merging**
