### PR TITLE
fix PPA upload from GH Actions

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by Be-ing** [comment]
oh I think the key needs to be imported to GPG from the environment variable

**Comment by rryan** [comment]
BTW I added "RJ Skerry-Ryan <rryan@mixxx.org>" as a UID to the key before adding it as a secret, so you shouldn't need to change the name.

**Comment by Be-ing** [comment]
`echo $RRYAN_AT_MIXXX_DOT_ORG_GPG_PRIVATE_KEY | gpg --import -`
Would that be safe? Asking before I try to check that I won't expose the key.

**Comment by Be-ing** [comment]
I tested locally. That should be fine.

**Comment by Be-ing** [comment]
```
Run echo $RRYAN_AT_MIXXX_DOT_ORG_GPG_PRIVATE_KEY | gpg --import -
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
Error: Process completed with exit code 2.
```
:/

**Comment by Be-ing** [comment]
@rryan can you verify through the GitHub web configuration that the environment variable is properly formatted including newlines?

**Comment by rryan** [comment]
It won't be available in PRs, right?

**Comment by Be-ing** [comment]
Secret variables are available for branches of the upstream repo. PRs from forks don't have access to them.

**Comment by rryan** [comment]
I can't see the secret anymore after creating it -- but it was a copy/paste of the ASCII-armored output of `gpg --export-secret-key --armor rryan@mixxx.org`. I don't believe I added a trailing newline after `-----END PGP PRIVATE KEY BLOCK-----`.

**Comment by Be-ing** [comment]
`echo -e $RRYAN_AT_MIXXX_DOT_ORG_GPG_PRIVATE_KEY > key.asc && gpg --import key.asc ; rm key.asc` might work although I'd rather not write the key to a file on the server even if it's temporary.

**Comment by rryan** [comment]
> `echo $RRYAN_AT_MIXXX_DOT_ORG_GPG_PRIVATE_KEY | gpg --import -`
> Would that be safe? Asking before I try to check that I won't expose the key.

Does `gpg --import --batch -` work?

**Comment by rryan** [comment]
> `echo -e $RRYAN_AT_MIXXX_DOT_ORG_GPG_PRIVATE_KEY > key.asc && gpg --import key.asc ; rm key.asc` might work although I'd rather not write the key to a file on the server even if it's temporary.

I think this would accomplish the same thing with a file descriptor that has no file associated with it?

`gpg --import <(echo $RRYAN_AT_MIXXX_DOT_ORG_GPG_PRIVATE_KEY)`

**Comment by rryan** [comment]
Hm.
```
$ gpg --armor --export-secret-key rryan@mixxx.org | gpg --homedir ./test --import
gpg: WARNING: unsafe permissions on homedir '/home/mixxx/test'
gpg: /home/mixxx/test/trustdb.gpg: trustdb created
gpg: key 6F709194D92C4947: public key "RJ Skerry-Ryan <rryan@mixxx.org>" imported
gpg: key 6F709194D92C4947: secret key imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret keys read: 1
gpg:   secret keys imported: 1
```

**Comment by Be-ing** [comment]
I suspect the issue is the contents of the environment variable rather than the shell command. Here is what someone figured out for CircleCI: https://discuss.circleci.com/t/gpg-keys-as-environment-variables/28641

**Comment by Be-ing** [comment]
> I don't believe I added a trailing newline after -----END PGP PRIVATE KEY BLOCK-----.

Can you test this? Also test adding a test variable with a new line that would be safe to echo like:
```
foo
bar
```

**Comment by Be-ing** [comment]
Using `"${{ secrets.RRYAN_AT_MIXXX_DOT_ORG_GPG_PRIVATE_KEY }}"` in the `run` script rather than a bash environment variable works. But the environment variable is still needed for the `if` condition.

**Comment by Be-ing** [comment]
I have disabled the Jenkins PPA upload jobs.

**Pull request merged**
