### PR TITLE
Release 2.2.3

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by uklotzde** [comment]
What about #2358?

**Comment by uklotzde** [comment]
@daschuer What is the state of https://bugs.launchpad.net/mixxx/+bug/1843922 (marked in progress)

**Comment by Be-ing** [comment]
> What about #2358?

That's a very minor issue and I'm not clear from reading the PR what the state of it is. I don't think it should hold up this overdue release any longer. We can always do more minor releases.

**Comment by daschuer** [comment]
> What about #2358?

This is a mature to merge. It fixes only a trivial spelling issue. Can one have a look?

**Comment by daschuer** [comment]
> @daschuer What is the state of https://bugs.launchpad.net/mixxx/+bug/1843922 (marked in progress)

I am unsure how the state is. Need to test. At least nothing that should block merging.

**Comment by Holzhaus** [comment]
By the way, we should also publish a blogpost upon release (https://mixxxblog.blogspot.com/). The last one is for release 2.1.3.

**Comment by uklotzde** [comment]
A changelog entry for #2358 needs to be added.

**Comment by Be-ing** [comment]
> A changelog entry for #2358 needs to be added.

Done

**Comment by uklotzde** [comment]
https://github.com/Be-ing/mixxx/pull/39

**Comment by uklotzde** [comment]
LGTM. Anyone else?

**Comment by daschuer** [comment]
LGTM, Thank you.

**Comment by Be-ing** [comment]
As a reminder, do _not_ make the Git tag until we have confirmed the packages work on all 3 OSs.

**Pull request merged**
