### PR TITLE
Deere: Add Charcoal colorscheme

### PR DESCRIPTION
**Pull request by Holzhaus**
The Deere skin was a bit too bright for me, so I made a darker version. I don't know if you want this to be included in Mixxx, but I thought I'd share it in case someone else interested in this.

Classic version

Charcoal version

### CODE REVIEW

**Comment by daschuer** [comment]
Cool Thank you. IMOH we could merge this to master. But I think @Be-ing is the taste master for Deere. 

I wonder if we can do some more tweaks, to differentiated the skins even more. Can you explain your use case and some more points that makes you doing this work?

Deere can also make use of a high contrast daylight skin usable for outdoor events with a bright surrounding. It can be used during garden parties or on trailer bars. 
A design more like GitHub or https://www.deere.de :-P 
What do you think?

**Comment by Holzhaus** [comment]
> I wonder if we can do some more tweaks, to differentiated the skins even more. Can you explain your use case and some more points that makes you doing this work?

In dark enviroments, I found this skin a bit too bright and I thought this version might be easier on the eyes.

> Deere can also make use of a high contrast daylight skin usable for outdoor events with a bright surrounding. It can be used during garden parties or on trailer bars.
> A design more like GitHub or https://www.deere.de :-P
> What do you think?

Possbly. But I think some more changes to Deere would be needed, because a bunch of colors are contained in the XML files that would need to be inverted to make the skin work with a light color scheme. I don't know what the for this is - ideally, all colors definitions should go into the `style.qss` file.

**Comment by esbrandt** [comment]
* The color scheme should also be available for ``Deere (64 Samplers)``. This is basically a clone from the regular Deere skin, but separated for performance reasons.
* Is in ``Preferences > Waveform`` one  of the  ``Filtered `` options enabled, the waveforms become unreadable ( black on black)
* The skin settings widget, visible when clicking the gear icon, still uses the default color scheme. You you may want to unify it.

**Comment by Be-ing** [comment]
> Cool Thank you. IMOH we could merge this to master. But I think @Be-ing is the taste master for Deere.

As long as the current color scheme remains the default I'm okay with adding this. I personally don't plan on using it, but if @Holzhaus is willing to maintain it, I don't object.

Many graphics are not being scaled smoothly on my 3840 x 2160 screen (scale factor 3.0). Look closely at the knobs and button icons:
image

I don't know how any of the QSS changes you made could do this. I am guessing it is a bug in Mixxx. @daschuer do you have any ideas?

**Comment by ronso0** [comment]
Thanks, this is much more pleasant in dark scenes!

Aftre taking a quick look (didn't test waveform/overview settings), I find it can be further improved:
- #EQKillButton could be brighter
- #QuickEffectKillButton is smaller than in the Classic theme
- inactive VU meters could be darker
- Mic/Aux modules are smaller, probably need to adjust bg colors in #MicAuxRack and child containers
- brighter font for selected libary rows

For some reason, many icons look choppy/pixelated with the Charcoal theme. Seems like something's going wrong with the SVG transformation

**Comment by ronso0** [comment]
Now, the toolbar has the same bg color as most major containers, that's why the contrast tweak for the toolbar knob indicators doesn't match the bg anymore

**Comment by ronso0** [comment]
some container margins are screwed up:
deere-margins-classic
vs
deere-margins-charcoal

due to [bug#1578111](https://bugs.launchpad.net/mixxx/+bug/1578111), some margins are a mixture of `margin` and `border`s matching the main background

**Comment by ronso0** [comment]
> For some reason, many icons look choppy/pixelated with the Charcoal theme. Seems like something's going wrong with the SVG transformation

Looks like the anti-aliasing is not applied (correctly) after SVG color shift

**Comment by daschuer** [comment]
This means we have a bug in the color scheme code blocking this PR. Bad.

**Comment by ronso0** [comment]
> > For some reason, many icons look choppy/pixelated with the Charcoal theme. Seems like something's going wrong with the SVG transformation
> 
> Looks like the anti-aliasing is not applied (correctly) after SVG color shift

I tried with `<Amount>0</Amount>` (no actual transformation) but the icons are screwed up anyway.
Also with `<HSVTweak/>` (no transform valuevalue).

also I notice different glitches with the waveform reset zoom icon:

`<Add><Amount>35</Amount></Add>`
svg_AddAmount_35

`<HueInv/>`
svg_HueInv

hope that helps..

**Comment by ronso0** [comment]
To further track down the issue I applied the same filters to Tango, et voila:
all  icons look fine, except those that where file size and effective size in the skin differ.
svg_tango_amount50

So I assume the bug's about **scaling and transforming**, not about transforming SVGs.

**Comment by uklotzde** [comment]
What's the state of this PR? Mergeable or still work in progress?

**Comment by Holzhaus** [comment]
Sorry, still WIP because I didn't implement the changes requested im https://github.com/mixxxdj/mixxx/pull/2130#issuecomment-502613835 and https://github.com/mixxxdj/mixxx/pull/2130#issuecomment-502613835 yet

**Comment by ronso0** [comment]
The issue with SVG filters is much more important 

> we have a bug in the color scheme code blocking this PR. Bad.

@Holzhaus Considering that resizing the icons to hide the SVG bug would take quite some time I suggest to rather invest a few minutes time investigating the actual `Filter` bug; maybe someone with Qt experience discovers something obvious. 
Filters are parsed here https://github.com/mixxxdj/mixxx/blob/master/src/skin/colorschemeparser.cpp#L68

If that is a dead end (or more complex to be fixed before this should be merged) I'd help with resizing the Deere icons.

**Comment by ronso0** [comment]
Maybe the bug is already about to be fixed in #1777 as it removes a lot of code around the imgloader.
Though that branch has a lot of conflicts, for example from #1988
I'll built that branch now to test it. (I

**Comment by ronso0** [comment]
> Maybe the bug is already about to be fixed in #1777 as it removes a lot of code around the imgloader.
I'll built that branch now to test it.

Nope, also present there.
I guess it saves time to know the bug is not in imgloader

**Comment by ronso0** [comment]
Did the `Filters` ever work for SVGs? I tried some branches (#1777 and lib-redesign) that touched the image processing but the bug is presetn in all of them.
Could it be we need a separate color processor for SVGs that manipulates the colors in SVG xml, then returns a pixmap instead of rendering the SVG and altering the derived pixmaps?

**Comment by daschuer** [comment]
I guess it works not, because the filters works on the rendered bitmaps. But we are trying to pass the svgs through when I remember correctly.

**Comment by Holzhaus** [comment]
I'm using LateNight now, so I probably wont fix the remaining issues. If someone is interested in picking this up, feel free to do so. Closing this.

**Pull request closed without merging**
