### PR TITLE
Controller: ION Discover DJ Pro

### PR DESCRIPTION
**Pull request by meltedpianoman**
An initial attempt to have support for the ION Discover DJ Pro. This file
was taken from https://mixxx.org/forums/viewtopic.php?f=7&t=3343 and modified
to make it work with a recent version of Mixxx.

Signed-off-by: meltedpianoman <meltedpianoman@gmail.com>

------------------------

See also topic: https://mixxx.org/forums/viewtopic.php?f=7&t=3343
It would be nice to see this supported by Mixx by default, so that it can be improved by the community and it will be maintained in case XML format / JS script changes are introduced.

I took the great work of joachim and made some small changes:
- Updated the XML to the new format
- Inverted both speed sliders
- Corrected the filename of the script file in the midi.xml file (as I use a Linux I have a case sensitive file system and Mixxx was unable to open the script)
- Renamed the files a bit

I'm not a DJ and I only performed some quick tests. Basic operation seems to work for me. I tested it on:
- Kubuntu 19.10 with Mixxx version 2.2.1
- Lubuntu 20.04 with Mixxx version 2.2.3

Regards,
Ivo Sieben

### CODE REVIEW

**Comment by Holzhaus** [comment]
Hi Ivo, thanks for contributing! Unfortunately this doesn't meet our code style requirements yet. Please use our pre-commit hooks or fix the code style issues detected by CodeFactor manually.

**Comment by Holzhaus** [comment]
Also, this is pointed at the master branch which means it will be not be released until Mixxx 2.4.0. If you want it to become a part of Mixxx 2.2.5 already, please rebase on the 2.2 branch: https://mixxx.org/wiki/doku.php/using_git#targeting_another_base_branch

Last but not least: Before we can merge your code into Mixxx, please sign the [contributor agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ). In a nutshell, this gives us permission to distribute your code under the GPL as well as in the Mac App Store which has some terms incompatible with the GPL.

**Comment by meltedpianoman** [comment]
I close this one, as I don't find a way to update this pull request after I rebased the commit to the 2.2 branch. Next pull request is #2893

**Comment by Holzhaus** [comment]
You can just force-push to the branch (`git push -f origin <branch>`) and then edit the target branch of this PR (using the edit button next to the PR title).

**Comment by meltedpianoman** [comment]
Ah... I see. I used the "edit" button, but I thought it was only about changing the title. :-(
I totally missed that the target branch could be updated via the Edit button as well. Sorry for that.

Anyway, I just signed the Contributor Agreements. I hope that the other Pull Request can do just fine?

**Pull request closed without merging**
