### PR TITLE
Revert 1 master

### PR DESCRIPTION
**Pull request by DJChloe**

### CODE REVIEW

**Comment by uklotzde** [comment]
@DJChloe What's the purpose of this PR?

The master/1.12 branch of your personal repository should follow mixxxdj/mixxx. Development is done in separate branches that originate from 1.12/master, depending on the target version. This is the root branch of your development branch. From time to time you can update (= pull) the root branch and merge it into your development branch. An alternative strategy (this is what I actually prefer/recommend) is rebasing your development branch on the updated root branch.

**Comment by DJChloe** [comment]
I'm a noob...
I wanted my fork to be up to date with mixxxdj/mixxx 
I stupidly followed this  :
http://stackoverflow.com/questions/20984802/how-can-i-keep-my-fork-in-sync-without-adding-a-separate-remote/21131381#21131381

I got my fork up to date, but with a commit ahaed from mixxxdj/mixxx, stupid.
Messing around I have done this revert and finally, the best way I found to do it more or less clean was to delete my fork and re-fork mixxxdj/mixxx

Are there any simple way to maintain a fork up to date with the upstream ?
On my local git, I've cloned only the 1.12 branch, not the master, and therefore cannot pull from mixxxdj/mixxx and then push back to my github. I did not find any solution on the web.

**Comment by DJChloe** [comment]
It was a real pain to find that :
git checkout -t -b master origin/master

**Comment by uklotzde** [comment]
http://mixxx.org/wiki/doku.php/using_git
"Note: If you plan fixing a bug or contributing a feature, you should fork the mixxx repository on GitHub first. Replace “mixxxdj” with your user name in following paragraphs."

1. Fork mixxxdj/mixxx on GitHub
2. Clone your forked GitHub repository locally -> will be referred to as "origin"
3. Add mixxxdj/mixxx on GitHub as a remote repository named "blessed" (you can choose another name if you want)
4. Create tracking branches for blessed/1.12 and blessed/master in your local repository
5. Now you can simply "git pull" the changes from blessed/1.12 and blessed/master into the corresponding branches of your local repository to keep them updated

**Comment by daschuer** [comment]
This is a very complete article: 
https://neval8.wordpress.com/2013/07/07/en-typical-workflow-with-github-on-shared-project/

**Comment by DJChloe** [comment]
>Fork mixxxdj/mixxx on GitHub

OK, done
https://github.com/DJChloe/mixxx

>Clone your forked GitHub repository locally -> will be referred to as "origin"

This step seems ok too

> Add mixxxdj/mixxx on GitHub as a remote repository named "blessed" (you can choose another name if you want)

I called it upstream

> Create tracking branches for blessed/1.12 and blessed/master in your local repository

OK, I have master and 1.12

> Now you can simply "git pull" the changes from blessed/1.12 and blessed/master into the corresponding branches of your local repository to keep them updated

> stuck : can pull from upstream/master but not from upstream/1.12 

chloe@chloe-GA-MA78GM-S2H:~/mygit$ git pull upstream/1.12 1.12
fatal: 'upstream/1.12' does not appear to be a git repository
fatal: Could not read from remote repository.

I think I shoud delete my local 1.12 and recreate it

**Comment by DJChloe** [comment]
OK, finally I did it, pfff

**Comment by daschuer** [comment]
> An alternative strategy (this is what I actually prefer/recommend) is rebasing your development branch on the updated root branch.

@uklotzde: 
We have to consider carefully when a rebase suits best. The rebasing in you latest PR where not very helpfull for me as reviewer, because you couldn't keep track which changes are made when and which comments belong where. It also forces me to revert my testing branch, instead of just merging the recent
commits.  
As long as the PR still merges cleanly with the target branch, there is no need for a rebase.  
Once we have conflicts, a rebase can be handy to fix the conflicting commits one by one instead of having one big merge commit.

**Comment by uklotzde** [comment]
@daschuer Indeed, the tool support for the "rebase" strategy is lacking. But with appropriate tool support it would be the perfect solution.

Maybe we can agree on this recommendation:
1) Rebase your development branch on the root/target branch often during development
2) Merge the root/target branch into your development branch after review has started

**Comment by daschuer** [comment]
Yes, that will work.

**Pull request closed without merging**
