### PR TITLE
rewrite Components JS library with ES6 classes

### PR DESCRIPTION
**Pull request by Be-ing**
Split off from #2682

TODO port these controller mappings that use Components to ES6:
  - [x] Allen & Heath Xone K2: @Be-ing 
  - [x] Hercules P32: @Be-ing 
  - [ ] Numark Mixtrack Platinum: @iamcodemaker @JosepMaJAZ
  - [x] Roland DJ 505: @Holzhaus Be-ing/mixxx#45
  - [ ] Stanton DJC.4: @nuess0r 
  - [ ] Numark N4: @Swiftb0y 
  - [ ] Behringer CMD MM1: @Swiftb0y 
  - [ ] Denon MC6000 Mk2: @uklotzde

### CODE REVIEW

**Review by daschuer — CHANGES_REQUESTED** [review]
This requires Qt 5.12, right? For Mixxx 2.4, beta scheduled in 6 month (after our Build System works :-/) our minimum Version is Qt 5.9 Version.   

This means, we cannot remove the old mappings to not brake the controller for users that have not yet done a distro upgrade.

**Comment by Holzhaus** [comment]
> For Mixxx 2.4, beta scheduled in 6 month (after our Build System works :-/) our minimum Version is Qt 5.9 Version.

Wait a sec, I thought 5.9 is the minimum Qt version for 2.3? Let's discuss this on Zulip: https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Minimum.20supported.20dependency.20versions

**Comment by Swiftb0y** [comment]
>  Numark N4: @Swiftb0y
Behringer CMD MM1: @Swiftb0y

I can try to port the N4 mapping to ES6 classes, but I don't have access to the controller anymore so my attempt will be just as blind as yours.
I still have access to the MM1 though, I just need to find the time.

**Comment by uklotzde** [comment]
@Be-ing I propose to convert this PR into a draft until the prerequisites are in place.

**Comment by Be-ing** [comment]
I am now doubting if we should continue in this direction. I think we may be able to remove the need for MIDI XML files for 2.4 without rewriting the entire controller system. I will experiment again with some ideas for this.

**Comment by Be-ing** [comment]
It turns out that we can load JS modules without rewriting the whole controller system, so I don't think we should continue with this approach. The work started here will still be useful for rewriting Components without needing MIDI input to go through XML.

**Pull request closed without merging**
