### PR TITLE
Changed beatloop_activate button behaviour to match lp1876003

### PR DESCRIPTION
**Pull request by fellock**
Changed beatloop_activate behaviour to:

- if a loop is active, deactivate it
- if no loop is active, activate a beatloop at the current playback position

As discussed in https://bugs.launchpad.net/mixxx/+bug/1876003

### CODE REVIEW

**Comment by ronso0** [comment]
The original bug is about the looping GUI if I'm not mistaking, so I propose to
* add `beatloop_toggle`
* leave `beatloop_activate` untouched since it is expected to...well _activate_ a beatloop
* change the behaviour of `reloop_toggle`, too
* in skins use `beatloop_toggle` instead of `beatloop_activate`

**Comment by Be-ing** [comment]
Fix the tests and I think this is good.

**Comment by Be-ing** [comment]
> leave beatloop_activate untouched since it is expected to...well activate a beatloop

I very much disagree with this. We have received many complaints over years that this behavior is problematic. I invented the design and I acknowledge it is a bad design; I still trip up on it myself sometimes. However, we could change the name to `beatloop_toggle` and alias the old `beatloop_activate` to `beatloop_toggle` and deprecate `beatloop_activate`.

> change the behaviour of reloop_toggle, too

That is unrelated.

**Comment by ronso0** [comment]
The reason I propose to not alter `beatloop_activate` is that is used in mappings, official or not.
If we got "many" complaints there may as well be many more user who like (or just deal with) the current behaviour.
Thus I propose to add a fresh new control.

> > change the behaviour of reloop_toggle, too
> 
> That is unrelated.

true, I referred to the GUI again: currently the reloop button is `reloop_toggle` + `loop_enabled` for feedback.
Because `beatloop_activate/toggle` is only a trigger, it doesn't tell the current loop status.
We need to attach `loop_enabled` to the beatloop_activate/toggle button then.

**Comment by Be-ing** [comment]
Ah, I forgot about the skin issue. So the `reloop_toggle` behavior is fine, but yes I agree the skins should be modified so that `loop_enabled` lights up the `beatloop_toggle` button instead of the `reloop_toggle` button.

**Comment by ronso0** [comment]
So do we agree to introduce a new control beatloop_toggle` for the new behaviour or not?

**Comment by Be-ing** [comment]
I agree with introducing `beatloop_toggle`. I do not agree with leaving `beatloop_activate` with the current behavior; I think `beatloop_activate` should become a deprecated alias for `beatloop_toggle`.

**Comment by fellock** [comment]
I fixed the skins, so that the Beatloop button lights up instead of the Reloop button.
Currently this pr only modifies `beatloop_active` behaviour and doesn't introduce any new controls.

When you guys settle on whether this should be a new control or just behaviour-name change then I will proceed per the outcome, and then this pr can be reviewed.

**Comment by Be-ing** [comment]
Please sign the [Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and leave a comment here when you have signed it. It gives us permission to publish Mixxx to the Mac App Store, which is not something we do currently but we want to keep that possibility open (I am afraid that will be a requirement to distribute any software for macOS in the future, but that's a bit of a tangent).

**Comment by fellock** [comment]
Signed!

**Comment by Be-ing** [comment]
> The reason I propose to not alter beatloop_activate is that is used in mappings, official or not.

Mappings would not break, but some would work differently, matching the new behavior of the button in the skin. Realistically many if not most mappings already hack around the clunky old design by testing `loop_enabled` and using `reloop_toggle` instead of `beatloop_activate` for the same physical button as `beatloop_activate`, for example #4307.

**Comment by fellock** [comment]
> When you guys settle on whether this should be a new control or just behaviour-name change then I will proceed per the outcome, and then this pr can be reviewed.

If we assume this new behaviour to be the new default one, then it is ready indeed - I'll mark it as such.
If we want to introduce a new control for this, then there's still work to do.

**Comment by Be-ing** [comment]
Thanks for cleaning up my bad design from years ago :)

**Pull request merged**
