### PR TITLE
clarify Windows build instructions

### PR DESCRIPTION
**Pull request by kant**
* fixed semantic issue on line 64

### CODE REVIEW

**Comment by ronso0** [comment]
this change can go to 2.3
please rebase on 2.3

**Comment by Be-ing** [comment]
Welcome and thanks for improving this! Please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

**Comment by ronso0** [comment]
yeah sorry, first of all: thanks for improving Mixxx :+1:

**Comment by Holzhaus** [comment]
@kant ping. You can simply rebase onto 2.3, like this:

    $ git rebase --onto upstream/2.3 upstream/main patch-1

See this for details: https://github.com/mixxxdj/mixxx/wiki/Using-Git#targeting-another-base-branch

**Comment by JoergAtGithub** [comment]
The sentence where the wording improvement was proposed for, is no longer contained in the actual README.md. Therefore I close this PR.

**Pull request closed without merging**
