### PR TITLE
Fix invalid forward declarations of Qt types

### PR DESCRIPTION
**Pull request by uklotzde**
Updated the [Coding Guidelines](https://github.com/mixxxdj/mixxx/wiki/Coding-Guidelines#includes)

### CODE REVIEW

**Comment by daschuer** [comment]
Ok, we can use QT_FORWARD_DECLARE_CLASS, because it is more universal. But I did not consider the direct version as invalid. Does this solve a real issue?

**Comment by uklotzde** [comment]
No real issue. But such a forward declaration relies on implementation details of the external library. It is a stronger dependency than a regular #include directive. It could break at any time, i.e. when the external type name becomes an alias.

**Comment by Holzhaus** [comment]
> Updated the [Coding Guidelines](https://github.com/mixxxdj/mixxx/wiki/Coding-Guidelines#includes)

I think clang-format puts the matching header for the current cpp file first. We should either turn that off or make an exception for that.

**Comment by uklotzde** [comment]
> > Updated the [Coding Guidelines](https://github.com/mixxxdj/mixxx/wiki/Coding-Guidelines#includes)
> 
> I think clang-format puts the matching header for the current cpp file first. We should either turn that off or document this as well. What do you prefer?

Make an exception, because this is common practice.

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you!

**Comment by Be-ing** [comment]
What is the purpose of this `QT_FORWARD_DECLARE_CLASS` macro? It is undocumented and seems to be useless. It is declared in qglobal.h as
```
# define QT_FORWARD_DECLARE_CLASS(name) class name;
```

The only info I can find about it online is
https://bugreports.qt.io/browse/QTBUG-37137
The [Qt wiki page](https://wiki.qt.io/Qt_In_Namespace) which is mentioned there does not mention `QT_FORWARD_DECLARE_CLASS`. What it says about forward declaration in case Qt is in a namespace is to use:
```
QT_BEGIN_NAMESPACE
class QCheckBox;
class QComboBox;
QT_END_NAMESPACE
```
But we are not using Qt in a namespace so I don't think this is relevant?

**Comment by uklotzde** [comment]
I also didn't find any official documentation about the macro.

The only other option is to avoid forward declarations of any external code by default. The macro at least documents where Qt classes are affected.

PS: An indirection that apparently does nothing could still be useful, see [std::convert::identity](https://doc.rust-lang.org/std/convert/fn.identity.html)

**Comment by uklotzde** [comment]
http://www.gotw.ca/gotw/034.htm

Standard C++ provides dedicated header files with forward declarations for a reason.

**Pull request merged**
