### PR TITLE
Updated customized Vestax Typhoon Mapping for 2.0+, new normal mapping for 2.0+

### PR DESCRIPTION
**Pull request by bestdani**
Updated the customized Vestax Typhoon mapping and added a mapping for 2.0 that reacts as labeled on the hardware.

Wiki description will follow hopefully soon.

<a href="http://mixxx.org/forums/viewtopic.php?f=7&t=3822">Forum Post</a>

### CODE REVIEW

**Comment by sblaisot** [comment]
please add new file to windows uninstaller: http://www.mixxx.org/wiki/doku.php/contributing_mappings#windows_installer_update

**Comment by Be-ing** [comment]
@bestdani : Could you update http://mixxx.org/wiki/doku.php/vestax_typhoon ?

**Comment by rryan** [comment]
It would be great to have this update in Mixxx 2.1 -- @bestdani, @Be-ing what else needs to be done on this PR?

**Comment by Be-ing** [comment]
It would be good to move the description of the mapping from the forum to the wiki.

**Comment by rryan** [comment]
@bestdani -- is there any reason this shouldn't replace the existing Typhoon mapping, rather than live alongside it?

**Pull request merged**
