### PR TITLE
[TEST] Skins :: hidden waveform cpu fix lp1758660

### PR DESCRIPTION
**Pull request by ronso0**
As noone tried to fix [lp1758660 "GUI lag with hidden waveforms in Tango & Deere, using integrated Intel graphics "](https://bugs.launchpad.net/mixxx/+bug/1758660) in c++ so far, I tried a hack in the skins themselves.

**Deere/LateNight**
waveforms container can't be collapsed anymore, but minimized to 1px. waveforms aren't visible/scratchable then due to a 1px spacer.

**Tango**
If hidden by topbar toggle, the waveforms are now a flashing pixel positioned in the top-left corner of the skin. 

At first I posted skin ZIPs in the bug conversation on launchpad, and @sohet confirmed the fixes is working for him in Tango.
I applied similiar fixes to Deere and LateNight.
If you have an Intel graphics card, please test this.

If this works it would be nice if it would make it into 2.1.1

### CODE REVIEW

**Comment by ronso0** [comment]
@MK-42 Can you give it a try?

**Comment by MK-42** [comment]
I'm currently short on time, I hope to find some for testing at the beginning of next week. Thanks alot for your effort!

**Comment by ronso0** [comment]
@MK-42 would it help if I prep a skins-only ZIP?

**Comment by ronso0** [comment]
On launchpad @sohet just reported that the fix in Deere is working, too (same fix as in LateNight).
It would be nice if there's a confirmation from a different system though, just to be sure.

**Comment by ronso0** [comment]
aargh, log spamming from #1512 is back. CPU usage is the same with/without waveforms...
```
Warning [Main]: QPainter::begin: Paint device returned engine == 0, type: 3
Warning [Main]: QPainter::setRenderHint: Painter must be active to set rendering hints
Warning [Main]: QPainter::setMatrixEnabled: Painter not active
Warning [Main]: QPainter::setPen: Painter not active
Warning [Main]: QPainter::setBrush: Painter not active
Warning [Main]: QPainter::setBrush: Painter not active
Warning [Main]: QPainter::setFont: Painter not active
Warning [Main]: QPainter::setPen: Painter not active
Warning [Main]: QPainter::begin: Paint device returned engine == 0, type: 3
Warning [Main]: QPainter::setRenderHint: Painter must be active to set rendering hints
```

Also I squashed the previous 6 commits.

**Comment by MK-42** [comment]
@ronso0 sadly I can't reproduce the screen lag on current master anymore, so I can't confirm if this patch changes anything.

**Comment by ronso0** [comment]
Okay, so I'll try to get a friend's machine to be sure

**Comment by ronso0** [comment]
Thanks for checking!

**Comment by ronso0** [comment]
@sohet Until I get hold of that machine with Intel graphics, can you confirm master doesn't lag anymore?

**Comment by sohet** [comment]
During a short test, it seems that current master (build on my linux box, debian stretch) avoids the lag. Qt5 may have removed it.

**Comment by sohet** [comment]
I also try current 2.1 branch (linked to Qt4), and find that the lag still remains.

**Comment by daschuer** [comment]
Tetsted with qt4 and I see no regression. 
Can we just merge this, or are there any drawbacks?

**Comment by Pegasus-RPG** [comment]
@daschuer This PR is a workaround, not a fix. This workaround sounds like it would make the problem worse in some cases since the whole point of hiding the waveforms is to decrease resource usage. Not completely removing the waveforms hinders that. Rather, this needs further investigation (profiling) on affected systems. Plus @sohet reports above that this isn't a problem in Qt5 anyway.

**Comment by ronso0** [comment]
I'm also against merging this right now, I changed the title accordingly.
Couldn't test this not-so-nice workaround myself on an affected machine.

@Pegasus-RPG Actually CPU usage is constant here no matter if waveforms are visible. I tested with LateNight from master and dragged the upper splitter to collapse the waveforms. Using qt5.2

**Comment by ronso0** [comment]
Closing this now as I can't reproduce the bug in 2.2 with an Intel machine anymore.

**Pull request closed without merging**
