### PR TITLE
Check m_pCurrentTrack is not null

### PR DESCRIPTION
**Pull request by ferranlala**
Fixes https://bugs.launchpad.net/mixxx/+bug/1818714

### CODE REVIEW

**Comment by ywwg** [comment]
Is there any problem if m_pCurrentTrack is not null, but also isn't the correct track?

**Comment by ywwg** [comment]
(with this fix I haven't noticed any issues with, say, the overview not matching the waveform, so I think it may be fine)

**Comment by ferranpujolcamins** [comment]
I'm not sure

**Comment by ywwg** [comment]
I think this check is sufficient.  Let's merge and I'll be on the lookout for any other issues

**Comment by uklotzde** [comment]
LGTM.

The handling of m_pCurrentTrack being invalid/unset is currently very inconsistent in WOverview. I would prefer the _early return_ style to skip the remainder of the function body:

```
if (!m_pCurrentTrack) {
    return;
}
```

**Pull request merged**
