### PR TITLE
Audio Data Caching: Log warning instead of debug message

### PR DESCRIPTION
**Pull request by uklotzde**
Follow up of my recent PR.

This helps to analyze audio issues that might be caused by a shortage of chunks for caching.

### CODE REVIEW

**Comment by daschuer** [comment]
Build fails due to a network error.
```
Err http://ppa.launchpad.net precise/main amd64 Packages

  Unable to connect to ppa.launchpad.net:http:
```

**Comment by jmigual** [comment]
This a Travis problem?

**Comment by daschuer** [comment]
I think yes. The patch here is at least unrelated. So I will merge it now.

**Comment by daschuer** [comment]
Thank you @uklotzde.

**Pull request merged**
