### PR TITLE
User right group for "ViewMenu_ShowSkinSettings", fixes lp1851993.

### PR DESCRIPTION
**Pull request by daschuer**
Fixes https://bugs.launchpad.net/mixxx/+bug/1851993

### CODE REVIEW

**Comment by daschuer** [comment]
This is also a 2.2 issue. Need to rebase.

**Comment by Holzhaus** [comment]
I this a MacOS-only fix or is the issue reproducable on other OSes, too? I'd test your PR, but I have no Mac.

**Comment by ronso0** [comment]
At lest on linux it works perfectly without this PR: shortcut is displayed `Ctrl + 1` and it toggles the menu.

**Comment by daschuer** [comment]
Yes, this works in my case as well. The issue that is fixed here is that there are 

[KeyboardShortcuts], ViewMenu_ShowSkinSettings entries in the keyboard mapping files: 
https://github.com/mixxxdj/mixxx/blob/fcbf2d08959d476bb23abf56a323e96787c68e5b/res/keyboard/de_DE.kbd.cfg#L148

Maybe they are used an MacOs and the default fails for some reason.

**Comment by Holzhaus** [comment]
Hmm, I have the issue of missing keyboard shortcuts on Linux as well (even with this PR applied).
The problems seems to be locale-dependent:

With `LANG=de_DE ./mixxx` the problem persists:
2019-11-21-163824_643x366_scrot

With `LANG=C ./mixxx` the problem is gone:
2019-11-21-163706_596x410_scrot

**Comment by ronso0** [comment]
> At lest on linux it works perfectly without this PR: shortcut is displayed `Ctrl + 1` and it toggles the menu.

Aha. I use the system locale, which is `en_US`

**Comment by daschuer** [comment]
In the German version the short cuts should be translated as well.
"Strg+1"

**Comment by esbrandt** [comment]
> In the German version the short cuts should be translated as well.

Hmm, they already are translated
https://www.transifex.com/mixxx-dj-software/mixxxdj/translate/#de/mixxx2-3/153124672?q=text%3Actrl.

Could it be, that not the translated shortcuts from ``res/translations/*.ts``, but from the keyboard shortcut file `res/keyboard/*.kbd.cfg` are displayed? We have contradicting shortcuts in https://github.com/mixxxdj/mixxx/blob/a7a79385cac013ab78150c6043629be0ef30fa5f/res/keyboard/de_DE.kbd.cfg#L148-L154
I have never noticed on macOS, because there is always the ``Command key (⌘)`` on display, no matter the language .
Capto_Capture 2019-11-21_09-10-55_PM

**Comment by Holzhaus** [comment]
> Could it be, that not the translated shortcuts from `res/translations/*.ts`, but from the keyboard shortcut file `res/keyboard/*.kbd.cfg` are displayed? We have contradicting shortcuts in
> 
> https://github.com/mixxxdj/mixxx/blob/a7a79385cac013ab78150c6043629be0ef30fa5f/res/keyboard/de_DE.kbd.cfg#L148-L154

Bingo, running this command fixed the issue for me:
```bash
$ sed -i 's/ViewMenu_ShowSamplers Ctrl+1/ViewMenu_ShowSkinSettings Ctrl+1/' res/keyboard/*.kbd.cfg
```

**Comment by daschuer** [comment]
Does this mean we can merge this now?

**Comment by Holzhaus** [comment]
As I said, the issue is only fixed if you fix the keyboard shortcuts in `res/keyboard/*.kbd.cfg`. For some reason, Ctrl+1 is mapped to ShowSamplers instead of ShowSkinSettings there.

**Comment by daschuer** [comment]
Ah got it. I did not understand it, because it was already fixed in master 
https://github.com/mixxxdj/mixxx/commit/4db75b67a0ebc4ecbfbceab057075a332b2fda1d

**Comment by daschuer** [comment]
OK, kbd.cfg files are fixed now.

**Comment by Holzhaus** [comment]
I tested with `LANG=cs_CZ`, `da_DK`, `de_CH`, `de_DE`, `el_GR`, `en_US`, `es_ES`, `fi_FI`, `fr_CH`, `fr_FR`, `it_IT` and `ru_RU` and the `Ctrl+1` shortcut shows up and works with all of them. LGTM.

**Comment by uklotzde** [comment]
Also, LGTM.

@daschuer Could you please add a line in the changelog in #1789?

**Comment by uklotzde** [comment]
The branch was targeted to master!!

**Comment by uklotzde** [comment]
Follow-up #2372

**Pull request merged**
