### PR TITLE
fix: remove scaleSignal in waveform analyzer

### PR DESCRIPTION
**Pull request by acolombier**
This PR removes the signal scaling applied on bass and global signal. 

@m0dB @ywwg @JoergAtGithub your review and test would be very appreciated! :) 

Depends on #13106 , which contains the Waveform version bump.

### CODE REVIEW

**Comment by m0dB** [comment]
As this hasn't been merged immediately after https://github.com/mixxxdj/mixxx/pull/13106, doesn't this require another version bump?

**Comment by acolombier** [comment]
It has been that long, so could we assume it is still fine to do it now? If we wait more, agreed it will need another bump.

**Comment by daschuer** [comment]
A version bump, is cheap now that we have already a bump. Regular user needs to reanalyze after update anyway. So let's bump again and avoid inconsistency for alpha users.

**Comment by acolombier** [comment]
Updated - are we happy with my approach to make a minor bump?

**Review by ywwg — APPROVED** [review]

**Review by daschuer — CHANGES_REQUESTED** [review]
WaveformFactory::waveformVersionToVersionClass() needs to be updated as well. 
I think we want to remove 6.0?

**Comment by JoergAtGithub** [comment]
@acolombier Unfortunately there is a merge conflict now

**Comment by acolombier** [comment]
Updated @JoergAtGithub - hopefully this can go in now!

**Comment by Swiftb0y** [comment]
there is a weird compilation error (maybe whitespace related?). Can you look into that?

**Review by ywwg — APPROVED** [review]

**Comment by acolombier** [comment]
@daschuer merge?

**Comment by Swiftb0y** [comment]
there is still an MSVC error. Can you look into that?

**Review by Swiftb0y — APPROVED** [review]
LGTM. waiting for @daschuer to resolve their review

**Review by daschuer — APPROVED** [review]
LGTM, thank you.

**Pull request merged**
