### PR TITLE
Unofficial Pre c++17 Ubuntu Xenial

### PR DESCRIPTION
**Pull request by daschuer**
With this PR, compiling with c++14 compilers should be still possible.

This removes also the alternative solution for clang dieabling -Winvalid-constexpr, Which helps to make correct use of the constexpr keyword. 

We may either merge this branch, or just keep it around for users which are sucked on an outdated compiler for some reasons.

### CODE REVIEW

**Comment by uklotzde** [comment]
If code I contributed is supposed to be rewritten and downgraded from C++17 to C++14 I really have to think if it was worth contributing in the first place. Just saying.

Please mark this PR as *unofficial* to avoid confusion.

**Comment by daschuer** [comment]
This is just the code I have used to test your PR. I took care to not destroy your work IMHO. The PR might look huge due to the clang-format hook.

**Comment by Be-ing** [comment]
I'm not in favor of merging this. If you want to maintain it, that's up to you, but I would think it would be easier to update your OS.

**Comment by daschuer** [comment]
Yes that is my plan, to update my PC once 2.2 falls out of support.
As of macOs this PR has a smaller impact to the constexpr issue compared to disable it entirely.

**Pull request closed without merging**
