### PR TITLE
VCI-100MKII: add variable beatjump, loop_move and fx super/mix knob

### PR DESCRIPTION
**Pull request by sohet**
- Fixed length loop_move -> beatjump by the default length, or _in loop_ loop_move by the current loop length
- Only fx wet/dry mix -> super1, or _on shift_ mix with soft takeover
- Map super knob link setting of fx parameters
- LoadSelectedIntoFirstStopped -> maixmize_library (push selector)
- Exchange up and down of waveform_zoom (following Deere skin)
- Map brake and reverse (drop beats_translate_match_alignment)

http://www.mixxx.org/wiki/doku.php/vestax_vci-100mkii#mapping_for_mixxx_development

### CODE REVIEW

**Comment by Be-ing** [comment]
Can you elaborate how the brake effect works? I'm confused about what the code dealing with slip_enabled does.

**Comment by Be-ing** [comment]
Can you elaborate how the brake effect works? I'm confused about what the code dealing with slip_enabled does.

**Comment by sohet** [comment]
Thank you for reviewing.

> Can you elaborate how the brake effect works? I'm confused about what the code dealing with slip_enabled does.

When engine.brake is deactivated by false value, the deck recovers the normal speed if it is still playing. In this case, there is no difference from loop on resumming the slip. Simply deactivate slip_enable and activate slip_enable again. The total effect is temporary retard and resume on beat.

activate engine.brake
(slow speed)
--- short ---
(slower speed)
deactivate engine.brake
(normal speed)
deactivate slip_enabled
(resume)
activate slip_enabled

But if the deck is stopped by the long engine.brake activation, the deactivation does nothing and the deck remains stopped. In this case, the same resumming method as above causes the shadow deck to stop. To avoid it, I change the condition of the function "VCI102.slip" and pick the following way.

activate engine.brake
(slow speed)
--- long ---
(stopped)
deactivate engine.brake
(do nothing on slip_enable at this point by the condition (!value && engine.getValue(group, "play")))
--- pause as you like ---
restart the deck by "play" (if you want to continue the session)
(normal speed)
deactivate slip_enabled ("VCI102.slip" is also connected to "play")
(resume)
activate slip_enabled

**Comment by Be-ing** [comment]
Okay, I think I understand. So shift and the jog wheel have to be turned until the deck fully stops, otherwise playback resumes when the wheel is released?

**Comment by sohet** [comment]
Just as you say.

> Please describe this on the wiki.

Done.

**Comment by Be-ing** [comment]
Alright, LGTM :+1:

**Comment by Be-ing** [comment]
Can someone merge this?

**Comment by daschuer** [comment]
Thank you @sohet and @Be-ing.

**Pull request merged**
