### PR TITLE
Sandbox: remove erroneous and superfluous home directory check

### PR DESCRIPTION
**Pull request by Be-ing**
This is only causing problems, not solving any:
https://mixxx.discourse.group/t/macos-big-sur-issue-and-temporary-resolution/20257/179

### CODE REVIEW

**Comment by Be-ing** [comment]
If it isn't broken, don't fix it!

**Review by Holzhaus — APPROVED** [review]
The `USER` variable check above should catch most issues anyway. No objections.

**Comment by Be-ing** [comment]
I think signed builds were failing that check because the home dir is not readable from the sandbox.

**Comment by Be-ing** [comment]
Merge?

**Pull request merged**
