### PR TITLE
Slimdown moc_compilation.cpp

### PR DESCRIPTION
**Pull request by poelzi**
The moc_compilation file became unbearable large, easily taking 10 minutes
to compile whenever a Q_OBJECT changes.
AUTOMOC scans for <basename>_moc.cpp includes and does not add the file
to the moc_compilation whenever it is included in the propper cpp file.

After this patch, moc_compilation.cpp is empty and the mocs are compiled
with the approptial cpp, increasing recompile speeds by a factor of 10 when
just a header file changed.

### CODE REVIEW

**Comment by poelzi** [comment]
@uklotzde @daschuer please merge. Since this will cause cause lots of conflicts, I don't want to keep this up to date for long time.

**Comment by Holzhaus** [comment]
> The moc_compilation file became unbearable large, easily taking 10 minutes
> to compile whenever a Q_OBJECT changes.

o.O You meant *seconds*, not *minutes*, right?

I think either something is misconfigured on your machine, you're using a C64 to build Mixxx or my CMake/Qt version is newer and takes care of that automatically. It hardly takes longer than a few seconds for me.

Can someone reproduce this long build time? I'd like to avoid this hack if possible.

**Comment by poelzi** [comment]
@Holzhaus no, I mean minutes. And no, I don't think something is misconfigured, it behaves exactly as AUTOMOC cmake is described. Look at your mixxx-lib_autogen/mocs_compilation.cpp file, count the includes and then count the number of lines it adds up to. When you change any CObject we define anywhere in our codebase, this file gets recompiled. With this patch, gcc with some changes in headers is down to 1 minutes when it needed 6-8 before.

**Comment by poelzi** [comment]
As you can read it https://doc.qt.io/qt-5/moc.html and here https://cmake.org/cmake/help/latest/prop_tgt/AUTOMOC.html
We are using it wrong and this is not a hack but fixes our wrong usage.

**Comment by uklotzde** [comment]
Same here, no issues. I cannot confirm this. Manually including all the generated moc files is a maintenance burden.

Linking takes the longest time, around 20-30 secs maximum.

**Comment by poelzi** [comment]
@uklotzde if you change any, total minor Q_OBJECT that is only included once, it does not recompile mocs_compilation at your machine ? Whats the content of this file ?

**Comment by uklotzde** [comment]
The CMake description suggest that the additional include in the `<base>.cpp` should be `#include "<base>.moc"` and not `#include "moc_<base>.cpp`? This at least looks more reasonable and matches the .cpp/.h naming.

**Comment by poelzi** [comment]
@uklotzde according to AUTOMOC description we are using the first case with this patch.
My mocs_compilation.cpp, the by far slowest file to compile is now:

```
// This file is autogenerated. Changes will be overwritten.
// No files found that require moc or the moc files are included
enum some_compilers { need_more_than_nothing };
```

**Comment by uklotzde** [comment]
Just checked my build folder. I have individual `moc_<base>.cpp` files as expected that are compiled individually without manually including them in every .cpp file. I don't get a `moc_compilation.cpp` file.

**Comment by poelzi** [comment]
@uklotzde if I include a "basename.moc" in the cpp file, I get warnings from automoc or need to put it at the end of the file which would be rather annoying.

**Comment by uklotzde** [comment]
Nevertheless, manually including auto-generated files just for compilation feels wrong. CMake should instead implicitly add them to the list of files that need to be built and compile them individually. I would expect the build system and the Qt integration to take car of that?

**Comment by poelzi** [comment]
Having one additional include in the cpp of a qobject is not a burden and I did all the work. If you forget it, does not matter and you end up with an entry there. Even the QT doc say to include the file and no, I don't feel it is wrong.
I'm sorry that I only have a 4/8 core machine and experiencing long and frustrating compile times because we are using qt wrong.

**Comment by uklotzde** [comment]
Ok, got it:

> Not included moc_<basename>.cpp files will be generated in custom folders to avoid name collisions and included in a separate <AUTOGEN_BUILD_DIR>/mocs_compilation.cpp file which is compiled into the target.

@Holzhaus I still don't understand why CMake doesn't simply add the source files implicitly to the corresponding target(s)? Including every single file manually is tedious and error prone.

**Comment by uklotzde** [comment]
I am only compiling with 2 (out of 4) Skylake cores without such severe issues.

**Comment by Holzhaus** [comment]
> @Holzhaus no, I mean minutes. And no, I don't think something is misconfigured, it behaves exactly as AUTOMOC cmake is described. Look at your mixxx-lib_autogen/mocs_compilation.cpp file, count the includes and then count the number of lines it adds up to. When you change any CObject we define anywhere in our codebase, this file gets recompiled. With this patch, gcc with some changes in headers is down to 1 minutes when it needed 6-8 before.
> [...]
> I'm sorry that I only have a 4/8 core machine and experiencing long and frustrating compile times because we are using qt wrong.

What CMake/Qt version do you use? I just tested this by making a minor change and starting a single-threaded (!) build on my laptop while on battery (so the CPU is be underclocked to save power). It took less than 1 minute including linking both `mixxx` and `mixxx-test`.

```
[15:20] ~/Projects/mixxx/cmake_build[HEAD@11c9e64e8e*?]$ git diff
diff --git a/src/preferences/dialog/dlgprefwaveform.h b/src/preferences/dialog/dlgprefwaveform.h
index 339038d07a..beef572cb7 100644
--- a/src/preferences/dialog/dlgprefwaveform.h
+++ b/src/preferences/dialog/dlgprefwaveform.h
@@ -39,6 +39,9 @@ class DlgPrefWaveform : public DlgPreferencePage, public Ui::DlgPrefWaveformDlg
     void slotSetBeatGridAlpha(int alpha);
     void slotSetPlayMarkerPosition(int position);

+  signals:
+    void someSignal(int position);
+
   private:
     void initWaveformControl();
     void calculateCachedWaveformDiskUsage();
[15:20] ~/Projects/mixxx/cmake_build[HEAD@11c9e64e8e*?]$ time cmake --build . -j 1
[  2%] Built target benchmark
[  2%] Symlinking test data to build directory...
[  2%] Built target mixxx-testdata
[  5%] Built target shout_mixxx
[  6%] Built target mixxx-xwax
[  6%] Built target ReplayGain
[ 10%] Built target QueenMaryDsp
[ 10%] Automatic MOC for target QtScriptByteArray
[ 10%] Built target QtScriptByteArray_autogen
[ 10%] Built target QtScriptByteArray
[ 11%] Built target MP3GuessEnc
[ 11%] Built target Kaitai
[ 11%] Built target fidlib
[ 12%] Built target libebur128
[ 13%] Symlinking resources to build directory...
[ 13%] Built target mixxx-res
[ 13%] Built target FpClassify
[ 13%] Built target Reverb
[ 13%] Built target PortAudioRingBuffer
[ 14%] Built target libKeyFinder
[ 14%] Symlinking to build directory...
[ 14%] Built target mixxx-script
[ 15%] Built target mixxx-proto
[ 15%] Automatic MOC and UIC for target mixxx-lib
[ 15%] Built target mixxx-lib_autogen
Scanning dependencies of target mixxx-lib
[ 15%] Building CXX object CMakeFiles/mixxx-lib.dir/mixxx-lib_autogen/mocs_compilation.cpp.o
[ 15%] Building CXX object CMakeFiles/mixxx-lib.dir/src/preferences/dialog/dlgpreferences.cpp.o
[ 16%] Building CXX object CMakeFiles/mixxx-lib.dir/src/preferences/dialog/dlgprefwaveform.cpp.o
[ 16%] Linking CXX static library libmixxx-lib.a
[ 87%] Built target mixxx-lib
[ 88%] Built target gtest
[ 88%] Built target gmock
[ 88%] Automatic MOC for target mixxx-test
[ 88%] Built target mixxx-test_autogen
[ 88%] Built target mixxx-qrc
[ 88%] Linking CXX executable mixxx-test
[ 99%] Built target mixxx-test
[ 99%] Linking CXX executable mixxx
[ 99%] Built target mixxx
[ 99%] Built target gmock_main
[ 99%] Built target gtest_main
[100%] Built target benchmark_main

real	0m59.705s
user	0m53.572s
sys	0m6.550s
```

Doing the same with this branch gives me:
```
real	0m38.785s
user	0m31.841s
sys	0m6.026s
```

So we get a 20 second speedup, but since the build is single-thread it will be even less noticeable. I think it's not really worth the maintenance burden.

Can you check what Qt/CMake version you're using? 10 minutes is not normal, and I guess the problem lies somewhere else.

**Comment by poelzi** [comment]
@uklotzde It really depends on your change. If you change a cpp file, the compile time is ok, if you change a header, it depends from.
cmake version 3.18.2
clazy version: 1.8
clang version: 10.0.1

**Comment by poelzi** [comment]
20 seconds are 20 seconds you will have to wait less on your ide, every time you press compile. I like it.

**Comment by Holzhaus** [comment]
> 20 seconds are 20 seconds you will have to wait less on your ide, every time you press compile. I like it.

It's actually not 20 seconds if you use multiple  threads. Then it might not even be noticeable at all.

But maybe clazy/clang is the culprit. I tested with gcc. I'll give it another try.

**Comment by poelzi** [comment]
Compiler a single threaded, it takes therefore at least the time of the longest file which is mocs_compilation.cpp

**Comment by Holzhaus** [comment]
> Compiler a single threaded, it takes therefore at least the time of the longest file which is mocs_compilation.cpp

Yes, but if you uses multi-threading, the workload will be distributed to multiple threads.

With 2 threads:

    [                               20s                                            ]
    [1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s]

Now the same workload without the file that takes 20s:

    [1s][1s][1s][1s][1s][1s][1s][1s][1s][1s]
    [1s][1s][1s][1s][1s][1s][1s][1s][1s][1s]

-> Saves 10 seconds

With 4 threads:

    [                              20 s                                            ]
    [1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s]
    [1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s]
    [1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s]

    [1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s]
    [1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s]
    [1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s]
    [1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s][1s]

-> Saves 5 seconds

**Comment by Holzhaus** [comment]
I'm pretty sure that clazy is the culprit... it's sloooooow.

**Comment by Be-ing** [comment]
This step is definitely a bottleneck in the build process. On my new laptop, I don't care. On this 9 year old Macbook Air, it is certainly noticeable. Is there a better solution to this? I don't know. It would be nice to overcome this bottleneck, but it doesn't matter to me much either way.

**Comment by Holzhaus** [comment]
> I'm pretty sure that clazy is the culprit... it's sloooooow.

Yes it is. I can finally reproduce the problem:

2.3 with clazy:
```
real	10m3.490s
user	9m59.149s
sys	0m4.329s
```

This branch with clazy:
```
real	1m1.909s
user	0m56.378s
sys	0m4.087s
```

In that case I think we can merge this. It's unfortunate that CMake doesn't just add the individual `moc_*.cpp` files to the target automatically rather than adding a single, huge cpp file that is much more complex to build. Maybe we should open a bug report upstream?

@uklotzde What do you think?

**Comment by uklotzde** [comment]
Ok, then we need this ugly workaround.

**Review by uklotzde — APPROVED** [review]

**Review by Holzhaus — APPROVED** [review]
Thank you.

**Comment by daschuer** [comment]
All Green. 
LGTM. Thank you for investigate that.
It has puzzledme as well.

**Comment by poelzi** [comment]
Thanks a lot, but at least everybody gets at least some seconds out of this ;)

**Comment by daschuer** [comment]
Oh no, this breaks Scons?

Am almost done with cmake PPA upload.
Revert this or remove scons?
Is there anything else that requires Scons?

**Comment by Be-ing** [comment]
Remove scons.

**Comment by uklotzde** [comment]
SCons is not covered by CI anymore. We have to remove it or accept that it is broken.

**Comment by uklotzde** [comment]
@Holzhaus I am currently building main locally after merging.

**Comment by uklotzde** [comment]
Suddenly unrelated clazy CI warnings/errors after merging to main that should be unrelated?! Suspending work on this after already spending too much time.

**Comment by Be-ing** [comment]
I see this when building now:
```
AutoMoc: /home/be/sw/mixxx/src/widget/effectwidgetutils.h:0: Note: No relevant classes found. No output generated.
```

**Comment by uklotzde** [comment]
> I see this when building now:
> 
> ```
> AutoMoc: /home/be/sw/mixxx/src/widget/effectwidgetutils.h:0: Note: No relevant classes found. No output generated.
> ```

Automoc seems to get confused by the contents of this file, didn't check why. Doesn't do any harm, though.

**Comment by uklotzde** [comment]
@poelzi https://bugs.launchpad.net/mixxx/+bug/1907528

**Pull request merged**
