### PR TITLE
Use Qt 5.14 on Appveyor

### PR DESCRIPTION
**Pull request by JosepMaJAZ**
get version automatically from build environment on windows.

Before merging, we need a clear picture of what will happen with the cache.  (We will have PRs with 5.12 and others with 5.14, and the patch here assumes there will be only one Qt- version in the build environment.)
See: https://ci.appveyor.com/api/buildjobs/ama90tkip0xqlxbl/log

### CODE REVIEW

**Comment by rryan** [comment]
Looks like the appveyor build failed:
```
-- Could NOT find Protobuf (missing: Protobuf_LIBRARIES) (found version "2.6.1")
CMake Error at CMakeLists.txt:1386 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.
  Could not find a package configuration file provided by "Qt5" with any of
  the following names:
    Qt5Config.cmake
    qt5-config.cmake
  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also "C:/projects/mixxx/cmake_build/CMakeFiles/CMakeOutput.log".
See also "C:/projects/mixxx/cmake_build/CMakeFiles/CMakeError.log".
-- Cache values
BENCHMARK_BUILD_32_BITS:BOOL=OFF
BENCHMARK_DOWNLOAD_DEPENDENCIES:BOOL=OFF
BENCHMARK_ENABLE_ASSEMBLY_TESTS:BOOL=OFF
BENCHMARK_ENABLE_EXCEPTIONS:BOOL=ON
BENCHMARK_ENABLE_GTEST_TESTS:BOOL=ON
BENCHMARK_ENABLE_INSTALL:BOOL=OFF
BENCHMARK_ENABLE_LTO:BOOL=OFF
BENCHMARK_ENABLE_TESTING:BOOL=OFF
BENCHMARK_USE_LIBCXX:BOOL=OFF
BUILD_GMOCK:BOOL=ON
BUILD_TESTING:BOOL=ON
CLCACHE_EXECUTABLE:FILEPATH=C:/Python37-x64/Scripts/clcache.exe
CLCACHE_SUPPORT:BOOL=ON
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_INSTALL_PREFIX:PATH=C:/mixxx
DEBUG_ASSERTIONS_FATAL:BOOL=OFF
INSTALL_GTEST:BOOL=OFF
LIBRT:FILEPATH=LIBRT-NOTFOUND
Protobuf_SRC_ROOT_FOLDER:PATH=Protobuf_SRC_ROOT_FOLDER-NOTFOUND
Qt5_DIR:PATH=Qt5_DIR-NOTFOUND
STATIC_DEPS:BOOL=ON
WARNINGS_FATAL:BOOL=OFF
WARNINGS_PEDANTIC:BOOL=OFF
Command exited with code 1
```

**Comment by JosepMaJAZ** [comment]
Doh... I forgot to remove the old set QT_PATH. Commited. Let's wait for the new compilation

**Comment by Be-ing** [comment]
Merge master to include the Windows build fix from #2695.

**Comment by Be-ing** [comment]
CI succeeded, thanks

**Pull request merged**
