### PR TITLE
Cleanup header comments

### PR DESCRIPTION
**Pull request by Holzhaus**
Superseedes https://github.com/mixxxdj/mixxx/pull/3275 so we can finally get this over with.

### CODE REVIEW

**Review by uklotzde — APPROVED** [review]
Very straightforward changes (mostly) limited to the header and footer of files. Not supposed to cause any severe merge conflicts.

**Comment by uklotzde** [comment]
@Be-ing @daschuer Merge?

**Comment by uklotzde** [comment]
Too late. Now we have the conflicts after merging #3411.

@Holzhaus Any ideas how to resolve them effectively? Or do we need to start from scratch now?

**Comment by Holzhaus** [comment]
> @Holzhaus Any ideas how to resolve them effectively? Or do we need to start from scratch now?

No, I resolved them manually.

**Comment by uklotzde** [comment]
Let's merge this PR after CI builds succeeded.

**Comment by Be-ing** [comment]
I resolved conflicts with main.

**Comment by uklotzde** [comment]
> I resolved conflicts with main.

Thank you! And main now builds cleanly again.

**Pull request merged**
