### PR TITLE
Merge 2.4

### PR DESCRIPTION
**Pull request by ronso0**

### CODE REVIEW

**Comment by ronso0** [comment]
Okay, so the merge itself seems okay (fix Windows configure -> Manual download), but now it fails building src\util\movinginterquartilemean.cpp(56) on Windows:
https://github.com/mixxxdj/mixxx/actions/runs/6632905711/job/18019579421?pr=12215#step:22:1308

**Comment by Swiftb0y** [comment]
lgtm, go ahead and push.

**Comment by ronso0** [comment]
Done.

Here, I've reverted the commit to see the log message again.
I'm curious why this only occurs on Windows CI. Is it the only this config treats this exact warning a error? foreach is used in many more places in a similiar manner.

**Comment by Swiftb0y** [comment]
not sure, there is some conditional preprocessor logic there. https://woboq.com/~codebrowser/qt6/qtbase/src/corelib/global/qglobal.h.html#1168
Maybe the windows build is configured slightly differently?

**Comment by ronso0** [comment]
I attached the error message above, in case someone wants to take a look.

**Pull request closed without merging**
