### PR TITLE
chore: update the donate button label

### PR DESCRIPTION
**Pull request by acolombier**
Noticed a weird mention of PayPal in the README which seem to have been missed in #3873

### CODE REVIEW

**Review by Swiftb0y — APPROVED** [review]
Do you also want to add some more open-collective specific metrics? https://shields.io/badges/open-collective-backers-and-sponsors

**Review by Swiftb0y — APPROVED** [review]
LGTM. @ywwg wdyt?

**Review by ywwg — APPROVED** [review]

**Comment by ronso0** [comment]
Um, why has this merged to main instead of 2.4? (I think that's the "oldest" version that may be looked up on Github)

**Comment by acolombier** [comment]
I did base it on `main` because that's the default view for anyone going to the Mixxx repo, but it might be worth having a cherry pick of this to 2.4 if anyone checks the README for the currently live version.
Happy to do this if you think it is worth the time.

**Comment by ronso0** [comment]
If no one disagrees in the next 24h I'll pick it and push directly to 2.4

**Pull request merged**
