### PR TITLE
Numark Mixtrack 3 - Shift+Filter can control either FX4 or channel gain

### PR DESCRIPTION
**Pull request by ghost**
I made a small change to the Mixtrack 3 script. It introduces a way to control the channel gain using the Shift+Filter knobs. The script uses the default behavior by default (Shift+Filter controls FX4). To enable gain control please change var ShiftFilterFX4 to false. In Mixxx 2.2 Shift+EQ and Shift+Filter affect only the focused FX.

Forum link: https://www.mixxx.org/forums/viewtopic.php?f=7&t=7286&start=300

### CODE REVIEW

**Comment by nttmusic** [comment]
Need to make a small change to ShiftFilterFX4's default value to assure backward compatibility.

**Comment by Be-ing** [comment]
LGTM thank you.

**Comment by Be-ing** [comment]
Could you add this to the [wiki](https://mixxx.org/wiki/doku.php/numark_mixtrack_pro_3#configuration_options)?

**Comment by nttmusic** [comment]
Will do

**Comment by Be-ing** [comment]
@nttmusic a user on the forum has a question about this: https://mixxx.org/forums/viewtopic.php?f=3&t=11698

**Comment by Be-ing** [comment]
Whoops, I noticed this was targeted at the master branch. I rebased it on 2.1 for the release.

**Pull request merged**
