### PR TITLE
Remove all sample-based Cue methods

### PR DESCRIPTION
**Pull request by Holzhaus**
Based on #4049. This changes the Cue API to use frame positions.

Prerequisite PRs:
- [x] #4074
- [x] #4075
- [x] #4076
- [x] #4077
- [x] #4078
- [x] #4079
- [x] #4080
- [x] #4081
- [x] #4082
- [x] #4083

~~This is extremely weird. Only the last commit is of interest (the other ones are part of other PRs). That last commit makes a bunch of test cases time out, and I have no idea why.~~

~~**EDIT** The commit seems to cause an endless loop in `Track::setCuePointsWhileLocked`. Investigating.~~

~~**EDIT 2** Looks like I'm not the brightest candle on the cake:~~

```cpp
    double toEngineSamplePosMaybeInvalid() const {
        if (!isValid()) {
            return kLegacyInvalidEnginePosition;
        }
        return toEngineSamplePosMaybeInvalid();
    }
 ```

~~No wonder there is an endless loop :)~~

**EDIT 3** Fixed.

### CODE REVIEW

**Review by uklotzde — APPROVED** [review]
:+1: LGTM

**Comment by LeDucDuBleuet** [comment]
Currently AutoDJ crashes Mixxx completely with a segfault when using "Enable random track addition to queue". It started crashing with this commit or the ones referred to in the first comment I believe a couple days after committing #4041... 

Let me know if we need to file a new bug on Launchpad. Thx

**Comment by Be-ing** [comment]
That is unrelated to this PR, please report a bug on Launchpad.

**Comment by LeDucDuBleuet** [comment]
@Be-ing Thanks for the quick reply, I opened one : https://bugs.launchpad.net/mixxx/+bug/1936396

**Pull request merged**
