### PR TITLE
Refactor Audioplot.py

### PR DESCRIPTION
**Pull request by kain88-de**
The CLI interface now has a nice help text explaining what the script is
supposed to do and the actual plotting function now leverages numpy (a
dependency of matplotlib).

@ywwg can you test if this works for you now.

### CODE REVIEW

**Comment by ywwg** [comment]
beautiful, works.  Just update diff_plots.sh to match the elimination of the -f flag

**Comment by ywwg** [comment]
(and maybe remove the echo line from diff_plots, which I accidentally left in)

**Comment by daschuer** [comment]
It would be nice if audioplot will output an example call with --help option, that actually works within the mixxx source tree.

**Comment by kain88-de** [comment]
> It would be nice if audioplot will output an example call with --help option, that actually works within the mixxx source tree.

It is doing that already in a way that is common to most POSIX tools. Just call the script and pass it the path of a file. `./audioplot.py ../src/test/golden*/<file>`

**Comment by daschuer** [comment]
The root issue for me is that I think we have still a docu gap here. 
The user may want to know why do I need this script and how it is supposed to call. 

An other solution would be to add a readme file that explains the purpose. 

But IMHO its suits best ti just extend the help text with.

```
You can use it for examine the sample files produced by mixxx-test
like that: "./audioplot.py ../src/test/golden*/<file>"
```

**Comment by daschuer** [comment]
By the way, can you integrate the diff script? 
https://github.com/mixxxdj/mixxx/blob/master/scripts/diff_plots.sh
Its somehow strict how to call it and It took me some time to figure out. 

The most valid use case is to compare Samples after a test fails: 
./diff_plots.sh ../src/test/golden_buffers/ScratchTestMaster ../src/test/golden_buffers/ScratchTestMaster.actual

**Comment by kain88-de** [comment]
> The user may want to know why do I need this script and how it is supposed to call.

really you think a developer can't figure out how to run the script from this?

```
./audioplot.py -h
usage: AudioPlot [-h] [-c COLUMNS] file

Audioplot is a simple script for drawing graphs of values. It reads a simple
csv text file where each line needs to contain the same number of
comma-separated values, like so:

0, 0, 0
1, 2, 1
2, 4, 2

Each column will be plotted as a separate curve on the same time series.
Matplotlib is used to display the result.

positional arguments:
  file                  file to plot from

optional arguments:
  -h, --help            show this help message and exit
  -c COLUMNS, --columns COLUMNS
                        lines to plot seperated by a comma, default "all"
```

IMHO that is everything one needs to know to use this script. argparse is supposed to produce help messages with a usage description so that I don't have to write that line anymore. 

But the documentation about the existence of this script might better live in the cpp-testfiles.

**Comment by daschuer** [comment]
> really you think a developer can't figure out how to run the script from this?

The issue is not how, it is the missing context. 

IMHO the proposed sentence above, actually helps. But If you think it will hurt here, because a user reads unrelated info leave it out. 

By the way:  We have also the Mixxx context in other scripts: 
https://github.com/mixxxdj/mixxx/blob/master/scripts/generate_sample_functions.py#L6

**Comment by ywwg** [comment]
These scripts are not really user-facing and are for our internal testing only.  It's not really important that a user know exactly what these scripts do -- maybe we can add a README.md but I'm totally fine with that being a TODO.

**Comment by kain88-de** [comment]
It should be mentioned in the EngineBuffer tests. Since this is a tool to help analyse the test we should mention them there. I'm will also add a line in the python script later what the intended use is. But I don't see the point of giving an example call of the script (that doesn't explain anything and a dev should figure out how to call the script without that)

**Comment by kain88-de** [comment]
I included the diffs script. `audioplot.py` is accepting wildcard arguments. I also added a note in appropriate places for what we are using the script.

**Comment by daschuer** [comment]
Thank you! Works really nice now. LGTM

**Pull request merged**
