### PR TITLE
Build: Enable warning -Woverloaded-virtual

### PR DESCRIPTION
**Pull request by uklotzde**
This option helps to detect unintended overloading of non-virtual methods from base classes. Could have detected the obsolete slots fixed in #3044.

As a prerequisite, some fixes in the controller subsystem were required. The backport to 2.3 would require some effort due to differences in the class hierarchy. I neither have the time nor motivation to sort this out.

### CODE REVIEW

**Comment by uklotzde** [comment]
@Holzhaus I didn't find a solution for suppressing the following warning during the build:

```
[264/681] Building C object CMakeFiles/mixxx-lib.dir/src/musicbrainz/crc.c.o
cc1: warning: command-line option ‘-Woverloaded-virtual’ is valid for C++/ObjC++ but not for C
```

**Comment by uklotzde** [comment]
> @Holzhaus I didn't find a solution for suppressing the following warning during the build:
> 
> ```
> [264/681] Building C object CMakeFiles/mixxx-lib.dir/src/musicbrainz/crc.c.o
> cc1: warning: command-line option ‘-Woverloaded-virtual’ is valid for C++/ObjC++ but not for C
> ```

"Fixed" by renaming the file :see_no_evil:

**Review by Holzhaus — APPROVED** [review]
LGTM, works fine on my machine. Waiting for CI.

**Comment by uklotzde** [comment]
@Holzhaus Wait a moment. The renamed Q_INVOCABLE in HidControllerJSProxy could cause issues. I'll check if this was really necessary.

**Comment by uklotzde** [comment]
> HidControllerJSProxy

Reverted. Locally builds without errors.

**Comment by uklotzde** [comment]
OSX/clang/SCons spoils all Travis CI builds. We need to get rid of it.

**Comment by uklotzde** [comment]
Ping

**Comment by uklotzde** [comment]
Pingping

**Review by Holzhaus — APPROVED** [review]

**Pull request merged**
