### PR TITLE
OpenGL ES fix  

### PR DESCRIPTION
**Pull request by daschuer**
I turns out the #3466 was not enough. 
Hopefully this builds now.

### CODE REVIEW

**Comment by Be-ing** [comment]
Did you intend to target 2.3?

**Comment by daschuer** [comment]
Oh, yes 2.3.

**Comment by Be-ing** [comment]
@moretocome can you test this?

**Comment by daschuer** [comment]
All Green. 
Can we just merge this.
Than we see if the PPA build succeeds.
Current it is broken anyway.

**Review by uklotzde — APPROVED** [review]
Next try ;) LGTM

**Comment by moretocome** [comment]
@Be-ing 

Less error, but still fails. Output:
```
[  0%] Built target mixxx-hidapi
[  1%] Built target mixxx-qrc
[  6%] Built target SoundTouch
[  6%] Built target shout_mixxx
[  6%] Automatic MOC for target QtScriptByteArray
[  6%] Built target libKeyFinder
[  8%] Built target mixxx-xwax
[  8%] Built target fidlib
[  8%] Built target QtScriptByteArray_autogen
[  9%] Built target ReplayGain
[  9%] Built target PortAudioRingBuffer
[ 12%] Built target QueenMaryDsp
[ 12%] Built target Kaitai
[ 12%] Built target FpClassify
[ 13%] Built target MP3GuessEnc
[ 13%] Built target Reverb
[ 13%] Symlinking resources to build directory...
[ 13%] Symlinking to build directory...
[ 14%] Built target mixxx-proto
[ 16%] Built target benchmark
[ 16%] Built target mixxx-res
[ 16%] Built target mixxx-script
[ 16%] Symlinking test data to build directory...
[ 16%] Built target gtest
[ 16%] Built target benchmark_main
[ 16%] Built target mixxx-testdata
[ 16%] Built target QtScriptByteArray
[ 16%] Built target gmock
[ 17%] Built target gtest_main
[ 17%] Automatic MOC and UIC for target mixxx-lib
[ 17%] Built target gmock_main
[ 17%] Built target mixxx-lib_autogen
[ 18%] Building CXX object CMakeFiles/mixxx-lib.dir/src/waveform/waveformwidgetfactory.cpp.o
[ 18%] Building CXX object CMakeFiles/mixxx-lib.dir/src/waveform/widgets/glrgbwaveformwidget.cpp.o
[ 18%] Building CXX object CMakeFiles/mixxx-lib.dir/src/waveform/widgets/glsimplewaveformwidget.cpp.o
[ 18%] Building CXX object CMakeFiles/mixxx-lib.dir/src/waveform/widgets/glslwaveformwidget.cpp.o
In file included from /home/pi/mixxx/src/waveform/widgets/glsimplewaveformwidget.h:3,
                 from /home/pi/mixxx/src/waveform/widgets/glsimplewaveformwidget.cpp:1:
/home/pi/mixxx/src/waveform/widgets/glwaveformwidgetabstract.h: In constructor ‘GLWaveformWidgetAbstract::GLWaveformWidgetAbstract(const QString&, QWidget*)’:
/home/pi/mixxx/src/waveform/widgets/glwaveformwidgetabstract.h:21:15: error: class ‘GLWaveformWidgetAbstract’ does not have any field named ‘m_pGlRenderer’
               m_pGlRenderer(nullptr) {
               ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/mixxx-lib.dir/build.make:6238: CMakeFiles/mixxx-lib.dir/src/waveform/widgets/glsimplewaveformwidget.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/pi/mixxx/src/waveform/widgets/glrgbwaveformwidget.h:3,
                 from /home/pi/mixxx/src/waveform/widgets/glrgbwaveformwidget.cpp:1:
/home/pi/mixxx/src/waveform/widgets/glwaveformwidgetabstract.h: In constructor ‘GLWaveformWidgetAbstract::GLWaveformWidgetAbstract(const QString&, QWidget*)’:
/home/pi/mixxx/src/waveform/widgets/glwaveformwidgetabstract.h:21:15: error: class ‘GLWaveformWidgetAbstract’ does not have any field named ‘m_pGlRenderer’
               m_pGlRenderer(nullptr) {
               ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/mixxx-lib.dir/build.make:6225: CMakeFiles/mixxx-lib.dir/src/waveform/widgets/glrgbwaveformwidget.cpp.o] Error 1
In file included from /home/pi/mixxx/src/waveform/widgets/glslwaveformwidget.h:3,
                 from /home/pi/mixxx/src/waveform/widgets/glslwaveformwidget.cpp:1:
/home/pi/mixxx/src/waveform/widgets/glwaveformwidgetabstract.h: In constructor ‘GLWaveformWidgetAbstract::GLWaveformWidgetAbstract(const QString&, QWidget*)’:
/home/pi/mixxx/src/waveform/widgets/glwaveformwidgetabstract.h:21:15: error: class ‘GLWaveformWidgetAbstract’ does not have any field named ‘m_pGlRenderer’
               m_pGlRenderer(nullptr) {
               ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/mixxx-lib.dir/build.make:6251: CMakeFiles/mixxx-lib.dir/src/waveform/widgets/glslwaveformwidget.cpp.o] Error 1
In file included from /home/pi/mixxx/src/waveform/widgets/glrgbwaveformwidget.h:3,
                 from /home/pi/mixxx/src/waveform/waveformwidgetfactory.cpp:24:
/home/pi/mixxx/src/waveform/widgets/glwaveformwidgetabstract.h: In constructor ‘GLWaveformWidgetAbstract::GLWaveformWidgetAbstract(const QString&, QWidget*)’:
/home/pi/mixxx/src/waveform/widgets/glwaveformwidgetabstract.h:21:15: error: class ‘GLWaveformWidgetAbstract’ does not have any field named ‘m_pGlRenderer’
               m_pGlRenderer(nullptr) {
               ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/mixxx-lib.dir/build.make:6199: CMakeFiles/mixxx-lib.dir/src/waveform/waveformwidgetfactory.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1289: CMakeFiles/mixxx-lib.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Pull request merged**
