### PR TITLE
pre-commit: add codespell hook

### PR DESCRIPTION
**Pull request by Be-ing**
I am tired of correcting typos in code review.

### CODE REVIEW

**Comment by ronso0** [comment]
does it have a review instance like git-clang where you have to run `git add` again after a commit attempt?

**Comment by Be-ing** [comment]
Yes. For example, I added this to rekordboxfeature.cpp:
```
/// This can ba something.
```

This is what happens with Git:
```
be@localhost ~/s/mixxx (codespell)> git add .
be@localhost ~/s/mixxx (codespell)> git commit
Check for byte-order marker..............................................Passed
Check for case conflicts.................................................Passed
Check JSON...........................................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check Xml............................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
Trim Trailing Whitespace.............................(no files to check)Skipped
Don't commit to branch...................................................Passed
codespell................................................................Failed
- hook id: codespell
- exit code: 1

src/library/rekordbox/rekordboxfeature.cpp:34: ba ==> by, be

eslint...............................................(no files to check)Skipped
clang-format.............................................................Passed
black................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
qsscheck.............................................(no files to check)Skipped
```

**Review by Holzhaus — APPROVED** [review]
Nice!

**Comment by daschuer** [comment]
@Be-ing: 

It looks like this is not ready for checks at the CI because it produces a lot of false positives: 

```
codespell................................................................Failed
- hook id: codespell
- exit code: 2

src/controllers/engine/controllerengine.cpp:1011: pReverse ==> perverse
src/controllers/engine/controllerengine.cpp:1012: pReverse ==> perverse

eslint...............................................(no files to check)Skipped
```

This also checks the whole file and not just the diff. 

Is there a quick solution or can we just disable it by default?

**Comment by Be-ing** [comment]
@Holzhaus do you know how to get codespell to only check the git diff?

**Comment by daschuer** [comment]
We may filter all line numbers that are not part of the diff.

**Comment by daschuer** [comment]
@Be-ing can we disable this hook until we have a solution? We have already too many failing CI PRs

**Comment by Be-ing** [comment]
okay

**Comment by daschuer** [comment]
How are case like pReverse intended to handle? can we configure our prefixes somehow?

**Comment by Be-ing** [comment]
Unfortunately not. You may want to add a request for something like that to https://github.com/codespell-project/codespell/pull/1657

**Comment by Holzhaus** [comment]
As you probably noticed, such a flag is present in the master branch of codespell. I used it in #3061.

**Pull request merged**
