### PR TITLE
Hidremove

### PR DESCRIPTION
**Pull request by daschuer**
This removed the hidapi from the Mixxx source tree and adds it as dependency in the deb files.

Hidapi is part of Ubuntu from Trusty.
The Trusty version compiles on Precise without any issues. So we can provide it as extra package from our PPA.

This setting works nice on Launchpad:
https://launchpad.net/~daschuer/+archive/ubuntu/mixxx

Before merge, we need to add hidapi to the windows and mac build server as well.

I could help there as well, but I cannot no yet, because of missing access.

### CODE REVIEW

**Comment by rryan** [comment]
Hi Daniel -- I already said we weren't going to do this in 2.0. Why is this PR against the 1.12 branch?

**Comment by daschuer** [comment]
Most likely a Debian maintainer needs it. 
... or someone with buildserver access finds time to integrate it before release.

**Comment by Pegasus-RPG** [comment]
There will not be time to do this before 2.0.0 is released. Please re-target this to master.

**Comment by daschuer** [comment]
successor: https://github.com/mixxxdj/mixxx/pull/796

**Pull request closed without merging**
