### PR TITLE
Implement CO for waveform alpha and prefilter waveform

### PR DESCRIPTION
**Pull request by poelzi**
Add two COs to control the waveform alpha as well as the prefilter
waveform alpha.

Adapt existing waveform renderers to use the CO.
Implement prefilter waveforms on the missing waveform renderers.

### CODE REVIEW

**Comment by poelzi** [comment]
Screenshot_2020-09-26_02-14-28
Example screenshot. The GL renderer does a 2 pass rendering, first the unfiltered and then the filtered signal. This way you can easily see, where the baseline starts after a break. Something I have struggled with, multiple times.

**Comment by Be-ing** [comment]
Why should this be configurable? What problem is this solving?

**Comment by poelzi** [comment]
It allows you to map it to a controller knob. I want to control, how much unfiltered waveform I want to see. I plan my transitions sometimes 30-90 seconds into the future (when the bass swap happens) but the track is already mixed in. Without seeing bass, I sometimes don't know where the break ends and the right point is.
If you don't like it, just set it to 0 and you get the old behavior back (depends on the renderer actually). Also, one maybe wants to tweak the normal alpha value to their own liking. The looks depend on the monitor.

**Comment by Be-ing** [comment]
Really? You want to adjust the rendering of the waveform from a controller?

**Comment by toszlanyi** [comment]
@poelzi - I like that idea very much and support your point. I am mixing the traditional way though counting the beats in my mind to know when I am kicking in the bass. to have a visual support for a bass kicking in after a break is much appreciated.

@Be-ing - it is not solving a bug or so but I really love this idea as a new feature. Possibly people (incl) me took is as granted and never thought about missing it. But once it is available I would love to use it. Wouldn't map it to a controller though.

**Comment by Holzhaus** [comment]
Maybe we should try to improve the rendering in other ways. Adjusting the waveform rendering from the controller weird and we don't have an unlimited number of knobs/faders/buttons available, so most people won't benefit from this.

**Comment by Be-ing** [comment]
Sorry if I came off as a little harsh before, but I think we should really question every time someone suggests adding yet another option to Mixxx's already large and complicated preferences. @poelzi you may well be onto something for improving the appearance of the waveforms, but I don't think a preference option is a great way to go about it. If it makes the waveform look better, why not use it always?

**Comment by ronso0** [comment]
Sounds like we want to
* improve the main (default) waveform (see [3 band waveforms](https://mixxx.zulipchat.com/#narrow/stream/247619-design/topic/3-Band.20Waveforms) )

A wish I understand and share:
* add some CO to switch to a 'high contrast' waveform mode (without having to switch the skin/theme)

**Comment by ronso0** [comment]
* keep the preferences simple

**Comment by Holzhaus** [comment]
> * keep the preferences simple

"keep" 😆

**Comment by ronso0** [comment]
you got the message :)
let's say "keep additional preferences simple": mode toggle instead of a slider/spinbox combo

**Comment by poelzi** [comment]
I just want to control the hard coded alpha value together with the alpha value of the filtered part. That's it. They are two settings in the waveform preferences and they are COs because I want to have them dynamic. I did not overcomplicate things and created a CO for each deck. One CO for each setting. If you don't want to map it, don't do it. Just use the slider and set it to whatever look you like.

If it is about simplicity, we should remove alpha for beatgrid as well. I use it, because I like it more not that prominant. And we should remove most of the waveform render types as well, why so many. Let's go the gnome way and remove everything remotely useful and just force our view how things should look/feel on the user.

I seriously don't get why this 2 new settings are such a problem.

**Comment by poelzi** [comment]
@ronso0 please read the patch and the description, has 0 todo with high contrast mode at all.

**Comment by ronso0** [comment]
> This way you can easily see, where the baseline starts after a break. Something I have struggled with, multiple times.

This and the screenshot made me call it 'High Contrast' mode as you appearantly want to have a higher contrast between bands than current master delivers.

**Comment by poelzi** [comment]
No. It makes the alpha value that it hard coded in each renderer share a adjustable setting which is also a CO.
Some renderers already implemented something like that, but for the rest ones:
First it renders the waveform with the prefilter alpha value and without equalizer settings.
Then it renders with the normal alpha value waveform, this time with eq adjustment.
This is why the the waveform has bass kill on, but you still can see where the bass would be, if the filter was off.
This helps a lot getting the bass swap on the correct bar. I found myself quite often moving the volume down of the next track, just to reactive bass, because I lost track where the break ends and the next segment starts, super annoying.

**Comment by ronso0** [comment]
thanks for the explanation, I'll test this branch.
though I doubt anyone will map this to a controller. we should think about how to make this accessible in some. there however, I think discrete modes will fit much better than a slider or knob, more something like an EQ Kill button per channel.
Or just draw the outlines of the bass band for example.

**Comment by Holzhaus** [comment]
> Or just draw the outlines of the bass band for example.

I think it might be feasible to do this unconditionally, without the need to make this an option or CO. But it probably needs testing to check if this works for all use cases. @poelzi would that work for you, too? 

> And we should remove most of the waveform render types as well, why so many. Let's go the gnome way and remove everything remotely useful and just force our view how things should look/feel on the user.

TBH, I thi k we should hide the redundant waveform renderers by default, and use GL/GLSL/CPU rendering depending on what is available.

And I do think the GNOME devs do have a point to some degree: adding config options makes stuff harder to grasp for the user, and possibly creates a worse out of the box experience. First, we should think hard about how to create the best experience for every user without the need to configure something. Only if we conclude that there users have clashing requirements that make this impossible we should consider a config option.

**Comment by ronso0** [comment]
I tested this and I could only see a notable effect with the RGB(GL+GLSL) and Filtered(GL) renderer:
with RGB I could see a difference with the bass band, with Filtered I could see some effect at the highs.

I did not find the balance to use this permanently and I don't imagine anyone would open the preferences during when mixxxing.
That said I still think the only way to make use of the controls is either by mapping a controller knob to affect both Waveform & Prefilter opacity, or by having a skin toggle that switches between two user presets: emphasis on waveform or pre-filter.

**Comment by poelzi** [comment]
I close this in favor of #3153 
Since adding 2 COs was to much, I wrote a new glsl shader that renders the waveform how I like it.

**Pull request closed without merging**
