### PR TITLE
fix library styles in 2.2

### PR DESCRIPTION
**Pull request by ronso0**
some labels and button borders in DlgRecording, DlgAutoDJ and DlgAnalysis were screwed up or offset.

**Deere & Shade**: adopt beatsize spinbox style for AutoDJ transition (I have the strange feeling I fixed this several times already...)
**LateNight**: add style for disabled buttons
**Tango**: make the scrollbars a bit wider

lib-fix_deere
lib-fix_shade
lib-fix_tango
lib-fix_latenight

### CODE REVIEW

**Comment by Be-ing** [comment]
LGTM with GNOME. Thanks for the polishing. :) It would be helpful to get a few more testers with different setups.

**Comment by ronso0** [comment]
> LGTM with GNOME. Thanks for the polishing. :) It would be helpful to get a few more testers with different setups.

Yup, it would be nice to have it confirmed it looks as above in Win/OSX as well!

**Comment by beenisss** [comment]
Looking good on macOS 10.13.6

**Comment by Be-ing** [comment]
Thanks. Could we get someone to test on Windows? @JosepMaJAZ?

**Comment by JosepMaJAZ** [comment]
Looking good here (heh.. I haven't used much the AutoDJ recently so I wasn't even aware of that... maybe I saw it but I didn't pay attention)

**Comment by ronso0** [comment]
> I think unrelated to changes here but saw this

Yes, unrelated. Your screenshot indicates there's another font used instead of Open Sans (which is included in Mixxx). I'll have a look.

**Comment by ronso0** [comment]
Should look like below. Note different letter spacing, also how C and S look like.
opensans
Which version and OS are you using?

**Comment by radusuciu** [comment]
Windows 10, with the build artifact from this PR. I can install from stable and beta to see if issue persists.

**Pull request merged**
