### PR TITLE
GH Actions: use Ninja CMake generator

### PR DESCRIPTION
**Pull request by Be-ing**
It is faster than the defaults.

### CODE REVIEW

**Comment by Holzhaus** [comment]
We'll use ninja for MSVC builds. I think we should still use makefiles on Ubuntu, to make sure everything is tested properly.

**Comment by Be-ing** [comment]
> We'll use ninja for MSVC builds

Well, it seems we'll have to add Ninja to the Windows build environment then. GitHub Actions doesn't include it in their VMs for any OS.

**Comment by Holzhaus** [comment]
> > We'll use ninja for MSVC builds
> 
> Well, it seems we'll have to add Ninja to the Windows build environment then. GitHub Actions doesn't include it in their VMs for any OS.

Yeah, taht would be good. Right now I need to `choco install ninja` to make it work.

**Comment by Be-ing** [comment]
This saves... a few seconds. Is it worth using a setup different from what most users and distributions will be using? :man_shrugging:

**Comment by Be-ing** [comment]
Why is Ninja necessary on Windows?

**Comment by Holzhaus** [comment]
> Why is Ninja necessary on Windows?

It's the preferred generator for CMake. The alternative would be using one of those weird multi-configuration Visual Studio generators. No idea if they work or how to use them properly.

**Pull request closed without merging**
