### PR TITLE
Prepare release candidate for 2.4.0

### PR DESCRIPTION
**Pull request by daschuer**
This removes the beta suffix from the Version creating a release candidate. 

After merging, we need to to a smoke test with all binaries.

More steps can be found here: 
https://github.com/mixxxdj/mixxx/wiki/Release-Checklist-2.4.0

### CODE REVIEW

**Comment by daschuer** [comment]
We really need to move on, 6 months delay is already quite long: 
This is the remaining list: 
https://github.com/mixxxdj/mixxx/milestone/15

The only open issue that might be a regression is this one: 
https://github.com/mixxxdj/mixxx/pull/12631

**Review by ywwg — APPROVED** [review]

**Comment by ywwg** [comment]
did you want this to be the last thing merged, or is it ok to merge more PRs after this one?

**Comment by daschuer** [comment]
We can still merge PRs after this is merged. However this should be the exception, because we then need to repeat smoke tests.

**Comment by daschuer** [comment]
My hope is to have this merged soon though.

**Pull request merged**
