### PR TITLE
Update controller mapping for Behringer DDM4000 mixer

### PR DESCRIPTION
**Pull request by git-developer**
This PR contains
* A fix for a bug that prevents the mixer to be completely initialized on startup
* Proper handling of mapping definitions with missing (falsy) MIDI address
* Consistent use of `null` instead of empty strings for intentionally missing values
* A `ParameterComponent` that is able to send correct output values for effect parameters
* Soft-takeover support for the `EnumEncoder` component
* Removal of redundant code
* Documentation fixes

The bug was really annoying and hard to detect: on startup, only a part of the mixer LEDs had the correct state. Some were on, but others were off unexpectedly. After a few hours of debugging, it turned out that the problem is the processing speed of the hardware mixer. When too many MIDI messages arrive in a short time, only a part of them is processed. My solution is a configurable throttling logic that delays component initialization. Users may disable the throttling or change the delay. 

The `ParameterComponent` is required to send proper output values for effect parameters. Some of them have unusual values ranges, e.g. flanger speed `[32..0,5]` in a non-linear manner. The `output()` function of the `Encoder` component is not prepared for this, it just multiplies this value with 127 and sends the result to the controller. The `ParameterComponent` uses the parameter (range: `[0..1]`) instead of the value, so the MIDI value is correct.

### CODE REVIEW

**Comment by git-developer** [comment]
Bug [#671277](https://bugs.launchpad.net/mixxx/+bug/671277) is related to the bug that I fixed by throttling.

**Review by Swiftb0y — COMMENTED** [review]
Since these are mostly changes to your library and the code quality is good, I suggest to just merge this. Objections, anyone?

**Comment by git-developer** [comment]
This issue should not be labeled stale.

**Comment by git-developer** [comment]
> Objections, anyone?

No objection from my side. Please do not mark this PR as stale.

**Comment by uklotzde** [comment]
> > Objections, anyone?
> 
> No objection from my side. Please do not mark this PR as stale.

The *stale* marker was added by a GitHub action.

@Swiftb0y Merge?

**Comment by Swiftb0y** [comment]
Sure

**Pull request merged**
