### PR TITLE
remove QtScript

### PR DESCRIPTION
**Pull request by Be-ing**
QScriptEngine has been removed from Qt 6. This feature is not used
by any skins (and AFAIK it never was). If we want a scriptable GUI
we should use QML.

### CODE REVIEW

**Comment by Holzhaus** [comment]
Maybe we should even target 2.3? Would be good if I didn't need to maintain a custom Qt5 installation...

**Comment by Be-ing** [comment]
No, 2.3 can't work with Qt 6 because of QGLWidget.

**Comment by uklotzde** [comment]
> No, 2.3 can't work with Qt 6 because of QGLWidget.

Doesn't matter, removing unused code is always acceptable.

**Review by uklotzde — APPROVED** [review]

**Comment by daschuer** [comment]
@demos (jclaveau): Has the "Modular" skin build on this. 
Maybe he can confirm if it is relevant for 2.3.

**Comment by Be-ing** [comment]
Not sorry, I don't care about maintaining unofficial skins. That's why they're unofficial.

**Comment by Be-ing** [comment]
I've never even heard of the "Modular" skin.

**Comment by Be-ing** [comment]
https://github.com/demos/developer_skins/tree/master/Modular

An unofficial skin in an abandoned repository that has no commits in 6 years? Are you serious? Please, someone press merge so we can get Mixxx building with Qt 6 in less than 7 years.

**Comment by daschuer** [comment]
I think you miss-read my comment. I was wondering if this PR is relevant for 2.3.

**Comment by uklotzde** [comment]
This change does not affect 2.3 as decided. LGTM

**Comment by uklotzde** [comment]
Let's release 2.4 shortly after 2.3 as soon as the remaining legacy issues have been fixed.

**Pull request merged**
