### PR TITLE
Deere: fix alignment of PFL buttons in 4 deck mixer when scaled

### PR DESCRIPTION
**Pull request by Be-ing**
Before (250% scaling):
deere-pfl-misaligned

After (250% scaling):
deere-aligned

### CODE REVIEW

**Comment by ronso0** [comment]
There's no gap between Pfl button and Vol fader handle anymore.
Could you also fix the xfader switches?

**Comment by Be-ing** [comment]
Fixed:
deere-vertical-spacing

**Comment by ronso0** [comment]
LGTM.

All those workarounds for https://bugs.launchpad.net/mixxx/+bug/1760516.
I don't have a clue how the skinning and scaling works, would be nice if someone would tackle this.

**Comment by Be-ing** [comment]
Thank you for review.

**Pull request merged**
