### PR TITLE
CMake: Fix Qt resource files with CMake 3.20

### PR DESCRIPTION
**Pull request by Holzhaus**
Fixes https://bugs.launchpad.net/mixxx/+bug/1921549.

### CODE REVIEW

**Comment by uklotzde** [comment]
Could you provide a short explanation what was wrong and how you fixed it?

**Comment by uklotzde** [comment]
Ok, the "how" is obvious, by inlining the code.

**Comment by Holzhaus** [comment]
I suspected somethings was wrong with the QRC file because according to the mixxx logs the resource dir is correct but the Qt Resource System still didn't find any resources.
Since I updated CMake 2 days ago to 3.20, I suspected that this was the root cause.

Before, we added a `mixxx-qrc` OBJECT target, then added the resulting objects to `mixxx` and `mixxx-test`. This is weird and apparently doesn't work with CMake 3.20. Instead, it now just adds the QRC file to the `mixxx`/`mixxx-test` target directly using `target_sources`. More straightforward and it works.

(We can't just add it to `mixxx-lib` because that would require using the `Q_INIT_RESOURCES` macro).

**Review by uklotzde — APPROVED** [review]
The new solution is simpler and easier to understand. Removing the remaining redundancy would require to fix mixxx-lib as the comment suggests. LGTM

**Comment by uklotzde** [comment]
Thank you for the quick fix!

**Comment by uklotzde** [comment]
Fortunately even Fedora f35/rawhide still uses 3.19.

**Comment by Holzhaus** [comment]
> Thank you for the quick fix!

I had to, otherwise I can't build Mixxx anymore 😜

**Comment by jospezial** [comment]
This change also fixed an issue with missing button icons that I had in Gentoo since 2 months with cmake-3.19.x.
Mixxx in fedora rawhide from rpmfusion package also has the missing button icons.

**Pull request merged**
