### PR TITLE
Upgrade bundled HIDAPI to libusb/hidapi v0.10.0

### PR DESCRIPTION
**Pull request by uklotzde**
HIDAPI has a new home and has also been updated recently. Fedora currently ships v0.9.0 (f33) and v0.10.0 (f34).

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Comment by daschuer** [comment]
Waiting for CI.

**Comment by uklotzde** [comment]
@Be-ing The macOS build failures in this PR could be an indicator that the caching on Travis is broken. I have no idea why this doesn't work.

**Comment by uklotzde** [comment]
Maybe not. It is complaining about a missing _NSAppKitVersionNumber symbol???

**Comment by uklotzde** [comment]
Next trial, now with AppKit dependency.

**Comment by uklotzde** [comment]
@daschuer @Be-ing Adding the missing dependency fixed the macOS build.

**Pull request merged**
