### PR TITLE
svg viewbox fix

### PR DESCRIPTION
**Pull request by m0dB**
Adjusted the Latenight palemoon and classic `btn__*.svg` so they render correctly on retina + some changes by @ronso0 to the qss files.

Almost all files were done automatically (with a perl script), multiplying the width and height by two and inserting viewBox with the non-multiplied width and height. The `btn__fx_selector_down.svg` and `btn__xfader_deck_*.svg` and `btn__xfader_aux_*.svg` were done manually.

This replaces https://github.com/mixxxdj/mixxx/pull/12364 and fixes https://github.com/mixxxdj/mixxx/issues/12361

### CODE REVIEW

**Comment by ronso0** [comment]
@Swiftb0y Do you have any idea why `eslint` kicked in?

It seems `github-labeler` also broke...

**Comment by JoergAtGithub** [comment]
Something really strange happend to my decks with this PR:

https://github.com/mixxxdj/mixxx/assets/64457745/cbd6c3b8-badd-4b9e-b8ff-ef3def2f9a2e

**Comment by ronso0** [comment]
Reverted in 2.4, no merging 2.4 to main (still building).

**Comment by ronso0** [comment]
@m0dB Please rebase onto 2.4

**Comment by ronso0** [comment]
and please pick c83b1257ae to fix the library radio buttons in Classic theme

**Comment by ronso0** [comment]
LGTM @100% on Ubuntu with Qt 5.12.8

**Comment by ronso0** [comment]
@m0dB Btw, how do Deere and Tango look like?

**Comment by m0dB** [comment]
Deere has only the sync master icon at non-retina resolution:

Screenshot 2023-12-08 at 16 57 35

Tango has more issues:

Screenshot 2023-12-08 at 16 56 21
Screenshot 2023-12-08 at 16 56 17


Screenshot 2023-12-08 at 16 56 50
Screenshot 2023-12-08 at 16 56 32
Screenshot 2023-12-08 at 16 56 28

If you can give me a list with the corresponding svgs files, I can run my script on them to see if it solves the issue without further tweaking.

**Comment by ronso0** [comment]
Sure, I was just curious because IIRC in Deere most icons were 48px or 32px squares. And in Tango they're all 1:1 (SVG:screen pixels).

**Comment by ronso0** [comment]
@JoergAtGithub This is looking good on Windows with both 100% **app scaling** and higher, and with Mixxx' scaling?

**Comment by JoergAtGithub** [comment]
There are scaling issues with CPU-Load-Meter (here 125% Windows Zoom):
grafik
With 175% Windows zoom this white bar on the right appears and the text looks strange:
grafik
150% Windows Zoom
grafik
100% Windows zoom + 400% Mixxx zoom looks fine:
grafik

Inverse Loop-In/Loop-Out marker icons in Palemoon seam to be the wrong ones
https://github.com/mixxxdj/mixxx/assets/64457745/7457a2e6-6789-4aee-a5e5-9d4f88a461d5

Otherwise all looks fine on Windows11.

**Comment by m0dB** [comment]
> There are scaling issues with CPU-Load-Meter (here 125% Windows Zoom):

I don't think that is related to this PR.

**Comment by ronso0** [comment]
> Inverse Loop-In/Loop-Out marker icons in Palemoon seam to be the wrong ones
https://github.com/mixxxdj/mixxx/assets/64457745/7457a2e6-6789-4aee-a5e5-9d4f88a461d5

Oh! I'll send a fix.

**Comment by m0dB** [comment]
> Inverse Loop-In/Loop-Out marker icons in Palemoon seam to be the wrong ones

Indeed, but also not due to this PR. But I will fix it here.

**Comment by m0dB** [comment]
> Oh! I'll send a fix.

Thanks, @ronso0 , I'll leave it to you!

**Comment by m0dB** [comment]
The issue with the OpenGL widget leaving this white border was already reported for the spinnies btw. Maybe this can be avoided by using only sizes that are multiple of 4? Or maybe we can set a different colour than white so it is not as noticable?

**Comment by ronso0** [comment]
Here it is: b83eb572887dbc40f868bdf2caa91d32e51e7969
I noticed that some files contain a few invisible objects. and many unused attributes.

**Comment by ronso0** [comment]
@m0dB when yo have picked that feel free to press merge yourself

**Comment by daschuer** [comment]
Did  you have an eye on these issues? 
grafik

The issue has changed compared to the #12364 version where an other icon was effected: 
grafik

Can we use the  #12364 version for the two? 

Did you onside the dark lower part of the numbers?  This is no mayor issue to me ..

**Comment by m0dB** [comment]
Not sure what goes wrong with the intro/outro icons, but I have recreated the end icons from the start icons. I can't check this myself, on retina they look fine.

**Comment by ronso0** [comment]
Thank you.
I think the intro/outro ramps are rendered like that because the angles are not 45° (the cathete ratio is 9/10), so it is somewhat random how the rounding is applied with fractional scaling.

**Pull request merged**
