### PR TITLE
Update mixxx_en_GB.ts

### PR DESCRIPTION
**Pull request by lxndrbe**
corrected italian wording in file

### CODE REVIEW

**Comment by ronso0** [comment]
IIRC we pull the translations from [transifex](https://www.transifex.com/mixxx-dj-software/) 
I already removed the italian parts there recently.

**Comment by Holzhaus** [comment]
Does it hurt to merge this until someone find the time to pull the latest translations into this repo? I'm not familiar with the process, so I don't know.

**Comment by alasdairmoons** [comment]
Maybe it would be a good idea of reworking the translation part.
There are a lot of triple entries for one and the same language (also in 2.2.x)
I reported this at https://bugs.launchpad.net/mixxx/+bug/1888486

**Comment by uklotzde** [comment]
We should not modify files manually that are generated by Transifex. All fixes will be lost with the next pull from Transifex.

**Comment by Holzhaus** [comment]
Alright, then I'll close this and hope that someone who is familiar with the process pulls the latest translations from transifex.

**Pull request closed without merging**
