### PR TITLE
Merge in changes from 2.4

### PR DESCRIPTION
**Pull request by ywwg**
I have not done this in a while so I might not have done it right

### CODE REVIEW

**Comment by ronso0** [comment]
IIRC issues only arise from wrongly resolved conflicts, and it helps tracking those by uncommenting the respective lines in the commit message editor.
Were there any conflicts?

**Comment by ywwg** [comment]
there was only a conflict in mixxx metainfo, which was automatically updated anyway.  Otherwise totally clean

**Comment by ronso0** [comment]
Well then, CI is all green. No need to check every commit, no? :man_shrugging:

**Comment by daschuer** [comment]
Yes, no need to check. I will merge this now let's see what happens. Next time you can push it directly.

**Pull request merged**
