### PR TITLE
Preferences: simplification & layout fixes

### PR DESCRIPTION
**Pull request by ronso0**
* remove the useless groupbox in Colors
* group Interface options (Skin + Misc)
* simplify Skin layout (needs less h-space, window can be smaller)

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
Looks good. Thank you for this nice improvement.

**Comment by ronso0** [comment]
Thanks. Follow-up is #12057

**Comment by daschuer** [comment]
Is this a regression from this PR? 
Do you have an idea where this icon is coming from?

**Comment by ronso0** [comment]
wrong PR, you meant to post in #12424 
(no, that was 2.4-beta I fetched earlier)

**Comment by daschuer** [comment]
Yes wrong PR, sorry.

**Pull request merged**
