### PR TITLE
Master

### PR DESCRIPTION
**Pull request by MythicPalette**
I made some changes to the base skins to contain dynamic decks, waveforms, and mixers. The overall idea is that you set your skin to 4 decks (like this https://prnt.sc/vefnkh ) Then enable the dynamic elements which will give them the appearance of having 2 decks (like this https://prnt.sc/vefo28 ) which means less screen real estate taken by your decks and waveforms while still allowing you to actively use the four decks on a controller. I personally use 3 and 4 for scratch tracks and the like so it's nice having them at the ready when I want them.

These custom skin versions have a hook that can be used in controller mapping scripts like my custom Numark Mixtrack Platinum script's function for pushing the deck switch button (button: https://prntscr.com/vb26nq ) ( script example: https://prnt.sc/vefowf ). When these values change in the skin then the skin itself changes to show the active deck/waveform/mixer channel. (Deck 1 active: https://prnt.sc/vefqzr ) (Deck 1 inactive: https://prnt.sc/vefr6m ) When deck one deactivates it changes the deck on the left side from showing deck 1 to deck 3 (Note that deck3_active and deck4_active are unused in this example, however I feel that having a variable for each active deck in the script allows for skin creators to have more flexibility in design). 

I'm hoping that by updating the skins like this, maybe creators of other mappings will be able to update their mappings to support this feature as well. If not, incorporating the feature into mappings is easy enough and I'd be happy to help with that process when and where I can.

[skins.zip](https://github.com/mixxxdj/mixxx/files/5499445/skins.zip)

I just accidentally messed this whole thing up I think... I didn't mean to tag anyone else's commits. Sorry about that. Not used to using git and I was trying to create my own little thing for the skins and here we are. Hopefully I didn't mess anything up too badly...

### CODE REVIEW

**Comment by daschuer** [comment]
I have not yet understand what is the essence of the change you are proposing. We can already use 4 Decks, even if you switch the skin to 2 Deck mode.

Can you add a step by step story, how you work with it and what Mixxx does/shows?

**Comment by daschuer** [comment]
To fix git do these steps from your git console in your working directory:
(Make sure you have a backup in case something goes wrong)

```
git checkout -b dynamic_decks
```

Copy the intentionally changed files from you zip archive to you working copy.
If you have created new files copy them as well and make git aware of them by.

```
git add pathtofile
```

Than commit you changed to you local repository:

```
git commit -a -m"put your commit message here"
```

Than push your changes to Github:

```
git push -u origin dynamic_decks
```

On GitHub you can now create a new pull request and close this one.

**Comment by daschuer** [comment]
For more Infos start reading here:
https://github.com/mixxxdj/mixxx/wiki/bugfix_workflow

**Comment by LadyDefile** [comment]
https://github.com/mixxxdj/mixxx/wiki/bugfix_workflow takes me to "Create new page". I don't have a Git console, it's not something I've ever used before honestly aside from uploading files to share with people in the past, I've never worked on someone else's code and every bit of research I do has gotten me nowhere.

To answer your question 

> I have not yet understand what is the essence of the change you are proposing. We can already use 4 Decks, even if you switch the skin to 2 Deck mode.
> 
> Can you add a step by step story, how you work with it and what Mixxx does/shows?

https://youtu.be/zVocq6VQ6U4 This should clearly demonstrate what I mean.

**Comment by LadyDefile** [comment]
Doing some studying up on Git because apparently it's easy to accidentally do a pull request on someone else's commits.

**Comment by Holzhaus** [comment]
Here's the correct link: https://github.com/mixxxdj/mixxx/wiki/Bugfix%20Workflow#issue-a-pull-request

**Comment by LadyDefile** [comment]
I think I did it correctly now. I created a fork and then did a pull request on that.

**Comment by Holzhaus** [comment]
I'll close this one then.

**Comment by LadyDefile** [comment]
Thanks.

**Pull request closed without merging**
