### PR TITLE
LateNight :: fix overlapped effect selector + other small fixes

### PR DESCRIPTION
**Pull request by ronso0**
Fixes https://bugs.launchpad.net/mixxx/+bug/1760402 (overlapping Meta knob)
and https://bugs.launchpad.net/mixxx/+bug/1758552 (skin warning about missing icon files).
Fixes inverted Aux play button

I made the EffectSelector smaller but let it expand when the screen allows. In order to make the effect list fit at minimum width I applied negative margin to it. Tested with 100% and 200% on Linux.

latenight-responsive-effectselector

latenight-effectselector-crop-fix

With collapsed units, components-js allows to show focus buttons (I use it to work around https://bugs.launchpad.net/mixxx/+bug/1760316). In that case the EffectSelector would be overlapped again by Meta knob. Focus button is now below effect enable button

latenight-stacked-focus-button

### CODE REVIEW

**Comment by Be-ing** [comment]
I'll try to borrow a new Macbook with a Retina screen tomorrow to see if the checkmark issue is fixed.

**Comment by Be-ing** [comment]
LGTM on GNU/Linux (3840 x 2160 @ 250%) and macOS (1440 x 900 @ 100%).

**Comment by Be-ing** [comment]
Could you add an option for 4 effect units to LateNight?

**Comment by ronso0** [comment]
> Could you add an option for 4 effect units to LateNight?

Nope. The time I have for Mixxx I'd rather use to fix https://bugs.launchpad.net/mixxx/+bug/1760229 for Deere & Shade as well

**Comment by Be-ing** [comment]
I will borrow my friend's newer 2016 Macbook again to work on 
https://bugs.launchpad.net/mixxx/+bug/1760229

**Comment by ronso0** [comment]
Do you want to fix the root of the issue or just work around it?
Workaround is #1581

**Comment by Be-ing** [comment]
Now is the time for quick workarounds

**Comment by ronso0** [comment]
Thought maybe you'd already an idea what's up..

**Comment by beenisss** [comment]
Screenshots with the updated LateNight skin, first one is at minimum window size, second one normal size:

screen shot 2018-04-02 at 19 54 25

screen shot 2018-04-02 at 19 55 13

**Comment by Be-ing** [comment]
@beenisss please test #1582.

**Pull request merged**
