### PR TITLE
lp1956144 prevent segmentation fault when using midi.sendShortMsg and platform vnc.

### PR DESCRIPTION
**Pull request by admindotnu**
When starting mixxx from the command line, and using -platform vnc. midi.sendShortMsg is resulting in a segmentation fault. This is because of the used triggerActivity() function to bump the x11 screensaver timer to prevent the sceensaver to popup.

Workaround is to check the platform, and if its vnc, skip the triggerActivity() function.

### CODE REVIEW

**Comment by Holzhaus** [comment]
Thanks for submitting a patch. 

Unfortunately, this will make an expensive string comparison on every single received MIDI message.

If we want to add this workaround it should be added to the Screensaver inhibitor, where this check can be done once during startup, not every time the controller sends a packet.

**Comment by admindotnu** [comment]
Thanks for the feedback, understand and agree on what you are saying.

I dont have the right experience to make such patch.

**Comment by Holzhaus** [comment]
Could you check if the crash is fixed if you replace lines 177-178 in `src/util/screensaver.cpp` with:

```cpp
if (display != nullptr) {
 ​    ​XResetScreenSaver​(display); 
 ​    ​XCloseDisplay​(display);
}
```

**Comment by admindotnu** [comment]
Just recompiled, looks like your change is working too.

**Comment by Holzhaus** [comment]
> Just recompiled, looks like your change is working too.

Alright, can you update the PR? You do that with `git commit --amend` and then `git push origin lp1956144 --force`.

**Comment by Holzhaus** [comment]
Also, please rebase on the `2.3` branch and edit the target branch of this PR:

https://github.com/mixxxdj/mixxx/wiki/Using%20Git#targeting-another-base-branch

**Comment by admindotnu** [comment]
I think its right now, same bug also appears in the main branche.

**Comment by Holzhaus** [comment]
>> Also, please rebase on the `2.3` branch and edit the target branch of this PR:
>> 
>> https://github.com/mixxxdj/mixxx/wiki/Using%20Git#targeting-another-base-branch
>
> I think its right now, same bug also appears in the main branche.

You didn't rebase yet, can you please run:

```
git fetch upstream
git rebase --onto upstream/2.3 upstream/main lp1956144
```

And then force-push again.

**Comment by ronso0** [comment]
...and then squash those 3 commits?
And choose a more compact commit message?

Simply run
`git rebase -i upstream/2.3`

This will give you an editor view similiar to this with an explanation underneath
```
pick fafcefd5e9 librarycontrol: revise focus control
pick 6352881e4d librarycontrol: use FocusWidget for MoveVertical & GoToItem, revise emitKeyEvent
pick ed172faa47 librarycontrol: consolidate move.. and scroll.. functions
```
At the top is the first (oldest) commit. In that line, replace `pick with `r` or `reword`.
For all commits below you can replace `pick` with `f` or `fixup`. This will ammend them into the first commit and drop their messages.
Now press the key combo labeled "Exit".
Now you get an editor view again and the chance to reword the first commit's message.
git will do its thing and print "Successfully rebase ..." in the terminal.

**Comment by daschuer** [comment]
The rebased branch is here: https://github.com/mixxxdj/mixxx/pull/4635

**Pull request closed without merging**
