### PR TITLE
Shade :: more descriptive labels for Hotcue-Intro/outro toggle

### PR DESCRIPTION
**Pull request by ronso0**
shade-hotcue-intro-toggle

~~icons that describe the actual toggle behaviour better than +/- and the green highlight before~~

Adds a button to toggle between previous hotcues 1-4 and an additional tray with hotcues 1-8 below and in/outro cues instead

### CODE REVIEW

**Comment by daschuer** [comment]
I am unsure if the whole toggle concept fits.
The hotcue buttons are needed during performace. Do we need the intro autro buttons as well? At least not all of them.
If not, they should not clutter the collappsed interface and should go to the hotcue region.

**Comment by ronso0** [comment]
hmm.. I think in the compact Shade design this is a good way to have both.
AFAIK we don't have a mapping that suppports Intro/outro cues  and they are needed in a prep session only, therefore I think it's okay to have either Hotcues or Intro cues visible and switch between them with the mouse.

Currently, not other way comes  to mind to have them both in a nice & accessible way.

**Comment by daschuer** [comment]
One Idea is to add a expandable "Cue" Tray, that allows to access Hot-Cues 5..8 and the new intro cues. 

I have not much experience with these buttons though. What are the use cases during a gig? 
I can imagine that jumping to intro_start and intro end might be useful if the CUE is lost. 

I have no use case for outtros though. 

So how about having hot cue 1 / 2 intro_start / intro end always visible and move the rest to a new tray?

**Comment by daschuer** [comment]
I never use >> and << by the way, only right click to << for seek to start. This can be replaced with into start and stop IMHO.

**Comment by ronso0** [comment]
> What are the use cases during a gig?

can't think of any. as I assume they're not mapped to controllers users would need to use the mouse, and then they're better off quickly dragging the playpos on the overview.

same appplies to seek buttons. I think you're right they can be removed.
we should keep reverse/reverseroll, so I don't see how we can make space to host more hotcues, I'd rather put the beatjump buttons above reverse.

**Comment by ronso0** [comment]
How do you like this as temporary solution?
shade_backforw

**Comment by ronso0** [comment]
We can also add the seek buttons to the beatjump tray so they're still in the skin

**Comment by uklotzde** [comment]
@daschuer Your feedback on the latest changes? Ready to merge?

**Comment by ronso0** [comment]
@daschuer the last commit adds the extra row with hotcues 1-8 like you proposed

HOTCUE / IN-OUT toggle switches between
* hotcues 1-4
* in/outro cues + hotcues 1-8 below

shade_newcuetray

**Comment by daschuer** [comment]
Thank you for the update and sorry for ignoring this PR so long. 

I think this is now heading in a good direction. Playing with I have found it confusing that the last for buttons are altering functions.  
However this is a good feature to either prepare a track and on the other hand have the four hot cues available during performance. 

I think we should merge this and wait for other critics. 

Thank you for taking care.

**Comment by ronso0** [comment]
> I think this is now heading in a good direction. Playing with I have found it confusing that the last for buttons are altering functions.

you mean that there are intro cues instead of hotcues after toggling?
this way it's more consistent IMO, than splitting hotcues 1-4 / 5-8 into different sections

**Comment by daschuer** [comment]
Yes, you are right. It is Ok for me.

**Pull request merged**
