### PR TITLE
Deere :: enlarge fx toggles

### PR DESCRIPTION
**Pull request by ronso0**
Recently, I used Deere for the first time with 4 fx units and controller and I found it quite difficult to read the fx enable status at a glance as both the Meta knobs and the toggles are blue.
This enlarges the fx toggles.

Btw, I'd really love to implement the EffectSelector 'hack' from Tango (minimal combined toggle and drop-down) in the EffectSelector widget but am still lacking the skills to do so.

this PR / master
deere-fx-coll

deere-fx-exp

### CODE REVIEW

**Comment by ronso0** [comment]
@Be-ing Any objections? Or do you have another idea how to improve the current situation?

**Comment by ronso0** [comment]
*pling*

**Comment by ronso0** [comment]
just noticed some ugly drawbacks with expanded units :man_facepalming: 
I'll try to make the enable buttons expand vertically there.

**Comment by ronso0** [comment]
I improved expanded units, too, and updated the screenshots in the 1st post.
empty and loaded slots are equally sized and aligned now.
Ready to merge IMO

**Comment by ronso0** [comment]
ping.
anynone likes to test this?

**Comment by uklotzde** [comment]
LGTM. Thank you for both your work **and** patience!

**Pull request merged**
