### PR TITLE
Update pre-commit config

### PR DESCRIPTION
**Pull request by uklotzde**
pre-commit autoupdate

### CODE REVIEW

**Comment by Holzhaus** [comment]
Thanks. 

The checks on this PR only run pre-commit against the diff, so only the YAML file is checked. For example, when `black` is updated the formatting rules may slightly change and cause reformattings in our python files.

Did you run this locally with the command line we use on CI to verify that this is not the case?

**Comment by uklotzde** [comment]
No changes: `SKIP=end-of-file-fixer,trailing-whitespace,clang-format,eslint,no-commit-to-branch pre-commit run --all-files`

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you!

**Comment by Holzhaus** [comment]
Should be backport this to 2.3? It won't make a difference for the user but we avoid introducing code with wrong formatting/typos in a 2.3.x release that causes problems when we merge 2.3 into main.

**Comment by uklotzde** [comment]
Rebased onto 2.3

**Pull request merged**
