### PR TITLE
pre-commit: Install clang-format dependency automatically

### PR DESCRIPTION
**Pull request by Holzhaus**
Should fix: https://github.com/mixxxdj/mixxx/pull/2464#issuecomment-604561887

### CODE REVIEW

**Comment by ronso0** [comment]
thanks, fixes the clang-format issues.

**Comment by Holzhaus** [comment]
If it works, please merge ;-)

**Comment by ronso0** [comment]
okay.
eve tnough it works for _me_ I was hesitating because I have _no idea_ what's possibly affected by the change.

**Comment by Holzhaus** [comment]
I uninstalled git-clang-format and clang-format and it worked for me, too.

**Pull request merged**
