### PR TITLE
Add extra_metadata flag

### PR DESCRIPTION
**Pull request by Holzhaus**
Adds an additional build flag and enable it for CI builds to ensure that there are no build-time errors in @uklotzde's metadata code.

### CODE REVIEW

**Comment by uklotzde** [comment]
I'm still thinking about how to achieve this without exposing a new, public feature flag that doesn't have an actual use case, yet. It might be confusing. If we decide to do it this feature flag should not only be declared as *experimental* but also as *internal* to prevent repo maintainers from enabling it!

**Comment by uklotzde** [comment]
Until then #2282 is continuously built and tested with `__EXTRA_METADATA__` enabled to verify correctness.

**Comment by Holzhaus** [comment]
Ok, if you think this is not necessary I'll close this for now.

**Comment by uklotzde** [comment]
We might have an actual use case soon: https://github.com/uklotzde/mixxx/tree/acoustidclient2
But this is still blocked by pending PRs.

**Comment by uklotzde** [comment]
...addressing https://bugs.launchpad.net/mixxx/+bug/1581256

**Pull request closed without merging**
