### PR TITLE
Remove else branch in SyncControl::setMasterBpm, fixing lp1783020

### PR DESCRIPTION
**Pull request by daschuer**
https://bugs.launchpad.net/mixxx/+bug/1783020

### CODE REVIEW

**Comment by daschuer** [comment]
Who is able to review and test this trivial PR?

**Comment by Be-ing** [comment]
Can you elaborate on how this changes the behavior of sync with tracks that don't have a beatgrid? Does removing this make sync do nothing for tracks without a beatgrid? Do you have any ideas why that code was there in the first place? Maybe @ywwg can comment on that?

**Comment by daschuer** [comment]
Without the change, sync resets to original rate, now sync is ignored. 
I assume this branch was introduce to fix a div by zero situation. 
See also https://bugs.launchpad.net/mixxx/+bug/1783020

**Comment by daschuer** [comment]
Can we merge this now?

**Comment by daschuer** [comment]
@ywwg Can you have a final look?

**Comment by ywwg** [comment]
Can we add a test case for this?  It should be fairly straightforward to create a new one based on the existing tests:

1. Load a track with beatgrid
2. Load a track without beatgrid
3. Enable sync on both decks
4. Adjust rate on both decks
5. adjust rate on deck with grid
6. confirm that rate on other 

deck doesn't change


Change looks good!
the test should fail before this change and succeed after.

**Comment by daschuer** [comment]
Done!

**Comment by rryan** [comment]
LGTM. I did some code archaeology and I think this is my fault :( sorry.

https://github.com/mixxxdj/mixxx/commit/2769df30681c313fe33ea54496e9293f1cc8672f

**Comment by rryan** [comment]
There's no good reason I can think of for why I added the else branch -- I was probably just like "well, if the bpm is zero then the rate slider should be zero" without really thinking.

**Pull request merged**
