### PR TITLE
Safeguards for TrackModel inheritance hierarchy

### PR DESCRIPTION
**Pull request by uklotzde**
Just minor syntactic stuff, no functional changes (yet):
* Decorate inherited functions with override/final keywords
* Remove redundant class members
* Hide internal constants

### CODE REVIEW

**Comment by rryan** [comment]
Thanks @uklotzde -- could you say a bit more about the direction you're headed in here? I think you were saying something about changing the DAO structure?

**Review by rryan — COMMENTED** [review]
I wasn't a giant fan of the member-variable references but this change does add a lot of noise by always going indirectly at the DAO through the TrackCollection. Is there a particular reason you decided to do that or is it preference?

**Comment by uklotzde** [comment]
We could add the corresponding getters to the base and that simply forward 
to m_pTrackCollection? That would avoid the additional noise and the base 
class stays in control. I don't like those references stored in each derived 
class decoupled from TrackCollection, because their lifespan and close 
relation to TrackCollection is hidden.

Future: All write (non-const) operations on the database must be handled and 
managed by TrackCollection that is responsible for the coordination and 
consistency between the various DAOs. TrackCollection should only provide 
const-references (or a limited read-only interface) to the internal DAOs as 
a shortcut for invoking read operations directly. The new crate DAO for 
example does neither send nor receive any signals, all this is managed by 
TrackCollection.

**Comment by rryan** [comment]
> We could add the corresponding getters to the base and that simply forward
> to m_pTrackCollection?

No big deal, just wondering.

**Comment by rryan** [comment]
Pending Travis/Appveyor, LGTM

**Comment by daschuer** [comment]
Thank you for this PR. 

IMHO the ideas outlined in Nazars branch, moving the TrackCollection in its own thread are still valid. Also the ideas of using lambda expressions to execute callers logic in a thread is still valid. How do you think about it? 

If we heading in this direction the m_pTrackCollection->getPlaylistDAO() calls are a good first step. 
Later we can split these calls into a main thread API and a TrackCollection thread API, to hide the lambda invocations from the users code. 

It would also be a good idea to distinguish calls that requires a result like get... , from calls that can be scheduled somehow decoupled.

**Comment by uklotzde** [comment]
Of course, asynchronous database access is my long-term objective, too!! The 
UI freezes when accessing the library are inacceptable.

But first we need a solid foundation of independent, isolated components 
(thinking in terms of microservices, at least adopting some principles) with 
less coupling and dependencies than what is found now. The potential thread 
boundaries have to be revealed before actually separating the components and 
placing them on different threads. Otherwise we will end up with a brittle 
and unstable result, suffering from deadlocks and data inconsistencies. 
Separation becomes much easier if operations have no (or at least very few) 
side effects and if the the components don't reference and call each other 
vice versa in uncontrollable ways.

**Comment by rryan** [comment]
+1 to the principles you're aiming for here. This PR discussion isn't the place for it but I think it might be useful to have a high level design doc or plan with examples of what interacting with the library would look like to client code in the end-state of your plans.

IMO Nazar's design was somewhat of a leaky abstraction with the lambdas, though it was very flexible because you could do whatever you wanted in the lambda.

**Pull request merged**
