### PR TITLE
Allen & Heath Xone K2 QuickEffect and sync changes

### PR DESCRIPTION
**Pull request by Be-ing**
Working on #2618, I wanted a way to use the QuickEffect superknob from my Xone K2. I took a [suggestion from the forum](https://mixxx.org/forums/viewtopic.php?p=42801#p42801) to use shift + low EQ knob. The simple implementation of this was cumbersome to use because the shift button had to be held down the whole time the QuickEffect superknob was in use. I made it so if the knob is turned for the QuickEffect superknob while shift is pressed, it does not go back to the low EQ knob when shift is released; it goes back to the low EQ knob the next time shift is pressed. This allows for using the QuickEffect superknob with one hand and using the other hand for another control.

I have implemented shift + top encoder press to toggle the QuickEffect enable button. Supershift + top encoder turn scrolls through the effect chain presets for the QuickEffect (this is not useful without #2618).

I rearranged other mappings for the top encoder to make sync easier to use. Now pressing the top encoder without shift toggles sync. Turning the top encoder without shift does jogging, and I increased the sensitivity of this. Gain is still accessible with shift + top encoder turn, but I got rid of the reset gain button because it's redundant with the gain knob. I also made supershift + top encoder press reset the tempo.

@poelzi could you test this with #2618?

### CODE REVIEW

**Comment by Holzhaus** [comment]
@poelzi ping

**Comment by Holzhaus** [comment]
This needs #2618 to be merged first, right? I'll convert this to draft for now.

**Comment by Be-ing** [comment]
The `chain_selector` ControlObject is new in #2618, but everything else in this PR works without that. If you prefer I can move that change to another branch.

**Comment by Be-ing** [comment]
I have been using this for a little while now and I am happy with the changes. Since no one has reviewed this, I'll merge it in a few days unless someone has anything to say.

**Pull request merged**
