### PR TITLE
Update Changelog for 2.4

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by Swiftb0y** [comment]
please rebase on main so ci works again

**Comment by daschuer** [comment]
Done

**Comment by daschuer** [comment]
@Holzhaus There seems to be still an issue with the timestamp. Can you have a look?

**Comment by Holzhaus** [comment]
Is this based on latest main? It will always use the latest commit date of the most recent change of the changelog file.

I suppose you need to run `pre-commit run --from-ref HEAD~1 --to-ref HEAD` manually after modifying the changelog file. Because thr hook runs before committing, and during the commit the timestamp changes.

Sorry, but I see no other way to handle this. I think we need to think about removing the appstream metainfo from the repo and instead generate it on the fly during packaging. Then, we just use the current time which is not only easier but also more correct.

**Comment by daschuer** [comment]
It is still failing :-(

**Comment by daschuer** [comment]
So I cannot squash the commits, right?

**Comment by daschuer** [comment]
I have now changed the update_metainfo.py in a way that is picks the commit before the changes form the change log. 
That should work on CI and local in the same way, because the parent commit is the same in both cases. 

It is also not to bad to use this date because that is the last change on the Mixxx source excluding CHANGELOG.md. 

@Holzhaus 
That do you think?

**Comment by daschuer** [comment]
Hey pre-commit is green.

**Review by ronso0 — APPROVED** [review]
Changelog LGTM

What about metainfo.py @Holzhaus ?

**Comment by daschuer** [comment]
Conflicts resolved! Merge?

**Comment by ronso0** [comment]
Changes LGTM, though macOS CI is failing.

**Pull request merged**
