### PR TITLE
Escape characters in mountpoint metadata sent to server.

### PR DESCRIPTION
**Pull request by kevinwern**
For odd case that the mountpoint contains querystring characters.
Note that this is not truly supported by IceCast2 servers
out-of-the-box, as the pages construct admin pages and filenames with
the unescaped source.

Also, shout_set_mount does not detect the first slash in a mount point
if it is encoded, so remove the initial slash before doing any work on
the string.

### CODE REVIEW

**Comment by kevinwern** [comment]
Thanks for the feedback, Uwe!  Just updated and tested.

**Comment by kevinwern** [comment]
Sorry, another project I work on uses 2 spaces...

Also deleted a .swp I stupidly included in the commit.  I could put that (and all .sw* files) in .gitignore if you think that might be helpful to other developers

**Comment by sblaisot** [comment]
Do not include .swf in .gitignore, this could be a flash file ;)

**Comment by kevinwern** [comment]
https://github.com/github/gitignore/blob/master/Global/Vim.gitignore

I figure this might be a good template

**Comment by sblaisot** [comment]
Oh,  I mean don't ignore *.swf but you can safely ignore dot file .swf ;)

**Comment by uklotzde** [comment]
LGTM.

Note: I'm assuming that the strings returned by ConfigObject::getValueString() are already trimmed.

Git: Before merging this branch I would recommend to correct the first commit with an interactive rebase by applying "Delete .engineshoutcast.cpp.swp" as a fixup (git rebase -i).

**Comment by daschuer** [comment]
This patch produces a valid URL, but seams not to be a valid solution due to the leak of libshout support. 
See discussion https://bugs.launchpad.net/mixxx/+bug/1329202

**Comment by kevinwern** [comment]
Closing this PR as per discussion:
https://bugs.launchpad.net/mixxx/+bug/1329202/comments/31

**Comment by rryan** [comment]
Thanks for working on this Kevin!

**Pull request closed without merging**
