### PR TITLE
Cmake 1.15 onyl for Apple

### PR DESCRIPTION
**Pull request by daschuer**
This fixes the build failure on Raspbian, reported here: https://github.com/mixxxdj/mixxx/pull/3645#issuecomment-784066395

### CODE REVIEW

**Comment by Holzhaus** [comment]
I'm against this. People use Raspbian because they want "stable" old software, which is obviously incompatible with building an up-to-date mixxx. If they really want to, there are prebuilt aarch64 binaries available on the CMake website. The alternative is to just use an up-to-date distro such as Arch Linux ARM.

Yes, this hack is small, but if we keep adding workarounds and exceptions we'll end up with an unmaintainable mess.

**Comment by daschuer** [comment]
It is also a high value that things works out of the box. 

@moretocome: 
It this the only thing that fails if you start from a fresh Raspbian or are there anyway other requirements missing. 
If the later is the case cmake would just be an additional point on the list.

**Comment by Be-ing** [comment]
Doesn't our PPA work for Raspbian? If so, I don't think there's a need for this hack.

**Comment by daschuer** [comment]
The alternative would be to copy the library without symlinks. We don't use them anyway.  

Or guard the FOLLOW_SYMLINK_CHAIN parameter directly.

**Comment by Be-ing** [comment]
AAC recording continues to work with macOS with this.

**Pull request merged**
