### PR TITLE
fix(ci): pre-commit on CI and bump actions versions

### PR DESCRIPTION
**Pull request by Swiftb0y**
Lets see if this works.

### CODE REVIEW

**Comment by Swiftb0y** [comment]
Well. Ok simply updating the CI should work. Seems to be some dependency used by pre-commit raised their minimum version requirements. I now just need to figure out how to update the mixxx-docker-ci container to a version that has distlib 3.5.0. @Holzhaus mind giving me a hand? I'm not very familiar with docker and docker hub. The current image just contains distlib 3.4.0.

**Comment by Swiftb0y** [comment]
Soo... basically the transient dependency virtualenv bumped their dependencies a couple hours ago https://github.com/pypa/virtualenv/pull/2394 which included a bump to distlib-3.5 which was released less than a month ago. So thats why neither ubuntu-latest (2.3) nor arch (snapshot from 2 months ago) carries that dependency.
So the way forward here IMO is updating our 2.3 pre-commit CI with the same config as main (since those diverged for some reason?!) and update the docker container which both use.

**Comment by Holzhaus** [comment]
Weird that `virtualenv` is still a thing, when `venv` has been part of the std library for years.

Anyway, updating docker is pretty easy. Just clone https://github.com/Holzhaus/mixxx-CI-docker and update the `Dockerfile`. Arch is rolling release and always has the latest software, so maybe it's not even necessary to make any changes to the `Dockerfile` at all.

In any case, you need to rebuild the docker image (`docker build -t some-tag .`) and then [push it to docker hub](https://www.devguides.dev/how-to-push-docker-image-to-docker-hub/), then update the GitHub workflow file.

I can take care of this, but it probably makes sense to reduce the bus factor and have multiple people that know how to do this.

**Comment by Swiftb0y** [comment]
unfortunately ubuntu-22.04 doesn't ship a new enough distlib version either. So I don't see a reason for using that instead of the docker container. But updating that requires action from @Holzhaus

**Comment by Holzhaus** [comment]
Btw, as a quick fix have you considered using `sudo python -m pip install -u distlib==0.3.5` on CI? I wouldn't do this on my local machine because it circumvents the package manager, but for CI it's okay I guess.

**Comment by Swiftb0y** [comment]
Thanks for responding. I figured out how to publish a docker image, but the problem was that I obviously can't push to your account. As pointed out, you probably just need to tag a new release and upload that. Should we make a collective mixxx account on docker hub that multiple core-team members can have access to?

**Comment by Swiftb0y** [comment]
> Btw, as a quick fix have you considered using `sudo python -m pip install -u distlib==0.3.5` on CI? I wouldn't do this on my local machine because it circumvents the package manager, but for CI it's okay I guess.

Thats already what pip is trying be default but it fails because it can't uninstall the distlib version installed by the system package manager.

**Comment by Holzhaus** [comment]
There's no need to push to my account, you can just push to your own account and then reference it instead of mine in the GitHub workflow file ;-)

And yeah, a Mixxx org docker account would probably a good idea. But that can be taken care of indepently, no need to delay this.

**Comment by Swiftb0y** [comment]
> There's no need to push to my account, you can just push to your own account and then reference it instead of mine in the GitHub workflow file ;-)

Sure... but it doesn't really solve the issue either. Also I don't have a docker hub account :sweat_smile: 
So can you take care of updating the container right now?

**Comment by Holzhaus** [comment]
> > Btw, as a quick fix have you considered using `sudo python -m pip install -u distlib==0.3.5` on CI? I wouldn't do this on my local machine because it circumvents the package manager, but for CI it's okay I guess.
> 
> Thats already what pip is trying be default but it fails because it can't uninstall the distlib version installed by the system package manager.

OK, if you add `--user` and remove `sudo` it *should* work then.

**Comment by Swiftb0y** [comment]
Works even without somehow, the issue now is that it can't find `appstreamcli` in the container image?!

**Comment by Holzhaus** [comment]
> > There's no need to push to my account, you can just push to your own account and then reference it instead of mine in the GitHub workflow file ;-)
> 
> Sure... but it doesn't really solve the issue either. Also I don't have a docker hub account :sweat_smile: 
> So can you take care of updating the container right now?

No, I'm already in bed and I need to get up in ~4 hours 😩

**Comment by Swiftb0y** [comment]
Ok no problem, I'll stop bothering you and create a mixxx org docker account in the process. I wish a good remaining 5 hours of sleep.

**Comment by Swiftb0y** [comment]
Not sure whats wrong with the container. Maybe @Holzhaus can work out whats wrong with https://github.com/mixxxdj/mixxx/commit/c0fa48fd99a7a5caa1dbeff96b765f42a4707177 (failing CI: https://github.com/mixxxdj/mixxx/runs/7683086173) when you find time. For now this CI works around the issue so we should merge ASAP so the failing PR can rebase/merge on this. Though this only fixes `2.3`, for `main` a similar workaround might work.

**Comment by daschuer** [comment]
Than you for taking care. This is green now.
Ready to merge?

**Comment by Holzhaus** [comment]
> Not sure whats wrong with the container. Maybe @Holzhaus can work out whats wrong with [c0fa48f](https://github.com/mixxxdj/mixxx/commit/c0fa48fd99a7a5caa1dbeff96b765f42a4707177) (failing CI: https://github.com/mixxxdj/mixxx/runs/7683086173) when you find time. For now this CI works around the issue so we should merge ASAP so the failing PR can rebase/merge on this. Though this only fixes `2.3`, for `main` a similar workaround might work.

Did you change the image in the meantime? I cannot reproduce the issue locally:

```bash
$ docker pull swiftb0y/mixxx-ci:latest
latest: Pulling from swiftb0y/mixxx-ci
38cab039087f: Already exists
0519f8466697: Already exists
7371074bdf7e: Pull complete
Digest: sha256:3bba27aca6095ed7afe71921098a8223191abcbad6559574971c1c4abe1292fd
Status: Downloaded newer image for swiftb0y/mixxx-ci:latest
docker.io/swiftb0y/mixxx-ci:latest
$ docker run -it swiftb0y/mixxx-ci:latest
[root@eff88617463d /]# git -v
git version 2.37.1
[root@eff88617463d /]# git clone --depth 2 https://github.com/mixxxdj/mixxx.git
Cloning into 'mixxx'...
remote: Enumerating objects: 7063, done.
remote: Counting objects: 100% (7063/7063), done.
remote: Compressing objects: 100% (5595/5595), done.
remote: Total 7063 (delta 2873), reused 3167 (delta 1392), pack-reused 0
Receiving objects: 100% (7063/7063), 41.45 MiB | 18.87 MiB/s, done.
Resolving deltas: 100% (2873/2873), done.
[root@eff88617463d /]# pip install pre-commit
...
[root@eff88617463d /]# pre-commit run --show-diff-on-failure --color=always --from-ref HEAD^1 --to-ref HEAD
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
...
fix utf-8 byte order marker..............................................Passed
check for case conflicts.................................................Passed
check json...........................................(no files to check)Skipped
check for merge conflicts................................................Passed
check xml................................................................Passed
check yaml...........................................(no files to check)Skipped
fix end of files.........................................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.................................................Passed
don't commit to branch...................................................Failed
- hook id: no-commit-to-branch
- exit code: 1
codespell................................................................Passed
eslint...............................................(no files to check)Skipped
clang-format.............................................................Passed
black................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
shellcheck...........................................(no files to check)Skipped
markdownlint-cli2........................................................Passed
Validate GitHub Workflows............................(no files to check)Skipped
qsscheck.............................................(no files to check)Skipped
changelog................................................................Passed
qmlformat............................................(no files to check)Skipped
qmllint..............................................(no files to check)Skipped
metainfo.................................................................Passed
```

**Comment by Holzhaus** [comment]
btw, for that reason you should tag proper versions and use them in the , not use the `latest` tag. When it gets updated later, older CI will start to fail for older revisions of the git repo because container image changed.

**Comment by Holzhaus** [comment]
anyway, we can already merge this to resolve the CI failures

**Comment by Holzhaus** [comment]
@Swiftb0y please have a look at: https://github.com/mixxxdj/mixxx/pull/4879

**Comment by Swiftb0y** [comment]
> btw, for that reason you should tag proper versions and use them in the , not use the latest tag. When it gets updated later, older CI will start to fail for older revisions of the git repo because container image changed.

Mhmm makes sense. I figured I'd use latest so we don't have to update the sources in the repo each time we update the container, but I didn't realize the consequence.

**Pull request merged**
