### PR TITLE
Skin layout revamp

### PR DESCRIPTION
**Pull request by ferranlala**
Supersedes https://github.com/mixxxdj/mixxx/pull/639

### CODE REVIEW

**Comment by ferranpujolcamins** [comment]
Is this ready to merge?

**Comment by Be-ing** [comment]
There are a lot of good improvements in this, thanks. However, now I face the issue that I can only see the buttons for toggling skin sections in full screen mode. My screen is 1366x768.
skin-pr

**Comment by ferranpujolcamins** [comment]
Hi Be, is this issue something this PR introduced? Or is LateNight too tall for you also in master?

**Comment by Be-ing** [comment]
This PR did not introduce the height issue, but the buttons were on top before so I could toggle some skin options without being in full screen mode. It is also possible to do through the menus in this PR without being in full screen mode, but that's not as obvious.

**Comment by ferranpujolcamins** [comment]
I see the problem. However, if it feels right to you, I'll address this
issue in another PR, this is already quite big.
El dia 04/04/2016 5:33 p. m., "Be" <notifications@github.com> va escriure:

**Comment by Be-ing** [comment]
Sure, this PR doesn't have to solve every issue.

**Comment by ferranpujolcamins** [comment]
@Be-ing , does https://github.com/mixxxdj/mixxx/pull/923 solve your height issue?

**Comment by ywwg** [comment]
I don't like the left/right buttons in the main decks.  Main decks shouldn't be assignable.

where did all the UI buttons go?

**Comment by Be-ing** [comment]
I think it makes sense to have crossfader assign buttons with 4 decks available. There is a spot in that button grid vacated by the spinny toggling button and I think filling that with crossfader assignment works. Do you think a button for something different would be more useful?

**Comment by Be-ing** [comment]
UI buttons went to the bottom of the window. The screenshot I posted shows that in this PR, that wasn't visible without fullscreen mode on my laptop screen. Hence PR #923

**Comment by ywwg** [comment]
I don't have a good suggestion for a replacement button, maybe loop on/off could go there instead?  Or maybe get rid of "reset beatgrid," since that's a feature not really needed during active performance, and then drop it to a grid of 4 buttons.  I know that some mixers have crossfader-assignable channels, but I don't want the main decks to be assignable in this skin.  It's too easy to confuse the user if they click it accidentally.

**Comment by Be-ing** [comment]
I'd be in favor of removing the "reset beatgrid" button and the crossfader assignment button and making a bit more width for the overview waveforms. Your concern about users getting confused with them does make sense. I do think crossfader assignment is a nifty feature and should be accessible somewhere in Mixxx. Maybe it would be better in the preferences somewhere.

**Comment by ferranpujolcamins** [comment]
> I don't have a good suggestion for a replacement button, maybe loop on/off could go there instead? Or maybe get rid of "reset beatgrid," since that's a feature not really needed during active performance, and then drop it to a grid of 4 buttons. I know that some mixers have crossfader-assignable channels, but I don't want the main decks to be assignable in this skin. It's too easy to confuse the user if they click it accidentally.

I agree to ditch the reset beatgrid button. We are going to have a proper beatgrid editing interface at some point.

Maybe we could move the crossfader assign buttons next to the crossfader?

**Comment by ywwg** [comment]
I'm not sure how much clearer I can be, I don't want crossfader assignment for main decks in this skin, thanks.

I'm also worried about moving the UI buttons, we moved them up there because people had a lot of trouble finding them in testing.  It takes up more room but people were able to quickly find and change the settings when the options were closer to the things they were changing.

**Comment by Be-ing** [comment]
Aesthetically, I feel the UI buttons are better placed on bottom. Big chunks of bright yellow background in the middle of where I'm often looking don't look good. Even if they are closer to the things they affect, I don't change them while mixing and don't need to be looking at them all the time while looking at the waveforms. I also think it makes more sense to group all the UI buttons together and there isn't room for that at the top.

**Comment by ferranpujolcamins** [comment]
> I'm not sure how much clearer I can be, I don't want crossfader assignment for main decks in this skin, thanks.

Don't worry I see you don't like it :)

This is how the skin looks like with the toolbar on top. I personally agree with Be: for me bottom is better.
captura de 2016-04-12 21 40 34

**Comment by ywwg** [comment]
no, I mean how it is in master.  The bottom bar controls views for the library area, and the top bar controls how the mixer appears.

**Comment by ferranpujolcamins** [comment]
I think is not that much of a problem. Maybe the first time people use Mixxx they take a couple extra seconds to find the buttons, but they are not that difficult to spot.
On the other hand, the space saved is worth it. Also I think the layout is a little bit tidier having all the buttons on the same toolbar.


> where did all the UI buttons go?
I've just realized I omitted the Mixer, EQ, Spinnies and Vinyl show/hide buttons that are on the top toolbar in master.
I can add all of them or only a few of them. Let me know which want would you like to be on the toolbar. Keep in mind that they all are accessible via the view menu.

**Comment by ywwg** [comment]
I had the Bitwig Studio UI in mind, where each pane has a small group of icon buttons to change various UI options: https://static.kvraudio.com/i/b/bts-mixer-clip-launcher.png.  Ableton does something similar: http://www.hezekinapollutina.com/.a/6a012876e57520970c0120a8cbeaf3970b-pi.   There are a few on the bottom, and then some more sprinkled around next to the thing that they alter.  I would have gone with icons instead of text but I was lazy and would have had to make tooltips for all of them.

**Comment by Be-ing** [comment]
Neither of those applications have scrolling waveforms though. The UI buttons in them are not right next to a part of the screen that is always moving and that the user is looking at a lot.

**Comment by Be-ing** [comment]
Regardless of where the buttons are, icons could be nicer than text.

**Comment by ferranpujolcamins** [comment]
> Regardless of where the buttons are, icons could be nicer than text.

I disagree. Text is self-explanatory, icons can be to decipher.

Another good point I see on the new layout is that all the UI toggles are grouped to the same place. So our users don't have to think/remember where is the control they are looking for.

**Comment by ferranpujolcamins** [comment]
I've hidden the UI buttons from the toolbar when the big library is on. They didn't work anyway.
captura de 2016-04-12 23 31 22

**Comment by ferranpujolcamins** [comment]
I've removed the beatgrid align and the crossfader assign buttons.

captura de 2016-04-13 11 41 34

**Comment by ywwg** [comment]
We still need to give people access to the removed UI options: EQs, Vinyl, Mixer, Spinnies.  Those need to go somewhere.  Maybe a Deere-style menu?

**Comment by ferranpujolcamins** [comment]
I don't see the point for a Deere style menu. It would require a click to open the menu and a click to toggle the button, so it doesn't offers any advantage over the view menu.

I've added them to the toolbar. Do you like it this way?

captura de 2016-04-14 11 14 15

**Comment by Be-ing** [comment]
> I've added them to the toolbar. Do you like it this way?
I like that way. :+1: 

I don't know if this would actually be an improvement, but what about switching the middle and right sections of the bottom buttons?

**Comment by Be-ing** [comment]
I think it is a little confusing that the right section of buttons only allows 1 button to be pressed but they look the same as the other buttons. Maybe make their background a slightly different color when activated?

**Comment by ferranpujolcamins** [comment]
> I don't know if this would actually be an improvement, but what about switching the middle and right sections of the bottom buttons?

That's personal taste. I don't really care. What do others think?

> I think it is a little confusing that the right section of buttons only allows 1 button to be pressed

If the window is big enough, they can all be active at the same time. I prefer keeping them the same color.

**Comment by Be-ing** [comment]
> If the window is big enough, they can all be active at the same time. I prefer keeping them the same color.

Ah, okay. I didn't realize that because my screen isn't big enough.

**Comment by pwhelan** [comment]
LateNight becomes superfluous without vertically stacked waveforms, IMHO.

**Comment by ywwg** [comment]
> LateNight becomes superfluous without vertically stacked waveforms, IMHO.
>  Show all checks

yes that's the primary reason LateNight exists

**Comment by pwhelan** [comment]
sorry... didn't see the waveforms in the middle, got confused with the track info boxes.

**Comment by ronso0** [comment]
@ferranpujolcamins @ywwg @Be-ing 

This PR seems to have fallen asleep.
From what I've heard, LateNight might get dropped in 2.1 due to the now historic effects section.
I'd like to make it ready for 2.1 by designing a the new effect section, therefor I'd adopt the LateNight part of this branch.
From the discussion I read that there are no major issues left and this is basically ready to merge and discussion about further tweaks can be continued in #923 ?

**Comment by daschuer** [comment]
A mergeable version can be found here: 
https://github.com/ferranpujolcamins/mixxx/pull/3

**Comment by daschuer** [comment]
I think a remaining issue here is if wee need crossfader assignment buttons for the decks. 
At least for two deck Shade skin they are not helpful and I am in doubt that this will work without confusion in the other skins. The rest looks good for me.

**Comment by daschuer** [comment]
In addition to the LateNight changes, this PR adds some items to the View menu and removes the individual spinny switching. New are: 

New are: 
* Show 4 Decks "[Master]", "show_4decks"
* Show Library "[Library]", "show_library"
* Show Spinning Vinyl "[Spinny]", "show_spinnies"
* Show Mixer "[Master]", "show_mixer"
* Show Eqs "[Master]", "show_eqs
* Show Crossfader "[Master]", "show_xfader"

I like the idea to have the view menu more complete. 
Is this a good setup for the 2.1 view menu? 
If Yes, I think we can merge this.

**Comment by Be-ing** [comment]
> I like the idea to have the view menu more complete.

The View menu is redundant with the skin settings menu but it is not accessible in full screen mode.

**Comment by daschuer** [comment]
>> I like the idea to have the view menu more complete.

> The View menu is redundant with the skin settings menu but it is not accessible in full screen mode.

What do you propose? 

The menu is accessible in full screen mode on my Ubuntu and should be accessible on the other OSs as well. On which OS is it broken? 

The redundant menu is a general question, we are IMHO not making things worse, if we add common skin settings to it as well.

**Comment by ronso0** [comment]
> The redundant menu is a general question, we are IMHO not making things worse, if we add common skin settings to it as well.

I agree, rarely used options can go to the View menu. But toggles for sub-menus -or button sets- like vinyl controls or beat grid buttons should stay in the skin. On the other hand, when there's a skin menu like Tango and Deere it (or the skin itself) should contain all options so users can be sure to find all options there.

**Comment by ronso0** [comment]
> The View menu is ... not accessible in full screen mode

On Xubuntu (Ubuntu Studio 14.04, xfce 4.10) it works well.
On Ubuntu 14.04 the menu bar is not when "Start in full screen mode" is enabled. If I toggle full screen off and on again, menu bar appears.

**Comment by ferranpujolcamins** [comment]
Can we close this after #1357 ?
@ronso0 @daschuer Is this something in this branch still relevant? I've just starting reading mixxx mails again and I'm a little bit lost.

**Comment by ronso0** [comment]
@ferranpujolcamins 
Yep, this can be closed.
Here you also proposed some changes to the menu bar, but I think those are not relevant anymore since we try to make the menu bar obsolete by moving many GUI toggles inside the skin, either into menus or a row of quick toggles.
Thanks for your work tough, we could use a lot of it!  LateNight finally arrived in 2.1 and it feels good :)

**Comment by ferranpujolcamins** [comment]
Thank you for taking care of LateNight!!!!

**Comment by poelzi** [comment]
As long as the menu can be switched back on I'm fine with that. The menu has advantages as well. Especially for handycaped I think they are useful and casual users may find them more confident.

Kind regards
 Poelzi

On 31 December 2017 18:20:53 CET, ronso0 <notifications@github.com> wrote:
>@ferranpujolcamins 
>Yep, this can be closed.
>Here you also proposed some changes to the menu bar, but I think those
>are not relevant anymore since we try to make the menu bar obsolete by
>moving many GUI toggles inside the skin, either into menus or a row of
>quick toggles.
>Thanks for your work tough, we could use a lot of it!  LateNight
>finally arrived in 2.1 and it feels good :)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mixxxdj/mixxx/pull/913#issuecomment-354615331

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Be-ing** [comment]
The discussion about the menu bar is getting quite off topic from this pull request. Let's continue the discussion on the [Launchpad issue](https://bugs.launchpad.net/mixxx/+bug/1740365) or start a new topic in the [#development stream on Zulip](https://mixxx.zulipchat.com/#narrow/stream/development).

**Pull request closed without merging**
