### PR TITLE
Fix warnings on initialization of MIDI controller

### PR DESCRIPTION
**Pull request by git-developer**
This pull request avoids the following warnings when a MIDI controller is initialized that contains effect unit controls:
* ```Warning [Controller]: ControlDoublePrivate::getControl returning NULL for ( "[EffectRack1_EffectUnit2_Effectundefined]" , "meta" )```
* ```Warning [Controller]: ControlDoublePrivate::getControl returning NULL for ( "" , "show_focus" )```

### CODE REVIEW

**Comment by Be-ing** [comment]
Thank you for taking care of these annoying warnings. Please rebase on the 2.3 branch.

**Comment by git-developer** [comment]
Sorry for messing up the base branch. I hope it's fixed now.

**Comment by uklotzde** [comment]
Thanks for contributing to Mixxx and welcome, Christian.

Before we merge your changes we need your permission by signing the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ). Please comment here when done.

**Comment by git-developer** [comment]
I signed the agreement.

**Comment by uklotzde** [comment]
> I signed the agreement.

I guess we need a valid E-Mail address. @daschuer @Be-ing Please confirm.

**Comment by git-developer** [comment]
OK, no problem, I signed once more using a different email address.

**Comment by uklotzde** [comment]
@Be-ing Merge?

**Comment by daschuer** [comment]
> I guess we need a valid E-Mail address. @daschuer @Be-ing Please confirm.

Yes, we need a legal person to get in contact in case of copy right issues.

**Comment by Holzhaus** [comment]
Works great, thank you! Finally these warnings are gone :D

**Review by Holzhaus — APPROVED** [review]

**Pull request merged**
