### PR TITLE
Auto DJ: Add new random tracks if one track does not exists

### PR DESCRIPTION
**Pull request by daschuer**
This fixes an issue reported in #13544 

In addition the logging is improved for such situation by failing earlier. Now it looks like this: 

```
info [Main] Unable to detect MIME type from not existing file "/home/daniel/Musik/- Humillaci¢n (Kopie).mp3"
info [Main] Unable to detect MIME type from not existing file "/home/daniel/Musik/- Humillaci¢n (Kopie).mp3"
debug [Main] SoundSourceProxy - SoundSourceProvider "MAD: MPEG Audio Decoder 0.15.1 (beta) NDEBUG FPM_64BIT" created a SoundSource for file "file:///home/daniel/Musik/- Humillaci¢n (Kopie).mp3" of type "mp3"
warning [Main] TrackRecord - Failed to obtain synchronization time stamp for not existing file QFileInfo(/home/daniel/Musik/- Humillaci¢n (Kopie).mp3)
warning [Main] SoundSourceProxy - Unable to update track from missing or inaccessible file "file:///home/daniel/Musik/- Humillaci¢n (Kopie).mp3"
debug [Main] BaseTrackCache(0x5612c6c9ba70) updateIndexWithQuery took 0 ms
warning [Main] Auto DJ: Skip missing track "/home/daniel/Musik/- Humillaci¢n (Kopie).mp3"
debug [Main] Committing transaction successfully on "MIXXX-1"
debug [Main] PlaylistTableModel(0x5612c6c96150) select() returned 0 results in 0 ms
debug [Main] GlobalTrackCache - Evicting track  TrackRef {"/home/daniel/Musik/- Humillaci¢n (Kopie).mp3","",390} Track(0x5612d4798d10)
debug [Main] GlobalTrackCache - Deleting Track(0x5612d4798d10)
debug [Main] Auto DJ disabled
```

### CODE REVIEW

**Review by Swiftb0y — APPROVED** [review]
LGTM :shrug:

**Comment by daschuer** [comment]
Can this be merged now?

**Comment by daschuer** [comment]
Can one merge this in absence of @Swiftb0y?

**Comment by daschuer** [comment]
Friendly ping @Swiftb0y

**Comment by Swiftb0y** [comment]
Sorry

**Pull request merged**
