### PR TITLE
m3u import: continue parsing after a blank line, fixing lp1806271

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by uklotzde** [comment]
Thanks for taking care! I've had a look at the example file, but didn't check the code carefully.

**Comment by uklotzde** [comment]
LGTM. Fix works as expected.

**Comment by uklotzde** [comment]
We don't need to wait on the AppVeyor CI build for this simple case.

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
