### PR TITLE
rename beatloop_activate to beatloop_toggle

### PR DESCRIPTION
**Pull request by Be-ing**
beatloop_toggle makes more sense with the new behavior of
deactivating the current loop if pressed when looping is enabled.

Follow up of #4328

### CODE REVIEW

**Comment by Be-ing** [comment]
I think we should ignore the pre-commit errors for this mass renaming PR.

**Comment by Swiftb0y** [comment]
Do we really need this mass renaming? We have to support the `beatloop_activate` CO anyways for a long time since there are skins and mappings outside our control. IMO updating the manual is sufficient. We can still merge since you already did most of the work, but for the future, I'd like to avoid these mass renaming PRs.

**Comment by Be-ing** [comment]
Strictly speaking no, we do not need the mass renaming because of the aliasing. But I think it is better to have everything included in the repository consistent. Aliasing is needed just for backwards compatibility with unofficial controller mappings and skins that were never merged.

**Comment by ronso0** [comment]
> Aliasing is needed just for backwards compatibility with ~~unofficial~~

...customized controller mappings and skins.

**Comment by ronso0** [comment]
> I think it is better to have everything included in the repository consistent

I agree. Document it in the manual, then let's merge.

**Comment by Holzhaus** [comment]
I disagree. There is no reason to rename, just document the new behavior. `activate` does not mean `enable`, it is similar to `hotcue_X_activate` IMHO.

**Comment by Swiftb0y** [comment]
>  There is no reason to rename

Not really, but the work has already been done so denying a merge is pointless and discouraging towards Be's efforts.

**Comment by ronso0** [comment]
> > There is no reason to rename
> 
> Not really, but the work has already been done so denying a merge is pointless and discouraging towards Be's efforts.

well, that argumentation could be abused for controversial PRs.
Actually for mass-renaming a prior discussion should be required.

**Comment by Swiftb0y** [comment]
>well, that argumentation could be abused for controversial PRs.

I agree, but I don't consider this change controversial. Though I can understand if you don't want to accept that argument.

**Comment by ronso0** [comment]
In this particular case I don't mind.
It's just that we should agree on mass renamings before doing the work, running into merge conflicts continously, time pressure to merge or not, having heated discussions  etc. which only unnecessarily draws energy. I think we had all that too often already.

**Comment by Be-ing** [comment]
I wouldn't really be upset if this is rejected. It didn't take much work to implement either. :shrug:

**Comment by ronso0** [comment]
That's why "In this particular case I don't mind." ;)

**Pull request closed without merging**
