### PR TITLE
Make all effect short names translatable

### PR DESCRIPTION
**Pull request by Be-ing**
This PR gives every effect a short name, even if they are not needed in English, in case a separate short name is needed for other languages.

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you. LGTM! 

Did you consider how to define what is a short name? 

For the following will work, any other options?  
//: Limited length effect name. Should not exceed the rendered pixel width of "XXXXXXX"

"XXXXXXX"
"Fancy Effect" -> too long
"Fancy Ef." -> fit even if there are more charater.
"花式效果" -> Fit
"花式特殊效果" does not fit even if there are less character.

**Comment by Be-ing** [comment]
I'm not sure if that question can be definitively answered until all skins are using WEffectSelector.

**Comment by daschuer** [comment]
We do not have much time to decide, since it is hard to fix long strings when they are already translated, because we do not have a tool that complains about this. 
So we should make sure that a translator receives the comment along with the new string to translate.
"XXXXXXXX" is really short, but it deserves the name short, and it works nicely for all current effects:
"Be 4 ISO"
"Be 8 ISO"
"LR 8 ISO" 
"Bq EQ
"Graphic EQ" 
"Filter"
"Moog Filter"
"Bitcrusher"
"Flanger"
"Echo"
"Auto pan"
"Hall"
"Phaser"

**Comment by Be-ing** [comment]
Currently the longest short name is "Bessel8 ISO", and that still leaves a little bit of width in WEffectSelector with #1063.

**Comment by daschuer** [comment]
"Bessel8 ISO"
"XXXXXXXXX" -> 9 x X 

But it would be better comparable if we cut all mixing effects down.

**Comment by Be-ing** [comment]
> But it would be better comparable if we cut all mixing effects down.

No, we should not shorten names any more than they need to be shortened.

**Comment by daschuer** [comment]
How do you now that this is not needed? 
My approach was to find out what the shortest reasonable length is. 7 x X is a good candidate for me since it allows, to display all effect in a recognisable way, but is short enough to allow fancy small skins. 

Do you like to go for 9 x X? Do you have reason to know  that every skin designer has that space?

**Comment by daschuer** [comment]
Since we cannot enforce a maximum length we may write: 
//: Limited length effect name. If it exceeds the width of "XXXXXXX" it might be schown middle elided.

**Comment by Be-ing** [comment]
Why does GitHub have a "Close and comment" button? :/

**Comment by Be-ing** [comment]
@sblaisot any thoughts on this?

**Comment by sblaisot** [comment]
It would be nice to have translator tips along with short names to translate in transifex interface (like long name it refers to and a hint on max size for the translation).
I don't know how to do that but @esbrandt can probably help on that.

**Comment by daschuer** [comment]
The //: comment are already displayed in Transiflex at the "Instructions" field. 

The question here is how we can give a hint what "Short" means. The idea was to add an example string of X as reference for a rendered length. This is far from being exact, but it is IMHO even better than just count the characters.   

How can we describe the length measure in an understandable way?  

We also need to decide how short short should be. I vote for 7 x X = "XXXXXX", Does this suite to find reasonable French abbreviations for the Effect names?

**Comment by Be-ing** [comment]
Please reopen this PR so it is not forgotten.

**Comment by daschuer** [comment]
We have two open points here: 
* Does a char X measure work (until we can do better)
* How many X is short? 

Any thought?

**Comment by esbrandt** [comment]
> The question here is how we can give a hint what "Short" means. The idea was to add an example string of X as reference for a rendered length. This is far from being exact, but it is IMHO even better than just count the characters.
> 
> How can we describe the length measure in an understandable way?

Transifex translation interface allows to set a character limit of X. Translations above X are rejected. This is a manual process, and has to be done by the maintainer for each string. 

Using the long name as hint gives the most context e.g.
```cpp
     //: Short name of "Bessel4 LV-Mix Isolator" ( character limit XXX )
      manifest.setShortName(QObject::tr("Bessel4 ISO"));
```
Done this manually for some short strings before , see [[1]](https://www.transifex.com/mixxx-dj-software/mixxxdj/translate/#de/github-master/105259731), works ok.

After updating language template and importing into Transifex, the language maintainers can search for strings containing``character limit``, and set the limit to XXX.

If translators do not use the Transifex service (they could download the template, translate using a 3rd party service/app) there is at least the chance the notice the existing character lime in the comments. 

the ``:// long name`` comment is not necessary for translators imo.

**Comment by daschuer** [comment]
The issue with the Transiflex Character Limit, is that it does not give a hint how wide a control needs to be to display all characters allowed without eliding. 

- "花式特殊效果" has 6 Character 
- "Effect" has also 6 Charters

This means the skin designer has to reserve the width for 6 big characters but a translator wasts space when using only 6 thin characters.

The second issue is that some skins have more, or a dynamic space. This would allow to display longer strings. The translator may want to violate the length rule knowing that  the rendered result is most likely elided. In the Effect name context, this will be the case anyway if we use LV2 effects, where we cannot influence the lenght of the name.  
 
Thats why I came up with the Idea to use the width of a rendered "X" as reference. 
```c++
//: Limited length effect name. Displayed without eliding, when not exceed the rendered pixel width of "XXXXXXX"
```

IMHO a Fixed character count does not suite here, and should be not set in Transiflex.

**Comment by daschuer** [comment]
@esbrandt Do you think this will work?

**Comment by Be-ing** [comment]
Doesn't the width of an X depend on the font face and size?

**Comment by daschuer** [comment]
Yes, I assume that the other characters scale proportional with the X.
Unfortunately this is not always true, but a good hint, since the same
string will always render, with  different length using different fonts in
the skin. We could also take any other character or a whole significant
test word: "Lorem Ipsum" This is probably not immune if the skin uses a
capitalized font or "curee new".
The whole thing it is just an assert to the translator: "the test word
 will fit" and to the Skinner: "Make the testword fit, and all translations
will likely fit as well"

Am 02.02.2017 5:07 nachm. schrieb "Be" <notifications@github.com>:

**Comment by daschuer** [comment]
We need a conclusion to continue here. 

I am for adding this to the short effect names: 
```//: Length of the rendered translated text must not exceed the length of  "Lorem Ipsum"```

bildschirmfoto vom 2017-04-05 20 38 52

What do you think?

**Comment by Be-ing** [comment]
We're not using monospace fonts, so wouldn't that be a crude estimate for specifying the width? I guess it would be better than nothing though.

**Comment by daschuer** [comment]
That was the idea, to give a more realistic and useful length than just counting characters, that will work for non latin fonts as well.

**Comment by uklotzde** [comment]
@Be-ing  Schedule this one for 2.1.0?

**Comment by Be-ing** [comment]
Yes, this must be taken care of before string freeze.

**Comment by Be-ing** [comment]
Superseded by #1439

**Pull request closed without merging**
