### PR TITLE
Skins: Fix sidebar item styling on 2.4 too

### PR DESCRIPTION
**Pull request by fwcd**
Forgot this affected 2.4 too, so here's a cherry-pick of #11970 onto 2.4

cc @ronso0

### CODE REVIEW

**Comment by ronso0** [comment]
I didn't pay attention either, sorry.

LGTM

**Comment by ronso0** [comment]
I'm surprised that merging 2.4 into main worked without conflicts...

**Comment by fwcd** [comment]
After the cherry-pick? If the lines are matching byte-for-byte Git shouldn't produce conflicts even for disjoint histories, so that would be the expected behavior.

**Comment by ronso0** [comment]
maybe my memory is deceiving me, and it was just rebases where I encountered those ridiculous 3-way diffs? 🤷

**Pull request merged**
