### PR TITLE
Install Qt Translation on MacOS 

### PR DESCRIPTION
**Pull request by daschuer**
Fixes https://github.com/mixxxdj/mixxx/issues/11110

### CODE REVIEW

**Comment by Swiftb0y** [comment]
Semantically, the change is a noop? Did you forget to change the above `if(WIN32)` to include macos? 
https://github.com/mixxxdj/mixxx/pull/11134/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR1485-R1489

**Comment by daschuer** [comment]
My first commit enters a recursive loop with CPack. I have not yet an idea why. After reverting it seems to work again. Strange.

**Comment by daschuer** [comment]
This is ready now.

**Comment by daschuer** [comment]
Who can give this a try on MacOS? 
You should find
Something like 
```
Debug [Main]: Loaded "qt" translations for locale "de_DE" from "/home/daniel/workspace/2.3/res/translations/"
```
in your mixxx.log and not a warning. 
```
Warning [Main]: Failed to load "qt" translations
```

**Comment by foss-** [comment]
2.3.3-120-g6afa8d6c67 (HEAD)

```
Debug [Main]: Loading resources from  "/Applications/mixxx.app/Contents/Resources/"
Debug [Main]: Found and will use default keyboard preset "/Applications/mixxx.app/Contents/Resources/keyboard/de_DE.kbd.cfg"
Debug [Main]: Loading resources from  "/Applications/mixxx.app/Contents/Resources/"
Debug [Main]: Failed to load "qt" translations for locale "de_DE" from "/Users/mixxx/bs-2.3-mac/amd64/environment/2.3-j00026-0b1209e3-osx10.12-x86_64-release/Qt-5.12.3/translations"
Debug [Main]: Loaded "qt" translations for locale "de_DE" from "/Applications/mixxx.app/Contents/Resources/translations/"
Debug [Main]: Loaded "mixxx" translations for locale "de_DE" from "/Applications/mixxx.app/Contents/Resources/translations/"
Debug [Main]: Loading resources from  "/Applications/mixxx.app/Contents/Resources/"
```

**Comment by daschuer** [comment]
Ah, thank you for testing. I will remove the misleading debug message as well.

**Comment by daschuer** [comment]
Please try again. Thank you.

**Comment by foss-** [comment]
```
Debug [Main]: Loading resources from  "/Applications/mixxx.app/Contents/Resources/"
Debug [Main]: Found and will use default keyboard preset "/Applications/mixxx.app/Contents/Resources/keyboard/de_DE.kbd.cfg"
Debug [Main]: Loading resources from  "/Applications/mixxx.app/Contents/Resources/"
Debug [Main]: Loaded "qt" translations for locale "de_DE" from "/Applications/mixxx.app/Contents/Resources/translations/"
Debug [Main]: Loaded "mixxx" translations for locale "de_DE" from "/Applications/mixxx.app/Contents/Resources/translations/"
Debug [Main]: Loading resources from  "/Applications/mixxx.app/Contents/Resources/"
```

Looking good.

**Comment by ronso0** [comment]
I assume you intended to ping @Swiftb0y, since I still have no clue of the implications here.

**Review by Swiftb0y — APPROVED** [review]
Code looks good. I trust the testing from @foss-

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
