### PR TITLE
Add hotcue mappings to hercules RMX keypad

### PR DESCRIPTION
**Pull request by nieknooijens**
Hi there

I replaced my ION discover DJ with a second hand hercules DJ RMX.
after messing around with udev and other settings, I got it to work, but discovered the keypad was completely unmapped. the wiki page for this controller is also out-of-date showing 2 possible mappings with 1 having keypad 5 and 6 mapped to the flanger effect from pre-mixxx 2.0.
I changed the script to use the hotcue buttons where they are designed for. unfortunately mixxx only has 4 hotcues so I mapped 5 and 6 to loop_in and loop_out (since I use them a lot).

if necessary I can also update the wiki page @https://www.mixxx.org/wiki/doku.php/hercules_dj_console_rmx if this MR gets approved.

### CODE REVIEW

**Comment by poelzi** [comment]
Some skins support 8 hotcue points if enabled in the skin settings.

**Comment by Be-ing** [comment]
> Some skins support 8 hotcue points if enabled in the skin settings.

That does not mean they all need to be mapped. I think it makes sense to use the other two for looping controls.

**Comment by Be-ing** [comment]
I'm quite confused why there are two mappings for this device...

**Comment by nieknooijens** [comment]
So should i remap 5 and 6 to hotcue 5 and 6?

Also this device doesn't have 2 mappings, but the wiki says so...

**Comment by Be-ing** [comment]
No, there's no need to map every possible hotcue. Most controllers only map 4 hotcues.

Augh, it seems there's a separate mapping for this controller for MIDI and for HID. How confusing...

**Comment by nieknooijens** [comment]
this MR only applies to the HID driver. (which is selected by default on ubuntu 17.10)

**Comment by Be-ing** [comment]
Okay, well this is better than having completely unused buttons. This was targeted at the master branch, so I rebased it on 2.1 for the release. For the future we can work on consolidating and updating both mappings for this controller.

**Comment by nieknooijens** [comment]
ok, keep me updated about the progress.

**Pull request closed without merging**
