### PR TITLE
Update to latest vcpkg commit

### PR DESCRIPTION
**Pull request by daschuer**
I am curious if it still works with the extended triplet name x64-osx-min10.12

### CODE REVIEW

**Comment by Be-ing** [comment]
This is a perfect illustration of why CI on the vcpkg repo is pointless.

**Comment by daschuer** [comment]
This does no longer work, because due to the triplet renaming in https://github.com/mixxxdj/vcpkg/pull/26
The issue is that this puts vcpkg into a crosscompiling mode where it generates packages for the x64-osx-min10.12 and users for tools x64-osx. When compiling with Mixxx in non compromising mode it detects a x64-osx and fails to find the packages in x64-osx-min10.12.

**Comment by Be-ing** [comment]
You are trying to solve problems that were already solved but you rejected the solution.

**Comment by daschuer** [comment]
I will start over

**Pull request closed without merging**
