### PR TITLE
CPack: Add missing text label

### PR DESCRIPTION
**Pull request by uklotzde**
Trying to fix the cpack -G "WIX" failure on AppVeyor caused by 3c3e5688c4b578fe2ddf8e6d3b36210055e01820

### CODE REVIEW

**Comment by Be-ing** [comment]
I removed this because it broke code signing on macOS.

**Comment by uklotzde** [comment]
Lets see if `"mixxx;Mixxx"` makes a difference to `"mixxx" "Mixxx"`

**Comment by Be-ing** [comment]
The issue was that macOS Gatekeeper was looking for a binary called `Mixxx` to validate the signature but that file didn't exist; the binary is `mixxx`.

**Comment by Be-ing** [comment]
It might have been https://github.com/mixxxdj/mixxx/commit/3c3e5688c4b578fe2ddf8e6d3b36210055e01820#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL1068 that fixed that, but I didn't test that independently from https://github.com/mixxxdj/mixxx/commit/3c3e5688c4b578fe2ddf8e6d3b36210055e01820#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL2408 so I'm not sure.

**Comment by Be-ing** [comment]
Looking at the AppVeyor error:
```
CPack Error: CPACK_PACKAGE_EXECUTABLES should contain pairs of <executable> and <text label>.
```
I think this reversion is necessary. It was probably https://github.com/mixxxdj/mixxx/commit/3c3e5688c4b578fe2ddf8e6d3b36210055e01820#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL1068 which fixed code signing for macOS.

**Pull request merged**
