### PR TITLE
Skins / Qt6: menu icon position fix

### PR DESCRIPTION
**Pull request by ronso0**
... + some cleanup

Menu icons are are a bit off to the left.
Screenshot_2024-05-29_02-19-51
____

With Qt6 the context menus should look like this:
(yes, this is expected to break styles with Qt5)
image
image
image
image
(yes, the shortcut Ctrl+a still overlaps "Select all")
image

Please verify on all OS and in all skins. Thanks!
* main menu (menubar)
* table header menu
* track menu (decks & library), especially Crates menu
* sidebar menu, especially Crates menu
* edit fields menu (searchbar, track table inline editing, beatsize spinboxes etc.)

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
This is how it looks on Windows 11 with this PR:
grafik
grafik
grafik
I wasn't able to edit the track title in the library (BTW, should there be a tooltip, which explains in-place editing?)
grafik

**Comment by ronso0** [comment]
Thanks @JoergAtGithub 

You only need to post screenshots if you notice significant deviation from my screenshots.

> Why is this menu in English language and all other in German?

Good question. On Linux, the selected locale is applied to all menus.
Not a regression of this PR, I just touched the stylesheets. Please file an Issue.

**Comment by ronso0** [comment]
Thanks @JoergAtGithub 

You only need to post screenshots if you notice significant deviation from my screenshots.

> Why is this menu in English language and all other in German?

Good question. On Linux, the selected locale is applied to all menus.
Not a regression of this PR, I just touched the stylesheets. Please file an Issue.

**Comment by ronso0** [comment]
> BTW, should there be a tooltip, which explains in-place editing?

Maybe, though I have no idea where that would go. Having it appended to every cell's tooltip seems a bit annoying, especially if you're already aware of the feature.
I think this is part of the meta issue: how to properly introduce all those fancy UI features, i.e. increase discoverability of features like track drag'n'drop, double-click on track labels, skin settings and what not.

**Comment by JoergAtGithub** [comment]
Please fix the conflicts

**Comment by ronso0** [comment]
I rebased onto 2.5.
Please check again on all targets:
* table header menu
* any QLineEdit menu (search, beat spinboxes, table inline editors, etc.)
* track menu -> crates
* sidebar -> crate name menu (with checkbox)
* "search related tracks" menu
* ...

**Comment by JoergAtGithub** [comment]
Overall it looks good on Windows11 (Qt6.5.3 from VCPKG). But the checked checkboxes look slightly smaller than the unchecked and have rounder corners.

100% Zoom:
grafik

200% Zoom:
grafik

**Comment by daschuer** [comment]
I can confirm the issue is fixed: 
grafik

I cannot confirm the different checkbox sizes. @JoergAtGithub is this a regression form this PR?

**Comment by JoergAtGithub** [comment]
The differnent checkbox size is not a regression by this PR!

**Comment by ronso0** [comment]
Okay, so we need a check on macOS @m0db @foss- @fwcd (?)

I'll take a look at the checkbox issue on Windows but will probably open a separate PR for this.

**Comment by foss-** [comment]
Crate checkbox + contextual menu for crate. There are no icons in the menu-bar options on macOS.

crate checkbox
contextual menu for crate
menu

**Review by daschuer — APPROVED** [review]
Thank you. This means macOS is not affected and we can merge.

**Pull request merged**
