### PR TITLE
Fix broken Mic mute button (used in Deere) and ...

### PR DESCRIPTION
**Pull request by daschuer**
https://bugs.launchpad.net/mixxx/+bug/1782568

### CODE REVIEW

**Comment by daschuer** [comment]
should that go to 2.1?

**Comment by daschuer** [comment]
fixes also https://bugs.launchpad.net/mixxx/+bug/1781748

**Comment by daschuer** [comment]
What is the right target branch for this bugfix?

**Comment by Be-ing** [comment]
The code looks good to me. I think this should be merged into the 2.2 branch.

**Comment by daschuer** [comment]
Thank you for review.

**Pull request merged**
