### PR TITLE
ParametricEQEffect: Fix typo in description

### PR DESCRIPTION
**Pull request by fwcd**
Just a minor typo I've come across.

### CODE REVIEW

**Comment by ronso0** [comment]
I assume this didn't affect translations.
In order to keep existing translations, it is preferred to change the source string in transifex (note that I have no experience with this):
https://help.transifex.com/en/articles/6236820-edit-source-strings-online#h_7e60a9b609

**Comment by ronso0** [comment]
tr wizard @daschuer what is your opinion?

**Comment by daschuer** [comment]
This string is translated in some languages, 
Better a redundant "n" in one language than an untranslated string. 
Let's postpone this fix to 2.5.

**Comment by daschuer** [comment]
... We cannot change the source text, because it is also the lookup key.

**Comment by ronso0** [comment]
Sounds resonable, though did you take a look at the article I linked above?

**Comment by fwcd** [comment]
Can we change the key for all languages?

**Comment by ronso0** [comment]
I don't know, I'm not familiar with the Transifex/lupdate workflow.
Here's the intro to the new'Update source' function added in July this year. it's available via Transifex User Interface (UI), Transifex API and Transifex Go CLI
https://community.transifex.com/t/introducing-enhanced-resource-updating-in-transifex/3503

Here the documentation for the 'new' CLI client:
https://github.com/transifex/cli#pushing-files-to-transifex
> `--keep-transations`: If present, translations of source strings with the same key whose content changes will not be discarded. This can also be set on a per-resource level in the configuration file.

**Comment by daschuer** [comment]
Ok, I will merge that now and fix the translations manually on Transifex.

**Comment by ronso0** [comment]
Thank you very much!

**Comment by daschuer** [comment]
Done.

**Pull request merged**
