### PR TITLE
fix(rekordbox): Fix missing playlists due to invalid child ID

### LINKED ISSUE #10923: Randomly missing playlists in Rekordbox formated drives
When i go to my Rekordbox usb devices in Mixxx there are always some playlists missing. 
rekordbox01

Don't know if this is a known issue.

Cheers Jakob

### PR DESCRIPTION
**Pull request by Holzhaus**
Fixes #10923.

### CODE REVIEW

**Comment by Holzhaus** [comment]
@emmetiray please check if this fixes the issue for you. To test this pull request, you can follow the instructions on the wiki: https://github.com/mixxxdj/mixxx/wiki/Testing#github-pull-requests

**Comment by emmetiray** [comment]
ok thanks. will check again.

**Comment by emmetiray** [comment]
@Holzhaus it seems to work now. sometimes mixxx crashes and closes without any error message when i open the rekordbox drive. but the next time it works well. thanks for everything.

**Comment by Holzhaus** [comment]
Thanks for testing. Are the crashes new or do they also happen without this change?

**Comment by Holzhaus** [comment]
No, but you can probably use the AUR package `mixxx_beta-git` and replace [line 48 in the PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mixxx_beta-git#n48) with:

    source=("${pkgname%-*}::git+https://github.com/Holzhaus/mixxx.git#branch=rekordboxfeature-fix-missing-playlists"

**Comment by emmetiray** [comment]
oh i just discovered another thing: it seems that every single playlist is visible now with all the music inside but there are some playlists where the music inside is not loaded. discovered that with: "kbirthday", "Ace_20_08_22/dance" and "Ace_20_08_22/soft", "08.0.8.2022"

**Comment by emmetiray** [comment]
missing_tracks

**Comment by emmetiray** [comment]
missingtracks_rekordbox

(example with "Kbirthday" in rekordbox)

**Comment by emmetiray** [comment]
"mix" and "skeelo" are two more playlists which are not showing any music inside. i think thats all.

**Comment by emmetiray** [comment]
@Holzhaus

**Comment by Holzhaus** [comment]
> oh i just discovered another thing: it seems that every single playlist is visible now with mostly all the music inside but there are some playlists where the music inside is not loaded. discovered that with: "kbirthday", "Ace_20_08_22/dance" and "Ace_20_08_22/soft", "08.0.8.2022"

Is this caused by this change? Or is this a new, unrelated issue?

**Comment by Holzhaus** [comment]
> "mix" and "skeelo" are two more playlists which are not showing any music inside. i think thats all.

These two *should* be empty, don't they? At least it looks like they don't have any playlist entries attached to them.

Please check if this is correct:
<details><summary>Playlists with track count</summary>
<pre><code>🗀 15.07.22
    🗎 riot code (3 tracks)
🗀 jaki_21_05_22
    🗎 jaki_melow (18 tracks)
    🗎 jaki2 (29 tracks)
    🗎 jaki (19 tracks)
🗀 18.05.22
    🗎 plaid - dial p (15 tracks)
    🗎 otherstuff (10 tracks)
    🗎 wettrax (33 tracks)
    🗎 kumo99 (14 tracks)
🗎 breakcore_gabba (3 tracks)
🗎 10.05.22 (23 tracks)
🗀 grime_hardwave
    🗎 maindir (24 tracks)
    🗎 TMSV - Jungle- Vol. 2 (3 tracks)
    🗎 ian shirtman - The Shirt Tape (7 tracks)
    🗎 Deadcrow - Transmission (3 tracks)
    🗎 Deadcrow - Lies (1 tracks)
    🗎 Deadcrow - 2015-2017 (9 tracks)
    🗎 BEAT PVP - BEAT PVP 1ª EDIÇÃO (16 tracks)
    🗎 Vinnie Grapes - Radiohooligans (8 tracks)
🗀 loststuff
    🗎 maindir (23 tracks)
    🗎 Tommy Holohan & Casper Hastings (4 tracks)
    🗎 The Horrorist (11 tracks)
    🗎 peryl (4 tracks)
    🗎 Pavel K. Novalis (1 tracks)
    🗎 Mode In Gliany (7 tracks)
    🗎 Mass-X-Odus (1 tracks)
    🗎 Kas_st (1 tracks)
    🗎 Jokasti & Nek (1 tracks)
    🗎 Jacidorex (1 tracks)
    🗎 Homemade Weapons & Red Army (1 tracks)
    🗎 Homemade Weapons & Gremlinz (1 tracks)
    🗎 Homemade Weapons (10 tracks)
    🗎 Hephaistos (1 tracks)
    🗎 FSOM (23 tracks)
    🗎 FRACTIONS (6 tracks)
    🗎 B2 (1 tracks)
    🗎 Endlec (1 tracks)
    🗎 Danilo Incorvaia (4 tracks)
    🗎 V_A_ Lars Huismann & Chris Koegler, Alignment, T (1 tracks)
    🗎 Ansome (1 tracks)
🗀 oldfolders
    🗎 Houndstooth (11 tracks)
    🗎 Jiri Ceiver (25 tracks)
    🗎 KiNK (15 tracks)
    🗎 halloween (20 tracks)
    🗎 Justin Berkovi (71 tracks)
    🗎 jackwho (18 tracks)
    🗎 HTH vs HTH (7 tracks)
    🗎 maindir (49 tracks)
    🗎 [tiva011] Justin Berkovi - Gravel Heart EP (4 tracks)
    🗎 _IGOR (2 tracks)
    🗎 acephale (26 tracks)
    🗎 15.12.2017 (7 tracks)
    🗎 v-tracks - limits (5 tracks)
    🗎 Vtracks (5 tracks)
    🗎 Vectors 3 (8 tracks)
    🗎 VA-Phuture_Beats_Vol._1-(DCD089-41802)-2CD-FLAC-1995-dL (40 tracks)
    🗎 va - kids (soundtrack) (13 tracks)
    🗎 usbcd (11 tracks)
    🗎 URBAN HOMES - Centres (5 tracks)
    🗎 Tube Jerk (20 tracks)
    🗎 this machine is broken (14 tracks)
    🗎 The Sound of Belgium (60 tracks)
    🗎 Terence_Fixmer-Depth_Charged (10 tracks)
    🗎 telex - remixes (12 tracks)
    🗎 Studio672 (42 tracks)
    🗎 Sound Architecture (10 tracks)
    🗎 schnoerres (5 tracks)
    🗎 RussianTechno (55 tracks)
    🗎 Rush Hour (12 tracks)
    🗎 Quarks - Rehmix (2000) (14 tracks)
    🗎 Physically Sick - Physically Sick (42 tracks)
    🗎 Point B - Suicide Beauty Spot (14 tracks)
    🗎 Physically Sick 2 - Physically Sick 2 (43 tracks)
    🗎 Palette_All-Stars--After_School_Special-(PAL051)-WEB-2008-dh (3 tracks)
    🗎 Mr Ozio - Lambs Anger (17 tracks)
    🗎 nachtigal (26 tracks)
    🗎 newstuff (7 tracks)
    🗎 nachtigal2 (38 tracks)
    🗎 Mr.Oizo-Analog Worms Attack_224kbps_mFY (15 tracks)
    🗎 marcel (6 tracks)
    🗎 mix (10 tracks)
    🗎 MMODEMM (72 tracks)
    🗎 Missile Recordings (16 tracks)
    🗎 Marcus Zils Musik (41 tracks)
    🗎 Lena Willikens - Phantom Dalia Ep (6 tracks)
    🗎 Kate Tempest-Everybody Down-Paul'sBoutique (11 tracks)
    🗎 Magazine 18 DigiFiles (4 tracks)
    🗎 koelncampus (13 tracks)
    🗎 Lorenzo Senni - Persona (2016) (6 tracks)
    🗎 khmparty (8 tracks)
    🗎 Koenigleopold-Eure_Armut_Kotzt_Mich_An-AT-2013-BCC (12 tracks)
    🗎 Koenigleopold-Eure_Armut_Kotzt_Mich_An (12 tracks)
    🗎 Jeandado - Globale Welt (13 tracks)
    🗎 Hotline Miami OST (23 tracks)
    🗎 Helena Hauff - Discreet Desires (10 tracks)
    🗎 hinterhof (19 tracks)
    🗎 Hotline Miami 2 - Soundtrack (2015) 1 (20 tracks)
    🗎 Gold+Beton 02 (10 tracks)
    🗎 group A - INITIATION (9 tracks)
    🗎 hafen (7 tracks)
    🗎 Gewoelbe (18 tracks)
    🗎 Halloween2 (57 tracks)
    🗎 gewoelbe217 (6 tracks)
    🗎 btf_sommerfest2 (44 tracks)
    🗎 DrumnBass (229 tracks)
    🗎 Good Stuff 7 (11 tracks)
    🗎 gold+beton (9 tracks)
    🗎 Comeme (17 tracks)
    🗎 btf_neo (58 tracks)
    🗎 Cristian Vogel (84 tracks)
    🗎 game tracks (1 tracks)
    🗎 btfweihnachts (60 tracks)
    🗎 campinc (8 tracks)
    🗎 Baumusik (5 tracks)
    🗎 Clipping - CLPPNG (14 tracks)
    🗎 baumusik's dozen - 1st anniversary compilation (9 tracks)
    🗎 btfsommerparty (26 tracks)
    🗎 Border Community (58 tracks)
    🗎 AZ (37 tracks)
    🗎 btf grimme (21 tracks)
    🗎 Albrecht Schrader - Leben in der Großstadt (4 tracks)
    🗎 Alex_Smoke-Vaporub__HAH001_-Promo_CDS-2008-HFT-1 (3 tracks)
    🗎 AWeX_-_Its_Our_Future-(SUPER_DJ_2024)-CDM-FLAC-2001 (1 tracks)
    🗎 antwerpen (53 tracks)
    🗎 baumusik - it is a rose- a raisin - a festive compilation (15 tracks)
    🗎 acephale27 (57 tracks)
    🗎 At the Drive-In - Relationship of Command (13 tracks)
    🗎 Atelier (20 tracks)
    🗎 ADA (50 tracks)
    🗎 Alex_Smoke-Blingkered-_HAH005D_-WEB-2009-XXW (4 tracks)
    🗎 A-Musik (23 tracks)
    🗎 Afreuroparemixes and more (10 tracks)
    🗎 Alex_Smoke_-_Paradolia__2006_ (13 tracks)
🗎 easy (50 tracks)
🗎 medium2 (39 tracks)
🗎 hard2 (13 tracks)
🗎 SARAHBD (25 tracks)
🗎 easy2 (32 tracks)
🗎 medium (47 tracks)
🗎 31.03.2022 (155 tracks)
🗎 kbirthday (26 tracks)
🗎 26.03.2022 (4 tracks)
🗎 30.07.2022 (94 tracks)
🗎 05.03.2022 (21 tracks)
🗎 Acephale_22.01.2022 (65 tracks)
🗎 heavy (6 tracks)
🗎 Acephale30 (36 tracks)
🗎 neumix (16 tracks)
🗎 08.0.8.2022 (94 tracks)
🗀 Ace_20_08_22
    🗎 dance (44 tracks)
    🗎 soft (30 tracks)
🗎 Unbetitelte Liste (2) (0 tracks)
🗎 mix (0 tracks)
🗎 skeelo (0 tracks)
🗎 btf lockdown (45 tracks)</code></pre></details>

**Comment by emmetiray** [comment]
i think this wasnt caused by the change. i checked the same drive in rekordbox software and it showed tracks in the playlists. here is an example screenshot from one of the "broken" playlists on the drive directly out of rekordbox: 
missingtracks_rekordbox

**Comment by emmetiray** [comment]
yeah. seems to have nothing to do with the change. i had a look on an earlier post which i did 18 days ago and i mentioned two of the playlists i mentioned now. probably i missed the other ones which where "broken" back then. if you want to be totally sure i could also install an old version of rekordbox again and check. The earlier post:
earlierpost

**Comment by Holzhaus** [comment]
> Please check if this is correct:
> <details><summary>Playlists with track count</summary>
> <pre><code>🗀 15.07.22
>     🗎 riot code (3 tracks)
> 🗀 jaki_21_05_22
>     🗎 jaki_melow (18 tracks)
>     🗎 jaki2 (29 tracks)
>     🗎 jaki (19 tracks)
> 🗀 18.05.22
>     🗎 plaid - dial p (15 tracks)
>     🗎 otherstuff (10 tracks)
>     🗎 wettrax (33 tracks)
>     🗎 kumo99 (14 tracks)
> 🗎 breakcore_gabba (3 tracks)
> 🗎 10.05.22 (23 tracks)
> 🗀 grime_hardwave
>     🗎 maindir (24 tracks)
>     🗎 TMSV - Jungle- Vol. 2 (3 tracks)
>     🗎 ian shirtman - The Shirt Tape (7 tracks)
>     🗎 Deadcrow - Transmission (3 tracks)
>     🗎 Deadcrow - Lies (1 tracks)
>     🗎 Deadcrow - 2015-2017 (9 tracks)
>     🗎 BEAT PVP - BEAT PVP 1ª EDIÇÃO (16 tracks)
>     🗎 Vinnie Grapes - Radiohooligans (8 tracks)
> 🗀 loststuff
>     🗎 maindir (23 tracks)
>     🗎 Tommy Holohan & Casper Hastings (4 tracks)
>     🗎 The Horrorist (11 tracks)
>     🗎 peryl (4 tracks)
>     🗎 Pavel K. Novalis (1 tracks)
>     🗎 Mode In Gliany (7 tracks)
>     🗎 Mass-X-Odus (1 tracks)
>     🗎 Kas_st (1 tracks)
>     🗎 Jokasti & Nek (1 tracks)
>     🗎 Jacidorex (1 tracks)
>     🗎 Homemade Weapons & Red Army (1 tracks)
>     🗎 Homemade Weapons & Gremlinz (1 tracks)
>     🗎 Homemade Weapons (10 tracks)
>     🗎 Hephaistos (1 tracks)
>     🗎 FSOM (23 tracks)
>     🗎 FRACTIONS (6 tracks)
>     🗎 B2 (1 tracks)
>     🗎 Endlec (1 tracks)
>     🗎 Danilo Incorvaia (4 tracks)
>     🗎 V_A_ Lars Huismann & Chris Koegler, Alignment, T (1 tracks)
>     🗎 Ansome (1 tracks)
> 🗀 oldfolders
>     🗎 Houndstooth (11 tracks)
>     🗎 Jiri Ceiver (25 tracks)
>     🗎 KiNK (15 tracks)
>     🗎 halloween (20 tracks)
>     🗎 Justin Berkovi (71 tracks)
>     🗎 jackwho (18 tracks)
>     🗎 HTH vs HTH (7 tracks)
>     🗎 maindir (49 tracks)
>     🗎 [tiva011] Justin Berkovi - Gravel Heart EP (4 tracks)
>     🗎 _IGOR (2 tracks)
>     🗎 acephale (26 tracks)
>     🗎 15.12.2017 (7 tracks)
>     🗎 v-tracks - limits (5 tracks)
>     🗎 Vtracks (5 tracks)
>     🗎 Vectors 3 (8 tracks)
>     🗎 VA-Phuture_Beats_Vol._1-(DCD089-41802)-2CD-FLAC-1995-dL (40 tracks)
>     🗎 va - kids (soundtrack) (13 tracks)
>     🗎 usbcd (11 tracks)
>     🗎 URBAN HOMES - Centres (5 tracks)
>     🗎 Tube Jerk (20 tracks)
>     🗎 this machine is broken (14 tracks)
>     🗎 The Sound of Belgium (60 tracks)
>     🗎 Terence_Fixmer-Depth_Charged (10 tracks)
>     🗎 telex - remixes (12 tracks)
>     🗎 Studio672 (42 tracks)
>     🗎 Sound Architecture (10 tracks)
>     🗎 schnoerres (5 tracks)
>     🗎 RussianTechno (55 tracks)
>     🗎 Rush Hour (12 tracks)
>     🗎 Quarks - Rehmix (2000) (14 tracks)
>     🗎 Physically Sick - Physically Sick (42 tracks)
>     🗎 Point B - Suicide Beauty Spot (14 tracks)
>     🗎 Physically Sick 2 - Physically Sick 2 (43 tracks)
>     🗎 Palette_All-Stars--After_School_Special-(PAL051)-WEB-2008-dh (3 tracks)
>     🗎 Mr Ozio - Lambs Anger (17 tracks)
>     🗎 nachtigal (26 tracks)
>     🗎 newstuff (7 tracks)
>     🗎 nachtigal2 (38 tracks)
>     🗎 Mr.Oizo-Analog Worms Attack_224kbps_mFY (15 tracks)
>     🗎 marcel (6 tracks)
>     🗎 mix (10 tracks)
>     🗎 MMODEMM (72 tracks)
>     🗎 Missile Recordings (16 tracks)
>     🗎 Marcus Zils Musik (41 tracks)
>     🗎 Lena Willikens - Phantom Dalia Ep (6 tracks)
>     🗎 Kate Tempest-Everybody Down-Paul'sBoutique (11 tracks)
>     🗎 Magazine 18 DigiFiles (4 tracks)
>     🗎 koelncampus (13 tracks)
>     🗎 Lorenzo Senni - Persona (2016) (6 tracks)
>     🗎 khmparty (8 tracks)
>     🗎 Koenigleopold-Eure_Armut_Kotzt_Mich_An-AT-2013-BCC (12 tracks)
>     🗎 Koenigleopold-Eure_Armut_Kotzt_Mich_An (12 tracks)
>     🗎 Jeandado - Globale Welt (13 tracks)
>     🗎 Hotline Miami OST (23 tracks)
>     🗎 Helena Hauff - Discreet Desires (10 tracks)
>     🗎 hinterhof (19 tracks)
>     🗎 Hotline Miami 2 - Soundtrack (2015) 1 (20 tracks)
>     🗎 Gold+Beton 02 (10 tracks)
>     🗎 group A - INITIATION (9 tracks)
>     🗎 hafen (7 tracks)
>     🗎 Gewoelbe (18 tracks)
>     🗎 Halloween2 (57 tracks)
>     🗎 gewoelbe217 (6 tracks)
>     🗎 btf_sommerfest2 (44 tracks)
>     🗎 DrumnBass (229 tracks)
>     🗎 Good Stuff 7 (11 tracks)
>     🗎 gold+beton (9 tracks)
>     🗎 Comeme (17 tracks)
>     🗎 btf_neo (58 tracks)
>     🗎 Cristian Vogel (84 tracks)
>     🗎 game tracks (1 tracks)
>     🗎 btfweihnachts (60 tracks)
>     🗎 campinc (8 tracks)
>     🗎 Baumusik (5 tracks)
>     🗎 Clipping - CLPPNG (14 tracks)
>     🗎 baumusik's dozen - 1st anniversary compilation (9 tracks)
>     🗎 btfsommerparty (26 tracks)
>     🗎 Border Community (58 tracks)
>     🗎 AZ (37 tracks)
>     🗎 btf grimme (21 tracks)
>     🗎 Albrecht Schrader - Leben in der Großstadt (4 tracks)
>     🗎 Alex_Smoke-Vaporub__HAH001_-Promo_CDS-2008-HFT-1 (3 tracks)
>     🗎 AWeX_-_Its_Our_Future-(SUPER_DJ_2024)-CDM-FLAC-2001 (1 tracks)
>     🗎 antwerpen (53 tracks)
>     🗎 baumusik - it is a rose- a raisin - a festive compilation (15 tracks)
>     🗎 acephale27 (57 tracks)
>     🗎 At the Drive-In - Relationship of Command (13 tracks)
>     🗎 Atelier (20 tracks)
>     🗎 ADA (50 tracks)
>     🗎 Alex_Smoke-Blingkered-_HAH005D_-WEB-2009-XXW (4 tracks)
>     🗎 A-Musik (23 tracks)
>     🗎 Afreuroparemixes and more (10 tracks)
>     🗎 Alex_Smoke_-_Paradolia__2006_ (13 tracks)
> 🗎 easy (50 tracks)
> 🗎 medium2 (39 tracks)
> 🗎 hard2 (13 tracks)
> 🗎 SARAHBD (25 tracks)
> 🗎 easy2 (32 tracks)
> 🗎 medium (47 tracks)
> 🗎 31.03.2022 (155 tracks)
> 🗎 kbirthday (26 tracks)
> 🗎 26.03.2022 (4 tracks)
> 🗎 30.07.2022 (94 tracks)
> 🗎 05.03.2022 (21 tracks)
> 🗎 Acephale_22.01.2022 (65 tracks)
> 🗎 heavy (6 tracks)
> 🗎 Acephale30 (36 tracks)
> 🗎 neumix (16 tracks)
> 🗎 08.0.8.2022 (94 tracks)
> 🗀 Ace_20_08_22
>     🗎 dance (44 tracks)
>     🗎 soft (30 tracks)
> 🗎 Unbetitelte Liste (2) (0 tracks)
> 🗎 mix (0 tracks)
> 🗎 skeelo (0 tracks)
> 🗎 btf lockdown (45 tracks)</code></pre></details>

@emmetiray ?

**Comment by emmetiray** [comment]
i went through every playlist on the drive in rekordbox compared it to the playlist you sent. i hope i made no mistake but it seems there are still some things.


folder: loststuff
mode in gliany playlist: 8 tracks (in the playlist you sent: 7 tracks)

folder: oldfolders
the sound of belgium playlist: 61 tracks (in the playlist you sent: 60 tracks) 
physically Sick 2 playlist: 44 tracks (in the playlist you sent: 42 tracks)
kate tempest-everybody down playlist: 12 tracks (in the playlist you sent: 11 tracks)
hinterhof playlist: 20 tracks (in the playlist you sent: 19 tracks)
drumnbass playlist: 230 tracks (in the playlist you sent: 229 tracks)
christian vogel playlist: 85 tracks (in the playlist you sent: 84 tracks)
antwerpen playlist: 54 tracks (in the playlist you sent: 53 tracks)


folder: (mainfolder)
medium2 playlist: 40 tracks (in the playlist you sent: 39 tracks)
mix playlist: 25 tracks (in the playlist you sent: 0 tracks)
skeelo playlist: 5 tracks (in the playlist you sent: 0 tracks)
btf lockdown playlist: 72 tracks (in the playlist you sent: 45 tracks)
neumix playlist: 17 tracks (in the playlist you sent: 16 tracks)
30.07.2022 playlist: 95 tracks (in the playlist you sent: 94 tracks)

folder: Ace_20_08_22
soft playlist: 31 tracks (in the playlist you sent: 30 tracks)

**Comment by emmetiray** [comment]
hope that helps. @Holzhaus

**Comment by Holzhaus** [comment]
Thanks, yes that helps. Apparently the relationship between playlists and tracks is more complicated than the unofficial documentation makes it seem: https://djl-analysis.deepsymmetry.org/rekordbox-export-analysis/exports.html#playlist-entry-rows

I think we should merge this PR now, and open a separate ticket for the missing tracks issue, which will probably require some reverse-engineering work.

**Review by Swiftb0y — APPROVED** [review]

**Pull request merged**
