### PR TITLE
Overview: allow custom range opacity, improve mark rendering

### PR DESCRIPTION
**Pull request by ronso0**
https://bugs.launchpad.net/mixxx/+bug/1842338
[Zulip: Improve visibility of loops on overview waveforms](https://mixxx.zulipchat.com/#narrow/stream/247619-design/topic/Improve.20visibility.20of.20loops.20on.20overview.20waveforms)

Before, marker contrast borders looked like double strokes when `color.isDimColor()` which made them appear like a tiny ranges. Due to rounding issue it was also not drawn consistently: sometime it's a single stroke at one side, sometimes it's a double stroke.

- [x] allow custom opacities for disabled & enabled mark ranges, allows more appearance control in conjunction with different range colors https://github.com/mixxxdj/mixxx/pull/3003/commits/427f3f8dbf7370833ffd808fe542ff5febcdb072: `<MarkRange>` accepts nodes `<Opacity>` and `<DisabledOpacity>`, both default to `0.5` (0.4 and 0.2 before)
- [x] improve mark rendering: Before, marker contrast borders looked like double strokes when `color.isDimColor()` which made them appear like a tiny ranges. Due to rounding issue it was also not drawn consistently: sometime it's a single stroke at one side, sometimes it's a double stroke.
- [x] move drawing of playedOverlay & playPosition to separate functions
- [x] add skin changes
- [ ] test & adjust opacity values

before: Note that 2, 3, 6 & 8 are all hotcues with the same color
image
this PR:
image

* draw mark ranges _behind_ waveform ?
ranges render may-be relevant parts of waveform unreadable
ranges stand out to much over played part of the overview

### CODE REVIEW

**Comment by Holzhaus** [comment]
Is hotcue 8 a saved loop?

**Comment by ronso0** [comment]
Nope, it's just a loop_in at exactly `8`, though we could use [that icon](https://unicode-table.com/en/21BB/) for saved loops.
loop_in (without an icon) would be invisble otherwise.
still experimenting with 
> * draw mark ranges behind waveform ?

**Comment by Holzhaus** [comment]
For saved loops I experimented with a half-transparent gradient for disabled saved loops, maybe you want to check that out over at #2194.

**Comment by ronso0** [comment]
> For saved loops I experimented with a half-transparent gradient for disabled saved loops, maybe you want to check that out over at #2194.

I see this only affects the scrolling waveforms. Also, once the loop display switched from a plain translucent overlay to a gradient.

In the overview we too little space (horizontally on small screens, vertically in mini decks) and to improve visibility I think we can play with the opacity and the stacking order first, before introducing gradients.

**Comment by ronso0** [comment]
This is ready to test with LateNight. Colors are adjusted for PaleMoon only.
Loop_in has an icon now, please test that @Be-ing

**Comment by ronso0** [comment]
@Be-ing @daschuer Please test if the range opacities in Deere & Shade work for you.
If you suggest different values please post a screenshot as wel so we can compare the visuals. Thanks!

**Comment by ronso0** [comment]
We can also discuss if/how to syncronize the range display n all skins.
In LateNight I've the overview loop_out marker unless the loop is enabled.
IIRC in Deere and Shade there are no overview loop markers. We should add the so we jump to it like to hotcues in all skins.

**Comment by ronso0** [comment]
Any comments on this, and on the loop_out proposal above?

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
