### PR TITLE
Use sqrt-based calculation for non-GL RGB waveform

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
This should yield the same behavior as the GL renderer. Square root based calculations makes beat clear.

PS: Backport to HSV renderer too?

### CODE REVIEW

**Comment by Be-ing** [comment]
I tested and it does now look the same as the RGB (GL) renderer. I noticed that the RGB (GL) and RGB (GLSL) renderers do not look the same. I personally prefer the look of RGB (GLSL).

**Comment by ishitatsuyuki** [comment]
I'm not sure what's the mathematical difference of GL and GLSL renderer. I didn't notice a big difference between them, so I thought it is precision loss. Am I wrong?

**Comment by Be-ing** [comment]
Here are what they look like for me:
GL:
gl
GLSL:
glsl

**Comment by ishitatsuyuki** [comment]
Possible causes:
- Alpha
- Method of drawing multiple samples per line (QPainter renderer use max, GL renderer blends, didn't look at GLSL renderer)

**Comment by Be-ing** [comment]
CPU RGB in this PR:
rgb
GL:
gl
GLSL:
glsl

**Comment by ishitatsuyuki** [comment]
Uh, lmao, nobody reminded me not removing the debug printf :P

**Comment by ishitatsuyuki** [comment]
@daschuer review?

**Comment by daschuer** [comment]
Thank you for this PR and signing the Contributor Agreement. 

Even though it is improved, it seams there is an issue with the stereo signal and a low resolution. 

Old: 
sw-old

New:
sw

GL:
gl

GLSL:
glsl

Do you have fun to look into this, or should we merge this as it is?

**Comment by daschuer** [comment]
sqrtf() is not a CPU saver.  Did you consider to use a approximating function? 
I think math exactness does not matter here.

**Comment by ishitatsuyuki** [comment]
Regarding the low resolution, I currently have no idea and I think it's fine to merge as-is as there's no obvious regression.

I don't think adding a custom sqrt is important; we're only doing it a few times per frame, and it's also what GL renderer is doing. What's more, the code bloat caused by a (probably copied) sqrt approximation algorithm is a quite big drawback.

**Comment by daschuer** [comment]
OK, LGTM!

**Comment by Be-ing** [comment]
@ishitatsuyuki, have you signed the [contributor agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ)? In summary it gives permission to license your work under the GPL v2 or later with an exception to allow it to also be distributed in the Mac App Store (which has terms incompatible with the GPL).

**Pull request merged**
