### PR TITLE
LateNight: Add source xcf and svg files for some elements

### PR DESCRIPTION
**Pull request by ywwg**

### CODE REVIEW

**Comment by sblaisot** [comment]
I'm afraid everything in `res/skins` will end up installed on end user computers.

Shouldn't we move that outside of `res`  or update our packaging systems to blacklist some directories like `sources` ?

**Comment by ywwg** [comment]
I asked about this on zulip and this is what @Be-ing suggested.  we have developer_skins but that's not quite right.  I do think we should have these in version control somewhere

**Comment by Be-ing** [comment]
> blacklist some directories

We could, but these file are only ~600 kb :man_shrugging:

**Comment by sblaisot** [comment]
I totally agree that these files should be in version control system.
I simply don't think they should be installed on every computer, aindependantly of their size.

Why not simply put them in `res/images/skins` ?

**Comment by ywwg** [comment]
done

**Comment by sblaisot** [comment]
LGTM, thank you !

**Pull request merged**
