### PR TITLE
Tango: ClubTwist theme is default, remove Classic theme

### PR DESCRIPTION
**Pull request by ronso0**
As porposed earlier, I remove the Classic scheme from Tango as it was derived from and too similiar to Deere. ClubTwist scheme fits the intended use case much better anyway.

### CODE REVIEW

**Comment by Be-ing** [comment]
I must have missed the PR where you added the ClubTwist color scheme. It looks essentially the same. As far as I can tell, the only difference is swapping which decks are blue and which are purple?

**Comment by ronso0** [comment]
Yup, colors of deck 1&2 are purple (2 decks is the most used layout 2 guess) which is bit easier on they eyes in my experience.
And the library focus borders are thicker which is very helpful in club situations.

**Comment by ronso0** [comment]
I might also make decks 3&4 green (like in LateNight?) and entirely remove the Deere'ish blue as it is too pale IMO and is really annoying me over the years.
This will make Tango a bit warmer in general.

**Comment by Holzhaus** [comment]
This now conflicts with master.

**Comment by ronso0** [comment]
Updated deck colors:
purple for deck 1/2
dark green for deck 3/4
image

I'll test this in a nightly session soonish to see if the colors work well.

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you. Does someone insist on keeping the classic theme as non-default colorscheme (I don't)? What happens when users that use Tango upgrade from 2.2? Will it switch over to ClubTwist automatically?

**Comment by ronso0** [comment]
> What happens when users that use Tango upgrade from 2.2?

dlgprefinterface.cpp takes care of that, the first (or the main) theme is selected.

**Comment by Holzhaus** [comment]
> Does someone insist on keeping the classic theme as non-default colorscheme (I don't)?

Apparently not. I'll go ahead and merge now.

**Comment by ronso0** [comment]
Thx!

> I'll test this in a nightly session soonish to see if the colors work well.

Didn't happpen, yet, as I'm with LateNight Flip and medium decks when I play _for real_.
I fear the colors of deck 3/4 are too bright, but that can be fixed anytime during beta.

**Pull request merged**
