### PR TITLE
Update README.md: added Mastodon link

### PR DESCRIPTION
**Pull request by foss-**
adding Mastodon to the social links

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Welcome as code contributor!
As a first-time contributor we need you to sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

**Comment by foss-** [comment]
Done

**Comment by JoergAtGithub** [comment]
I changed the target from Main to 2.4. But the code needs to be rebased to this branch too: https://github.com/mixxxdj/mixxx/wiki/Using-Git#targeting-another-base-branch

**Comment by daschuer** [comment]
I have rebased this on 2.4 and pushed it directly: 
https://github.com/mixxxdj/mixxx/commit/e154c5b03fe18bd30e452cc02e62a5a850901036
Thank you.

**Comment by ronso0** [comment]
Congratulations @foss- for your first PR!

**Pull request closed without merging**
