### PR TITLE
FAAD2 Patch for 2.3

### PR DESCRIPTION
**Pull request by uklotzde**
Follow-up of #2850. Once again I missed to adjust the target branch.

Same source branch and commits, different target branch.

### CODE REVIEW

**Comment by daschuer** [comment]
Ups, I missed that either. Sorry.

**Review by daschuer — APPROVED** [review]
LGTM

**Comment by daschuer** [comment]
Strange: 

```
The following tests FAILED:

	175 - DurationUtilTest.formatSecondsLong (Failed)

Errors while running CTest

The command "ctest" exited with 8.
```

**Comment by Holzhaus** [comment]
Just a fluke again. I guess xvfb is not that stable. Can we disable GUI/X support except for the tests that actually need it?

```
175/618 Test #175: DurationUtilTest.formatSecondsLong ..............................................***Failed    0.07 sec
qt.qpa.screen: QXcbConnection: Could not connect to display :99.0
Could not connect to any X display.
```

**Pull request merged**
