### PR TITLE
add LateNight (64 Samplers)

### PR DESCRIPTION
**Pull request by ronso0**
superseeds #11105 

Users can now choose between 4, 8, 16, 32, 48 or 64 samplers.

- [ ] add previews with many samplers

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
LGTM, Do you want to add the screenshot before merge or in an a separate action for all skins?

**Comment by ronso0** [comment]
hmm, true, we can merge now and I'll add the screenshots later on.

**Comment by daschuer** [comment]
OK, Thank you.

**Comment by ronso0** [comment]
pushed a fixup cf22f6c80afcd5822f7a73f4c4fe26f07fade0e8

**Pull request merged**
