### PR TITLE
fix shade sampler at minimal width [2.2]

### PR DESCRIPTION
**Pull request by nopeppermint**
before:

before
after:

after

### CODE REVIEW

**Comment by nopeppermint** [comment]
affects 2.1 as well
so might be a candidate for 2.1.6

**Comment by nopeppermint** [comment]
reminder: please cherry-pick also into branch 2.1

**Comment by daschuer** [comment]
I will care for it.  .. done. Thank you.

**Comment by nopeppermint** [comment]
thanks

**Pull request merged**
