### PR TITLE
Retire Ubuntu Focal

### PR DESCRIPTION
**Pull request by daschuer**
This stops building Ubuntu Focal on our nighty PPA 
This is a prerequisite for merging https://github.com/mixxxdj/mixxx/pull/4810

### CODE REVIEW

**Review by Swiftb0y — APPROVED** [review]
waiting for ci

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you.

**Comment by ronso0** [comment]
From looking at #4810 it's not clear what this is about.
Is it C++20 / gcc10?
https://mixxx.zulipchat.com/#narrow/stream/247620-development-help/topic/Deprecating.20ubuntu.2020.20early

**Comment by Swiftb0y** [comment]
Both I guess. C++20 requires at modern enough gcc version (which is not available on focal).

**Comment by ronso0** [comment]
> This stops building Ubuntu Focal on our nighty PPA
This is a prerequisite for merging https://github.com/mixxxdj/mixxx/pull/4810

It's not clear what change of #4810 exactly requires retiring Focal (that conversation is rather long and that info doesn't stick out).
I know Focal is EOL now, I wanted to know what I can do to still build `main` on Focal.

**Comment by Swiftb0y** [comment]
Ah, I was pushing heavily to use `std::span<CSAMPLE>` instead of the `CSAMPLE* pIn, int num` paradigm. Unfortunately, that requires a version of the standard library that only works since gcc 10. So if you want to build the newest `main` on focal, you can try to get mixxx to compile using gcc10. Alternatively, you can upgrade to Jammy (not sure how feasible that is, I don't have enough experience with ubuntu).

**Comment by ronso0** [comment]
Alrigth, that's the route I planned to go anyway, or try clang.

> Alternatively, you can upgrade to Jammy (not sure how feasible that is, I don't have enough experience with ubuntu).

IME the core system upgrade did kinda works, with an unmodded system there may be no issues But mods & tweaks related to hardware and workflow tend to break. Most issues are obvious and noticed right away, though the annoying part is the stuff that breaks when I'm really not in the mood for fixes and reboots.
That might be different nowadays.
Anyway, to have a clean base I'll do a fresh 22.04 install _some day_ and hopefully remember to document _all_ tweaks. "Some day" is usually during (central-european) autumn/winter ; )

**Comment by daschuer** [comment]
I did a branch that allows to build main with focal: https://github.com/daschuer/mixxx/tree/focal_main

**Comment by ronso0** [comment]
Thanks, though that won't help with building PRs.

**Comment by daschuer** [comment]
The situation is currently a bit cumbersome. We have merged this, to not put extra work on @Swiftb0y and @davidchocholaty which is a fully valid request and covered 100 % by our Minimum Requirement policy. However the merged class is not even used right now, and the patch required to keep Ubuntu Focal working is only minimal. 

Since 22.4.1 is released a few days ago, my Ubuntu Focal is offering me an update. I will Upgrade in the next month or such when I am in a good mood fro that. In the meantime I will maintain the branch. 

I feel sorry that we now put extra work on @ronso0 who has many open PRs and will only find time for the upgraded in autumn/winter. 

Since a 2.4 cut out is overdue since 8 months. How about this: 
* Cut out the 2.4 branch now 
* Merge my focal franch to this branch and revert this PR there 

This will allow @ronso0 continue his wonderful polishing work without hassle towards a 2.4 branch and doe not stop @Swiftb0y using c++20 in main. 

What do you think?

**Comment by Swiftb0y** [comment]
Mhmm. While I have nothing in principle against cutting a 2.4 branch now, this results in the case where we have the rubberband stretcher in the release which is still completely unpolished. I guess we can live with that, trying to find workaround is not worth it. 
So I guess we decide to postpone C++20 support to 2.5?

**Comment by daschuer** [comment]
A cut out alone means we polish for a beta release. We can decide what is required to do. 
For me, It is OK to have a pitch shift effect in the current state in a beta release. It is already useful. 
If it turns out to be confusing for user or even break things we can disable during the beta phase. 

> So I guess we decide to postpone C++20 support to 2.5?

This statement does not quite fit, because we have C++20 support already. Nothing is "postponed". The crucial question is more like: "Will put the Focal support in 2.4 put extra work on us". I consider not, because bug fixes in a beta branch will probably not required features not supported in Focal. If this would be the case, I would like to drop the Focal support from the beat.

**Comment by ronso0** [comment]
Don't worry, and please don't complicate things because I'm not up to date.
Looks like I'm building with g++10 right now, and no complaints about missing `<span>` anymore...

**Comment by Swiftb0y** [comment]
> This statement does not quite fit, because we have C++20 support already. Nothing is "postponed".

Well, as I see it, "Ubuntu Focal support $\centernot\iff$ C++20 support". So if we keep focal support in the beta, we can't merge polishing PRs which make use of C++20 features. And since we don't want to drop support for a ubuntu version as part of a bugfix release, that means we can't put any C++20 into any 2.4.x release. So that's why that would postpone any use of C++20 to 2.5. 

So yes and no, ubuntu focal support for 2.4 simply means not being able to use new features for a longer than time in some circumstances (2.4.x PRs). Which I personally find quite annoying.

**Comment by Swiftb0y** [comment]
> Don't worry, and please don't complicate things because I'm not up to date.

Well, I acknowledge that you are probably not alone. There are a lot of users that might want to stay on focal a little longer...

>  Looks like I'm building #4810 and `main` with g++10 right now, and no complaints about missing `<span>` anymore...

I didn't know it was that easy to just use gcc10... What changes did you make? While gcc10 is not fully C++20 compliant, it implements about 90%, which is good enough for now IMO.

**Comment by ronso0** [comment]
> What changes did you make?

https://mixxx.zulipchat.com/#narrow/stream/247620-development-help/topic/Deprecating.20ubuntu.2020.20early/near/293636016
> this is how I set up to use g++10 and gcc10 with Ubuntu Focal Fossa 20.04
> * install g++ & gcc 10.3 from focal-updates repo
> * use update-alternatives to use v10.3 by default, as described here https://askubuntu.com/a/1316782 (setting all g++/gcc-10 paths via cmake-gui didn't work out, it used 9.4 instead)

**Comment by daschuer** [comment]
> Well, as I see it, "Ubuntu Focal support !=
C++20 support"

That's true. We just need to predict how likely it is that we will use c++20 features not supported by gcc 9.4 in polish releases. 
Since we have now two solutions for keeping Focal compiling, there is no need to decide that in a rush. I think we need anyway a beta phase of 6 months, so the problem will fade out slowly anyway, before we release 2.4.

**Comment by Swiftb0y** [comment]
Sure, lets cut the 2.4 beta now. If  I get to annoyed by the lack of C++20 in 2.4, we can still drop focal support during the beta.

**Pull request merged**
