### PR TITLE
Fix broken build: Float conversion warnings

### PR DESCRIPTION
**Pull request by uklotzde**
Caused by #2940

### CODE REVIEW

**Comment by Holzhaus** [comment]
Pinging @ywwg manually to make sure it passes his email filter :-)

**Review by Holzhaus — APPROVED** [review]

**Comment by Holzhaus** [comment]
LGTM, I'll just merge this for now. @ywwg if this fix is incorrect please open a new PR.

**Review by Holzhaus — CHANGES_REQUESTED** [review]
Yikes, CI disagrees:

```
	254 - EngineSyncTest.ZeroLatencyRateChangeNoQuant (Failed)

7242	255 - EngineSyncTest.ZeroLatencyRateChangeQuant (Failed)

7243	256 - EngineSyncTest.ZeroLatencyRateDiffQuant (Failed)
```

**Comment by uklotzde** [comment]
@Holzhaus Sorry for not testing this properly before publishing the PR.

**Comment by Holzhaus** [comment]
> @Holzhaus Sorry for not testing this properly before publishing the PR.

Sorry for not merging #2940 into `2.3` locally before hitting merge on GitHub. Shit happens.

**Comment by uklotzde** [comment]
I have only fixed the failures. But using EXPECT/ASSERT_EQ for any of the results is wrong in these tests.

**Review by Holzhaus — APPROVED** [review]
LGTM, i pulled it into 2.3 locally and it works fine. Waiting for CI.

**Pull request merged**
