### PR TITLE
cmake default_option() parentheses

### PR DESCRIPTION
**Pull request by daschuer**
I have found some time to dig down the latest cmake issue. It turns out that it is an issue in our own module, but the parentheses are not required anyway. 
This PR fixes both. 

The original cmake_dependent_option() also suffers the issue, I have reported a bug and issued a PR with the fix:
https://gitlab.kitware.com/cmake/cmake/-/issues/22303

### CODE REVIEW

**Comment by Holzhaus** [comment]
But the actual notation should be `UNIX;NOT APPLE;MP4_FOUND OR MP4v2_FOUND` IIRC. Because the semicolon is like an `AND`.

Check the example at: https://cmake.org/cmake/help/latest/module/CMakeDependentOption.html

So the bug was us using braces, which were redundant anyway.

**Comment by daschuer** [comment]
> But the actual notation should be UNIX;NOT APPLE;MP4_FOUND OR MP4v2_FOUND IIRC.

That is part of the first commit.

**Review by uklotzde — APPROVED** [review]
@Holzhaus Merge?

**Comment by Holzhaus** [comment]
Fix looks good, didn't test yet. I just copied the code from cmake_dependent_option. Unsure if we want to mess around with that code or just not use parentheses which are unnecessary anyway. But if it works, feel free to merge it.

**Comment by daschuer** [comment]
My upstream patch is now merged: 
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6225/diffs

**Comment by Holzhaus** [comment]
The upstream implementation uses a temp var. Should we do, too?

**Comment by Holzhaus** [comment]
Anyway, no need to hold up this PR. But IMHO we should follow the upstream implementation unless we have a good reason not to.

**Pull request merged**
