### PR TITLE
Revert "Handle not supported files when dragging to waveforms and spinnies"

### PR DESCRIPTION
**Pull request by ywwg**
Reverts mixxxdj/mixxx#13208

Tested manually, this fixes waveform drag breakage

### CODE REVIEW

**Comment by acolombier** [comment]
Looks like merging this would un-fix #13206. 
Looking at the code change, the bug appears to be fairly trivial to fix. Shall we consider fixing it instead of reverting entirely?

**Comment by ywwg** [comment]
My preference when there is a breakage is to revert first and then work on a corrected fix, rather than try to "fix forward" 

(example reasoning: https://www.linkedin.com/pulse/service-recovery-rolling-back-vs-forward-fixing-mohamed-el-geish)

**Comment by ywwg** [comment]
too often, what seems to be a simple fix on top of a breakage ends up making the situation worse, and then you have to fix on top of that.... unless the cost of rolling back is huge, it's best to do that first.

**Comment by daschuer** [comment]
@acolombier If you have a fix under your thumb, we may test it and decide. Both are easy to test IMHO.

**Comment by acolombier** [comment]
I don't yet, but might be able to get one together later today. Happy with the revert so this isn't a blocker

**Comment by ywwg** [comment]
can someone approve so we can fix the 2.4 branch then?

**Review by acolombier — APPROVED** [review]

**Comment by Swiftb0y** [comment]
fyi @ywwg it seems like you're pushing your personal branches upstream. Check your get config please.

**Comment by daschuer** [comment]
The fix is here: https://github.com/mixxxdj/mixxx/pull/13275

**Pull request merged**
