### PR TITLE
Loopescape Test Fix 

### PR DESCRIPTION
**Pull request by daschuer**
Try to fix the test fails reported in https://github.com/mixxxdj/mixxx/pull/1487#issuecomment-359367301

### CODE REVIEW

**Comment by uklotzde** [comment]
Still failing with a rounding error:
```src/test/looping_control_test.cpp:538: Failure
The difference between 200 and m_pChannel1->getEngineBuffer()->m_pLoopingControl->getCurrentSample() is 1, which exceeds kLoopPositionMaxAbsError, where
200 evaluates to 200,
m_pChannel1->getEngineBuffer()->m_pLoopingControl->getCurrentSample() evaluates to 199, and
kLoopPositionMaxAbsError evaluates to 1.0000000000000001e-09.
src/test/looping_control_test.cpp:554: Failure
The difference between 200 and m_pChannel1->getEngineBuffer()->m_pLoopingControl->getCurrentSample() is 1, which exceeds kLoopPositionMaxAbsError, where
200 evaluates to 200,
m_pChannel1->getEngineBuffer()->m_pLoopingControl->getCurrentSample() evaluates to 199, and
kLoopPositionMaxAbsError evaluates to 1.0000000000000001e-09.
```

**Comment by daschuer** [comment]
Strange. Is this probably caused by this commit: af218bc ?
It looks like there is some unintended remaining integer rounding in place, which looses one sample. Maybe because the rounding error in the previous test. If this where an intentional rounding, it should probably round to an even value.

**Comment by uklotzde** [comment]
@daschuer If I revert this commit the test succeeds.

**Comment by daschuer** [comment]
I have got it. A "real" bug: seekInsideAdjustedLoop() has truncated the result to an int. Fixed.

**Comment by uklotzde** [comment]
LGTM 👍  Waiting for the build server to finish.

**Pull request merged**
