### PR TITLE
CMake: Fix dependency detection

### PR DESCRIPTION
**Pull request by Holzhaus**
Prerequisite for the vcpkg-based buildenv.

### CODE REVIEW

**Comment by Be-ing** [comment]
```
   Target "mixxx-test" links to target "Vorbis::vorbisenc" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:1369 (add_executable):
  Target "mixxx-test" links to target "Vorbis::vorbisenc" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:358 (add_library):
  Target "mixxx-lib" links to target "Vorbis::vorbisenc" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:1125 (add_executable):
  Target "mixxx" links to target "Vorbis::vorbisenc" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

**Comment by Holzhaus** [comment]
I suspected this because our static libs are weirdly linked. That's why I put this into a separate PR ;-)

**Comment by Be-ing** [comment]
Are you sure there isn't a bug in your new modules?

**Comment by Be-ing** [comment]
This needs to be merged at the same time as switching to the vcpkg dependencies, so I'm closing this in favor of #3594.

**Pull request closed without merging**
