### PR TITLE
change default skin to LateNight

### PR DESCRIPTION
**Pull request by Be-ing**
Thanks to @ronso0's hard work on this skin for Mixxx 2.3!

As [discussed on Zulip](https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Default.20Skin)

### CODE REVIEW

**Comment by Be-ing** [comment]
Any objections?

**Comment by ronso0** [comment]
Even if we don't expect any, let's keep this open for two days at least so everyone not following the discussion on Zulip has a chance to object.

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you!

**Comment by Holzhaus** [comment]
I think a month is enough time to object, I'll merge now.

**Pull request merged**
