### PR TITLE
Add warnign when trying to enable AutoDJ with left & right deck

### PR DESCRIPTION
**Pull request by MetriSomesh**
Added warning message when trying to enable AutoDJ if there's no left & right deck.

### CODE REVIEW

**Comment by daschuer** [comment]
Cool, that's looks better. Now you just need to fix the indentation of the whole switch case block.

**Comment by MetriSomesh** [comment]
@ronso0  @daschuer  can you merge this pull request?

**Comment by MetriSomesh** [comment]
@daschuer  After fixing the indentation while the time of push request its saying "Everything up-to-date". What to do?

**Comment by ronso0** [comment]
"Everything up-to-date" will be printed _only if you didn't commit changes_.

The procedure is like this:
* fix indentation
* `git add -p` (confirm all changes you want to commit)
* `git commit --amend` (here this is okay, i.e. will not create issues for reviewers, because the diff of this PR is small)
* `git push -f [your-remote] warning-msg`

**Comment by MetriSomesh** [comment]
@ronso0  How to get remote branch?

**Comment by daschuer** [comment]
Just origin

**Comment by daschuer** [comment]
Git should already know it soba `git push -f` should do the trick.

**Comment by ronso0** [comment]
> @ronso0 Which remote branch ?

**Your** remote repo = your mixxx fork, usually called "origin".

> Git should already know it soba git push -f should do the trick.

Git only knows if you configured it accordingly, see https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-git and please go trough the tutorials linked in that page https://github.com/mixxxdj/mixxx/wiki/Using-Git#Tutorials

**Comment by MetriSomesh** [comment]
@ronso0  I have read all of it. And still its giving everything is up-to-date

**Comment by daschuer** [comment]
Do you see your commit with `gitk`? 
what is the output of `git branch`?

**Comment by MetriSomesh** [comment]
@daschuer  output of git branch : warning-msg

**Comment by daschuer** [comment]
and
`git diff``

**Comment by MetriSomesh** [comment]
@daschuer git diff showing nothing, but I have edited the file

**Comment by daschuer** [comment]
"Local changes to index but not committed" is the hint. 
This means the changes are in the staging area. Now you need to make a commit of them. 
```
git commit --amend
git push -f
```

**Comment by ronso0** [comment]
also very useful:
`git status` to see the current status at a glance, e.g. overview of staged and unstaged changes.

**Comment by MetriSomesh** [comment]
@daschuer  I have commited the changes, I know about git status and I make use of that and I tryied --amend and force push as well nothing is changing in the push request. It always says Everything is up-to-date

**Comment by daschuer** [comment]
I am out of ideas. Maybe you can use the edit function in GitHub to create a PR.

**Pull request closed without merging**
