### PR TITLE
Late night coverart splitter

### PR DESCRIPTION
**Pull request by ferranlala**
*Adds a splitter between coverart and library sidebar in LateNight.
https://bugs.launchpad.net/mixxx/+bug/1517649

*Adds a new <Collapsible> tag to <Splitter> to specify which children can be collapsed.

 *Make coverart non collapsible in all skins, since we have the CO to show/hide it.

### CODE REVIEW

**Comment by Be-ing** [comment]
Please include a screenshot with PRs that change the GUI.

**Comment by ferranpujolcamins** [comment]
captura de 2016-04-07 09 48 08
captura de 2016-04-07 09 51 10

**Comment by ferranpujolcamins** [comment]
This is ready to merge.

**Comment by ywwg** [comment]
Thanks for doing this.  One more check before I merge, can you show me what mixxx looks like on first-start with this change?  Like, move your ~/.mixxx folder to ~/.mixxx-divert and let mixxx start up without any settings whatsoever.  I just want to make sure that the default sizes and settings are still good

**Comment by ywwg** [comment]
(that has been a big problem in the past)

**Comment by ferranpujolcamins** [comment]
This is what Mixxx looks like on a first start with the skin at its minimum size.
captura de 2016-04-10 18 55 30

And this is maximized (screen resolution 1920x1080).
captura de 2016-04-10 18 55 33

**Comment by ywwg** [comment]
looks good, thanks!

**Pull request merged**
