### PR TITLE
Changelog 2.4

### PR DESCRIPTION
**Pull request by daschuer**
Another update.

### CODE REVIEW

**Comment by ronso0** [comment]
recent merge of 2.3 (respectively the conflict resolution commit fail to build:
https://github.com/mixxxdj/mixxx/commit/6589f5d2dc9ccdb8f33a239c59876cb359d9351b

**Comment by daschuer** [comment]
Now it is working again. I must have failed to amend my last changes after testing.

**Comment by ronso0** [comment]
okay, triggered a re-run since pre-commit also failed.

and there's a conflict now.

**Review by ronso0 — APPROVED** [review]

**Comment by ronso0** [comment]
@mixxxdj/developers Let's please make more use of milestones and the `Changelog` label

**Comment by daschuer** [comment]
The 2.4 version of the Changelog still contains all PRs. At one point we need to decide which are really relevant and remove the others. IMHO we can at least remove the collections of PRs without description. This is basically my staging area for removal.

**Pull request merged**
