### PR TITLE
This fixes Auto DJ stop after the track lengh changed 

### PR DESCRIPTION
**Pull request by daschuer**
This likely fixes https://github.com/mixxxdj/mixxx/issues/11448
All positions that are used in Auto DJ are now clamped to the track end. 
This ensures that the Auto DJ keeps going even if a faulty track is played. 

~~This also refreshes the invisible AudibleSound cue when the user re-analyzes waveforms.
Before, the only way to reset this cue was to reset either intro or outro, which they might want to keep.~~

### CODE REVIEW

**Comment by daschuer** [comment]
I have moved the Audible Sound cue reset commit to https://github.com/mixxxdj/mixxx/pull/11482
This way this PR becomes a pure Bug-Fix.

**Review by Swiftb0y — APPROVED** [review]
LGTM as a bandaid fix. In the future we really need to come up with a clear way of invalidating and regenerating track-related data. Otherwise checks like these will get out of hand really quick.

**Review by ronso0 — COMMENTED** [review]
LGTM, just some ideas for improvement

**Comment by ronso0** [comment]
Whoops, too late...

**Pull request merged**
