### PR TITLE
LateNight: fix & rearrange Sync/Leader buttons, side by side

### PR DESCRIPTION
**Pull request by ronso0**
**Edit: final icons**
image
image

image

Please test if this icon works.
If so I'll use it for the other skins, too.

Btw it's not clear to me what the dim state does -- the tooltip doesn't clarify that either.
@ywwg Can you explain / improve that?

### CODE REVIEW

**Comment by Holzhaus** [comment]
> Btw it's not clear to me what the dim state does -- the tooltip doesn't clarify that either.

I don't know if I understand your question correctly, but there are 3 sync leader states:

- Follower: this deck follows the clock of another deck (the sync leader) 
- Leader: this deck is the sync leader. All other decks will follow this deck's clock. The leader can be:
  - Implicit leader: the leader was picked automatically by Mixxx
  - Explicit leader: the leader was picked explicitly by the user

All of this only makes a difference when at least one of the sync decks has a non-const beatmap. The leader deck will play unchanged, the other decks (followers) will be timestretched so that the beats align. 

These playback speed changes are much more noticable on some tracks than on others.

Setting the leader explicitly is useful when one track is just a drum loop and the other one has melody. In such a case I'd set the melody track as leader to prevent an "old tape effect" (wow an flutter), because small tempo changes will be much less noticable on the drum track.

**Comment by ronso0** [comment]
Great, thanks for the summary @Holzhaus 

Leader is implicit if Sync is locked on 2+ decks.
Leader is explicit if the user wants that.
From explicit I can switch back to implicit. Then Mixxx can make any other deck the implicit leader if some conditions are met?

**Comment by ronso0** [comment]
>|  Files with Coverage Reduction | New Missed Lines | % |
> | :-----|--------------|--: |
> | [src/engine/cachingreader/cachingreaderworker.cpp](https://coveralls.io/builds/41456216/source?filename=src%2Fengine%2Fcachingreader%2Fcachingreaderworker.cpp#L121) | 2 | 63.48% |

???

**Comment by daschuer** [comment]
I have played a bit with this and unfortunately the follower state is not clear for me. The clock is too dominant in that case.
grafik 
How about this, dimm the inactive clock and remove it in the follower case.  
In  this case the orange clock moves around which looks nice IMHO.

**Comment by ywwg** [comment]
>  @ywwg Can you explain / improve that?

dim state is "soft leader", which is when Mixxx picks which deck is the leader.  Bright state is when the user picks an explicit leader.  Users should normally be ok with whatever leader Mixxx picks, and on rare occasion they may want to pick something explicit.  

Note that if none of the decks are soft leader, the Internal Clock is actually being selected.  We will eventually need a user interface for the Internal Clock (which is just a bpm selection and sync button -- Traktor has the exact same thing)

**Comment by ywwg** [comment]
I like the idea of adding / removing the clock

**Comment by ywwg** [comment]
lol I didn't scroll up -- thanks @Holzhaus for the great explanation!

**Comment by ywwg** [comment]
>  From explicit I can switch back to implicit. Then Mixxx can make any other deck the implicit leader if some conditions are met?

Yes, any deck with sync activated, that is playing, has a bpm, and is audible, is a candidate to be implicit leader. If any of these conditions changes the sync code will magically find the next best deck :)

**Comment by ronso0** [comment]
Passing the clock around sounds reasonable, but there shouldn't be a blank button, = the button icon shouldn't change either IMO.
If Sync lock is enabled on 2+ decks one deck (implicit leader) would have a lit, blank button next to Sync and you'd have to look at other decks to know what that icon would be.
That is confusing.

**Comment by daschuer** [comment]
The wall clock icon is confusing alone ;-)

**Comment by daschuer** [comment]
But yes, that is true. Can we visualize the token passing differently?

**Comment by ronso0** [comment]
I added the crown icon for testing, select "PaleMoon -crown" theme.

**Comment by ronso0** [comment]
> But yes, that is true. Can we visualize the token passing differently?

I have no idea, yet

**Comment by Holzhaus** [comment]
> > But yes, that is true. Can we visualize the token passing differently?
> 
> I have no idea, yet

My suggestion would be to make the icon black on dark gray for followers or sync disabled (white icon is too prominent), black on yellow (or a less red orange tone) for implicit leader, black on red for explicit leader.

**Comment by ronso0** [comment]
outline for implicit leader:
image

> My suggestion would be to make the icon black on dark gray for followers or sync disabled (white icon is too prominent), black on yellow (or a less red orange tone) for implicit leader, black on red for explicit leader.

okay, so I'll make a less prominent icon for the follower/disabled state.

**Comment by ywwg** [comment]
I think we've done sufficient bikeshedding for this first implementation -- let's try living with it in HEAD for a while and see how we like it

**Comment by ronso0** [comment]
alrighty, so I'll compress this and let you know when it's ready

**Comment by ronso0** [comment]
done. please test once more.

**Comment by Holzhaus** [comment]
Thanks, LGTM. We can still change stuff later on if we deem it necessary.

Some warnings, but probably unrelated to this PR:
```
warning [Main] /home/jan/Projects/mixxx/src/skin/legacy/legacyskinparser.cpp:2038 SKIN ERROR at skin:/decks/rate_controls_compact.xml:98 <PushButton>: Invalid <TooltipId> in skin.xml: "sync_master"
 qt.svg:warning [Main] Cannot open file 'skin:/buttons_/btn__square_set.svg', because: No such file or directory
 qt.svg:warning [Main] Cannot open file 'skin:/buttons_/btn__square_active.svg', because: No such file or directory
warning [Main] /home/jan/Projects/mixxx/src/skin/legacy/legacyskinparser.cpp:2038 SKIN ERROR at skin:/decks/rate_controls.xml:92 <PushButton>: Invalid <TooltipId> in skin.xml: "sync_master"
warning [Main] /home/jan/Projects/mixxx/src/skin/legacy/legacyskinparser.cpp:2038 SKIN ERROR at skin:/decks/rate_controls_compact.xml:98 <PushButton>: Invalid <TooltipId> in skin.xml: "sync_master"
warning [Main] /home/jan/Projects/mixxx/src/skin/legacy/legacyskinparser.cpp:2038 SKIN ERROR at skin:/decks/rate_controls.xml:92 <PushButton>: Invalid <TooltipId> in skin.xml: "sync_master"
warning [Main] /home/jan/Projects/mixxx/src/skin/legacy/legacyskinparser.cpp:2038 SKIN ERROR at skin:/decks/rate_controls_compact.xml:98 <PushButton>: Invalid <TooltipId> in skin.xml: "sync_master"
warning [Main] /home/jan/Projects/mixxx/src/skin/legacy/legacyskinparser.cpp:2038 SKIN ERROR at skin:/decks/rate_controls.xml:92 <PushButton>: Invalid <TooltipId> in skin.xml: "sync_master"
warning [Main] /home/jan/Projects/mixxx/src/skin/legacy/legacyskinparser.cpp:2038 SKIN ERROR at skin:/decks/rate_controls_compact.xml:98 <PushButton>: Invalid <TooltipId> in skin.xml: "sync_master"
warning [Main] /home/jan/Projects/mixxx/src/skin/legacy/legacyskinparser.cpp:2038 SKIN ERROR at skin:/decks/rate_controls.xml:92 <PushButton>: Invalid <TooltipId> in skin.xml: "sync_master"
 qt.svg:warning [Main] Cannot open file 'skin:/palemoon/buttons/btn_embedded_sync.svg', because: No such file or directory
 qt.svg:warning [Main] Cannot open file 'skin:/palemoon/buttons/btn_embedded_sync_active.svg', because: No such file or directory
 ```

**Pull request merged**
