### PR TITLE
lp1765210 Fidlib: Thread-safe and reentrant generation of filters

### PR DESCRIPTION
**Pull request by uklotzde**
https://bugs.launchpad.net/mixxx/+bug/1765210

Cherry-picked from #1624

### CODE REVIEW

**Comment by daschuer** [comment]
I think it is trivial to fix it in the fidlib code.
It is unmaintained anyway and we have the code already in our repro. 

see: 
https://github.com/uazu/fidlib
> Fidlib run-time filter design and execution library. CURRENTLY UNMAINTAINED. Consider daschuer/mixxxdj fork if this doesn't work for you. 

It looks like we have a new baby

**Comment by uklotzde** [comment]
Ok. Then I'll do the (easy but tedious) editing in place now to avoid the mutex. You can pick up those changes if you plan to publish and maintain a separate version of Fidlib.

**Comment by uklotzde** [comment]
Forked. Now thread-safe without using any synchronization primitives!

**Comment by uklotzde** [comment]
I recommend to include this in 2.1.1 to prevent crashes.

**Comment by uklotzde** [comment]
Improved the naming with a force push: "context"/"ctx" is more appropriate than "buf"

**Comment by uklotzde** [comment]
Marked as *critical* because I experienced a crash caused by an error in Fidlib code at least twice. This happened before I included a fix in my customized version.

**Comment by daschuer** [comment]
Thank you for doing this tedious work. I did not expect that this was so much.
LGTM

**Comment by daschuer** [comment]
Mac OS fails because of unrelated issues.

**Pull request merged**
