### PR TITLE
SoundTouch 2.1.1

### PR DESCRIPTION
**Pull request by uklotzde**
Rebased and reopened after experiencing that Ubuntu 18.04 still includes libSoundTouch 1.9.2:
https://launchpad.net/ubuntu/+source/soundtouch

Predecessors:
#1907 (reopening the original PR was not possible)
#1960 (building without the bundled libSoundTouch fails)

### CODE REVIEW

**Comment by daschuer** [comment]
This builds and woks here. Thank you.
Unfortunately AppVeyor complains: "Could not find Qt 5.11.2 at "". for the windows build.

**Comment by Be-ing** [comment]
>  Unfortunately AppVeyor complains: "Could not find Qt 5.11.2 at "". for the windows build.

I just fixed that earlier today: a47a6dd6543d7804ca249ac66f9ab5f44abfdd7e

**Comment by uklotzde** [comment]
Rebased and fixed the merge conflict.

**Comment by daschuer** [comment]
LGTM, Thank you.

**Pull request merged**
