### PR TITLE
[WiP] SoundTouch 2.1.1

### PR DESCRIPTION
**Pull request by uklotzde**
- Delete a forgotten .tar.bz2 file
- Update the bundled version from 2.1.0 to 2.1.1

Please note that we are still bundling SoundTouch 2.0.0 for Mixxx 2.2. That doesn't matter as long as the version provided by the (Linux) distribution is newer. Do the Windows and macOS builds use the bundled version? In this case I would propose a backport of this upgrade to both 2.1 and 2.2.

### CODE REVIEW

**Comment by daschuer** [comment]
This version also introduces run time exceptions. Do we need to add try catch blocks in Mixxx code? 
We also need to consider the new Beat detector already merged previously by SoundTouch 2.1.

**Comment by uklotzde** [comment]
The runtime exceptions already affect the Fedora builds, even if we don't update the bundled version. I received an update of the system library just today. This affects all distributions that receive an upgrade.

**Comment by daschuer** [comment]
That does not necessarily mean that all users should "suffer" from it.
So we have a urgent "bug" to consider this for all fedora users. Which version do you use by the way?

**Comment by daschuer** [comment]
Reading the soundsource code, we do not really have a problem if the library is updated in the distro. Before: assert  crash, now unhanded exception crash. Which not happens because we use it correct.

**Comment by uklotzde** [comment]
Runtime exceptions have been introduced with version 2.1. We could disable the runtime exceptions for SoundTouch entirely and thereby restore the legacy behavior. But then exceptions will be substituted by assert() and code from a release build happily continues as if nothing happened. With maybe unknown side effects any time during the following session.

Undefined behavior is even worse than a crash! A crash might stop the music, hopefully early while practicing and not while performing. You should always pre-listen to your tracks before you actually use them. Undefined behavior might torture your sound system and your listeners, at any possible time.

I prefer an early and sudden crash.

**Comment by daschuer** [comment]
LGTM. Waiting for CI

**Comment by uklotzde** [comment]
Exceptions are evil. Luckily we get rid of them in Rust ;)

**Comment by rryan** [comment]
> A successful CI build is crucial, because I haven't tested this locally!

Do our tests even exercise SoundTouch? I don't think so...

**Comment by rryan** [comment]
Argh, wrong button.

**Comment by uklotzde** [comment]
The CI build should mainly very successful compilation. I have not tried to build it locally after adding the exception handler.

**Comment by rryan** [comment]
On this topic, I've wanted to enable `-fno-exceptions` for a while, because we don't use them but we don't get the performance benefit of not using them.

**Comment by Be-ing** [comment]
Why are we bundling this library?

**Comment by uklotzde** [comment]
libmixxxminimal.so contains the bundled sources even though a recent system version (2.1.1) is available:
```
nm libmixxxminimal.so --demangle
...
0000000000074180 r soundtouch::AAFilter::calculateCoeffs()::__PRETTY_FUNCTION__
0000000000074400 r soundtouch::BPMDetect::updateXCorr(int)::__PRETTY_FUNCTION__
...
```

On the other hand it libmixxxminimal.so depends on the system library:
```
ldd libmixxxminimal.so | grep -i soundtouch
	libSoundTouch.so.2 => /usr/lib64/libSoundTouch.so.2 (0x00007f1710b29000)
```

Any ideas?

**Comment by uklotzde** [comment]
I'm trying to remove the bundled libSoundTouch. This PR will then be replaced by a new one, if that works out.

**Comment by uklotzde** [comment]
Superseded by #1960.

**Pull request closed without merging**
