### PR TITLE
vectorize default cover, fix mistake from e859676

### PR DESCRIPTION
**Pull request by ronso0**
This fixes empty cover art in library and decks when a track has no cover art OR as a PNG cover.

While converting library & preferences icons to vector images in #1774 , I wrongly replaced 'png' with 'svg' in coverartutisl.cpp.

### CODE REVIEW

**Comment by nopeppermint** [comment]
Hi @ronso0 
I am sorry, but this is not fixing my issue, same problem as before..

**Comment by ronso0** [comment]
please read the PR description.
This restores the default/empty cover art in lib & decks:
latenight-restore-default-cover

**Comment by ronso0** [comment]
a side note:
with 2.2, an empty cover in the detached cover viewer would look like this, which is less coherent IMO:
default-cover-2 2

2.1
default-cover-2 1

**Comment by nopeppermint** [comment]
> please read the PR description.
This restores the default/empty cover art in lib & decks:

I know

After proper clean (scons -c) and rebuild it's now working ;-)

> a side note:

on my PC in 2.1 and 2.2 the detached cover viewer looks both like on 2.2 on your PC..

**Comment by rryan** [comment]
thanks!

**Pull request merged**
