### PR TITLE
Fixes a race condition when loading tracks via AutoDJ 

### PR DESCRIPTION
**Pull request by daschuer**
This fixes https://bugs.launchpad.net/mixxx/+bug/1941743 at two places. 
See commits.

### CODE REVIEW

**Comment by Holzhaus** [comment]
Could you add tests for that issue to avoid future regressions?

**Comment by Be-ing** [comment]
Does this fix https://bugs.launchpad.net/mixxx/+bug/1941989 ?

**Comment by uklotzde** [comment]
> Does this fix https://bugs.launchpad.net/mixxx/+bug/1941989 ?

Probably not. The skipped tracks are not supposed to have a very short or zero duration.

**Comment by uklotzde** [comment]
Running the manual test from the bug report triggers debug assertions in main due to invalid frame positions. Did you run the tests for 2.3 successfully?

**Comment by uklotzde** [comment]
@daschuer  Please run this test for 2.3 and watch the memory footprint.

**Comment by daschuer** [comment]
> Did you run the tests for 2.3 successfully?

Yes.

**Review by uklotzde — APPROVED** [review]
At least one of the race conditions is fixed. While testing I noticed that AutoDJ always loads tracks into the same deck again and again. But this is an edge case and only happens with empty tracks.

Let's merge to fix the bug, even though we don't have any regression tests.

Thank you! LGTM

**Comment by daschuer** [comment]
> While testing I noticed that AutoDJ always loads tracks into the same deck again and again

This is the desired behavior. The AutoDJ loads new tracks until it finds a suitable successor. This happens normally while the previous track is still playing in the other deck.

**Pull request merged**
