### PR TITLE
An anti-aliased whitelabel drawing

### PR DESCRIPTION
**Pull request by ywwg**
If it's all right, here is my proposal for the default cover image. It has a little more embossing and depth than the previous cover image.  The previous image also had some aliasing issues which needed to be addressed anyway.

### CODE REVIEW

**Comment by daschuer** [comment]
Please revert this. This does not integrate well into The Shade skin and this does not fulfill the requirement @esbrandt has brought up in 
https://github.com/mixxxdj/mixxx/pull/435

**Comment by ywwg** [comment]
shit, sorry, which requirement?

**Comment by ywwg** [comment]
I think the solution is to have skin-specific default covers

**Comment by rryan** [comment]
> I think the solution is to have skin-specific default covers

There's something to be said for consistency though... @esbrandt's is subtle and looks pretty good in all 3 skins IMO.

**Pull request merged**
