### PR TITLE
Added missing null check

### PR DESCRIPTION
**Pull request by daschuer**
This fixes: 
https://bugs.launchpad.net/mixxx/+bug/1926197

### CODE REVIEW

**Comment by ronso0** [comment]
Thanks, this indeed prevents the crash : )

A more meaningful commit message would help identifiying this in the log.
BpmControl: add missing null check ?

**Review by ronso0 — APPROVED** [review]

**Comment by ronso0** [comment]
By chance, did you have a look if there are more checks missing here?

**Review by uklotzde — APPROVED** [review]
LGTM

**Comment by uklotzde** [comment]
> By chance, did you have a look if there are more checks missing here?

I did.

**Pull request merged**
