### PR TITLE
Protobuf: Use package provided config if available 

### PR DESCRIPTION
**Pull request by daschuer**
This is a workaround for a probably outdated CMake Modul. 

This aims to fix linking with protobuf v23.4 and the required Abseil. 

https://mixxx.zulipchat.com/#narrow/stream/247620-development-help/topic/Compiling.20Error.20on.20Arch

### CODE REVIEW

**Comment by winter1967** [comment]
The workaround have fixed the compile-error for me.  (EndeavourOS / Archlinux)

**Comment by daschuer** [comment]
I have tested this with an experimental vcpkg environment including v23.4. 
You can find the workflow run here: 
https://github.com/daschuer/mixxx/actions/runs/5661162465
The module mode has been disabled intentionally so the Ubuntu builds are failing.

**Comment by daschuer** [comment]
@winter1967 I have improved that PR for Windows and macOS. 
Can you confirm that it is still working?

**Comment by toszlanyi** [comment]
> @winter1967 I have improved that PR for Windows and macOS. Can you confirm that it is still working?

@daschuer - I just compiled this PR (GIT Version: 2.3.5-27-gb48611f170 (protobuf-config)) without issues on EndeavourOS

**Comment by daschuer** [comment]
Great. Who can review and merge this than?

**Review by Swiftb0y — APPROVED** [review]
I don't have the issue locally so I can not test whether the PR actually fixes the it, but the changes seem reasonable, so LGTM.

**Pull request merged**
