### PR TITLE
Mixtrack pro fx update

### PR DESCRIPTION
**Pull request by andybeetz**
Adding a switch to allow the FX encoder to control the meta knobs of Effect 1 on FX 1 and FX 2 (when shifted).

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Why do you use `meta `and not `super1`?

**Comment by andybeetz** [comment]
I don't know what super1 is or does.

**Comment by JoergAtGithub** [comment]
grafik
Blue is the super knob and yellow the meta knob. The super knob controls all meta knobs together and is also visible in colapsed view of the FX unit.
Note: The screenshot is from Mixxx 2.4, it might be different on Mixxx 2.3.

**Comment by ronso0** [comment]
> The knob doesn't exist in my installed version

GUi Super knobs are hidden by default. You can enable them in the Skin Settings (Ctrl+1).
https://manual.mixxx.org/2.3/en/chapters/appendix/mixxx_controls.html#control-[EffectRack1_EffectUnitN]-super1

**Comment by andybeetz** [comment]
> > The knob doesn't exist in my installed version
> 
> GUi Super knobs are hidden by default. You can enable them in the Skin Settings (Ctrl+1). [https://manual.mixxx.org/2.3/en/chapters/appendix/mixxx_controls.html#control-[EffectRack1_EffectUnitN]-super1](https://manual.mixxx.org/2.3/en/chapters/appendix/mixxx_controls.html#control-%5BEffectRack1_EffectUnitN%5D-super1)

I will pick this as my reason for using meta

**Comment by ronso0** [comment]
Hmm, this is no good reason IMO.
@JoergAtGithub is right, Super is a more versatile control as it allows users to work with all 3 effect slots. If just one effect is desired they can leave the unused effects disabled (default state).
Even though the Super knob maybe hidden (1) the mapping documentation can link to https://manual.mixxx.org/2.3/en/chapters/appendix/mixxx_controls.html#control-%5BEffectRack1_EffectUnitN%5D-super1 and (2) users will see the Meta knobs move anyway.

**Pull request closed without merging**
