### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by jwilk**

### CODE REVIEW

**Comment by uklotzde** [comment]
Nice typo ;) Welcome to Mixxx. Would you please rebase on 2.3?

We also need you to sign the contributor agreement before we can merge any code: https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ

**Comment by ronso0** [comment]
..though I think most laptops still have a shit button nowadays ;)

**Comment by jwilk** [comment]
> We also need you to sign the contributor agreement

No, thanks.

**Comment by ronso0** [comment]
@jwilk What's the issue with the contributor agreement?
It basically says that all your changes adapt to the Mixxx license --which is GPLv2 currently-- and you'd be listed as contributor (with a nickname if you like).

**Pull request closed without merging**
