### PR TITLE
FX mixmode icons for all skins

### PR DESCRIPTION
**Pull request by ronso0**
- [x] add FX mixmode buttons to LateNight
- [x] replace text labels in Deere with icons

LateNight
latenight-fx-mixmode

Deere
deere-fx-mixmode

### CODE REVIEW

**Comment by ronso0** [comment]
done. check it out!

**Comment by Be-ing** [comment]
I like the designs, but somehow the curved lines in the LateNight icons are blurry when scaled even though they are vectors:
screenshot from 2018-08-06 22-12-55
screenshot from 2018-08-06 22-15-41

Shade has the same problem:
screenshot from 2018-08-06 22-14-04

Deere and Tango icons look smooth.

**Comment by Be-ing** [comment]
Looking closer, there are other issues with scaling in LateNight. Some icons have crisp, sharp edges, but others look pixelated:
screenshot from 2018-08-06 22-22-57
These icons look blurry:
  * reverse
  * play (triangle part only)
  * pitch nudge (triangle part only)
  * slip
  * quantize
  * eject
  * repeat

It's strange that the beatjump icons look good but the pitch nudge icons have blurry edges.

**Comment by ronso0** [comment]
> I like the designs, but somehow the curved lines in the LateNight icons are blurry when scaled even though they are vectors. Compare them to the knob notches which scale smoothly

This really is interesting.
Looking at your screenshot I notice that all 'sharp' icons are buttons loaded via templates like button_Xstate.xml with **a)** `scalemode="STRETCH_ASPECT"` for each button state (0,1, pressed, unpressed) and **b)** explicite size (though this doesn't affect the button size when icons are defined inline and not via css).

I'll add `scalemode` to some inline buttons..

**Comment by ronso0** [comment]
Btw this issue does not occur with qt4

**Comment by ronso0** [comment]
unfortunately I can't test with my 2.2 qt5 builds since manual scaling was removed..

**Comment by daschuer** [comment]
> unfortunately I can't test with my 2.2 qt5 builds since manual scaling was removed..

Here is a pending PR for this issue: https://github.com/mixxxdj/mixxx/pull/1741

**Comment by ronso0** [comment]
weird...I tested with #1741 and qt5.2.1 and all icons are sharp
latenight_hipdi_buttons

but t wouldn't draw the (inline) buttons at all if I use `scalemode="STRETCH_ASPECT"` and DON'T define the button size.

@Be-ing please test again.
those are test commits which I'll revert/squash once we find a solution.

**Comment by Be-ing** [comment]
The play and reverse buttons look good now, but the others are still blurry:
screenshot from 2018-08-07 10-07-35
I'm puzzled why this is not an issue with other skins (except the mix mode icon in Shade).

**Comment by Be-ing** [comment]
I suspect we are doing something wrong in the C++ code for WPushButton. Skins might not be the best place to fix this...

**Comment by ronso0** [comment]
> The play and reverse buttons look good now

great. Transport row (loop, jump, hotcues...) was the only place I tried the fix.

> I'm puzzled why this is not an issue with other skins (except the mix mode icon in Shade)

Just had a quick look at the button templates in Deere & Tango, and it looks like all use `scalemode="STRETCH_ASPECT"`. Shade otoh has only raster images and doesn't use scale_mode for mixmode button

**Comment by ronso0** [comment]
it appears that, with scalemode, the final buttons size is considered to scale the icons.
without scalemode, the icons seemingly are rendered in their original size, THEN scaled up.

**Comment by ronso0** [comment]
I'll revert the recent commits and apply the fix to the mixmode buttons only.

In another PR I''ll add 'scalemode' to buttons using vector images in all skins

**Comment by Be-ing** [comment]
I think it would be better to change the scaling behavior of WPushButton than add a workaround to every instance of WPushButton in every skin.

**Comment by Be-ing** [comment]
WPushButton has this comment:
```
                // The implicit default in <1.12.0 was FIXED so we keep it for
                // backwards compatibility.
                Paintable::DrawMode unpressedMode =
                        stateContext->selectScaleMode(unpressedNode, Paintable::FIXED);
```
It's not clear to me what would be the harm of changing the default to STRETCH_ASPECT, which is apparently required for modern screens. Explicitly requiring STRETCH_ASPECT for every single widget does not seem like a great solution to me. @daschuer and @rryan, what do you think? Should we change the default scale mode? Or maybe we can add an attribute to the skin manifest to opt-in to STRETCH_ASPECT by default so it doesn't have to be specified for every widget?

**Comment by ronso0** [comment]
yes, that's what I wrote earlier.

> Or maybe we can add an attribute to the skin manifest to opt-in to STRETCH_ASPECT by default so it doesn't have to be specified for every widget?

that's the option I'd support for pushbuttons (!) per skin.
remember the are other widgets like sliders that need to keep the aspect of the handle but stretch the scale to available space.

**Comment by Be-ing** [comment]
Any widgets that need a scaling mode other than STRETCH_ASPECT would still be able to explicitly specify one.

**Comment by ronso0** [comment]
okay.
so this is ready to merge

**Comment by Be-ing** [comment]
LGTM thank you!

@daschuer what do you think about the scaling issue? I am leaning towards adding a new opt-in skin attribute for setting the default scale mode.

**Pull request merged**
