### PR TITLE
RekordboxFeature: ask for access outside sandbox for PDB file

### PR DESCRIPTION
**Pull request by Be-ing**
fixing https://bugs.launchpad.net/mixxx/+bug/1913922

### CODE REVIEW

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you. Let's wait until the user confirms that this fixes the issue.

**Comment by zabox** [comment]
Awesome, that fixed the issue. Thanks a lot!

**Comment by Holzhaus** [comment]
Do we need the same fix for all other external libraries?

**Comment by uklotzde** [comment]
> Do we need the same fix for all other external libraries?

Probably yes. Without a separate file access layer regressions in the future are likely. But this is out of scope.

**Pull request merged**
