### PR TITLE
Added easter egg random sort also in crates and playlists

### PR DESCRIPTION
**Pull request by jmigual**
Corresponding to bug https://bugs.launchpad.net/mixxx/+bug/1447082

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you, for this PR. It fixes the issue. 

How about moving the code into BaseSqlTableModel::setSort ? 
This will avoid some code duplication and gives us the chance to use random in a hierarchic search. 
Something like "a random Track from 1980"

**Comment by jmigual** [comment]
I agree with you give me 10 minutes and I'll fix it

**Comment by esbrandt** [comment]
Thanks.
If the ``Preview`` column is selected, and you perform a right click in the in the tree-view´s Library/Playlist/Crate root (sub)items , a random sort is always triggered. 
I´d expect the sorting only when clicking on the ``Preview`` column header of the selected table.

**Comment by daschuer** [comment]
We will get a new random sorting every time we access the database. This makes the Random result volatile, which seams to be not what the user expect. 

In the right click test case, it looks like there is a redundant DB lookup, which can be probably removed. 

We may add a new hidden column or a temp table to the database that holds the "last_random_value". Every random sorting should use BY last_random_value. Then we need a new "Randomize" query, which refreshed the last_random_value column on every header toggle from ASC to DESC. 

.. but that is out of the scope of this PR.

**Comment by jmigual** [comment]
So, I try to remove the redundant DB lookup or we will merge this?

**Comment by daschuer** [comment]
I will test this today and merge it like it is.  
Please investigate the lookup issue. If there is a low impact solution, you may open an other PR. 
I think I will file a new bug for the advanced random solution. For me this a minor issue, we can fix later.

**Comment by daschuer** [comment]
Here it is: https://bugs.launchpad.net/mixxx/+bug/1574331

**Comment by daschuer** [comment]
LGTM. Thank you.

**Pull request merged**
