### PR TITLE
[WIP] Effects refactoring

### PR DESCRIPTION
**Pull request by daschuer**
This is a rebase of https://github.com/mixxxdj/mixxx/pull/2618 without moving files and mass reformatting. 

While the diff is still huge, it has been reduced from 10,478 to 8475 lines. 

The next step is to spit it into merge-able chunks.

### CODE REVIEW

**Review by Be-ing — CHANGES_REQUESTED** [review]
I have been testing #2618 for months. This introduces hundreds of untested commits. Moreover, splitting it up is impossible without breaking main or reintroducing bugs in new features which have already been fixed, which would be a waste of time. Please close this.

**Comment by Be-ing** [comment]
Please stop. This is a waste of everyone's time.

**Comment by uklotzde** [comment]
@daschuer Do you plan to take over responsibility for the whole feature?

PS: In the role of the original developer I would consider such a PR an adversarial act.

**Comment by Holzhaus** [comment]
Instead of making dozens of untested commits by rebasing, you could just diff this branch against @Be-ing 's branch. Then we could just add the resulting patch as a single commit that reverts the mass formatting to @Be-ing's branch.

**Comment by daschuer** [comment]
This PR is my kind-intentioned attempt to resolve a dead lock in the integration process of the original branch. 

Before this PR 
* Reviewing the PR is not feasible
* Splitting the PR is not feasible 

Now, we have a PR that produces a clean diff. This is still quite unhandy to review because of more commits GitHub can handle and multiple features in one PR, but it is at least a step forward.

This PR was not intended to be merged. It should serve a commit container that can be used to extract the features. 
In the current state it helps to see clearly what has been changed. 

I am not really sure if I have interest to take ownership of this PR. For my understanding the ball was on my side. Now it is back on the field. Unfortunately it sound like @Be-ing has no interest to pick it up. 

Let's see if I find time to extract un-controverse features to reduce this one even more. 

> Instead of making dozens of untested commits by rebasing, you could just diff this branch against @Be-ing 's branch. 

Using these rebase commits was the only feasible way to use git to resolve the conflicts that have been developed in the history after the mass-reformating and renaming commits. This way we have also clean commits as base for the feature branch without the hassle of dealing with the unwanted changes. 

> Then we could just add the resulting patch as a single commit that reverts the mass formatting to @Be-ing's branch.

Good idea, I will give it a try.

**Comment by Holzhaus** [comment]
Great. The "revert mass reformatting" commit will make the pre-commit hook fail though. I guess we can add that commit, review the PR, then revert that commit before merge.

**Comment by daschuer** [comment]
Than there is no point for such a commit.
We see the same diff here, without a failing CI.

**Comment by Holzhaus** [comment]
Yeah, but we keep the PR discussions in a single place. And we can review the PR without the formattings, then review the formatting independently. All without adding untested rebased commits. But if this PR works for you for reviewing the diff, that's okay for me, too. Just make sure to comment your findings on #2618.

**Comment by daschuer** [comment]
The issue is also, that we cannot commit fixes when the revert commit is still in place.

Giving that this is a 8k PR and extrapolate the normal comment density, I expect many findings.

From this point of view, small rebased PRs will be a lot more handy. I think that we can effort untested intermediate commits, they should be build-able thought.

**Comment by Be-ing** [comment]
> Unfortunately it sound like @Be-ing has no interest to pick it up.

I have not abandoned #2618.

I will not review any or merge any commits undoing formatting changes nor discuss this topic any further. You are defeating the purpose of having automatic formatting which is to *not talk about formatting*. Neither will I discuss or review any PRs splitting this branch will waste time reintroducing regressions.

**Comment by daschuer** [comment]
> I am out of patience for bikeshedding.

This has a problematic undertone, sounding like not welcoming any non major review comment. I think we need go back to a mode where we discuss solutions for found issues instead of rating them. We should treat comments with the same patience independent if the PR has 8000 or 10 lines.

**Pull request closed without merging**
