### PR TITLE
fix: eslint v9 pre-commit hook

### PR DESCRIPTION
**Pull request by Swiftb0y**
Fix pre-commit eslint hook broken by #13843

Currently running the eslint hook on JS files results in this lengthy error message:

<details><summary>Error</summary>
<p>

```
**(node:13057) ESLintIgnoreWarning: The ".eslintignore" file is no longer supported. Switch to using the "ignores" property in "eslint.config.js": https://eslint.org/docs/latest/use/configure/migration-guide#ignoring-files
(Use `node --trace-warnings ...` to show where the warning was created)

Oops! Something went wrong! :(

ESLint: 9.14.0

ESLint couldn't find an eslint.config.(js|mjs|cjs) file.

From ESLint v9.0.0, the default configuration file is now eslint.config.js.
If you are using a .eslintrc.* file, please follow the migration guide
to update your configuration file to the new format:

https://eslint.org/docs/latest/use/configure/migration-guide

If you still have problems after following the migration guide, please stop by
https://eslint.org/chat/help to chat with the team.
**
```

</p>
</details> 

This PR fixes this by migrating to the new config format.

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Comment by Swiftb0y** [comment]
Thank you

**Comment by Swiftb0y** [comment]
fyi eslint is still broken rn because it doesn't seem to recognize the API definitions. idk when I'll get around to fixing that. Do you have time/interested to look into it @acolombier?
https://github.com/mixxxdj/mixxx/actions/runs/11857965705/job/33047521182

**Comment by Swiftb0y** [comment]
My attempt to fix it @acolombier #13913

**Pull request merged**
