### PR TITLE
Renamed makeUnbufferedConnection and used it for VuMeter controls

### PR DESCRIPTION
**Pull request by JoergAtGithub**
This is the Follow-UP of #4566 which replaces makeConnection for VuMeter/L/R controls by makeCompressedConnection in controller the mappings that comes with Mixxx.
These controls appear in short intervals and are primary responsible for event queue overload on slow computers. On the other hand, these are numeric values, which are no used in the application logic of the mappings. Therefore the mapping logic can't be influenced by skipping superseded values.
This PR doesn't replace the use of legacy ConnectControl statements, because in theses cases it wouldn't be a 1:1 replacement without risk.

### CODE REVIEW

**Comment by daschuer** [comment]
pre-commit fails

**Comment by daschuer** [comment]
The code looks good.

**Comment by JoergAtGithub** [comment]
> pre-commit fails

Yes, but how can I fix: "Executable `eslint` not found"

Maybe a dummy commit to rerun the CI Actions?

**Comment by daschuer** [comment]
We can rerun them from the GitHub GUI.

**Comment by daschuer** [comment]
Just did it.

**Comment by daschuer** [comment]
> I don't think the commit: Debug vcpkg_copy_pdbs should be added.

Yes, this was just for debugging.

**Comment by daschuer** [comment]
I see in the log: 
`[INFO] Installing environment for https://github.com/pre-commit/mirrors-eslint.`
and 
```Executable `eslint` not found```

@Holzhaus Do you have an idea why this fails? 


@JoergAtGithub 
Do you have the eslint hook installed and succeeds it locally? 
I think we can merge anyway in this case.

**Comment by JoergAtGithub** [comment]
No unfortunately not - I'm on Windows, where local pre-commit isn't available.

I see an eslint update in #4558 a month ago. Maybe eslint was never executed since then, and nobody noticed?

**Comment by Holzhaus** [comment]
> No unfortunately not - I'm on Windows, where local pre-commit isn't available.

Why do you think that? I'm pretty certain it works on Windows, too.

**Comment by JoergAtGithub** [comment]
It's written in the Wiki, that it's Linux only. And I also tried myself, it just hangs and no commit is possible. Also on CI, it's just executed on Linux.

**Comment by Swiftb0y** [comment]
The frontpage of the pre-commit website mentions multiple times that hooks were tested on Linux, macOS and Windows, so I can't believe it doesn't work on there.

**Comment by Holzhaus** [comment]
> It's written in the Wiki, that it's Linux only.

No idea who added that, I didn't. 

> And I also tried myself, it just hangs and no commit is possible.

Weird, we should definitely debug this. Does it set up the environment or does that also hang? 

> Also on CI, it's just executed on Linux.

There is no point of running pre commit on all 3 OSes because the output should be exactly the same. It would just be a waste of electricity.

**Comment by JoergAtGithub** [comment]
@Swiftb0y I did an experimental commit, that reverted the changes from #4580 and now eslint is found on GitHub again.

**Comment by Swiftb0y** [comment]
mhmmm. I'm still confused, this shouldn't be happening. I mean pre-commit won't pass for any of the modified mappings anyways so we can ignore that. Still, I'm confused why its broken on CI. I guess I'll try to reproduce the issue in a VM when I find the time. I really did not mean to break CI.

**Comment by Holzhaus** [comment]
> mhmmm. I'm still confused, this shouldn't be happening. I mean pre-commit won't pass for any of the modified mappings anyways so we can ignore that. Still, I'm confused why its broken on CI. I guess I'll try to reproduce the issue in a VM when I find the time. I really did not mean to break CI.

I suppose you overwrote the `additional_dependencies` list and replaced it with a list containing just eslint-jsdoc, but not eslint itself?

**Comment by uklotzde** [comment]
> > mhmmm. I'm still confused, this shouldn't be happening. I mean pre-commit won't pass for any of the modified mappings anyways so we can ignore that. Still, I'm confused why its broken on CI. I guess I'll try to reproduce the issue in a VM when I find the time. I really did not mean to break CI.
> 
> I suppose you overwrote the `additional_dependencies` list and replaced it with a list containing just eslint-jsdoc, but not eslint itself?

#4595

**Comment by JoergAtGithub** [comment]
Uwes fix worked! eslint is fount again.

Now eslint fails as expected - I think these unrelated eslint changes shouldn't be fixed in this PR?

**Comment by Holzhaus** [comment]
> Now eslint fails as expected - I think these unrelated eslint changes shouldn't be fixed in this PR?

No, don't worry about that 😅

A bit OT: as someone who didn't follow the original PR #4566 I really had problems to understand what a "compressed" connection is. I think the name is misleading because we don't try to reduce the file size, we just drop obsolete packages. I think we should consider changing the name (but I won't insist on that). If we do, we should do that before merging this to avoid unnecessary commits in the git history.

IIRC we do the opposite of [tail drop policy](https://en.m.wikipedia.org/wiki/Tail_drop) often used in network equipment, i.e. we drop old packages instead of new ones, correct? 

How about these:

- `makeConnectionWithHeadDropPolicy`
- `makeFlushingConnection`
- `makeCongestionControlledConnection`
- `makeDeduplicatingConnection`

**Comment by JoergAtGithub** [comment]
`makeFlushingConnection` sounds goog to me, but I'm not sure if this is the correct English word for this. In other parts of the code, I use SkipSuperseded, but this is very long.

**Comment by uklotzde** [comment]
How about `makeUnbufferedConnection()`? From the client's perspective values that are not consumed in time are discarded  because no internal buffering is provided.

**Comment by JoergAtGithub** [comment]
Makes sense to me, we don't need to expose the technical implementation details to the user.

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you.

**Pull request merged**
