### PR TITLE
[WIP] qopenglwindow based wglwidget

### PR DESCRIPTION
**Pull request by m0dB**
**DRAFT PR, WORK IN PROGRESS**

Derive the waveform widgets and the spinny widgets from WGLWidget which is either derived from QGLWidget or is a custom QWidget that contains a QOpenGLWindow container widget (not QOpenGLWidget) and that triggers the prerender and drawing of these widgets from the QOpenGLWindow frameSwapped signal instead of the vsync thread. 

It is possible to switch between the two implementations use MIXXX_USE_QGLWIDGET defined in wglwidget.h.  When WGLWidget is derived from QGLWidget, it is basically indentical to main (changes only to have a common API with the QOpenGLWindow based implementation).

Known issues:
- No VU-meters
- No drop and mouse events on waveform (but are working on WSpinny. I know why)
- Fixed framerate at 60 fps
- The beat markers are not alpha-transparent (the minor detail mentioned earlier)
- Only briefly tested on linux, kind of works but there are issues
- Not all waveform renderers are properly hooked up yet. Those will show as a red rectangle
- On my hardware (integrated intel GPU), the GLSL waveform behaves much worse than the GL waveform (causing the framerate to become unsteady)
- Some actions (scrolling in the library, but surprisingly not in the sidebar) stalls the updates

Next steps:
- Reduce or remove use of MIXXX_USE_QGLWIDGET ifdefs except for wglwidget.{h|cpp}
- Try to drive the QOpenGLWindow based implementation with vsyncthread instead of QOpenGLWindow::frameSwapped as this might work better on linux on will allow for lower framerate.

### CODE REVIEW

**Comment by Be-ing** [comment]
> It is possible to switch between the two implementations use MIXXX_USE_QGLWIDGET defined in wglwidget.h. When WGLWidget is derived from QGLWidget, it is basically indentical to main (changes only to have a common API with the QOpenGLWindow based implementation).

Could you add a CMake option for this?

**Comment by JoergAtGithub** [comment]
I tried this on Windows, and it doesn't feel smooth. The preferences indicate, that I got only a quarter of the selected frame rate:
grafik

**Comment by m0dB** [comment]
Thanks @JoergAtGithub for trying. That's disappointing. Also disappointing and very frustrating is that I try to add the VUMeters back, and even without drawing anything, only creating a QPainter(openGLWindow), CPU skyrockets and framerate drops. If I use native GL functions it stays low. This is both drawing from vsyncthread and from frameSwapped. I feel like I am missing something because it obviously makes no sense that drawing waveforms and spinnies is smooth but adding nother widget that basically does nothing causes these issues.

**Comment by Be-ing** [comment]
QPainter uses OpenGL when it is painting onto a QOpenGLWidget:

https://doc.qt.io/qt-5/qpainter.html#performance

> OpenGL 2.0 (ES) - This backend is the primary backend for hardware accelerated graphics. It can be run on desktop machines and embedded devices supporting the OpenGL 2.0 or OpenGL/ES 2.0 specification. This includes most graphics chips produced in the last couple of years. The engine can be enabled by using QPainter onto a [QOpenGLWidget](https://doc.qt.io/qt-5/qopenglwidget.html).

**Comment by m0dB** [comment]
QOpenGLWindow in my case, but yes, I am aware if this. This is also used and works fine for the waveform overlays (markers etc), and for the Spinnies. But with the VuMeters, just creating the QPainter makes everything go slow. I am drawing the waveforms and spinnies smoothly at 60 fps, I add the vumeters (without actually drawing anything, I mere create the qpainter and return) and things because sluggish, CPU goes from 30% to 80% and framerate drops.  I am lost.

**Comment by m0dB** [comment]
It is clear that using QPainter(openGLWindow) does come with a performance penalty. I will try to rewrite WVuMeterGL to use only native OpenGL calls.

**Comment by JosepMaJAZ** [comment]
Will try to do some tests today.

I compiled it although I didn't realize that I have to set some defines first, so i tested it without the changes.
What I noticed is that all non-GL waveforms don't show (software waveforms), and the "QT" ones fail too.

I would assume that without the define, these would work as before.
CPU an GPU usage was normal in this scenario.

**Comment by JosepMaJAZ** [comment]
Ok, I have now realized that the defines actually set back the old behaviour, so I tested on the new behaviour.

So the problems are actual problems, and the CPU/GPU usage was relevant.

In that case, I have to say that I didn't see the problems with the framerate. My screen is at 59Hz and vsyncthread worked similarly to how it works with 2.3 (i.e. missing some frames at higher speeds, but keeping above 55 at all times). Hardware is an i7 6700 with Nvidia GTX 1060

**Comment by m0dB** [comment]
Thanks for testing, @JosepMaJAZ . Yes, it is expected that not all waveform renderers work.

I am not sure how to proceed with this. On macOS the QOpenGLWindow based waveform widgets behave well, but when I add the GL VuMeters, performance drops. I feel that this is because of the of QPainter on the GL surface, when I use native calls the performance drop does not occur. It is all pretty vague.

**Comment by m0dB** [comment]
This PR has been replaced by https://github.com/mixxxdj/mixxx/pull/10959

**Pull request closed without merging**
