### PR TITLE
macOS packaging: Rename bundle resources to `Info.plist.in` and `Mixxx.entitlements`

### PR DESCRIPTION
**Pull request by fwcd**
These are the conventions established by Apple (see [the official docs](https://developer.apple.com/documentation/bundleresources/)) and naming these files accordingly makes them easier to find for developers accustomed to standard macOS projects.

### CODE REVIEW

**Comment by daschuer** [comment]
Is this for 2.4?

**Comment by fwcd** [comment]
Yes, we could definitely target 2.4 too, I've rebased the changes.

**Review by Swiftb0y — APPROVED** [review]
LGTM, anything left to do here?

**Comment by daschuer** [comment]
I am not able to test that. Do the resulting bundle still work as desired? If yes, let's merge this.

**Pull request merged**
