### PR TITLE
Enable QML debugging and profiling in debug builds

### PR DESCRIPTION
**Pull request by Swiftb0y**
Allows builds to be profiled and debugged by external applications
such as VS and Qt Creator.
See https://doc.qt.io/qt-5/qtquick-debugging.html

### CODE REVIEW

**Comment by Swiftb0y** [comment]
The doc says that enabling QML debugging is a security risk so we might want to reflect that in the build output.

**Comment by daschuer** [comment]
What is on a risk?  It is probably the same when adding debug information to the binary.
We ship them along with our release. 

But anyway, how about adding a cmake status message, that mentions the risk.

> QML debugging is enabled. Only use this in a safe environment.

This is printed a qDebug in 5.12 and from 5.13 to street.

**Comment by Swiftb0y** [comment]
> What is on a risk? It is probably the same when adding debug information to the binary.

I'm not sure. AFAIK you can puppeteer the entire application through an unprotected TCP socket. So you can change everything in the QML engine from the outside. So I guess the risk is comparable to being able to attach a gdb to a remote process?

> But anyway, how about adding a cmake status message, that mentions the risk.

Yes, thats what I'm advocating for.

> >  QML debugging is enabled. Only use this in a safe environment.
>
> This is printed a qDebug in 5.12 and from 5.13 to street.

I fear this is not enough. Its a single line behind lots of other log messages and maintainers might only compile the application and won't get to see it running. So I'd like to add a message during compile time that mentions the risk there as well.

**Comment by daschuer** [comment]
Ah ok, this opens a network port, that's the risk.

**Comment by daschuer** [comment]
Yes, that makes sense. The message should mention the network port.

**Comment by Swiftb0y** [comment]
Included a message. What do you think?

**Review by daschuer — APPROVED** [review]
LGTM, thank you.
@Holzhaus does it work for you?

**Comment by daschuer** [comment]
It still work btw.

**Comment by Holzhaus** [comment]
Doesn't work for me:

```
$ ./mixxx -qmljsdebugger=port:9000
QML debugging is enabled. Only use this in a safe environment.
"Unknown option 'qmljsdebugger'."
```

https://doc.qt.io/qt-5/qtquick-debugging.html#starting-applications

Or how is this supposed to be used?

**Comment by Holzhaus** [comment]
Ah, it actually works. But the message is confusing. I guess this needs to be fixed in the command line arg parser.

**Comment by Swiftb0y** [comment]
> I think this needs to be fixed in the command line arg parser.

Seems to be the case. It occurs to me as well, but attaching with Qt Creator works. I can inspect the Component tree and do some profiling. If you don't have QtCreator installed, afaik there should be a `qmlprofiler` tool that you can use as well to create profile you can then inspect with `gprof` and similar tools.

**Comment by Swiftb0y** [comment]
Merge?

**Comment by Swiftb0y** [comment]
> "Unknown option 'qmljsdebugger'."

The issue seems to be that we're parsing the commandline args at the wrong time. We're parsing them in main while we should rather parse them in the QApplication subclass (so `MixxxApplication` I guess). 
https://doc.qt.io/qt-5/qapplication.html#QApplication

**Pull request merged**
