### PR TITLE
Tango :: overhaul SkinSettings knobs & Spinny/Cover controls

### PR DESCRIPTION
**Pull request by ronso0**
- reworked knob templates to allow showing the QuickEffect toggle in channel mixer when the Kill buttons are hidden
- use graphics for the mix mode buttons instead of text (like those in Shade #1702  but taller)
- fixed skin settings menu for qt5: the sampler row selection buttons where loaded as Singleton and weren't rendered at all
- fixed links in 64-samplers Skin menu (i.e. there was no way of enabling more than two sampler rows...)
- Skin Settings menu: added `EQ Kill buttons`, simplified Spinny/Cover toggles,
re-ordered some items
- Spinny/Cover Art settings are now separate COs, settings will persist when changing to Deere
- add deck numbers to channels's level VU and move them to center when channel mixer is hidden
(and permanent level meters are enabled)
- unify some skin COs based on #1623 ([Master],show_4effectunits, ~,8_hotcues etc.)
tango-overhaul2
tango-overhaul1

### CODE REVIEW

**Comment by daschuer** [comment]
I have an issue with the Tango preview deck, not related to this PR. It is grayed out in 2.1 and master. Do you have an idea how this can happen? 
bildschirmfoto vom 2018-07-11 23 15 12

**Comment by daschuer** [comment]
This area is also effected: 
bildschirmfoto vom 2018-07-11 23 22 12

**Comment by daschuer** [comment]
The rest LGTM! Thank you

**Comment by ronso0** [comment]
> I have an issue with the Tango preview deck

This is supposed to be an indicator that you first have to configure a headphone device before wanting to use it instead of noticing too late. Adding/removing/configuring sound devices while would always result in a playback pause which is not optimal ;)

see https://bugs.launchpad.net/mixxx/+bug/1741683
"Any Pfl buttons and Preview deck seem to be ready, even though there's no headphone device configured. When clicking those controls, no sound would play and there'd be no feedback about why not."

**Comment by daschuer** [comment]
Ah, now I remember the discussion.
It is confusing that the preview column works, but you have no control over the deck. 
Can you add an overlay text, that explains the situation?

**Comment by ronso0** [comment]
> It is confusing that the preview column works, but you have no control over the deck.

Yup, this is inconsistent.
Now it looks like this:
tango-headphone-hint

**Comment by daschuer** [comment]
Greate. I will adopt this for Shade as well.
LGTM.
Is it ready for merge?

**Comment by Be-ing** [comment]
No, the mix mode icons lose the connection with the tooltip. Either the "D+W" and "D/W" text needs to be shown together with the icons or we need different icons.

**Comment by ronso0** [comment]
> No, the mix mode icons lose the connection with the tooltip

Users see two icons
d w_mode
d-w_mode
and the tooltip
```
Mix Mode
Adjust how the dry (input) signal is mixed with the wet (output) signal of the effect unit
D/W mode: Mix knob crossfades between dry and wet
    Use this to change the sound of the track with EQ and filter effects.
D+W mode: Mix knob adds wet to dry
    Use this to change only the effected (wet) signal with EQ and filter effects.
```

IMO the icons match both the `EffectUnit_mix_mode` and `EffectUnit_mix` tooltips.
Ultimately, "crossfade" creates the reference to distinguish both modes.

It's a bit irritating that only "EQ and filter effects" are mentioned, so maybe we should change the tooltip to include just "effects"?

**Comment by Be-ing** [comment]
Instead of discussing this in circles, let's do some usability testing to see if people who are unfamiliar with the mix mode concept can associate the icons with the tooltip descriptions.

**Comment by nopeppermint** [comment]
@ronso0 you might take a deeper look into the logic for the skin settings button "always Show Level Meter" it's only changeable if "Channel Mixer" is not activated ..

**Comment by Be-ing** [comment]
The D+W icon is backwards and should be reflected over the vertical axis. As it is, it depicts the wet signal decreasing as the the knob is moved to the right, which is the opposite of how it works. This doesn't affect the meaning, but I find it a little odd that the wet signal extends down instead of up.

**Comment by Be-ing** [comment]
> The D+W icon is backwards and should be reflected over the vertical axis. As it is, it depicts the wet signal decreasing as the the knob is moved to the right, which is the opposite of how it works.

After playing with reflecting the icon, I see now that the top of the icon is meant as fully on. When I first saw it, I saw the wet line going down from the dry line. I think this confusion could be alleviated by filling in the areas under the lines, but that wouldn't work for the D/W icon as it is.

**Comment by Be-ing** [comment]
Perhaps what is so confusing about the D+W icon is that the graphs for the dry and wet are superimposed, so it does not convey that what the graphs are depicting are being added together. Instead it looks like the dry and wet are mutually exclusive because they share the same space.

**Comment by ronso0** [comment]
>  you might take a deeper look into the logic for the skin settings button "always Show Level Meter" it's only changeable if "Channel Mixer" is not activated ..

this as intended: they can only be toggled when you would actually see a difference. 
the other way around would be more irritating IMO.

**Comment by ronso0** [comment]
@Be-ing I already have some previous versions that also play with area below the curves. they were not ideal but I'll play with them again. let's merge #1623 and this as it improves other parts of the skin. I agree usability testing would provide insights if we need to discuss those icons on such a depth

**Comment by Be-ing** [comment]
Can you cherrypick 6626498 to another branch and rebase to remove it from this branch? IMO it is a regression to remove the text labels without clear replacements. We can continue discussing the icons in another PR separate from the unrelated changes in this branch.

**Comment by ronso0** [comment]
We can as well discuss it here.

We want two icons that depict the difference between two FX mixing modes. Those icons should be clear and distinct so they can be used in different skins at different sizes. Regarding the available space in our skins the icons need to be in a landscape format.

When talking about the mixmode we should take a look how fading is depicted in the Crossfader section in Preferences, because it's a similiar mixing of signals, and is proved and tested.
There, we see a stack of two graphs: a channel volume curve, and above the total volume curve:
fxmixmode_xfader
fxmixmode_xfader2
Here, the most impressing/interesting part is IMO definitely the channel volume curves.
Looking at the FX mix mode, those are also the significant difference between the two mix modes: the 'channel' volume curves are symmetric only in D/W mode, in D+W mode Dry is constant and Wet is increased from left to right.

@Be-ing  The only alternativ proposals are yours where you want to show the addition of channel AND total volume. Side by side, those icons look like a Tangram tutorial. Also, they are too tall to fit into Shade skin.
1)) channel Vol + total Vol
fxmixmode_totalvol_being


I also tried to show the channel volume by "filling" the area below the curves.
2) curves + grid lines
fxmixmode_curves_vlines1
This makes them complex and unclear IMO. Also, the overlapping areas in the middle are irritating.

Another approach avoiding that overlap in the D/W icon:
3) curves + grid lines2
fxmixmode_curves_vlines2
those are a bit clearer but still too complex to transport the actually quite simple difference.
Also, I find it irritating that the Dry volume is measured from the top down while the Wet volume is measured from the bottom up.

4)) curves + gradients
fxmixmode_gradients
Less complex but still having that top-down/bottom-up issue. The difference is not significant enough IMO.

Looking at the crossfader images and the icons above, I advocate picking up the crossfader vocabulary and use the channel volume curves only to depict two fx mix modes:
5)) dry/wet curves only, Tango
fxmixmode_curves_only
Shade:
fxmixmode_shade


That's why I advocate using those icons (5) as they are the best-matching icons that we came up with so far. The tooltip strings need to be changed anyway IMO:

Mix Mode
Adjust how the dry (input) signal is mixed with the wet (output) signal of the effect unit
**D/W mode**: Mix knob crossfades between dry and wet
    Use this to change the sound of the track with EQ and effects.
**D+W mode**: Mix knob adds wet ~~to dry~~ **, dry is constantly fully on**
    Use this to change only the effected (wet) signal with EQ and effects.

**Comment by ronso0** [comment]
@Be-ing Any feedback?

**Comment by Be-ing** [comment]
Will look at this soon

**Comment by Be-ing** [comment]
Sorry for the delay. Last week got unexpectedly busy for me so I didn't have much time for Mixxx other than reviewing #1705. I will also be travelling this weekend and likely won't be able to respond then.

> When talking about the mixmode we should take a look how fading is depicted in the Crossfader section in Preferences, because it's a similiar mixing of signals, and is proved and tested.
There, we see a stack of two graphs: a channel volume curve, and above the total volume curve

I wouldn't call those "proved and tested". I have always been confused by the "Slow fade/fast cut" curve and had no idea that one of those lines was the channel volume curve and the other was the total volume curve. But the constant power curve is clear.

Thank you for doing the work of trying alternate ideas and showing screenshots. I agree that none of those other proposals work very well.

After using the plain "D+W" and "D/W" text labels for a while, the visual difference between them is easy to mistake while mixing. The icons you propose in this PR do not have such a problem; the visual distinction is clear.

I am doubting that we will be able to convey to very many users what these icons represent just from the icons, so I think the connection to the tooltip is particularly important. Unfortunately the connection between these graphics and the "D/W" and "D+W" text in the tooltips is not clear and neither is the meaning of the lines. After stepping away from this for a while and testing it again, the icons look like some random, meaningless lines and I'm afraid that's what they'll look like to anyone not following this discussion. Can you think of any ways to convey what each line represents in the graphics? My first thought was to put the characters "D" and "W" next to the lines, but I'm not sure how helpful that would be and it would also be odd for translation. Maybe something like a water droplet or spigot to represent "wet"? This is challenging because we do not have much space to work with.

**Comment by daschuer** [comment]
Currently 2.2 and master are equal. It does not matter if we target the first or the later. 

@ronso0 has put a lot of work into this branch and looking for good alternatives, this is the result. 
I vote for tweaking the tooltips a bit and merge it. If we get complains from real users, we can reconsider the decision. 
Merging this, also does not mean that all other skins are forced to use the same design.  

We have
``` 
Adjust how the input signal D is mixed with the wet (output) signal of the effect unit
D/W mode: Mix knob crossfades between dry and wet
Use this to change the sound of the track with EQ and filter effects.
D+W mode: Mix knob adds wet to dry
Use this to change only the effected (wet) signal with EQ and filter effects.
```
how about 
``` 
Adjust how the original signal (dry=D) is mixed with the effect unit output signal (wet=W).
D/W mode (Crossing lines): Mix knob crossfades between dry and wet signal.
Use this to change the sound of the track with EQ and filter effects.
D+W mode (Flat dry line): Mix knob adds wet to 100 % dry signal. 
Use this to change only the effected (wet) signal.
```

I am actually more concerned about the missing magic for the filter effects. The Echo like effects change their mixing mode according to this parameter, but not the filter effects. 

Actually it is:
``` 
Adjust how the original signal (dry=D) is mixed with the effect unit output signal (wet=W). In case a single echo like effect is loaded this knob has no effect, in this case it defaults to D+W mode. 
D/W mode (Crossing lines): In case a filter like effect is loaded, mix knob crossfades between dry and wet signal, this produces a parasitic phaser effect. In case the filter like effect is chained after the echo like effect, the dry signal and the delayed wet signal is passed to the filter effect.
D+W mode (Flat dry line): Mix knob adds wet to 100 % dry signal. 
Use this to change only the effected (wet) signal.  In case the filter like effect is chained after the echo like effect, only the delayed wet signal is passed to the filter effect.
```

Who understands that, on the first sight?

**Comment by Be-ing** [comment]
I like your idea to describe the icons as "Crossing lines" and "Flat dry line" in the tooltip. I think that nicely solves the problem without adding visual clutter to the graphics. I don't like the other changes to the tooltip you're proposing though. We can merge this and continue discussing that in another PR for the tooltip. However a merge conflict has developed in this branch.

>  Merging this, also does not mean that all other skins are forced to use the same design.

Yes it does, we cannot use completely different designs in different skins, especially if we change the tooltip to describe the designs of the icons.

> I am actually more concerned about the missing magic for the filter effects. The filter like effects change their mixing mode according to this parameter, but not the echo like effects.

I don't know what problem you're referring to. I have not noticed any.

> Currently 2.2 and master are equal. It does not matter if we target the first or the later.

How has this happened?? There should have been no new features merged to 2.2 since it was branched. But anyway, that's a separate discussion from the topic of this PR...

**Comment by Be-ing** [comment]
@ronso0 could you adjust the mix mode icons for Deere and LateNight? I think all that needs adjustment are the colors.

**Comment by ronso0** [comment]
ot: it's a mystery to me why commit hashes of local and online branch are not identical anymore.
also I don't understand how a file that is deleted anyway in my branch suddenly creates a merge conflict. and how to solve that...

**Comment by Be-ing** [comment]
I am guessing something got rebased somewhere along the way. Maybe you need to rebase this branch?

**Comment by ronso0** [comment]
> could you adjust the mix mode icons for Deere and LateNight (in a new PR)?

So we agree on that new tooltip? If so I can change it here and fix the other skins' icons in a follow-up PR
```
Adjust how the original signal (dry=D) is mixed with the effect unit output signal (wet=W).
D/W mode (Crossing lines): Mix knob crossfades between dry and wet signal.
Use this to change the sound of the track with EQ and filter effects.
D+W mode (Flat dry line): Mix knob adds wet to 100 % dry signal. 
Use this to change only the effected (wet) signal.
```

Re: merge conflict
I'm clueless, would rebasing solve this?

**Comment by Be-ing** [comment]
>  I'm clueless, would rebasing solve this?

You can test by creating a new branch locally, rebasing, then try merging it into 2.2.

**Comment by ronso0** [comment]
okay, rebased to 2.2

**Comment by Be-ing** [comment]
There are two commits with the same commit message "Tango: fix position QuickFX enable button when no EQ is loaded" but they have totally different sets of changes. Could you `git rebase -i` to fix the commit messages?

**Comment by ronso0** [comment]
should be alright now

**Comment by Be-ing** [comment]
LGTM, thanks! Let's continue the discussion of the mix mode tooltip in a new PR.

**Pull request merged**
