### PR TITLE
Happy New Year 2020!

### PR DESCRIPTION
**Pull request by sblaisot**
Happy new year to all Mixxx team! 🎉

### CODE REVIEW

**Comment by daschuer** [comment]
Happy New Year!

**Comment by ywwg** [comment]
woooo!

**Comment by Holzhaus** [comment]
Happy New Year!

**Comment by uklotzde** [comment]
Happy new year to everyone.

Back to business: There is also licensing information with a calendar year in all cmake/modules files. Just search for the string "-2019".

**Comment by sblaisot** [comment]
Thanks for pointing that out @uklotzde 
Updated.

**Comment by uklotzde** [comment]
LGTM. Thank you!

**Pull request merged**
