### PR TITLE
Samplers master sync

### PR DESCRIPTION
**Pull request by Be-ing**
Update sampler sync buttons in LateNight and Shade to use master sync

### CODE REVIEW

**Comment by Be-ing** [comment]
I realized I changed LateNight to use text rather than the PNG images. Which way should it be? The main decks use text.

**Comment by daschuer** [comment]
LGTM 
@ywwg: ?

**Comment by daschuer** [comment]
I have just noticed that you are not a Mixxx contributor at Launchpad. 
Please sign: https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ
and comment here when done.
Thank you.

**Comment by Be-ing** [comment]
Signed.

**Comment by ywwg** [comment]
Samplers have problems with master sync because many samples don't have a bpm.  This change is ok but it may reveal some flaws in the master sync code.

**Comment by ywwg** [comment]
> the main decks use text.

I've been slowly switching everything to text.  There's no rush though

**Comment by Be-ing** [comment]
So, should I delete the unused PNG files now?

**Comment by ywwg** [comment]
I'm still not sure we should do this.  One of the problems we discovered in testing master sync is that decks would sync to the bpm of a stopped sampler, which could be very unexpected.  Allowing users to turn on sync lock on samplers will reintroduce this problem again.  I think we should fix that bug before fixing the skin or else people will have difficulty using  master sync with anything loaded in a sampler. -- allowing samplers to have a simple bpm-match should be good enough for now.

**Comment by daschuer** [comment]
Doe we have a bug for this? It sound like a critical bug if this can also happen loading a track with no beats to the decks.

**Comment by rryan** [comment]
Hello! This branch is against the 1.12 branch, which is now closed to any changes except bugfixes. Please re-open your PR against master if this PR is still relevant.

**Pull request closed without merging**
