### PR TITLE
Fix "Wrong Key format written to the file Tags"

### PR DESCRIPTION
**Pull request by Swiftb0y**
This is my yet untested attempt at fixing #10890

The reading of the tag is there, I have yet do discover all the places where the `TrackInfo` needs the key to be properly set. I have also not yet decided to how to handle the case where the user sets some custom key (guess the appropriate `ChromaticKey` and handle appropriately when we can't guess it). Also yet untested. 

Adoption is welcome.

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for picking this up. 
My work has stalled on the discussion in https://github.com/mixxxdj/mixxx/pull/11098 and 
https://github.com/mixxxdj/mixxx/pull/11301
around broken user workflow. 

I just did a brief look, but I have not found the comment. 
It mentions the need for a preferences option. Can you recal 

I think the underlying issue was that we need to make sure we do not alter extended user tags written from third party tools. 

How is the situation with this PR?

**Comment by Swiftb0y** [comment]
> It mentions the need for a preferences option. Can you recal

From what I understand summarizing the discussion, the user wants to keep the buggy behavior and have tool to rewrite from the buggy format to the standard one. That is nice to have, but feels like overcomplication to me. I wouldn't implement it if it requires more than 30 SLOC. 

> I think the underlying issue was that we need to make sure we do not alter extended user tags written from third party tools.

That is reasonable. And probably not too hard.

> How is the situation with this PR?

Neither issues have not been addressed here, but I have an idea on how to do so.

I would introduce a `key` property (similar to how I've done in this PR) that carries the `ChromaticKey` value. On import, we try guessing it from the `keyText` and store the raw key in the `keyText`. If we can't guess it, set the `ChromaticKey` to `INVALID`. On export, if the `ChromaticKey` is invalid, fallback to the `keyText`. if the `ChromaticKey` is valid, check the preferences on whether to re-export the `keyText` verbatim (legacy) or overwrite it with the `standard` notation.

Since we can't really determine whether the key exported is our non-standard text or something custom from the user carrying extra information, we can't really do much more than overwrite the key with standard notation or leave it alone.

Anyways, do you have interested in reviving #11096 so we can get this back on track?

**Comment by daschuer** [comment]
Yes, I will have y look.

**Comment by daschuer** [comment]
This is now integrated in https://github.com/mixxxdj/mixxx/pull/11096

**Comment by Swiftb0y** [comment]
superseeded by #11096

**Pull request closed without merging**
