### PR TITLE
DownmixAndOverlapHelper: Limit both read and write size

### PR DESCRIPTION
**Pull request by uklotzde**
Just a quick guess, needs to be verified! But it seems to work.

### CODE REVIEW

**Comment by Be-ing** [comment]
It works! :tada:

**Comment by Be-ing** [comment]
I'll wait to give @daschuer a chance to review this before merging.

**Comment by Be-ing** [comment]
How about refactoring DownmixAndOverlapHelper to use a SampleBuffer instead of a plain C array? We would have caught this bug sooner if this was already the case.

**Review by daschuer — CHANGES_REQUESTED** [review]
Thank you very much for finding this bug. 
I have one minor comment.  

I agree that this error may leads to unreliable results in detection, because it takes random data from after the buffer. However I cannot imagine how this can produce BPM = 0. 

Since This this is a 2.3 PR, we should keep the scope limited and not do a major refactoring.

**Comment by uklotzde** [comment]
> How about refactoring DownmixAndOverlapHelper to use a SampleBuffer instead of a plain C array? We would have caught this bug sooner if this was already the case.

I don't see the actual value to invest this time. Let's just fix all issues and then just leave this class as is.

**Review by daschuer — APPROVED** [review]

**Comment by daschuer** [comment]
Thank you. LGTM waiting fro CI.

**Comment by uklotzde** [comment]
@daschuer This file produced different BPMs (including 0) as discussed on Zulip:
http://download.wavetlan.com/SVV/Media/HTTP/AAC/MediaCoder/MediaCoder_test4_AAC-LC_v4_Stereo_ABR_32kbps_48000Hz.m4a

Please note that decoding with FFmpeg fails in after ~1/3 of the audio data, but that doesn't matter for testing. Decoding and analyzing is *slow*.

**Comment by uklotzde** [comment]
Maybe the beat analysis is susceptible or has other, yet undiscovered issues?

**Comment by daschuer** [comment]
I am afraid. We need to have an eye on this.

**Comment by Be-ing** [comment]
> I don't see the actual value to invest this time. Let's just fix all issues and then just leave this class as is.

The debug assertion in the new commit is good enough, but I'd still prefer to use a class that already has this built in than add a special case debug assertion here to preserve the use of C arrays.

**Comment by Be-ing** [comment]
CI passed :+1:

Thank you for finding the source of this bizarre bug and fixing it.

**Comment by Be-ing** [comment]
Phew, I am glad my database did not end up begin corrupted. I was getting worried when investigating this yesterday until I figured out all the broken detection was on 48 kHz tracks.

**Pull request merged**
