### PR TITLE
fix clazy issues after merging the 2.3 branch

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by uklotzde** [comment]
The dependency qtdeclarative5-dev got lost again.

**Comment by uklotzde** [comment]
Still failing

**Comment by daschuer** [comment]
Clazy is free finally. The rest is unrelated.
Sorry for all the noise.
My local clazy us soo slow compared to GitHub actions.

**Comment by uklotzde** [comment]
Thank you for taking care! LGTM

**Pull request merged**
