### PR TITLE
Change Mixxx install dir under Windows

### PR DESCRIPTION
**Pull request by sblaisot**
This PR addresses bug #1457618.

It changes the installation path of Mixxx under windows, adding the version number in it, and consequently let you install several Mixxx versions on the same computer.

It works well between 1.11 and 1.12 (you can install 1.12 on top of 1.11, and even 1.11, 1.12beta1 and 1.12 (final when available).

There is no upgrade path between 1.12beta1 (before this patch) and 1.12beta1 (after patch) because they have the same name, which makes impossible to use uninstaller to remove 1.12beta1 (before patch) after installing 1.12beta1 (after patch). But hey, If you're adventurous enough to install a beta, you should be able to manually remove a directory.
We can get rid of this if be bump version number to 1.12beta2 on the same time we merge this patch.

### CODE REVIEW

**Comment by sblaisot** [comment]
any comment, feddback ?
do we change version number to beta2 to avoid uninstall problems ?

**Comment by Be-ing** [comment]
When this is installed alongside 1.11, does this solve the issue with uninstalling one removing both?

**Comment by sblaisot** [comment]
yes, I tested installing 1.12 (with this patch) next to 1.11, and uninstalling one of them. the other one was not changed/uninstalled.

**Comment by Be-ing** [comment]
Well then, I think we should go with this bandage solution for 1.12. The next release can move to a new installer system.

**Comment by sblaisot** [comment]
following Owen's comment in bug lp:1457618, I close this PR.

It has no sense to retarget it to master because I want to work on a new installer for next release.

**Pull request closed without merging**
