### PR TITLE
Update to latest 2.4 build environment including DbInterop 0.19.1 static

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
CI doesn't run

**Comment by daschuer** [comment]
I have no idea why it would s not running. 
It is running here: 
https://github.com/daschuer/mixxx/actions/runs/5504623769

**Comment by daschuer** [comment]
The linked CI is green.

**Comment by JoergAtGithub** [comment]
Tested this locally on Windows and it works for me. Thank you!

**Pull request merged**
