### PR TITLE
32 Sampler fix 

### PR DESCRIPTION
**Pull request by daschuer**
This fixes https://bugs.launchpad.net/mixxx/+bug/1779559

### CODE REVIEW

**Comment by Pegasus-RPG** [comment]
Is there a way to add a test for the problem this solves?

**Comment by daschuer** [comment]
This was a trivial bug, I am not going to write a test for this.

**Comment by Pegasus-RPG** [comment]
Okay. I'm not clear on how your changes will affect things, that's why I asked.

**Comment by daschuer** [comment]
the issue was, that the output buffer was not cleared before the new samples where added.
So we hear garbage +  the samplers.

**Comment by uklotzde** [comment]
LGTM. I was able to reproduce the bug and verify that it has actually been fixed.

**Comment by daschuer** [comment]
Thank you for review!

**Pull request merged**
