### PR TITLE
Read controller presets from subfolders

### PR DESCRIPTION
**Pull request by ferranlala**
Make PresetInfoEnumerator scan controllers folder recursively and follow symlinks.
Organize controller presets in subfolders.
- [ ] Treat script paths relative to the preset file

### CODE REVIEW

**Comment by ferranpujolcamins** [comment]
WIP, please check that you can import your controller's preset and it works properly

**Comment by ferranpujolcamins** [comment]
True, let me see if I can make Mixxx copy the folder structure. But, how is this affected by #1524?

Also, what should we do with the JS files? What should xml midi specify?

1 - relative path from the .midi.xml file location
2 - relative path from controllers/
3 - only filename, and we search it recursively inside controllers/

**Comment by Be-ing** [comment]
I think the file path in the XML file pointing to JS files should be interpreted as a path relative to the XML file. It wouldn't make much sense to have the XML file in a subfolder and have the JS file in the folder above it.

Also, if we're doing a mass rename I think it would be a good time to make the naming convention for the XML and JS files consistent. Currently we have hyphens between words for JS files followed by the redundant word "script". For XML files we use spaces between words. Spaces are annoying to type in shells because of the need for escaping, so I'd prefer to replace spaces with hyphens, plus remove the useless "-script" suffixes.

**Comment by Be-ing** [comment]
I am planning on adding to #1524 so mappings are only copied to the user folder if they are modified via the GUI. That may create some merge conflicts with this, but I'm not sure. If you'd like to volunteer to implement that before me, please do.

**Comment by ferranpujolcamins** [comment]
If you finish your branch first, I'll do the merge with mine, no problem. If I finish first, I might take yours.

**Comment by Be-ing** [comment]
Closing this because it's not worth reworking this for the legacy controller system. In the new controller system, each mapping will get its own folder.

**Pull request closed without merging**
