### PR TITLE
Fix MSVC_REDIST_DIR issues

### PR DESCRIPTION
**Pull request by Holzhaus**
Fixes these warnings during configuration:

```
CMake Warning at C:/hostedtoolcache/windows/cmake/3.13.5/x64/cmake-3.13.5-win32-x86/share/cmake-3.13/Modules/InstallRequiredSystemLibraries.cmake:549 (message):
  system runtime library file does not exist:
  'MSVC_REDIST_DIR-NOTFOUND/x64/Microsoft.VC141.CRT/msvcp140.dll'
Call Stack (most recent call first):
  CMakeLists.txt:1089 (include)
```

I suspect this prevents that the MSVC redistributable is currently not included in the build.

### CODE REVIEW

**Comment by uklotzde** [comment]
The .msi now contains the C runtime dll:

```
  309128 16. Nov 03:57 CM_FP_Libraries.concrt140.dll
   23928 16. Nov 03:57 CM_FP_Libraries.msvcp140_1.dll
  186248 16. Nov 03:57 CM_FP_Libraries.msvcp140_2.dll
   20360 16. Nov 03:57 CM_FP_Libraries.msvcp140_codecvt_ids.dll
  585096 16. Nov 03:57 CM_FP_Libraries.msvcp140.dll
   36744 16. Nov 03:57 CM_FP_Libraries.vcruntime140_1.dll
   94088 16. Nov 03:57 CM_FP_Libraries.vcruntime140.dll
  309128 16. Nov 03:57 CM_FP_Unspecified.bin.concrt140.dll
   23928 16. Nov 03:57 CM_FP_Unspecified.bin.msvcp140_1.dll
  186248 16. Nov 03:57 CM_FP_Unspecified.bin.msvcp140_2.dll
   20360 16. Nov 03:57 CM_FP_Unspecified.bin.msvcp140_codecvt_ids.dll
  585096 16. Nov 03:57 CM_FP_Unspecified.bin.msvcp140.dll
   36744 16. Nov 03:57 CM_FP_Unspecified.bin.vcruntime140_1.dll
   94088 16. Nov 03:57 CM_FP_Unspecified.bin.vcruntime140.dll
   17920  9. Apr 2020  CM_FP_Unspecified.libEGL.dll
 3568128  9. Apr 2020  CM_FP_Unspecified.libGLESv2.dll
```

- Why have they been added twice?
- Do we still bundle the ANGLE libraries?

**Comment by Holzhaus** [comment]
No idea, sorry.

**Comment by Holzhaus** [comment]
To elaborate: I have no idea about windows packaging, I just noticed the recurring CMake warning in the build log. I didn't change naything regarding ANGLE packaging, just a bug in the static protobuf linking and used another action for setting the Winodws dev vars.

**Comment by uklotzde** [comment]
The ANGLE DLLs need to be included, I guess.

I just noticed the install(TARGETS ...) command that allows to specify the kind of resource, i.e. LIBRARY or RUNTIME.

**Comment by uklotzde** [comment]
All DLLs (ANGLE + CRT) are installed into the program folder. I can confirm that it works.

If I deselect the "Libraries" option in the installer the ANGLE DLLs are installed as before, but the CRT DLLs are not.

It would be preferred to install the CRT DLLs into the system folder, either updating an existing version or if missing. But I don't know how to achieve this.

**Review by uklotzde — APPROVED** [review]
LGTM

**Pull request merged**
