### PR TITLE
clang-format: Enable AlwaysBreakBeforeMultilineStrings

### PR DESCRIPTION
**Pull request by uklotzde**
As discussed/requested by @xerus2000 on Zulip: https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/About.20coding.20style/near/198524026

- Enable AlwaysBreakBeforeMultilineStrings
- Define custom StatementMacros (that don't require a trailing semicolon)

Statement macros with a redundant semicolon will cause warnings depending on the build settings.

### CODE REVIEW

**Review by Holzhaus — APPROVED** [review]
LGTM. I'll wait a bit so other devs can weigh in before we change clang-format settings.

However, this seems to break the line-length pre-commit hook :(

**Comment by uklotzde** [comment]
The next commits are unrelated but might fix the pre-commit failure.

**Comment by daschuer** [comment]
The version bump does not help.

This is failing:
subprocess.CalledProcessError: Command '['clang-format', '--dump-config', '/home/travis/build/mixxxdj/mixxx/tools/../src/mixxx.cpp']' returned non-zero exit status 1.

It leads that to the line-length check reformat the files with clan-format default styling.
This results into a toggling complains either of the line-lenght or the clang-format hook.

The issue is:

The issue is this: 

```
YAML:35:3: error: unknown key 'StatementMacros'
  - Q_DECLARE_FLAGS
  ^
```

It is because StatementMacros was introduced in clang-format 8. 
Ubuntu Bionic has version 6.

**Comment by Holzhaus** [comment]
So we either need to remove that config option for now, or introduce a hard limit on 80 chars line length and remove the custom hook. I'd be in favor of the latter but do as you wish :D

**Review by daschuer — CHANGES_REQUESTED** [review]
I think we need to waive of StatementMacros for now. 

What is the issue you are trying to solve by the way? 
If we compile with -wpedantic we are already warned about the extra semicolon. 

clang-format is not disturbed by this, I have just checked.  

We have the extra semicolon everywhere but 
diff clang-format will not catch it, since it is not part of the diff.

**Comment by uklotzde** [comment]
> I think we need to waive of StatementMacros for now.
> 
> What is the issue you are trying to solve by the way?
> If we compile with -wpedantic we are already warned about the extra semicolon.
> 
> clang-format is not disturbed by this, I have just checked.
> 
> We have the extra semicolon everywhere but
> diff clang-format will not catch it, since it is not part of the diff.

clang-format should not catch it. But if we remove it to avoid the warning we need to inform clang-format about the implicit semicolon.

**Comment by uklotzde** [comment]
The new pre-commit failures are unrelated and have emerged in other branches, too.

**Comment by daschuer** [comment]
> Otherwise the formatting will be wrong.

I have played a bit with Q_UNUSED
With and without Semikolon, but I cannot trick clang format. 

Do you know a case?

**Comment by uklotzde** [comment]
@daschuer Sorry. I replaced your comment instead of writing a reply. I always wonder why GitHub offers such a weird feature.

**Comment by daschuer** [comment]
Ok I agree, the feature was added to clang-format, because it is useful.
However we have no real problems in our code base that is fixed by the flags.
So lets just remove that from this PR and merge it. We can postpone the solution until we have a real issue.
Is that Ok?

**Comment by uklotzde** [comment]
I would like to keep those macros documented instead of throwing them away

**Comment by daschuer** [comment]
Yes that works for me. We can enable them once we have dropped Ubuntu Bionic.

**Comment by uklotzde** [comment]
@daschuer Ping

**Comment by daschuer** [comment]
Thank you for the remainder. LGTM.

**Review by daschuer — APPROVED** [review]

**Pull request merged**
