### PR TITLE
SyncLock: update skin with new control object names

### PR DESCRIPTION
**Pull request by ywwg**

### CODE REVIEW

**Comment by ronso0** [comment]
please update `LateNight/decks/rate_controls_compact.xml`, too.

**Comment by ywwg** [comment]
done

**Comment by ronso0** [comment]
Thanks, LGTM

btw, do we need Sync Leader as right-click action of Sync?
There's an explicit button now, and to make the Sync right-click discoverable discoverable we'd need to add a `sync_enabled_leader` tooltip ID (concatenated from existing `sync_enabled` and a new string).

**Review by uklotzde — APPROVED** [review]
Thank you! LGTM

**Comment by ronso0** [comment]
thanks @uklotzde I was pulled afk before I could hit merge...

**Pull request merged**
