### PR TITLE
Many fixes and improvements not only for openSUSE [1.12 branch]

### PR DESCRIPTION
**Pull request by jobermayr**

### CODE REVIEW

**Comment by jobermayr** [comment]
Set menu text color is required to make it readable:

Before:
before

After:
after

**Comment by daschuer** [comment]
In cinnamon desktop the menu background colour and text colour is set via the controls theme. 
Which desktop is effected on openSUSE? I am afraid this patch will break the behaviour for some other environments.

**Comment by jobermayr** [comment]
KDE 5.13.0 on openSUSE Factory.

Why should it break other environments?
It is consistent with hardcoded background color in https://github.com/mixxxdj/mixxx/blob/1.12/src/mixxx.cpp#L748 and https://github.com/mixxxdj/mixxx/blob/1.12/src/mixxx.cpp#L749.
Then we need a contrasty color to make users able to view the text.
So it doesn't depend on special environment but mixxx.

**Comment by daschuer** [comment]
> Why should it break other environments?

Every desktop environment has his own Idea how and where to display the menu bar. So I consider styling the menu bar as a desktop environment task, similar to the window decoration. 
We also do not style messages boxes and our preference window. This avoids to give Mixxx a foreign look and feel (apart form the skin). 
I believe KDE thinks the same and there must be a n other root cause for this issue we should fix.

**Comment by jobermayr** [comment]
Offending commit is: 82d5518

From http://doc.qt.io/qt-4.8/qwidget.html#palette-prop:
 > QWidget propagates explicit palette roles from parent to child.

**Comment by daschuer** [comment]
Interesting! With Cinnamon, the menu bar does not inherit the background colour of the main window. 
Are the menu bars in KDE always coloured like the main window background? 
Are there desktop wide settings to pick a common colour of all menu bars? 

We may remove the setPalette(Pal); call, which will reintroduce, the flickering before the Mixxx skin appears. But this seams to be less annoying to your issue.  We may also make this conditional for KDE or we may try to save the initial pallet and pass it to the menu bar.

Or do you have an alternative idea to remove the flickering? It was a band-aid anyway, since the flickering issue was not entirely solved by it.

**Comment by jobermayr** [comment]
> We may remove the setPalette(Pal); call, which will reintroduce, the flickering before the Mixxx skin appears. But this seams to be less annoying to your issue.

I could solve the menu issue with "Restore QMenuBar background."

**Comment by daschuer** [comment]
Thank you for your changes. It looks like a nice solution. 
Why was it required to remove the dummy file menu? 
With Cinnamon Desktop the menu bar is hidden until there is at least one menu item.
I have original added the file menu dummy to have the LaunchImage at exactly the same size
like the final Mixxx GUI. This is currently broken in this PR. (I should have added a comment :-/)

**Comment by jobermayr** [comment]
> I have original added the file menu dummy to have the LaunchImage at exactly the same size
like the final Mixxx GUI. This is currently broken in this PR. (I should have added a comment :-/)

Reverted behavior and added a comment ...

**Comment by daschuer** [comment]
LGTM. 
Thank you very much.

**Pull request merged**
