### PR TITLE
Update Reloop Beatmix 2/4 mapping to reflect new effects UI

### PR DESCRIPTION
**Pull request by sblaisot**
Following changes in effects section of Deere and Tango, update the mapping on Reloop Beatmix 2/4 to control 3 effects by effect unit by default (previously single effect mode was the default).

### CODE REVIEW

**Comment by sblaisot** [comment]
wiki updated accordingly: https://www.mixxx.org/wiki/doku.php/reloop_beatmix_4#effects_section

**Comment by sblaisot** [comment]
any chance to have this merged before 2.1 @Be-ing ?

**Comment by Be-ing** [comment]
Yes. I will review controller mappings after the beta release. Don't worry, we'll get this done in 3 months :).

**Comment by Be-ing** [comment]
I will get to reviewing this soon, but for now I will be taking a break from development and code review for a few days.

**Comment by Be-ing** [comment]
I took a look at the wiki and I don't think either of the modes make much sense for 2.1. At a minimum, I suggest mapping the knobs to the metaknobs and the Beats encoder to the dry/wet knob. Because this controller does not have buttons to toggle the enable switches of the effects, I suggest setting every effect to enabled in the `init` function. To avoid confusion when setting up like I described in #1103, you could also set the dry/wet knob to fully dry on startup.

If you want to go the extra mile and implement a way to control the parameters of effects, you could use turning the Beats encoder while holding it pushed down to switch the focus between effects.

**Comment by Be-ing** [comment]
@sblaisot unless you have time to implement the changes in my above comment within the next day or two, let's push this back to 2.2.

**Comment by Holzhaus** [comment]
What's the status of this?

**Comment by Holzhaus** [comment]
@sblaisot Do you intend to pick this up at some point, or should we close this?

**Pull request closed without merging**
