### PR TITLE
GL ES compatible Waveforms 

### PR DESCRIPTION
**Pull request by daschuer**
This introduces the waveforms:  
RGB - QT (GL ES) 
HSV - QT (GL ES)
VSynctest -QT (GL ES) 

I am not sure if that can be treated as a Bug-Fix for https://bugs.launchpad.net/mixxx/+bug/1825461
and suiting for 2.2.2 or is this a new feature for master . 

This PR is on top of https://github.com/mixxxdj/mixxx/pull/2088 which should be merged first.

### CODE REVIEW

**Comment by Be-ing** [comment]
Cool, thank you for working on this. This is a lot of new code. I think it would be more appropriate to target this for master. Hopefully someone with a Raspberry Pi can test this.

**Comment by uklotzde** [comment]
The merge conflicts caused by retargeting from 2.2 to master need to be resolved.

**Comment by daschuer** [comment]
Ready for merge.

**Comment by uklotzde** [comment]
Restarted the macOS build on Travis, just to be sure. PR can be merged after it finished successfully.

**Pull request merged**
