### PR TITLE
Add hotcue clearing support

### PR DESCRIPTION
**Pull request by tandy-1000**
As spotted by https://mixxx.discourse.group/t/a-complete-numark-dj2go2-touch-mapping/22616/2.

TODO:
- [ ] XML mapping updates?
- [ ] Testing

### CODE REVIEW

**Comment by Swiftb0y** [comment]
Thank you for filing this PR, it seems however that @doteya was faster than you #10841 (and his PR is also already complete).

**Comment by tandy-1000** [comment]
Hahaha excellent, nevermind then

**Comment by sven-simulacrum** [comment]
Hello. This change was not implemented to the latest build of Mixxx 2.3.4. I’ve tried to change the .js file manually but receive an error on line 103: "    for (let i = 1; i <= 4; i++) { " returns an error. Any advice?  Apologies I’m no coder!

**Comment by Swiftb0y** [comment]
Hey there @sven-simulacrum, clearing hotcues on the pads of the DJ2Go2 has already been implemented in another pull request (#10841). If hotcue clearing does not work as outlined in that PR, please open a separate issue and I'd be happy to work with you to resolve it.

**Comment by sven-simulacrum** [comment]
Thanks I’ve opened the issue here: https://github.com/mixxxdj/mixxx/issues/11408

**Pull request closed without merging**
