### PR TITLE
SPSCQueue: hack around libc++ bug on macOS

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by Holzhaus** [comment]
Could you post the fix upstream, so that we can just update our library copy?

**Comment by Be-ing** [comment]
I don't know if that would be appropriate. The bug was in LLVM's libc++ and has already been fixed. SPSCQueue is doing it right according to the C++ standard.

**Comment by uklotzde** [comment]
This custom ~~workaround~~hack is not suitable for an upstream fix. Are we able to restrict it to selected LLVM/Clang versions?

**Comment by uklotzde** [comment]
Still undefined, so no need for a more specific check:
https://libcxx.llvm.org/docs/FeatureTestMacroTable.html

**Comment by Be-ing** [comment]
There are [macros](https://stackoverflow.com/posts/16342320/revisions) for the clang version number, but I do not know how to get the libc++ version. I am unclear if each version of clang must be used with a certain libc++ version or if they are independent.

**Comment by Be-ing** [comment]
CI passed. Merge?

**Review by uklotzde — APPROVED** [review]
Hopefully we don't forget to re-add this patch when updating from upstream. LGTM

**Comment by Be-ing** [comment]
> Hopefully we don't forget to re-add this patch when updating from upstream.

CI will catch this quickly if we do forget it.

**Pull request merged**
