### PR TITLE
CI: Use SSH Agent to deploy to download server

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by Holzhaus** [comment]
OK, I finally found a way to work around the MSYS2 cygheap corruption. This is ready now.

**Comment by daschuer** [comment]
Thank you for digging that down.  I don't see any obvious issue. 
Did you double check that we do not expose secrets? It looks like GitHub does it well for us, right?

**Comment by Holzhaus** [comment]
No, I don't think this will expose our secrets. Ready to merge IMHO.

**Comment by daschuer** [comment]
Thank you for all this nerve-racking work ...

**Pull request merged**
