### PR TITLE
CMake: remove obsolete references to files generated by scons

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Review by daschuer — CHANGES_REQUESTED** [review]
The files are still there on a developers machine.

**Comment by Be-ing** [comment]
If someone still has old files on their machine that they have not cleaned up, that is their problem. That's not relevant to cpack which is executed on GH Actions always in a new VM.

**Comment by daschuer** [comment]
This file is not only used by GitHub actions.
These extra lines do not hurt.

**Comment by Be-ing** [comment]
What else uses these lines besides GitHub Actions?

**Review by uklotzde — APPROVED** [review]
Developers are supposed to start the build from a clean checkout. We are not able to exclude any unknown files that *might* still lay around in the local file system. The common exclude patterns in CPACK_SOURCE_IGNORE_FILES are an acceptable exception.

The only alternative would be to *explicitly* define all files/patterns that should be *included* in the set. That would be my preferred approach to avoid unintended inclusions.

**Comment by daschuer** [comment]
That is slightly different here. If you switch from to 2.2 and back the files are there. 
These extra lines are helpful and do not hurt.

**Comment by Be-ing** [comment]
By that logic we should still have these files in `.gitignore` but we have already removed those.

**Comment by daschuer** [comment]
Ups ... I see that was done here: https://github.com/mixxxdj/mixxx/pull/2777
We may consider to revert this turns out to be an issue.

**Comment by Be-ing** [comment]
Considering nobody has complained, I think there is no issue. It is unlikely anyone would accidentally commit scons files to 2.3 because they would be untracked files that would have to be intentionally staged. For CPack it is very unlikely to be a problem because CPack only needs to be run by GH Actions. There is no need for developers to run CPack locally unless they are working on packaging.

**Comment by Be-ing** [comment]
Considering nobody has complained, I think there is no issue. It is unlikely anyone would accidentally commit scons files to 2.3 because they would be untracked files that would have to be intentionally staged. For CPack it is very unlikely to be a problem because CPack only needs to be run by GH Actions. There is no need for developers to run CPack locally unless they are working on packaging.

**Comment by Holzhaus** [comment]
> That is slightly different here. If you switch from to 2.2 and back the files are there. 
> These extra lines are helpful and do not hurt. 

I though we already decided that we don't want another 2.2 release. is this really an issue?

**Comment by daschuer** [comment]
It is probably no real issue but it is extremely annoying if the huge cache directory is packed, running your system out of space. 
Compared to this keeping the ignore lines are also no issue.

**Comment by Be-ing** [comment]
You are more likely to notice the build artifacts from 2.2 if they are not in .gitignore so they show up as untracked files in `git status`.

**Comment by Be-ing** [comment]
ping

**Comment by daschuer** [comment]
Let's close this. These lines are still helpful.  The issue is, if one still has these file and likes to keep them, he as to re-add them and exclude his changes from commits. This is annoying. This comes with the cost of just three extra lines visual clutter.
There is no extra maintenance, because we will always need to maintain an exclude region in the CMakeList.txt

* cache -> a biiiig directory, duplicate it will likely eat up all HD 
* *_build -> or old recommend cmake build folder, some users might not yet have moved to build, because there is no pressing reason 
* .sconf_temp -> we never want to see this folder in a package

**Comment by uklotzde** [comment]
Let's separate those lines from the rest and leave a comment to remove them after some grace period, e.g. branching 2.4.0 beta

**Comment by Be-ing** [comment]
We now have a stable release without SCons. I don't think there's any reason to keep this legacy code.

**Review by daschuer — APPROVED** [review]
OK, now that the 2.2 branch is no longer relevant the risk of problems after merging this is marginal. LGTM

**Pull request merged**
