### PR TITLE
controllers: ensure required samplers are created

### LINKED ISSUE #12747: Pioneer DDJ-FLX4: one or more MixxxControls ... invalid (sampler count)
### Bug Description

I updated to version 401 and when mix loaded it displays an error. ive updated to version 449 same issue. I'm using the a ddj-FLEX4, on windows 10. 

one or more MixxxControls specified in the outputs section of the loaded mapping were invalid.
some LEDs and other feedback may not work correctly. 
* Check to see that the MixxxControl names are spelled correctly in the mapping file (.xml)
* Make sure the MixxxControls in question actually exist. Visit the manual for a complete list: https://manual.mixxx.org/2.4/chapters/advanced_topics.html#mixxx-controls

MIDI output message 0x98 0x34 has invalid MixxxControl [Sampler9], track_loaded
MIDI output message 0x97 0x34 has invalid MixxxControl [Sampler9], track_loaded
MIDI output message 0x9A 0x35 has invalid MixxxControl [Sampler14], track_loaded
MIDI output message 0x99 0x35 has invalid MixxxControl [Sampler14], track_loaded
MIDI output message 0x98 0x35 has invalid MixxxControl [Sampler10], track_loaded
MIDI output message 0x97 0x35 has invalid MixxxControl [Sampler10], track_loaded
MIDI output message 0x9A 0x33 has invalid MixxxControl [Sampler8], track_loaded
MIDI output message 0x99 0x33 has invalid MixxxControl [Sampler8], track_loaded
MIDI output message 0x9A 0x37 has invalid MixxxControl [Sampler16], track_loaded
MIDI output message 0x99 0x37 has invalid MixxxControl [Sampler16], track_loaded
MIDI output message 0x9A 0x34 has invalid MixxxControl [Sampler13], track_loaded
MIDI output message 0x99 0x34 has invalid MixxxControl [Sampler13], track_loaded
MIDI output message 0x9A 0x31 has invalid MixxxControl [Sampler6], track_loaded
MIDI output message 0x99 0x31 has invalid MixxxControl [Sampler6], track_loaded
MIDI output message 0x9A 0x32 has invalid MixxxControl [Sampler7], track_loaded
MIDI output message 0x99 0x32 has invalid MixxxControl [Sampler7], track_loaded
MIDI output message 0x9A 0x30 has invalid MixxxControl [Sampler5], track_loaded
MIDI output message 0x99 0x30 has invalid MixxxControl [Sampler5], track_loaded
MIDI output message 0x98 0x37 has invalid MixxxControl [Sampler12], track_loaded
MIDI output message 0x97 0x37 has invalid MixxxControl [Sampler12], track_loaded
MIDI output message 0x9A 0x36 has invalid MixxxControl [Sampler15], track_loaded
MIDI output message 0x99 0x36 has invalid MixxxControl [Sampler15], track_loaded
MIDI output message 0x98 0x36 has invalid MixxxControl [Sampler11], track_loaded
MIDI output message 0x97 0x36 has invalid MixxxControl [Sampler11], track_loaded

### Version

2.4-beta-449-gc43b5d40a3

### OS

windows 10

### LINKED ISSUE #12784: controller mappings: fix remaining [Master] VU meter connection
### Bug Description

It's [Main],vu_meter... now

### Version

2.4

### OS

_No response_

### PR DESCRIPTION
**Pull request by ronso0**
This PR simply ensures mappings request all required samplers being created, exactly like they set `[App],num_decks` if they need more than 2 decks.

With #12657 some mapping flaws produce mapping warnings, and users may not be able to resolve the issues.
This will occur with a fresh profile or when users don't have any tracks loaded in samplers with numbers higher than the deafult (4) or skin minimum (8, Shade skin).
After having merged #12657 this is just much more likely to happen.

To reproduce:
* ~~load Shade skin~~ doesn't matter, mappings are loaded before skins are created https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/2.2E4.20samplers.20regression
* close Mixxx, remove samplers.xml to ensure not more than the samplers required by the skin are created (Shade needs 8)
* start Mixxx (8 sample players are created)
* load Denon MC7000 or DDJ-FLX4 mapping (see #12747) or any of the mappings fixed in this PR
* mapping warning will popup

There may be more mappings that affected in a different way, I just did a quick check where `[Sampler` is used with
https://github.com/search?q=repo%3Amixxxdj%2Fmixxx+%22%5BSampler+path%3A%2F%5Eres%5C%2Fcontrollers%5C%2F%2F&type=code&p=2

### CODE REVIEW

**Comment by mxmilkiib** [comment]
I just so happened to delete my (pretty much unchanged apart from jog wheel LED rotation speed values) Reloop Beatmix 2/4 .js, now getting this, doh!

**Comment by ronso0** [comment]
Oh, so with the BeatMix mapping you also get complaints about missing controls for sampler 5++?

Somehow I assumed (didn't double-check) skins were loaded prior to any mapping, and Mixxx provides skins with min. 8 samplers, so #12747 would have happened with a custom skin.
But actually that is unlikely so the actual fix would be to increase the default number of samplers.
Or extend the (soft) fix to all mappinsg that need more than 4 samplers (a lot of mappings I think).

**Comment by mxmilkiib** [comment]
I was going to double check so I changed back to the default controller preset and at that point the waveform changed to this!;

image

That rings a bell though.. did someone mention it somewhere recently? Can't find an issue with a brief search

Anyway, the error on start;
```
Uncaught exception: file:///usr/share/mixxx/controllers/Reloop-Beatmix-2-4-scripts.js:181: Error: script tried to connect to ControlObject ([Sampler5], track_samples) which is non-existent.
Backtrace: @file:///usr/share/mixxx/controllers/Reloop-Beatmix-2-4-scripts.js:181
@file:///usr/share/mixxx/controllers/Reloop-Beatmix-2-4-scripts.js:195
```

**Review by ywwg — COMMENTED** [review]
do we also need an update to traktor s3?

**Comment by ronso0** [comment]
I'm pretty sure I checked all the Traktor mappings. But I didn't test them since I didn't set up a virtual HID device.

Do you still have an S3?
If yes, you can test yourself. Select the S3 mapping, close Mixxx, remove samplers.xml, restart.

**Review by daschuer — APPROVED** [review]
The changes are looking reasonable. Thank you.

**Pull request merged**
