### PR TITLE
Logging updates:

### PR DESCRIPTION
**Pull request by rryan**
* Rename --debugLevel to --logLevel and use English names for the levels.
* Add qInfo support when Qt5 is used.
* Bypass --logLevel for controller debug statements when --controllerDebug is enabled.

### CODE REVIEW

**Comment by Be-ing** [comment]
Should --developer also bypass --logLevel like --controllerDebug?

**Comment by rryan** [comment]
> Should --developer also bypass --logLevel like --controllerDebug?
You mean set log level to 'debug'  if --developer is set? SGTM

**Comment by Be-ing** [comment]
> You mean set log level to 'debug' if --developer is set?

Yes, that's what I mean.

**Comment by Be-ing** [comment]
I have tested this and it works well. Thanks!

**Comment by Be-ing** [comment]
--controllerDebug should turn on printing from JS without having to specify --logLevel debug

**Comment by rryan** [comment]
> --controllerDebug should turn on printing from JS without having to specify --logLevel debug

Good point -- done.

**Comment by Be-ing** [comment]
I tested again and it works. LGTM. 👍

**Pull request merged**
