### PR TITLE
add taglib path to includes

### PR DESCRIPTION
**Pull request by m0dB**
I needed to add taglib/ to some includes in order to be able to compile main.

### CODE REVIEW

**Comment by daschuer** [comment]
The `taglib` prefix has been removed for all taglib includes on purpose, because taglib 2.0 supports to be installed with the taglib-2 suffix. Which cpp file fails to build? Probably the taglib include is not used for that.

**Review by daschuer — CHANGES_REQUESTED** [review]
You need to use the taglib includes to make it work.

**Comment by m0dB** [comment]
Sorry, I don't understand what you mean by that.

**Comment by m0dB** [comment]
The files included by `src/track/taglib/trackmetadata_file.h` are located in the buildenv installed by `source tools/buildenv.sh setup`, as described [here in zulipchat](https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Build.20on.20macOS.20ARM64/near/421939913) in `buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/taglib/`

This path is not added to the include paths. If `taglib/` was removed from the includes, something must be missing elsewhere, otherwise it will not compile.

**Comment by daschuer** [comment]
Can you post the ninja output inclusive the command line that leads to this error?

**Comment by m0dB** [comment]
```
FAILED: CMakeFiles/mixxx-qml-lib.dir/mixxx-qml-lib_qmltyperegistrations.cpp.o 
/usr/local/bin/ccache /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DMIXXX_USE_QML -DMIXXX_USE_QOPENGL -DQT_CONCURRENT_LIB -DQT_CORE5COMPAT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKCONTROLS2_LIB -DQT_QUICKWIDGETS_LIB -DQT_QUICK_LIB -DQT_SQL_LIB -DQT_SVGWIDGETS_LIB -DQT_SVG_LIB -DQT_TESTCASE_BUILDDIR=\"/Users/maarten/git/mixxx/build\" -DQT_TESTCASE_SOURCEDIR=\"/Users/maarten/git/mixxx\" -DQT_TESTLIB_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -D__BROADCAST__ -I/Users/maarten/git/mixxx/build/mixxx-qml-lib_autogen/include -I/Users/maarten/git/mixxx -I/Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtQml/6.5.3 -I/Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtQml/6.5.3/QtQml -I/Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtCore/6.5.3 -I/Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtCore/6.5.3/QtCore -I/Users/maarten/git/mixxx/src/control -I/Users/maarten/git/mixxx/src/qml -I/Users/maarten/git/mixxx/src -I/Users/maarten/git/mixxx/build/src -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtCore -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6 -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/share/Qt6/mkspecs/macx-clang -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtQml -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtQmlIntegration -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtNetwork -isystem /Users/maarten/git/mixxx/lib/rigtorp/SPSCQueue/include -isystem /Users/maarten/git/mixxx/lib/portaudio -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtConcurrent -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtGui -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtOpenGL -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtPrintSupport -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtWidgets -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtSql -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtSvg -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtTest -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtXml -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtSvgWidgets -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtCore5Compat -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtQuick -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtQmlModels -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtQuickControls2 -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include/Qt6/QtQuickWidgets -isystem /Users/m0dB/git/mixxx/buildenv/mixxx-deps-2.5-arm64-osx-min1100-release-bea61fb/installed/arm64-osx-min1100-release/include -fdiagnostics-color=auto -O3 -DNDEBUG -std=gnu++20 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -mmacosx-version-min=11.0 -fvisibility=hidden -fvisibility-inlines-hidden -pipe -O3 -ffast-math -funroll-loops -fomit-frame-pointer -ffunction-sections -fdata-sections -MD -MT CMakeFiles/mixxx-qml-lib.dir/mixxx-qml-lib_qmltyperegistrations.cpp.o -MF CMakeFiles/mixxx-qml-lib.dir/mixxx-qml-lib_qmltyperegistrations.cpp.o.d -o CMakeFiles/mixxx-qml-lib.dir/mixxx-qml-lib_qmltyperegistrations.cpp.o -c /Users/maarten/git/mixxx/build/mixxx-qml-lib_qmltyperegistrations.cpp
In file included from /Users/maarten/git/mixxx/build/mixxx-qml-lib_qmltyperegistrations.cpp:19:
In file included from /Users/maarten/git/mixxx/src/qml/qmlplayermanagerproxy.h:7:
In file included from /Users/maarten/git/mixxx/src/qml/qmlplayerproxy.h:10:
In file included from /Users/maarten/git/mixxx/src/track/track.h:8:
In file included from /Users/maarten/git/mixxx/src/sources/metadatasource.h:8:
In file included from /Users/maarten/git/mixxx/src/track/trackmetadata.h:7:
In file included from /Users/maarten/git/mixxx/src/track/trackinfo.h:9:
In file included from /Users/maarten/git/mixxx/src/track/serato/tags.h:8:
In file included from /Users/maarten/git/mixxx/src/track/serato/beatgrid.h:12:
/Users/maarten/git/mixxx/src/track/taglib/trackmetadata_file.h:3:10: fatal error: 'aifffile.h' file not found
#include <aifffile.h>
```

**Comment by daschuer** [comment]
Ah I see a taglib depedency is missing.

**Comment by daschuer** [comment]
I have prepared a fix here: https://github.com/mixxxdj/mixxx/pull/12830

**Pull request closed without merging**
