### PR TITLE
install multiple sizes of rasterized icons

### PR DESCRIPTION
**Pull request by Be-ing**
The Flathub manifest renames the icon to work around this: https://github.com/flathub/org.mixxx.Mixxx/blob/master/org.mixxx.Mixxx.yaml#L274

### CODE REVIEW

**Comment by uklotzde** [comment]
This change might break existing packaging recipes and requires a note for maintainers.

**Review by uklotzde — APPROVED** [review]

**Comment by Holzhaus** [comment]
Two points:

1. We shouldn't rename our icon to match some ID used by some other application (flatpak) that we do not control. 
2.  This violates the freedesktop icon naming specification, which states:

> An application must either use a generic application icon name provided by this specification, or install an icon named the same as the executable for running the application.

I'm not willing to rename the `mixxx` executable to `org.mixxx.Mixxx`, so I don't think we should merge this.

**Comment by uklotzde** [comment]
I was assuming that this renaming was due to some freedesktop conventions according to the other PRs, but missed to actually verify it myself. If this is not the case and the naming is only a custom convention of flatpak then we should not follow it blindly.

In this respect I agree with @Holzhaus.

@Be-ing Next time please add the rationale in the description of the PR to prevent such misunderstandings.

**Comment by uklotzde** [comment]
@Holzhaus I wonder why the icon naming convention doesn't follow that of the .desktop file and ID naming convention? Doesn't make any sense to me, because it will result in naming conflicts.

**Comment by Be-ing** [comment]
I am confused as well. I don't understand why Flathub wants it to be reverse DNS in conflict with the icon naming specification.

**Comment by Be-ing** [comment]
Regardless we should install rasterized versions though.

**Comment by Be-ing** [comment]
Let's see what happens with `mixxx.svg` and `mixxx.png`... https://github.com/flathub/org.mixxx.Mixxx/pull/35

**Comment by Be-ing** [comment]
Yeah [Flathub builds break with `mixxx.svg` and `mixxx.png`](https://flathub.org/builds/#/builders/8/builds/6717):

```
Running appstream-compose
FB: Running: flatpak build --die-with-parent --nofilesystem=host /srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-FrBg2z appstream-compose --prefix=/app --origin=flatpak --basename=org.mixxx.Mixxx org.mixxx.Mixxx
Processing application org.mixxx.Mixxx
Error loading desktop file: Failed to find icon: Failed to find icon org.mixxx.Mixxx
Error: ERROR: appstream-compose failed: Child process exited with code 1
```

**Comment by Be-ing** [comment]
I opened an [issue on Flathub](https://github.com/flathub/flathub/issues/2463)... let's see what the response is.

**Comment by Holzhaus** [comment]
For now, I suggest to just leave the name unchanged and take care of the renaming in the flatpak packaging code. Then we can at least merge the other stuff in this PR.

**Comment by Be-ing** [comment]
It's not just Flathub, building the Flatpak locally has the same issue:

```
Finishing app
Exporting share/applications/org.mixxx.Mixxx.desktop
Exporting share/icons/hicolor/scalable/apps/org.mixxx.Mixxx.svg
Not exporting share/icons/hicolor/32x32/apps/mixxx.png, non-allowed export filename
Exporting share/icons/hicolor/32x32/apps/org.mixxx.Mixxx.png
Exporting share/icons/hicolor/64x64/apps/org.mixxx.Mixxx.png
Exporting share/icons/hicolor/128x128/apps/org.mixxx.Mixxx.png
Exporting share/icons/hicolor/256x256/apps/org.mixxx.Mixxx.png
Exporting share/icons/hicolor/512x512/apps/org.mixxx.Mixxx.png
```

**Comment by Be-ing** [comment]
I reported the [issue](https://github.com/flatpak/flatpak/issues/4368) to Flatpak.

**Comment by Holzhaus** [comment]
Does installing a flatpak package install an executable? If not, the executable would be `flatpak` with the app name `org.mixxx.Mixxx` passed on the command line. If you strictly adhered to the icon naming spec, you'd have to name the icon `flatpak.svg` which would be nonsensical and cause conflicts if multiple flatpak apps are installed. So I guess using the reverse DNS name is the next best thing in this specific case. But generally, the icon name should stay `mixxx.svg` and the flatpak packager needs to take care of the renaming.

**Comment by Be-ing** [comment]
ping

**Review by uklotzde — APPROVED** [review]
Thank you! LGTM

**Pull request merged**
