### PR TITLE
fix HID controller output on Windows with common-hid-packet-parser.js

### PR DESCRIPTION
**Pull request by Be-ing**
Specifying the report ID is required on Windows as discovered in [this forum thread](https://mixxx.org/forums/viewtopic.php?f=3&t=11946).

### CODE REVIEW

**Comment by Be-ing** [comment]
Hmm, maybe this should be done in C++ rather than JS?

**Comment by Be-ing** [comment]
> Hmm, maybe this should be done in C++ rather than JS?

No, the problem is that the [JS is relying on an implementation quirk of hidapi on Linux](https://mixxx.org/forums/viewtopic.php?p=38832#p38832).

**Comment by Be-ing** [comment]
@fayaaz can you test this on both Windows and Linux?

**Comment by daschuer** [comment]
Who is able to qualify this? Or should we merge this just as it is?

**Comment by Be-ing** [comment]
I don't think we should merge this without any testing. We may break HID output on Linux where it is working without testing.

**Comment by daschuer** [comment]
What is the state here?

**Comment by Be-ing** [comment]
Still no one has tested this.

**Comment by Xerus2000** [comment]
I'll test it for the Traktor Kontrol F1

**Comment by Pegasus-RPG** [comment]
At first glance, this diff appears to be losing information, especially on the Wiimote and CDJ scripts. Can you state what your aim was with these changes?

**Comment by Xerus2000** [comment]
Moving discussion/debugging to https://mixxx.zulipchat.com/#narrow/stream/113295-controller-mapping/topic/HID.20Mapping now.

**Comment by Pegasus-RPG** [comment]
Also, the proposed solution in the Wiki can be confusing. If we should always send the first byte as the report ID, then we should just do it in C++ so writing scripts is straightforward. But some devices actually use different report IDs, so we can't make that assumption. So before we change anything in Mixxx, should something in HIDAPI be changed? Let's submit a patch there if so rather than hacking around it here.

**Comment by Be-ing** [comment]
@Pegasus-RPG the way common-hid-packet-parser.js was identifying packets before, using packet lengths, was inappropriate. As far as I can tell, it should be using report IDs to differentiate packets. That is why the packet length was removed in some scripts.

**Comment by Xerus2000** [comment]
I guess we should close this and I will then open a new PR from my branch, since I can actually test it all.

**Comment by Be-ing** [comment]
Okay, I'll close this when you open a new PR.

**Pull request closed without merging**
