### PR TITLE
update minimum requirements to Ubuntu 20.04

### PR DESCRIPTION
**Pull request by Be-ing**
Per https://github.com/mixxxdj/mixxx/wiki/Minimum-requirements-policy, this may not be merged until Ubuntu 20.04.1 is released on August 6, 2020.

### CODE REVIEW

**Comment by uklotzde** [comment]
- this PR should be rebased when due
- right before merging we could remove all workarounds for Qt < 5.12

**Comment by Holzhaus** [comment]
> * right before merging we could remove all workarounds for Qt < 5.12

Why before? If we do it afterwards, these changes can be checked by CI.

**Comment by Be-ing** [comment]
I think @uklotzde meant in the same pull request.

**Comment by Be-ing** [comment]
Ready for merge?

**Comment by daschuer** [comment]
Let's not break Ubuntu Bionic 18.4 builds before we have merged a PR that requires that.

**Comment by JoergAtGithub** [comment]
There is a merge conflict

**Comment by Be-ing** [comment]
Yes I will rebase this soon.

**Pull request closed without merging**
