### PR TITLE
Devendor FindSQLite3.cmake

### PR DESCRIPTION
**Pull request by daschuer**
It is part of CMake since 3.13 and defines SQLite::SQLite3, without 3

https://cmake.org/cmake/help/latest/module/FindSQLite3.html

### CODE REVIEW

**Comment by ronso0** [comment]
no comment on the code change, but [macOS builds fail](https://github.com/mixxxdj/mixxx/runs/4553482859?check_suite_focus=true#step:17:302).

**Comment by daschuer** [comment]
Mmm that strange, I have no idea where 'SQLite3::SQLite3' is comming from on Mac

```
 CMake Error at /Users/runner/buildenv/mixxx-deps-2.4-x64-osx-058063e/scripts/buildsystems/vcpkg.cmake:538 (_add_executable):
  Target "mixxx-test" links to target "SQLite3::SQLite3" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:1571 (add_executable)
```

**Comment by Be-ing** [comment]
It was your choice to reject a fully working solution...

**Comment by daschuer** [comment]
This PR will succeed, once we have switched to the environment including this: https://github.com/mixxxdj/vcpkg/pull/27

**Comment by Be-ing** [comment]
No, it won't, because you're creating a circular dependency. Again, this was already resolved but you rejected the solution.

**Comment by Holzhaus** [comment]
I'll mark this as draft until all CI checks are green.

**Comment by daschuer** [comment]
This depends on https://github.com/mixxxdj/vcpkg/pull/38

**Comment by daschuer** [comment]
There is a single prerequisite missing, merging from upstream vcpkg:  https://github.com/mixxxdj/vcpkg/pull/41
Can one have a look?

**Comment by daschuer** [comment]
This needs to become part of https://github.com/mixxxdj/mixxx/pull/4717 to fix the build failure.

**Pull request closed without merging**
