### PR TITLE
Fix replay gain analysis

### LINKED ISSUE #13702: ReplayGain Analysis is broken
### Bug Description

The track property remains empty.

```
warning [AnalyzerThread 1 #2] AnalyzerEbur128::storeResults() averageLufs invalid: -10.4834
```

### Version

2.5, main

### OS

_No response_

### PR DESCRIPTION
**Pull request by uklotzde**
Fixes #13702.

### CODE REVIEW

**Comment by uklotzde** [comment]
How could such an obvious bug slip through?

**Review by Holzhaus — APPROVED** [review]

**Comment by Holzhaus** [comment]
Weird indeed. Thanks for the fix!

**Comment by ronso0** [comment]
"Lazyness, on a laaazy afternoooooon 🎶

sorry.
we should make make building and smoke testing mandatory somehow

**Comment by Swiftb0y** [comment]
indeed

**Pull request merged**
