### PR TITLE
Numark DJ2GO2 Touch: Correct sysex message to get control settings at startup

### LINKED ISSUE #11658: Numark DJ2GO2 Touch controller script has incorrect sysex message
### Bug Description

The current sysex message does not retrieve the control settings from the controller since it is using the wrong manufacturer and device id. I have the correct sysex message tested under Windows 11 and Ubuntu 22.04.2 which I will create a pull request for when assigned to me.

It isn't a critical bug but it is annoying. The file with the problem is: res/controllers/Numark_DJ2GO2_Touch_scripts.js

### Version

2.3.5

### OS

Windows11 and Ubuntu 22.04.2

### PR DESCRIPTION
**Pull request by burnsak**
Fixes #11658

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Welcome and thanks for improving this! Please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

**Comment by JoergAtGithub** [comment]
@tandy-1000 Could you test, if these Numark DJ2GO2 Touch mapping changes works with your device too? Especially the sysex message can only be tested by someone, who has such a controller.

**Comment by burnsak** [comment]
> Welcome and thanks for improving this! Please sign the [Mixxx Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) and comment here when you have done so. It gives us permission to distribute your contribution under the GPL v2 or later license and the Apple Mac App Store. It is also helpful for us to have contact information for contributors in case we may need it in the future.

I signed the agreement

**Comment by tandy-1000** [comment]
Works for me!

**Comment by JoergAtGithub** [comment]
@burnsak  Thank you, for improving this mapping!
@tandy-1000 Thank you, for testing the improved mapping!

**Pull request merged**
