### PR TITLE
fix playlist import, Lp1814469

### PR DESCRIPTION
**Pull request by daschuer**
This is a fix for
https://bugs.launchpad.net/mixxx/+bug/1814469
a regression since QT5

It also uses the enhances QUrl() constructor of QT5

### CODE REVIEW

**Comment by daschuer** [comment]
This continues https://github.com/mixxxdj/mixxx/pull/2020

**Comment by uklotzde** [comment]
LGTM. The test will prevent further regressions and can be extended if we get any new bug reports :+1:

**Comment by daschuer** [comment]
I am only afraid the test may fail on windows because QUrl might work OS dependent. 
I hope AppVeyor does not time out.

**Review by uklotzde — CHANGES_REQUESTED** [review]
Test failure on Windows:
```
[ RUN      ] PlaylistTest.Normalize
src\test\playlisttest.cpp(19): error: Value of: "/c:/foo/bar.mp3"
Expected: parser.playlistEntrytoLocalFile("file:///c:/foo/bar.mp3").toStdString().c_str()
Which is: "c:/foo/bar.mp3
```

**Comment by daschuer** [comment]
Great, so it works, we just to need to make the test conditional.

**Comment by daschuer** [comment]
Now it should work

**Review by uklotzde — APPROVED** [review]

**Comment by uklotzde** [comment]
LGTM, waiting for the CI builds.

**Comment by daschuer** [comment]
All checks have passed :-)

**Pull request merged**
