### PR TITLE
default.nix: Add script to run Mixxx inside gdb

### PR DESCRIPTION
**Pull request by haslersn**

### CODE REVIEW

**Comment by haslersn** [comment]
Why did **continuous-integration/appveyor/pr** fail?

**Comment by daschuer** [comment]
It has a 1h timeout.

**Comment by daschuer** [comment]
Is this ready to merge?
I have not tested it, but I think in this case we can fix issues upstream if there are any.

**Comment by haslersn** [comment]
Yes, I tested it.

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
