### PR TITLE
pre-commit: Add hooks for Python

### PR DESCRIPTION
**Pull request by Holzhaus**
This adds linting and autoformatting for Python code. As the code in the `build/` directory would require extensive changes, I'd propose to schedule this for 2.4.0 when we drop `SCons` and remove the `build/` directory.

### CODE REVIEW

**Comment by daschuer** [comment]
Original I got the same issues on Xenial. 

in my case it works with: 

sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.7
python3.7 /usr/bin/pip3 install --user pre-commit
pre-commit install

**Comment by Holzhaus** [comment]
Thanks. I already fixed it in #2485, but forgot to pull the changes into this branch ;-)

**Comment by daschuer** [comment]
In general we don't want to mass refactoring for code style. 
How about using https://github.com/wbolster/black-macchiato
a git-clang-format equivalent. 
In this case we can start using black now.

**Comment by Holzhaus** [comment]
Hmm, when we drop SCons we only have a handful of python-scripts in the `scripts` directory. And most of them wouldn't pass the `flake8` check either. Since they are only a few helper tools I'd say changing code automatically is not optimal but okay-ish. If you insist, I'll see if I can integrate macchiato, but I'm not sure if I find a solution for flake8.

**Comment by daschuer** [comment]
Let's treat code smell and style issues differently. Mass refectoring for the first is appropriate, but not for the later.

This means it is Ok to use flake8 on whole files. For black a diff based solution will allow us to commit this immediately.
If we don't have it we need to wait after scons. 
Or is there no need for it at all after scons ... :-/

**Comment by Holzhaus** [comment]
Well, we do have python helper scripts in the `scripts` directory. We can also restrict the linters to that directory and ignore `build/`.

**Comment by Holzhaus** [comment]
I fixed the style issues (and some bugs like undefined variables) for the Python scripts in the scripts directory. I also ported them over to Python 3 (Python 2 was released in 2000 (!) and is EOL since January 1st).

**Comment by uklotzde** [comment]
Are these changes ready to be merged?

**Comment by Holzhaus** [comment]
> Are these changes ready to be merged?

Yes.

**Comment by daschuer** [comment]
Than let's do it.
LGTM.

**Pull request merged**
