### PR TITLE
Cache appveyor-tools

### PR DESCRIPTION
**Pull request by daschuer**
This is a workaround for the build failures due to download limit of https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1

### CODE REVIEW

**Comment by daschuer** [comment]
Unfortunately we cant check it as a PR. 
Here is a test run that shows that the cache itself works: https://github.com/daschuer/mixxx/runs/4472904620?check_suite_focus=true

**Comment by Holzhaus** [comment]
IMHO we should get rid of the manual emcryption altogether and use GH Secrets instead.

**Comment by daschuer** [comment]
Yes that's would be better, but can be only done by @rryan the certificate owner. This is a band aid for the meantime.
Merge?

**Review by ywwg — APPROVED** [review]
I think this is acceptable for now -- do we have a bug filed for moving to GH secrets or similar?

**Comment by daschuer** [comment]
I have just filed one: 
https://bugs.launchpad.net/mixxx/+bug/1954961

**Comment by Holzhaus** [comment]
I think we can just ping @rryan.

**Comment by daschuer** [comment]
@Holzhaus can we merge this as an intermediate step?

**Comment by Holzhaus** [comment]
> @Holzhaus can we merge this as an intermediate step? 

Yes, although we were already close to maxing out the allowed cache size IIRC, so I'm a bit worried that this could result in much longer build times.

The proper fix should only take a few minutes. I'll ping @rryan on Zulip.

**Comment by Swiftb0y** [comment]
We stopped using appveyor. Can this PR be closed then?

**Comment by daschuer** [comment]
With the new signing, this PR is no longer relevant.

**Pull request closed without merging**
