### PR TITLE
LateNight: move preview deck above search bar

### PR DESCRIPTION
**Pull request by ronso0**

### CODE REVIEW

**Comment by ronso0** [comment]
reminder: close https://bugs.launchpad.net/mixxx/+bug/1906973

**Comment by ronso0** [comment]
@Holzhaus Merge?

**Comment by Holzhaus** [comment]
I'm "already" in bed and only have my phone, so can't test this. Will do tomorrow morning.

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you. CI failure is unrelated (see #3527).

**Comment by ronso0** [comment]
whoops, I over-optimized something here, the feature Dlgs look broken now.
will fix that soon.

**Pull request merged**
