### PR TITLE
packaging: strip trailing newline from CPACK_DEBIAN_PACKAGE_DESCRIPTION

### PR DESCRIPTION
**Pull request by ronso0**
I couldn't test PR artifacts on Ubuntu 20.04 becasue `dpkg 1.19.7 (amd64)` refused to install DEB package due to blank line after package description
```
dpkg: error processing archive Mixxx-HEAD-r8107-e6c2463023.deb (--install):
  parsing file '/var/lib/dpkg/tmp.ci/control' near line 10:
  blank line in value of field 'Description'
```

### CODE REVIEW

**Comment by ronso0** [comment]
tested locally with `cpack -G DEB` :heavy_check_mark:

**Comment by ronso0** [comment]
> tested locally with `cpack -G DEB` heavy_check_mark

meeh, not fixed. artifact still fails to install with the same error.
so `Package` and `Package for PPA` are different, and artifacts are the results of the latter?
cpack -G DEB` vs `cpack -G External -D DEB_SOURCEPKG=ON` > uses dpkg-buildpackage

**Comment by ronso0** [comment]
will look into this again tomorrow, but @daschuer you can provide a fix more quickly?

maybe we add a pre-commit hook to strip the trailing newline from CPACK_DEBIAN_PACKAGE_DESCRIPTION instead of hacking around an hook-enforced newline?

**Comment by daschuer** [comment]
This is strange, because my local 
```
cpack -G DEB 
```
works. 

Tested on Ubuntu Focal 20.4 using cmake version 3.16.3

This must be an issue with cmake 3.13 our minimum requirement.

**Comment by daschuer** [comment]
Let's have a look if this works
https://github.com/mixxxdj/mixxx/pull/3756

**Comment by ronso0** [comment]
> This is strange, because my local
> 
> ```
> cpack -G DEB 
> ```
> 
> works.
> 
> Tested on Ubuntu Focal 20.4 using cmake version 3.16.3
> 
> This must be an issue with cmake 3.13 our minimum requirement.

yeah that works for me, too,here

**Comment by daschuer** [comment]
See: https://github.com/mixxxdj/mixxx/pull/3756

**Comment by ronso0** [comment]
Thanks @daschuer

**Pull request closed without merging**
