### PR TITLE
CMake: fix detection of SoundTouch pkgconfig file and version

### PR DESCRIPTION
**Pull request by Be-ing**
I noticed this bug after copying this module to Tenacity.

### CODE REVIEW

**Comment by daschuer** [comment]
The version constrain does not seem to work: 
```
-- Found SoundTouch: /usr/lib/x86_64-linux-gnu/libSoundTouch.so  
-- Linking libSoundTouch dynamically
```
Tested in a fresh build directory and SoundTouch 1.9.2 installed. 

If I remove the QUIET flag it prints; 
```
-- Checking for module 'soundtouch>=2.1.1'
--   Requested 'soundtouch >= 2.1.1' but version of SoundTouch is 1.9.2
```

**Review by daschuer — CHANGES_REQUESTED** [review]
This does not yet work as intended.

**Comment by uklotzde** [comment]
```
$ pkgconf --list-all | grep -i soundtouch
soundtouch                     SoundTouch - SoundTouch is an open-source audio processing library for changing the Tempo, Pitch and Playback Rates of audio streams or files
libSoundTouch                  SoundTouch - SoundTouch is an open-source audio processing library for changing the Tempo, Pitch and Playback Rates of audio streams or files
soundtouch-1.0                 SoundTouch - SoundTouch is an open-source audio processing library for changing the Tempo, Pitch and Playback Rates of audio streams or files
```

@daschuer Please post the output on the affected system.

@Be-ing Did you try to use `libSoundTouch` instead of `soundtouch`?

**Comment by uklotzde** [comment]
All 3 variants on Fedora 34:

```
-- Checking for module 'SoundTouch>=2.1.1'
--   Package 'SoundTouch', required by 'virtual:world', not found
-- Found SoundTouch: /usr/lib64/libSoundTouch.so  
-- Linking libSoundTouch dynamically
```

```
-- Checking for module 'soundtouch>=2.1.1'
--   Package dependency requirement 'soundtouch >= 2.1.1' could not be satisfied.
Package 'soundtouch' has version '2.0.0', required version is '>= 2.1.1'
-- Found SoundTouch: /usr/lib64/libSoundTouch.so  
-- Linking libSoundTouch dynamically
```

```
-- Checking for module 'libSoundTouch>=2.1.1'
--   Package dependency requirement 'libSoundTouch >= 2.1.1' could not be satisfied.
Package 'libSoundTouch' has version '2.0.0', required version is '>= 2.1.1'
-- Found SoundTouch: /usr/lib64/libSoundTouch.so  
-- Linking libSoundTouch dynamically
```

None seems to be correct.

**Comment by uklotzde** [comment]
The `libSoundTouch.pc` file in Fedora 34 is outdated and advertises `Version: 2.0.0` :see_no_evil:

**Comment by uklotzde** [comment]
The current package name `SoundTouch` is wrong, both `soundtouch` or `libSoundTouch` should work.

**Comment by uklotzde** [comment]
The wrong version number is caused by an outdated [configure.ac](https://gitlab.com/soundtouch/soundtouch/-/blob/2.1.1/configure.ac). This has been fixed for the new version 2.3.0.

**Comment by uklotzde** [comment]
`soundtouch` is the official package name according to the build spec in Fedora:

```
# pkgconfig compat links for compat with older (API compatible) releases
# dunno why upstream keeps changing the pkgconfig name
# Update 2016-02-13: now looks like that is soundtouch.pc without version
ln -s soundtouch.pc %{buildroot}%{_libdir}/pkgconfig/libSoundTouch.pc
ln -s soundtouch.pc %{buildroot}%{_libdir}/pkgconfig/soundtouch-1.0.pc
```

**Comment by uklotzde** [comment]
https://src.fedoraproject.org/rpms/soundtouch/pull-request/2

**Comment by daschuer** [comment]
On Ubuntu Groovy I have this: 
```
pkg-config --list-all | grep -i soundtouch
soundtouch                     SoundTouch - SoundTouch is an open-source audio processing library for changing the Tempo, Pitch and Playback Rates of audio streams or files
```

**Comment by daschuer** [comment]
The found version is not checked, because it is not passed too find_package_handle_standard_args like here:
https://github.com/mixxxdj/mixxx/blob/50b40ab20125bd9eee8982e1ed0025dbcf86b67c/cmake/modules/Findhidapi.cmake#L100

**Review by uklotzde — APPROVED** [review]
I can confirm that the package name `soundtouch` is correct.

The version detection works for SoundTouch 2.1.2 and newer. It was broken for SoundTouch 2.1.0 and 2.1.1.

Unless we fix this bug on our side Fedora and any other distribution will not be able to use the system library for Mixxx and always link the bundled version statically.

@daschuer Please work with upstream Debian/Ubuntu if they ship an outdated package as we did for Fedora.

**Comment by uklotzde** [comment]
@Be-ing Please change the target branch to 2.3.

**Comment by uklotzde** [comment]
We could also increase the required version number to 2.1.2 due to the buggy package configuration of SoundTouch 2.1.1.

**Comment by uklotzde** [comment]
Ubuntu 20.04: 2.1.2
Ubuntu 18.04: 1.9.2

It doesn't matter why the version detection for 18.04 fails, SoundTouch is too old anyway.

**Comment by daschuer** [comment]
> @daschuer Please work with upstream Debian/Ubuntu if they ship an outdated package as we did for Fedora.

The most recent Ubuntu Impish 21.10 ships  SoundTouch 2.2 which is identified as 2.2 in the lower case pc file. The Name in the pc file is upper case. Both matches the upstream repro. So I it looks like everything is correct for Ubuntu. 

I can confirm that only the lower case lookup works: 
```
pkg-config soundtouch --modversion
2.1.2
```

I don't think we have an issue on Fedora, because even though it falsely identifies itself at 2.1.1 it still meets our requirements.

**Comment by daschuer** [comment]
The pending issue here, preventing the merge, is that the version constrains in the pkg-config call is bypassed by the find_library() later call https://github.com/mixxxdj/mixxx/pull/4209#issuecomment-899291059

**Comment by uklotzde** [comment]
Requiring the broken version 2.1.1 is pointless, because it will never be found.

**Comment by uklotzde** [comment]
Ubuntu 20.04 build artifact is linked dynamically:

```
ldd /tmp/mixxx | grep -i SoundTouch
libSoundTouch.so.1 => not found
```

@daschuer So what's your issue here? The appended `.1` version of the .so file that should actually be `.2`? Fedora packaging includes a patch for this that has been submitted upstream now and is included in SoundTouch 2.3.1.

**Comment by uklotzde** [comment]
Unfortunately 18.04 is not built even after switching the base branch.

**Comment by uklotzde** [comment]
No issues on Fedora:

```
ldd mixxx | grep SoundTouch
libSoundTouch.so.2 => /lib64/libSoundTouch.so.2 (0x00007f54ec5a4000)
```

**Comment by daschuer** [comment]
> Requiring the broken version 2.1.1 is pointless, because it will never be found.

We require soundtouch>=2.1.1which is found a s 2.1.2 or whatever, so there is no issue. 

2.1.1 is our version in the lib folder. It looks odd if we require a higher version that we provide. 
Once all our targets provide this or a higher version we can remove sound touch from our lib folder.

> @daschuer So what's your issue here?

The issue is that requiring a version in the OPTIONAL  pkg_check_modules branch is pointless if it is not also checked in the final find_package_handle_standard_args().

That's all.

**Comment by uklotzde** [comment]
Let's please merge this simple fix and then you could provide a follow-up PR.

**Comment by daschuer** [comment]
We can't mege this to 2.3 because it is a regression for Ubuntu 18.04.

It is easy to meke this megeable, see my comment where I have already ouined the solution:
https://github.com/mixxxdj/mixxx/pull/4209#issuecomment-907784728

**Comment by Be-ing** [comment]
I moved the version check from the pkgconfig call, which didn't do anything because of the find_library, to the root CMakeLists.txt. Like hidapi, I implemented a fallback of reading the version from SoundTouch.h in case pkgconfig is not available.

**Comment by uklotzde** [comment]
CI build succeeded. @daschuer Ready now?

**Review by daschuer — APPROVED** [review]
LGTM, Thank you. It is working as desired on Ubuntu Bionic and Groovy.

**Pull request merged**
