### PR TITLE
Deere: Refactored mixer buttons.

### PR DESCRIPTION
**Pull request by ferranlala**
New mixer layout with better usable buttons!

### CODE REVIEW

**Comment by ferranpujolcamins** [comment]
Known bug: when no EQ is selected in 4deck mode, there's a big gap between the key knob and the vumeter. This space should be taken by the vumeter and the fader. Can we just postpone this to a later version anyway? :)

**Comment by ywwg** [comment]
can you post before/after screenshots?  I'm not sure what changed.  Also the head mix knob elements are misaligned

**Comment by ferranpujolcamins** [comment]
Before:

captura de pantalla de 2015-08-20 20 47 09
captura de pantalla de 2015-08-20 20 47 15

After:

captura de pantalla de 2015-08-20 20 46 22
captura de pantalla de 2015-08-20 20 46 54


It takes a bit roe of horizontal space but there's an improvement on usability of the buttons and text visibility.


> Also the head mix knob elements are misaligned

I'm not sure what do you mean here.

**Comment by Be-ing** [comment]
Looks good!

I'm also not sure what you mean @ywwg . What is there to align the head mix knob to?

**Comment by ywwg** [comment]
I rebuilt and the problem went away, nevermind.

**Comment by ywwg** [comment]
In the new version the text under the fx knobs has gotten bigger and is interfering with the knobs even more than it already was

**Comment by ferranpujolcamins** [comment]
> In the new version the text under the fx knobs has gotten bigger and is interfering with the knobs even more than it already was

I think this text size is what we want at the end. The good solution for me is to fix [Bug #1395245](https://bugs.launchpad.net/mixxx/+bug/1395245). However this means new code and someone will have to review it. :)

The alternative is to revert the fx knobs text size back to the small size. It's ugly, but it's a fast hack.

Which approach shall I take?

**Comment by ywwg** [comment]
no, it is too late to come up with a design for adding short text to all the effects. I think if we make the effect knobs a little smaller and make the box just a few pixels taller we can go back to the old font size and make sure the text is not touching the knobs

**Comment by ferranpujolcamins** [comment]
Ok, here you have a first approach.

I've also changed the position of the super and d/w knobs. Before, they were on the first fx row, taking a lot of space from it. Now they are vertical and in a column next to the three fx rows, so the effects are now the same size.

**Comment by ywwg** [comment]
still seeing this: 
knobs

**Comment by ferranpujolcamins** [comment]
What about this?

captura de pantalla de 2015-08-21 14 48 06

**Comment by ywwg** [comment]
much better

**Comment by ywwg** [comment]
heh, try shrinking the skin down to minimal width -- bad things start happening.  Change the minimum size to 1024, 700 and I think we're ok

**Comment by ywwg** [comment]
btw here is the selection color issue I mentioned.  This probably happens because the skin is not defining specific values for selection colors and the colors are being picked up from the default theme, which may be different on different computers. Check out how latenight themes the library for guidance.
colors

**Comment by ferranpujolcamins** [comment]
Because how I put the knobs of the minimized effects units, it needs to be 1170x700. This can be really optimized but involves a lot of work and re-thinking, lets leave it like this for 1.12.

**Comment by ywwg** [comment]
Is there any way to get down to 1024?  We've had a lot of complaints about latenight taking up too much space on small screens so if we can save those 50 pixels somehow it would be a big win.

**Comment by ferranpujolcamins** [comment]
Ok, it was not that hard :)

Now let me check this issue with the library colours.

By the way, my priority right now is to push 1.12, but unless you keep pointing me to more skin issues, I'll put my time to other parts of Mixxx. Is there other 1.12 blockers nobody is taking care of?

**Comment by ferranpujolcamins** [comment]
I have no idea about what's happening with your colours. I see on the image that the selection colour is a gradient, but there's no gradient specified on the QTableView section of style.qss. Maybe you have the skin files somehow messed up?

**Comment by ywwg** [comment]
First, that selection color is the unfocused selection color.  As I described, I believe that gradient is part of my system's theme.  And since the skin doesn't define that color, the system theme version shows through.  

Like I said, look at latenight, I even figured out how to style the scrollbar correctly! https://github.com/ferranpujolcamins/mixxx/pull/1

**Comment by ferranpujolcamins** [comment]
I've just made the scroll bars blue :)

**Comment by ywwg** [comment]
cool, if you can just fix the conflicts that github is reporting I'll merge it in

**Comment by ferranpujolcamins** [comment]
Done!

**Comment by ywwg** [comment]
didn't realize this was targetted to master.  manually merged to 1.12

**Comment by ferranpujolcamins** [comment]
Ooops, my fault. Thank you.

2015-08-29 2:26 GMT+02:00 Owen Williams <notifications@github.com>:

**Pull request merged**
