### PR TITLE
Fix debug assertion in AcoustidClient / Fetch multiple recordings from MusicBrainz

### PR DESCRIPTION
**Pull request by uklotzde**
Fix a debug assertion if the track is recognized (or not?), but no MusicBrainz recordings have been found. In this case the "recordings" key/value pair is missing, which previously triggered a debug assertion.

### CODE REVIEW

**Comment by daschuer** [comment]
AMD Build failed:
```
Thee following tests FAILED:
	183 - EngineBufferE2ETest.CueGotoAndStopTest (Failed)
	185 - EngineBufferE2ETest.CueStartPlayTest (Failed)
```
Is this related?

**Comment by daschuer** [comment]
That can't be related to the changes here ...

**Comment by uklotzde** [comment]
We need to consider all recordings from the first result with maximum score, not only the first one.

**Comment by uklotzde** [comment]
A reusable component for managing pending network requests and replies will follow in a separate PR.

**Comment by daschuer** [comment]
This is now conflicting.

**Comment by daschuer** [comment]
Now the list of findings contains duplicates: 
this PR: 
grafik

master: 
grafik

**Comment by uklotzde** [comment]
> Now the list of findings contains duplicates:
> this PR:
> grafik
> 
> master:
> grafik

The deduplication got lost on the way. Fixed.

**Comment by daschuer** [comment]
LGTM, Thank you.

**Pull request merged**
