### PR TITLE
Fix OS X build on Travis by disabling FFmpeg

### PR DESCRIPTION
**Pull request by uklotzde**
A compatibility issue in SoundSourceFFmpeg. No fix available, so let's just disable it.

### CODE REVIEW

**Comment by uklotzde** [comment]
I have also disabled FFmpeg in the RPM Fusion package builds, same issue for F29/Rawhide.

**Comment by Be-ing** [comment]
Can you elaborate what this compatibility issue is?

**Comment by uklotzde** [comment]
Uh, just noticed that it's in the encoder and **not** the decoder as expected. I didn't take into account that we also have an FFmpeg encoder.

Looks like a "AV_" prefixes are missing for some defines.

**Comment by uklotzde** [comment]
Let's see if fixing the identifiers works unconditionally for all supported platforms. But I don't plan to maintain this legacy stuff ;)

**Comment by uklotzde** [comment]
Will be reopened when ready...

**Pull request closed without merging**
