### PR TITLE
Revert "Fixing Tango Crash "

### PR DESCRIPTION
**Pull request by Be-ing**
Reverts mixxxdj/mixxx#1747

Attempting to fix [huge performance regression reported by multiple Windows users](https://mixxx.org/forums/viewtopic.php?f=3&t=12082)

### CODE REVIEW

**Comment by sblaisot** [comment]
I can confirm the problem.

git6746 was OK
git6748 was the first build showing the problem.

I can confirm the appveyor artifact from this PR doesn't have the problem anymore.

**Comment by Be-ing** [comment]
Thank you for testing!

**Comment by sblaisot** [comment]
out of scope but worse noting: Remember lp:1729345 ? (scrolling waveforms showing triangles instead of the scrolling waveform). 
Interrestingly when the interface lag, the scrolling waveform show from time to time.

**Comment by sblaisot** [comment]
does merging this implies that tango will start to crash again ?

**Comment by Be-ing** [comment]
Not necessarily. The crash only happened with Qt 5, which is not supported by Mixxx 2.1, and was only confirmed with Qt 5.2, which is not supported by any Mixxx version! Not one user has reported the problem with Mixxx 2.1 using Qt4. There was no good justification for merging #1747 into the 2.1 branch.

**Pull request merged**
