### PR TITLE
[WIP] Add Gudron skin

### PR DESCRIPTION
**Pull request by Holzhaus**
This adds the [Gudron skin](https://www.mixxx.org/forums/viewtopic.php?f=8&t=8476) that was published in 2016 by @zezic and modifications by forum user "Pensive". This is a very cool skin, and it would be a shame if it gets lost, so this serves as a backup (the original download at `zezic.ru` seems to be down).

I added some formatting fixes, but there is still some stuff that would be nice:

- [x] Colored Hotcue support (currently, skin colors them regardless of of assigned color)
- [ ] FX section support
- [ ] Add option to have minimal sampler version
- [ ] Add support for side-by-side waveform displays

### CODE REVIEW

**Comment by upCASE** [comment]
Hi Holzhaus,

I'm pretty sure that the original author mentioned that he'd get working on this skin again soon in the forum thread. Maybe try to get in touch first before you reinvent the wheel.
Anyway: I'd love to see this skin Mixxx as well. Would be great if it could be scaled down a bit, as it uses much space on my old Vaio...

**Comment by zezic** [comment]
@Holzhaus @upCASE Hello, guys! Actually I'm here and watching. I'm trying to find the source SVG file of Gudron on my HDD to provide it to you, but I've not succeed yet (but it should be there!).
What's about continuation of work on this skin - I'm not sure that this particular skin should be developed further and I'm even not sure that the current skin engine of Mixxx is good enough for what it supposed to do at the moment.
Recently I've worked with libs called GLFW, NanoVG and NanoSVG a bit and I liked their flexibility, maybe I should look at alternative skin engine idea before starting to develop another skin.

**Comment by Holzhaus** [comment]
> I'm trying to find the source SVG file of Gudron on my HDD to provide it to you, but I've not succeed yet (but it should be there!).

Thanks, that'd be cool and enable us to continue working on this skin.

> What's about continuation of work on this skin - I'm not sure that this particular skin should be developed further and I'm even not sure that the current skin engine of Mixxx is good enough for what it supposed to do at the moment.
> Recently I've worked with libs called GLFW, NanoVG and NanoSVG a bit and I liked their flexibility, maybe I should look at alternative skin engine idea before starting to develop another skin.

Well, it's your spare time and you have to decide what you want to do with it. If you want to start development of a better the skin engine, this could potentially benefit Mixxx greatly. That said, I really like this skin and the lack of FX sections and compact samplers are the only things preventing me from using this full-time. 

Sure, there's always room for improvement. But my personal experience I often have big plans that take a lot of time to complete and end up nowhere because I lost interest or lacked free time along the way. So instead of the awesome solution I imagined when I started, I ended up with lots of promising, but unfinished code that goes to waste.

Hence, I now try to use a more incremental approach and split stuff up into smaller subtasks that can be each be tackled one at a time. This also has the benefit of easier code reviews (because the diffs are smaller) and more direct feedback, leading to better end results. But most importantly, users don't have to wait for indefinite amounts of time, as results of my work become usable much sooner, which also keeps me motivated.

However, that's just my personal experience in regards to how I work, and you have to decide what works best for you.

**Comment by Holzhaus** [comment]
@zezic hey, did you find the time to look for the SVG files yet? I really like this skin and would love to see it integrated into Mixxx.

**Comment by zezic** [comment]
Hi, @Holzhaus (and @ronso0) ~~I scanned my whole RAID and I can't find the sources of Gudron. How it was possible to lost them is still a mystery for me. I even checked my email box, documents in social networks and backups of personal blog. Probably, they gone with my old laptop which I gifted to my brother. I think, there is no way to restore them because of multiple HDD rewrites even if they were there.~~

OMG! I just found it by searching for another skin codename which is "Kephyr".
Here is the SVG:
[gudron.svg.zip](https://github.com/mixxxdj/mixxx/files/3876124/gudron.svg.zip)

It should look like this when opened with Inkscape:

gudron-svg

There are several layers, some of them contain boundaries (rectangles) used for exporting.
I've changed the fonts: Felipe -> Roboto, Arial -> Montserrat. So you will need Roboto, Roboto Condensed and Montserrat installed in your system.

Also there is a Kephyr itself:

kephyr-svg

I don't like it much, although here is an SVG:
[kephyr.svg.zip](https://github.com/mixxxdj/mixxx/files/3876164/kephyr.svg.zip)

**Comment by Holzhaus** [comment]
Great! Thank you! Now we have a real possibility that Gudron could be added to Mixxx.

**Comment by daschuer** [comment]
Hey, a daylight skin. That really closes a gap.

**Comment by Holzhaus** [comment]
@ronso0 Do you have interest in working on this Skin? My knowledge of skins is very limited and I'm not a graphics designer, but I'd really like Gudron to be part of Mixxx.

**Comment by ronso0** [comment]
I didn't have a look at how Gudron is built and what effort it takes to overhaul effects etc., but I can imagine to work on this after 2.3 is out.

> Hey, a daylight skin. That really closes a gap.

With the LateNigh redesign I built a pretty solid foundation for theming it, and I plan to work on a daylight theme in the 2.3 beta phase and hopefully finish it for the release.

This is an (completely unpolished) example preview from the redesign PR I made by just tweaking a few color codes:
image

**Comment by ronso0** [comment]
Considering the missing features in Gudron, we need to continue discussing wether we want to stick to releasing full-featured skins only, or if we can agree on releasing yet incomplete skins, too, marked as [Preview] or [WIP] for example.
Pretty much what we discussed [there on Zulip](https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Re-thinking.20Skins.20*.20Specialised.20vs.2E.20generalised/near/164739631)

**Comment by ronso0** [comment]
a few essential things that need to be fixed even for a preview version IMO:
* EQ kill buttons for High/Mid bands with 2 decks
* beatjump controls, spinboxes for beatjump & looping
* taller track overview for all hotcue and position features
* Vinyl controls
* slip mode toggle

Considering this and the sections we have to add later on (Fx, mic/aux), I think we should design Gudron for 1920px screens.

**Comment by ronso0** [comment]
Every now and then I'll post some Gimp sketches with ideas and layout fixes here that we can discuss before actually working on the skin.

This for example is how I'd rearrange deck controls. Seek buttons are static now when the position display size changes. Hotcues are next to Play and Cue.
BPM controls should be consolidated into one column if possible (top to bottom): BPM / rate % / slider / temp. rate change buttons / perm. rate buttons
Then, Key controls can go in between Hotcues and Looping.
image


To have an equally sized QuickEffect knob I reduced the v-size of the EQ knobs a bit, they just need ~270° anyway.
image

**Comment by Holzhaus** [comment]
Nice! Are you planning on making this a SVG-only skin?

**Comment by ronso0** [comment]
> Nice! Are you planning on making this a SVG-only skin?

I had a brief look at the source SVG and I think properly extracting the vectors / icons will be a lot of work.
I think the first step should be to apply some tweaks and then publish it as bitmap skin.

The main issue with the SVG / Inkscape: there doesn't seem to be a suitable workflow via Inkscape extensions to export objects (object groups) to single vector files to use them as button icons for example.
I tried some but either the file is not cropped (just the visible area) and/or some container gradients (shadows) are screwed up. Maybe someone has experience with Illustrator in this regard?
Also Mixxx has issues rendering svg gradients with transparency.

**Comment by Holzhaus** [comment]
I'm not an Inkscape expert, but can't you use clipping? https://design.tutsplus.com/tutorials/quick-tip-what-are-clipping-and-masking-in-inkscape--vector-24947

**Comment by ronso0** [comment]
Thx, but clipping can only cut shapes from objects but it doesn't resize the page.

Unfortunately it's much more complex here:
we have multiple layers with button shapes, texts/icons, in/active highlights, button shadows, and a layer with the object boundaries.
To have compact vector files for every style element we need to pick all relevant objects (or just parts of them) from all visible layers, resize the page to the object boundary, and then export only the selected ojects to a new file with a proper name.There are a loooot of elements and doing this manually would be a pita, for the initial export as well as for revisions later on.

The workflow for exporting sized bitmaps is much easier, though, thus I'd stick to that for the first version and only change what necessarily needs to be changed. Later on we can work out a way to separate the vector sources and simplify the styling by making use of `border-image` and `background-color` etc. I expect that to be as much work as designing the current svg source... in the end maybe we're better off by reusing templates from LateNight for that.

**Comment by Holzhaus** [comment]
> > Nice! Are you planning on making this a SVG-only skin?
> 
> I had a brief look at the source SVG and I think properly extracting the vectors / icons will be a lot of work.
> I think the first step should be to apply some tweaks and then publish it as bitmap skin.
> 
> The main issue with the SVG / Inkscape: there doesn't seem to be a suitable workflow via Inkscape extensions to export objects (object groups) to single vector files to use them as button icons for example.
> I tried some but either the file is not cropped (just the visible area) and/or some container gradients (shadows) are screwed up. Maybe someone has experience with Illustrator in this regard?

@zezic do you have an idea how to do this?

**Comment by zezic** [comment]
> > > Nice! Are you planning on making this a SVG-only skin?
> > 
> > 
> > I had a brief look at the source SVG and I think properly extracting the vectors / icons will be a lot of work.
> > I think the first step should be to apply some tweaks and then publish it as bitmap skin.
> > The main issue with the SVG / Inkscape: there doesn't seem to be a suitable workflow via Inkscape extensions to export objects (object groups) to single vector files to use them as button icons for example.
> > I tried some but either the file is not cropped (just the visible area) and/or some container gradients (shadows) are screwed up. Maybe someone has experience with Illustrator in this regard?
> 
> @zezic do you have an idea how to do this?

What's about deconstructing the SVG - I think, Inkscape will provide the best SVG support possible. And for making the skin 100% vector we can load off some of the details to the QSS side, things like BG gradients, tiny borders, etc. I will look at the state of the branch and let you know what can I do for it.

**Comment by Holzhaus** [comment]
@ronso0 can you share your current progress?

**Comment by ronso0** [comment]
Seems I worked on it in a separate skins folder outside my git and I'm not sure what my changes are based on. Doesn't make much sense to sort it out and open a PR right now as there's nothing really useful to test, and the knob changes aren't implemented, yet.
I'll come back to this when I'm done with some tweaks for LateNight 2.3 and the knob arcs.

**Comment by Holzhaus** [comment]
@ronso0 Are you still planning to work on this? I still think this skin is beautiful, but now that the LateNight skin has been polished so much, I'm unsure if it's worth the additional maintenance burden.

**Comment by ronso0** [comment]
In my mixxx browser session I have a reminding Gudron tab with a screenshot of the mixer view :)
At some point I may come back to this because it's a beautifully designed skin with some refreshing ideas.
When I do I recommend publishing the current state first, extended by basic fx and beatgrid editing support for example. Even for that a lot has to be done. I don't even think about vectorizing the graphics...

And we need to check if everyone is okay with publishing a skin that does not provide the current default beatloop/beatjump UI with spinboxes etc.
https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Re-thinking.20Skins.20*.20Specialised.20vs.2E.20generalised

Right now I'm more motivated to work on UX improvement for 2.3/2.4 rather than going down the skin xml rabbithole.
And I'll be a dad from january on, so I'll focus on the stuff I can get done in time :)

**Comment by ronso0** [comment]
But I think we should keep this draft. I fear if we close it we'll forget about it.

**Comment by Holzhaus** [comment]
> And I'll be a dad from january on

Let us know when it happens, so we can congratulate :tada:

**Comment by ronso0** [comment]
Oooouuuh, also there are some more 'urgent' wishes like
* radio DJ skin
https://mixxx.discourse.group/t/mixxx-for-broadcast-radio/20038/6
https://vb-audio.com/Voicemeeter/VoicemeeterAudioMixer.jpg
* daylight color scheme
* improve touch accessibility

**Comment by Holzhaus** [comment]
> * daylight color scheme

Maybe we can adopt that Kephyr skin that @zezic posted above?

**Comment by Holzhaus** [comment]
I still think that this skin looks stunning, but let's close this unless we can agree to drop another skin in favor of this.

**Pull request closed without merging**
