### PR TITLE
Skins: update preview images for LateNight 64 sampler skins

### PR DESCRIPTION
**Pull request by ywwg**
fixes: https://github.com/mixxxdj/mixxx/issues/11763

### CODE REVIEW

**Comment by ronso0** [comment]
Thanks.
Why 4k images? The previews are 640x360 (1280x720 with 200%) and can't be zoomed. I don't thnk we need that extra 1 MB here.

**Comment by ronso0** [comment]
Btw those need to be in **LateNight (64 Samplers)**

**Review by ronso0 — CHANGES_REQUESTED** [review]
Those need to be in **LateNight (64 Samplers)** ; )

**Comment by ywwg** [comment]
I can shrink them more if you want

**Comment by ronso0** [comment]
> I can shrink them more if you want

Yes, please use 1920x1080, it's just the ratio (16:9) matches that of the preview label
The images of this PR are all 1920:1200, therefore the preferences label won't use the available width
https://github.com/mixxxdj/mixxx/blob/0bc192caab0c20f76cbab2a482b25c6cbb4eedc1/src/preferences/dialog/dlgprefinterface.cpp#L355-L358

**Comment by ywwg** [comment]
ok yeah can do.

**Comment by ronso0** [comment]
Yup, looking good now. Thank you!

**Comment by ronso0** [comment]
oh, we could have squashed into one. Hmm next time..

**Pull request merged**
