### PR TITLE
[WIP] Deere mixer redesign

### PR DESCRIPTION
**Pull request by Be-ing**
I find the 3 1 2 4 deck layout confusing with my Allen & Heath Xone K2. This new option changes the order that the mixer columns and the stacked waveforms are laid out.

### CODE REVIEW

**Review by daschuer — COMMENTED** [review]
Isn't this a mapping issue? 
I think all skins are effected somehow. And it is a property of the controller setup how they are arranged on the table.

**Comment by Be-ing** [comment]
Yes, this issue affects all 4 deck skins. I thought about adding the option to all skins in one PR but then I started working on other areas of Deere to get it to work better with 4 decks and 4 effect units.

**Comment by Be-ing** [comment]
For 4 deck all-in-one style controllers, which is most 4 deck controllers, I think the 3 1 2 4 layout is the only one that makes sense because the left side of the controller toggles between decks 1 & 3 and the right side toggles between decks 2 & 4. But the Xone K2 is unusual because it has dedicated buttons for every deck and does not require toggling between decks, so either 3 1 2 4 or 1 2 3 4 layouts could work with the controller.

In #1538, I added options for both layouts depending on the MIDI channel the controller is set to. I find 3 1 2 4 quite confusing, especially in the context of using 4 effect units my other Xone K2. With the 4 effect unit mapping, the bottom grid of buttons controls the effect unit routing buttons. I can look down a column to see which decks an effect unit is assigned to or across a row to see which effect units are applying to a deck. With the 4 deck controller laid out 3 1 2 4 that gets quite confusing.

**Comment by Be-ing** [comment]
I rearrange the 4 deck mixer to vertically duplicate the 2 deck layout. This way, each mixer section is adjacent to the deck it controls like Tango, which removes the potential for confusion between which mixer section manipulates which deck. The 1 2 3 4 / 3 1 2 4 toggle option now only applies to the waveforms in parallel waveform mode.

I also moved the effect unit assignment buttons to the mixer where there is more space to allow all 4 buttons to be laid out horizontally. This is more intuitive with a Xone K2 used for 4 effect units.

There is still polishing to do to make the mixer sections more clearly distinct, add some padding, and align the mixer sections with the decks when the crossfader is showing. Here is a current screenshot:
deere-wip

**Comment by daschuer** [comment]
I think there is a use case for the original Deere Mixxx region. It matches all four deck controllers and your double Xone K2 mapping in 3124 mode as well. I see how the proposed design is less confusing looking at the GUI, but looking at the controller, it it can be more confusing. Also the waveform assignment was not too confusing to me. 
So I would prefer to stick with the original version to offer both alternatives via Tango and Deere. 
We may consider to make it an option though, only switching the waveforms does IMHO not make much sense to me. The waveform alignment should always match the mixer alignment.

**Comment by Be-ing** [comment]
With the old mixer layout, sure I could get my K2 to match the layout of the mixer, but both the 3-1-2-4 and 1-2-3-4 layouts were confusing. Having the decks laid out 3-1-2-4 on the controller made the effect unit routing grid on my other K2 really confusing. Rearranging the mixer in a 1-2-3-4 layout made it confusing which mixer column manipulated which deck. Both problems are solved by putting the mixer controls adjacent to the deck they manipulate. The old layout required a bunch of ugly hacks so I will not implement an option to revert to it in Deere. Users who prefer that layout can still use LateNight.

It is still annoying to have the decks split into two rows, but solving that will require a completely new skin design like [djay's vertical 4 deck mode](http://media.idownloadblog.com/wp-content/uploads/2014/12/Djay-Pro-for-Mac-Four-Deck-Vertical.jpg).

**Comment by daschuer** [comment]
It seems I do not understand you issue.
The 3124 mapping should be the preferred setup for your K2. If the effect layout is confusing in this cas, I think it is an issue of the mapping not the skin. Do we have a picture that visualises the issue?

**Comment by ronso0** [comment]
I appreciate you adopted the 4-channel mixer layout from Tango.
Back then, I started Tango with 2 decks, and the present 4-channel mixer design there was admittedly just a consequence of my laziness to completely redesign the mixer for 4 decks. Nevertheless, IMO it has proven to be useful when using Mixxx without a controller, or with a 2-deck controller which provides a second layer for decks 3/4. Which is also the intended use case for stacking the waveforms
in a 1-2-3-4 order: facilitate the correlation between waveforms and respective decks. I see the difficulty this creates for a default 4-column mixer, though. I thougt this is why we discussed to provide a switch (for all 4-deck skins) to choose the order of stacked waveforms.
For any controller with a mixer section the GUI mixer is obsolete (but I watch users having it visible anyway), except for making sure the physical knobs match their on-screen counterpart. 

If your primary motivation for this PR is the inconvenient FX mapping for the K2 (and similiar devices), we should provide a mapping for the case you describe. I don't like the idea to drop the previous industry-standard 4-channel mixer layout for our default skin, without an option to go back to what most people working with physical 4-channel mixers are used to.
IMO directing users to LateNight is not an option either since it **a)** is completely different aesthetically and **b)** requires at least a 1280px screen to be convenient, and Deere still should work on 1024px screens.
Btw, when switching to this Deere variant @1366px, I get a warning the skin would be too big.

**Comment by ronso0** [comment]
It would be helpful to have an option to break out each column from the centralized mixer and attach it to attach it to the respective deck.
Otoh I see the effort this would cost for Deere alone, and -being consequent- adding the reverse option to Tango.

**Comment by ronso0** [comment]
Btw effect slots are completely broken.

**Comment by Be-ing** [comment]
The 4 effect unit mapping for the Xone K2 has each column controlling an effect unit. The buttons in the grid on the bottom of the K2 assign the effect unit to each deck. By putting 4 columns next to each other, the buttons become a conventional signal routing matrix. This allows me to look horizontally across the grid to see which effect unit is assigned to which deck. I can easily see both which decks an effect unit is assigned to and which effect units are applying to a deck depending on which way I look at the matrix. However, if the layout of my other K2 controlling 4 decks is out of order, controlling the effect unit routing buttons gets really confusing. I suppose it would be possible to rearrange the routing matrix in a 3-1-2-4 order going down the column, but this would be really unconventional and confusing when looking at the routing buttons on screen.

**Comment by Be-ing** [comment]
>  For any controller with a mixer section the GUI mixer is obsolete (but I watch users having it visible anyway), except for making sure the physical knobs match their on-screen counterpart.

It is not quite accurate to call the on screen mixer obsolete. Many controllers do not provide level meters, gain knobs, and/or filter knobs. Also, the Xone K2's knobs do not have center detents, so the on screen mixer is helpful for seeing when the knobs are at exact center. Personally I like being able to look at either my screen or my controller for feedback about the positions of mixer controls. Throughout a set I look at both at different times.

**Comment by Be-ing** [comment]
> I don't like the idea to drop the previous industry-standard 4-channel mixer layout for our default skin, without an option to go back to what most people working with physical 4-channel mixers are used to.

The old layout is not an industry standard. Traktor's layout is similar to this PR:
image

djay's 4 deck layout is entirely different:
image

I think Serato doesn't even let the user see the mixer on screen.

**Comment by Be-ing** [comment]
> Btw effect slots are completely broken.

What do you mean by "effect slots"? All the effects controls work fine for me.

> Btw, when switching to this Deere variant @1366px, I get a warning the skin would be too big.

Hmm, interesting. Thank you for letting me know. I'll test this on my old laptop.

**Comment by Be-ing** [comment]
The crossfader creates a design challenge with this layout. The Xone K2 has no crossfader, so it is not a problem for me personally, but most controllers do have a crossfader. 

deere-crossfader

Putting the crossfader in the mixer creates a misalignment between the mixer controls and the decks they control. The only way to solve this with the crossfader in the mixer is to not let the decks expand vertically when the crossfader is shown, but that would create a lot of unused horizontal space. djay does that in the screenshot I [posted above](https://github.com/mixxxdj/mixxx/pull/1548#issuecomment-373349797), but I do not like how much space that wastes. On the other hand I don't really like Tango's approach of moving the crossfader outside of the mixer... does anyone have other ideas?

**Comment by Be-ing** [comment]
I tried moving the crossfader below the mixer like Traktor and djay. Aesthetically it works well, but it does not leave much room for the library with 4 decks + 4 effect units:
deere-moved-crossfader
Unfortunately it is not currently possible to have crossfader assignment buttons on each side of the crossfader like Traktor. The `orientation` Control for decks is a 3 state switch and it does not seem there is a way for WPushButton to toggle between state 1 (unassigned from crossfader) and state 2 (right side of crossfader) without the button also having a state 0 (left side of crossfader). So a button could not toggle a deck between the right side of the crossfader and unassigned from the crossfader. :/

I think 4 decks + 4 effect units + crossfader is an edge case. The only use case I can think of for that would be using a dedicated effects controller like a Xone K2 or MIDI Fighter Twister together with a 4 deck all-in-one controller with a crossfader. If using a dedicated effects controller with an external hardware mixer, there is no point showing the crossfader on screen. So I think this is good enough although it is not perfect.

**Comment by daschuer** [comment]
What will be the result of your work? I think we should keep the Deere with side by side sliders for 2.1 as default.

**Comment by Be-ing** [comment]
This is already close to the end result. I just need to add a bit of padding in the mixer, check that it looks nice in all configurations, and change the colors of the knobs + faders.

I do not understand why it is a problem to have this as the default skin. In Traktor, this is the only mixer layout available. I have not heard or read anyone complain about Traktor's mixer layout.

**Comment by ronso0** [comment]
> The old layout is not an industry standard.

Sorry for the misunderstanding, I was referring to 4-channnel mixers. Basically I don't look at other DJ software very often, except when I meet some friends of mine who play with Traktor and control vinyl.

My objection is just that I feel you're rushing this radical, irreversible change (as long as there's no related skin option) of our default skin because of a single controller, and that we should consider (aka wait for) the opinions of a few more devs.
AFAICT making the new layout optional would only require to reuse the previous mixer templates. 

> crossfader placement
For Deere I prefer the crossfader inside the mixer. That slight offset between decks and their mixer channels isn't really disturbing IMO as long as there's no strong border between upper and lower mixer channel. The crossfader in it's own row with all that space on the sides feels(!) like a waste of space, I'd rather see the waveforms expand.

> hide effect unit routing buttons when effect units are hidden
I still think this is not a good idea (also to hide FX3/4 switches when those FX units are hidden): the intention to have those switches near the decks or in the mixer is to have all aspects affecting a deck in one place and all information handy, which is perfect. Hiding those switches while having i.e. a manipulated Moog filter active in a hidden FX unit would leave users clueless about what's going on. This contradicts the initial intention IMO.

**Comment by ronso0** [comment]
Here the FX units look like this:
deere-1234-fx-units

I tried prebuilt master, self-compiled master & self-compiled 2.1...hm

**Comment by daschuer** [comment]
I am still pro the parallel layout as Deere default, because all hardware mixers are arranged like that.

**Comment by Be-ing** [comment]
I see no need to limit software to mimic hardware designs as long as it is still intuitive to use with hardware. 4 deck mixers are laid out that way because they are physically separate devices from turntables and CDJs. That is not the case with a software's GUI.

> we should consider (aka wait for) the opinions of a few more devs.

I would like to hear from someone who has a conventional 4 deck all-in-one controller. @uklotzde, how does this design feel with your Denon MC6000 Mk2? I have briefly tested the 3-1-2-4 deck layout with my Xone K2 and I think the new mixer design in this PR works as well as the old one for that use case.

>  AFAICT making the new layout optional would only require to reuse the previous mixer templates.

IMO the cost of keeping the old design as an option is too high. The old design required confusing and complicated XML templates that were difficult to maintain. I am glad to be rid of that ugly code with the new design.

**Comment by daschuer** [comment]
> I suppose it would be possible to rearrange the routing matrix in a 3-1-2-4 order going down the column, but this would be really unconventional and confusing when looking at the routing buttons on screen. The problem here is not the mapping, it is the skin design.

IMHO this is a good solution. The 3-1-2-4 order seems to be the most common order. 
The routing buttons on screen are in 
```
1 2 
3 4
```
in the same order as the decks. 
You have to do the same brain gym to match the decks with the sliders. Think of 
```
  1 2
3     4
```
and it works.

**Comment by Be-ing** [comment]
I have changed the routing buttons on screen to 1-2-3-4 in one horizontal row. This works quite well with my double Xone K2 setup. I can press a row of buttons in the matrix and see buttons on screen light up in a row in the same order.

The root of this design problem is that the decks are laid out in a 2 x 2 grid instead of one row or column of 4. I don't want to replicate that with the effect unit routing buttons.

**Comment by Be-ing** [comment]
@ronso0 on further thought I think it would be a good idea to have a separate option to toggle the effect unit routing buttons. Most cheap controllers do not have buttons for these so most users will leave them set to the defaults (effect unit 1 to deck 1 and effect unit 2 to deck 2). In that case it makes sense to hide the routing buttons but keep the effects showing.

Regarding the squished EffectSelectors, I do not know what is going on. I tested this skin again at 100% on my new laptop and did not see anything like your screenshot. I'll test it on my old laptop.

**Comment by Be-ing** [comment]
@ferranpujolcamins could you test this with your double Xone K2 setup?

**Comment by daschuer** [comment]
> I have changed the routing buttons on screen to 1-2-3-4 in one horizontal row. This works quite well with my double Xone K2 setup. I can press a row of buttons in the matrix and see buttons on screen light up in a row in the same order.

Why that? If you go back to the layout of all other controllers you would have 3-1-2-4 and everything is in line. It really does not matter which number the decks / faders and effect units have as long as they are aligned in the same way. 

> The root of this design problem is that the decks are laid out in a 2 x 2 grid instead of one row or column of 4. I don't want to replicate that with the effect unit routing buttons.

The industrial standard of a four deck controller is 3-1-2-4. It does not make sense to change anything in Mixxx just because a single controller that has an optional mapping for 1-2-3-4. 

See:
https://www.traktorbible.com/freaks/mappingview.aspx?id=960 

I might not have understood your issue, so can you do marks your effect controls in the picture? 

this is also cool:
https://www.youtube.com/watch?v=yTFzKm2WWvQ

**Comment by Be-ing** [comment]
My [Xone K2 mapping](https://mixxx.org/wiki/doku.php/allen_heath_xone_k2) is documented on the wiki.

**Comment by Be-ing** [comment]
> It really does not matter which number the decks / faders and effect units have as long as they are aligned in the same way.

That is true until you consider the effect unit routing buttons in the skin. Putting those in an order other than 1-2-3-4 would be odd.

**Comment by daschuer** [comment]
> My Xone K2 mapping is documented on the wiki.

Sorry, I have already looked ontoHow do I see how the buttons are mapped?

**Comment by Be-ing** [comment]
On one controller I have the decks laid out one per column in a 1-2-3-4 order. On the other controller I have the effect units laid out one per column in a 1-2-3-4 order. On the 4 effect unit layout, the buttons at the bottom route that effect unit to decks 1-2-3-4 going down the column. With the 4 columns of effect units next to each other, this creates a routing matrix so I can see what effect units are assigned to a deck by looking across the rows instead of down the columns.

**Comment by daschuer** [comment]
Ah, thank you, I understand. But that does not rectify to remove the parallel 3-1-2-4 mixer here.
I have read that the K2 Controller can be switched to 3-1-2-4 mode. Everything should work in the same way if the effect unit is moved to the same order.  If not, this is a mapping issue.

The only issue is the effect making row introduced here. It does not match anything.
If you wish a mapping hid like in the hardware, it should follow the same rule. 
The current 1-2-3-4 mapping is a source of confusion for example of one used a standard four dech controller, or two two deck controllers Wich are 3-1-2-4.

**Comment by Be-ing** [comment]
> I have read that the K2 Controller can be switched to 3-1-2-4 mode. Everything should work in the same way if the effect unit is moved to the same order. If not, this is a mapping issue.

If the effect units are also moved to 3-1-2-4 and the routing buttons are changed to 3-1-2-4 going down the column that would preserve the matrix relationships. But I think it would be weird to look down the columns of the routing buttons then look back at the arrangement of decks on screen. Also, arranging the routing buttons on screen 3-1-2-4 would be weird.

Even without the effects mapping, I find the 3-1-2-4 deck layout odd with the old mixer layout. 4 deck all-in-one controllers have some global controls in the middle like 3-1 [master gain] 2-4. I imagine that helps keep it clear which column is which on the controller. But without that it gets quite confusing to think which controller column corresponds to which deck on screen.

What is nice about associating the mixer controls with the decks instead of the old mixer layout is that it works both for 1-2-3-4 and 3-1-2-4 controller layouts.

**Comment by Be-ing** [comment]
4 deck hardware mixers do not have to deal with these design challenges because when 4 CDJs and/or turntables are used, 2 are placed side-by-side on each side of the mixer:

```
[deck 1] [deck 2]    | 1 2 3 4 |    [deck 3] [deck 4]
```
This way there is no potential for confusion regarding which mixer column applies to which deck. We may consider a skin design like this in the future. It might be able to work by making the decks taller than they are wide.

By contrast, with LateNight and current Deere (without this PR), we have:

```
[deck 1] | 1 2 3 4 |    [deck 3]
[deck 3] |         |    [deck 4]
```
This scrambles the relationship between decks and mixer columns.

**Comment by daschuer** [comment]
> 4 deck hardware mixers do not have to deal with these design challenges because when 4 CDJs and/or turntables are used, 2 are placed side-by-side on each side of the mixer

Right, but some do it anyway: Rane Sixty-Four
And almost all 4 Decks Midi controllers.

**Comment by ronso0** [comment]
For me it feels like there are a few issues mixed up in this discussion, and this PR doesn't really fix them properly.
If the reason to attach mixer channels to their respective deck and to change the waveform order, is to make it match a physical 4-turntable/cdj or full 4-deck controller setup, wouldn't it be consequent IMO to rearrange the decks as well. All done with one single `3124`/`1234` option. The layout would look like this:
```
[wave   1                  ]
[wave   2                  ]
[wave   3                  ]
[wave   4                  ]
[deck 1]    mixer   [deck 3]
[deck 2] 1  2  3  4 [deck 4]
[    FX 1    ] [   FX 3    ]
[    FX 2    ] [   FX 4    ]
```
This way -IMO- the GUI looks coherent, the horizontal FX button row makes sense, and we can keep the current 4-channel mixer. Decks can be loaded as Singletons and be arranged according to `1234` or `3124` layout choice.
We'd need to adapt the highlight of the crossfader buttons, but that's no big deal.

**Comment by daschuer** [comment]
This one IMHO is too controversy to slip into 2.1
Which part is the bug, that has to be fixed to the K2 mapping?
Can we do this for 2.1 and shift the rest?

**Comment by Be-ing** [comment]
At least we have one skin (Tango) in 2.1 for the double Xone K2 mapping.

**Comment by Be-ing** [comment]
If this won't be merged for 2.1, I am not going to continue working on it further. If someone else wants to, you are welcome to. This was only intended as a quick change to make the double Xone K2 setup usable with Deere for 2.1. As stated before, it doesn't really solve the root problem. Only a skin with a 4 x 1 deck layout will do that. #1549 is a good start on that with the decks oriented horizontally. I will work on another skin with the decks oriented vertically like the screenshots of djay above.

**Pull request closed without merging**
