### PR TITLE
LV2 packaging fixes

### PR DESCRIPTION
**Pull request by Be-ing**
see commit messages

### CODE REVIEW

**Comment by Be-ing** [comment]
@daschuer could you take a look at this?

**Comment by Be-ing** [comment]
@daschuer ready for merge?

**Comment by daschuer** [comment]
LGTM, and works good. 
With this being merged, we can IMHO merge the LV2 branch to master.

**Comment by Be-ing** [comment]
Thank you for review. We have a [segfault](https://bugs.launchpad.net/mixxx/+bug/1773097) to fix before we can merge the LV2 branch to master.

**Comment by daschuer** [comment]
Ok, Ubuntu Travis build seems to fail unrelated. Mac Os fails because of missing liliv. So it should be save for merging.

**Comment by Be-ing** [comment]
We also need to finish #1674 before merging the LV2 branch.

**Pull request merged**
