### PR TITLE
Focus library directly

### PR DESCRIPTION
**Pull request by ronso0**
**1** Implements an old ToDo in librarycontrol:
focus library directly, without the indirection via sidebar, and without having to assume the library is next/after the sidebar,

**2** Adds `[Library], focus_widget` control which allows mappings with more fine-grained library control.
For example Trax encoder turn or press can now trigger specific actions _per context_.

The control holds the internal number of the current lib focus widget:
``` c++
enum class FocusWidget {
    NONE,
    SEARCHBAR,
    SIDEBAR,
    LIBRARY
};
```
Internally it's updated by `[widget]FocusChange([widget] | NONE)` signal emitted by each widget's `focusInEvent` / `focusOutEvent`.
Valid external updates (from scripts) are 1...n only, verified by each widget's `hasFocus()` functions.

**ToDo**
- [ ] remove skin demo

### CODE REVIEW

**Comment by uklotzde** [comment]
This would allow to map dedicated navigation buttons found on some controllers.

**Comment by ronso0** [comment]
I don't understand the concern. Future GUI designs will still use `[group],contrlkey` right? So there'll be ways to make use of those COs.

**Comment by ronso0** [comment]
> There is no guarantee there will be a sidebar in future designs, or if it exists, that it would always be showing.

Indeed. But sure there'll be some kind of feature bar or alike, like in https://github.com/mixxxdj/mixxx/tree/jmigual-library-redesign.

**Comment by Swiftb0y** [comment]
> I'm not sure this is a great idea. There is no guarantee that future GUI designs will have all of these widgets which could break controller mappings.

I disagree. I think this is a very useful addition for lots of mappings that were made for serato. If we for some reason don't have a sidebar (or something comparable) we can just ignore the CO. The mapped button on the hardware does become useless, but it kinda was so already at the beginning when there was no CO.

Rejecting this PR for a hypothetical in the far future leads to stagnation of progress just as much as bikeshedding. We just need to agree/document that we can drop these COs in the future again otherwise this will lead to lots of bikeshedding too.

**Comment by Be-ing** [comment]
> The mapped button on the hardware does become useless, but it kinda was so already at the beginning when there was no CO.

That's a good point. It's not that big of a deal if those buttons stop working. In the worst case scenario the user can use their mouse anyway.

**Comment by Be-ing** [comment]
> I think this is a very useful addition for lots of mappings that were made for serato.

Can you elaborate? Which specific controllers would this be useful for? It is already confusing how many different ControlObjects there are for navigating the library. What is the benefit of these new ones? Why should they be used instead of the old ones? Should the old ones ever be used?

>  allow special library behaviour with controllers that have two library control sections like the S4 Mk3.

I don't understand. What does this have to do with the S4 Mk3?

**Comment by ronso0** [comment]
> It is already confusing how many different ControlObjects there are for navigating the library

What is confusing you?
`[Library],Move...` = arrow keys
`[Library],MoveFocus..` = Tab key
`[Library],GoToItem` = a bit like Return

The `[Playlist]` controls can be used on controllers that have more a Trax knob, or mappings that internally track if you're navigating the sidebar or the table.

The Reloop Terminal Mix series for example has 4 buttons above the Trax push encoder:
**View**, **Crates**, Back & Prep
The NI S4 Mk3 also has 4 similiar buttons. Other (Serato) controllers have a View and a Prep button. With the new controls those buttons could now act exactly like're labeled.

As I mentioned a few times already: consider this PR a first step to allow more fine-grained library control.
None of those controls necessarily needs to be used in official mappings, but adds more flexibility for custom mappings.
For example if you only use playlists when performing and thus don't need to access the search bar from the controller, the **View** button could switch between sidebar and tracks table.

Next step I'm working on: read-only controls for the focus state `[Library],XyzHasFocus` where Xyz = Libary, Searchbar or Sidebar. With those, pressing a Trax encoder could trigger actions _per context_, especially with controllers that have **two** push encoders, thus no need to sacrifice another button to implement `MoveFocus` controls
* in the searchbar: go to library, longpress: clear search
* in the sidebar: go to library, longpress: go to searchbar
* in the table: load to deck N, longpress: go to searchbar

I hope that finally clarifies my intention and the value of the new controls.

**Comment by Be-ing** [comment]
> more flexibility for custom mappings

Again, I am skeptical it is a good idea to make mappings responsible for this. If there are different use cases for the same controller designs, I think those should be handled by preferences in Mixxx, not offloaded to users to edit their mappings if they don't like how it works.

**Comment by ronso0** [comment]
made some stupid mistakes I need to iron out.

**Comment by Be-ing** [comment]
> For example if you only use playlists when performing and thus don't need to access the search bar from the controller, the View button could switch between sidebar and tracks table.

Why not make a preference option to skip the search bar with MoveHorizontal?

I'm really skeptical that introducing a third way to map library navigation or leaking implementation details of the library to controller mappings are good ideas. What exactly is the problem this PR solves? Is it unfixable by changing the behavior of the existing controls?

> With the new controls those buttons could now act exactly like're labeled.

The View button on the S4 Mk3 is designed to maximize the library. I don't understand what that has to do with this PR.

**Comment by Be-ing** [comment]
It seems there are a few common patterns for library navigation on controllers:

1. A push encoder (Numark Mixtrack Platinum FX3, Allen & Heath Xone K2)
2. A push encoder plus 2 buttons (Pioneer DDJ-SX3, DDJ-1000)
3. A push encoder plus 4 buttons (Denon MC7000, NI Kontrol S4 Mk3, Reloop Terminal Mix)

I think there should be exactly one recommended way to map these common patterns. Currently I cannot figure out what that is nor do I understand how this PR helps.

**Comment by Be-ing** [comment]
> I find it frustrating that after typing in the library search bar, scrolling with [Library], MoveVertical does not scroll through the search results. Instead it scrolls through the history of search queries. Does anyone else find this cumbersome?

What does this have to do with this PR?

> The reason you ran into this issue:
Instead of mapping encoder push to [Libary],GoToItem

That is unrelated. That has no impact on the behavior of `[Library], MoveVertical` after typing in the search box.

If the reason for this PR is to move focus from the search bar after typing in it, this branch doesn't do anything to change that.

**Comment by Be-ing** [comment]
If the issue you are trying to address is that `[ChannelX], LoadSelectedTrack` does not behave identically to `[Library], GoToItem` because there is no way to specify a deck to load to with `[Library], GoToItem`, then let's address that. I don't get how this PR is a solution to that.

**Review by daschuer — CHANGES_REQUESTED** [review]
Is there a need for independent set and a get variables? You can set and get the same variable. 

So I think it should be: 
[Library], library_focus
[Library], sidebar_focus
[Library], searchbar_focus

For my understanding the term library refers to the entire lower half of the Mixxx window.
Internally it is LibraryView which is not really better. It is the view of the selected feature, in most cases a table of tracks.  

alternatives:
[Library],pane_focus
[Library],right_view_focus
[Library],table_focus (not always a table, but OK)

**Review by Be-ing — DISMISSED** [review]
This seems to be a complicated solution in search of a problem. Merging this would make an already confusing situation for controller mapping developers even more confusing. I am not in favor of merging this without a clear explanation of what this enables that was not possible before and why that is beneficial.

**Comment by ronso0** [comment]
> This seems to be a complicated solution in search of a problem

Nope. I created these controls because see the potential for mappings.

> without a clear explanation of what this enables that was not possible before and why that is beneficial.

@Be-ing The fact that after neither my examples on Zulip nor those I posted here help you imagine how these controls allow interesting mappings and workflows, you already being confused by the current controls set, arguing against adding these controls with some hypothetical, incompatible future GUI design (which implies we'd do a really bad job if we fail to migrate current library controls), fear of "increased confusion" (implies we're unable to properly document new controls)... in turn leaves _me_ kinda confused & disappointed, but most importantly discourages me from arguing with you any further about this.

**Comment by ronso0** [comment]
Looking forward on some comments on the code.
1st post updated with a brief description.

**Comment by Be-ing** [comment]
As far as I can tell this was started in a misguided attempt to solve an issue that I ran into (despite my lack of endorsement for the idea from the beginning), but it doesn't do anything about that issue... so, what is the motivation for this? Is this something *you* want for your own controller mapping? If not, what is the purpose?

**Comment by Be-ing** [comment]
>  Though the S4 Mk3 could benefit, sure.

How? Do you mean this:

> You were asking for simplicity so I was proposing to do all that with just the encoder turn + push only.
Then you also wouldn't have to the Star and Playlist buttons to MoveFocus... but do something different?
Maybe Star jumps to the search bar, and Playlist switches between sidebar and tracks table?

I don't consider that a benefit. That would replace two buttons which already work fine with two other buttons which are more complicated. What is a button that switches between sidebar and tracks table supposed to do when the search bar is focused?

**Comment by Be-ing** [comment]
> Now we have relative controls equal to Tab / Shift+Tab.
The new controls are absolute get/set controls, one for each of the current library widgets.

Yes, I understand that. But that does not explain *why* the new absolute controls are helpful. Should mapping developers use the relative or absolute controls? Is the answer different for different controls? If so, how should that be decided?

**Comment by Be-ing** [comment]
Could there be a way to implement what you want in C++, for example with a generic `[Library], encoderPress` Control (the name is just an example), rather than offloading that complexity to controller scripts? Would that be generalizable to other controllers?

**Comment by ronso0** [comment]
Sure we can have a static C++ implementation of _my_ preferred workflow, and if that changes I simply recompile? Or do you think of cramming the configuration into the preferences? _That_ sounds complex...

The whole point is to have the flexibility in js.

**Comment by Holzhaus** [comment]
> Update: set ControlPushbuttons `[Library], library_set_focus` `[Library], sidebar_set_focus` `[Library], searchbar_set_focus`
> 
> get COs, read-only, bound to focusEvents so they work with mouse and keyboard focus change, too. `[Library], library_has_focus` `[Library], sidebar_has_focus` `[Library], searchbar_has_focus`
> 
> This can be tested without controllers with the demo buttons in the lateNight top row.

Can we reduce the number of new COs? If the goal is to have flexibility in JS, we can simply use a single `[Library],focus` CO where 0 = unknown, 1 = library, 2 = sidebar, 3 = searchbar. Since those are only numbers, we can easily add more, and we can simply rename the documentation for 2 and 3 to left pane/right pane if we use a 2-pane design for the new library.

**Comment by Holzhaus** [comment]
> Excellent idea, thanks!
> So, one control for getting and setting the focus?

Exactly.

**Comment by ronso0** [comment]
FWIW QML has nothing to do with QWidget, but the QML docu I read so far uses examples like "MySliderWidget", so I think it doesn't make any difference for users how we name this controls.

**Comment by ronso0** [comment]
@Be-ing I renamed the CO and the internal control.
If this get's a LGTM I have to remove the skin demo, then we can merge.

**Review by daschuer — CHANGES_REQUESTED** [review]
Thank you for you efforts. I have left some comments.

**Review by Be-ing — APPROVED** [review]
waiting for @daschuer's approval

**Comment by ronso0** [comment]
@daschuer Anything left to do?

**Review by daschuer — APPROVED** [review]
Works good, thank you.

**Comment by ronso0** [comment]
Thanks, all done.

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
