### PR TITLE
LateNight: add toggles to show loop and beatjump controls

### PR DESCRIPTION
**Pull request by Russe**
Add tooltip strings for loop controls and beatjump controls toggles.
Add toggles toLateNight skin settings to toggle visibility of loop controls and beatjump controls.
Adapt layout of skin settings to avoid hiding items when mixxx window has minimum size.

### CODE REVIEW

**Comment by ronso0** [comment]
Could you please explain your motivation to add this control?

**Comment by Russe** [comment]
As I never used the loop controls I wanted to have an UI with only needed elements.

- clear UI
- only buttons for my need
- avoid pushing wrong buttons (problem with loops is here that I could create markers at the track which can not be removed any more, only moved before start or after end of track)

**Comment by ronso0** [comment]
I see your use case.
Though, I'm afraid that if we merge this as is, next week there'll be someone adding a toggle for the beatjump controls ; )
So I suggest to either use the `[ ] Loop / Jump Controls` toggle of the compact decks for the full decks, too.
Or add another separate toggle for the beatjump controls.

Either way, if you open the LateNight skin settings menu in plain `main` branch and switch between mini, compact & full decks you'll notice that the settings sections are static (i.e. not resizing). So the spacers need to be adjusted. Also, if you resize the Mixxx window to the smallest size LateNight allows the `DECKS   2 / 4` toggle at the top is squeezed and not readable anymore.
Fixing the sections' margin to allow both the smallest size as well as expanding as it does currently, that is a bit more work. If you agree to add the beatjump toggle I'll take care of the spacers in a follow-up (I'm a bit picky with LateNight changes since I made the redesign).

**Comment by Russe** [comment]
Thanks for your explanation.
I will have a look into this at weekend, I'm pretty sure I can adapt the layout with spacers and so on, as well an additional toggle for beatjump controls at full deck. In my opinion we should provide separate toggles for loop and beatjump controls at full deck settings.

**Comment by ronso0** [comment]
:+1:

**Comment by Russe** [comment]
Today I had time to test this PR on other systems.

Added additional toggle for beatjump controls.
Adapted spacers that settings sections are static when switching between mini, compact & full decks.
Installation files of this PR has been tested on Ubuntu and Windows 10: OK
Tested with PaleMoon and Classic.

**Comment by ronso0** [comment]
You don't need to test such changes on other systems since you didn't change the c++ base (except tooltips) and you didn't add any potentially problematic widgets like WidgetStacks.

Tbh I'm not happy with how dense the menu is now on screens that have sufficient vertical space (see old / new screenshot below)
I'll try to make the spacers and separators auto-expand and send you a commit.

**Comment by Russe** [comment]
> Tbh I'm not happy with how dense the menu is now on screens that have sufficient vertical space (see old / new screenshot below) I'll try to make the spacers and separators auto-expand and send you a commit.

OK, I can add the/some spacers again and check that there's no overlapping or clipping on small screens. I can do that next weekend I guess.

**Comment by Russe** [comment]
Sorry for the delay, my development system was broken.
I added the spacers and some margins again, now settings are not so densed anymore.
Everything is still visible at minimum window size.

**Comment by ronso0** [comment]
Don't worry, this is no pressing issue : )
I'll take a look in the next days.

Besides: I totally forgot that there was WScrollable added ast year #3890
That still has a few issues but we should keep it in mind for future additional settings.

**Comment by ronso0** [comment]
I think this is okay to merge, though I'm not happy with the dense skin settings menu.
Using auto-expand categories and separators will complicate the layout too much. Insted, I'll try to wrap it in a WScrollable and restore the previous layout spacing. This will happen in a separate PR.

Before we merge this, could you please squash the skin commits so we have one tooltip commit and one skin commit?

**Comment by ronso0** [comment]
ping @Russe 
> Before we merge this, could you please squash the skin commits so we have one tooltip commit and one skin commit?

**Comment by Russe** [comment]
Thanks for ping, got lost in some other stuff :-)

**Comment by ronso0** [comment]
Thanks for this addition!

**Comment by ronso0** [comment]
ToDo
* Beatjump Controls > Beatjump/Loopmove Controls
* in compact skin settings: Beatjump Controls > Beatjump Size
* rework skin settings spacers/separators to make menu expand when window is taller than minimal height
* alternative: wrap skin settings with WScrollable

**Pull request merged**
