### PR TITLE
GitHub Actions: Fix pre-commit-PR job and improve workflow

### PR DESCRIPTION
**Pull request by Holzhaus**
The `no-commit-to-branch` hook is useless on CI servers.

### CODE REVIEW

**Comment by uklotzde** [comment]
Any ideas why the first *pre-commit (pull_request)* action has been marked as skipped?

**Review by uklotzde — APPROVED** [review]

**Comment by Holzhaus** [comment]
That's intentional. The GitHub Action workflow file contains 2 jobs:

The first one checks *all files in the repo* (but disables some hooks due to our policy to not mass-reformat legacy files). Currently it only runs on pushed to the mixxx repo. 

The second one checks all hook (except `no-commit-to-branch`) , but only operates on the diff of a pull request.

For pushes, the second one is disabled, for pull requests the first one is disabled.
We did the same on Travis CI. Theoretically we could enable the first job for pull requests, too, but that would just be a waste of time IMHO.

**Comment by uklotzde** [comment]
I am aware of the two jobs. But the jobs have different names while both the names and events of the skipped and the executed job are indentical here.

**Comment by Holzhaus** [comment]
> I am aware of the two jobs. But the jobs have different names while both the names and events of the skipped and the executed job are identical here.

No idea tbh. I can check again tomorrow and post a follow-up PR if I find the cause.

**Comment by uklotzde** [comment]
The confusing skipped action is only a display issue. LGTM

**Pull request merged**
