### PR TITLE
macOS packaging: Fix running macOS bundle from development build directory

### PR DESCRIPTION
**Pull request by fwcd**
There are several configurations in which a developer could run a Mixxx build on macOS:

- `-DMACOS_BUNDLE=OFF`, running `<path to repo>/build/mixxx`
  - This works, since `ConfigObject::computeResourcePathImpl` will find the `CMakeCache.txt` and assume it's a dev build
- `-DMACOS_BUNDLE=ON` and running the App from a packaged DMG
  - This also works, since the `ConfigObject::computeResourcePathImpl` will find the packaged up `Resources` directory
- `-DMACOS_BUNDLE=ON` and running `<path to repo>/build/mixxx.app` (i.e. without packaging it up with `cpack`)
  - This currently **does not work**, since neither of the above assumptions are valid, the executable path does not contain a `CMakeCache.txt` and the `Resources` folder is not packaged up. The user thus sees this alert:
    image

This PR fixes the third use case by searching for the `CMakeLists.txt` in the `mixxx.app` bundle's parent directory if it identifies that it is running from within an app bundle. Currently it searches `mixxx.app/Contents/MacOS`, where obviously it won't find anything.

### CODE REVIEW

**Comment by fwcd** [comment]
@daschuer Any chance you could take a look at this? Would be really convenient for debugging sandboxing issues.

**Comment by daschuer** [comment]
Can we merge this to 2.4?

**Review by daschuer — APPROVED** [review]

**Comment by fwcd** [comment]
Sure!

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
