### PR TITLE
LateNight 2.1 :: fine tuning, 4 FX units, more samplers, skin menu

### PR DESCRIPTION
**Pull request by ronso0**
This is roughly what has to be done to lift LateNight to a proper level.

**General**
- [x] fix fonts: resize GUI quick toggles
- [x] fix fonts: OpenSans for all numbers
- [x] vectorize remaining buttons (deck toggles, xFader switches)

**Toolbar**
- [x] find a way to adjust additional GUI options: Deere/Tango-like skin menu, or maybe a [combobox](https://www.mixxx.org/wiki/doku.php/creating_skins#combobox) to set the number of sampler rows

**Decks**
- [x] add beatgrid edit buttons right to waveforms
- [x] add crossfader routing switches below mixer channels (4 decks only)
- [x] don't transform Key display to uppercase
- [x] add SplitCue button to mixer
- [x] fix mixer alignment when EQs are hidden
- [x] implement star rating in deck controls grid

**Mic/Aux**
- [x] add ducking controls
- [x] tweak Mic/Aux units
- [x] remove crossfader switches from Mic units

**Samplers**
- [x] make space for 8 HotCues when window is at minimal size: shrink Sync, move it below VU meter
- [x] make Title/Artist font case with decks

**Library**
- [x] prevent OS themes from making Analyze radio buttons invisible
- [x] fix style & position of Library buttons, colorize AutoDJ & Recording toggles

**Nice to have**
- _create minimal samplers*_
- _merge vinyl control toggle & vinyl status light*_
- _vectorize VUs, add path mask, so they are easier to resize*_
- _clean up SVGs*_

### CODE REVIEW

**Comment by ronso0** [comment]
@Be-ing I recall removing the microphone xfader switches from Tango earlier on your demand.
What was the reason again? They're not implemented in the engine?

**Comment by Be-ing** [comment]
Correct, the microphones are processed independently of the crossfader, so they do not have crossfader orientation switches.

**Comment by ronso0** [comment]
Fresh screen, minimal window size:
ronso0__0 0 12__2018-01-25__samplers8hcuessync_micduck_



Changed:
- Sampler Sync below pitch fader
- Sampler can host 8 HotCues
- Mic Ducking controls
- xFader switches for 4 decks, as well as for 2 decks with irregular xFader assignment
- 'Open Sans' font for Key, BPM, Rate, PlayPosition, Duration, Beat spinboxes

Please test!

**Comment by nopeppermint** [comment]
@ronso0 looks good, some minor problems:
* eject Button on preview is missing!
* if you change to 4 Deck mode, toogle some of those (Crossfader Orientation) "LMR" Buttons, change back to 2 deck mode, then those buttons are also visible in 2 Deck Mode, but only for 1-2 clicks then they disappear, the only way to get them back is to change to 4 Deck mode..
lmr
* Mixer without EQ (2 deck mode) looks somehow "left" orientated ;-)
mixer_without_eq
* 8 hotcue and Sampler Sync : working as expected 
* about Fonts:
It looks "special" with at least 3 different fonts (bpm, SYNC Button, and Song Title) also the Hotcue "7" looks a little bit strange for me..
open_sans
as comparator the deere skin (seems more like one font for me)
font_deere
* Audio Latency Usage Meter:
-> missing Tooltip
-> not working (always zero) at the same time with deere I got:
cpu_deere

**Comment by nopeppermint** [comment]
* Head and PRE/MST Knob Texts:
they were better readable in branch 2.1 , I suggest to but them horizontal instead of vertical as before (I am sure there is still enough space for"Split Cue" ;-)
branch 2.1:
head_pre_mst_before
new:
head_pre_mst_new

**Comment by nopeppermint** [comment]
* Sampler
-> branch 2.1 shows Artist + Title
sampler_title_artis_2 1
-> this PR only shows Title, NO longer Artist, I prefer to see Artist + Title !
sampler_title_no_artis

**Comment by ronso0** [comment]
> if you change to 4 Deck mode, toogle some of those (Crossfader Orientation) "LMR" Buttons, change back to 2 deck mode, then those buttons are also visible in 2 Deck Mode, but only for 1-2 clicks then they disappear, the only way to get them back is to change to 4 Deck mode..

Consider it a feature & indicator in case you're decks are assigned to crossfader irregularly. Here you can correct that without switching back to 4 decks, and the buttons disappear as soon as the assignment s 'regular'.

Re: fonts
You really can distinguish Open Sans numbers from Ubuntu letters? Chapeau...
Text labels on HotCue, Play button etc. are a LateNight special. Everything else is a suitable workaround until we agree to include another font that fits those buttons (and find that font, of course).

> this PR only shows Title, NO longer Artist, I prefer to see Artist + Title !

Please make suggestions on how to show both artist AND title so that
- sampler grid stays intact aka equally spaced samplers
- we use space efficiently (upper case artist AND title are huge)
- we have a clear distinction between artist and title

From the discussion about Shade 2.1 I read that you use the samplers as parking slots and need artoist and title there, which is fine. All other skins only just show the title of the 'sample' which is mostly a snippet of a track or just a sound, and artist isn't really important then.



> Head and PRE/MST Knob Texts:

Already fixed in the meantime. Also, I'll take of the other Preview deck and latency meter.
Tooltips are typically the last thing I fix before finishing a skin PR, so please check if you find some are missing, or wrong.

**Comment by nopeppermint** [comment]
> Consider it a feature & indicator in case you're decks are assigned to crossfader irregularly. Here you can correct that without switching back to 4 decks, and the buttons disappear as soon as the assignment s 'regular'.

ok, make's sense

> Re: fonts
> a LateNight special. 

just my first impression, 

> another font that fits those buttons (and find that font, of course

 might be not an easy task ;-)

> Please make suggestions on how to show both artist AND title so that
> - sampler grid stays intact aka equally spaced samplers
>- we use space efficiently (upper case artist AND title are huge)
>- we have a clear distinction between artist and title

I see the problems you're facing..
I did a simple compare between 2.0 and 2.1 latenight and just saw this.
In 2.0 we had both Artist + Title but no fixed sampler grid and Title&Artist were NOT upper case, separation was done with a comma. Was not to bad (except the non equal spaced samplers, if this is important)

> Tooltips

I will take a look

**Comment by ronso0** [comment]
okay, this is almost finished.

Regarding additional skin settings, which toggles do we really need? The menu (wherever it will be, however it will look like) doesn't need to be as extensive as in Deere or Tango, Latenight should stay simple IMO.

Mixer
- show EQs
- show Kill buttons?

Effects
- show super knobs
- 2 or 4 FX units (to be introduced in a future PR)

Samplers
- number of sample decks (to be introduced in a future PR)
- Load/Save sample decks

**Comment by ronso0** [comment]
Done. See PR description for most important changes
ronso0__0 0 12__2018-01-29__almost_finished


> Regarding additional skin settings, which toggles do we really need? The menu (wherever it will be, however it will look like) doesn't need to be as extensive as in Deere or Tango, Latenight should stay simple IMO.

I just sorted the GUI quick toggles, added FX Super Knob toggle and some separators.
This should work for now. 
Please test!

**Comment by nopeppermint** [comment]
nice @ronso0 

> show Kill buttons?

yes please (in my case more a hide than show ;-)

> colorize toggles in Recording & AutoDJ 

looks good!

> Tooltips

missing for:
* "SUPER KNOBS" show/hide Button 
* "EQ" show/hide Button


> implement star rating in deck controls grid

somehow I do not see this star rating in deck control..
no_stars

another thing is this:
bildschirmfoto 2018-01-29 21 29 37

is it necessary to show all 64 Samplers, even if the current skin only supports 4 .. ;-)


bildschirmfoto vom 2018-01-29 21-35-57

**Comment by nopeppermint** [comment]
should this look like that ? (I mean there are two pictures on this button)
* there is no tooltip for this Button

**Comment by ronso0** [comment]
> somehow I do not see this star rating in deck control..

interesting..so I'll have to explicitly define the font color for this. Because I can see two stars, they're very dark, but they're there.
On which OS are you?

> tooltips missing for:
    "SUPER KNOBS" show/hide Button
    "EQ" show/hide Button

okay, if all the other are in place. There are some controls we don't have tooltips for, yet. We could create them, but we can't add them to skins right now, because of the 2.1 string freeze for translations.
We can work on adding them to master after I fixed [lp:1740513](https://bugs.launchpad.net/mixxx/+bug/1740513)

> is it necessary to show all 64 Samplers, even if the current skin only supports 4

Nope. Please file a bug. Although the goal is to have all skins support 64 sample decks, I doubt this will happen. See discussion about that in Shade update PR.

**Comment by nopeppermint** [comment]
> Please file a bug

https://bugs.launchpad.net/mixxx/+bug/1746105

> On  which OS are you?

Linux Mint 18.3 x64, Cinnamon 3.6.7

**Comment by nopeppermint** [comment]
- star rating 
 => now working
bildschirmfoto vom 2018-01-29 23-52-01


- EQ Kill
 => working, thanks

**Comment by naught101** [comment]
Just trying the old LateNight again (sorry, I haven't had time to compile from the branch), and maybe it's because I'm used to using Deere for the ratings widget, but the title/artist sections seem quite dense. Perhaps it would be good if both rows had an extra pixel or two of padding on all sides? This might also help to make the 2-deck version line up with the mixer panel at the bottom.

**Comment by ronso0** [comment]
@naught101 
You don't need to compile to test a skin.
Check mixxx wiki [1](https://mixxx.org/wiki/doku.php/start#getting_started) [2](https://mixxx.org/wiki/doku.php/using_git), and my comments [here](https://github.com/mixxxdj/mixxx/pull/1259#issuecomment-310031072) and [here](https://github.com/mixxxdj/mixxx/pull/1357#issuecomment-336876652)

The essence from those links:
use git to test skins/mappings
- choose/create a folder on your disk where to put mixxx source code
- in there, type `git clone https://github.com/ronso0/mixxx` to clone the repo to your disk
- `git checkout Tango-update` to switch to skin update branch
- link the `/res/skins/Tango-update` from repo clone to your skin directory
- start Mixxx, Settings > Preferences > choose new skin, test
- type `git pull` every time you want to pull recent changes from PR and skin will be updated
- restart Mixxx, test again

In case you experience strange behaviour of a skin, you can also try with a clean profile:
`mixxx --resourcePath /where/ever/source/files/are/res/ --settingsPath /*the folder you like*/`
Your library won't be accessible then but you have a clean mixxx.cfg and soundconfig.xml

**Comment by ronso0** [comment]
You're right, in LateNight 2.0 artist and title rows were 2px taller... 2.0:
ronso0__0 0 12__2018-01-31__latenight-2 0-deck

2.1 (this branch)
ronso0__0 0 12__2018-01-31__latenight-2 1-deck


Btw the decks' bottom margin and smaller margin of the mixer are fixed no matter how tall the decks are. Only thing that changes is the overview's height, it's compressed to minimum with 4 decks

**Comment by naught101** [comment]
Ah, cool, thanks. Now running the updated version.

I mean this bit, I don't understand why the mixer is slightly taller than the decks:
mixxx latenight untitled

I'm not sure that I like the ALL CAPS ARTIST in the new version, but if it does stay, that's all the more reason to have more padding around the artist (it's more noticably cramped with all caps). 

Otherwise the new skin is looking damn fine. I quite like the green, even though it seems like the kind of colour that shouldn't work..

**Comment by ronso0** [comment]
> I'm not sure that I like the ALL CAPS ARTIST in the new version, but if it does stay, that's all the more reason to have more padding around the artist (it's more noticably cramped with all caps).

I'm sure I don't like it. And I don't recall transforming anything to uppercase, I just wanted to keep as many things the 'LateNight style' as they were. Now that I see it side by side, I'll double check the 2.0 version.
Sure we can increase artist & title rows, but it'll eat up another half line of the library.. Will check that

I know that you were talking about that tiny offset between mixer and decks, it's just that 'it was like that' and -for me- it somehow creates character, compared to streamlined Deere and Tango. We also need to keep in mind that we actually need larger margins between that major skin components so the skin works good on big screens. But if that's an issue for others as well, I'll remove it.

**Comment by ronso0** [comment]
Okay, I fixed uppercase text-transform for artist & sampler title. Apparently I introduced it by mistake while consolidating css, and it felt plausible for LateNight ;)
Also artist & title have more whitespace around them.

**Comment by naught101** [comment]
Padding fix is much better. I think the decks could benefit from an extra couple of px left/right padding on my screen (1080p), though I can see how that might be problematic for smaller screens.

>[taller mixer] somehow creates character, compared to streamlined Deere and Tango

Ok, yeah, I can agree with that. It helps to differentiate between the sections a bit too. Perhaps it should actually be bigger on larger screens though, to make it more obviously intentional.

Also, there is a gap between the decks in 4-deck mode. A similar gap could be added between the decks and the mixer, to further accentuate the separation.

And perhaps the line-fill in the bottom section of the deck could also be added to the top section (KEY to FX2), to further reinforce the deck gap?

Another couple of minor things:

- The beat grid adjust section expansion button has two icons, and no tool-tip.
- Maybe the minimum waveform height should be equal to the minimum height when the beat grid section is open?
- the text in the master section (MASTER, L/R, HEAD, PRE/MST) could be slightly lighter, to differentiate between the text and background lines.
- the zero and 100% position markers in the master section are slightly squashed, and a bit blurry:

screenshot_20180202_104822

**Comment by daschuer** [comment]
PRE/MST is IMHO uncommon 
How about PFL/MST or CUE/MST ?

**Comment by ronso0** [comment]
> The beat grid adjust section expansion button has two icons, and no tool-tip.

It's one icon saying something like "configure beatgrid". not intuitive for you?
As I said
> There are some controls we don't have tooltips for, yet. We could create them, but we can't add them to skins right now, because of the 2.1 string freeze for translations.
We can work on adding them to master after I fixed lp:1740513

This is one of them.

Thanks, your further suggestions are good, let's keep them in mind for the next PR.
I think LateNight is in a good shape now and I'd like to get this merged soon.

> How about PFL/MST or CUE/MST ?
CUE/MST is fine. Before it was PRE/MAIN

**Comment by ronso0** [comment]
Latest changes:
- headphone mix knob is labeled CUE/MST 
- knob labels in Mixer and expanded FX slots are much easier to read, they now have a dark background
- removed expanding spacers from FX unit controls column, increased padding
ronso0__0 0 12__2018-02-03__knob-label-bg_fx-units

Ready to merge?

**Comment by nopeppermint** [comment]
nice !
* Preview text is written in capital letters, I prefer mixed letters, as in the decks/samplers

**Comment by Be-ing** [comment]
* The PLAY button on the auxiliary inputs is confusing. It uses the tooltip for mute, but it says PLAY.
  * With 4 decks and no EQ kill buttons, the EQ knobs are misaligned:
image
  * I do not see an icon to toggle broadcasting.

Anyhow, this PR has enough improvements to be merged as is. Let's continue the discussion in a new PR.

**Comment by ronso0** [comment]
Thanks for merging!

> The PLAY button on the auxiliary inputs is confusing. It uses the tooltip for mute, but it says PLAY

https://bugs.launchpad.net/mixxx/+bug/1747212
optimize Auxiliary enable control 

> With 4 decks and no EQ kill buttons, the EQ knobs are misaligned

if they're aligned with VU like before, the whitespace within the mixer just doesn't look good..

**Comment by Be-ing** [comment]
I think the EQ knobs should be centered with respect to the volume faders.

**Comment by naught101** [comment]
> > The beat grid adjust section expansion button has two icons, and no tool-tip.
>
> It's one icon saying something like "configure beatgrid". not intuitive for you?

On my system, it looks like this:

screenshot_20180204_152541

**Comment by naught101** [comment]
@Be-ing : the knobs and faders ARE centred on my screen, although the 'Filter' text is not:

screenshot_20180204_152906

**Comment by naught101** [comment]
Ah, it's because the EQ-Kill offsets the knobs..

**Pull request merged**
