### PR TITLE
Controller script js import

### PR DESCRIPTION
**Pull request by ferranlala**
This PR adds a new include function for JS controller scripts. It allows JS scripts to include other js files. This new function can work with the current way to include scripts by specifying them in the xml.

The include function takes a filename as only parameter and then loads and evaluates the content of that file:
`include("commonFunctions.js");`

The filename can be specified with an absolute path or a relative path. The relative path is taken relative to the importing file. The path syntax is the one specified for Qt (unix style).
`include("../scripts/commonFunctions.js");`
`include("/home/ferran/mixxx_scripts/commonFunctions.js");`

Files are only included once, so it's safe to include the same file from several sources. It is also safe to include a file that has been already included in the xml.

If a call to include is removed from a file while mixxx is running, mixxx reloads the including file live and the included file content is no longer available.

JS snippets in the xml files can't include script files. Only JS loaded from a script file can include other files. (there is no unit test for this because ControllerEngine resets itself when a script file is updated, this makes the test difficult to implement. It has been manually tested in linux though).

You can see some simple examples in the unit tests.

**Why this new way of including controller scripts?**

It's now easier to maintain complex mappings:
- Script files can now be organized in folders and subfolders.
- Now script files are included live: no need to re-apply the xml mapping to a controller to include/uninclude a new script file.
- Only the main script file needs to be specified in the xml file: set and forget.

Easy to share scripts:
- Ben creates a complex controller script library that is written in several files. Mary downloads Ben's library. Before PR, Mary needed to manually specify every file of the library in her xml file. Now, she only needs to include the main file of Ben's library in her script file. The rest of the includes are handled by the library itself.

Kazakore recently [shared in the forums](https://www.mixxx.org/forums/viewtopic.php?f=7&t=11677&p=37502) a massive xml file with all the possible midi messages a controller can send. With that xml and this PR, a developer can now forget about the xml during script development, which greatly decreases the development time.

**TODO:**
- [ ] If a file specified with relative path is not found, search it relative to res/controllers/
- [ ] Document in wiki

### CODE REVIEW

**Comment by Be-ing** [comment]
Thanks for working on this. I'll hold off discussing it until after 2.1 is released.

**Comment by ferranpujolcamins** [comment]
Wow, just discovered [mixco](https://sinusoid.es/mixco/).
I think this PR is totally unnecessary. I think I'll close it.

@Be-ing thoughts?

**Comment by Be-ing** [comment]
I think this will be obsoleted by [implementation of the feature upstream in Qt](https://bugreports.qt.io/browse/QTBUG-22356).

**Comment by ferranpujolcamins** [comment]
After thinking about it I came to the conclusion that this is not the way to go.
The way to o is either:
- We develop a good story for advanced mappings around some JS bundler like Browserify
- QScriptEngine finally gets built-in support for ECMAScript modules

**Pull request closed without merging**
