### PR TITLE
LateNight skin: Small decks for big library view with vu meters and play / pause button.

### PR DESCRIPTION
**Pull request by bestdani**

### CODE REVIEW

**Comment by Be-ing** [comment]
Please include a screenshot when proposing changes to the GUI.

**Comment by bestdani** [comment]
current look:

**Comment by Be-ing** [comment]
Looks pretty good :) Would it be possible to squeeze mini volume faders and the crossfader in this in a way that doesn't make it too big?

**Comment by bestdani** [comment]
I think that something like that could be placed there, but I thought the main intention of showing the small decks is to have a quick overview of what happens on the decks while browsing for tracks so that you will notice when a track ends for example. I also discared my first thoughts about adding moving waveforms for this reasons since I don't think that they add information required for this quick general overview. I also thought about testing to display all four decks in one row instead of using two rows since I think that vertical screenspace is the important option in the big library view.

**Comment by Be-ing** [comment]
You made some unrelated commits to this branch so now they're included in this PR. I made the same mistake with my first PR. See the instructions on https://github.com/mixxxdj/mixxx/pull/607 for how to fix this.

**Comment by Be-ing** [comment]
I do like the one row version better. Yes, the intention is to keep only information helpful for picking the next track on screen. IMO the level meters are not helpful for this, but the volume faders and crossfader would be. These show which deck(s) are actually making sound at the moment. The key, rate, and BPM are very helpful for this purpose.

**Comment by bestdani** [comment]
Ehhhhm ok, I'm not used to github though I use git quite often locally (will have to read a basic introduction maybe when I can find time for it). I ended up with a branch for the skin changes and one for the mappings now, I guess it requires a new pull request then?

**Comment by Be-ing** [comment]
Yes, open a separate pull request for each new feature or bug fix.

**Comment by sblaisot** [comment]
You added new files to res/controller. Please also update windows uninstaller : https://www.mixxx.org/wiki/doku.php/contributing_mappings#windows_installer_update

**Comment by Be-ing** [comment]
This pull request has not been updated in years so I am closing it to reduce the clutter of open PRs. If you solve the merge conflicts and would like to have this merged in the future, please reopen it. However, I am not convinced anymore that this is a great idea. To me it feels like a hack around around LateNight's waste of vertical space which has since been solved.

**Pull request closed without merging**
