### PR TITLE
Add warning when trying to enable AutoDJ with left & right deck

### PR DESCRIPTION
**Pull request by MetriSomesh**
Added warning message when trying to enable AutoDJ if there's no left & right deck.

### CODE REVIEW

**Comment by ronso0** [comment]
Please stop opening new PRs, instead follow the instructions @daschuer and I gave you and fix the original PR. This is actually trivial given the small change set.
First get familiar with how git works. Not doing that and not reading the hints `git` gives in the terminal and thereby implicitly` asking for help for every single step is a waste of developer time.

To be continued in #11013

**Comment by MetriSomesh** [comment]
@ronso0  Sorry about that I will not repeat my mistakes again, I understood the problem and the pre-commit was causing it I don't know how. But at the time of commit normally it ask for password, but while using pre-commit it doesn't ask any password, that's why it is causing errors

**Comment by MetriSomesh** [comment]
@ronso0 You can check this request for the checks If any error will occur I will restudy the whole github and then I will start contributing to this community

**Comment by ronso0** [comment]
Pre-commit is still failing since the indentations don't match.
You need to install pre-commit as explained in using Git https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking
Then pre-commit will be run on the changed files when you `git commit` (and that will not ask for your password, only `git push` will)

**Comment by MetriSomesh** [comment]
@ronso0  I have installed it already.

**Comment by MetriSomesh** [comment]
@ronso0 I am sorry to disturb you again but I was looking for this from nearly 4 hours now still cant find a way to fix it

The pre-commit is giving this output:

err

**Comment by ronso0** [comment]
You obviously didn't bother to read the command output. Below the red Failed it says
"Python was not found"...

**Comment by daschuer** [comment]
There is work in progress to make pre-commit on windows more robust. Please 
```
git pull git@github.com:daschuer/mixxx.git pre-commit-python
```
Unfortunately this will combine the two PRs, but I can clean that up before merge.

**Comment by daschuer** [comment]
You may also report your experience in the original PR that we get it merged soon: 
https://github.com/mixxxdj/mixxx/pull/11004

**Comment by ronso0** [comment]
> You obviously didn't bother to read the command output. Below the red Failed it says "Python was not found"...

Ok, sorry, didn't know this is a known issue on Windows.
Please proceed as @Holzhaus suggested on Zulip https://mixxx.zulipchat.com/#narrow/stream/247620-development-help/topic/Pre-commit-help/near/306704977
Download the pre-commit patch file, apply it locally, git commit --amend and force-push.
Then this should finally be in a mergeable state.

**Comment by MetriSomesh** [comment]
@ronso0 I have followed all the steps as you followed

**Comment by MetriSomesh** [comment]
@daschuer  I am sorry, I didn't opened my github because I was searching solution on the error which was given by the pre-commit. I have now seen the PR you mentioned.

**Comment by ronso0** [comment]
Okay, finally LGTM
@daschuer any more comments?

This is a good first step. Later on it would be nice to show a message when assign switches are changed while AutoDJ is running. Though I think this is out o scope here.

**Comment by MetriSomesh** [comment]
@ronso0 @daschuer  Thank you very much for your help. I learned a lot of things while doing my first ever git request successful.

**Review by daschuer — APPROVED** [review]
LGTM, Thank you for your endurance!

Before merge, we need your permission to distribute the code with Mixxx. 
Please sign https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ and comment here when done. Thank you.

**Review by ronso0 — APPROVED** [review]

**Comment by MetriSomesh** [comment]
@ronso0  Done

**Comment by MetriSomesh** [comment]
@ronso0  and @daschuer  Thank you very much.

What is LGTM anyway ?

**Comment by daschuer** [comment]
LGTM= Looks good to me

**Pull request merged**
