### PR TITLE
Bug 1316785 -- improve controller preset directory buttons 

### PR DESCRIPTION
**Pull request by Frydac**
Pull request for 
https://bugs.launchpad.net/mixxx/+bug/1316785

I asked some questions in the bugtracker, they where not answered so I tried to use some common sense.

I created 2 commits, the first adds the requested description, removes the local preset button as afaik it serves the exact same function as the user preset button. However the code to read the presets is still intact in that commit. 
In the second commit I removed all references I could find to the local preset folder. The only issue I can see when doing this is that when a user uses 2 versions of mixxx, one with only the local presets folder and one with only the user presets folder, that he might have to put his presets in 2 distinct folders (the user could use the global preset folder in stead of course).
I've tried to look at the git log when these elements where introduced exactly, but that proved a more difficult exercise than expected, so I haven't gotten to the bottom of when which folder was introduced and why.

### CODE REVIEW

**Comment by daschuer** [comment]
ok to test

**Comment by daschuer** [comment]
It looks like it was introduced here: 
https://github.com/mixxxdj/mixxx/commit/bd08cb0a1c5d904cb5552e0a640d2ae6fb50171d

Other related commits: 
https://github.com/mixxxdj/mixxx/commit/5d1dec6cc5c5fbd2728b8102b4bc2b9801ddd301
https://github.com/mixxxdj/mixxx/commit/2f7877f9f74b841c12e865a62b3faf2d66d9b50e
https://github.com/mixxxdj/mixxx/commit/bb2be2a21b7790f34601eab4a0478f5f677e610c
https://github.com/mixxxdj/mixxx/commit/8d047cdcbc988a7b7b5a1ee6592c01dd5d4b6c18

**Comment by daschuer** [comment]
@all: Is it OK to just remove the "/preset" folder support?  
Or should be continue to support it under the hood? 

What should be the merge target of this PR 1.12.0 1.12.1 1.13?

**Comment by sblaisot** [comment]
For windows users, and following discussion on bug https://bugs.launchpad.net/mixxx/+bug/1457624

I think that user should not be encouraged to put their own files or modified one in the mixxx installation folder.

Instead, mixxx preference folder (%APPDATA%\Mixxx or whatever it is on windows) should be used for "one user only" files and Mixxx should support %ALLUSERSPROFILE%\Mixxx for "multi user" preferences (or otherwise we can add a clear subdirectory for user data in the Mixxx installation directory different from the one we put default files in).

Files in the Mixxx installation directory should be considered deletable on uninstall

Consistency across OSes is also required. The same behaviour should occur on the different OSes (at least the"most same" as possible), on file update and Mixxx uninstallation.

**Comment by rryan** [comment]
RE: removal of /presets as @daschuer points out it's kind of an artifact. We supported it for a while and then the HID refactor came in which renamed it to controllers. But then users who used 'presets' complained that it didn't work anymore so we supported both. At some point this "local" and "user" distinction got added which I agree is just confusing as they both do the same thing. 

Let's remove '/presets' support. This release is a good time for breaking changes.

That means this PR should be against '1.12'.  

+1 to @sblaisot -- the text for the system presets folder should warn that users should put downloaded presets in their user presets folder.

**Comment by Frydac** [comment]
Updated description to reflect the suggestions, rebased my branch to the current master (didnt realize github would then see all my commits as new, not sure what the recommended way is of keeping PR in sync)

**Comment by Frydac** [comment]
Forgot to save my last edits in the .ui file, amended them to my last commit.

**Comment by daschuer** [comment]
Now we have this: 

> Save the preset file(s) in the "User Preset Folder" to make the preset available only for the current user. (Recommended)

> Save the preset file(s) in the "System Preset Folder" to make the preset available for all users. (Not recommended: this folder is subject to change when uninstalling/reinstalling the application, files could get overwritten or deleted)

It feels weak to offer a button an tell the user what he should not do with it in the first place. 

What about just removing the second button? 
Or keep it with a hint like "Preinstalled Presets" 

In case we keep both buttons, please make sure they have the same size. Put them in a grid or something.

**Comment by Frydac** [comment]
Ok,  thanks for the feedback.

I agree it didn't feel quite right, though it seemed informative to me, 'expert' users would be able to use it safely, but then again, the usecases are probably very few and in those cases, copying the presets for each user is a not too cumbersome workaround.
@sblaisot 's solution of adding a 3rd 'all users' folder would probably be best, however mac/linux don't really have the standard concept for an 'all users' folder similar to windows afaik. Adding this functionality is maybe best left for another issue when the need presents itself.

Considering this it seemed best to me to change the description above the buttons, remove the description next to the user button, and remove the System Presets button and its description.

Documenting the system preset folder is maybe something for in (some appendix in) the manual?

**Comment by Frydac** [comment]
Forgot to remove the qt connection to the button, amended to latest commit

**Comment by daschuer** [comment]
> Mixxx uses "presets" to connect messages from your controller to controls in Mixxx. If you do not see a preset for your controller, you can download one online from the Mixxx Forums or Mixxx Wiki. After downloading a preset, place the XML (.xml) and Javascript (.js) file(s) in the "User Preset Folder"

Nice! Thank you very much. 

Can you debase this to 1.12?  
I think it is 
git rebase --onto 1.12  c4532a0

Before merge, we need you permission. Please signs https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ

**Comment by daschuer** [comment]
Mmm wait. We are in beta stage now. 
@esbrandt: Is it still allowed to change strings? 
Maybe it is better to keep the old slightly wrong translated string instead of an precise untranslated.

**Comment by Frydac** [comment]
K, I think I got the right rebase now. First time it was on master (and I thought it was on 1.12 so I pushed), then I got some order wrong in my command and got lots of conflicts, finally I used:
git rebase --onto 1.12 master bug_1316785
which seemed to do the trick.

**Comment by daschuer** [comment]
We are probably able to translate the new description before release.
If not, I do not expect a real problem because a user who is able to find a controller script in our English forums, will be able to read an untranslated string as well.

**Comment by daschuer** [comment]
LGTM. Thank you @Frydac!

**Pull request merged**
