### PR TITLE
CI: Add build using Qt6 on Arch Linux

### PR DESCRIPTION
**Pull request by Holzhaus**
Do not merge until qt6 build works.

### CODE REVIEW

**Review by Be-ing — APPROVED** [review]
Merge?

**Comment by uklotzde** [comment]
Let's merge or rebase on main and see the results before merging.

**Comment by uklotzde** [comment]
Or a `qt6-ci` branch dedicated to performing CI builds after merging `main` periodically? All Qt6 development will continue on main. The only drawback is that new CI build failures are detected after merging PRs into main.

**Comment by Be-ing** [comment]
I'm not going to bother setting up extra complexity to only run CI jobs periodically on some other branch and I think this would be pointless. What will most likely happen if someone wastes time on that is that the CI jobs on that other branch will be ignored entirely.

**Comment by Be-ing** [comment]
It's not hard to scroll to the bottom of a pull request and see which checks failed and passed. It's really not a big deal to have a red X on https://github.com/mixxxdj/mixxx/pulls

**Comment by uklotzde** [comment]
Disturbing the CI checks for everyone on main for an unforeseeable time is a strong burden.

I recommend the extra branch as proposed. One step after another.

**Comment by Be-ing** [comment]
More Git branches only creates extra work. Let's get everything into main ASAP.

**Comment by uklotzde** [comment]
I am not going to open PRs one by one and scroll through all test results before deciding if it is ready for review.

**Comment by Be-ing** [comment]
Then the only route forward I see is piling all changes needed for Qt6 into one giant pull request.

**Comment by Be-ing** [comment]
That or tolerate having entire source code files that aren't built on CI for some time.

**Comment by Holzhaus** [comment]
> Then the only route forward I see is piling all changes needed for Qt6 into one giant pull request including starting Qt6 CI.

We can also just make a `qt6` branch with CI, then merge that branch into `main` and revert the commit that adds Qt6 CI on `main`.

Then all Qt6 PRs can be opened against the `qt6` branch. We can regularily merge the `qt6` branch into `main`.

 Because the CI commit was reverted on `main`, CI on `main` will still pass. We can drop the `qt6` branch when Qt6 CI starts to pass.

**Comment by Be-ing** [comment]
Creating big branches is a setup for disaster. I will stop working on Qt6 support if this is done just for the sake of not seeing a red X.

**Comment by Holzhaus** [comment]
> Creating big branches is a setup for disaster. I will stop working on Qt6 support if this is done just for the sake of not seeing a red X.

Have you read my comment here? https://github.com/mixxxdj/mixxx/pull/4428#issuecomment-945180459

There would be no big branch, because the `qt6` branch will be regularily merged into `main`. The only difference between the `qt6` branch and `main` would be that `qt6` contains a commit that adds Qt6 CI and `main` additionally contains a commit that reverts that commit (so that Qt6 CI is not added to `main` when we merge `qt6` into `main`).

**Comment by Be-ing** [comment]
I am highly doubtful anyone will bother paying attention to some superfluous branch's CI results.

**Comment by Be-ing** [comment]
A branch solely for CI that nobody pays attention to is no more useful than running builds locally.

**Comment by Holzhaus** [comment]
> I am highly doubtful anyone will bother paying attention to some superfluous branch's CI results.

What do you mean? The qt6 PRs go against the `qt6` branch, which means that we can look at those CI results on every Qt6 PR.

> I see two choices:
>
> 1. Tolerate not building some files on CI for a while.
> 2. Tolerate seeing a red X for a while.

The issue with (2) is that we accustom ourselves to ignoring the CI check mark. And because the Qt6 CI check always fails, what difference does it make compared to not having that check at all? So I think we should have a `qt6` branch that can be used to resolve Qt6 build issues. As soon as it builds we can drop the branch and use main instead.

**Comment by Be-ing** [comment]
> The qt6 PRs go against the qt6 branch

I will not continue working on Qt6 this way. This is a setup for trouble.

**Comment by Be-ing** [comment]
How will we maintain the qt6 branch? Keep merging main -> qt6, then merge branches into qt6, then merge qt6 -> main? This seems messy. Alternatively we can rebase PRs onto main right before merging.

**Comment by daschuer** [comment]
Uh, the reverted commit 12019eb in main prevents that. 
Can we create another Qt branch from main and re-revert the commit?

**Comment by Be-ing** [comment]
None of this cross-cross merge mess or Git tricks would be needed if we just looked at the individual CI checks.

**Comment by Holzhaus** [comment]
I don't see any problem with the proposed method and think it's far easier and less messy than uncommenting the workflow all the time. But If you like it better go ahead.

**Pull request merged**
