### PR TITLE
release Mixxx 2.1

### PR DESCRIPTION
**Pull request by Be-ing**
:tada:

### CODE REVIEW

**Comment by uklotzde** [comment]
Don't worry, I did not plan to not merge this PR ;)

The resulting merge commit on the 2.1 branch should finally be tagged with the release tag *after* this PR has been merged (see also the *rc1* tag). Pushing a locally created tag into the remote repo will implicitly create a GitHub release of the same name. Afterwards the release information has to be edited manually, because it is derived from the metadata of the corresponding commit.

**Comment by Be-ing** [comment]
Wait, let's give @ronso0 a chance to fix https://bugs.launchpad.net/mixxx/+bug/1764099

**Comment by Be-ing** [comment]
Oh, let's not forget to pull the latest translations!

**Comment by rryan** [comment]
:+1: yay! Great job everyone. 

I don't see a Git tag on this commit?

**Comment by Be-ing** [comment]
See @uklotzde's comment above about the Git tag.

**Comment by rryan** [comment]
I might be misunderstanding, but I was going to suggest we merge a tagged commit with the "squash and merge" option which does not hide the commit behind a GitHub merge commit.

> The resulting merge commit on the 2.1 branch should finally be tagged with the release tag after this PR has been merged (see also the rc1 tag). Pushing a locally created tag into the remote repo will implicitly create a GitHub release of the same name. Afterwards the release information has to be edited manually, because it is derived from the metadata of the corresponding commit.

What's the difference between merging a tagged commit vs. pushing a tagged commit in this scenario?

**Comment by ronso0** [comment]
> Wait, let's give @ronso0 a chance to fix https://bugs.launchpad.net/mixxx/+bug/1764099

Doing it right now..

**Comment by ronso0** [comment]
https://github.com/mixxxdj/mixxx/pull/1611

**Comment by Be-ing** [comment]
So should I tag this?

**Comment by uklotzde** [comment]
@rryan Sounds good to me :+1: The rc1 has been tagged later. Here we can use the workflow you proposed.

**Comment by uklotzde** [comment]
I just wanted to make sure that the tag appears directly on the release branch and not in a separate commit before the actual merge commit, even if that might be empty.

**Comment by nopeppermint** [comment]
follow up to #1611 =>  #1612 fix the remaining vinyl buttons

**Comment by christophski** [comment]
Great work everybody, well done (Y)

**Pull request merged**
