### PR TITLE
Rate perm button fix

### PR DESCRIPTION
**Pull request by ywwg**
Fix two regressions: The rate_perm buttons in the UI stopped working, because the rate slider connection ignores updates from the engine itself.  This is correct behavior, because doing so would create infinite signal loops.

Second, fixed the visual rate indicator showing up as "-100" before a track is played.

### CODE REVIEW

**Comment by ywwg** [comment]
any notes for review?

**Review by Holzhaus — APPROVED** [review]
Thanks! I can reproduce the issue and you patches fix it. Nice that you also added a new test to prevent future breakage. Since I'm not know the intricacies of the enginebuffer code somebody else should have a look, too. But so far this LGTM.

**Comment by ywwg** [comment]
this is a pretty simple fix but I need an LGTM from someone.  @daschuer @rryan @Be-ing ?

**Comment by ywwg** [comment]
>  I can reproduce the issue and you patches fix it.

(and thanks for testing this!)

**Review by daschuer — APPROVED** [review]

**Comment by daschuer** [comment]
LGTM Thank you.

**Pull request merged**
