### PR TITLE
Upgrade qm-dsp from 1.7.1 to 1.8.0

### PR DESCRIPTION
**Pull request by uklotzde**
No changes for us, just a formal update.

- Remove obsolete patches
- Delete unused thread sources

### CODE REVIEW

**Review by Holzhaus — COMMENTED** [review]
I was worried updating to a new major version so short before the release, but it looks like there are only very few changes. Maybe it's okay in this case.

**Comment by uklotzde** [comment]
> I was worried updating to a new major version so short before the release, but it looks like there are only very few changes. Maybe it's okay in this case.

No source code changes otherwise, they only applied @daschuer's pending patches.

**Comment by daschuer** [comment]
It looks like this reverts the patches.

**Review by daschuer — CHANGES_REQUESTED** [review]
I think you need to revert the part with the patches.

**Comment by uklotzde** [comment]
Did I get the changelog wrong?

QM Vamp Plugins v1.8 (January 2020)
-----------------------------------

 - Fix incorrect chromagram tuning in key detector, improving
   key detector output (thanks to Daniel Schürmann)
 - Add Merged Key Strength Plot output to key detector
 - Fix incorrect time alignment of tonal-change plugin outputs

Sorry for the noise. I guess I got confused by all this patching.

**Pull request closed without merging**
