### PR TITLE
 first pass at filter by 'datetime_added'.

### PR DESCRIPTION
**Pull request by austintino**
First pass at adding `datetime_added` as a filter to the sqliteDB.

https://bugs.launchpad.net/mixxx/+bug/1485404

### CODE REVIEW

**Comment by jclaveau** [comment]
It's just a suggestion but, in my old company, we always used "_on" suffix ("added_on" in your case) for dates or datetimes as it allowed us to change from one type to another without having to rename everything.

**Comment by daschuer** [comment]
Sorry for still complaining.. 

The library column is labelled "Date Added" so IMHO a required search tag is "date_added". 
I have on preference, if we should keep "datetime_added" or not. 

Before we can merge this, you need to become a Mixxx contributor. 
Please sign: https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ
and comment here when done. 

Thank you.

**Comment by austintino** [comment]
@daschuer 

Added the ```date_added``` field based on your comments. Also, agreement signed. :smile:

**Comment by daschuer** [comment]
I have just tested it, and it works like a charm. Thank you. 
LGTM

**Pull request merged**
