### PR TITLE
Highlight Crates a Track is in

### PR DESCRIPTION
**Pull request by rryan**
Clone of @MK-42's PR #598 with a performance fix.

### CODE REVIEW

**Comment by MK-42** [comment]
This won't compile in my tree because of the nullptr references. Is the current master merged in here so that we build with c++11?

**Comment by MK-42** [comment]
works after merging current master in. Also is blazing fast again ;-) LGTM

**Comment by rryan** [comment]
SGTM, thanks @MK-42 !

**Comment by rryan** [comment]
@MK-42 -- you're not in the Mixxx credits yet -- what name would you like to be added?

**Comment by rryan** [comment]
Oops -- you're in the 1.12 branch but I was looking at master. nevermind!

**Comment by sblaisot** [comment]
@rryan you take the wrong guy. There is another one that's not in the credits ;)

**Comment by rryan** [comment]
@sblaisot oops :) what name would you like in the credits?

**Comment by sblaisot** [comment]
@rryan you just have to merge PR606 ;)

**Pull request merged**
