### PR TITLE
Add latest changes to CHANGELOG (main)

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
12973, 13113, 13121 are already part of 2.4.1

**Comment by daschuer** [comment]
Fixed by amend.

**Comment by JoergAtGithub** [comment]
> 12973, 13113, 13121 are already part of 2.4.1

Please check these 3 PRs again

**Comment by JoergAtGithub** [comment]
#13196 is for 2.4.2

**Comment by daschuer** [comment]
Oh, I have realized I did this PR again. Now I have rebased the new version onto the old. 
Hope it is good now.

**Comment by JoergAtGithub** [comment]
The following issues were merged into 2.4, but are listed under 2.5:

- https://github.com/mixxxdj/mixxx/pull/13050
- https://github.com/mixxxdj/mixxx/pull/12687
- https://github.com/mixxxdj/mixxx/pull/12673
- https://github.com/mixxxdj/mixxx/pull/12674
- https://github.com/mixxxdj/mixxx/pull/12675
- https://github.com/mixxxdj/mixxx/pull/12665
- https://github.com/mixxxdj/mixxx/pull/12666
- https://github.com/mixxxdj/mixxx/pull/12662
- https://github.com/mixxxdj/mixxx/pull/12663
- https://github.com/mixxxdj/mixxx/pull/12847
- https://github.com/mixxxdj/mixxx/pull/12853
- https://github.com/mixxxdj/mixxx/pull/12889
- https://github.com/mixxxdj/mixxx/pull/13223
- https://github.com/mixxxdj/mixxx/pull/12811
- https://github.com/mixxxdj/mixxx/pull/13208
- https://github.com/mixxxdj/mixxx/pull/12878

The following seem to be wrong references:
- Don't include X11Info on QT6 https://github.com/mixxxdj/mixxx/pull/5
- Disable broken tests and skip ANGLE DLL install on Windows https://github.com/mixxxdj/mixxx/pull/93
- Silence some float conversion warnings by making conversion explicit https://github.com/mixxxdj/mixxx/pull/6

**Comment by daschuer** [comment]
fixed

**Comment by JoergAtGithub** [comment]
LGTM! Thank you!

**Pull request merged**
