### PR TITLE
Sync Lock: Fix InternalClock,bpm so it can be used to control overall rate

### PR DESCRIPTION
**Pull request by ywwg**
Should fix https://bugs.launchpad.net/mixxx/+bug/1937123

### CODE REVIEW

**Comment by ywwg** [comment]
@Be-ing, this change should fix your issue where changing InternalClock,bpm wasn't affecting playback rate.

**Review by Be-ing — APPROVED** [review]
This works as it used to, thanks. I have no comment on the implementation and leave that for someone else to review.

**Review by daschuer — APPROVED** [review]
LGTM, Thank you

**Comment by daschuer** [comment]
Works also in the double BPM case

**Pull request merged**
