### PR TITLE
Replace ConfigKey::isEmpty()/isNull() with Configkey::isValid()

### PR DESCRIPTION
**Pull request by Holzhaus**
Requested by @daschuer here: https://github.com/mixxxdj/mixxx/pull/2947#discussion_r470441512

### CODE REVIEW

**Comment by Holzhaus** [comment]
The pre-commit hook will fail until #3014 has been merged.

**Comment by uklotzde** [comment]
Unfortunately a test fails.

**Comment by Holzhaus** [comment]
> Unfortunately a test fails.

Ah, apparently that was a bug before this PR as well, but we didn't notice it because no script in our repo requests a completely empty key. I just wonder why I can't reproduce it on my machine and the Travis checks didn't complain either.

**Comment by uklotzde** [comment]
LGTM. Waiting for CI.

**Comment by uklotzde** [comment]
CI failure is unrelated. We need to get rid of the SCons builds asap.

LGTM

**Comment by uklotzde** [comment]
Merged too early. Now I get multiple debug assertions at startup:

```
Critical [Main]: DEBUG ASSERT: "key.isValid() || flags.testFlag(ControlFlag::AllowInvalidKey)" in function ControlProxy::ControlProxy(const ConfigKey&, QObject*, ControlFlags) at /tmp/mixxx/src/control/controlproxy.cpp:17
```

**Comment by Holzhaus** [comment]
Master or 2.3?

**Comment by uklotzde** [comment]
master

**Comment by Holzhaus** [comment]
Do you have a controller connected? Which skin? I cannot reproduce it.

**Comment by Holzhaus** [comment]
Ah, looks like it's Deere.

**Pull request merged**
