### PR TITLE
I have a Numark MixTrack Pro II

### PR DESCRIPTION
**Pull request by Dazmed707**
Complete Mapping for MixTrack Pro II ?
Found for 2.3.2 ? or 2.4.0?

Guide install ?

### CODE REVIEW

**Comment by Be-ing** [comment]
GitHub is not a support forum. The support forum is at https://mixxx.discourse.group

**Comment by Dazmed707** [comment]
Apart from support, I would like to know if the code for mixxx versions 2.3.2 and 2.4.0 has support for that console?

**Comment by ronso0** [comment]
The use the website or the forum for that.
Since you're here anyway:
If you went to https://mixxx.org/features/#hardware you'd have discovered the Supported Devices link which would send you to https://github.com/mixxxdj/mixxx/wiki/Hardware-Compatibility where you'd find tables with supported devices (not sorted alphabetically so you'd need to search the page for "Numark" for example)

**Comment by Swiftb0y** [comment]
I think that list is no longer maintained, rtfm an consult https://manual.mixxx.org/2.3/en/hardware/manuals.html instead.

**Comment by ronso0** [comment]
> I think that list is no longer maintained, rtfm and consult https://manual.mixxx.org/2.3/en/hardware/manuals.html instead.

https://github.com/mixxxdj/website/issues/254

**Comment by ninomp** [comment]
I own this particular controller. Mapping for it is included in Mixxx since version 2.1 (see https://github.com/mixxxdj/mixxx/pull/1540). There was no changes to this mapping since then because no changes were needed.

**Pull request closed without merging**
