### PR TITLE
GH Actions: fix Windows caching

### PR DESCRIPTION
**Pull request by Be-ing**
This was broken by #3809.

### CODE REVIEW

**Comment by Be-ing** [comment]
Windows build is back down to 15 minutes. Please merge promptly. I am tired of waiting 50 minutes for Windows CI jobs.

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you.

**Comment by Be-ing** [comment]
Merge?

**Comment by Be-ing** [comment]
race condition :P

**Comment by Be-ing** [comment]
Thanks for merging quickly.

**Pull request merged**
