### PR TITLE
macOS packaging: Add better rasterization of icon

### PR DESCRIPTION
**Pull request by fwcd**
As a small follow-up to #4545, this PR adds a better rasterization of the macOS icon.

The version added in the original PR used an ICNS that was generated by downscaling a 1024x1024 render of the icon. This works fine for most use-cases and with the widespread use of high dpi displays usually isn't really a big issue. However, on non-retina displays there are some noticeable artifacts with the smaller versions. For example, consider the Mixxx icon in this dialog:

image

The icon noticeably lacks its gray border. Contrast this with e.g. the icons for Preview or GIMP, which feature crisp borders that are optimized for the smaller icon size.

This PR addresses this by rendering every size individually from the source SVG into the ICNS (using [this script](https://gist.github.com/fwcd/2946ed5871df3aac8fcd267cb7cd8b52)). With the new ICNS, the icon renders properly at all sizes:

Screen Shot 2022-10-13 at 01 04 27

### CODE REVIEW

**Comment by daschuer** [comment]
Cool, thank you for taking care.
Can you also put the script in the Mixxx's tool folder?

**Comment by ronso0** [comment]
> Can you also put the script in the Mixxx's tool folder?

I couldn't find clear info on gist licenses.
Can someone clarify this before the script (based on another script) is included in Mixxx?

**Comment by daschuer** [comment]
So we need to ask the original author. @fwcd can you do it? 

https://zebracatzebra.com/oss/getting-the-gist-of-github-gist-licensing/
... explains it and has even a template message.

**Comment by fwcd** [comment]
Not a lawyer, but isn't the snippet sufficiently trivial to not be copyright-protectable?

**Comment by fwcd** [comment]
I have added a new version of the script in `packaging/macos/regenerate_icns.sh` that is

- written from scratch
- tailored to Mixxx's paths
- only based on the `inkscape` man pages and [this Stackoverflow post](https://stackoverflow.com/questions/12306223/how-to-manually-create-icns-files-using-iconutil)

Thus there hopefully shouldn't be any licensing issues.

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Pull request merged**
