### PR TITLE
widget/wkey: Do not throw debug assertion if key is invalid

### PR DESCRIPTION
**Pull request by Holzhaus**
Should fix https://github.com/mixxxdj/mixxx/pull/3015#issuecomment-674522582

### CODE REVIEW

**Comment by uklotzde** [comment]
Why do we need this exception?

**Comment by Holzhaus** [comment]
> Why do we need this exception?

https://github.com/mixxxdj/mixxx/pull/3022#issuecomment-674529658

**Comment by uklotzde** [comment]
Ok. LGTM

**Comment by daschuer** [comment]
We have discovered the bug because of the assertion. 

In 2.2 this issue would have been a warning, now this is an assertion, but we don want to crash because of skin issues, right? 
So to completely fix this issue we need to revert that back to a warning. I suggest to issue skin warnings whenever a group is mandatory for a control, this way we have the skin line number as part of the warning. 

Alternative or in addition we may respect the "NoWarnIfMissing" is flag even if "AllowInvalidKey" is set. 

I have also notice that we have redundant checks in 
```
ControlProxy::ControlProxy(const ConfigKey& key, QObject* pParent, ControlFlags flags)
``` 
 
Now it is gone and there is no single hint that something is wrong in the skin. 

What do you think?

**Comment by daschuer** [comment]
The flag "AllowInvalidKey" is a bit misleading, because it only effects debug builds. How about rename it to 
"NoDebugAssertsForValidKeys"

**Comment by daschuer** [comment]
@Holzhaus: What do you think about this? 
Will you talk care or should I issue a follow up PR?

**Pull request merged**
