### PR TITLE
chore: add note about ConfigKey naming convention

### PR DESCRIPTION
**Pull request by acolombier**
Let me know if you can see anywhere where it would be worth pointing out as well.

### CODE REVIEW

**Review by Swiftb0y — COMMENTED** [review]
sorry I forgot to submit the review earlier. anyways, not super important just wanted to mention it.

**Comment by JoergAtGithub** [comment]
This way it appears for the class 
grafik
To appear befor the constructor, it must be place immediately before the constructor

**Comment by Swiftb0y** [comment]
yeah thats what I meant. I don't know which usage is more common so its more likely to be seen.

**Comment by JoergAtGithub** [comment]
If you want it in Intellisense, only the place beforr thr constructor is helpful, because this is where you enter the control name.

**Comment by Swiftb0y** [comment]
then lets add it there too?

**Pull request merged**
