### PR TITLE
[linux] add udev rule for Focusrite (Novation) controllers

### PR DESCRIPTION
**Pull request by dszakallas**
adds an udev rule for enabling r/w for Focusrite (Novation) controllers on Linux

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for this PR. 
We just need your permission in order to merge this. 
Please sign: https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ
and comment here when done.

**Comment by dszakallas** [comment]
it's done

**Comment by daschuer** [comment]
LGTM 

I think that can go to the 2.2 branch. 
Can you rebase it? 

git rebase --onto upstream/2.1 15e11e24033382ff9bcc63c8a43333095741d846
git push -f

**Comment by Be-ing** [comment]
Why is this needed? Aren't all Novation controllers USB MIDI class compliant?

**Comment by dszakallas** [comment]
This came up when testing the my controller script on Debian. I wasn’t able to send messages to it until I added this rule. The OS was run in a VM though if that has any bearing on this.

**Comment by Be-ing** [comment]
That's really strange. If it's a MIDI device, access to the USB device shouldn't be needed like it is with HID. Could you try testing sending MIDI messages with `amidi`?

**Comment by dszakallas** [comment]
I was able to send messages to the controller with `amidi`. I'll close this PR.

**Pull request closed without merging**
