### PR TITLE
GitHub Workflows security hardening

### PR DESCRIPTION
**Pull request by sashashura**
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or action) is restricted.
It is recommended to have [most strict permissions on the top level](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) and grant write permissions on [job level](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) case by case.

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you. 
Can you rebase you changes to our 2.3 branch?

**Comment by daschuer** [comment]
I mean instead of main. We merge 2.3 in regular intervals to main, so that the changes will finally land there as well.

**Comment by Holzhaus** [comment]
> I tried to change the base branch, but it includes 200 unrelated commits. Shall I open a new pull request and close this one?

No, opening a new PR won't solve anything as long as you use the same branch. You need to rebase: https://github.com/mixxxdj/mixxx/wiki/Using-Git#targeting-another-base-branch

**Comment by daschuer** [comment]
Try:
`git rebase --onto upstream/2.3 HEAD~1`

**Comment by Holzhaus** [comment]
> Your branch and 'origin/patch-2' have diverged,
> and have 45 and 5263 different commits each, respectively.
>   (use "git pull" to merge the remote branch into yours)

This is expected. Quoting from the link I posted:

> Since this changes commits that you already pushed to the server, you need to use the -f flag when pushing the changes to the remote repository:
>
>     git push -f origin fixing_some_bug

**Pull request closed without merging**
