### PR TITLE
feat(engine): improve mono-compatibility for Rubberband R3.

### LINKED ISSUE #11361: New Rubberband R3 breaks mono compatibility, phase issues
### Bug Description

I just observed that engaging the Rubberband R3 engine it creates serious phase issues and breaks mono compatibility. This can be really serious problem for broadcasting and for partially or totally mono sound systems. For me the issue is more apparent with speakers than with headphones.

Here is a sound sample:

https://on.soundcloud.com/YwQmG

keylock on
0:0.01 default sound
0:8.00 mono mode on
0:13.00 adjusting speed +0.13, 0, -0.13
0:36.00 switching back to stereo
0:40.00 adjusting speed +0.13, 0, -0.13

### Version

2.4-alpha-1419-g0243efdaf8 (main)

### OS

OpenSUSE Tumbleweed

### PR DESCRIPTION
**Pull request by Swiftb0y**
Fixes #11361

Huge thanks to @atskler for noticing the issue and reporting it to us and upstream, as well as @cannam for doing the actual hard work of fixing the problem.

### CODE REVIEW

**Comment by daschuer** [comment]
I have issued a PR against upstream VCPK to update to rubberband 3.2.0

**Review by daschuer — APPROVED** [review]
LGTM, Thank you. 

@atskler Can you confirm that this change is sufficient?

**Comment by atskler** [comment]
> My distro will never get R3

My will get it as it is a rolling release distro.
Anyways will Mixxx require minimum Rubberband v3.2 as a dependency for building it?

**Comment by Swiftb0y** [comment]
> Anyways will Mixxx require minimum Rubberband v3.2 as a dependency for building it?

No, it will just not be mono-compatible with a lower rubberband version.

**Comment by daschuer** [comment]
Ok than let's merge it. Thank you for all the testing.

**Comment by atskler** [comment]
Rubberband 3.2 is available for my distro so I built Mixxx and checked it and it solved the problem.

**Pull request merged**
