### PR TITLE
scons and python3 

### PR DESCRIPTION
**Pull request by olafhering**
make a few places in the scons code compatible with python3.
This is a hard requirement after Tumbleweed contains a python3 based scons.rpm

### CODE REVIEW

**Comment by Be-ing** [comment]
Thank you for working on this. I'd like to hold off on any changes to the build system until after the 2.1 beta release on Friday. I am still running Fedora 26 with Scons2 and don't have time to deal with an OS upgrade or build system troubles before the beta release.

**Comment by daschuer** [comment]
Fortunately this build on our CI and on my system, so it should be save to merge it.
But first we need your permission, Please sign 
https://docs.google.com/a/mixxx.org/spreadsheet/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ
and comment here when done. 

Thank you.

**Comment by uklotzde** [comment]
One more change is required for a successful build with SCons 3:

depends.py, line 536
```
from .features import Optimize
```

Redirecting stdout now works, this was an open issue before. Nice, now I can drop SCons 2 👍

**Comment by daschuer** [comment]
LGTM. Thank you very much.

**Pull request merged**
