### PR TITLE
Fix Traktor F1 output packet mapping

### PR DESCRIPTION
**Pull request by mbouron**
HIDPacket.addControl() expects its offset to start at 0 and applies to
the packet payload (which does not take the header into account).

The Traktor F1 expects the output report to be 81 bytes long with its
first byte (the header) set to 0x80. Moreover, sending a packet larger
than 81 bytes seems to stall the device on Linux. At this point the
device needs to be unplugged/plugged in order to accept new packets.

Offsetting the current values by one fixes the output LEDs and
avoids stalling the device on Linux.

### CODE REVIEW

**Comment by Be-ing** [comment]
Thanks for fixing this! This legacy mapping has never been documented. Could you describe how it works on https://mixxx.org/wiki/doku.php/native_instruments_traktor_kontrol_f1 ?

**Comment by mbouron** [comment]
Sure, I need to get familiar with it first as I just started to use mixxx (my plan is to make my own mapping (for my two f1s) and migrate my setup from Traktor to mixxx (on Linux)).

**Comment by uklotzde** [comment]
Please rebase your branch *onto* 2.2 and do a *force push*. Then all unrelated commits should disappear.

Before we forget it, would you please sign our [Link: contributor agreement form](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ) for this and all future contributions.

**Comment by ronso0** [comment]
..comment race condition again ;)

**Comment by Be-ing** [comment]
Thanks!

**Comment by mbouron** [comment]
I just rebased on top of the 2.2 branch and also signed the contributor agreement.

**Comment by mbouron** [comment]
Sorry I didn't take the time to read the developer documentation yet but do you target a release branch first and then backport it to master later on ?

**Comment by Be-ing** [comment]
Controller mappings go to the stable branch. I already merged 2.2 to the 2.3 (beta) branch and 2.3 to master.

**Comment by Be-ing** [comment]
FYI, the reason this broke was because the common-hid-packet-parser.js library was using HIDAPI wrong, which coincidentally worked on Linux but never worked on Windows. We tried to fix controller mappings when fixing that bug, but we don't have access to the hardware for every mapping so we couldn't verify that it didn't break.

https://mixxx.org/forums/viewtopic.php?p=38832#p38832
#1953

**Pull request merged**
