### PR TITLE
[Backport] fix: prevent double free on DigitsRenderer

### PR DESCRIPTION
**Pull request by acolombier**
Backport of #13859

### CODE REVIEW

**Review by Swiftb0y — APPROVED** [review]
LGTM

**Comment by Swiftb0y** [comment]
we should enable "rebase and merge" for this...

**Comment by m0dB** [comment]
> we should enable "rebase and merge" for this...

but should we merge this now?

**Comment by Swiftb0y** [comment]
yup, I thought I didn't have the rights to reenable rebase but I apparently have, so I reenabled it.

**Pull request merged**
