### PR TITLE
[Do not merge] Demonstrate that ColumnCache is seriously broken

### PR DESCRIPTION
**Pull request by uklotzde**
Start Mixxx and watch the debug assertions.

Hopefully, someone can explain how this is supposed to work correctly? I don't get it.

### CODE REVIEW

**Comment by ywwg** [comment]
pasting from chat: Owen W.: (@Uwe Klotz) somewhere along the way, columncache got broken. In basetrackcache it is correctly inited with all of the columns (done when it's constructed inside mixxxlibraryfeature.cpp). However in basesqltablemodel, it only gets inited with a few columns -- id, preview, and coverart -- inside LibraryTableModel::setTableModel. This means header column lookup by name is broken, which means saving header layouts is broken, which explains why I'm having trouble getting the last_played_at column added

Owen W.: we need to always init the columncache with all of the column names so its indexes are correct. We could either make columncache static, since it's a readonly object, or use a factory function or something

**Comment by ywwg** [comment]
I think what happened is during a refactor, someone didn't understand what SetColumns was doing, because it was poorly named.  So when a second columncache was created, it was not initialized correctly

**Comment by ywwg** [comment]
Probably the correct fix is to have columncache build itself correctly, and mixxxlibraryfeature should use it as a source of truth instead of the other way around.

**Comment by uklotzde** [comment]
Hopefully obsolete with #3328 ;)

**Pull request closed without merging**
