### PR TITLE
LateNight: add Quick Effect selector

### PR DESCRIPTION
**Pull request by ronso0**
based on #4501

image

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
Thank you! LGTM

**Comment by Be-ing** [comment]
Thanks for working on this but I don't like the styling removing the border. Why should this look so different from the effect comboboxes?

**Comment by ywwg** [comment]
Thanks also for doing the work! 

My comment is about the always-on visibility of the effect selector.  It adds clutter to the user interface and I'm not sure it will be changed very often for most people.  There's also not enough room for the whole effect name to be visible. One option is it could be hidden unless the Effects button is pushed.  Or, it could only be visible if an option is selected in the Skin Settings.  Or, we could move it to a new box between the two effect racks -- there's a decent amount of space available there.

**Comment by Be-ing** [comment]
>  There's also not enough room for the whole effect name to be visible.

Could we make the mixer columns a little bit wider? Maybe make the down arrow narrower?

> Or, we could move it to a new box between the two effect racks -- there's a decent amount of space available there.

I kinda like this idea. It would provide more width for 2 decks but I don't think it would help the width for 4 decks. I do like that it would allow keeping these comboboxes visible even if the mixer is hidden.

**Comment by ronso0** [comment]
>  There's also not enough room for the whole effect name to be visible

I don't think the entire effect (chain) name needs to be visible.
The purpose of the effect selectors is to show at a glance which effect is selected. With the elided strings in this specific case it's hard to confuse **Filter** with **Smoot..** (Smooth Growl) or **Echove..** (Echoverb), even for **Filter** and **Filter...** (Filter Echo).

The effect selector should be as close as possible to the effect controls, thus it needs to be in the mixer.
Putting this into a box somewhere else decreases discoverability and usability (where is the selector for this deck? / what is this selector for?). It gets even harder if that box' visibility is unrelated to the quick effect. Effect units can be hidden, there can be 2 or 4. Both is unrelated to the number of decks/channel mixers.

**Comment by Be-ing** [comment]
> I don't think the entire effect (chain) name needs to be visible.

I agree, and the more width available for the text, the better.

**Comment by ronso0** [comment]
> One option is it could be hidden unless the Effects button is pushed

While this is an interesting approach I'm unsure if it's inviting to push the button while
* the effect is unknown
* and it's unclear if the knob is in the neutral position

Actually, if the knob arc would indicate the neutral position we could implement your suggestion, but it could still confuse users "where the heck did the effect drop-down go? I could sware it was right here.."

**Comment by JoergAtGithub** [comment]
Is it possible to make the drop-down-list wider than the control itself? Currently it's pure guessing which effect is behind which entry: 
grafik

**Comment by ronso0** [comment]
It's supposed to look like this but appearantly the change got lost after merging a follow-up PR
image
PR coming soon.

@JoergAtGithub Could you show a screenshot of the regualr effect selector popup please?

**Comment by ronso0** [comment]
#4518

**Comment by JoergAtGithub** [comment]
In case of the narrow mixer with the small Kill Buttons, it would be nice to have also a small Drop-Down-Menu arrow:
grafik

**Comment by ronso0** [comment]
It's not feasible to move the arrow below the text. I think having a smaller arrow is possible, though I doubt a few pixels make a difference for this condensed view tbh.

**Pull request merged**
