### PR TITLE
CMake: Bump CMAKE_PROJECT_VERSION to 2.4

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Review by Be-ing — CHANGES_REQUESTED** [review]
This conflicts with #3259.

**Comment by Holzhaus** [comment]
That conflict would be trivial to resolve. The current version is wrong this is is a tiny fix we can easily apply now.

**Comment by Be-ing** [comment]
The point is we should not be using CMAKE_PROJECT_VERSION at all.

**Comment by uklotzde** [comment]
Restoring consistency is a valid reason to merge this PR until the final solution is ready.

**Review by uklotzde — APPROVED** [review]

**Comment by uklotzde** [comment]
Ping. Agreed?

**Comment by Holzhaus** [comment]
Merge?

**Review by daschuer — APPROVED** [review]

**Comment by uklotzde** [comment]
LGTM

**Pull request merged**
