### PR TITLE
Keyboard sheet update

### PR DESCRIPTION
**Pull request by ronso0**
* add Return: preview load+play / preview stop / track info dialog
* fix 'rev' (is now back 1beat)
* update manual links

### CODE REVIEW

**Comment by daschuer** [comment]
Is this a 2.4 PR?

**Comment by ronso0** [comment]
Yes, good catch. Changed the base.

**Review by daschuer — APPROVED** [review]
Looks good. Thank you.

**Comment by ronso0** [comment]
Thanks, that was quick!

Oh, and one thing to keep in mind @mixxxdj/developers:
when the mapping SVG was touched and saved as "Optimized SVG", double-check all layers are still there.
IIUC that may discard layers which makes the export workflow (for the manual)... much less fun.

**Pull request merged**
