### PR TITLE
Remove ControlObjectThread

### PR DESCRIPTION
**Pull request by daschuer**
This is on top of https://github.com/mixxxdj/mixxx/pull/713, which should be reviewed and merged first. 

This is target to 1.12, since COT use direct connections, which is a risk to run into Bug #1406124.

### CODE REVIEW

**Comment by rryan** [comment]
I've given this two read-throughs and don't see anything immediately wrong. I'm worried I'm missing something though.

What's the segfault risk of leaving COT in 1.12? I think the main COTs that get destroyed/recreated regularly are vinylcontrol and controllerengine (when the user disables / enables them).

**Comment by daschuer** [comment]
A risk for a party stopper would be when a COT is destroyed during runtime AND and its value is written from a different thread. Before I have started to work on this, I have tried to find some of them by debugging, without success. Finding such condition by review was also hard because it is hard to track the lifetime of a COT if it is destroyed by a tree of objects. 

If we assume there actually are no such conditions, there is still a crasher risk during skin change and Mixxx shutdown. 

So the final question is: What is more risky, applying this or have a rare crasher risk in 1.12

**Comment by ywwg** [comment]
I've been using 1.12 extensively lately and it's been very stable.  I think without an easily-reproduceable crash caused by this bug, we should not try to fix it in 1.12.

**Comment by Be-ing** [comment]
> I've been using 1.12 extensively lately and it's been very stable. I think without an easily-reproduceable crash caused by this bug, we should not try to fix it in 1.12.

+1

**Comment by rryan** [comment]
Hello! This branch is against the 1.12 branch, which is now closed to any changes except bugfixes. Please re-open your PR against master if this PR is still relevant.

**Pull request closed without merging**
