### PR TITLE
Deere :: simplify mixer templates

### PR DESCRIPTION
**Pull request by ronso0**
I'd like to improve the Deere mixer templates as they are a maze right now, basically unmaintainable once one didn't look at it for a while.

- [x] simplify channel templates
- [x] fix and simplify Master level meter alignment
- [ ] improve EQ Kill & QuickEffect enable toggles: no radio buttons, bigger like in other skins
- [x] permanent Gain knob (like in LateNight & Tango)
- [x] remove [ChannelN],mute button (now it's visible only with 4 decks)
- [x] add permanent xfader buttons to 2-deck mixer (see discussion in #2071)

### CODE REVIEW

**Comment by Be-ing** [comment]
Thanks for taking this up! Sorry for making such a mess of the code.

**Comment by ronso0** [comment]
never mind, I added my share when I fixed the meter alignment etc.

**Comment by ronso0** [comment]
this is ready to test.
the 4-decks mixer looks the same independent from waveform layout.
It needs less h-space with 2 decks, and also less v-space with 4 decks.
Gain is always visible (above levels) like in other skins.

not 1oo% happy with the 2-deck orientation buttons and the EQ Kill buttons. Suggestions welcome

**Comment by daschuer** [comment]
The deck orientation buttons should blue only when they are out of default position.  A regression in this commit. 
I can see that there is not much space, but in the current place they are not associated with their decks. 

Looking now at Deere, I have doubts if this skin still has a place in Mixxx. 

Tango fits perfectly for the medium and small screen range. It has a nice design. 
 you look from a distance it now has almost the same grayish flat design than Deere. 
So Tango is already the better Deere. Do we need both? 

Sorry to say, but in general I think we have made Deere worse over the time. Here the 2.0.0 Version: 

grafik

It was usable with a relaxed look.
It is probably a mistake to tweak all skins for all use cases and all screen sizes. 
I would be happy if we de-optimize Deere for small screens and re-add more blank space between the controls. Maybe we can do it by halve all controls in size. In a UHD setup they are big again. 

How about turning Deere into an accessible high contrast skin? 
I also liked the old design. 

grafik

Or we pick up this somehow: "Deere, the better Traktor"
grafik

:-P

**Comment by ronso0** [comment]
Thanks for the interesting direction you're taking this discussion to.

wouldn't say we made Deere worse, the mistake IMO was to keep the minimal size of 1024px only because it is our default skin that should work on pretty much all screens.

Pro
* standard 2-deck layout (not mirrored) 
* Club-standard 4-deck mixer layout
* minimal design, no bling-bling, no skeumorphism like LateNight

Contra
* very flat color scheme, blue used by ALL toggles and indicators, no distinction regarding their importance
* very stuffed at 1o24px, spinnies eat to much v-space

I like the old Deere (blue/orange) very much. it somehow has the same layout as Shade (play/pause in mixer area) . Maybe there's a way to grow it to supply 4 decks.

Re this PR:
I'll fix the xfader buttons, then this is ready to merge IMO

**Comment by daschuer** [comment]
Yes, sorry my post was unfair. 

All design decisions we have made, where reasonable and good on its own. It is just that we have lost the beauty and uniqueness in this process IMHO. 

How about making Tango default and let Deere grow again? 
Alternative: Shrink all controls lets say to 75 % and use the free space for a relaxed look. 

Anyway, thank you for taking care and let's merge this as you have planed.

**Comment by uklotzde** [comment]
### Deere

Please keep Deere alive!! It's my favourite, very functional and the look is both clean and modern. The flat design is perfect for focusing on what really matters. 4 decks are only needed for electronic music and hardcore beat jugglers. The classic 2 deck layout is sufficient for many uses cases and you can add samplers or the preview deck if needed.

### LateNight

LateNight's look is aging, skeumorphism is a relict from the 1990s/2000s.

### Tango

Tango is compact, but unintuitive and I don't like the overall look & feel. I'm also missing the detailed wave form view per deck of Deere that is perfect for both mixing and adjusting the beat grid or cue points. Parallel waveforms are not needed when using your ears and the unused space can be used for an extended library view.

### Some general thoughts

Do we really need to support 1024px on the desktop forever, just because there are some legacy systems?? Small screen sizes may become a requirement again when considering built-in screens of controllers, but that's a completely different use case and maybe a candidate for QML.

All-in-one controllers, built-in screens, responsive ui/ux, streaming, multi-device support (including mobile apps), cloud connection, ... Our resources are limited, we are not able to support each and every minor legacy use case. Otherwise we will become irrelevant and obsolete very soon. Our commercial contenders are moving fast and came up with entirely new application architectures and rewrites recently that take the new requirements and the changing environment into account. We are currently losing contact to the competition rapidly and I'm really concerned about this!

**Comment by daschuer** [comment]
Thank you @uklotzde for the post, you are so right. While we may have different tastes and preferences how to use Mixxx, I think Mixxx has already started to fall into oblivion because of the missing streaming support. 

I see among my friends many mounting their full size stereo with expensive loudspeakers, replacing that with active streaming boxes from quality in question. But they are happy with it, just because they can access there favorite music. 
Compared to Mixxx, we can iron out all edges and create a perfect GUI, but we will be still thrown from the users devices anyway, just because the user can't stream. 

Back to the topic here: 
Is it required that the Mixxx default skin suits all? Or would it be better to present a one that fits to 80 % without compromises? Do you propose to specialize Deere for the 80 % and ditch all edge case to de-clutter it and allow easy access for newcomers. I would support that very much. 

Maybe we need some usability test with users new to Mixxx. How can we improve the first time impression? I guess deck orientation buttons are not part of that. :-/

**Comment by foss-** [comment]
This discussion should probably go to zulip as it's only slightly related to this PR. It's a discussion worth having, although I think there's a sentiment to not drop Deere to which I agree. Deere was the skin I first learned mixxx with. Later switched to Tango but it's my second favorite skin. LateNight looks dated to my eyes and Shade I find things very hard to spot and work with.

Discussing the default skin is interesting as Tango indeed to me feels like it's the skin most in touch with current UI design. Which obviously is a subjective feeling.

**Comment by ronso0** [comment]
Re: 
### General Thoughts
I agree we should not stick to 1024px minimum size for Deere at all costs but increase it to 1280px like we did for LateNight. Earlier the idea came up to have 'minimum screen size' and 'recommended screen size' (at least internallly), where the window would use 1280px but you _could_ squeeze it into a 1024px screen. A hint in Prefs > Interface about limited functionality would clarify the situation that not all components would fit on smaller screens.

We should keep the Deere controls sized as they are. If they were smaller we unnecessarily decrease accessibility. At 1280px the spacing is much more relaxed and sufficient IMO.
Nevertheless we need to improve the indicator color situation in Deere
> blue used by ALL toggles and indicators, no distinction regarding their importance: Play, Fx enable, Sampler expand button, HotCues

Deere should stay the default skin. Tango is not 100% comfortable when used with a mouse, it was designed with controllers in mind from the very start. Over time it has grown unnecessarily and with some compromises to incorporate ALL available deck controls (HotCues, full loop controls row..) @uklotzde are those what make Tango uninituitive in your eyes?.

I totally agree we should not try to make every skin fit every use case.
Actually I'm thinking about emphasizing Tango's 'controller extension' approach and wiping out some of those compromises I mentioned above. Maybe it would even make sense for this to start Tango with almost minimal configuration and make additional components opt-in, instead of starting with a stuffed view that tries to suit everyone's needs.
For this to work I'd appreciate a minimal skin desccription as we already have it for controller mappings [lp:1741290](https://bugs.launchpad.net/mixxx/+bug/1741290)

> LateNight's look is aging, skeumorphism is a relict from the 1990s/2000s

LateNight's ... is ... a relict from the 1990s/2000s, and that's okay. You can go even further back in time by choosing Shade.
I don't condemn skeumorphism in general. [Gudron](https://mixxx.org/forums/viewtopic.php?t=8476) is a nice example and I wish we had an official skin like this.

**Comment by ronso0** [comment]
> I think Mixxx has already started to fall into oblivion because of the missing streaming support.

Is Traktor fallling into oblivion?

**Comment by daschuer** [comment]
> A hint in Prefs > Interface about limited functionality would clarify the situation that not all components would fit on smaller screens.

Good Idea!

> Deere .. At 1280px the spacing is much more relaxed and sufficient IMO.

OK. 

> I totally agree we should not try to make every skin fit every use case.

The issue is that we have not clearly defined that. Due to the ability to change everything a contributor that is missing a use case but likes the design might be tempted to break the original intention. A clear statement for each skin will help here. 

> I don't condemn skeumorphism in general. 

I like a bit more skeumorphism. I bet the fashion will com back after the users are too annoyed by to much flat design. 

> We where in good contact with Zezic it integrate his skin, But I guess he has not enough spare time anymore. I guess we need one to jump in here and help to update it for master. 

> Is Traktor fallling into oblivion?

They are not sleeping (like us): 
https://www.digitaldjtips.com/2019/01/first-look-traktor-dj-2-software-with-soundcloud-streaming/
https://www.theverge.com/2018/10/18/17994924/soundcloud-streaming-dj-mix-download-traktor-serato

However I guess the pressure is not that high because Traktor explicit targets the professional DJs that own their music. It comes to the user along with a controller. 
While we have not data, I guess that the most casual Mixxx user do not own a controller. 

Among my friends Mixxx currently competits with the Android version of Dejay 2 which supports Spotify or even the Spotify App on two Android devices. Currently I have no arguments to bring them back using Mixxx. That feels bad, like a wast of my spare time.

**Comment by ywwg** [comment]
> LateNight's ... is ... a relict from the 1990s/2000s, and that's okay. You can go even further back in time by choosing Shade.

agree :).  Also remember that LateNight is the only skin that has stacked waveforms!  This is its primary feature for me and Mixxx should always have at least one skin with this feature.

I would even entertain adjustments to latenight that reduce the skeumorphism, esp having narrower mixer faders.  I think it could be brought up to date in an incremental way.

**Comment by ywwg** [comment]
> Do we really need to support 1024px on the desktop forever, just because there are some legacy systems??

Mixxx has a lot of users in developing countries who can't afford professional dj equipment, or even recent computers.  It is difficult to maintain support for older systems but I believe this is a place where Mixxx can be a really positive force in the world.  Being able to enable people of less means to help other people dance should be one of our core missions.  So, we should always make sure there is a low-rez option for these users.

**Comment by Be-ing** [comment]
The only regression that I have noticed from brief testing is that the volume faders and meters are awkwardly tall with 4 decks + split waveforms.

> I agree we should not stick to 1024px minimum size for Deere at all costs but increase it to 1280px like we did for LateNight. Earlier the idea came up to have 'minimum screen size' and 'recommended screen size' (at least internallly), where the window would use 1280px but you could squeeze it into a 1024px screen. A hint in Prefs > Interface about limited functionality would clarify the situation that not all components would fit on smaller screens.

This seems like a good idea to me. Some vertical space could probably be freed up in Deere by designing it for a 1280px width.

> We should keep the Deere controls sized as they are. If they were smaller we unnecessarily decrease accessibility. At 1280px the spacing is much more relaxed and sufficient IMO.

I disagree. After using Tango for a while now, I think the widgets in Deere are larger than they need to be.

**Comment by daschuer** [comment]
> I disagree. After using Tango for a while now, I think the widgets in Deere are larger than they need to be.

Since the HIDPI and svg  age all this is relative. It finally all depends on the Display size, resolution and scaling factor. Does the OS scaling take the display dimensions into account, by the way? 
And https://bugs.launchpad.net/mixxx/+bug/1793954 is pending ...

**Comment by ronso0** [comment]
> The deck orientation buttons should blue only when they are out of default position. A regression in this commit.

When are you seeing this? Everything's IMO:
After startup, buttons are grey and left decks' orientation is `0`, right decks' orientation is `2`

**Comment by ronso0** [comment]
Should be okay to merge now.

Please keep in mind: I know the xfader buttons don't look nice in 2-deck mode. I implemented them to have a consistent solution in all skins, and they're just a temporary hack until we implement the more general xfader solution discussed in https://github.com/mixxxdj/mixxx/pull/2071#issuecomment-480543057

**Comment by ronso0** [comment]
deere-xfader

**Comment by daschuer** [comment]
>>  The deck orientation buttons should blue only when they are out of default position. A regression in this commit.

> When are you seeing this? Everything's IMO:
> After startup, buttons are grey and left decks' orientation is 0, right decks' orientation is 2

Everything is fine. Thank you.

**Comment by daschuer** [comment]
LGTM

**Comment by Be-ing** [comment]
Why was this merged? The [regression](https://github.com/mixxxdj/mixxx/pull/2081#issuecomment-485308349) has not been fixed.

**Comment by daschuer** [comment]
Oh sorry, I have missed that point. I have also not identified this a problem. I actually think it is a better solution if you switch the parallel waveform. Do you think we should revert to the old layout?

**Comment by ronso0** [comment]
> Why was this merged? The [regression](https://github.com/mixxxdj/mixxx/pull/2081#issuecomment-485308349) has not been fixed.

@Be-ing Sorry, I forgot to respond when you first mentioned it.
I also don't think this is a regression. Though we could add some space above and below the Vol faders in this situation.

now
deere-mixer-reg

vs

deere-mixer-fixed-reg



Actually, I think we have left over an ugly situation with the clunky faders in a full-featured 4-decks mixer with parallel waveforms:
deere-mixer

**Comment by ronso0** [comment]
> After using Tango for a while now, I think the widgets in Deere are larger than they need to be.

I guess iit's the more generous layout spacing in Deere that gives you this impression.
The actual main controls in Tango, LateNight and Deere are the same size, mostly they're 22x22px minimum. Only some exceptions like Key controls, Fx assign or Fx link buttons are smaller in Tango, not to mention Shade.

**Comment by ronso0** [comment]
Let's continue the general discussion there https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Re-thinking.20Skins.20*.20Specialised.20vs.2E.20generalised

**Comment by Be-ing** [comment]
> we could add some space above and below the Vol faders in this situation

That looks better. It still looks a bit odd IMO, but not so bad.

> Actually, I think we have left over an ugly situation with the clunky faders in a full-featured 4-decks mixer with parallel waveforms

That looks okay to me, but if you have ideas to improve it, go for it.

**Pull request merged**
