### PR TITLE
Import/export Serato marker file tags (MP4/FLAC)

### PR DESCRIPTION
**Pull request by uklotzde**
Parsing of Serato markers from MP4 and FLAC files.

- OGG files are not supported yet, Serato uses a different format
- Export of file tags is disable to prevent data corruption

### CODE REVIEW

**Comment by uklotzde** [comment]
@Holzhaus Import works, but the round trip tests with this data captured from an MP4 file fail.

**Comment by uklotzde** [comment]
I'm done here. The import works, but the round trip tests are failing. This is not an issue as long as we keep the export of file tags disabled!

### Serato Markers

**Expected**
```
YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtAABTZXJhdG8gTWFya2Vyc18AAgUAAAAOAAAAr///
//8A/////wDMAAABAAAATxL/////AP////8AzIgAAQAAALlo/////wD/////AAAAzAEAAAC5
aP////8A/////wDMzAABAAABMWH/////AP////8AAMwAAQD//////////wD/////AAAAAAMA
//////////8A/////wAAAAADAP//////////AP////8AAAAAAwD//////////wD/////AAAA
AAMA//////////8A/////wAAAAADAP//////////AP////8AAAAAAwD//////////wD/////
AAAAAAMA//////////8A/////wAAAAADAP//////////AP////8AAAAAAwAA////A
```

**Actual**
```
YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtAABTZXJhdG8gTWFya2Vyc18A
```

### Serato Markers2

**Expected**
```
YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtAABTZXJhdG8gTWFya2VyczIAAQFBUUZEVDB4UFVn
QUFBQUFFQVAvLy8wTlZSUUFBQUFBTkFBQUFBQUN2QU13QUFBQUFBRU5WUlFBQUFBQU5BQUVB
QUU4U0FNeUkKQUFBQUFFTlZSUUFBQUFBTkFBSUFBTGxvQUFBQXpBQUFBRU5WUlFBQUFBQU5B
QU1BQUxsb0FNek1BQUFBQUVOVlJRQUFBQUFOCkFBUUFBVEZoQUFETUFBQUFBRU5WUlFBQUFB
QU5BQVVBQVhoRkFNd0F6QUFBQUVOVlJRQUFBQUFOQUFZQUFkcHVBQURNekFBQQpBRU5WUlFB
QUFBQU5BQWNBQTlXVUFJZ0F6QUFBQUVKUVRVeFBRMHNBQUFBQUFRQUEAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA
```

**Actual**
```
YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtAABTZXJhdG8gTWFya2VyczIAAQFBUUZEVDB4UFVn
QUFBQUFFQVAvLy8wTlZSUUFBQUFBTkFBQUFBQUN2QU13QUFBQUFBRU5WUlFBQUFBQU5BQUVB
QUU4U0FNeUlBQUFBQUVOVlJRQUFBQUFOQUFJQUFMbG9BQUFBekFBQUFFTlZSUUFBQUFBTkFB
TUFBTGxvQU16TUFBQUFBRU5WUlFBQUFBQU5BQVFBQVRGaEFBRE1BQUFBQUVOVlJRQUFBQUFO
QUFVQUFYaEZBTXdBekFBQUFFTlZSUUFBQUFBTkFBWUFBZHB1QUFETXpBQUFBRU5WUlFBQUFB
QU5BQWNBQTlXVUFJZ0F6QUFBQUVKUVRVeFBRMHNBQUFBQUFRQUEAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA
```

**Comment by Be-ing** [comment]
Have you tested if there are timing shifts with AAC and Vorbis? Is it only MP3 that has that problem?

**Comment by uklotzde** [comment]
No, I haven't performed any playback offset test and I am not planning to do this. This is not a use case for me. I just wanted to ensure that the mapping to file tags is in place. Someone else may pick up here.

**Comment by uklotzde** [comment]
I remember a slight shift for an AAC file with FFmpeg were I placed the last marker at the end of the file in Serato.

**Comment by Holzhaus** [comment]
I'll look into fixing the roundtrip tests. Maybe someone else can have a look at the offsets in the meantime.

**Comment by Holzhaus** [comment]
By the way, some the ID3v2 tests fail:
```
$ ctest -j4 --output-on-failure -R '(MetadataTest|TagLib)'
Test project /home/jan/Projects/mixxx/cmake_build
    Start 574: TagLibTest.WriteID3v2Tag
    Start 362: MetadataTest.ParseBpmValidRange
    Start 366: MetadataTest.CalendarYear
    Start 361: MetadataTest.ParseBpmPrecision
1/9 Test #366: MetadataTest.CalendarYear ........................   Passed    0.16 sec
    Start 583: TrackMetadataTest.parseArtistTitleFromFileName
2/9 Test #361: MetadataTest.ParseBpmPrecision ...................   Passed    0.18 sec
    Start 363: MetadataTest.ParseBpmInvalid
3/9 Test #362: MetadataTest.ParseBpmValidRange ..................   Passed    0.29 sec
    Start 364: MetadataTest.NormalizeBpm
4/9 Test #363: MetadataTest.ParseBpmInvalid .....................   Passed    0.19 sec
    Start 584: TrackMetadataTest.mergeImportedMetadata
5/9 Test #583: TrackMetadataTest.parseArtistTitleFromFileName ...   Passed    0.21 sec
    Start 365: MetadataTest.ID3v2Year
6/9 Test #364: MetadataTest.NormalizeBpm ........................   Passed    0.18 sec
7/9 Test #584: TrackMetadataTest.mergeImportedMetadata ..........   Passed    0.19 sec
8/9 Test #574: TagLibTest.WriteID3v2Tag .........................***Exception: SegFault  1.25 sec
Note: Google Test filter = TagLibTest.WriteID3v2Tag
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from TagLibTest
[ RUN      ] TagLibTest.WriteID3v2Tag
Setting track title
MetadataSourceTagLib - Exporting track metadata into file "/home/jan/Projects/mixxx/no_id3v1_mp3.zXhahq" with type 3

9/9 Test #365: MetadataTest.ID3v2Year ...........................***Exception: SegFault  1.20 sec
Note: Google Test filter = MetadataTest.ID3v2Year
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from MetadataTest
[ RUN      ] MetadataTest.ID3v2Year
majorVersion 3


78% tests passed, 2 tests failed out of 9

Total Test time (real) =   1.64 sec

The following tests FAILED:
	365 - MetadataTest.ID3v2Year (SEGFAULT)
	574 - TagLibTest.WriteID3v2Tag (SEGFAULT)
Errors while running CTest
```

**Comment by Holzhaus** [comment]
> I'm done here. The import works, but the round trip tests are failing. This is not an issue as long as we keep the export of file tags disabled!
> 
> ### Serato Markers
> **Expected**
> 
> ```
> YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtAABTZXJhdG8gTWFya2Vyc18AAgUAAAAOAAAAr///
> //8A/////wDMAAABAAAATxL/////AP////8AzIgAAQAAALlo/////wD/////AAAAzAEAAAC5
> aP////8A/////wDMzAABAAABMWH/////AP////8AAMwAAQD//////////wD/////AAAAAAMA
> //////////8A/////wAAAAADAP//////////AP////8AAAAAAwD//////////wD/////AAAA
> AAMA//////////8A/////wAAAAADAP//////////AP////8AAAAAAwD//////////wD/////
> AAAAAAMA//////////8A/////wAAAAADAP//////////AP////8AAAAAAwAA////A
> ```
> 
> **Actual**
> 
> ```
> YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtAABTZXJhdG8gTWFya2Vyc18A
> ```

It's good that we have these round-trip tests. This test failure is actually not caused by a bug in the dump() code. It fails to dump it *because the parsing fails* so that the payload is empty, so that it only dumps the encoded prefix.

**Comment by uklotzde** [comment]
#2722

**Comment by Holzhaus** [comment]
> It fails to dump it _because the parsing fails_ so that the payload is empty and it only dumps the encoded prefix.

... and apparently the parsing fails because the format differs from the format used in MP3s. I'll have a closer look on tuesday.

**Comment by uklotzde** [comment]
The reference data in the MP4 marker tests (V1 and V2) has been extracted from an .m4a file with 8 cue points.

**Comment by Holzhaus** [comment]
Markers2 look good, there is probably only a single 0 null byte of padding missing at the end of the dumped data. This is why import works even though parsing markers fails: if markers is empty, it just uses markers2.

However it is worrying that parsing markers fails, I gotta look into that ASAP.

**Comment by Holzhaus** [comment]
Can you cherry-pick commit github.com/Holzhaus/mixxx/commit/91f44dfc6df839a3a70fc6d946520f82fab5b491?

If the payload is empty, the encoded payload should be as well.

**Comment by Holzhaus** [comment]
I need some time to reverse the MP4 markers format. Do the other filetypes work? If so, we can put the MP4 stuff into a separate PR and review/merge the other formats independently.

**Comment by uklotzde** [comment]
I have not tested Ogg and Opus. But both are using the same Vorbis comment file tags.

**Comment by Be-ing** [comment]
Serato does not support Opus anyway.

**Comment by Holzhaus** [comment]
This is super strange, the second field in the MP4 markers entry is apparently 12 bits (!) shorter than the other fields... (note the uneven number of `f`s in row 1)

```
┌──────────┬──────────┬────────┬──────────────┬────────┬────────┬────────┬────────┐
│ position │ field2   │ field3 │ end_position │ field5 │ color  │ typeid │ field8 │
╞══════════╪══════════╪════════╪══════════════╪════════╪════════╪════════╪════════╡
│ 175      │ fffff    │ 00     │ ffffffff     │ 00     │ cc0000 │ 01     │ 00     │
├──────────┼──────────┼────────┼──────────────┼────────┼────────┼────────┼────────┤
│ 20242    │ ffffffff │ 00     │ ffffffff     │ 00     │ cc8800 │ 01     │ 00     │
├──────────┼──────────┼────────┼──────────────┼────────┼────────┼────────┼────────┤
│ 47464    │ ffffffff │ 00     │ ffffffff     │ 00     │ 0000cc │ 01     │ 00     │
├──────────┼──────────┼────────┼──────────────┼────────┼────────┼────────┼────────┤
│ 47464    │ ffffffff │ 00     │ ffffffff     │ 00     │ cccc00 │ 01     │ 00     │
├──────────┼──────────┼────────┼──────────────┼────────┼────────┼────────┼────────┤
│ 78177    │ ffffffff │ 00     │ ffffffff     │ 00     │ 00cc00 │ 01     │ 00     │
└──────────┴──────────┴────────┴──────────────┴────────┴────────┴────────┴────────┘
```

**Comment by Be-ing** [comment]
Are FLAC and Vorbis working already?

**Comment by Holzhaus** [comment]
uklotzde/mixxx#14

**Comment by Holzhaus** [comment]
All failing tests should be fixed in uklotzde/mixxx#14 now.

**Comment by uklotzde** [comment]
Jan has fixed all the tests and disabled everything that does not work yet. Waiting for the CI builds and a local build after the final rebase and merge conflict fixes.

**Comment by uklotzde** [comment]
```
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] SeratoMarkersTest.ParseAndDumpBase64EncodedMP4
[  FAILED  ] SeratoMarkers2Test.ParseAndDumpBase64EncodedMP4
```

**Comment by uklotzde** [comment]
@Holzhaus Something seems to be broken now
```
Thread 1 "mixxx" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	  return ret;
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff39ed895 in __GI_abort () at abort.c:79
#2  0x00007ffff3a488c7 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff3b59e1d "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff3a4fdec in malloc_printerr (str=str@entry=0x7ffff3b5c100 "free(): double free detected in tcache 2") at malloc.c:5347
#4  0x00007ffff3a513fd in _int_free (av=0x7ffff3b8b9e0 <main_arena>, p=0x34483560, have_lock=0) at malloc.c:4201
#5  0x0000000000c39ebf in QTypedArrayData<unsigned short>::deallocate(QArrayData*) (data=<optimized out>) at /usr/include/qt5/QtCore/qarraydata.h:236
#6  QString::~QString() (this=0x7fffffffbf80, __in_chrg=<optimized out>) at /usr/include/qt5/QtCore/qstring.h:1133
#7  mixxx::taglib::mp4::exportTrackMetadataIntoTag(TagLib::MP4::Tag*, mixxx::TrackMetadata const&) (pTag=0x2ab129e0, trackMetadata=...) at /tmp/mixxx/src/track/taglib/trackmetadata_mp4.cpp:408
#8  0x0000000000be2c31 in mixxx::(anonymous namespace)::Mp4TagSaver::exportTrackMetadata (trackMetadata=..., pFile=0x2f0a27f8) at /tmp/mixxx/src/sources/metadatasourcetaglib.cpp:378
#9  mixxx::(anonymous namespace)::Mp4TagSaver::Mp4TagSaver (trackMetadata=..., fileName=..., this=0x2f0a27f0) at /tmp/mixxx/src/sources/metadatasourcetaglib.cpp:363
#10 std::make_unique<mixxx::(anonymous namespace)::Mp4TagSaver, QString const&, mixxx::TrackMetadata const&> () at /usr/include/c++/10/bits/unique_ptr.h:934
#11 mixxx::MetadataSourceTagLib::exportTrackMetadata(mixxx::TrackMetadata const&) const (this=0x2f6003f0, trackMetadata=...) at /tmp/mixxx/src/sources/metadatasourcetaglib.cpp:783
#12 0x000000000067684c in Track::exportMetadata(mixxx::MetadataSource const&) (this=this@entry=0xcb9d910, metadataSource=...) at /usr/include/qt5/QtCore/qdebug.h:125
#13 0x00000000006550ae in SoundSourceProxy::exportTrackMetadataBeforeSaving(Track*) (pTrack=0xcb9d910) at /tmp/mixxx/src/sources/soundsourceproxy.cpp:221
#14 0x0000000000b46159 in TrackCollectionManager::saveTrack(Track*, TrackCollectionManager::TrackMetadataExportMode) (this=0x3a6c8c0, pTrack=0xcb9d910, mode=TrackCollectionManager::TrackMetadataExportMode::Immediate)
    at /tmp/mixxx/src/library/trackcollectionmanager.cpp:199
#15 0x0000000000b46c62 in virtual thunk to TrackCollectionManager::saveEvictedTrack(Track*) () at /tmp/mixxx/src/library/trackcollectionmanager.cpp:186
```

**Comment by uklotzde** [comment]
free(): double free detected in tcache 2

**Comment by Holzhaus** [comment]
The backtrace looks like it's related to tag export. I'll have a look, didn't test with `__EXTRA_METADATA__` yet.

**Comment by uklotzde** [comment]
It happened when exporting the metadata. But export of Serato tags is disabled **and** the files didn't contain any Serato tags! I will recompile without this branch and test again.

**Comment by uklotzde** [comment]
I can confirm that the crashes are caused by these changes.

**Comment by uklotzde** [comment]
Gosh! I forgot to pull after merging Jan's PR on GitHub. And I found a possible reason ;)

**Comment by uklotzde** [comment]
@Holzhaus To fix my merging mess I basically rebased your branch on top of master and added my fix commit. Let's see if this works.

**Comment by uklotzde** [comment]
Ready.

**Comment by Holzhaus** [comment]
So everything works now for you?

**Comment by Holzhaus** [comment]
@uklotzde does it work fine for you?

**Comment by uklotzde** [comment]
I haven't tested the Serato import/export again. But everything else is working now, i.e. no regressions.

The import/export is covered by extensive tests that should give more reliable results than manual testing.

LGTM

**Comment by uklotzde** [comment]
...referring to Jan's contributions ;)

**Comment by Holzhaus** [comment]
By the way, I also tested with tag dumps from the file you mentioned initially, and it works.

We mustn't merge our own PR, but technically this is your PR, so... may I hit merge?

**Comment by uklotzde** [comment]
I did it.

**Pull request merged**
