### PR TITLE
Set UNIX_SHARE_PATH to absolute path including install prefix

### PR DESCRIPTION
**Pull request by uklotzde**
Got it!

Partially reverts and fixes commit: 1122ae87ef9a085ed705a6a8761c6c7ad0f5dce3

https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/CMake.20installation.20directories

### CODE REVIEW

**Comment by uklotzde** [comment]
This is really urgent to repair the broken builds. I already patched the RPMFusion build manually, because I could not wait on someone approving this PR.

**Comment by Be-ing** [comment]
I think this is hacking around the real problem. I think we should reconsider computeResourcePath in configobject.cpp...

**Review by daschuer — APPROVED** [review]
At least this fixes a real bug. So let's merge. LGTM

**Comment by daschuer** [comment]
Wait, is this related here? 

```
CPack: Create package using WIX
CPack: Install projects
CPack: - Install project: mixxx []
CPack: -   Install component: Libraries
CPack: -   Install component: Unspecified
CPack: Create package
CPack Error: CPACK_PACKAGE_EXECUTABLES should contain pairs of <executable> and <text label>.
CPack Error: CPACK_PACKAGE_EXECUTABLES should contain pairs of <executable> and <text label>.
CPack Error: WiX element <FeatureRef> can not be closed by </Fragment> in 'C:/projects/mixxx/cmake_build/_CPack_Packages/win64/WIX/features.wxs'
CPack Error: 3 WiX elements were still open when closing 'C:/projects/mixxx/cmake_build/_CPack_Packages/win64/WIX/features.wxs'
CPack Error: Problem running WiX candle. Please check 'C:/projects/mixxx/cmake_build/_CPack_Packages/win64/WIX/wix.log' for errors.
CPack Error: Fatal WiX Generator Error
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: mixxx
Command exited with code 1
echo "*** FAILURE ***"
"*** FAILURE ***"
```

**Comment by uklotzde** [comment]
> Wait, is this related here?
> 
> ```
> CPack: Create package using WIX
> CPack: Install projects
> CPack: - Install project: mixxx []
> CPack: -   Install component: Libraries
> CPack: -   Install component: Unspecified
> CPack: Create package
> CPack Error: CPACK_PACKAGE_EXECUTABLES should contain pairs of <executable> and <text label>.
> CPack Error: CPACK_PACKAGE_EXECUTABLES should contain pairs of <executable> and <text label>.
> CPack Error: WiX element <FeatureRef> can not be closed by </Fragment> in 'C:/projects/mixxx/cmake_build/_CPack_Packages/win64/WIX/features.wxs'
> CPack Error: 3 WiX elements were still open when closing 'C:/projects/mixxx/cmake_build/_CPack_Packages/win64/WIX/features.wxs'
> CPack Error: Problem running WiX candle. Please check 'C:/projects/mixxx/cmake_build/_CPack_Packages/win64/WIX/wix.log' for errors.
> CPack Error: Fatal WiX Generator Error
> CPack Error: Problem compressing the directory
> CPack Error: Error when generating package: mixxx
> Command exited with code 1
> echo "*** FAILURE ***"
> "*** FAILURE ***"
> ```

No idea when this started and it also happens in other PRs without this patch, e.g. #3285. This patch only restores the previous state.

**Comment by Be-ing** [comment]
How about using QFileInfo to get an absolute path instead of compiling a hardcoded path into the binary?

**Comment by uklotzde** [comment]
> How about using QFileInfo to get an absolute path instead of compiling a hardcoded path into the binary?

How? The executable does not know where the resources have been installed and this location is independent of where the executable has been installed.

**Comment by Be-ing** [comment]
>  this location is independent of where the executable has been installed

Why? What is a use case for this? Why not look in  "../share/mixxx" relative to the binary in computeResourcePath? Compiling an absolute path into the binary introduces a source of nondeterminism.

**Comment by Be-ing** [comment]
https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

CMAKE_INSTALL_DATADIR is read only so we can assume a relative relationship between the binary path and resource directory.

**Comment by uklotzde** [comment]
I just wanted to restore the previous state that is known as working. Everything else could be deferred until later. No need to introduce another regression.

We should not make any assumptions about the relative location between CMAKE_INSTALL_BINDIR and CMAKE_INSTALL_DATADIR.

**Comment by Be-ing** [comment]
> We should not make any assumptions about the relative location between CMAKE_INSTALL_BINDIR and CMAKE_INSTALL_DATADIR.

Why not? What is the point of letting the build system put the resource folder wherever? We don't do this on Windows or macOS. Users can already manually specify it with a command line option if they want some esoteric setup for whatever reason.

**Comment by daschuer** [comment]
Let's merge this now and move the discussion to Zulip. 

For my feeling it is not worth the work for allow movable binaries, if there is no use case or demand for it.

**Pull request merged**
