### PR TITLE
Update Novation Launchpad controller scripts to v3.1.1

### PR DESCRIPTION
**Pull request by dszakallas**
# Upgraded scripts

Controllers:
- Novation Launchpad MK1 (Novation-Launchpad-scripts.js)
- Novation Launchpad MK2 (Novation-Launchpad MK2-scripts.js)

Changes since v2.3.1:

### Bug Fixes

* remove circular dependencies ([746cc72](https://github.com/dszakallas/mixxx-launchpad/commit/746cc72e985f25f0100495173fb70351d262dc0d))

## [3.0.0](https://github.com/dszakallas/mixxx-launchpad/compare/v2.3.3...v3.0.0) (2022-04-30)

⚠️ Requires Mixxx 2.4 or newer ⚠️ 

#### New features & improvements:
- [x] Introduce a JSON compatible declarative configuration of layouts to make preset authoring easier
- [x] Sampler palette layout
- [x] Basic RGB LED support for HOTCUEs
- [x] RGB LED support for samplers
- [x] Library maximize / minimize button

#### Fixes:
- [x] Loopjump and beatjump modifiers work more consistently with the rest of the controls
- [x] Fixed retain attack mode bug causing incorrect behavior when shift/control changed between attack/release

#### Breaking changes:
- [x] Drop compatibility with Mixxx < 2.4 (old JS engine)
---------

### Bug Fixes

* short layout clash ([f6e0085](https://github.com/dszakallas/mixxx-launchpad/commit/f6e008533dc24f1ecf103f31cd0e716d5530b04d))

### Bug Fixes

* **app:** initialize pfl control properly ([ffe460f](https://github.com/dszakallas/mixxx-launchpad/commit/ffe460fb6cb530b828eb80daac14be7814e3c7b4))

# New scripts

- Novation Launchpad Mini MK3 (Novation-Launchpad Mini MK3-scripts.js)

# Notes

Uses ES6 features, I tested compatibility with Mixxx 2.4.0. **Not compatible with Mixxx 2.3**

### CODE REVIEW

**Comment by dszakallas** [comment]
> Hey there, I'm very happy to see this PR and will review it shortly. I've also taken a quick glance at your blog:
>>   As a functional programmer, I am not entirely happy with the amount of classes and state involved, but moving to a reactive functional paradigm seems to be too much work, as the system boundaries are imperative by nature, requiring extensive plumbing; while the inner, reactive part would be too thin.

>This might change in the future. It would require significant work and breaking API changes, but if our mapping used Qt signals and slots and was run in a QMLEngine instead of JS engine, it would be much easier to write mappings in a FRP-style, which it seems you enjoy.

Sounds interesting. Have you tried it? Could you point me to a tutorial?

**Comment by dszakallas** [comment]
It seems like JSDoc insists on processing the files and fails with

```
TypeError: Cannot read properties of undefined (reading 'typeAnnotation')
Occurred while linting /__w/mixxx/mixxx/res/controllers/Novation-Launchpad MK2-scripts.js:3410
Rule: "jsdoc/check-param-names"
    at getParamName (/github/home/.cache/pre-commit/repoalbnzog_/node_env-default/lib/node_modules/eslint-plugin-jsdoc/dist/jsdocUtils.js:129:26)
    at /github/home/.cache/pre-commit/repoalbnzog_/node_env-default/lib/node_modules/eslint-plugin-jsdoc/dist/jsdocUtils.js:258:12
    at Array.map (<anonymous>)
    at Object.getFunctionParameterNames (/github/home/.cache/pre-commit/repoalbnzog_/node_env-default/lib/node_modules/eslint-plugin-jsdoc/dist/jsdocUtils.js:257:61)
    at utils.getFunctionParameterNames (/github/home/.cache/pre-commit/repoalbnzog_/node_env-default/lib/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:434:32)
    at _default.meta.docs.description (/github/home/.cache/pre-commit/repoalbnzog_/node_env-default/lib/node_modules/eslint-plugin-jsdoc/dist/rules/checkParamNames.js:269:40)
    at iterate (/github/home/.cache/pre-commit/repoalbnzog_/node_env-default/lib/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:825:3)
    at checkJsdoc (/github/home/.cache/pre-commit/repoalbnzog_/node_env-default/lib/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:1127:9)
    at ruleErrorHandler (/github/home/.cache/pre-commit/repoalbnzog_/node_env-default/lib/node_modules/eslint/lib/linter/linter.js:1050:28)
    at /github/home/.cache/pre-commit/repoalbnzog_/node_env-default/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:58
```
I added the exception to `.eslintignore`

**Comment by Swiftb0y** [comment]
> Sounds interesting. Have you tried it? Could you point me to a tutorial?

I did a couple experiments, but nothing has been implemented in Mixxx yet unfortunately. I just wanted to signal that I read and acknowledge your criticism as valid.

**Review by Swiftb0y — APPROVED** [review]
LGTM. thank you

**Pull request merged**
