### PR TITLE
Upgrade 3rd-Party Libraries/Plugins

### PR DESCRIPTION
**Pull request by uklotzde**
Vamp plugin SDK: 2.3 -> 2.6
Soundtouch: 1.8.0 -> 1.9.2
Vamp QM plugins: unknown version -> 1.7.1

Might help to fix https://bugs.launchpad.net/mixxx/+bug/1553135

### CODE REVIEW

**Comment by rryan** [comment]
Oops :/ I have a branch that removes vamp entirely.

**Comment by uklotzde** [comment]
That's preferable ;) It didn't take long to exchange the files.

Don't know why the branch doesn't compile on Travis, although I added 
-Dkiss_fft_scalar=double to the vamp-plugins build. On my local machine 
everything works, just checked again.

**Comment by rryan** [comment]
Let's go ahead and merge to get the updates and I'll deal with the conflicts once I finish my VAMP-removal branch.

**Comment by rryan** [comment]
Thank you!

**Pull request merged**
