### PR TITLE
Kontrol S4 Mk3 mapping

### PR DESCRIPTION
**Pull request by rah2501**
Submitting [Be-ing's mapping](https://github.com/mixxxdj/mixxx/pull/4056) for consideration.

### CODE REVIEW

**Review by Be-ing — CHANGES_REQUESTED** [review]
This mapping is incomplete.

Do not ship it

**Comment by rah2501** [comment]
> Do not ship it

You've misunderstood and misrepresented what [that campaign](https://dont-ship.it/) is about.  The campaign is against *distributions* shipping patches in packages which they've taken from version control systems and are not intended to be shipped by *project developers*.  (I should know, I used to work on mobile linux with a number of the project developers involved in the campaign.)

This Mixxx pull request contains code that the *patch author* considers should not be committed.  It does not contain code that the *project developers* consider should not be committed, at least no project developers have voiced any objections as yet.  This is a different situation to what the "Don't Ship It" campaign is campaigning against.

**Comment by Be-ing** [comment]
You are misrepresenting incomplete code as if it is ready to be widely distributed to users... while also doing nothing whatsoever to help with the code -- and not even being able to, because [you don't have the hardware](https://mixxx.discourse.group/t/traktor-kontrol-s4-mk3-support/25838). This pull request is trolling at worst and irresponsible at best.

**Comment by rah2501** [comment]
> You are misrepresenting incomplete code as if it is ready to be widely distributed to users

I'm not misrepresenting, I'm presenting incomplete code as if it is ready to be widely distributed to users.  Code being incomplete is not, in and of itself, a reason not to distribute code to users.

Incomplete code can be and in many cases is, useful.  Such as this case.

**Comment by Be-ing** [comment]
You're not even capable of making that judgement without having the hardware.

**Review by Swiftb0y — CHANGES_REQUESTED** [review]
This is simply just a blatant reupload of #4056.

While we usually appreciate when people offer to pick up PRs that have gone stale (such as the PR introducing this controller mapping), those contributors usually continue the remaining work. This is not the case here. If you look at the original PR, I left a bunch of review comments outlining a part (I only reviewed 1/4th of the code) of what still needs to be done. The current state of the mapping does not meet our standards for inclusion. Nor can we confirm if it actually works without a trusted party with access to the hardware. If you want to help us with getting this mapping merged, please look at my review comments (in the previous PR) and work on fixing those. To do that, you'll need the controller hardware for testing and debugging. Here are some resources to get you started on controller mapping: 
https://github.com/mixxxdj/mixxx/wiki/Contributing%20mappings

Please note that just opening a PR with a working mapping is not a guarantee of timely (or even at all) inclusion. We have many PRs and too few people to review them.

**Comment by rah2501** [comment]
> You're not even capable of making that judgement without having the hardware.

I don't need the hardware in order to read [testimony](https://mixxx.discourse.group/t/traktor-kontrol-s4-mk3/21613/89) from others ([including](https://mixxx.zulipchat.com/#narrow/stream/113295-controller-mapping/topic/Traktor.20Kontrol.20S4.20MK3/near/251506105) [yourself](https://mixxx.discourse.group/t/traktor-kontrol-s4-mk3/21613/46)) who find the mapping useful.

Let me quote:

> my mapping in [#4056](https://github.com/mixxxdj/mixxx/pull/4056) is in a usable state

-- https://mixxx.zulipchat.com/#narrow/stream/113295-controller-mapping/topic/Traktor.20Kontrol.20S4.20MK3/near/251335771

**Comment by rah2501** [comment]
> This is simply just a blatant reupload of #4056.

Indeed. I stated that explicitly in the description.

> I left a bunch of review comments

I see.  I hadn't realised there were outstanding review comments.

**Comment by Be-ing** [comment]
There's no point continuing here if you're just going to argue without even attempting to help.

**Pull request closed without merging**
