### PR TITLE
Echo fix: echo added left channel samples to right channel

### PR DESCRIPTION
**Pull request by quirxmode**
This fixes what is likely a copy-paste error. Or I completely misread the code. Please review.
(I did not check the rest of the code, the ping-pong cod is not symmetric either but that might be fine.)

### CODE REVIEW

**Comment by quirxmode** [comment]
Ah the PR is messed up because it also contains the trans effect...

**Comment by uklotzde** [comment]
Welcome and thanks for contributing to Mixxx. As a *first-time contributor* we need you to sign our *[Contributor Agreement](https://docs.google.com/forms/d/e/1FAIpQLScC9QG327sjLL0eWftmfGUasxFFLxg6LCXJ2xHDYRzFIRqyiw/viewform?formkey=dEpYN2NkVEFnWWQzbkFfM0ZYYUZ5X2c6MQ
)*. Then comment here when done.

The echo effect fix should go into 2.3.1. Please rebase this branch on the 2.3 branch and remove the unrelated commits. Force push your branch to update the PR and then change the target branch from *main* to *2.3*.

**Review by uklotzde — CHANGES_REQUESTED** [review]
Please do *git rebase -i* to drop all unrelated commits and changes. Then rebase on 2.3.

The *echo fix* affects only a single line of code in a single file.

**Review by uklotzde — APPROVED** [review]
Changes seem to be legit. Contributor agreement has been signed. LGTM, waiting for CI...

**Comment by uklotzde** [comment]
For future contributions please read [The seven rules of a great Git commit message](https://chris.beams.io/posts/git-commit/)

I would have probably written: "Echo effect: Feed back samples from left/right instead of only left channel"

**Comment by Be-ing** [comment]
Good catch! Thanks for fixing this.

**Pull request merged**
