### PR TITLE
LateNight :: 2.2 fixess

### PR DESCRIPTION
**Pull request by ronso0**
* repair FX unit labels (we had 1 & 2 twice)
* remove double (focus) border from library
* minor aesthetic tweaks

### CODE REVIEW

**Comment by nopeppermint** [comment]
Hi @ronso0 
currently I see two problems with latenight on 2.2
1. (only with your "fixes") the left sidebar is no longer fully extendible (vertical) which I find not optimal, I like to use the whole height of my screen ;-)
slider_left

2. (also on branch 2.2, not only on your pr)
somehow the preview play button is missing after releasing left mouse click...
play_button

**Comment by nopeppermint** [comment]
already found the first one, that's when you have cover arts enabled but there is no cover art for the selected song ...

**Comment by ronso0** [comment]
apparentlly I forgot the pause icon in 8fcb5f86bac25fdd443df64ab483efa88ac9e9ba
I'm working on a fix for strange scaling of the same button's vector icon in Shade. I'll fix it there for LateNight as well

**Comment by ronso0** [comment]
what you noticed earlier is interesting, too: the default cover art is not anymore read from /res/images/library due to some wrong auto-replace changes I made to /src/library/coverartutils.cpp in e859676ede67c59058ac4fd1c38eceea4a3d7322
A shame that slipped through, only checked the preferences & library icons.
Fix is in #1817

**Review by benis — COMMENTED** [review]
Nothing obviously amiss, based on my limited experience.

**Comment by beenisss** [comment]
Looking good on Mac.

**Review by benis — APPROVED** [review]

**Comment by ronso0** [comment]
Ready to merge.

**Comment by nopeppermint** [comment]
apart of the two things I already mentioned It looks good

**Comment by ronso0** [comment]
I finally fixed the library preview button, and vectorized the other icons in the library:
2 2-latenight-lib-vectors

the preview icons now also scale with the library line height, unlike BPM icon and Played checkmark.

**Comment by nopeppermint** [comment]
@ronso0 
nice, that also works on my pc

I suggest to increase the orange border of the hover of the play button or use a more bright orange for that, it's almost not visible.

and I get a strange behavior with multiple active preview buttons...
somehow_buggy

**Comment by nopeppermint** [comment]
peek 2018-09-30 13-09

**Comment by ronso0** [comment]
> and I get a strange behavior with multiple active preview buttons...

I noticed this, too. It happens when you hectically click several preview buttons.
I reported the bug: https://bugs.launchpad.net/mixxx/+bug/1795377

**Comment by ronso0** [comment]
> I suggest to increase the orange border of the hover of the play button or use a more bright orange for that, it's almost not visible.

The orange pause icon and the darker background should be the main indicator, not the border which has the same color as a highlighted library column. This is consistent in all skins.

**Comment by uklotzde** [comment]
Still LGTM. I'm planning a new snapshot build for RPM Fusion and would like to include all these nice polishing changes.

**Comment by uklotzde** [comment]
I'm trying to change the target branch from *master* to *2.2* as supposed to be.

**Comment by uklotzde** [comment]
Let's go :)

**Comment by daschuer** [comment]
@nopeppermint can you still reproduce the preview button issue? 
I cannot, can you? The bug is tracked here: 
https://bugs.launchpad.net/mixxx/+bug/1795377

**Comment by nopeppermint** [comment]
ezgif-2-5b4a2fc4762d

@daschuer 
Yep, they are still there, at least @ 2.2.2

but much less frequent as it seems

**Pull request merged**
