### PR TITLE
Add new beats implementation

### PR DESCRIPTION
**Pull request by Holzhaus**
This adds a new beats implementation that is supposed to replace the other two implementations ([obligatory xkcd](https://xkcd.com/927/)).

I'm still experimenting with the design and there's still a bunch of stuff missing or not properly tested, but in case someone already wants to leave some comments, feel free to do so.

**To Do:**
- [x] Fix Serato BeatGrid import/export
- [x] ~~Fix test `BeatMapTest.TestBpmAround`~~ Replaced with new tests that are verifyable by hand (e000ebfb81da8060e1805ce3aba23043b527909a)
- [x] Fix test `EngineSyncTest.HalfDoubleConsistency`
- [x] Fix test `EngineSyncTest.BeatMapQuantizePlay`
- [x] Fix test `SeratoBeatGridTest.SerializeBeatMap`
- [x] Based on #4361, which should be merged first.
- [x] Calculate predominant BPM instead of arithmetic average in `getBpmInRange()`

### CODE REVIEW

**Comment by Be-ing** [comment]
ping @hacksdump

**Comment by Holzhaus** [comment]
> ping @hacksdump

FWIW the new implementation is not really related to the old one. @hacksdump used a list of (index, bpm) define a beatgrid. This implementation uses (position, beatsTillNextMarker) tuples instead.

**Comment by daschuer** [comment]
How about splitting out the first commits? For me it looks like they are already mature.

**Comment by JoergAtGithub** [comment]
> 
> 
> How about splitting out the first commits? For me it looks like they are already mature.

Isn't this done in https://github.com/mixxxdj/mixxx/pull/4361 ?

**Comment by daschuer** [comment]
Can you brief describe how the transition from BeatGrid and BeatMap into NewBeats and into a measure based format will work?
Regarding loading and storing beats. 

I like the idea of frame based anchor points, because it is native in then engine. However, we had some voices pro a seconds based format.  

I am missing the info how measures will be coded. 

I think we need to to consolidate a plan, for the final format to have the chance to discuss implications before the code is written. 
Do we have one?

**Comment by ywwg** [comment]
> The last remaining test that fails is `EngineSyncTest.HalfDoubleConsistency` which suffers from a slight rounding issue:

let me know if you need any help with this enginesync test, I know they can be tricky.

**Review by daschuer — APPROVED** [review]
LGTM and works also good. 
Thank you very much.

**Pull request merged**
