### PR TITLE
Bump libc6 downgrade version

### PR DESCRIPTION
**Pull request by daschuer**
libc6=2.35-0ubuntu3.4 is no longer available

### CODE REVIEW

**Review by Swiftb0y — DISMISSED** [review]

**Comment by daschuer** [comment]
There seems to be a dependency issue around 'libdjinterop.a': 
```
[ 10%] Built target mixxx-gitinfo
gmake[2]: *** No rule to make target 'lib/libdjinterop-install/lib/libdjinterop.a', needed by 'CMakeFiles/mixxx-lib_autogen_timestamp_deps'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:1391: CMakeFiles/mixxx-lib_autogen_timestamp_deps.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```
This happens also in other PRs so probably unrelated. I have no Idea how to fix it. Locally I have not such issues. 
Does one have an idea for a fix?

**Comment by ronso0** [comment]
from the macOS runner, simply a version mismatch?
>   Could not find a configuration file for package "DjInterop" that exactly
  matches requested version "0.20.1".
>
>   The following configuration files were considered but not accepted:
>
> /Users/runner/buildenv/mixxx-deps-rel-2.4-arm64-osx-min1100-3e909e2/installed/arm64-osx-min1100/share/djinterop/DjInteropConfig.cmake, version: 0.19.2

**Comment by ronso0** [comment]
I revoked @Swiftb0y's approval because there are new significant changes, or rather the scope broadened.

**Comment by ronso0** [comment]
🎉

**Comment by ronso0** [comment]
Squash (the libdjinterop commits) so all commits can be built?

**Comment by daschuer** [comment]
Done. I still don't have a clue why this broke...

**Comment by JoergAtGithub** [comment]
LGTM! Thank you!

**Comment by JoergAtGithub** [comment]
This broke my local Windows configuration, CMake fails now with:
```
CMake Error at CMakeLists.txt:2373 (set_target_properties):
  Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
  "optimized".  The INTERFACE_LINK_LIBRARIES property may contain
  configuration-sensitive generator-expressions which may be used to specify
  per-configuration rules.
```

**Comment by JoergAtGithub** [comment]
`${ZLIB_LIBRARIES}` has the value: `optimized;C:/Users/Joerg.WORLDWARTWEB/source/repos/JoergAtGithub/mixxx/buildenv/mixxx-deps-2.4-x64-windows-0309294/installed/x64-windows/lib/zlib.lib;debug;C:/Users/Joerg.WORLDWARTWEB/source/repos/JoergAtGithub/mixxx/buildenv/mixxx-deps-2.4-x64-windows-0309294/installed/x64-windows/debug/lib/zlibd.lib`

**Comment by daschuer** [comment]
Fixed here: https://github.com/mixxxdj/mixxx/pull/12442

**Pull request merged**
