### PR TITLE
LP1698678: Regression test + Fix for SoundSourceFFmpeg

### PR DESCRIPTION
**Pull request by uklotzde**
See also: https://bugs.launchpad.net/mixxx/+bug/1698678

### CODE REVIEW

**Comment by uklotzde** [comment]
As expected this API compliance test fails for SoundSourceFFmpeg:
```
[----------] Global test environment tear-down
[==========] 460 tests from 63 test cases ran. (33799 ms total)
[  PASSED  ] 459 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SoundSourceProxyTest.readBeyondEnd
```

**Comment by uklotzde** [comment]
SoundSourceFFmpeg now passes the new test.

**Comment by uklotzde** [comment]
@daschuer After merging I would be able to close the corresponding launchpad bug ;)

**Comment by daschuer** [comment]
Thank you! LGTM.

**Pull request merged**
