### PR TITLE
Behringer BCR2000: add echo out roll effect

### PR DESCRIPTION
**Pull request by git-developer**
This PR contains
* a new feature: a button for an echo out roll effect (enables echo while muting the deck; optionally toggles other effects like filter simultaneously)
* a fix: use the correct control to reset key, as explained in [#4030](https://github.com/mixxxdj/mixxx/pull/4030#issuecomment-877059072)

### CODE REVIEW

**Review by Be-ing — CHANGES_REQUESTED** [review]
The effects system has been designed so that to do what you are trying to implement, the user turns on the echo effect and lowers the volume fader. This design of suddenly cutting of input instantaneously was already tested years ago and rejected. It sounds smoother when the fader is lowered over a continuous range.

Controller mappings do not have access to which effects are loaded. This is by design because it would couple features to specific models of controllers. Relying on the user to only press the button when the assumed effect is loaded is not robust. Also, you are assuming the meaning of parameters and which order they are in which scripts cannot assume.

**Comment by git-developer** [comment]
Thanks for your quick feedback.

> the user turns on the echo effect and lowers the volume fader

The effect is great for low delay time, e.g. 1/4 or 1/8 beat, and for being toggled fast, e.g. 1/2 beat . It's hard to achieve this manually by additionally moving a fader.

> It sounds smoother when the fader is lowered over a continuous range.

I tried different versions of the effect before submitting this PR, and also played around with lowering the volume fader in several steps. The current implementation introduces no sound problems because the echo signal is overlayed before muting the channel.

> Relying on the user to only press the button when the assumed effect is loaded is not robust. Also, you are assuming the meaning of parameters and which order they are in which scripts cannot assume.

I agree on this. This effect button requires that the user configures the group of the internal echo effect (with parameters delay, quantize and triplet), defaulting to the first effect of the first unit. This is documented in the object constructor.

I'd understand if you reject this PR to minimize the risk of confusion for a user who doesn't pay attention to the JS doc. Just give me a hint and I'll close it, no problem. My motivation for this PR is that I know this kind of effect (fast toggle of echo + lowpass filter while muting the source) from a (fairly outdated) software called djdecks, and missed it in Mixxx. I was happy to emulate it in javascript, and maybe someone else has use for it.

**Comment by Be-ing** [comment]
Of course you can keep using this for yourself and post it to the forum as well, but I don't think this is something we should merge into Mixxx. In 2.4 we will be adding powerful features for effect chain presets (#2618) that can be loaded by controller mappings without coupling specific ways of using effects to specific controllers.

**Comment by git-developer** [comment]
OK, that's fine for me. Maybe this effect can be composed by the changes introduced by your PR, would be great. It's just a combination of effects combined with a channel mute. I'll close this PR for now. Keep up the good work!

**Pull request closed without merging**
