### PR TITLE
Fix -Wclazy-function-arg-by-ref warnings

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by daschuer** [comment]
I am afraid this is not always the best solution. If the parameter is copied into a member variable, we should use it by value and move it into the member variable. Can Clazy distinguish both cases?

**Comment by uklotzde** [comment]
> I am afraid this is not always the best solution. If the parameter is copied into a member variable, we should use it by value and move it into the member variable. Can Clazy distinguish both cases?

We should already have such use cases, also modifying a parameter that is passed by value directly. If the checks for this branch succeed than clazy is clever enough to detect where pass-by-value is required.

**Comment by Holzhaus** [comment]
> I am afraid this is not always the best solution. If the parameter is copied into a member variable, we should use it by value and move it into the member variable. Can Clazy distinguish both cases?  

Can you elaborate why copying beforehand and then moving it is preferable over copy on assignment?

**Comment by uklotzde** [comment]
Did you use [Fixits](https://github.com/KDE/clazy#enabling-fixits) for these changes?

**Comment by Holzhaus** [comment]
The first commit is mostly fixits, the second one is manual cleanup.

**Comment by uklotzde** [comment]
> > I am afraid this is not always the best solution. If the parameter is copied into a member variable, we should use it by value and move it into the member variable. Can Clazy distinguish both cases?
> 
> Can you elaborate why copying beforehand and then moving it is preferable over copy on assignment?

If you std::move() the argument at the call-side into the pass-by-value argument then you don't risk that the implicitly shared string gets cloned during the function even though you discard it after the function call returns. std::move() only works for pass-by-value, but not for pass-by-reference.

I am not a fan of defaulting to copy-on-write, because the behavior is so manifold and nontransparent.

**Comment by uklotzde** [comment]
> > > I am afraid this is not always the best solution. If the parameter is copied into a member variable, we should use it by value and move it into the member variable. Can Clazy distinguish both cases?
> > 
> > 
> > Can you elaborate why copying beforehand and then moving it is preferable over copy on assignment?
> 
> If you std::move() the argument at the call-site into the pass-by-value argument then you don't risk that the implicitly shared string gets cloned during the function even though you discard it after the function call returns. std::move() only works for pass-by-value, but not for pass-by-reference. std::move() allows you to pass and release ownership with the function call.
> 
> I am not a fan of defaulting to copy-on-write, because the behavior is so manifold and nontransparent.

That said this PR this perfectly ok. Whenever we need the feature we can switch from pass-by-reference to pass-by-value as needed. The first std::move() into (caller) or out of (callee) the argument should disable the clazy warning.

**Comment by uklotzde** [comment]
CI failures on Travis are unrelated. LGTM

@daschuer?

**Review by uklotzde — APPROVED** [review]

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Comment by uklotzde** [comment]
Who is volunteering to resolve the merge conflicts? :grimacing:

**Comment by daschuer** [comment]
when merging master?

**Comment by daschuer** [comment]
Do you mean merging 2.3 to main? 

I can do it after merging https://github.com/mixxxdj/mixxx/pull/3336 which will also produce many conflicts. 
I have a merge version here already.

**Comment by uklotzde** [comment]
to main

**Pull request merged**
