### PR TITLE
Invert exists() check

### PR DESCRIPTION
**Pull request by daschuer**
Ups ...

### CODE REVIEW

**Comment by Holzhaus** [comment]
Weird, why does Appveyor show up here? Can we revoke the Appveyor access in the repo settings?

**Review by Holzhaus — APPROVED** [review]
LGTM, waiting for CI.

**Comment by uklotzde** [comment]
I also messed up this merge.

After this works reasonably well let's leave 2.3 alone and fix everything else only for 2.4! These merges are no fun and cost more time than what they are worth.

**Comment by daschuer** [comment]
I have fixed the merge. I had a merge in Progress at the same time.

**Comment by daschuer** [comment]
I have now removed the Appveyor and Travis Webhooks.

**Comment by uklotzde** [comment]
We don't need to wait for the remaining CI builds to finish for this trivial change. LGTM

**Pull request merged**
