### PR TITLE
Fixed: Windows M4A infinite recursion (SoundSourceMediaFoundation)

### PR DESCRIPTION
**Pull request by uklotzde**
I tried to find a suitable regression test, but that didn't work as expected. Very difficult without a local build environment.

At least this major bug in the nightly builds should be fixed now.

### CODE REVIEW

**Comment by Be-ing** [comment]
```[00:01:37] plugins\soundsourcemediafoundation\soundsourcemediafoundation.cpp(256): error C2039: 'writableSampleFrames': is not a member of 'mixxx::WritableSampleFrames'
[00:01:37] C:\projects\mixxx\src\sources/audiosource.h(75): note: see declaration of 'mixxx::WritableSampleFrames'
[00:01:37] plugins\soundsourcemediafoundation\soundsourcemediafoundation.cpp(256): error C2228: left of '.writableData' must have class/struct/union
[00:01:37] scons: *** [win64_build\plugins\win64_build\mediafoundation\soundsourcemediafoundation.obj] Error 2
[00:01:37] scons: building terminated because of errors.```

**Comment by JosepMaJAZ** [comment]
Going to try this today and comment back. I believe it depends on the file, or at least on how much seeking is needed. Or maybe some rounding, but I'll better test this first and report.

**Comment by JosepMaJAZ** [comment]
Ok, the same action with the same track, on this compile versus my compile confirms that it is now fixed.

**Comment by uklotzde** [comment]
No, it doesn't depend on the track, easy reproducible. But even if I knew how to fix it I wasn't able to reproduce the issue within a test. Strange.

**Comment by sblaisot** [comment]
@uklotzde FYI you can create a personal appveyor account linked to your github account and plug it to your own fork so you have CI on your personal branches without the need to open a PR at an early stage.

**Comment by uklotzde** [comment]
@sblaisot I already had one, but only remembered it some days later :laughing: I used it with a private branch now. You just need to know that the build always fails and you have to examine the logs afterwards for the actual results.

**Comment by uklotzde** [comment]
It would help a lot if both Apple and Microsoft provide free pre-loaded VM images for cross-plattform development. Even if limited to only 30 days of usage that would be a big improvement over the current situation.

**Comment by esbrandt** [comment]
> It would help a lot if both Apple and Microsoft provide free pre-loaded VM images for cross-plattform development. Even if limited to only 30 days of usage that would be a big improvement over the current situation.

Time limited Windows virtual machines for VMWare etc. are available (https://developer.microsoft.com/en-us/windows/downloads/virtual-machines)

**Comment by Be-ing** [comment]
AppVeyor tests passed.

**Comment by uklotzde** [comment]
We should merge this ASAP, because Mixxx crashes with any M4A file on Windows when seeking forward. I verified manually that the fix works as expected by testing the AppVeyor build artifact.

**Comment by daschuer** [comment]
I cannot comprehend how exactly the recursion happens, but the changes are LGTM. 
So we can merge now. Thank you for the fix.

**Pull request merged**
