### PR TITLE
Delete all experimental build environments

### PR DESCRIPTION
**Pull request by daschuer**
This is the final PR feeing up the major portion of disk space on our download server. 
I have kept all environment that are referenced from the mixxx repository any other intermediate environments will be removed.

This is a requirement to continue with the release process.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Just for reference, if we delete these buildenvs from the download server, than we can still download the identical file from GitHub artifacts?

**Comment by daschuer** [comment]
The artefacts have a timeout after they will be deleted.
We may recreate them by rerunning the CI run. 
But they are all intermedita steps not further referenced.

**Comment by JoergAtGithub** [comment]
I checked seeral hashes and none occured in a code search in mixxxdj/mixxx. LGTM! Thank you!

**Comment by daschuer** [comment]
:-( did not work

**Pull request merged**
