### PR TITLE
LateNight + Deere high pixel density scaling fixes

### PR DESCRIPTION
**Pull request by Be-ing**
I tried changing WPushButton to use SCALE_ASPECT scalemode by default on Mixxx >= 2.0 skins, but this messed up other skins. Instead I edited LateNight to specify SCALE_ASPECT for all buttons. Along the way I fixed some missing tooltips.
before:
screenshot from 2018-10-20 23-49-18

after:
screenshot from 2018-10-21 15-07-29

### CODE REVIEW

**Comment by Be-ing** [comment]
There were more buttons to fix than I thought when I looked closer. I think I took care of them all now.

**Comment by ronso0** [comment]
(github has some issues I guess? waiting for my comments to show up..)

**Review by ronso0 — CHANGES_REQUESTED** [review]

**Comment by ronso0** [comment]
FX expand labels are shifted down for some reason. Padding in style.qss wouldn't help.

**Comment by Be-ing** [comment]
@ronso0 ready for merge?

**Comment by ronso0** [comment]
The logo appears chopped and not aligned with the GUI toggles
fix: 2c3d1df64e8b7bce5bd2a370b8c49059a4014690

**Comment by ronso0** [comment]
and hotcues can be in group 02edc774b079b0eb61bef0c3636bd907007782f8

**Comment by ronso0** [comment]
The rest LGTM!

**Comment by Be-ing** [comment]
With the current 2.2 branch, LateNight is unusable for me in any configuration. Because it is bigger than my screen, putting it in full screen mode behaves strangely with GNOME. The Mixxx window decorations are gone, but there is a blank space where the GNOME status bar usually is:
screenshot from 2018-10-24 11-56-04
Without full screen mode:
screenshot from 2018-10-24 11-56-23

You are correct that even with this branch, with 4 decks and 4 effect units this branch is practically unusable on my screen (it would help to get rid of that redundant menu bar...)
screenshot from 2018-10-24 12-10-20
Deere also has trouble fitting on my screen comfortably with 4 decks + 4 effect units:
screenshot from 2018-10-24 12-14-21
Tango is better:
screenshot from 2018-10-24 12-15-27

But other configurations work of LateNight fine on my screen without the excessive minimum window size:
screenshot from 2018-10-24 12-09-23
screenshot from 2018-10-24 12-12-55

**Comment by Be-ing** [comment]
Thank you for the review and doing some fixes for me! :+1:

**Pull request merged**
