### PR TITLE
Fixes missing library error in Debian 11

### PR DESCRIPTION
**Pull request by JaviVilarroig**
Minor tweak at CMakefile to fix compilation issue in Debian 11.

### CODE REVIEW

**Comment by Holzhaus** [comment]
Thanks, but can you post the error message you're getting? I'm guessing that TagLib requires Zlib on Debian? If we really need to depend on Zlib (and I'm not sure we do), we'd need a proper cmake find module.

**Comment by JaviVilarroig** [comment]
Yes of course. I must have shared the issue in Zulip before.
Cmake runs without problem, but when I compile I get:
`/usr/bin/ld: /lib/x86_64-linux-gnu/libz.so.1: error al añadir símbolos: DSO faltante desde línea de orden`

**Comment by Holzhaus** [comment]
can you `export LANG=C`, rerun cmake and post the error message again?

**Comment by JaviVilarroig** [comment]
Ups. Sorry.
`/usr/bin/ld: /lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line

collect2: error: ld returned 1 exit status
`

**Comment by uklotzde** [comment]
TagLib on Fedora also depends on libz. Both SCons and CMake builds succeed without linker errors.

**Comment by uklotzde** [comment]
See also: https://bugs.launchpad.net/mixxx/+bug/1779539

**Comment by Holzhaus** [comment]
> TagLib on Fedora also depends on libz. Both SCons and CMake builds succeed without linker errors.

So it's a debian bug?

This is how it look on Arch:

```
$ ldd /usr/lib/libtag.so
	linux-vdso.so.1 (0x00007fffaad90000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f5ff9cea000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f5ff9b0d000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f5ff99c8000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f5ff99ae000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f5ff97e7000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f5ff9e45000)
```

And the cmake build works without problems:
```
$ ldd cmake_build/mixxx | grep libz
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f7fc981a000)
	libzstd.so.1 => /usr/lib/libzstd.so.1 (0x00007f7fc60e8000)
```

@JaviVilarroig What output does `taglib-config --libs` produce on your system?

**Comment by JaviVilarroig** [comment]
`-L/usr/local/lib -ltag`

**Comment by JaviVilarroig** [comment]
Hummm. If you consider that this do not qualifies for a PR I have no problem on closing it.
I was just trying to send a fix for something that was looking easy.
I can continue fixing the issue manually until we get a better fix.

**Comment by Holzhaus** [comment]
> `-L/usr/local/lib -ltag`

Does `/usr/local/lib` contain zlib? Did you compile taglib yourself?

**Comment by uklotzde** [comment]
You don't seem to be using the system library. The output should be just `-ltag`.

**Comment by JaviVilarroig** [comment]
`/usr/local/lib` contain libtag, not zlib.
No, AFAIK I didn't compile taglib by myself. I follow some other projects that I must compile myself. I don't know if any of them can have installed a custom copy of taglib.
I'm going to reinstall the package and will see what happens.

**Comment by Holzhaus** [comment]
> You don't seem to be using the system library. The output should be just `-ltag`.

This is the output for me:
```
$ taglib-config --libs
-L/usr/lib -ltag
```

So I think the library directory being preset is okay, I'm just wondering why it says `/usr/local/lib` instead of `/usr/lib`. This might indeed indicate that a non-system lib is used.

**Comment by JaviVilarroig** [comment]
I have reinstalled libtag1-dev.
Now the output of taglib-config  is `-L/usr/lib/x86_64-linux-gnu -ltag`
But cmake fails with the very same message.

**Review by uklotzde — CHANGES_REQUESTED** [review]
The CMake build works without issues on a vanilla Ubuntu 20.04 install (based on Debian 11):
https://ci.appveyor.com/project/uklotzde/mixxx/builds/33631121/job/wppilmgvjvwe21gy

**Comment by uklotzde** [comment]
See also: #2887

**Comment by JaviVilarroig** [comment]
I'm going to close this PR to avoid GitHub pollution.
I can live with the current situation without to much problems.
I'm planning to reinstall a my laptop, I will test there. If the issue still exists I will share in Zulip befor reopening.
Thanks for your support, and sorry for having being so impulsive on opening the PR.

**Pull request closed without merging**
