### PR TITLE
Hercules DJ Control MP3 e2: add new mapping

### PR DESCRIPTION
**Pull request by pyxl-dev**
Hello ! This mapping is based on the currently existing mapping and it is supposed to improve UX. Buttons were mapped to match labels then it's more intuitive to use. I'd like to have your feedback on it to make more interesting. :)

### CODE REVIEW

**Comment by Be-ing** [comment]
Thank you for submitting this. We cannot give feedback without documentation as described on https://github.com/mixxxdj/mixxx/wiki/Contributing-Mappings#documenting-the-mapping

**Comment by yancelly** [comment]
Alright ! I'll do my best to make a documentation quickly.

**Comment by yancelly** [comment]
The guide says "Clone the manual repository and add a page in the hardware/controllers directory." but I can't find any hardware folder. Could you help me ?

**Comment by Holzhaus** [comment]
> The guide says "Clone the manual repository and add a page in the hardware/controllers directory." but I can't find any hardware folder. Could you help me ?

You need to check out the 2.3 branch in the manual repo first.

**Comment by yancelly** [comment]
> > The guide says "Clone the manual repository and add a page in the hardware/controllers directory." but I can't find any hardware folder. Could you help me ?
> 
> You need to check out the 2.3 branch in the manual repo first.

Got it ! Thank you !

**Comment by Holzhaus** [comment]
@0xYoan Friendly ping.

**Comment by uklotzde** [comment]
Please rebase on 2.3 and then force push.

I will change the milestone to 2.3.1 because I don't expect that this PR will be ready for 2.3.0.

**Comment by Holzhaus** [comment]
@0xYoan why did you close this?

**Comment by 0xYoan** [comment]
Sorry but I can't find my mapping on my computer because I didn't have the intelligence to save it on Github a few months ago ^^'

**Comment by Holzhaus** [comment]
What do you mean? The mapping was there, in the branch you just deleted. Maybe you can still restore it.

**Pull request closed without merging**
