### PR TITLE
Add Google's benchmarking library.

### PR DESCRIPTION
**Pull request by rryan**
As mentioned by @ywwg, in lp:1524561, we could use a way to micro-benchmark things like our filters, SampleUtil, etc. So far we mostly do ad-hoc measurements using PerformanceTimer.

Google open sourced their internal benchmarking library:
https://github.com/google/benchmark

It's in the same sort of style as googletest/googlemock so it will fit into our test suite pretty nicely. 

It's essentially requires C++11 but master is on C++11 now so that's fine. I'm not sure if it will build on MSVC though -- works fine on Clang for me.

I added an example in SampleUtilTest where we have some commented out benchmarks. Paging @daschuer as I dropped some of the stuff you did around "equal start conditions".

To run the benchmarks, run `mixxx-test --benchmark`.

### CODE REVIEW

**Comment by daschuer** [comment]
>I added an example in SampleUtilTest where we have some commented out benchmarks. Paging @daschuer as I dropped some of the stuff you did around "equal start conditions".

When I original played with it, I have noticed that the second copy loop works always then the first. 
Adding the dummy loop at the start of all these tests equalizes the start condition for all. 
Don't know if this effect persists in the new setup.

**Comment by ywwg** [comment]
Can we integrate this with Jenkins so we can see benchmark trends over time?

**Comment by rryan** [comment]
> Can we integrate this with Jenkins so we can see benchmark trends over time?

Yes, though I expect the current build server would produce noisy results due to how slammed it usually is.

**Comment by rryan** [comment]
Can anyone check if this builds on Windows? I think it's low risk for master other than the possibility of breaking the windows build.

**Comment by sblaisot** [comment]
I can test, but not before Thursday. Can this wait that time?

**Comment by rryan** [comment]
Indeed -- no rush. Thanks @sblaisot

On Tue, Dec 15, 2015 at 4:23 PM, Sebastien BLAISOT <notifications@github.com

**Comment by rryan** [comment]
Hey look at that -- denormal values do slow things down ;)

This BM isn't in this PR, just playing around. Not sure why the samplerates are so off in teh test name -- I gave it 44.1, 48, and 96k.

```
Benchmark                                                      Time(ns)    CPU(ns) Iterations
---------------------------------------------------------------------------------------------
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOn/43.0664k/64           323        323    2231325
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOn/43.0664k/256         1276       1276     540182
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOn/43.0664k/1024        4966       4965     125365
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOn/43.0664k/4k         18632      18635      36993
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOn/46.875k/64            324        323    2192103
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOn/46.875k/256          1220       1220     525585
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOn/46.875k/1024         4929       4929     142388
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOn/46.875k/4k          19576      19588      33739
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOn/93.75k/64             305        305    2095808
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOn/93.75k/256           1238       1237     553605
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOn/93.75k/1024          4836       4836     140042
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOn/93.75k/4k           20001      19997      35741
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOff/43.0664k/64         3179       3179     220730
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOff/43.0664k/256       12622      12620      56795
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOff/43.0664k/1024      49101      49098      14074
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOff/43.0664k/4k       201183     201141       3252
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOff/46.875k/64          3154       3154     223451
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOff/46.875k/256        12751      12748      53348
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOff/46.875k/1024       50681      50673      10000
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOff/46.875k/4k        205086     205005       3487
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOff/93.75k/64           3088       3088     223686
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOff/93.75k/256         12453      12452      49866
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOff/93.75k/1024        47959      47959      13018
BM_EngineFilterLinkwitzRiley4_DenormalsZeroOff/93.75k/4k         195840     195817       3600
```

**Comment by sblaisot** [comment]
sorry, too busy, too tired, need to work a little more for/with santa claus tonight, I will test windows compilation during the week-end.

I don't understand your tests results. With DenormalsZeroOff, you have more time, more CPU and less iterations: DTZ accelerate things. Am I misreading ? or you mean "working with denormals when DTZ is off do slow things down" ? in this case, yes, Mixxx is almost unusable when DTZ is not set.

**Comment by sblaisot** [comment]
not working:
```
cl /Folib\benchmark\src\sysinfo.obj /c lib\benchmark\src\sysinfo.cc /TP /nologo /MP /Zi /MD /GL /fp:fast /Gy /O2 /Damd64 /DMIXXX_BUILD_RELEASE /D'Q_ASSERT(x)=qt_noop()' /D__WINDOWS__ /D_ATL_XP_TARGETING /D_ATL_MIN_CRT /DNOMINMAX /DUNICODE /DWIN64 /DSETTINGS_FILE=\"mixxx.cfg\" /D__PORTAUDIO__ /DQT_SHARED /DQT_TABLET_SUPPORT /DQT_CORE_LIB /DQT_GUI_LIB /DQT_OPENGL_LIB /DQT_XML_LIB /DQT_SVG_LIB /DQT_SQL_LIB /DQT_SCRIPT_LIB /DQT_NETWORK_LIB /D__SNDFILE__ /DPROTOBUF_USE_DLLS /D__MAD__ /D__MEDIAFOUNDATION__ /D__HSS1394__ /D__HID__ /D__VINYLCONTROL__ /D__SHOUTCAST__ /D__SSE__ /D__SSE2__ /D__SSE__ /D__SSE2__ /D__AUTODJCRATES__ /D_USING_V110_SDK71_ /DHAVE_STD_REGEX /DHAVE_STEADY_CLOCK /Ilib\benchmark\include /ID:\mixxx-buildserver64 /ID:\mixxx-buildserver64\include /Ilib\benchmark /Ilib\soundtouch-1.8.0 /Ilib\replaygain /ID:\mixxx-buildserver64\build\qt-everywhere-opensource-src-4.8.6\include /ID:\mixxx-buildserver64\build\qt-everywhere-opensource-src-4.8.6\include /ID:\mixxx-buildserver64\build\qt-everywhere-opensource-src-4.8.6\include\QtCore /ID:\mixxx-buildserver64\build\qt-everywhere-opensource-src-4.8.6\include\QtGui /ID:\mixxx-buildserver64\build\qt-everywhere-opensource-src-4.8.6\include\QtOpenGL /ID:\mixxx-buildserver64\build\qt-everywhere-opensource-src-4.8.6\include\QtXml /ID:\mixxx-buildserver64\build\qt-everywhere-opensource-src-4.8.6\include\QtSvg /ID:\mixxx-buildserver64\build\qt-everywhere-opensource-src-4.8.6\include\QtSql /ID:\mixxx-buildserver64\build\qt-everywhere-opensource-src-4.8.6\include\QtScript /ID:\mixxx-buildserver64\build\qt-everywhere-opensource-src-4.8.6\include\QtXmlPatterns /ID:\mixxx-buildserver64\build\qt-everywhere-opensource-src-4.8.6\include\QtNetwork /ID:\mixxx-buildserver64\build\qt-everywhere-opensource-src-4.8.6\include\QtTest /ID:\mixxx-buildserver64\build\qt-everywhere-opensource-src-4.8.6\include\QtScriptTools /Ilib\gtest-1.7.0\include /Ilib\fidlib-0.9.10 /ID:\usr\include\taglib /Ilib\qtscript-bytearray /Ilib\reverb /Ilib\hidapi-0.8.0-rc1\hidapi /Ilib\xwax /Ilib\scratchlib /Ilib\vamp-2.3 /Ilib\gtest-1.7.0\include /Ilib\gmock-1.7.0\include /Ilib\benchmark\include
sysinfo.cc
C:\Program Files (x86)\Windows Kits\8.1\include\um\VersionHelpers.h(113) : error C2065: '_WIN32_WINNT_WIN8' : identificateur non déclaré
C:\Program Files (x86)\Windows Kits\8.1\include\um\VersionHelpers.h(113) : error C2660: 'IsWindowsVersionOrGreater' : la fonction ne prend pas 2 arguments
C:\Program Files (x86)\Windows Kits\8.1\include\um\VersionHelpers.h(119) : error C2065: '_WIN32_WINNT_WINBLUE' : identificateur non déclaré
C:\Program Files (x86)\Windows Kits\8.1\include\um\VersionHelpers.h(119) : error C2660: 'IsWindowsVersionOrGreater' : la fonction ne prend pas 2 arguments
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\xlocale(337) : warning C4530: Gestionnaire d'exceptions C++ utilisé, mais les sémantiques de déroulement n'ont pas été activées. Spécifiez /EHsc
scons: *** [lib\benchmark\src\sysinfo.obj] Error 2
scons: building terminated because of errors.
```

(sorry for french messages)
error C2065: '_WIN32_WINNT_WIN8' : undeclared identifier
error C2660: 'IsWindowsVersionOrGreater' : function doesn't take 2 arguments
error C2065: '_WIN32_WINNT_WINBLUE' : undeclared identifier
error C2660: 'IsWindowsVersionOrGreater' : function doesn't take 2 arguments
warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc

**Comment by rryan** [comment]
Thanks for the test @sblaisot -- I just pushed a commit that hopefully fixes that. Could you try again?

**Comment by sblaisot** [comment]
it's better, but now we have an unresolved external symbol. Probably an external library missing when linking mixxx-test

```
benchmark.lib(sysinfo.obj) : error LNK2001: symbole externe non résolu __imp_SHGetValueA
win64_build\mixxx-test.exe : fatal error LNK1120: 1 externes non résolus
scons: *** [win64_build\mixxx-test.exe] Error 1120
scons: building terminated because of errors.
```

**Comment by rryan** [comment]
Cool @sblaisot, closer! Just pushed another change to add the library needed for that symbol.

**Comment by sblaisot** [comment]
Not better:

```
benchmark.lib(sysinfo.obj) : error LNK2001: symbole externe non résolu __imp_SHGetValueA
win64_build\mixxx-test.exe : fatal error LNK1120: 1 externes non résolus
scons: *** [win64_build\mixxx-test.exe] Error 1120
scons: building terminated because of errors.
```

**Comment by rryan** [comment]
Ah, I guess it needs to be linked to mixxx-test.exe, not benchmark.o. Can you try my latest commit?

**Comment by sblaisot** [comment]
ok, It links without error now, but I catched this warning: `[...]\mixxx\lib\benchmark\src\check.h(31) : warning C4722: 'benchmark::internal::CheckHandler::~CheckHandler' : destructor never returns, potential memory leak`

**Comment by sblaisot** [comment]
now that is has been built, do you want me to make any test with it under win 10 64b ? just let me know.

**Comment by rryan** [comment]
Thanks @sblaisot -- could you run ```mixxx-test.exe --benchmark``` and let me know what the output is?

That warning should be harmless.

**Comment by sblaisot** [comment]
I tried `mixxx-test.exe --benchmark` and `mixxx-test.exe --benchmark --gtest_output=xml:test_results.xml`, I see Mixxx is running for a few seconds, but nothing happens, no output neither on screen or in test_result.xml.

maybe I need another option like `--benckmark-output=xml:benc_result.xml`?

**Comment by rryan** [comment]
Oh jeez, that same stdout problem. There is no --benchmark_output flag provided by the library in this case. 

Could you try removing the "Console console()" line from line 7 of src/test/main.cpp ?

**Comment by sblaisot** [comment]
not better :(

**Comment by rryan** [comment]
Thanks for confirming the build is not broken @sblaisot. We should figure out this stdout problem with mixxx-test.exe but since it's not specific to the benchmarking I'm going to go ahead and merge.

**Pull request merged**
