### PR TITLE
Backport of #2776: Ensure that tracks with an invalid bpm are re-analyzed

### PR DESCRIPTION
**Pull request by uklotzde**
Unfortunately #2776 was targeted at *master* instead of *2.3* as intended. Commits are identical.

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
LGTM

**Comment by daschuer** [comment]
waiting for ci

**Comment by uklotzde** [comment]
@daschuer Only the pre-commit-hook fails as expected. Already fixed on 2.3.

**Comment by daschuer** [comment]
Ok, thanks.

**Pull request merged**
