### PR TITLE
Sound Preferences: Move Query button above the fold.

### PR DESCRIPTION
**Pull request by ywwg**
Even on my high-rez screen, the Query button is way at the bottom below the input/output selectors,
and there's so much white space it's hard to even notice that there's a scroll bar on the side.  This
patch puts the query button and the hint above the giant selector list.

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you adopting this. It is actually also useful on tiny sceens, where Query button is hidden by default. 
I have just a look at it and the query buttons appears closer to the unrelated hints than to the device tabs. 
Can you arrange the Query button with the Input/output section somehow? 

I also got already the experience that the tab layout just hides some infos instead of being helpful. 
We have a static bottom section for a while and the region above has grown, so the original reason for the tabs seams to be gone. It just double hides infos on tiny screens (scrollbar and tab). 
Would you mind to remove the tabs as well?

**Comment by ywwg** [comment]
I don't want to get rid of the tabs right now -- I made more tweaks, and shoved the debugging information below the fold since it's not as relevant.  Still don't love it

**Comment by esbrandt** [comment]
Moving the button is a good idea, I`d give it a go.
* Move the ``Query Device`` button into the default tab of the I/O assignment box. Stick it to the top to simulate workflow ``Query devices-->Select devices``. Add horizontal line to give it some room.
* Move debug info below the I/O box into the hint group. Provides relevant info right where is explained what to make out of it (btw. what ``known latency`` again stands for?)
preferences

**Comment by daschuer** [comment]
"known latency" is the value that is reported by the system when setting the buffer size. 
It may be true or not, depending on the chosen sound API.

**Comment by ferranpujolcamins** [comment]
"Known" is confusing, it seems it is a true value. Maybe it could be
changed to "reported" or "system reported"?
El dia 12/03/2015 16.48, "Daniel Schürmann" <notifications@github.com> va
escriure:

**Comment by ywwg** [comment]
> default tab

that means the query button will disappear when the users selects the other tab, so I don't want to do that.  Also it'll be tricky to code and I don't want to do that either :).  I'll tweak the report values into the Hints box

I don't want to do too much more tweaking to this -- I mostly just want to get the Query button into a more visible spot.

**Comment by ywwg** [comment]
ok I think this version is acceptable, we can continue to improve it but for now I think this is a lot better.

**Comment by ywwg** [comment]
fixed conflicts

**Comment by esbrandt** [comment]
Tinkered a bit with the last version of your patch.
This basically removes all unwanted vertical whitespace (around 100+ px) , and makes vertical tracking on resize behave like in all other preferences panes (resize to whitespace on bottom).

This is the last from me for this PR, use it if you like and merge already ;)

* Removed a stray vertical spacer
* Moved vertical spacer to the button
* Changed tabs to take only minimum vertical space . Note: The cosmetic 1px spacer in the tabs are necessary, or the drop-down list fall out of ordering (e.g. Master becomes last instead 1st)
* Add horizontal line to split-up from region above

```patch
diff --git a/src/dlgprefsounddlg.ui b/src/dlgprefsounddlg.ui
index a51788c..13a66a5 100644
--- a/src/dlgprefsounddlg.ui
+++ b/src/dlgprefsounddlg.ui
@@ -65,12 +65,12 @@
         <enum>Qt::Vertical</enum>
        </property>
        <property name="sizeType">
-        <enum>QSizePolicy::Preferred</enum>
+        <enum>QSizePolicy::MinimumExpanding</enum>
        </property>
        <property name="sizeHint" stdset="0">
         <size>
          <width>20</width>
-         <height>40</height>
+         <height>1</height>
         </size>
        </property>
       </spacer>
@@ -167,6 +167,13 @@
     </layout>
    </item>
    <item>
+    <widget class="Line" name="line_2">
+     <property name="orientation">
+      <enum>Qt::Horizontal</enum>
+     </property>
+    </widget>
+   </item>
+   <item>
     <layout class="QHBoxLayout" name="buttonsHLayout">
      <item>
       <widget class="QPushButton" name="queryButton">
@@ -192,6 +199,12 @@
    </item>
    <item>
     <widget class="QTabWidget" name="ioTabs">
+     <property name="sizePolicy">
+      <sizepolicy hsizetype="MinimumExpanding" vsizetype="Expanding">
+       <horstretch>0</horstretch>
+       <verstretch>0</verstretch>
+      </sizepolicy>
+     </property>
      <property name="currentIndex">
       <number>0</number>
      </property>
@@ -205,10 +218,13 @@
          <property name="orientation">
           <enum>Qt::Vertical</enum>
          </property>
+         <property name="sizeType">
+          <enum>QSizePolicy::MinimumExpanding</enum>
+         </property>
          <property name="sizeHint" stdset="0">
           <size>
            <width>20</width>
-           <height>40</height>
+           <height>1</height>
           </size>
          </property>
         </spacer>
@@ -225,10 +241,13 @@
          <property name="orientation">
           <enum>Qt::Vertical</enum>
          </property>
+         <property name="sizeType">
+          <enum>QSizePolicy::MinimumExpanding</enum>
+         </property>
          <property name="sizeHint" stdset="0">
           <size>
            <width>20</width>
-           <height>40</height>
+           <height>1</height>
           </size>
          </property>
         </spacer>
@@ -238,38 +257,6 @@
     </widget>
    </item>
    <item>
-    <spacer name="verticalSpacer1">
-     <property name="orientation">
-      <enum>Qt::Vertical</enum>
-     </property>
-     <property name="sizeType">
-      <enum>QSizePolicy::Expanding</enum>
-     </property>
-     <property name="sizeHint" stdset="0">
-      <size>
-       <width>20</width>
-       <height>40</height>
-      </size>
-     </property>
-    </spacer>
-   </item>
-   <item>
-    <spacer name="verticalSpacer">
-     <property name="orientation">
-      <enum>Qt::Vertical</enum>
-     </property>
-     <property name="sizeType">
-      <enum>QSizePolicy::Expanding</enum>
-     </property>
-     <property name="sizeHint" stdset="0">
-      <size>
-       <width>20</width>
-       <height>40</height>
-      </size>
-     </property>
-    </spacer>
-   </item>
-   <item>
     <widget class="QGroupBox" name="Hints">
      <property name="title">
       <string>Hints and Diagnostics</string>
@@ -352,6 +339,22 @@
      </layout>
     </widget>
    </item>
+   <item>
+    <spacer name="verticalSpacer">
+     <property name="orientation">
+      <enum>Qt::Vertical</enum>
+     </property>
+     <property name="sizeType">
+      <enum>QSizePolicy::Expanding</enum>
+     </property>
+     <property name="sizeHint" stdset="0">
+      <size>
+       <width>20</width>
+       <height>40</height>
+      </size>
+     </property>
+    </spacer>
+   </item>
   </layout>
  </widget>
  <layoutdefault spacing="6" margin="11"/>
```

**Comment by ywwg** [comment]
can you create a PR for my PR?  I am too lazy to apply a diff manually :)

**Comment by ywwg** [comment]
looks good!

**Pull request merged**
