### PR TITLE
TrackDAO: Remove const qualifiers from signals to suppress clazy warnings

### PR DESCRIPTION
**Pull request by uklotzde**
As requested: https://github.com/mixxxdj/mixxx/pull/2718#discussion_r522247765

Ugly. But it makes the design flaws obvious and suppresses the warnings.

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
Ok, I am in doubt that the reasoning for this warning is correct.
The const nature is for detect only partly related issues.  
However, this probably a reasonable way around the issue. 
So LGTM.

**Comment by daschuer** [comment]
Waiting for CI.

**Review by Holzhaus — APPROVED** [review]
Thank you!

**Comment by uklotzde** [comment]
Merging after 2 approvals.

**Pull request merged**
