### PR TITLE
[Don't merge] Appveyor emailing test 

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by sblaisot** [comment]
Do you know you can very easily setup your own appveyor acount to build your fork ?

**Comment by sblaisot** [comment]
same for travis also

**Comment by Be-ing** [comment]
@sblaisot could you document how to do that on the wiki somewhere?

**Comment by sblaisot** [comment]
Sure. Adding it to my todo. lp1740799

**Comment by daschuer** [comment]
They have probably an issue:
http://help.appveyor.com/discussions/questions/3986-sending-emails-to-commit-authors

**Comment by sblaisot** [comment]
the issue your are pointing to is marked as resolved.
Why do you try to notify by email gateway ? there is a customizable webhook notification that could be helpful: https://www.appveyor.com/docs/notifications/#webhooks

**Comment by daschuer** [comment]
Unfortunately Zulip had no not for the default Appveyor webhook. So we can either write a Appveyor not at Zulip to parse the data provided, or modify the send messages to match the Travis bot for instance.

Since the data provided by email might be sufficient, it was the fastest solution on the first sight. 

Do you have some special ideas or requirements?
I think the Zulip community will be happy if we would provide a generic we hook solution.
Do you like to jump in here?

**Comment by sblaisot** [comment]
OK, I will take a look. I think zulip should have an incoming web hook to publish message. As we can tell appveyor which body to send this could do the job. Let me dig through the docs

**Comment by daschuer** [comment]
Thank you. It looks like it is straight forward to use the Travis not on Zulip and define a custom message in appveyor.yml.
Please be sure not to publish the API key or the encrypted steam email.

**Comment by daschuer** [comment]
https://docs.travis-ci.com/user/notifications/#Webhooks-Delivery-Format

https://www.appveyor.com/docs/notifications/#webhook-payload-default

**Comment by sblaisot** [comment]
I was thinking of https://www.appveyor.com/docs/notifications/#webhook-payload-custom

**Comment by sblaisot** [comment]
I juste dropped you a PM on zulip about zulip integration

**Comment by sblaisot** [comment]
Oh shit !
from https://www.appveyor.com/docs/build-configuration/#secure-variables:
> secure variables are not decoded during Pull Request builds which prevents someone from submitting PR with malicious build script displaying those variables.

so we can't use secure variable to handle api key. Instead we should define these variables in appveyor account interface.

**Comment by sblaisot** [comment]
and even like that, there is no way to prevent someone to craft a special commit and make a PR to grab the value :(

**Comment by daschuer** [comment]
It is "only" to protect us from spam.  So if one is that smart, it is ok. I just not want to make it instantly visible.

**Comment by sblaisot** [comment]
yes, but you have to enable `Enable secure variables in Pull Requests from the same repository only` preference in the general tab of the account and I don't have access to it.
Until that, your PR has no change to work with secure variables.

**Comment by daschuer** [comment]
I have now here only the commiter email in case of Failing. If this works, it would be nice to have it. 

I have also looked into the Travis problem. I have no Idea why that odes not work. 
The code is already in 2.1 so we should be notified, because it is not a fork PR. 

I have also tried to use the encrypted key directly but I failed to install the travis command line. 
https://docs.travis-ci.com/user/encryption-keys/ 
our public key is here: https://api.travis-ci.org/repos/mixxxdj/mixxx/key

**Comment by Be-ing** [comment]
Should this be closed now?

**Pull request closed without merging**
