### PR TITLE
Changelog for 2.5.0

### PR DESCRIPTION
**Pull request by daschuer**
This still contains all PRs. I think we can: 
* Remove Misc Refactorings
* Use a single line for Qt6, QML Skin and OSI and Webassembly support

What do you think? 

@Eve00000 Do you have interest for another release blog post? This time with new features, Yeah!

### CODE REVIEW

**Review by Swiftb0y — APPROVED** [review]

**Comment by Eve00000** [comment]
Will it be possible to set the release public and publish the post before 31 / 12 n preferable around X-mas?
I've got some inspiration that becomes obsolete when we publish half januari.

**Comment by daschuer** [comment]
Yes let's target this. It depends on the community support for the pending regression, but I am fine to push it though to a certain date. 

Once we have a date we can also pre-announce press contacts. For instance 2024-12-22.

**Comment by Eve00000** [comment]
Top, as there are most of the time some last minute changes, we'd better put the target on the 20th (friday)
We can already ask testers to be available the 21th. (I'll be!)

**Comment by ronso0** [comment]
> Remove Misc Refactorings

Why?
I think a significant amount of dev time went int these fixes and optimizations (development and discussions), most of them unnoticed by users, so I think we should keep it, even if it's just to show what else has been done besides the shiny new features.

**Comment by ronso0** [comment]
When this is merged I'll try to unify formatting and syntax a bit.

**Comment by daschuer** [comment]
>> Remove Misc Refactorings

> Why?

We had we similar deiscussion when releasing 2.4.0 and I removed user unrelated things then here: 
https://github.com/mixxxdj/mixxx/commit/f1b96b7698ae65ebb39de98b95444a03ff302567

In the progress of the 2.4 branch I have skipped user unrelated things initally. 

Maybe we find a middle ground when restructuring the 2.5.0 entries? 

> When this is merged I'll try to unify formatting and syntax a bit.

That's welcome. Thank you. Can we merge this than now? This put the branch closer to the relase ... 🚀

**Pull request merged**
