### PR TITLE
Electrix Tweaker mapping

### PR DESCRIPTION
**Pull request by Be-ing**
Mapping for the Tweaker controller from Electrix (http://electrixpro.com/ )

Forum thread: http://mixxx.org/forums/viewtopic.php?f=7&t=7189

I would like to map hotcues in slip mode to work similar to the normal cue point. That is, I want to be able to press play while holding a hotcue button to let the deck continue playing after the hotcue button is released. However, these bugs stand in the way of that:
https://bugs.launchpad.net/mixxx/+bug/1466606
https://bugs.launchpad.net/mixxx/+bug/1159247
https://bugs.launchpad.net/mixxx/+bug/1467057

I will ask Electrix for a blank template image to label for a wiki page

### CODE REVIEW

**Comment by daschuer** [comment]
It there someone known who, can confirm these changes? 
If not, it is it save to commit without a look of a second pair of eyes?

**Comment by Pegasus-RPG** [comment]
I have a Tweaker but no time to test this right now. Since this is the 
first mapping created for the Tweaker, there's no existing functionality 
to break, so there should be no problem committing this.

**Comment by daschuer** [comment]
@Be-ing: Please give a hint when this should be merged.

**Comment by Be-ing** [comment]
There is one last function I'd like to put in. I'd like to make shift + high encoder control track gain. I tried to get this working the other night but ran into some issues with the Tweaker firmware jumping between values. I'll try to get that working again soon. Otherwise it's ready to merge.

When the bugs regarding hotcues are fixed, I'll update the mapping.

**Comment by Be-ing** [comment]
I realized that the way to make hotcue_X_activate work like the normal cue point when starting from a paused deck is to set play to 0, rather than 1, which is counterintuitive. I added a note about it to http://mixxx.org/wiki/doku.php/mixxxcontrols

**Comment by Be-ing** [comment]
Okay, ready to merge!

**Comment by ywwg** [comment]
Since this only affects a single controller configuration (other than a small addition to the controller js library) this is ok to merge.  Thanks!

**Comment by Be-ing** [comment]
Listed in community supported mappings table on the wiki.

**Pull request merged**
