### PR TITLE
Fail early in case Taglib 2.0 is found

### PR DESCRIPTION
**Pull request by daschuer**
This makes the build error because of Taglib 2.0 explicit. 

https://github.com/mixxxdj/mixxx/issues/12708

I am strictly against hacking a support in to 2.4-beta, because it requires a good amount of testing. 
Any issue will put user data on a risk 

See also the discussion about the new " / " separator in multi-valued fields
https://github.com/mixxxdj/mixxx/pull/12613

### CODE REVIEW

**Comment by daschuer** [comment]
Can we merge this soon? We really have to avoid brute force patches that make Mixxx build with Taglib 2.0 without proper testing-

**Review by Swiftb0y — CHANGES_REQUESTED** [review]
how likely is it that this will cause issues for package maintainers? Is is reasonable to expect taglib>=1.11 to be available everywhere?

**Comment by daschuer** [comment]
This will likely cause trouble for the Linux Arch and OpenBSD package maintainers, because they have decided to not put Taglib 2.0 in a separate namespace. This is not an issue for Tagging software out there, but it is an issue for all Media players that sync their internal database to the file tags. 
I am not sure how big the issue is, but we should not rush into it for our 2.4.0 release that is overdue anyway. 

Fixing this seems to be the most pressing issue for 2.4.1

**Comment by Swiftb0y** [comment]
Great. so Mixxx 2.4.1 shipping taglib 2 is reasonable milestone?

**Comment by daschuer** [comment]
The issue is that all users of these bleeding edge systems can't even not use Mixxx 2.3.6. because of the binary incompatibility of Taglib 2.0.

**Comment by daschuer** [comment]
Done.

**Review by Swiftb0y — APPROVED** [review]
Thank you. LGTM.

**Comment by mxmilkiib** [comment]
2.5 build fails on Arch currently.

I installed taglib1 from the AUR, but it still fails..

**Comment by daschuer** [comment]
Can you post the terminal output of the failure?

**Comment by mxmilkiib** [comment]
```
[ 21%] Building CXX object CMakeFiles/mixxx-lib.dir/src/widget/weffectchain.cpp.o
/home/milk/pkgs/mixxx-git-debug/src/mixxx/src/track/taglib/trackmetadata_ape.cpp: In function ‘bool mixxx::taglib::ape::importCoverImageFromTag(QImage*, const TagLib::APE::Tag&)’:
/home/milk/pkgs/mixxx-git-debug/src/mixxx/src/track/taglib/trackmetadata_ape.cpp:62:56: error: ‘const class TagLib::APE::Item’ has no member named ‘value’; did you mean ‘values’?
   62 |                 tag.itemListMap()["COVER ART (FRONT)"].value();
      |                                                        ^~~~~
      |                                                        values
make[3]: *** [CMakeFiles/mixxx-lib.dir/build.make:5718: CMakeFiles/mixxx-lib.dir/src/track/taglib/trackmetadata_ape.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:243: CMakeFiles/mixxx-lib.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:302: CMakeFiles/mixxx.dir/rule] Error 2
make: *** [Makefile:212: mixxx] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
makepkg -si --noextract  113.20s user 16.50s system 441% cpu 29.384 total
```

**Comment by vlada-dudr** [comment]
```patch
diff --git a/src/track/taglib/trackmetadata_ape.cpp b/src/track/taglib/trackmetadata_ape.cpp
index c370c6a7f9..b4af3b5afb 100644
--- a/src/track/taglib/trackmetadata_ape.cpp
+++ b/src/track/taglib/trackmetadata_ape.cpp
@@ -59,7 +59,7 @@ bool importCoverImageFromTag(QImage* pCoverArt, const TagLib::APE::Tag& tag) {
     if (tag.itemListMap().contains("COVER ART (FRONT)")) {
         const TagLib::ByteVector nullStringTerminator(1, 0);
         TagLib::ByteVector item =
-                tag.itemListMap()["COVER ART (FRONT)"].value();
+                tag.itemListMap()["COVER ART (FRONT)"].binaryData();
         int pos = item.find(nullStringTerminator); // skip the filename
         if (++pos > 0) {
             const TagLib::ByteVector data(item.mid(pos));
```

Works for me. But if you crashed on this likely means that mixxx builds agains taglib 2.0

**Comment by mxmilkiib** [comment]
> Works for me.

What works for you? Building 2.5-alpha on an up-to-date Arch machine with taglib1 from the AUR?

> likely means that mixxx builds agains taglib 2.0

2.0 is installed currently, hmm.

FWIW/clarity, here is the file listing of both taglib and taglib1;

```
taglib /usr/
taglib /usr/bin/
taglib /usr/bin/taglib-config
taglib /usr/include/
taglib /usr/include/taglib/
taglib /usr/include/taglib/aifffile.h
taglib /usr/include/taglib/aiffproperties.h
...
taglib /usr/include/taglib/xmfile.h
taglib /usr/include/taglib/xmproperties.h
taglib /usr/lib/
taglib /usr/lib/cmake/
taglib /usr/lib/cmake/taglib/
taglib /usr/lib/cmake/taglib/taglib-config-version.cmake
taglib /usr/lib/cmake/taglib/taglib-config.cmake
taglib /usr/lib/cmake/taglib/taglib-targets-noconfig.cmake
taglib /usr/lib/cmake/taglib/taglib-targets.cmake
taglib /usr/lib/libtag.so
taglib /usr/lib/libtag.so.2
taglib /usr/lib/libtag.so.2.0.0
taglib /usr/lib/libtag_c.so
taglib /usr/lib/libtag_c.so.2
taglib /usr/lib/libtag_c.so.2.0.0
taglib /usr/lib/pkgconfig/
taglib /usr/lib/pkgconfig/taglib.pc
taglib /usr/lib/pkgconfig/taglib_c.pc
```

```
taglib1 /usr/
taglib1 /usr/lib/
taglib1 /usr/lib/libtag.so.1
taglib1 /usr/lib/libtag.so.1.19.1
taglib1 /usr/lib/libtag_c.so.0
taglib1 /usr/lib/libtag_c.so.0.0.0
taglib1 /usr/lib/taglib1/
taglib1 /usr/lib/taglib1/bin/
taglib1 /usr/lib/taglib1/bin/taglib-config
taglib1 /usr/lib/taglib1/include/
taglib1 /usr/lib/taglib1/include/taglib/
taglib1 /usr/lib/taglib1/include/taglib/aifffile.h
taglib1 /usr/lib/taglib1/include/taglib/aiffproperties.h
...
taglib1 /usr/lib/taglib1/include/taglib/xmfile.h
taglib1 /usr/lib/taglib1/include/taglib/xmproperties.h
taglib1 /usr/lib/taglib1/lib/
taglib1 /usr/lib/taglib1/lib/libtag.so
taglib1 /usr/lib/taglib1/lib/libtag_c.so
taglib1 /usr/lib/taglib1/lib/pkgconfig/
taglib1 /usr/lib/taglib1/lib/pkgconfig/taglib.pc
taglib1 /usr/lib/taglib1/lib/pkgconfig/taglib_c.pc
```

**Comment by daschuer** [comment]
This should allow to use the new taglib1 package: https://github.com/mixxxdj/mixxx/pull/12760

**Pull request merged**
